### ISSUE TITLE
AMD Navi 5700 xt No Fan Speed Control

### ISSUE THREAD

**Issue by tonarii** [Rem0o/FanControl.Releases#1]
Hi, thanks for this amazing job, as many i was looking for a free replacement of Argus monitor and this looks perfect !
As mentioned in the title, the Fan speed modification is not working on Navi cards (at least the 5700XT). But the measurements are ok.
Any idea how i can help you to fix that ?
Again thanks a lot.

**Comment by lyingd** [comment]
Same issue, AMD Navi 5500XT.

**Comment by drosado1** [comment]
+1 on the 5700xt

**Comment by Rem0o** [comment]
Any compatibility issue is directly related to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.  I do not develop the driver portion of the software. I pull directly from that repo. I would suggest opening an issue on there for Navi GPUs with your specific model and driver version. If it gets fixed there, FanControl will also get it.
