### ISSUE TITLE
Feature Request: Control RGB leds

### ISSUE THREAD

**Issue by FreezyExp** [Rem0o/FanControl.Releases#100]
I would love to see some simple controls for RGB settings.

Off
Fixed Color
Color from gradient based on Sensor

Nice to have:
- effects

Long term goal
- alienfx support ( I believe there is an open standard now )

**Comment by Rem0o** [comment]
I want to keep fan control focused on controlling fans for cooling, so I won't be going the RBG route.

**Comment by Revadike** [comment]
I can really recommend https://github.com/CalcProgrammer1/OpenRGB
