### ISSUE TITLE
Low CPU speed, High Fan speed and extremly low performance

### ISSUE THREAD

**Issue by PUREHAX** [Rem0o/FanControl.Releases#1002]
Yesterday I put the programm in the Windows autostart.
Today I started my pc and after 5 min it startet to speed up the fans and my processor was running on 0.20 GHz.
It was extremly laggy. I closed the programm and everything was fine.

**Comment by Rem0o** [comment]
Some users reported with asus boards they had to do something with armoury crate which interfered somehow.
