### ISSUE TITLE
Control section unable to detect all fans

### ISSUE THREAD

**Issue by KotonoHanako** [Rem0o/FanControl.Releases#1003]
![image](https://user-images.githubusercontent.com/81602511/183336187-cf1d68ab-152a-4046-9e9d-36590a284549.png)
As the title says, only four fans are detected under the Control section, and only two of them are paired with their speeds (CPU and Top 1). 
Any way to detect more fans for control? I've tried assisted setup, but it always gives me those four under Control. I'm also unable to link my GPU and 3 with their respective speeds.

**Comment by Rem0o** [comment]
There is no way to "detect more fans". What you see is what you get.

**Comment by snverse** [comment]
> There is no way to "detect more fans". What you see is what you get.

Does this mean that you have to delete the program and try to do another first time setup every time you attempt to detect a fan?

I have been trying to get Fan Control to work with an EVGA Z690 Classified motherboard and the program detects the fans on my GPU, but anything plugged into the motherboards fan headers (CPU and SYSFAN) seems to not be detected. I was trying to take the fans off smart and auto to 51% PWM and DC. Should I have attempted a first time setup between all those changes?

**Comment by Rem0o** [comment]
First time setup doesn't change what's detected. It just configures what's detected.  Again, what you see is what you get.
