### ISSUE TITLE
Error Connecting to Fans

### ISSUE THREAD

**Issue by Watch2834** [Rem0o/FanControl.Releases#1007]
Trying to get this software configured correctly but it keeps giving me errors when trying to pair a control to the speed tabs. Both the control and Speed tabs display my fans RPM's fine but after trying to determine which is which by setting a custom flat curve to 0%, nothing changes. Tried going the opposite direction to 100% and nothing changed in my case. 

When tried to automatically pair a control to a speed sensor it gives me an error that states " No Speed Sensor reacted to Control" then proceeds to list the specific number of the control tab.  

Tried looking through the readme for potential incompatibility with my fans but wasn't able to find anything. Also tried watching installation videos from other people but all of theirs paired automatically.

Does anyone have any idea on what I can do to make this work? I've been trying for the past 2 hours and haven't had any luck. Any help would be greatly appreciated. Below is a gyazo screenshot of what the software is showing me currently. 

https://gyazo.com/8cbe261010e744b3fb683c36913bd20f

 
Parts listed and relevant information:
Asus ROG Strix Z690-E motherboard
EVGA FTW 3090 Ti
10 Lian Li AL120's (RGB connected to the controller. PWM Fan cables connected into various motherboard fan headers)
The respected fan headers have been changed from "auto connect" to PWM setting and given a 50% flat curve on the manual setting within the BIOS

**Comment by RapidJamer** [comment]
im going through the same thing atm as well. All but one of my fans is responding and able to auto pair

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/990

Lot of people seem to have to mess with armory crate stuff for Asus boards to start responding to FanControl.

**Comment by RapidJamer** [comment]
The pain about is that i dont see the fan control settings period. Not showing anything related to it. I try to look it up on how to access it and theres just nothing related to enabling manual controls

**Comment by EightB1ts** [comment]
Hi @Watch2834 !

I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi
Looking for beta testers. If you have time, please let me know if it works for you!

**Comment by CriticalPoint** [comment]
> Hi @Watch2834 !
> 
> I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi Looking for beta testers. If you have time, please let me know if it works for you!

Strangely not a lot of uptake!? I am interested. I loaded your plugin and it 'just works'; thank you so very much for that!
I think the folks (users) over at SignalRGB would love to find out about this - how many testers do you want, if any? 🙏🏻
