### ISSUE TITLE
Blank Space Toggling Controls

### ISSUE THREAD

**Issue by quigonwhiskey** [Rem0o/FanControl.Releases#1008]
I've noticed when I click in blank space (to bring window into focus, etc) - it will sometimes remove the selected curve from some of my fan controls, where the list will change from my selection to the default generic "curve" label. I am using the auto fan curve. Not sure but was wondering if maybe hidden cards are still allowing some interaction even though they aren't visible? I haven't really messed with it enough to tell if there's specific locations causing the issue or anything, I just know it happens randomly and when I click in blank space in the window.

**Comment by Rem0o** [comment]
Well, could you try and give me steps to reproduce this exact issue? Can you do it reliably?

**Comment by quigonwhiskey** [comment]
I hadn't intentionally tried to trigger it yet, but when it it did happen it was obviously random and not me clicking a bunch for no reason, Just one of clicks to focus the window. But here's a clip of triggering it. After doing this its clearly not the hidden cards as the clicks happened in another location. It Seems to be happening underneath a curve card that's reduced, but its the fan that reacts and no longer is tied to it. I've seen it do it for multiple fans tied to the same curve, but in this case it was all 1 to 1.
[Here's the clip in onedrive](https://1drv.ms/v/s!AiCE8mzeztY4gbkUGpG7dX7rrPi7zg?e=e0Aw8V)

**Comment by Rem0o** [comment]
From the look of it, it's not really clicking empty space, but more so "dragging" a small amount as you would drag n drop a card.  Trying to get the same effect, but to no avail.

**Comment by quigonwhiskey** [comment]
Nice, glad you were able to tell what was going on. It may be that it's more sensitive in my case because I've used dime registry tweaks that affect the mouse - cursor magnetism and cursor update interval. Thanks for taking the time to look into that, even though it's hardly an app breaker and more of an annoyance lol

**Comment by Rem0o** [comment]
See V122.
