### ISSUE TITLE
window and sensor error message popup every time when pc wakeup from sleep after last update

### ISSUE THREAD

**Issue by hsinyu-chen** [Rem0o/FanControl.Releases#1009]
**Describe the bug**
after last update
every time my pc wakeup from sleep
this message and window popup 
(few second after , all sensors show up without issues
![image](https://user-images.githubusercontent.com/10412282/184350296-14783552-edda-47d5-b333-49a5c9ef4011.png)

**Comment by Rem0o** [comment]
There is a refresh logic at start that will try to init a few times. It means it failed once but then retried and got it right the second or third time. Though there should be no pop-up if it succeeded in the end. Will fix that.
