### ISSUE TITLE
Missing Speed Sensors - Latest Update

### ISSUE THREAD

**Issue by Ahplla** [Rem0o/FanControl.Releases#1011]
Every time I turn on the computer this error message appears on the speed sensor.

![FanControl_ERprjNIGnv](https://user-images.githubusercontent.com/16189267/184479047-1438cf19-55ce-4ad7-b224-65f46848282e.png)

I click continue, save. But the problem comes back when restarting or turning on the computer.

![F3MIIXiGsY](https://user-images.githubusercontent.com/16189267/184479105-70cb00a1-b6f5-4650-9ed1-01e579b5e797.png)

**Comment by Rem0o** [comment]
See V122 if that helps.  It should prompt you to re-save your config.
