### ISSUE TITLE
The software only supports up to 6 fan ports

### ISSUE THREAD

**Issue by tommydude2002** [Rem0o/FanControl.Releases#1013]
I'm using a Z690 MEG Godlike Board and the software cannot detect System Fan #7 and #8. There is no way to manually add it.

**Comment by coderjo** [comment]
I think this is a result of LibreHardwareMonitor not having information on the board, and thus falling back to whatever defaults they have for the detected board and/or controller. I have a similar issue with my board and am trying to figure out adding support to LHM.

**Comment by Rem0o** [comment]
See README on hardware compatibility.
