### ISSUE TITLE
Temps ramped up when closed/minimized?

### ISSUE THREAD

**Issue by Nem0404** [Rem0o/FanControl.Releases#1014]
As the title said, when i closed FC (pressed X button, FC icon at bottom right taskbar is still there, which means its working in the background, right?), my CPU temps suddenly goes up 10-20c, but when i opened the UI again, i could see the temps started going back down, it doesnt happen 100% of the time. feels like FC is off when i closed/minimized it? Is this intentional or a bug?

Window 10, latest updates
Ryzen 5800x, B550

**Comment by Rem0o** [comment]
FC runs in the background. Closing the window actually releases some resource, which might CPU spike for a second, hence the temperatures.
