### ISSUE TITLE
AUTO Fan Curve

### ISSUE THREAD

**Issue by zerovvon** [Rem0o/FanControl.Releases#1018]
Hi,

I use AUTO Fan Curve for CPU and GPU. The CPU temperature, under light load, rises sharply for a few seconds and the fans turn on. The only thing that helped me is changing Idle temp to 70°C.

I also noticed that the response time only works for lowering the temperature, and in the case of the video card it doesn't work at all (I tried setting 30 sec).

https://i.imgur.com/cOsBUuR.jpg

CPU: i7-9700KF 4.6Ghz 1.22V - Be quiet Dark Rock Pro 4
GPU: RTX 2060 Super AORUS
3xFRONT Fans: Arctic P14 PWM PST CO

**Comment by Rem0o** [comment]
Hi,

I'm not quite happy with the way the "auto" fan curve works. It tries to do to many things, and in doing so is a master of none.  It's very hard to configure. The only way it works nice is for mining rigs or any constant load. That's where it shines.

I would recommend you to stick away from it and use regular graphs/linears.

**Comment by zerovvon** [comment]
Hi,
Things are no better with the use of "Graph".
<img src="https://i.imgur.com/iOeNTGA.jpg" width="500"/>
<img src="https://i.imgur.com/F6tErzF.jpg" width="1000"/>

**Comment by zerovvon** [comment]
This is the curve for the CPU cooler.  Idle - 55 °C (jumps to 70 °C). Light load - 74 °C. Full load - 87 °C.

**Comment by zerovvon** [comment]
My configuration provides for a complete shutdown of all fans up to 60 °C. Perhaps I need to move the CPU temperature to 70 °C with 0% fan speed?

**Comment by Rem0o** [comment]
@zerovvon Yes... but I would not recommend shutting off your CPU cooler completely is any case. You might find that at low RPM you can't even hear it.
