### ISSUE TITLE
Mix Fan Curve with more than two inputs

### ISSUE THREAD

**Issue by alex6dj** [Rem0o/FanControl.Releases#102]
I. I'm using this software in mi desktop now. But I'm trying to use it in one Windows Server machine.
I have a big controlled fan blowing air in an 16 disk chamber, But for control this fan I will need to use a lot of mix curves. If you can implement this whit a variable number of inputs the jobs will be easy.
Sorry my English.

**Comment by Rem0o** [comment]
Well I get your idea, but in practice, why not simply using two disk of different locations (one in the middle of the stack, one somewhere else... ) in a mixed curve?  I do have custom sensors on the way, but it's not ready for prime time yet.

**Comment by alex6dj** [comment]
In fact this is a really good idea 👍. I will check this using the hotests disks, because not all are the same.

**Comment by alex6dj** [comment]
Ok this do the trick. Thanks.
