### ISSUE TITLE
Feature Request: Allow Hiding Curves

### ISSUE THREAD

**Issue by Wolphin5** [Rem0o/FanControl.Releases#1026]
I have some "Cards" in the Curves area I would like to hide and not show, but don't want to delete (they are Flat items used in a mix to set the minimum setting spec for the Fans and Pump), so they don't stop.  I would prefer not to see them, so that I don't change them.

**Comment by Rem0o** [comment]
Wll be coming .

**Comment by Rem0o** [comment]
V146
