### ISSUE TITLE
Fans don't respond to my curve. How to fix it and get rid of the '?' beside it?

### ISSUE THREAD

**Issue by MennoP2020** [Rem0o/FanControl.Releases#1027]
Sometimes the fans dont respond to my curve and go to a higher usage level then I had set. In these moments a "?" appears next to it. How can I fix it?

**Comment by Rem0o** [comment]
That means something else in your system is taking over.  You should try to identify it.

Take a look here:
https://github.com/Rem0o/FanControl.Releases/issues/988#issuecomment-1214397074
