### ISSUE TITLE
"Target" curve stuck at "Load Fan Speed" when using custom sensor

### ISSUE THREAD

**Issue by colinluca** [Rem0o/FanControl.Releases#1029]
The Target custom curve will stuck at the the "Load Fan Speed" when started up if using a custom temp sensor. Need to manually change any settings in the "Target" curve for it to refresh.
Have tried recreating the fan curves, custom sensor, and deleting CACHE.
Problem started to occur after V123 update.

**Comment by Rem0o** [comment]
Spotted. Will fix.
