### ISSUE TITLE
Feature Request: Asus EC sensor support

### ISSUE THREAD

**Issue by chorong761** [Rem0o/FanControl.Releases#103]
It would be nice if the fans could be controlled using T_sensor which is under ASUS EC

**Comment by Rem0o** [comment]
Any Public API available to add such support?

**Comment by chorong761** [comment]
tbh im not sure, but programs like hwinfo and aida could read it

**Comment by Rem0o** [comment]
I know HWInfo got a SDK, but it's commercial only.

**Comment by chorong761** [comment]
I see, thanks!

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.HWInfo
