### ISSUE TITLE
Question marks on percentage speed?

### ISSUE THREAD

**Issue by DoisPontinhos** [Rem0o/FanControl.Releases#1036]
**Describe the bug**
Why am I getting these questions marks ?

![Screenshot_1](https://user-images.githubusercontent.com/82269167/186011921-96cc9bff-c4e6-4b4e-ac3a-fb0e91b406a3.png)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No log.txt

**Relevant hardware specs and setup**
Specs:
Gigabyte RTX 3070 Gaming OC LHR v2
i5-12600K
Gigabyte Z690M DS3H

**Comment by Rem0o** [comment]
V124 should fix this.
