### ISSUE TITLE
Tray Icon Temperature stuck after waking from sleep with v123

### ISSUE THREAD

**Issue by chorong761** [Rem0o/FanControl.Releases#1037]
**Describe the bug**
The Temperature in the tray icon would get stuck after waking from sleep. Changing the temperature source to something else and back would fix it. The source I normally use would be from GPU.

**Is there a log.txt file next to FanControl.exe with recent date entries?**

```
22-07-22 오전 4:09:39: An exception occured with this dialog view: MessageDialog
22-07-22 오전 4:09:39: System.InvalidOperationException: No loaded DialogHost instances.
   於 MaterialDesignThemes.Wpf.DialogHost.GetInstance(Object dialogIdentifier)
   於 MaterialDesignThemes.Wpf.DialogHost.<Show>d__26.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 FanControl.Domain.DialogService.<>c__DisplayClass9_0`1.<<ShowDialog>b__0>d.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 FanControl.Domain.ApplicationContext.<InvokeAsync>d__10.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 FanControl.Domain.DialogService.<ShowDialog>d__9`1.MoveNext()
```

**Relevant hardware specs and setup**
Win 11
Asus Prime X570-Pro
Gigabyte RTX 2070

**Comment by Rem0o** [comment]
Bug spotted and will be fixed in the next version.

**Comment by Spuner** [comment]
If I understand correctly, I have the same problem, but the icon gets stuck even when I turn on my PC normally

![Screenshot (25 08 22, 07 38 49 AM)](https://user-images.githubusercontent.com/30773815/186569395-1027adc8-f86e-4192-82b1-39b73755599a.png)
.

**Comment by RafeeDaBoy** [comment]
> If I understand correctly, I have the same problem, but the icon gets stuck even when I turn on my PC normally
It sometimes happens when waking from sleep and sometimes during boot.

**Comment by Rem0o** [comment]
Download the new update.
