### ISSUE TITLE
Program consistently loses sensor data - "Error while restoring config"

### ISSUE THREAD

**Issue by anew742** [Rem0o/FanControl.Releases#104]
![Screenshot (1378)](https://user-images.githubusercontent.com/6956085/103419068-49a0c900-4b46-11eb-979d-520a9a7c0346.png)

This message keeps popping up. I have to manually re-select the sensor input in order to get the fan curves to work again, but then within a few days it gets messed up again. Additionally, the program often freezes and will not close after attempting to manually set the temperature sources. This happens on both V59 and V60

**Comment by Rem0o** [comment]
Seems like your GPU is "off" for some reason? Is this your only GPU?

**Comment by anew742** [comment]
> 
> 
> Seems like your GPU is "off" for some reason? Is this your only GPU?

This is the only GPU installed in the system, yes.
Since updating past version 60 I haven't had this issue, however! 
I haven't update drivers or anything, so that wasn't the problem.

(apologies for the super late response)

**Comment by nonsenseninja** [comment]
I guess I'm facing the same or at least a similar issue. Basically every time I boot up my PC Fan Conrol greets me with this error message:
![image](https://user-images.githubusercontent.com/10883936/107212712-a6c25100-6a07-11eb-834f-bd9b5f4a5e99.png)
I then gotta manually hit "Refresh sensors detection" to get things working again. My log file shows the following (sorry that it's in German but I guess that's how .NET handles things):

> 08.02.2021 12:12:51: Unhandled exception in FanControl v1.0.0.0
08.02.2021 12:12:51: System.AggregateException: Ausnahmen einer Aufgabe wurden nicht überwacht (entweder wegen Wartens auf die Aufgabe oder wegen des Zugriffs auf die Ausnahmeeigenschaft. Daher wurde die nicht überwachte Ausnahme vom Finalizer-Thread erneut ausgelöst. ---> System.NotSupportedException: Von diesem CollectionView-Typ werden keine Änderungen der "SourceCollection" unterstützt, wenn diese nicht von einem Dispatcher-Thread aus erfolgen.
   bei System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bei System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   bei FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   bei FanControl.ViewModels.MainWindowViewModel.Refresh()
   bei FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__112_10>d.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.NotSupportedException: Von diesem CollectionView-Typ werden keine Änderungen der "SourceCollection" unterstützt, wenn diese nicht von einem Dispatcher-Thread aus erfolgen.
   bei System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bei System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bei System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   bei FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   bei FanControl.ViewModels.MainWindowViewModel.Refresh()
   bei FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__112_10>d.MoveNext()<---

**Comment by Rem0o** [comment]
I put on a 30 sec delay to avoid these kind of problems upon boot. If you remove the start with windows task and start the software manually, say, 1 min after boot, does the problem occurs?

**Comment by nonsenseninja** [comment]
> I put on a 30 sec delay to avoid these kind of problems upon boot. If you remove the start with windows task and start the software manually, say, 1 min after boot, does the problem occurs?
Sorry for the late reply but, yes, starting manually a bit after boot seems to circumvent the issue. Would increasing that delay you mentioned any further help? Maybe the delay could be made user-configurable to fine-tune different systems?

**Comment by Rem0o** [comment]
I guess it would help.   Could maybe allow it to be edited as you said.

**Comment by nonsenseninja** [comment]
I experimented a bit more and sadly I must say that not starting Fan Control alongside Windows does in fact not consistently resolve this issue :( Do you have any other ideas as to what might cause this? Is it more likely to be an underlying issue with LibreHardwareMonitor or something that gets handled the wrong way on your end?

**Comment by Rem0o** [comment]
The message is simply a direct result of sensors simply *not" being there, it is LHM. However, it is most likely some kind of conflict with an other software.
