### ISSUE TITLE
Fan Control dosen't detect my 3rd GPU FAN

### ISSUE THREAD

**Issue by miau33** [Rem0o/FanControl.Releases#1047]
Hi,

I got an RTX 3070 TI with 3 fans, software detects only 2. Any ideea how to fix this?

King regards.

**Comment by Rem0o** [comment]
There are no Nvidia cards with 3 channels. 2 fans are plugged on one channel, the other fan on the other channel.

**Comment by miau33** [comment]
Got you, thanks for the fast respond.
