### ISSUE TITLE
EVGA X299 DARK Unable to 

### ISSUE THREAD

**Issue by carlmemory** [Rem0o/FanControl.Releases#105]
Hi,

I found that FanControl can only read the rpms of the fans but not control them on EVGA X299 DARK.
I will post the log below.

`Motherboard

SMBios Version: 3.0

BIOS Vendor: American Megatrends Inc.
BIOS Version: 1.24
BIOS Date: 2020/10/19
BIOS Size: 16 MB

System Manufacturer: EVGA Corp.
System Name: X299 DARK
System Version: Default string
System Wakeup: PowerSwitch

Motherboard Manufacturer: EVGA Corp.
Motherboard Name: X299 DARK
Motherboard Version: 1.0
Motherboard Serial: Default string

Chassis Type: Desktop
Chassis Manufacturer: EVGA Corp.
Chassis Version: Default string
Chassis Serial: Default string
Chassis Asset Tag: Default string
Chassis SKU: Default string
Chassis Boot Up State: Safe
Chassis Power Supply State: Safe
Chassis Thermal State: Safe
Chassis Power Cords: 1
Chassis Lock Detected: No
Chassis Security Status: None

Processor Manufacturer: Intel(R) Corporation
Processor Type: CentralProcessor
Processor Version: Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz
Processor Serial: 
Processor Socket Destignation: CPU0
Processor Socket: Other
Processor Version: Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz
Processor Family: IntelXeon
Processor Core Count: 18
Processor Core Enabled: 18
Processor Thread Count: 36
Processor External Clock: 100 Mhz
Processor Max Speed: 4000 Mhz
Processor Current Speed: 2600 Mhz

Cache [L1] Size: 1152
Cache [L1] Associativity: 8Way

Cache [L2] Size: 18432
Cache [L2] Associativity: 16Way

Cache [L3] Size: 25344
Cache [L3] Associativity: FullyAssociative

Memory Device [0] Manufacturer: 
Memory Device [0] Part Number: 
Memory Device [0] Device Locator: CPU1_DIMM_A0
Memory Device [0] Bank Locator: NODE 1
Memory Device [0] Speed: 2133Memory Device [0] Size: 
8192 MB

Memory Device [1] Manufacturer: NO DIMM
Memory Device [1] Part Number: NO DIMM
Memory Device [1] Device Locator: CPU1_DIMM_A1
Memory Device [1] Bank Locator: NODE 1
Memory Device [1] Speed: 0Memory Device [1] Size: 
0 MB

Memory Device [2] Manufacturer: 
Memory Device [2] Part Number: 
Memory Device [2] Device Locator: CPU1_DIMM_B0
Memory Device [2] Bank Locator: NODE 1
Memory Device [2] Speed: 2133Memory Device [2] Size: 
8192 MB

Memory Device [3] Manufacturer: NO DIMM
Memory Device [3] Part Number: NO DIMM
Memory Device [3] Device Locator: CPU1_DIMM_B1
Memory Device [3] Bank Locator: NODE 1
Memory Device [3] Speed: 0Memory Device [3] Size: 
0 MB

Memory Device [4] Manufacturer: 
Memory Device [4] Part Number: 
Memory Device [4] Device Locator: CPU1_DIMM_C0
Memory Device [4] Bank Locator: NODE 1
Memory Device [4] Speed: 2133Memory Device [4] Size: 
8192 MB

Memory Device [5] Manufacturer: NO DIMM
Memory Device [5] Part Number: NO DIMM
Memory Device [5] Device Locator: CPU1_DIMM_C1
Memory Device [5] Bank Locator: NODE 1
Memory Device [5] Speed: 0Memory Device [5] Size: 
0 MB

Memory Device [6] Manufacturer: 
Memory Device [6] Part Number: 
Memory Device [6] Device Locator: CPU1_DIMM_D0
Memory Device [6] Bank Locator: NODE 1
Memory Device [6] Speed: 2133Memory Device [6] Size: 
8192 MB

Memory Device [7] Manufacturer: NO DIMM
Memory Device [7] Part Number: NO DIMM
Memory Device [7] Device Locator: CPU1_DIMM_D1
Memory Device [7] Bank Locator: NODE 1
Memory Device [7] Speed: 0Memory Device [7] Size: 
0 MB

SMBios Table

 ABgAAAECAPAD/4CYizcBAAAAAw0FDf//QW1lcmljYW4gTWVnYXRyZW5kcyBJbmMu
 ADEuMjQAMTAvMTkvMjAyMAAAARsBAAECAwQAAgADAAQABQAGAAcACAAJBgUGRVZH
 QSBDb3JwLgBYMjk5IERBUksARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcA
 RGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcAAAIPAgABAgMEBQkGAwAKAEVW
 R0EgQ29ycC4AWDI5OSBEQVJLADEuMABEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0
 cmluZwBEZWZhdWx0IHN0cmluZwAAAxYDAAEDAgMEAwMDAwAAAAAAAQADBUVWR0Eg
 Q29ycC4ARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJp
 bmcARGVmYXVsdCBzdHJpbmcAAAgJBAABAAIPDkoxQTEAUFMyTW91c2UAAAgJBQAB
 AAIPDUoxQTEAS2V5Ym9hcmQAAAgJBgABAAId/0oyQTEAVFYgT3V0AAAICQcAAQAC
 CAlKMkEyQQBDT00gQQAACAkIAAEAAgccSjJBMkIAVmlkZW8AAAgJCQABAAISEEoz
 QTEAVVNCMQAACAkKAAEAAhIQSjNBMQBVU0IyAAAICQsAAQACEhBKM0ExAFVTQjMA
 AAgJDAAB/wAA/0o5QTEgLSBUUE0gSERSAAAICQ0AAf8AAP9KOUMxIC0gUENJRSBE
 T0NLSU5HIENPTk4AAAgJDgAB/wAA/0oyQjMgLSBDUFUgRkFOAAAICQ8AAf8AAP9K
 NkMyIC0gRVhUIEhETUkAAAgJEAAB/wAA/0ozQzEgLSBHTUNIIEZBTgAACAkRAAH/
 AAD/SjFEMSAtIElUUAAACAkSAAH/AAD/SjlFMiAtIE1EQyBJTlRQU1IAAAgJEwAB
 /wAA/0o5RTQgLSBNREMgSU5UUFNSAAAICRQAAf8AAP9KOUUzIC0gTFBDIEhPVCBE
 T0NLSU5HAAAICRUAAf8AAP9KOUUxIC0gU0NBTiBNQVRSSVgAAAgJFgAB/wAA/0o5
 RzEgLSBMUEMgU0lERSBCQU5EAAAICRcAAf8AAP9KOEYxIC0gVU5JRklFRAAACAkY
 AAH/AAD/SjZGMSAtIExWRFMAAAgJGQAB/wAA/0oyRjEgLSBMQUkgRkFOAAAICRoA
 Af8AAP9KMkcxIC0gR0ZYIFZJRAAACAkbAAH/AAD/SjFHNiAtIEFDIEpBQ0sAAAkR
 HAABpQ0EBAAADAEAAAAISjZCMgAACREdAAGlCAQDAQAMAQAAAONKNkIxAAAJER4A
 AaUIBAMCAAwBAAAA5Eo2RDEAAAkRHwABpQgEAwMADAEAAADlSjdCMQAACREgAAGl
 CAQDBAAMAQAAAOZKOEI0AAAKBiEAgwEgICBUbyBCZSBGaWxsZWQgQnkgTy5FLk0u
 AAALBSIAAURlZmF1bHQgc3RyaW5nAAAMBSMAAURlZmF1bHQgc3RyaW5nAAAgFCQA
 AAAAAAAAAAAAAAAAAAAAAAAAIgslAAEEAAAAAANMTTc4LTEAABoWJgABZwCAAIAA
 gACAAIAAAAAAAIBMTTc4QQAAJBAnAAEAAgADAAQABQAGAAAAIwsoAAElACYAJwBE
 ZWZhdWx0IHN0cmluZwAAHBYpAAFnAIAAgACAAIAAgAAAAAAAgExNNzhBAAAkECoA
 AQACAAMABAAFAAYAAAAjCysAASUAKQAqAERlZmF1bHQgc3RyaW5nAAAbDywAKQBn
 AQAAAAAAgAFDb29saW5nIERldiAxAAAkEC0AAQACAAMABAAFAAYAAAAjCy4AASUA
 LAAtAERlZmF1bHQgc3RyaW5nAAAbDy8AKQBnAQAAAAAAgAAAACQQMAABAAIAAwAE
 AAUABgAAACMLMQABJQAvADAARGVmYXVsdCBzdHJpbmcAAB0WMgABZwCAAIAAgACA
 AIAAAAAAAIBBQkMAACQQMwAAgACAAIAAgACAAIAAACMLNAABJQAyADMARGVmYXVs
 dCBzdHJpbmcAABoWNQABagCAAIAAgACAAIAAAAAAAIBMTTc4QQAAHBY2AAFqAIAA
 gACAAIAAgAAAAAAAgExNNzhBAAAbDzcANgBnAQAAAAAAgAFDb29saW5nIERldiAx
 AAAdFjgAAWoAgACAAIAAgACAAAAAAACAQUJDAAAnFjkAAQECAwQFBgcAgKIRNQA3
 ADgAVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0u
 AFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBU
 byBCZSBGaWxsZWQgQnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8g
 QmUgRmlsbGVkIEJ5IE8uRS5NLgAAKQs6AAGDAQAAABAgT25ib2FyZCBJR0QAACkL
 OwABhQEAAADIIE9uYm9hcmQgTEFOAAApCzwAAYEBAAAD4iBPbmJvYXJkIDEzOTQA
 ABAXPQADAwMAAABg/v8EAAAAAAAAAAAAAAATHz4AAAAAAP///wA9AAIAAAAAAAAA
 AAAAAAAAAAAAAAARKD8APQD+/0gAQAAAIAkAAQIagABVCAMEBQYBAAAAAKAPsASw
 BLAEQ1BVMV9ESU1NX0EwAE5PREUgMQAAFCNAAAAAAAD//38APwA+AAEAAAAAAAAA
 AAAAAAAAAAAAAAAAABEoQQA9AP7/AAAAAAAACQABAgKAAAAAAwQFBgAAAAAAAACw
 BLAEsARDUFUxX0RJTU1fQTEATk9ERSAxAE5PIERJTU0ATk8gRElNTQAgAE5PIERJ
 TU0AABEoQgA9AP7/SABAAAAgCQABAhqAAFUIAwQFBgEAAAAAoA+wBLAEsARDUFUx
 X0RJTU1fQjAATk9ERSAxAAAUI0MAAACAAP///wBCAD4AAQAAAAAAAAAAAAAAAAAA
 AAAAAAAAEShEAD0A/v8AAAAAAAAJAAECAoAAAAADBAUGAAAAAAAAALAEsASwBENQ
 VTFfRElNTV9CMQBOT0RFIDEATk8gRElNTQBOTyBESU1NACAATk8gRElNTQAAEBdF
 AAMDAwAAAGD+/wQAAAAAAAAAAAAAABMfRgAAAAAB////AUUAAgAAAAAAAAAAAAAA
 AAAAAAAAABEoRwBFAP7/SABAAAAgCQABAhqAAFUIAwQFBgEAAAAAoA+wBLAEsARD
 UFUxX0RJTU1fQzAATk9ERSAxAAAUI0gAAAAAAf//fwFHAEYAAQAAAAAAAAAAAAAA
 AAAAAAAAAAAAEShJAEUA/v8AAAAAAAAJAAECAoAAAAADBAUGAAAAAAAAALAEsASw
 BENQVTFfRElNTV9DMQBOT0RFIDEATk8gRElNTQBOTyBESU1NACAATk8gRElNTQAA
 EShKAEUA/v9IAEAAACAJAAECGoAAVQgDBAUGAQAAAACgD7AEsASwBENQVTFfRElN
 TV9EMABOT0RFIDEAABQjSwAAAIAB////AUoARgABAAAAAAAAAAAAAAAAAAAAAAAA
 AAARKEwARQD+/wAAAAAAAAkAAQICgAAAAAMEBQYAAAAAAAAAsASwBLAEQ1BVMV9E
 SU1NX0QxAE5PREUgMQBOTyBESU1NAE5PIERJTU0AIABOTyBESU1NAADxC00ARU9D
 LDAAAAAABxNOAAGAAYAEgAQgACAAAAUDB0wxLUNhY2hlAAAHE08AAYECAEgASCAA
 IAAABQUITDItQ2FjaGUAAAcTUAABggIAYwBjIAAgAAAFBQZMMy1DYWNoZQAABDBR
 AAEDswJUBgUA//vrvwOQZACgDygKQQFOAE8AUAAABAASEiT8ALMAEgASACQAQ1BV
 MABJbnRlbChSKSBDb3Jwb3JhdGlvbgBJbnRlbChSKSBDb3JlKFRNKSBpOS03OTgw
 WEUgQ1BVIEAgMi42MEdIegBVTktOT1dOAACCFFQAJEFNVAAAAAAApa8CwAAAAAAA
 g0BVADEAAAAAAAAAAAAAAPgA0qIAAAAAAQAAAAwACwDGBlAAAAAAAP4AuBUAAAAA
 AAAAAAIAAAB2UHJvAAAAAAAAiAZWAAAAAAAOCFcAAdsAACRNRUkAANtRWAABAwFV
 AgCQBgMAZiAAAAAASAgAAAAAAAAAAAAC////////////////////////////////
 AwAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAE1FSTEATUVJMgBNRUkzAAB/BFkAAAA=

Intel CPU

Name: Intel Core i9-7980XE
Number of Cores: 18
Threads per Core: 2
Timer Frequency: 10 MHz
Time Stamp Counter: Invariant
Estimated Time Stamp Counter Frequency: 2592.01 MHz
Estimated Time Stamp Counter Frequency Error: 0.01037 Mhz
Time Stamp Counter Frequency: 2592 MHz

MSR Core #1

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  000026C0  00002D00
 0000019C  00000000  88470800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #2

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002700  00002D00
 0000019C  00000000  88480800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #3

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002740  00002D00
 0000019C  00000000  88490800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #4

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  000027C0  00002D00
 0000019C  00000000  88490800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #5

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002740  00002D00
 0000019C  00000000  88470800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #6

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  000026C0  00002D00
 0000019C  00000000  88470800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #7

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  000026C0  00002D00
 0000019C  00000000  88480800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #8

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002680  00002D00
 0000019C  00000000  88490800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #9

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  000026C0  00002D00
 0000019C  00000000  88480800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #10

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002700  00002D00
 0000019C  00000000  88470800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #11

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002700  00002D00
 0000019C  00000000  88480800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9D53
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #12

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002700  00002D00
 0000019C  00000000  88490800
 000001A2  00000000  006D0A00
 000001B1  00000000  883F0800
 00000606  00000000  000A0E03
 00000611  00000000  609C9E36
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #13

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002780  00002D00
 0000019C  00000000  88490800
 000001A2  00000000  006D0A00
 000001B1  00000000  88410800
 00000606  00000000  000A0E03
 00000611  00000000  609C9E36
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #14

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002780  00002D00
 0000019C  00000000  88490800
 000001A2  00000000  006D0A00
 000001B1  00000000  88410800
 00000606  00000000  000A0E03
 00000611  00000000  609C9E36
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #15

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002700  00002D00
 0000019C  00000000  88470800
 000001A2  00000000  006D0A00
 000001B1  00000000  88410800
 00000606  00000000  000A0E03
 00000611  00000000  609C9F1F
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #16

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002780  00002D00
 0000019C  00000000  88480800
 000001A2  00000000  006D0A00
 000001B1  00000000  88410800
 00000606  00000000  000A0E03
 00000611  00000000  609C9F1F
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #17

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002700  00002D00
 0000019C  00000000  88480800
 000001A2  00000000  006D0A00
 000001B1  00000000  88410800
 00000606  00000000  000A0E03
 00000611  00000000  609C9F1F
 00000619  00000000  00000000
 00000639  00000000  00000000

MSR Core #18

 MSR       EDX       EAX
 000000CE  00070C2C  F3011A00
 00000198  00002740  00002D00
 0000019C  00000000  88410800
 000001A2  00000000  006D0A00
 000001B1  00000000  88410800
 00000606  00000000  000A0E03
 00000611  00000000  609C9F1F
 00000619  00000000  00000000
 00000639  00000000  00000000

MicroArchitecture: Skylake
Time Stamp Counter Multiplier: 26

Nvidia GPU

Name: NVIDIA GeForce RTX 3090
Index: 0
Driver Version: 460.89
Driver Branch: r460_74-7

DeviceID: 0x220410DE
SubSystemID: 0x39983842
RevisionID: 0xA1
ExtDeviceID: 0x2204

Thermal Settings

 Sensor[0].Controller: GPU_INTERNAL
 Sensor[0].DefaultMinTemp: 0
 Sensor[0].DefaultMaxTemp: 127
 Sensor[0].CurrentTemp: 31
 Sensor[0].Target: GPU

Clocks

 Clock[0]: 225000
 Clock[1]: 17
 Clock[2]: 600000
 Clock[3]: 1
 Clock[4]: 525000
 Clock[5]: 1
 Clock[6]: 450000
 Clock[7]: 1
 Clock[8]: 405000
 Clock[9]: 9
 Clock[10]: 585000
 Clock[11]: 1
 Clock[12]: 675000
 Clock[13]: 17
 Clock[40]: 540000
 Clock[41]: 1
 Clock[42]: 555000
 Clock[43]: 1
 Clock[44]: 108000
 Clock[45]: 1
 Clock[62]: 1
 Clock[63]: 1
 Clock[64]: 221619
 Clock[65]: 32
 Clock[71]: 423336
 Clock[72]: 32
 Clock[78]: 525000
 Clock[79]: 32
 Clock[85]: 449999
 Clock[86]: 32
 Clock[92]: 285135
 Clock[93]: 32
 Clock[99]: 584999
 Clock[100]: 32
 Clock[106]: 675000
 Clock[107]: 32
 Clock[204]: 540000
 Clock[205]: 32
 Clock[211]: 555000
 Clock[212]: 32
 Clock[218]: 108000
 Clock[219]: 32
 Clock[281]: 1
 Clock[282]: 32

Tachometer

 Status: NOT_SUPPORTED

P-States

 Percentage[0]: 0
 Percentage[1]: 7
 Percentage[2]: 0
 Percentage[3]: 0

Usages

 Usage[1]: 1
 Usage[5]: 1
 Usage[6]: 7
 Usage[9]: 1
 Usage[13]: 1

Cooler Settings

 Status: NOT_SUPPORTED

Fan Coolers Status

 Items[0].Type: 1
 Items[0].CurrentRpm: 0
 Items[0].CurrentMinLevel: 30
 Items[0].CurrentMaxLevel: 100
 Items[0].CurrentLevel: 30
 Items[1].Type: 2
 Items[1].CurrentRpm: 0
 Items[1].CurrentMinLevel: 30
 Items[1].CurrentMaxLevel: 100
 Items[1].CurrentLevel: 0

Memory Info

 Value[0]: 25165824
 Value[1]: 24932352
 Value[2]: 0
 Value[3]: 16617508
 Value[4]: 24182856

LPC F718XX

Base Address: 0x0290

Hardware Monitor Registers

      00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

 00   FF C3 00 01 01 FF FF 00 00 00 02 00 6D 4C 00 30
 10   00 00 00 00 00 00 06 FF FF FF FF FF FF FF FF FF
 20   CB 91 77 76 7C 77 A2 D3 C0 FF FF FF FF 26 4D 00
 30   7A D7 FF FF FF FF C9 C8 75 85 FF FF FF FF FF 00
 40   44 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 50   FF FF FF FF FF FF FF FF FF FF 03 04 10 19 34 FF
 60   00 22 00 00 FF FF 02 00 00 00 FF 0E 40 24 FF 00
 70   FF FF 26 FF 32 FF 2A FF 26 00 26 26 26 00 00 00
 80   FF FF 64 55 64 55 55 46 FF FF FF FF FF FF A8 FF
 90   00 04 00 00 00 FF 1F FF 44 02 00 3F 55 05 99 1A
 A0   08 DD 00 26 01 7D 46 3C 32 28 FF 4C 33 33 33 0D
 B0   07 CD 00 4D 01 6D 46 3C 32 28 FF 59 3F 3F 3F 0C
 C0   0F FF 00 00 00 89 4B 44 3C 37 FF B2 4C 00 00 0E
 D0   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 E0   00 00 00 00 00 00 00 00 00 FF FF FF 00 00 01 00
 F0   00 00 00 00 00 00 31 FF 02 AB FF 00 FF 00 FF FF

`

**Comment by carlmemory** [comment]
The monitoring chip seems to be a fintek f71889ad.

**Comment by Rem0o** [comment]
Support is handled by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.
