### ISSUE TITLE
This country or region does not support donations to this recipient, I'm chanese

### ISSUE THREAD

**Issue by juyss** [Rem0o/FanControl.Releases#1050]
**Describe the bug**
[A clear and concise description of what the bug is. Hardware support requests do NOT count as a bug. See README. Screenshots are worth a thousand words.]

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
https://github.com/sponsors/Rem0o
