### ISSUE TITLE
ZeroRPM Implementation Recommendation

### ISSUE THREAD

**Issue by SinanAkkoyun** [Rem0o/FanControl.Releases#1052]
Hey, when turning on GPU curves, many RTX cards only go down to 30% and not to 0% (zero rpm only allowed on stock curves)
When turning off fan control, it goes down to zero. This means that custom zero rpm curves do not exist

However, I had this very simple but cool idea to achieve zero rpm idle whilst having a custom curve:
Temp monitoring is always available, sso implement a mode in which the fan control only gets activated above a certain temp threshold. When it's below, it needs to be turned off so that the NVIDIA API acts as if the stock fan curve is running, however when it exceeds the temp the control kicks on and the custom fan curve can be applied.

I would be super happy if you would implement this, a lot of people would benefit from that!
Also, thank you so so much for the great software.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/issues/1187
