### ISSUE TITLE
Feature request: Temporary startup curves

### ISSUE THREAD

**Issue by Rodg88** [Rem0o/FanControl.Releases#1057]
I have a graphics card with fans that only start at a higher % than their lowest running speed, causing pulsing until they properly spin up. At the moment I get around this by manually setting a flat 50% speed curve for a few seconds when my PC starts/wakes up, which gets the fans spinning, then I switch to a normal sloped curve so the fans slow down but stay spinning.

An automatic way to set a 'startup curve' would be nice to stop having to do this manually each time my PC wakes up or Starts up.

Another option would be a "jumpstart" feature, where if it detects a fan isnt spinning when it should be, set it to a specific speed for a certain time.

**Comment by Rem0o** [comment]
That's what start% is for in the control card. Set 50% as a start%.

**Comment by Rodg88** [comment]
Oh that does seem to work for me, thanks!
