### ISSUE TITLE
Request: Curve detection system

### ISSUE THREAD

**Issue by Ekristoffe** [Rem0o/FanControl.Releases#1058]
** This is not a bug report, just an idea of a function **
Could it be possible to create a curve from an existing behavior of a fan ?
For example looking at a fan % and an temp and reporting in a file every x second.
By doing this we can learn the default behavior of card and motherboard.
It could be a nice tool if we want to emulate and optimize a component cooling.

**Comment by Rem0o** [comment]
So you report a temperature ( which sensor ? ) and fan rpm... then what? What if the curve has some hysteresis, or basically is not a linear function ?  I fail to see the purpose, and implementation would have lots of gotchas.

**Comment by Ekristoffe** [comment]
I mean a recording system to learn how the default function work (fan % / temp) I know fan RPM aren't good because of the lag of the RPM sensor itself.
i don't know if a plugin could have access to temp and fan control % (Read only) ?

**Comment by Rem0o** [comment]
Well, at that point just use LHM straight up, code is open.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
