### ISSUE TITLE
Fan RPMs gone missing

### ISSUE THREAD

**Issue by molnarti** [Rem0o/FanControl.Releases#1059]
**Describe the bug**
So this may sound trivial, but when i started to use FanControl it showed the fan speed in RPMs next to the percentage to each fan, except the GPU. However the RPM is now gone totally. I don't know if this was caused by an update or something changed in the settings, i searched the changelog and the issues here on gitlab but found nothing.

Was this feature removed or its a problem with my set up?

![image](https://user-images.githubusercontent.com/25829862/187521946-63563f53-38d0-4e32-b223-e3b5182550f4.png)

**Comment by coderjo** [comment]
Do the speeds show up on the speed cards if you show them? (uncheck "hide fan speed cards" and check "show hidden cards" to ensure they are visible)

If so, it may be that you need to re-associate controls with fan speed inputs.

**Comment by Rem0o** [comment]
^

My guess is that you got the settings to hide them. Open the left hamburger menu, and unhide everything if needed.

**Comment by molnarti** [comment]
yes, you are right, it seems my controls and speed sensor got unpaired somehow. repairing them solved the issue and now can see the fanspeed on the control cards 
![image](https://user-images.githubusercontent.com/25829862/188321370-fa11bcf5-6c23-4753-8de1-f64a48feb631.png)
