### ISSUE TITLE
Feature request - "Mix" Fan curve - "Min" function

### ISSUE THREAD

**Issue by mhartvig** [Rem0o/FanControl.Releases#106]
I would like a "Min" function added to the mix fan curve. 

Example: Using a "Sync" fan curve in combination with a "Flat" fan curve I can set a upper limit for how fast my fan should spin (the flat curve) while keeping the fan in sync with my other fans.

**Comment by Rem0o** [comment]
Fair enough!

**Comment by mhartvig** [comment]
Thanks for the quick update!
FYI it should be added here as well https://github.com/Rem0o/FanControl.Releases#fan-curve-types
