### ISSUE TITLE
Fans at ZERO

### ISSUE THREAD

**Issue by goncalo532** [Rem0o/FanControl.Releases#1060]
Was AFK on a game and suddenly hear the AIO ramp up to 100% with liquid temps as measured by T sensor going up to 55 celsius before I emergency shut down. Restarted it, fan control shows fans at "15%" but actual RPM is zero and visually not spinning (screen attached). Tested and fans are working fine so it is an app issue, is there a way to have an emergency profile quick in? Can't have this happen randomly while I am not looking.
![Fancontrol ZERO](https://user-images.githubusercontent.com/59667597/187633180-526b46cc-f7f4-4ee2-b0ff-64b6b1c0129d.jpeg)

**Comment by Rem0o** [comment]
Expand those control cards, something seems off with your configuration. Post a screenshot will all infos visible.

**Comment by goncalo532** [comment]
Ye very weird, as far as I can tell has been working fine for the past 2 months never saw this happen and haven't changed anything apart from updating fan control. On the last restart it seems to have gone back to working with nothing changing.
![Fan curve](https://user-images.githubusercontent.com/59667597/187717561-5cdf7d4d-6155-4f87-9673-5bf84a09725a.jpg)
![Controls](https://user-images.githubusercontent.com/59667597/187717569-d4bdc72a-e9e1-432b-b03b-3d47fa026d5b.jpg)
![AIO pump curve](https://user-images.githubusercontent.com/59667597/187717574-0eb9e976-5537-41e3-8883-9ba3a34918c5.jpg)

**Comment by Rem0o** [comment]
My guess is that your start% set at 15 is too low.   In your previous example, it was trying to kickstart them at 15, but it's not enough to make them spin up.   Use the built-in function to find the start%, or find it manually, but 15 is too low.

**Comment by madwulf** [comment]
Just updated and having the same issue, set a flat 100 curves and it still will sit the fan control at 15% 0 RPM. doing the test for minimum rpm reported I needed my fans set at 96% something I've not had to do previously.

**Comment by goncalo532** [comment]
I have always used the built in pre-set feature never did it manually, definitely has been something post 124 update not sure.

**Comment by Rem0o** [comment]
@goncalo532 So what's the actual start % of your fans?

**Comment by Rem0o** [comment]
> I see the pre-built feature does not detect the start % as it states the fans never stopped but testing manually they start spinning at 14%.

If the feature says that, it means the fan never hit 0 RPM even when it instructed 0%.  Did you match the control with the right RPM ?

**Comment by goncalo532** [comment]
Not sure on the question mind explaining a bit? I have setup the fan control that the start percentage is 14% if that is what you are asking

**Comment by Rem0o** [comment]
For a given fan, do the following:

![image](https://user-images.githubusercontent.com/14118956/187949768-973f0632-41bf-4c84-8fd4-8b8517b61a4f.png)

On step 1. , does it matches with something?

On step 2. , is it able to stop the fan, and what's the start% it finds.

**Comment by goncalo532** [comment]
Oh yes that was paired and just retried no issues with the sensor pairing. In terms of  the start % it states fans never stopped. Does detect fan stop % at 12%.
![never stopped](https://user-images.githubusercontent.com/59667597/187950486-e3f2802e-a630-4d88-8163-9e4812e5dae5.jpg)

**Comment by Rem0o** [comment]
How can it detect the stop at 12% if the fan never stops? Makes no sense.

**Comment by goncalo532** [comment]
I agree it makes no sense, when I do detect fan stop % auto it shows. With both start and stop at 0%, the detect start % auto still states fans never stopped.
![auto detct stop %](https://user-images.githubusercontent.com/59667597/187955733-6e7a5c7a-61b6-4a9f-8be3-b31fb7011f9d.jpg)

**Comment by Rem0o** [comment]
During the start% part, when it sets it to 0%, does the RPM on the card drop? Or it stays spinner?

**Comment by goncalo532** [comment]
So during the start % part it never stops. Manually I can set to 0 and it will stop, going up slowly I can see it starts spinning at 10%. The rpms seems pretty constant once you setup a percent,

The bios does have a setup as all do but it seems to only be active during boot, the reason I say this is because when the fans went to zero suddenly the other day I would have expected the bios to kick in if it sensed temperatures going through the roof. Also there are two fan headers so I think it would be too much of a coincidence for both to have stopped working at the same time. Asus does have this AI suite 3 which controls fans but that is not on.

**Comment by Rem0o** [comment]
How long does it takes for the fan to stop if you manually set it to 0%? The start% functionality waits 7 seconds for it to stop. If it somehow takes longer, maybe that's why we have this weird behavior.

**Comment by goncalo532** [comment]
Takes 9 seconds for it to stop from 50%, 15 seconds from 100%, 7.3 seconds from 35% which is the minimum. I tried going down on my curve and even with it set to zero / stopped before testing the start % it doesn't work.

Interesting I note every time the detect start % commences and states setting to 0 the rpms for whatever reason jump to 66% which is the fan control curve for that temperature. And earlier I could see with cooler temps it was jumping to lower rpms. Basically every time the detect start % attempts to stop the fans they auto jump to the speed they are set to be at for that specific temp on the curve.

![detect start %](https://user-images.githubusercontent.com/59667597/187963637-2625ba4f-b356-4300-8044-2818633ce78c.jpg)

**Comment by Rem0o** [comment]
Update to V126.

**Comment by Rem0o** [comment]
Fixed in 128.
