### ISSUE TITLE
Missing time average sensor warning with V125

### ISSUE THREAD

**Issue by mattzink** [Rem0o/FanControl.Releases#1066]
**Describe the bug**
After upgrading to V125, I receive an error pop-up with the following message _everytime_ FanControl starts up.
```
These errors occurred while restoring the configuration: 
-  Missing sensor for time average sensor "CPU/GPU Time Average"
```

I haven't changed my config in a while and have never seen this in any previous version. If I click "Refresh" the error message pop-up again immediately. If I click "Continue", everything seems to be working normal.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No new entries in a month

**Relevant hardware specs and setup**
ASUS Z690 Extreme + Intel 12900K + Gigabyte 3080 TI

**Comment by pyrocumulus** [comment]
I have the same issue. Took me some time to figure out that there is actually no problem, apart from this error message. The sensor is found and is actually working too. It seems to be something with the code which checks the configuration upon read.

If I choose another sensor in the "CPU/GPU Time Average" (for example CPU Core) and check the sensor configuration then the problem goes away. But if I restore the "Max CPU/GPU" as the sensor, the problem reappears. All the while, all the sensors and curves are working correct though.

**Relevant hardware**
Gigabyte Tomahawk B550
Ryzen 7 5800X
Gigabyte 3070 Ti Gaming OC

**Comment by muddymind** [comment]
I also have this issue:

![image](https://user-images.githubusercontent.com/8367895/188279461-cb2fb363-3365-45b0-ba5a-d730657ce8d0.png)

**Comment by Rem0o** [comment]
V126 should fix this.
