### ISSUE TITLE
Fan speeds hit 100% as FanControl starts since v125

### ISSUE THREAD

**Issue by SlimJim192** [Rem0o/FanControl.Releases#1068]
Since the latest update my fans now hit 100% just as FanControl launches and takes control -- my hysteresis settings means it then drops down to the actual curve value quite slowly (which is desired when the fans actually ramp up based on temp).

Before FanControl launches the fans behave normally (motherboard settings) - which are nowhere near 100%.

Its just as FanControl intialises.

If I turn a fan off in the app and then turn it back on - it does the same thing ramps to 100% briefly. Doesnt seem to occur on the GPU though. Just fans wired to motherboard.

Is this intentional? I don't really like it if so.. 

An option to go back to how it was would be great. (before it was more or less unnoticeable switching from mobo curves to FanControl curves).

To confirm, just gone back to v122 via Releases Page - and the issue is gone!

**Relevant hardware specs and setup**
B550 Aorus Pro AX Rev1.0

**Comment by Rem0o** [comment]
Any custom sensor in your config?

**Comment by johnlevandowski** [comment]
![fancontrol](https://user-images.githubusercontent.com/1932609/188183965-0f6bfcda-4634-4fbf-a53b-e9b2c6458c4c.png)

**Comment by Rem0o** [comment]
@johnlevandowski 

In v125, 
1) if you disable the control case rear, what % does it goes to.
2) If you refresh the sensors (three dot menu at the top right), does it blasts at 100% still or is it just when you launch the app

**Comment by johnlevandowski** [comment]
>     1. if you disable the control case rear and case front, what % does it goes to.

Disabling case rear and case front it goes to 0%.  Enabling case rear and case front again causes them to spin up to 100% and then back to 30% (my setting from the graph).

>     2. If you refresh the sensors (three dot menu at the top right), does it blasts at 100% still or is it just when you launch the app

Refresh sensors detection causes the fans to spin up to 100% and then back to my settings.  It also will do this when launching the application.

**Comment by SlimJim192** [comment]
> Any custom sensor in your config?

Thanks for the reply.

I have a mix fan curve for these Fans set to average?

It averages my graph CPU curve and GPU curve.

Will post screens a bit later (not at my desktop).

**Comment by johnlevandowski** [comment]
Thanks,  I had a mix fan curve setup before, but I thought having a custom sensor would be easier since I'm using the Max of 7 different sensors.

**Comment by Rem0o** [comment]
@johnlevandowski  What start% do you have configured on your control cards.

**Comment by johnlevandowski** [comment]
> @johnlevandowski What start% do you have configured on your control cards.

The start % is 0% for all of them, except the GPU which is 30%

**Comment by Rem0o** [comment]
@johnlevandowski  If you set manual mode to 50% on a control, disable, enable, does it shoot up still to a 100%?

**Comment by johnlevandowski** [comment]
> @johnlevandowski If you set manual mode to 50% on a control, disable, enable, does it shoot up still to a 100%?

Yes

**Comment by SlimJim192** [comment]
![image](https://user-images.githubusercontent.com/9752274/188228362-f6533213-4163-4d2f-b324-121819ed5c35.png)
Here's my setup.

Occurs on CPU fans and Case (IN and EX) fans - but not GPU fan.

Can also confirm if set to manual mode - when you switch on they go to 100% before dropping.

**Comment by JKawmi** [comment]
I am also facing the same issue since v125, I thought it was a bug with the delay in the settings, is there anyway I can disable the delay completely? The lowest I can set it is 1 second.

Here is my very simple setup
![image](https://user-images.githubusercontent.com/13506188/188280033-d23ea5ff-c523-4be4-8ad1-05f48b17a434.png)

**Comment by Rem0o** [comment]
V126 should help with this.

**Comment by JKawmi** [comment]
Just updated to V126 and the issue is still happening

**Comment by Rem0o** [comment]
@JKawmi do you get the same behavior if you disable then enable back a control?
If you revert back to, does it really fixes it?

**Comment by SlimJim192** [comment]
@Rem0o - I've just upgraded to v126 - Still experiencing the same behaviour as v125.

Definitely doesn't happen at all back on v124.

**Comment by Rem0o** [comment]
I'm really having a hard time to figure what could cause this. It has to be some non-obvious side effect that only affects some motherboards, since I personally did a ton of tests on 2 different without getting that behavior.

This is kind of a hail Mary : [FanControl.Library.zip](https://github.com/Rem0o/FanControl.Releases/files/9483581/FanControl.Library.zip)

I changed back the only thing that I can see that could potentially cause this behavior. Just swap this DLL in.

**Comment by SlimJim192** [comment]
Yeah I can appreciate not being able to reproduce would be difficult to troubleshoot.

I've just tried that DLL but no change unfortunately..

I can tell you the controller on my board for the affected fans is an ITE IT8688E - I wonder if the others here have the same one.
![image](https://user-images.githubusercontent.com/9752274/188292257-1f17f755-dd31-4485-8705-3595416b0538.png)

**Comment by SlimJim192** [comment]
https://user-images.githubusercontent.com/9752274/188292479-46553685-c0e8-4c39-902f-f846dc128fce.mp4

Heres a small screen cap of it occuring. As you can see it appears to send a 100% command initially which then gradually works its way down (the rate at which seems to obey the % step down setting - in my case 2%/sec).

If I do it very quickly it doesnt happen. But happens on launch, when turning on/off, when refreshing sensors - doesnt matter if using curve or manual.

**Comment by Rem0o** [comment]
@SlimJim192  Will send you an other dll that logs everything a control received as instruction from FanControl.
Keep only 1 control enabled to keep the logs manageable, and do the bug.

**Comment by SlimJim192** [comment]
@Rem0o No problem

**Comment by Rem0o** [comment]
Please clean your log.txt before going forward with this for clean logs.

[FanControl.Library (2).zip](https://github.com/Rem0o/FanControl.Releases/files/9483637/FanControl.Library.2.zip)

**Comment by SlimJim192** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9483642/log.txt)

Here you go - The first value set appears to be 98 -- and at this point it doesnt seem to know the current value.

(You can see this at launch and then once again when I did it manually).

**Comment by SlimJim192** [comment]
Awesome! I guess the question now is why doesnt it know ha.

Just let me know if theres anything else I can do.

**Comment by Rem0o** [comment]
@SlimJim192  Found it to be ITE implementation specific in LHM where it won't read the control sensor when no software value is provided. 

Basically, I use the control value as a starting point when enabling a control.  It starts from that point, then use the step up/down to go to the target. 

For eg:  Control is at 68 by default, step down is 5% per second. You enable the control with a target value of 58%.  The first iteration will be (58 -5) = 53, then (53-5) again for the final 58%.   

However, when NO value is provided, here null, I didn't account properly for this scenario that I frankly overlooked, and it defaulted to the maximum control value, here 100. Hence why you saw 98, 100-2.

**Comment by Rem0o** [comment]
@SlimJim192 and everyone here having issue

Swap these out and tell me how it goes.

[FanControl.zip](https://github.com/Rem0o/FanControl.Releases/files/9485143/FanControl.zip)

**Comment by johnlevandowski** [comment]
> @SlimJim192 and everyone here having issue
> 
> Swap these out and tell me how it goes.
> 
> [FanControl.zip](https://github.com/Rem0o/FanControl.Releases/files/9485143/FanControl.zip)

That fixed the problem for me.  👍

**Comment by SlimJim192** [comment]
> @SlimJim192 and everyone here having issue
> 
> Swap these out and tell me how it goes.
> 
> [FanControl.zip](https://github.com/Rem0o/FanControl.Releases/files/9485143/FanControl.zip)

Yep sorted! Great work!

**Comment by JKawmi** [comment]
> @SlimJim192 and everyone here having issue
> 
> Swap these out and tell me how it goes.
> 
> [FanControl.zip](https://github.com/Rem0o/FanControl.Releases/files/9485143/FanControl.zip)

Fixed the issue for me as well, thanks! :)

**Comment by Rem0o** [comment]
V127 brings this change in. Thanks everyone.
