### ISSUE TITLE
Feature: different step% up and down

### ISSUE THREAD

**Issue by Meeni-mc** [Rem0o/FanControl.Releases#107]
# Requested feature

Have a different control for up/down 'step%' in fan controller. 

# Use case

I have an AMD Ryzen 3600 CPU. It does swing in temperature with load very rapidly. I'd like my CPU fan to ramp-up to the maximum speed as quickly as possible, but I'd like the fan to tapper slowly to the rest speed.

One can control the 'step%' and set it to '1', but that applies both ramping-up and ramping-down fan speed, which makes the fan too slow to react to rapid load increase.

# Example

| time (s) | 0 | 1 | 2 | 3 |
| --- | --- | --- | --- | --- |
| temp (C) | 35 | 95 | 45 | 35 |
| fan (%) up/down step 50 | 30 | 80 | 40 | 30 |
| fan (%) up 50, down 10 (desired) | 30 | 100 | 80 | 60... |

**Comment by Cubox** [comment]
This would be great as well
As you said, the Ryzen CPUs jump in temperature quite harshly by their nature.
You could mitigate that using hysteresis on the temperature curve, checking "only use hysteresis on temperature down"

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V68
