### ISSUE TITLE
Updates do not show when minimised 

### ISSUE THREAD

**Issue by speed-of-heat** [Rem0o/FanControl.Releases#1071]
**Describe the bug**
Whenever there is an update, if Fancontrol is set to be minimised to the tray, no UI shows for the update, and seems to cause Windows to go "black screen" for a while.  Also while there is an update waiting no icon shows in the tray, until the update is applied. Forcing you to manually open the UI and perform the update .

**Comment by Rem0o** [comment]
The update check only happens when the window is first loaded. If you are minimized to tray on start, there is no update check until you open it up, where it will ping this github repo for a new version.

**Comment by Rem0o** [comment]
Next version will prompt the minimized window if an update is available.
