### ISSUE TITLE
Since last version "manual control" do nothing

### ISSUE THREAD

**Issue by Majber** [Rem0o/FanControl.Releases#1073]
**Describe the bug**
Since last version (126), or maybe 125 (I have two updates today). I cant use manual control to change speed of my "mix" curve. I will provide screenshot. It should change to 100% but its stays at mix. Force apply dont do anything too.

![image](https://user-images.githubusercontent.com/8217598/188282092-931b9b4c-6a54-4953-8308-31c92c2db37e.png)

Please help, Im not english native speaker.
Win10 pro, 
![image](https://user-images.githubusercontent.com/8217598/188282119-ca5a795c-9fdc-4398-8c0a-b53a88956cad.png)

**Comment by Rem0o** [comment]
Relaunch updater.exe

**Comment by Majber** [comment]
its working!, thank you
