### ISSUE TITLE
Fan manual control is not available

### ISSUE THREAD

**Issue by frasx** [Rem0o/FanControl.Releases#1074]
So i downloaded the software but the "manual control" and "force apply" buttons are disabled.
Maybe i've just missed something important while downloading the software. 
I am starting fan control in administrator mode. I hope someone can help me.

My motherboard is an Intel Z87 Mainboard ATX and i am on windows 10 64bit.

![image](https://user-images.githubusercontent.com/78259109/188284790-3c6504f8-6563-4e90-ae7c-5ad98f5b8dad.png)

**Comment by Rem0o** [comment]
Toggle the control card on first.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/188287449-cbd07adf-3953-4e8c-b7fd-f24cf2f69be4.png)
