### ISSUE TITLE
Can't start FanControl

### ISSUE THREAD

**Issue by Mark-Joy** [Rem0o/FanControl.Releases#1077]
**Describe the bug**
I couldn't get the app to start on Windows 8.1 fresh installation.
Error: System.MissingMethodException: Method not found

Any help, pls?

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9483801/log.txt)

**Relevant hardware specs and setup**
Windows 8.1 fresh installation

**Comment by Rem0o** [comment]
From README:

Q: Does it run on my OS?
A: If your OS is Windows 10 Or 11, yes.
