### ISSUE TITLE
update 127 broke... one fan

### ISSUE THREAD

**Issue by Requen** [Rem0o/FanControl.Releases#1079]
i'm not quite sure how to formulate this, but directly after clicking update and the inevitable restart of fancontrol one fan is not controllable anymore. 

the fan sensor shows it spinning at minimum RPM, but manual controlling it or setting any % in linked curves at 0 Celcius doesn't make it move. the functions "pair speed sensor automatically" showed no errors and correctly identifying the already correct fan sensor. "detect fan start % automatically" said it could never stop the fan, which is expected as the fan has a minimum rotation of 300 rpm and cannot be stopped (Dynamic X2 GP-18 PWM) unless i switch it to DC in BIOS, which was no issue in the versions before.

fancontrol sees the fan, but cannot control it anymore basically.

i double checked if something else broke when i clicked update in fancontrol. went into BIOS and manually set the Fan to 33, 50, 66 and 100%, all fine and creating the expected tornados. i also didn't change any hardware or software, also no uncalled windows updates in between. i started my pc, fancontrol does the programmed settings, i saw the called out fan spinning at my set percent. i wanted to set minimum rpm of gpu to 25 because today is unusually hot, it asked for update. after update, fan is dead.

personal request: i would love to just revert to 126 for the moment. the version is sadly not available here (last version is 122 or so). if you could make this available until this issue is fixed, that would be great, this software is the bread and butter of my air-flow case, one fan spinning at minimum rpm doesn't help my case.

thank you and thanks for all the hard work!

edit: i went ahead and installed the available v122. (all) fans and curves work as expected. no errors here.

**Comment by Rem0o** [comment]
That's odd. The fact the pairing still works means the fan is responding to fan control. 

Can you share a screenshot of the "problem" occuring, with all of your config visible, cards expanded and everything.

**Comment by Requen** [comment]
![FanControl_2022-09-06_04-11-59](https://user-images.githubusercontent.com/66755508/188532514-64a03ba5-6c20-4c6c-ab85-86afdd02f730.png)

setting 2x180 Front to manual comtrol and slide to 100% or anything above 33% (starting point) doesn't change anything. they start just fine at 33% on v122 to v126

**Comment by Requen** [comment]
![image](https://user-images.githubusercontent.com/66755508/188534301-0d7398da-043b-4854-a36c-9d80a0fea91f.png)

this is from v122 just now.

![image](https://user-images.githubusercontent.com/66755508/188534543-96f27830-ba0d-4c9f-be45-e08dd418e36a.png)

works also on v122. it's kinda a head-scratcher 😕

**Comment by Rem0o** [comment]
Remove the start% and stop% (set 0) on that control since it just doesn't stop.

**Comment by Requen** [comment]
![2022-09-06_05-20-10](https://user-images.githubusercontent.com/66755508/188542559-c03ad4b5-b63b-41ac-af8f-dce0c1025e77.png)

it gave me this error message after setting both to zero, i then did "pair speed sensor automatically" again and then the fan started working. problem solved! thank you very much!
