### ISSUE TITLE
Feature/confused?: fan stop speed

### ISSUE THREAD

**Issue by Meeni-mc** [Rem0o/FanControl.Releases#108]
# Use case: Trying to avoid short-cycling fans in passive cooling idle scenario.

I have an AMD Ryzen processor. This processor can rest at idle fanless (about 40C average). However, this processor has large temperature spikes when idling (that 40 average consists of rapid spiking between 35 and 50). 

This results in the fan doing rapid cycling, up for a second, down for 2 seconds, up for half a second, down for 2 seconds, etc. Not very good for fan life. 

I'd like to have better control of how long the fan turns on for. If it turns on, it should stay on for a configurable minimum amount of time (at the slowest speed setting if strictly following would turn it off). 

# Observed behavior with fan stop speed setting 

I tried to use the `start %` and `stop %` settings to achieve this behavior. But that did not at all do what's on the tin and I ended-up confused as to what the 'stop' control does. 

The idea is that the fan would start when reaching 50C, and turn off when reaching 40C

_(one could also use histeresys, but that has all sort of side effects on the noise profile under load with sharp fan speed fluctuation that are rather annoying)_

## Setting

Fan hardware on-off threshold is 27%.

### graph curve

1. 0% until 39C
2. a flat plateau speed 31% between 40 and 50C
3. Temperature is then linear to 100% at 95C.

### stop controls
1. I set the `stop %` at 30% (lower than the plateau speed 31%)
2. I set the `start %` at 35% (that should kick-in somewhere above 50C)

### what happens

That does not do at all what I expected. When temperature reaches 40, the fan kicks in at 35% (requested 31%), but for some reason, the controller appears to try to do PWM with a DC fan by rapid-pulsing it 35%-0% to achieve an average of 31% load instead of letting it settle down to 31% voltage. It does not try to do that with stop 0% (confusing), instead the fan runs at 35% constant (requested 31%, should not run at all thus). Overall I don't understand what the `stop %` parameter does. 

# Desired behavior

One can prevent fans short-cycling on-off, one way or another, whatever works :)

**Comment by Rem0o** [comment]
Start %: Minimum percent for the fan to kickstart from a dead stop (0 RPM)
Stop %: Percent under which the fan will stop spinning when it is running ( > 0 RPM )

Those 2 parameters describe the "physical" nature of the fan and should not be configured to achieve a specific cooling behavior.
You can use the automatic detection to set those up. With most fans, theses % are not the same for both parameters, stop % is lower.

Now for your actual use case.

If your fan ends up rapid-cycling, then you set your minimum temperature way too low. Ryzens do run hot on idle, that's just the nature of it. If your idle limit is 50, then be it, it's 50, not 39.

I would then do something like this to get passive cooling on idle:

Graph fan curve:
5c Hysteresis, 2-3 seconds response.

0-50 => 0 %
50-100 => 31% to a 100% linear curve

OR, a more fancy version

Mix Fan curve:

Mix Function: Min

FanCurve A: Target Fan curve:

Idle temp: 40
Load temp: 60,
Idle Fan Speed: 0,
Load Fan speed: 100%
Response time: 2 secs

Fan Curve B: Linear fan curve
Response time: 2 secs
Hysteresis: 5 deg
(60 deg, 31%)
(100 deg, 100%)

**Comment by Meeni-mc** [comment]
Thanks for adding the 'min' mixer, it's exactly what I missed in v61, and gets the job done nicely.
