### ISSUE TITLE
LIAN LI UNI FAN SL120 AND L-CONNECT 3

### ISSUE THREAD

**Issue by MARXTORO** [Rem0o/FanControl.Releases#1080]
**Describe the bug**
Fan Control is an amazing program, just have a few issues i would like help with: Lian Li SL120 fans do not show up on the app, i noticed what i think to be a plugin in the download folder called "Lian Li.Sensor" but i have no idea how to install the plugin. Also, my RX 6950 XT does not change with the curve. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No

**Relevant hardware specs and setup**
PC desktop AMD Ryzen 7 5800X, RX 6950 XT, MSI MPG B550 faming carbon WIFI. 3 SL120 fans and 3 fans connected directly to MB.

**Comment by Rem0o** [comment]
I have no official support for Lian-Li L-Connect stuff. 

For your AMD card, from the FAQ:

Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!

**Comment by Rem0o** [comment]
update on AMD cards, but still experimental: https://github.com/Rem0o/FanControl.ADLX

**Comment by EightB1ts** [comment]
Hi @MARXTORO !

I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi
Looking for beta testers. If you have time, please let me know if it works for you!
