### ISSUE TITLE
Allow Graph Curves to Take Other Fan Curves as Input

### ISSUE THREAD

**Issue by scolby33** [Rem0o/FanControl.Releases#1081]
I would like to use a modified sync curve from my GPU's stock fan. In pseudocode:

```
if gpu_fan_speed >= 40:
    return gpu_fan_speed
else:
    return 0
```

There's probably a few ways to do this (maybe I've missed one that's currently possible?), but the most flexible would allow using a graph curve where the x-axis is an input fan curve value and the y-axis is the output value.

**Comment by Rem0o** [comment]
If that's only applied to a single fan, you could set a start% on the control card of that fan to 40 and a stop % to 39, it will do the trick.

**Comment by scolby33** [comment]
Thank you. That works perfectly for my use case.
