### ISSUE TITLE
NVAPI_GPU_NOT_POWERED error

### ISSUE THREAD

**Issue by drittich** [Rem0o/FanControl.Releases#1085]
**Describe the bug**
An `NVAPI_GPU_NOT_POWERED` error was thrown.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9496681/log.txt)

**Relevant hardware specs and setup**
[hardware specs.txt](https://github.com/Rem0o/FanControl.Releases/files/9496697/hardware.specs.txt)

**Comment by Rem0o** [comment]
Care to elaborate? Do you have an Nvidia GPU? This exception might happen when you wake from sleep, but it won't break the app.

**Comment by drittich** [comment]
Yes, I do have an Nvidia GPU. There is no obvious problem resulting from the error, just a popup and then it logs it. Thought you might want to know about it so you could handle it rather alerting and logging the exception. If not, feel free to close.
