### ISSUE TITLE
update broke it

### ISSUE THREAD

**Issue by ELEMENTALFARTS** [Rem0o/FanControl.Releases#1089]
updated it, and it wont start because the side-by-side configuration is incorrect.
the event log said 
Activation context generation failed for "C:\Users\Joseph\Downloads\FanControl.Releases-master\FanControl.Releases-master\FanControl.exe".Error in manifest or policy file "C:\Users\Joseph\Downloads\FanControl.Releases-master\FanControl.Releases-master\FanControl.exe.Config" on line 0. Invalid Xml syntax.

on windows 11

deleted and reinstalled it and it worked. seems like there is something wrong with the updater.

**Comment by Rem0o** [comment]
That's odd.  Checked the content of the update, and the exe.config is there and it works properly when I test it.
