### ISSUE TITLE
No sensing HDD temp when connected to SAS controller

### ISSUE THREAD

**Issue by alex6dj** [Rem0o/FanControl.Releases#109]
The problem is with some disk connected to an LSI SAS adapter. They don't report temperature so I can't use to control the fan speed. I'm using SpeedFan app an it informs temperature over SMART and SCSI protocol, Hard Disk Sentinel app show temperature to, and windows over PowerShell support it to, so it can't a miss configuration.

Fan Control v60
Windows Server 2019
LSI Adapter, SAS2 2308

**Comment by Rem0o** [comment]
Well the driver I'm using doesn't support it, support would have to be added in,

See https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by alex6dj** [comment]
Hi again. The new plugins system indirectly solve my issue. Now I can develop a litle plugin to extract the temp fron sas disk maybe using powershell.

**Comment by alex6dj** [comment]
Hi just in case any one is yet interested in solve this issue I just publish a plugin with drives support in Microsoft Storage Space.

[FanControl.StorageSpacePlugin](https://github.com/QAppsSoft/FanControl.StorageSpacePlugin)

**Comment by fbcl00** [comment]
I'm not using microsoft storage spaces and still can't get any temp info from any hdds connected to my LSI SAS adapter. Has anyone come up with a solution?
