### ISSUE TITLE
Didn't detect an AX1200i fan.

### ISSUE THREAD

**Issue by GunnzAkimbo1974** [Rem0o/FanControl.Releases#1091]
It detected the other fans in the system except the PSU fan.

Is the app able to detect PSU fan through the corsair link process?

**Comment by Rem0o** [comment]
It might if you have this enabled:

![image](https://user-images.githubusercontent.com/14118956/189139110-fe4960a8-7150-4e4c-a4a2-81d953fff9bf.png)
