### ISSUE TITLE
GPU fans (not under control by fan-control) ramp to 100% seemingly randmonly

### ISSUE THREAD

**Issue by FlareFlo** [Rem0o/FanControl.Releases#1092]
**Describe the bug**
During regular operation, the GPU will ramp up to 100% RPM, even though it is not controlled by FanControl.
Logs:
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9542827/log.txt)
( Contains alot of nvidia API errors )

**Relevant hardware specs and setup**
[DxDiag.txt](https://github.com/Rem0o/FanControl.Releases/files/9542834/DxDiag.txt)
Setup:
<img width="1663" alt="FanControl_w4mORUOPRs" src="https://user-images.githubusercontent.com/78537307/189534504-b48df723-ebc7-4d17-b00b-2b168c297bbd.png">

**Comment by Rem0o** [comment]
Well, how is that a FanControl bug if the control is off?  If it's off, there is no command sent to the driver to control the fan.

**Comment by FlareFlo** [comment]
> Well, how is that a FanControl bug if the control is off? If it's off, there is no command sent to the driver to control the fan.

I have not had any issues with the fan ramping when it was off, and the errors in the log file pointing at an NVIDIA card made me confirm the suspicion. `NVAPI_NVIDIA_DEVICE_NOT_FOUND` and `NVAPI_ERROR` errors are not harmless from the sound of it.

**Comment by Rem0o** [comment]
That means it tries to detect a card from the api, and the API returns an error for whatever reason ( could be many things ).  Shouldn't make your fan ramp up or anything.

**Comment by Rem0o** [comment]
Do you have msi after burner running also? Make sure it's fan control is off.

**Comment by FlareFlo** [comment]
> Do you have msi after burner running also? Make sure it's fan control is off.

It is disabled

**Comment by TheFuchsen** [comment]
Hooking up to this, but how can I dissable MSI afterburner's fan control? Thought It was on by default always. (I'm undervolting my GPU with it)

**Comment by Rem0o** [comment]
Uncheck this: 
![image](https://user-images.githubusercontent.com/14118956/191267095-26332e70-ca5e-4c0d-85ff-614617607216.png)

**Comment by TheFuchsen** [comment]
Thank you!
