### ISSUE TITLE
Errors report. Buttons are unreachable.

### ISSUE THREAD

**Issue by severgun** [Rem0o/FanControl.Releases#1096]
**Describe the bug**
If I have a lot of missing hardware, errors report window is so big, so close buttons are unreachable and whole app blocked. 
Only TaskManager can close it.

Scrollbar would be nice
![EujondRHQh](https://user-images.githubusercontent.com/1197314/189728498-c75122c3-f40b-4c8b-8118-782ddba7a1be.png)

**Comment by Rem0o** [comment]
Can you at least press escape to get out?

**Comment by severgun** [comment]
Actually yes. But still, please, consider adding scrollable list. And width seems limited for no practical reason.

**Comment by Rem0o** [comment]
I will set a max height with a scrollbar.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/190427180-2f795a7c-f27e-4a3c-b8c6-d5ed67cae0f6.png)

**Comment by Rem0o** [comment]
See V128
