### ISSUE TITLE
I end up deleting all contents of fancontroller & sy0tgrw45yeaKPIHJN]'=

### ISSUE THREAD

**Issue by jekv2** [Rem0o/FanControl.Releases#1097]
**Describe the bug**
[A clear and concise description of what the bug is. Hardware support requests do NOT count as a bug. See README. Screenshots are worth a thousand words.]

Its using it with pc when it happens, you dont want words. This goddamn thing has mind of its own, have it set 50%, reboot 100%, open it rinse reapet, gotta watch configuration floater jump 1k times 50% fonfig, 100% config, back and forth

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
If you want a place to rage, this isn't the place. If you got a real issue, do like everyone else here and open a proper issue, with details of the problem/bug. I won't answer this.

Closing.
