### ISSUE TITLE
YOUR APP DOES WHAT EVER

### ISSUE THREAD

**Issue by jekv2** [Rem0o/FanControl.Releases#1099]
your app keeps  resetting the apps config, i end up deleting all and =starting over from scratch. IT HAS ITS OWN FUCKING MIND.......

**Comment by Rem0o** [comment]
If you want a place to rage, this isn't the place. If you got a real issue, do like everyone else here and open a proper issue, with details of the problem/bug. I won't answer this.

Closing.
