### ISSUE TITLE
Feature Request - Calibrate the speed curve of the PWM fan

### ISSUE THREAD

**Issue by DE8468** [Rem0o/FanControl.Releases#11]
The speed curve of each PWM fan is not the same
Assuming that the nominal minimum and maximum speeds of the two PWM fans of A and B are all the same 600-2000, then we set the fan speed to 70% at 70°C in the temperature control strategy, but through the monitoring software we may see that A 1200 rpm, B is 1500 rpm
Can you add the function of setting PWM curve calibration for each fan?
Thanks

**Comment by Rem0o** [comment]
I guess you found the offset option on the control cards? It's not exactly a calibration, but it should account for the RPM difference between fans.
