### ISSUE TITLE
GA z170-sli motherboard detects only one of 3 sys-fan controllers

### ISSUE THREAD

**Issue by MeeniMc** [Rem0o/FanControl.Releases#110]
Of 3 SYS fans, for some odd reason, only SYS3 is operated by fancontrol. The other fans have their speed reported, but are not controllable.

The motherboard comes with
1. 1 PWM CPU header (found and operable by fancontrol)
2. 1 DC CPU OPT header (found and operable by fancontrol)
3. 3x SYS fan headers (fans found, show RPM, SYS3 is operable by fancontrol)

In the POS software that comes with the motherboard (SIV), all 3 SYS fans can be assigned a custom curve and respond accordingly.
 
All fans are set to 'manual' in the BIOS, with the same curve. 

Let me know if more info is needed (like hwinfo logs or something)

**Comment by Rem0o** [comment]
Some SuperIO chips in LibrehardwareMonitor have limited support, I would guess yours is one of them. Probably missing the control register addresses for SYS1 and SYS2,

**Comment by sameSEA** [comment]
I have similar issue with asus b450-f
the sensor ite it8665e got 6 fans, but not all are shown.
Particularly last entry 6 is for AIO fan - not shown.

For example, I tried to control these fans with Argus monitor - all fans detected and can be controlled.

**Comment by Rem0o** [comment]
Updated LHM which seems to have added support for ITE chips better. See if that helps with version 71.

**Comment by MeeniMc** [comment]
No changes, thanks for updating anyway.
