### ISSUE TITLE
FanControl not detecting maximum RPM correctly

### ISSUE THREAD

**Issue by daideroon** [Rem0o/FanControl.Releases#1102]
Hello, I have had to disable Fan Control as recently it has stopped my fans running at anywhere near full speed. I only noticed as my GPU temps went higher than usual while gaming and have since located the cause of the extra heat.
Here is an example, my GPU has a AIO cooler with a fan, here is the RPM it is running at rest with Fan Control disabled:
![image](https://user-images.githubusercontent.com/57393484/190203308-d8fd8add-320e-45c5-b262-eb68deddf295.png)

However if I set the fan to Manual Control at 100% the RPM drops:
![image](https://user-images.githubusercontent.com/57393484/190203623-c07b56aa-32ea-42d6-988f-281bde9a70d4.png)

This is happening for all of my fans and CPU AIO Pump and is a recent problem, I only noticed it this week.

I have an ASUS ROG STRIX B550-F GAMING board. Armoury Crate is enabled (I use it for Aura Sync) but other than a really basic fan setting of 4 options I can see no fan controller software. AI Suite is disabled and that did use to have FanXpert on it but it has been disabled some time and this has only started happening recently.
In the BIOS all fan control methods are set to Auto.

Is there any testing I can perform to help locate the problem here?

**Comment by Rem0o** [comment]
Is your fanexpert/armory crate/asus software set to "Silent" somehow?  I've had report where that would hard limit the available range on fans.

**Comment by daideroon** [comment]
That is interesting, it is hard to tell what it was on but I have set it to "Normal" and even "Turbo" with no change.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/930

**Comment by daideroon** [comment]
Okay thanks, I will take a look later

**Comment by daideroon** [comment]
The problem in 930 was not the same as mine unfortunately (mine were not set to the same mode). However I have used the Armoury Crate removal tool to completely remove it, rebooted a couple of time and then gone through the FC assisted setup again and it seems to be working. I will monitor it for now.
Thanks for your help.
