### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by Michayah86** [Rem0o/FanControl.Releases#1103]
I have tried Windows removal tool and Advanced Uninstall PRO to uninstall FanControl. But it doesn't show up. I also cant find the install location nowhere (there might be a uninstaller there). I also tried to reinstall it, but that just starts the program.
How do I uninstall this program?

**Comment by Rem0o** [comment]
There is no installer and no uninstaller, it's a portable executable.

**Comment by Rem0o** [comment]
Yes.

**Comment by Impact123** [comment]
@Michayah86 If you configured it to start with windows you might want to remove the task from windows' task scheduler as well.
