### ISSUE TITLE
Just saw this in Autoruns. FanControl flagged via Bitdefender & VirusTotal.

### ISSUE THREAD

**Issue by Skichy** [Rem0o/FanControl.Releases#1104]
Hi all, Rem0o,

Just came across these two flags regarding FanControl and just wanted to let you know and to make sure if this is serious or just a false positive.
My system has started to show signs of issues so I want to make sure it has nothing to do with this.

Many thanks.

VirusTotal Link.

https://www.virustotal.com/gui/file/11bd2c9f9e2397c9a16e0990e4ed2cf0679498fe0fd418a3dfdac60b5c160ee5/detection

![FanControl Zip Flagged as Hack tool](https://user-images.githubusercontent.com/113623422/190453191-ef7d7c18-7ee3-4aed-a256-8bbda4316ade.png)

**Comment by Rem0o** [comment]
It flagged WinRing0.sys.  It's a false positive.
