### ISSUE TITLE
Feature Suggestion: Bézier Curves

### ISSUE THREAD

**Issue by KindarConrath** [Rem0o/FanControl.Releases#1105]
I am not certain of how helpful it would be, but I wanted to make the suggestion that instead of linear ramps between points, 
you could create a Bézier curve with handles. This would allow for a smoother graph without having to make many points.

Admittedly it could also result in some strange fan curves.

**Comment by Rem0o** [comment]
Keep in mind in the end there is only 256 possible values for a fan.  Having a curve that smooth would not change much. Also, would have to compute the value with a bezier function for every temp change, which would be more compute, again, for not much.

**Comment by KindarConrath** [comment]
For the second point, I assumed that you would save the set of points so you wouldn't have to calculate it each time you would just look up in an array. For the first point I didn't realize there were only 256 possible settings so you're right the curve doesn't make a lot of sense

**Comment by Rem0o** [comment]
@KindarConrath  Yes I would cache a lookup table or something, but the main idea is that it's added complexity, for no real benefit in practice.
