### ISSUE TITLE
Feature request - do not initialize "average" blocks with zeroes

### ISSUE THREAD

**Issue by ItsMeAubey** [Rem0o/FanControl.Releases#1109]
I am using FanControl to adjust the speed of my radiator fans automatically. 

I have an ambient temperature sensor connected to a motherboard header. The motherboard reports only integers to HWInfo - 20c, 21c, etc. I use that ambient temperature sensor and my coolant sensor, along with a mix block in subtract mode, to create a "delta" temperature:

![image](https://user-images.githubusercontent.com/35206674/190830196-a585f252-c18f-497f-9128-8a8f8e285972.png)

I then pass the resulting "delta" temperature into an auto fan control block which modulates my fans to keep my coolant temperature at a maximum of 6 degrees over ambient temperature:

![image](https://user-images.githubusercontent.com/35206674/190830228-79d662f5-2b1c-476b-8a90-09562f8713df.png)

My problem happens when the temperature in the room is very close to the next whole degree. As my motherboard reports only whole digits to HWInfo, a room temperature of 21.975 celsius is reported as 21c. If the temperature increases by a tiny amount (or just measurement error by a fraction of a degree), that 21c reading will increase to 22c, increasing my "delta" temperature by a whole degree in an instant. This jump means I need to use a 2-3c deadband in my auto fan curve block. 

My solution to this issue is to use a time average block with a very long setting (5 minutes) to average out the ambient temperature sensor readings. When I do this, everything works perfectly fine. 

The issue is that whenever I refresh sensors, or start up my PC, it seems that the "time average" block is initialized with a value of zero. I cannot see how the function is implemented, but the end result is that my temperature delta reading is thrown waaay off for 5 minutes until the average block catches up. For those five minutes, my PC fans run at full blast. 

My feature request is that the time average block fully initializes itself with the current (or first non-zero) sensor reading instead of zero, making the block immediately useful when FanControl is started or sensors are refreshed. 

Thank you for this wonderful software. You have freed me from a lifetime of fan noise and ICUE hogging huge amounts of CPU/RAM 24/7.

**Comment by Rem0o** [comment]
There is a whole lot going on with your config.

The time average sensor will first be read with the first value it picks up, not from 0 or anything like that.  However, the value you average out is let say "6" from the first iteration, you'll get stuck with that value for a whole 5 min before it gets averaged out.

![image](https://user-images.githubusercontent.com/14118956/190869676-f9f749dd-e350-4e10-9f7d-750df3a8f192.png)

**Comment by ItsMeAubey** [comment]
I am using the HWINFO plugin to read my sensors as LHM does not seem to pick them up. HWInfo is started for easily a full 10 seconds before FanControl starts at boot, and the average block is still reset to zero when hitting "refresh sensors" with HWInfo fully up and running. 

Perhaps the hwinfo plugin is outputting zero as a default value? 

Maybe the easy and universal solution is to just add a "wait $X seconds before initializing blocks" option to the burger menu, and just sleep($X) or something before the blocks actually receive inputs? Would be useful to fix weird plugin behaviour in general. 

Please let me know if there are any logs, etc that I could provide to make your work easier. 

Thanks again!

**Comment by Rem0o** [comment]
@ItsMeAubey  could you catch a screenshot where we see the "0" for the timeaverage and whatever value it is supposed to be at the same time?

**Comment by ItsMeAubey** [comment]
@Rem0o 

![image](https://user-images.githubusercontent.com/35206674/190876952-712a6eac-e3dc-4091-899a-d79a73649314.png)

All I did to achieve this is click "refresh sensors detection"

**Comment by Rem0o** [comment]
But what's "Radiator intake air temp" ?  I tried to reproduce the issue, but with a regular sensor, it works as expected.

**Comment by ItsMeAubey** [comment]
![image](https://user-images.githubusercontent.com/35206674/190877150-496bf3db-f961-4086-b690-8f72de9ad926.png)

![image](https://user-images.githubusercontent.com/35206674/190877156-f491f4c4-3773-47ed-9546-825b4929be7f.png)

"radiator air intake temp" is a HWinfo-plugin-provided temperature sensor. It is not from a mix. it is the raw original sensor value from the plugin. The zero issue happens in just this state, with zero mixes: 

![image](https://user-images.githubusercontent.com/35206674/190877225-79dd9059-9021-471a-a59d-2b1c22bd8078.png)


You may need to refresh sensors more than once. It happens roughly 50% of the time for me.

**Comment by Rem0o** [comment]
Found the culprit. It has to do with plugins having no guarantee of having their sensors initialized with a valid value. HWInfo plugin doesn't initialize with a value in its sensors. It waits for the first clock update to do so.

My solution will be to call a plugin update immediately after the plugin initialize, to make sure it is in a proper state of out the box.

**Comment by ItsMeAubey** [comment]
Fantastic. Thank you so much!

**Comment by ItsMeAubey** [comment]
It seems that v129 contains the fix for this - it doesn't seem to be happening anymore?

**Comment by Rem0o** [comment]
You are correct. Pushed it in.
