### ISSUE TITLE
Webroot antivirus threat detected after update to V128

### ISSUE THREAD

**Issue by MetalHeartZ** [Rem0o/FanControl.Releases#1111]
![Screenshot 2022-09-17 145834](https://user-images.githubusercontent.com/75481922/190853303-1d9df278-e229-4575-b486-0c16af294c48.png)

**Comment by Rem0o** [comment]
The dll is opensource, feel free to inspect the source code.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by mekwall** [comment]
[Webroot doesn't detect anything according to Virus Total](https://www.virustotal.com/gui/file/d46361473aed1efe50c90c3036cf357a213b4e0bad88826bfc862782d0e1732c). You might be infected by a virus that is hooking into random DLLs because this DLL is totally safe.

**Comment by mreidMR2** [comment]
I got the same WebRoot threat popup after updating to FanControl V130 from V127.  WebRoot automatically quarantined 
LibreHardwareMonitor.dll from the FanControl folder.  I went to the LibreHardwareMonitor github repo, downloaded latest zip.  I then extracted just LibreHardwareMonitor.dll (version 0.9.1.0  | ‎September ‎14, ‎2022, ‏‎11:47:52 AM) to a temp folder and scanned with VirusTotal.  No vendors, including WebRoot, reported a virus.  Windows 10 shows the previous DLL version was timestamped 8/22/2022 1:29 PM. So I stopped FanControl, moved the new DLL to FanControl folder and restarted FanControl.  This time WebRoot didn't flag it.  Did a manual WebRoot scan, still no threat warning.  My conclusion is that the version of LibreHardwareMonitor.dll released with FanControl V127 and earlier are OK with WebRoot, but not the FanControl versions after V127 including V130.
![wr](https://user-images.githubusercontent.com/114368676/192174023-118cca4d-3315-4e61-879f-1bed50e3bec3.jpg)

**Comment by Rem0o** [comment]
I actually compile the master branch of LHM with each release.  Dotpeek it if you have suspicions. No idea why it got flagged this time.

**Comment by mreidMR2** [comment]
Nah, the simplest solution for me is to not accept anymore updates, just full re-install after x months with a VirusTotal scan first.  I'm a Java/Python/Delphi developer and don't need or want a .NET decompile tool installed just to validate someone else's free and useful utility app.
