### ISSUE TITLE
V128 create duplicate control cards + sensors

### ISSUE THREAD

**Issue by DfrostX** [Rem0o/FanControl.Releases#1112]
Hi Rémi,

Something seems to have changed between 127 and 128 that has created some issues to my config. After updating, the program is duplicating some control cards and sensors (from HWinfo).

If I discard change upon starting Fan Control. my config will load properly, until the next time I close/ start Fan Control.

I have saved the "new" Json file updated by v128 and attached both files (before and after updating from 127 to 128) to this report. You can clearly see the redundant entries starting at line 435 of the v128 file and the sensor count somehow jumping from 39 to 85...

I will roll back to v127 for the time being.

[Json files.zip](https://github.com/Rem0o/FanControl.Releases/files/9591516/Json.files.zip)

**Comment by dabm-git** [comment]
Related: #1110

**Comment by Rem0o** [comment]
Any log.txt?

**Comment by DfrostX** [comment]
None got created. Is there a way to trigger a debug mode?

**Comment by Rem0o** [comment]
Found the bug.

**Comment by Rem0o** [comment]
[Test.zip](https://github.com/Rem0o/FanControl.Releases/files/9592408/Test.zip)

Replace those 2 files on V128 and tell me if it fixes it.

**Comment by DfrostX** [comment]
> [Test.zip](https://github.com/Rem0o/FanControl.Releases/files/9592408/Test.zip)
> 
> Replace those 2 files on V128 and tell me if it fixes it.

Worked like a charm, thanks!

**Comment by Rem0o** [comment]
@DfrostX  will publish this quickly in the next release.

**Comment by Rem0o** [comment]
@AliveNoMore  you had to replace the files, not use only those 2.

**Comment by DfrostX** [comment]
Officially fixed thru v129. Closing
