### ISSUE TITLE
Last version v128 is broken

### ISSUE THREAD

**Issue by Kuro-23** [Rem0o/FanControl.Releases#1113]
FanControl was reporting wrong case temperature (34c instead real temp was 47c) ad my pc overheated... There are many duplicated control cards and sensors poping at startup after last update and all of them does not exist.
I'm using FanControl since 6 months now and I never changed config file and this is my first bug.

Had to rollback to v122 to be sure my pc does not catch fire.

**Comment by DfrostX** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1112

**Comment by Huntakillaz** [comment]
Also I have .Net 6.0.9 but it doesn't seem to want to use it asking me to get 6.0.8 installed
