### ISSUE TITLE
net 6.0 build doesn't auto update

### ISSUE THREAD

**Issue by tormento** [Rem0o/FanControl.Releases#1114]
I have tried net 6.0 build since v128 but now that v129 is out, it doesn't automatically update.

Is it fixable?

**Comment by Rem0o** [comment]
OTA is still 4.8 only. Updates won't work for 6.0.

**Comment by tormento** [comment]
I noticed that 😜

Do you plan to support or is it a long way to go?

**Comment by Rem0o** [comment]
Will do the transition at some point.

**Comment by mattzink** [comment]
Bummer, the .net 6.0 version runs wayyy better on my machine
