### ISSUE TITLE
missing speed and control sensors in build 129

### ISSUE THREAD

**Issue by goathens** [Rem0o/FanControl.Releases#1115]
Build 128 reports the following errors every time I restart.  Same error reports when I "refresh sensors"
![image](https://user-images.githubusercontent.com/66317503/190929642-7569ca32-64a2-4996-ba52-c63ffc0b36cb.png)

I use FanControl to control my cpu and case fans, and use fan sensors for my amd gpu. I *think* everything is still working ok.

**Comment by Rem0o** [comment]
Update to V129 and see if your problem still occurs.

**Comment by goathens** [comment]
It continues, unfortunately. Also tried a power cycle.

**Comment by goathens** [comment]
I also tried it with build 127 and got the error, so I can't say for sure which version started this problem.  Changed the title for relevance.

**Comment by IamGimli** [comment]
I'm having the same issue and the following is in the FanControl error log:

`2022-09-20 08:45:40: System.IO.FileNotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()`

**Comment by goathens** [comment]
@Rem0o the alert fires whenever the application launches and whenever the PC wakes from sleep, and I think that it will go away if I "save" the userconfig of FanControl.  However, I'd like to know how to trigger FanControl to look for these fan sensors in future versions of the application, when the bug is fixed?

I'm saving a copy of UserConfig.json for later, just so I can re-try on future versions.
