### ISSUE TITLE
[Request] Update LibreHardwareMonitor 0.9.0

### ISSUE THREAD

**Issue by Kodikuu** [Rem0o/FanControl.Releases#1117]
0.9.0 (and 0.9.1) bring significant amount of new hardware support

**Comment by Rem0o** [comment]
It's up to date with v129.

**Comment by Kodikuu** [comment]
Ah, I thought you were using your fork, nevermind then

**Comment by Rem0o** [comment]
Forgot I had a fork. Will delete it. I'm currently following the master branch.
