### ISSUE TITLE
[Feature Request]: Ability to load/change profiles via command line

### ISSUE THREAD

**Issue by t3t3** [Rem0o/FanControl.Releases#112]
As the title says. This would be really great for event/time based scheduling on i.e. remote/headless machines; I'd even use this on my main Workstation to tailor fan & noise for tasks which would ideally be accompanied by heavy/adaptive/low cooling of either CPU or GPUs or both (tasks that particular needs i know of beforehand... i.e. rendering vs. video cutting vs gaming, etc.)

I admire FanControl a lot for already allowing this (sort of) by scripted replacement of the .json file.

All in all I'd rate FanControl as one of the best tools of this sort, of many I've tried so far (if not _the_ best); keep it coming ;)

**Comment by asdsadsaasd12312132** [comment]
I was going to suggest this a long time ago but I invented a workaround. On launch, FanControl runs the json file matching the last used profile, so all you have to do is close FanControl, rename the profile you want to use to the last used profile, and launch FanControl. I have automated this with AHK scripts. I always use a profile called Default.json and I swap my actual profiles with that. Example of running FanControl using the Idle (target).json profile.

```
Process, Close, FanControl.exe
Process, WaitClose, FanControl.exe
FileCopy, C:\My files\Portable programs\Auto backup\FanControl\Idle (target).json, C:\My files\Portable programs\Auto backup\FanControl\Default.json, 1
Run, C:\My files\Portable programs\Auto backup\FanControl\FanControl.exe, C:\My files\Portable programs\Auto backup\FanControl,,hide
```

Closing the the process results in orphanned tray icons, so this function can be used to refresh the tray icons:

```
Tray_Refresh() ;call it with this

Tray_Refresh() {
/*		
	Remove dead icons from the tray menu
	https://www.autohotkey.com/boards/viewtopic.php?f=76&t=19832&start=20
*/
	WM_MOUSEMOVE := 0x200
	detectHiddenWin := A_DetectHiddenWindows
	DetectHiddenWindows, On

	allTitles := ["ahk_class Shell_TrayWnd"
			, "ahk_class NotifyIconOverflowWindow"]
	allControls := ["ToolbarWindow321"
				,"ToolbarWindow322"
				,"ToolbarWindow323"
				,"ToolbarWindow324"
				,"ToolbarWindow325"
				,"ToolbarWindow326"]
	allIconSizes := [24,32]

	for id, title in allTitles {
		for id, controlName in allControls
		{
			for id, iconSize in allIconSizes
			{
				ControlGetPos, xTray,yTray,wdTray,htTray,% controlName,% title
				y := htTray - 10
				While (y > 0)
				{
					x := wdTray - iconSize/2
					While (x > 0)
					{
						point := (y << 16) + x
						PostMessage,% WM_MOUSEMOVE, 0,% point,% controlName,% title
						x -= iconSize/2
					}
					y -= iconSize/2
				}
			}
		}
	}

	DetectHiddenWindows, %detectHiddenWin%
}
```
Alternatively,[ LP#TrayIconBuster](https://www.codeproject.com/Articles/19620/LP-TrayIconBuster) can be used, which automatically refreshes the tray every 5 seconds. The first option has the problem of being unable to refresh the tray icons if you have not clicked the arrow to show hidden icons at least once after booting Windows.

![image](https://user-images.githubusercontent.com/51249734/104177351-b8dabf00-545c-11eb-85b4-0a1af15394bc.png)

This option does not have that problem.

**Comment by Rem0o** [comment]
@asdsadsaasd12312132  to add to your post,  the last used profile is actually cached inside the "CACHE" file. Look it up.

**Comment by asdsadsaasd12312132** [comment]
> @asdsadsaasd12312132 to add to your post, the last used profile is actually cached inside the "CACHE" file. Look it up.

I knew about that but for some reason when I did my original testing I did not think to close FanControl, edit the cache file then launch FanControl. I just tried to edit the file with FanControl open. I will implement this method I suppose.

**Comment by asdsadsaasd12312132** [comment]
New solution: edit the last profile used in the CACHE file. It is required that you download and place this [library ](https://github.com/hi5/TF#TF_ReplaceLine) in the same folder as your script.

```
#Include %A_ScriptDir%\tf.ahk

Profile_to_use = "CurrentConfigFileName": "\"test.json\"",

Process, Close, FanControl.exe
Process, WaitClose, FanControl.exe
TF_ReplaceLine("!C:\My files\Portable programs\Auto backup\FanControl\CACHE", 2, 2, Profile_to_use)
Run, C:\My files\Portable programs\Auto backup\FanControl\FanControl.exe, C:\My files\Portable programs\Auto backup\FanControl,,hide
```

**Comment by t3t3** [comment]
Yeah, I have already done something similar using AHK and modifying the cache file via basic DOS scripting; I did just write an AHK to actually click on exit in the tray icon menu, but it did fail quite often; killing FanControl + IconBuster seems to be a better way, at least for the time being.

PS: Is it just me, or is neither the CACHE file nor the *.json profile really "well-formed" JSON? Imo the acutal JSON is jast a fully escaped json-formatted string within another JSON object (means it needs to have all line endings and quotes escaped in plain text). I mean, technically spoken it is JSON, but because of that "double stacking" it can't be edited quite comfy...

**Comment by trankillity** [comment]
The solutions are pretty good, however I would still like to request that FanControl take a command line parameter of the JSON profile to load. Should be pretty simple functionality, and would allow for different profiles in different scenarios without needing the UI to load them.

**Comment by Rem0o** [comment]
Do you mean when launching the app or while the app is running? Those are two very different.

**Comment by trankillity** [comment]
Both would be great, but understand that startup command line is likely to be easiest to implement.

**Comment by Rem0o** [comment]
I will look into command line args at startup.

**Comment by Rem0o** [comment]
See V81.

**Comment by zdunex25** [comment]
Any future plans to include support for command control while app is running as well? Tying up GPU profile (in my case) to selected games would be way more handy.
