### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by egefeyzioglu** [Rem0o/FanControl.Releases#1121]
Hi,
README.md references opening a pull request so I assume contributions are welcome, but I wasn't able to find any source code anywhere. Is the source code available for this project/are contributions welcome?

**Comment by Rem0o** [comment]
Not exactly, please read the "Issues and hardware compatibility" section carefully.
Links to the relevant source code are there.

**Comment by egefeyzioglu** [comment]
I was intending to add a "do you want to save" prompt when the user tries to exit without saving. This could only be added to your project, not any of the backend libraries.

**Comment by Rem0o** [comment]
There is already exactly that?
![image](https://user-images.githubusercontent.com/14118956/191881767-95c2a755-77b8-4f27-a551-b3cdbdd4655d.png)

**Comment by egefeyzioglu** [comment]
Oh ok great sorry it didn't use to a while ago but I guess it's been added in the meantime. Thanks!
