### ISSUE TITLE
net 6.0.9 is installed, auto-start is not working

### ISSUE THREAD

**Issue by 1LUC1D4710N** [Rem0o/FanControl.Releases#1122]
net 6.0.9 is installed, but I have x86 and x64, could this be reason auto-start not working?
![Screenshot 2022-09-22 105230](https://user-images.githubusercontent.com/7138247/191689723-307ae928-754c-46f5-ae6b-0b5e5cc1beff.png)

**Comment by 1LUC1D4710N** [comment]
I'll try FanControl 129 net 4.8

**Comment by Huntakillaz** [comment]
So it's weird, I ran the update file from the directory manually, and it downloaded new files and works fine now, which means it's missing files in the zip download.
I could be wrong, but it's what noticed when I had downloaded 128 and got the same error.

**Comment by Rem0o** [comment]
^ Update file will download 4.8.

**Comment by 1LUC1D4710N** [comment]
Yes, I started completely over with nothing and tried FanControl net 6.0, this error comes after fresh start of device or from reboot.

I don't know how else to explain, but yes, sticking with net 4.8 for now.
