### ISSUE TITLE
 Happens every second -> NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR

### ISSUE THREAD

**Issue by mreidMR2** [Rem0o/FanControl.Releases#1132]
FanControl V130 appears to be working (see screenshot.jpg) but the log.txt is 300MB where the below error happens every second starting in August.  I zipped the log.txt due to size.  See log.txt.zip 

I setup FanControl months ago and haven't made any changes since it does what I want/need, just been updating.  I'm disappointed that I wasn't notified that errors were happening.  It seems that in your try...catch blocks you could implement error counters and alert the user on startup or an icon on the UI.  It's ridiculous to have a 300MB error log.  If I didn't have the Webroot threat popup, I would have never known of the errors.  Does the log.txt have a max size limit or would it append forever?

8/27/2022 2:18:47 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR
   at FanControl.Models.NVApiControlSensor.HandleException(NVIDIAApiException exception)
   at FanControl.Models.NVApiControlSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Relevant hardware specs and setup**
See video.JPG and hardware.txt
[hardware.txt](https://github.com/Rem0o/FanControl.Releases/files/9644440/hardware.txt)
![screenshot](https://user-images.githubusercontent.com/114368676/192230568-55b03f54-c74a-4013-a730-fe8ef00ee11b.jpg)
![video](https://user-images.githubusercontent.com/114368676/192230615-e701ad39-4dc9-4234-bc8f-9ef92bec15fb.jpg)
[log.txt.zip](https://github.com/Rem0o/FanControl.Releases/files/9644442/log.txt.zip)

**Comment by Rem0o** [comment]
Something is definitely wrong between the NvApiWrapper implementation and your system. I would recommand trying the LHM one instead. You'll have to reapply the gpu temp to your curve. 

![image](https://user-images.githubusercontent.com/14118956/192287239-2d346c06-df1e-4df6-80ba-81cbda5fac41.png)

**Comment by mreidMR2** [comment]
I did as you suggested and now only use LHM.  No errors written to your all purpose text log after many tests that use the proprietary Nvidia GEFORCE Experience stuff like video capture and filters.  

It seems, however, that your program may have a bug.  In the zipped log.txt I sent, the first exception on 8/26/2022 is:
8/26/2022 11:48:13 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND

It appears that you tried to get an instance or handle to an NVIDIA_DEVICE and were told that no NVIDIA_DEVICES were found.
Yet you continued to referenced it by FanControl.Models.NVApiControlSensor.Update().  Maybe I'm wrong but that's what appears to happen for 298MB worth of errors.

Two suggestions:
1) Let the user know errors are happening.  This is fundamental to exception handling. It shouldn't be a secret. Currently, you simply use
	try
	{
	    FunctionThatMightThrow();
	}
	catch (Exception ex)
	{
	    SilentlyWriteToTextLog(ex)
	}
and expect the user to use a menu option to view errors on a background utility app that is probably treated as set and forget.

2) Limit max size that log can reach.  300MB is ridiculous.

Anyway, appreciate the good free program that does what a fan controller should do in an attractive and functional UI.

**Comment by Rem0o** [comment]
@mreidMR2 
Seems like the API returns a device, but when calling methods with that device the NvAPI returns NVAPI_NVIDIA_DEVICE_NOT_FOUND. 

Will add a check in the initialization process of the NvApi stuff to make sure that the "update" portion works, and fail early before adding it to the main update loop, causing your 300mb of logs.

Will also look at some way to warn the user if the log file gets out of hands. Might split it after 10 mb worth of logs, to keep it manageable, but also with a user visible warning.

**Comment by mreidMR2** [comment]
Sounds reasonable, thanks for looking into the issue.  For the most part, this is a nicely thought out and presented utility, keep up the good work.
