### ISSUE TITLE
GIGABYTE X570 AORUS MASTER (ITE IT8792E) controls not detected

### ISSUE THREAD

**Issue by St0RM53** [Rem0o/FanControl.Releases#1133]
This motherboard has 2 ITE controllers, the secondary one that controls System 4, 5, and 6 headers is not detected.
Please fix.

**Comment by Rem0o** [comment]
See https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/search?q=IT8792E&type=issues

Known issue, no fix yet.

**Comment by St0RM53** [comment]
yeah, i only found later; shame:/
