### ISSUE TITLE
Feature Request: Clock Speed / Frequency sources for all curve types

### ISSUE THREAD

**Issue by RaphaelTarita** [Rem0o/FanControl.Releases#1134]
In regards to the new AMD processors (7000) boost behaviour, regular temperature curves don't make a lot of sense. The processor will boost to 95°C and then try to hold that temperature. Meaning, if you have a fan curve ramping up to 100% at TjMax, it will run at 100% all the time (which means a lot of noise) and the processor will keep boosting (which means a lot of heat produced and electricity used).

A possible approach for fan curves on that new boosting behaviour would be to apply an inverted curve to the CPU's clock frequency. This way, the fans will ramp down if the CPU is able to hold its frequency, and will ramp up if the CPU stops boosting due to temperature limits.

For that purpose, we'd need a kind of "frequency sensor" that can be chosen as the source for a fan curve. This would also be a quite interesting feature in regards to the "Mix" curve type, which could combine a temperature curve and a frequency curve.

I did not find this kind of functionality already existing in FanControl, so I'd like to propose this as a feature.

**Comment by Rem0o** [comment]
That kinda works for stable, full load scenarios, but what about normal load and or idle scenarios, where the cpu will live anywhere between 1 ghz and like 5?  Also, the frequency will be different from core to core, and can be all over the place ( up, down, up down ) . The idea ain't crazy, but I'm not sure it would work great in practice as described.

**Comment by RaphaelTarita** [comment]
well, yes, this is all true, and I don't think a frequency curve alone will do the job. I'm just thinking that with the new boosting behaviour, frequency could be _added_ as a new information to the full curve component, alongside temp sources. FanControl seems to be very good and capable at working with and transforming curves and sensors, so I'm sure one could craft a quite efficient overall CPU curve with that.

Regarding different frequencies per core, I could imagine it working similar to the different core temperatures currently, where you have the choice between a bunch of different sensors on the CPU (for all the cores) and also an all-core average

Regarding erratic frequency changes, yes, that could be a problem, but I think with proper hysteresis settings and also by mixing with temperature curves, this could be overcome as well.

In any case, more benchmarks (also low-load scenarios) as well as benchmarks of the eco mode are probably needed here to be certain how one could exactly utilize frequency data in a fan curve.

**Comment by gotmachine** [comment]
I think in general, exposing all available sensor data would be a good move.

I agree that frequency is extremely jittery and more importantly doesn't reflect accurately actual CPU load or thermal output
However, package power is basically the most accurate information one can get about instantaneous thermal output. It is also a jittery sensor by nature, but it's nothing that can't be solved with a bit of fine tuning with the various sensor data manipulation tools of FanControl.
