### ISSUE TITLE
Missing 4th fan header on EVGA 3080 FTW3

### ISSUE THREAD

**Issue by GuilhermeReda** [Rem0o/FanControl.Releases#1137]
Hello,

I have recently replaced my GPU fans for a waterblock, and since my motherboard has few FAN headers, I decided to use the one available in the side of the GPU for the radiator fans. [Image](https://images.idgesg.net/images/article/2020/10/evga-rtx-3080-ftw3-ultra-8-100860532-large.jpg?auto=webp&quality=85,70)
But, this fan header is not detectable in the FanControl software, but is configurable in EVGA Precision X1ᐪᔿ.
I would be nice to be able to control all fans from one place.

Thank you.

**Comment by Rem0o** [comment]
Sadly, I don't think these headers are usable by third-party.

Also, see hardware compatilibty section of the readme.
