### ISSUE TITLE
About ASUS B450 model motherboard can not identify the case fan problem

### ISSUE THREAD

**Issue by Heaven98op** [Rem0o/FanControl.Releases#1140]
When I use FanControl any version, I found that ASUS B450 motherboard is unable to set up a fan to the chassis, I can really identify in other sensor software, in order to determine this problem, I visited many forums, indeed ASUS B450 motherboard everyone can not identify the chassis fan, attached pictures. 
![Snipaste_2022-09-28_21-47-25](https://user-images.githubusercontent.com/78060099/192842278-d5aecd4f-2cb2-44a2-94b4-1b4d942b6723.png)
![Snipaste_2022-09-28_21-48-32](https://user-images.githubusercontent.com/78060099/192842288-d1c8bce5-e573-45a6-aa57-24bd0c637fec.png)

**Comment by Rem0o** [comment]
Please see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.
