### ISSUE TITLE
Fan control being overridden by an external source, though no other program is using WinRing0.

### ISSUE THREAD

**Issue by Itaxhix** [Rem0o/FanControl.Releases#1141]
As said in the title, I checked using resource monitor and only FanControl was running WinRing0, I don't have any applications that control the fan and my bios also doesn't have the fan speed settings. I'm wondering if it's just a bug where the reading for an external software might just be wrong (or maybe it counts its own control as overriding itself???).

This bug along with my fans going crazy until I restart the software got me confused for a few hours figuring out what the problem was until I realized that turning off force apply still lets me control the fan though the question mark is still there. Whereas the fan going crazy bug is just an issue of its own.

**Comment by DfrostX** [comment]
Maybe related to this:

https://github.com/Rem0o/FanControl.Releases/issues/988

**Comment by Marius8** [comment]
if you are using a Gigabyte mainboard, the issue is most likely related to the current inablility of a library FanControl uses, to access a control IC, gigabyte uses https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/731

**Comment by Itaxhix** [comment]
Problem was that my stock gpu fans do not allow the fan speed to go under 25% (fan curve had points under 25%, and that is when the "?" comes up), not a problem with the software or ui.
