### ISSUE TITLE
Fan doesn't start sometimes - gets stuck at stopped state

### ISSUE THREAD

**Issue by panoskj** [Rem0o/FanControl.Releases#1142]
I have a few fan controls. One of them is set to start at 21% and stop at 18% of the assigned curve. While it does stop and start as expected most of the times, sometimes it will fail to start. If it fails to start, it remains stuck until I disable the fan control and enable it again (using the green toggle). I tried "Manual control" and "Force apply" options but the fan remained stuck. In this state, the fan control displays 0% and 0RPM while the curve may display up to 100%. Other fan controls using the same curve work as expected. I have been using the software for a couple of days so I am not sure what triggers this bug.

One thing I can think of that might be related, is that the automatic start threshold detection failed for this fan: it determined 66% was the threshold while it should have be 21%. I know this because a) I have two more of the same fan and their start threshold is also 21% and b) I used manual mode to verify that the fan does indeed start at 21%. But this fan seems to take longer to start: it doesn't start instantly when you apply 21% to it, but a few moments later.

Let me know if there is something I can do to debug this issue.

_Edit: I am not using any other software that could interfere with fans. I use MSI Afterburner but its fan control settings are completely disabled. In BIOS, I have disabled smart fan control and set the fans to work at 100%._

**Relevant hardware specs and setup**
OS: Windows 11
Motherboard: Gigabyte Z690 UD

**Comment by panoskj** [comment]
It works properly if I set the start threshold to 66% after all.

**Comment by Rem0o** [comment]
Yes it can run between start and stop.

Start% is meant as a "kickstart" to get it going, then it can go down up to the stop%. You should leave it like what the software detected.

**Comment by panoskj** [comment]
@Rem0o thanks for the advice.

Meanwhile I encountered the same problem with another fan that the software itself had detected as starting at 21%. I had to raise it to about 40% to get it started. So the automatic detection doesn't guarantee that a fan won't ever get stuck.

I tried setting the fan back to starting at 21% after this happened and it wouldn't get stuck again. So it needs more speed to start very rarely and that's why the automatic detection couldn't help.

But it feels wrong to always start the fans at 40% or 60% just to lower them down to 20%. It takes a few seconds too because of the step down rate.

My ideas to improve this situation:
1. Add an option to show a notification if a fan isn't starting at its start speed.
2. Add an option to gradually apply more speed until the fan starts. It doesn't matter if it takes some extra seconds to start, as long as it doesn't get stuck. You could make the steps exponential instead of linear to make this process faster (e.g. 5, 10, 20, 40 instead of 5, 10, 15, 20).
3. Add an option to temporarily ignore the step down rate when starting a fan.

By options I mean checkboxes in the fan controls, like "Force Apply" for example.

**Comment by Rem0o** [comment]
@panoskj  the fact your fans don't always need the same % (by a long shot at that, 21% to 60% is quite a difference) to start is quite unusual. You are the first ever to report such a thing, so congrats!

In that scenario, indeed the automatic detection is worth nothing. In fact, the whole start/stop% system doesn't work in this case, except if you put the start% at the maximum of the observed values, like you did at 60%. 

I don't think the app needs even more options.  What doesn't work right now is that you can get in a stuck state, even if the requested % is a 100%.  I will add a timeout to the start% logic, so that it will exit that logic if no start was detected after let say 5 seconds.
