### ISSUE TITLE
missing Sanity check on Sync curve

### ISSUE THREAD

**Issue by Marius8** [Rem0o/FanControl.Releases#1144]
When selecting a Curve for a Control, youcan Select the Sync Curve on the Control, that is the source for the Sync Curve.
Same, when selecting the Curve first, the Controls where the Sync is selected as a Curve can still be chosen as the 'Selected control'.
https://prnt.sc/KhiLAy1Dttc4
https://prnt.sc/D8nqXvOqPX0v

**Comment by Rem0o** [comment]
But can you actually? It’s in the drop down, but it shouldn’t be selectable.

**Comment by Marius8** [comment]
it can be selected both ways, at least on V130.
was quite surprised, when my fans suddenly shot up 100%

**Comment by Rem0o** [comment]
Just verified, you are right it's possible, but saving that config will fail. Will implement a loop detection.
