### ISSUE TITLE
Commander Pro Temp sensor accuracy

### ISSUE THREAD

**Issue by kick81** [Rem0o/FanControl.Releases#1145]
Is it possible to adjust the accuracy of the temp sensors attached to Commander pro?

I´m trying to make a delta temp curve using 2 different t-probes (ambient and coolant) but the temperatures are not accurate.
For example temp in idle marks 28c and when the water is warming up goes directly to 30 and if water continues warming, jumps directly to 33 (29c / 31c /32c are missing)

Temps readings are 23-25-28-30-33-35-38-40-43, there are value jumps and no decimals at all.

I have 4 temp sensors connected to commander pro

   +Two g1/4 sensors for hot water (before rad) and cold water (after radiators). Like this one 

<img width="338" alt="Screenshot_2" src="https://user-images.githubusercontent.com/114614288/193456149-bd03b6db-36c3-4665-970a-790395632c76.png">

   +One T-probe for ambient outside the case
   +Another T-probe for ambient inside the case

Here are the temp sensors using ICUE (only for the example, I have completely uninstalled it)

<img width="380" alt="S2WLQeN_d" src="https://user-images.githubusercontent.com/114614288/193456223-0a48b9de-13b1-4e0f-b892-bfab33f5c509.png">

Here are the sensors in Fancontrol

<img width="246" alt="Screenshot_1" src="https://user-images.githubusercontent.com/114614288/193456074-8af2eeed-a8a8-4c2d-bc7e-069b9d8afc65.png">

Thanks in advance, if you need more info let me know.

**Comment by Rem0o** [comment]
This is a plugin issue, not a main FanControl one. Please move this issue to the plugin repo.

**Comment by DfrostX** [comment]
Personally, I would completely remove the commander pro plugin completely, it`s still buggy... And move to the HWinfo plugin with the “Corsair Link/Azetek support option ticked in the HWinfo options(section safety).

This is how I use to measure my water temp using the commander pro before moving to an Aquatuning product.

**Comment by Rem0o** [comment]
See https://github.com/iJacks1980/FanControl.CommanderPRO/issues/20#issuecomment-1264670834

**Comment by Rem0o** [comment]
Closing, since wrong repo.
