### ISSUE TITLE
Feature Request: Curve on a Curve

### ISSUE THREAD

**Issue by incansvl** [Rem0o/FanControl.Releases#1146]
**Describe the bug**
I have individual fan curves set up for CPU and GPU fans as normal (although i'm struggling to control my MSI 6700XT's fans at the moment, so that one is "theoretical fan speed".

I am currently controlling the case fans with a mix (Max) of the CPU and GPU percentages, but that means the case fans going to 100% (noisy) if the GPU or CPU hits 100%, when I know the case fan speeds don;t gain much cooling above 65%, just a lot more noise.

A simple solution would be the facility to put an arbitrary max and min value on the case fan speed, as well as a +/- offset from the Mix curve output.

However a more flexible solution would be the ability to base a curve on a curve, so I could MAX the CPU and GPU together, and then build a new S-shaped case fan curve outputting between (say) 35% and 65% for inputs from 1 to 100%.

The ultimate solution might be to have a "function block" where the user can write a custom transfer function from one or more inputs to an output value, but that's perhaps a bit over the top (OTT).

**Is there a log.txt file next to FanControl.exe with recent date entries?**
N/a

**Relevant hardware specs and setup**
CPU: Intel 4770K @4GHz
GPU: MSI Radeon 6700XT @~2600MHz (still experimenting with undervolt/overclock values)
Motherboard: Asus Z97M Plus

**Comment by Rem0o** [comment]
What you want to do is already covered. You shouldn't share the same curve for your CPU or GPU fan and your case fans. I know Jayz2cents does it in its video, but that's bad.

Trying to use the same curve that controls your CPU fan for your case fans is not the most optimal approach.

My recommendation:

* Put 2%/sec step up and step down for your case fans.
* Have 1 curve for your CPU fan, 1 for your GPU fan. Fast response time, one way hysteresis on both.
* Create 3 other NEW curves for your case fans, 1 cpu based that max at 65%, 1 gpu based that max at 65, and a mix of those two with a max function.  Have those with a 5 sec response time. Apply the mix to your case fans,

Final result should look like this:
![image](https://user-images.githubusercontent.com/14118956/193592901-97f7a8df-71fc-41cd-9fc8-d1df5cdb4c83.png)


No need for some new fancy function to convert your CPU fan curve for your case fans, just create new, specific ones.

**Comment by incansvl** [comment]
Ok I see how that works. It sidesteps the "curve on a curve" requirement, at the cost of creating and maintaining additional curves.

Thanks for the suggestion, I will give it a try.
