### ISSUE TITLE
2 Fan Controls gone after v59

### ISSUE THREAD

**Issue by whatanoob** [Rem0o/FanControl.Releases#115]
In all versions later than release 59, I can no longer control my CPU and my case fan because I went from having 5 fan controls to having 3, with only one of them controlling a fan (the GPU fan).

**Comment by Rem0o** [comment]
Quick question: If you take the LibreHardwareMonitorLib dll from v59 and put it in the V62 folder, do you get your fans back?

**Comment by whatanoob** [comment]
Yeah, that does seem to work.

**Comment by Rem0o** [comment]
Right, so that means the latest update for Libre broke some stuff.

**Comment by fauder** [comment]
I had 5 controls I used and 3 controls that did not match any fan and ALL my fans were accounted for -> No problems.

My 2 chassis intake fans were daisy-chained and connected to a single connector on my mobo. I decided to separate them and connected one of them to CPU_OPT connector of the mobo instead (my goal was to associate this fan with my cpu curve on FanControl and the other fan with my gpu curve). But I can not see the second fan (that is now connected to CPU_OPT connector) on FanControl.

Maybe it is possible that CPU_OPT can not be controlled ?

But if it can be controlled, should I also find the v59 release and copy LibreHardwareMonitorLib dll from there ?

**Comment by Rem0o** [comment]
@fauder 

If it was working before and now they are gone yes, if it never was supported, then there is no point.

**Comment by fauder** [comment]
Fair enough, I started using your software just recently with V62. So I don't know if they worked with V59. I'll try with said DLL from V59 and report back.

By the way thanks this software. Really simple UI and well thought out UX. I'd donate in a heartbeat but Turkey had problems with Paypal and I believe it's currently not an option.

**Comment by fauder** [comment]
Seems I can not do that as there is only V62 on the releases section of this repo. Can you tell me which version of LibreHardwareMonitorLib I should look at to find that dll ?

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases

**Comment by Rem0o** [comment]
@whatanoob  could you send me your log so I can see which super IO chip you got?  You can copy the log from the top right menu.

**Comment by whatanoob** [comment]
https://hastebin.com/pusotixoce.yaml

**Comment by Rem0o** [comment]
Well, I would like from the version that actually doesn't work.

**Comment by whatanoob** [comment]
There it is from v62

https://hastebin.com/tukamucowo.yaml
