### ISSUE TITLE
Error: Windows cannot find FanControl

### ISSUE THREAD

**Issue by vaztin13** [Rem0o/FanControl.Releases#1156]
Hi! i checked the boxes to start fan control on startup but it doesnt work, also i tried putting the .exe file in shell:startup, but the error keeps showing. I need to manually open each time i turn on the pc.

**Comment by Rem0o** [comment]
Start with windows works with the Task Scheduler. Take a look in there if the task is created correctly and if the user it uses as admins rights. If your daily user is admin, you shouldn't have problems.
