### ISSUE TITLE
Flat fan "curve" not being adhered to

### ISSUE THREAD

**Issue by TWSSYesterday** [Rem0o/FanControl.Releases#1158]
Looking for a pretty simple setup, 65% fan speed on my GPU's two fans at all times, no more, no less.
When GPU comes under any load, they ramp up to 3600RPM aand are on about 1600RPM at 45%, so unsure why it's not being adhered to?

Config: https://hastebin.com/rekulujipe.json
Version: 131

**Comment by Rem0o** [comment]
There is a "?" next to the percentage on the control card right? 
Which gpu model is it? Any other software that might take over? MSI after burner?

**Comment by plomdawg** [comment]
I'm having the same issue and just found this comment: https://github.com/Rem0o/FanControl.Releases/issues/988#issuecomment-1214397074

**Comment by TWSSYesterday** [comment]
> There is a "?" next to the percentage on the control card right? Which gpu model is it? Any other software that might take over? MSI after burner?

Not seeing a "?"

GPU is a zotac 2080 Super, no additional software that controls fans is installed.

**Comment by Rem0o** [comment]
@TWSSYesterday  can you screenshot the FanControl UI with everything visible when the problem occurs?

**Comment by TWSSYesterday** [comment]
It's quite difficult to get it perfectly showing however this is the best I could do without trying for 30 mins.
https://imgur.com/a/ue317YC

**Comment by Rem0o** [comment]
That’s odd. The fact it shows 55 on the card means it did receive the command. However the card seems to be able to crank its speed without affecting the control sensor, which I’ve never seen before. I got no clue how this might work. Most likely a GPU bios thing, but i don’t know.

**Comment by TWSSYesterday** [comment]
RIP :( Is there no way to force it to overwrite?

**Comment by Rem0o** [comment]
My only handle is the control sensor. I set it, it is being set, but there seem to be still an override that the card respond to.

**Comment by TWSSYesterday** [comment]
That's a shame. Thanks anyways.
