### ISSUE TITLE
Graphics Card FanControl gets ovewritten randomly

### ISSUE THREAD

**Issue by Sebrukai** [Rem0o/FanControl.Releases#1159]
Hello guys!

I have the issue that the GPU controlling disconnects randomly. There is a question mark and it says that it gets overwritten. Then the speed changes to 30% which is the default idling which I see in Afterburner (I dont control the fans using AB, I only undervolt the GPU). But once I deactivate and activate it again using the switch, everything goes back to normal.

Does anybody know what causes the issue and how to fix it? Thank you very much.

**Comment by Rem0o** [comment]
Which are you using? 

![image](https://user-images.githubusercontent.com/14118956/194615596-1d3ebe84-092e-48ab-9c19-b1344559dab3.png)

**Comment by Sebrukai** [comment]
I am currently reinstalling (dont think that this will help but giving it a try) and I checked all boxes but Controller at the left and checked the NvAPiWrapper box as well

**Comment by Sebrukai** [comment]
Testet it out with a game: Its not random but sets self to 30% when I am in a game as if the GPU sensors it runs hot and sets self to idle speed ignoring FanControl

**Comment by Rem0o** [comment]
Could show screenshot your FanControl UI with everything visible?

**Comment by Sebrukai** [comment]
![image](https://user-images.githubusercontent.com/115285244/194650258-90a6471c-68cf-4617-b0b3-a519cd66249e.png)

There you go! I hope you can find the issue, love the software so far (except for this bug and that it doesnt start with Windows no matter what I try)

**Comment by Rem0o** [comment]
Are you sure AfterBurner isn't interfering? Fan settings in there are confusing.  
![image](https://user-images.githubusercontent.com/14118956/194652668-6cf218f9-b3b7-4a5a-afe8-03d7656822e2.png)

**Comment by Sebrukai** [comment]
Yeah, AB is definitely not the problem. I thought about some weird BIOS setting, would that be possible? Because once the card spikes in temperature, it goes back to idle in 30%

**Comment by Rem0o** [comment]
Ah,  the 30% is a known issue with NvAPI. As soon as you ovverride the fan control value, the minimum will get stuck to 30%. If that's a deal breaker, disable the control for your GPU in FanControl, and use after burner for that only.

**Comment by Sebrukai** [comment]
Hello again! I tried using AfterBurner but I have the same 30% issue there as well. It worked a couple months with AfterBurner but then suddenly this problem occured. Do you know a fix? Would be highly appreciated.
