### ISSUE TITLE
Remove donate popup for users that have donated?

### ISSUE THREAD

**Issue by CZonin** [Rem0o/FanControl.Releases#116]
I was wondering if this could be done in a future release?

**Comment by Rem0o** [comment]
I will look into adding a way to opt out of it, at least for a greater period of time. I won't be able to completely disable it ONLY for those who donated, since I'm not tracking anything and I don't plan to do so.

**Comment by CZonin** [comment]
True, I didn't think about the tracking. I guess just a simple checkbox for "Do not show again for x days" would be useful.
