### ISSUE TITLE
IT for my work company has listed FanControl.sys as a "Severe" Threat in Windows Defender

### ISSUE THREAD

**Issue by LightTreasure** [Rem0o/FanControl.Releases#1160]
This morning, Windows Defender blocked and quarantined FanControl.sys from my computer:
![image](https://user-images.githubusercontent.com/1550856/194650324-d677bd2b-ffd1-4fd2-b5c3-7078388925da.png)

This happened because my computer is domain-joined for my work company and IT has listed FanControl.sys as a threat. I have asked them the reason why, and I'm awaiting their response.

In parallel, I noticed that FanControl.sys only appears in the directory when FanControl.exe is actually running, which seems to indicate the file is deployed on-the-fly. FanControl.sys is a Kernel-mode driver, so it definitely has the potential to be a security threat - add the on-the-fly deployment to that, and the possibility of it being a security threat increases even more. Furthermore, I looked at the repository and noticed that this is not open-source software, as I had assumed ( I'm aware there is a discussion about this in #89 ). 

So IT could be right - this could actually be a severe threat. I'm hoping not, given that it is based on open-source libraries and is a great tool (I liked it so much, I donated via Paypal). However, the on-the-fly deployment of the driver is definitely weird. Could you please explain why it works that way?

**Comment by Rem0o** [comment]
That's how LHM works. Behind the scene it's WinRing0.
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

More specifically https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/3bc334205f2ea79c161ee0dc35d0393d61aeb10e/LibreHardwareMonitorLib/Hardware/Ring0.cs 

is where the kernel stuff is initialized.

**Comment by LightTreasure** [comment]
Interesting. Looking at the following code in Ring0.cs (as well as the definition of the KernelDriver class in https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/3bc334205f2ea79c161ee0dc35d0393d61aeb10e/LibreHardwareMonitorLib/Hardware/KernelDriver.cs )

It appears as if the driver is registered as a service when installed, and then it needs to be obtained from that service. Failing this, the driver is extracted and installed.

I just downloaded and ran LibreHardwareMonitor and it does not spawn and register a new driver every time it runs. Why is this behavior different in FanControl? 

`_driver = new KernelDriver(GetServiceName(), "WinRing0_1_2_0");
            _driver.Open();

            if (!_driver.IsOpen)
            {
                // driver is not loaded, try to install and open
                _filePath = GetFilePath();
                if (_filePath != null && ExtractDriver(_filePath))
                {
                    if (_driver.Install(_filePath, out string installError))
                    {
                        _driver.Open();

                        if (!_driver.IsOpen)
                            _report.AppendLine("Status: Opening driver failed after install");
                    }
                    else
                    {
                        // install failed, try to delete and reinstall
                        _driver.Delete();

                        // wait a short moment to give the OS a chance to remove the driver
                        Thread.Sleep(2000);

                        if (_driver.Install(_filePath, out string secondError))
                        {
                            _driver.Open();

                            if (!_driver.IsOpen)
                                _report.AppendLine("Status: Opening driver failed after reinstall");
                        }
                        else
                        {
                            _report.Append("Status: Installing driver \"").Append(_filePath).Append("\" failed").AppendLine((File.Exists(_filePath) ? " and file exists" : string.Empty));
                            _report.Append("First Exception: ").AppendLine(installError);
                            _report.Append("Second Exception: ").AppendLine(secondError);
                        }
                    }

                    if (!_driver.IsOpen)
                    {
                        _driver.Delete();
                        DeleteDriver();
                    }
                }
                else
                {
                    _report.AppendLine("Status: Extracting driver failed");
                }
            }

            if (!_driver.IsOpen)
                _driver = null;
`

**Comment by Rem0o** [comment]
@LightTreasure 

Not sure yet, but from FanControl, when trying to open the driver, I get this:
![image](https://user-images.githubusercontent.com/14118956/194719390-16536294-fbcc-4549-af4e-5324b0d154ea.png)

Will check a bit more.

**Comment by LightTreasure** [comment]
Ooh, interesting. I'll check LHM my side, I didn't see this.
