### ISSUE TITLE
FanControl accesses my drive every minute and prevents it from sleeping

### ISSUE THREAD

**Issue by DerJantob** [Rem0o/FanControl.Releases#1165]
Hey,
I have noticed that my hard drive no longer goes to sleep. I wanted to figure out the problem and with the help of the program "Process Monitor" I found out that FanControl accesses the hard disk once every minute and thus prevents it from sleeping (or wakes it up).

![grafik](https://user-images.githubusercontent.com/79801484/194917194-1138cd0b-516c-4030-9c52-14aaf5215df5.png)

Is there anything I can do to prevent this?

Kind regards
Jannik

**Comment by Rem0o** [comment]
Remove hard drive monitoring from your sensor settings.

**Comment by DerJantob** [comment]
Well, this was too easy. Somehow I overlooked this setting.
Thank you for the quick help :)
