### ISSUE TITLE
Feature Request: Command line args

### ISSUE THREAD

**Issue by Jessi810** [Rem0o/FanControl.Releases#1166]
I'm not sure if this app has command line options beside --config. Something that would allow us to change the value/s of 'Controls' or 'Curves' items.

Sample:
.\FanControl.exe --curve 'MyCustomFlatCurve' --set  'Percent=60' --control 'GPU Fan' --set 'ManualControl=true; ManualControlValue=80'

This allows changing of fan speeds, etc. by clicking Windows shortcut, a global shortcut and through CLI without having to open the app and manually changing the settings there.

Update: I just noticed, we can change configurations through the tray icon.

**Comment by Rem0o** [comment]
There is a command line arg to set a custom config.   

Fancontrol.exe -c yourconfig.json
