### ISSUE TITLE
Feature: CSV logging

### ISSUE THREAD

**Issue by TheWoodsy** [Rem0o/FanControl.Releases#117]
I'd love to be able to monitor the fan speed set by this app in addition to current speed and temperatures.

Please implement the option of CSV logging to a file.

**Comment by TheWoodsy** [comment]
MSI Afterburner shared memory integration would be incredible too.

**Comment by Rem0o** [comment]
I won't add any advanced monitoring abilities to FanControl. I want the software to stay focused on controlling fans and nothing else.

Same thing for MSI Afterburner integration. I don't really see the added value to the core functionality.

**Comment by TheWoodsy** [comment]
Is there any way currently to exfiltrate the PWM duty cycle set by the application?

**Comment by Rem0o** [comment]
Not really, what I'm setting is a 8 bit value ( 0-255 ), then the driver/controller decides what to do with it.
