### ISSUE TITLE
Fan Control / Command Prompt on startup

### ISSUE THREAD

**Issue by IdiotSandwich00** [Rem0o/FanControl.Releases#1177]
**Command Prompt on Startup searching for Fan Control not installed**
I had to uninstall / delete fan control because it was doing more harm than good to my computer, not here to fault anyone granted it could be very well my issue however I get a cmd prmpt pop up even though I uninstalled

![image](https://user-images.githubusercontent.com/115895181/196002056-d2e88465-fc17-4f08-a99a-6d9693a2739a.png)

Please help because this is very frustrating!

**Comment by Rem0o** [comment]
Task Scheduler => Delete the fan control entry.

**Comment by dmares01** [comment]
I will write up a section for the README in this as well @Rem0o

**Comment by Rem0o** [comment]
@dmares01  sure go ahead, under the installation section
