### ISSUE TITLE
Paired RPM Sensor Required & Additional Fan Appears?

### ISSUE THREAD

**Issue by 0pLuS0** [Rem0o/FanControl.Releases#1178]
Hello,

```Specs:```
Windows 11 Home 21H2
Asus B550F-Gaming
EVGA 3080 FTW3 Ultra

Is this ASUS board well supported?

I use MSI Afterburner for a custom GPU fan curve, Undervolt curve, OSD for the gpu/cpu, and display in the tray icon the cpu/gpu temps.

I only want to use FanControl to control the cpu and case fans.

Would it be safe to use both apps like this, without conflict between them?

I read the ```A paired RPM sensor is required``` message might have to do with other software installed. Does this mean, installed, or running? Afterburner was not running when I ran FanControl for the first time.

I also understand that the software is going to detect all the sensors, but this board only has 6 fan headers, and it showed a total of 7 fans, so I don't understand where the 7th is coming from.

```Board fan headers:```

1x 4-pin CPU
1x 4-pin CPU_OPT
1x 4-pin AIO_pump
3x 4-pin Chassis

Fan 5, 6, 7 were shown as needing the rpm sensor, and I am only using the cpu and 3 chassis fan headers, for a total of only 4 fans, yet, 5, 6, 7, they showed percentages being used, so how is there some sort of load with these 3 showing in the UI.

I'm attaching the log, but I don't see anything related to these issues.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9793579/log.txt)

THANKS

```Paired RPM sensor required```

![Paired RPM Sensor Required](https://user-images.githubusercontent.com/36190223/196017180-050fb534-fd1f-4b33-9d2a-c113730d942f.jpg)

```7 fans in the UI, but only 6 fan headers?```

![FanControl UI](https://user-images.githubusercontent.com/36190223/196017181-118c32f6-361b-4378-b2d3-e588139b694e.jpg)

**Comment by Rem0o** [comment]
Your fan controller chip probably has 7 channels, but your board only uses 6.  Simply ignore the left-over channel (7).
The 3 non-used fans having a % is normal. That is just the default setting applied to these channels.
SImply hide the control cards/ speed cards you don't use.  

I don't see any problem with your setup otherwise.

**Comment by 0pLuS0** [comment]
Ok thanks

**Comment by Rem0o** [comment]
Yes it’s safe to use both. Plenty of people do.
