### ISSUE TITLE
REQUEST: Option To Remove Not Hide

### ISSUE THREAD

**Issue by 0pLuS0** [Rem0o/FanControl.Releases#1179]
Hello,

Can you please make an option to remove sections not being used instead of hiding them?

I would love to see in the UI only show what someone uses, instead of being grayed out. I find it looks a bit cluttered and distracting like this.

And then if you want to put back the sections, there's an option in the settings to click on to place it back.

I hope this can be done, this would be really great.

THANKS

**Comment by Rem0o** [comment]
You can remove the grayed-out/hidden stuff. Open the left hamburger menu and look for the checkboxes there.

**Comment by 0pLuS0** [comment]
Ahh I'm sorry for making this post then, I certainly overlooked this.

I was under the impression you could only hide/gray them out.

THANKS
