### ISSUE TITLE
The V131 video card cannot be recognized

### ISSUE THREAD

**Issue by HAIPAI19** [Rem0o/FanControl.Releases#1181]
My version is V131, but I can't identify the temperature of the graphics card, so I can only add and adjust the CPU and motherboard. Is there any way to solve this problem? I like this software very much, but I can't adjust the temperature of my video card, so I'm a little sad.

**Comment by Rem0o** [comment]
What is your video card? Is the driver up to date? Did you check the GPU section in the sensor settings of FanControl?

**Comment by HAIPAI19** [comment]
My video card is amd6750xt. The driver is not the latest. The latest one has a bug. The customer service asked me to leave the latest one alone. I checked that the gpu part has been enabled. Because it was the same video card before, it can also be used, but not this time.



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 16, 2022 23:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Rem0o/FanControl.Releases] The V131 video card cannot be recognized (Issue #1181)




 
What is your video card? Is the driver up to date? Did you check the GPU section in the sensor settings of FanControl?

**Comment by HAIPAI19** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rem0o/FanControl.Releases"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月16日(星期天) 晚上11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Rem0o/FanControl.Releases] The V131 video card cannot be recognized (Issue #1181)





 
What is your video card? Is the driver up to date? Did you check the GPU section in the sensor settings of FanControl?

**Comment by sparkycz1** [comment]
Hi, another one here. V131 and AMD 6750XT with Windows 11, clean install.

**Comment by sparkycz1** [comment]
V132 Fixed the problem.
