### ISSUE TITLE
X670 Asus board does not show fans in FanControl

### ISSUE THREAD

**Issue by MacieQA** [Rem0o/FanControl.Releases#1182]
I just got the X670 Strix board and when I open Fan Control I can only see my GPU fans xD
So I have 2 fan controls for GPU (middle fan and side fans) but no case fans or CPU fan is available.

Is this normal for ASUS boards? I dropped pretty penny for that setup and now I can't use my fav software of all time :(

**Comment by Rem0o** [comment]
Those boards are brand new with a new chipset. Support hasn't been added yet.  Will have to be community sourced into:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

Will be closing, see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
