### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by vuldin** [Rem0o/FanControl.Releases#1186]
It would be great to list the uninstall instructions in the README. Thanks for a great app!

**Comment by Rem0o** [comment]
Well, there is basically none, since it's a stand-alone app.  Only thing that can be left hanging is the scheduled task if you checked start with windows.

**Comment by dmares01** [comment]
I can write up a quick little uninstall section for the README if you want me too

**Comment by Rem0o** [comment]
README updated.
