### ISSUE TITLE
Switch back to default card curve to hit 0rpm mode.

### ISSUE THREAD

**Issue by LynxesExe** [Rem0o/FanControl.Releases#1187]
Hello!

**Describe the bug**
This is not a bug, it's a **_feature request_**.
It turns out that there are some cards that allow softwares to trigger 0rpm mode, some other cards have a 0rpm mode that can only be triggered by the default stock curve itself.
What this means is that if a card has a 0rpm mode, but does not allow fan control to go to 0rpm mode, fan control will always keep the fans at the minimum allowed (therefore the little question mark will appear saying that another source is overriding the setting, I assume Fan Control checks the current RPM and figures out it's not matching the requested percentage).

MSi Afterburner managed to workaround this by essentially switching to the default curve whenever the custom fan curve wants to set 0rpm (this is what they say on the tooltip over their software anyway):
![image](https://user-images.githubusercontent.com/33750575/196168463-6db95b30-94d6-4baa-9f98-50f783c83dc6.png)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Doesn't apply.

**Relevant hardware specs and setup**
 - GPU: RTX 4090 AMP Extreme Airo (this is probably the only important piece of info needed):
   - This card does have a 0rpm mode, however it cannot be triggered from a software curve, only from it's standard curve, in this case the checkbox showed on the screenshot above does the trick.
 - Mother Board: MSI Mag z690 WiFi DDR4
 - OS: Windows 11 Home 21H2 build 22000.1098

Of course, I can provide any other piece of info necessary if requested.
Thank's in advance!

**Comment by Rem0o** [comment]
This issue has been raised a few times. I do think this option as an opt-in feature is reasonable if the implications are explained properly to the user, aka, anything that happens in this mode is entirely dependent on the hardware curve, and FanControl has no control.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/196313550-27705d84-a8f3-4ec5-822b-721dec3c40fe.png)

Prototyping a new option in the sensor settings, stay tuned.

**Comment by LynxesExe** [comment]
Hi!
I just saw an update with the new option, I will test it out soon.

Yes, I agree, it makes sense to explain to the user what this actually does, as it will be dependent exclusively on the specific GPU stock fan curve. I read the tooltip and it does seem pretty clear to me, I'm just now sure whether this is a Nvidia limitation or a vendor specific limitation; but I have sincerely have no idea, so I'm raising this as a question in general more than a potential mistake on your side.

Let me know if you wish for me to close (since I opened) the issue after I do some testing or if you prefer closing it yourself

Thank you for the quick reply and sorry for the lack of response!

**Comment by LynxesExe** [comment]
Yup, tested and it works just fine, after rebooting too.

There might be some improvement for the quality of life that could be done, this however, mostly comes from my case since my fans make an annoying buzzing sound, so I honestly don't know whether it would be worth implementing this or not, that's up to you to consider and decide : ) .

As of right now FanControl does exactly what you'd expect it to do, under a certain temperature it falls back into 0rpm mode and over a certain temperature it goes into the user defined curve, this works but ultimately it means that the 0rpm mode will effectively only last for 1~ degree, as an example:

If you set the 0rpm mode to kick in from 40c and lower, the 0rpm, mode will work at 40c, but it will switch back to user defined at 41, because that's where FanControl takes control of the fans again. Meaning that you end up in a continuous cycle of on/off for the fans within a few seconds.

It would be interesting (but I would expect that this would mean some extra working and maybe core logic changes, I don't know what the code looks like so this is a complete thrown out there assumption) if the user had the ability to tell FanControl to cool down the GPU until, for example, 35c before working again at, for example, 45c, which right now isn't exactly possible (as far as I know anyway).

This way it would, yes, take a longer amount of time for the fans to cool off the GPU enough before turning off, but it would also mean longer periods of time before the GPU turns the fans back on. The differences would be minimal, but I saw this being the behavior of some stock fan curves and of MSi Afterburner.

Again, I'm not sure if this is worth doing or not and whether it makes sense investing time into it.

I will however close the issue since I think this should be tracked in a new issue/feature request, what has been request has been added and works great! Of course, if you think that this is worth implementing and tracking it here is a better idea it can always be re-opened.

Thank you again for everything!

**Comment by Rem0o** [comment]
@LynxesExe 
To avoid on/off cycles, hysteresis + response time is your best friend.

You can also experiment with the Target Fan Curve mixed with your existing graph, which you can also add a "trigger like" functionality.

Set mix fan curve to max, add both the target and graph, then your target to idle = 35 deg/0% then Load to 45 => 30%.
That "should" give you the behavior you described.

**Comment by LynxesExe** [comment]
Yup, it does seem to do exactly that!
Perfect, thank you so much, I don't why I didn't think of just doing that before, shows the great flexibility of FanControl.

Once again, thank you for the suggestion and great work!
