### ISSUE TITLE
Unable to control NZXT Kraken x63 pump speed

### ISSUE THREAD

**Issue by Fozz13** [Rem0o/FanControl.Releases#1194]
I just downloaded the program and it has been working great, the only problem is I am unable to control my AOI Pump speed. I own a NZXT Kraken x63, it is able to detect the pump speed sensor and is print the rpm's but whenever I try to change the associated fan speed that pump speed does not change. I have tried to change the CPU fan header, restarted the pc, and nothing has seemed to work. I'm curious if this is just a bug on my end, or a compatibility issue with NZXT AOI's

**Comment by MFH01** [comment]
use cam
