### ISSUE TITLE
GPU fans won't going to 0 rpm

### ISSUE THREAD

**Issue by ytrfegd** [Rem0o/FanControl.Releases#1198]
Hello guys.Thanks this incredible project.

Have an issue for gpu curves.When GPU < 58°,my curves set GPU fan rpm to 0%.But it doesn't work, fans rpm has lock on 30%.I need to manually disable the GPU fan control,spins can stop.

I'm allready enbale the "Nvidia 0% hardware cure override" in Sensor settings and using "Force Aplly".

OS:Windows 11 22H2

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/197402056-fb18a63c-0ba7-474a-bc51-fedeaa460f71.png)

Works like the MSI afterburner one.  Keep in mind you don't have access to 1-29% with that option enabled. The override happens at 0. 

I would suggest you set your start and stop % to 30 on your control card.

**Comment by ytrfegd** [comment]
> ![image](https://user-images.githubusercontent.com/14118956/197402056-fb18a63c-0ba7-474a-bc51-fedeaa460f71.png)
> 
> Works like the MSI afterburner one. Keep in mind you don't have access to 1-29% with that option enabled. The override happens at 0.
> 
> I would suggest you set your start and stop % to 30 on your control card.

Thank you for your reply.
![image](https://user-images.githubusercontent.com/75162719/197403186-6c02b6f1-05a2-4144-a684-dada2e82876c.png)
![image](https://user-images.githubusercontent.com/75162719/197403234-ba90e170-120e-41f3-9763-6075f0bce4b6.png)
![image](https://user-images.githubusercontent.com/75162719/197403295-5e331cd0-8051-4ec5-8baa-bfcb4adb6887.png)
I put some img here. It seems to be the same as what you said

**Comment by Rem0o** [comment]
Without any Fan Control, by itself, at what temperature your card will go 0 rpm?

**Comment by ytrfegd** [comment]
> 

Like below the 55° around.

**Comment by Rem0o** [comment]
You won't be able to override that limit. I would suggest you move 0 rpm point in your graph to respect that built-in limit.

**Comment by ytrfegd** [comment]
> You won't be able to override that limit. I would suggest you move 0 rpm point in your graph to respect that built-in limit.

Thanks.I tried to make the points more dense to better implement your suggestion,but looks like not working.
![image](https://user-images.githubusercontent.com/75162719/197406128-600d62a3-afb1-4526-b5ca-15b486c01b50.png)
![image](https://user-images.githubusercontent.com/75162719/197406183-f20dc18d-1702-4c59-8e32-25e0559c479a.png)
![image](https://user-images.githubusercontent.com/75162719/197406192-0ec1cf75-0945-4785-a764-79f984aec3e0.png)

**Comment by Rem0o** [comment]
If you simply disable your control, does it go to 0? If it doesn't then no tweaking in FanControl will change anything.   The setting will only let your card do its default behavior when % is set to 0.

**Comment by ytrfegd** [comment]
> If you simply disable your control, does it go to 0? If it doesn't then no tweaking in FanControl will change anything. The setting will only let your card do its default behavior when % is set to 0.

Yes.When the temperature is less than 50°,at the time disable fancontrol's switch,the fan will immediately stop turning.On the contrary, if you don't control him, you will always be limited to 30%.

**Comment by Rem0o** [comment]
If the limit is 50, then you should set your 0 rpm point at or below that limit, and then any other points should be at or above 30%.

**Comment by ytrfegd** [comment]
> If the limit is 50, then you should set your 0 rpm point at or below that limit, and then any other points should be at or above 30%.

Thank you for your patience.But now there are many 0rpm points below and equal to the limit...

**Comment by Rem0o** [comment]
In none of your screenshots I can see the temperature and the output of the graph at the same time.

**Comment by ytrfegd** [comment]
Sorry about that.I added the temperature information
![image](https://user-images.githubusercontent.com/75162719/197408462-bc39348b-aefb-4f4f-b9de-09f04b2e3dd8.png)

**Comment by ytrfegd** [comment]
> In none of your screenshots I can see the temperature and the output of the graph at the same time.
Sorry about that.I added the temperature information.
![image](https://user-images.githubusercontent.com/75162719/197408472-b5d22a7e-c870-4634-ac8a-bc933bc14fd7.png)

**Comment by Rem0o** [comment]
With screenshots, just screenshot the whole thing. 

In that previous state, if you disable the control card, it immediately goes to 0?

**Comment by ytrfegd** [comment]
> With screenshots, just screenshot the whole thing.
> 
> In that previous state, if you disable the control card, it immediately goes to 0?

Yes,when disable control,it immediately goes to 0(If the temperature is right).

**Comment by Xavinooo** [comment]
I have the exact same issue with my RTX 3080 FE : if I toggle the switch, it goes to 0 and starts spinning at the set temperature (45 in my case) but never comes down to 0 again : 
![image](https://user-images.githubusercontent.com/113215765/197409650-4b51710f-22ed-4a7e-90c8-71f09679fefe.png)

**Comment by ytrfegd** [comment]
> I have the exact same issue with my RTX 3080 FE : if I toggle the switch, it goes to 0 and starts spinning at the set temperature (45 in my case) but never comes down to 0 again : ![image](https://user-images.githubusercontent.com/113215765/197409650-4b51710f-22ed-4a7e-90c8-71f09679fefe.png)

Exactly the same

**Comment by Rem0o** [comment]
@Xavinooo  do you have the option enabled in sensor settings?

**Comment by Xavinooo** [comment]
Yep : 
![image](https://user-images.githubusercontent.com/113215765/197410524-fe935091-4f3a-4491-b8fa-a1f20c65faaa.png)

**Comment by Rem0o** [comment]
@Xavinooo 
1) Disable your control, send screenshot of 0 RPM.
2)  if you set your control to manual mode, then slide back and forth from 0 to something over 30, back to 0, does it stops?

**Comment by ytrfegd** [comment]
> 2\. if you set your control to manual mode, then slide back and forth from 0 to something over 30, back to 0, does it stops?

**1.**
![image](https://user-images.githubusercontent.com/75162719/197411972-5c2d0996-cbc8-483a-96d7-05a7e137fcb0.png)
**2.**
![image](https://user-images.githubusercontent.com/75162719/197412053-96bec980-a3dc-4e99-b240-af26965c0282.png)
![image](https://user-images.githubusercontent.com/75162719/197412098-ccd691f6-f950-4120-8f37-6d08d22e9c32.png)

**Comment by Rem0o** [comment]
Noticed you got "force apply" on , remove that.

**Comment by ytrfegd** [comment]
> 

![image](https://user-images.githubusercontent.com/75162719/197444987-0f3ac104-6833-49b9-a178-758464f1d5ed.png)
![image](https://user-images.githubusercontent.com/75162719/197445032-123465e8-6647-467e-88c5-a463657f188c.png)
![image](https://user-images.githubusercontent.com/75162719/197445050-daffa9d3-a24a-4ada-bebe-17c4de00169a.png)
Looks like not work

**Comment by Xavinooo** [comment]
Well, on my side, nothing works.
Even what worked yesterday isn't working anymore.
Started from strach with a brand new install of FanControl et tried everything, the fan are no more stopping (yesterday they did !)
Sometimes, the "30%" label of the gpu fan card card goes to 22% and straight up to 30%.

**Comment by Xavinooo** [comment]
Came back from work, didn't change anything, if I toggle the switch, fan stops.
I start furmak to make them spin : ok.
When I stop furmark and when the temp is below the my limit (45°), they don't stop, even if I toggle manually the switch.

**Comment by Rem0o** [comment]
@Xavinooo  any errors in the log.txt?

**Comment by Xavinooo** [comment]
I have no log.txt file.
But I noticed, when the monitor go to sleep (after 5 minutes in my case), fans do stop.

**Comment by ytrfegd** [comment]
Although the fan can now be stopped by the modified configuration, the start point of the curve is disabled again without checking force aplly (for example, if you set 55° to start spinning and the card defaults to 50°, it will still start spinning at 50° if force aplly is not checked). Currently it is still the most suitable solution to stop the fan by manual control...

**Comment by ytrfegd** [comment]
The ultimate solution was used - connecting the fan to the motherboard. Everything is working fine now.
