### ISSUE TITLE
I only have the option to control GPU fans and not Case fans

### ISSUE THREAD

**Issue by kydo26** [Rem0o/FanControl.Releases#120]
Although it recognizes the RPM of my other fans, it doesn't give me the ability to control them. I have Gigabyte Z390 UD, Intel i7 9700k and RTX 3070

![Screenshot 2021-01-04 202036](https://user-images.githubusercontent.com/77516765/104789356-7b2aae80-575a-11eb-8bc9-70e6f1c3b797.png)

**Comment by terminalwhoami** [comment]
I'm having a similar issue, except I can control 2/3 fans.  Also a Gigabyte motherboard.  I see the RPM for the final fan, but don't have a control option.  I've used this motherboard on Debian and I'm pretty sure lm_sensors was able to control the fan.

**Comment by Cubox** [comment]
If you download and run the binary from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases
What do you see on those fans?

**Comment by kydo26** [comment]
> 
> If you download and run the binary from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases
> What do you see on those fans?

It shows the fans running and also shows the Z390 UD
