### ISSUE TITLE
Fan Control fails to Initialize

### ISSUE THREAD

**Issue by pheight57** [Rem0o/FanControl.Releases#1201]
**Describe the bug**
I really love your program, but this only recently started happening to me after I ran an update for Fan Control. I have tried entirely removing the program and reinstalling it. I really don't want to have to rely on ASUS's Armoury Crate for my fans, so, help please? I think based on reviewing similar problems reported here that it might have to do with the storage check timing out? If so, what files do I need to edit and where, because I can't get into the program to disable that check...

**Is there a log.txt file next to FanControl.exe with recent date entries?**

> 24-Oct-22 13:16:56: System.Management.ManagementException: Invalid namespace 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.AddGroups()
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
24-Oct-22 13:16:56: LibreHardwareMonitor could not initialize or has no sensors.

**Relevant hardware specs and setup**
System specs can be found [here](https://pcpartpicker.com/b/Fm6RsY).

**Comment by pheight57** [comment]
[log_old.txt](https://github.com/Rem0o/FanControl.Releases/files/9853878/log_old.txt)
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9853879/log.txt)

**Comment by Rem0o** [comment]
Seems to be failing in the storage section. Disable the storage section in sensor settings, If you can't access it, open your json config file, and manually set the storage property to false.  Should do the trick.

**Comment by pheight57** [comment]
Well, this is embarrassing. It looks like I accidentally deleted my json config file when I did the complete removal and reinstall...Is there a basic one available somewhere that I can grab a copy of so that I can make the edit you suggested so that I can get back into the program?

**Comment by Rem0o** [comment]
```json
{
  "Sensors": {
    "DisabledPlugins": [],
    "LibreHardwareMonitorSettings": {
      "Controller": false,
      "CPU": true,
      "GPU": false,
      "Memory": false,
      "Motherboard": true,
      "PSU": false,
      "Storage": false,
      "ZeroRPMOverride": false
    },
    "NvAPIWrapperSettings": {
      "Enabled": false,
      "ZeroRPMOverride": false
    }
  }
}
```

**Comment by pheight57** [comment]
Thanks! Man, you are a flipping legend! Just sent you a $20 donation!

**Comment by Rem0o** [comment]
No problem! Closing.

**Comment by troglodyte9** [comment]
where is sensor
