### ISSUE TITLE
Cannot pass further down than ~600RPM on my CPU Fan using FanControl

### ISSUE THREAD

**Issue by pawelstrzyz** [Rem0o/FanControl.Releases#1206]
Yesterday I started playing with this very nice application. It recognized all my fans properly but... there are like two 'funny' things:
* I cannot control CPU fans separately, although they are conneceted to CPU and CPU Opt headers (maybe this is not possible, because with Asus Fan Xpert 4 I could not do that as well)
* I cannot anyhow force my CPU Fans to spin slower than ~570-600 RPMs - using Xpert 4 that was possible. What is more case fans attached to two other motherboard headers respond correctly to my changes and I can set like 10% of speed and they will spin down below 400 RPMs

In BIOS I saw that there is an option for minimal CPU Fan spin at 200 RPMs and I did not touch that value. In addition to this I think that all is set to PWM in BIOS using some Standard mode.

**Comment by Rem0o** [comment]
CPU and CPU-Opt are linked, they are the same channel, just with two headers.

As for your RPM range, try and set them to DC in bios if that helps.  Also, I believe Asus do some funny things with their modes, limiting the range available depending on the mode. Thus 100% on "silent" won't be the same as "100%" on "High performance" or whatever the names are.   I can't override that behavior, so you'll have to figure out which settings will let you have the wanted range in FanControl.

**Comment by pawelstrzyz** [comment]
Today I have executed a calibration of fans using QFan built in tool and it turned out that available range for CPU fans is 28-100% and for case fans it was able to go down to 14%. Moreover even in Manual mode it is impossible to fill any value below 28 for CPU Fan. So it seems that Xpert 4 does some hidden magic and is able to overwrite the default min values. I could try to switch to DC but I really doubt this can help somehow. @Rem0o thank you very much for your reply!

**Comment by Rem0o** [comment]
No problem!

Closing.
