### ISSUE TITLE
Not detecting any fans (except GPU)

### ISSUE THREAD

**Issue by nirurin** [Rem0o/FanControl.Releases#1207]
**Describe the bug**
Transferred from an MSI X670e MPG motherboard, to an Asus X670e Strix motherboard, and now the only fans that show up on the app are the gpu fans. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Untitled-1.txt](https://github.com/Rem0o/FanControl.Releases/files/9865273/Untitled-1.txt)

**Relevant hardware specs and setup**
AM5 X670 board, windows 11

**Comment by Rem0o** [comment]
Please see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

**Comment by L1NGU1C4** [comment]
Hi. I was having this problem. Try to (re)install HWMonitor and HWInfo. When I installed, it worked. Also, look in your BIOS if the fans are activated (the PWM option, for example).
