### ISSUE TITLE
Adding Temp-Sensor Data with XML 

### ISSUE THREAD

**Issue by FabiB97** [Rem0o/FanControl.Releases#121]
i got a aquacomputer pump and with there software aquasuite i am able to export the internal sensor data to a xml and let it update every second

The XML looks like this
```
<?xml version="1.0" encoding="utf-8"?>
<LogDataExport xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Name>Wassertemperatur</Name>
  <ExportTime>2021-01-16T03:17:44.4895039+01:00</ExportTime>
  <Logdata>
    <LogDataSet>
      <t>2021-01-16T02:17:43.691</t>
      <value>34.4239</value>
      <name>Wassertemperatur</name>
      <unit>°C</unit>
      <valueType>TEMPERATURE_C</valueType>
      <device>System</device>
    </LogDataSet>
  </Logdata>
</LogDataExport>
```

i tried adding the .sensor to the end but aquasuite still attaches the xml so it doesnt get recognized and i think theres some more work to do in the code to read out the temp data

is that possible?

**Comment by lordimac** [comment]
I was about posting the same thing. Using a similar setup with AquaSuite/Aqua Computer Hardware, but without the possiblity to control my fans trough AquaSuite. So I was thinking about importing the XML as virtual Sensor in Fan Control, but obviously, it's not that simple. AquaSuite also offers an export to SharedMemory. Maybe someone with development skills can write a plugin for Fan Control to get the data from AquaSuite with Shared Memory support. I can offer any information from my side if this leads to a plugin for this awesome type of software.

**Comment by Rem0o** [comment]
AFAIK, there is Aquasuite support in LHM:

Make sure the "controller" section is ticked:
![image](https://user-images.githubusercontent.com/14118956/140999439-515c5ccf-4447-4836-9f21-5dbf3957b023.png)

**Comment by Sacred-Shadow** [comment]
Unfortunately, I have to get the ticket up again. I now have a QUADRO from aquacomputer. The Aquasuite is also installed.

But even after controller is activated in the section, it doesn't find any of the sensors.

**Comment by Rem0o** [comment]
Just checked, those are the supported devices: 
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/tree/master/LibreHardwareMonitorLib/Hardware/Controller/AquaComputer

**Comment by Sacred-Shadow** [comment]
Unfortunately, no.
So do you think I should submit a request to the LHM?

Just solved it with your HWInfo plugin.

**Comment by Rem0o** [comment]
Closing. Plugin system could cover this.
