### ISSUE TITLE
Sensor Settings cutting off Plugins List

### ISSUE THREAD

**Issue by gnewtzie** [Rem0o/FanControl.Releases#1211]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

I have a corsair commander and in the plugins list, it cuts off the whole list now and there doesn't appear to be a way to scroll or resize the modal.
it should have a scrollbar or be sizable

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]
![Screenshot 2022-10-27 090941](https://user-images.githubusercontent.com/5942772/198308399-31b8c363-f2c9-4884-bc40-820c6c89b275.png)

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by gnewtzie** [comment]
wow. that was fast. It looks fine now with the update.

**Comment by Rem0o** [comment]
Had a release planned for today anyway, added that one in last minute!
