### ISSUE TITLE
Getting a lot of errors thrown and GPU fans stuck at 0.

### ISSUE THREAD

**Issue by Noahnew10** [Rem0o/FanControl.Releases#1213]
Not sure when it started, but I recently noticed that my GPU fans are no longer spinning and its giving me the '?' on all of my fan sensors. Though the ?s only stay on the GPU sensors, and they fluctuate on the system fans and CPU fan. I've been using Fan Control for about 3 months now and have had no problem, but I guess now I do now. Thought that maybe Afterburner was interrupting FC but I completely uninstalled afterburner and saw no change. I have also enable the 'force apply' option to the '?'s and didn't notice much change either. Any ideas?

Log:
[FC error log.txt](https://github.com/Rem0o/FanControl.Releases/files/9882461/FC.error.log.txt)

This error is now popping up on startup, though when refreshing, it goes away and the sensors show up anyway.
![FC error pic](https://user-images.githubusercontent.com/116839551/198376874-0076d03f-f0bb-40fb-a383-6c3966058091.png)

![FC setup pic](https://user-images.githubusercontent.com/116839551/198377922-330c2de4-7467-4fcc-84c7-517aa2be0053.png)

**Comment by Rem0o** [comment]
A few things:

1) Show your sensor settings. Do you have the Nvidia override for 0% activated?
2) Go through the assisted setup once:
![image](https://user-images.githubusercontent.com/14118956/198394692-cd13dcdd-b2b5-4ee9-b50d-104dabc01f69.png)
3) Do you get a prompt to save your settings? If so, do save.  Send your json config file here also.

**Comment by Noahnew10** [comment]
Went through the assisted setup and didn't see and noticeable change.
Here is my sensor settings and my config file.

![FC sensor settings](https://user-images.githubusercontent.com/116839551/198737069-848e5206-898b-49d3-b477-895f6ec59049.png)

config file
[GPU vs CPU temp - Copy.zip](https://github.com/Rem0o/FanControl.Releases/files/9892119/GPU.vs.CPU.temp.-.Copy.zip)

**Comment by Rem0o** [comment]
Something is conflicting with FanControl and preventing control. 

Make sure your bios settings don't have any "smart control" enabled on your headers.
Could also be something else.
