### ISSUE TITLE
ITE IT8695E receives Fan Readings but not controllable

### ISSUE THREAD

**Issue by elbastron** [Rem0o/FanControl.Releases#1214]
I own a Gigabyte AORUS Z690 Ultra mainboard which has both an ITE IT8689E which works just fine with FanControl but also an ITE IT8695E where fan speeds are read but can't be controlled by FanControl. 

[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/9888082/LibreHardwareMonitor.Report.txt)

Strangely the ITE IT8689E doesn't show control percentages in LibreHardwareMonitor but these can be controlled through FanControl. The IT8695E shows control percentages in LibreHardwareMonitor however. My main issue is IT8695E's Fan #3 which I'd love to be able to control in accordance to my GPU temperature.

![grafik](https://user-images.githubusercontent.com/85590940/198580630-2bb18042-a56f-4866-89d3-45d44c3c5eea.png)

I suppose that the IT8695E fan controller is not yet fully supported, may this be added in the future? Thanks.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

Support may be added in the future, but that doesn't depend on me much. I don't have special access to every motherboard on the market, or documentation on newer chips that come out. FanControl rely entirely on external sourcing mainly via https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.
