### ISSUE TITLE
[Question] When will the developer attach a license to this project?

### ISSUE THREAD

**Issue by Zliced13** [Rem0o/FanControl.Releases#1216]
Just wondering, will this be one of those unlicensed GitHub projects? Or will the developer eventually attach a license to this project?

**Comment by Zliced13** [comment]
Is there a EULA, or a TOS I can read if there is no license for this project?

**Comment by Rem0o** [comment]
As you may probably know:

"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

Now may I ask why/what exactly you are looking for?

**Comment by Zliced13** [comment]
Oh, I forgot default copyright laws exist, my bad. I was just wondering why there is no license attached to this repository. I got my answer and that is all I needed.
