### ISSUE TITLE
Not working at all in Windows 11, but works fine in WIn 10 on same pc

### ISSUE THREAD

**Issue by Ps519** [Rem0o/FanControl.Releases#1217]
Everything working perfectly in Windows 10, set up some curves and no errors during operation. However, on the same pc when I boot into Windows 11, the app stops working completely (even though all the same drivers have been installed, etc.). I tried using both a fresh extracted folder, and launching from a copy of the app folder I use in Windows 10, the effect is the same. There are "Missing sensors" errors, and manual controls of the fans don't work at all either.
I have tried downloading LHM separately and it works fine - all the sensors are there, fan speeds are detected normally. Also tried using the HWInfo plugin for the sensors, but can't seem to make it work so far.
My question is this: are there maybe some libraries/drivers/etc that I might be missing on my Windows 11 installation? (apart ftom the .net, I checked that, it is installed)
P.S.Hardware: Asus b450m motherboard, tried using the Asus software for fan control in win 11, it works, fan speed can be changed and speeds are detected, but no luck with FanControll :(... Seems like a small issue that can be fixed easily, I just don't know what else to check, thanks for any suggestions!

**Comment by Rem0o** [comment]
First time I hear from someone having issues from 10 to 11.  Do you have a log.txt file getting created?

**Comment by Ps519** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9895485/log.txt)
![Screenshot_20221030_115942](https://user-images.githubusercontent.com/116943995/198870980-14232bcd-9d06-4bed-89fe-33433659bcf3.png)
Yes, here is one of the logs, however today I noticed something else - LHM actually is Not working fine, it shows some ridiculous values for rpms)) Does your app use LHM for controls as well as for sensors? 
I tried installing Asus AI suite, and fan controls in it do work. The only other software that works is Argus Monitor. I tried FanCtrl frow github as well, but it is not working either as it is also based on LibreHardwareMonitor....

**Comment by Ps519** [comment]
HWInfo is working fine, btw. LHW seems to be the issue)
![Screenshot_20221030_121938](https://user-images.githubusercontent.com/116943995/198871371-1d3d624f-0274-4e36-bdeb-330e47030cbc.png)

**Comment by Ps519** [comment]
Basically, I found the thread that helped me with a workaround for this issue (launch CPUID HWMonitor before launching FanControl) 
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/614
-> so it is more of a LHM hardware compatibility issue, rather than  FanControl specific. Weird thing is that it all worked fine on the same hardware in Windows 10 =)
