### ISSUE TITLE
"An un expected error occurred. See the log file for details." After Updating NVIDIA GPU Driver

### ISSUE THREAD

**Issue by SionHu** [Rem0o/FanControl.Releases#1219]
Describe the bug
[A clear and concise description of what the bug is. Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

Everything worked fine until I updated the Nvidia GPU driver through GeForce Experience to version 526.47. After the update, when I tried to open the FanControl executable file, the following message pops up:
![image](https://user-images.githubusercontent.com/21280591/198848564-3c503daa-8420-4f72-8b4f-92874c7dd90d.png)

So I deleted the folder and re-downloaded the latest release (v134) from the GitHub repo, but the same thing happened when I double-clicked the FanControl app.

Is there a log.txt file next to FanControl.exe with recent date entries?
[Link it here]
Although the error says "See log file for details", I do not see a generated log file.

Relevant hardware specs and setup
[Laptops and most proprietary pre-built desktops are not supported.]

- OS: Windows 11 22H2
- OS build: 22623.875
- GPU: Nvidia GeForce RTX 3060 Ti
- GPU drive version: GeForce Game Ready Driver V526.47
- CPU: AMD Ryzen 5 3600XT 6-Core Processor
- AIO: Bykski Mini DDC Pump Reservoir

_PS: I suspect this is the compatibility issue with the latest Nvidia GPU driver, so I am going to downgrade my current driver and see if that helps. Hope this raises the attention of the developers cause this is such a GREAT app 😄_

**Comment by Rem0o** [comment]
Just updated to 526.47 and got no issue.

Make sure you got V135. 

Log would be "log.txt" in the same folder as the exe file and your json configs.
