### ISSUE TITLE
DateTime BIOS related issue

### ISSUE THREAD

**Issue by Sky550** [Rem0o/FanControl.Releases#122]
Hello. Wanted to control fan speed on my chinese X99Z102 but got this error on startup
17.01.2021 13:47:54: System.ArgumentOutOfRangeException: Параметры Year, Month и Day описывают непредставимое значение DateTime.
   в System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   в LibreHardwareMonitor.Hardware.BiosInformation.ParseBiosDate(String biosDate)
   в LibreHardwareMonitor.Hardware.SMBios..ctor()
   в LibreHardwareMonitor.Hardware.Computer.Open()
   в FanControl.Domain.ComputerAccessLayer.Initialize(Nullable`1 disableStorage)
17.01.2021 13:47:54: Could not initialize.
my BIOS date is 27/05/2020

**Comment by Rem0o** [comment]
That's a LibreHardwareMonitor issue, most likely due to your Windows installation language. Can't do anything about it here.

**Comment by Sky550** [comment]
@Rem0o , for some reason bios creator set date in European format instead of US. Flashing another BIOS solved this issue.
