### ISSUE TITLE
Load configuration 

### ISSUE THREAD

**Issue by Stubbsyefc1** [Rem0o/FanControl.Releases#1222]
A question,

When i save and try to load my save it tries to open from System32?

![image](https://user-images.githubusercontent.com/86574812/198854528-aaa6a679-f19a-4b3a-975e-551cd73989aa.png)

I put my save in system32.. I'm so confused on why it does this?, Is this normal?

**Comment by Rem0o** [comment]
Your working folder is System32 for some reason.  Look at the task in the task scheduler and make sure the "working folder" is the same the exe of fancontrol is in.

**Comment by Stubbsyefc1** [comment]
So what am i looking for? 

![image](https://user-images.githubusercontent.com/86574812/199108065-f0272c91-37b8-4938-b816-cc5f80a941ba.png)

**Comment by Rem0o** [comment]
Right click the fan control task, properties.

**Comment by foreachthing** [comment]
You can reset the task scheduler entry by uncheck/check "Start with Windows" in FanControl.
I had a similar issue 😦
