### ISSUE TITLE
Fans on 100% after sleep, or after turning on the pc.

### ISSUE THREAD

**Issue by AdoKulo** [Rem0o/FanControl.Releases#1223]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]
Hi,

Sometimes, when my PC gets from sleep, or I just turned on the PC (it's most often when it gets from sleep), the program turns on my fans to maximal RPM . Most often the programs mishandles CPU fans, and sometimes exhaust. I just had an incident in which the programs turned all of the fans to maximum. However, the program doesn't show that the fans are at maximum in controls. For the CPU it has like a small question mark. For other, it doesn't even show that.

It'd be great if I could get some instructions on that.

Software is great, and I really like it!

Thank you!

Best,

Ado

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
Does it recovers after some time coming back from sleep?

**Comment by AdoKulo** [comment]
No, I don't think so. I've tried to leave it for a minute or so, but it didn't came back. What I do is to turn off curve slider, and then turn it on again. It then adjust itself properly instantaneously.

Perhaps is the hardware information significant. Fans that are making problems are the same model. For CPU cooler I have two Asus rog strix xf 120 in Push & Pull, and another unit of the same fan for exhaust.

**Comment by LMC4S** [comment]
Same

**Comment by AdoKulo** [comment]
Not sure why would you mark it completed if the problem still persist?
