### ISSUE TITLE
Nvidia 3080 difference in rpm

### ISSUE THREAD

**Issue by davedave85** [Rem0o/FanControl.Releases#1227]
im checking the rpm % between fan control and precision x and its a difference of 12%, the workaround i did is to put that % (diff) in offset but the problem is not getting the correct % of the rpm

**Comment by Rem0o** [comment]
% in FanControl is not actually a % of rpm, but more of a % of power applied to the fan ( duty cycles or voltage ).  Relative to rpm, it is a non linear function. It is meant like this.
