### ISSUE TITLE
Feature Request: Multiple Temp Sources

### ISSUE THREAD

**Issue by Neko-urself** [Rem0o/FanControl.Releases#123]
Would it be possible to add a feature where the fan curve will take temperatures from multiple chosen sources and take the highest temperature from those chosen ones?

**Comment by gengen1988** [comment]
It does have multiple sources feature, but only for two sources. If you want more than two, you must add more curve as a workaround

![image](https://user-images.githubusercontent.com/1947568/104874169-36d32480-598d-11eb-8f89-015b559cc0da.png)

"Mixed" in this figure is combine 3 sources, which are GPU / SSD / PCH

**Comment by Neko-urself** [comment]
Oh yeah, i missed that one. i wasn't sure what it meant. Thanks so much!
