### ISSUE TITLE
[Idea] Using mouse wheel to adjust manual fan speed

### ISSUE THREAD

**Issue by ownlyme** [Rem0o/FanControl.Releases#1232]
To test your fan for resonant frequencies it's important to check every percentage of fan speeds.
With the current implementation of the manual control slider it's a bit finicky to do that.
My suggestion is letting the sliders catch mousewheel inputs to increase/decrease by 1% each step.

**Comment by Rem0o** [comment]
Not a bad idea. Will take a look.
