### ISSUE TITLE
Corsair HX1500i PSU not showing up in FanControl

### ISSUE THREAD

**Issue by matchabrined3** [Rem0o/FanControl.Releases#1233]
The Corsair HX1500i PSU is not showing up in FanControl. Can you fix this please?

**Comment by matchabrined3** [comment]
I commented on here:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/458
And @zeule responded:

"One needs to add USB ID for that PSU: https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=5619c6609130bce910736a61724a5ee033a0822c"

[Here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Psu/Corsair/CorsairPsuGroup.cs#L16) is the list. [Here](https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/tree/drivers/hwmon/corsair-psu.c?h=hwmon-next#n815) is the "upstream" list. Just copy missing entries and recompile.

"

If that helps @Rem0o

**Comment by Rem0o** [comment]
Well, he suggest you make the change youself to add your PSU, then test the change, before creating a PR. 
From the look of it I guess you never touched code in your life.  

I will be compiling a dll with the entry for your PSU. I will post it here. At that point, swap it in the FanControl folder and see if it picks up your PSU.

**Comment by matchabrined3** [comment]
Thank you very much @Rem0o.

I will wait for your reply, and test it as soon as you post it.

**Comment by Rem0o** [comment]
[LibreHardwareMonitorLib_WithHX1500.zip](https://github.com/Rem0o/FanControl.Releases/files/9903735/LibreHardwareMonitorLib_WithHX1500.zip)

Make sure you got the Corsair PSU section enabled in sensor settings.

**Comment by matchabrined3** [comment]
> [LibreHardwareMonitorLib_WithHX1500.zip](https://github.com/Rem0o/FanControl.Releases/files/9903735/LibreHardwareMonitorLib_WithHX1500.zip)
> 
> Make sure you got the Corsair PSU section enabled in sensor settings.

Thank you, testing now.

**Comment by matchabrined3** [comment]
> [LibreHardwareMonitorLib_WithHX1500.zip](https://github.com/Rem0o/FanControl.Releases/files/9903735/LibreHardwareMonitorLib_WithHX1500.zip)
> 
> Make sure you got the Corsair PSU section enabled in sensor settings.

I swapped out the .dll

No fans are being detected now.

I click "Refresh Sensors Detection"

And It says "LibreHardwareMonitor could not initialize or has no sensors."

**Comment by matchabrined3** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9903841/log.txt)
Here is the log file.

**Comment by Rem0o** [comment]
[LibreHardwareMonitorLib_WithHX1500.zip](https://github.com/Rem0o/FanControl.Releases/files/9903894/LibreHardwareMonitorLib_WithHX1500.zip)

We got further, but the code crashes when trying to read the PSU name and ID. There was an unsafe array access, I fixed that in the version above.

**Comment by matchabrined3** [comment]
Thank you. Testing now.

**Comment by matchabrined3** [comment]
@Rem0o  

Tested.

No crashing now, but it does not pick up the PSU.

I tried the Assisted Setup, and Refresh sensors detection. Both failed to pick up the PSU.

I dragged and dropped the .dll into the .exe version of LibreHardwareMonitor, and the HW1500i does come up in LHM.

@Rem0o  any ideas?



I've got the PSU running in single rail mode. Would that make a difference?


I've attached the latest log for you:
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9904068/log.txt)

And a pic of the psu in LHM
![002  corsair in lhm](https://user-images.githubusercontent.com/117102976/199088903-5f83d667-ff05-4698-b067-6e7a5cf9963e.PNG)

**Comment by Rem0o** [comment]
In FanControl, does it pick up the speed sensor in the speed section?

**Comment by matchabrined3** [comment]
> In FanControl, does it pick up the speed sensor in the speed section? Or any temperature in a temperature drop down? Like VRM and Case. 

Here are the controls and speeds.
I'm not sure what Fan 4 and Fan 5 are. They don't exist. I've turned them all the way up to reflect that.


![image](https://user-images.githubusercontent.com/117102976/199090342-d486b9f5-76a6-432c-b532-97695993a843.png)

How do I get a 'temperature in a temperature drop down'?


>The fan won't be controllable from FanControl as the PSU stuff in LHM doesn't provide any command to control the fan itself, only monitor the various sensors. In any case, you _WONT_ have a control card for your PSU.

I am able to control fan speed with iCUE, but the minimum speed via their software is 40%, which is like 900 rpm and very audible. I'm looking to control it at a steady 400 RPM, but thats not possible with their software.

If it can be controlled by iCUE, surely it can be controlled via other means? 
I plugged a usb C -> internal usb 2.0 cable from the PSU to the motherboard.  So surely it can be controlled.

**Comment by Rem0o** [comment]
Create a fan curve, like a graph from the bottom right + button, then select a temperature from the drop down of the graph card.

**Comment by matchabrined3** [comment]
> Create a fan curve, like a graph from the bottom right + button, then select a temperature from the drop down of the graph card.

Testing now.

**Comment by matchabrined3** [comment]
![image](https://user-images.githubusercontent.com/117102976/199095469-d4333afe-abde-4576-bfda-0bf987be5ef8.png)

Yes the temperature sensors do show up.
Great work.
Thank you.

**Comment by matchabrined3** [comment]
> ICUE is proprietary from Corsair. The API is not public. Corsair doesn't want third party to mess with their stuff. What LHM got is most likely derived from the HWMon stuff on Linux, which most likely was reverse-engienered the best they could. What we got is not 100% of the features on ICUE.
> 
> If your end goal is to control your fan on your PSU, you won't be able to do so from FanControl or any derived LHM work. That is until the protocol to control the fan is found, and that it is made public somehow. Only then the community will be able to implement it in various third-party stuff, like LHM/FanControl.

That's very good to know.
Thank you for your help.

**Comment by matchabrined3** [comment]
@Rem0o  Shall I try and push the .dll that you have created to the latest version of FanControl?

You have added support for a new PSU! :)

**Comment by Rem0o** [comment]
Opened a PR with the changes. Should get merged in at some point.

Thanks for the testing.

**Comment by aiac** [comment]
https://github.com/CorsairOfficial/cue-sdk/issues/13
