### ISSUE TITLE
Create Custom Sensor File fails

### ISSUE THREAD

**Issue by foreachthing** [Rem0o/FanControl.Releases#1235]
After FC stars with Windows, try to create a Custom Sensor FILE. It tries to store the file in c:\windows\system32.
After restarting FC, manually, it stores the file in app directory. After reboot, that file does "not exist" anymore. FC tries to load the non-existent file in c:\windows\system32.

Using Win11, latest FC V135.

**Comment by foreachthing** [comment]
After FC stars with Windows, try to create a Custom Sensor FIILE. It tries to store the file in c:\windows\system32.
After restarting FC, manually, it stores the file in app directory. After reboot, that file does "not exist" anymore. FC tries to load the non-existent file in c:\windows\system32.

Using Win11, latest FC V135.

**Comment by Rem0o** [comment]
What is the start in folder for the task in the task scheduler?
![image](https://user-images.githubusercontent.com/14118956/199106854-f5c974b3-96ec-4bc1-aa97-927bccc67a95.png)

**Comment by foreachthing** [comment]
Oooh!
I played with that because I didn't want the dos window to open.
So, "Start in" was empty ... then cmd starts in c:\windows\system32! Doh!
Thanks for the hint!
