### ISSUE TITLE
Starting with Windows sets the fan speeds to 0 temporarily before fan curve is applied

### ISSUE THREAD

**Issue by integralfx** [Rem0o/FanControl.Releases#124]
Specs:
* FanControl v63
* B550 Aorus Pro V2

**Comment by Rem0o** [comment]
All fans? Gpu fans?

**Comment by integralfx** [comment]
Just the fans that have a fan curve applied to them

**Comment by Rem0o** [comment]
If you remove start with windows, and start it manually at startup, same behavior?

**Comment by integralfx** [comment]
Yep, manually starting does the same thing

**Comment by Rem0o** [comment]
While the program is running, when you toggle off one of those fans that gets set to 0, what % does it goes to by default?

**Comment by integralfx** [comment]
Do you mean disabling the fan curve? I have them set to 50% in BIOS so that's what it gets set to.

**Comment by Rem0o** [comment]
Old issue, closing.
