### ISSUE TITLE
Info : Lost fans speed sensors after sleep/wake up on windows => solution that works in my case

### ISSUE THREAD

**Issue by snakesrules94** [Rem0o/FanControl.Releases#1240]
**Describe the bug**

Fan speed sensors not showing after sleep / wake up .
Behaviour ok if reboot

**Relevant hardware specs and setup**

Gigabyte B660M DS3H DDR4 / Intel 12th gen I5 12600KF

**Description**

Hi all, like many peoples , i have the problem that after wake up from sleep mode ( win 11 22H2 ) , Fan control ( latest version ) is loosing all my fans speed sensors and show an error windows saying that sensor are not found . If i reboot the computer , everything if fine again until next sleep / wake up session

**My solution**

I found a solution that seems to works for me : i've downgraded the bios !!
I was until now with the F20a version , and tried the F20 ( official version as F20a was a beta release ) ==> no changes
My MB was delivered with F5 version , i then tried the F6 version on Gigabyte support ==> it works 👍 

F6 seems to be the latest version before they start to add Intel 13th gen support. As i have a 12th gen , this is not an issue for me and i can stay with the F6 version. it seems that there is something broken on that point with the F20 bios series or maybe an issue with the couple F20 bios / Intel 12th gen CPU .

Anyway , if it can help some of you , have a look on your bios version if you have this speed sensor loss issue .
As we used to say : latest is not always better :-)

**Comment by Rem0o** [comment]
Good to know. Will close as its not an open issue.
