### ISSUE TITLE
[Feature Request]: Linear map curve

### ISSUE THREAD

**Issue by thghca** [Rem0o/FanControl.Releases#1251]
I's be nice to have way of mapping fan power range to another fan power range.
Fans below a certain value do not start and above a certain value they become very noisy. These values are very different for each fan, and because of this, you have to duplicate curves with offsets. Offset almost does the job but clips upper values.
So I propose a separate curve for linear interpolation of one interval to another.
As an alternative - completely replace offset with two values: the upper and lower borders and make the same map function.

**Comment by chli1** [comment]
I think the same way. Maybe it's enough to define a min/max fan speed on the controls and then map and adjust the input values from the curves accordingly.

E.g. you can define 50% max fan speed for CPU fan control; if reading 80% from the connected curve this will result in -> 80% input x 50% max=40% effective fan speed.

This way you can use a single normalized curve with 100% being the maximum speed you would ever want to apply to a fan and let the controls decide at what actual speed the fans should run at 100% input.
