### ISSUE TITLE
Asus Rog strix Z690 hero cpu fans do not seem to start up?

### ISSUE THREAD

**Issue by DannyDarth** [Rem0o/FanControl.Releases#1252]
**Describe the bug**
I have an Asus Rog Strix z690 hero motherboard with a 12900k cpu. Fan Control doesn't seem to change the fan speeds at all on 
any cpu temp source.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No log

**Relevant hardware specs and setup**
Asus Rog Strix z690 hero
i9-12900k

**Comment by Rem0o** [comment]
Seem? You got to give a clearer picture. 

Screenshot?

**Comment by DannyDarth** [comment]
you need a screen shot of the list of cpu's?
![image](https://user-images.githubusercontent.com/81840598/200128308-5236386f-d90e-4502-ac6a-d2b37620d9a0.png)

**Comment by Rem0o** [comment]
Well you set your graph to be 100% for all temperatures?  If it wouldn't respond, you would get a question mark in the control card.

**Comment by Rem0o** [comment]
No answer after 10 days, closing.

**Comment by DannyDarth** [comment]
Sorry i didn't understand the question.

**Comment by Rem0o** [comment]
The graph in the screenshot you sent doesn't make sense. It's a all maxes out graph to 100% for all temperatures.

You said

> Fan Control doesn't seem to change the fan speeds at all on
any cpu temp source.

While the graph you sent doesn't set different speeds based on temperature.

**Comment by DannyDarth** [comment]
> The graph in the screenshot you sent doesn't make sense. It's a all maxes out graph to 100% for all temperatures.
> 
> You said
> 
> > Fan Control doesn't seem to change the fan speeds at all on
> > any cpu temp source.
> 
> While the graph you sent doesn't set different speeds based on temperature.

I manually set it to 100 to see if i would hear a change in the speed the fan would go for the cpu, but i heard no change in speed.

**Comment by Rem0o** [comment]
What about those numbers:
![image](https://user-images.githubusercontent.com/14118956/201939699-4351ba8b-d55d-4337-be3f-9067974605da.png)

**Comment by DannyDarth** [comment]
Yes it says its going up but im not hearing a change in sound. Back when i first built the pc the fans would ramp up. But i have since taken armoury crate off and disabled it in the bios. Its bloatware to me.
