### ISSUE TITLE
[New Requirement] Different weight in the average function of the Mix curve

### ISSUE THREAD

**Issue by XieZhuoJun** [Rem0o/FanControl.Releases#126]
Hi Rem0o, thanks for the amazing tool. It works perfect in my pc. Though I have an idea for the average function of the Mix curve. 

Do you think if its possible to add weight for input curves? For example, I have fan curve A with weight 0.2 and value 15, and curve B with weight 0.8 with value 60, then the output would be 51 instead of 37.

This would work when a I want to control a fan according to the temprature of both GPU and CPU, but it could be more important for CPU, so I can set a higher weight for the CPU curve.

**Comment by Rem0o** [comment]
Well why don't you simply use a max function and set the curves for both your CPU and GPU accordingly?

Or, use the Sum function and weight the % of each curve to whatever your linking, will do the same thing.
