### ISSUE TITLE
Control Fan cannot control other sensor

### ISSUE THREAD

**Issue by NTAmmar** [Rem0o/FanControl.Releases#1263]
> See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

![SharedScreenshot](https://user-images.githubusercontent.com/92214498/200595440-6166dffc-f386-4225-8645-9ac1e8737c48.jpg)

i found abug or iissue, as you can see the INTAKE only Control fan #2 or in my motherboard it control CPU OPT. if i pair to other fan (1 3 4 5) it still control the fan no 2, not the choosen fan (1 3 4 5)
it same as other control, only control the sensor below it
CPU only fan #1
Exhaust only fan #3

my mother board are ga-Z97X-Gaming 3

_Originally posted by @NTAmmar in https://github.com/Rem0o/FanControl.Releases/discussions/1262#discussioncomment-4087460_

**Comment by DfrostX** [comment]
Hi NTAmmar,

I'm not sure what you are trying to do, but you cannot pair a control # with another fan than the one it is hardware tied by the controller.

From your image, Control 1 is for you CPU_FAN, so it can ONLY control that fan header. The speed you assign is just RPM reading (speed feedback). Even if you assign another reading then the one it belong, it will still not control it.

So control 1 cannot control CPU_OPT, but only CPU_FAN  for CPU_OPT, you need to use control 2.

My guess is as is:

Control # -- FAN NAME -- SPEED reading
Control 1 -- CPU_FAN    -- FAN 1
Control 2 -- CPU_OPT    -- FAN 2
Control 3 -- SYS_FAN 1 or 2 or 3 (not sure which, maybe all at the same time) -- FAN 1 or 2 or 3

**Comment by Rem0o** [comment]
@DfrostX  answered perfectly.

Closing.
