### ISSUE TITLE
Tray icon is very hard to read with Windows Light theme enabled

### ISSUE THREAD

**Issue by crafty35a** [Rem0o/FanControl.Releases#127]
The system tray icon text can be very difficult to read when the Windows 10 Light theme is selected. Can you auto-adjust the text color, or give us an option to change it?

**Dark theme**
![image](https://user-images.githubusercontent.com/1082003/105067014-516cd280-5a4d-11eb-8b72-9d99ad903717.png)

**Light theme**
![image](https://user-images.githubusercontent.com/1082003/105066884-37cb8b00-5a4d-11eb-8965-80078673ec85.png)

**Comment by Rem0o** [comment]
Will sync to Windows with the next update. Might as well add an option for dark mode to follow system preferences.

**Comment by Rem0o** [comment]
Fixed.

**Comment by crafty35a** [comment]
One thing I've noticed in the new release- the tray icon text is determined by the Windows "default app mode" setting. But that setting doesn't control task bar color. So I think the tray icon text needs to be based on the "default Windows mode" setting instead.

**Comment by Rem0o** [comment]
Sad part is, I'm using https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uisettings?view=winrt-19041 to get the Windows color, but default Windows mode is not available from that API. I will have to find another way to get access to it, probably a registry key.

**Comment by crafty35a** [comment]
You may have already found this, but in the registry it's Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize "SystemUsesLightTheme"

**Comment by Rem0o** [comment]
Oh Windows.... *sigh*

**Comment by Rem0o** [comment]
V65 now reads the proper registry key
