### ISSUE TITLE
No More Corsair Commander Pro Plugin?

### ISSUE THREAD

**Issue by ABO896** [Rem0o/FanControl.Releases#1272]
Has the Corsair commander pro plugin been discontinued?
The repo seems to be gone and its a huge bummer because without it fan control cant detect my case fans, only my CPU fans. Any help would be appreciated.

**Comment by xmoki** [comment]
while i still have the files and i'm using them, i would like to know that happened? did Corsair asked to be deleted or what?

**Comment by Rem0o** [comment]
^ No idea, but the guy who maintained the repo said he had issues, and after a while the repo got deleted completely.
