### ISSUE TITLE
Missing Tray Icon With "Start With Windows"

### ISSUE THREAD

**Issue by JMS-Projects** [Rem0o/FanControl.Releases#1277]
When Fan Control starts with Windows, there is no tray icon for the program. I check task manager and see that the Fan Control process is running. However, I have no way of accessing the UI. I have the "Start with Windows" option checked. I do NOT have the "Start minimized" option checked. Even so, the UI does not open on startup, nor does a tray icon appear. If I end the task, then run the program manually by opening FanControl.exe, then the UI opens normally and the tray icon appears.

Not sure if it is relevant, but I am using a standard non-admin windows account. I have configured the task in windows task scheduler to run with the admin account regardless of whether that user is logged in. However, the issue occurs if I log into the admin account as well.

Log File: 
https://drive.google.com/file/d/1aZ4sYM_1-8Vg5jcsFzP4RFWchlF5SVI5/view?usp=share_link

Specs: 
Fan Control Version 136
Windows 10 Education, version 21H1
https://pcpartpicker.com/list/MJ2wpH

**Comment by Rem0o** [comment]
I believe your problem is that the process must run on the same user that the UI will be displayed on.  If the user set the in task scheduler is different than the logged on user, you won't have access to the UI.

**Comment by gf9276** [comment]
I also have this problem. The same user will not automatically appear the UI when he or she starts up

**Comment by Rem0o** [comment]
@gf9276  What delay you got with Start With Windows?

Also what user appears here:

![image](https://user-images.githubusercontent.com/14118956/202206274-66472ea7-f232-4b85-9f58-f772de66cd14.png)

**Comment by gf9276** [comment]
> @gf9276 What delay you got with Start With Windows?
> 
> Also what user appears here:
> 
> ![image](https://user-images.githubusercontent.com/14118956/202206274-66472ea7-f232-4b85-9f58-f772de66cd14.png)

Sorry, my question seems a little different. After my computer is turned on, the software does not automatically run, but I set "Start With Windows".
![F~O}XAUQ}GHHF M6R%EX7V](https://user-images.githubusercontent.com/45392113/202211046-18115c52-34f1-4f97-a48f-29451dfc184c.png)

**Comment by Rem0o** [comment]
Set your delay to 15-30 seconds.

**Comment by gf9276** [comment]
> Set your delay to 15-30 seconds.

Thank you very much. The problem has been solved.

**Comment by JMS-Projects** [comment]
> I believe your problem is that the process must run on the same user that the UI will be displayed on. If the user set the in task scheduler is different than the logged on user, you won't have access to the UI.

This was the issue. The issue seems to arise when you choose "run task whether user is logged in or not".
