### ISSUE TITLE
Auto curve set min fan speed but high temperature in Version 136

### ISSUE THREAD

**Issue by msylgj** [Rem0o/FanControl.Releases#1278]
Auto curve set min fan speed but high temperature. like this pic blow. It can work since config been changed, but slowly down to min value. 
Hardware: 
 - M-board: MSI Z390 
 - CPU: intel 9700k
 - GPU; Nvidia 2080 (colorful)
Setting: [Sensors.zip](https://github.com/Rem0o/FanControl.Releases/files/9996956/Sensors.zip)

![image](https://user-images.githubusercontent.com/1388852/201516724-4b2b7d4b-bfe9-4479-bcff-d68973f16d70.png)

**Comment by msylgj** [comment]
testing net6 version. seems to be ok. I will close this issue after test.

**Comment by Rem0o** [comment]
You did not hit the load temperature, auto will only ramp up if you get close.
