### ISSUE TITLE
Do not display sensor cards, Gigabyte Z390 M GAMING-CF

### ISSUE THREAD

**Issue by xabelgul** [Rem0o/FanControl.Releases#128]
Hello,
[FanControl-log.txt](https://github.com/Rem0o/FanControl.Releases/files/5843978/FanControl-log.txt)

First of all I thank you for taking the trouble to make a new program from scratch that reflects the philosophy of the aged but beloved SpeedFan.
In my system, Gigabyte Motherboard Z390 M GAMING-CF draws my attention the fact that Fan Control does not have any cards associated with any sensor but is able to read their values to choose which to display as a tray icon.
As a consequence, as you well know, it is not possible to link them to any fan to control their speed.
I attach FanCntrol_log in case it is helpful.

Thanks for your interest and attention.

**Comment by Rem0o** [comment]
Well, that means your SuperIO chip isn't supported by LibrehardwareMonitor. Until support is added there, nothing I can do.

**Comment by xabelgul** [comment]
Thanks for your attention and congratulations for your work!
Best regards

Javier

En Wed, 20 Jan 2021 23:46:42 +0100, Rem0o <notifications@github.com>  
escribió:

>
> Well, that means your SuperIO chip isn't supported by  
> LibrehardwareMonitor. Until support is added there, nothing I can do.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
