### ISSUE TITLE
Launching FC crashed PC

### ISSUE THREAD

**Issue by skenzer** [Rem0o/FanControl.Releases#1280]
### Discussed in https://github.com/Rem0o/FanControl.Releases/discussions/1279

<div type='discussions-op-text'>

<sup>Originally posted by **skenzer** November 13, 2022</sup>
I was doing some benchmarking and quite FC and other apps during the tests. I went back to launch FC and my pc immediately crashed and restarted.
I have attached the error log for reference.
Thanks much!
brad
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9997633/log.txt)
</div>

**Comment by Rem0o** [comment]
Seems like it has issues with storage. Do you use any storage sensor? If not, I would untick the storage sensors in Sensor Settings.

**Comment by skenzer** [comment]
ok, thank you. I will try that.
