### ISSUE TITLE
Taskbar Display Temp Erroneus

### ISSUE THREAD

**Issue by Symtrips** [Rem0o/FanControl.Releases#1281]
I just upgraded to an Intel i5-13600kf and now fan control shows the temperature data for CPU Core #3 Distance to tjmax as the current temp in the task bar despite that sensor not being selected for any of my curves. Is there a way to force using the CPU package temp?

**Comment by Impact123** [comment]
This can be configured in the sidebar
![image](https://user-images.githubusercontent.com/899193/201795115-1e5bc35e-91c5-4167-ba07-8b49c5274c89.png)

**Comment by Rem0o** [comment]
@Impact123  answered it.

Closing
