### ISSUE TITLE
CPU suddenly gets very hot

### ISSUE THREAD

**Issue by MaxxaMTrasher** [Rem0o/FanControl.Releases#1282]
I came across FanControl several weeks ago and created three different fan curves (CPU, GPU and case fans) for my system. I was very happy with the result! Even under full load, the temperatures of both the processor and graphics card never rose above 80°C.

Unfortunately, for a few days now I have had the problem that **the fan curve for the CPU is no longer working properly**. I haven't changed anything on the software side, just installed the normal Windows- and driver updates as always. Since then, at least I think so, the fans of my CPU AiO water cooling system have been turning up and down and no longer run as constantly as before. **The CPU temperature also reaches almost 100°C** at its peak! Can someone here confirm / reproduce this problem and maybe already have a solution ready?

Of course, I have already monitored the parameters of my system with the help of various programs (TaskManager, HWMonitor, etc.), but could not find any abnormalities. Is it possible that "my" current Windows version is not compatible with the current version of FanControl?

I use: **Windows 11 Home, 21H2, build 22000.1281, Windows Feature Experience Pack 1000.22000.1281.0**

![Screenshot (2)](https://user-images.githubusercontent.com/118440859/202428294-b997405d-0aef-4a0a-b00b-5755f82a7d55.png)

**Comment by Rem0o** [comment]
Just from your picture we can see the problem: 
![image](https://user-images.githubusercontent.com/14118956/202556267-b03dc509-7d62-4dde-be2c-7f498dbd0ec2.png)

Your CPU control is overridden by something else, or is not controllable by FanControl. Driver updates and Windows updates can mess with FanControl being "compatible".   Make sure you got no "smart" control enabled for your CPU, like a fan curve in your BIOS or something similar, if that rings a bell.
