### ISSUE TITLE
Hide hidden fans

### ISSUE THREAD

**Issue by nbolton** [Rem0o/FanControl.Releases#1285]
Fan #2, #3, and #5 are not connected and never will be. They're marked has hidden, but I wouldn't say these are actually hidden.

How about a feature that actually hides the hidden fans rather than making them appear disabled.

![image](https://user-images.githubusercontent.com/313427/202686163-812eeb1d-7901-4578-b06e-e1e353b9962f.png)

**Comment by DfrostX** [comment]
You can, just remove the checkmark in the "show hidden card" ckeckbox.

![Hidden](https://user-images.githubusercontent.com/70845235/202695853-af3faafb-3fd6-42ac-922b-3f49f67a4e1c.jpg)
