### ISSUE TITLE
Fan at 100% but not max RPM

### ISSUE THREAD

**Issue by dadodasyra** [Rem0o/FanControl.Releases#1286]
**Describe the bug**
When my Fan CPU is at 100% (either manually or automatically set by FanControl its stucked at 570RPM~. And when I disable the control from Fan Control it can go at more than 550 RPM with 3x less "power" 
![image](https://user-images.githubusercontent.com/44753923/202757928-f0ba8c8d-2f59-461d-9ff2-22b43e01a073.png)
![image](https://user-images.githubusercontent.com/44753923/202758022-f5da99f6-55ae-4d85-bc30-acdd11a5774d.png)
This cause my CPU to overheat because the fan can't really go faster with FanControl.
I already repair controllers, redid the stop test and start test. The issue is still here

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No logs

**Relevant hardware specs and setup**
Here's the CPU Fan https://www.amazon.fr/gp/product/B09K7SHXJJ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by Rem0o** [comment]
You got an Asus motherboard right?  I would be ready to bet you are using a "silent" mode somewhere, either in your BIOS or in a Asus software somewhere. 

Asus modes "limit" the available RPMs artificially with these modes, causing exactly what you describe.

**Comment by dadodasyra** [comment]
Yes I did and I probably activate it somewhere in AI suite
![image](https://user-images.githubusercontent.com/44753923/202768306-cabe21e6-b17e-45ca-b2d5-11a3b9458216.png)
The profile was on Silent but not the tick box under. Tried to switch it but (at least withotu reboot) it does not seems to fix something

**Comment by dadodasyra** [comment]
The fact is that Asus as so much trash software that maybe I enabled something else on another soft of them and desinstalled it since it.

**Comment by Rem0o** [comment]
That's where your problem is, somewhere in there. Can't help you much more than pointing that out. Maybe look around other issues with keywords like "RPM" and "ASUS" and "SILENT".

**Comment by dadodasyra** [comment]
![image](https://user-images.githubusercontent.com/44753923/202853100-9e2e9b00-53ff-429e-8c2f-a11a4f27d741.png)
After a "reboot" (in fact I did an hibernate) It works, thx
