### ISSUE TITLE
Add language localization

### ISSUE THREAD

**Issue by FrannDzs** [Rem0o/FanControl.Releases#1287]
I would like to translate the interface into Spanish. Do you take multilanguage into consideration? I know it's not a matter of life and death but it's not a bad thing.

**Comment by DrSpaniel** [comment]
> Language is kind of a rabbit hole I don't really want to get into. Had requests for a least 10 different languages. 
> 
> I wouldn't be able to reliably have a translator per language every time I add/modify a label. That would either 
> 
> a) slow me down terribly
> 
> b) provide badly/not up to date translations 
> 
> 
> 
> I would hope the program is simple enough to be maneuvered around even if English is not your native tongue.

hey, I speak fluent Spanish and French. i'd be willing to translate if you'd like :)

**Comment by Rem0o** [comment]
@FrannDzs  I'm talking from experience, as I did it before in a professional setting. Even in the best case scenario, It's a lot of maintenance.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.i18n
