### ISSUE TITLE
Support user replacing the librehardwaremonitor files with nightly builds

### ISSUE THREAD

**Issue by thewan056** [Rem0o/FanControl.Releases#1288]
I've been checking in every now and then on LHWmonitor and I noticed they added support for my motherboard in the nightly builds. I have tested it and I can see Fan Speed RPM and Percentage, as well as all the necessary temperature sensors. The current release version has none.

As we have no idea when LHWmonitor will release a new release version with that new hardware support, then FanControl needs to integrate that latest release version and we don't know when that will come out either. 

So I suggest to allow the more adventurous users with more recent hardware to replace the LHWmonitor files in a FanControl release with the latest LHWmonitor nightlies that support their motherboard so that they can test them early and enjoy your software earlier, and reduce the amount of time suffering when using their mobo manufacturers software from hell.

Yes I did try doing the above already. I took the latest nightly files and replaced them in the current release of FanControl and nothing showed up.

**Comment by Rem0o** [comment]
Well, you can, and you did. Just replace the LibreHardwareMonitorLib.dll with the one from the nightly.  
If FanControl starts, then it worked, and it uses that new dll. 

When I update FanControl, this is exactly what I do. I just pick the latest DLL, make sure it didn't add any breaking change, then publish it as is.
