### ISSUE TITLE
Fan controler not detecting fans on MB

### ISSUE THREAD

**Issue by Tkey2** [Rem0o/FanControl.Releases#1289]
Hello ,

My windows just updated and after logging back in the Fan controller no longer detecting the fans plugged in to the MB

It does detect graphic card and also water sensor on the commander core.

Was working perfectly fine before this stupid update

How i can fix it ?

Thank you

**Comment by Rem0o** [comment]
Give your computer an full reboot, and start from a fresh FanControl "install" (folder).

**Comment by Dajova** [comment]
Uhuh... and what now? It's been stuck like this for a full 10m without progressing.
![image](https://i.imgur.com/mGQI7VT.png)
