### ISSUE TITLE
Updated to V137 and now getting the following error "Could not load the configuration. An unexpected error has occurred and has been added to the log file."

### ISSUE THREAD

**Issue by Zaerroeh** [Rem0o/FanControl.Releases#1293]
**Describe the bug**
Updated to V137 and immediately got the following error after the application restarted "Could not load the configuration. An unexpected error has occurred and has been added to the log file." My fan curves are gone and the applications settings have changed to default, ie. light theme and default fan names.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
2022-11-19 2:21:10 PM: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider)
   at FanControl.ViewModels.MainWindowViewModel.<>c__DisplayClass129_0.<RestoreApplicationState>b__0()

**Comment by Rem0o** [comment]
Mind sharing the json file for your config that fail to load?

**Comment by DerJantob** [comment]
I have the same problem since the update.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/10047901/log.txt)
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/10047902/log_1.txt)
[json.zip](https://github.com/Rem0o/FanControl.Releases/files/10047905/json.zip)

**Comment by Rem0o** [comment]
@DerJantob  thanks I was able to find the issue. 

Reuploaded V137. Please download again, or run the updater.exe manually.

**Comment by DerJantob** [comment]
Hey, thanks for the quick help. However, I only got one step further. The configuration loads, but apparently it doesn't manage to load the time average sensor.

These errors occured while restoring the configuration:
• Missing sensor for time average sensor Time Average MaxCPUGPU
• Graph Fan curve SystemTemp, missing sensor With identifier: Time/Time Average MaxCPUGPU
if this error occurs when upon startup, try increasing your
startup delay.

Regards
Jannik

**Comment by chli1** [comment]
I have the same issue. Problem seems to be if a custom (average) sensor depends on another custom sensor. I have a custom "Mix" sensor to get my maximum value for the various mainboard temperatur sensors and another custom average sensor that uses that value as input and returns the average value for that. With v137 that stops working the the average custom sensor isn't shown any more.

**Comment by DerJantob** [comment]
I am also not able to close the program. I have to end the process with the task manager

**Comment by Mielie6005** [comment]
I have a problem where windows security doesn't allow the update as it sees it as a severe dangerous trojan virus.

**Comment by Rem0o** [comment]
@DerJantob With the latest version I was able to load the configuration you posted. Male sure you got the latest. Reuploaded since.

**Comment by DerJantob** [comment]
Oh, you're right, it seems to be working now. I tried updating the program a couple of times yesterday, but that did nothing. Maybe my PC just needed a reboot. Thanks for the help. Its is a really awesome program btw :)
