### ISSUE TITLE
Auto update triggers antivirus

### ISSUE THREAD

**Issue by haralla** [Rem0o/FanControl.Releases#1297]
Windows defender quarantined the Updater.exe after clicking on auto updater. Following detected:

Trojan:Win32/Bearfoos.A!ml

**Comment by chrissolo92** [comment]
I had the same warning in Windows Defender. Other virus scanners also warn about Updater.exe.
https://www.virustotal.com/gui/file/60b0569028238cddccfd3dfdee34262093358d06d2b9d30fc4c56e3a90dbf218?nocache=1

**Comment by perokopotato** [comment]
Me too

![image](https://user-images.githubusercontent.com/18622945/202895321-7b669599-093a-4a8c-814b-68b23e6f9046.png)

**Comment by WGOS** [comment]
Same. It's `Trojan:Win32/Wacatac.H!ml`

**Comment by alistairgd** [comment]
So, did Defender catch it, or is there a risk our PCs are infected?

**Comment by Dupanoodle** [comment]
![Screenshot_20221120_121149](https://user-images.githubusercontent.com/13904602/202901375-4e154f07-1c1c-4139-951b-d26a0994b191.png)

Same for me. Happened when I was prompted for the update. updater.exe has been quarantined and the update from v136 to v137 hasn't completed.

**Comment by DumbTrollface** [comment]
Same here

**Comment by dabm-git** [comment]
It seems that Rem0o has encrypted the file, which raises alarms, looking at the file in depth, it connects to google-analytics, @Rem0o  any explanation?

**Comment by radj** [comment]
I think the problem may be with the Updater since the [zip file](https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip) committed to the repo works without issues.

**Comment by Rem0o** [comment]
It happens every single time I update the updater binaries. Defender freaks out. Submitted for review already, but it may takes so time to propagate the whitelisting.

@dabm-git there is nothing encrypted.  There is a http call to increase an update counter on GA.

**Comment by DumbTrollface** [comment]
> It happens every single time I update the updater binaries. Defender freaks out. Submitted for review already, but it may takes some time to propagate the whitelisting.

I think it would be a good idea to mention this in the FAQ.

**Comment by Mielie6005** [comment]
I resloved thid for my pc. I copied my fan config in a different location than the fan control file and deleted fan control, reinstalled it, and loaded the fan config. It works fine now

**Comment by yashGhela** [comment]
Hi so has this issue been fixed? Is it safe to use?

**Comment by WGOS** [comment]
> Hi so has this issue been fixed? Is it safe to use?

I've updated today successfully without turning off Defender

**Comment by yashGhela** [comment]
ok mine is working too, looks like its all good

**Comment by Rem0o** [comment]
If anybody has any more issue please report, but this should be solved once everybody is on the new definition update.

**Comment by momala454** [comment]
avast is detecting fancontrol.sys as a vulnerable driver and is blocked

**Comment by Goopicious** [comment]
Hello! I downloaded from the latest archive under the "Installation" section. After running that zipped file in VirusTotal, it comes back with these two flags. Curiously, Microsoft Defender does not detect anything. I am not very tech savvy in this area but thought this was an issue worth reporting. I am very thankful for your hard work on this app. 
![1](https://user-images.githubusercontent.com/63078054/204623463-c851daee-a2af-4f23-8b90-9b478e02e845.png)
