### ISSUE TITLE
Update to version 137 triggers windows defender as trojan.

### ISSUE THREAD

**Issue by perokopotato** [Rem0o/FanControl.Releases#1298]
Update to version 137 triggers windows defender as trojan.
![image](https://user-images.githubusercontent.com/18622945/202895260-365bd5d1-1ea8-4c70-b6cb-64458c933bf1.png)

**Comment by St54Kevin** [comment]
Yep same for me 
![image](https://user-images.githubusercontent.com/448627/202895411-6c43069c-eade-4f17-be91-4c49c3dfdd94.png)

**Comment by xIUPITERx** [comment]
Same for me.

**Comment by xIUPITERx** [comment]
Dupe of #1297

**Comment by Rem0o** [comment]
Closing as @xIUPITERx  mentionned the dupe of #1297
