### ISSUE TITLE
No control over one fan

### ISSUE THREAD

**Issue by neilangierof** [Rem0o/FanControl.Releases#13]
Hey man. Thanks for the great app! I was wondering if there were any known issues or limitations - I'm having trouble getting one particular fan to work. It is one of two bottom intake fans and the app is just unable to control it at all, while the other one works just fine. Fans are all hooked up to PWM headers and set to AUTO in the BIOS.

**Comment by Rem0o** [comment]
Which SuperIO chip does your board has? Look in the log.

**Comment by neilangierof** [comment]
Is it this one?


Chip ID: Unknown Winbond / Nuvoton / Fintek with ID 0x8733 at 0x4E/0x4F
