### ISSUE TITLE
How to reset all settings and uninstall this program?

### ISSUE THREAD

**Issue by NathanZhengNaixian** [Rem0o/FanControl.Releases#130]
Dear Developer(s),

This app is great but I think I don't need the feature after all, thanks for programming it. Now I want to uninstall this app and set everything back, how to operate this? Select and delete is easy but what about the settings? will they keep attached or gone with the deleted file? I think the MSI dragon center and Afterburner is the most convenient way rather than setting up all curves etc.

BR

**Comment by Rem0o** [comment]
Close and delete, simple as that.
