### ISSUE TITLE
After switching back the user, main window will open

### ISSUE THREAD

**Issue by bobdig** [Rem0o/FanControl.Releases#1304]
A minor detail but non the less I report it.
If I am switching users on a machine (without signing out), if I am then switching back to the first (and main user), the Fan Control main window will open, with no reason. 
 
Thanks for this great utility.

**Comment by Rem0o** [comment]
Do you have a scheduled task when any user log on?

**Comment by Rem0o** [comment]
The trigger part is what I'm looking for. Technically it should be "at log on", which should only fire when you first log on, not everytime you sign change user. I may get that part wrong, as I didn't dive really deep on multi-users scenarios.

**Comment by Rem0o** [comment]
That's probably because if the program is running, and you fire it again, it will communicate to the already running instance, and show its window.  That's behavior I explicitly coded in, so that if you double click on the icon while the app is running, it shows the UI.

**Comment by Rem0o** [comment]
@bobdig  As a quick fix, if you always run the same config file, go to the "action" part of the task, and edit the following line

```
/C start /B FanControl.exe 
```

to 

```
/C start /B FanControl.exe -c yourconfig.json
```
Where yourconfig.json if your config file, whatever that is.  This should prevent the window from showing up.
