### ISSUE TITLE
Virus detected 

### ISSUE THREAD

**Issue by CurryOnPatat** [Rem0o/FanControl.Releases#1307]
My windows defender Says this is a virus
![image](https://user-images.githubusercontent.com/99186666/202929898-07459da1-8485-4a55-b1f8-799ce9bf2cfa.png)
https://www.virustotal.com/gui/file/60b0569028238cddccfd3dfdee34262093358d06d2b9d30fc4c56e3a90dbf218

**Comment by bfeist** [comment]
Yep. I just got the same 
![image](https://user-images.githubusercontent.com/662952/202931301-baedb2dc-be26-4402-9759-a8fdccf6ea86.png)

**Comment by Rem0o** [comment]
Duplicated of https://github.com/Rem0o/FanControl.Releases/issues/1297
