### ISSUE TITLE
FanControl detects only 5 of 6 fans.

### ISSUE THREAD

**Issue by HAse-ONE** [Rem0o/FanControl.Releases#131]
Hi

i just started to use FanControl and while i was setting it up with fan curves etc. i realized, that one case fan is missing. All my 5 case fans (Noctua NF A14 PWM) are connected via separate fan headers on the motherboard (MSI MEG X570 Unify) and they all show up on HWiNFO64. 

Is this a bug, or something on my end?

**Comment by Rem0o** [comment]
Not a bug, just missing support from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
