### ISSUE TITLE
Corsair HX1000i PSU not showing up in FanControl

### ISSUE THREAD

**Issue by chudungg** [Rem0o/FanControl.Releases#1310]
![Screenshot 2022-11-21 233359](https://user-images.githubusercontent.com/21027584/203119296-4db98345-ff42-4d55-b84a-fc25d5b277d8.png)
![Screenshot 2022-11-21 233307](https://user-images.githubusercontent.com/21027584/203119307-79998b7a-e006-424d-9041-77f9412d3410.png)

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/10059020/log.txt)

I read https://github.com/Rem0o/FanControl.Releases/issues/1233 
Could you make a version for hx1000i psu ?

**Comment by Rem0o** [comment]
Technically from the source code the HX1000i is supported.
If you open up LibreHardwareMonitor, do you get anything?

**Comment by chudungg** [comment]
- [ ]

**Comment by Rem0o** [comment]
I believe the rev2 of the HX1000i has been added in a few days ago: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/3aff4f0f47eedd23114c15179afc11065121f5fa

**Comment by chudungg** [comment]
yes, its showing up now . tk you

> Reference

**Comment by everdrone** [comment]
Not showing up for me as well, is that change in LHM merged into the latest FanControl release?

**Comment by Rem0o** [comment]
FanControl has the latest LHM commit.   Make sure you got your sensor settings to include the PSU.
