### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'NvAPIWrapper'

### ISSUE THREAD

**Issue by pheight57** [Rem0o/FanControl.Releases#1312]
So, after updating FanControl yesterday, I started getting the following error and it will simply not load. Not sure if it was that update or the updates for Windows and AMD Adrenalin that caused this one.

My system also has a PowerColor AMD Radeon RX 6900 XT Liquid Devil in it and has never had an nVIDIA GPU, so I am not even sure why we are searching for the NvAPIWrapper...Please see the log entry below. [Also, note, I went searching through the registry editor to try to fix the warning and note at the end of this entry, but was unable to locate the settings it is referencing under the Microsoft Fusion registry location.]

> 21-Nov-22 17:16:09: System.IO.FileNotFoundException: Could not load file or assembly 'NvAPIWrapper, Version=0.8.1.100, Culture=neutral, PublicKeyToken=310fd07b25df79b3' or one of its dependencies. The system cannot find the file specified.
File name: 'NvAPIWrapper, Version=0.8.1.100, Culture=neutral, PublicKeyToken=310fd07b25df79b3'
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.IsAvailable()
   at FanControl.Domain.ComputerAccessLayer.SetNvAPIWrapperSettings(SerializableNvApiWrapperSettings settings)
   at FanControl.App.<OnStartup>d__11.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Rem0o** [comment]
NvAPIWrapper is part of the software to support Nvidia cards. The software covers more stuff than what's needed for your specific computer, that's normal.

Do you have the NvAPIWrapper.dll in your FanControl directory?

**Comment by pheight57** [comment]
![image](https://user-images.githubusercontent.com/116587549/203381572-9c2f7fd7-8bd7-42be-9f96-f4257749f46b.png)

**Comment by pheight57** [comment]
I am not seeing one in the FanControl folder.

**Comment by Rem0o** [comment]
Well clearly it's missing, so download FanControl again and extract everything back into this folder.

**Comment by Rem0o** [comment]
@pheight57  Glad it was a quick fix. Enjoy and thanks a lot!
