### ISSUE TITLE
Manual control greyed out.

### ISSUE THREAD

**Issue by MiaaMii** [Rem0o/FanControl.Releases#1314]
Manual control doesn't work, they're all greyed out. 

My use case:

Motherboard: MSI X299 XPOWER GAMING AC (MS-7A91)
Chipset: Intel X299 (Kaby Lake)
CPU: Intel Core i7-7820X
GPU: MSI GTX 1080 Ti GAMING X (GP 102-350)

I tried to reinstall the program to resolve the error, nothin happened.

**Comment by Rem0o** [comment]
Toggle the switch on the control card?

**Comment by MiaaMii** [comment]
Problem solved 
I am dumb!

@Rem0o thanks for the reply

**Comment by Rem0o** [comment]
To the left of the greyed out slider.
