### ISSUE TITLE
computer crash

### ISSUE THREAD

**Issue by Davidy1313** [Rem0o/FanControl.Releases#1317]
Hey man, why does my computer crash every time I try to click ok? He is 6 years old, could that be the reason? TNX
![גהכ](https://user-images.githubusercontent.com/114259342/203673419-43dccf41-599e-4229-ba3f-45901ebaf649.png)

**Comment by Rem0o** [comment]
try and untick some categories, like memory and storage, and see if you get further.

**Comment by patrickli** [comment]
I have the same problem. For me I don't think it crashes, it just immediately shuts down. I tried unticking some of the options and it let me get pass this page, but when asked to reload the app and click yes, the system shutdown again.

**Comment by patrickli** [comment]
OK did some more testing. This happens when you click "Pair speed sensor automatically". Can be reproduced very reliably.

**Comment by Rem0o** [comment]
@patrickli  on a specific control or all of them?

**Comment by patrickli** [comment]
All of them

**Comment by Rem0o** [comment]
@patrickli  Can you simply set a control in manual mode and change its speed without it crashing?

**Comment by patrickli** [comment]
Yes I can. That's what I am doing right now.

**Comment by Rem0o** [comment]
You can what the "Pair speed sensor automatically" does manually:

Set every control to 60, make sure you got none hidden.
Set every control 1 by 1 to 20%.

**Comment by rknauber** [comment]
Wanted to say thanks for having this info here and that skipping the auto pairing resolved this issue for me as well. 7700k on a Gigabyte Z170 board, Corsair iCUE Commander Core with AIO and 6 fans, 4 sticks of Corsair RAM just for future reference of anyone stopping by this post.
