### ISSUE TITLE
Exclude version.json from configs

### ISSUE THREAD

**Issue by Cubox** [Rem0o/FanControl.Releases#132]
Hi,

I was about to submit a patch to fix this, but since the code is not here I'll open an issue.
![image](https://user-images.githubusercontent.com/479129/105641674-aceff380-5e85-11eb-95e2-bed55f22faf0.png)
version.json should be ignored here

**Comment by Rem0o** [comment]
But why do you have version.json in your folder?

**Comment by Cubox** [comment]
That's an excellent question.
I don't know. Where should the file be? I'll send a screenshot of the working directory

**Comment by Rem0o** [comment]
It shouldn't be anywhere, it's not in the zip.

**Comment by Cubox** [comment]
I think what happened is that I downloaded the repo as a zip, then ran Uploader.exe which downloaded everything for me, and created version.json somewhere

**Comment by Rem0o** [comment]
The repo has version.json located at root. You just need Updater.exe alone in a folder or the zip itself.

Closing.
