### ISSUE TITLE
Is there any way to keep the fan curve working without the app running in background?

### ISSUE THREAD

**Issue by straightstah** [Rem0o/FanControl.Releases#1320]
Just like in MSI Afterburner, where you can set the curve, hit the "firmware control mode" and you don't need the app to be running in background anymore

**Comment by Rem0o** [comment]
Nop.

**Comment by DrSpaniel** [comment]
> Nop.

is it possible to have it running in the background without the window open, similar to how steam or discord does?

**Comment by Rem0o** [comment]
@DrSpaniel  Yes, it will minimize to the app tray if you "x" the window.
