### ISSUE TITLE
[Asrock B550m Steel Legend] Extra fan header detected by FanControl

### ISSUE THREAD

**Issue by vitduck** [Rem0o/FanControl.Releases#1323]
**Describe the bug**
The MB has 6 fan headers according to manual. The Bios also shows 6 fans. 
CPU_FAN1
CPU_FAN2/WP
CHA_FAN1/WP
CHA_FAN2/WP
CHA_FAN3/WP
CHA_FAN4/WP

However, FanControl shows an extra fan, i.e Fan#7. This is not a bug per se. But I am curious where the fans is coming from. 
Also is there some way to know which Fan# corresponds to which fan header without manually speeding it up ? 

![AsrockB550m](https://user-images.githubusercontent.com/575950/204121205-039c6bb9-788e-4a19-8de4-6160b962c3d2.PNG)

**Relevant hardware specs and setup**
MB: Asrock B550m Steel Legend 
Windows 10 22H2
Fan Control: latest version (v137) 

Thanks for creating this software.

**Comment by Rem0o** [comment]
FanControl doesn't know motherboards really, but channels on the control chip that is on your motherboard. Most likely yours has 7 possible channels, but your motherboard only uses 6 of the available 7.

**Comment by vitduck** [comment]
Thanks for replying. 

Since this does not affect FanControl's operation, I would like to close this issue.
