### ISSUE TITLE
Regression(63->64): Tray Icon black on dark taskbar

### ISSUE THREAD

**Issue by pseisam** [Rem0o/FanControl.Releases#133]
"Tray icon temperature colors now match with Windows dark/light mode"

Just installed the new version 64 and my tray icon switchend from a readable white to not really readable black (windows with night mode turned off and fan control using the dark theme).

![grafik](https://user-images.githubusercontent.com/11456503/105647166-0109d080-5ea4-11eb-816c-6a87a242c267.png)

**Comment by Maarten-vdv** [comment]
Came here to say the same. I put my app in dark mode because it looks nicer, but I would like to keep the tray icon white foor readability.

**Comment by Rem0o** [comment]
Can you post your Windows theme config? Dark mode, light mode?

**Comment by pseisam** [comment]
Design is default

Colors:
Windows-Mode: dark
Default-App-Mode: light (switching this to dark fixes the color of the tray icon btw., but I don't want to default it to dark)

"Sync theme  with Windows" is turned of in fan control and Dark theme is chosen.

**Comment by Rem0o** [comment]
So it seems like I'm syncing to the Default-App-Mode and not the Windows-Mode, didn't think about having both of those settings different. Will investigate.

**Comment by glenpayne** [comment]
Same issue here, dark tray icon (showing temperature) isn't visible on dark taskbar, thanks for the attention to it ;)

**Comment by Rem0o** [comment]
V65 now reads the proper registry key.
