### ISSUE TITLE
[Bug] Minimum% value not being preserved on load

### ISSUE THREAD

**Issue by khift363** [Rem0o/FanControl.Releases#1335]
**Describe the bug**
If you apply a 'Minimum %' value to a fan, save the configuration, close the program, then reopen the program there will be no 'Minimum %' value applied.

There is a functional workaround to apply a flat and a mix to each fan that would need a minimum.

Before saving and closing:
![image](https://user-images.githubusercontent.com/37545815/205287146-18d7a11b-d72c-4e69-ae6a-f1764694bd14.png)

After reopening:
![image](https://user-images.githubusercontent.com/37545815/205287183-5cb282ec-48b5-420c-adda-441b62e9263a.png)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No error log was generated, the option for it is greyed out, and I don't see a way to force a log to generate although I could just be blind.

**Relevant hardware specs and setup**
Using an ASRock X670E Steel Legend motherboard, but the problem occurs both for fan headers on the motherboard and for the GPU fans as well.

**Comment by zme-ul** [comment]
spotted this issue too, left me scratching my head for a bit or who

**Comment by adomm420** [comment]
still happening with the latest update, minimums cleared on a startup of the app. this shouldn't take so long to fix.

**Comment by zme-ul** [comment]
I can confirm issue is fixed in ver 139

**Comment by adomm420** [comment]
> I can confirm issue is fixed in ver 139

it doesn't show v139 in releases.
