### ISSUE TITLE
Problem with 64 version.

### ISSUE THREAD

**Issue by romek71** [Rem0o/FanControl.Releases#134]
Hi Rem0o.

After launching the program I have a problem accessing the user interface and no icon in tray.On launching it generates a log.txt. file which I send you below.Version 63 works without any problems.

![screenshot 1](https://user-images.githubusercontent.com/67829150/106008644-cc6e6280-60b7-11eb-8f76-ae0995f55cca.jpg)
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5880996/log.txt)

**Comment by Rem0o** [comment]
Problem is you are on Windows 7, and I'm using some W10 specific features.

**Comment by romek71** [comment]
This is what I suspected. I'll stick with version 63 for now and don't plan to switch to win10.Thanks for a good program!!!!
