### ISSUE TITLE
Improvement: The color of tray icon

### ISSUE THREAD

**Issue by Sanczzg** [Rem0o/FanControl.Releases#1343]
This is not a big problem. When I'm using the FanControl without enabling "display tray icon temperature", which means that the dark theme setting of tray icon color does nothing, the little fan icon in tray bar is pure white. And when the Windows 11 is in light mode, the icon is almost invisible, as shown below:

![image](https://user-images.githubusercontent.com/55305469/205519629-906a00f4-3c64-4181-8155-312cd75c1e6a.png)

It won't affect any function of FanControl, but looks weird to me. An option of choosing a dark icon will simply solve this.

**Comment by Sanczzg** [comment]
Or probably an option of hiding tray icon also works. Once you set up all the fan curves, you just need it runs in the background and won't open it frequently.

**Comment by Rem0o** [comment]
Will make a black icon that will sync with themes.
