### ISSUE TITLE
AORUS 6750 XT unable to set fan speed through FanControl

### ISSUE THREAD

**Issue by DimkaTsv** [Rem0o/FanControl.Releases#1344]
I have simple issue. 
My 6750 XT fan speed cannot be set up through FanControl app. It can be set up with Afterburner and Adrenaline software though. 
But through Fan Control it just doesn't react even if i forcing it. As if there is some sort of misunderstanding between software and fan controller on GPU. 

Motherboard: Gigabyte B550M AORUS Elite
CPU: AMD Ryzen 5 5600X
RAM: 32GB Kingston Renegade 3600 16-20-20
GPU: Gigabyte AORUS 6750 XT 12 GB

![image](https://user-images.githubusercontent.com/9446187/205583534-500b3285-ebd9-40c4-9486-5a3e0c0827db.png)

**Comment by DfrostX** [comment]
See https://github.com/Rem0o/FanControl.Releases/discussions/596#discussioncomment-2619300

**Comment by Rem0o** [comment]
Known issue. No solution in sight. Closing.
