### ISSUE TITLE
Dark Theme got worse with v139

### ISSUE THREAD

**Issue by Dullson** [Rem0o/FanControl.Releases#1348]
Changes introduced in v139 degraded the readability of the interface in dark mode.

## Reduced text contrast
The usage of dark text reduces contrast and makes it harder to read. The outline of toggle switch is barely visible now, it's just a dot. Also textbox labels (like "Curve" above Target text in the picture) are more blended.

![example1](https://user-images.githubusercontent.com/5316261/205892726-9968810b-8384-448c-8ad4-38d2d23c6c23.png)

## Changed background colors and secondary color usage
I am not a big fan of this new greenish color but my preference aside, usage of the secondary color green on [X] button causes a bright-on-bright situation again and makes it hard to see. (I didn't pick these custom colors by the way, they are the default ones inherited from OS)

![example2](https://user-images.githubusercontent.com/5316261/205893970-8121b2ec-786f-4c7f-91be-87c088540609.png)

## Alternating layout colors
Lastly, I think the new dark text is applied dynamically based on the background color. This causes the text color to alternate between different elements and breaks the UI consistency.
The image below shows how the new window layout compares to the old one. The white text was used consistently on all elements before.
Now we are going: white window title -> black application title -> white control title -> black control card text -> white curves title and card -> again white custom sensors title into black card text

![example4](https://user-images.githubusercontent.com/5316261/205897166-a8a01ae2-0678-42d2-9f09-604bb69cfc2a.png)

If these changes are intended and here to stay, I would like this issue to become an enhancement request to add an option for the old dark mode. More options to customize theme colors would be even better!

**Comment by nicko88** [comment]
I had to look into something like this not too long ago.

I recommend skimming this, there are lots of ideas and ways to do this.

https://stackoverflow.com/questions/1855884/determine-font-color-based-on-background-color/62303960#62303960

The top couple solutions should work well enough, but if you want to dig deeper, there are even better ways to achieve even better results.  It's more complicated than it first seems because it involves how the human perceptual vision system works.

**Comment by Rem0o** [comment]
@nicko88  That's already how it mostly works, it's just that the "default" threshold to switch to from light to dark I'm using isn't really good.  Will tweak it.

**Comment by Rem0o** [comment]
Update to V140 and tell me how it goes. Threshold is much more biased towards white text now.

**Comment by Dullson** [comment]
Yes, it is very biased towards white right now but that is fine IMO, as I am not going for a cyan background when I use dark mode anyways. But the threshold is not balanced if you aim for a good breakpoint for readability in every scenario.

**Comment by Rem0o** [comment]
Where-ever I set my breakpoint, some people near that limit will be unhappy.  I feel like the current implementation works well enough, and if you want to go white cards, you'll get black text over it.
