### ISSUE TITLE
[Feature Request] Tray icon mouse-over improvements

### ISSUE THREAD

**Issue by CAKyPA** [Rem0o/FanControl.Releases#1349]
Hi,
It's nice to see more info on tray icon mouse-over behavior.
Like windows Task Manager tray icon.

Or like this:
Fan Control V139...
CPU temp: X
GPU temp: X
Fan X RPM: X

If possible adding Max, Min values to each lines would be nice too.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/207974976-994a2bbb-192f-4b1c-bb3b-78cf40835608.png)

You'll be able to have multiple icons.
