### ISSUE TITLE
FR Disable checking and prompting for updates on startup.

### ISSUE THREAD

**Issue by x0rtrunks** [Rem0o/FanControl.Releases#1350]
It's pretty common for applications that have an auto-update function to give the user some control over when and if updates are checked for and if notification is made. 

A range of options would be nice, like full silent auto update, download and notify, or manual check only.

Thanks

**Comment by mikicof** [comment]
Yes please, I second this one. My PC is half the time being used as a headless Steam Remote Play server, and when an update is available, it brings up the window in front of the screen and I'm unable to dismiss it or minimize it until I enter to my network via VPN, enter my PC via RDP and then update it so I can restart and go directly to the Steam Big Picture...

It would be fine to me a toggle to enable automatic update or even one to automatically apply updates in the background.

Thanks!

**Comment by Rem0o** [comment]
Will add it. In the mean time, you can simply type "999" in the DisablePopupVersionNumber field and it will do the trick:
![image](https://user-images.githubusercontent.com/14118956/212555153-f62561e2-b3bc-40e4-80f0-e9d381a8a35d.png)

**Comment by Requen** [comment]
i installed fan-control onto my tech-illiterate brother's pc and yeah he constantly nags me about the updates on boot-up and what to do. i however would like a "full silent no pop-up no confirmation auto update" like x0rtrunks already mentioned. because i also don't want to call my brother every few updates to tell him to update ;)

**Comment by hruzgar** [comment]
Yeah please!! It is really annoying. Just a Checkbox in the settings which says "Disable Update Pop-ups" would really be enough. I just want to update it, if i want to. That or auto update. But popups are really annoying. Even if there is a checkbox to don't show for the current version. I mean the next version will annoy me again.

**Comment by Rem0o** [comment]
Implemented a while back. Closing.
