### ISSUE TITLE
Fan omits control from program

### ISSUE THREAD

**Issue by rocapillon** [Rem0o/FanControl.Releases#1357]
Fan 3 never stops, the others do, thanks to this program I can put 1 and 3 to put only towards the cpu, and put the one that puts GPU to give air when the gpu needs, there is the possibility of stopping fan 3 or is it impossible?

![Captura](https://user-images.githubusercontent.com/22078482/206847725-e3e1d559-5aa0-42e8-abd9-c9e62146117d.JPG)
![2e4af384-a6de-45ef-b73a-e22802ff7f3b](https://user-images.githubusercontent.com/22078482/206849036-5baa9e38-9b44-4ecc-84da-a2f7104f47a6.JPG)

**Comment by Rem0o** [comment]
The only thing that might work is if you switch the header from PWM to DC mode in your BIOS, if that option is available.  Seen some cases where that works.

**Comment by rocapillon** [comment]
> The only thing that might work is if you switch the header from PWM to DC mode in your BIOS, if that option is available. Seen some cases where that works.

**Comment by rocapillon** [comment]
> The only thing that might work is if you switch the header from PWM to DC mode in your BIOS, if that option is available. Seen some cases where that works.

**Comment by rocapillon** [comment]
> The only thing that might work is if you switch the header from PWM to DC mode in your BIOS, if that option is available. Seen some cases where that works.

I fixed it by removing smart fan from bios, now I can put all of them at 0 rpm, but for safety, those of the cpu, I will leave them at a minimum of 750rpm

thz
