### ISSUE TITLE
Request, FC priority setting

### ISSUE THREAD

**Issue by shmrv** [Rem0o/FanControl.Releases#1358]
Is it possible to configure FC scheduled task priority?
For examle, Above normal? 

Export from Task Scheduler:
<Priority>4</Priority>

**Comment by Rem0o** [comment]
That's quite an obscure setting that isn't even available from the user interface in Windows.  Why exactly would you want to change it?

**Comment by shmrv** [comment]
Hello!

Export from Task scheduler.
Priority setting is missing in windows task interface.  Possible to change priority by import/export task xml.
"<Priority>4</Priority>" manually changed in my case.
On heacy load FC reacts better with this setting.

Thx alot for help.


<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2022-10-02T19:33:31.881+03:00</Date>
    <Description>Start FanControl at startup</Description>
    <URI>\FanControl</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <Delay>PT30S</Delay>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-949940232-3590970349-3235360653-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>4</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>cmd.exe</Command>
      <Arguments>/C start /B FanControl.exe</Arguments>
      <WorkingDirectory>C:\utils\FC\</WorkingDirectory>
    </Exec>
  </Actions>
</Task>

**Comment by Rem0o** [comment]
@shmrv the API I'm using has these listed.  Will take a look at "above normal", should be enough in high load scenarios for Fancontrol to not get starved.

**Comment by shmrv** [comment]
Thx, mate!
