### ISSUE TITLE
Disabling a fan curve sets fan speed to 40% instead of BIOS value (but not always)

### ISSUE THREAD

**Issue by pseisam** [Rem0o/FanControl.Releases#136]
- I have set 30% fan speed in BIOS fan curve for temperature 50 to 70 (arbitrary) and CPU is currently in that temperature range.
- I have a flat fan curve in fan control which sets the fan speed to 60% (arbitrary).
- I click on the button to activate the fan curve and the fan begins to spin up to 60%.
- I click the button again and the fan speed goes back to 40% instead of 30% (CPU still in same temperature range).

-> If I click the button multiple times I can get it to reset the fan to the 30% BIOS value.
-> It doesn't matter which type of fan curve is used (I tried flat and target).
-> All fans are affected (CPU and case fans)

Some infos:
- Windows 10
- Fan Control V64 and V65
- B550 chipset

Please tell me if you need any more infos.

**Comment by Rem0o** [comment]
When you disable, it reverts to automatic BIOS control mode, and I have no control as to what it does. Every motherboard on that aspect can be different, so I'm not really sure what you want me to change here.

**Comment by pseisam** [comment]
I am wondering if there is a bug that it doesn't go to BIOS control mode and instead sets it to 40%.
I come to that conclusion because it does work with the correct fan speeds if I click often enough (and I am not sure if it depends on the count of clicks rather than on the delay between clicks).

I will add a video later this day to the issue and if you don't see something wrong just close this post.

Thanks for your quick reply and effort you put into the tool :-)

**Comment by Rem0o** [comment]
Well it for sure doesn't set to "40%" or any arbitrary value like that.

**Comment by seiphr** [comment]
It might just be that your motherboard's SuperIO chip has a slow polling rate or doesn't reset itself to auto-control after the register control key is released (or perhaps does so after a timeout, which is longer than you expect it to be). It's most likely an issue in LHM rather than Fan Control.

**Comment by pseisam** [comment]
Ok, sounds reasonable that it is something about my Mainboard since no one else had complained about that yet and I tested other fan control versions like v52 too.

Nevertheless here is the promised video:
https://www.dropbox.com/s/mc2qkiqlwhuhfjr/fanspeed.mp4?dl=0

So it starts with the BIOS 32% than the 55% flat curve is activated. Then the curve is deactivated but it gets stuck at 40%. I activate the curve again and this this time the deactivation goes back to the expected 32% again.

I also left the PC with 40% and after half an hour it was still at 40%. So this is not just a delay.

So now after seeing this any further idea what the issue could be or any idea for a workaround? Maybe a BIOS setting?

Otherwise you might just close this issue since it is just a little annoyance and probably not relevant to many people.
