### ISSUE TITLE
FanControl loses its settings every time the system boots up

### ISSUE THREAD

**Issue by amiltonjr** [Rem0o/FanControl.Releases#1364]
I am currently using v139 but since 137 I guess every time the system boots up, all the settings are gone. Then I close all the many dialog boxes to load a previous saved configuration, then it works. Is anybody else experiencing the same issue? What do I do?

**Comment by Rem0o** [comment]
Have you extracted FanControl in a folder somewhere on your C drive?

If you look at the action in the scheduled task, does the location makes sense?

![image](https://user-images.githubusercontent.com/14118956/207204114-575edbaf-4d0c-476b-9154-1ebb60008120.png)

**Comment by amiltonjr** [comment]
> 

Yes, the location makes sense

![Screenshot 2022-12-12 224121](https://user-images.githubusercontent.com/7596915/207205343-673c65a7-72b0-4576-8689-e5275b39b7ec.jpg)

**Comment by Rem0o** [comment]
What kind of popups do you get at startup?

**Comment by amiltonjr** [comment]
I just rebooted the machine, First, it showed this:

![1](https://user-images.githubusercontent.com/7596915/207205892-c9a7a583-05da-4e55-b606-f67f25b96785.jpg)

Then the program closed itself when I clicked Ok. Then I clicked on the shortcut to open it up again and this is what is shown:

![2](https://user-images.githubusercontent.com/7596915/207206056-7f5ec04d-a28d-4b6e-8a0e-edd34df911ec.jpg)

![3](https://user-images.githubusercontent.com/7596915/207206097-cf3dced1-0be6-4cab-bc68-d1f99a33616d.jpg)

Now I want to load configuration, so it asks me if I want to discard, I confirm and then I select to load it:

![4](https://user-images.githubusercontent.com/7596915/207206246-05df95d5-e6e0-4cee-a999-29258ba0a11a.jpg)

This error shows up right after loading (sometimes, not every time):

![5](https://user-images.githubusercontent.com/7596915/207206415-748e1059-9ceb-4ee3-8794-24f0f7ef9ba1.jpg)

Closing the dialog box reveals the app running as it should:

![6](https://user-images.githubusercontent.com/7596915/207206499-8830c1a2-3b87-4435-a96b-0f794c59c713.jpg)

If I restart the machine, it is gone and I have to do the same steps again.

**Comment by Rem0o** [comment]
What kind of delay do you have set? 

![image](https://user-images.githubusercontent.com/14118956/207206827-93d1d5b9-c491-4174-9f02-22fcc98b1ad2.png)

**Comment by Rem0o** [comment]
1 and 5?  Try 30.

**Comment by amiltonjr** [comment]
I noticed a weird behavior: after it reached the timeout of 30 seconds and started to open up, the mouse cursor became laggy and barely responsive for a few seconds, like a system-wide stutter. That's something very unusual... My system is running from an NVMe SSD, not even a chance to be laggy though

**Comment by amiltonjr** [comment]
Yep, there's a CACHE file, and I was monitoring it for changes now, and it does reset whenever I close and re-open the app

**Comment by Rem0o** [comment]
Try and deactivate a few sensor sources. Keep CPU, GPU and motherboard, uncheck all the others.

**Comment by amiltonjr** [comment]
![1](https://user-images.githubusercontent.com/7596915/207210359-fc7d97b0-07f1-4a24-ad9d-29f2549db04d.jpg)

**Comment by Rem0o** [comment]
Seems like LHM has a problem initializing at startup.  That's basically the whole backend of the application which reads sensors etc.   

Any log.txt?

**Comment by amiltonjr** [comment]
It seems to be working now... I didn't know Corsair was causing issues here though

**Comment by amiltonjr** [comment]
It definitely is working now. However the mouse stutter problem is still there whenever the app is loading up. There's no point in making the whole system stutter like that.

**Comment by Rem0o** [comment]
^ do you got storage still ticked? On some system, the WMI request can make it stutter if you got spinning drives connected.

**Comment by amiltonjr** [comment]
I don't... further investigation needed

![1](https://user-images.githubusercontent.com/7596915/207214929-1e08cb08-8f6c-4e75-aa7f-c04a924f82b2.jpg)

**Comment by Rem0o** [comment]
Go one by one if needed, but one category must be causing that.
