### ISSUE TITLE
Hysterasis on the way down not working correctly, evga 3070ti

### ISSUE THREAD

**Issue by AvocadoGuy** [Rem0o/FanControl.Releases#1369]
I have an evga 3070ti xc3 Ultra. It has a factory firmware 0rpm mode below 55c, fan is stopped below this temp and spins up only at 55c. It stops the fan if it falls to 54c again, and starts the fan once it hits 55c again. This is because it does not have hysteresis. My goal is to use FanControl to emulate this same curve, except with the addition of "only on the way down" hysteresis provided by fancontrol. 

My goal is to make it so when the card warms from idle (0rpm) to 55c, and the fan turns on, i dont want it to be able to turn back off until its cooled all the way to 45c. From what i understand, hysteresis setting of 10c combined with "hysteresis only works on the way down" should achieve this. However, it does not work correctly when i apply these settings.

EVERY time the temp hits the 55/54c temp, the hysteresis somehow resets (?) and the speed updates. It does not wait 10c to update. However, this only happens on the way down. If i disable "Only on the way down," then it will succesfully wait 10c before updating, however when i "on the way down" is enabled, it will not wait 10c before updating. Specifically, it seems to trigger when it hits 55/54. I suspect it may be getting tripped by the card's stock firmware as this is the 0rpm cutoff.

I know this is possible because MSI Afterburner successfully does this. Its hysteresis setting only has one mode, which seems to be "Only on the way down" mode. Afterburner will successfully achieve my goal of making the card wait till 45c to turn fan off, as described above. Something is wrong with fancontrol's downward hysteresis.

For reference, this is how afterburner describes the function, (and it does work in afterburner on this gpu)
"-Last temperature value causing fan speed to change is being latched.
-When temperature is decreasing, no fan speed changes are allowed while the difference between latched and current temperature values is less than the defined hysteresis value"

Please look into this bug, let me know if you have questions

**Comment by Rem0o** [comment]
Mind sharing a screenshot of the graph you are using?

**Comment by AvocadoGuy** [comment]
https://imgur.com/a/GOTDwaU

Here is a screenshot. currently the gpu fan controls are disabled because of this issue.

I will try your suggestions later today or tomorrow when i have time and let you know. Thank you for writing back.

While i have you here, i have another question. The tooltip for response time is unclear to me. Is this the same as polling rate? 
![fancontrol1](https://user-images.githubusercontent.com/45061198/207448678-63974ccc-91e5-49b1-952c-b17bb5863baf.PNG)
![fancontrol2](https://user-images.githubusercontent.com/45061198/207448681-e4a8f696-d5cb-4e29-aafd-61f3cd2508ba.PNG)

**Comment by Rem0o** [comment]
Response time is : 

For how long the temp must exceed hysteresis before a change can occur.

**Comment by AvocadoGuy** [comment]
I tried what you said and it worked! This is the best fan control program that has ever existed, thank you for all your work. Regarding the response time tooltip, perhaps your explanation in your reply to me can be added to the tooltip, as the language was unclear to me as it currently is. I would also suggest explaining somewhere in the software that the hysteresis is bypassed on either extreme of a curve. I think its smart to do this, but i think a user needs to know, as evidenced by my case. Thank you for your help!

**Comment by Rem0o** [comment]
Yeah will revisit the tooltip, glad we sorted that out. Closing.
