### ISSUE TITLE
Feature Request: Monitoring multiple sensors in tray

### ISSUE THREAD

**Issue by k3ack3r** [Rem0o/FanControl.Releases#1374]
Yeah yeah I know - There are limitless numbers of programs that can do that but it'll be nice if this program could have more than one temperature sensor in the tray, possibly removing the need to have a temperature monitor program running.

**Comment by Rem0o** [comment]
It is in the pipeline.  Will rename the Theme and color dialog to something like "Appearance", and will put the tray icon stuff in there, with options for "n" tray icons.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/207974868-a95605ec-dede-4571-84ff-6adbe524ffa4.png)

**Comment by Rem0o** [comment]
See V141
