### ISSUE TITLE
REQUEST temps in taskbar

### ISSUE THREAD

**Issue by mirddes** [Rem0o/FanControl.Releases#1375]
i currently use coretemp and gputemp almost exclusively for their gpu and cpu temps in the taskbar.
would be great to ditch both.
![image](https://user-images.githubusercontent.com/13982888/207561193-ea9f4949-43f0-4fcd-975d-c57b3da773e5.png)

i've always wished i could have bigger numbers, so also having that option would be a clear advantage for many users, especially the less sighted among us.

**Comment by Rem0o** [comment]
Sadly the canvas is limited to 32x32, so you can't make it as big as you want. What you see there in the screenshot is pretty much the max.

**Comment by Rem0o** [comment]
See V141 for multiple temperature tray icons.

**Comment by mirddes** [comment]
very nice!
![image](https://user-images.githubusercontent.com/13982888/208175352-6b19808d-4500-4e15-b510-2c09c946f18c.png)
now if you can add a colour mixer for each of them they can be colour coded for easy reference :D

and something about the tooltips, coretemp/gputemp leave something to be desired but does it even matter...?
![image](https://user-images.githubusercontent.com/13982888/208176132-6e9c5e4a-0f9c-4a04-b25b-2349600c1fbe.png)
![image](https://user-images.githubusercontent.com/13982888/208176156-c173747f-387d-4bf9-b2a7-c847fd84469b.png)


thank you very much for your amazing contribution to humanity.
