### ISSUE TITLE
Since FanControl v131 it never updates properly unless I manually run the updater.exe file. 

### ISSUE THREAD

**Issue by nefariouslegion** [Rem0o/FanControl.Releases#1376]
Whenever I try to update FanControl it closes and then I see a command window for like a half a second and then nothing happens. If I re-open FanControl it's still on the old version. If I then manually run the updater.exe file it works. This has happened since v131 all the way til now. I just had to do this to update to 140. 

FYI FanControl it set to run at startup

**Comment by Rem0o** [comment]
My guess is that somehow the user set in the scheduled task doesn't have enough rights to run the updater from FanControl,   If you download https://github.com/Rem0o/FanControl.Releases/releases/tag/V138 manually and open it up and accept the update to 140, does it crash?

**Comment by nefariouslegion** [comment]
The only user account on this PC is my account and it's an Admin account. So it should have the rights. It used to update just fine. I can try that downgrade and update though still if you want me to? Will it mess up my user settings by downgrading?

**Comment by Rem0o** [comment]
Exact it onto an other location, it will be independant from your original.

**Comment by nefariouslegion** [comment]
Tried and had the same issue. I screen recorded it so you can see what happens and pause to see the command prompt that shows up for a split second after FanControl closes
https://user-images.githubusercontent.com/89366675/207715225-17f2bd90-9799-47e9-b5a5-7a9f69cfd46c.mp4

**Comment by nefariouslegion** [comment]
FYI the update from v140 to 141 worked properly. No idea why
