### ISSUE TITLE
Stuck curves for GPUs

### ISSUE THREAD

**Issue by FengDoge** [Rem0o/FanControl.Releases#1377]
ISSUE:
![屏幕截图 2022-12-15 134853](https://user-images.githubusercontent.com/39090455/207782805-ed8237f2-2e45-4324-a473-7289613e4566.png)
![屏幕截图 2022-12-15 134936](https://user-images.githubusercontent.com/39090455/207782893-8e626d42-0789-48a9-b1b1-c8c45513ecf6.png)
-FanControl temperature does not follow and update the GPUs' temperature on the curve, also does not increase RPM. The temperature source within' the software show the correct temperature however.
-When the mix custom sensor selects two gpus, the max/min function can only report the temperature of gpu0, even if the temperature of gpu1 is higher. When the sum/avg function is selected, the sum/avg value will be refreshed only when the temperature of gpu0 changes.
-Set GPU1 as the temperature source, after restarting the software/pc, the temperature source will be reset to GPU0.

I have tried the following solutions:
-Delete and re-download the Software
-Reload the fan presets.
-Re-create the same preset from scratch.

I have just updated my NVIDIA drivers to 527.56 today.
I also have updated my FanControl version to v140 from v139.

Everything was working just fine until I added another GPU
System:
OS: Win11
CPU: AMD Ryzen 7 5800X
GPU1:NVIDIA RTX 2060 Super
GPU0:NVIDIA GTX 1660 Super

**Comment by FengDoge** [comment]
[tt2.zip](https://github.com/Rem0o/FanControl.Releases/files/10234115/tt2.zip)
 Here is my config, it's seems all fine, but curves temp source just always reset to GPU0. So it stucks and cannot change the RPM. The mix sensor share the same issue. I'll go to 138 and try again.
![屏幕截图 2022-12-15 140228](https://user-images.githubusercontent.com/39090455/207784810-29e650c7-9569-47e6-bdf7-e4d071e3062c.png)

**Comment by Rem0o** [comment]
Do you have this issue with V140?

**Comment by Rem0o** [comment]
Issues with multiple Nvidia gpus should be fixed.
