### ISSUE TITLE
Add a 'Cancel' button to 'unsaved changes' pop-up

### ISSUE THREAD

**Issue by seiphr** [Rem0o/FanControl.Releases#138]
Currently the option 'Yes' saves the changes and 'No' discards them.  A 'Cancel' option would be useful to go back to the main screen without saving and carry on making changes. Whilst, you could argue that the 'Yes' button has the same indirect outcome, it's annoying to have to re-open the application when clicking 'Yes' if you want to make further changes. 

Alternatively - perhaps this is just me - it's somewhat counterintuitive compared to the behaviour you would expect from the 'No' option. In most commercial software, the No button wouldn't discard the changes, it would cancel the save action.  Perhaps a more explicit choice of buttons would be 'Yes', 'Discard', and 'Return'?

**Comment by Rem0o** [comment]
Good comment, however,

> it's annoying to have to re-open the application when clicking 'Yes' if you want to make further changes.

Well, why do you need to re-open? If you clicked the "X" button, you want to exit the window, no? Otherwise, if you just want to save, you can save from the 3 dot menu, and it won't close the app.

**Comment by seiphr** [comment]
Yeah, you're right.  I think what bothers me is that the 'No' option discards everything.  Instinctively if I made a mistake and notice as I click close, I want to be able to go back and fix it.  Take MS Word as an example - there you have 'Save', 'Don't Save', and 'Cancel'.  I think that's pretty standard and intuitive.

If I read the pop-up, then then it could be argued that the behaviour of 'No' as it currently is does make sense.  But it's not the normal or expected behaviour when confronted with a save on close pop-up.

**Comment by Rem0o** [comment]
Cancel added for next version.
