### ISSUE TITLE
I always have to run the updater twice

### ISSUE THREAD

**Issue by pjmdesi** [Rem0o/FanControl.Releases#1386]
**Describe the bug**
On Fan Control launch, occasionally there is a message to update to the latest version. When I click the update button, it goes through the normal process. However, once it launches again, the software is in a default state, as if it had been fully reset (theme, fan settings, hide/show selections, and curves are all reset to default, but my specific hardware is shown).

This would be a much bigger issue if I hadn't come across a _fix_: Simply close Fan Control and re-open it, then everything is back to what it was before and the update prompt comes up again. Click update... again. It installs, then, it's perfect. All the correct settings are loaded. 

Fan Control is installed here:
C:\Users\[username]\iCloudDrive\Deployable Utilities\FanControl

**Is there a log.txt file next to FanControl.exe with recent date entries?**
My Latest log.txt has entries from months ago, so whatever the error is, it's probably not being logged.

**Relevant hardware specs and setup**
Windows 11 build 22621.963 (issue existed in previous builds)
AMD Ryzen 7 5800X3D 8-Core Processor 3.40 GHz
EVGA GeForce RTX 3090 FTW3 Ultra Gaming

**Comment by Rem0o** [comment]
If you search for FanControl.exe in explorer, is there multiple "FanControl.exe" on your computer?

**Comment by pjmdesi** [comment]
@Rem0o 
I did a search, and I am not seeing multiple versions of the file. Just the one in the directory I mentioned

**Comment by pjmdesi** [comment]
@Rem0o 
Yes, it looks like I do have 2 versions on my machine. There's one I found in C:\Windows\System32. No idea how it got there!
Should I remove this one?

**Comment by Rem0o** [comment]
Yes

**Comment by pjmdesi** [comment]
@Rem0o 
After removing the duplicate app from my System32 folder, the issue was not solved. I went through a few updates to be sure, but the same situation as above is still happening.
Install update -> FC opens as if reset -> close -> reopen -> reinstall update -> FC opens as it should.

**Comment by Rem0o** [comment]
> Install update -> FC opens as if reset

In that first section, before installing an update, what folder is written here?
![image](https://user-images.githubusercontent.com/14118956/213889184-29bb4654-7b03-455f-a3a4-9f10786ed77f.png)

**Comment by pjmdesi** [comment]
This is what my config says:
![Screenshot_20230121_042506](https://user-images.githubusercontent.com/36543053/213889389-bdbefcb1-89b5-4523-9279-8136448e7faf.png)

**Comment by Rem0o** [comment]
Ok then when you update and you "lose" your config, what location is it?

**Comment by pjmdesi** [comment]
@Rem0o 
Next time there's an update, I'll be sure to check that.

**Comment by pjmdesi** [comment]
Just updated to v145. Reset config is set to:
![image](https://user-images.githubusercontent.com/36543053/217897195-0c19bfe1-43b9-417f-90f0-3f91e358dc4a.png)

**Comment by Rem0o** [comment]
@pjmdesi  I don't quite understand how it got there. 

Is there a FanControl.exe at all in System32? or is it just the working directory.

**Comment by congyiwu** [comment]
I decompiled `FanControl.exe` and  `Updater.exe` b/c this happened to me too, and I had a hunch as to what was going on...

In the `FanControl.Domain.UpdaterService` class, I saw:
```cs
private async Task UpdateVersion(CancellationToken cancellationToken) {
...
    using (FileStream updaterFile = File.Create("Updater.exe"))
...
    ProcessUtilities.StartShellExecute("Updater.exe", "-v", Environment.Version.Major.ToString());
    this._applicationContext.Exit();
```

In the `Updater.Program` class, I saw:
```cs
private static async Task Main(string[] args) {
...
    Console.WriteLine("Extracting archive...");
    string extractDirectoryPath = ".";
    Result result3 = Program.Extract(result2.Content, extractDirectoryPath);
...
    Process.Start(new ProcessStartInfo("cmd", "/C start /B FanControl.exe -w")
...

private static Result Extract(Stream zipStream, string extractDirectoryPath)
{
    try
      {
        if (!Directory.Exists(extractDirectoryPath))
        ...
```

In both places, you're using relative paths (`Updater.exe` and `.`), which are going to be interpreted relative to `Environment.CurrentDirectory` (AKA the current working directory / CWD), which can either be inherited from or arbitrarily set by the parent process, but isn't necessarily the parent folder of either process.

Instead, you should derive the parent folder from `Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)`, which is what `FanControl.Domain.ApplicationState` does when it creates the `Configurations` folder:
```cs
private static readonly string ROOT_FOLDER = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "Configurations");
```

Here's the full repro of the bug, starting w/ a clean machine:
1. Assume FanControl is initially downloaded to `C:\original\FanControl.exe`
1. If you navigate to `C:\original` in Explorer and double click `FanControl.exe`, CWD is `C:\original`, and `C:\original\Configurations` will be created
  * BTW if you navigate to `C:\some\other\path` in Explorer, paste `C:\original\FanControl.exe`, CWD will be `C:\some\other\path`. Similar behavior can occur in the terminal or scripts.
1. Exit FanControl
1. Start it again by typing FanControl in the Start menu and picking the autosuggested entry
   * CWD will be `C:\Windows\System32`!
   * This how I've been starting FanControl
   * `C:\original\Configurations` will still be used
1. If `C:\original\FanControl.exe` tries to update itself when CWD is `C:\Windows\System32`, the following happens:
1. `C:\original\FanControl.exe` downloads `Updater.exe` to `C:\Windows\System32` and starts it.
1. `C:\Windows\System32\Updater.exe` inherits `C:\Windows\System32` as the CWD from its parent process (*not b/c it's located there*).
1. `C:\Windows\System32\Updater.exe` download the new FanControl version to `C:\Windows\System32\FanControl.exe` and starts it.
1. `C:\Windows\System32\FanControl.exe` will create `C:\Windows\System32\Configurations` and make you reconfigure everything
1. If you exit FanControl and start it again from the Start menu, it will start `C:\original\FanControl.exe`, which is still the old version

**Comment by fre-sch** [comment]
Did this overwrite any actual system32 files?

I could use the archive to find all files belonging to FanControl in system32 and remove them, but without knowing if this did overwrite legitimate system32 files, I'm hesitant to do so.
