### ISSUE TITLE
[HELP REQ] GPU fans keep getting overridden and I don't know why!

### ISSUE THREAD

**Issue by Tw33die** [Rem0o/FanControl.Releases#1387]
First off, apologise if this is a stupid issue to raise but I can't figure it out.

I have my GPU fans set in FC but it always has that little ? saying there is a conflict/being overridden by an external source. If I toggle control off then on again, it works for a time before the ? comes back. Like if I open another program or launch a game, FC loses control again. I have 'Force apply' on but it doesn't seem to do anything. 

I have Afterburner for undervolting my card to help with temps, so maybe it is that? But I have tried repeatedly to turn the fans off on that and set a profile where 'Auto' is enabled. It's like it just breaks every few minutes and my GPU fans come on when they don't need to be.

Any assistance possible? I'm not great with this stuff. Only ever used Afterburner before. 

Thank you!

**Comment by Tw33die** [comment]
Edit - Like I just opened a new tab on Firefox and the fans on the GPU start up again even though it is below the temp the graph states. The ? is back on FC, stating it is being overridden somewhere. Afterburner is NOT on. 

Just from opening a Firefox tab?? 

Please help! 

The card is an MSI Suprim 3080Ti.

**Comment by Tw33die** [comment]
Adding the below, it might be a clearer explanation. Not sure. 

The GPU fans will always default to 30% speed (around 1040rpm) no matter the temps. Even when the GPU temps are 20 degrees.

I have a graph set up so that FC should only turn the fans on when the card temps exceed 30 degrees.

If I toggle control off then on again, it drops to 0% below 30 degrees. However, whenever it then hits 30 degrees, the fans will come on (good) but STAY ON (bad) even when temps drop back below that threshold.

I dunno.

**Comment by Asneb** [comment]
Having the same issue , tried playing around to find a fix but couldn't when applied it works until the temperature ramps up over a load and comes back down getting stuck at 30%

**Comment by Rem0o** [comment]
30% is a hard limit on nvidia cards now for third party controls.   What you can do is enable the override in sensor setting and set 0% at the temperature you know your card can 0 rpm.

**Comment by Asneb** [comment]
Does afterburner even with fan control disabled overrides control? even with the function active the cards starts at fan stop ramps up if load is applied but goes to 30% and never comes down

**Comment by Rem0o** [comment]
No after burner won't if you got fan control disabled in there.

To get 0 rpm working:

![image](https://user-images.githubusercontent.com/14118956/208256068-4b722350-f217-4cb4-af41-a2a0b7f0afee.png)

![image](https://user-images.githubusercontent.com/14118956/208256083-4892e0cb-1b09-47ae-b68f-1f115e3f4d73.png)

You can't set anything between 1-29 % for the rest of your fan curve.

**Comment by Asneb** [comment]
![image](https://user-images.githubusercontent.com/87947601/208265213-d36f7639-f9ae-4384-916a-ffcc0034d190.png)
Like this?

**Comment by Rem0o** [comment]
Yes, however i doubt your gpu accept to be 0 rpm at 60.

**Comment by Asneb** [comment]
My card makes fans kick in at 60c , but it worked like that.
