### ISSUE TITLE
Feature request: Tray icon color

### ISSUE THREAD

**Issue by Zyarra** [Rem0o/FanControl.Releases#1388]
Hey'
Now that we have multiple tray icons it would make sense to be able to color them.
EG, Nvidia temp green, Intel temp blue.

**Comment by batthing** [comment]
+1 for this please :)

**Comment by Mind777** [comment]
+1

**Comment by Spuner** [comment]
Yeah, that would be nice.

**Comment by Zyarra** [comment]
> Like this?
> 
> ![image](https://user-images.githubusercontent.com/14118956/212124947-2c5734ad-8a7c-43d4-bd30-2e536f40aa81.png)

OHYEAH BABY

**Comment by Spuner** [comment]
@Rem0o, if you swap the gauges in the system tray, then the next time you activate the profile - they are not crumpled.

![2023-01-12-21-53-35](https://user-images.githubusercontent.com/30773815/212142800-42f9943e-3b82-443c-b7df-90e1a7a13340.png)

**Comment by Rem0o** [comment]
V143

**Comment by Zyarra** [comment]
> V143

Super!
However the color picker doesn't work.
It works perfect when I google the hex and enter manually, just the color picker that doesn't do anything :)

**Comment by batthing** [comment]
> > V143
> 
> Super! However the color picker doesn't work. It works perfect when I google the hex and enter manually, just the color picker that doesn't do anything :)

Interesting, it works for me - excellently btw. Thanks!

**Comment by Zyarra** [comment]
> > > V143
> > 
> > 
> > Super! However the color picker doesn't work. It works perfect when I google the hex and enter manually, just the color picker that doesn't do anything :)
> 
> Interesting, it works for me - excellently btw. Thanks!

I swear it was not working yesterday,every color was switching to black -- but it does now!
ignore my comment then!

**Comment by tormento** [comment]
What about automatic colors, custom temperature based?

That would be nice and eye catching,

**Comment by tormento** [comment]
@Rem0o :)
