### ISSUE TITLE
[ERROR]:Fails to launch. "An unexpected error occured. See log file for details."

### ISSUE THREAD

**Issue by TheT1133** [Rem0o/FanControl.Releases#1391]
I was running fancontrol without problems severals months. Now it suddenly refuses to start at all. I've done zero changes to bios settings.

Any idea?

Log: 

17.12.2022 17.19.43: System.InvalidOperationException
   kohteessa FanControl.Domain.ApplicationContext.ShowMainWindow()
   kohteessa System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   kohteessa System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- Pinon jäljityksen loppu aiemmasta sijainnista, jossa palautettiin poikkeus ---
   kohteessa System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   kohteessa System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   kohteessa System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   kohteessa System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   kohteessa System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   kohteessa System.Windows.Threading.Dispatcher.Invoke(Action callback)
   kohteessa FanControl.Domain.IPC.MultiInstanceMessaging.OnNewInstance(OnMessageEventArgs`1 args)
   kohteessa FanControl.Domain.InterProcessMessaging`1.<>c__DisplayClass10_0.<StartReceiverLoop>b__0()

**Comment by Rem0o** [comment]
Do you have multiple instance running, like on an other user account for eg? Take a look in task manager in the "details" section for FanControl.exe

**Comment by TheT1133** [comment]
> Do you have multiple instance running, like on an other user account for eg? Take a look in task manager in the "details" section for FanControl.exe

No. It's crashes instantly when I launch it.

**Comment by Rem0o** [comment]
The error log you posted shows an other instance is running. 

> FanControl.Domain.IPC.MultiInstanceMessaging.OnNewInstance(OnMessageEventArgs1 args)

**Comment by TheT1133** [comment]
> The error log you posted shows an other instance is running.
> 
> > FanControl.Domain.IPC.MultiInstanceMessaging.OnNewInstance(OnMessageEventArgs1 args)

I checked, there was no other instance running. Only one pops up and instantly crashes. But I solved the problem just by formating whole pc. There was some corrupted windows files which I was not able to repair and those were causing other issues aswell.
