### ISSUE TITLE
Tray Icon Color

### ISSUE THREAD

**Issue by CrimsnShadow** [Rem0o/FanControl.Releases#1394]
Icon in tray is black, still functions as normal. (Just a minor issue)

Windows 10, Version 22H2.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/208312596-8b979c9d-2ee8-49f5-af8a-65aef36d85bf.png)

**Comment by CrimsnShadow** [comment]
Apparently I'm just blind.. Lol Thanks.
