### ISSUE TITLE
(feat req.) Ability to start fans at specific speed

### ISSUE THREAD

**Issue by Cedric-NET** [Rem0o/FanControl.Releases#1396]
I absolutely love fancontrol so far,
However it's missing a feature (that is present on other software) which is to be able to start spinning fans (at initial power up) at a certain speed.
This is in particular useful for DC fans that you want to start close to their lowest speed, they won't start properly unless you "kick them in the butt" with an initial (and short) 100% or at least 60% spin speed

So this is NOT the start speed : it's a kick in, eg if the fan was at zero and needs to be at 50%, the fan has first to "boost" at a defined boost speed (eg 60 or 100%) for like 2 sec, then go back to the set speed.

What's double frustrating is that the ramping up speed of fans is actually limited to 50%/sec so this limitation does the exact opposite of what I'm asking, and actualy causes problems while trying to spin fan very slow

Just a feature request :)

**Comment by Rem0o** [comment]
Start% does exactly that. It is used as a kick-in.  Make sure to set your stop% also correctly and it will behave exactly like you describe.  From 0 RPM it will kick it to whatever start% you set, until the fan spins, then go back down to whatever is the real command,
