### ISSUE TITLE
[BUG] Doesn't show the TEMP_SENSOR of my Strix Z690-E

### ISSUE THREAD

**Issue by serveradmin9912** [Rem0o/FanControl.Releases#1397]
I used this software for years with my Z97 Board and the 2-Pin Temp Sensor was always detected.

I Upgraded to an ASUS Strix Z690-E and the temp sensor isn't detected any more. Libre Hardware Monitor also doesn't show the sensor.

The Sensor is showen in HWInfo and ASUS Fan Xpert..

Is there some way i can fix this?

**Comment by Rem0o** [comment]
See README
https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
