### ISSUE TITLE
Virus detected and update fails V65 

### ISSUE THREAD

**Issue by jyanes83** [Rem0o/FanControl.Releases#140]
When attempting to update using updater.exe OR simply downloading the latest release from Github.   Windows throws an error that there is a virus, as well as Google Chrome detects a virus on download and does not allow to go further.  

here is the error being thrown by updater.exe 
Unhandled Exception: System.ComponentModel.Win32Exception: Operation did not complete successfully because the file contains a virus or potentially unwanted software
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Updater.Program.<Main>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Updater.Program.<Main>(String[] args)

**Comment by Sn0whax** [comment]
Have you verified if this is actually a virus or not?

**Comment by jyanes83** [comment]
I have not.  Are you getting this issue too?  or am i the only one.   If i am the only one then i can look into something isolated to my system.   I just thought it was wide spread due to downloading straight from github and the zip itself being flagged by Chrome.

**Comment by jyanes83** [comment]
Ok sorry for the false report of this.   Not sure what happened here but just tried the update again today and all worked as expected on version 65.   Again not sure what happened yesterday when i received the error i shared.

**Comment by en-ot** [comment]
Hello!
Dr.Web is detecting a "Troyan downloader" (by heuristics) when upgrading from v.91 to v.92. and puts the FanControl.exe and FanControl.sys into quarantine. Then after re-scan quarantined file for viruses dr.web reports 0 viruses and allows to restore files. But .exe becomes totally unusable, it can not be executed or removed until reboot.
Can You please make your upgrader/downloader behaviour less virus-like?

**Comment by Rem0o** [comment]
@en-ot 

"Can You please make your upgrader/downloader behaviour less virus-like?"

The updater / downloader does 3 things:

1) Console.log messages
2) Download this zip then extract it: https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip
3) Open it with admin rights since the app needs admin rights to run.

I don't know what part of this is "virus-like", but that's what I want the updater to do and it does it fine. 
It should either be reported as false-positive, or ignored.
