### ISSUE TITLE
Repeated "loaded settings" messages on open

### ISSUE THREAD

**Issue by TrickyWidget** [Rem0o/FanControl.Releases#1400]
This is only a minor annoyance, but often when I open the GUI, a message will appear at the bottom of the window saying that it has loaded Sensors.json.  But it often repeats that message several times, sometimes over a dozen.  And since the message display is animated, it can take a while for it to finally stop.  Everything still works fine, it's just a bit distracting.

FanControl V141
Asus Prime Z790-P WiFi D4 Motherboard
Windows 10 Pro 64 22H2
No errors or log.txt
[Sensors.zip](https://github.com/Rem0o/FanControl.Releases/files/10280546/Sensors.zip)

**Comment by Rem0o** [comment]
The message at the bottom is called a "snackbar", and it works as a queue., even if the window is off   If you get dozens of message, might that be because you changed config multiple times while the window was off?

**Comment by TrickyWidget** [comment]
No, I haven't changed anything lately.  And I've only got the one config file.

**Comment by Rem0o** [comment]
Is the message alternating or is it always the same?

**Comment by TrickyWidget** [comment]
It's always the same.  "Configuration loaded: Sensors.json"

I'm not sure, but it may be related to how long it's been since I last opened the GUI.  It seems like maybe the longer it's been, the more messages there are.  Kind of like they're periodically queuing up while it's in the background, and then all spill out when I open it.

**Comment by Rem0o** [comment]
^ Everytime your computer goes to sleep then wakes back up, the config is loaded, and a message is queued.

**Comment by TrickyWidget** [comment]
Ah, that sounds like the cause!  It would be nice if it didn't queue duplicate messages.  Thanks.  :)

**Comment by kladnik** [comment]
> ^ There is an option for that, will apply it to the loaded config message.

Where is that option? I still get multiple notifications when I open the app

**Comment by Taomyn** [comment]
I have this issue, what is the config option?
