### ISSUE TITLE
Configuration Warns of Modification When it Hasn't Been Modified

### ISSUE THREAD

**Issue by hl2guide** [Rem0o/FanControl.Releases#1401]
**Describe the bug**

When using the app it often warns of unsaved configuration changes, when nothing has been changed.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No.

**Relevant hardware specs and setup**

Windows 11 22H2.

**Comment by Rem0o** [comment]
That will occur when there is an update in the app that saves new stuff in the config.  Simply apply the save and move on.
