### ISSUE TITLE
Improved Configuration Switching Drop Down

### ISSUE THREAD

**Issue by hl2guide** [Rem0o/FanControl.Releases#1402]
Please add a dropdown for faster config switching.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/209162433-363c4c82-c675-4bf5-a883-f19de7920dc6.png)

Are you using the tray icon?

**Comment by hl2guide** [comment]
I was using the main UI. I'll start using the tray icon.
