### ISSUE TITLE
Feature request: GPU memory temperature as temperature source

### ISSUE THREAD

**Issue by donberke** [Rem0o/FanControl.Releases#1405]
Hi,

As modern videocards provide GPU memory temperature sensor it would be nice to have the GPU memory temperature available as a temperature source in Fan Control.
Personally I would like to ramp the GPU fan speed on ether high GPU core or memory temps with a Mix sensor. My 3080 suffers high memory temps on low GPU core loads.

Thanks!

**Comment by DfrostX** [comment]
You didn’t do much research before asking eh? There are literally a dozen thread on the subject.

Anyway, here is one https://github.com/Rem0o/FanControl.Releases/issues/757#issuecomment-1122436719

**Comment by donberke** [comment]
Ah sorry, I did search the github issues but somehow glossed over that this is the setting I need. Apologies and thanks for the link!
