### ISSUE TITLE
Low RPM by 100%

### ISSUE THREAD

**Issue by GammelBro** [Rem0o/FanControl.Releases#1406]
Currently I have a problem where the software sets the percentage speed to 100% and the fans barely spinns if I disable the custom curve the mainboard settings will apply and the fans will spinn faster. All fans are the same (Corsair LL-120) and all are connected directly to the mainboard (I hate the ICUE :) )

[report.txt](https://github.com/Rem0o/FanControl.Releases/files/10295762/report.txt)

![FanControl_CjTET593GN](https://user-images.githubusercontent.com/1346889/209356136-bcd4f46d-f910-42a4-ac7a-a09cb71610e7.png)

**Comment by Rem0o** [comment]
Asus motherboard? Make sure you don’t have a silent profile on in any of their software or bios.

**Comment by Rem0o** [comment]
@GammelBro  Was it exactly that?
