### ISSUE TITLE
Feature request: Corsair temp sensor support. 

### ISSUE THREAD

**Issue by Logman7732** [Rem0o/FanControl.Releases#1414]
Exactly as the title shows. I do not have a motherboard temp sensor , so i had to use the corsair commander xt for temp sensors and rgb. As far as I am aware, it is unsupported. I would like to control my fans based on water temp and target a delta between ambient and the water temp. If this is already possible please let me know because the temp sensor is no where to be found in the software. Thanks

**Comment by Rem0o** [comment]
There was a commander plugin floating around at some point, but the author flushed the repo.  Would love to have support back in, but we’re not there yet.

**Comment by EvanMulawski** [comment]
@Rem0o I'm starting to work on a new plugin for Commander Pro/Core. Hoping to have something done within the next month or so.

**Comment by Rem0o** [comment]
Will keep an eye out @EvanMulawski
