### ISSUE TITLE
Not all fans in Control

### ISSUE THREAD

**Issue by Yanaroh** [Rem0o/FanControl.Releases#1417]
![Fan control](https://user-images.githubusercontent.com/121438535/209549788-9a01eb90-e5f2-42b5-b3de-8d708e38bc83.png)

Hi sorry if someone else already had the issue and i'm annoying but i'm not that good with software and stuff... So to put it short i want to use this Software and i Already made a Donation since i think its awesome. I just have one issue i can't controll all Fans. On Fan speed it shows all fans though....
I have an Aorus x570 ULTRA Mainboard. SIV software from Aourus is not working anymore (doesn't show that its installed no matter how often i install it) That is not an issue though since i want to use Fan Control.

EDIT
I just saw that someone else with an Aorus x570 Mainboard had the same Issue so i guess My mainboard is not supportet? will it get Supportet anytime soon?

**Comment by Rem0o** [comment]
See README on hardware compatibility. In your case you got only one header missing. You can most likely make your setup work without it.

**Comment by Yanaroh** [comment]
Thank you for your Answer. Really Thank you. Sadly i can't work around it with those headers and i'm missing System 3, 4, 5 and 6... 3 should be CPU fan which i don't use anyway but i use 4 5 and 6 i thought of working around but i can't find a way at the moment sadly... 
I really appreciate your answer though and i really hope support for my motherboard will come with time...
