### ISSUE TITLE
Lenovo Ryzen computer without support

### ISSUE THREAD

**Issue by daniel-lo** [Rem0o/FanControl.Releases#142]
Hi there,

I just received a new computer:

https://pcsupport.lenovo.com/de/de/products/desktops-and-all-in-ones/5-series/g5-14amr05/90q1/90q1004vge/pc1q4h3f/downloads/driver-list/

The nvida fan is supported by this app but none of the other fans can be "seen".

Is there anything I can provide to support development?

Cheers

`Motherboard

SMBios Version: 3.2

BIOS Vendor: LENOVO
BIOS Version: O4ZKT24A
BIOS Date: 24.12.2020
BIOS Size: 32 MB

System Manufacturer: LENOVO
System Name: 90Q1004VGE
System Version: IdeaCentre G5 14AMR05
System Wakeup: PowerSwitch

Motherboard Manufacturer: LENOVO
Motherboard Name: 3728
Motherboard Version: NOK
Motherboard Serial: 

Chassis Type: Desktop
Chassis Manufacturer: LENOVO
Chassis Version: None
Chassis Serial: PC1Q4H3F
Chassis Asset Tag: 
Chassis SKU: Default string
Chassis Boot Up State: Safe
Chassis Power Supply State: Safe
Chassis Thermal State: Safe
Chassis Power Cords: 1
Chassis Lock Detected: No
Chassis Security Status: None

Processor Manufacturer: AMD
Processor Type: CentralProcessor
Processor Version: AMD Ryzen 7 3700X 8-Core Processor
Processor Serial: Unknown
Processor Socket Destignation: AM4
Processor Socket: AM4
Processor Version: AMD Ryzen 7 3700X 8-Core Processor
Processor Family: AmdZen
Processor Core Count: 8
Processor Core Enabled: 8
Processor Thread Count: 16
Processor External Clock: 100 Mhz
Processor Max Speed: 4400 Mhz
Processor Current Speed: 3600 Mhz

Cache [L1] Size: 512
Cache [L1] Associativity: 8Way

Cache [L2] Size: 4096
Cache [L2] Associativity: 8Way

Cache [L3] Size: 33280
Cache [L3] Associativity: 16Way

Memory Device [0] Manufacturer: Hynix
Memory Device [0] Part Number: HMA82GU6CJR8N-XN
Memory Device [0] Device Locator: DIMM 1
Memory Device [0] Bank Locator: P0 CHANNEL A
Memory Device [0] Speed: 3200Memory Device [0] Size: 
16384 MB

Memory Device [1] Manufacturer: Hynix
Memory Device [1] Part Number: HMA82GU6CJR8N-XN
Memory Device [1] Device Locator: DIMM 1
Memory Device [1] Bank Locator: P0 CHANNEL B
Memory Device [1] Speed: 3200Memory Device [1] Size: 
16384 MB

SMBios Table

 ABoAAAECAPAD/4CYiz8BAAkAAw0BGAEMIABMRU5PVk8ATzRaS1QyNEEAMTIvMjQv
 MjAyMAAAARsBAAECAwTSzXbZLjDrEaBvbE0PLn4ABgUGTEVOT1ZPADkwUTEwMDRW
 R0UASWRlYUNlbnRyZSBHNSAxNEFNUjA1AFBDMVE0SDNGAExFTk9WT19NVF85MFEx
 X0JVX0xlbm92b19GTV9JZGVhQ2VudHJlIEc1IDE0QU1SMDUASWRlYUNlbnRyZSBH
 NSAxNEFNUjA1AAACDwIAAQIDBAUJBgMACgBMRU5PVk8AMzcyOABOT0sAICAgICAg
 ICAgICAgICAgICAgICAAICAgICAgICAgICAgICAgICAgICAgICAgIABEZWZhdWx0
 IHN0cmluZwAAAxYDAAEDAgMEAwMDA4AAAAAAAQADBUxFTk9WTwBOb25lAFBDMVE0
 SDNGACAARGVmYXVsdCBzdHJpbmcAAAoKBACDAYUCgQMgICBUbyBCZSBGaWxsZWQg
 QnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AICAgT25ib2FyZCAxMzk0
 AAALBQUAD0xFTk9WTyBUaGlua0NlbnRyZSBFbWJlZGRlZCBDb250cm9sbGVyIC1b
 TzRaQ1QxMkEtMS4xMl0tAExFTk9WTyBUaGlua0NlbnRyZSBCSU9TIEJvb3QgQmxv
 Y2sgUmV2aXNpb24gMS4yNABMZW5vdm8gU2VydmljZSBFbmdpbmUgTm90IFN1cHBv
 cnRlZABJTlZBTElEAElOVkFMSUQASU5WQUxJRABJTlZBTElEAElOVkFMSUQASU5W
 QUxJRABJTlZBTElEAElOVkFMSUQASU5WQUxJRABJTlZBTElEAElOVkFMSUQASU5W
 QUxJRAAADAUGAAJzY3JlKysAU01JOjAwQjJDMDAwAAAYBQcAEgAAIBQIAAAAAAAA
 AAAAAAAAAAAAAAAAACsfCQBBTUQAAgAlAAMABQAAAAIQAAAAAAAAAAAAAABUUE0g
 Mi4wAEFNRAAAEhcKAAMCAgAAAAAAAACAAAAAgAAAAIAAABAXCwADAwMAAAACCgAC
 AAAAAAAAAAAAAAATHwwAAAAAAP//MwALAAIAAAAAAAAAAAAAAAAAAAAAAAATHw0A
 AABAAP//CwILAAIAAAAAAAAAAAAAAAAAAAAAAAAHGw4AAYABAAIAAhAAEAABBgUH
 AAIAAAACAABMMSAtIENhY2hlAAAHGw8AAYEBABAAEBAAEAABBgUHABAAAAAQAABM
 MiAtIENhY2hlAAAHGxAAAYIBAIIAghAAEAABBgUIAAIAgAACAIBMMyAtIENhY2hl
 AAAEMBEAAQNrAhAPhwD/+4sXA4tkADAREA5BMQ4ADwAQAAQFBggIEPwAawAIAAgA
 EABBTTQAQU1EAEFNRCBSeXplbiA3IDM3MDBYIDgtQ29yZSBQcm9jZXNzb3IgICAg
 ICAgICAgICAgAFVua25vd24AVW5rbm93bgBVbmtub3duAAASFxIAAwICAAAAAAAA
 AIAAAACAAAAAgAAAEVQTAAsAEgBAAEAAAEAJAAECGoBAgAwDBAAFAgAAAACADLAE
 sASwBAMIAAaArQAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA
 RElNTSAxAFAwIENIQU5ORUwgQQBIeW5peAA3NDI2ODE3RgBITUE4MkdVNkNKUjhO
 LVhOICAgIABVbmtub3duAAAUIxQAAAAAAP///wETAA0A////AAAAAAAAAAAAAAAA
 AAAAAAAAEhcVAAMCAgAAAAAAAACAAAAAgAAAAIAAABFUFgALABUAQABAAABACQAB
 AhqAQIAMAwQABQIAAAAAgAywBLAEsAQDCAAGgK0AAAAAAAAAAAAAAAAAAAAAAAAE
 AAAAAAAAAAAAAAAAAAAAAAAAAERJTU0gMQBQMCBDSEFOTkVMIEIASHluaXgANzQy
 NjgxODYASE1BODJHVTZDSlI4Ti1YTiAgICAAVW5rbm93bgAAFCMXAAAAAAD///8B
 FgANAP///wAAAAAAAAAAAAAAAAAAAAAAAIUFHQABS0hPSUhHSVVDQ0hISUkAAAgJ
 HgABAAISEEoxNTAwAFVTQiAzLjIAAAgJHwABAAISEEoxNTAxAFVTQiAzLjIAAAgJ
 IAABAAISEEoxNTAyAFVTQi1DAAAICSEAAQACEhBKMTUwNgBVU0IgMy4yAAAICSIA
 AQACEhBKMTUwNwBVU0IgMy4yAAAICSMAAQACEhBKMTMwMQBVU0IgMy4yAAAICSQA
 AQACCx9KMTMwMQBOZXR3b3JrAAAICSUAASICACBKMTcwNABpU0FUQQAACAkmAAEi
 AgAgSjE3MDUAaVNBVEEAAAgJJwABIgIAIEoxNzAwAGlTQVRBAAAICSgAASICACBK
 MTcwMgBpU0FUQQAACAkpAAEiAgAgSjE3MDMAaVNBVEEAAAgJKgABIgIAIEoxNzA2
 AGlTQVRBAAAICSsAAQACABxKMTEwMABIRE1JAAAICSwAAQACABxKMTEwMQBIRE1J
 AAAICS0AAQACABxKMTEwMgBEUAAACAkuAAEAAh8dSjIxMDAARnJvbnQgQXVkaW8A
 AAgJLwABAAIfHUoyMTAxAEF1ZGlvIEphY2sAAAgJMAABAAIfHUoyMTAyAEhEIEF1
 ZGlvIEhEUgAACRExAAGqDQQDDAAEAQAAABlKMTAAAAkRMgABpggEAw4ABAEAAAAJ
 SjM3MDAgTS4yIFNsb3QAAAkRMwABqAoEA4AABAEAAAMASjM3MDggUENJRSB4NCBz
 bG90IGZyb20gUHJvbW9udG9yeQAACRE0AAGmCAQDhgAEAQAAAgJKMzcwMyBQQ0lF
 IHgxIHNsb3QgZnJvbSBQcm9tb250b3J5AAAJETUAAaYIBAOHAAQBAAACAkozNzAy
 IFBDSUUgeDEgc2xvdCBmcm9tIFByb21vbnRvcnkAAAkRNgABqAoDA4QABAEAAAD/
 SjM3MDcgUENJRSB4NCBzbG90IGZyb20gUHJvbW9udG9yeQAACRE3AAGmCAMDiQAE
 AQAAAP9KMzcwMSBNLjIgV0xBTi9CVCBzbG90IGZyb20gUHJvbW9udG9yeQAAKQs4
 AAGFAQAACQBSVEw4MTExRSBHaWdhIExBTgAAKQs5AAGHAQAADQRSZWFsdGVrIEFM
 QzEyMjAAAIMWOgABAAAAAAAAAAAAAAAAAAAAgAFUVlQtRW5hYmxlbWVudAAAD0k7
 AAAQAAAQAAMBAAAAABjg28wBGQIBAwIDAwAEAAUABgAHAAgECQMKAwsADAANAA4A
 EAARABIAEwAUABUAFgAXAP8A4ODh4QAADRY8AAIAAAAAAAAAAAAAAAAAAAAAAWVu
 fFVTfGlzbzg4NTktMQB6aHxDTnx1bmljb2RlAAB/BD0AAAA=

LpcIO

Chip ID: Unknown ITE with ID 0x8638 at 0x2E/0x2F

AMD CPU

Name: AMD Ryzen 7 3700X
Number of Cores: 16
Threads per Core: 1
Timer Frequency: 14.31818 MHz
Time Stamp Counter: Invariant
Estimated Time Stamp Counter Frequency: 3593.49 MHz
Estimated Time Stamp Counter Frequency Error: 0.66257 Mhz
Time Stamp Counter Frequency: 3593.25 MHz

MSR Core #1

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFF0E5E9
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #2

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFC0B856
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #3

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFCD7AE4
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #4

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFE45C8B
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #5

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFE5F969
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #6

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFEBDE41
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #7

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFDB2D47
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #8

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFCA47C0
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #9

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFEE8274
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #10

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFF1375B
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #11

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFF3499D
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #12

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFC9AC4C
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #13

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFEDDC79
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #14

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFFF71D3
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #15

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFEC0B07
 C0010015  00000001  09000011
 C0010064  80000000  49120890

MSR Core #16

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFDCCFD5
 C0010015  00000001  09000011
 C0010064  80000000  49120890

Ryzen
Nvidia GPU

Name: NVIDIA GeForce GTX 1650 SUPER
Index: 0
Driver Version: 457.52
Driver Branch: r455_00-358

DeviceID: 0x218710DE
SubSystemID: 0x38521462
RevisionID: 0xA1
ExtDeviceID: 0x2187

Thermal Settings

 Sensor[0].Controller: GPU_INTERNAL
 Sensor[0].DefaultMinTemp: 0
 Sensor[0].DefaultMaxTemp: 127
 Sensor[0].CurrentTemp: 34
 Sensor[0].Target: GPU

Clocks

 Clock[0]: 300000
 Clock[1]: 17
 Clock[2]: 540000
 Clock[3]: 25
 Clock[4]: 585000
 Clock[5]: 25
 Clock[6]: 147272
 Clock[7]: 25
 Clock[8]: 405000
 Clock[9]: 9
 Clock[10]: 540000
 Clock[11]: 25
 Clock[12]: 810000
 Clock[13]: 17
 Clock[40]: 540000
 Clock[41]: 1
 Clock[42]: 540000
 Clock[43]: 25
 Clock[44]: 108000
 Clock[45]: 1
 Clock[62]: 1
 Clock[63]: 9
 Clock[64]: 35019
 Clock[65]: 32
 Clock[71]: 113775
 Clock[78]: 584999
 Clock[85]: 147272
 Clock[86]: 6
 Clock[92]: 84702
 Clock[93]: 32
 Clock[99]: 539999
 Clock[106]: 810001
 Clock[107]: 32
 Clock[204]: 539999
 Clock[205]: 32
 Clock[211]: 539999
 Clock[218]: 107999
 Clock[219]: 32
 Clock[281]: 1
 Clock[282]: 32

Tachometer

 Status: NOT_SUPPORTED

P-States

 Percentage[0]: 3
 Percentage[1]: 6
 Percentage[2]: 0
 Percentage[3]: 0

Usages

 Usage[1]: 1
 Usage[2]: 3
 Usage[5]: 1
 Usage[6]: 6
 Usage[9]: 1
 Usage[13]: 1

Cooler Settings

 Status: NOT_SUPPORTED

Fan Coolers Status

 Items[0].Type: 1
 Items[0].CurrentRpm: 999
 Items[0].CurrentMinLevel: 29
 Items[0].CurrentMaxLevel: 100
 Items[0].CurrentLevel: 29

Memory Info

 Value[0]: 4194304
 Value[1]: 4049920
 Value[2]: 0
 Value[3]: 16706864
 Value[4]: 2939608`

**Comment by Rem0o** [comment]
LpcIO
Chip ID: Unknown ITE with ID 0x8638 at 0x2E/0x2F

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
You can try and use theses infos to add support and test your fans in LHM.
Hardware support issues have no places here.
