### ISSUE TITLE
Some fans will not go to 100%

### ISSUE THREAD

**Issue by otherside1** [Rem0o/FanControl.Releases#1420]

**Comment by Rem0o** [comment]
Asus motherboard?

**Comment by Rem0o** [comment]
Make sure you got no "profile" set in any Asus stuff, like armory crate or the bios.  These limit the available RPM.

**Comment by otherside1** [comment]
Dell. Should i have put this issue at https://github.com/Rem0o/FanControl.DellPlugin ?
