### ISSUE TITLE
Feature Request: "Time Peak" custom sensor

### ISSUE THREAD

**Issue by Matt-Gore** [Rem0o/FanControl.Releases#1423]
Hi, very nice tool!
The only feature I'm currently missing is an alteration of the "Time Average" sensor. Instead of the average, the maximum value (peak) in a given time frame would be returned by this custom sensor.

**Comment by Rem0o** [comment]
Isn't this the opposite of what you would want to do in most case? This would result in a very "spiky" sensor. Any fan curve bound to that would constantly spike up and down.

**Comment by Rem0o** [comment]
> If the input fluctuates up and down, then the output would stay consistently high.

Let say you open up your browser or something. Your CPU will have a tiny spike to let say 65 degree. If you have a 5 second window set, you'll go from low RPM, 5 second high RPM ( stuck to that 65 value ), then back down to low RPM.  That 5 second of high RPM is trying to cool down something that happened 5 seconds ago that is long gone already.   

If you like that "stay high until back down to idle" behavior, did you give the "trigger" fan curve a try?

**Comment by Matt-Gore** [comment]
good point. So I think I would want something like:
actual temp --> 5 second average --> 5 minute maximum

However, you are absolutely right that the "trigger" curve is actually what I need, thanks! (I guess I just assumed that graph would be more powerful than the others.)

**Comment by Rem0o** [comment]
>  (I guess I just assumed that graph would be more powerful than the others.)

Nop! Every fan curve type has a dedicated purpose. You can even combine the trigger behavior with an other fan curve using a mix. This will allow you to get let say a normal ramp up up to the load temperature (with a graph), then the trigger will kick in and will be applied until the temp goes back down to the idle temp.
