### ISSUE TITLE
Auto Activate Profile On Application Launch

### ISSUE THREAD

**Issue by Mind777** [Rem0o/FanControl.Releases#1426]
How can i enable a profile automatically when a program is launched?

e.g., i run a game = profile 1 auto launch
I play a 4k video = profile 2 auto launch

Then exit program, auto return to default profile

**Comment by DfrostX** [comment]
Autohotkey  can do stuff like that but you will need to do some research as it involve scripting (using command lines) 

or you could try one of my favorite application: Autoaction https://github.com/Codectory/AutoActions/releases. Note that is
has not been updated in ages so your mileage may vary.
