### ISSUE TITLE
FanControl causes CPU temp fluctuates after gaming

### ISSUE THREAD

**Issue by aarontrk98** [Rem0o/FanControl.Releases#1427]
**Describe the bug**
As described by the title. I've found recently that after gaming, FanControl sometimes causes CPU temp to spike resulting in linked fans ramping up and down. Restarting FanControl solves the issue.

**Relevant hardware specs and setup**
CPU: Ryzen5 5600X
Motherboard:Gigabyte B550I AORUS PRO AX

**Comment by Rem0o** [comment]
Did you catch any anormal cpu usage of FanControl to support your claim? Screenshot maybe?

**Comment by aarontrk98** [comment]
I didn't catch any high cpu usage by fancontrol but after end many tasks, close fancontrol solved the problem immediately. And after that when I encounter this issue again I just restart fancontrol and it fixes the issue every time. I will trying to see if I can capture and abnormal cpu usage next time this happens.

**Comment by Rem0o** [comment]
Could be also your fan control config depending how you set it up.

**Comment by aarontrk98** [comment]
https://user-images.githubusercontent.com/71147357/210680328-7857fda6-0ffe-4cae-b830-11be33516140.mp4

**Comment by aarontrk98** [comment]
https://user-images.githubusercontent.com/71147357/210680590-8d657f4a-468c-43b0-b3c6-8315648d5a40.mp4

**Comment by aarontrk98** [comment]
https://user-images.githubusercontent.com/71147357/210681600-26114f4f-415e-4443-a65c-af7f2eb2c6c4.mp4

**Comment by DfrostX** [comment]
Is it me or is your pump speed going to 0 RPM...

Seem like everytime there is a spike in CPU temp it`s because your pump stopped. then it start (because your pump RPM went up) until the temp is low enough, then it stops again so your temp goes up again.

I think you need to set a minimum speed to your pump so it does not stop.

**Comment by aarontrk98** [comment]
Oh man I didn't even notice that. Thank you! I guess after heavy CPU load when the pump slows down some how 30% is too low sometimes and causes the pump to stop completely.

**Comment by Rem0o** [comment]
Good catch @DfrostX, closing.
