### ISSUE TITLE
Only GPU fans Show Up

### ISSUE THREAD

**Issue by kydo26** [Rem0o/FanControl.Releases#143]
The only fans that show up in the control section are my GPU fans and not the CPU or case fans, even though it recognizes their rpm in the speed section.
![Screenshot 2021-01-04 202036](https://user-images.githubusercontent.com/77516765/106341905-84407300-6264-11eb-947d-647890aeb42c.png)

**Comment by Rem0o** [comment]
That's "normal", some chips are only interfaced for their RPM and nothing else.   You can lookup here to see if support can be added: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.
