### ISSUE TITLE
Wrong Path for when saving "configuration as.."

### ISSUE THREAD

**Issue by hl2guide** [Rem0o/FanControl.Releases#1432]
**Describe the bug**
Trying to "Save Configuration As.."  results in a weird, unchangeable path for destination.

![example](https://user-images.githubusercontent.com/17044982/210314275-7ca47e10-9e59-478c-84f2-8019a7552fd6.png)

"Load Configuration" also has the same path problem:

![example2](https://user-images.githubusercontent.com/17044982/210314738-5a6d4fcb-62b3-4013-88c0-cb257c77b508.png)

**Relevant hardware specs and setup**
OS: Windows 11 Pro 22H2
FanControl Version: 142

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/210425005-7c53c426-3aa8-406f-8426-05abca2ee55a.png)
