### ISSUE TITLE
GPU curves not following, but they follow some others

### ISSUE THREAD

**Issue by Werewolfke** [Rem0o/FanControl.Releases#1433]
(not sure if this is the same issue as some others have here, thats why a new one.)
My gpu does not follow a set curve, the 'balls' stay in the same spot, even tho the temperature keeps rising, the fans do not change.
they even just stop turning.
If i use an flat curve, or ask it to follow an other graph with mixed temperatures, it does it perfectly. making new graphs do not help for following its own temperature. it also do does not follow the cpu temp curve, so maybe it is so that he does not follow any single temp graph? its weird.
![image](https://user-images.githubusercontent.com/104201837/210549650-9a9411ac-4620-4493-89bf-11065bc9f8b6.png)
![image](https://user-images.githubusercontent.com/104201837/210549727-41c0da78-f918-40e0-a9f1-b0b5e4240dfd.png)

It might be bcs of the latest update, because it did work a few months ago.

this is an rtx3080.

BUT!!! my 1660ti in the same system does follow the graphs. and the points on there do move when temperature changes.
Would this be more of and driver issue then? idk...

**Comment by Rem0o** [comment]
In your original post, what version were you on?  V141 had issues with multi nvidia gpus.

**Comment by Rem0o** [comment]
Swap this one in V142 and see if that fixes it.

[FanControl.Library.zip](https://github.com/Rem0o/FanControl.Releases/files/10346551/FanControl.Library.zip)

**Comment by Rem0o** [comment]
Dual Nvidia gpus issues should be fixed. Closing.
