### ISSUE TITLE
Confused Config with 2x Aorus 4090's

### ISSUE THREAD

**Issue by jameslashmar** [Rem0o/FanControl.Releases#1434]
Loving this app!  However, when i come to set it up, the config saves incorrectly

I have 2x Aorus 4090's.  These are pretty niche as they are the waterforce versions with a 360 cooler and 3 fans each.
https://www.gigabyte.com/Graphics-Card/GV-N4090AORUSX-W-24GD-rev-10#kf

I figure out which is which and name them appropriately, i save the standard config, make some adjustments and save a new benchmarking config.

In the config JSON the identifier for both cards is different
`"Identifier": "NVApiWrapper/0-AD102-A/fan/0"`
VS
`"Identifier": "NVApiWrapper/1-AD102-A/fan/1"`

However, FanControl gets confused.  So if i name one front and one side, when i load the config, suddenly they both become the same name.  Also, let's say i toggle a curve to have all fans at 100% for 1 config, and then untoggle that curve to go back to standard.  

Both cards do the opposite, i.e. one will set the curve, one won't.  Then when i load the other config, the opposite happens.  

I've tried manually setting this in the JSON but it doesn't work, something is getting confused somewhere, even if i use force.

Below are the two configs and the log.txt

[https://www.dropbox.com/t/SMFJodolE6ECBHHD](url)

**Comment by Rem0o** [comment]
[FanControl.Library.zip](https://github.com/Rem0o/FanControl.Releases/files/10346548/FanControl.Library.zip)
Had a look at your config and I think I spotted the issue.

Assuming you are running the net48 version,
swap this one in and see if it fixes the issue.

**Comment by Rem0o** [comment]
Dual Nvidia gpus should be fixed. Closing.

**Comment by jameslashmar** [comment]
Just updated and can confirm. This is working brilliantly now on both of my dual 4090 machines.  I needed the unofficial Corsair plugin for my other machine to recognise those fans, which again are now working perfectly. 
https://github.com/EvanMulawski/FanControl.CorsairLink
