### ISSUE TITLE
No Intel Arc's temperature

### ISSUE THREAD

**Issue by Orion2913196277** [Rem0o/FanControl.Releases#1436]
I installed Intel Arc driver and found that the FanControl can't read my GPU's temperature while the Arc driver and HWININFO can. I asked Intel support and was imformed that the FanControl hasn't support Intel Arc GPU.
So I wish that support of Intel Arc will be added.

**Comment by DfrostX** [comment]
from the readme: [https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility](url)

>Issues and hardware compatibility
I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on the following projects. If you can't contribute meaningfully with a branch/PR, don't pollute their issue page with "XXXXX doesn't work". The hardware is needed for testing. If a dev has interest in that project, is browsing it, has your specific hardware AND the knowledge to make it work, that dev won't be looking for your issue, he'll just raise a PR.
> 
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
> https://github.com/falahati/NvAPIWrapper
> Please` only open issues on this repository for the software itself, UI, feature request and so on.
> 
> If you do have a special hardware compatibility request and you can provide a working sample of code that can be used in .NET, like with a [Plugin](https://github.com/Rem0o/FanControl.Releases/wiki/Plugins), then feel free to submit that.

**Comment by Orion2913196277** [comment]
Sorry for the message

**Comment by FreekHub** [comment]
You can still use the HWInfo plugin for Fancontrol to at least read the fanspeed and gpu temp etc, i haven't been able to make the control work on my ASRock Challenger Intel ARC A770 16GB so far

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.IntelCtlLibrary
