### ISSUE TITLE
Randomly missing settings

### ISSUE THREAD

**Issue by Littleasome14** [Rem0o/FanControl.Releases#1437]
**Describe the bug** when i shut down my pc or reset it it will either loses all sensors and setting or it will have missing settings even know i saved the setting and i have to start from scratch all over again. please let me know if you need any info its starting to get iritaing 
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
Where do you have your FanControl folder located? You can't execute it out of the zip. Once it's at a proper place, untick and tick again the Start with windows checkbox so the location updates behind the scenes.

**Comment by Littleasome14** [comment]
i unzip it in download and move it to my doc folder on the C: and than open it up and set it up and it will work for a couple of weeks and than after that it will say error sensor missing and than ill have my set up all mest up

**Comment by Rem0o** [comment]
^ What sensor missing? You'll have to be specific with exactly what is happening, with screenshots/logs.

**Comment by Littleasome14** [comment]
okay i will have to wait till it dose it again because i redownloaded the program. but if it dose act up it will normally be all case fan rpm sensor and only the fans and the gpu fan but its a amd gpu and ik you don't support it yet(cpu fan doesn't get affected). but itll display lost senor and what ever fan that it doesn't read(at one point it did all but cpu fan) I will screen shot it when it acts up and i dont know where the log is so if you can let me know so when it dose happen i can save it for you. btw amazing software.
