### ISSUE TITLE
GPU fans not adhering to curve

### ISSUE THREAD

**Issue by wistfulglen** [Rem0o/FanControl.Releases#1439]
I've set up a graph curve based on the GPU temp, with the first point being 0°C at 35%.

The intention is that I want the GPU fans to always spin at at least 35% even at low temperatures, and then ramp up from there. It doesn't seem like they actually adhere to that, since they're at a standstill most of the time when the system isn't under heavy load. They'll frequently have very short spikes where they ramp up to about 500-700 RPM for a second at a time, but then they immediately stop again.

Is there anything I can do to have it be consistent?

**Comment by Rem0o** [comment]
Many things to consider:

Can your GPU actually sustain 35% or might it be too low? Kinda like a car engine can't idle at like 100 rpm, there is a minimum speed.

Show your GPU control card expanded in a screenshot.
Show your GPU graph in a screenshot.

**Comment by wistfulglen** [comment]
> Many things to consider:
> 
> Can your GPU actually sustain 35% or might it be too low? Kinda like a car engine can't idle at like 100 rpm, there is a minimum speed.
> 
> Show your GPU control card expanded in a screenshot. Show your GPU graph in a screenshot.

[Here](https://imgur.com/a/UFvvIi2) is an Imgur album with everything!

**Comment by Rem0o** [comment]
Run this on your GPU controls: 
![image](https://user-images.githubusercontent.com/14118956/211573105-b88e31c0-078d-4261-9c84-04a6ba374912.png)

What's the resulting %?

**Comment by Zyarra** [comment]
My 4090s fans also work weirdly.
Fan start% detection is 6%(wrong)
Fan stop detection is 3%(also wrong)
My fan only stops if i set it to 0% and starts if i set to 30%.
Anything above 0% sets it to 30%, if it was higher than 30%+ earlier. If it was 0% then it won't spin up below 30%
Anything below 30% and above 0% sets it to 30%, if it was 30%+ earlier. 0% sets it to 0%
There is also an exclamationmark(!) next to the fancontrol signaling that its not behaving properly.

**Comment by Rem0o** [comment]
@Zyarra 

![image](https://user-images.githubusercontent.com/14118956/212132568-80059168-4891-45c9-aa03-a170392ad33d.png)

**Comment by wistfulglen** [comment]
> Run this on your GPU controls: ![image](https://user-images.githubusercontent.com/14118956/211573105-b88e31c0-078d-4261-9c84-04a6ba374912.png)
> 
> What's the resulting %?
The resulting % is 42.

**Comment by Zyarra** [comment]
> @Zyarra
> 
> ![image](https://user-images.githubusercontent.com/14118956/212132568-80059168-4891-45c9-aa03-a170392ad33d.png)

i didnt read that but did it anyway intuitively :)
wish i could override this min 30%. 30% is already loud and 20% is already enough... :(
well, life is such. :)

**Comment by Rem0o** [comment]
@wistfulglen  well you got your answer. You can't run your card at such low % like 35, your start % is 42.  Make sure to keep the minimum level so that your fan can at least keep a constant speed.
