### ISSUE TITLE
Turning off fancontrol curve doesn't always go back to the motherboard set fan curve

### ISSUE THREAD

**Issue by seanarimo** [Rem0o/FanControl.Releases#1441]
I have two 140mm case fans that are set with a fan curve in the motherboard bios. For info they're set to run at 20% fan speed and go up based on cpu temperature. 

Now in FanControl I have a fan curve for these two case fans which I manually turn on when I need it (when gaming). 

The issue I'm having is when I manually turn this off (after gaming) it normally sets the fans to run at 40% instead of going back to the motherboard bios setting of 20%. 

If I repeatedly press the off/on button it'll eventually turn off properly and go back to the 20% value. It's not consistent though and normally at least the first 4-5 times times I turn it off/on/off it'll always go to 40%. 

It seems like the curve on/off button is not turning off properly for this to happen. I'm not sure why FanControl is setting it to 40%. 

What am I doing wrong here?

**Comment by Rem0o** [comment]
Might it be that when you are turning it off the cpu temperature still warrants a higher value than the minimum 20% set in your bios?  FanControl can't randomly set a specific value like that when you turn the control off.

**Comment by djinnerator** [comment]
I've also noticed this recently on my ASRock B650M. I set my CPU cooler to a flat fan curve of 100%. After it reached 100%, I disabled control for Fan Control so the motherboard would take over again. My CPU fans remained at 100% until I reenabled control, changed the curve, then disabled control again.

I know for a fact it's not because "cpu temperature still warrants a higher value" because my motherboard fan curve on my CPU never reaches 100%, even at critical temperature. It can only reach 100% by manually doing that. When idle or casually using my computer, the fac power hovers between 30-40%.

**Comment by djinnerator** [comment]
> @djinnerator can you send the LHM report? (Copy report to clipboard) Don't paste the whole thing here, put it inside a txt file or something.
> 
> I want to know which superIO chip you have.

Here's the report: https://pastebin.com/BarXTFVZ

**Comment by seanarimo** [comment]
> Might it be that when you are turning it off the cpu temperature still warrants a higher value than the minimum 20% set in your bios? You mentionned a cpu bound curve in your bios.
> 
> FanControl can't randomly set a specific value like that when you turn the control off.

Thanks for replying I've taken a closer look for a while now to be sure it's not the bios cpu bound curve kicking in. Everything I see points to FanControl doing it but it's not guaranteed of course. 

Did a quick test booted PC up still cold, 2 case fans are doing their bios cpu bound 20% speed (actually 1 is set to 20% and the other is 21%). 

Start FanControl, manually turned on the Control for case fans for a brief time then I disabled it, on disabling it went to 40% fan speed.  Turned Control on again and disabled it and this time it went to the correct bios cpu curve again.

**Comment by Rem0o** [comment]
@seanarimo  can you test something for me:

Download LHM, 

![image](https://user-images.githubusercontent.com/14118956/212556790-32b13659-2dc4-47a7-9862-567efa767fbc.png)

Right click on a control sensor, set a random %, then right click again and set it to "default". What behavior do you get.  Keep FanControl closed.

**Comment by seanarimo** [comment]
@Rem0o 

Hi did a clean boot, fancontrol is not running, opened LHM, Fan at 21%. 
![image](https://i.ibb.co/m91wfW2/f1-Capture.png)

Set it Manual 80% for a minute. 
![image](https://i.ibb.co/DYVnrPX/f2-Capture.png)

Set it back to Default and it went to 40%.  (arrggh!)
![image](https://i.ibb.co/RbDrNQ3/f3-Capture.png)

Set it Manual 80% again.
![image](https://i.ibb.co/XpR4XYt/f4-Capture.png)

Set it back to Default and it went to 21%.
![image](https://i.ibb.co/5BNsgbG/f5-Capture.png)

**Comment by Rem0o** [comment]
That confirms where the underlying issue is.  

As for the multiple system fans, the detected control chip probably has unused channels on your motherboard.

**Comment by seanarimo** [comment]
Why would Default revert to 40% after having manual control? Is the motherboard alarmed that it's not in control anymore?

**Comment by Rem0o** [comment]
> Why would Default revert to 40%

That, I have no idea. Would probably have to dig/debug the back to default routine for your specific chip.

**Comment by seanarimo** [comment]
I understand it's good I know for sure now it's a problem on my end. Thanks for your replies and time.
