### ISSUE TITLE
Force Apply regularly stops working

### ISSUE THREAD

**Issue by Dilvanon** [Rem0o/FanControl.Releases#1442]
Issue:
Starting a few updates back, I needed to use the 'force apply' option for my fan curves to work. Still though, every 10ish minutes, the force apply seems to stop working and all my fans are ramping up to full speed for about 2 seconds, before returning to their set speed (presumably, the force apply kicks back in). As far as I have observed, the issue only occurs under load.

I could observe that the issue was mostly occuring under heavy CPU load and both with FanControl minimized or opened. Though, occasionally the issue occurs in idle state, too. I was able to sometimes circumvent this issue by setting my BIOS fan curves (which were overwritten by FanControl, as desired, beforehand) to be based not on CPU temperature but on another temperature sensor, which would be mostly unaffected by CPU temperature increases. Still, under heavy CPU load I could briefly witness the '?' to appear next to the '!' force apply icon on some of my fans.

Further information:
- My fan curves are based on my water temperature fetched by HWInfo. 
- I am using an MSI motherboard, the BIOS version did not change since using FanControl.
- The log.txt also does not show any new entries.
- I am using Windows 10 (up to date).

**Comment by Rem0o** [comment]
Force apply won't prevent an other source from ramping up the fans, but it will override that immediately, as you are experiencing. What you need to figure out is what is ramping up your fans to 100%. You mentioned under load, might it hit a specific high temperature where your motherboard will override ?

**Comment by Dilvanon** [comment]
That's the strange thing, as per my BIOS, no fan should ever go to full speed. Either, they are in smart fan mode and I have them set to 30% at all times or I disabled smart fan mode (where possible) and defaulted them to 30%.
Regarding the temperature, as it was happening both during heavy CPU load (Cinebench to test and gaming as normal use case) AND sometimes in idle, I could not pinpoint an exact temperature, where this would happen.

**Comment by Rem0o** [comment]
Just noticed you are using HWInfo as a source. Is it just happening with curves that are bound to HWInfo sensors?  If for any reason HWInfo stops reporting the sensor for a while, FanControl will invalidate the sensor and the curves will go into "failsafe" mode, aka 100%, until the sensor comes back.

**Comment by Dilvanon** [comment]
Yes, all these curves are bound to HWInfo sensors.
Good call, I updated HWInfo - so far, the issue hasn't occured again. Thanks for the help!

**Comment by Dilvanon** [comment]
Did some more observations, the 'fix' seems only to be coincidental, the issue still occurs. All my curves are bound to one singular HWInfo sensor, so thinking that HWInfo just stops working should ramp up all fans, but it is mostly one fan (group, connected to one header), but also not always the same, it switches around. The issue also does not seem to be connected to one singular fan curve in FanControl, as sometimes a singular fan ramps up with others bound to the same curve do not. Any ideas on software side?

**Comment by Rem0o** [comment]
From the software side, it would be all or nothing. There is no reason a single control would randomly get applied a 100%.  The logic is dead simple enough. It's basically:

Read fan curve => apply value to control register if different than previous. 

As I previously stated, a missing sensor will cause a fan curve to fail-safe to 100%, but every controls bound to that fan curve would behave the same. 

Can you share your config? Screenshot and json file.

**Comment by Dilvanon** [comment]
Here is my config:
Screenshot:
![FanControl_Config](https://user-images.githubusercontent.com/106605765/211596407-4ac2450f-9e79-4285-90f9-5faaa74d5376.png)

json file as txt (.json not supported for upload):
[FanControl_json.txt](https://github.com/Rem0o/FanControl.Releases/files/10384395/FanControl_json.txt)

Some explanation:
Radiator 1 and 2 are configured with three fans in chained connection, wirde to one fan header. All other fans are connected to one fan header each. HWInfo pulls the the water temperature from an Aquacomputer D5 as the only parameter for the two fan curves.

**Comment by Dilvanon** [comment]
Not really - some things come to my mind: I'm always running Aquacomputer's "aquasuite" to monitor temps etc., which is theoretically able to control fan speeds, but I do not have their fan hub, so hardware requirements are not met to control fans with this software. I have MSI Afterburner installed, but only to use RivaTunerStatisticsServer - I know that there are some fan curve controls in Afterburner, but I haven"t touched those ever. That should be all (excluding BIOS settings of course).

**Comment by Dilvanon** [comment]
Update: problem supposedly fixed
First I set the flat fan speeds in BIOS at 45%, since there is an info given that fans might behave strange if not in smart fan mode and set to a speed slower than 40%. Though, the problem still occured. Now, I actually ENABLED a constant fan curve of 30% in MSI Afterburner and the problem hasn't occured anymore and the force apply works as intended.
