### ISSUE TITLE
Asus Prime X470-Pro (Very Slow Ramping)

### ISSUE THREAD

**Issue by N3RD-MAN** [Rem0o/FanControl.Releases#1443]
This Software is a Game-Changer for most users..... But...

..... In my case, After a few updates which i can not recall!!! the software started to develop a very very slow ramping problem! It is not my hardware nor is it my bios setup.. I have tried other software capable of doing what FC does and it does not have this issue...

The only options selected in sensor are 

Motherboard
CPU 
GPU

I also noticed someone else with the same motherboard saying the same thing, I do not want to revert back to version 112 which works but isn't playing nice with certain options. 

Please resolve this issue or its back to using hardware bios 

I started using this software for a (GPU FAN MOD) Fans connected to motherboard to control temps.

**Comment by N3RD-MAN** [comment]
Seriously ? 

You see how complicated you make things, I already told you what the issue is.... 

After a few updates things just decided to not work properly. 

It has nothing to do with me changing anything, (STEP UP/STEP DOWN) Untouched like eveything else is untouched. 

You have changed the way you progrmmed your software and that is why it doesnt work properly.

**Comment by Rem0o** [comment]
> You have changed the way you progrmmed your software and that is why it doesnt work properly.

That's an assumption you made on your side. If it was as simple as that,  the problem would affect everyone, but it doesn't. So clearly something specific is going on, hence why I need details, otherwise I won't be able to help you properly. 

You'll have to define "Slow ramping".  Is it the fact your fans don't hit the expected RPM and stay low? Do your fans hit the max rpm but it takes a while? How long? Give me a specific exemple, and also send your json config file.

**Comment by N3RD-MAN** [comment]
Slow Ramping is exactly what I am describing..... 

I move the slider up on manual, it takes up to 1 minute or more for the percentage to go up or down. 

Now with automated settings with fan curves! the same very thing as stated... 

slow ramping

**Comment by Rem0o** [comment]
Is there a "?" appearing on the control card as it happens?  Also, send your json config file you are using.

**Comment by N3RD-MAN** [comment]
[Fini.zip](https://github.com/Rem0o/FanControl.Releases/files/10374298/Fini.zip)

I apologise for my frustration, But i really appreciate this software :) 

I have supplied the file you requested, I just want to say version 112 works fine other than slight bugs with forgetting cpu from time to time.

**Comment by Rem0o** [comment]
2 things:

* When the slow ramp up happens, is there a small "?" appearing on the control card you are playing with.
* Take the LibreHardwareMonitorLib.dll file out of V112, copy it, and paste it onto a folder containing V142, then start V142.  Does the problem occur still in that "modified" V142 version?

**Comment by N3RD-MAN** [comment]
The slow ramp up does not have any question marks. 

Okay, replacing the "LibreHardwareMonitorLib.dll" resolved the issue, but what happens when it requires an update! will it overwrite the LibreHardwareMonitorLib.dll file ? 

Thanks, I should of thought of this myself but I didn't want to corrupt the software.

**Comment by Rem0o** [comment]
Yes, any new update will override the LHM lib.

**Comment by N3RD-MAN** [comment]
So I should just keep a back-up of 112 until you find a solution to this problem, because I am not the only person with this issue as I have read around... !!! 

It's not my place to suggest anything but it would be nice keep it simple and have several version catering for different chipsets ? or just have a GPU only version for thos of us that mod our GPU's with 120mm fans running from the motherboard using the GPU sensor.

**Comment by Rem0o** [comment]
> I am not the only person with this issue as I have read around... !!!

Can you point me links to that?

I have not seen any problem of that sort yet.

**Comment by Maloonkey** [comment]
A bit late, but I am also an Asus Prime x470-Pro user and updated from an older version and this has happened to me. FanControl is practically unusable now as it takes upwards of 30 seconds for sensors to update reported temps and fan speeds, and for the fan speeds to change.

**Comment by Rem0o** [comment]
^ @Maloonkey   if you download LibreHardwareMonitor directly, do you experience the same slow update issue in there? Make sure you got FanControl closed as you do.

**Comment by Rem0o** [comment]
One of my guess that is specific to Asus boards is this: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/1131b4098da66b76c83efc6375f961420fe416fc/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/EC/WindowsEmbeddedControllerIO.cs#L20

The code that manages the EC seems to have a retry mechanism that will hang the whole thread until it succeeds or fails after multiple attemps.

**Comment by N3RD-MAN** [comment]
Thanks for notifying Rem0o on this matter, You are the fifth person to bring this up that I have seen online. 

Its a strange thing that it's only Prime x470-Pro users. also windows 10 cumulative updates seem to effect the software :S

NZXT H510 (2X REDUX NOCTUA 120mm 1700RPM) Exhaust
RM750X White
DeepCool CAPTAIN 240 EX WHITE AIO (2X REDUX NOCTUA 120mm 1700RPM)
Ryzen 7 5800X3D
Asus Prime X470-Pro
Corsair Vengeance RGB-Pro DDR4 32GB 3600Mhz 4x8
RTX 3070Ti (Primary GPU)  
Sapphire Nitro+ SE RX 580 8GB (2X REDUX NOCTUA 120mm 1700RPM) MODDED
Crucial 1TB 970 Evo (NVME)
WD Blue 1TB SN550 (NVME) 

WINDOWS 10 21H2 (19044.2486)

**Comment by Rem0o** [comment]
@Maloonkey  I'm pretty sure it is the asus EC stuff then. There isn't a way to disable it from FanControl's perspective. Will take a look on LHM's side and see what I can do.
