### ISSUE TITLE
Can't detect temperature of m.2

### ISSUE THREAD

**Issue by rocapillon** [Rem0o/FanControl.Releases#1444]
How can I make it detect the temperature of the m.2? I'm thinking of buying a heatsink with a fan, but since it doesn't detect the temperature I can't configure a curve

Specs in attachement

![Sin título](https://user-images.githubusercontent.com/22078482/211227611-94452359-2091-436e-9df5-2adb0d41af50.png)

**Comment by DfrostX** [comment]
Until it get fixed in LibreHardwareMonitor (the library from which FanControl pull its data), you could try the Hwinfo plugin [HWinfo Plugin](https://github.com/Rem0o/FanControl.HWInfo)

**Comment by rocapillon** [comment]
It didn't work, it was my fault not to select storage, I'm sorry, I removed nvapiwrapper and now even more graphics sensors appear, thanks for the help
It didn't work, it was my fault not to select storage, I'm sorry, I removed nvapiwrapper and now even more graphics sensors appear, thanks for the help
![Sin título](https://user-images.githubusercontent.com/22078482/211943698-f6f15558-a9d2-41f4-9b73-868bb9a03451.png)
