### ISSUE TITLE
cannot control one of my fans

### ISSUE THREAD

**Issue by henryyywong** [Rem0o/FanControl.Releases#1449]
I got 2 chained rear fans, 1 CPU fan, 2 chained front fans hooked up to my pwm on my MB at sys_fan1, cpu_fan, sys_fan2 respectively.
However, in Fan Control, i can only adjust the fan speed of my CPU and front fans only. The rear fans are only detected but not in control.
In HwMonitor, i can see the rpm of all fans.
How can i fix this?
specs:
CPU: R5 3600
MB: MSI B450M MORTAR MAX

**Comment by Rem0o** [comment]
You can't "fix" this. 

"The rear fans are only detected but not in control."
"In HwMonitor, i can see the rpm of all fans."

Those are equivalent. HWMonitor can't control your fans also.  

See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
