### ISSUE TITLE
Feature request: Disable logs

### ISSUE THREAD

**Issue by brunoherrera** [Rem0o/FanControl.Releases#1452]
Hi, I'm having lots of entries to log.txt because of HWiNFO janky solution for NZXT Kraken sensors, FanControl is logging "1/11/2023 14:42:16: HWInfo sensor value went missing from registry: HWInfo/NXZT Kraken X53/X63/X73/Liquid Temperature/°C, HWInfo/NXZT Kraken X53/X63/X73/Pump/RPM" every one or two seconds, everything works perfectly though. So, having the option of disabling logging would be a good addition in general.

Windows 10
FC v142
HWiNFO64 v7.36-4960

UPDATE: found out about FanControl.Liquidctl and I don't have any issues now, will clsoed the issue, but I still think it would be a nice addition to be able to disable logs.

**Comment by Impact123** [comment]
You should probably not close the feature request then.
