### ISSUE TITLE
Feature Request: Support for Lian Li SL120 V2 Fans

### ISSUE THREAD

**Issue by pfilbin90** [Rem0o/FanControl.Releases#1456]
I have a Lian Li build with 7 SL120 V2 Fans and then 3 SL120 (version 1) fans from their Galahad AIO Cooler.  10 fans total and FanControl doesn't appear to be able to recognize any of them.  None of them respond to the automatic setup.  I am requesting that these fans get officially supported.

Thanks

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

**Comment by EightB1ts** [comment]
Hi @pfilbin90 !

I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi
Looking for beta testers. If you have time, please let me know if it works for you!
