### ISSUE TITLE
When FanControl is minimizes, there's a debug warning firing every second

### ISSUE THREAD

**Issue by Noctis-** [Rem0o/FanControl.Releases#1457]
**Describe the bug**
It would seem that when fan control is minimized, these messages will pump out every second , polluting the [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview).
If i open program so it's not minimized they go away.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
![image](https://user-images.githubusercontent.com/6160139/212433368-f3f0fd63-dd04-447b-ad65-b2c935763a57.png)

**Relevant hardware specs and setup**
using version 142 on a win 10 machine

**Comment by Rem0o** [comment]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2a38b2c70a5e851bc5b926e0641c1848e719d86b/MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs#L300

DebugView registers as a listener, so as soon as it hooks to the process, it will start picking it up.
