### ISSUE TITLE
Increase resolution for temperature

### ISSUE THREAD

**Issue by sctanf** [Rem0o/FanControl.Releases#146]
On steeper curves, 1 degree of resolution changes the fan speed too much.

**Comment by Rem0o** [comment]
Well, the sensors don't have decimal precisions, so I don't see the point of allowing decimal precision in the software?

**Comment by sctanf** [comment]
In LibreHardwareMonitor they do, at least for my CPU sensors. I also checked in Hwinfo.

**Comment by Rem0o** [comment]
Can you explain me the exact use-case where sub-decimal precision is required for a fan curve on a 30 to 100 deg range?

**Comment by sctanf** [comment]
Most of my fan curve is concentrated at the 75-85 range, where the fanspeed
would change up to 5% per degree. I switched to FanControl because it's far
better than my bios fan control, but the decimal precision is the only
thing I miss.

**Comment by Cubox** [comment]
@sctanf Can't you mitigate that with changing the fan speed change value? Put it to 1% and see if that helps

**Comment by Rem0o** [comment]
You can play with response-time, hysteresis, and step % as @Cubox said to try and get the desired behavior.

Step% is "control" based though, it's not in the fan curve.

**Comment by sctanf** [comment]
> @sctanf Can't you mitigate that with changing the fan speed change value? Put it to 1% and see if that helps
I think that would ramp my fan too slowly to be useful, unless the update speed was adjustable to 100ms

**Comment by sctanf** [comment]
> You can play with response-time, hysteresis, and step % as @Cubox said to try and get the desired behavior.
> 
> Step% is "control" based though, it's not in the fan curve.

Okay, thanks.

**Comment by Cubox** [comment]
I think this is where https://github.com/Rem0o/FanControl.Releases/issues/107 would help

If you could have fan change be instant on increase but slow on decrease you would have an answer to your problem.

**Comment by sctanf** [comment]
> I think this is where https://github.com/Rem0o/FanControl.Releases/issues/107 would help
> 
> If you could have fan change be instant on increase but slow on decrease you would have an answer to your problem.

That's not the issue I'm having, the change is still only at a minimum 5% fan speed. If the temperature is stable and changing slowly, there is a sudden 5% jump when it crosses a degree (and a ramp of <5 is too slow)

**Comment by Cubox** [comment]
Just to be certain, where exactly do you need the increased resolution? On temperature readings only? In the graph window, for putting points per sub-degree?

**Comment by sctanf** [comment]
> Just to be certain, where exactly do you need the increased resolution? On temperature readings only? In the graph window, for putting points per sub-degree?

Sub-degree plotting would require the first to work. I really only need the temperature reading to be precise.

**Comment by Cubox** [comment]
At the risk of starting to be too insistant, and please don't take this the wrong way Rem0o, https://github.com/Rem0o/FanControl.Releases/issues/89 would be your definitive answer.
Depending on the amount of work needed to make it work, it would be really easy for me to create a patch for you. That could be either merged into the main source, or if Rem0o does not like it, you could keep your own binaries with that change.
If it's only making the reading more precise, I'd guess in a few minutes that can be patched

**Comment by Rem0o** [comment]
> In LibreHardwareMonitor they do, at least for my CPU sensors. I also checked in Hwinfo.

But do you actually get meaningful sub-decimal reading? In my case, none of my sensors get anything but "0" at the decimal level. Also, I extract a "float" already from LHM, so if there was sub-decimal precision, you would get it.

**Comment by sctanf** [comment]
> But do you actually get meaningful sub-decimal reading? In my case, none of my sensors get anything but "0" at the decimal level. Also, I extract a "float" already from LHM, so if there was sub-decimal precision, you would get it.

I do, I have checked in LibreHardwareMonitor and in Hwinfo as well. Both show precision to the 0.1 degree. Either something in FanControl or LibreHardwareMonitor is rounding the temperature, because I don't see evidence of a sub-decimal precision temperature being used.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/106408008-62352500-640b-11eb-9e9e-af1bed48c178.png)
![image](https://user-images.githubusercontent.com/14118956/106408016-6cefba00-640b-11eb-86b6-b097438f6931.png)

I double checked in LHM, the UI and interface exposes a decimal, but the underlying value is an int.

**Comment by Cubox** [comment]
![image](https://user-images.githubusercontent.com/479129/106408146-1f407500-643e-11eb-9b2f-26851a760d82.png)
![image](https://user-images.githubusercontent.com/479129/106408155-249dbf80-643e-11eb-9e48-fa8e6fbd7190.png)

**Comment by sctanf** [comment]
LibreHardwareMonitor
![CPU](https://user-images.githubusercontent.com/36978460/106408297-cf44bc80-6403-11eb-92e7-ef73ebdd9306.png)
Hwinfo (Update rate set to 100ms)
![Hwinfo](https://user-images.githubusercontent.com/36978460/106408483-29de1880-6404-11eb-8fe0-28d74c842595.png)

**Comment by sctanf** [comment]
![FC](https://user-images.githubusercontent.com/36978460/106408883-f354cd80-6404-11eb-8eda-dd26c854119c.png)
Using an external file as a dummy sensor, it only responds at 1 degree intervals.

**Comment by Rem0o** [comment]
Ah, didn't check all the sensors for every hardware type, but indeed it seems like Ryzen does exposes more than a hundred or so meaningful values.

> That's not the issue I'm having, the change is still only at a minimum 5% fan speed. If the temperature is stable and changing slowly, there is a sudden 5% jump when it crosses a degree (and a ramp of <5 is too slow)

However, I still find your use-case quite weird. Normally, you wouldn't want to have your "load" temperature area to be in the steep part of the curve, since you will get constantly changing fan speed. Sub-decimal precision won't change that annoying behavior.  You could get away with it with a high one-way hysteresis, like 10 degree or something like that, and the fan speed would only ramp down with a 10 degree drop.

**Comment by sctanf** [comment]
In practice the steep curve works fine. The only issue is that if the temperature is slowly increasing there is still a 5% jump, no matter the hysteresis. There is more than one way to try and mitigate this, if you can't do decimal precision. Maybe the step size can change dynamically?

**Comment by Rem0o** [comment]
I think 2 way step size is the only way to go.   Will see how to implement it in the future.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V68

**Comment by Rem0o** [comment]
Decimal precision is now possible in the graph fan curve.
