### ISSUE TITLE
Request: PluginSensorsContainer activity list

### ISSUE THREAD

**Issue by emko764** [Rem0o/FanControl.Releases#1460]
Can you provide a new List "ActivitySensors"?
I managed to inject some sensors with the HWinfo and added new sensor type "Activity" with values containing percentage sign in the plugin. The only problem is visual. In FanControl I can only set them as TempSensors and they show with temperature sign. So a new list that show "%" will be perfect.
Regards!

**Comment by Rem0o** [comment]
And where would that new type of sensors fit into FanControl?

**Comment by Rem0o** [comment]
The work required to integrate a new type of sensor as an input is kinda big.

 Each field where you can select a temperature has a value range, text, tooltips and so on. All of those would have to be dynamic depending on the type of sensor. Not saying its not doable, it very much is, just wanted to put some perspective as to the amount of work required to make this nice and maintainable.
