### ISSUE TITLE
Fan Control will not control...

### ISSUE THREAD

**Issue by Turner77a** [Rem0o/FanControl.Releases#1461]
Hi.
Have a x670e Hero asus, and running commander pro (fan hub). I see the fans. But when trying to control the fans nothing happens. Pls advise.

**Comment by Rem0o** [comment]
What you see in the software aren't fans, but fan headers, the ones on your motherboard. If nothing is plugged into them, you won't have anything to control. 

If your fans are plugged into the commander pro, you could try this plugin made by a community member:
https://github.com/EvanMulawski/FanControl.CorsairLink
