### ISSUE TITLE
Fan Control locks all changes from Bios untill i physically turn computer off and on again.

### ISSUE THREAD

**Issue by Cerunnir** [Rem0o/FanControl.Releases#1465]
Motherboard: Gigabyte Z690 AORUS PRO w/latest bios.

I control my CPU, GPU and Case fans with Fan Control.

I have set the fan curve to "silent" on CPU and Case in Smart Fan 6 in the Bios.

If I reboot the computer with Fan Control running, the computer puts all the fans to 100% speed before windows and Fan Control boots up again. It I enter BIOS and try to change the fans, I am unable to adjust them at all. They are locked at 100%, no matter what setting I apply. It seems that Smart Fan 6 loses the ability to control the fan speed. It can read the speed just fine at 1500 RPM, but I am not able to adjust it.

To fix it I have to shut the computer down, and start it up again with the power button. When I do this, BIOS regain the ability to control the fans. Just rebooting (not using "shut down") don't fix it.

If it is stuck at 100%, Fan Control does fix the speed once it boots up.

It's not a big deal that the fans run at 100% once in a while when I reboot, but I though I would report the issue.

It only happens if I reboot, and not if I manually exit Fan Control by right clicking the tray icon. It seems to me that Fan Control does not reliquish control back to the BIOS correctly when windows shut down the program during the reboot sequence.

**Comment by Rem0o** [comment]
When you shutdown, do you get a "force shutdown" prompt from Windows?

FanControl is hooked to the shutdown routine for windows where it will check for unsaved change and exit the app, as if you manually exited.  However, this event is finnicky and may not let the app the time to completely release all important resources.  Will take a deeper look later this week.

**Comment by Cerunnir** [comment]
I also suspect it is related to how Windows shuts down the program. I noticed that sometimes I can reboot a few times before the problem shows up. The "force shutdown" does pop up but I only notice the steam client in there for a split second. I did not notice Fan Control in that list. It's a pretty fast computer with i7-12700k and a lightning fast NVMe drive. Could be that the computer grinds through the shutdown routine to fast sometimes?

**Comment by RADon0880** [comment]
Got same problem on gigabyte aorus elite z690m ddr4

**Comment by bleeptech-nl** [comment]
Same problem. Gigabyte B550I Aorus Pro AX.

I've done some research. 
A whole list of motherboards with the same issue is listed here
https://www.reddit.com/r/gigabyte/comments/144w41f/issues_with_3rd_party_fan_control_softwares/
(with another reddit mention at https://www.reddit.com/r/gigabytegaming/comments/js7y9x/aorus_pro_b550m_unable_to_adjust_fan_speed_stuck/)

And then there seem to be duplicate issue reports in this github of people who seem to experience the same
https://github.com/Rem0o/FanControl.Releases/issues/1465
https://github.com/Rem0o/FanControl.Releases/issues/2676
https://github.com/Rem0o/FanControl.Releases/issues/2004
https://github.com/Rem0o/FanControl.Releases/issues/1751
(list not exaustive)

@Rem0o You may be on to something when you say that FanControl does not get enough time to restore the BIOS settings. But still, plenty of people have these boards. Any chance you could look into this again?

I also noticed an effect where if I set my BIOS curve points to 0% (exept the highest one which is fixed at 100) the BIOS, when warm booting, turns the fans full-on 100% for say a second, and then off 0% for a second. This keeps repeating until FanControl starts when windows loads.
This only happens with the BIOS points set to 0%. Anything higher defaults to 100% fan speed all the time until FanControl starts.
Maybe that gives a clue, maybe not. You'll have to judge.

I'm available for testing.
