### ISSUE TITLE
T_Sensor not detected on Asus Z790 Platform

### ISSUE THREAD

**Issue by DIDOUDD** [Rem0o/FanControl.Releases#1468]
Hello, first thanks for this great tools. I use Fancontrol to monitor the water temperature of my WaterCooled with a Asus B550, it's good. But I changed my motherboard with a Asus Strix Z790-F and the T_sensor in Fancontrol has disappeared (like aida64) but appears in ArmouryCrate or in the Bios. Could you see that in your futurs updates, thanks in advance.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.
