### ISSUE TITLE
Release 143 broke fan and AIO detection

### ISSUE THREAD

**Issue by aj0413** [Rem0o/FanControl.Releases#1474]
Without looking at source code can't be too sure on what's causing the behavior but release 143 does not detect my fans or AIO. This isn't a problem in 142 and a current workaround seems to be to install the previous version and then upgrade.

I use a Kraken Z73 AIO and a number of Uni Li SL120 v2 fans connected to one of their hubs; the AIO would be Fan 2 below and the hub is Fan 4. As you can see, release 142 has no problems detecting and reporting these devices. And while I use liquidctl to control the AIO speed, FanControl does allow me to control my fan speeds through the hub. 

You can see in the error report from 143 an issue with missing method from LibreHardwareMonitor. Further, I noticed that a number of dependencies was removed from the fancontrol.deps.json in 143; as well as some dlls, ex. System.IO.Ports.dll ... which does seem to coincide with the stacktrace (unless the hardcoded path reference is in the issue).

I'm attaching the reports generation by each version, the error log from 143, and images of each as a point of comparison to highlight what I mean when describing the behavior.

Love this software and use it all the time, so I spent some time trying to debug it myself, but hands are kinda tied without source code. 
[report-142.txt](https://github.com/Rem0o/FanControl.Releases/files/10454778/report-142.txt)
![image-142](https://user-images.githubusercontent.com/18425821/213389042-76422248-37ec-4d24-8cf5-68fdef9af7fa.png)
[report-143.txt](https://github.com/Rem0o/FanControl.Releases/files/10454779/report-143.txt)
![image-143](https://user-images.githubusercontent.com/18425821/213389044-5ed8d5fc-f32e-4f18-b777-c3ac1487076b.png)
[error-log-143.txt](https://github.com/Rem0o/FanControl.Releases/files/10454780/error-log-143.txt)

**Comment by Rem0o** [comment]
Noticed that the net7 was broken along the way.   Deleted it. Use the net48.

**Comment by aj0413** [comment]
You’ll probably want to reach out and update the scoop manifest then since it currently only targets the net7 version. 

I’ll go ahead and use my own manifest in the meantime to target net48
