### ISSUE TITLE
Flicker

### ISSUE THREAD

**Issue by Vikthor77** [Rem0o/FanControl.Releases#1477]
When there is a refresh and the main window is on the screen, the monitor flashes while the fan is running.
If I move the mouse over the fan, it spins for a few seconds, and the monitor flickers.

**Comment by Rem0o** [comment]
You got GSYNC I suppose?

**Comment by Vikthor77** [comment]
Yes, I use Gsync compatible mode, but the problem occurs even when it's turned off.

**Comment by Rem0o** [comment]
I can't find the issue, but some other user had the same issue. I think the solution was to go to the Nvidia control panel, and go to the program list, and set Gsync/vertical sync off for FanControl specifically.
