### ISSUE TITLE
"Target" fan curve is not working as intended?

### ISSUE THREAD

**Issue by marhensa** [Rem0o/FanControl.Releases#148]
For what I understand, 
"target" fan curve keeps fan running **until** specific idle temps are reached out.

But it seems fan speed always runs at "Load fan speed" even when idle temperature is reached, even at lower temperature.

Here's ther screenshot, 
my idle temp is 35C, load temp is 45C.
my idle fan speed is 18%, load fan speed is 65%

When temperature reached 35C, even until stuck at 32C, fan speed still runs at 65%.

![Screenshot 2021-01-31 132829](https://user-images.githubusercontent.com/816600/106376497-70158680-63c8-11eb-9ccf-8165a27ca4aa.png)

I'm using version V65.

**Comment by Rem0o** [comment]
Yep, there is a bug in the temperature selection which doesn't read it properly. Will fix in next version.
