### ISSUE TITLE
Feature request: Custom LHM dll

### ISSUE THREAD

**Issue by Cubox** [Rem0o/FanControl.Releases#1484]
Hi,

A quick feature request:
I use a custom LHM dll that I compiled myself from the LHM code, with a patch that they rejected for DIMM temperature support.
The update process will each time remove my own LHM for your one.

Could there be a way to set the update process to not touch LHM?
This is a very low-priority feature request.

Thanks :)

**Comment by Rem0o** [comment]
I can hardly see how that would be doable in a convenient way. Right now the updater just unzip everything on top.

**Comment by rzhlm** [comment]
> Hi,
> 
> A quick feature request: I use a custom LHM dll that I compiled myself from the LHM code, with a patch that they rejected for DIMM temperature support. The update process will each time remove my own LHM for your one.
> 
> Could there be a way to set the update process to not touch LHM? This is a very low-priority feature request.
> 
> Thanks :)

Hi @Cubox , could you explain what you modified in LHM to get the DIMMs working?

**Comment by Cubox** [comment]
@rzhlm https://github.com/Cubox/LibreHardwareMonitor
