### ISSUE TITLE
Manual Control Grayed Out

### ISSUE THREAD

**Issue by Aloofyy** [Rem0o/FanControl.Releases#1485]
![image](https://user-images.githubusercontent.com/123345762/213963383-e83f885d-5353-4414-8e82-5654d982c2da.png)
It looks something like this
could someone help me?

**Comment by Impact123** [comment]
Try enabling this
![image](https://user-images.githubusercontent.com/899193/213964146-6c49f6dd-695d-4fe8-93f8-9acc41eda394.png)

**Comment by Aloofyy** [comment]
> Try enabling this ![image](https://user-images.githubusercontent.com/899193/213964146-6c49f6dd-695d-4fe8-93f8-9acc41eda394.png)

tysm it works and im sorry for sounding stupid lol
