### ISSUE TITLE
Suggestion: remove -30% offset limit or add option to disable fan on rpm trigger

### ISSUE THREAD

**Issue by NeverUsedID** [Rem0o/FanControl.Releases#1487]
I like  to bring a fan down to 0 rpm while another fan is running

Story:
I have a fan close to my AMD GPUI to allow Zero RPM feature to work properly when two monitors ar used. because AMD limits the minium speed of a fan to 23% and thats really noisy. So i decided to add another fan to the side of the GPU which its not hearable. But i do not want to interfere the airstream of the gpu fan once its is starting up, so i need an option to disable the fan, while the gpu fan is running. I thought i could use a sync curve, but the offset is limited to -30%

**Comment by Rem0o** [comment]
Fair enough. 30% was an arbitrary limit but there is really no reason for it.

**Comment by NeverUsedID** [comment]
Thinking about it in the evening, it still would be nice to not have a limit on the sync curve, but it would not solve my problem, i think. What i need is a logic like: "Switch fan X off, when Fan Y is running."

**Comment by Rem0o** [comment]
You can also use the subtract on a mix to do that kind of logic, but there are many ways to achieve this.

**Comment by NeverUsedID** [comment]
Thanks for your answer, i tried that before, but that was not working very well, but i think it was more a problem in front of the keyboard :) . The one with the curve was easy. Nice that this is possible as most program do not allow to go to lower rpms on higer temprature. Thanks for your support. Will send a small donation right away to support you too.
