### ISSUE TITLE
Possible Bug: polling plugins and .exe files

### ISSUE THREAD

**Issue by brunoherrera** [Rem0o/FanControl.Releases#1488]
Does Fan Control launch executables inside plugins folder (example: liquidctl.exe) when updating sensor info? because I see it constantly opening and closing that .exe and is taxing the cpu non-stop.

**Comment by Rem0o** [comment]
In the case of that specific plugin, sadly yes, it would seem to be highly inefficient since it most likely call the exe at every update cycle ( 1 Hz ) to push and pull the information.  

That's specific to that plugin implementation.

**Comment by brunoherrera** [comment]
> In the case of that specific plugin, sadly yes, it would seem to be highly inefficient since it most likely call the exe at every update cycle ( 1 Hz ) to push and pull the information.
> 
> That's specific to that plugin implementation.

super sad, thanks! I'll close this issue
