### ISSUE TITLE
FanControl software does not have the option to pair the pump fan to the custom sensor.

### ISSUE THREAD

**Issue by Chummpp** [Rem0o/FanControl.Releases#1489]
**Describe the bug**
[I have a liquid cooled Gigiabyte RTX 4080 and I would like to pair the radiator fans to the custom sensor. The problem is I can't pair the radiator fans to the custom sensor because the option to do that is missing. The only option available is to pair the speed sensor which is not the same thing as the custom sensor.]

[The log file is blank/empty]

**Relevant hardware specs and setup**
[A liquid cooled RTX 4080]

**Comment by Rem0o** [comment]
What do you mean "custom sensor"?

**Comment by IkarosForever** [comment]
I have the same problem. I set a fan to pump_fan2, I can control the fan in BIOS, but I cannot find the option in fancontrol. I am the MSI Z790 ACE
