### ISSUE TITLE
Mix fan curve accepts itself as an input

### ISSUE THREAD

**Issue by Taudris** [Rem0o/FanControl.Releases#149]
Shouldn't the mix fan curve you're editing be hidden from itself?

![image](https://user-images.githubusercontent.com/1720131/106382942-bc84a600-6377-11eb-8705-a61f9448eb9a.png)

To make things even more complicated, a hypothetical Mix A could be an input to Mix B, and then Mix A could be altered to accept Mix B as an input, causing Mix A to reference itself indirectly through Mix B (and B through A). This should also not be possible. But it does at least seem less likely to occur than what I've highlighted here, so maybe it's not worth the coding exercise to identify and prevent this case.

**Comment by Rem0o** [comment]
Well, try it, I put some validation in which should prevent funny scenarios.

**Comment by Taudris** [comment]
Ah, so I see. It shows in the dropdown, but you get a message when you select an invalid item. Even the Mix A and B example I gave fails with a message. Good enough for me.
