### ISSUE TITLE
After v144 FanControl wakes PC from sleep

### ISSUE THREAD

**Issue by b1ckdrgn** [Rem0o/FanControl.Releases#1490]
As per title, after the v144 update FanControl consistently wakes the PC from user-initiated sleep.  This was not happening prior to v144

PC is Windows 10, fully patched

**Comment by Rem0o** [comment]
Any plugin? Did you try a rollback to V143?
You're the first to report sleep issues, and V144 didn't change anything really that could relate to that.

**Comment by b1ckdrgn** [comment]
Sorry, what plugins do you mean?  I'm going to try rolling back this morning.

In the event logs I get the following right after it wakes back up:

1st: 
Event ID 1
The system has returned from a low power state.

Sleep Time: ‎2023‎-‎01‎-‎26T05:13:27.539351900Z
Wake Time: ‎2023‎-‎01‎-‎26T05:14:38.625237700Z

Wake Source: Timer - FanControl.exe


2nd:
Event ID 7045
A service was installed in the system.

Service Name:  R0FanControl
Service File Name:  C:\FanControl\FanControl.sys
Service Type:  kernel mode driver
Service Start Type:  demand start
Service Account:

**Comment by b1ckdrgn** [comment]
I see what you mean by plugins - no, not running any of the plugins

**Comment by Rem0o** [comment]
Try and disable "storage" in sensor settings.

**Comment by b1ckdrgn** [comment]
I've already reverted to the previous version and didn't choose storage when I set it up - if that seems stable for a few nights I'll update again and make sure storage is off as well

**Comment by b1ckdrgn** [comment]
I've figured out what was going on....

I have a Razer Naga Pro and Synapse updated right around the same time I upgraded to the latest Fan Control.  The Synapse update apparently brought back a Naga issue:

The Naga installs a HID for both Keyboard and Mouse besides it's actual device install.  The two HIDs need to be set to 'not wake from sleep' otherwise you get what was happening to me.  FanControl.exe showed up in the event logs because I have it set to check every minute and was the first thing that would run after wake it seems.

As soon as I made the changes to the HIDs, the PC stopped waking up.  Please close this report and thanks for trying to help.
