### ISSUE TITLE
[Enhancement] Add new source: GPU Hotspot Temperature

### ISSUE THREAD

**Issue by Hyporeal** [Rem0o/FanControl.Releases#1492]
![Screenshot 2023-01-25 164429](https://user-images.githubusercontent.com/87534492/214698238-293fc4ec-3648-48f5-865c-de430ac34b1f.png)

We currently have the option to create 'Graph Fan Curve' with a 'Temperature Source'. The GPU allows for the main sensor only. It would be useful to also include the GPU Hotspot Temperature as a 'Temperature Source'.

Thank you for your time and great work!

**Comment by Rem0o** [comment]
Try the other GPU provider in the sensor settings. Keep GPU on and turn off NvAPIWrapper.

**Comment by Hyporeal** [comment]
![Screenshot 2023-01-26 010530](https://user-images.githubusercontent.com/87534492/214769067-25504d23-63fc-4f4e-9ac2-41cd4e9db8f4.png)

Solved! Thank you and sorry to bother you if this was documented!
