### ISSUE TITLE
Bug: Set manual control

### ISSUE THREAD

**Issue by AthylaKing** [Rem0o/FanControl.Releases#1493]
**Describe the bug**
When configuring a fan (for example, a case) in manual mode and saving the configuration, when the computer is restarted, the slider of the fan in question shows a sign? and the speed is the minimum and you have to reconfigure it manually.
**Relevant hardware specs and setup**
I5 11400F AORUS Z590 ELITE 16GB.

**Comment by Rem0o** [comment]
Try and set "force apply" on that specific control, in the three dot menu..
