### ISSUE TITLE
AMD 6800Xt temperature sensors not detecting

### ISSUE THREAD

**Issue by Slavstralian** [Rem0o/FanControl.Releases#1494]
I don't know how much detail to put here... all of a sudden with an update ( unsure which) Fancontrol does not detect my 6800XT sensors for Temps.

**Comment by Rem0o** [comment]
If you have upgraded drivers for your GPU or something like this, make sure you have at least rebooted before going further.

**Comment by Blarnix** [comment]
I am also still having this issue, unsure when it started but it feels like it was recent. I'm on 23.4.3 using an RX6700XT and I cannot see any sensors there. It is possibly a LHM issue, though, since I also do not see them in LHM. I'll do some more digging.
