### ISSUE TITLE
ERROR!!!A discrepancy was detected between the control "..."and its target value.

### ISSUE THREAD

**Issue by katastrophe92** [Rem0o/FanControl.Releases#1497]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]
- First of all thank you for this amazing repository, I really LOVE IT
-A couple of updates ago started to show these error pop-up, before it did worked just fine. I didn't changed any hardware or OS. But I can still control the bugged fans cards. I do not know how to fix it
![27 01 2023  22-44-50](https://user-images.githubusercontent.com/103950507/215255340-8373ec0f-510c-4094-950f-f178f0df81a5.png)
![27 01 2023  22-10-48](https://user-images.githubusercontent.com/103950507/215255346-0114035f-f7ea-40f2-9620-e00cf4455271.png)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]
- [log.txt](https://github.com/Rem0o/FanControl.Releases/files/10526671/log.txt)
- [log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/10526673/log_1.txt)

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]
- Win 10 Pro, MSI RTX 2070, I7 8700k, 32Gb GSkill 3400

**Comment by Rem0o** [comment]
You can unhide/hide cards by clicking the three dot menu at the top of a card.  Cards get hidden during the initial assisted setup if fan control couldn't control that specific card at that time.
