### ISSUE TITLE
[Feature-Idea] Let the fan never run at x% RPM. (to prevent humming)

### ISSUE THREAD

**Issue by Finnschi001** [Rem0o/FanControl.Releases#1499]
First: I didnt found a channel to suggest new feature ideas. If the post is wrong here, feel free to move it. (or comment where to post)

Fans (especially when using 2 or more of the same kind) can create a humming noise at some (fan specific) frequencies/RPM that are really annoying. I "fixed" it, by having little steps in my otherwise smooth fan curve. 

Idea: Make a function, where you can exclude a specific PWM% from the fan curve. In my example 33% and 38%. Also add an "i" or "?" hover icon to explain the functions purpose. (I really like these kind of explanations for other feature in the program 👍)

------------
Thank you for this wonderful program, it is awesome to control my deshrouded GPUs new fans based on the GPU temperature 😊

**Comment by Dupwnt** [comment]
Hello Finnschi001,  I saw your suggestion and I think I might be able to help you out.   There is already a way to avoid having the fan speed hovering around an undesirable RPM, it's just a matter of using the right type of fan curve.    
When you go to create a new fan curve you'll see that it gives you the following options-  Auto, Sync, Mix, Flat, Target and Graph.   You'll want to use **Graph** in this situation.   Graph curves give us the ability to have our fan jump right over any speed we wish to avoid.   I've uploaded a picture of a graph fan curve to help you visualize how this works.   It's from a different piece of software but it'll do the job just fine.    If you take a look you'll see that this curve has the fan speed set to 0% until the temps reach 40 degrees at which point the fan speed will immediately jump from 0% up to 20%.  Now the fan speed will remain at 20% until the temps reach 60 degrees where it is set to make another big leap up from 20% all the way to 45%.     You just build your graphed fan curve in such a way that you have the fan step right over any speeds you wish to avoid.   I hope this makes sense, if not let me know and I'll do my best to help you get it sorted out.

![Step2](https://user-images.githubusercontent.com/1229863/216826000-de1992c8-cd39-46db-b397-013a7f7de77d.png)

**Comment by Rem0o** [comment]
@Finnschi001  I think the way you are handling the situation is already the proper one ( a graph with a step ).  

The philosophy behind fan control is to give you building blocks that you can do almost anything out of, not giving very specific features to handle a very specific situation like yours.  By keeping the features "generic" it keep the software simple while also giving great flexibility.
