### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by broizter** [Rem0o/FanControl.Releases#15]
Hey, I was wondering if the source code for this project could be released?

**Comment by Rem0o** [comment]
Not as of now. The hardware compatibility/driver parts are all open sourced though.

**Comment by broizter** [comment]
Obviously the program needs privilege escalation to run so it would have been nice to have a look at the code, but I fully respect your decision!

**Comment by Rem0o** [comment]
FYI, the admin requirement to run the app comes from LibreHardwareMonitor running in the background as a backend service.

**Comment by quinndiggity** [comment]
Fixed in https://github.com/Rem0o/FanControl.Releases/pull/1629

**Comment by wiiznokes** [comment]
Hi, I made an open source alternative [here](https://github.com/wiiznokes/LibreFanControl) for those interested. Works also on Linux.
