### ISSUE TITLE
Possible to get FC to run automatically at startup using standard (non-admin) account?

### ISSUE THREAD

**Issue by Xenonfish** [Rem0o/FanControl.Releases#1502]
Hi there,

Great program well done! 

I'm having difficulty trying to get it to run under standard account in Win11. I want to give the program permission to run on log on of the standard account without having to give it permission via UAC prompt, and also be able to see system tray icon(s) to open GUI.

I found this thread: [https://github.com/Rem0o/FanControl.Releases/issues/12](url) which mentions that the elevated privileges have been embedded into the app, so does this mean that I should just need to select "start with windows" in the settings for it to work?
At the moment when I do this I get the UAC prompt for permission.

Due to this, I've been trying to avoid the UAC prompt by changing settings in the task scheduler, the best I've got so far is for the program to run (viewable in task manager) but there is no tray icon(s) and cannot access GUI.

Please could you advise if it's possible to run in standard account with no approval needed? If so can this be configured in the task scheduler? I'd be very grateful for any advice on how to set it up to make it work in this respect.

Kind Regards
XF

**Comment by Rem0o** [comment]
> if it's possible to run in standard account with no approval needed

You can't.

It's really meant to work on a admin-level account, not much else you can do from a non-admin level acocunt.

**Comment by Xenonfish** [comment]
Thanks for confirming.

Out of interest why does the program need admin rights to run?

I'll just manage the UAC prompts on boot each time then. No big deal.

Thanks,
XF

**Comment by Rem0o** [comment]
It access root level memory to change fan speed, read temperature and so on.

**Comment by GregWoods** [comment]
The root question has been answered, but others remain, so some guidance would be nice.
> I've been trying to avoid the UAC prompt by changing settings in the task scheduler, the best I've got so far is for the program to run (viewable in task manager) but there is no tray icon(s) and cannot access GUI.

Q: is there a way to run it in Task Scheduler and still see the tray icon?
