### ISSUE TITLE
Unable to control fanspeed on my 6700XT

### ISSUE THREAD

**Issue by k3ack3r** [Rem0o/FanControl.Releases#1503]
The program seems to pickup the temperature, fanspeed and fan %, but it tells me that there is a discrepancy and gives me an option to force apply, which doesn't do anything. (MSI afterburner works)

Maybe another important note is that third party programs register a different fan speed for some odd reason... for example GPU-Z shows a 105% fan speed when I've set 100% in Adrenaline.

**Comment by Rem0o** [comment]
From README: 

Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!
