### ISSUE TITLE
Nvidia 0% hardware curve override seems not work

### ISSUE THREAD

**Issue by gggssepgf** [Rem0o/FanControl.Releases#1504]
I enabled Nvidia 0% hardware curve override,but it seems not work
![image](https://user-images.githubusercontent.com/48855391/215759854-ba4ff757-d56b-49fb-9844-922de90ee347.png)
![image](https://user-images.githubusercontent.com/48855391/215760039-588317d6-663b-433d-9b11-2fcea7e8a2eb.png)
force apply won't work too,may it be the vbios issue?

MB:MS-ICraft B550M WIFI
GC:Gainward RTX 3090 Glare OC

**Comment by Rem0o** [comment]
The override will only apply what the GPU would do on its own without any software. It won't make it go 0 rpm if the gpu doesn't want to go 0 rpm in the first place.   

2 things:
1) Make sure your "graph" hits 0 when you want it to.  
2) When you disable a "graphic card" control, does it go to 0 on its own?

**Comment by gggssepgf** [comment]
> The override will only apply what the GPU would do on its own without any software. It won't make it go 0 rpm if the gpu doesn't want to go 0 rpm in the first place.
> 
> 2 things:
> 
> 1. Make sure your "graph" hits 0 when you want it to.
> 2. When you disable a "graphic card" control, does it go to 0 on its own?

1.here's my "graph"
![image](https://user-images.githubusercontent.com/48855391/215793278-214a395b-cd24-4154-ab43-d63b3a18c80c.png)
even though it's below 40℃,it will still remain 30%rpm
2.yes,it does

**Comment by gggssepgf** [comment]
> For 2), more specifically,
> 
> When it is in its 30% state where you think it should to go 0, and you immediately disable the control, does it go immediately to 0?

yes，if I disable the control,it will go immediately to 0.And if not it will remain 30% all long no matter how low the tempreture is

**Comment by Rem0o** [comment]
Try this:

Disable the "force apply", then put the control in manual mode, slide it to 50%, let it go up there, then go back down to 0.

**Comment by gggssepgf** [comment]
> Try this:
> 
> Disable the "force apply", then put the control in manual mode, slide it to 50%, let it go up there, then go back down to 0.

I tried this,when I slide it back to 0,it will first back to 30% and maintain for several seconds then go back to 0

**Comment by Rem0o** [comment]
Good, now leave force apply off, put back your fan curve, and see if it goes to 0 by itself now.

**Comment by gggssepgf** [comment]
> Good, now leave force apply off, put back your fan curve, and see if it goes to 0 by itself now.

![image](https://user-images.githubusercontent.com/48855391/215805207-1873afc8-989a-42ea-bd50-e480cd3192e8.png)
![image](https://user-images.githubusercontent.com/48855391/215805944-6f19de11-ff4a-45e7-9412-f8b954a9760b.png)

it's still not being controlled,as long as there's load on GPU,even 10% usage,no mater the tempure is,rpm will go up,and not being controlled by fancontrol

**Comment by Rem0o** [comment]
> as long as there's load on GPU,even 10% usage,no mater the tempure is,rpm will go up,

That, FanControl can't do anything about.   Nvidia has closed manual 0 rpm control on gpus.
