### ISSUE TITLE
Bitdefender :: Gen:Illusion.Mustang

### ISSUE THREAD

**Issue by foreachthing** [Rem0o/FanControl.Releases#1506]
Bitdefender just erased FanControl.exe:
![image](https://user-images.githubusercontent.com/10420187/215868974-b90c169e-0f2b-42cd-a192-2eae573875d8.png)

Any ideas, except making exceptions?

FanControl V144
Edition	Windows 11 Pro
Version	22H2
OS build	22621.1105

**Comment by Rem0o** [comment]
It's a false positive. Happens from time to time.

**Comment by foreachthing** [comment]
Ok. Just never had one :-)

**Comment by rafanidius22** [comment]
its happening with my enterprise too... is so bad to me
