### ISSUE TITLE
Razer PWM fan controller support

### ISSUE THREAD

**Issue by PineappleBrains** [Rem0o/FanControl.Releases#1507]
Is there a plugin out there for the Razer PWM fan controller? Or any other way to get FanControl to recognize the fans through this controller?

**Comment by Rem0o** [comment]
Not AFAIK.

**Comment by arlo-infinity** [comment]
@PineappleBrains 

Do you have the Razer PWM fan controller?  If so, can you confirm that it isn't recognized in FanControl via the USB.
I was thinking of buying this but I will go with the Corsair Commander Pro (which already has a plugin) if I can't use FanControl.

@Rem0o 

Thanks for you excellent software! Do you have any idea of how likely any of the other plugins that bridge the USB interface to access PWM fan's might be adaptable to provide plugin support for the Razer PWM?  It would be awesome to have 8 independent PWM channels available.

**Comment by EvanMulawski** [comment]
Now available: https://github.com/EvanMulawski/FanControl.Razer

**Comment by 325racer** [comment]
So I must not understand or am completely missing something. I just downloaded, but I don't see the .dll to add to the Plugin folder.

I literally just installed one of these modules 15 minutes ago and trying to get it to work with Fan Control.

**Comment by BthatKing** [comment]
Can i still control each fan independent with this Plugin?

**Comment by Rem0o** [comment]
Closing via @EvanMulawski  
https://github.com/EvanMulawski/FanControl.Razer
