### ISSUE TITLE
Feature Request: Execute commands when temperature points are hit

### ISSUE THREAD

**Issue by Quad5Ny** [Rem0o/FanControl.Releases#151]
**Feature Request:**  The ability to execute commands based on a temperature chart.  This is because the USB fan controller I and many others have (NZXT brand) doesn't have any open source software to set a curve.

The only options are a very bloated software package or static fan speed's via command line (NZXT Cam or liquidctl).  Liquidctl is open source but I cannot code for the life of me nor does it include the ability to pull temperatures & run in the background.
https://github.com/liquidctl/liquidctl - https://github.com/liquidctl/liquidctl/blob/master/liquidctl/driver/smart_device.py

Simplest implementation I can think of:
-Box/Grid Style entry's for control points
-Temperature being read from a sensor already available
-Base Command to initialize the USB fan controller (only done at the start of the program)
-Control Points at Fixed values, no ramping up because these are individual commands being sent
   (Think of a max of 3-5 control points+a command for each point)
-Always choose the closest control point, so if we're at 46c it should run the command for 60c (hysteresis and polling time still apply)

Thank-you for even taking the time to read this as I don't think NZXT is going to clean up their bloatware anytime soon.  So it's either I ask a stranger or figure out a AutoHotKey script (maybe powershell) that gets loaded via task scheduler.

For what it's worth thank-you again and I will be buying you some coffee's if I end up using your software.

```
---
Example Interface Settings:
---
Polling Period:
  Period: [3000]ms
Initialize CMD:
  Init_CMD: ["C:\Program Files\SmartDevice\Controller.exe" -init]
Control Point 1:
  CP1_Temp: [30]c
  CP1_CMD: ["C:\Program Files\SmartDevice\Controller.exe" -pwm 40]
Control Point 2:
  CP2_Temp: [60]c
  CP2_CMD: ["C:\Program Files\SmartDevice\Controller.exe" -pwm 70]
Control Point 3:
  CP3_Temp: [80]c
  CP3_CMD: ["C:\Program Files\SmartDevice\Controller.exe" -pwm 100]
Control Point 4: (NOT IN USE)
  CP4_Temp: []c
  CP4_CMD: []
Control Point 5: (NOT IN USE)
  CP5_Temp: []c
  CP5_CMD: []

Example running code (if you can even call it that):
---
Polling Period 0:
Set CP1_Loaded & CP2_Loaded & CP3_Loaded = 0,  Execute Init_CMD
wait 3000ms

Polling Period 1:
@25c
   Temperature is Closest to CP1_Temp & CP1_Loaded == 0
     CP1_CMD executed & Set CP1_Loaded = 1
   Set CP2_Loaded = 0 & CP3_Loaded = 0
   wait 3000ms

Polling Period 2:
@25c
   Temperature  is Closest to CP1_Temp & CP1_Loaded == 1
     (So we do nothing)
   (For sanity) Set CP2_Loaded = 0, CP3_Loaded = 0
   wait 3000ms

Polling Period 3:
@45c
   Temperature is Closest to CP2_Temp & CP2_Loaded == 0
     CP2_CMD executed & Set CP2_Loaded = 1
   Set CP1_Loaded = 0 & CP3_Loaded = 0
   wait 3000ms

Polling Period 4:
@48c
   Temperature is Closest to CP2_Temp & CP2_Loaded == 1
     (So we do nothing)
   Set CP1_Loaded = 0 & CP3_Loaded = 0
   wait 3000ms

Polling Period 5:
@76c
   Temperature is Closest to CP3_Temp & CP3_Loaded == 0
     CP3_CMD executed & Set CP3_Loaded = 1
   Set CP1_Loaded = 0 & CP2_Loaded = 0
   wait 3000ms
---
```

**Comment by Rem0o** [comment]
AFAIK, LHM does has some NZXT stuff implemented 
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/tree/master/LibreHardwareMonitorLib/Hardware/Controller/Nzxt

Couldn't this be simply improved?

**Comment by Quad5Ny** [comment]
It could but that would involve importing code from a completely different license and programing language.

I was thinking of the user including liquidctl as a optional binary as liquidctl can fully control most of NZXT's various hardware devices.  _The only caveat is every time fan speeds needs to be adjusted the binary needs to be run again._

To me it seems like arranging a GUI and piping commands/getting status updates from a external binary would be simpler than adapting code to access a USB HID.

Real example
  (More detail here: https://github.com/liquidctl/liquidctl/blob/master/docs/nzxt-hue2-guide.md)
```
liquidctl.exe initialize
liquidctl.exe set fan1 speed 55
liquidctl.exe status
```
I honestly don't know what would be best. But I can tell you anyone who has ever used NZXT CAM would be happy to be rid of it.

**Comment by Rem0o** [comment]
> To me it seems like arranging a GUI and piping commands/getting status updates from a external binary would be simpler than adapting code to access a USB HID.

I would argue otherwise. This is not a clean solution, potentially I/O heavy, CPU heavy and so on.

**Comment by Quad5Ny** [comment]
> > To me it seems like arranging a GUI and piping commands/getting status updates from a external binary would be simpler than adapting code to access a USB HID.
> 
> I would argue otherwise. This is not a clean solution, potentially I/O heavy, CPU heavy and so on.

No it is not a clean solution, simple (in my eyes) but not clean.  What would you suggest?

**Comment by Rem0o** [comment]
> No it is not a clean solution, simple (in my eyes) but not clean. What would you suggest?

A plugin.
See https://github.com/Rem0o/FanControl.Releases/wiki/Plugins
