### ISSUE TITLE
Fan control auto start / stop % detailed explanation

### ISSUE THREAD

**Issue by rollsch** [Rem0o/FanControl.Releases#1517]
Can someone explain how the minimum % start and stop % works?

Eg if I have a DC fan that has the following:
![image](https://user-images.githubusercontent.com/1109554/217390137-1d6feb79-4cb4-4658-8f26-96b94d4773db.png)
Fan start % 78%
Fan stop % 21%

Fan will comfortably run at 25% as long as its been "Started". Even just spinning it with your finger will get it  going.

What I would like to happen is the following:

FanControl requests 45% fan speed, it sees that 45 > 21 and 45 < 78. Fan control then inputs 78% fan speed temporarily until the fan is detected spinning, the fan speed is then immediately dropped back to 45%.

Fan control requests a drop from 25% to 15%, 25 < 21 so fan control simply sends 0% and stops the fan.

Is this how fan control works? Or is it more simple in its functionality?

Edit: From some simple testing using a flat fan curve it seems to do as I expected above. Can someone confirm if I have missed anything?

**Comment by Rem0o** [comment]
It is exactly how you described it.  The start% is a kickstart before going back to whatever % is requested.  Anything below stop% will snap to 0.

**Comment by rollsch** [comment]
Fantastic. Thank you.
