### ISSUE TITLE
TUF x299 Mark 1 chassis fans not detected

### ISSUE THREAD

**Issue by DJZK** [Rem0o/FanControl.Releases#1523]
**Describe the bug**
Cannot clearly see all the fan controllers from TUF X299 Mark 1. Fans are attached in Chassis Fan 4 and 5 and the BIOS can see it clearly.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Nope

**Relevant hardware specs and setup**
Motherboard: TUF x299 Mark 1

**Comment by DJZK** [comment]
![image](https://user-images.githubusercontent.com/38833462/217832918-503ad9c7-07d6-45c3-b7c2-04d3dfd3f899.png)
This shows it only detected the CPU fan and the GPU fan

**Comment by DJZK** [comment]
btw this board works fine in the older version of Fan Control

**Comment by Rem0o** [comment]
Which version? Can you A/B the difference between the two?  Most of the time, such problems aren't version related, but something specific to your setup that has changed.

**Comment by DJZK** [comment]
I changed the motherboard once switched to TUF Sabertooth Mark 1 (without formatting/clean installing Windows). That works as well. Then when I switched back here, to x299 Mark 1, the case fans can no longer be detected. Tried reinstalling Fan Control and no luck. 

or do i need to delete something else?
