### ISSUE TITLE
Multiple fans not working on Aorus Pro V2

### ISSUE THREAD

**Issue by Negerhoran** [Rem0o/FanControl.Releases#1526]
As stated, I have multiple headers that simply doesnt work. I have a Aorus Pro V2 mobo from Gigabyte, and the headers in question are basically every one except CPU, CPU_OPT and FAN_1. 
One of the other headers actually was controllable, but the sensors reported nothing and the graphs didnt seem to work. Only Manual mode/force wokred.

**Comment by Rem0o** [comment]
See README:

https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
