### ISSUE TITLE
Possible to add NZXT pump liquid temperture sensor ? 

### ISSUE THREAD

**Issue by Dfaker-HK** [Rem0o/FanControl.Releases#1532]
Hello, recently I found out this software is so great that it can control fan curve by gpu temperture, but when I try to adapt my whole system fan control to this software I found out that I'm not able to add nzxt pump temperture sensor as a temerture source, is there any way I can do it?

**Comment by Rem0o** [comment]
Do you got the "controller" section ticked on in sensor settings? Otherwise, you might give one of the available plugin a shot.
