### ISSUE TITLE
[Feature request] Let users set the order of the tray icon temperatures

### ISSUE THREAD

**Issue by danielmmmm** [Rem0o/FanControl.Releases#1533]
It would be nice if we could change the position of tray icon temperatures. Maybe with a little drag handle to the left of the temperature source, instead of the current bullet point. The top icon would become the leftmost icon.

**Comment by Rem0o** [comment]
I can't control that order really, since Windows will decide where that icon go. You can reorder them from windows by drag n dropping them around, and Windows will remember that order afterwards.

**Comment by danielmmmm** [comment]
Haha, that (Windows messing things up) doesn't surprise me. Unfortunately, reordering these icons is "glitchy" at best.

Could Windows be tricked by adding the tray icons with a delay, one after another? Or will they still be at random positions then?

**Comment by Rem0o** [comment]
@danielmmmm  There is no reliable way to decide the position/order of tray icons, so I don't think it is worth the effort.

**Comment by danielmmmm** [comment]
I understand. But thanks for looking into the matter 😊
