### ISSUE TITLE
Feature request: Combined ("mix") sensors

### ISSUE THREAD

**Issue by LyraelRayne** [Rem0o/FanControl.Releases#1539]
I'd like to be able to combine a number of sensors into one virtual sensor I can attach to a curve. I *could* do this at the moment by creating a bunch of identical curves, then assigning them to a "mix" curve, but that is inconvenient.

An alternative to this feature would be to allow assigning multiple sensors to the same curve, but "mix" sensors would be more versatile as then you can use max, average, etc. the same as a mix curve.

My use case is basically that my motherboard has a set of numbered sensors, the purpose of which I don't actually know. I want to set a curve for my case fans based on the highest of these temperatures. Another use case would be to set the CPU fan based on the highest core temperature.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/218609030-a6ae9b85-9a82-4a0d-a932-43c6c476cad6.png)

https://getfancontrol.com/docs/

**Comment by LyraelRayne** [comment]
/facepalm Sorry to bother you then :D

**Comment by Rem0o** [comment]
No worries.
