### ISSUE TITLE
Fancontrol.sys driver identified as vulnerable in Avast latest update

### ISSUE THREAD

**Issue by Quad-Gamer** [Rem0o/FanControl.Releases#1541]
**Describe the bug**
Avast's "Block vulnerable kernel drivers" detects fancontrol.sys as vulnerable and stops it from loading.

Avast version: 23.1.6049 (build 23.1.7883.762)
FanControl version: 146

Just wanted to let you know.

Thank you for an excellent program.

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/1521
