### ISSUE TITLE
'Avast blocked a vulnerable driver' issue :(

### ISSUE THREAD

**Issue by louis-lowlight** [Rem0o/FanControl.Releases#1543]
Hello, I have been using the program for 2 days now, and everything worked well except this morning. Avast Antivirus blocked the driver 'fancontrol.sys'. This is an image that depicts the issue. In french and english just in case. [https://ibb.co/my5y71h](url) [https://ibb.co/ds9Ls8p](url)

I did not find any log.txt file in the folder however.

Please help, I really like the software.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1521
