### ISSUE TITLE
GPU control not working?

### ISSUE THREAD

**Issue by Sick-Andrew** [Rem0o/FanControl.Releases#1544]
Started using FanControl 146 but can't get my head around the GPU control of my GIGABYTE Radeon RX 6750 XT.
The speeds of the GPU fan are shown when the 3 fans are running.
But I'm not able to change the speeds/rpm manually or with a curve.
Is that something the GPU manufacturer or AMD Software block me from doing?

![image](https://user-images.githubusercontent.com/39406635/219043558-794c3b8f-fc74-446a-839b-b8357501666d.png)

**Comment by Rem0o** [comment]
See README
```
Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!
```

**Comment by Sick-Andrew** [comment]
> See README
> 
> ```
> Q: My new AMD card can't be controlled, why?
> A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!
> ```

Thanks, I saw that but didn't consider the 6750XT a newer card. Then I realized it was released in 03/2022 so yeah...
Sorry for the trouble.
