### ISSUE TITLE
Missing speed sensors

### ISSUE THREAD

**Issue by timhill3100** [Rem0o/FanControl.Releases#1552]
In the last 30 or so versions of this software I continue to get this issue where the gpu fan speed sensors cannot be found and the case fans say they are spinning at anywhere from 3000-9000 rpm and the cpu fan is spinning at 20.7 rpm constantly. I have all noctua nfa12 fans (cooler is NH-U12A) and have used a msi 3060 and a FE 3060ti with the same issues.

**Comment by Rem0o** [comment]
Please see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.

Closing.
