### ISSUE TITLE
"Manual Control" and "Force Apply" grayed out

### ISSUE THREAD

**Issue by spiff09** [Rem0o/FanControl.Releases#1554]
Hello. First off, here because of Jayztwocents. Awesome software.

Anyway, as it's stated in the subject. For some reason those two items are unselectable for me. Only "Hide" can be clicked from the three-dot menu on the Controls cards.

Help, please. Ciao!

![Screenshot 2023-02-18 210454](https://user-images.githubusercontent.com/125743073/219867351-8965f18e-1369-4b05-acdc-5bac0de8c9ba.png)

**Comment by Rem0o** [comment]
toggle the switch on the card first.

**Comment by spiff09** [comment]
Awesome. Thanks!
