### ISSUE TITLE
GPU fan: this control doesn't respond

### ISSUE THREAD

**Issue by Connovar6** [Rem0o/FanControl.Releases#1557]
Using the assisted setup.
I get  GPU fan: this control doesn't respond.
Gives a RPM and Speed % but no active control apart from pairing speed. which pair fan #1 and #6
Trigger fan curve identifies hardware. And heat % of trigger points

All other fans working fine.

Running 

MSI MAG Tomohawk wifi X570
AMD Radeon RX 5600 XT
AMD Ryzen 5 3500X

Had Read in another post XT cards may not be supported 

Turned of all other fan control programes. However using MSI afterburner to control fan speeds when needed.

**Comment by Rem0o** [comment]
> Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!
