### ISSUE TITLE
Can only control 2 out of 3 system fans

### ISSUE THREAD

**Issue by terminalwhoami** [Rem0o/FanControl.Releases#156]
Gigabyte H97M-D3H motherboard.  I've used this motherboard on linux with lm_sensors/fancontrol and I was able to control all 3 system fans.  Is this a limitation of Libre Hardware Monitor? or is there something I'm missing?

V63 was the first version I used, and just updated to V66 of Fan Control.  (btw, when i ran the updater, it wasn't able to import my previous fan settings)

**Comment by Rem0o** [comment]
It is a limitation, every hardware support matter is handled by LHM.

**Comment by terminalwhoami** [comment]
Ok, I'll open an issue on their github and see if they can help me.
