### ISSUE TITLE
Crazy fan speeds with a question mark beside the percentage.

### ISSUE THREAD

**Issue by Ayman71** [Rem0o/FanControl.Releases#1560]
Fan control reads insane fan speeds like 13000rpm or so, and I see a question mark on the percentage. when I click on it this message appears.
![Screenshot 2023-02-23 223700](https://user-images.githubusercontent.com/88652290/220999740-06dc4e67-9111-463b-a9a8-470df3c60cc2.png)
No matter if HWiNFO64 is open or not the issue still exists. 
I also get this warning message when the program initializes at the startup
![image](https://user-images.githubusercontent.com/88652290/221000249-da731c58-7ceb-48a3-9d0f-1df828e6ded6.png)

**Comment by Rem0o** [comment]
Where are those commander pro sensors coming from? Plugin?

**Comment by Ayman71** [comment]
> 

yes, I downloaded it around one month ago when I first built the PC

**Comment by Rem0o** [comment]
Well the stuff you are experiencing are caused by the plugin, not FanControl itself. You should probably report to the plugin's dev, not here.

**Comment by Ayman71** [comment]
> Well the stuff you are experiencing are caused by the plugin, not FanControl itself. You should probably report to the plugin's dev, not here.

yes, apparently it was from the plugin. I installed the latest plugin and rebooted and it worked like a charm.
