### ISSUE TITLE
Fan Control opens when waking computer from sleep

### ISSUE THREAD

**Issue by Tom-Archer** [Rem0o/FanControl.Releases#1563]
**Describe the bug**
In Fan Control v147, when I resume from sleep or hibernation, Fan Control opens.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No.

**Relevant hardware specs and setup**
Gigabyte H170-HD3 and i5-6600 CPU

**Comment by DerJantob** [comment]
I am experiencing the same issue

**Comment by MrInkless** [comment]
Same here

**Comment by VladiHub** [comment]
+1

**Comment by an-tech** [comment]
+1

**Comment by ringoz** [comment]
true

**Comment by cydRabbit** [comment]
+1

**Comment by skyhigh24** [comment]
Same here

**Comment by Rem0o** [comment]
Found the issue. Will fix shortly.

**Comment by Rem0o** [comment]
V147 "release" has the fix, otherwise you can run updater.exe again and it should have the fix.

**Comment by MrInkless** [comment]
> V147 "release" has the fix, otherwise you can run updater.exe again and it should have the fix.

Fixed for me. Thank you for the quick fix!

**Comment by Tom-Archer** [comment]
Yep, seems to be fixed for me too! Thanks

**Comment by Spuner** [comment]
No, the problem did not go anywhere with the upgrade to version 147. It's still an issue.

**Comment by Tom-Archer** [comment]
How did you perform the update? The first time I ran the "updater.exe" I didn't notice it didn't update properly so the problem persisted. Running it a second time from an admin command prompt seemed to do the trick.

**Comment by Spuner** [comment]
@Tom-Archer, updated from FanControl.

**Comment by Spuner** [comment]
I launch the update through the console - everything is fixed. Interesting...

**Comment by Smyl3** [comment]
After sleep I'm getting "Fan Control is refreshing after wake up from sleep" alert message that never disappears....
V164
