### ISSUE TITLE
Fan Settings Wont Save When I Turn The PC Off And On Again

### ISSUE THREAD

**Issue by Talcoman** [Rem0o/FanControl.Releases#1565]
When i exit FanControl after entering all my fan settings and opening it again all of it disappears even when i save it manually. Also it does not show up as an application only as a winrar file, is it supposed to be that way?

**Comment by Talcoman** [comment]
Now, also when i try to save a configuration it says "Configuration could not be saved. See error log for details." While saying "Configuration saved as userconfig.json" At the bottom. Note that it does not say anything in the error log.

**Comment by Talcoman** [comment]
The settings now save when closing the software and reopening it although it still does not save when turning the pc off and on again.

**Comment by Rem0o** [comment]
You need to extract the program first before using it.

**Comment by Talcoman** [comment]
Lol i totally missed that, thanks alot
