### ISSUE TITLE
Bug when loading a saved profile

### ISSUE THREAD

**Issue by johannbl** [Rem0o/FanControl.Releases#157]
I use two profiles and often switch between them. The buggy behaviour goes as follow:

1. Upon loading the new profile, nothing happens.
2. When I go back in the menu to reload that profile again, I get prompted asking if I want to save changes as the profile changed.
3. I click no, proceed with reloading the profile I want (the one I first loaded at step 1)
4. Profile loads correctly.

**Comment by Rem0o** [comment]
It was reported to me already and the fix is inbound, just haven't pushed a new release yet.

**Comment by johannbl** [comment]
Thanks! I missed that report.

**Comment by Rem0o** [comment]
Wasn't reported on Github ;)
