### ISSUE TITLE
Gigabyte motherboard pins 4-6 do not work.

### ISSUE THREAD

**Issue by sunblzer** [Rem0o/FanControl.Releases#1570]
Any fans plugged into pin headers 4-6 on gigabyte motherboards do not work with fan control. The fans and sensors are accurately picked up in GUI but manual control does not change the fans.

Error Setup:
Motherboard - Gigabyte Aorus b550 pro ax
Plug a fan into headers 4-6 (any).
There's something fishy that gigabyte has done to fan headers 4-6...

Fix:
Plug fans into CPU, CPU_OPT and system 1-3. do not use headers 4-6.

**Comment by Rem0o** [comment]
Please see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

Closing.
