### ISSUE TITLE
Feature Request: Close to tray

### ISSUE THREAD

**Issue by mirddes** [Rem0o/FanControl.Releases#1571]
![image](https://user-images.githubusercontent.com/13982888/221442089-5ae53879-f6fa-4de3-b171-44b77ee520c3.png)
I absolutely love this app, thank you very much!

**Comment by Rem0o** [comment]
Simply "X" the window.

**Comment by mirddes** [comment]
> Simply "X" the window.

now i feel absurdly silly, thank you very much.
