### ISSUE TITLE
Unable to control any fans

### ISSUE THREAD

**Issue by Wingkinken** [Rem0o/FanControl.Releases#1572]
motherboard - Z570-F 

![image](https://user-images.githubusercontent.com/126438105/221471288-a3ac3755-d431-4de8-9497-fe3e7289dcc2.png)

Error: No Speed Sensor Reacted

I have seen the other thread where the suggestion was to tweak armory crate's fan settings. That didn't work either.

Any suggestions to resolve this please?

Fans go crazy when loading up a game - trying to resolve this: https://youtube.com/shorts/IqQ161YYoR8

**Comment by Rem0o** [comment]
Can't see much rpm sensors, but from the look of it, all your fan headers on your motherboard seem to read 0 rpm. Do you have anything plugged in your headers? How are your fans connected?

**Comment by Wingkinken** [comment]
Hey RemOo looks like its plugged in a Fan Hub - which may be the reason for this! I saw a topic for corsair but not for any others.

All good - it seems like the actual fan issue in the YT video was the GPU fan going crazy!

**Comment by Rem0o** [comment]
FanControl reads and controls fan headers on your motherboard.   If you want to gain control over some fans, simply swap them from the hub to some SYS_HEADER(s) .
