### ISSUE TITLE
[BUG] Fan Curve not being preserved when switching profiles.

### ISSUE THREAD

**Issue by Ivaylo-Lafchiev** [Rem0o/FanControl.Releases#158]
To start off, just wanted to say this software is really cool and for the most part works really well.
The reason I downloaded this was because I wanted to create a static fan profile for my Case fans when doing GPU rendering. Currently most of them are driven from CPU and CPU Optional, so based on CPU speed only, so they never kick up during GPU renders.
I was able to do this quite easily, however I also created a second profile to use while Gaming, with usual fan curves.

The problem happens when switching between the 2 profiles.
Steps to reproduce: 
1. Create 2 profiles, and create Curve X and Curve Y in both profiles.
2. In Profile 1, set Curve X for Fan 1, and in Profile 2 set Curve Y for Fan 1, 
3. Save the profiles
4. Switch between profiles 1 and 2, and all the custom curves will load correctly, but Fan 1 will still have Curve X, instead of Curve Y set.

This unfortunately makes the profile switching not very useful.

Hopefully it's an easy fix!

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/issues/157

It was already reported, the fix is in the next version, will push it soon.

**Comment by Ivaylo-Lafchiev** [comment]
Sorry, I checked the open issue and didn't spot it. I  would recommend leaving at least one of the reports opens to avoid duplicates.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V67
