### ISSUE TITLE
Everytime Windows boots I get error "Windows cannot find 'FanControl.exe.'"

### ISSUE THREAD

**Issue by nefariouslegion** [Rem0o/FanControl.Releases#1587]
**Describe the bug**
Everytime Windows boots I get a blank command prompt window along with an error message that says "Windows cannot find 'FanControl.exe'. Make sure you typed the name correctly, and then try again."
![image](https://user-images.githubusercontent.com/89366675/222619538-b792db34-c159-4c28-9bbe-090f1bd10e4f.png)

However if I manually run FanControl it opens just fine. I had manually deleted the FanControl folder and its contents and redownloaded it. Extracted it to the same location with the same name. Now I get this error. I never got this error prior to deleting it.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Doesn't appear to be a log file.

Hoping someone can help me fix this?

**Comment by Rem0o** [comment]
Go to the Task Scheduler in Windows and look up where the FanControl task points to.

**Comment by nefariouslegion** [comment]
Ah yep that fixed it. It was pointed to the wrong location. Thank you.
