### ISSUE TITLE
Window not showing and save prompt not working.

### ISSUE THREAD

**Issue by katzolik** [Rem0o/FanControl.Releases#159]
When i open the app, the window seems to open below the taskbar and to the right of my display.
Also when i close the application, the buttons "yes" and "no" on the "save config" prompt do nothing.

**Comment by JackRamsie** [comment]
I also can no longer view the window. I can't find the program in to uninstall via control panel either, its there but not there.  I see it running in taskbar, very strange.  It was in program folder visible before before pretty sure. I checked properties I don't have it hidden or anything. Seems to be running somehow, on previous settings maybe?

**Comment by Thoroughmas** [comment]
Same issue here. Judging by the speed of my fans, my profile has stopped working properly, but I can't open the program to fix it. Downloading a new copy to reinstall didn't help.

**Comment by katzolik** [comment]
> When i open the app, the window seems to open below the taskbar and to the right of my display.
> Also when i close the application, the buttons "yes" and "no" on the "save config" prompt do nothing.

I could resolve the the problem by changing the windows scaling back to 100%.

**Comment by xzkeee** [comment]
same here ,i have 300% ui scale on win10.
window not showing.
after change software ui scale to system, window shows.

**Comment by Rem0o** [comment]
Will take a look a windows scaling....

**Comment by flowerdealer** [comment]
I have this issue too. Workaround is to set scale to 100%, open the UI, and set scaling back.

**Comment by peterparnes** [comment]
I had the same issue. This should really be added to the README.
