### ISSUE TITLE
PCH/Chipset temperature source is missing

### ISSUE THREAD

**Issue by deastr** [Rem0o/FanControl.Releases#1592]
I'm not sure if I open this issue here or at LibreHardwareMonitor, apologies if it's the wrong place.

I have an ASUS X570 motherboard. I added PCH fan to Fan Control and I can manually control it's speed. But it's temperature is missing from temperature sources so I can't control it using a graph control:

![2](https://user-images.githubusercontent.com/18551424/222951155-12ae9dcf-612f-41ef-a0e9-02ead446ba86.png)

My settings:

![3](https://user-images.githubusercontent.com/18551424/222951199-a47514ea-3c4c-48ec-ade0-6cd30b8af7ab.png)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
