### ISSUE TITLE
No speed control reacted to sensor Commander Core

### ISSUE THREAD

**Issue by MarkMuratore** [Rem0o/FanControl.Releases#1596]
I am trying to use the commander core link plugin and receive the following for all my fans when using auto setup: no sped control reacted to sensor for fanXX. Only the pump, which is connected to the CPU fan header on the MB, and my GPU fans are detected. All other fans are connected to the commander core. I am using a gigabyte aorus 570s master MBAny ideas? TIA

**Comment by Rem0o** [comment]
Shouldn't this be on the plugin's repository? 

@EvanMulawski
