### ISSUE TITLE
CPU_OPT and SYS_FAN_4 on B650 AORUS ELITE AX

### ISSUE THREAD

**Issue by nicesub** [Rem0o/FanControl.Releases#1597]
Hello,

I am new to this application and just built my first PC and trying to tune the fans. I am trying to configure the fans using this application and I came to struggle with certain controls on specific headers on MB Gigabyte B650 AORUS ELITE AX.

So basically PWM fans or pump connected to headers CPU_OPT or SYS_FAN_4 cannot be controlled via the application. The application sees them and it gives me the RPM redout but when I try to manually change the RPM nothing happens. Other headers are working fine but these two just do not react to application inputs. 

I verrfied in BIOS that I can control it there but outside of it no luck. Any advice on how to solve this?

**Comment by Cjorss** [comment]
I wonder if there is a broader issue with Fan Control on gigabyte motherboards here. I have a similar issue on my X670E Aorus Xtreme where Sys_Fan_4 is not recognized by Fan Control at all. 

I've seen another thread on linus tech tips forum about the X670E Aorus Master board which was I think like yours, he could at least see the RPM but was unable to control Sys_Fan_4.

I at first mistakenly connected my fans to a Sys_Pump header so I wasn't too surprised that Fan Control didn't work properly. But then found that my fans were still unrecognized on Sys_Fan_4. (Working fine with BIOS control)

I only got around my issue by joining Sys_Fan 2-3 and moving the fans from Sys_Fan_4 to Sys_Fan_2.

You might be able to do something similar by joining some of the fans on CPU_Fan or Sys_Fan_1-3 but I don't know about controlling the pump within the app without a dedicated fix.

**Comment by Sn00kiT** [comment]
Same problem here on Gigabyte X570 Aorus Pro. On my board there are 3 Fans Headers which are not recogionzed correctly. SysFan2 and 4 and SysFan 5 Pump. Even tried to use differnt BIOS versions.
![2023-03-10 15_38_15-Fan Control V149 (userConfig json)](https://user-images.githubusercontent.com/77878228/224344481-386272c1-b7e2-4292-a1fa-6495a29e024d.png)

**Comment by githubuser1234567892** [comment]
I have the same problem with my Z690 master, only displaying 3 fans when I have 7 in my system, I have tried reinstalling windows, different bios, and even different CPUs from 2 generations.

**Comment by Rem0o** [comment]
See https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/251#issuecomment-1465250610
