### ISSUE TITLE
Fan Control - unexpected Error on start up

### ISSUE THREAD

**Issue by KurtSmart** [Rem0o/FanControl.Releases#1599]
Hi, I've been using Fancontrol for a while and its working fine but recent updates i cant even get it to start. I get unexpected error on clicking the exe. attached log file

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/10928797/log.txt)

**Comment by viviancels** [comment]
Hello. I have same error and same LOG.

Yesterday I leave windows 10 and now I use windows 8.1 (with NetFramework 4.8 instaled, it shows in control panel as update Microsoft Windows (KB4486105). Today I try to start FanControl 159 on windows 8.1 and got this error. PC: Asus A88XM Plus, AMD 870K, windows 8.1 Professional x64
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11645446/log.txt)

**Comment by TheWellHeeledKing** [comment]
![FanControlErrorMessage](https://github.com/Rem0o/FanControl.Releases/assets/151823222/cc42e3fe-121c-443e-9a5f-97f6eb2c43d7)

Hey. I had the same problem when I started my Win 11 PC this morning using a local non-admin account, started Fan Control and entered my admin password (the way I always start Fan Control). I tried it twice, it failed twice. I checked for OS Updates, downloaded and installed the available Win 11 23H2 Update and tried again with the same result. While the FanControl window is still open it does control the fans according to the latest configuration (which I have not changed for a while now). When I close the error msg, Fan Control ends and it's control over the fans ceases.

It'd be great to have a solution or workaround for this. Thanks in advance!

System
Processor	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
Installed RAM	32,0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	23H2
OS build	22631.2715
Experience	Windows Feature Experience Pack 1000.22677.1000.0

Graphics Card 
AMD Radeon RX 6700 XT 
BIOS Part Number 113-V398MECH-1OC
BIOS Version 020.002.000.019
BIOS Date 2021/11/15 01:48
AMD Software : Adrenalin Edition Version 23.10.2 released 16/10/2023

Motherboard B450 TOMAHAWK MAX (MS-7C02) (AM4)

RAM Type DDR4 
4 x 8192 MBytes (32GB)
Manufacturer	Patriot Memory
Max Bandwidth DDR4-2132 (1066 MHz)

log.txt
23/11/2023 08:18:47: System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotifierCompat.Show(ToastNotification notification)
   at FanControl.Domain.WindowsNotificationService.Notify(String message)
   at FanControl.Domain.UpdaterService.<CheckForUpdateAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<OnStartup>d__12.MoveNext()
23/11/2023 08:19:13: System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotifierCompat.Show(ToastNotification notification)
   at FanControl.Domain.WindowsNotificationService.Notify(String message)
   at FanControl.Domain.UpdaterService.<CheckForUpdateAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<OnStartup>d__12.MoveNext()
23/11/2023 09:06:04: System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotifierCompat.Show(ToastNotification notification)
   at FanControl.Domain.WindowsNotificationService.Notify(String message)
   at FanControl.Domain.UpdaterService.<CheckForUpdateAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FanControl.App.<OnStartup>d__12.MoveNext()

**Comment by Doc1faux** [comment]
Hi and thank your for your wonderful software ;)

As @TheWellHeeledKing, I run into the same behavior since today, with the same Windows version (11 23H2) and same logs as well.

My configuration:
AMD Ryzen 7 5700X
NVIDIA GeForce RTX 3060 Ti with 546.17 WHQL driver

I suppose it's tied to a now required permission to display notifications but FanControl does not appear in the list of softwares which asked for it in "Settings > System > Notifications".
On this screen, I've tried to disable the "Do not disturb" feature or enable the "Startup App Notification" but no improvement :/

**Comment by Rem0o** [comment]
@TheWellHeeledKing 

I guess the problem only happens when FanControl isn't running on an admin account, since in that case it must require the notification permission which is not managed right now.

In any case, what you are seeing is the program trying to show you a notification that an update is available.  It shouldn't break anything beyond the update notification itself.  Will look into it soon.

**Comment by TheWellHeeledKing** [comment]
Ok, many thanks @Rem0o ! I wonder if starting FanControl from PowerShell, in turn run as admin, would be a workaround? I can't try it right now because I'm streaming but will do so later. In the meantime, I've set the fan curves in the bios.

**Comment by Doc1faux** [comment]
@Rem0o I confirm running FanControl from an admin account resolves the issue and it's tied to the notification that an update is available.
So while waiting a future fix, if any user encounters this issue, you can login on your admin account, launch FanControl and update or tick the "Do not remind me" case. After that, launching FanControl from a standard account does not fire the error ;)

**Comment by Rem0o** [comment]
UnauthorizedAccessException will simply be ignored when I try to create a notification. Should do the trick.

**Comment by TheWellHeeledKing** [comment]
Many thanks @Rem0o ! Fan Control is back to doing it's work and keeping my rig nice and cool! It's a great tool which I found, I guess, like many others after watching Jay2Cents recommend it on youtube. https://www.youtube.com/watch?v=uDPKVKBMQU8

Just one question: is it possible somehow to control the fans on my MSi Mech 2X AMD Radeon RX 6700 XT OC Edition graphics card? Fan Control detects the temperature sensors such as GPU Core and Hot Spot etc but cannot identify controllers for the fans so I still have to do that from AMD's Adrenalin software or MSi Afterburner. It'd be great to have all fan controls in one place.
