### ISSUE TITLE
CPU fan speed too low

### ISSUE THREAD

**Issue by hjohn** [Rem0o/FanControl.Releases#16]
I'm having an odd issue that wasn't present in some of the earlier Fan Control versions. but has been not working correctly for a while now.

What I'm seeing is that the CPU fan speed, even when set to 100%, will only go to about 1000 rpm.  Other programs and the bios (and also earlier versions of Fan Control) will go much higher.  In those programs setting the CPU to 100% will result in a rpm of 2500 orso.

Even with Fan Control's CPU fan set to disabled, it will still override the CPU fan speed when it starts.  Normally the CPU fan idles at around 800 rpm, but as soon as Fan Control starts it drops to 300 rpm.  If I use a Flat curve to set it to 100%, it goes up to about 1000 rpm.  If I disable the fan again, it drops to 30% (somekind of default it seems) and about 300 rpm.

Other fans (chassis fans, south bridge fan, GPU fan) do work as expected.

Perhaps I need to report this at LHM?  Just curious since it worked in the past.

Motherboard is an ASRock x570 chipset.

**Comment by Rem0o** [comment]
What header exactly do you got it plugged into? Is-it a PUMP_HEADER by any chance or something similar?

**Comment by hjohn** [comment]
The CPU fan is plugged into the CPU_FAN1 header.  One of the regular fans is plugged into CPU_FAN2/WP header.  The other two fans use CHA_FAN1/WP and CHA_FAN3/WP.
