### ISSUE TITLE
Multiple issues on my hardware - chance of more improvements of your software

### ISSUE THREAD

**Issue by Enomine88** [Rem0o/FanControl.Releases#160]
Hi,

i have multiple issues with your program on my hardware.
I want to help you improving you program to do more auto detecting and hardware support.

The list of issues may be very long so i first begin with saying "hello" and are you even interested in working together? I would give you the chance of analysing my PC and executing scripts to auto detect controllers, fans, temperatures and so on. Maybe this would give you more experience in "different hardware".

As you told in one of your videos on youtube - hardware support is you biggest wish.

So first we begin with my hardware:
- ASUS Sabertooth 990FX R2.0 (2013) (Providing 6 PWM headers on 3 lanes)
- NVIDIA GeForce GTX 1660 Super (2021) (Providing 3 PWM headers on 3 lanes)
- AMD FX-8350 Eight-Core Processor 4.01 Ghz
- **ATTENTION** Windows 10 Enterprise **LTSC**

Issues are multiple:
- Not found Controllers
- Not found RPM of Fans
- Not found Temperatures
- Temperatures are detecting the wrong temperatur

Thanks

Enomine

**Comment by Rem0o** [comment]
Please read the README.md.
