### ISSUE TITLE
"Hide" should hide control/sensor widget, not just grey/disable it

### ISSUE THREAD

**Issue by CalculonPrime** [Rem0o/FanControl.Releases#1608]
This is a feature request.

I have some unused controls and sensors.  The current "hide" function just greys them out and doesn't really hide them. Typically, in a widget framework, when you said "hide" you mean the widget gets removed from the page and no longer takes up screen real estate.

This feature would allow making the window nice and tight, with no wasted space or distractions.

As far as how you would then allow re-enabling controls and sensors, one option would be to have a picklist titled, "hidden sensors - select sensor to re-enable" (for example), that opens a list of hidden sensors when clicked.  With that list open, you could select one to unhide it.

**Comment by Rem0o** [comment]
Untick this: 
![image](https://user-images.githubusercontent.com/14118956/224458274-8c598daf-265a-494a-b4e3-1ad7c17394e6.png)

**Comment by CalculonPrime** [comment]
OK thanks.  I take it having that unchecked by default generated even more tickets? :)

**Comment by raspitakesovertheworld** [comment]
I'm trying to find this option, it is now 2025 and let me guess, it got removed?
I would suggest to rename this feature, correctly as "GREY OUT", because that is what it really is, not hide: hide always means "not visible anymore", that is the definition of hidden.
