### ISSUE TITLE
Ability to read hard drive/SSD temperatures

### ISSUE THREAD

**Issue by Snelso91** [Rem0o/FanControl.Releases#161]
After checking through the available options in Fan Control for basic temperature sensors, I can only see sensors that are provided by my motherboard and my GPU (ignoring the test and custom sensor).
![Fan Control Temp Sensors](https://user-images.githubusercontent.com/78712321/107307732-26d7cd80-6a7f-11eb-9f1a-4f9d9cce6372.png)

However, when I run the Libre Hardware Monitor application, I can clearly see that it is able to detect temperature sensors for all of my disks as well.
![Libre Hardware Monitor Temp Sensors](https://user-images.githubusercontent.com/78712321/107307762-348d5300-6a7f-11eb-8b08-4d7c603bd017.png)

For certain drives such as my M.2 SSD, or other drives that have a fan pointed at them, it would be useful to be able to adjust the fan speed based upon the drives' temperatures.
Therefore, since Fan Control is based upon Libre Hardware Monitor, could you please consider adding compatibility for these sensors to be used in Fan Control?
NB: The Libre Hardware Monitor version is v0.8.6 and the Fan Control version is v66.

**Comment by Rem0o** [comment]
You probably have your storage sensors disabled from the left-side hamburger menu.

**Comment by Snelso91** [comment]
> You probably have your storage sensors disabled from the left-side hamburger menu, as storage temps are supported.

Ah right, I didn't notice that before as I was using the default settings, but they appear to be working correctly now.
Would you mind telling me why they are disabled by default in the menu? Is there some downside to having them enabled/reading their temperatures?

**Comment by Rem0o** [comment]
Hard drives spinning up and or prevented from going to sleep.

**Comment by Snelso91** [comment]
> Hard drives spinning up and or prevented from going to sleep.

@Rem0o in that case, is there a way to only monitor SSD temperatures so as to allow hard drives to spin down normally?
If there isn't currently but it is possible, could you please consider adding this feature to the next release?
