### ISSUE TITLE
Which CPU Temp Option?

### ISSUE THREAD

**Issue by nimo956** [Rem0o/FanControl.Releases#1611]
If I want to create a curve based on CPU temp, which of the first five options below should I select?

![CPU Temp Sensors](https://user-images.githubusercontent.com/127604706/224486252-80d51714-c937-441c-b7c6-5f4b3e55a5fe.jpg)

**Comment by SimonZerafa** [comment]
I would use the one you have highlighted. The others are for each individual Core Complex (CCX), the max and average temperatures and the CPU iGPU temperature 😊

**Comment by Rem0o** [comment]
You could use Core or CCd average. It doesn't really matter, as long as you adjust your fan curve to reflect that sensor's temperature range.

**Comment by lostcowboy** [comment]
Have you been able to try the Custom Sensors yet? That is what I am trying, I just did it today, so I will likely be adjusting it. I used a MIX one and put all the CPU temps in it.  I then used a TIME one, set for 30 sec., and utilized the MIX as the source. The TIME one goes to my CPU curve. The only bad thing about the Custom Sensors is you can't hide them.
<img width="766" alt="FanControl_wNskjdQTdA" src="https://user-images.githubusercontent.com/26156479/227131014-1d0967e2-814a-4059-83a2-d79c62ca2a94.png">
