### ISSUE TITLE
request depreciation of Appearance, promotion of theme/SystemTray submenus

### ISSUE THREAD

**Issue by mirddes** [Rem0o/FanControl.Releases#1617]
![image](https://user-images.githubusercontent.com/13982888/224688895-94abdc6b-61f8-4ba5-aee9-b7d557f5fcd2.png)
![image](https://user-images.githubusercontent.com/13982888/224691197-2d792c9c-8d3b-4f88-992d-26362f154c53.png)

**Comment by jeyrella** [comment]
I believe this is no longer an issue with the menu improvements as of v...168(?)

**Comment by mirddes** [comment]
Indeed. The new layout is awesome.
