### ISSUE TITLE
Direct Setting for RPM of fans

### ISSUE THREAD

**Issue by hl2guide** [Rem0o/FanControl.Releases#162]
Please allow the user to directly set the RPM for fans:

e.g. run fan at 800 RPM

**Comment by Rem0o** [comment]
To do that, would have to create a RPM/% map for all of your fans with an utility. Then I would have to support both % and RPM, depending if you created the maps or not. That's alot of complications for no benefits. It's easy enough to find the % for 800 rpm if you really want that specific speed for some reason.
