### ISSUE TITLE
Unable to see watercool pump or temp 

### ISSUE THREAD

**Issue by Rixonline** [Rem0o/FanControl.Releases#1624]
No matter what I do, I can't get fancontrol to see my distro pump that is connected to the pump header 
It also doesn't see the water cooling temp sensor that's connected to the motherboard.

Tried the Asus plug-in, tried uninstalling.
Worked perfectly on my previous asus build 

**Relevant hardware specs and setup**

Asus rog strix x670e - am5
Nvidia 4090, and 7950x3d
Distro is a bitspower sena lian li evo

**Comment by Rem0o** [comment]
See hardware and compatibility section in README.
