### ISSUE TITLE
Gigabytye X670E Aurous Master Motherboard Not Detecting Fans Or Sensors.  

### ISSUE THREAD

**Issue by 007L2Kill** [Rem0o/FanControl.Releases#1626]
Hope you can help me, I brought a new motherboard but the control of the fans ramping is annoying, so I thought I try Fan control software out to see how I get on with it, but the problem is on start-up it kept throwing errors up, but now that as stopped and going through all the settings the software only detects two sensors or fans that is CPU and SYS fan 1 as there are eight fan headers on the board and straggly only shows sixth on the main page.

I am using headers CPU, SYS fan 1, Sys fan 4, SYS fan 5, SYS fan 8, only first two are working rest what's on the main page fan 3 to 6 are showing nothing and control nothing.

Can anything be done to see all other fans?

Thank you.

**Comment by Matthew2051** [comment]
Same here but on the X670E AORUS XTREME mb. Just updated BIOS to F7b, no more sensors or fans.

**Comment by Marius8** [comment]
the issue lies with how Gigabyte handles the 2nd control chip on the boards..
A Fix for that for AMD boards has been released by LibreHardwareMonitor just Minutes after the release of V150 https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/251 https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/297c3485d6fff785f0f7bc1ea7e23383c5b97177

**Comment by 007L2Kill** [comment]
Thanks a lot.

Updated to the latest software and no difference, still only shows what I said above.

**Comment by stylez84** [comment]
I have the same motherboard and the same issue. Latest Libre Hardware Monitor (0.9.2) doesn't resolve the issue. According to LHM the chip on this motherboard is ITE IT8689E. It shows RPM for Fan #1 and nothing else.

**Comment by Matthew2051** [comment]
Again, slightly different mb, X670E AORUS XTREME... but same thing, no improvement. After updating BIOS to F7b, went from 30+ sensors to 14. No fans. Maybe something on the BIOS end as since updating, I can't access the fan xpert / control in the BIOS either.

**Comment by Marius8** [comment]
does LibreHardwareMonitor show all entries properly for the X670E Master board?
If not, the board might not maintained properly yet in the scource.. (or we might need to wait for LibreHardwareMonitor/LibreHardwareMonitor/pull/1026

**Comment by stylez84** [comment]
@Marius8 I guess it depends on what you mean by all entries. Here's a screenshot from LibreHardwareMonitor showing what it sees on my Aorus X670E Master.
![image](https://user-images.githubusercontent.com/128747819/227356633-c63649b9-4a82-47ea-b729-6f54b8f372be.png)

**Comment by Matthew2051** [comment]
> LibreHardwareMonitor

Sample from XTREME, guessing there should be much more under the mb!

![image](https://user-images.githubusercontent.com/70651100/227356964-6b11bc08-b5c7-497c-89c2-dc6feab63b16.png)

**Comment by stylez84** [comment]
I'm going to troubleshoot this on my end a bit. My case fans are plugged into pump headers (pump 6 and pump 7) and my AIO is on pump 8. I would expect/hope these to show in LHM so they could also be controlled.
I'm going to test relocating my case fans to the regular fan headers and see if they show an RPM in LHM.

**Comment by Marius8** [comment]
@Matthew2051 yes.. there should be a LOT more visible, maybe the bios update broke something in that regard..
if you can, try reverting to the last bios version, otherwise you might need to open an issue with LibreHWM.
@stylez84 most of the higher end gigabyte boards have 2 control chips, don't know, if that is the case for the X670 series, too, but the last 2 or 3 gens at least have 2 ( on both AMD and intel platforms) and it does not seem to recognize the 2nd chip on yours, as you state 8 headers, but only 6 are visible

**Comment by Matthew2051** [comment]
> @Matthew2051 yes.. there should be a LOT more visible, maybe the bios update broke something in that regard.. if you can, try reverting to the last bios version, otherwise you might need to open an issue with LibreHWM. @stylez84 most of the higher end gigabyte boards have 2 control chips, don't know, if that is the case for the X670 series, too, but the last 2 or 3 gens at least have 2 ( on both AMD and intel platforms) and it does not seem to recognize the 2nd chip on yours, as you state 8 headers, but only 6 are visible. for comparison: this is my X560: ![image](https://user-images.githubusercontent.com/10903611/227361604-33fb441f-ea58-4a39-bf3b-1b55d1e6a160.png)

Yeah, two chips... already had that head scratching session when first configuring FanControl, I was able to compromise though and make do with the sensors on the first chip... most of the fans were daisy chained off the recognisable headers too.

Thanks for the the feedback though, will have another tinker this weekend and update.

**Comment by stylez84** [comment]
I was able to move my case fans to the fan headers along the bottom of the motherboard and they're now showing properly. It seems the second unsupported chip is controlling all the pump headers and the one regular fan header along the right side of the motherboard.

**Comment by Marius8** [comment]
ok.. updated to V152.. the secondary chip can still not be controlled on the X570 platform..
@Rem0o do you use the 'official' releases, or nightly build of the HWM library?

**Comment by Matthew2051** [comment]
> > @Matthew2051 yes.. there should be a LOT more visible, maybe the bios update broke something in that regard.. if you can, try reverting to the last bios version, otherwise you might need to open an issue with LibreHWM. @stylez84 most of the higher end gigabyte boards have 2 control chips, don't know, if that is the case for the X670 series, too, but the last 2 or 3 gens at least have 2 ( on both AMD and intel platforms) and it does not seem to recognize the 2nd chip on yours, as you state 8 headers, but only 6 are visible. for comparison: this is my X560: ![image](https://user-images.githubusercontent.com/10903611/227361604-33fb441f-ea58-4a39-bf3b-1b55d1e6a160.png)
> 
> Yeah, two chips... already had that head scratching session when first configuring FanControl, I was able to compromise though and make do with the sensors on the first chip... most of the fans were daisy chained off the recognisable headers too.
> 
> Thanks for the the feedback though, will have another tinker this weekend and update.

By chance there was a new BIOS released the other day for the X670E XTREME, version F8a. This resolved my issue with not seeing fans and sensors. All sorted now apart from the lack of second chip usable in Fan Control, but as mentioned, I can make do using certain headers and live without one of my sensors placed in the case.

![image](https://user-images.githubusercontent.com/70651100/227780276-8629fb2f-98f5-43fa-b738-e44741f4cade.png)

**Comment by Marius8** [comment]
ok, small update from some testing of mine:
LibreHWM can control the 2nd chip in 0.9.2. on my board.
right click the control of a fan on the 2nd chip, and select a % value under manual.
something other, i found, while experimenting with that, is that FanControl can manage the 'fans' on the 2nd chip while Libre HWM is open.
once you close it, the control of the 2nd chip goes back to the mainboard

**Comment by 007L2Kill** [comment]
I just updated my BIOS to F10a and everything still the same, only see 5 fans

**Comment by Marius8** [comment]
Ok, on my X570, everything works now as expected :D
@Matthew2051 @007L2Kill @stylez84 regarding your 2nd chip: it looks to me, like Gigabyte changed chips, when building the X670 boards, one of you should open an issue with LibreHWM

**Comment by 007L2Kill** [comment]
Cheers guys for the updates.

Been building a custom water loop, took longer than I thought it would, but was hoping after reading all the comments that 153-fan control would work.

Updated to 153 and nothing, just the same no difference, weird as HWinfo does not read the sensors, but AIDA64 Extreme does.

Would like to get this working so I can set the case fans to work with GPU core temp.

**Comment by Rem0o** [comment]
@007L2Kill  did you activate the InpOut option in sensor settings?

**Comment by 007L2Kill** [comment]
> @007L2Kill did you activate the InpOut option in sensor settings?

Hi

Yes, its activated and shows 2 more fans but zero control for what ever fans it was showing, seems to me it’s a Gigabyte bios issue because that many beta bios just lately and because I wanted control of the fans to work with my GPU, I brought some splitters and extension cables and modified the case fans to work off the 3 working headers and works great.

Thanks a lot.
