### ISSUE TITLE
[Documentation] Windows Notification Task Bar Widget

### ISSUE THREAD

**Issue by ThePieMonster** [Rem0o/FanControl.Releases#1628]
Similar to "Core Temp", allow the user to use any of the sensors and create a notification widget. 

![image](https://user-images.githubusercontent.com/11359134/226085518-0bdfa94b-8ede-448e-95fa-b3c7cff9d6d8.png)

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/226118657-ff5af395-d67e-4ff6-8a4b-0382cb9c559a.png)

**Comment by ThePieMonster** [comment]
Oh wow. I was looking through the website documentation and did not see this! I guess I'll adjust my issue to say this should be documented on the read me / website and perhaps even in the UI tool in a easier to find manner.  :)

Thank you!
