### ISSUE TITLE
Clear Naming for CPU Fan

### ISSUE THREAD

**Issue by hl2guide** [Rem0o/FanControl.Releases#163]
Please consider improving the app to auto label a fan as a CPU fan if it is for the CPU fan header port.

**Comment by Rem0o** [comment]
Problem is, I don't have that information behind the scene.

**Comment by hl2guide** [comment]
ah ok, is the CPU fan normally fan 1 then?

**Comment by Rem0o** [comment]
It is motherboard dependant, so I can't tell, sorry.
