### ISSUE TITLE
7900 XTX missing junction temps

### ISSUE THREAD

**Issue by lordraiden** [Rem0o/FanControl.Releases#1633]
Hello it would be possible to add junction temps to Fan control?

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

**Comment by lordraiden** [comment]
> See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

Thanks for the info, sorry I didn't know.
In any case it looks like there might be a solution soon 
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/251

**Comment by Rem0o** [comment]
@lordraiden  I'm sticking with control only. Don't want to bloat the application.

**Comment by lordraiden** [comment]
> @lordraiden I'm sticking with control only. Don't want to bloat the application.

I understand but it will debloat our PC, so we can uninstall the other app to see the histogram of temps or rpm, etc.

It could be a tabbed interface, something simple
