### ISSUE TITLE
Adding extra thermal sensor so Fan Control can use it

### ISSUE THREAD

**Issue by voivodpl** [Rem0o/FanControl.Releases#1634]
Ok, so I have BQ! Silent loop 2, and I would rather want to rely on water/cooler temp rather than CPU package for CPU fan speed.
What thermal sensor/monitor do you recommend for me to buy so it could be used with Fan Control app?

**Comment by Rem0o** [comment]
AFAIK there is no third party temp sensor that work with FanControl just yet.

**Comment by voivodpl** [comment]
Any plans? ;-)

**Comment by EvanMulawski** [comment]
This is technically possible if you have a Corsair Commander and use [my plugin](https://github.com/EvanMulawski/FanControl.CorsairLink).
