### ISSUE TITLE
[Feature request] Set fans to X% if temp below B (Mix Card)

### ISSUE THREAD

**Issue by lordraiden** [Rem0o/FanControl.Releases#1635]
I have a mix card like this
![imagen](https://user-images.githubusercontent.com/17175395/226387953-f9aae363-7ac6-4131-89a5-88c092a3ced9.png)

It takes into account GPU and CPU temps with its curves, based on their own temps.

I'm running a custom water loop and I would like to have in the mix card a setting to override the curves if other temps is below a value.

For example **if** water temp is below 20 set the radiators fans to 0. **If not** the fan curves apply. 

This will simplify the setup and will add more flexibility, and the same config would be valid for my winter and summer :)

**Comment by Rem0o** [comment]
While I agree it may seem complex, your requirement is quite complex, and every "block" in the equation describe one of the variable of your requirement. A block for that specific requirement may get made, but then a dozen others would also be justified. I prefer sticking with simpler blocks that allow complex logics to be made, keeping the number of blocks to a minimum.
