### ISSUE TITLE
help with plugin

### ISSUE THREAD

**Issue by qe58hmr** [Rem0o/FanControl.Releases#1636]
have thermaltake aio connected it with controller im trying to use fancontrol with it i tryed the https://github.com/fu-raz/FanControlThermaltake i copied FanControl.Plugins.dll to plugin but it didnt show can some one plz explain to me how step by step

**Comment by Rem0o** [comment]
You only need to put the thermaltake dll into the plugin folder, not  FanControl.Plugins.dll.
