### ISSUE TITLE
[BUG] Update from 149 > 150 Failed

### ISSUE THREAD

**Issue by Hammerfest** [Rem0o/FanControl.Releases#1637]
Have had since v136 and let it do its update without issue.
Update released today is v150, but when I hit update the application closes and nothing else happens.
Relaunching from FanControl.exe is still v149 and prompts for update which continues the same cycle above.

No error in event logs, or app logs to tell me whats going on.

Its possible the issue is the files aren't ready from Github, it still shouldn't just close old version then not do anything after hitting update however.

**Comment by matlegit** [comment]
I have the same issue going from v147 to v150

**Comment by Hammerfest** [comment]
Yep, update went through without issue.

You pointed out the issue with the updater as well so im sure if its possible to fix or workaround it might see the light in the future.

Closing for now.
