### ISSUE TITLE
Configuration does not work on EX-A320M-GAMING

### ISSUE THREAD

**Issue by cremilton** [Rem0o/FanControl.Releases#164]
Program configuration is not applied without opening the HWMonitor program, and the correct display of the fans also occurs only after the HWMonitor is executed!

Thanks for the software development!

Following are images of the test:
After hwmonitor, sensor detect is not correct

![before-hwmonitor](https://user-images.githubusercontent.com/3596949/107780859-ffeef500-6d25-11eb-9924-8a979ae5396d.png)

before-hwmonitor

![after-hwmonitor](https://user-images.githubusercontent.com/3596949/107780832-f8c7e700-6d25-11eb-981e-a0fd43782273.png)

In LibreMonitor everything appears correctly: 

![libre-monitor](https://user-images.githubusercontent.com/3596949/107780946-19903c80-6d26-11eb-9312-62181bbc6499.PNG)

**Comment by Rem0o** [comment]
Define "correct" and "not correct".

**Comment by cremilton** [comment]
Oops, the problem occurs with the libremonitor itself!
I've already reported!
Thank you!
