### ISSUE TITLE
I can't control any fan

### ISSUE THREAD

**Issue by JulietteDestang** [Rem0o/FanControl.Releases#1644]
hi, 
i'm a noob with fan control! I don't know why it can't find any of my fan.
i have this error: "nvapi cant not initialize or have no sensor"
Can you help me on this?
sorry !

![image](https://user-images.githubusercontent.com/72016327/227172616-75bcaa5a-8dc1-42e7-9b63-8b1a4e71844f.png)

**Comment by JulietteDestang** [comment]
it's an asus rog, thanks for your answer :)

**Comment by eddurov** [comment]
> You must have a laptop or a pre-built Dell/Lenovo right?

I have lenovo and the same problem=) Is there any problems especially with lenovo?

**Comment by Rem0o** [comment]
@eddurov  they are not supported. See README.

**Comment by JulietteDestang** [comment]
Why are you closing my issue? I have an Asus :(
