### ISSUE TITLE
Fan control for AMD GPU not working/is overridden

### ISSUE THREAD

**Issue by panda4k** [Rem0o/FanControl.Releases#1647]
**Describe the bug**

Edit: Using FanControl V151

Creating any fan curve and assigning it to the fan control for the Sapphire Nitro+ SE 6900XT doesn't work.

It appears to start adjusting the fan speed briefly as observed by the change in the fan speed in % number in FanControl and then after a second it returns back to whatever the GPU's default fan curve is setting it to. That change is not visible physically on the GPU fans themselves so the report is probably only reporting what it is attempting to do and not what it actually did or it did but the fans didn't have enough time to react since something else is overriding it.

Force Apply is enabled, no difference.

For other fan control software that I have running, is only the AMD Adrenalin software without having the Fan Tuning toggle enabled in its settings.

Worth noting is that when trying to set a custom curve with MSI Afterburning or Argus Monitor, it works as intended. (those apps are not running when trying FanControl), as well as that I have CorsairLink plugin installed which works also fine alongside all other controls and monitors.

**Relevant hardware specs and setup**
Gigabyte B550 Aorus Elite V2 rev1,
Sapphire Nitro+ SE 6900XT

![image](https://user-images.githubusercontent.com/83919497/227321602-2642245e-decd-4a43-a872-2a5e8f2b4ace.png)

**Comment by rodochopper** [comment]
yes that happened to me too, but with the CPU showing only 20RPM, also all the other sensors didn't work, just the sensor for the GPU and one case fan from motherboard. Tried to manual speed them up but no changes, tried to force them but nothing. They all worked on other versions. 

asus strix b550-f gaming
Noctua fans for the cpu
rtx 3060ti
AMD 5900x

tried to check on the mobo bios and all of the sensors were recognized

**Comment by Rem0o** [comment]
from FAQ:

Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!

**Comment by panda4k** [comment]
I've tried [FanControlADLX](https://github.com/Rem0o/FanControl.ADLX) plugin (I noticed it is marked as Experimental) and that allows FanControl to work properly with the GPU. However it doesn't appear to be able to go bellow 15% of the speed, so essentially 0 rpm mode isn't working.

**Comment by areasudon** [comment]
> from FAQ:
> 
> Q: My new AMD card can't be controlled, why? A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!

How does it work in MSI Afterburner? Its also third party, or they have direct support from amd maybe

**Comment by panda4k** [comment]
> > from FAQ:
> > Q: My new AMD card can't be controlled, why? A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!
> 
> Why does it work in MSI Afterburner? Its also third party, or do they have direct support from amd probably?

Realistically MSI Afterburner has been around for years, would be strange if they didn't make it work by now. I'm sure FanControl will manage the same eventually.
