### ISSUE TITLE
 [Feature Request] Wattage

### ISSUE THREAD

**Issue by MarekBeers** [Rem0o/FanControl.Releases#165]
I don't know how you can implement this with a varying wattage and stuff, but I removed my fan from my PSU and now control the PSU fan speed by temperature, but I think it's cool to have a fan curve of wattage over multiple components.

Combine multiple items for the wattage so CPU+GPU
And make a curve with a custom end point that the user can set e.g. 300W (in my case a 3900xt and a GTX 1080)

I think this maybe can be a cool addition! Or not you tell me. xD

**Comment by Rem0o** [comment]
Well why not use temperature? Watts ultimately convert to heat, then temperature, which is what you want to control.

**Comment by sctanf** [comment]
Temperature takes some time to rise, maybe you want to catch the heat load before it hits. Wattage would be a slightly faster indicator than temperature, although it doesn't compensate for ambient temperature. Otherwise I see no benefit, unless your temperature sensor is hopelessly broken or something.

**Comment by Rem0o** [comment]
Catching before it happens? You'll catch more than heat, which will result in erratic fan speed changes. You never want to overcomplicate a control loop.

**Comment by sctanf** [comment]
I didn't say it would be a good alternative. Wattage fluctuates even more than temperature does.

**Comment by Rem0o** [comment]
@MarekBeers if you don't have a good case for your feature request, I will close this issue.

**Comment by MarekBeers** [comment]
As i said I had a noisey fan in my power supply so i replaced it with a normal 120mm fan but its plugged in to my motherboard for pwm control and my power supply does requlates the fan based on wattage but i dont have that funcunality anymore and maybe some other people also have this niche use case. And i dont have the temprature of the psu saddly.

Maybe you dont like the idea and that's fine so you can close the thread if you want.

**Comment by sub20hz** [comment]
Is there any chance this could be reconsidered? I too am looking to control a custom psu fan that ultimately should respond to system wattage (or really just cpu+gpu wattage). This is the primary use case I have in mind where temperature sensors simply won't work here.

On top of that, with higher and higher cpu core counts, I find that even average temperatures aren't simple indicators to use when tuning a fan curve for a particular noise profile, as opposed to just setting it based off of cpu package wattage. Similarly, when setting fan curves for case fans, I find wattage to be a very reliable indicator to use when balancing a noise profile. This could be particularly useful for people that are running high wattage hardware in absurdly small form factors, among other things.

**Comment by dr04e606** [comment]
I'm also one of those who replaced their fans inside their PSU's... 

I have tuned my radiator fans towards silence, so they barely spin until the corresponding chip reaches 55C and only after that they (very gradually) ramp up. With such variability in cooling performance, the ability to create a mix custom sensor with CPU+GPU power consumption sum would be a much better way to control PSU fan. 

FanControl is already great, but having the ability to use power consumption sensor data for controlling your fans, would make it even better.
