### ISSUE TITLE
I thought the suggestions made from friends from China

### ISSUE THREAD

**Issue by llznni** [Rem0o/FanControl.Releases#1650]
I am a friend from China. [Fan ControL] is the best fan controller I have used. I have used it for two years. Thank you very much for your credit. I hope the software can produce the Chinese version. I have recommended a lot of friends use.

**Comment by llznni** [comment]
There are more and more Chinese users, and your software is getting stronger and stronger, and supports you from the bottom of your heart. On behalf of all Chinese users

**Comment by Rem0o** [comment]
Already an issue for multi-lang support, so will be closing..

Thanks for the support
