### ISSUE TITLE
how can I control the fan connected to MSI pump_fan 2

### ISSUE THREAD

**Issue by IkarosForever** [Rem0o/FanControl.Releases#1653]
I set a fan to pump_fan2, I can control the fan in BIOS, but I cannot find the option in fancontrol. I am the MSI Z790 ACE, how can I solve the problem?

**Comment by Rem0o** [comment]
See the hardware compatibility section in the README.

**Comment by IkarosForever** [comment]
> See the hardware compatibility section in the README.

sorry about this problem, maybe I mean that if I have two pumps, how can I control the two pumps respectively? there is only one option for one pump.
<img width="1431" alt="1" src="https://user-images.githubusercontent.com/128843736/229336979-9d0f6092-3b54-4240-8f55-3712d555a269.png">

**Comment by wqshmzh** [comment]
Same here. I use V219 and pump_fan 2 of MSI Z790ACE does not show in FanControl.
