### ISSUE TITLE
Unable to update from 149

### ISSUE THREAD

**Issue by Taomyn** [Rem0o/FanControl.Releases#1657]
**Describe the bug**
Every release since 149 I've been unable to upgrade, and starting up it shows an error and I must kill the task.

![image](https://user-images.githubusercontent.com/4365929/227739696-aeca6848-c037-495f-81ae-15c4a549f1da.png)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No

**Relevant hardware specs and setup**
Gigabyte B450 I AORUS PRO WIFI-CF
MSI nVidia 1070Ti

**Comment by Rem0o** [comment]
any log.txt?

**Comment by Taomyn** [comment]
Yes but nothing logged since January

**Comment by LyraelRayne** [comment]
I get the same message. No log.txt present.

B550 Aorus Pro AX

**Comment by Rem0o** [comment]
I think the ids for the IT879 got renamed, breaking configurations that were built on top. Are there "new" control and speed cards appearing?

**Comment by LyraelRayne** [comment]
I tried to "refresh sensors detection" (I presume that's how new cards would be found) and got an "Initialization failed" popup followed by the original message. Still no log.txt

**Comment by Taomyn** [comment]
I made a copy of my current folder and then upgraded to 153, on starting this is what I got:
![image](https://user-images.githubusercontent.com/4365929/229687068-f5840bc6-3d83-4784-9765-820c197d093f.png)

Afterwards I had some extra fan controls/speed and it's a bit of a mess:
![image](https://user-images.githubusercontent.com/4365929/229687237-31bf0642-4c44-427e-b783-9f0da62dec74.png)

So tonight I will reset the config and see what it detects from a clean start.

**Comment by javs** [comment]
Oof, my bad, I renamed that in LHM, I didn't realize that would break here. I got the same error recently with my board.

What you can do is open the fan config .json file in a text editor (backup first), search and replace `it879xe` for `it8792e`, then start fan control.

**Comment by Taomyn** [comment]
Thanks @javs, that did the trick, I got the previous version config file, made the changes, placed the file into the config folder and it started as expected.

**Comment by LyraelRayne** [comment]
Thanks, that fixed it for me as well.
