### ISSUE TITLE
[Feature request] Disable new update notification popup.

### ISSUE THREAD

**Issue by teijiIshida** [Rem0o/FanControl.Releases#1658]
Hello, I'd like to request an option to disable the notification popup whenever there is a new update.

I'd like to manually update every few months, but whenever there is a new update, there is a popup telling me about it (on application launch). It's pretty annoying. Can you please add this feature? Or add a "silent mode" where there will never be any popup whatsoever until the user turn it off?

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/227797034-9187d17d-aef7-4414-b830-61554b23a641.png)

Just check this checkbox.

**Comment by teijiIshida** [comment]
That will only disable it for one version, no?

If another version releases after that version, it will pop up again. Then, I'll have to check it again and again for every new version.... which doesn't really solves the problem but delaying it.

**Comment by Rem0o** [comment]
Nop, as long as you stay on a given version, you won't get any pop-up.
