### ISSUE TITLE
Refresh sensors detection - more frequently/automatical

### ISSUE THREAD

**Issue by joyzer** [Rem0o/FanControl.Releases#166]
Is it possible to have Refresh sensors detection - more frequently/automatical - as quite often the fans don't ramp down unless I trigger this manually.

Thanks :)

**Comment by Rem0o** [comment]
Refresh sensor detection is not supposed to be automatic or done every minute. It is a hard reset. If your fans don't ramp down, it means something else is interfering with your fans.
