### ISSUE TITLE
Enable TieredPGO

### ISSUE THREAD

**Issue by mattzink** [Rem0o/FanControl.Releases#1660]
Since FanControl is a long-lived service, it would be nice if the .NET 7 build enabled [Tiered PGO](https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/#pgo). This would improve CPU and memory utilization. It can be enabled by default by [simply adding](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/compilation#profile-guided-optimization) `<TieredPGO>true</TieredPGO>` to your csproj file.

Today, I hand edit the "FanControl.runtimeconfig.json" file to enable it, but the updater overwrites it after each update, so it would be nice if this was enabled by default for everyone.

**Comment by Rem0o** [comment]
Will have to read the whole thing. Does it needs to be enabled for every assembly? Like LHM itself isn't compiled with it AFAIK.

Also, any downside?

**Comment by mattzink** [comment]
> Does it needs to be enabled for every assembly?
No, only the executable project.

> Also, any downside? Why isn't it just enabled by default?
The only downside is a small amount of extra memory usage when the runtime is still gathering information on call counts, etc to determine which methods should be re-JIT'd with extra optimizations. That memory is released eventually, though. This will be enabled by default in .NET 8.

**Comment by Rem0o** [comment]
Sold. Will enable it in the next release.
