### ISSUE TITLE
Case fans ramp up during setup but "never start" for controlling

### ISSUE THREAD

**Issue by dmb33** [Rem0o/FanControl.Releases#1664]
All of my fans ramp up during the initial setup, but my 3 intake case fans "never start" at the end of setup. They appear to be recognized, but I have no control over them. My exhaust fans are connected to the motherboard. My intake fans are connected to the fan hub connector in the back of my corsair airflow 5000d case. I've used this exact case and fans with Fan Control before and it worked. Again the fans do ramp up during the setup process but that's it. 

![Screenshot of fan controler](https://user-images.githubusercontent.com/129034595/227854463-193a0018-3bef-4e26-b5a0-2d3a7a245fc7.png)

**Comment by Rem0o** [comment]
See the hardware and compatibility section in the README.
