### ISSUE TITLE
X570 Pro4 SB chipset temp

### ISSUE THREAD

**Issue by bcrod** [Rem0o/FanControl.Releases#1669]
I'm using X570 Pro4 motherboard from ASROCK and FanControl can't read South Bridge Chipset temps, no detection. I don't understanding.  HWINFO64 reads just find. I have to use hwinfo plugin to detect the temp.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
