### ISSUE TITLE
Custom sensor as input for custom sensor

### ISSUE THREAD

**Issue by Marcaroni8** [Rem0o/FanControl.Releases#167]
The error `"SensorName" can't be added to the mix.` is given when adding a custom sensor to another custom sensor.
This is a problem when trying to do more complicated stuff, like combining Min and Max functions with an Average function.

**Comment by Rem0o** [comment]
Yeah for the moment mix sensors are pretty basic. Didn't code in mix of mixes to avoid infinite loops.  It is on my to-do.

**Comment by Rem0o** [comment]
Can confirm it will be supported in my next release.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V68
