### ISSUE TITLE
Fan Speed Broken

### ISSUE THREAD

**Issue by Audipower** [Rem0o/FanControl.Releases#1673]
After New Windows 10 Install on a Asus Prime B-350 Plus (AM4) Mainbord ( Ryzen 1600X) with the same Bios Settings as before.

Fan Control doesn't work in Setup 

The Fans Ramp Up but Fan Control doesn't see Changes and says no Sensor Found to Pair for all 3 Fan Controller on the Mainbord.

CPU Fan No Sensor, but Ramp Up Speed /  Fan Chassi 2 Ramp Up both checkt with Asus FanXpert and Hwinfo.
CPU goes from 300 - 1200 rpm  / Chassi 2 From 600 - 1300 rpm / Chassi 1 is free

Fan Controls Shows 3 Fans
Fan Speed Shows 2 Sensors  Fan#1 with 20,7 rpm and Fan#2 with 2647,8 rpm Fan#3 Sometimes Nothing and then  9768,5 Rpm 
The RPM Never Changes 

I try Fan Control with HW Info Plugin but nothing 

I try new Download and delete all Old Files with PC Restarts  Nothing 

I will try it with a Older Version of Fan Expert but i cant find a Download for Version  V147

**Comment by Rem0o** [comment]
Releases available here:
https://github.com/Rem0o/FanControl.Releases/releases

As for hardware compatibility, see README.

**Comment by Audipower** [comment]
hellp
