### ISSUE TITLE
Feature Request: Fan speed as a source for Trigger and Graph curves

### ISSUE THREAD

**Issue by valkuc** [Rem0o/FanControl.Releases#1677]
First of all, thanks for application. I want to ask you to add ability to use not just temperature sensor in Trigger and Graph curves, but also to have ability to select fan sensor. 
Here is real life example. I have extra two 40mm fans below GPU and I want them to start rotating when the GPU fans at 30% and after that value to be in sync with GPU fan. When the GPU fans speed drop below 30% the 40mm fans should stop. This is for Trigger curve. Using Graph curve will give even more freedom in adjusting fan speed.
My current setup look like that:
![изображение](https://user-images.githubusercontent.com/6421082/228667778-85e55172-6338-4ebd-9d1d-42f75b3f9478.png)

**Comment by Rem0o** [comment]
Various ways you can do this already. 
Expand your 40MM control card, and set your start% at 40%, stop% at 30%. Then simply use your Sync With GPU fan curve with 0% offset.

**Comment by valkuc** [comment]
Yep, this will work but using this approach the fan will be fully turned off if GPU fan is below 40%. I specifically added 25% offset to make 40mm fans turn at lowest possible speed (no noise) when GPU fans turned off.
If there was ability to build Graph curve based on fan speed I would do something like this:
0-50% GPU --> 25% my fan
50-100% GPU --> linearly scale my fans from 25% to 100%

**Comment by Rem0o** [comment]
Well, I can't really add exactly what you are requesting, as it would require any actual temperature input to be able to be replaced by other types of sensors, which don't behave the same as temperature sensors.   
That would be a massive overhaul from the app's perspective. 

Could add maybe more parameters to the sync fan curve to support those kind of advanced mappings. 

However for your use case, why not simply set a graph based on GPU temperature, shaping it to based on temperature so that it behaves roughly like you want?

**Comment by Rem0o** [comment]
Idea:

Sync fan curve => three dot menu => proportional => set a 50% offset.

Your 40mm control, use that fan curve, set a minimum% to 25, remove start and stop% (0), set a -50% offset.

**Comment by valkuc** [comment]
> Idea:
> 
> Sync fan curve => three dot menu => proportional => set a 50% offset.
> 
> Your 40mm control, use that fan curve, set a minimum% to 25, remove start and stop% (0), set a -50% offset.
> 
> That should give you the exact (?) mapping you described.

Not work for me. Those 40mm fans require high pulse to start, so removing start % preventing fans from starting.

**Comment by valkuc** [comment]
> Well, I can't really add exactly what you are requesting, as it would require any actual temperature input to be able to be replaced by other types of sensors, which don't behave the same as temperature sensors. That would be a massive overhaul from the app's perspective.
> 
> Could add maybe more parameters to the sync fan curve to support those kind of advanced mappings.
> 
> However for your use case, why not simply set a graph based on GPU temperature, shaping it to based on temperature so that it behaves roughly like you want?

Theoretically it's possible to use temp Graph curve, but then it's necessary to figure out GPU curve itself that is probably hardcoded inside GPU. Not an easy way ))

Well, anyway, thanks again for your software. I find it much more user friendly and convenient than the one that comes with motherboards from famous manufacturers.

**Comment by Rem0o** [comment]
> Not work for me. Those 40mm fans require high pulse to start, so removing start % preventing fans from starting.

You can still set whatever start% if a kickstart is required.

**Comment by valkuc** [comment]
> > Not work for me. Those 40mm fans require high pulse to start, so removing start % preventing fans from starting.
> 
> You can still set whatever start% if a kickstart is required. Previous idea should work.

Hm... Tried one more time and it's working, the fan is staring. Probably I did some mistake when did that first time. So, I got your idea. Now just need to figure out valid % proportions to match my use case.

Thank you!
