### ISSUE TITLE
High CPU Usage (5% constant)

### ISSUE THREAD

**Issue by Lollaskates** [Rem0o/FanControl.Releases#168]
Is this normal? What could be causing such a high CPU usage? Losing that much performance to fan polling seems not worth the additional control over the BIOS.

If you don't have any ideas I'd be happy to try and take a look.

**Comment by Rem0o** [comment]
Screenshot of your current settings?

**Comment by Lollaskates** [comment]
Hey Rem0o, just stock. I opened the app for the first time and checked out the resource utilization as it was open and polling, and minimized it to tray, etc (wondering if it was the GUI drawing that was causing the usage) and it appears to just be constant. If this is not normal, I'll proceed with screwing around with a config and see if it changes.

Windows 10 Version 10.0.19042.804
Ryzen 5900X
RTX 3080

**Comment by Lollaskates** [comment]
Interesting, after closing the process and opening it a few times the cpu usage dropped to what I would expect, virtually nothing. Hm...

**Comment by Rem0o** [comment]
There shouldn't be any "artifact". With the UI open, it should still average <1%.

**Comment by Lollaskates** [comment]
Hmm, It just happened again randomly. I opened Task Manager and saw it again at 5% constant. It happened around the time I ran HWInfo64 - perhaps there's some unfortunate interplay between them both polling all the devices / sensors.

**Comment by Rem0o** [comment]
Remove HWInfo from the equation maybe?

**Comment by Lollaskates** [comment]
Hm, well it seems like I'm unable to reproduce it reliably, and normal operation seems okay so I'll go ahead and close this! Thanks for the fast responses. Cheers!
