### ISSUE TITLE
Pc crahses immediatly after pressing ok...

### ISSUE THREAD

**Issue by DerFnn0** [Rem0o/FanControl.Releases#1680]
hey,
i wanted to start using fan control, but evry time aufter hitting ok the PC crahes.
idk if its my PC components because there kinda old:
Motherboard: Gigabitye GA H110 m SA2r
CPU: I7 6700
GPU: RTX 2070 super
(i know its kinda fucked up)

or has it something to do with software or the Bios???

**Comment by Rem0o** [comment]
Hitting   ok... where? Which dialog?

Can you provide a screenshot?

If it's the assisted setup, some boards don't like getting hit with 0% ( no power ) on the CPU header, which fan control does during the setup.  Yu may just skip the assisted setup all together and just start setting fan curves without it.
