### ISSUE TITLE
Suggestion : Adding an API

### ISSUE THREAD

**Issue by 1rabbit** [Rem0o/FanControl.Releases#169]
Awesome software. I love it

It would be great to have an API with json outputs to integrate the data such as temperatures/rpm in all sorts of applications, such as telegram bots, monitoring from a remote location, external display... Endless possibilities :) 

Maybe even load different profiles remotely

Keep up the good works !

**Comment by 1rabbit** [comment]
Nice. I see it's supposed to have a http server open on http://localhost:8085/data.json but I can't access It with only fan control running. Does that mean I have to run another instance of libre hw or is it possible to open it with just fan control running? That would be a convenient option :)

**Comment by Rem0o** [comment]
The HTTP server is in the "application" portion of LHM, not the LibreHardwareMonitorLib portion, which is the one I'm using. Anyway, FanControl is not a monitoring tool, and I think this feature is out of scope.
