### ISSUE TITLE
Failed to load plugin Thermaltake.dll

### ISSUE THREAD

**Issue by scorpiontzr** [Rem0o/FanControl.Releases#1691]
First of all thanks for this nice peace of Software.
I search for an SW I can control both Thermaltake and system Fan.
...
so I started with SW Version 152,
then I downloaded the Thermaltake plugin (V1.0.0).
the Setup is Win11, AMD Ryzen 7 5700X, Radeon 6700XT, ASRock X570 Phantom Gaming 4.

![image](https://user-images.githubusercontent.com/115881181/229353009-e34159bf-9982-466a-86d1-655562d1a86b.png)

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11132191/log.txt)

please help.
Thanks 
BR Dirk

**Comment by Rem0o** [comment]
Have you gone into right-click -> properties on the dll and unlocked it after you downloaded?

**Comment by scorpiontzr** [comment]
No i didn't and afterwards it works
many thanks
