### ISSUE TITLE
Issues with GPU pairing

### ISSUE THREAD

**Issue by Kolo4204** [Rem0o/FanControl.Releases#1692]
Hey

Every fan seems to be paired except for my GPU. Is this a compatibility issue?

![Schermafbeelding 2023-04-02 162626](https://user-images.githubusercontent.com/129674005/229359475-ae51365f-a4b2-4a88-8669-28fcdfedc659.png)
![Schermafbeelding 2023-04-02 162642](https://user-images.githubusercontent.com/129674005/229359483-e556de68-3941-4a42-8129-6613dbab60d1.png)

**Comment by Rem0o** [comment]
>  Is this a compatibility issue?

Seems like it, or you got something like Afterburner controlling the fan. 10XX series normally have no issues.

**Comment by Kolo4204** [comment]
Thanks for you reply 

I don’t have anything like MSI Afterburner. Fancontrol is the only software I have installed.

**Comment by Rem0o** [comment]
Make sure your drivers are up to date also.
