### ISSUE TITLE
Issue with 4080 triple fan control and detection.

### ISSUE THREAD

**Issue by ponduzn** [Rem0o/FanControl.Releases#1695]
I have the gainward RTX 4080 phantom card, fan control only seems to detect 2 out of 3 fans(not sure if two are paired into one control?).

And i seem unable to control the fans that are detected effectively, i can manually override at static speeds, but with curve it wont go below 30% speed, and sometimes it revs up and down fast even without temp changes, like from 30-100%, over and over until i deactivate the controls.

When fans according to curve should be below 30% it throws the "?" next to the speed, saying "A discrepancy was detected between the control and its target value, and force apply doesnt do anything.

This is with or without any other fan control tools, but i have had to disable gpu control in "fan control" and use "expertool" to control gpu curves at this moment since it doesnt work.

Specs :
Asus z790 prime a wifi
I7 13700k
Gainward RTX 4080 phantom
![FanControl_eGw1GDMDsL](https://user-images.githubusercontent.com/11321675/229718669-8df4f171-7d13-4a95-a9fb-4296cb8cec3b.png)

**Comment by Rem0o** [comment]
Sub-30% isn't available on newer Nvidia cards. You can use the 0% override in sensor settings to get back 0 RPM, but you can't do [1-29]%.

**Comment by nomnom14** [comment]
RTX 40 Series have only 2 Fan Control Headers (like on FE Cards), so 2 Fans are paired.

**Comment by ponduzn** [comment]
> Sub-30% isn't available on newer Nvidia cards. You can use the 0% override in sensor settings to get back 0 RPM, but you can't do [1-29]%.

Thanks, that explains that! I'd rather just let it be at 30% rpm when idling etc. then. 

Still i experience a weird issue with my card, and its seemingly unrelated to your software or any other fan control software for that matter, as it happens without any, and just default card curve,

Where my fans ramp up to crazy speeds, sometimes seemingly random(after its been triggered by temp, even at 30c), and sometimes its at specific temperatures.

In my case, whether im using fixed fan speeds or curves, at 57c  GPU temp, or 70c GPU hotspot(according to HWmonitor), then fans go to around 120k rpm according to Fan Control( i doubt that number is true, but its at least 100% fan speed).

I read a reddit post, where i also put my results, where people with other brand 40 series nvidia users have reported the same issue, but it seems random what the fix is, and their fixes does not work for me.
I have sent Gainward a email about this.

Do you have any idea about this issue?

**Comment by ponduzn** [comment]
> RTX 40 Series have only 2 Fan Control Headers (like on FE Cards), so 2 Fans are paired.

Makes sense, thanks for clarifying!

**Comment by ProxSym** [comment]
Hey was wondering if anyone had a fix with the gpu fans spinning while idle just recently downloaded fan control everything else has been fine but its just that my gpu fans are spinning even while idle usually my 4080 would stop spinning when idle i tried fan curve and all that to see if i could set them to stop spinning when at idle temps but still nothing
