### ISSUE TITLE
Can't control fans with curve

### ISSUE THREAD

**Issue by BigbyErisTech** [Rem0o/FanControl.Releases#1696]
After a PC crash my installation of Fan Control became corrupted, and I've just created a fresh instal from the latest download. On my previous install, I was able to control my Silent Wings 4 Pro fans with fan curves, however the option no longer seems to appear.

The option to use a fan curve does appear for my pump however, which is an EK FLT 80

No BIOS settings have changed since previous installation was working earlier today.

![image](https://user-images.githubusercontent.com/117084602/229752846-b5e389d0-0b8c-4ff9-a2a2-dd3a0501a42c.png)

**Comment by Rem0o** [comment]
What do you mean the option doesn't appear? Just three dot menu the control card you want and untick manual control.

**Comment by skorpion8909** [comment]
I have the same problem. Am I doing something wrong or is a bug or an unknown feature?
The "Manual Controle" button is there but cannot be clicked.
![image](https://github.com/Rem0o/FanControl.Releases/assets/25708126/e02278b4-c93d-4b4f-b34d-d8f934ba409f)

**Comment by Rem0o** [comment]
turn the toggle on first.
