### ISSUE TITLE
V153 broke GPU-Z plugin

### ISSUE THREAD

**Issue by lutzgooren** [Rem0o/FanControl.Releases#1697]
As mentioned in the title, the latest update V153 broke the GPU-Z plugin: https://github.com/vision57/FanControl.GPU-Z
Rolling back to V152 fixed the issue.

**Comment by Rem0o** [comment]
How does it break it? Shouldn't the issue be raised in that repo?

Try and disable InpOut in sensor settings in V153, it's the only significant change.
