### ISSUE TITLE
One case fan does not respond

### ISSUE THREAD

**Issue by DoctorEw** [Rem0o/FanControl.Releases#1699]
Fan Control (correctly) detects 4 devices on my pc, 2 case fans, the CPU fan and my GPU. I have the GPU control turned off and let it handle itself for now (if anyone has recommendations for a fan curve on a GTX 1080 I'm all ears). The problem I'm running into is that one of the case fans does not respond to any controls by the Fan Control software. I can view the RPM but it just spins at some preset value of ~70% max. Both case fans are the same brand (Fractal Design GP-12) so it's odd to me that one works and the other does not. If I change the fan curves in the BIOS the bad fan will respond to temperature swings appropriately but nothing in Fan Control. Even setting a default curve to be 0%, 50% or 100% and it just keeps spinning at 70% speed. I've tried re-running the setup wizard but that didn't change anything. Any ideas on how to solve? It's not the end of the world since the fan is operating but I would like to get noise levels down when the PC is idle.

**Comment by Rem0o** [comment]
The fan itself doesn't matter, it's all a matter of where you plugged it.  Support may be hit and miss on different headers for a given motherboard.

You can try different headers, or make sure that header has no specific setting applied to it in the BIOS.

**Comment by DoctorEw** [comment]
Just adding a comment because I had to dig into my PC the other day so I tried swapping fan headers on the fan that wasn't responding to Fan Control software. Swapping headers solved my problem completely `¯\_(ツ)_/¯`

For more info, the "broken" header (fan still worked, just FC couldn't adjust voltage so it was steady state at whatever default speed BIOS had) was on fan header SYS_FAN4 (middle right edge when looking at the board), and now it is on fan header SYS_FAN2 (bottom edge, on the left half), on a MSI B450 Tomahawk.
