### ISSUE TITLE
Support for GDDR6X Memory Junction sensor found in RTX 30xx cards?

### ISSUE THREAD

**Issue by joakimlemb** [Rem0o/FanControl.Releases#170]
Is it possible to get support for the GDDR6X Memory Junction sensor found in RTX 30xx series cards in FanControl?

It was recently added to HWinfo: https://www.hwinfo.com/forum/threads/hwinfo-v6-42-released.7016/

**Comment by Rem0o** [comment]
None of my Nvidia API seem to support it as of now.  As soon as it is available, it will follow through. HWInfo SDK is a commercial product, so it isn't of any help here.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.HWInfo

**Comment by dementeb** [comment]
> https://github.com/Rem0o/FanControl.HWInfo

Please help, how to build this?

**Comment by Rem0o** [comment]
@dementeb  added appveyor build with artifacts, look up the README.

**Comment by vision57** [comment]
Hey guys, I have developed a GPU-Z wrapper plugin for FanControl, without 12-hours limit of HWiNFO.

https://github.com/vision57/FanControl.GPU-Z
