### ISSUE TITLE
AIO pump greyed out but reads rpm on speed card

### ISSUE THREAD

**Issue by Trae132** [Rem0o/FanControl.Releases#1700]
AIO pump greyed out, its nzxt kraken X.  I swapped to pwm in bios.  It says cant detect on initial setup of app.  There is a speed card for it reading accurate rpm though?  I have no other pump control software however I did try starting cam before and after fan control launch based on another topic here and nothing changes.  I can control the pump in cam.  

Maximus X hero
i7-8700k
gtx-1080ti
win 10 64

**Comment by Rem0o** [comment]
Greyed out means after the setup the software didn't detect any response from the control of the pump. Basically means either:

* Not/badly supported
* Something else keeps control

**Comment by nomnom14** [comment]
Kraken X offers no PWM Control over BIOS/Motherboard headers so you have to work with CAM/Internal USB

**Comment by Trae132** [comment]
Thanks for clarifying, I had my hopes up of having one single app to control all cooling and it was gonna be this one.  Any idea what happens if I dont use cam at all?  The pump rpm shows in the speed card and its the same as what cam sets it to by default even if cam hasnt been launched yet this boot.  Either way this Fan Control app is a gem im not dumping this.
