### ISSUE TITLE
0% Mode not working on 4070Ti (Inno3D / Nvidia Reference PCB)

### ISSUE THREAD

**Issue by nomnom14** [Rem0o/FanControl.Releases#1702]
First i really want to say how much i appreciate your Software - being able to control Case Fans based on GPU and CPU Temperatures at the same time is huge for SFF Cases!

However i have a small issue: I cannot get the Fans on my 4070Ti to stop. Fan curve is set to 0% and Nvidia 0% workaround is activated.

Is it possible that Nvidia Drivers block fans from stopping while the Card is in High Performance mode? I have to leave it activated due to a compatibility issue with my Asus Motherboard.

Inno3D 4070Ti
Fancontrol 153
Win 11 Pro
Nvidia Studio Driver 528.49

**Comment by nomnom14** [comment]
Small side note: When activating 0% Mode GPU Fans will be locked to 38% or higher. Without 0% Mode they go as low as 30% PWM.

**Comment by Rem0o** [comment]
> Is it possible that Nvidia Drivers block fans from stopping while the Card is in High Performance mode

I do believe these modes will have an impact.

**Comment by ctimlock** [comment]
I've got the same card and had the same issue - is resolved by setting the start and stop % to 30 for the GPU fans.

![image](https://user-images.githubusercontent.com/10769351/230749576-95d77c89-c549-45d5-a03d-29d5e90324b2.png)

This is also recommended in the tooltip for the 0% override, FYI.
![image](https://user-images.githubusercontent.com/10769351/230749611-8acbf362-8c3f-49fe-974f-5107005584e6.png)

**Comment by ctimlock** [comment]
I actually noticed this today - I believe that the fans need to get above a certain % before they will allow for 0% mode...

My curve wasn't applying the 0% correctly, so I enabled manual control - still wouldn't set 0%. Set them to 50% for a few seconds, then back to 0%, and they turned off!

**Comment by Rem0o** [comment]
@ctimlock  answered the issue properly. 

Closing.
