### ISSUE TITLE
Expecting 84 sensors found 61...

### ISSUE THREAD

**Issue by SamAresOfficial** [Rem0o/FanControl.Releases#1703]
Not entirely sure if those numbers are accurate or not, but literally every time I start my computer I get this error popup which quickly disappears after 10-15 seconds, but then leaves the application in the foreground so I have to close it manually. My main issue with this is that I just want the program to stay minimized unless I want to check something or there's an update, but I have to close it every time I start. I extended the start delay with no fix to the issue (it's currently at 60sec.) I have been using fan control for months now, but this is the only issue I've had, love the software otherwise.

Checking my log file I found this, which is repeated many times in it among different dates.

12/4/2022 2:23:58 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
12/4/2022 2:23:58 AM: NvAPI failed. A complete refresh is required.

I have a Gigabyte Gaming OC 4090, if that helps.

**Comment by Rem0o** [comment]
You could swap the other GPU provider, see if it cause less issues.  Untick the NVapiwrapper one in Sensor settings, and leave GPU ticked on the LHM side.  You'll have to refill the GPU related stuff, but it might be worth a shot.
