### ISSUE TITLE
Is it possible to add fan control on the server motherboard（such as supermicro motherboard with bmc/ipmi）

### ISSUE THREAD

**Issue by leonaiverson** [Rem0o/FanControl.Releases#1705]
now the software is able to read temperature of device on supermicro motherboard,but it can't read speed status of the fans on the motherboard.in my situation,it only  got gpu fans and miss all the system fans and chassis fans .  
i searched the problem ,and i got that  the server motherboard circuit is different from Consumer motherboard,and it control fan speed via bmc device which maybe is not support in this software.
so Is it possible to add fan control on the server motherboard via bmc ?

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility in the README.
