### ISSUE TITLE
Easy Anti-Cheat Security Violation

### ISSUE THREAD

**Issue by jimmyswany** [Rem0o/FanControl.Releases#1706]
Game Security Violation Detected (#0000000D)
[FanControl.exe]

**Comment by Amon-2** [comment]
Same issue, pretty reproduceable, when playing Warthunder.

**Comment by druidbruce** [comment]
same issue here, was playing BDO(black desert), happened 3 times this week now, 2 times even when im afk.

**Comment by Rem0o** [comment]
Untick this: 
![image](https://user-images.githubusercontent.com/14118956/230940255-0f618a6f-12ef-46cf-965d-5e06a3629bc6.png)

**Comment by Amon-2** [comment]
Thanks, will try it out! 

Absolutely in love with the tool otherwise, it has never been so easy to get a custom loop absolutely quiet!

**Comment by druidbruce** [comment]
Thanks for the solution, but would you say this is something anti-cheat should not be detecting where we should also report to them?

**Comment by jimmyswany** [comment]
Thank you @Rem0o, I haven't had any issues after changing that setting.
