### ISSUE TITLE
Corsair AX860i PSU not being detected

### ISSUE THREAD

**Issue by RyanThaDude** [Rem0o/FanControl.Releases#1710]
I'm trying to completely rid of iCUE and so far everything on my Gigabyte X760 with the Corsair Commander Core and RTX 2060 is being detected and controlled perfectly except for the AX860i PSU. Corsair PSU is checked in the sensor settings but to no avail. Is the AX860i not supported or is there something else I need to do?

**Comment by Rem0o** [comment]
Not all corsair PSUs are supported.:

See https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Psu/Corsair/CorsairPsuGroup.cs line 18 to 31

**Comment by RyanThaDude** [comment]
Yup, mine's not on that list. FWIW I decided to add the device ID (0x1c00) to that list and build it myself but it still didn't find it. My guess is that the HXi and RMi series are supported and not the AXi. The AX1600i is mentioned but is commented out probably for reasons.

**Comment by Rem0o** [comment]
^ nice try. 

Since I can't help you out on that front from FanControl's perspective, will close this.

**Comment by EvanMulawski** [comment]
@RyanThaDude I just added support for AXi-series PSUs in the CorsairLink plugin: https://github.com/EvanMulawski/FanControl.CorsairLink

**Comment by RyanThaDude** [comment]
Works perfectly. Thanks!
