### ISSUE TITLE
REQ: Config Backup

### ISSUE THREAD

**Issue by quadcom** [Rem0o/FanControl.Releases#1712]
Hey guys,

I thought it would be great if we could set a backup DIR in the config (optionally of course). Anytime a change to the setup happens, and it's saved to the JSON file, a backup is saved in that set DIR.

It would save me -and others from going into the program folder and copying the JSON manually.

**Comment by SimonZerafa** [comment]
You can save twice using the "Save configuration as" option and the last saved file is the one which becomes the default automatically.

It might be nice if this was automated so that changes were recorded in a backup folder within FanControl but this does workaround this issue for now.
