### ISSUE TITLE
[question/feat req] is it possible to correct detected max fan speed ?

### ISSUE THREAD

**Issue by msoltyspl** [Rem0o/FanControl.Releases#1713]
**Describe the bug**
Not a bug, even my sensors in bios show incorrect speed (but evga's own soft shows it correctly - likely via its usb connection).

Basically my AIO (EVGA CLC 280) fans are connected to "CPU fan header" on "X570 AORUS PRO (rev. 1.0)". At full speed (which is ear crushing 2200something as per EVGA's soft) is shown in bios or fancontrol at 1500. I'm not really sure why - but that's besides the point.

But to workaround an issue like that - it would be superb feat if a fan sensor could be manually adjusted in such case (perhaps it's already possible to set it directly in json config ?).

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Nope

**Relevant hardware specs and setup**

X570 AORUS PRO (rev. 1.0), bios F37a
EVGA CLC 280 (connected to primary cpu fan header, set to full speed in bios)

**Comment by Rem0o** [comment]
Are you sure you are reading the right RPM sensor?  Maybe the matching between control/speed cards went wrong.

**Comment by msoltyspl** [comment]
Yea, the sensor is right - the built-in firmware/soft of this AIO (controlled via usb) - which defaults internally to some automatic/curve behavior is probably responsible for this reading (though why later under windows the sensor still showed lower speed despite the fan being pushed to the max speed manually - idk).

Yesterday I swapped AIO to deepcool's lt720 - which doesn't have any internal controller - everything works fine with it (and on the same fan connectors as the earlier evga).

This issue can probably be closed as this was clearly a corner case, and I'm not sure how much "fix sensor max speed" feature is even of any use beside such corner cases.

And thanks for amazing software.
