### ISSUE TITLE
[Question] FanControl 4.8 vs 7.0 ?

### ISSUE THREAD

**Issue by Rexadev** [Rem0o/FanControl.Releases#1716]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V147 - Both released in v417

[FanControl_net_4_8](https://github.com/Rem0o/FanControl.Releases/releases/download/V147/FanControl_net_4_8.zip)

[FanControl_net_7_0](https://github.com/Rem0o/FanControl.Releases/releases/download/V147/FanControl_net_7_0.zip)

**Comment by Rem0o** [comment]
It's the version of .NET used to compile the app.  

4.8 is legacy, widely compatible, while 7.0 is the latest version, requires a download of the framework.
