### ISSUE TITLE
(GPU) fan keeps oscillating between Start % and Stop %

### ISSUE THREAD

**Issue by sctanf** [Rem0o/FanControl.Releases#172]
My GPU fan curve will go well below the Stop % but sometimes the fan never stops, instead it keeps starting and falling to the Stop %, where it will go to 0% and immediately ramp to the Start %. Eventually it will stay at 0% but not after repeating this many times.

**Comment by Rem0o** [comment]
Screenshot of your expanded GPU control card and fan curve used please.

**Comment by sctanf** [comment]
Here:
![GPU](https://user-images.githubusercontent.com/36978460/108645626-19581580-7479-11eb-8091-30a735140d60.png)

**Comment by sctanf** [comment]
I captured a graph if it helps:
![graph](https://user-images.githubusercontent.com/36978460/108645946-0560e380-747a-11eb-9e78-6b320a5b1657.png)
In Fan Control the target speed is well below 20% at this point.

**Comment by Rem0o** [comment]
I was able to reproduce the issue, but 2 things: 

Why are your step up and down % for your GPU so slow?
Why did you set start and stop% that don't match the actual start and stop of your GPU?

These precise conditions are the only way I could reproduce that behavior.

**Comment by sctanf** [comment]
Essentially, below 27% the fan is useless and if I don't get it spinning at the start the fan malfunctions.

The gpu uses the fan rpm to control fan power, but whatever they use is very poorly calibrated. It oscillates around the target rpm heavily before reaching a steady state. It is also very aggressive at stopping the fan if the rpm drops too low. If it drops below 900 rpm the fan stops, and then immediately spins up, repeatedly.

The high Start % guarantees the fan rpm won't drop too low at the start. The slow step size and high Stop % prevents the rpm dropping too rapidly.

**Comment by Rem0o** [comment]
Just curious, try the following:

Three dot menu of the GPU control card, and detect the start and stop % that way. Then, set 5% step up and down. Finally, set the min speed of your Linear curve to Start% - 1, Min temp to 10 deg above your typical idle, and whatever max temp/speed you like. How is that working out?

**Comment by sctanf** [comment]
Auto got me 12% Start %
![start](https://user-images.githubusercontent.com/36978460/108652442-ccc90600-7489-11eb-8738-a2be0b569fcf.png)
and 15% Stop %
![stop](https://user-images.githubusercontent.com/36978460/108652441-ccc90600-7489-11eb-9c0a-83bbd6123a31.png)
Running idle:
![test](https://user-images.githubusercontent.com/36978460/108652440-cc306f80-7489-11eb-9c99-84eb38db7903.png)
The start % is stuck at 40% but I highly doubt setting it to 12% like it told me would have helped.

**Comment by sctanf** [comment]
Of course under load it is stable, the fan speed would be around 40-45% and no sudden stopping or anything.

**Comment by Rem0o** [comment]
Wait, how can your start% be lower than your stop%? That doesn't make any sense.

**Comment by sctanf** [comment]
It isn't, the 1 second response time of Fan Control means it can't see all the actual fan starts and stops.

**Comment by sctanf** [comment]
The graphs are on a update period of 100msec.

**Comment by Rem0o** [comment]
You've officially won the weirdest running GPU fan of the year, never seen anything like it. Anyway, I got to patch your specific case with the configuration you mentioned with your screenshot.  In the mean time of a release, try setting your step down% a bit higher than 0.5%.

**Comment by sctanf** [comment]
Many other fans (not necessarily in computers) also have control via rpm, my gpu just happens to have a really bad implementation of it. Either way, thanks, I'll set a higher step for now.

**Comment by sctanf** [comment]
I raised the Stop % too and it seems a little better.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V69
