### ISSUE TITLE
Any way to get CAM and liquidctl to play nice?

### ISSUE THREAD

**Issue by Trae132** [Rem0o/FanControl.Releases#1727]
I cant use them both together, I unfortunately have to run CAM for the lcd screen on the pump to work.  I tried the liquidctl plugin which would be so perfect to use in Fan Control but I cant figure out if theres a way to get them to work together.  If I launch cam first it says no sensors detected, if I run cam after FC launches then cam wont detect or run my screen.  Anyone figured this out?  I have Kraken Z73 latest FC latest CAM windows 10

**Comment by Rem0o** [comment]
Please transfer to the plugin's repo.
