### ISSUE TITLE
Easy Anti-Cheat - Game Security Violation Detected (#0000000D) [FanControl.exe]

### ISSUE THREAD

**Issue by Cantejito** [Rem0o/FanControl.Releases#1730]
**Describe the bug**
Was playing BattleBit Remastered and I got kicked by Easy Anti-Cheat with the following info:
![Screenshot_1](https://user-images.githubusercontent.com/125479909/233801764-7ab1536c-3fdd-44aa-be7e-9993d79afa26.png)
The kick was after hours of playing and is the first time it happend.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11302097/log.txt)

**Relevant hardware specs and setup**
CPU: Ryzen 5800X
MBO: MSI B550 GAMING PLUS
GPU: NVIDIA RTX 3060 Ti

**Comment by MaximeTasset** [comment]
I have the same issue:
**Relevant hardware specs and setup**
CPU: Ryzen 3800X
MBO: MPG X570 GAMING PLUS
GPU: NVIDIA GTX 1070

**Comment by Rem0o** [comment]
Turn off InpOut in sensor settings if it's on.

**Comment by Cantejito** [comment]
Wasn't that added on the last update? If so, wouldn't it be better for have it off by default? Or it's critical for some functions? Speaking from the absolute ignorance.

**Comment by Rem0o** [comment]
I made it opt-out at first, latest update made it opt-in instead.

**Comment by Cantejito** [comment]
Oh, that explains the sudden errors. Nothing more to say, closing post.
