### ISSUE TITLE
Fan Control not detecting GPU temperature

### ISSUE THREAD

**Issue by tandpastatester** [Rem0o/FanControl.Releases#1734]
Fan Control shows my GPU temp as a 30 °C, and as far I noticed so far it's fixed at that temperature regardless of stress or activities. I don't know where this temperature is coming from, but this is not my actual GPU temperature:
![NVIDIA_Share_5cQTBTgjw0](https://user-images.githubusercontent.com/26697672/234261683-aae13b52-1866-48f9-974b-f95f4030366c.png)

**Relevant hardware specs and setup**
ASUS ROG STRIX Z370-I GAMING
Intel Core i7-8700K
NVIDIA GeForce GTX 1070 PCIe v3.0 x16 (8.0 GT/s) @ x16 (8.0 GT/s)

**Comment by UrmasK222** [comment]
Not sure about the hardware compatibility but meanwhile, a workaround might help you.
You can use https://github.com/Rem0o/FanControl.HWInfo to import sensor data.
I use this to import RAM temps.
br
Urmas

**Comment by Rem0o** [comment]
Any log.txt?

**Comment by tandpastatester** [comment]
> Any log.txt?

Hi Rem0o, I was able to fix it by backing up my FanControl installation and reinstalling it. No idea what the problem was, if you are still curious, I can send the log file that was in my old installation. Let me know, otherwise feel free to close the ticket.

Cheers!
