### ISSUE TITLE
FAQ: Is it capable of removing numeric limits (PWM/voltage) when controlling fan speed

### ISSUE THREAD

**Issue by yumeyao** [Rem0o/FanControl.Releases#174]
not having time to try it yet but just curious (And I think this question might be considered as a FAQ):

- Some motherboards manufacturers (namely ASUS) limits the lowest possible PWM/voltage to a relatively high number. (I guess that's because the manufacturer thinks a user may 'mistakenly' set a low value which causes the fan stop running and creating 'annoying' support tickets....) Also the high temperature cap (for full fan speed) is limited to a very low number (70C).

  But obviously it's the BIOS that has such limitations, not the SuperI/O chip, So I wonder if this software can bypass these limitations?

- Also some graphic cards have such limitations as well so you can't (adjust to even) lower the fan speed on low load. A traditional way to fix this is modding the vBIOS. It would be a great favor if this software can do the job.

**Comment by Rem0o** [comment]
1) Not AFAIK: for eg my board limits my CPU header to 17%. I can set it to 0%, but the fan speed won't actually go below 17% .

2) Again, this ain't magic. Those limitations are low-level, and this is using a driver to talk to the components, so no.
