### ISSUE TITLE
SuperMicro Missing System Fans

### ISSUE THREAD

**Issue by ThePieMonster** [Rem0o/FanControl.Releases#1741]
Unsure if this is a issue with LibreHardwareMonitor or this UI tool.

Either way, there should be two fans showing in the UI. 

<img width="627" alt="image" src="https://user-images.githubusercontent.com/11359134/235374190-fe45db0c-fa3b-49b6-8f33-eeb9dbdba82d.png">

**Comment by Alexikik** [comment]
I have the same problem on my laptop, works fine with ArgusMonitor

**Comment by Ekristoffe** [comment]
hey guys, can you try this soft and see if the fan are shown ?
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
it may be just the library used doesn't support the fan yet ...

**Comment by Rem0o** [comment]
@Ekristoffe  ^ this
