### ISSUE TITLE
No longer able to update

### ISSUE THREAD

**Issue by thefunkygibbon** [Rem0o/FanControl.Releases#1743]
Since a few builds ago, it's not able to update itself despite telling me there are updates available. 

Fan Control Updater

Downloading Fan Control v155...
A Fan Control instance was opened, the program was closed.
Extracting archive...
Validating checksums...
ERROR: Checksum validation failed.
ERROR: Actual: f36c7c0648af53b09a00580dfc7cdd71 | Expected: 89138BA33B8E3ABBF764A6F03ADE5665
Restarting Fan Control...

Then it restarts but with the same V154.
Think its done this since about V152 for me. 
Happy to provide all the details of my PC if needs be.   Using latest Windows 11 22H2 Release

**Comment by gaspardleon** [comment]
same here 
![image](https://user-images.githubusercontent.com/30315792/235803770-d2bd9763-bc09-4a4e-b636-a196983eb51e.png)
I get that then again asked to update to 155 over and over again...

I'm on the dotnet 7 version of the program if that makes any difference

**Comment by Rem0o** [comment]
There is sometimes a desync between the different files that make the update on the server when I just release an update.

 Just tested right now, both net4.8 and net7 should work fine.

**Comment by Rem0o** [comment]
Are you using an old version of updater.exe? Make sure to use the latest one from this repo, or trigger the update from FanControl itself, as it will download the latest updater the same way.

**Comment by thefunkygibbon** [comment]
Well yes. Upgrading manually by downloading extracting and overwriting is clearly going to work.  The issue is with auto updating .  
It may well be something to do with a desync as previously mentioned though as it was fine the following day when I tried to auto update

**Comment by biboxay321** [comment]
> Well yes. Upgrading manually by downloading extracting and overwriting is clearly going to work. The issue is with auto updating . It may well be something to do with a desync as previously mentioned though as it was fine the following day when I tried to auto update

Well in my case, I still stuck with that up until 30 mins ago before I do the overwriting step. Mine seem like to stuck forever with 154 so I did I as a last resort.

**Comment by gaspardleon** [comment]
So I manually upgraded to 156...

Today I got a message "A new version is available: 157 (current is 156)"

so I click Update and again:

![image](https://github.com/Rem0o/FanControl.Releases/assets/30315792/8cf57208-3eeb-4dbc-bf87-6b9f3b28e1d4)

**Comment by biboxay321** [comment]
> So I manually upgraded to 156...
> 
> Today I got a message "A new version is available: 157 (current is 156)"
> 
> so I click Update and again:
> 
> ![image](https://user-images.githubusercontent.com/30315792/238495796-8cf57208-3eeb-4dbc-bf87-6b9f3b28e1d4.png)
> 
> before 154 every update was quick and painless.
> 
> any trick to getting autoupdate working again?

I just did upgrade from 156 to 157 without any issue.

**Comment by Rem0o** [comment]
I suspect you are using an Updater.exe manually without going through the one FanControl uses?

Otherwise, do a quick search for updater.exe in your FanControl folder see if there are multiple instances, and delete all of them.

@gaspardleon

**Comment by gaspardleon** [comment]
> 



> I suspect you are using an Updater.exe manually without going through the one FanControl uses?
> 
> Otherwise, do a quick search for updater.exe in your FanControl folder see if there are multiple instances, and delete all of them.
> 
> @gaspardleon

I always click the link in the program when it prompts me, never manually ran updater.exe
![image](https://github.com/Rem0o/FanControl.Releases/assets/30315792/a61af2e9-22d8-4f5e-9cfd-3182ca9e5200)

I will delete updater.exe and see if that makes any difference

**Comment by gaspardleon** [comment]
I tried deleting Updater.exe

No difference:

Here is an unlisted Youtube screencast I made: https://youtu.be/gUT8Sxm-PaE

**Comment by biboxay321** [comment]
> I tried deleting Updater.exe
> 
> No difference:
> 
> Here is an unlisted Youtube screencast I made: https://youtu.be/gUT8Sxm-PaE

Please try manual update one more time. This time you should delete everything in the older version's folder minus the one configs file you want to move to the newer version. At least that's what I did and I got no problem updating from 156 to 157.

**Comment by biboxay321** [comment]
> > Please try manual update one more time. This time you should delete everything in the older version's folder minus the one configs file you want to move to the newer version. At least that's what I did and I got no problem updating from 156 to 157.
> 
> Manual update would be no problem... but my issue is that before v154 Auto-update worked great... and it's so easy when it works

What I meant is to do a clean install and let's see if the problem persists when it's time for the 159 update.

**Comment by gaspardleon** [comment]
No need... I tried again today using the built in updater without changing anything and it now suddenly worked.

Good work on fixing the issue - thanks

**Comment by gaspardleon** [comment]
well this continued for the last few days while it was prompting me to update to 159... then, this morning, I clicked update yet again and it finally worked.

I wonder if the update notification prompt and the actual update could be tied together so they pull from the same data, so it actually always works when it asks to be updated.

Glad it finally works, will report back if it fails next time :)

**Comment by thefunkygibbon** [comment]
I'm giving up.  you guys seriously need to re-work how these updates work.  I've been trying to update every few days now since 155, giving it a few days grace after release so that "github can get synced" or whatnot.   still no.  having to manually update.  there has to be a simpler way to update?

**Comment by Rem0o** [comment]
@thefunkygibbon 

The update flow works for tens of thousand of people at every update, but somehow fails for a few.

Flow is: 
1) FanControl downloads https://github.com/Rem0o/FanControl.Releases/blob/master/version.json and look at the version number.
2) If version number is greater than its own version, prompt for download
3) Download https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip
4) Unzip, compute hash from FanControl.exe/FanControl.dll and compares to the one in version.json
5) done

In your case, problem seems to be at 3) and 4).  Is the "expected" hash printed in the console the same as the one here? https://github.com/Rem0o/FanControl.Releases/blob/master/version.json

My only guess is that somehow the extracting of the zip onto your folder fails for some reason, but somehow it doesn't crash at that point, and goes through the checksum validation with the old exe in place.

**Comment by gaspardleon** [comment]
> @thefunkygibbon
> 
> The update flow works for tens of thousand of people at every update, but somehow fails for a few.
> 
> Flow is:
> 
>     1. FanControl downloads https://github.com/Rem0o/FanControl.Releases/blob/master/version.json and look at the version number.
> 
>     2. If version number is greater than its own version, prompt for download
> 
>     3. Download https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip
> 
>     4. Unzip, compute hash from FanControl.exe/FanControl.dll and compares to the one in version.json
> 
>     5. done
> 
> 
> In your case, problem seems to be at 3) and 4). Is the "expected" hash printed in the console the same as the one here? https://github.com/Rem0o/FanControl.Releases/blob/master/version.json
> 
> My only guess is that somehow the extracting of the zip onto your folder fails for some reason, but somehow it doesn't crash at that point, and goes through the checksum validation with the old exe in place.

I can guess at a few potential issues:
- no error when unable to overwrite old file.
- possible to download old file? caching?

I'll continue to monitor the situation... my program is currently up-to-date, but when 160 comes out, we'll see what happens
If I have another issue I can compare the hash displayed to the one in version.json

Cheers

**Comment by gaspardleon** [comment]
Excellent, so a popup for v160 this morning:
![popup to v160](https://github.com/Rem0o/FanControl.Releases/assets/30315792/3099be99-d021-4507-994f-47276b2ac1ba)

which results in an actual error message:
![failed Extract](https://github.com/Rem0o/FanControl.Releases/assets/30315792/8dff0b99-3418-4acf-9cc3-3830ef7c42d5)

Next, I will use process explorer to see which program is holding onto Autofac.dll and hopefully that will resolve the mystery.

**Comment by gaspardleon** [comment]
While trying to capture which program had it locked, the update just succeeded... oh well just try it a few times I guess

**Comment by thefunkygibbon** [comment]
Fetching latest release:
Response status code does not indicate success: 403 (rate limit exceeded).

I've not done anything with github (downloaded/uploaded) in the last few days, so i'm guessing its your end and not mine. 

I'm giving up.   I'm not getting enough use of the app at all to justify all these weird and needlessly frustrating updating issues.

**Comment by Rem0o** [comment]
@thefunkygibbon 

That's odd.   I don't see how that rate limit would be on my end, otherwise tens of thousands would be 403ed the same way you are, which is not the case.   Github public API has a rate limiter, but you would have to get a high request volume from most likely other sources to get that one request to fail this way.

**Comment by gaspardleon** [comment]
> Excellent, so a popup for v160 this morning: [snip]
> 
> which results in an actual error message: ![failed Extract](https://user-images.githubusercontent.com/30315792/246270400-8dff0b99-3418-4acf-9cc3-3830ef7c42d5.png)
> 
> Next, I will use process explorer to see which program is holding onto Autofac.dll and hopefully that will resolve the mystery.

Same error (can't overwrite Autofac.dll) trying to go from 160 -> 161...

Fix / Workaround was to run the Updater.exe by itself instead of clicking the nice update button in the GUI.

For whatever reason even though it says it's closing the program the system still locks Autofac.dll (probably only for a very short time)

Running Updater.exe directly with FanControl already closed works fine, so that's my current work-around

**Comment by gaspardleon** [comment]
I'm hopeful.

The latest update (to 164) was a single click affair just like the old days, no file lock issue, Yay

**Comment by Tommy0x00007D1** [comment]
I had this issue or similar with v179, where it found new update but after "completing" the update it was still on old version and for me it was probably a permission problem, because I ran the file "Updater.exe" as admin and it worked.

**Comment by gaspardleon** [comment]
just a comment the latest update (to 185) actually worked normally... no more locked Autofac.dll! yay

so for me... currently at least this one appears to be fixed
