### ISSUE TITLE
REQ: Day/Night profiles

### ISSUE THREAD

**Issue by jonylentzmc** [Rem0o/FanControl.Releases#1748]
Hey! I've been using fan control for a while and it is an amazing software!

I though about a feature that could be great to have: 2 or more different "profiles" that saved the fan curves and where automatically  applied according to the time of the day so you could have a profile that runs the fans a bit higher during the day and a profile that is silent for nightime...

**Comment by Rem0o** [comment]
You could already do it with scheduled task in windows. Simply run a task at whatever time of the day
```
FanControl.exe --config daytime.json 
```

and another at night
```
FanControl.exe --config nighttime.json 
```

**Comment by jonylentzmc** [comment]
I didn't knew that you could parse profiles as an argument for the program
It worked, thank you
