### ISSUE TITLE
Failed sensor detection with the built-in option

### ISSUE THREAD

**Issue by Mrkkkkc** [Rem0o/FanControl.Releases#175]
not sure why this is still happening, attached a log
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6049190/log.txt)

**Comment by Rem0o** [comment]
To get that log, did it failed to restore and then a popup came up to try and refresh?

**Comment by Mrkkkkc** [comment]
yes, but pressing yes gives no response, the software did not refresh the sensor. I had to exit and restart the software manually.
