### ISSUE TITLE
Plugins not loading in + feature request

### ISSUE THREAD

**Issue by Tron-Creeper2** [Rem0o/FanControl.Releases#1754]
### **Describe the bug**

Basically the plugins do not load.
- FanControl.ADLX.dll
- FanControl.AsusWMI.dll

![Screenshot_9](https://user-images.githubusercontent.com/94975374/236640900-196f3585-94c4-4cc8-b0f1-7bddc6770eeb.png)

![Screenshot_10](https://user-images.githubusercontent.com/94975374/236640902-3db66737-a12d-48cc-af63-e31a65dceb33.png)

![Screenshot_16](https://user-images.githubusercontent.com/94975374/236641891-bae34caf-7a8b-4996-9736-9c6e00d39f07.png)

### **Is there a log.txt file next to FanControl.exe with recent date entries?**

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11413100/log.txt) - it was generated in Czech language.

### **Relevant hardware specs and setup**

**MB:** ROG STRIX X570-E GAMING
**CPU:** AMD Ryzen 7 3700X
**GPU 1:** NVIDIA GeForce GT 1030
**GPU 0:** AMD Radeon RX 6700 XT
**RAM:** VENGEANCE RGB PRO 32GB
**CASE fans** - DC controlled (doesn't have PWM control)

### **Feature Request:**

- I'd like to be able to use the column mode and row mode together
basically so I can stack it together

- and maybe some sort of auto-config-transfer?
basically it would read the config file (for ex. previous version - V140) and auto-configures a new config for current version of the FanControl - hope it makes sense

### **Additional screenshots:**

![Screenshot_11](https://user-images.githubusercontent.com/94975374/236640903-cb0dfc6d-b133-49f6-9a38-0a19fd55c269.png)

![Screenshot_12](https://user-images.githubusercontent.com/94975374/236640905-5c981481-5a6e-4b9b-a827-ea8193357420.png)

![Screenshot_13](https://user-images.githubusercontent.com/94975374/236640906-59411bfc-66d5-497c-a028-9b4b2ef56cf7.png)

![Screenshot_14](https://user-images.githubusercontent.com/94975374/236640908-ebc8f3a7-fa7f-4071-a15a-b7dee938643d.png)

![Screenshot_15](https://user-images.githubusercontent.com/94975374/236640910-8115e06a-84f0-432b-9b50-843562bf1fbf.png)

**Comment by Rem0o** [comment]
For the plugin dlls, there might be something strange going on if you try to load FanControl from the OneDrive synced folder.
Try and set your whole installation somewhere in C:/Users or C:/Program Files.

For your feature request, it's not really clear what you want to do with the row and columns. For the auto-transfer thing, I don't quite understand either.  A V140 config should work just fine in the current version.
