### ISSUE TITLE
Hysteresis doesn't seem to work correctly

### ISSUE THREAD

**Issue by Fraser-Watson** [Rem0o/FanControl.Releases#1756]
Let me add some background to this to help you understand my situation

> I have a 4090 FE with 3 x 4k 144Hz monitors.
> 
> During certain light tasks (because the GPU is pushing so many pixels at a high refresh rate), the GPU seems to creep over 51c, which then triggers the Nvidia BIOS to run both fans at 30%, until the card drops to 35c. This cannot be overridden by any fan control application.
> 
> The problem here is that when both fans are running at 30%, they are quite loud, and it is distracting. It also takes quite long time for the GPU to cool all the way down to 35c. 
> 
> I came to the conclusion that stopping the fans at 40c is more realistic and results in the fans turning off much sooner, as the temperature drop is not linear

My solution is to use FanControl to trigger _one_ fan at 50.5c, and the other fan at 53c. So unless the GPU is under actual gaming load, only one fan will spin. 

At 50.5c, _one_ fan will start spinning to prevent the card from reaching 51c (Like I mentioned earlier, if 51c is reached, the Nvidia BIOS will control both fans until the card is below 35c). I have added a hysteresis of 10c, a response time of 3s and checked "Hysteresis only applies on the way down". I would expect the fan to keep spinning until the card reaches 40.5c, and then stop. However, this doesn't happen. It will often stop at around 48c and then start spinning again a few moments later once the temperature rises to 50.5c again, seemingly ignoring the hysteresis.

Am I misunderstanding how this feature works, or is this a bug? It really doesn't make any sense from what I am observing at the moment.

**Comment by Rem0o** [comment]
If you got a graph, hysteresis will be ignored at your leftmost and rightmost points.   Add another point far right and far left if you want your current points to act under hysteresis rules.
