### ISSUE TITLE
Time Average custom sensors showing NaN

### ISSUE THREAD

**Issue by chjohans** [Rem0o/FanControl.Releases#1759]
When starting FanControl, and after performing a "Refresh sensors detection", any custom sensors of the type "Time Average" will show NaN until a number of seconds specified as the "Time" option for the custom sensors has passed since starting FanControl or performing a "Refresh sensors detection". This causes a lot of other issues, and it's quite obvious why this is happening.

It should be an easy fix, just use whatever is the largest of "Time" for the custom sensor or ""time passed since starting FanControl or "Performing a refresh sensors detection" when computing the value of the custom sensor.

**Comment by Rem0o** [comment]
See V156
