### ISSUE TITLE
cracking noises

### ISSUE THREAD

**Issue by Nofgla** [Rem0o/FanControl.Releases#176]
The program causes sound interferences in form of cracking noises. These cracking noises only appear while the program is running. As soon as I close fancontrol they are gone.

For information: I’m using an Amplifier + DAC + Headphones (Schiit Magni 3+ Schiit Modi 3 + HiFiMAN Sundara).

**Comment by Rem0o** [comment]
As soon as you close the UI or the program entirely? If it is the UI, what you are hearing is most likely your GPU. Had the same thing happen when I was gaming when a USB DAC. This has nothing to do with the program itself.

**Comment by Nofgla** [comment]
closing the UI doesn't do anything. the noises only stop if I close the program entirely via the task manager.

**Comment by Rem0o** [comment]
No other program causes this? I don’t really know what to say except you probably got a noisy USB power line. It’s an audio issue, I don’t see how I could fix this.

**Comment by Nofgla** [comment]
yeah, it's definitely this program.  I downloaded fancontrol the day before yesterday and since then the cracking noises appeared and they stopped immediately after I closed the program entirely --> so no other program is the issue. 
I never had this issue before and I have used my pc as source for my dac/amp for ages.
Anyway, I could try to install the program on my laptop to see if I get the same noises there as well.

**Comment by Rem0o** [comment]
FYI, I do use a USB DAC + external amp myself on my PC with FanControl running for over a year, and no noise what-so ever. However, the program does play with PWM outputs, voltage control and other stuff, which is noisy by nature, and can be noisier on some motherboards.

If you can switch from USB to like TOSLINK or Coaxial, that should do the trick.

**Comment by Nofgla** [comment]
Yeah, that's a good idea. I'll consider that.
