### ISSUE TITLE
Editing graph curve - "selected point" temperature will not change

### ISSUE THREAD

**Issue by chjohans** [Rem0o/FanControl.Releases#1760]
See the attached screenshot. Notice how the selected point says that the temp for that point is 8C, when in fact it is 2C. If I move the point it will still say 8C, no matter where I move it. If I type something else as the Temp value for this point and click OK it does not move the point. I can edit the graph by moving the points around just fine.

![image](https://user-images.githubusercontent.com/24390228/236661704-d191b066-55fe-4c92-96fe-0f1658d28512.png)

**Comment by Rem0o** [comment]
could you send me that config file with that graph in it?

**Comment by chjohans** [comment]
Sure, please see the attached config.
[userConfig - CorsairLink.zip](https://github.com/Rem0o/FanControl.Releases/files/11422010/userConfig.-.CorsairLink.zip)

**Comment by Rem0o** [comment]
Found the bug, will fix in the next release, thanks!

Got a new feature in the pipeline to easily import config elements:

![image](https://user-images.githubusercontent.com/14118956/236973381-20b54909-11a1-4185-a7d6-78ca4f1fcd35.png)

Really useful for me to import your stuff in and analyze quickly, and I guess it will be useful generally to share stuff around.

Cheers.

**Comment by chjohans** [comment]
Very cool feature, and thanks @Rem0o for supporting this the way you do!
