### ISSUE TITLE
Excessive CPU usage (~3.3%)

### ISSUE THREAD

**Issue by kotauskas** [Rem0o/FanControl.Releases#1763]
**Describe the bug**
FanControl perpetually sits at roughly 3.3% of CPU usage (with 12 logical processors in the system). A quick peek into Process Hacker reveals that 2 threads are responsible for most of that usage, the TIDs of which change all the time. Frequent termination and spawning of threads can also be seen.

![Process Hacker thread list](https://user-images.githubusercontent.com/28248600/236703192-1cf36da5-5acd-4105-a556-6f35d58af295.png)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Nope.

**Relevant hardware specs and setup**
- CPU: AMD Ryzen 5 3600
- GPU (only device whose fan is being controlled): AMD Radeon RX 6600 (via FanControl.ADLX plugin)

**Comment by Rem0o** [comment]
The ADLX plugin is janky at best. The current implementation was not profiled or optimized yet.  Please move that issue to the ADLX plugin repo.

**Comment by kotauskas** [comment]
I see. My impression was that the thread-spawning shenanigans weren't something the ADLX plugin deliberately did on its own. Disabling it and only controlling the CPU and side fan yields a much more tolerable 0.1% of CPU usage.
