### ISSUE TITLE
Can you make a feature to show changes when its asking to save?

### ISSUE THREAD

**Issue by Trae132** [Rem0o/FanControl.Releases#1767]
Almost every time I open fan control on a fresh boot it asks me to save even though I didnt make changes.  If I say yes and save it closes but next boot it asks me to save agaon.  Im not making changes and would love to see what its detecting.  It would also be a good feature.

**Comment by telejoshi** [comment]
Same.

**Comment by Rem0o** [comment]
If you really want to know right now, simply text diff the before/after save of the json file.

**Comment by Qerbas** [comment]
To get around this issue I had to save the current config as a new one, load it, and  then load the default one and then I stopped getting the notification to save. The only differences in the files were the version changed a new line " "InpOut": false," was added. I'll keep an eye on it and see if the issue happens again with a new version.

**Comment by Trae132** [comment]
> To get around this issue I had to save the current config as a new one, load it, and then load the default one and then I stopped getting the notification to save. The only differences in the files were the version changed a new line " "InpOut": false," was added. I'll keep an eye on it and see if the issue happens again with a new version.

ill try that, thanks

**Comment by Rem0o** [comment]
@Qerbas  that's a new setting that was added in this version, hence why it appeared and asked to save.
