### ISSUE TITLE
After random time, controls are reversed. Reboot fixes temporarily.

### ISSUE THREAD

**Issue by Racle** [Rem0o/FanControl.Releases#177]
After random time, controls are reversed. More % I add, less RPM I get. Works fine after reboot.

I usually found this when I'm leaving my computer on for longer periods (I'm mining with my gaming GPU).
Usually computer isn't extremely loud, but after case fan speed goes to 200rpm instead 1200rpm, GPU is doing LOT of work to keep that cool.

Recording here (happens with all fans): https://recordit.co/xzAEGINdWV
Log: [log.txt](https://github.com/Rem0o/FanControl.Releases/files/6073851/log.txt)

Windows 10 Pro
x470 pro prime (latest bios installed)
2700x
32gb 3200mhz ram

Fans (cpu, cpu_opt, cha_fan 1-3) are directly plugged to MOBO

**Comment by Rem0o** [comment]
Is that the case for all headers or only that specific one?

**Comment by Racle** [comment]
> Is that the case for all headers or only that specific one?

> Recording here (happens with all fans): https://recordit.co/xzAEGINdWV

Yes, with all fans (excluding gpu as I had disabled those)
cpu, cpu_opt, cha_fan 1-3

**Comment by Rem0o** [comment]
Is that with fan curves or with the manual mode only? I've never seen such behavior before, so I'm kind of confused. The % value is read through the sensor itself, so it is not the software somehow inverting the control, as the % value would be wrong also.

**Comment by Racle** [comment]
Manual or fan curves. Usually I found out this out when case fans should run 1300rpm and they actually run 200rpm and my GPU fans are running 95% as it is trying to cool while miming (its making quite lot of noice). 


And I find this extremely odd also.

Never seen behavior like this. And couldn't find single one result on Google either.

I'm now running asus Ai suite 3 and using that as fan controller as an test. But I don't recall this happening with Ai suite before. 

if it happens with asus tools also, I might need to reinstall windows, as it might be OS related problem also..

**Comment by Rem0o** [comment]
Basically how it works is, I set a control value (0 to 255) to the control chip. The control chip then returns that value if it was accepted.  That's the % you see on the control card. So the proper % is applied.  No sorcery here. That's as far as the software "controls" the fans. Then it is the chip which applies whatever PWM or voltage to the header based on that instruction.

Now the fact the fan then slows down tells me somehow the chip is doing something wrong. Might be BIOS, might be other software conflicting....

**Comment by Racle** [comment]
Small update. Switched back to AI Suite III fan controlling (it has worse controls :( ), but fan speed are as they should be.
5 days uptime now and it's still working as it should be.

Going to switch back to FanControl soon and test if that has same issue still.

**Comment by Racle** [comment]
Small update 2. 

Happened with also with AI suite (after I rebooted today). Suddenly while using my fans went from 70% to 30% speed, like they did with FanControl before.

Might be OS related issue, or hardware related issue, or some app does this.. Closing this as it's clearly not FanControl related.
