### ISSUE TITLE
Case Fans Uncontrollable

### ISSUE THREAD

**Issue by BobDylansRam** [Rem0o/FanControl.Releases#1775]
I have two case fans. They are bundled together in one block for speed. However, it is not under control so I cannot change its RPM or add it to a curve etc. Others I have seen have control over case fans so I believe I am experiencing an issue.

BeQuiet! Dark Base 700
2080 Super Gaming x Trio
B450 Tomahawk
Windows 10

**Comment by Rem0o** [comment]
If you can, put one case fan per motherboard header, ideally SYS headers.

**Comment by Ekristoffe** [comment]
Hello,
How your fan are connected ?
Are they connected to your motherboard ? 
Or to a black box ?
Also are those fan with a 3pin connector or 4 pin or something else ?

**Comment by BobDylansRam** [comment]
> Hello, How your fan are connected ? Are they connected to your motherboard ? Or to a black box ? Also are those fan with a 3pin connector or 4 pin or something else ?

The issue was as Rem0o expected, they werent connected to motherboard. I attached them to a SYS heading and they are controllable now.
