### ISSUE TITLE
Missing control for ASUS VRM Heat Sink Fan5

### ISSUE THREAD

**Issue by jkroepke** [Rem0o/FanControl.Releases#1778]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

Missing control for ASUS VRM Heat Sink Fan. 

![image](https://github.com/Rem0o/FanControl.Releases/assets/1560587/63ee3987-9fd2-44a2-8a88-b990edcf8e40)

After a [BIOS mod from hardwareluxx](https://www.hardwareluxx.de/community/threads/asus-b550-strix-tuf-prime-series-sammel-und-laberthread.1272489/) Forum, it possible to configure the VRM Heat Sink Fan through PWN and I'm able to configure a curve the same way like configure the Chassis Fan. However, I'm not able to configure the curve from FanControl (or AI Suite 3)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No

**Relevant hardware specs and setup**
ASUS ROG B550i

.

**Comment by Rem0o** [comment]
Hi,

> Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

Please see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility .
