### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by lonelymyp** [Rem0o/FanControl.Releases#178]
the program suddenly gave an error.
after the restart, the control parameters and the names of the sensors have disappeared.
the binding to the charts was dropped, the charts themselves remained in place.

Log:
`04.03.2021 18:59:01: Unhandled exception in FanControl v1.0.0.0
04.03.2021 18:59:01: System.AggregateException: При ожидании задачи или доступе к ее свойству исключения не были замечены исключения задачи. В результате незамеченные исключения были созданы повторно потоком завершения. ---> System.NotSupportedException: Данный тип CollectionView не поддерживает изменения в своем SourceCollection из потока, отличного от потока Dispatcher.
   в System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   в System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   в System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   в FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   в FanControl.ViewModels.MainWindowViewModel.Refresh()
   в FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()
   --- Конец трассировки внутреннего стека исключений ---
---> (Внутреннее исключение #0) System.NotSupportedException: Данный тип CollectionView не поддерживает изменения в своем SourceCollection из потока, отличного от потока Dispatcher.
   в System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   в System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   в System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   в FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   в FanControl.ViewModels.MainWindowViewModel.Refresh()
   в FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()<---

04.03.2021 18:59:01: System.NotSupportedException: Данный тип CollectionView не поддерживает изменения в своем SourceCollection из потока, отличного от потока Dispatcher.
   в System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   в System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   в System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   в FanControl.ViewModels.MainWindowViewModel.RefreshSensors()
   в FanControl.ViewModels.MainWindowViewModel.Refresh()
   в FanControl.ViewModels.MainWindowViewModel.<<RestoreApplicationState>b__119_10>d.MoveNext()`

**Comment by Rem0o** [comment]
Will be fixed in the next version.
