### ISSUE TITLE
Add Fancontrol.NzxtKraken plugin

### ISSUE THREAD

**Issue by brokenmass** [Rem0o/FanControl.Releases#1784]
I've developed a minimal c# native Fancontrol plugin for NZXT Kraken devices (https://github.com/brokenmass/Fancontrol.NzxtKraken) that should provide support for those devices without the issues caused by using a separate executable (like the approach used in Fancontrol.Liquidctl).

It currently supports Kraken V2 and V3 but I've only actually tested it on my Kraken X73

Would it be possible to get included it in the list of plugin in Fancontrol readme ?

Thanks.

**Comment by brokenmass** [comment]
That doesn't seem to work for me (and other users). This is because recent Kraken X3 have a different PID (0x2014), while LHM only supports 0x2007 . This plugin also supports kraken v2 and I plan to add support for new Kraken 2023 in a couple days.

**Comment by Rem0o** [comment]
Right.   Any reason creating a seperate plugin vs creating a PR for LHM?

**Comment by brokenmass** [comment]
I actually was not aware that LHM had (incomplete) support for NZXT AIO hardware.

**Comment by Rem0o** [comment]
Fair enough. Raise a PR here for the README, I'll merge it.

**Comment by brokenmass** [comment]
#1785

**Comment by Rem0o** [comment]
Merged
