### ISSUE TITLE
High Temperatur PCIe x1

### ISSUE THREAD

**Issue by heidl** [Rem0o/FanControl.Releases#1786]
Hello everyone!

I just discovered this awesome tool and am looking forward to using it!
When I was setting up a custom fan curve and looking at the temperature source options, I noticed some very high temperatur from one source compared to the others.
I am not very knowledgeable about computers and their components. Can anyone tell me what I am seeing and if this is normal? I am really worried about this!
Sorry if this is not the right place to post something like this!
![High Temperatur ](https://github.com/Rem0o/FanControl.Releases/assets/96009268/78eff3ba-34d1-4ef8-9f15-6737caac8a9a)

**Comment by DfrostX** [comment]
See here [https://www.reddit.com/r/buildapc/comments/101upqu/pcie_x1_temperature_abnormally_high/](url)

Most likely an invalid reading. I would not worry about it.

**Comment by heidl** [comment]
You are the best, thank you! I'm definitely less worried now :D
