### ISSUE TITLE
Cant control anything

### ISSUE THREAD

**Issue by klisza1993** [Rem0o/FanControl.Releases#1788]
I've got  laptop "MateBook D 16 AMD Ryzen 5" do you plan to support it? i cant control anything, the most important for me is  fan control. For now there's nothing ;/ 
![image](https://github.com/Rem0o/FanControl.Releases/assets/76993967/f6d30521-fe88-48ac-bf91-1b6874369dd0)

**Comment by DfrostX** [comment]
Laptops are not supported
