### ISSUE TITLE
Fan Control V157 - EVGA 3080 LEDs

### ISSUE THREAD

**Issue by solodolo-42** [Rem0o/FanControl.Releases#1791]
I just noticed the LEDs are no longer working on the graphics card. Would the latest update cause an issue with the LEDs?

---------------------------------------------------------------------------------------
ASUS ROG STRIX B550-F GAMING | EVGA GeForce RTX 3080 XC3 Ultra Gaming

**Comment by Rem0o** [comment]
I wouldn't think there is any causality between the two, especially since nothing changes on the GPU side.

**Comment by solodolo-42** [comment]
That's good to know. Appreciate it!
