### ISSUE TITLE
Net 4.8 vs 7.0

### ISSUE THREAD

**Issue by Mind777** [Rem0o/FanControl.Releases#1798]
Net 4.8 vs 7.0

Which version of fan control is recommened to download, net 4.8 or net 7.0?

Is there any differences/benefits between the different version?

**Comment by Rem0o** [comment]
Net48 is legacy, but widely compatible and built in with windows, while net 7 is the latest version of the runtime, with a download of the runtime required.  The net7 version should be more optimized, in theory, but in practice, you shouldn't notice any difference.
