### ISSUE TITLE
won't start with v39

### ISSUE THREAD

**Issue by agaiagaiagai** [Rem0o/FanControl.Releases#18]
Ran the update to v39 and FanControl didn't start again. Reboot and fresh reinstall didn't help either, nothing is happening.

Last log looks like this:
`10.08.2020 18:35:30:    bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bei System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   bei FanControl.Domain.ApplicationContext.SaveCacheState()`
`10.08.2020 18:35:30: Unhandled exception in FanControl v1.0.0.0`
`10.08.2020 18:35:30: Eine Aufgabe wurde abgebrochen.`
`10.08.2020 18:35:30:    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FanControl.App.d.d()`

**Comment by Rem0o** [comment]
Seems like your cache file is locked somehow? Try and delete it.

**Comment by agaiagaiagai** [comment]
Already deleted cache, but it's still not working or showing up in Task Manager or just anything really. Sadly not creating a log file either. I erased everything from my previous installation, unpacked the latest release from Github and still no reaction.

**Comment by Rem0o** [comment]
What's your GPU?

**Comment by agaiagaiagai** [comment]
GPU: XFX RX 5700 XL DD Ultra
Mainboard: ASRock B450M Pro4

I think the last version I ran before the update was v32 or v34. Is there an archive anywhere with all previous releases? If it stills works with the older versions, I could try out where things start going wrong for me.

**Comment by Rem0o** [comment]
Lookup the releases https://github.com/Rem0o/FanControl.Releases/releases

**Comment by agaiagaiagai** [comment]
OK so I tried a couple of releases, up until v38 everything works just fine, also with my own userConfig.
v39-beta, v39-beta.2 and v39 won't start. 
Opening v35, updating to v39 and restarting results in the following log:

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5052541/log.txt)

Deleted the CACHE file, still not working. 
For me personally it's not a big problem now, since v38 is running again, but it still seems odd to me.

**Comment by SubZero0** [comment]
Same issue here. V39 won't start, but V38 does.

**Comment by Swenerick** [comment]
Hi there o/, 

First, thank you a lot for your software. Exactly what I as looking for.
v38 runs fine but v39 won't start on my system as well.

Gigabyte Aorus x570 - Ryzen 5 3600 - ASrock PG RX580 8Gb OC

Hope that can help (?)

Greetings

**Comment by Rem0o** [comment]
Found the issue, will push an update with the fix.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V40

If it still crashes, I added more logs at startup to be able to diagnose better.

**Comment by agaiagaiagai** [comment]
I tried the new version, still crashed. This is the log.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5058104/log.txt)

Seems like it is looking for a dll from the Nvidia driver, which I and the other people reporting the bug don't have as we are using AMD GPUs.

**Comment by Rem0o** [comment]
> I tried the new version, still crashed. This is the log.
> 
> [log.txt](https://github.com/Rem0o/FanControl.Releases/files/5058104/log.txt)
> 
> Seems like it is looking for a dll from the Nvidia driver, which I and the other people reporting the bug don't have as we are using AMD GPUs.

Bingo

**Comment by Rem0o** [comment]
Deleted the two previous releases and pushed a new one which should not try to init the Nvidia GPU if it ain't there in the first place. Chicken and egg problem.

**Comment by agaiagaiagai** [comment]
Yes that worked for me, running smoothly now. Thanks for your quick fixes.

**Comment by Swenerick** [comment]
Thank you for the update. Unfortunately, It won't load on my system.

log says:

8/11/2020 21:23:11: Unable to load DLL 'nvapi64': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
8/11/2020 21:23:11:    at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI64_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]()
   at NvAPIWrapper.Native.GeneralApi.Initialize()
   at FanControl.Domain.ComputerAccessLayer.Initialize()
8/11/2020 21:23:11: Could not initialize.

Greetings

**Comment by Rem0o** [comment]
> Thank you for the update. Unfortunately, It won't load on my system.
> 
> log says:
> 
> 8/11/2020 21:23:11: Unable to load DLL 'nvapi64': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
> 8/11/2020 21:23:11: at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI64_QueryInterface(UInt32 interfaceId)
> at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegateT
> at NvAPIWrapper.Native.GeneralApi.Initialize()
> at FanControl.Domain.ComputerAccessLayer.Initialize()
> 8/11/2020 21:23:11: Could not initialize.
> 
> Greetings

Are you on V41? If it tries to open the API, then it means it is detecting an Nvidia GPU in your system, which doesn't make sense.

**Comment by Swenerick** [comment]
Arf... oui, en effet.

Sorry I didn't see the 41. Now it works 👍 
Thank you so much.

**Comment by Rem0o** [comment]
Will close this issue now. Thanks for the fast responses!
