### ISSUE TITLE
Corsair Hydro Series H100i Pro

### ISSUE THREAD

**Issue by hrst** [Rem0o/FanControl.Releases#180]
Hi,

I got a new gaming PC about a year ago, and it came with the Corsair Hydro Series H100i Pro water cooling for CPU. I've never done anything regarding fan control, but recently I recently learned when I heard (or did not hear, to be specific) a friend's PC.

He has an ASUS motherboard and uses Asus GPU Tweak. I have the MSI MPG Z390 GAMING PLUS, read a few articles, and found FanControl. I've installed it and did a few tests to identify which control belongs to which fan. Thanks for the great tool!

I can control every fan except the two Corsair Hydro Series H100i Pro fans. Is there any way I can control those with FanControl, or would I need to install the iCUE software from Corsair? (Have not installed anything yet.)

Any help is highly appreciated!

**Comment by Rem0o** [comment]
If the fans are plugged to the integrated Corsair headers, then yeah, can't control them. 

Either use motherboard headers, or contribute here for those headers to be supported:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.
