### ISSUE TITLE
All fans duplicated in Controls and Speeds sections

### ISSUE THREAD

**Issue by mikebm94** [Rem0o/FanControl.Releases#1805]
**Describe the bug**
After updating from version 157 to 158, all of the fans are duplicated in both the 'Controls' and 'Speeds' sections. The duplicated entries do not keep any customized names, 'hidden' settings, or links to fan curves that may have been set on the original entries.

![fancontrol-controls](https://github.com/Rem0o/FanControl.Releases/assets/66471661/b1a51162-2e69-4b7b-8d2d-9209d001b8f9)

![fancontrol-speeds](https://github.com/Rem0o/FanControl.Releases/assets/66471661/c8219a1a-4e05-48e7-9085-af813b8cd046)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No.

**Relevant hardware specs and setup**
OS: Windows 11 Pro - 21H1 - Build 22000.1936
FanControl Version: v158

**Comment by robert914** [comment]
Yes, I saw this same problem after I let it upgrade from V157 to V158. After switching= back to V157 everything returned it to normal.

**Comment by Rem0o** [comment]
Caught the bug, will only happen if the initialization retries/fails multiple times. 

The bug itself doesn't prevent your config working properly, and a simple refresh should erase the duplicates. Will fix ASAP.

**Comment by robert914** [comment]
I can confirm that the problem goes away with V159. Thanks @Rem0o for the quick fix!

**Comment by mikebm94** [comment]
Yep, V159 fixes it. That was fast, thanks!
