### ISSUE TITLE
GPU Fans not detected - NVApi not inizialized

### ISSUE THREAD

**Issue by gi2000** [Rem0o/FanControl.Releases#1807]
**Describe the bug**
For some time the program just worked, but today, without changing the GPU driver, the software gets the following error.
![pHfmjL0Jnr](https://github.com/Rem0o/FanControl.Releases/assets/36670660/1982b5d0-6f9f-403d-93a4-74c2214f5c74)
![pl6RgqiheB](https://github.com/Rem0o/FanControl.Releases/assets/36670660/68a16dd9-946b-4eb2-a7f4-49dc8aee0370)

After a few restarts of the software, they sometimes reappear, but I can't get them to stay.
Also, the linking of the AIO pump seems to have changed the CPU. When the GPU shows up, the AIO Pump has the name AIO Pump (As I set it), but when the GPU is missing, the AIO is found as fan # 7.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11642183/log.txt)

**Relevant hardware specs and setup**
https://pcpartpicker.com/user/gi2000/saved/cwpxgs

I hope you can help me. If you need anything else, just let me know.

**Comment by NSX2022** [comment]
How did you fix this?
