### ISSUE TITLE
DO NOT UPDATE (to 159)

### ISSUE THREAD

**Issue by Silther** [Rem0o/FanControl.Releases#1808]
**Describe the bug**
The update to 159 (from 157) will clear your config, so make a backup or wait for a fix

**Comment by Rem0o** [comment]
How so? 

There should be a configuration folder in your FanControl folder with all the configurations you saved over time.

**Comment by robert914** [comment]
Just a data point, but I had no issues upgrading from V157 to V159.

**Comment by sam86314** [comment]
Can confirm that my configuration file got screwed up when I updated.

Fortunately I had a backup in the FanControl main folder.

Have to redo the initial setup, but this has shown how important backing up your config profiles is.
