### ISSUE TITLE
FanControl changing maximum fan RPM

### ISSUE THREAD

**Issue by Skjolnir** [Rem0o/FanControl.Releases#181]
Hey,

I have this behavior where whenever I start FanControl the max RPM of my CPU fan (Fan #2 in the screenshots) changes.

normal control/RPM values:
![2021_03_12_13_23_59_Libre_Hardware_Monitor](https://user-images.githubusercontent.com/5647119/110940071-9ec33d00-8336-11eb-906f-adbf34e933a4.png)

after starting FanControl:
![2021_03_12_13_24_40_Libre_Hardware_Monitor](https://user-images.githubusercontent.com/5647119/110940074-9f5bd380-8336-11eb-8c1a-36ff15e17154.png)

**Comment by Rem0o** [comment]
You can't run both LHM and FanControl at the same time, they share the same driver and most likely will cause unexpected behavior.
