### ISSUE TITLE
Spams log file with errors on start up after update to 159

### ISSUE THREAD

**Issue by Erik85** [Rem0o/FanControl.Releases#1811]
I get this errors on start up and it has made 4 log files after update to 159.

/From log file/ 

2023-06-04 05:33:45: Unhandled exception in FanControl v159.0.0.0
2023-06-04 05:33:45: System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenV3.Update() i C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Controller\Nzxt\KrakenV3.cs:rad 194
   vid FanControl.Domain.BackendProviders.LHM.UpdateVisitor.VisitHardware(IHardware hardware)
   vid LibreHardwareMonitor.Hardware.Computer.Traverse(IVisitor visitor) i C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:rad 395
   vid FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Update()
   vid System.Collections.Generic.List`1.ForEach(Action`1 action)
   vid FanControl.Domain.ComputerAccessLayer.Update()
   vid FanControl.Domain.ApplicationClock.DoActions()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   vid System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by brokenmass** [comment]
do you have nzxt cam open ?

**Comment by Erik85** [comment]
Yes nzxt start with win so its open. And after i closed cam and restarted Fan Control it works even with cam open now.? i will se if its works after PC restart but anyway thx for answering and help?.

**Comment by Tw33die** [comment]
Same for me with CAM. I always have it on for my Kraken. I've never been able to get the fan control softwaare to override CAM.

**Comment by Erik85** [comment]
I have Kraken X63. And i only use Cam to monitoring PC temp and loads and RGB of pump ect but now i need to find a better software for that :).
The errors comes back on every PC restart if cam is loaded before Fan Control. If Fan Control is loaded first it works fine. Anyway my solution is stop using Cam for now. 

Thanks of time and help.

But is it Fan control update that broke "conflicted" or NZXT´s sotware thats broken it has been working fine until the update from FC?.

**Comment by brokenmass** [comment]
@Erik85 i believe it was just erroring silently as CAM takes full ownership of a device if it can and that should have prevented fancontrol to work even before. 

(For rgb controls I suggest signalrgb)

**Comment by Tw33die** [comment]
> I have Kraken X63. And i only use Cam to monitoring PC temp and loads and RGB of pump ect but now i need to find a better software for that :). The errors comes back on every PC restart if cam is loaded before Fan Control. If Fan Control is loaded first it works fine. Anyway my solution is stop using Cam for now.
> 
> Thanks of time and help.
> 
> But is it Fan control update that broke "conflicted" or NZXT´s sotware thats broken it has been working fine until the update from FC?.

How do u stop CAM from controlling the fans on ur Kraken? Even with the 'override' in Fancontrol CAM still controls it.

**Comment by brokenmass** [comment]
You have to turn off cam and remove it from auto start. If you use fan control (and signalrgb) you don’t really need it anyway

**Comment by Tw33die** [comment]
> You have to turn off cam and remove it from auto start. If you use fan control (and signalrgb) you don’t really need it anyway

Thanks, I'll look at Signalrgb
