### ISSUE TITLE
[Feature Request] Alerts

### ISSUE THREAD

**Issue by defaultsecurity** [Rem0o/FanControl.Releases#1812]
Dear Rémi,

Words cannot describe how professional, elegant and needed your program is. Someone should write a poem about it. You ended a decade of struggle for me. Thank you from the bottom of my heart.

**Alerts**
This feature would be very useful. Alerts could be triggered based on temperatures and when fans stop working. Perhaps alerts could execute user defined command line operations, thus making the notification possibilities endless.

Keep up the good work.

**Comment by Rem0o** [comment]
Thanks @defaultsecurity 

Your suggestion is a duplicate of https://github.com/Rem0o/FanControl.Releases/issues/807, I will close this issue.


Cheers.
