### ISSUE TITLE
Most recent AMD WHQL driver probably hides Radeon temperature sensors

### ISSUE THREAD

**Issue by marek-lestach** [Rem0o/FanControl.Releases#1818]
After updating AMD Software: Adrenalin edition because Windows decided to replace driver with older version, I am unable to find Radeon temperature sensors in FanControl.

**Is there a log.txt file next to FanControl.exe with recent date entries?**

Not really. I refreshed sensors and none of the Radeon sensors are listed. That's it.

**Relevant hardware specs and setup**

AMD Ryzen 7 5700X
Saphire Radeon RX 6700 XT 
Windows 11 22H2 build 22631.1830 (insider beta)
FanControl 159

**Radeon driver**

Driver Version
22.40.57.05-230523a-392410C-AMD-Software-Adrenalin-Edition
AMD Windows Driver Version
31.0.14057.5006

**Comment by User2564** [comment]
I hate to annoying however, one might be surprised how often a system reboot fixes oddities.

**Comment by marek-lestach** [comment]
I tried restart with no luck.

**Comment by notsureserious** [comment]
I had to use AMD's driver uninstaller package (in safe mode).  Reboot.  RE-Extract the Adrenaline software/driver, but cancel the install.  Then go to device manager to Microsoft VGA, update driver, browse and then select the driver directory under "C:\AMD\WHQL-AMD-Software-Adrenalin-Edition-23.5.2-Win10-Win11-May31\Packages\Drivers\Display\WT6A_INF"  and click select.  Fixed the missing GPU temp sensor. PITA, but here it is.

**Comment by marek-lestach** [comment]
I probably temporarily "fixed" it (it is more like workaround) by installing drivers provided by Windows Update. In the span of last months, Windows is trying hard to actively replace user-installed AMD drivers with windows ones which breaks lot of things, not only sensors. While not really happy with the solution, it seems to work. For now.

**Comment by Rem0o** [comment]
Navi 3 support:

https://github.com/Rem0o/FanControl.ADLX
