### ISSUE TITLE
Unable to edit Graph curves, Save as/Load configuration, or auto match fans after v71 update

### ISSUE THREAD

**Issue by ryanzigler** [Rem0o/FanControl.Releases#182]
After the auto-update to v71 a few minutes ago, I have lost the ability to edit both newly created and existing "Graph" fan curves. Additionally, I can no longer save a configuration using the "Save as" option; the only way to save a configuration is using the "Save" option to overwrite the currently loaded configuration. The "Load configuration" option in the overflow menu no longer works, however, I can load alternative configurations from the tray notification icon.

Additionally, when I attempted to create a new configuration from scratch as a troubleshooting step, the "Match fans automatically" function did not work.

Needed to downgrade to v70 to fix the problems.

[Pastebin of log from "Copy log to clipboard"](https://pastebin.com/qpEU4kdJ)
[Pastebin of log from install directory](https://pastebin.com/evupqQKE)

**Comment by CZonin** [comment]
Same issue here, can't edit any existing graph curves since updating to 71.

**Comment by Rem0o** [comment]
Pushed a fix. Sorry about the inconvenient.
