### ISSUE TITLE
[Feature request] Better support for 0rpm mode at idle

### ISSUE THREAD

**Issue by Vasllo** [Rem0o/FanControl.Releases#1820]
Hi, first of all, I would like to thank you a lot for this software, it's truly great, the best solution I have found so far, and I plan on donating whenever I have spare money (unemployed CC student).
But to the point, what I want can be achived in different ways, but I'll describe the objetive, issue and ideas below.

Objective:
Graph curve with 0rpm idle without constant spinning up and stopping of the fans.
E.g.: I want my fans to spin up when my sensor reaches 55ºC and stop when it reaches 50ºC.

Issue:
I can't set different start and end points in the curve, so the temperature gets stuck in the boundary between 0rpm and >0rpm, causing the fans to spin up and down constantly, causing unnecessary wear. I mitigate this by using average temperature from the last X seconds instead of direct sensors, but it only helps a bit.
Hysteresis doesn't do what I want to, even if I set a 10ºC hysteresis, the fans often stop at <1ºC below the boundary for some reason.

Ideas:
1 - Checkbox to apply hysteresis only at the boundary between 0rpm and >0rpm on the curve (in addition to the "only on the way down" option);
2 - Trigger curve that can trigger another curve instead of only a constant value. E.g.: a 55ºC load temp to trigger my curve, and a 50ºC idle temp to trigger a flat 0% curve or 0% direct value;
3 - Special start and end points for graph curves. E.g.: I could set the start point at 50% at 55ºC and the end point at 50% at 50ºC, so if the temperature start climbing from <50ºC, the fans will only spin up when the temperature reaches the start point, as well as stop only when it reaches the end point.

There probably are more ways to tackle this, but I wanted to give some ideas to help out the way I can. If I feel brave enough to mess with the code, I might try to do something once I have time and willpower.

**Comment by Vasllo** [comment]
I found a way to do this in the closed issues with a mix of the curve + trigger, so this is no longer necessary, but this is really not intuitive and could be easier.

**Comment by Vasllo** [comment]
> If you are using a graph, the hysteresis is always ignored at the first and last point of your graph. You can always make an other set of points at each extremes to get hysteresis at your desired stop point.

If I understood you correctly, for a 55ºC cut-off and 10ºC hysteresis, I should add a point at 45ºC, is that it? Because if it is, I tried that, based on another issue, and it didn't work. Only the curve+trigger mix worked.

**Comment by Rem0o** [comment]
Hysteresis is not meant to be seen as triggered at a specific temperature "gate".  So if you want specific "trigger" point, the trigger function is the way to go.
