### ISSUE TITLE
The fan suddenly controls only in an on-off format

### ISSUE THREAD

**Issue by efirlus** [Rem0o/FanControl.Releases#1822]
![KakaoTalk_20230609_083701111](https://github.com/Rem0o/FanControl.Releases/assets/62008334/1c4909ce-95b8-4c84-82be-36e9426dae6d)
![KakaoTalk_20230609_083727157](https://github.com/Rem0o/FanControl.Releases/assets/62008334/7ce8a07f-c780-4fb7-80d7-0e55cec36fb4)

As you can see from the two screenshots, one of the two fans installed on the computer starts to turn off at 21% or less, and on full load at 22% or more.

Fan 2 is running perfectly fine in a linear.

The motherboard is MSI MAG B650M and the fans are Noctua NF-F12 PWM BLACK.

**Comment by Rem0o** [comment]
That high number you see if quite common when you are on the threshold of the fan starting to spin.   I should probably filter it out as its quite predictable.  As soon as you get past the starting point, the number should be representative of the actual fan speed.
