### ISSUE TITLE
Fan not run at full speed when hit 100%

### ISSUE THREAD

**Issue by HuguesGauthier** [Rem0o/FanControl.Releases#1823]
I don't know if it is a bug.

I created a Curves graph 

![image](https://github.com/Rem0o/FanControl.Releases/assets/8374362/5e34d3d4-90d4-45ab-8618-d92810437b33)

and i associated the graph to my radiator fan.
when the % hit 100%, my fans do not run at full speed

![image](https://github.com/Rem0o/FanControl.Releases/assets/8374362/d9f6853e-ef94-41d7-b28c-32729c30d9cb)

full speed must be 2000 rpm not 730 rpm.

**Comment by Rem0o** [comment]
First, I see you have have associated your speed and control sensors.   Run the assisted setup to get that sorted out.

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/895ddb08-15f2-4482-a408-d75f8608e968)


Then, what kind of motherboard? Asus? Seen cases where having a silent profile in armory create/asus crapware  changed the RPM range available for FanControl.

**Comment by HuguesGauthier** [comment]
Wow, I remove all the crapware, problem solved.

**Comment by HuguesGauthier** [comment]
I have the same problem, when the % is at 0, then the fan still spining.
![image](https://github.com/Rem0o/FanControl.Releases/assets/8374362/c5bba12e-8d65-416d-84dd-7e58a4894d44)
![image](https://github.com/Rem0o/FanControl.Releases/assets/8374362/07a5c79f-e3af-4820-a56c-46868f4d7024)
![image](https://github.com/Rem0o/FanControl.Releases/assets/8374362/5b1b1d02-57d9-41d4-af0d-83383331de68)
