### ISSUE TITLE
[Feature Request] Theme Dependent Primary, Secondary, and Tray Icon Colors

### ISSUE THREAD

**Issue by dkgameplayer** [Rem0o/FanControl.Releases#1824]
At the moment, when switching to dark mode in Windows and Fancontrol is set to follow the system, the tray icon (which is normally dark greyish in font color) gets lost in the dark taskbar and is not visible. It would be useful to set different colors for different themes so appearance dependent components can be light grey in dark theme, and dark grey in light theme for visibility. Thank you. Love the software.

**Comment by Rem0o** [comment]
You can always override 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/a4a0c8cc-19cf-4e73-a1fe-ac7d912870be)
