### ISSUE TITLE
Fans reacting too fast / agressive on short utilization spikes

### ISSUE THREAD

**Issue by MPH2210** [Rem0o/FanControl.Releases#1825]
I didn't know where else to ask, I hope here is fine.

My graph is set from 0% at 20° to 100% at 80°+ and my i5 13th gen has very short spikes, when opening i.e. a browser with recently opened tabs.
This creates a short spike of CPU utilization, which makes the fans increase their speeds to a very audible level (to around 70%)

I tried some things myself but did not get any results I was happy with. Could someone help me out by any chance?

Thanks!

**Comment by Rem0o** [comment]
Start by setting some hysteresis + response time on your graph.
