### ISSUE TITLE
Corsair Commander Pro Temp Sensor goes to 0C and NaN every few seconds

### ISSUE THREAD

**Issue by sarkarnen** [Rem0o/FanControl.Releases#1827]
**Describe the bug**
My configuration uses a temperature sensor connected to a Commander Pro to report loop coolant temperature, and controls fan speed based on that temp. Every few seconds, all temperature readings from the Commander Pro either shift to 0C or NaN. As it does this, the fans ramp down as it thinks the temp is 0C. The sensor reading returns but then shifts back a few seconds later. Video of the phenomena is linked below. I've tried downgrading to V158 as well as replacing the Corsair Link DLL. I normally don't have iCue installed, but shutting down Fan Control and installing Corsair iCue yields constant temperature readings without issue. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11713575/log.txt)

**Relevant hardware specs and setup**
Intel Core I7 13700KF
ASUS Prime Z790M-Plus D4
32 GB Oloy 3200 MTs
RTX 3080 Vector FTW3

Video: https://github.com/Rem0o/FanControl.Releases/assets/136206652/8f79af9e-a515-48b1-b4bb-1cdba772a3f2

**Comment by Rem0o** [comment]
That's a bug with the plugin, not FanControl itself.  Please transfer to the plugin's repo and close this one.
