### ISSUE TITLE
[Feature Request]  Numbers rounding.

### ISSUE THREAD

**Issue by xlsupport** [Rem0o/FanControl.Releases#1828]
Keeping your UI as minimalistic as possible...  may I suggest you have a look at the string formats for Temps/Percentages and RPM.

Showing RPM with decimals for me simply doesn't make sense.  708.3 or 709 RPM, who cares?

For temps and percentages I'm not sure about the need for decimals. But IF you choose for precision then please make it a fixed decimal. This avoids the changing/jumping width for e.g.  50 % to 51.2 %   or  78 °C to 79.3 °C

btw: Awesome app.

**Comment by Rem0o** [comment]
> Showing RPM with decimals for me simply doesn't make sense. 708.3 or 709 RPM, who cares?

A lot of people actually, originally had no decimal places, but people kept asking for it, and if the info is there, why not show it all.

> IF you choose for precision then please make it a fixed decimal. This avoids the changing/jumping width for e.g. 50 % to 51.2 % or 78 °C to 79.3 °C

In the end, it's a compromise. Some boards won't have any decimal, so having a ".0" all the time would also look bad.  Adding yet an other menu option for that feels overkill.
