### ISSUE TITLE
Taskbar Temperature Icon Order

### ISSUE THREAD

**Issue by Mind777** [Rem0o/FanControl.Releases#1833]
Can you plz implement a way to order the taskbar temperature icons?

I have 3 icons and getting them in the correct order is difficult to do by dragging the numbers on the taskbar as they don't always go in the correct order after moving one.

Also, once i have the correct order, this seems to be lost on a system restart.

**Comment by Rem0o** [comment]
That order is not controlled by the software sadly. You must order then properly relative to the others.

**Comment by Mind777** [comment]
ok, thanks anyway.
