### ISSUE TITLE
Request sensor selection

### ISSUE THREAD

**Issue by Ratchet4220** [Rem0o/FanControl.Releases#1841]
So I have an Asrock Extreme4 x570 motherboard. For some reason my cpu and Southbridge (aka chipset) temps don't change. 

My tdie (aka package) temp does change and reports correctly in CPUID HWMonitor. I know fan control sees this temp, as it's currently displayed in my task bar. What I would like to do is set my cpu fan to be controlled by the tdie temp, instead of the mainboard cpu temp that doesn't change...

Is this possible?

**Comment by Rem0o** [comment]
See the https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility section

**Comment by Ratchet4220** [comment]
What is that link supposed to tell me? I read that page... I actually found the solution to my issue about an hour ago, but your documentation does not cover it. I guess because it's in beta? Btw the beta fan curve seems to be working pretty well... I also like the ability to set min/max temp limits.
