### ISSUE TITLE
Which temp source? 

### ISSUE THREAD

**Issue by Moophoop** [Rem0o/FanControl.Releases#1842]
![IMG_0770](https://github.com/Rem0o/FanControl.Releases/assets/128733093/49f5fde0-4387-4d8a-8fa6-ce81907eed71)

My core temp runs way higher than ccd1 and cpu, should I be using the core temp for the temperature source for my cpu fan?

**Comment by Rem0o** [comment]
Should probably go Core, just scale your curve around the temperature it ranges.
