### ISSUE TITLE
[FR] Publish to Winget Repo

### ISSUE THREAD

**Issue by PhillyUrbs** [Rem0o/FanControl.Releases#1845]
The Windows Package Manager (also known as winget) is a free and open-source package manager designed by Microsoftfor Windows.

Please consider publishing this app to the Winget repository to allow for easy installation on end user systems.

See this repo for info on how to publish: https://github.com/microsoft/winget-pkgs

**Comment by cbr-github** [comment]
I'd also be interested in this. However it is currently blocked by:
>[Policy] zip-binary
Blocked by [Zipped-Binary issue](https://www.github.com/microsoft/winget-cli/issues/2711)

see: https://github.com/microsoft/winget-pkgs/issues/97145#issuecomment-1437239734

**Comment by PhillyUrbs** [comment]
I didn't know you could submit an issue to that repo requesting that someone else package an app. Looks like we will need @Rem0o to create a supported install package.

**Comment by zotabee** [comment]
+1 for this !

**Comment by AnonymousWP** [comment]
Any updates on this?

**Comment by min7-i** [comment]
It's now available via winget. Thanks to the installer added in V181 and lm-gh who created an [MR](https://github.com/microsoft/winget-pkgs/pull/139480) to add it in the winget-pkgs repo.
