### ISSUE TITLE
CPU temp lost from tray icon after upgrading CPU

### ISSUE THREAD

**Issue by Taomyn** [Rem0o/FanControl.Releases#1849]
I upgraded my AMD 2700X (Gigabyte B450 motherboard) to a 5900X and afterwards the FanControl tray icon stopped showing the CPU temp. I deleted FanControl V160 and created it again, but even after going through the auto-config the icon remained the same. - the CPU/case/GPU fans are all fine.

I've only been able to get it back by manually editing he json file and changing the section for it - I was able to find an old copy that had this but the Identifier and the Name were different:

```
    "TrayIcons": [
      {
        "Color": null,
        "SensorId": {
          "Identifier": "/amdcpu/0/temperature/2",
          "IsHidden": false,
          "Name": "Core (Tctl/Tdie)",
          "NickName": "Core (Tctl/Tdie)"
        }
      }
    ]
```

I tried finding anywhere in the docs on how the tray icon is supposed to be configured with the application, but found nothing.

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/76aa28b3-75cc-4395-91a3-875a315d174f)

**Comment by Taomyn** [comment]
@Rem0o thank-you for the explanation, I'm all sorted now.
