### ISSUE TITLE
[Request] A history diagram of the temperatures

### ISSUE THREAD

**Issue by Scanda85** [Rem0o/FanControl.Releases#185]
I as a user of fancontrol wants to see the a history diagram of the temperatures for the last few minutes. I want to use the effect on the temperatures when i configure the best working points of the fan speed.
For example when i change the fanspeed i want to see how much the temperature will increase or decrease during few minutes.

**Comment by Rem0o** [comment]
FanControl is not a monitoring tool. 
Use the monitoring tool you'd like if you want to monitor your temperatures with graphs, plots and so on.
