### ISSUE TITLE
Manual control sliders "flipped" HWM Confirms fan speeds.

### ISSUE THREAD

**Issue by killermelon1458** [Rem0o/FanControl.Releases#1852]
The software works fine when using curves, but the moment I click manual control the fan does the opposite of what its told. 
Example 100% the RPMs drop to 0
0% the RPMs go to max
40% the RPMs go to 60%

![fan control bug 2](https://github.com/Rem0o/FanControl.Releases/assets/39802375/bcb3ed35-80c5-4394-94d5-7c94aac98b3e)

![Fan control bug](https://github.com/Rem0o/FanControl.Releases/assets/39802375/8b507a5e-323d-421e-9dfb-e44aab09beca)

**Comment by Rem0o** [comment]
You should have the same behavior with curves, not just manual controls. 

Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/1852
