### ISSUE TITLE
v160 Update Causes Chipset Temp to Display as -1 degrees

### ISSUE THREAD

**Issue by Mind777** [Rem0o/FanControl.Releases#1855]
Correct temperature display of x570 chipset with v159

After updating to v160 chipset temp now displays as -1

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

Probably a bug was introduced with a recent change in https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.

Will keep an eye for a fix.
