### ISSUE TITLE
Response Time option does not appear to work

### ISSUE THREAD

**Issue by michaelsong-hz** [Rem0o/FanControl.Releases#1856]
**Describe the bug**
Hey, love your software! I think an update in the last month or two might have broken the response time option, as I've noticed my fans instantly ramping up and down. I've demonstrated this for two separate fan controls in the following videos:
https://www.youtube.com/watch?v=0nDSRWa22II
https://www.youtube.com/watch?v=jHSWmlCMgxo

**Is there a log.txt file next to FanControl.exe with recent date entries?**
There's nothing relevant that I can see - just errors when updating my GPU drivers which causes a reload.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/11858435/log.txt)

**Relevant hardware specs and setup**
CPU: AMD Ryzen 7 7700X 4.5 GHz 8-Core Processor
CPU Cooler: Noctua NH-U12A 60.09 CFM CPU Cooler
Motherboard: Asus ROG STRIX B650E-I GAMING WIFI Mini ITX AM5 Motherboard
Memory: Kingston FURY Beast 16 GB (2 x 8 GB) DDR5-6000 CL40 Memory
Video Card: EVGA FTW3 GAMING GeForce RTX 3080 10GB 10 GB Video Card
Case: Cooler Master MasterBox NR200 Mini ITX Desktop Case
Case Fan: Noctua A12x15 PWM 55.44 CFM 120 mm Fan
Case Fan: Noctua A12x15 PWM 55.44 CFM 120 mm Fan
Case Fan: Noctua A12x25 PWM 60.1 CFM 120 mm Fan
Case Fan: Noctua A12x25 PWM 60.1 CFM 120 mm Fan

**Comment by Rem0o** [comment]
For the graph, hysteresis/response time is ignored at the limits you set with your first and last point.   You can duplicate these points further each side to have hysteresis at your idle and load point.

**Comment by michaelsong-hz** [comment]
I see, it would be nice if this behaviour was mentioned in the docs somewhere for future reference. Thanks for the help!
