### ISSUE TITLE
lost my fans, after updating to V161

### ISSUE THREAD

**Issue by BK-Morpheus** [Rem0o/FanControl.Releases#1858]
I was controlling CPU, Rear, Front and GPU Fans with Fan Control, just fine for a long time now.
After updating to Version V161 a few minutes ago, the application won't detect any fans, other than those from my Nvidia GPU.

Running the fan and sensor detection again, is still not finding the fans, that are connected to the mainboard, only the two fans from my Nvidia GPU.

Rolling back to V160 fixed the issue immediately.

Specs:
Asus X370-Prime Pro
Ryzen 5700x
RTX 3070
Windows 10 x64

**Comment by Rem0o** [comment]
Any logs in log.txt indicating a problem initializing LibreHardwareMonitor?

**Comment by BK-Morpheus** [comment]
After deleting Fan Control (except my config file) and downloading it again, there is no log file (but the behavior still exists, when updating to V161).

**Comment by asmasca** [comment]
Same issue here with same board. Also no log file that I can find.

**Comment by Rem0o** [comment]
@asmasca  Three dot menu top right, open error log.   If its greyed out, you got none.

**Comment by asmasca** [comment]
It's greyed.

**Comment by Rem0o** [comment]
If you loadup the lastest version of [LHM](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases), any sensor/fans showing?

**Comment by asmasca** [comment]
All the fan speeds show up. FanControl also actually shows the fan speeds, but can't control them.

**Comment by alias8818** [comment]
Same here.

**Comment by mich43l** [comment]
same here, also with Asus X370-Prime Pro

**Comment by Apicedda** [comment]
same here, same motherboard. I've got a log file but i think it contains unrelated errors
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/11895181/log_1.txt)

![Screenshot 2023-06-28 152438](https://github.com/Rem0o/FanControl.Releases/assets/9436220/d3436b14-5b45-43e3-b73b-01199903429e)

**Comment by brswattt** [comment]
Prime x370 pro, same issue. will post whatever info is needed.

**Comment by Lukatta** [comment]
Same motherboard, x370 prime pro. Same issue.

**Comment by Rem0o** [comment]
Identified the issue.

**Comment by tekert** [comment]
It should be fixed in [#1109](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1109), fan controls where not exported when moving to the IT8665E sensor configuration (previouly they where taken for a default non IT8665E configuration), they are now added.

**Comment by brswattt** [comment]
> Identified the issue.

awesome, thank you!!

**Comment by Rem0o** [comment]
See V162

**Comment by asmasca** [comment]
Works again. Thanks a lot!
