### ISSUE TITLE
Feature request - any method of remote control 

### ISSUE THREAD

**Issue by dementeb** [Rem0o/FanControl.Releases#186]
Good day, thank you for awesome tool.

Please, is there an any possibility to external control the fan speed and receive data from the sensors? rest api, console command?

Thank!

**Comment by Rem0o** [comment]
Not as of now. 

What's the use case?

**Comment by dementeb** [comment]
I have a "smart" home with home assistant / mqtt / node-red stack. This will allow me to control the noise depending on various factors ... For example - the presence of a person nearby. Or room temperature. And on the street, for example. Or take into account the humidity .. Lots of applications! )
Even just controlling the speed of the fans would be great. I get the sensors from the open hardware monitor, but there is no memory junction data for the video card. But this is overkill, yes. 
Well, I will study the possibility of using some kind of script system like auto-it

Thanks again for the great software.

**Comment by dementeb** [comment]
There is a system with very noisy fans, they are powered separately through the molex, and the pwm and tachometer from the motherboard. This must be controlled from external factors.

**Comment by Rem0o** [comment]
You could develop a plugin that inject a "sensor" that in reality is a form of a remote command. 

See:
https://github.com/Rem0o/FanControl.Releases/wiki/Plugins

**Comment by dementeb** [comment]
Wow its a variant, thank u, I wll try )

**Comment by jamsven** [comment]
I would also be interested for a solution. I would like to use openhab to controll my pc fans

**Comment by dementeb** [comment]
This is the solution for me:
https://github.com/Rem0o/FanControl.Releases/issues/112#issuecomment-758273494
I will switch profiles, not bad.

**Comment by Rem0o** [comment]
See V81.
