### ISSUE TITLE
How to unhide a hidden curve?

### ISSUE THREAD

**Issue by mihalski** [Rem0o/FanControl.Releases#1863]
I accidentally hid a curve and I cannot figure out how to unhide it.

**Comment by mihalski** [comment]
> I accidentally hid a curve and I cannot figure out how to unhide it.

Settings> Show hidden card > unhide.

Not obvious, but I figured it out after 10 minutes.,

**Comment by Rem0o** [comment]
I plan to move that checkbox more "in view" in the main page.
