### ISSUE TITLE
FanControl responds only every 14-15 seconds

### ISSUE THREAD

**Issue by RansomSpawn** [Rem0o/FanControl.Releases#1866]
everything is fine except for the responding time of Fan Control in general which is around 14 seconds.
no matter what i setup in the program, fan control does it only every 14-15 seconds.
if i set the step down time to 1%/sec fan controll will step down by 1% steps but only every 14-15 seconds and not every second. it also updates the ui only every 14-15 seconds and take changes also only then but it sets only the next value which it should set every second.
so it changes the fan speed only 1% down every 14-15 seconds.
if i set the down steps to 10%/sec it changes it 10% down but also only every 14-15 sec...
it responds to my inputs (via mouse etc) like usual...

my specs:
Asus Prime x470 pro
Ryzen 7 5800X3D
Asus RTX 3070 TUF - GPU Tweak 3 OC
windows 10 pro - 21H2

what could cause this behaviour and how to change that?
is it a bug or is it my system?
thank you for your help!

**Comment by Rem0o** [comment]
Untick Embedded EC in your Sensor settings.

**Comment by RansomSpawn** [comment]
thank you, its working now :)
