### ISSUE TITLE
FanControl startup task runs under the wrong user account

### ISSUE THREAD

**Issue by Pomax** [Rem0o/FanControl.Releases#1869]
**Describe the bug**

When setting FanControl to start up with Windows, on a Windows installation that uses proper user management (i.e. normal users that are NOT administrators, bizarrely: not the default when you install windows. By default the user's account counts as an admin account) the task for that is added to the administrator's task schedule list. This also means that it will run "in their profile" instead of starting for the user that's logged in, so when the user logs on, nothing happens (the task is not active for that user). When you update the task to run "for any user log on", the task _will_ run, but FanControl will be running _in the administrator's user session_ so the user that logged on has no access to it.

And to make things more fun, you can't change the task so that it runs "For another user" and picking your standard user account, because the UAC requirements mean that even with "use highest privileges" checked the task will refuse to run due to _that user_ not having admin permissions.

There has to be a way for FanControl to ask for "never ask for UAC again" rights so that standard users can run it at startup instead of having it run through the admin logon and having to switch accounts just to change a setting =S

**Comment by Rem0o** [comment]
> There has to be a way for FanControl to ask for "never ask for UAC again" rights so that standard users can run it at startup

As the program is structured right now ( single process application ), you can't have the UI if you don't have admin privilege, since the UI and the backend, which requires the admin level, run under the same process.

**Comment by Pomax** [comment]
Guess that makes this a feature request then.

**Comment by Rem0o** [comment]
Linking to https://github.com/Rem0o/FanControl.Releases/issues/135.

Closing.
