### ISSUE TITLE
FanControl windows pop up on windows start

### ISSUE THREAD

**Issue by nicesub** [Rem0o/FanControl.Releases#1871]
**Describe the bug**
Since 162 update when I start machine FanControl app window will pop up on windows start. Before 162 it would start with windows as expected but it would remain minimized and in the tray I would not need to manually minimize it.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No, no log entries post 162 update.

**Relevant hardware specs and setup**
I am not sure this is relevant?

**Comment by DfrostX** [comment]
Yeah the same happened to me. Seems like with the 161 -> 162 update, the option "start minimized" got disabled in settings menu. Just re-enable it.

**Comment by nicesub** [comment]
OMG, you are right! It looks like the config got reset with this update. Closing this now :)
