### ISSUE TITLE
[Feature Request] Automatic Updates in Background without user input

### ISSUE THREAD

**Issue by PulsarNeutronStar** [Rem0o/FanControl.Releases#1873]
Not a bug.

For me, and if I may assume, maybe most users, Fan Control is a great tool which is being setup in the beginning to a suitable state and then, it works reliably in the background without the need for any user input.

While I enjoy seeing constant development and frequent updates to the software, I would like to suggest the following, new feature:

It would be great if there would be a checkbox I can select, (default = false) with the result of the program updating itself in the background (during startup) whenever a new update has been detected. The frequency of updates recently has increased a bit and I would find confort in being able to have those updates run fully automatic in the background without the need for any userupdate.

Thanks.

**Comment by Rem0o** [comment]
I always went against this since an update "may" break compatibility sometime with existing configs.  If it does it in the background without any user input, well the user has no idea something even happened, and may not notice if something broke/bugs out.
