### ISSUE TITLE
[Plugin API] Restore main window

### ISSUE THREAD

**Issue by EvanMulawski** [Rem0o/FanControl.Releases#1875]
Allow plugins to restore the Fan Control application window to show critical alerts, e.g. pump failures and error detections.

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/0ac0d544-5038-4d0e-bf89-c99716d11f8c)
I did have this in the pipeline at some point. Will be adding it in the next release. I'll check if there is some other useful stuff I might be throwing in.

**Comment by Rem0o** [comment]
V163

**Comment by EvanMulawski** [comment]
@Rem0o Getting the following exception when calling this new method:

```
Type: System.InvalidOperationException
Message: The calling thread cannot access this object because a different thread owns it.
Source: WindowsBase
Stack Trace:
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at FanControl.Domain.ApplicationContext.ShowMainWindow()
   ...
```

Looks like it needs to be invoked by the dispatcher?

**Comment by Rem0o** [comment]
@EvanMulawski  yep I rushed it. Will fix.
