### ISSUE TITLE
All the fan control files keep appearing on my desktop background 

### ISSUE THREAD

**Issue by Kyhtred** [Rem0o/FanControl.Releases#1877]
Hi all, I'm really liking this software so far but im having a small but annoying issue. For some reason after i close down the software all the fan control files appear on my desktop and i have to manually remove them only for them to re appear. Is there any fix around this as its rather inconvenient.

Thanks in advance

**Comment by Rem0o** [comment]
All the files? What files? The json config files, or all the exe/dlls?

Where are you running the executable from?
