### ISSUE TITLE
Tray hint not displayed disk name

### ISSUE THREAD

**Issue by pult** [Rem0o/FanControl.Releases#1879]
**Tray hint not displayed disk name**
![FanControl_v162_at_2023 0703](https://github.com/Rem0o/FanControl.Releases/assets/1542721/1c44d42f-7944-436e-b083-72a91d4d4633)

**Comment by Rem0o** [comment]
Screenshot of the tray icons page with the selected sensors?

**Comment by pult** [comment]
Yes
![зображення](https://github.com/Rem0o/FanControl.Releases/assets/1542721/8425329d-2099-462e-9cfb-0ce53d00875f)

**Comment by pult** [comment]
Yes
![зображення](https://github.com/Rem0o/FanControl.Releases/assets/1542721/df78baff-8843-4842-b897-c51ec3d8ee23)

**Comment by pult** [comment]
Yes 
![зображення](https://github.com/Rem0o/FanControl.Releases/assets/1542721/10f9df1a-f6d3-4b52-986a-3d2096f08e4c)

**Comment by Rem0o** [comment]
I got it.  
You nicknamed your sensors right? "SSD Kingston" must not be stock.  The tray icon was not using the nicknames. 
Will use the nickname in the next release. Should look a lot better.

Thanks for reporting.
