### ISSUE TITLE
Start minimized has weird behaviour

### ISSUE THREAD

**Issue by zotabee** [Rem0o/FanControl.Releases#1880]
**Describe the bug**
Since one or two versions, Fan Control windows open itself automatically when the my computer starts instead of being minimized like in the past.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
no

**Relevant hardware specs and setup**
-

I noticed that ""StartMinimized": true," line is completely gone in newer version, if I put it back, it will be removed at the next save of Fan control settings save.

In "settings", "Start minimized" was unchecked, I checked it back. But the question is where is that setting saved now if that's not in the userConfig.json file ?

**Comment by Rem0o** [comment]
Was moved from the config files to the CACHE file.

**Comment by zotabee** [comment]
Noted. Thanks for the information.

**Comment by ppamorim** [comment]
@zotabee Same issue here, it's always opening when my computer starts, I am on version 162.
