### ISSUE TITLE
Windows scrollbar & resizing

### ISSUE THREAD

**Issue by TestDmitriy** [Rem0o/FanControl.Releases#1881]
**Describe the bug**
When i resized window to show only lowest row with cards  - windows scroll bar become inaccessible. So, i have to expand window to see lowest row, but now it shows 2 rows of cards

It happened after last update.
Everything on the screenshot/yellow marker. 

Thank you
![07-03-2023_2119](https://github.com/Rem0o/FanControl.Releases/assets/86534431/ed175a30-2f2b-4aa6-ab1c-67ee31587a18)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V164

**Comment by TestDmitriy** [comment]
Thank you for quick fix.
Is it possible to limit vertical size of window up to lowest row of cards?
