### ISSUE TITLE
Loading previous version profiles causes crash

### ISSUE THREAD

**Issue by phantum29** [Rem0o/FanControl.Releases#1885]
**Describe the bug**
I haven't used the profile 'normalcool' since v149. My default profile loads fine and opens when fancontrol opens. However, now when I load configuration, select 'normalcool' from the list of previous configurations, the window shows loading, 'configuration loaded: normalcool.json' then FanControl crashes. There are no log entries, and when using winmerge to compare the two jsons, aside from some fan curves, and the version number, they're nearly identical. This problem occurs when I open any previous configuration from V149 or earlier since I rarely switch configurations.
![FanControlV162_ConfigLoadCrash](https://github.com/Rem0o/FanControl.Releases/assets/85202149/6323978b-b24a-4b74-a399-9b073518d831)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No relevant log entries.

**Relevant hardware specs and setup**
No configuration changes since V149 to now (V162). MSI X570 Tomahawk wifi, 5900X, evga 3080ti FTW3 ultra hybrid. Total of 9 unique controllable fans including GPU's PCB and GPU radiator fans.

**Comment by Rem0o** [comment]
Could you share said json files?

**Comment by phantum29** [comment]
Changed extension to .log for git supported upload. quiet.json is what was loaded at the time of update and works. NormalCool is what fails to load. Thanks!

[NormalCool.json.log](https://github.com/Rem0o/FanControl.Releases/files/11953029/NormalCool.json.log)
[quiet.json.log](https://github.com/Rem0o/FanControl.Releases/files/11953030/quiet.json.log)

**Comment by Rem0o** [comment]
I could load it just fine, but I don't have an Asus board.

[NormalCool2.json.log](https://github.com/Rem0o/FanControl.Releases/files/11953462/NormalCool2.json.log)

I unticked Embedded EC from your config, try that again.

**Comment by phantum29** [comment]
Thanks. I think you meant MSI mobo. I tried to import the config, no such luck unfortunately. I'll try removing where I have fancontrol 'installed' and try anew. 
![image](https://github.com/Rem0o/FanControl.Releases/assets/85202149/e6444c2c-7534-46f4-8bcc-36582d61ba8b)

**Comment by phantum29** [comment]
Oh, it must be _something_ with my install. I just tried to create a new configuration and that caused a crash. The file (Test1.json) did get generated, but I'm unable to open it as it's essentially blank. Still no entries in the log, any way to turn on debug / make it more verbose? I'll give the new install a try later and let you know. Thanks for your help.

**Comment by Rem0o** [comment]
What kind of language setting do you got going on in Windows?

**Comment by phantum29** [comment]
Just US English.
