### ISSUE TITLE
Fans not working

### ISSUE THREAD

**Issue by aaronpotter8556** [Rem0o/FanControl.Releases#1886]
My GPU (AMD) and Chassis 1 (air In) fans are not working, but Out fans Chassis 2 & M.2 headers are working fine. nothing this making the 2 sensors work.

**Comment by Rem0o** [comment]
For AMD GPU, see FAQ.

For your other fan,  do you have other empty headers that appear in fan control?

**Comment by aaronpotter8556** [comment]
yes they show. will look into the FAQ for AMD cards thx. I've some what solved the fans, they are now working. just ran the automatic function, they all work on curve's now

**Comment by DennistheCook** [comment]
Issue here is only the Cpu header and Cpu_Opt header are detect by fan control 162V , all system fan header will not respond.
Gigabyte B5650E Master, Noctua Cpu cooler and case fans.
