### ISSUE TITLE
Application does not work properly after update

### ISSUE THREAD

**Issue by dgarcia90** [Rem0o/FanControl.Releases#1888]
Hello everyone, I'm having the following issue after the latest update.

When I login and open Fancontrol it does not refresh the ifnormation. All the spees, temps, etc remain the same. For instance if when I open Fancontrol the CPU temp is 39º it will remain that way. It happens the same with the rest of sensors, fans, etc

I tried to refresh the sensors but it does nothig, basically anything I tried to do in the application does nothing. For instance when clicking on "Load configuration" it does not open  any window to select a config file.

Any idea of what can I try to fix this?

**Comment by dgarcia90** [comment]
> Asus board right?
> 
> The EmbeddedEC sensors are jamming the refresh cycle. Try and uncheck that option in sensor settings.

Hey thanks for your reply. I will check that.  What I did was delete the cache config and re-open fancontrol now looks like it's working again. Thanks again!

**Comment by dgarcia90** [comment]
Hey, I'm still having the issue everyonce in a while. However, the issue seems to get fixed if I closed and re-open fancontrol

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1867

Will be fixed.

**Comment by dgarcia90** [comment]
> See #1867
> 
> Will be fixed.

Hey Rem0o thanks! I also wanted to let you know that it might be related to the configuration files. For instance I had 2 configuration files, the default "userconfig" and one I created myself. When I have this issue I have to delete the userconfig and cache files. Then I re-open FanControl and lastly I load my custom configuration file.
Hope this information helps :)

**Comment by Rem0o** [comment]
The issue occured if a specific dialog wanted to pop-up as the programs started. That popup only occured if a specific error occured with a configuration, hence why it might/might not happen depending on the config.
