### ISSUE TITLE
[Feature Request] Nvidia 30xx FE cards zero rpm

### ISSUE THREAD

**Issue by evoandroidevo** [Rem0o/FanControl.Releases#189]
I know that these cards have zero rpm but only if nothing is controlling the fan curve to get around this i was think maybe we could set a temp on a fancontol and if its below that temp could it disable the control of that fan and then when the temp goes back up have it auto turn on back to the curve. i dont know if this would work but doesnt hurt to ask thanks for making this its the simplest fan control software out there and i love it

Example:
![Example1](https://i.imgur.com/4eOS9by.png)
![Example2](https://i.imgur.com/ebmXyEq.png)

**Comment by Rem0o** [comment]
I won't do any "go arround this issue" kind of hacks, since it is a specific issue with the driver somehow not acting the same for those cards. Until there is an available way to set 0 RPM, I won't try to tackle this issue.
