### ISSUE TITLE
Turning off DC fans

### ISSUE THREAD

**Issue by paekbum** [Rem0o/FanControl.Releases#1892]
is it safe to turn DC fans off completely using fancontrol? i read something about DC fans burning due to voltage?

thx

**Comment by Rem0o** [comment]
Running a DC fan at a non-zero voltage where it's not enough to make a fan spin could cause such issue.

For EG:  you set 17% on a fan that needs 34% to actually start spinning.

**Comment by paekbum** [comment]
right but turning them completely off as 0% is ok?

**Comment by Rem0o** [comment]
Yes that's ok, as long as your motherboard allows it

**Comment by mgth** [comment]
Then does the soft take care of that ? I mean I see that when we are inside stop/start value you force start value until the fan actually start witch is nice. I cannot see if the fan is forced to 0 when the value is actually under stop value. 
I think it would be even better to have a setting percent where under you stop, upper you force to smallest spinning speed.
