### ISSUE TITLE
Temperatures stuck and not updating

### ISSUE THREAD

**Issue by Bonsai2509** [Rem0o/FanControl.Releases#1893]
My CPU and GPU temperatures are stuck and fan control keeps reloading but it doesn't change. Sometimes I have to restart my pc several times for it to finally start working again and update the temperatures.

**Comment by Rem0o** [comment]
Asus board?

Go into sensor setting, and uncheck embeddedEC.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1867.

will be fixed.
