### ISSUE TITLE
Fan Control lowers screen refresh

### ISSUE THREAD

**Issue by Noobgonewild** [Rem0o/FanControl.Releases#1899]
I am using a Dell 27' 165hz refresh monitor. My current OS is Windows 11. I noticed that when I change a setting, try to close the program and the "save settings" window pops up, it's low FPS. Then, investigating further, i placed the Fan Control window in front of the area where windows start bar would open and clicked it. The animation on the start bar were awful, low fps. So i opened the "UFO test".
With fan control closed (minimized to tray), i was getting 165 fps, no problem. With fan control opened, all frames dropped to 34 fps. I tried with different windows and programs to lower the fps and i couldn't replicate it, so Fan Control is the only culprit here. Every time when Fan Control is opened, all windows animations lower in fps; not just windows animation though, all fps are somehow lowered.

There are no logs since this is not an event to log. I will add some screenshots i guess.

My specs:
CPU: i5 9600k
GPU: RTX 3070
RAM: 32GB
SSD: M.2 NVME
![2023-07-08 13_10_49-UFO Test_ Multiple Framerates — Mozilla Firefox](https://github.com/Rem0o/FanControl.Releases/assets/138976168/8e3c023f-abec-4b9d-be23-022d51f263e8)
![2023-07-08 13_10_16-UFO Test_ Multiple Framerates — Mozilla Firefox](https://github.com/Rem0o/FanControl.Releases/assets/138976168/fd35033e-5d63-4aa0-8b37-9d8422fb4dc9)

**Comment by Rem0o** [comment]
Known issue with WPF.  There are a few workarounds listed here: 
https://github.com/dotnet/wpf/issues/2294

**Comment by Noobgonewild** [comment]
fixed it using this method:

![2023-07-08 23_37_28-Solved_ Low Frame Rate with Desktop App - The Spotify Community — Mozilla Firefo](https://github.com/Rem0o/FanControl.Releases/assets/138976168/be9c8842-1011-4c13-88ea-f401e919e235)


Thanks!

**Comment by AndreaBaccolini** [comment]
> fixed it using this method:
> 
> ![2023-07-08 23_37_28-Solved_ Low Frame Rate with Desktop App - The Spotify Community — Mozilla Firefo](https://github.com/Rem0o/FanControl.Releases/assets/138976168/be9c8842-1011-4c13-88ea-f401e919e235)
> 
> Thanks!

I don't have that setting in my NVIDIA control panel.
