### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by Swenerick** [Rem0o/FanControl.Releases#19]
Hi,

I would love to see two features:

It would be great to have an option to force the fan to hold at a certain speed when a component (let's say the GPU) reach a temp (defined by the user). For instance, if the GPU reach 75 degrees the fan(s) will maintain the desired speed until the GPU temperature goes down to 55 degrees (just as exemple). It could be an option in the graphs (?) 

And the second one is about a kind of QCP (quick control panel) with simple icons for differents speeds for all fans. The panel could be personalized by the user so he can choose how many steps he wants (thru the genius "+" sign (simple and so neat)) (as exemple : 4 steps for stop - low - half - full).

I hope I explained well enough :)
Greetings

**Comment by Rem0o** [comment]
For your first idea, would a new fan curve type do the trick? 

I would have the following parameters:
* Load temp
* Idle temp
* Idle fan speed
* Max fan speed

Kinda like the linear, except it would not do the linear transition and stick to the load fan speed until the fan speed reaches the idle temp.

**Comment by Swenerick** [comment]
Hi,

This sounds really good!

Thank you!

August 20, 2020 4:00:00 AM CEST Rem0o <notifications@github.com> wrote:

For your first idea, would a new fan curve type do the trick?
I would have the following parameters:Load tempIdle tempIdle fan speedMax fan speed
Kinda like the linear, except it would not do the linear transition and stick to the load fan speed until the fan speed reaches the idle temp.

**Comment by Rem0o** [comment]
Took me 10 minutes to code and get a sample working. 
My only concern is how to name it!

Target fan curve?
Load fan curve?

Help me out here.

**Comment by Swenerick** [comment]
Target seems ok to me :)

August 20, 2020 3:52:16 PM CEST Rem0o <notifications@github.com> wrote:

Took me 10 minutes to code and get a sample working.
My only concern is how to name it!
Target fan curve?
Load fan curve?
Help me out here.

**Comment by Rem0o** [comment]
Will be in the next release. Stay tuned.

**Comment by Swenerick** [comment]
Wow, great! :)

August 20, 2020 9:51:16 PM CEST Rem0o <notifications@github.com> wrote:

Will be in the next release. Stay tuned.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V45
