### ISSUE TITLE
Can't Edit Curves

### ISSUE THREAD

**Issue by benburns** [Rem0o/FanControl.Releases#190]
I have added a graph curve, but when I click the Edit button nothing happens. Is this the correct way to edit a curve?
![Edit](https://user-images.githubusercontent.com/2476369/111926108-8a3f1d00-8a79-11eb-8c4f-835b6e582096.png)

**Comment by Rem0o** [comment]
This version I accidently uploaded a version with a bug and quickly uploaded the fix without changing the version number. You must have caught the erroneous version. Just run the updater.exe again or download fresh.

**Comment by benburns** [comment]
Thanks, the new exe is working.
