### ISSUE TITLE
Gigabyte A5-K1 Laptop

### ISSUE THREAD

**Issue by alec-jensen** [Rem0o/FanControl.Releases#1902]
FanControl doesnt detect any controls.

**Comment by Rem0o** [comment]
From the FAQ:

Q: There is no control cards / control cards are missing / control cards are not changing my fan speeds, what's the issue?
A: See [Issues and hardware compatibility](https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility).
