### ISSUE TITLE
Not detecting fans, the fan controll only detect 7/8 of my fans and 2/3 gpu fans

### ISSUE THREAD

**Issue by khuedragonstar** [Rem0o/FanControl.Releases#1908]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
FanControl doesn't detects fans per say, it detects fan channels, or headers.   GPUs don't have 3 fan headers even if they have 3 fans, most of them have 2 channels, 2 fans being on 1 channel. 

Also, see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
