### ISSUE TITLE
[v162] Program keeps reloading, doesn't exit properly

### ISSUE THREAD

**Issue by Tharn** [Rem0o/FanControl.Releases#1910]
**Describe the bug**
Starting Fan Control v162 for the first time after boot (many minutes after), all the cards will disappear and re-appear several times before the program has loaded properly. The notification area temperatures also disappear and reappear several times before the program loads "successfully". After this happens, when I click on "exit", whether in the icon context menu or from the hamburger menu, the program will not exit. It is still responsive and I can do other things like turning cards on and off, but I cannot exit cleanly. And turning cards on and off does not change the fan RPMs at all, it seems the program is frozen entirely with the UI still responsive.

It will sometimes exit properly, but the restart loop always happens - with icons vanishing and reappearing, cards vanishing and reappearing even if I click "Cancel" when it tries to fix the sensors or save the config.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
There is nothing written in the log when this happens.

**Relevant hardware specs and setup**
MSI Tomahawk Max B450
Ryzen 3700X
Asus Dual OC 3060 Ti
Non-PWM Case Fans
Wraith Prism

**Comment by byteen88** [comment]
Having the same issue, even in v164

**Comment by Tharn** [comment]
Since reinstalling fresh and not moving the install folder to C:\Programs I have not had the issue pop up again. Do the other people experiencing this by any chance use system parent folders?

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1867

Will be fixed in the next release.

**Comment by Tharn** [comment]
Not fixed in V168 unfortunately. And the issue you linked doesn't seem to mention cards disappearing and Fan Control reloading repeatedly right at startup. If that's in there somewhere, apologies.
