### ISSUE TITLE
Intermitent Fan Detection Issue

### ISSUE THREAD

**Issue by DBenS** [Rem0o/FanControl.Releases#1911]
**Describe the bug**
Sometimes and always in the first initialization (after the boot), the program warns about detection failure. Sometimes it claims for 1 undetected sensor, sometimes for 2.  

It is interesting note that if I press CANCEL or if I close the application and run it again, most of time it does not send this message. Another thing is the fact of, although the message appears, it seems everything is OK, I mean, I see the sensors I had set (but obviously not the hidden ones) **and the program controls the FANs as I set before** .

![image](https://github.com/Rem0o/FanControl.Releases/assets/13090884/cfc3ded9-9793-4b0d-883c-27d74bf4940a)

One thing must be considered: since the AUTO-DETECT identify all sensors and some of them we do not suppose to use in the FAN control, would be interesting have a way to SUPPRESS them of the list of  the auto detection (perhaps when we HIDE them).

**Is there a log.txt file next to FanControl.exe with recent date entries?**
There is no LOG in the FAN folder.

**Relevant hardware specs and setup**
I'm using an ASUS MAXIMUS FORMULA Z690 with NVIDIA GTX 1080-TI and LIAM-LI AIO 360.

**Comment by Rem0o** [comment]
Go into sensor settings, and disable Embedded EC. Then save.

**Comment by DBenS** [comment]
Do you mean edit directly the JSON fle?  I say this because I don't have the Embedded EC in my panel (I guess).

**Comment by DBenS** [comment]
I edited the JSON file and after some error messages I saved the configuration.
It seems be solved the problem accordingly.
Thank you.
