### ISSUE TITLE
Lian Li Uni fans not being detected/controlled

### ISSUE THREAD

**Issue by Miyazono1** [Rem0o/FanControl.Releases#1917]
so i just replaced the old cheap fans i had with some Lian Li Uni fans, but they're not being detected in fan control. my NZXT AIO fans are being detected and controlled properly, but the others are not. there are 2 other fans being detected and paired with speed controllers, but i have no idea what they are, as they seemingly do not respond to RPM changes. the Lian Li fans are being detected fine in both the BIOS and in Lian Li's own software, but not in fan control.

**Comment by Rem0o** [comment]
Have you plugged them the same way you had your old fans? If so no change is required. 

If you plugged them differently, then it's another story.  Keep in mind FanControl doesn't detects fans, it detects fan headers. If you plugged them onto other headers that never were detected, then you got your answer.

**Comment by Miyazono1** [comment]
> Have you plugged them the same way you had your old fans? If so no change is required.
> 
> If you plugged them differently, then it's another story. Keep in mind FanControl doesn't detects fans, it detects fan headers. If you plugged them onto other headers that never were detected, then you got your answer.

only difference was that i plugged them in to cha_fan2 instead of 3. but even re-running the assisted setup doesn't pick them up properly. it detects a total of 3 fans, and i'm not even sure what the third one could be, i only have 2 sets of fans. what mode should i have all my fans set to in the BIOS? i usually have them all set to auto. i changed nothing and now FC isn't even controlling the AIO fans that were fine 10 minutes ago lmao.

**Comment by Rem0o** [comment]
Any change in the BIOS setting you made since? You should have any auto control in the bios off, so set something like a fixed speed that is tolerable at bootup.

**Comment by Miyazono1** [comment]
> Any change in the BIOS setting you made since? You should have any auto control in the bios off, so set something like a fixed speed that is tolerable at bootup.

so i shouldn't have any kind of curve set in the bios at all? just set the control mode and a fixed RPM?? i'll give that a shot. i assume PWM mode is the correct one?

**Comment by Rem0o** [comment]
>  i assume PWM mode is the correct one?

There is no "correct". Some people have better results with DC.

**Comment by Miyazono1** [comment]
> > i assume PWM mode is the correct one?
> 
> There is no "correct". Some people have better results with DC.

so is it possible that even though these lian li fans (i assume) are supposed to be controlled via PWM, since that's the kind of wire it was connected with, that might be what's causing the issue of them not being controlled in FC?

**Comment by Miyazono1** [comment]
well i can say for sure that i'm stumped. i've tried every combination of settings i can think of, but FC just will not control these fans, the same way they didn't control the fans i replaced. it's really weird and really annoying, since other software does control those fans, but FC does not.

**Comment by Rem0o** [comment]
> the same way they didn't control the fans I replaced

Ahhh, I assumed the previous ones were working, my bad.

**Comment by Miyazono1** [comment]
> > the same way they didn't control the fans I replaced
> 
> Ahhh, I assumed the previous ones were working, my bad.

yeah no, the set of fans i replaced were not being controlled by basically ANY software, which is why i wanted to replace them, but now with the new ones also not being controlled, it's getting annoying lmao.

**Comment by Rem0o** [comment]
It's never about the fans themselves, it's all about what you plug them into.

**Comment by Miyazono1** [comment]
> It's never about the fans themselves, it's all about what you plug them into.

well they're plugged into the right headers, lian li's software picks them up no problem, they read normally in the BIOS, so idk what it could be.

**Comment by Rem0o** [comment]
Are they powered via a hub?

**Comment by Miyazono1** [comment]
> Are they powered via a hub? Seems like they are powered via a USB hub and only the RPM readings gets to the mobo.

they are, yes. so was my old set. both power and RGB are through the hub.

**Comment by Rem0o** [comment]
Well FanControl doesn't support that hub natively. 

https://github.com/EightB1ts/FanControl.LianLi

**Comment by Miyazono1** [comment]
> Well FanControl doesn't support that hub natively.
> 
> https://github.com/EightB1ts/FanControl.LianLi

and just like that we're in business. thanks a ton. and out of curiosity, is there a list of plugins i can go through so see if there's any others i could be using? i couldn't find any kind of curated list when i initially set up the software.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#plugins

**Comment by Miyazono1** [comment]
> https://github.com/Rem0o/FanControl.Releases#plugins

thanks. oh and while i have you lol, idk if i'm just dumb or what, but i could not for the life of me figure out how to download the plugin for AMD gpus. there was no proper download for it, only a link to appveyor, and i have no idea what to do from there lmao.
