### ISSUE TITLE
ECEmbedding: issues even disabled

### ISSUE THREAD

**Issue by DBenS** [Rem0o/FanControl.Releases#1919]
I had disabled ECEmbedding in my configuration file to avoid errors as sensors undetected. It functions normally but today, when I turned on the computer and manually call FanControl, the error appeared again and a LOG file was created. So, I simply end the FanControl program and call it again: the error did not appear. 

Interesting note that the video error message about LOG reported something about "ECEmbedding" - which is disabled in my settings.

Follows the [LOG file](https://drive.google.com/file/d/1nqq0JkKQGRLyg_VC_rJuvZh5tv6-yhCy/view?usp=sharing) and the active [configuration file](https://drive.google.com/file/d/1PF6qSL35Y8wiZPiqX2ZQF_xz4EGPoKsv/view?usp=sharing).

Thank you.

**Relevant hardware specs and setup**
ASUS MAXIMUS FORMULA Z690 with INTEL 12900KF and drivers up to date.

**Comment by Rem0o** [comment]
Have you edited the file manually at some point? Seems like it couldn't parse the value for the field EmbeddedEC.

**Comment by DBenS** [comment]
Yes, I set the "EmbeddedEC = false;" directly in the Configuration file, once I didn't know where exactly to make this modification: 

![image](https://github.com/Rem0o/FanControl.Releases/assets/13090884/fc479f8f-5afe-4480-9f52-a48b5c2bbb4b)

Please note that I utlized Notepad++ to edit the file and there are neither special characters nor weird control-characters in the line:

![image](https://github.com/Rem0o/FanControl.Releases/assets/13090884/5add3d60-1eba-4a69-8d54-a052975bf9e5)


**Just in time:** today I updated the version and I had the same error ("_59 sensors expected but found 58_") even with this line disabled. I edited again the config file changing this number to 58 and it seems to had corrected the problem.

![image](https://github.com/Rem0o/FanControl.Releases/assets/13090884/afb3938d-8e35-4d7c-8bf9-8338b074c4d6)

But the newest version seems to have a problem with Dialog:
![image](https://github.com/Rem0o/FanControl.Releases/assets/13090884/0011015e-812d-4496-a638-8fa4d7c3d455)

The Configuration file and the LOG.txt are [available here].(https://drive.google.com/drive/folders/1FRMxdWE0tgpBGOlJF46AdIQpjwhE4D1q?usp=sharing) to your review.

Kind regards.
