### ISSUE TITLE
FanControl waking PC from sleep

### ISSUE THREAD

**Issue by CZonin** [Rem0o/FanControl.Releases#192]
Today I started noticing that as soon as my PC went to sleep, it would instantly wake itself back up. After it happened a few times I checked to see what was causing it and it said that FanControl was causing the wake. I also checked in Event Viewer and it said the same thing.

![Screenshot 2021-03-22 192207](https://user-images.githubusercontent.com/67965669/112070512-33eae080-8b44-11eb-813f-1eff441409e6.png)

**Comment by Rem0o** [comment]
Wake timer? I don't use any of that. 
You are also the first person to report this. I honestly have no idea.

**Comment by CZonin** [comment]
> Wake timer? I don't use any of that.
> You are also the first person to report this. I honestly have no idea.

Ya I'm not sure. It seems to have fixed itself though.
