### ISSUE TITLE
[Enhancement Request] Sample boxes inside Theme Selector page

### ISSUE THREAD

**Issue by jeyrella** [Rem0o/FanControl.Releases#1921]
**Describe the bug**
Now that the Theme Selector has moved to its own hamburger selector page, the result of the selections aren't visible until you switch out of theme page.

Not only that, with the _Controls_ and _Curves_ boxes having slightly differing hues, it is difficult to envisage the result of the change until the change is actually made.

How about for efficiency and ease, having a sample of the result right next to the selectors in the Theme page, à la:

![image](https://github.com/Rem0o/FanControl.Releases/assets/46089380/c0815207-8bb1-4913-a16a-f36318e6841b)

**Comment by Rem0o** [comment]
Actually thought about it, it's in my backlog.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V164

Hope you like it.

**Comment by jeyrella** [comment]
@Rem0o Looking great!  Thanks :)
