### ISSUE TITLE
Improved Faster Configuration Switching

### ISSUE THREAD

**Issue by hl2guide** [Rem0o/FanControl.Releases#1927]
**Describe the bug**
Please improve the configuration switching speed (load time) if possible.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
N/A

**Relevant hardware specs and setup**
N/A

**Comment by Rem0o** [comment]
Quick note. If all your configs have the same sensor settings, the switch time will be quick, as no reinitialization of the sensors will be required.  As soon as the sensor settings are different, a full refresh will be performed before switching config.
