### ISSUE TITLE
Alle system fans header will not respond

### ISSUE THREAD

**Issue by DennistheCook** [Rem0o/FanControl.Releases#1929]
issue here is only the Cpu header and Cpu_Opt header are detect by fan control 163V .
All system fan/pump header will not respond, fans are visible in HWifno.

Gigabyte B5650E Master, Noctua Cpu cooler and case fans.

**Comment by Rem0o** [comment]
You may enable InpOut, which has control over gigabyte peculiar dual chip setup:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/d15b26d2-319f-4be9-b6a9-b36101248993)

**Comment by DennistheCook** [comment]
InpOut check but no response.

**Comment by DennistheCook** [comment]
Mebie mine donatie was to small.....working system fan headers $10 :P
Keep up the good work Rem0o...

**Comment by DennistheCook** [comment]
I narrot it down to system fan/pump header that are not responding/grey out in Fan control. Used HWinfo as plugin, system fan header 3 is responding and working. It's working but system fan/pump not responding/grey out.
<img width="906" alt="Fan control 2023-07-22 123511" src="https://github.com/Rem0o/FanControl.Releases/assets/773822/1c092742-478c-4da2-8a7e-413af5e3f7d8">

**Comment by Rem0o** [comment]
See hardware and compatibility in README.
