### ISSUE TITLE
V73 file sensor not found

### ISSUE THREAD

**Issue by Bear21** [Rem0o/FanControl.Releases#193]
Upgraded from V70 to V73 and file sensor stopped working stating that "FileSensor/x.sensor" can't be found. i moved my x.sensor file into a FileSensor subdirectory but it didn't help. neither my sensor file or the example sensor file was selectable as a sensor.

**Comment by Rem0o** [comment]
+ sign => file sensor => put the name of your file.

**Comment by Bear21** [comment]
thanks, I did re-read the readme looking for instructions in this after the update before posting ^^ it would've been awesome to either detect the use of a file sensor when upgrading and display a message or automatically add the new file sensor item to the config based on the old config. Could have been a smooth transition.
