### ISSUE TITLE
When updating nVidia GeForce drivers, Fan Control gets into error loop

### ISSUE THREAD

**Issue by TheAndyMac** [Rem0o/FanControl.Releases#1931]
_Not 100% sure if this is a bug or a feature request as it sort of sits between them._

**Describe the bug**
If nVidia GeForce drivers are updated while Fan Control is running, it comes up with an error which you can accept or cancel and it repeats this error. Understand that the lack of sensors/controls during the update probably causes this, but maybe there is a way to sense the update process and come up with a different message, simply provide more info in the error message, or provide options on the error message dialog box to close Fan Control and/or suspend it for a short period of time.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/12092447/log.txt)

**Relevant hardware specs and setup**
- Asus ROG Maximus XI Hero (Wi-Fi) Z390 Motherboard
- Intel Core i9-9900K, G.Skill Trident Z RGB 16GB (2x8GB) DDR4
- Noctua NF-A15 140mm PWM Chromax.Black Fans x2
- Noctua NH-U12S Ultra-Quiet CPU Cooler & NF-F12 Fan
- ASUS Dual OC GeForce RTX 2070 Overclock Edition 8GB PCIe3 Graphics Card
- 4TB Samsung 8609 EVO SATA III 6Gb/s 2.5" SSD

**Comment by Rem0o** [comment]
See V180, should handle it better.

**Comment by TheAndyMac** [comment]
Thank you.
Andrew
