### ISSUE TITLE
fan control booting problem

### ISSUE THREAD

**Issue by SvdNist** [Rem0o/FanControl.Releases#1932]
hi i downloaded the lestest version (v163) and when i click on the application file after i unzipped the folder it says: 'an unexpected error accured. see log file for details.' 
im not very good with laptop i hope someone can help me..
thx! ;P

my laptop specs:  Acer TravelMate 6592
Processor: Intel Core 2 Duo T7300 2 x 2 GHz (Intel Core 2 Duo)
Graphics adapter: Intel Graphics Media Accelerator (GMA) X3100
4gb ram, ssd128 gb

**Comment by Rem0o** [comment]
FanControl is not compatible with laptops.

**Comment by Rem0o** [comment]
Might want to take a look this way: https://github.com/hirschmann/nbfc
