### ISSUE TITLE
Losing communication with D5 pump - shuts pump down

### ISSUE THREAD

**Issue by TechLife127** [Rem0o/FanControl.Releases#1936]
First: Awesome work!  I learned of this from Jayztwocents and have been using it on every rig I build since!

I've finally run into an issue though, and of course it's on the new build I did for me...

I've been battling this for days.  Even after the update this afternoon.  Everything is perfectly fine until one of my flow sensors starts beeping.  I open fancontrol and sure enough, one of the D5's has a single digit number and a question mark next to the pump.  I switch the slider for that pump back and forth, spins back up, beeping stops, good for a while again.

I have two loops.  One for CPU, one for GPU.  Both are using EK D5 pumps purchased in the last 2 months.

I have disabled literally everything you can imagine that may interfere with fans/pumps. Log is attached, please let me know if I can forward any additional information that will assist in locating the problem.

P.S. It just happened twice in the last 10 minutes.  The second time, it looks as if it took the fans with it
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/12135302/log.txt)

**Comment by TechLife127** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/44595192/445b4eb1-fdbe-4946-95bf-f61dc0c8a1a1)

**Comment by DfrostX** [comment]
From your log, the Aquacomputer plugin is failing and making FanControl throw an error.

7/21/2023 10:16:29 AM: AquacomputerPlugin: Closing.
7/21/2023 10:16:29 AM: Unhandled exception in FanControl v163.0.0.0
7/21/2023 10:16:29 AM: System.NullReferenceException: Object reference not set to an instance of an object.

Do you have the AquaSuite software/service running at the same time as the Aquacomputer plugin? I'm not sure how well the 2 can play along running at the same time.

I own an Highflow Next and found out that using the HWinfo plugin to read the the temp from it in FanControl is by far the most reliable option. I would qualify it of flawless. Note that I do not use Aquasuite or it's service at all... Maybe give it a shot?

**Comment by TechLife127** [comment]
Thank you so much for the quick reply. I spent so much time on fans and pumps, I never considered the Aquacomputer. Medevil84 actually updated that plug-in for me yesterday since I have two in the same system which he hadn’t thought of. Works awesome since!

Anyway, I disabled the Aqua service and Fancontrol is extremely happy with life. Zero errors. Thank you, thank you, thank you for everything

Keep up the awesome work on FC and I wish you the best!

**Comment by DfrostX** [comment]
I had deleted my message since I thought it wasnt the issue... But I guess you received it as an email notification.

Im gladb it helped!

**Comment by TechLife127** [comment]
I did, and you were spot on

**Comment by Rem0o** [comment]
Seems solved. Will close.
