### ISSUE TITLE
v73 - Loading Configuration Does Not Apply Curves

### ISSUE THREAD

**Issue by LiamShinkso** [Rem0o/FanControl.Releases#194]
It no longer applies configurations upon loading them.
If you then attempt to load a different config it bring up the "config has changed, do you want to save?" box.
Selecting "no" will then apply the config you initially attempted to load.
Works both ways with the two configs I have.

**Comment by Rem0o** [comment]
From the README

_Q: There is no control cards / control cards are missing / control cards are not changing my fan speeds, what's the issue?
A: Your motherboard's SuperIO chip is not supported / badly supported, see the Issues section._

**Comment by Rem0o** [comment]
I'm sorry, I wrote my answer on the wrong issue.

**Comment by deartonym** [comment]
I have exactly the same issue. thought the controls/curves will be loaded below, the correct curves are not applied.

**Comment by BB-66** [comment]
I have the same issue here for the past 3 versions (v73 to v76). This happened before and was fixed, it's happening again now :(
