### ISSUE TITLE
Excellent piece of software, but it doesn't minimise at startup

### ISSUE THREAD

**Issue by vices90o** [Rem0o/FanControl.Releases#1940]
No matter how many times I check the Settings > Start minimised box, it always shows the maximised window at startup. Thanks if you can fix it... Tried updating to no effect

**Comment by Rem0o** [comment]
Do you get any dialog popup within the software as it comes up?

**Comment by rknauber** [comment]
I'll try and get more info but this started happening I think with the latest update. I do remember I unchecked the minimize option, Saved, and then rechecked and saved again. Is still doing it. Will check more later tonight or in the morning.

**Comment by rknauber** [comment]
Forgot to reply back that after doing the steps I described above it seems to have resolved it for me for at least the past 2 days.

**Comment by vices90o** [comment]
I tried what rknauber suggested, but no luck at all... Also tried adding the -m argument to the scheduled task action, but same result. I even tried to change the "WindowsState": 0  to 1 in the CACHE file (it always returns to a 0 value), and no change either... Anyway, it's an excellent program, so I guess I'll just keep closing the window manually until the next update.

**Comment by Rem0o** [comment]
[log_show_window_reason.zip](https://github.com/Rem0o/FanControl.Releases/files/12185811/log_show_window_reason.zip)

OK since I can't figure it out, here's a special version with added logs for whenever the software decides to show the main window. It will say the exact reason. 

@vices90o  Please run this and send the corresponding log.  Copy your configuration folder to this instance so you keep your settings.

**Comment by vices90o** [comment]
@Rem0o Thanks a lot for checking this issue... This is the result that I got (I hope it's the right file):

27 jul. 2023 10:50:08: Showing window because: Start minimized setting :False, -w False, -m False 

'Start minimized' was checked in Settings; 'Start with Windows' was also checked (30s delay), as well as 'Check for updates'.

**Comment by vices90o** [comment]
@Rem0o I ran it again with the 'Start minimized' box unchecked, and the result was the same:

27 jul. 2023 11:11:47: Showing window because: Start minimized setting :False, -w False, -m False

**Comment by Rem0o** [comment]
@vices90o  We are getting closer. 

Seems like at that time, the start minimized setting is false.

> 'Start minimized' was checked in Settings 

Was it checked after the fact when the window opened?

Also, do you have multiple cache files? You should look at the one in the "fancontrol/configuration" folder.

**Comment by vices90o** [comment]
@Rem0o 

>  Was it checked after the fact when the window opened?

Yes, it was checked...  However, if I uncheck the box, then save the configuration, quit the program and restart it again, it remains unchecked. 

> Also, do you have multiple cache files? You should look at the one in the "fancontrol/configuration" folder. The setting for start minimized should be in that CACHE file.

No, there is only 1 CACHE file... In this file, if the box is unchecked -> "StartMinimized": false  ;  if the box is checked -> "StartMinimized": true  

However, the log seems to show always the same result, and the window is always maximized:

27 jul. 2023 10:50:08: Showing window because: Start minimized setting :False, -w False, -m False 
27 jul. 2023 11:27:45: Showing window because: Start minimized setting :False, -w False, -m False 
27 jul. 2023 12:07:25: Showing window because: Start minimized setting :False, -w False, -m False 
27 jul. 2023 12:14:00: Showing window because: Start minimized setting :False, -w False, -m False 

Hope this helps.

**Comment by Rem0o** [comment]
Can you send me your whole fan control folder as a zip?

**Comment by vices90o** [comment]
@Rem0o

> Can you send me your whole fan control folder as a zip?

OK, sure... 

[FanControl.zip](https://github.com/Rem0o/FanControl.Releases/files/12187440/FanControl.zip)

**Comment by Rem0o** [comment]
@vices90o  I literally opened your instance and it started minimized.  Are you referring to when you boot up your computer?

if so, could you uncheck and recheck start with windows so that the task in the task scheduler gets recreated?

**Comment by vices90o** [comment]
@Rem0o Hello again... Yes, it didn't start minimized when I booted the computer, but also when I checked/unchecked, quit the program and restarted it... However, I browsed through the registry and deleted every FanControl-related entry, deleted the scheduled task and removed the program folder; then I reinstalled it again from scratch, and now it's working perfectly.

I have no clue what the underlying conflict or issue was (or if I made a mess trying to fix the settings), but now it works like a charm... Thanks a lot for your help and your time, Rem0o!

**Comment by Rem0o** [comment]
Would have liked to know the specific mix of conditions you created to make that effect happen, but glad you got it sorted out.

Also,

Registry entries? What registry entries? Fan Control doesn't use any specific registry entry, except for the scheduled task itself.

**Comment by vices90o** [comment]
> Registry entries? What registry entries? Fan Control doesn't use any specific registry entry, except for the scheduled task itself.

Well, there were some of them (unfortunately I can't remember the keys), but I guess they were just cache stuff... Anyway, I deleted all the ones I could find through the search function., just in case.

Sorry for not being of any help with your question, but, as you suggested, my guess it that the task needed to be recreated and that's what fixed the issue.
