### ISSUE TITLE
software does not detect cpu fan

### ISSUE THREAD

**Issue by Federation60** [Rem0o/FanControl.Releases#1941]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

Software detects all other fans i have installed such as my cpu and case fans but it doesnt detect the cpu fan, it knows its there are records the rpm but i cant control it.
cant find any log.txt in the folder
![image](https://github.com/Rem0o/FanControl.Releases/assets/137520766/9f5b61f9-63ab-4004-8c21-d7d97fb1008b)

**Comment by Federation60** [comment]
also, the cpu fan controller has no effect on the actual speed on the cpu fan 
![image](https://github.com/Rem0o/FanControl.Releases/assets/137520766/650243a6-e90b-4805-8fa5-eac434e439cb)

**Comment by Rem0o** [comment]
See hardware and compatibility in README.
