### ISSUE TITLE
Detects cpu/chassis fans only if CPUID HWMonitor is running.

### ISSUE THREAD

**Issue by gustavomgama** [Rem0o/FanControl.Releases#1943]
I tested with a fresh config file and it is 100% because of the hwmonitor running. 
MOBO:
EX-A320M-GAMING

**Comment by gustavomgama** [comment]
No plugins installed also, fresh download and userconfig file.

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/1171
