### ISSUE TITLE
CPU fan no longer working after 162 update

### ISSUE THREAD

**Issue by Arkandos** [Rem0o/FanControl.Releases#1944]
**Description**
After updating from 149 (I think) to 162 the CPU fan control no longer works as shown on the screenshot. It does not respond to curves nor manual control. All other fan controls seem operable still.

![image](https://github.com/Rem0o/FanControl.Releases/assets/5114247/6daea812-1eb8-4eed-9caa-5735ffcd2966)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No, last entry was a month ago.

**Relevant hardware specs and setup**
Intel(R) Core(TM) i7-9700K
Gigabyte GA-Z97X-Gaming 3 ATX LGA1150 Motherboard

**Comment by Azyrion** [comment]
[had the same issue](https://github.com/Rem0o/FanControl.Releases/issues/1835#issuecomment-1635973629) but v164 seems to have solved this issue for me.
