### ISSUE TITLE
No Edit Button on Fan Curves?

### ISSUE THREAD

**Issue by MrShuuurn** [Rem0o/FanControl.Releases#1945]
There doesnt appear to be an edit button on my fan curves, tried deleting and adding ect.

All I can do is set linear curve values, not able to edit graph ones, any ideas?

<img width="477" alt="fan control issue 01" src="https://github.com/Rem0o/FanControl.Releases/assets/134025140/55e45c61-6181-447a-943e-39e9a68d55bf">

**Comment by Rem0o** [comment]
I think you got the only color combo from your theme that actually hides the edit button on the graph. It's still there by the way. Just look at the color of the dot in the graph, same thing.

**Comment by MrShuuurn** [comment]
Thanks @Rem0o that was exactly the issue
