### ISSUE TITLE
v164: changed font in tray

### ISSUE THREAD

**Issue by pult** [Rem0o/FanControl.Releases#1949]
On win 11, the font in the tray has changed.
? Is there any way to adjust the font ?

**win 11**
![зображення](https://github.com/Rem0o/FanControl.Releases/assets/1542721/c0fee950-e96c-4d38-88d2-893f08e5f7df)

**win 10**
![зображення](https://github.com/Rem0o/FanControl.Releases/assets/1542721/364c2407-7f92-4963-b07f-a14b9041cc71)

**Comment by Rem0o** [comment]
Make sure you got the same scaling setting.

**Comment by pult** [comment]
100% in both cases.
win-11 v162 screens: https://github.com/Rem0o/FanControl.Releases/issues/1879

**Comment by pult** [comment]
Sorry: After restart v164 painting is normalized.
Probably, the previous launch(v164) took place at a time when the screen was of a different size

**Comment by Rem0o** [comment]
@pult  Ahhh, yea if you got screens of different resolution, the scaling will be done using the screen the window originated on.

**Comment by pult** [comment]
Thank you. 
You are right, a monitor (100%) is connected to the laptop (>100%).
