### ISSUE TITLE
the program does not see all the fans

### ISSUE THREAD

**Issue by MadMaxx-over** [Rem0o/FanControl.Releases#195]
mb asus tuf b450 pro
5 arctit fans are connected. 3 pcs p12 via hub. 2 pcs p14
also 2 fans from the fuma 2 cooler are connected to the fan CPU port

the program sees only the fans p12, and the video card
p14 and fuma 2 does not see!

https://i.imgur.com/LviMAnX.png
https://i.imgur.com/DAfSc9u.png

**Comment by Rem0o** [comment]
From the README

Q: There is no control cards / control cards are missing / control cards are not changing my fan speeds, what's the issue?
A: Your motherboard's SuperIO chip is not supported / badly supported, see the Issues section.
