### ISSUE TITLE
Feature Removal Request: Gigantic Enormous Popup when resuming from sleep

### ISSUE THREAD

**Issue by ericwj** [Rem0o/FanControl.Releases#1950]
Can you please entirely remove this Gigantic Enormous Popup that shows up when resuming from sleep?

If it'd be visible really short there is no point in showing it.
If it'd be visible for half minutes dragging out to minutes with a .1% probability (PASTA: in .1% of cases) it is so freaking annoying in the way of everything for so stupendously long periods!

.1% of cases doesn't sound bad enough. Murphys law demands on some computers it'll be shown in 10-50% of cases when resumindg from sleep!? idk idc I saw it and I couldn't continue working and it annoyed me tremendously that's for sure

It is very poor judgement to make it this big.
It is very poor judgement to make it stay in one spot (its not draggable to the edge of the window or under the taskbar to make it less brutally obtrusive, and this would just be a hacky workaround anyway).

I don't perform work on my computer with Fan Control.
Fan Control should be out of my way.
Management by exception. If you expect or have reason to still believe everything might be (become) OK, don't show the banner.

Please get this banner out of my way. Or make it configurable to be permanently suppressed unless there is a problem.

Please.

Regards

**Comment by Rem0o** [comment]
What "Gigantic Enormous Popup" are you referring to?  Screenshot?

**Comment by ericwj** [comment]
This is shown over productivity programs when the Fan Control window is minimized/closed to tray. Two minutes and counting by now. The size is over a quarter of the screen on 4k. You can render a whole essay on it.
<img width="320" alt="image" src="https://github.com/Rem0o/FanControl.Releases/assets/9473119/8184091c-bf30-4b89-9812-36bad4f05edd">

**Comment by ericwj** [comment]
3 minutes... Need I continue?

**Comment by ericwj** [comment]
And I can hear all fans are OK. It's doing this for no practical good.

**Comment by ericwj** [comment]
10 minutes is a nice round number. I must've pressed cancel with my fist last time. Except my monitor is unharmed.

**Comment by Rem0o** [comment]
No need to spam 4 messages, chill with the attitude.   Trying to help here and address your issue. 

Now there is 2 things:

First, yes, the dialog is too wide I agree. I will limit the width so that the text wraps and should make the footprint smaller. 

Second, the reason for this dialog is that when your computer goes to sleep, all fan control settings are reset by the motherboard.   FanControl must then effectively "restart" and reapply everything.   Until that restart is done, the software can't do anything, hence the dialog on top of the UI until its done.   It's configured to try up to 6 refreshes with a 5 second interval between refresh. Normally, the first refresh is enough and it takes a few seconds.   

In your case, it seems like refreshing process gets stuck somehow, hence why the dialog isn't closing.   Are you on the latest version (V164) ?

**Comment by ericwj** [comment]
Yes this is version 164.

The fans turn up when I command the sleep. The fans go silent sometime after resuming. I think even before I have a chance to see this popup, because I have to sign in first. So Fan Control did regain all control it needs. I think there needs to be no rescanning resuming from sleep, just regain command of what it already knows about. One shouldn't fiddle while my computer hibernates.

And yes unless there is a problem, I don't care to see whether it is enumerating devices or whatnot without explicitly asking for that information.

**Comment by Rem0o** [comment]
@ericwj  I found the issue for the dialog never closing.  Will be pushing an update with the fix sometime soon.

**Comment by ericwj** [comment]
Thanks millions! I'm impressed ;) Will try ASAP.

**Comment by Smyl3** [comment]
> The fans turn up when I command the sleep. The fans go silent sometime after resuming. I think even before I have a chance to see this popup, because I have to sign in first. So Fan Control did regain all control it needs. I think there needs to be no rescanning resuming from sleep, just regain command of what it already knows about. One shouldn't fiddle with hardware while the computer is asleep or hibernated.
> 
> And yes unless there is a problem, I don't care to see whether it is enumerating devices or whatnot without explicitly asking for that information.

Same here.
After sleep waiting for the dialog to close but never does.
