### ISSUE TITLE
[Enhancement] Add a 'Force start' percent control setting

### ISSUE THREAD

**Issue by mgth** [Rem0o/FanControl.Releases#1955]
It would be nice to have a setting percent witch would be between 0 and stop value that would force fan start even if when are under stop value. Now i trick the curve to obtain this but I feel that it make the curve less reusable.
Note that as it is not compatible with "minimum %" it could be an alternative usage of this value like maybe "[x] force start at minimum %" or even just change minimum comportement when the value is less than stop % (Might be confusing, I dont know)

**Comment by Rem0o** [comment]
Your whole paragraph is confusing. 

Why would you want to force start the fan if you are under the stop value?

**Comment by mgth** [comment]
As I see it, the curve is not specific to one fan, and I have one fan that starts higher than the others. I prefer to have it spinning a little to fast than not spinning at all. With the current behaviour, I have to create a specific curve for it with a flat part on the left. I think it would be better to have a per fan parameter that tell at witch percent we should ensure the fan is spinning (even if it emplies having it spinning faster).

**Comment by Rem0o** [comment]
Have you tried a simple offset on the control?

**Comment by Rem0o** [comment]
Or down, for that specific control.
