### ISSUE TITLE
v165 is broken, doesn't close

### ISSUE THREAD

**Issue by pookguy88** [Rem0o/FanControl.Releases#1959]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
You'll have to provide details.   
In what situation? Does it always does it?  What's your computer setup, OS?

**Comment by Wateraga** [comment]
Yeah I got this too, kept reinitialising over and over and wouldn't close, had to use task manager to close and then restart FanControl, it threw an error saying "expected 24 sensors but counted 23" until I clicked the "refresh sensors" button.. Seems to be working okay now

**Comment by Wateraga** [comment]
> Yeah I got this too, kept reinitialising over and over and wouldn't close, had to use task manager to close and then restart FanControl, it threw an error saying "expected 24 sensors but counted 23" until I clicked the "refresh sensors" button.. Seems to be working okay now

Actually it is sometimes throwing them sensor errors and repetetively loading the profile until I manually refresh and load profile.

When I close using the "X" button the tray sensors are refreshed which didn't happen on 164, not sure if related but definititely different.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1867

Will be fixed in the next release.
