### ISSUE TITLE
freezing system for one minute

### ISSUE THREAD

**Issue by DonKamili** [Rem0o/FanControl.Releases#196]
Hi, when fan control is starting with Windows or if I Start it manually it seems everything is slowing down so nothing is moving. It looks like the computer freezed. After a minute or so it starts up for a sec and freezes again for a minute and than I can work again and do everything. Using Windows 10.
I can reproduce it if i exit the control and start it up again.

I am using a comodo Firewall, maybe this is the problem?

**Comment by Rem0o** [comment]
> I am using a comodo Firewall, maybe this is the problem?

You tell me?
