### ISSUE TITLE
'LOAD CONFIGURATION" issue, from 'burger' drop down menu

### ISSUE THREAD

**Issue by eitaniel** [Rem0o/FanControl.Releases#1961]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

something is up with the 'burger' drop down menu to top right of the fancontrol window. with specific reference to using the 'load configuration' option. nothing happens when i click that, no new window pop's up with my saved profiles for me to select and use them. i have to close fancontrol at taskbar, reboot the app, then suddenly it works again. this has happened for last 3 days at least at this point. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

desktop pc, 
msi b550 mag mortar wifi
ryzen3900x
radeon rx6700xt 12gb gigabyte OC
vga 850 gq psu
phanteks PH-TC14PE PWM cpu cooler

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/12259978/log.txt)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1867

Will be fixed in the next release.

**Comment by eitaniel** [comment]
thank you brother. looking good again.
