### ISSUE TITLE
Can only control my gpu fan speed

### ISSUE THREAD

**Issue by mareSLO** [Rem0o/FanControl.Releases#1962]
Hi. So my gpu fan speed control works ok. My other fans are detected, or at least the rpm's are, but when i go to manual mode and even if i try to force apply, changing the speed does nothing, rpm stays the same, fans don't change speed. If i try to pair the controls and speeds automatically, it does it ok for the gpu, but for the fans it says no speed sensor reacted to control sensor
![Posnetek zaslona 2023-08-04 223634](https://github.com/Rem0o/FanControl.Releases/assets/11389588/a1a7743b-9c5d-4db7-a54c-a7ed55001803)
.

I'm running on the latest bios on the mb and have no other fan monitoring software. All the fans are controlled via the motherboard directly. I have the ab350 gaming 3 mb from gigabyte.  Hope someone can help me out.

**Comment by mareSLO** [comment]
No one has the same issue as me ? If i need to give more information, or some sort of log file, i'll gleadly do so.

**Comment by Rem0o** [comment]
See hardware and compatibility in README.
