### ISSUE TITLE
`Missing Speed sensor` for all of my devices

### ISSUE THREAD

**Issue by uttarayan21** [Rem0o/FanControl.Releases#1965]
**Describe the bug**
Missing speed sensor on v165
![image](https://github.com/Rem0o/FanControl.Releases/assets/18732700/1edb7ea8-5176-4624-a3cf-ecace41c7729)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
This is the only log.txt
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/12293688/log.txt)

**Relevant hardware specs and setup**
![image](https://github.com/Rem0o/FanControl.Releases/assets/18732700/3585df45-4145-4481-ac54-603b33621498)

Asus Prime Z790-P
i7-13700K
INNO3D iChill Nvidia 3080-Ti

I'm also using a 360mm AIO which I don't have the exact model for but it connects to the AIO pump header on the mother board.

Edit:
Additional info
This showed up on startup so I closed fan control ( from the systray as well ) and started it again manually but it still keeps happening.

Edit:
Rebooting seems to have solved the issue but it still keeps appearing every once in a while.
I'll keep this open in case you want to look into it, else feel free to close it.

**Comment by uttarayan21** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/18732700/6f873e39-f106-44bd-8340-23e60c4fec6a)

I'm using a delay of 30 seconds which is the default IIRC

**Comment by krisbot01** [comment]
Not sure if this is related but this just happened to me after installing the latest Nvidia drivers.
