### ISSUE TITLE
Request: Add a sensor to fan speed

### ISSUE THREAD

**Issue by storym94374** [Rem0o/FanControl.Releases#197]
I would like to control the chassis fan according to GPU fan, but I found that GPU fan control stays at 0% and does not represent the actual fan speed. Is it possible to sync the fan with other fan speed instead of fan control?
The GPU I'm using is Radeon VII, and its fan control can be correctly shown in GPU-Z. It would also be great to fix this issue.

**Comment by Rem0o** [comment]
Option 1: Create a curve from GPU temperature, which should represent what your GPU fan is doing anyway.
Option 2: Help me get support for Radeon cards here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
Option 3: Create a plugin with the sensor you want https://github.com/Rem0o/FanControl.Releases/wiki/Plugins
