### ISSUE TITLE
constant crashing. 

### ISSUE THREAD

**Issue by GH0STRN** [Rem0o/FanControl.Releases#1972]
**Describe the bug**
Fancontrol crashes all the time on me 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log_3.txt](https://github.com/Rem0o/FanControl.Releases/files/12328240/log_3.txt)

**Relevant hardware specs and setup*
ryzen5950X Lian li controllers x2 3080ti. custom water cooled loop

**Comment by Rem0o** [comment]
The log:

```
 GetInputReport failed. ---> System.ComponentModel.Win32Exception: The device is not connected
   --- End of inner exception stack trace ---
   at HidSharp.Platform.Windows.WinHidStream.GetInputReport(Byte[] buffer, Int32 offset, Int32 count)
   at LianLi.FanController.GetSpeed(Int32 fancontroller_channel)
   at FanControl.LianLiPlugin.Sensors.Update()
```

The problem comes from the LianLi plugin.  Please transfer your issue over that repo. Thanks.
