### ISSUE TITLE
fan sensor not defined

### ISSUE THREAD

**Issue by shamhm0r** [Rem0o/FanControl.Releases#1974]
Hello
when I sync there is no fan sensors detected.

**Comment by shamhm0r** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/53694214/e46f43ae-334b-4b5f-9cfa-f3cf28af770e)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

Your computer is sadly not supported properly.  If it's a built desktop PC, support may get added later on.

Closing.
