### ISSUE TITLE
Case fans not stopping on idle

### ISSUE THREAD

**Issue by tom-cor** [Rem0o/FanControl.Releases#1977]
This software is what I've been looking for for a long time! But I have only one big problem.

**Describe the bug**

Case fans are correctly detected with their respective start pwm %,  but, although the motherboard allows for them to stop completely when temps are low enough (Via Asus AI Suite), with this software I cannot do the same.
After reading some other issues posted, I understand that Asus is kinda tricky with how it handles fan control... but I hope there's light at the end of the tunnel... Again, kudos for this great program!

**Relevant hardware specs and setup**

Mobo Asus TUF GAMING B550M-PLUS (WI-FI)
2x DeepCool 140mm ARGB fans
1x IDCooling 120mm ARGB fan

**Comment by aaronbc** [comment]
I have the B550 motherboard as well (w/o WiFi).  In the BIOS I set all my chassis fans to operate in DC mode and also changed the setting to allow the fans to stop.  After this, Fan Control is able to stop the fans when the fan percentage drops below the stop threshold.  Seems to work well for me.

**Comment by tom-cor** [comment]
Thanks a lot! This worked great! Bye AiSuite and Msi Afterburner! And hello to this wonderfull fan manager! 🎉
