### ISSUE TITLE
Error: changing profiles with hotkeys

### ISSUE THREAD

**Issue by Spuner** [Rem0o/FanControl.Releases#1978]
If you change profiles via hotkeys in version 166, this error pops up. There is no such problem in version 165. If you change profiles in version 166 from the Fan Control icon in the system tray - the error is not displayed, everything is normal.

Here is the changelog:

```
14.08.2023 5:55:34 AM: System.InvalidOperationException: Cannot set ShutdownMode when application is shutting down or already shut down.
   at System.Windows.Application.set_ShutdownMode(ShutdownMode value)
   at FanControl.App.OnStartup(StartupEventArgs eventArgs)
```

**Comment by Rem0o** [comment]
Found the issue. Will release a fix shortly.
