### ISSUE TITLE
All curves are NaN

### ISSUE THREAD

**Issue by TheGuy920** [Rem0o/FanControl.Releases#1983]
**Describe the bug**
All curves are NaN after boot and application restart. Occasionally works after several (7+) application restarts or several (3+) system restarts. Windows 11 Home 22H2 22621.2134. FC-V166. Similar Issue #1980 

![image](https://github.com/Rem0o/FanControl.Releases/assets/53882381/909c4671-3f76-4bbe-ab8e-c55a08a76c99)

**Log**
Log file empty

**Specs**
13700k 5.6Ghz
RTX 4090

Need confirmation that userConfig is clear of any personal info before uploading. Did a quick scan and it seemed clean.

Reliant devices don't seem too happy. Minimum percentages are within 15-20%. Unable to confirm efficacity of FanControl over fan speeds. Can confirm all fans running except 4090 fans (at 2% util). Only reported RPM is pump fans, while others are running. Once a restart is successful all operations work as expected.

Also not happy that source is not available by traditional means

![image](https://github.com/Rem0o/FanControl.Releases/assets/53882381/c039b048-de81-4b9c-b382-1e3bd1ac616d)
![image](https://github.com/Rem0o/FanControl.Releases/assets/53882381/bb64aa94-d966-4c92-920e-9e6a08e81fc8)

**Comment by Rem0o** [comment]
I would guess from that state none of the values like RPM and temperatures are updating?  Just posted a V167 that addresses that issue.

**Comment by TheGuy920** [comment]
Seems good off that bat, will continue to monitor for a few days before I'm confident I can close this. After application start, restart, etc. it fails to get sensor data and retries until it does. It does work but, its just an added 4-8 seconds at application start it seems

**Comment by Rem0o** [comment]
That's normal. It just failed to show that retry properly before, and it locked the UI. That was the bug.

**Comment by Qlix0804** [comment]
> 

I am curious if there is something we can all do to avoid this from happening on our end, or if you know what actually causes it. It seems to work for a few weeks after a new release then randomly breaks till we go update to the new release.

**Comment by TheGuy920** [comment]
The NaN still likes to float around but it cant stick around for more than a second so I would feel safe closing this issue...
Until that is, @Qlix0804 responded with the message above. Not sure if its in reference to the long boot time or the NaN issue so a bit more clarification would be nice.
