### ISSUE TITLE
Error has occurred check log.txt for more info.

### ISSUE THREAD

**Issue by SamAresOfficial** [Rem0o/FanControl.Releases#1987]
Title, and I've been using FC for nearly a year now and everything was fine until a week or so ago until fan control wouldn't open, the icon in the task was broken and nothing I did could get it open in any way. The application was just invisible, and no amount of troubleshooting fixed it. So, I decided to create a new installation and start from scratch and things have been pretty buggy, even though they weren't before. The program will just freeze, the sensors break, everything freezes, and my fans just lock in place. And sometimes the program silently crashes. And my gaming performance will tank. So far, I haven't been getting errors except the past few days I've gotten this error, so I'm trying to sort it out.

8/15/2023 8:48:35 PM: System.InvalidOperationException: Cannot set ShutdownMode when application is shutting down or already shut down.
   at System.Windows.Application.set_ShutdownMode(ShutdownMode value)
   at FanControl.App.<OnStartup>d__12.MoveNext()
8/16/2023 6:36:02 PM: System.InvalidOperationException: Cannot set ShutdownMode when application is shutting down or already shut down.
   at System.Windows.Application.set_ShutdownMode(ShutdownMode value)
   at FanControl.App.<OnStartup>d__12.MoveNext()
8/16/2023 6:40:04 PM: System.InvalidOperationException: Cannot set ShutdownMode when application is shutting down or already shut down.
   at System.Windows.Application.set_ShutdownMode(ShutdownMode value)
   at FanControl.App.<OnStartup>d__12.MoveNext()

Windows 11 Pro
i9-13900K
Arctic Freezer 360mm
Gigabyte 4090
DDR4 4400Mhz 32GB

**Comment by Rem0o** [comment]
Version of the software?

**Comment by SamAresOfficial** [comment]
Latest 167, this originated on 165 though I believe

**Comment by Rem0o** [comment]
Notify if this behaviour still occurs on v167.

**Comment by SamAresOfficial** [comment]
> Notify if this behaviour still occurs on v167.

Seems to have been resolved now.
