### ISSUE TITLE
Adding Average Mix crashes

### ISSUE THREAD

**Issue by benncarroll** [Rem0o/FanControl.Releases#199]
Hey there,

Have discovered a bug when adding a Mix source, if you select Average with no sources selected, program throws up endless dialogs until being quit. 
Seems like it is trying to evaluate it every cycle and crashes on a division by zero or something similar, maybe could just be disabled until sources are added?

```
1/04/2021 7:09:49 PM: Unhandled exception in FanControl v1.0.0.0
1/04/2021 7:09:49 PM: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average(IEnumerable`1 source)
   at FanControl.ViewModels.MixFanCurveViewModel.UpdateCurrentCommandTarget()
   at FanControl.Domain.ApplicationClock.DoActions()
```

**Comment by Rem0o** [comment]
Good catch, will fix.
