### ISSUE TITLE
[Feature Request] Add option to use custom curve for Mixed Graph instead of averaging the graphs

### ISSUE THREAD

**Issue by Rexadev** [Rem0o/FanControl.Releases#1990]
I use `Mix Graphs` to Mix sensors and would like to use custom curves for it instead of editing curve for each sensor

In my case, I want to create a custom graph (now Fancontrol just averages the graphes) for Mix - All which uses Average Temp of All Components

**Comment by Rexadev** [comment]
In my case, I want to create a custom graph (now Fancontrol just averages the graphes) for `Mix - All` which uses Average Temp of All Components

@Rem0o

**Comment by Rem0o** [comment]
Create a mix custom sensor and include all the sensors you want in there, then use that mix sensor as the input for a graph.

**Comment by Rexadev** [comment]
@Rem0o thanks
