### ISSUE TITLE
asus crosshair VII

### ISSUE THREAD

**Issue by makatru** [Rem0o/FanControl.Releases#2]
Hi, I am using your software to control my pc's fans, and it is wonderful, and I appreciate all the work you have done. But for my motherboard, an asus crosshair VII, CPU fans work fine, but chassis fans, I see their RPM, but not able to regulate their speed, could it possibly work?
Thanks for everything

**Comment by Rem0o** [comment]
Any compatibility issue is directly related to https://github.com/LibreHardwareMonitor/LibreHardwareMonitor. I pull directly from this library all of the RPMs, controls and so on. I would suggest opening an issue with your specific motherboard and SuperIO chip on there.
