### ISSUE TITLE
Error on resume from Energy Saving Mode

### ISSUE THREAD

**Issue by Jodeldiplom** [Rem0o/FanControl.Releases#20]
First of all thanks for this great project! Works great out of the box and I love the UI you have created.

I have one small issue though:

When I put Windows into the Energy Saving Mode and resume my work sometime later, i get the following error:

![error](https://user-images.githubusercontent.com/46313496/90049484-27acc400-dcd5-11ea-8950-aa8e56e05632.png)

Log files contains the following error:

2.08.2020 19:42:25: Unhandled exception in FanControl v1.0.0.0
12.08.2020 19:42:25: NVAPI_GPU_NOT_POWERED
12.08.2020 19:42:25:    bei FanControl.Domain.ApplicationClock.a.b()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
12.08.2020 19:42:34: Unhandled exception in FanControl v1.0.0.0
12.08.2020 19:42:34: NVAPI_GPU_NOT_POWERED
12.08.2020 19:42:34:    bei FanControl.Domain.ApplicationClock.a.b()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
12.08.2020 19:46:42: Unhandled exception in FanControl v1.0.0.0
12.08.2020 19:46:42: NVAPI_GPU_NOT_POWERED
12.08.2020 19:46:42:    bei FanControl.Domain.ApplicationClock.a.b()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
12.08.2020 19:46:50: Unhandled exception in FanControl v1.0.0.0
12.08.2020 19:46:50: NVAPI_GPU_NOT_POWERED
12.08.2020 19:46:50:    bei FanControl.Domain.ApplicationClock.a.b()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5064724/log.txt)

Looks like my graphic card needs some time to power up again after the system was asleep.

Is there some way to supress error messages in the UI and just have them logged to the log file?

Thanks!

**Comment by Rem0o** [comment]
I've experienced the same behavior with my GTX 1060, seems like the drivers takes a few seconds to wake up. It's annoying but it doesn't break anything. I will try to isolate this error and maybe delay the config once the computer wakes back up.

**Comment by Jodeldiplom** [comment]
Hi Rem0o ,

Thanks for the very quick response. :-) 

Not sure if this works with a background window.. but maybe this is useful to detect the wake up and postpone the config a few seconds?

[SystemEvents.PowerModeChanged Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.powermodechanged?redirectedfrom=MSDN&view=dotnet-plat-ext-3.1)

**Comment by Rem0o** [comment]
Right now I use this exact event, just no delay, straight up reset the config once it hit the resume state.

**Comment by Jodeldiplom** [comment]
Hmmm... just thinking about some kind of dirty workaround....

Maybe you can use "polling" to check if  the GPU is powered up again?

1) Upon hitting the resume state, you send a query to the NVAVIWrapper
2) If you should get the NVAPI_GPU_NOT_POWERED exception, you pause for a short period of time and go to 1) again

Yeah, I know... lame. :-)

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V43

**Comment by Jodeldiplom** [comment]
Thanks for the quick fix!

Version 43 still caused some problems, but V44 seems to have fixed all problems.

**Comment by Rem0o** [comment]
Yeah the error could pop-up in a few more places than I expected, had to do an other release.
