### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by 411621** [Rem0o/FanControl.Releases#2000]
Fan control so far so good except one minor issue: icon visibility.

The fan "propeller" symbol icon image when viewed in task manager is white. However, the task manager background is also white!
Thus not visible!
Reversely the case in the system tray. There the fan "propeller" symbol icon image is black. My system tray/taskbar/desktop is dark gray/black! Again, thus not visible!
All just the reverse!

Suggestions, ideas:
A) Simply reverse colorization of icon image!
B) Fancier, allow user to set or select a few fix colors!
C) Even fancier: Have propeller animated and spin!
D) Super-duper fancy: Have the fan color change with temperature: cool - blue or green, warm orange and when all "goes up soon in flames", shortly before that red! (similar in style like the color of the temperature icons of HD Sentinel change with increasing temperature.
(Sample screenshot of HD Sentinel configuration panel attached)
![HT center now temperature threshold control](https://github.com/Rem0o/FanControl.Releases/assets/29167457/7493f9da-5c40-4161-a8e5-0b5c96c7f8e3)

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/1d701953-d415-4b7f-9b14-377d923fe954)
