### ISSUE TITLE
Driver vulnerable

### ISSUE THREAD

**Issue by lordraiden** [Rem0o/FanControl.Releases#2003]
Avast AV warns me that I need to disable this setting if I want to allow the fan control driver to work
![imagen](https://github.com/Rem0o/FanControl.Releases/assets/17175395/ae7e94f7-5429-43f6-a4de-553c6b910f21)

Is there some problem with the fan control driver? it is not signed or something?

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/1521
