### ISSUE TITLE
Fan Control not detecting GPU temp sensors after card upgrade

### ISSUE THREAD

**Issue by theshulker** [Rem0o/FanControl.Releases#2011]
I recently replaced my 6700 XT GPU for a 7900 XT. Since then, Fan Control is not able to detect temp sensors from the new GPU. All worked fine with previous card. No other changes, only video card swap.
Is there a known limitation with newest Radeon software or cards?  Thank you.

GPU: Sapphire 11323-02-20G Pulse AMD Radeon RX 7900 XT Gaming Graphics Card with 20GB GDDR6, AMD RDNA 3
Fan Control: V168
AMD Adrenalin Edition: 23.8.2

**Comment by Ryuisnod** [comment]
having the same issue with my 7900xtx

**Comment by Rem0o** [comment]
From README:

```
Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!
```

**Comment by Ryuisnod** [comment]
Hey, I actually got it working after installing the pro version of
adrenaline

**Comment by maxrr** [comment]
Just upgraded from 1080 Ti to 7800 XT. Same issue.

**Comment by Rem0o** [comment]
Navi 3 support:

https://github.com/Rem0o/FanControl.ADLX

**Comment by Ryuisnod** [comment]
Thanks
