### ISSUE TITLE
[Feature Request] Show the Loaded Configuration File

### ISSUE THREAD

**Issue by MohSamNaf** [Rem0o/FanControl.Releases#2018]
Hi Rem0o,

Thanks for sharing this amazing tool. I only use it now for fan setups and controls..

I would like to know if it is possible, if you have the time, to implement a tiny feature, maybe somewhere in the top bar (close to the 3 dots), telling us what is the currently loaded .json configuration. I have different configurations depending for light work, gaming and running Deep Learning applications, and sometimes I get lost what is the loaded config until I visually check the setup manually to recognize which is which!

Thank you!

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/e4eeb386-cdd4-4106-a9cc-98ca889242ab)

**Comment by MohSamNaf** [comment]
I feel so dumb not noticing it after 1 year of usage xD
Thank you
