### ISSUE TITLE
Does not work with Lenovo laptops?

### ISSUE THREAD

**Issue by Menduksay** [Rem0o/FanControl.Releases#2022]
It seems that the program cannot control the fans of a Lenovo IdeaPad Gaming 3 laptop, specifically the model 15ach6 82k201tyar.

I tried to try all the possible options and configurations but I don't see any changes, is it possible to make it work?

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/12566488/log.txt)

**Comment by DfrostX** [comment]
See this

https://github.com/Rem0o/FanControl.Releases/issues/1788
