### ISSUE TITLE
Source code availability?

### ISSUE THREAD

**Issue by A7exSchin** [Rem0o/FanControl.Releases#2023]
Hi there!
Just found the FanControl and might wanna add some stuff for myself (via fork ofc). Where can I find the source code?

Thanks!

**Comment by DfrostX** [comment]
From the readme : Sources for this software are closed.

See here for the develloper's take on this  https://github.com/Rem0o/FanControl.Releases/issues/1143#issuecomment-1405887721

**Comment by A7exSchin** [comment]
Thanks for the quick answer. Sad to see good tools being closed source. Imma close this rn.
