### ISSUE TITLE
GPU at 60% fan after reboot (even with Fancontrol removed).

### ISSUE THREAD

**Issue by d4icon** [Rem0o/FanControl.Releases#2026]
**Describe the bug**
Hello,

Run the program for the first time.
It did the analysis of the fans.

I just wanted to test it.

Now when I restart the pc, the GPU fan is set to 60%, and I have to manually enter the Afterburner and change it.
In the afterburner profile it is as usual, correct.

But I don't know what happens that now always when I reboot the gpu is set to 60% since I opened the program and tried it.

What is happening?

thanks

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
GPU 4080 nvidia

**Comment by Rem0o** [comment]
My guess is the process got killed before it could exit properly, and the command got stuck. In AfterBurner, set the "auto" mode, hit apply, set back your curve, hit apply. Should fix it.

**Comment by d4icon** [comment]
> My guess is the process got killed before it could exit properly, and the command got stuck. In AfterBurner, set the "auto" mode, hit apply, set back your curve, hit apply. Should fix it.

Hello,

Thanks for the help, but it didn't work.

I have tried several times, and it keeps doing the same thing :-(
Any other ideas?

**Comment by Rem0o** [comment]
You could try and reinstall your Nvidia driver, see if that resets it.

**Comment by d4icon** [comment]
oki, i try
