### ISSUE TITLE
CPU fan flaked on me

### ISSUE THREAD

**Issue by bananabull** [Rem0o/FanControl.Releases#2028]
this has happened before and i honestly forget what fixed it but i just installed two argb power extention sleaves and when i booted  it up and no more control if it somehow helps
specs
ryzen 5 5600
4 antec 120mm fusion argb fans 
asus tuf b550-plus wifi II
amd radeon rx 6700 by xfx not rx 6700 xt don't know if it makes a difference but oh well
SilverStone Technology Air Slimmer 90 ARGB Enhanced Performance 92mm Slim Fan (cpu fan) 

like i said it was working before also i switched fan controllers from the antec one to a IHTP Fan Hub and plugged the power sleeves and now cpu just can't pair 
i really just need suggestions the only reason i post this it the mobo auto fan setting suck and max the fan and no the bois doesn't do anything because armor crate overwrites the prm setting ig don't know why asus just wants to kill my fans ig any help would be appreciated and sorry for the rant 

UPDATE
i've learned it's reading all the fans as one i even tried switching around what was plugged into the argb headers i think it's the controllor doing that so i'm even more confused

**Comment by Rem0o** [comment]
FanControl works with 1 fan, 1 motherboard header ( channel ).  Not clear by your message how each individual fan is plugged, but if it ain't 1 fan/1 header, it won't work.  If multiple fans are chained via a hub to a single header, they will be controlled as one.

**Comment by bananabull** [comment]
yeah um so the bet way i can explain the first part is i switched fan hubs the old one worked fine all for case fans where plugged into the fan hub along with the argb cords. when i switched to the new fan hub and plugged everything in and booted it up the cpu fan lost the sensor to the cpu fan. mind you  i never switched or moved the cpu fan header and was confused why it said it was lost so i turned my case fans to 0% and all the fans stopped hence the second part "reading them all as one" i think i lost control of the case fans though when i switched the hub i'd have to plug the old one in it might be a faulty 4 pin connector on the hub because that's why i has problems with the software the one day is i didn't plug it the 4 pin sys fan but i'm not sure if that help but they are chained via a hub always were just the new one might be causing problems

**Comment by bananabull** [comment]
ok really sorry it totally was the hub i switched to the old one worked perfect the new one is the problem it won't even respond to the bois fan settings really sorry to waste your time
