### ISSUE TITLE
Fan Control v73 does not detect AIO pump (PWM)

### ISSUE THREAD

**Issue by Dutchy735** [Rem0o/FanControl.Releases#203]
Title says it all. 

i recently started using this software and i'm really liking it. this however is a major disappointment. The AIO does pop up in the BIOS and even displays its RPM. I believe it has something to do with the hardware libraries. However, I'm a big noobie when it comes to these things. I tried everything that I could do myself though. I'm running the latest BIOS version and installed al windows updates.

Hardware:

Asus ROG Strix B450-I Gaming
AMD Ryzen 7 3800XT
Custom Loop AIO pump on PWM mode, on the dedicated AIO PWM Header on the motherboard

Software:

Windows 10 Pro
Fan Control V73

If anyone could help that would be magnificent!

Edit: Photo

![image](https://user-images.githubusercontent.com/81909813/113520021-7f63ac80-9590-11eb-8ccc-8ac48e1e6f53.png)

**Comment by Rem0o** [comment]
Please read the README. I can't support and fix every motherboard.
