### ISSUE TITLE
[Feature Request] Min starting temperature if idle

### ISSUE THREAD

**Issue by victor-sm** [Rem0o/FanControl.Releases#2033]
The fans of my GPU start only at about 35% (preventing me from slowly ramping them up) and quickly become audible. I want to keep them off at low temperatures, but this inevitably results in a situation where the fans start to turn on/off while fluctuating around the initial starting temperature. 

What I would propose is a field to set a minimum temperature for the curve/fan to activate if it's currently off:

![MinStartTemp](https://github.com/Rem0o/FanControl.Releases/assets/7871132/3dfe39eb-f8b7-441f-b214-63dda4b2596e)

I threw together a mockup. In my example, the fans would start when the GPU reaches 50° but keep cooling until reaching 35°. Thus giving me a nice 15° degree range where small workloads or spikes wouldn't trigger the fans immediately.

**Comment by Rem0o** [comment]
There are already a few different ways to address your issue on/off issue.  

1: increase your hysteresis value. 2 deg is very low. Also untick "only on the way down", and add another point in your graph to the far left at 0%.  Hysteresis is ignored at the limits ( first and last point you set ). Duplicating your first point will override that behavior.
2: set your 0 point higher. 45 degree is a pretty normal threshold for 0 rpm on nvidia gpus.
3: If you really want a "trigger" point, create a trigger curve, and mix it with your graph. Something like this:

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/14698224-665c-4ae2-abee-2c65ed04769d)
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/92eaf994-bebe-45de-91f7-6b615de987a5)

The "trigger" portion will do exactly the behavior you described, and the "max" function of the mix will make it override your graph until the temp drops back to your desired idle point.  The graph will only take over with temperatures over 50 deg. Between 35 and 50, the trigger will hold 36%.  Once below 35 degree, both the graph and trigger will 0%, and the trigger will only fire back at 50 degree.
