### ISSUE TITLE
Not Controlling Corsair Fans

### ISSUE THREAD

**Issue by marcoistasy** [Rem0o/FanControl.Releases#204]
I am having an issue with FanContrl V73 whereby the sotware isn't able to control my Corsair case fans (LL120 RGB fans; see the attached screenshot. I am wondering if this is a known issue and how I might solve it? The four fans which the software isn't able to control are being detected by my motherboard. 

<img width="1916" alt="Screenshot 2021-04-04 204900" src="https://user-images.githubusercontent.com/7032741/113526281-80441080-9587-11eb-81e4-4f4caff6c7ef.png">
).

**Comment by Rem0o** [comment]
Please read the README. I can't support and fix every motherboard.

If you want to tackle compatibility  -> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by marcoistasy** [comment]
Thanks for your reply! I should have clarified -- my MB was being supported and worked okay with the software for around a week, and then it stopped being compatible.
