### ISSUE TITLE
No Controls or Speeds for Acer Predator G3-572 (2017)

### ISSUE THREAD

**Issue by sbstratos79** [Rem0o/FanControl.Releases#205]
As the description suggests. No controls or speeds are available for my Acer Predator G3-572 (i5-7300HQ 1050Ti). Is there any additional info I can provide to enable support for this laptop? Acer provides a PredatorSense utility to control fan speeds, but it doesn't have a lot of customization.

**Comment by Rem0o** [comment]
It is simply not supported. There is no magic. Support is based on if there is an API publicly available to control the fans.

**Comment by sbstratos79** [comment]
https://github.com/hirschmann/nbfc Notebook FanControl has a preset for this model, so it should be supported, right?

**Comment by Rem0o** [comment]
Project doesn't seem very active. A plugin could be made (https://github.com/Rem0o/FanControl.Releases/wiki/Plugins) or the controls could be ported over LibrehardwareMonitor I guess (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor).
Either way, lots of work. Feel free to contribute and test.

**Comment by sbstratos79** [comment]
I don't code so I can't make a plugin. I'll look into LibreHardwareMonitor. Thanks.
