### ISSUE TITLE
cannot reorder the cards

### ISSUE THREAD

**Issue by KiGamji** [Rem0o/FanControl.Releases#2053]
hello there! I'm running FanControl V170 and I'm unable to move the cards:
![image](https://github.com/Rem0o/FanControl.Releases/assets/59279014/223b2174-36b4-43c9-80c8-c310297d09eb)

...any help is appreciated

**Comment by Rem0o** [comment]
You can only reorder cards in the same category.

**Comment by KiGamji** [comment]
> You can only reorder cards in the same category, if it doesn't work 1 way round, try the other card.

https://github.com/Rem0o/FanControl.Releases/assets/59279014/245acb98-6a8b-419c-83f9-d84fd4851207

**Comment by Rem0o** [comment]
You need to release your click between cards when the little line appears .

**Comment by KiGamji** [comment]
> You need to release your click between cards when the little line appears .

I do, but the cursor keeps being in "unavailable" state, and what I'm also trying to show is that the line doesn't move anywhere until I drag my mouse out of and then in the app. Though nothing changes - still can't reorder for some reason

**Comment by KiGamji** [comment]
seems to work fine with V174 and clear Windows installation
