### ISSUE TITLE
External fans on ROG Strix cards

### ISSUE THREAD

**Issue by LuxiP7** [Rem0o/FanControl.Releases#2054]
Hello!

ROG Strix series cards (In this example 5700 XT) have external fan ports that are controllable only through ASUS software (GPU Tweak III). None of the typical sensor reporting software has any idea of their existence (HWiNFO, AIDA64, HWMonitor) neither does AMD Software.
I'm guessing that without extensive reverse engineering it would be impossible to support.
![GPU_Tweak_III_iWFq71G2ua](https://github.com/Rem0o/FanControl.Releases/assets/67970318/3d1eff92-6470-4659-935a-0b4ad10225f3)

**Comment by Rem0o** [comment]
> I'm guessing that without extensive reverse engineering it would be impossible to support.

Bang on.

**Comment by MaximusChia** [comment]
Similar issue with MSI Suprim Liquid 4090, FanControl does detect RMP from both Radiator and Internal fans, however can't take control on them.
