### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Tron-Creeper2** [Rem0o/FanControl.Releases#2055]
**Describe the bug**
![Snímek obrazovky 2023-09-27 215723](https://github.com/Rem0o/FanControl.Releases/assets/94975374/e255679b-b16d-4778-b917-b769f2087042)
That repeated about 20 times, then I closed the app, happened again.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[[Link it here]](https://drive.google.com/file/d/19_BfzO5GLt5fSXEmL6slWSXuBu11t-Rz/view?usp=sharing)

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

CPU: Ryzen 7 3700X
Motherboard: ROG STRIX X570-E GAMING
GPU 1: 6700XT
GPU 2: 1030 OC
BIOS/Date: American Megatrends Inc. 4403, 27.04.2022
Win build (Win 11 Pro): 10.0.22621 Build 22621
RAM: 4x8GB@3333Hz

**Comment by Rem0o** [comment]
Seems to be a problem with a plugin you are running which fires an exception.  Are you using the ADLX?
