### ISSUE TITLE
System Freezing with FanControl v74

### ISSUE THREAD

**Issue by mrwoot101** [Rem0o/FanControl.Releases#206]
Hi All,
I have a strange issue where this software appears to lockup my entire computer, I cannot CTRL+ALT+DEL etc so my only option is to press the reset button.

It appears to be random when it occurs, but the past 2 days about an hour after boot it will freeze the system. It also froze when I updated to the latest version.
Nothing appears to show up in event viewer either.

Systems Specs -
CPU: Ryzen 5 2600
GPU: GTX 1080ti 
MoBo: GA-AX370M-Gaming 3

**Comment by Rem0o** [comment]
Anything in your log.txt file?

**Comment by mrwoot101** [comment]
Hey Rem0o, I don't have a log.txt file? - I'm running it from My Documents, 
Here is the running log : https://pastebin.com/HCeN3VFr

![directory](https://user-images.githubusercontent.com/82125712/114109814-62750380-9919-11eb-8606-38623bdc7d07.png)
