### ISSUE TITLE
ITE IT8695E is not controllable by FanControl, but are in LibreHardwareMonitor

### ISSUE THREAD

**Issue by tprochazka** [Rem0o/FanControl.Releases#2061]
I would rather create a new issue, it has already been reported several times here, for example, #1214

But the issue is that LibreHardwareMonitor on my MB can fully control all of my fans
There is just no visible default value. It looks like this:

![image](https://github.com/Rem0o/FanControl.Releases/assets/172094/3fe3a986-14bf-416f-802f-e20ea5da60de)

When I right-click on it

![image](https://github.com/Rem0o/FanControl.Releases/assets/172094/c7b46fbf-e0a1-471a-8a9e-a97c3128390f)

And the corresponding fan really speeds up

![image](https://github.com/Rem0o/FanControl.Releases/assets/172094/8abac555-deff-4123-85be-d5b2cab017ff)

So it is not an issue on the Libre Hardware monitor, but only in Fan Control app, maybe when your app is not able to read the default value of PWM, it decides to not make it controllable, but it still is. So it is most likely fixable and it will help a lot of users of this awesome app.

**Comment by Rem0o** [comment]
What does your sensor sources look like ? Have you activated InpOut? It is required to control the 2nd chip.

**Comment by tprochazka** [comment]
I have
![image](https://github.com/Rem0o/FanControl.Releases/assets/172094/45c2865b-8387-4a5e-826a-1769990b9b1a)

When I run wizard which pairs the controller to the fan, it skips all controls from the second sensor as non-controllable.
They are hidden (visible only when I turn on display hidden cards).

Even when I unhide them, set to manual like this
![image](https://github.com/Rem0o/FanControl.Releases/assets/172094/9a6ef3ea-153c-45ff-b805-7568074945c7)
Nothing happens.

**Comment by Rem0o** [comment]
Are you using the latest commit of LHM or the latest release? Make sure you use the same librehardwaremonitorlib dll in both fancontrol and lhm.  You can override the one in fan control.


Fan control does litteraly the same thing as right clicking a control in lhm, so I suspect the results are different because of a different version of the lib.

**Comment by tprochazka** [comment]
I initially checked only that both DLLs are the same version 0.9.2.0.
But now I have found that they are not binary identical.
I have official build from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.9.2
I tried to replace LibreHardwareMonitorLib (dll, pdb, xml)
I got this after start

![image](https://github.com/Rem0o/FanControl.Releases/assets/172094/40fb183a-901f-49d7-9963-1c2f1c0bfea0)

I still see all fan controls, but still all from second sensor is not possible to control.

![image](https://github.com/Rem0o/FanControl.Releases/assets/172094/03a4e89a-2eea-4133-af04-3000411dc270)

**Comment by tprochazka** [comment]
I tried even deleting settings and doing a clean start, still the same.
I have version 171.

**Comment by tprochazka** [comment]
So my mistake, it doesn't work even on Libre Hardware monitor. I used the wrong controller.
I will try to ask there.

**Comment by Rem0o** [comment]
No worries. Good luck.
