### ISSUE TITLE
Error when changing profiles with hotkeys

### ISSUE THREAD

**Issue by Spuner** [Rem0o/FanControl.Releases#2062]
It gives an error when changing profiles, but the profile changes. Also when changing profiles with hotkeys, the icon in the system tray disappears and appears with sensors of the selected profile. I also noticed that if you change profiles via hotkeys, the profiles change with 2-3 seconds delay. (If you change profiles from the tray icon - profiles change quickly. This problem was also in the previous (170) version).

![2023-10-04 19_59_41-Fan Control V171 (Profile 1 - Auto Fans Control json)](https://github.com/Rem0o/FanControl.Releases/assets/30773815/0497fcd7-0d2d-4d8f-a29e-b2379d6e2ce1)

**Comment by Rem0o** [comment]
It is technically not an error, more of a... feature?  When you press a hotkey, you start a new executable ( I guess you have it bound to FanControl.exe -c [configfilehere]), that will "talk" with the existing executable to switch profile. That has a delay.   If that previous executable was on a different user profile than your existing profile, this warning will be shown telling you that old instance was killed.

**Comment by Spuner** [comment]
Why then are there no such notifications in version 170 (and below)?

**Comment by morgenrot68** [comment]
I have the same problem. With 1.70 everything was ok and now with 1.71 I get this annoying message. 
I use links to switch between the different configs:

"C:\Archive\Utilities\Fan Control\FanControl.exe" -c Half.json
"C:\Archive\Utilities\Fan Control\FanControl\FanControl.exe" -c Normal.json
"C:\Archive\Utilities\Fan Control\FanControl\FanControl.exe" -c Full.json

Previously I was able to switch between configs using these links. This is no longer possible since 1.71. 

Is it possible to downgrade to 1.70?
Or is there another solution?

**Comment by Spuner** [comment]
@morgenrot68, I'm back to 168 altogether. In 170 version it takes longer to switch profiles using hotkeys than in 168 version. To return to the previous version (170) - copy the "Configurations" folder to the Fan Control folder of the 170 version.

**Comment by morgenrot68** [comment]
Thanks, but where do I get the older versions? For me the update overwrites the fan control folder.

**Comment by morgenrot68** [comment]
Found it. There are these two versions offered, what is the difference?
FanControl_net_4_8.zip
FanControl_net_7_0.zip

**Comment by Spuner** [comment]
@morgenrot68, try copying the "Configurations" folder from version 171, and copy it into the folder with version 170 (which you downloaded from here). But if all the settings have been overwritten, you will most likely have to re-configure everything.

P.S. always keep the stable versions of the configurations separately as a backup.

P.P.S. I download "FanControl_net_7_0.zip". But I don't know if there can be a conflict with configurations between versions or not.

**Comment by morgenrot68** [comment]
@Spuner 
Thank you, I will try that. I hope that I do not have to reconfigure everything. That would be real work.
And for the future I will make a backup before an update and turn off the AutoUpdate function.

**Comment by Spuner** [comment]
@morgenrot68, you're welcome.

P.S. always backup your important data.

**Comment by morgenrot68** [comment]
Me idiot. I do a full backup of my systems every week. Just have to extract it from there.

**Comment by tychoid** [comment]
Yeah, bummer.  I automate all my fan profile configuration switching.  The popup is a bit of a drag.

**Comment by Rem0o** [comment]
See V172
