### ISSUE TITLE
Unexpected error occured

### ISSUE THREAD

**Issue by makecim** [Rem0o/FanControl.Releases#2064]
Hi, just got a problem when starting the app. "An unexpected error occured. See log file for details."

There is the link of my logs (unfortunately its in french im sorry about that and i hope u can help me):

https://textup.fr/734046hY

Btw the app still working if i dont close the error message lol

**Comment by Rem0o** [comment]
Seems like you are missing a dll in the FanControl folder.  Emoji.wpf.dll

It comes with the app. Is it missing in your folder?

**Comment by makecim** [comment]
Yep this file is missing in the folder root. 

how to reinstall without losing my settings ?

**Comment by Rem0o** [comment]
Pull the dll from the zip.

**Comment by makecim** [comment]
I did it but now the logo are not clickable. Image: https://goopics.net/i/g33e1t

Can i just reinstall fancontrol and paste my actual "fanControl.exe.config" file in the new install ?

**Comment by Rem0o** [comment]
You only need to carry over the "configuration" folder

**Comment by makecim** [comment]
Ok this method was the best and worked fine for me. Thanks for your help!
