### ISSUE TITLE
Fan Control not autostarting

### ISSUE THREAD

**Issue by CharlieB62** [Rem0o/FanControl.Releases#2068]
Hi,
Very nice program - you are a talented guy!
I have seen other messages regarding Fan Control not starting at logon, but I still can't get the program to launch when I log in.  Fan Control is in the Task Scheduler, but does not launch when I try to run it from there.  Could it be because the account I use does not have admin privileges?
Charlie

**Comment by Rem0o** [comment]
> Could it be because the account I use does not have admin privileges?

That's the issue.

**Comment by CharlieB62** [comment]
Thanks.  I changed the account to an admin and all is good!
