### ISSUE TITLE
Fans show up in other software, but yet are missing here?

### ISSUE THREAD

**Issue by pstraka17** [Rem0o/FanControl.Releases#207]
I finally tried Rem0o / FanControl after folks recommended me it over MSI Creator Center (which basically the same thing a MSI Dragon Center). While nice, the main flaw I noticed in it for me is that it fails to control all of my fans, or at least recognize them. I have a total of 6 case fans in my PC (not counting an additional 3 for my NZXT Kraken, which I use NZXT CAM to control), and out of the 6, I can only control 3 in Rem0o's FanControl. Yet in MSI Creator Center, I have full control over all 6 case fans... this puzzles me. How in the world is it possible that basically this malware of a program from MSI is capable of allowing me full fan control, yet Rem0o / FanControl, a better third party software fails to do so? Clearly all the fans should be recognized by Windows 10, otherwise MSI Creator Center wouldn't see them.

My specs are as follows:

Windows 10 Pro

AMD Ryzen 9 5950X 3.4 GHz 16-Core Processor

NVIDIA GeForce EVGA 1080ti SC2

NZXT Kraken Z73 73.11 CFM Liquid CPU Cooler

MSI PRESTIGE X570 CREATION EATX AM4 Motherboard

G.Skill Trident Z RGB 32 GB (2 x 16 GB) DDR4-3600 CL16 Memory

Samsung 980 Pro 500 GB M.2-2280 NVME Solid State Drive

EVGA G5 850 W 80+ Gold Certified Fully Modular ATX Power Supply

**Comment by Rem0o** [comment]
I sure hope MSI allows you to control all your fans, they are the one making the hardware.  Sadly, I could ask MSI how to control their fans, they won't tell me. All that stuff is kept closed.

Support is handled by this library, feel free to contribute: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
