### ISSUE TITLE
Temp Sensor Data Incorrect

### ISSUE THREAD

**Issue by MSW2301** [Rem0o/FanControl.Releases#2071]
FanControl Temp Sensor Data is incorrect. 

Temp#1: 32°C
Temp#2: 28°C
Temp#3: 86°C (!)
Temp#4:   4°C (!)
Temp#5: 20°C

My guess is Temp#3 reports (incorrectly) the chipset and Temp#4 I don't have any idea.

They don't line up with HWInfo (nur with Temps reported in Bios)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

FanControl vs HWInfo

https://imgur.com/a/YxCId5w

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

Asus Strix B650e-e Mainboard
AMD 7800x3D CPU
Asus Strix 4090 GPU
4 x WD SN 850X M2 SSDs
64 GB (2 x 32 GB) Trident Z5 NEO DDR5-6000 RAM

**Comment by Rem0o** [comment]
Please see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

**Comment by DfrostX** [comment]
I would not worry too much about it. This look like a faulty reading. Classic from Asus boards

https://www.hwinfo.com/forum/threads/asus-tuf-gaming-b550m-plus-high-temp2-temperature.6667/
