### ISSUE TITLE
RX 6400 can be fan controlled on Linux, cant do the same on Windows

### ISSUE THREAD

**Issue by massatt212** [Rem0o/FanControl.Releases#2073]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

Can you get fan controller working on Windows for RX 6400, if you need any more info ill be happy to help

**Comment by Rem0o** [comment]
Only way to do so in windows would be through ADLX. Tried to dabble with it with https://github.com/Rem0o/FanControl.ADLX, but without a card and with miserable doc from AMD, hard to go forwards.

**Comment by massatt212** [comment]
I'm.trying the adlx, it sees the info, but the fan wont spin up

**Comment by Rem0o** [comment]
@massatt212  the library/plugin needs work. If you have experience coding .NET at all, you could take this on.

**Comment by massatt212** [comment]
.zero exp.with coding, idk if Linux stuff can help you, u should check them out a bit.

**Comment by RokeJulianLockhart** [comment]
Doesn't https://github.com/Rem0o/FanControl.Releases/issues/535#issue-1169197832 block this, @massatt212?

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX is much better now you can give it a try and report problems in that repo.
