### ISSUE TITLE
Another instance of Fan Control already running error

### ISSUE THREAD

**Issue by yungcammy** [Rem0o/FanControl.Releases#2075]
Seemingly whenever i close the app, my fans freeze at their existing setting (Task Manager still indicates an instance of Fan Control running in the tray.) 

This also means it's unusable unless the window is always open. 

Upon opening Fan Control, two instances appear in Task Manager before one closes, and after around 10-15 seconds Fan Control opens with this error:

An other instance of FanControl was running under user "S-1-5-21-1609447441-4060751834-1259962850-1005". It was was closed to start this new instance.

My fans also then go crazy as the control of the fans returns to my set curves, instead of the frozen phantom instance that seems to occur when Fan Control is in the tray.

I have tried multiple fresh reinstalls and such and am completely lost as to why this occurs, especially since I only have one copy of the software on my computer. It also persists following windows updates, driver updates and restarts.

Any help would be much appreciated, thank you!

**Comment by Rem0o** [comment]
Look at your task scheduler in windows.  Do you have 2 different tasks named fancontrol?

**Comment by yungcammy** [comment]
I only had one task but deleted it and restarted regardless. Unfortunately nothing has changed.

**Comment by S7R4nG3** [comment]
Started running into this one myself after the last update - I did a little bit of tinkering and found a fix that works for me:

Go into Task Manager -> Startup -> Fan Control -> Right Click -> Disable

I think the Task Manager Startup applications are conflicting with the Task Scheduler command causing the program to launch twice...

Once I disabled the Task Manager startup options, I rebooted and its back to normal.

Might be worth taking a peek to see how that Task Manager startup entry is getting written in...

**Comment by yungcammy** [comment]
Unfortunately for me, Fan Control doesn't seem to appear in the Task Manager Startup menu, which seems unusual, but thank you for giving your solution anyway and I'm happy you found a fix for it.

**Comment by TheViking12** [comment]
Fan Control doesn't even show up in task manager for me

**Comment by S7R4nG3** [comment]
Yea - could be related to executing the application as an elevated user (admin access)?

Another thing I tinkered on a bit to see if it'd change anything was within Task Scheduler, locate the task to start the app and my initial user set to execute the task ("When running the task, use the following user account:") was empty - I wen through the prompt and tried setting that to my local user account - no effect - then swapped it over to the Administrators group? 

Its still configured that way, maybe give that a try? If it doesn't resolve it, I'd still highly recommend reverting the user back to your login user to prevent any access elevation concerns...

**Comment by s-geissler** [comment]
Can confirm the same behavior.

I am running two different profiles (different configuration files) and switch between them using hotkeys that trigger a task scheduler task, so I can start the profile without the need to click the UAC window.

Now I am getting the same behavior where every time I switch to another profile, instead of silently switching configs, the GUI opens, and I get the message @TheViking12 posted above.

Each task essentially runs a command like `FanControl.exe -c config1.json` to switch to that specific profile. It used to be silent in the background, now the GUI opens up complaining of an already running instance.

**Comment by Rem0o** [comment]
See V172
