### ISSUE TITLE
Corsair Commander Core Plugin won't allow for 0% fan control

### ISSUE THREAD

**Issue by wsm78** [Rem0o/FanControl.Releases#2078]
**Describe the bug**
See title - and when attempting zero percent I get plenty of error popups. The RPMs do decrease but not to zero, and did make sure to exclude any and all rgb/fan control software besides this one.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/12851500/log.txt)

**Relevant hardware specs and setup**
Two Commander Cores with all fans/RGB connected into it (excluding GPU and RAM)

**Comment by DfrostX** [comment]
Maybe ask for support on the plugin repo? Its not the same dev.

[Here](https://github.com/EvanMulawski/FanControl.CorsairLink/issues)
