### ISSUE TITLE
Taskbar tray icon disappears with TaskbarX

### ISSUE THREAD

**Issue by krismg** [Rem0o/FanControl.Releases#208]
I'm not sure if it's an issue with Fan Control or TaskbarX (https://chrisandriessen.nl/taskbarx), but when TaskbarX is installed and running, the Fan Control taskbar icon will disappear from the tray. (Task Manager reveals Fan Control is still running in the background, albeit without the taskbar tray icon.)

**Comment by Rem0o** [comment]
If you remove TaskbarX from the equation, any issue?

**Comment by krismg** [comment]
> If you remove TaskbarX from the equation, any issue?

If TaskbarX hasn't run at all after signing in to Windows, I get zero issues with Fan Control.

If Fan Control tray icon already disappears, stopping TaskbarX won't bring the tray icon back. (A Windows user sign out then sign in, or Win restart, is required to make Fan Control's tray icon appear again.)
