### ISSUE TITLE
abnormal temperature shown

### ISSUE THREAD

**Issue by GRFTSOL** [Rem0o/FanControl.Releases#2080]
![图片](https://github.com/Rem0o/FanControl.Releases/assets/108245502/25dc1f9d-2f63-4a6e-9cd4-730277b6b84b)
as the picture, there is a 87.5℃ part, but I cant see anything in that temp in other software like aida64, and my computer has no load currently
Specs: 
![图片](https://github.com/Rem0o/FanControl.Releases/assets/108245502/76ffa452-0bcd-4a1c-8aad-826baec09225)

**Comment by DfrostX** [comment]
I would not worry too much about it. This look like a faulty reading. Classic from Asus boards

https://www.hwinfo.com/forum/threads/asus-tuf-gaming-b550m-plus-high-temp2-temperature.6667/

**Comment by GRFTSOL** [comment]
Thank you!

**Comment by GRFTSOL** [comment]
> I would not worry too much about it. This look like a faulty reading. Classic from Asus boards
> 
> https://www.hwinfo.com/forum/threads/asus-tuf-gaming-b550m-plus-high-temp2-temperature.6667/

Thank you!
