### ISSUE TITLE
Feature Request: Adjustable Rate of Change or a Time Window for Fan Speed Adjustments

### ISSUE THREAD

**Issue by Aydinhamedi** [Rem0o/FanControl.Releases#2081]
**Feature Description:**

I propose the addition of a feature that allows users to adjust the rate of change in fan speed (RPM). This would provide a smoother transition when increasing or decreasing the fan speed, rather than an abrupt change. 

**Use Case:**

This feature would be particularly useful in scenarios where a sudden change in fan speed could be disruptive or undesirable. For example, when running intensive applications, a user might want to gradually increase the fan speed over a certain time period rather than having it suddenly ramp up. This could provide a more pleasant user experience and potentially extend the lifespan of the hardware by avoiding abrupt changes in fan speed.

**Comment by Rem0o** [comment]
This feature exists already in the form of step up and step down.  Simply lower those way down.

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/8cdbcce4-332b-49fc-b050-27179af6532c)

**Comment by Aydinhamedi** [comment]
Oh sorry

**Comment by Aydinhamedi** [comment]
Now its the best fan control software ever
