### ISSUE TITLE
Version 171 Breaks Command Line Setting of Profile

### ISSUE THREAD

**Issue by ricperrott** [Rem0o/FanControl.Releases#2083]
Prior to version 171, I could call FanControl from the command line to set a specific profile such as..

`FanControl.exe" -c Default.json`

Now, after 171 if I try to do this I get an error message that

![Screenshot 2023-10-13 104254](https://github.com/Rem0o/FanControl.Releases/assets/1429693/837cf3f7-d31a-4c9d-a3fc-b5574353ec92)

This breaks a script that I have to automate profile switching and as such renders 171 useless for me.

Please look into this and revert this behavior if possible.

Thank you

**Comment by Rem0o** [comment]
See V172
