### ISSUE TITLE
Gigabyte RTX 4070 Gaming OC start and stop the fans

### ISSUE THREAD

**Issue by NoMan9200** [Rem0o/FanControl.Releases#2089]
Hello,
first thanks for the great SW!
i set a Graph Curve that stops the 3 fans of the RTX until reaching 65°C. In idle mode there is no problem, all fans including that from the RTX dont turn. When the GPU is busy the fans start turning after reaching 50°C although the Curve starts after 65°C. Nvidia 0% fan override is active. Other SW like MSI Aftferburner etc. is closed. The BIOS of the RTX is set to the silent mode. 
I would be really happy if this is a bug that you can fix. If i should submit some logs let me know.
Greetings.

**Comment by NoMan9200** [comment]
No idea? :-(

**Comment by Rem0o** [comment]
GPUs have internal rules that can't be changed.  The temperature at which they allow 0 RPM is one of them.   FanControl can't change that. You got to configure FanControl around that native behavior.  Keep in mind the 0-30 range also is not available from FanControl.
