### ISSUE TITLE
Is there any way to add VRAM Sensors for Nvidia 3000 Series

### ISSUE THREAD

**Issue by jetonr** [Rem0o/FanControl.Releases#209]
I guess I am not the only one with the overheating VRAMs for 3000 series, since the this is using the hwmonitor sensors can we by any chance have the temp for VRAMs as well?

**Comment by Rem0o** [comment]
` since the this is using the hwmonitor sensors`

Nop.  => https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

If you are a HWInfo user, you can use this to import the sensor: https://github.com/Rem0o/FanControl.HWInfo

**Comment by Artago** [comment]
> ` since the this is using the hwmonitor sensors`
> 
> Nop. => https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
> 
> If you are a HWInfo user, you can use this to import the sensor: https://github.com/Rem0o/FanControl.HWInfo

Would the sensor need to be added to LibreHardwareMonitor before the option is available in FanControl?

PS: Love the app! Good work!

**Comment by Rem0o** [comment]
> Would the sensor need to be added to LibreHardwareMonitor before the option is available in FanControl natively without a plugin?

Exactly.
