### ISSUE TITLE
White Blank UI

### ISSUE THREAD

**Issue by RaySoyama** [Rem0o/FanControl.Releases#2090]
**Describe the bug**
After the most recent Update, the FanControl UI is now a blank, white, empty UI that I can't open. The empty window shows up when I try to alt-tab, but I cannot select or open it. I tried using the win-arrowkeys to dock the window but that did not work.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
N/A

**Relevant hardware specs and setup**
Processor: AMD Ryzen 9 3900X 12-Core Processor 3.80 GHz
Installed Ram: 32.0 GB
GPU: NVIDIA GeForce RTX 3080 Ti
System: Windows 10 Home 22H2

**Image** 
![image](https://github.com/Rem0o/FanControl.Releases/assets/42445829/85162b4d-d0ea-4a1f-a35d-9db5d1626606)

**Comment by Rem0o** [comment]
try deleting your cache file in the configuration folder, then start the app.
