### ISSUE TITLE
Fan Control blocking boot drive creation when using Rufus 4.1

### ISSUE THREAD

**Issue by No-good-deed-goes-unpunished** [Rem0o/FanControl.Releases#2097]
**Describe the bug**
Fan control starts with Windows. A M.2 NVMe drive is connected via USB-C cable.
When I rebuild my Windows ISO I then use Rufus to create the boot drive on that external drive.
Rufus fails to build boot drive because Fan Control is accessing the dsrive.
Fan Control is installed on a different drive.
I have to exit Fan Control, create my boot drive and then restart Fan Control

**Relevant hardware specs and setup**
Happens on two different PCs: Z790 motherboards, 32gb/64gb RAM, RTX 30xx GPUs, Kingston KC3000D Boot drives
Windows 10 21H2 (19044.3208).

Error messages:
![fc_block_ext](https://github.com/Rem0o/FanControl.Releases/assets/138647241/13d0eb2a-8e47-4b56-8e17-b241fda7ca22)

![fc_error](https://github.com/Rem0o/FanControl.Releases/assets/138647241/3d4c053b-003f-4acd-abc7-71cb1dcd3a74)

**Fan Control versions affected**
I have tested it on 168, 170, 171 and 172. All exhibit the same behaviour.

**Comment by Rem0o** [comment]
Disable drive monitoring in Sensor settings.

**Comment by No-good-deed-goes-unpunished** [comment]
Ugh! ok, I guess I'll have to live with it.
I have a fan curve for the Kingston SSDs. It works on the temp sensors of the Boot SSD drive.
Rufus says the drive is locked for read/write. Wouldn't fan control only need to read sensors?

**Comment by No-good-deed-goes-unpunished** [comment]
Closed.
