### ISSUE TITLE
Request: NZXT Grid+ V3 Support

### ISSUE THREAD

**Issue by CZonin** [Rem0o/FanControl.Releases#210]
Is there any chance at support for the Grid+ V3 fan hub? I've noticed that it's possible within Argus Monitor without any separate integration.

**Comment by Rem0o** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/tree/master/LibreHardwareMonitorLib/Hardware/Controller/Nzxt

**Comment by Rem0o** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/812

**Comment by CZonin** [comment]
Ya tested out an earlier dll that worked perfectly with FanControl. I think they did some more updates to it since then. I'll test it more next time you do a release with LibreHardwareMonitor updated.

Glad to finally be able to use FanControl again!
