### ISSUE TITLE
Ignore Hysteresis at Min & Max Temps

### ISSUE THREAD

**Issue by solodolo-42** [Rem0o/FanControl.Releases#2107]
So I have the "Ignore hysteresis at min & max temps" checked where you can edit the graph curve. When I click on the Vertical Ellipsis, it is not showing as checked. It happens on all graph curves for me. See pics below.

<img src="https://live.staticflickr.com/65535/53286135061_72361ed9df_c.jpg" width="800" height="596" alt="hysteresis"/><br>
<img src="https://live.staticflickr.com/65535/53286385048_bbce9d04fb_c.jpg" width="800" height="353" alt="hysteresis-2"/>

**Comment by Rem0o** [comment]
Ahhh yes binding error.   The one in the dialog is binded properly and the setting itself works.  Will be fixed next version.

**Comment by Rem0o** [comment]
V173
