### ISSUE TITLE
Temperatures above 99 degrees will not fit in the tray icon

### ISSUE THREAD

**Issue by lonelymyp** [Rem0o/FanControl.Releases#211]
Temperatures above 99 degrees will not fit in the tray icon. Only the first two digits are displayed.
![image](https://user-images.githubusercontent.com/2085051/115128112-2bbb7f00-9fe4-11eb-9f08-d1d1fcc1b21a.png)

**Comment by Rem0o** [comment]
Well yes, maybe with anything above 99 I could set an icon meaning "hot" ?

**Comment by lonelymyp** [comment]
For some AMD sensors, this is a normal value, taking into account that a shift of +20 degrees can be. I do not know if it is correct to replace it.

**Comment by Rem0o** [comment]
I just can't fit 3 numbers in there while keeping it visible.

**Comment by carlosvroque** [comment]
Maybe add a different color/bold when above 100 and just display the last two digits? 

108 would show as **08** instead of the current 10.

**Comment by Rem0o** [comment]
Anything above 100 will be "!"
