### ISSUE TITLE
Fancontrol segfaults when window resized or moved to second monitor

### ISSUE THREAD

**Issue by sportsracer48** [Rem0o/FanControl.Releases#2115]
**Describe the bug**
The moment I move the fancontrol window to my secondary monitor it segfaults and closes. The same thing happens if I resize the window.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
The crash doesn't log anything there, but windows gives 
Faulting application name: FanControl.exe, version: 173.0.0.0, time stamp: 0xa8079461
Faulting module name: ntdll.dll, version: 10.0.19041.3570, time stamp: 0x3be1c500
Exception code: 0xc0000374
Fault offset: 0x00000000000ff279
Faulting process id: 0x168
Faulting application start time: 0x01da0e1941e68d6c
Faulting application path: C:\Program Files\fanControl\FanControl.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: b04df333-b652-44dc-9436-f4d533fe7f6a
Faulting package full name: 
Faulting package-relative application ID: 

**Relevant hardware specs and setup**
Windows 10. Main screen is 3840 x 2160, secondary is 1920 x 1080 to the left of the main aligned at the top

**Comment by Rem0o** [comment]
What happened exactly here?

**Comment by sportsracer48** [comment]
I found an identical issue
https://github.com/Rem0o/FanControl.Releases/issues/1582 and decided I
needed to diagnose the issue in more detail. So far it seems to have
something to do with cinebench. All I've done is eliminate possibilities so
far (it's not caused by an overclock, it doesn't depend on which monitors
are enabled, it happens on a fresh install, etc) it sometimes doesn't
happen and I have no idea why. My specs are identical to the ones in that
other issue except I'm on windows 10. Driver updates did not help.

**Comment by sportsracer48** [comment]
Well I have it fixed now and the most important part was letting GPU tweak 3 open 15 seconds before fancontrol to apply its settings. No clue why that mattered
