### ISSUE TITLE
nvidia rtx 3080, gpu curve not working

### ISSUE THREAD

**Issue by AIdenT99** [Rem0o/FanControl.Releases#2121]
Whenever i try to se the fan curve and allocate it to my gpu it'll either keep it at 0 rpm or it will make the middle fan in my gpu go up and then drop to 0 rpm constantly. no idea what is causing this
![Screenshot (445)](https://github.com/Rem0o/FanControl.Releases/assets/149964730/072d5a36-16a5-4305-ac2b-51746bd86fe6)
![Screenshot (444)](https://github.com/Rem0o/FanControl.Releases/assets/149964730/53d908eb-fd9e-45a8-9cae-8aefbc6f6bca)

**Comment by Rem0o** [comment]
Fans have a minimum % to make them spin at all.  Most likely your fan curve plays arround that threshold, which explains the start/stop.    From your screenshot, 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/c7538ed0-4f2b-49ab-a25e-fa9549e980dd)

those rpms are very low.   You should setup your fan curve to either be off, or make them spin at a minimum of like 700/800 rpm.   You can configure the "start/stop" % of these controls if you expand the control card. You should probably set those at 45% to be safe from what I can see.
