### ISSUE TITLE
I can't set Start % to 0%, It just goes to 30% 

### ISSUE THREAD

**Issue by Ligeek566** [Rem0o/FanControl.Releases#2128]
I don't know why but when I try to set my case fans to 0% so I can have them run under like 1300rps, it just doesn't let me, and after I set my fan curves in Bios, now only one case fan goes to 9% and AIO now aswell goes to 18% where it was 30% before.I tried checking boxes on Nvidia 0% hardware curve override and NvApiWrapper, but all stayed the same, also that probably wouldn't work because I have a Amd card.

**Comment by Rem0o** [comment]
You can't set your start% lower than your stop%. You need to adjust that first.
