### ISSUE TITLE
What are the functions of zh-CN, ru, pl and other folders?

### ISSUE THREAD

**Issue by wangwang37** [Rem0o/FanControl.Releases#2130]
When I opened the main folder and saw the names of these folders, I thought the software had multi-language support. But after checking the issues, I was very sorry to find that there is no multi-language support. 
So what is the function of the dll files in these folders? Confusion from newbies.
![image](https://github.com/Rem0o/FanControl.Releases/assets/74105320/33df3440-4371-4ace-874a-e580e7a3e25e)

**Comment by Rem0o** [comment]
Microsoft.Win32.TaskScheduler, a module FanControl uses to manage the scheduled task comes with resource files, those are simply packaged in. I could probably exclude those.
