### ISSUE TITLE
Confirmed the update prompt, something said failed in the cmd popup now wont launch

### ISSUE THREAD

**Issue by Trae132** [Rem0o/FanControl.Releases#2135]
Title really covers it, I see some other posts about virus but I didnt get a virus popup mine failed in the block box popup that happens every update.  I can download the 174 version new from the non github website version but how do I transfer all my setting to the brand new download?

**Comment by zuh** [comment]
Same happened to me, updating from 173 to 174 on Windows 11 produces this:

![kuva](https://github.com/Rem0o/FanControl.Releases/assets/1219673/55e21928-f872-45dd-a9fe-8c6f91788a33)

**Comment by Trae132** [comment]
> Same happened to me, updating from 173 to 174 on Windows 11 produces this:
> 
> ![kuva](https://user-images.githubusercontent.com/1219673/284794184-55e21928-f872-45dd-a9fe-8c6f91788a33.png)

Yup it seems to be working after I downloaded a fresh copy from his website getfancontrol.com and then copied my cache, json profile, and plugin folder.  Literally just did it 10seconds ago so not sure if its fully working but it certainly looks like my profile and settings.  Id like t hear from someone knowledgeable if I missed something.

**Comment by nilshomeier** [comment]
Same here. Updater failed due to some restrictions, and FanControl.exe wont launch now. Windows eventlog gives a .net error.
![2023-11-22 07_07_12-Ereigniseigenschaften - Ereignis 1026,  NET Runtime](https://github.com/Rem0o/FanControl.Releases/assets/10177623/6d06e892-8954-4212-96ea-eaaae9ea873c)

**Comment by Cersei123** [comment]
Same here!
Workaround -> Download the latest version manually and overwrite all data in the extisting path.

**Comment by burkm489** [comment]
Same happend to me. I got the previous release of FanControl. When I tried to install the update "174" some error messages popped up during installation for a second, and then FanControl had dissapeared. I looked for the prior installation: Gone on all drives.
I tried to install the FanControl Net Version 7: Nothing. Tried to do the same with Net Version 8: Nothing. My prior configuration seems to be gone also...

**Comment by Sturmfunke** [comment]
Same problem.
After  downloading the Net 8.0 version and starting it in a separate folder, it told  me I also have to install this: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer?cid=getdotnetcore (which was already installed apparently, so I just did a "repair").
After copying the files to my old FanControl folder where I have all the configs, the program fails to start: "Failing to initialize blabla".

But the program still seems to work. I had to load my configuration manually, which seems fine now.

**Comment by Sailing74** [comment]
Similar problem here with Win10. Saving the "Configurations" folder, deleting everything and reinstalling a fresh download of 174 fixed the problem for me.

**Comment by essinghigh** [comment]
Same issue on Win11, I just extracted FanControl_net_8_0.zip over my existing installation with no issues - config is all there.

**Comment by burkm489** [comment]
Hi Henry,

My problem seems to be, that my original FanControl folder has been deleted without a trace and the new installation, which I setup manually, seems to ignore my old configuration files. Strange…

Kind regards

 

 

Von: Henry Essinghigh ***@***.*** 
Gesendet: Mittwoch, 22. November 2023 08:19
An: Rem0o/FanControl.Releases
Cc: burkm489; Mention
Betreff: Re: [Rem0o/FanControl.Releases] Confirmed the update prompt, something said failed in the cmd popup now wont launch (Issue #2135)

 

Same issue on Win11, I just extracted FanControl_net_8_0.zip over my existing installation with no issues - config is all there.

**Comment by burkm489** [comment]
My problem is, that I don’t know the prior installation folder of FanControl. I looked around on all drives, but couldn’t find a trace of it.

My manual installations seem all to end up as “FanControl” folder in the root directory of my system. 

 

Von: Wolf-Burkhard Menzler ***@***.*** 
Gesendet: Mittwoch, 22. November 2023 08:27
An: 'Rem0o/FanControl.Releases'
Betreff: AW: [Rem0o/FanControl.Releases] Confirmed the update prompt, something said failed in the cmd popup now wont launch (Issue #2135)

 

Hi Henry,

My problem seems to be, that my original FanControl folder has been deleted without a trace and the new installation, which I setup manually, seems to ignore my old configuration files. Strange…

Kind regards

 

 

Von: Henry Essinghigh ***@***.*** 
Gesendet: Mittwoch, 22. November 2023 08:19
An: Rem0o/FanControl.Releases
Cc: burkm489; Mention
Betreff: Re: [Rem0o/FanControl.Releases] Confirmed the update prompt, something said failed in the cmd popup now wont launch (Issue #2135)

 

Same issue on Win11, I just extracted FanControl_net_8_0.zip over my existing installation with no issues - config is all there.

**Comment by xeophyte** [comment]
My FanControl didn't start after an update. Can't even start the FanControl.exe.
So, should I wait for some hotfix or "reinstall" and restore the config? Is restoring settings about restoring userConfig.json from the Configuration directory?
And btw, downloading from https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip?raw=true is VERY slow.

**Comment by essinghigh** [comment]
@xeophyte please refer to my earlier comment in this issue.
> Same issue on Win11, I just extracted FanControl_net_8_0.zip over my existing installation with no issues - config is all there.

You can just download the latest version manually and extract it on top of your existing install, this will only overwrite modified files so your config will not be lost.
https://github.com/Rem0o/FanControl.Releases/releases/download/V174/FanControl_net_8_0.zip downloads almost instantly for me.

**Comment by Peca21** [comment]
1. Go to FanControl install directory
2. Delete that json dll file
3. Run updater.exe

**Comment by Jakub-Mikolajczyk-pl** [comment]
For me Defender is blocking the update, it's pointing to this file, created when I try to update to 174:
<img width="189" alt="image" src="https://github.com/Rem0o/FanControl.Releases/assets/26859826/557236bb-43b8-4064-a42a-8e27b656fb77">

**Comment by Rem0o** [comment]
Usually the submission process for Defender takes less than a few hours at max, this time it takes way too long. Rolled back the old updater until it goes through.

**Comment by soenneker** [comment]
@Rem0o have you considered the AppData dir for installation?

Automatic updating is hard:

https://www.freecodecamp.org/news/the-architecture-of-an-intelligent-application-update-system-3fc2f27a4a2/

**Comment by andrelehto** [comment]
I ran into the same issue, a fresh download solved the issue: https://getfancontrol.com/ 

Remember to save your configs.

**Comment by zuh** [comment]
> Usually the submission process for Defender takes less than a few hours at max, this time it takes way too long. Rolled back the old updater until it goes through.
> 
> Sorry for the inconvenience everybody.

Just to confirm, after the rollback my update went through successfully without any other actions (I deliberately didn't update and was still running 173). Thanks!
