### ISSUE TITLE
FanControl does not start anymore after the latest update

### ISSUE THREAD

**Issue by mmeiburg** [Rem0o/FanControl.Releases#2137]
**Describe the bug**
After the update if I want to start FanControl nothing happens.
If I want to restart the updater I get the "System.io Exception" that a process is blocking the execution.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
The log file has no entries related to this, the last entry is from November 9th.

**Relevant hardware specs and setup**
Windows 11 Pro - 10.0.22621 Build 22621
CPU: AMD Ryzen 9 5900X
GPU: Intel Arc 770
RAM: 32GB

I would really help you out with more information but I don't know were I can get it.
Where can I find the current version of FanControl or the update log?

**Comment by essinghigh** [comment]
Duplicate of #2135

**Comment by mmeiburg** [comment]
Like in #2135 mentioned downloading the latest zip file and copy it over the local files fixes the issue. 
System is silent again :)
