### ISSUE TITLE
FanControl quits silently

### ISSUE THREAD

**Issue by alperozcetin** [Rem0o/FanControl.Releases#214]
It quits after ~10 mins after startup (auto start as minimized), without any exception. Not visible on system tray and not controlling fans. Couldn't found any events/logs.

**Comment by Jelliol** [comment]
Same here. Since last update.
Even only when I focus on tray icon, it quits.

**Comment by rnd-zrg** [comment]
Same here since v75. It quits roughly 10 minutes after each startup; it stays active indefinitely without any subsequent issues when I reopen it afterwards.

**Comment by Rem0o** [comment]
Was having the same issue on my laptop. I couldn't find anything. I recompiled it, and since then I got no issue :/ .    Run the updater.exe in your app folder.

**Comment by rnd-zrg** [comment]
Still nothing. Tried running the updater, tried nuking the previous installation and re-installing it from the fresh zip, still the same result. It quits silently after roughly 5 to 10 minutes after each startup.
After it quits, I launch it again - does not quit after that.

**Comment by rnd-zrg** [comment]
This fixed it! Thanks a lot.

**Comment by Dogeboge1023** [comment]
updated to v76 and it still quits

**Comment by Rem0o** [comment]
If won't delete the old task @Dogeboge1023
