### ISSUE TITLE
"The errors occured while restoring the configuration: Missing sensor for time average sensor Max AVG"

### ISSUE THREAD

**Issue by alperozcetin** [Rem0o/FanControl.Releases#215]
I have created a mix sensor and a time average sensor for that, having this error immediately when FanControl is launched. Potentially an issue of order when config is loaded.

**Comment by Rem0o** [comment]
But the chosen sensor for your time average sensor is loaded properly? I think my deserialization validation has an issue and doesn't fit the actual deserialization behavior, which here I believe is working properly.
