### ISSUE TITLE
Set app tab bar to black

### ISSUE THREAD

**Issue by KotletJB** [Rem0o/FanControl.Releases#2150]
![image](https://github.com/Rem0o/FanControl.Releases/assets/62251729/272d5e3a-0cdd-4529-b9e1-db638993163c)

enabling dark mode should also change bar on top do dark

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/68e7da73-9388-4b41-afbd-2f13717b432f)

It's coming.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V178
