### ISSUE TITLE
Fancontrol keeps crashing everyday

### ISSUE THREAD

**Issue by infowege** [Rem0o/FanControl.Releases#2158]
### Discussed in https://github.com/Rem0o/FanControl.Releases/discussions/2157

<div type='discussions-op-text'>

<sup>Originally posted by **infowege** November 27, 2023</sup>
Quelle
FanControl

Zusammenfassung
Nicht mehr funktionsfähig

Datum
‎26.‎11.‎2023 14:31

Problemsignatur
Problemereignisame:	CLR20r3
Problemsignatur 01:	FanControl.exe
Problemsignatur 02:	174.0.0.0
Problemsignatur 03:	c63f3d0e
Problemsignatur 04:	FanControl
Problemsignatur 05:	174.0.0.0
Problemsignatur 06:	c63f3d0e
Problemsignatur 07:	14
Problemsignatur 08:	4c
Problemsignatur 09:	System.NullReferenceException
Betriebsystemversion:	10.0.22631.2.0.0.256.48
Gebietsschema-ID:	1031
Zusatzinformation 1:	e35e
Zusatzinformation 2:	e35e827e6acfd1d25039555aaf63a14a
Zusatzinformation 3:	6bfb
Zusatzinformation 4:	6bfb5909d1c43c95eec601cd16c576ed

![image](https://github.com/Rem0o/FanControl.Releases/assets/50275529/1651ebaf-32d4-41e4-94dc-9afdae4eff4f)

</div>

**Comment by Rem0o** [comment]
The updater had an issue with the latest update.

Try and take a fresh install from https://github.com/Rem0o/FanControl.Releases/releases/tag/V174 and copy it on top of your existing installation.   Keep your "Configuration" folder.
