### ISSUE TITLE
Source Available?

### ISSUE THREAD

**Issue by Bennett-Fourr** [Rem0o/FanControl.Releases#2159]
I know in the past you have [stated](https://github.com/Rem0o/FanControl.Releases/issues/89#issuecomment-777726717) that you do not want to make the code open source. I was wondering if there was any chance you could do something like what [Unreal Engine](https://www.unrealengine.com/en-US/ue-on-github) does or make it [Source Available](https://en.wikipedia.org/wiki/Source-available_software) so that people can examine the code without having to use tools like Ilspy.

**Comment by Rem0o** [comment]
What for? As you said, those in the known can already use a variety of tools if for some reason they want to dig in and look for something.
