### ISSUE TITLE
When FanControl is moved under "Program Files" Task Scheduler command is not working

### ISSUE THREAD

**Issue by alperozcetin** [Rem0o/FanControl.Releases#216]
When FanControl is moved under "Program Files" Task Scheduler command is not working due to the space between Program and Files.

"cmd.exe /C start C:\Program Files\FanControl\FanControl.exe"

Error: "Windows cannot find 'C:\Program'. Make sure you typed the named correctly, and then try again."

**Comment by Rem0o** [comment]
Run the Updater.exe and delete the task in the task scheduler before starting back fancontrol.

**Comment by Rem0o** [comment]
V77 fixed the task for good.
