### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by BOF007** [Rem0o/FanControl.Releases#2163]
Hello,

How do i uninstall the program? I do not see it in the control panel, or the startup shell, yet it starts up every boot.

As it does not work on my Dell Precision 5480

**Comment by Rem0o** [comment]
Untick this: 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/8affd51b-c37f-4a9b-8089-d5c311bf2102)

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#uninstall
