### ISSUE TITLE
EVGA 1080TI FTW 3 - Only controls one fan. Doesn't find the other two fans

### ISSUE THREAD

**Issue by jjrrw174** [Rem0o/FanControl.Releases#2164]
Hello,

I have a GTX 1080TYI FTW 3 GPU. It's connected via a daisy chained PCIE 6+2 pin wire

Fan Control only find the first fan. When changing speed manually, only the first reacts to this.

Anyway to change this behaviour?

**Comment by Rem0o** [comment]
Usually triple fan cards have actually 2 fan channels, where 1 fan is on 1 channel, and the other 2 fans are connected in parallel to the other channel. 

Can you send your config (json file) ?

**Comment by Rem0o** [comment]
Ok so only 1 channel detected... maybe try to go into sensor setting, untick NvAPI and tick "GPU" in LHM, then refresh?  See if that backend detects 2 channels.... If it doesn't maybe that card only has 1 normal channel that NVAPI sees and the other 2 fans are configured in a non-standard way by EVGA.

**Comment by Rem0o** [comment]
@jjrrw174  in your lastest test, you didn't untick NVAPIWrapper, since it still there in the config.

**Comment by jjrrw174** [comment]
I have disable it a few times but nvi keeps appearing in the config.
[userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/13518953/userConfig.json)

**Comment by jjrrw174** [comment]
I can see all fans in GPU-Z

![image](https://github.com/Rem0o/FanControl.Releases/assets/125767458/63b8da59-d1e9-47fd-8acf-314d84833ca7)

![image](https://github.com/Rem0o/FanControl.Releases/assets/125767458/7694f97b-00d7-4cb9-92ab-9910ae96f764)

**Comment by Rem0o** [comment]
ahhh, did a little research on iCX and indeed seems like a non-standard way for EVGA to manage their fans.  Probably mapped to an I/O port somewhere that could probably be accessed with WinRing0 , but I found no example anywhere on how those could be controlled.  I think it was only limited to the 10XX series also, so not exactly widespread.  I would stick to EVGA PrecisionX for your GPU fans, just leave it unchecked in FanControl.

**Comment by MeatSafeMurderer** [comment]
> ahhh, did a little research on iCX and indeed seems like a non-standard way for EVGA to manage their fans. Probably mapped to an I/O port somewhere that could probably be accessed with WinRing0 , but I found no example anywhere on how those could be controlled. I think it was only limited to the 10XX series also, so not exactly widespread. I would stick to EVGA PrecisionX for your GPU fans, just leave it unchecked in FanControl.

I'd really appreciate if you were to look into this again. PrecisionX is hot garbage (not to mention abandoned now) and even just basic fan control with it is a frustrating experience, with it constantly resetting, forgetting settings, not applying, etc.
