### ISSUE TITLE
[Help] ASRock AMD Radeon RX 7800 XT no fan control available

### ISSUE THREAD

**Issue by grigory-bogush** [Rem0o/FanControl.Releases#2174]
I have ASRock AMD Radeon RX 7800 XT and ASRock 650m Pro Rs motherboard.
I installed the AMD plugin and the fan now shows up, but there 0 rpm and no percentage reported at all.

I would like to know if it's on Fan Control's side or ASRock just doesn't allow it and if there is any way to enable manual control.

**Comment by DfrostX** [comment]
From the front page
Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!

and

**(_EXPERIMENTAL)_** https://github.com/Rem0o/FanControl.ADLX (AMD gpus)

In other words if the **(_EXPERIMENTAL)_** plugin doesn’t work, then... No
