### ISSUE TITLE
Fancontrol doesn't initialise upon opening

### ISSUE THREAD

**Issue by 4GHB** [Rem0o/FanControl.Releases#2180]
It was working when i first downloaded, after every restart of my PC, it would fail initialising upon start up, after that i turned off the auto start, and started it manually. Now it just refuses to work no matter what.

The error log:
![Screenshot 2023-12-06 160018](https://github.com/Rem0o/FanControl.Releases/assets/153065982/41e24d80-d421-4c60-b275-7e7a97544ec9)

Running an I7-14700KF, ASUS TUF TUF GAMING B760M-PLUS WIFI motherboard with an  RTx4070.

**Comment by ShomuH** [comment]
Same thing here. It was working just fine, but all of a sudden it doesn't start up anymore. Windows doesn't prompt any errors. Howe ever, the Windows Task Scheduler shows an error: (0xC0000005)
White-Listing FanControl.exe in Windows defender didnt work. Windows didn't allow me to set an exception for FanControl on "Data Execution Prevention". 
Is there any fix? I would love to keep using FanControl for my Fan Control <3

**Comment by Rem0o** [comment]
@ShomuH  Try downloading https://github.com/Rem0o/FanControl.Releases/blob/master/Updater.exe, put it inside your FanControl folder, and run it as admin.

**Comment by ShomuH** [comment]
> @ShomuH Try downloading https://github.com/Rem0o/FanControl.Releases/blob/master/Updater.exe, put it inside your FanControl folder, and run it as admin.

@Rem0o
Awesome! FanControl is up again :) Thanks for the great tool and the fast reply! I donated you a coffee ;)
