### ISSUE TITLE
Version 174 is waking my computer from sleep

### ISSUE THREAD

**Issue by astorm67** [Rem0o/FanControl.Releases#2181]
I've noticed over the last couple of days that my computer had been waking from me putting it to sleep overnight. I decided to check event viewer when it happened today and saw the following: 

A service was installed in the system.

Service Name:  R0FanControl
Service File Name:  C:\Users\*****\Desktop\Computer Stuff\FanControl\FanControl.sys
Service Type:  kernel mode driver
Service Start Type:  demand start

Fan Control also had trouble recovering any of my configs next time I intentionally woke my computer, but I saw another thread on here that said something along the lines of open HWiNFO, close Fan Control, close HWiNFO, and restart Fan Control, and that seemed to work. 

[Fan Control Log.txt](https://github.com/Rem0o/FanControl.Releases/files/13593226/Fan.Control.Log.txt)

Specs:

V174
CPU: Ryzen 5700x
GPU: Asrock 6700xt
Mobo: MSI Mag b550 Tomahawk Max Wifi
PSU: Thermaltake Toughpower GF3 750W
5 Deepcool 120mm fans and 3 Arctic 120mm fans being controlled by the software. All PWM

**Comment by Rem0o** [comment]
What kind of sleep mode for the WinRing0 driver to still be running? Is it one of those "half sleep" C-State kind of sleep where processes are still running?

**Comment by astorm67** [comment]
Sorry, I'm not entirely sure how to check that. When I search my files for that driver, though, it shows up in the files for OpenRGB, which I do have some startup settings selected for.
