### ISSUE TITLE
Librehardwaremonitor dosn't detect my temp sensor probe

### ISSUE THREAD

**Issue by dsalcido1** [Rem0o/FanControl.Releases#2182]
I wanted to set my fan curves to an alphacool fitting temp sensor that i have in my pc but the hardware monitor built in doesnt detect this probe but some other software that i have does detect like pcid hwmonitor and msi center
![Screenshot 2023-12-06 205632](https://github.com/Rem0o/FanControl.Releases/assets/153150009/30f0299c-78d6-4ef9-9f43-966a67ada2df)

**Comment by Rem0o** [comment]
Please see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
