### ISSUE TITLE
Microstutters in VR with Meta and PICO headsets

### ISSUE THREAD

**Issue by olinapa** [Rem0o/FanControl.Releases#2184]
This is maybe niche for users here so I hope the developer can help.

I play PCVR, mostly Simracing titles like AMS2, ACC, RF2. Since I reinstalled Fancontrol, and this might have been the case before,I am getting microstutters and those with the 3 headsets I own(Quest2, Pico Neo3Link and P4)

its perceived with the Q2 and P4 and somehow annoying but I can live with that at the moment, but with the Neo3Link its just unbearable. You can see in the screenshot the spikes I am getting as an evidence, in VR its terrible feeling

Any guidance how I could fix that because the workaround I found and why I am writing here, is that by switching Fancontrol Off, the Games are butter smooth again

Thanks in advance

![image](https://github.com/Rem0o/FanControl.Releases/assets/153345001/88802625-c0cf-496c-bfa9-d19e96d0d068)

**Comment by Rem0o** [comment]
FanControl has its process priority set to above normal.  It only really uses very little CPU, but that might be the cause. Try setting it to "normal" and see if something changes.   Also, what do you got enabled in sensor settings? The more stuff you got in there, the more resources the program will take.

**Comment by olinapa** [comment]
> FanControl has its process priority set to above normal. It only really uses very little CPU, but that might be the cause. Try setting it to "normal" and see if something changes. Also, what do you got enabled in sensor settings? The more stuff you got in there, the more resources the program will take.

thanks a lot for your reply. its already set as "Normal" in my install.

as per sensors,I have all the box ticked since I am using Corsair PSU, Asus GPU, Ryzen CPU and Gigabyte MB

![image](https://github.com/Rem0o/FanControl.Releases/assets/153345001/d4723eae-93ef-434e-8520-a18d3d2ce83a)

**Comment by Rem0o** [comment]
@olinapa  you might not need all of these ticked, depending on what sensors you use for your fan curves.  Since I didn't see your config I can't really tell, but my guess is that you only really need Motherboard, CPU, GPU and that's it.

**Comment by olinapa** [comment]
> @olinapa you might not need all of these ticked, depending on what sensors you use for your fan curves. Since I didn't see your config I can't really tell, but my guess is that you only really need Motherboard, CPU, GPU and that's it.

ok thanks a lot,I will do a 1st run by reducing CPU priority even below normal and check the impact.

Then next remove some of these sensors as I concretely use 2 variables to trigger the Fans speeds, my RTX GPU core temp and my 5800x3D core temp

![image](https://github.com/Rem0o/FanControl.Releases/assets/153345001/4da6184f-1301-444a-9f18-ce5ed6ac3b9a)

**Comment by olinapa** [comment]
tried to lower even further CPU and it made no difference, the stutter in Game was still the same.

same NO effect by unchecking the various sensors in the settings

I am stuck right now.

**Comment by Rem0o** [comment]
Try and replace "GPU" with NvAPIWrapper . You'll have to reconfigure with the sensors from that provider, but give it a shot.

**Comment by olinapa** [comment]
> Try and replace "GPU" with NvAPIWrapper . You'll have to reconfigure with the sensors from that provider, but give it a shot.

ok I will.thanks again

**Comment by olinapa** [comment]
@Rem0o this did the trick, using the NVAPIwrapper got me rid of these stutters and I can control all my PC case fans and AIO still.
thanks for  pointing me towards the right direction
last question maybe and sorry for being a pain, the LHM has both GPU core and hotspot temps bot NVAPI looks like Core only right?

**Comment by Rem0o** [comment]
Yes Core only available from there. It's a much lighter implementation with some missing features.

**Comment by Globespy** [comment]
> @Rem0o this did the trick, using the NVAPIwrapper got me rid of these stutters and I can control all my PC case fans and AIO still. thanks for pointing me towards the right direction last question maybe and sorry for being a pain, the LHM has both GPU core and hotspot temps bot NVAPI looks like Core only right?

I will try this out as it seems that any new Nvidia driver is a stutter fest, and the single culprit is FanControl. Took me a while to figure this out as I assumed a simple piece of software like FanControl could not be the problem.
Any GPU monitoring causes micro stuttering in all games, so I had to revert to the garbage Fan5 BIOS fan control (X570 Aorus Master) which I really didn't want to do.
I will check out this NVAPIwrapper to see if it resolves as I really love FanControl.
