### ISSUE TITLE
Program Cash 

### ISSUE THREAD

**Issue by Grant-K** [Rem0o/FanControl.Releases#2185]
**Describe the bug**
The Fan Control Software Crashes upon trying to create a new config

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
Custom Built with a Corsair Icue Commander core XT fan controller and silent wings 4 fans and 1 noctua fan

**Comment by Rem0o** [comment]
At what part exactly does it crash? During the initial assisted setup?

**Comment by Gareassan** [comment]
yesterday it was working for me.

today i get an error on startup ( also using corsair plugin ) 
Fancontrol starts without plugin

11.12.2023 19:34:28: System.UnauthorizedAccessException: Zugriff verweigert (Ausnahme von HRESULT: 0x80070005 (E_ACCESSDENIED))
   bei Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   bei Microsoft.Toolkit.Uwp.Notifications.ToastNotifierCompat.Show(ToastNotification notification)
   bei FanControl.Domain.WindowsNotificationService.Notify(String message)
   bei FanControl.Domain.UpdaterService.<CheckForUpdateAsync>d__17.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FanControl.App.<OnStartup>d__12.MoveNext()
