### ISSUE TITLE
Crashing on version 76

### ISSUE THREAD

**Issue by Mrkkkkc** [Rem0o/FanControl.Releases#219]
Don't really know when it crashes or if it starts at all.
I have it in system tray on start-up, so I never really notice if it crashes on start or not (seems that others have similar issue as well)

![image](https://user-images.githubusercontent.com/79404196/115780169-5ae93c00-a3a8-11eb-84d8-d62a45178df1.png)

**Comment by razz-matazz** [comment]
From time to time I notice that my FanControl (76) icon is missing in my taskbar. So it has crashed without any information.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/217
