### ISSUE TITLE
The program does not start minimized

### ISSUE THREAD

**Issue by Kraton96** [Rem0o/FanControl.Releases#2191]
The program does not start minimized, I tried deleting the folder and downloading the program again, but the problem remained.

**Comment by Rem0o** [comment]
Do you get an error popup or any other kind of popup when the app starts?

**Comment by Kraton96** [comment]
No type of error appears..

**Comment by pythagorasg** [comment]
I have the same issue after clean install of windows 11 23h2, fan control doesn't start automaticaly.
I have tried to add to registry the .exe file, run as admin checked in compatibility mode. Tried to switch off start minimized, reboot, on again reboot. Nothing.

**Comment by pythagorasg** [comment]
> I have the same issue after clean install of windows 11 23h2, fan control doesn't start automaticaly. I have tried to add to registry the .exe file, run as admin checked in compatibility mode. Tried to switch off start minimized, reboot, on again reboot. Nothing. There is no option start automaticaly with windows, only start minimized.

I fix it, although the program was transfered from previous windows setup to a hard drive and then as it was to the new setup, option "Start at user log" on was disabled.

**Comment by Kraton96** [comment]
The problem still hasn't been resolved, I've tried all kinds of solutions. Does anyone know how to help me?

**Comment by Kraton96** [comment]
It seems I was able to solve the problem. Below I leave the solution.

1) Disable startup minimized from the application and restart your computer

2) Add to the registry the automatic startup of the program in this location: "Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" , add a string value with the path of the program: "C:\Program Files ( x86)\Fan Control\FanControl.exe" -m. Obviously the path varies based on where you placed the folder. The "-m" at the end is used to start it minimized.

3) At this point restart the PC once again

4) The program will not start by itself, you will need to open it manually and re-enable autostart and icon startup from the program settings. Restart your PC one last time and if everything goes well, you will have solved the problem.

**Comment by herbp98** [comment]
@Kraton96 hi, i dont think my brain is smart enough to follow these steps, so i really need your help with this. do you have a discord?

**Comment by FeintDoxx** [comment]
> [@Kraton96](https://github.com/Kraton96) hi, i dont think my brain is smart enough to follow these steps, so i really need your help with this. do you have a discord?

From my experience, startup issues happened on .net 6 and newer .net 4.8 haven't had issues myself.

But if you're still looking to go down this path see the photos:

paste the location in the navigation bar at the top:
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

right click and add a string, name it "Fan Control" or "FanControl", just choose a name in this case, and change its value to:
`"C:\Program Files ( x86)\Fan Control\FanControl.exe" -m`

or as mentioned change the location if you installed it elsewhere.

Follow the remainder of the steps of restarting and enabling manually.

![Image](https://github.com/user-attachments/assets/1a5943a5-0e6c-46f5-b51a-55cdacaa3498)
![Image](https://github.com/user-attachments/assets/d15a9ec9-fdbb-47ff-8f1e-e327d23217c5)
![Image](https://github.com/user-attachments/assets/679c0438-1420-49e5-9995-0a2b2d6fa4ef)
![Image](https://github.com/user-attachments/assets/108d8842-c484-482c-8fce-c9d027a1d255)

Although in my case, I just have .net 4.8 version installed and the my settings for the app are as shown in the last photo. Don't have the registry edits in place and working fine on startup.
