### ISSUE TITLE
FanControl stops working at random (seemingly)

### ISSUE THREAD

**Issue by brunoherrera** [Rem0o/FanControl.Releases#2194]
I have a fan setting that sets fans to 50%, which I add to the mix fan curve before starting a gaming session, what I usually do after I'm done gaming, is just closing FanControl discarding any changes as a way to remove the gaming settings (set fans at 50% speed minimum) and I keep doing my stuff as usual.

But then I either detect the pc being noisy (usually because I leave the room and come back and I can tell it's louder than in regular use) and that makes me check if everything is ok using monitoring apps, or just because I regularly check the monitoring tools anyways, and notice gpu and cpu liquid temperature are lower than usual, and that's because fan control stopped.

FanControl does not respond, but not in the typical Windows way, in which you can see it grey out a bit and the window title says "(Not Responding)", no, this kind of not responding is literally not responding, all sensors freezes, and when I try to refresh sensors, usually it keeps displaying the refreshing notice in the middle, infinitely, but this time it didn't even show that; And another symphtom is that when I right click tray icon and select exit, the icon goes away, seemingly exiting successfully but in process explorer shows that it hasn't closed at all.

I will append the log, if you need any other information about this let me know.

And many thanks in advance.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13664254/log.txt)

v157 .NET 8

**Comment by Rem0o** [comment]
Your log is filled with LIQUIDCTL plugin stuff.
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/935edeee-cfc9-472d-916b-8951ecdbe101)

**Comment by brunoherrera** [comment]
> Your log is filled with LIQUIDCTL plugin stuff. Might want to take a look at that plugin. ![image](https://private-user-images.githubusercontent.com/14118956/290301096-935edeee-cfc9-472d-916b-8951ecdbe101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTQ4NzgsIm5iZiI6MTcwMjQ5NDU3OCwicGF0aCI6Ii8xNDExODk1Ni8yOTAzMDEwOTYtOTM1ZWRlZWUtY2ZjOS00NzJkLTkxNmItODk1MWVjZGJlMTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE5MDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNWZmMzdhM2MyZTZkOGUxODYxNzYzYTUxNzZmYmY5YjMwNDhiY2FkZWM1NmRjYmZlNzI2MTU0YjE3ZWZkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1z4wT2JJDSuYqXFF55ccBSACFSx7r9W4GfmzGZ-t_c)

why does it have your system's user name though?

**Comment by Rem0o** [comment]
Because somehow some debug information didn't get stripped in the dll.
