### ISSUE TITLE
All this is unnecesarily complex. 

### ISSUE THREAD

**Issue by kovan** [Rem0o/FanControl.Releases#2196]
There should be a "Thermostat" option, like in the heating and cooling systems of homes, cars, and almost everything.
"Thermostat" means, keep the temperature at below this level. 

All this fan curves... etc. is unnecesarily complex (apart from not being conceptually right, because, for example, maybe in winter 500rpm is enough when the CPU is at 40º, but in summer you need more RPM at that temperature).

I also tried the "Auto option", but it doesn't exactly do the "Thermostat" thing I was referring to.

**Comment by Rem0o** [comment]
The difference with computers is that the thing you are trying to control temperature can swing 50 degree is less than a second and vary very rapidly. Thermostat are best with slow changing temperatures.  PID style controllers for PC fan control simply does not work, that's the reason no one does it. 

"Auto" was my best shot at it.   Maybe we can see the settings you applied and try to tweak them for the desired effect?

**Comment by kovan** [comment]
I disagree with your first part. If the temp ramps up rapidly you just ramp the fans equally fast.

About the "auto" option, it was working "almost" right; in the sense, it was keeping the temperature below the desired amount. The problem was that to do that it was turning the fans on and off every few seconds, which was annoying, instead of finding the "sweet spot" RPM to keep the temp at that level. I can post the exact settings, I'll do it in the next comment because I have to switch computers.

**Comment by kovan** [comment]
Ohh sorry, I deleted it. I tried a lot of things. I think I was using "Idle temp" as the desired maximum temperature, and the rest of the settings I don't remember, sorry.
