### ISSUE TITLE
Fancontrol erroneously appears on top of all windows even if minimized to the system tray.

### ISSUE THREAD

**Issue by 333hronos** [Rem0o/FanControl.Releases#2197]
**Describe the bug**
Fancontrol is incorrectly detected by Nvidia ShadowPlay as a foreground program, causing videos to be placed in the wrong folder named "Fancontrol.exe".
For example, if I record a desktop, or a browser, or from a messenger client, the video recordings should be placed in folders with the appropriate name ("Desktop" or "Firefox" or "Telegram.exe"). Instead, the videos are placed in the "Fancontrol.exe" folder, despite the fact that the program is minimized to the system tray.
Perhaps this is due to the fact that the program does not really minimize completely, but remains invisible somewhere on top of the screen.
This started a couple of months ago. Previously, videos were placed in the correct folders, despite FanControl running in the background, being minimized to the system tray.
https://i.imgur.com/9qLFwdu.png
I have to move the recorded videos to the correct folders each time, and give the videos the correct name (since the title of the video also indicates the title of the program in which it was filmed).

**Is there a log.txt file next to FanControl.exe with recent date entries?**
https://docs.google.com/document/d/10KZWq04_O8AW6kjI5lq-JI1lFDk-5FEqnOEN-E0R1lU/edit?usp=drive_link

**Relevant hardware specs and setup**
i5-11400f, Asus tuf gaming B560M-E, 16gb ram, rtx 4060 ti 16gb, Win 10 Pro 22H2

**Comment by Rem0o** [comment]
I can't think of anything special FanControl does with its window.  When you close the window, it's gone. Only the process remains . There is no trickery. Perhaps it's more of a shadowplay bug?  I don't see anything really I can do on my end to help you with that.
