### ISSUE TITLE
Make tray icon/temp high-res

### ISSUE THREAD

**Issue by cmeeren** [Rem0o/FanControl.Releases#220]
I have a high-DPI screen and am using 150% scaling, and the FanControl temperature tray icon is visibly lower-res than my other tray icons. (Sorry about the screenshot-of-screenshot thing; it's a workaround for limitations in Snip & Sketch when you use scaling.)

![image](https://user-images.githubusercontent.com/7766733/115856250-8c0b5000-a42c-11eb-8ab2-f0f7c68ec3ff.png)

**Comment by Rem0o** [comment]
If you can find me a cookie cutter way of handling creating a text to Tray icon in WPF that is DPI aware, I'm all ears.

**Comment by Rem0o** [comment]
Right now my code looks something like this

```c#
var bitmapText = new Bitmap(16, 16);
var graphics = Graphics.FromImage(bitmapText );
graphics .TextRenderingHint = System.Drawing.Text.TextRenderingHint.SingleBitPerPixelGridFit;
graphics .DrawString(temperatureText, _fontToUse, _brushToUse, -3, -1);

var icon = Icon.FromHandle(bitmapText .GetHicon());
```

Putting a higher number in the bitmap resolution doesn't result in a clearer text.

**Comment by cmeeren** [comment]
> Putting a higher number in the bitmap resolution doesn't result in a clearer text.

Did you try this with Windows scaling set to e.g. 150%? (`Bitmap(24, 24)` should fit with 150%.)

I'd try this myself, but I can't find the source. Is it on a private repo?

Other than that, I don't have any ideas. Tried searching a bit, but didn't find anything.

**Comment by Rem0o** [comment]
Dup of https://github.com/Rem0o/FanControl.Releases/issues/38
