### ISSUE TITLE
MSI RTX cannot set the speed below 30% or activate fan stop.

### ISSUE THREAD

**Issue by Draken69CZ** [Rem0o/FanControl.Releases#2200]
On the GPU I can't set the fan speed lower than 30% or activate fan stop at lower temperatures, is there any way to deactivate the scrubber at lower temperature to activate fan stop or other solution?
 
<img width="703" alt="01" src="https://github.com/Rem0o/FanControl.Releases/assets/154266745/f2e56de3-627c-4b95-a7ff-ecf3eafc7f09">
<img width="703" alt="02" src="https://github.com/Rem0o/FanControl.Releases/assets/154266745/3293b0ff-9106-4f3f-add8-a06320262af3">
Thank you.

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/219d89a4-699a-40cb-99cd-2a88fbd7a4ff)

Read the (?) carefuly.
