### ISSUE TITLE
Fan Control not applying fan curve 

### ISSUE THREAD

**Issue by Lacysda** [Rem0o/FanControl.Releases#2201]
I recently noticed that fan control does not apply my curve to some fans on my Corsair controller unless I go back in and increase the percentage of the fan speed and then bring it back down. The fans they are applying it to are on a +7% offset. I have to do this everytime I start my pc in order to use the fan curve correctly. If there is a fix to this that anyone’s knows about it will be appreciated. Thank you!

![IMG_6131](https://github.com/Rem0o/FanControl.Releases/assets/154270615/adb86dd2-ec2b-4cf5-aab7-3ea87887c466)

Other times the fans on an offset also won’t apply.

![IMG_6132](https://github.com/Rem0o/FanControl.Releases/assets/154270615/8a745408-efd4-4ded-ab56-81606fea72b2)

**Comment by Rem0o** [comment]
All of the problematic fans are from the Corsair plugin? I don't see anything wrong from FanControl's perspective.  What kind of start/stop% are set on those?

**Comment by Lacysda** [comment]
Yes all on the Corsair plugin. Currently they're on a 0% start 0% stop as the programs automatic feature didn't work with them which I'm assuming is bc it's from a plugin. This is my first pc and I'm not too sure what it means or what I would set it too.

**Comment by Lacysda** [comment]
If anyone has a solution to this I'd appreciate it. I've attempted to delete fan control and redownload and it still happens.
