### ISSUE TITLE
FanControl crashes when loading alternative configurations

### ISSUE THREAD

**Issue by altae7** [Rem0o/FanControl.Releases#2202]
I use the latest version of FanControl (175) and I've got multiple configurations for different situations. There is a standard configuration called "Fix" which I use whenever there is no specific use case. Then there are other configurations which are for certain use cases like one for gaming (called "gaming"), one for high ambient temperatures (called "Fix (Summer)") and so on. Sadly though whenever I try to load one of those alternative configurations FanControl crashes. What's strange is the fact that those alternative configurations can be loaded using the command line interface. For example fancontrol.exe -c gaming.json starts FanControl and successfully loads the gaming configuration. 

I run Windows 11 on an AMD AM4 platform (Ryzen 9 5950X). There are 64 GB RAM and the graphics card is a Nvidia Geforce RTX 2080Ti.

**Comment by Rem0o** [comment]
Any log.txt?

**Comment by altae7** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13717254/log.txt)

**Comment by Ngals** [comment]
think that I have the same issue
[error.txt](https://github.com/Rem0o/FanControl.Releases/files/13761643/error.txt)
send error on windows. the commande line works.
if  it can help

**Comment by XenHat** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13812741/log.txt)

**Comment by Rem0o** [comment]
Should be fixed in V177

**Comment by altae7** [comment]
Great, thanks for your efforts.
