### ISSUE TITLE
Multiple logs 

### ISSUE THREAD

**Issue by Jacksco007** [Rem0o/FanControl.Releases#2207]
Some times when I turn on the computer I get a warning that there are multiple logs. So I go to the folder and delete them but then after another couple of starts the warning and the other logs reappears. What could be the problem?

**Comment by Rem0o** [comment]
Well, what's in the logs? Share the files.

**Comment by Jacksco007** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13761573/log.txt)
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/13761575/log_1.txt)
[log_2.txt](https://github.com/Rem0o/FanControl.Releases/files/13761579/log_2.txt)

**Comment by Jacksco007** [comment]
[multiple logs.zip](https://github.com/Rem0o/FanControl.Releases/files/13761600/multiple.logs.zip)

**Comment by Rem0o** [comment]
All of the logs refer to "CommanderCoreDevice" from https://github.com/EvanMulawski/FanControl.CorsairLink
