### ISSUE TITLE
Fan Control doesn't start up after sleep

### ISSUE THREAD

**Issue by adejoshy** [Rem0o/FanControl.Releases#221]
If I leave my computer for awhile or I put it in sleep mode, when it opens back up, fan control won't restart so my fans are wrong again and I have to do a full restart of my computer. Even if I try to manually open the app after my pc has been in sleep it won't open.

**Comment by shivv3r** [comment]
Same issue here. Fan Control doesn't start with the system since version 74. I'm on 76 now and still the same issue.

**Comment by dabm-git** [comment]
I think it's a problem with your BIOS when coming out of sleep mode, I had the same problem with a Xeon for the x99 platform, changing the BIOS to a current one with the fix solved it.

**Comment by Rem0o** [comment]
Was a problem with the task in the task scheduler that started the program with Windows. V77 will override it for good and you should have no issue anymore with it.

**Comment by adejoshy** [comment]
Thank you.
