### ISSUE TITLE
Switching profiles using a script creates a log.txt on the desktop

### ISSUE THREAD

**Issue by Draken69CZ** [Rem0o/FanControl.Releases#2216]
Hello, I use a script in AHK to switch the profile in Fan Control to fast speed for 30 seconds and then back to normal fan mode. I use the commands

```
FanControl.exe -c Quick_Cooling.json
FanControl.exe -c Windows.json
```

Always at the time of switching profiles, a message is written to log.txt on the desktop

```
31/12/2023 0:09:42: System.NullReferenceException: object reference not set to object instance.
   In FanControl.App.OnExit(ExitEventArgs e)
31.12.2023 0:10:15: System.NullReferenceException: Object reference not set to an instance of an object.
   at FanControl.App.OnExit(ExitEventArgs e)
```
If I switch profiles directly in Fan Control the log is not written, the script that switches profiles is run as an administrator.

**Comment by Rem0o** [comment]
Could replicate the bug, will fix.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V177
