### ISSUE TITLE
fancontrol v176 cant find any fans on auto setup

### ISSUE THREAD

**Issue by JustAChickenBoi** [Rem0o/FanControl.Releases#2223]
**Describe the bug**
![image](https://github.com/Rem0o/FanControl.Releases/assets/103614321/f5a4576c-00ac-43ed-a717-6c19c60244f2)
nothing responded

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13815205/log.txt)

**Relevant hardware specs and setup**
it says laptops are not supported so should i close this bug report? although my specs are 
![image](https://github.com/Rem0o/FanControl.Releases/assets/103614321/55c4ea7e-64df-44cb-98a5-f29bda2c3deb)
![image](https://github.com/Rem0o/FanControl.Releases/assets/103614321/bdd5ebad-65c3-42e4-b2b2-ee383181fe67)
![image](https://github.com/Rem0o/FanControl.Releases/assets/103614321/dbf440b7-3fb7-42b6-bb05-185d37feec93)

**Comment by Rem0o** [comment]
laptops fans are not interfaced the same way desktops are, so indeed, laptops not supported.
