### ISSUE TITLE
Unexpected error occured

### ISSUE THREAD

**Issue by Nadragh2** [Rem0o/FanControl.Releases#2226]
**Describe the bug**
An unexpected error has occured. See log files for details. https://i.imgur.com/wffbFFY.jpeg
Also these errors occured https://i.imgur.com/j9VqmVj.jpeg

I havent used GTX960 since 2022 (have 6700XT now) and no idea how to fix this because i cant go to setting or anywhere.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/13829215/log_1.txt)

json here:
[userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/13833534/userConfig.json)

**Comment by Rem0o** [comment]
Fixed in V177
