### ISSUE TITLE
Start and Stop Threshhold not working for Nvidia Graphics Card with Nvidia 0 fan mode active

### ISSUE THREAD

**Issue by PhilippM7** [Rem0o/FanControl.Releases#2227]
The Fans start spinning at the Stop% Threshhold not at the Start% Threshhold, probably because there is a command send to the Card to not spin which makes the card spin or something.
the Card is a Nvidia Palit RTX 4070.
As the Fans start spinning at the Stop% threshhold, they almost immediately stop again as the Curve goes down 1%.

**Comment by PhilippM7** [comment]
It seems the Problem also occurs for one of my System Fans, so it does not seem to be related to Nvidia or the Zero Fan Mode.

**Comment by Starlynk1** [comment]
Just to let ya know, I was sure the Nvidia 0% setting was checked but went in again on my set up and it wasn't checked. Something caused it to uncheck itself. Also during an Assisted Setup, you can turn it on there but that settting doesn't retain either. Only option I found so far that seems to be working (without having done a restart yet) is manually setting it in the Sensor Settings (Edit Sources). Hope that helps.

**Comment by PhilippM7** [comment]
im sure its checked, but thats not the Problem actually. The 0% Fan Mode works fine. The Problem is with the Threshholds.

**Comment by Rem0o** [comment]
Can you should the control card of your GPU and what start/stop you set on there?

**Comment by PhilippM7** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/97338141/7063b65a-3661-4b65-87d5-a14ef22bdb0c)
You mean this? the Fans start at 35%.

**Comment by Rem0o** [comment]
This setup will kickstart the fan at 40, then may go down to 35. Any value below 35 stops the fan. This kickstart behaviour is maybe what cause confusion?

**Comment by PhilippM7** [comment]
No, its the Problem that the Fans dont start at 40% but at 35% what is a bug in my opinion. It should work like Card gets hot, gets cooled from 40% to 35% and then the Fans are idle until the Percentage goes up to 40% again no?

**Comment by Rem0o** [comment]
Well that depends mostly on the fan curve you set, the start and stop will only dictate the behaviour from and to 0 rpm.  Show the fan curve.

**Comment by PhilippM7** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/97338141/00e80359-9cf2-4b11-af79-6e1d42f3f275)
I am using this Auto Fan Curve.

**Comment by mjamil85** [comment]
Yeah, I have a same issue ([#2242](https://github.com/Rem0o/FanControl.Releases/issues/2242)) like yours & I really start getting annoying this issue. Endup set both Start and Stop at 50%.

**Comment by PhilippM7** [comment]
So is this an Issue? And if not, what are the Start% and the Stop% supposed to do?

**Comment by Rem0o** [comment]
@PhilippM7 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/8fadc9e8-312d-4a36-9fde-1595bf815745)

It tells the software the minimum % the fan requires to start/stop spinning. It's not an instruction or a command, it's a threshold.    Between Start and Stop % is not a "dead zone". I think this is what is causing confusion here.   Since the fan needs let say 40% to start but only stops at 35%, that means the fan CAN run between [35-40]. It will just need a kickstart to 40 before dropping back to let say 36, or 38.    So yes effectively the fan will "start" spinning from a command over the stop%, if that makes sense.

**Comment by PhilippM7** [comment]
Ok, then this is not an Issue. Solved it with a Trigger - Auto Curve combination
