### ISSUE TITLE
Support for LCD screens

### ISSUE THREAD

**Issue by JCKodel** [Rem0o/FanControl.Releases#2229]
Bought one of these: https://pt.aliexpress.com/item/1005006218541126.html

![image](https://github.com/Rem0o/FanControl.Releases/assets/379339/36ab8d49-9e9c-468a-a8f4-b41e8b37ef65)

Someone knows if there is a plugin for such devices?

**Comment by Fr0stX76** [comment]
Unless your LCD has a fan, why would FanControl support this? FanControl is not a monitoring interface.

Maybe Aida64 will work on it, but to be honest, this look like a cheap usb monitor that comes with its own proprietary software.

**Comment by Rem0o** [comment]
As @Fr0stX76  said.  

Closing.

**Comment by JCKodel** [comment]
> Unless your LCD has a fan, why would FanControl support this? FanControl is not a monitoring interface.
> 
> Maybe Aida64 will work on it, but to be honest, this look like a cheap usb monitor that comes with its own proprietary software.

Sorry. I didn't figured out I was talking to fucking retards.

It won't happen again.
