### ISSUE TITLE
Unexpected Error Occured

### ISSUE THREAD

**Issue by doinurmop** [Rem0o/FanControl.Releases#2230]
**Describe the bug**
Hi there, been using fancontrlo for a long time, first time ive had this issue. 
Whenever I try to launch it now it throws that error at me and freezers the program (rendering it unusuable)
I have zero idea how to read logs so i've no real clue what could be the issue. i've tried deleting the folder and redownloading the newest version of the program incase something got corrupted possibly, but it didn't change anything.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13847516/log.txt)

Thank you for any help.

**Comment by Rem0o** [comment]
Are you on V177?

**Comment by doinurmop** [comment]
> Are you on V177?

I was not ,it was a slightly older version.
Just tried it, it notified me that I need to update my  .net runtime (I'm surprised windows didn't do this for me lol)

Did that and it's working perfectly fine now. Thank you!
