### ISSUE TITLE
NVAPI_ERROR

### ISSUE THREAD

**Issue by Fr0stX76** [Rem0o/FanControl.Releases#2238]
Salut Rémi, premièrement bonne année!

Ok so I updated to 177 last night and this morning every reboot out of 4, I get this error in my log (and all Nvidia sensors go missing, of course).

NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR

Did you change anything in the NVAPI Wrapper initialization between 176 and 177? This is quite weird, I don`t think I have had a FanControl initialization issue for years... For the record, HWinfo can read NvAPI, so can my Gsync switch script that is based on it. I'm a bit confused as of why this is happening.
See my log

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/13853910/log.txt)

Also, note that I only have motherboard, Corsair plugin, HWinfo plugin and NvAPI enabled.

**Comment by Rem0o** [comment]
Haven't touched the NVApi wrapper stuff in more than a year.  Did you update Nvidia drivers?

**Comment by Fr0stX76** [comment]
Nope, same I've been using for the last months (537.58, the new ones have major issues with VSync and HAGS).

I did remove the 4096 resolutions of my monitor using CRU 2 days ago and also updated my chipset driver (AMD B650E) yesterday. But this behavior started this morning. Also I'm not sure I see the connection between overriding the EDID of my monitor or updating a chipset driver.

Anyway, not a big deal, I was only using NvAPI to get the temp of my GPU on the tray icon. I now have disabled NvAPI in FanControl and switched to getting it from HWinfo plugin.

**Comment by Fr0stX76** [comment]
Never mind, Hwinfo started doing something similar. I fixed it by redoing my MSI afterburner undervolt profile. No clue what happened here...
