### ISSUE TITLE
Not starting with Windows

### ISSUE THREAD

**Issue by bigaxe32** [Rem0o/FanControl.Releases#224]
Since (I think) V74 Fan Control has not started with Windows. However, manually opening the program doesn't work. I need to run the updater to get it to run. This is a pretty huge issue for me, as it still "takes control" of the fans, but doesn't update the fan speeds. I noticed when my GPU was at 85°

Thanks

**Comment by Rem0o** [comment]
I don't know what state you got your app in, but I would suggest a clean copy of V77 in its own folder. Copy your json configs (not the CACHE) into it and report back.

**Comment by bigaxe32** [comment]
Thank you, this fixed it. Really love this program!
