### ISSUE TITLE
Option for temperature results in Fahrenheit

### ISSUE THREAD

**Issue by JazzfanRS** [Rem0o/FanControl.Releases#2240]
Simply put I'm too old to learn a new temperature scale. Please consider allowing for temp scaling option.

**Comment by Tenome** [comment]
Surprised it took this long to suggest it (that I see anyway). +1

**Comment by JazzfanRS** [comment]
I did see it mentioned in [Discussions] (https://github.com/Rem0o/FanControl.Releases/discussions?discussions_q=fahrenheit) exactly 2 years ago today, and a year and a half ago. Misplaced suggestion? Just happy to find a fan control/temp monitor I can work with.

**Comment by JazzfanRS** [comment]
This the only reason I am still using SpeedFan 4.52 (2016 release). Degrees in Fahrenheit option.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V192
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/879f3dd8-2f91-42e9-8492-c19e87f758d1)
