### ISSUE TITLE
Start and Stop Function is broken. Version (177)

### ISSUE THREAD

**Issue by mjamil85** [Rem0o/FanControl.Releases#2242]
Latest Version (177) for Start & Stop seem broken or not working anymore.

For example, I set Start (50%) & Stop (45%). The fans should start to kick in once hit 50% & Stop below 45%. But, when reach 46% before hit 50%, the fan start kick in & stop again after below 45%. I attach the screen shot picture & video below. In the video you can see something weird happen it hit 50% come out from nowhere. Whatever I set at Stop, it should not trigger the fan as it should only trigger for Start only.

![image](https://github.com/Rem0o/FanControl.Releases/assets/155965177/39a3a842-33e1-4d74-b5af-a3e811cb4d3e)

https://github.com/Rem0o/FanControl.Releases/assets/155965177/c617c6bf-f5f9-4aa7-981a-07997b3ac0e5

**Comment by Rem0o** [comment]
I don't see anything anormal with the video.   Your fan curve hovers arround your stop %.  You changed the stop % a few times to go under the current curve value, before the curve would go back down under that value.  Everytime the fan is stopped and starts, it shoots to 50% before going back down to the value above the stop%.

Could you precise what exact sequence in the video doesn't make sense?

**Comment by mjamil85** [comment]
Example new video below. It should start at 50% instead it start 45%. Last 2nd or 3th previous version didn't have this kind of issue.

[

https://github.com/Rem0o/FanControl.Releases/assets/155965177/c6a2fc7a-4e62-484a-b73b-f897ec211772

](url)

**Comment by mjamil85** [comment]
Nevermind. It getting me annoying to solved this issue. I set both start & stop at 50%.

**Comment by Rem0o** [comment]
I read your statement again and trying to guess.  Do you expect a asymmetrical behaviour? Like from a stop the fan shouldn't start until the curve hits 50, and from a running state it then stops only at 45?  If that's what you meant, it never worked this way, it works as intended. The range between start and stop is meant to be usable from 0 rpm.  If you actually want that behaviour for your fan, you can use the trigger fan curve, which does exactly what I described here. You can use a mix then if you want to combine the trigger with a regular fan curve.

**Comment by Rem0o** [comment]
Works as expected.
