### ISSUE TITLE
Feature request: support disabling LibreHardwareMonitor entirely

### ISSUE THREAD

**Issue by koitsu** [Rem0o/FanControl.Releases#2245]
I've recently come across FanControl whilst looking for something to replace EVGA Precision X1.

My needs are incredibly simple: a program that can 1) set GPU fan speeds to a particular percentage (ex. 49%), and 2) set the fan speeds this way at log-on or system boot.  Precision X1 meets both these goals but since EVGA is done with GPUs I can't see this software working forever.  And sadly [nvfancontrol](https://github.com/foucault/nvfancontrol) doesn't meet these requirements.

Anyway, I tried FanControl and thought "OK, this might suffice, even though I do not care for a systray application I'll tolerate it as long as the CPU and memory utilisation are minimal".

After tinkering, I found that the only sensor I need for this functionality is NvApiWrapper.  Working great!

![ss02](https://github.com/Rem0o/FanControl.Releases/assets/8430773/210ae8a8-363b-4b70-b9b8-74978fac6a79)

...except for one problem: every time FanControl starts, it pops up the message: **LibreHardwareMonitor could not initialize or has no sensors.**  Well of course it has no sensors -- I intentionally have them all disabled.  NvApiWrapper is all I need.

![ss01](https://github.com/Rem0o/FanControl.Releases/assets/8430773/28dbbd58-a195-4f90-b2dd-3bcf2f69acda)

Is there a way to stop this message from happening -- or better yet, simply do not load/initialise LibreHardwareMonitor **at all** if all the sensors are disabled?

Footnote: this ticket **IS NOT** the same thing as #1850 or #1813 or #1327.

**Comment by Rem0o** [comment]
I think I never came across this exact use case, and indeed the error message is redundant and should not happen. Will fix this in the next version.

**Comment by Rem0o** [comment]
LHM will be disabled complexly in this case.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V178
