### ISSUE TITLE
Increasing CPU Handles

### ISSUE THREAD

**Issue by Icey400** [Rem0o/FanControl.Releases#2248]
I don't know if this is a bug or a feature, but I noticed while having Fan Control open, in Task Manager, my CPU handles increase 100 handles a second. I've narrowed it down to FC because when FC is not open, with all of my regular programs opened, the handles do not increase. It has even gone to +3 million handles. I was on Version 176, and when I updated to Version 177, the same issue occurs. I don't know if having this many handles is detrimental, but I would love an update as to if this is intentional or not.

**Comment by Rem0o** [comment]
I do not observe that behavior.  What do you got enabled in sensor settings?

**Comment by Icey400** [comment]
Under LibreHardwareMonitor, I have the Motherboard, CPU, GPU, and Embedded EC (ASUS) enabled. Under NvApiWrapper, I have it enabled (will override LHM).

**Comment by Rem0o** [comment]
My guess is that it is bound the the Embedded EC implementation somehow.  If you keep that off, does it stops?

**Comment by Icey400** [comment]
I disabled the Embedded EC sensor and the issue still persists. Right now only the Motherboard, CPU, and GPU sensors are enabled.

**Comment by Rem0o** [comment]
Well, by process of elimination, can you pinpoint which of the sensor source causes the issue?

**Comment by Icey400** [comment]
I didn't realize the sensors could be the main culprit. The culprit was the GPU sensor. As soon as I unchecked it, the handles stopped increasing. Thanks for the help.

**Comment by Rem0o** [comment]
The GPU implementation is LHM is not the most optimized.   If you got an Nvidia GPU, I would recommend using the NvAPIWrapper one.
