### ISSUE TITLE
[request] ability to set a default speed in case sensor become unavailable or GPU Memory Junction sensor access

### ISSUE THREAD

**Issue by taktakmeian** [Rem0o/FanControl.Releases#225]
I am using the hwinfo plugin with great success but unfortunately the Shared Memory support is now limited to 12 hours runtime on the free version.
It would be great to be able to set a default fan speed that would be taken into account when the sensor driving the curve becomes unavailable so I can rest easy until I can turn shared memory support back on when it turns off.

alternatively, a workaround would be to be able to access GPU memory junction temps directly within  Fan Control

thank you very much for the great app !

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.HWInfo/issues/1
