### ISSUE TITLE
Nvidia Instant Replay / Shadowplay incompatible with GPU fan control.

### ISSUE THREAD

**Issue by ManLikeeUmar** [Rem0o/FanControl.Releases#2257]
I have a PNY XLR8 4090 and I'm trying to use the start-stop feature for 30°C and below. This doesn't seem to work when using Instant Replay. Any fixes/solutions? Or maybe it needs to be patched in an upcoming update.

![Screenshot 2024-01-19 021408](https://github.com/Rem0o/FanControl.Releases/assets/157082847/44b04edf-bf03-4f44-8714-90f17926202e)
![Screenshot 2024-01-19 021250](https://github.com/Rem0o/FanControl.Releases/assets/157082847/744fdaa6-0854-4211-8bfb-31794b667c26)

It gives me the error "This control is being overridden by an external source." Only fix is to stop Instant Replay or stop the task "NVIDIA Share" in task manager.
![Screenshot 2024-01-19 021759](https://github.com/Rem0o/FanControl.Releases/assets/157082847/41fc91d9-9c4d-4d03-92eb-d2f8dda23174)

Thanks for the help.

**Comment by ManLikeeUmar** [comment]
Damn no reply...oh well

**Comment by Rem0o** [comment]
FanControl can't force your card to go 0 RPM, the API just doesn't allow it. The card has a mind of its own to decide if it can go 0 RPM.  Most likely the screen recording uses the card in a way that doesn't satisfy the conditions to go 0 RPM.
