### ISSUE TITLE
Fan Control slowly losing its functionality with each update.

### ISSUE THREAD

**Issue by Akiisqt** [Rem0o/FanControl.Releases#2259]
**Describe the bug**
The app used to show my 2 Controllers and GPU, each time I've updated the app I've lost another one of them. First the GPU, then my Pump Controller now my fan controller.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Last file is from last year.

**Relevant hardware specs and setup**
[PC part picker list](https://pcpartpicker.com/b/X3Xbt6)
Pump is connected to PUMP connector on the motherboard
Otherwise, I'm using two Lian Li Controllers that are chained together into the CPU connector

**Comment by Rem0o** [comment]
I'm a bit confused.  What do you mean by lost?  Are the cards simply not there anymore? Or are they not responding?

If you go back to whatever version that worked before, does it still work?

**Comment by Akiisqt** [comment]
They disappear, removing fan control completely and reinstalling fixed the issue

**Comment by Akiisqt** [comment]
The issue might be missing files that don't get added with each update, I noticed many missing folders and files from my “updated” version using the auto updater, when I manually updated all issues were fixed.
