### ISSUE TITLE
Fan keep dropping RPM when in manual 100% mode.

### ISSUE THREAD

**Issue by e-max** [Rem0o/FanControl.Releases#2264]
Hi guys!

I have a Deepcool LS520 attached to a Gigabyte Z790 motherboard. It recognized the pump and seemed to work fine. I chose "Manual control" and set the fan speed to 100%, which makes the pump run at 3100 RPM, exactly what I want. However, for some reason, sometimes the RPM on the pump drops to 2500 RPM, making the pump really noisy. I can temporarily fix it by manually setting the fan speed to 0, waiting for it to switch off, and then setting it to 100% again, which returns it to 3100 RPM. 

Could you please say if there is a way I can debug this behavior?

![pump_3100](https://github.com/Rem0o/FanControl.Releases/assets/242936/84ed89fa-51e6-4e18-adac-8e9fa20cfd05)
![pump2000](https://github.com/Rem0o/FanControl.Releases/assets/242936/29f1c193-45ae-49c5-ae13-244eb6a839c3)

**Comment by e-max** [comment]
It's plugged into "CPU_OPT (CPU Fan/Water Cooling Pump Header)" - 4 pins.

**Comment by Rem0o** [comment]
I'm affraid from Fancontrol's perspective there's is nothing more to it.   Keep in mind when Fancontrol send's a command to the fan controller, it is merely a suggestion, not an "absolute order" if that makes sense. The 100% on the card is not the command sent, but the command read back from the controller, so the controller is telling fancontrol it is running 100%. Now why the RPM drops, must be something specific to that header on your motherboard the way it is configured maybe from the BIOS, or just some built-in behavior.

**Comment by e-max** [comment]
Got it.  I'll try to plug the pump into another header and see if it'll help.

Thanks a lot for the response!
