### ISSUE TITLE
Every time i restart my computer, i have to set every temperature sources again which pointed to GPU hotspot (7900 XTX)

### ISSUE THREAD

**Issue by GreenGandalf** [Rem0o/FanControl.Releases#2269]
Every time i restart my computer, i have to set every temperature sources again which pointed to GPU hotspot (7900 XTX).

No log file created about this.

I have a full AMD configuration and am using a 7900 XTX GPU. Setting a high delay for starting up the program after restarts didnt help either.

**Comment by Rem0o** [comment]
Are you using any plugin to get that sensor?

**Comment by Physics-Dude** [comment]
I have a similar issue but with the 7800XT as my main GPU with a false missing sensor identifier error that appears with every reboot. With every reboot, I get the following error:

![image](https://github.com/Rem0o/FanControl.Releases/assets/22563517/02417406-d5b8-400f-a4fb-23a6f1475758)

Then I have to manually select the AMD GPU's Hot Spot in this one curve and save my config.

![image](https://github.com/Rem0o/FanControl.Releases/assets/22563517/d18e0f86-d2fe-4b49-b835-6f84f1b8662f)

Using Version 179 (NET 4.8), but the issue has been present before the last couple updates at least.

Also using AMD driver version 23.12.1. Will update it to 24.1.1 to see if the issue remains.

**Comment by Physics-Dude** [comment]
AMD software update seems to have fixed it for now.

**Comment by GreenGandalf** [comment]
It does seem like the new update fixed this for me too! :)

**Comment by GreenGandalf** [comment]
Donated 5$ just for good measures ;)

**Comment by Rem0o** [comment]
I did nothing for this specific issue, you could have kept your dollars, but thank you :)

**Comment by GreenGandalf** [comment]
i know that, but the issue got fixed and i love using your program :)

**Comment by Miska1995** [comment]
Oh, the cause for my problem is the fact that I never extracted the file from WinRAR. I did that and now it works fine - and my saved configurations do not reset on restart.
