### ISSUE TITLE
AMD and installing plugins

### ISSUE THREAD

**Issue by BiteMyAssets** [Rem0o/FanControl.Releases#2270]
Hi folks,

apologies if this is in the incorrect place, I am new top github and am struggling getting this working with my system.

When I launch the program it only detects 3 fans, although I have 6 case fans, 2 cooler fans and my gpu has 3 fans in it (currently not detecting any of my GPU fans at all)

Tried to install the plugin for AMD and got lost as I also didnt know what "compile the solution" means.

Any help would be most appreciated! 

My Device specifications below:

Processor	AMD Ryzen 9 7900X 12-Core Processor               4.70 GHz
Installed RAM	32.0 GB (31.1 GB usable)
System type	64-bit operating system, x64-based processor
GPU                 AMD dadeon RX 7900 XTX

Edition	Windows 10 Pro

**Comment by Rem0o** [comment]
Hi,

First question to ask:

Where are said fans plugged, and how. Give full detail if adapters, splitters or whatever are used.

Then, RX 7900 XTX fans are not supported currently by the software. Alternative is using AMD Adrenaline.

**Comment by BiteMyAssets** [comment]
Fans are plugged in via 3 cables into the motherboard:

Cable 1 has the 3 intake fans on front on a single splitter
Cable 2 has the 3 exhaust fans on back on a single splitter
Cable 3 has the 2 cooler fans attached to CPU on a single splitter

**Comment by Rem0o** [comment]
3 cables will give you 3 controls/channels, that's normal.  Fans on the same splitter will be controlled together.

**Comment by BiteMyAssets** [comment]
Ah, okay. So I should control the 3 sets of fans with Fan control and the control the GPU fan curve with adrenalin?

Any idea if there is a plan to support the 7900xtx fans in the future?

Thank you sir 🙏🏼
________________________________

**Comment by Rem0o** [comment]
For AMD GPU: https://github.com/Rem0o/FanControl.ADLX
