### ISSUE TITLE
MultitActivation of the fan speed curve by few different temperature sensors

### ISSUE THREAD

**Issue by RTuros** [Rem0o/FanControl.Releases#2273]
Is it possible to make the set fan speed curve switch on by measuring from two sensors? 
For example:
The speed of the fans on the chassis turns on according to the GRAPH curve due to high CPU temperature. (CPU sensor Tctl/Tdie)
In games, it is often the GPU that is used more heavily, and I need to change the sensor (to GPU sensor) according to which the GRAPH curve for fan speed should be activated before starting games.
Is it possible to set the curve according to two sensors? (Depending on which sensor reaches the set temperature earlier)

**Comment by Fr0stX76** [comment]
@RTuros If the graph you want to use is the same for both sensors, create a mix custom sensor with max option and add the 2 sensors required. Then add the mix custom sensor to your curve graph and use that curve on your fan.

If the sensors need to have their unique graphs, create 2 graphs, one for each sensor, then create a mix fan curve with max option and add both graphs to it. Finally add the mix fan curve to your fan.

One last tip, If the temps bounces a lot on one of your sensor, create a time average sensor and use a period of a couple seconds (ex I use 5 sec. on my CPU to remove the spikes). Then use that time average as your graph sensor.
