### ISSUE TITLE
Fans stopped and high-pitched pure tone

### ISSUE THREAD

**Issue by crawfishie** [Rem0o/FanControl.Releases#2274]
**Describe the bug**

I leave my Windows 11 computer on 24/7 and lock it when I'm away or going to bed. I do not use sleep mode. I've been using FanControl since April 2022, and every few months, I've returned to my computer room after several hours away and heard a loud, high-pitched pure tone, and it's coming from the PC. I open FanControl, and the rear case fan is reporting crazy RPM, and the front fans report 0 RPM. The rear fan is actually stopped despite the impossible RPM reported. The CPU fan thankfully is still working, and no harm has come. I built this system in July 2021 and never had this problem using the BIOS fan control, so that's what, 8 months problem-free with the BIOS. Rebooting clears the problem. There are no entries in the FanControl log in the last three days, nor are there any entries in Windows logs relevant to the problem. I have no idea how to reproduce this rare, seemingly random problem, but I am curious if anyone has seen this before. This has got to be the third or fourth time I've observed it in 21 months or so of using FanControl.

**Is there a log.txt file next to FanControl.exe with recent date entries?**

No log entries in the last 3 days.

**Relevant hardware specs and setup**

Asus TUF Gaming B550-Pro, AMD 5800X, Scythe Fuma 2, 32 GB RAM, Asus TUF RTX 3060ti, be quiet! Silent Wings 3 PWM 140mm BL070 rear fan, be quiet! Silent Wings 3 PWM 120mm front fan BL071 x 2

![Screenshot 2024-01-28 143039](https://github.com/Rem0o/FanControl.Releases/assets/101072550/9affe87b-2085-4fb8-96a5-d61f7776d1d7)

**Comment by Rem0o** [comment]
My guess is that you are running your fans at the edge/lower limit of their RPM range right? Like sub 600-700 rpm?  As your fans get dusty, they might need a tad more power to run, and you enter the area where you have barely not enough power to make it spin, and you'll get this result. The tach will report crazy values, and you might get a coil whine/pitch.  That's not good.   You want to have a bit of headroom above the minimum % your fans run to avoid such issues.

Did you use the assisted setup to get your start/stop% or you adjusted them manually?

**Comment by crawfishie** [comment]
It's like 450 RPM for the front fans and 700 for the rear fan. This is not a startup problem, as every time it's happened, the computer was on and typically had been on for many days. It's rare for me to power it off, and like I said, I don't use sleep mode. I was using the same speeds in the 8 months before FanControl, and I just carried them over. If you think those speeds are low, you'd freak at the speeds I use on my Windows 10 Z87 i5 4670 system. Its CPU fan idles at 200 RPM! I've been doing that for the entire 10+ year life of that system, which is also always on, and it's never given me any trouble, including with FanControl. So, I'm going to conclude this is some idiosyncratic problem with my B550 system, and since I don't have a repro case, I'm going back to BIOS control and see if it recurs in the next several months. Maybe the fans have developed a problem.

**Comment by Rem0o** [comment]
Fans are mechanical devices, and will wear and tear, and may change a bit over time. 
Dust buildup will also change how much power is required for a given RPM. Running them as the limit of their lowest running state will highlight such small change.
