### ISSUE TITLE
V78 doesn't start up

### ISSUE THREAD

**Issue by blacky22983** [Rem0o/FanControl.Releases#228]
I'm using Windows 10 Insider 21376, but with the current version V78, FanControl doesn't start any more.
When I try to open it in the Explorer, even the explorer hangs and doesn't react any more. I have to restart or kill the explorer.exe task by taskmanager.

Reboot of Windows didn't help.
V77 was working fine.

**Comment by Rem0o** [comment]
If you download  https://github.com/Rem0o/FanControl.Releases/releases/tag/V77 again, does it starts properly?

**Comment by blacky22983** [comment]
ah :)
It's not only the source-code in the zipfile...

Yes this version runs fine.

**Comment by Rem0o** [comment]
any log.txt with V78?

**Comment by blacky22983** [comment]
Found out it is an issue with the lastest insider version (21376).
With version 21370 the V78 works fine.

This is all I found in the logfile
_07.05.2021 10:51:09: Unhandled exception in FanControl v1.0.0.0
07.05.2021 10:51:10: System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FanControl.Domain.UpdaterService.<UpdateVersion>d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FanControl.Domain.UpdaterService.<<CheckForUpdate>b__7_0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei FanControl.Domain.DialogService.<>c__DisplayClass7_0.<<ProgressDialog>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
07.05.2021 10:51:10: System.Net.WebException: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)_

**Comment by Rem0o** [comment]
If it's only with an insider version of Windows, will close.
