### ISSUE TITLE
Gigabyte GA-Z97X-UD3H can only control 4 of 6 fans

### ISSUE THREAD

**Issue by fartwhif** [Rem0o/FanControl.Releases#2284]
Tried a few things and could not get your otherwise outstanding software to establish control for 2 of my 6 fans.

I have 
```
GTX 1070  ,  sense OK, control OK
Fan 1, "CPU" sense OK, control OK
Fan 2, "CPU OPT" not used, sense i assume OK, control i assume OK
Fan 3, sense OK, control OK
Fan 4, sense OK, control BAD (control widget does not appear even when showing hidden)
Fan 5, sense OK, control BAD (control widget does not appear even when showing hidden)
```

I was able to tap into a DLL in my `C:\Program Files (x86)\Gigabyte\EasyTune` directory.  Running EasyTune does NOT provide fan suite as displayed in the vast number of screenshots online, and I don't know why.

So I fired up Visual Studio, new .NET console project and referenced the DLL
```
    <Reference Include="Gigabyte.EnvironemntControl">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Gigabyte\EasyTune\Gigabyte.EnvironemntControl.dll</HintPath>
    </Reference>
```
instantiate the `FanControl` class, and it gives sense and control for 5 motherboard header fans, including 4 and 5.  Make sure that the registry key `HKLM\SOFTWARE\GIGABYTE\ThermalConsole\SIO` exists beforehand or there will be an NRE.  Discovered your project.  Tried it.  I then noticed that you gave it the concept of plugins, but I also noticed they only work for sense, at least that's what the readme seems to suggest.  Correct me if I'm wrong.  Are plugins something just anyone can create and use?  Is there a knowledge base, wiki, or other type of documentation and/or SDK for plugins? I know that redistribution of GIGABYTE IP is almost certainly off the table, but maybe detect if the DLL exists somewhere and present the option for using it?  I don't know, just an idea.

It appears there has been much frustration over the years expressed online about the way Gigabyte has "done weird" with their boards.  Please let me know, thanks.

```
            FanControl fc = new FanControl();
            Console.WriteLine($"FanCount: {fc.FanCount}");
            Console.WriteLine($"FanControlCount: {fc.FanControlCount}");

            string fcDisplayName = string.Empty;
            string displayName = string.Empty;
            for (int i = 0; i < fc.FanCount; i++)
            {
                fc.GetFanControlDisplayName(i, out fcDisplayName);
                fc.GetFanDisplayName(i, out displayName);
                Console.WriteLine($"Fan {i}: {displayName}, {fcDisplayName}");
            }


            //0%
            //fc.SetFanSpeedFixedMode(0, 0x0);
            //fc.SetFanSpeedFixedMode(1, 0x0);
            //fc.SetFanSpeedFixedMode(2, 0x0);
            //fc.SetFanSpeedFixedMode(3, 0x0);
            //fc.SetFanSpeedFixedMode(4, 0x0);

            //100%
            fc.SetFanSpeedFixedMode(0, 0xff);
            fc.SetFanSpeedFixedMode(1, 0xff);
            fc.SetFanSpeedFixedMode(2, 0xff);
            fc.SetFanSpeedFixedMode(3, 0xff);
            fc.SetFanSpeedFixedMode(4, 0xff);

            int top = Console.CursorTop+1;
            float fanSpeed = 0;
            while (true)
            {

                for (int i = 0; i < fc.FanCount; i++)
                {
                    Console.SetCursorPosition(0, top + i);
                    Console.WriteLine();
                    Console.SetCursorPosition(0, top + i);

                    fc.GetFanControlDisplayName(i, out fcDisplayName);
                    fc.GetFanDisplayName(i, out displayName);
                    fc.GetFanSpeed(i, out fanSpeed);
                
                    Console.WriteLine($"Fan {i}: {displayName}, {fcDisplayName}, Speed: {fanSpeed:F2}");
                }
                Thread.Sleep(100);
            }
```
output:
```
FanCount: 5
FanControlCount: 5
Fan 0: CPU Fan, CPU Fan
Fan 1: CPU OPT, CPU OPT
Fan 2: System Fan 1, System Fan 1
Fan 3: System Fan 2, System Fan 2
Fan 4: System Fan 3, System Fan 3

Fan 0: CPU Fan, CPU Fan, Speed: 1088.71
Fan 1: CPU OPT, CPU OPT, Speed: 0.00
Fan 2: System Fan 1, System Fan 1, Speed: 747.51
Fan 3: System Fan 2, System Fan 2, Speed: 501.11
Fan 4: System Fan 3, System Fan 3, Speed: 603.22
```

**Comment by Rem0o** [comment]
Hi,

Board support is done via https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.
If you board has 2 control chips like other gig boards, you have to enable InpOut 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/ed4ee564-e403-4e76-9cd3-41df18db768f)

You can also contribute to the project to improve your board support in there, which FanControl will inherit directly.

Now as for your DLL/Plugin idea, plugins do allow to add control sensors, not just sense.
Made a basic wiki : https://github.com/Rem0o/FanControl.Releases/wiki/Plugins#iplugincontrolsensor-inherits-ipluginsensor

Otherwise, you can take a look at the different plugins made by the community to give you an idea:
https://github.com/Rem0o/FanControl.Releases#plugins

You could create a plugin which detects the DLL on the PC, then interface it like you did with your little test program.

**Comment by fartwhif** [comment]
I noticed InpOut and enabled it, reran the assisted wizard, actually i went back again and checked everything for a third pass with no joy.  TYVM for the documentation, do plugins allow you to offer your system control of fans?

**Comment by Rem0o** [comment]
@fartwhif  Technically nothing stops you from doing that.   FanControl has temp inputs and control outputs, with plugin you could set up your home.

**Comment by fartwhif** [comment]
Sorry, I'm a major edit fiend and just as I finished you had already replied!  Nice., thanks for your time.

**Comment by fartwhif** [comment]
It's been going strong, no issues yet!  Thanks to Gigabyte for the libraries, even though it's not exactly kosher to use them like this I hope they don't mind!   If anyone is interested, the alternative gigabyte plugin is over at https://gitlab.com/fartwhif/fancontrol.altgigaplugin/-/tree/main/FanControl.AltGigaPlugin/bin/Release?ref_type=heads
