### ISSUE TITLE
Settings lost when the computer is shut off unexpectedly

### ISSUE THREAD

**Issue by paridkushta** [Rem0o/FanControl.Releases#2285]
Tested in many computers. To recreate, just hard shut down your computer, or turn the electricity off.

We regularly have power outages and when the computers shut off suddenly, FanControl shows the first welcome messages and tutorial.

I have set things up for my family so that they never see FanControl, otherwise they'll mess with the settings.

But when this happens the app doesn't start minimized and all the messages require the user to brainlessly press Yes on every interaction and ruin everything.

Thank you for your work!

**Comment by Fr0stX76** [comment]
Not that it will solve anything, but as an electrical engineer, the power outage part triggered me. Power outage are the worst for electronic in general, they induce a major stress on components. This is especially true for PCs as on top of the electrical issues it might induce, you have software corruption (firmware or OS). My advice would be for you to invest in a good UPS with USB or serial communication that will do a clean shutdown and protect from power surges.

**Comment by paridkushta** [comment]
Oh i agree, i do use UPSs on everything i personally own. Though i can't make other people buy UPSs unfortunately.

If you take it for granted that no damage happens when power suddenly cuts off, the issue with the app itself is that this shouldn't happen.

And it's even more interesting that it doesn't lose fan configurations and curves, only the basic settings that should not be dynamic in the first place.

So we shouldn't focus on the UPS part rather than the fact that the program should write its settings somewhere clearly, and only overwrite if saved.

If the program has already saved a configuration, it shouldn't lose it if power gets cut off. I don't think that's unreasonable, right?

**Comment by Rem0o** [comment]
The program saves its working state in the CACHE file.  More specifically, there is a "FirstLaunch" property, which triggers the welcome dialogs.  This state is saved when the app closes and when the window is minimized to the tray.

Now if for some reason this file gets corrupted, the app won't be able to read it back, and will default to the first launch state.  I can add a cache save just after running the welcome screen, but that won't fix the corrupt file part, if that is indeed the issue.

**Comment by paridkushta** [comment]
Please forgive my ignorance in advance, but can't the configuration settings just be all saved on the default .json file?

Or to better ask, why is the .json file there if it can't be read after a power loss?

How does the CACHE file work if i only run the app, make no changes, close the app? (Similarly to just turn on, run FanControl, shutdown).

You have every right to tell me off of course, but as a beginner developer, it may be really useful info.

I appreciate your help!

**Comment by Rem0o** [comment]
The CACHE file saves general settings, not specific to a fan configuration. The json config files are for actual fan settings.  It saves the last config loaded, the window position and so on. 

> Or to better ask, why is the .json file there if it can't be read after a power loss?

It can be read, IF the power loss didn't corrupt it.  Power loss is not "normal operating behavior". Power loss can/will mess up stuff, as the computer won't have time to finish operations.

**Comment by paridkushta** [comment]
Why does the CACHE file have to be live? Can't those settings (minimzed run, update notification disable, sensors, colors) be decoupled into another general file, that is only overwritten when i press "Save"?

**Comment by Rem0o** [comment]
The CACHE file isn't "live".  It just gets saved at different times than your fan configuration. 

>  Can't those settings (minimzed run, update notification disable, sensors, colors) be decoupled into another general file

It is exactly that, that general file is the CACHE file.   It also gets saved when you hit save.

**Comment by paridkushta** [comment]
Sorry again if i seem annoying, it's not my intention to sound like a toddler, but why can't it work just like the user .json file, and not get corrupted?

How can we make that file start acting normally, like the rest of the system?

Because files are not being physically corrupted, as in filesystem corrupted.

So if it's not actually physically damaged, it means something about that file is "live" while the app is running, that cannot be saved in time.

And even more fascinating it's that when force-closed through task manager, this issue doesn't occur.

I remember one of your update logs mentioned fixes about abrupt stops of the app, including shutdown logic.

**Comment by Rem0o** [comment]
The file corrupt part was a theory, never said it was actually happening.  Your issue is an isolated issue, it doesn't happen to the general public., or I would be overwhelmed with emails about this, which I'm not.  

>  it means something about that file is "live" while the app is running
It's not. There is no file handle hanging or anything like that.  

> How can we make that file start acting normally, like the rest of the system?
It is acting normally. There is nothing fancy about it, I treat it just as the other config files, it just get saved at different times/events, that's it. 

We can theorize all we want,  one thing for sure is that if we see the welcome dialog, then either the file is not present or the first launch property is set to true.  What would help us is to see the state of the CACHE file when the problem happen.

**Comment by paridkushta** [comment]
I have three separate devices on hand that use FanControl.

An MSI laptop, a Lenovo mini-PC, and a fully built computer on an ASUS motherboard.

The laptop and mini-PC are integrated-graphics only, office use.

Is there anything i can do to help you out in tracking this issue? (Other than send you videos of me pulling the plug or force shutting down).

I also can reproduce this on 100% of other computers i've tested, but those three devices i have on hand personally to do anything at any time.

I actually found the issue on other computers, since mine are on UPSes.

**Comment by Rem0o** [comment]
> Is there anything i can do to help you out in tracking this issue? 

Send the state of the CACHE file here when the problem occurs, aka when you got the welcome screen on.

**Comment by paridkushta** [comment]
Ok so i will disable auto startup, force-shutdown, turn the computer on, and send you the cache file without the program running and overwriting it.

Is that ok?

**Comment by Rem0o** [comment]
Closed? Conclusion?

**Comment by paridkushta** [comment]
I updated to V180, and tried 6 times to simulate a power outage by unplugging and draining my UPS, and the issue didn't come back.

This issue had been going on since V173 but i hadn't had the time to figure out what triggered it (in order to report it as a bug).

If it does happen again, i will see if i can replicate it on whatever computer i see it, and after rebooting the computer, before running FanControl, i will pull the CACHE file for you.

Until then i closed the issue so that it won't bother you. Tell me anytime if you need any other experiments from my side.

PS: If it's not clear yet again, I value your work very highly. Never intend to be a pain in the ass for you, only want to help make this program bullet-proof.
