### ISSUE TITLE
Automatic tray icon color change fails when an automatic OS theme switch happens during Sleep

### ISSUE THREAD

**Issue by DarkwaterV3** [Rem0o/FanControl.Releases#2286]
**Describe the bug**
When the PC wakes from Sleep, and [Windows-Auto-Dark-Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) switches to dark/light theme because the sun rose or set during Sleep, FanControl does not pick up on this and leaves me with a white tray icon in light mode or a black tray icon in dark mode. I am required to go to 'Tray Icons', uncheck and recheck 'Sync icon color with Windows', and save my config, to again get the appropriate tray icon color. I have to do this once or twice daily to keep the tray icon correct.

This is the only app on my PC that is tripped up by a sundown during Sleep that triggers a theme change on wake. The two other apps on my system that adapt their tray icon to the OS theme, [Eartrumpet](https://github.com/File-New-Project/EarTrumpet) and Dropbox, do not suffer from this issue.

Manual OS theme switches, however, **do** result in FanControl switching to the appropriate tray icon color. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
I looked in my log but could not find any relevant entries.

**Relevant hardware specs and setup**
I believe this is not relevant. I'm on Windows 10.

Thank you.

**Comment by Rem0o** [comment]
Hi,

Took a look at the program, and in my case the theme can't switch "during" sleep, so I'm not sure exactly how that works in your case.   FanControl is subscribed to a Windows event when the colors/theme changed.  If somehow that event is missed, sync won't work.   What I can do is subscribe to wake from sleep event, and check for theme sync when the computer wakes back up.

**Comment by DarkwaterV3** [comment]
Sorry, I wasn't clear on how it switches during sleep. What I meant to say was that the scheduled moment for a switch occurs during sleep and the theme is immediately switched upon wake.

Thank you for the update. I'll keep an eye on the issue and report on if the problem persists.

**Comment by Rem0o** [comment]
Which icon exactly are you referring to? The app icon or the tray icon?

**Comment by DarkwaterV3** [comment]
Tray.
