### ISSUE TITLE
FanControl still showing on disconnected monitor in prior multi monitor setup

### ISSUE THREAD

**Issue by pseudobacon** [Rem0o/FanControl.Releases#2288]
I have been running FanControl on a second monitor for a while but then I sold that monitor and now only have one. For some reason, FanControl still thinks it should be displayed on that second, non existent monitor (I know because the animation flies out to that side of my desk off the single monitor where the second monitor physically used to be).

**Comment by Rem0o** [comment]
Whenever you'll close the window again in a "good" location, the app will remember that as its new default location.

**Comment by Rem0o** [comment]
Use the (Windows Key + arrow keys) while the window is selected to move it around.   Otherwise close the app, open the CACHE file and edit the "Top" and "Left" properties to 0, save, and open back up.

**Comment by pseudobacon** [comment]
Ok I think the cache file edit fixed it thanks
