### ISSUE TITLE
32-bit plugins?

### ISSUE THREAD

**Issue by fartwhif** [Rem0o/FanControl.Releases#2289]
Hello,

I'm writing a plugin that is using proprietary 32-bit libraries.  I would like to keep the plugin as tightly bound to them as possible without resorting to any IPC or COM wrappers to traverse issues like this.  I forced FanControl.exe to run in 32-bit mode and my plugin works, but NvApiWrapper and/or Nvidia curve overide stop working. (I'm guessing it is or they are 64-bit-only).  Does or will FanControl support 32 bit plugins?

when built for `AnyCPU` platform:

```
2/2/2024 9:59:41 PM: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at GigaFan.MyDecompiledEnvironmentControl.MyNativeCpuApi.GBFunc2(Int32 Var1, Int32 Var2, StringBuilder Param1, StringBuilder Param2)
   at GigaFan.MyDecompiledEnvironmentControl.MyGenericCPU..ctor()
   at GigaFan.MyDecompiledEnvironmentControl.MyFanControl.InitObjects(String productName)
   at FanControl.AltGigaPlugin.AltGigaPlugin.Initialize()
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
```

when built for `x86 platform` (32-bit):
```
2/2/2024 10:07:32 PM: System.BadImageFormatException: Could not load file or assembly
'file:///C:\Users\user\Downloads\FanControl\Plugins\FanControl.AltGigaPlugin.dll' or one of its dependencies. 
An attempt was made to load a program with an incorrect format.
```

**Comment by Rem0o** [comment]
I'm not too sure how that's supposed to work.  FanControl is compiled for "AnyCPU" and doesn't have any predefined "bitness" embedded into it.  To use a native 32bit, I would guess FanControl needs to be compiled explicitly in x86 mode?

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/0aca0be6-5874-4c1f-aa57-c244353cc1a0)

NvAPIWrapper doesn't support 32bit apps on X64 operating system.

**Comment by fartwhif** [comment]
Thanks, relieved I can still get Nvidia GPU via LHM while in 32 bit mode.  Good stuff.  

Some plugins require 64 bit and some 32 bit. I don't know of an easy way to make a system like you have here work with either.  When it's AnyCPU and "prefer 32 bit" isn't enabled then it runs in 64 bit.  AnyCPU just means it CAN be run in 32 bit but won't try to unless the prefer 32 flag is enabled, or you're running a 32 bit copy of windows, or the program that started it is already running in 32 bit (like if explorer.exe were running in 32 bit).  (these flags can be changed within the exe without recompiling, using a Microsoft utility)  I put a copy-paste tutorial in my [plugin's readme](https://gitlab.com/fartwhif/fancontrol.altgigaplugin)

**Comment by Rem0o** [comment]
Glad it works out for your plugin! If you don't need anything else specific from me, please close this issue.

**Comment by fartwhif** [comment]
i should add that my plugin isn't 32 bit, but a native DLL it relies on is, so whenever it tries to use pinvoke that DLL BadImageFormatException is thrown
