### ISSUE TITLE
[Request] Quick actions

### ISSUE THREAD

**Issue by nikkopt** [Rem0o/FanControl.Releases#229]
I have my fan curves configured on the bios and i have been looking for a program that let's me briefly control them on windows. Just came across this and it's amazing.
There are times when i want to fully stop my fans for a while or to run them at full speed (to quickly remove the hot air inside the case for example). This program let's me do it but i have to manually toggle every fan i want to control and apply the specific flat curve (0% or 100%) depending on what i want.
It would be great if the program had something like quick actions. Where you could "program" certain fans to do certain "things" just by toggling a switch (or pressing a button). For example, a switch to run fan 1 and 2 full speed for 2 minutes and then turning it off (letting the bios take over again).
They could be programmed to do a whole bunch of things, not just my specific examples.
Does it sound like a good idea?

**Comment by Rem0o** [comment]
Just save different profiles for your needs, and quick switch by right clicking the tray icon => configurations.

**Comment by nikkopt** [comment]
You are right, didn't think of that. For what i need it is indeed enough
