### ISSUE TITLE
Tray icon positions change at random

### ISSUE THREAD

**Issue by Combo86** [Rem0o/FanControl.Releases#2290]
**Describe the bug**
When using multiple tray icons, their positions/order will randomly switch every time the application starts.

**Relevant hardware specs and setup**
W11, FC version 180

**Comment by Rem0o** [comment]
Tray icon position is not controlled by the application, but by Windows.

**Comment by Combo86** [comment]
It does seem to respect the order set in FC initially (see screenshots), it's just after a restart the order is changed.. Unfortunately Windows doesn't allow any adjustment in the order either :(

![FC1](https://github.com/Rem0o/FanControl.Releases/assets/130478710/04e700ba-01ad-46db-9cee-1a8a45934422)
![FC2](https://github.com/Rem0o/FanControl.Releases/assets/130478710/4ede996c-4ae4-4311-bdfd-c3a41c8a5b67)

Anyway, thx for the quick response!

**Comment by Rem0o** [comment]
Windows does allow to reorder. Just drag the icons in the tray in the order you want.

**Comment by Combo86** [comment]
Lol, thx, feeling pretty stupid now ;)

**Comment by Combo86** [comment]
Solved
