### ISSUE TITLE
Will not lock PWM %

### ISSUE THREAD

**Issue by airisom** [Rem0o/FanControl.Releases#2291]
Will not lock PWM percentage on v180. V179 works perfect. I get a question mark next to PWM% while rpm hunts around. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No error log available, and open error log is greyed out
![V179](https://github.com/Rem0o/FanControl.Releases/assets/54457539/f055836b-67a1-4782-934a-7bf00dd5741d)
![V180](https://github.com/Rem0o/FanControl.Releases/assets/54457539/c18e9641-c6a3-4eb0-bbad-ae930e90f4e4)

**Relevant hardware specs and setup**
Asus X670E Hero
7800X3D
2x 32GB 6000MHz CL30
6900XT
Windows 11 Pro
FanControl V180 8.0

4x PWM Front Fans on one header (CHA)
3x PWM Bottom Fans on one header (CHA)
3x PWM Top Fans on one header (CPU)

**Comment by Rem0o** [comment]
If you take the LibreHardwareMonitorLib.dll from the V179 folder and overwrite the one in the V180 folder, do you get the same problem?

**Comment by airisom** [comment]
Yes, I get the same problem.

**Comment by Rem0o** [comment]
And you can switch back and forth right now between V179 and V180 and the problem only occurs in V180? 
Asking because there is literally no changes made that touches the portion of software which controls fans.

**Comment by airisom** [comment]
I fixed it. I had to recreate my config for V180. Importing config data from V179 to V180 must have caused issues somehow.
