### ISSUE TITLE
Temperature sensor stopped working on all drives, except for the boot drive

### ISSUE THREAD

**Issue by KINDR3D** [Rem0o/FanControl.Releases#2298]
After updating to version 180, FanControl suddenly isn't able to recognize the temperature sensor of both HDD's and secondary SSD. Never had this issue before. When trying to select the sensor, it tells me: " *** can't be used as a source sensor. A loop was detected." After restarting the system, it gives me the same error for all 3 drives: Missing sensor for time average sensor ***: FanControl.SerializableSensorId

**Comment by Rem0o** [comment]
Send your json config file.

**Comment by KINDR3D** [comment]
[userConfig.json](https://github.com/Rem0o/FanControl.Releases/files/14224219/userConfig.json)

**Comment by Rem0o** [comment]
Mind sharing also a screenshot of every error you get while trying to open your config?

Took a look at your config, and the loop would have to be in the time average sensors or the mix custom sensor. Basically, you 
can't have a time average or custom mix sensor referring to itself indirectly through a reference loop.   
I have seen you created a bunch of time average sensors for your drives with 1 sec time set.  What's the use for these?

**Comment by KINDR3D** [comment]
The time average sensors are only there to have a the temperature of all drives visible in the home screen. I've tried deleting the time average and mix sensors, but the temperature sensors of the drives are still missing, so I can't re-add them to a new sensor profile. Screenshot is the error I get upon startup. 

![image](https://github.com/Rem0o/FanControl.Releases/assets/159539784/2e688b5c-cb3a-4ea3-960d-65d7946c4b5e)

**Comment by KINDR3D** [comment]
Rolling back to version V173 fixed it
