### ISSUE TITLE
Multiple temperatures in a system tray

### ISSUE THREAD

**Issue by Eldenroot** [Rem0o/FanControl.Releases#23]
Screenshot below:
![image](https://user-images.githubusercontent.com/778890/90984730-29994180-e577-11ea-8cf3-1c9a03526ffd.png)

Select more temps which would be displayed in the system tray

**Comment by OlympicLarry** [comment]
+1

**Comment by Nickneem** [comment]
+1

**Comment by JarrettWendt** [comment]
+1

**Comment by pigsodomizer** [comment]
+1

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/38
