### ISSUE TITLE
Corsair Commander Core Sensors No Longer Being Read After Update V180

### ISSUE THREAD

**Issue by PanosonicYouth** [Rem0o/FanControl.Releases#2300]
Previously it read all of the fan speeds and pump speeds as well as coolant temp, these are no longer being read for the Corsair iCUE Commander Core.
Pump - no speed
Fan 1 - 6 - no speed
Coolant Temp Nan %

Have refreshed sensors multiple times to no avail. Log attached.
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/14228860/log_1.txt)

**Comment by Rem0o** [comment]
The Commander Core is supported via the https://github.com/EvanMulawski/FanControl.CorsairLink plugin and nothing natively by FanControl itself.  

I would look over there with the usual troubleshooting if you got ICUE installed and so on.
