### ISSUE TITLE
V180 Stopped Detecting Radeon RX470

### ISSUE THREAD

**Issue by MenaHabib** [Rem0o/FanControl.Releases#2302]
Hi there,
I wanted to report an issue with the latest update, V180. After updating, I noticed that my GPU fan has stopped. 
After checking its card in FC, it was reporting 0 and not detecting it at all. It worked fine when I reverted to the last version

-GPU: AMD Radeon RX470 (HIS brand)

**Comment by Rem0o** [comment]
If you go back to V179 does it still work? Nothing change in V180 concerning Radeon cards, so most likely something else is going on, likely driver related?

**Comment by MenaHabib** [comment]
Yea, once I got back to V179, it just worked!
Not sure about the drivers tbh. I will update the driver to the latest version and see if this could help.

**Comment by MenaHabib** [comment]
I updated everything, GPU driver and FanControl and now everything is working great again.
Not sure what the issue was but I'm happy it's working for me now :)
