### ISSUE TITLE
Must restart Fan Control if losing HWinfo link.

### ISSUE THREAD

**Issue by TheRealBix** [Rem0o/FanControl.Releases#2304]
Sometimes HWinfo fails to send data through its gadget, Fan Control then show an error but do not try to get new data, it just lock itself to NaN values and need to be restarted to get proper data.
[image](https://github.com/Rem0o/FanControl.Releases/assets/4289656/9da7341b-4864-4b1a-a004-b29952dfffc5)

You can see some occurrences here below.

> 01/02/2024 18:44:17: HWInfo sensor failed momentarily during operation: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C - Missing
> 01/02/2024 18:44:17: Unhandled exception in FanControl v179.0.0.0
> 01/02/2024 18:44:17: System.Exception: HWInfo sensors failed: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C
>    à FanControl.HWInfo.HWInfoPlugin.Update() dans C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:ligne 93
>    à FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
>    à System.Collections.Generic.List`1.ForEach(Action`1 action)
>    à FanControl.Domain.ComputerAccessLayer.Update()
>    à FanControl.Domain.ApplicationClock.DoActions()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 09/02/2024 15:24:37: Unhandled exception in FanControl v180.0.0.0
> 09/02/2024 15:24:37: System.Exception: HWInfo was closed during operation.
>    à FanControl.HWInfo.HWInfoPlugin.Update() dans C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:ligne 78
>    à FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
>    à System.Collections.Generic.List`1.ForEach(Action`1 action)
>    à FanControl.Domain.ComputerAccessLayer.Update()
>    à FanControl.Domain.ApplicationClock.DoActions()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 09/02/2024 21:28:09: HWInfo sensor failed momentarily during operation: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C - Missing
> 09/02/2024 21:28:09: Unhandled exception in FanControl v180.0.0.0
> 09/02/2024 21:28:09: System.Exception: HWInfo sensors failed: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C
>    à FanControl.HWInfo.HWInfoPlugin.Update() dans C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:ligne 93
>    à FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
>    à System.Collections.Generic.List`1.ForEach(Action`1 action)
>    à FanControl.Domain.ComputerAccessLayer.Update()
>    à FanControl.Domain.ApplicationClock.DoActions()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 10/02/2024 21:45:51: HWInfo sensor failed momentarily during operation: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C - Missing
> 10/02/2024 21:45:51: Unhandled exception in FanControl v180.0.0.0
> 10/02/2024 21:45:51: System.Exception: HWInfo sensors failed: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C
>    à FanControl.HWInfo.HWInfoPlugin.Update() dans C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:ligne 93
>    à FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
>    à System.Collections.Generic.List`1.ForEach(Action`1 action)
>    à FanControl.Domain.ComputerAccessLayer.Update()
>    à FanControl.Domain.ApplicationClock.DoActions()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 10/02/2024 23:09:44: HWInfo sensor failed momentarily during operation: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C - Missing
> 10/02/2024 23:09:44: Unhandled exception in FanControl v180.0.0.0
> 10/02/2024 23:09:44: System.Exception: HWInfo sensors failed: HWInfo/DDR5 DIMM [#1] (P0 CHANNEL A/DIMM 1)/SPD Hub Température/°C
>    à FanControl.HWInfo.HWInfoPlugin.Update() dans C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:ligne 93
>    à FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Update()
>    à System.Collections.Generic.List`1.ForEach(Action`1 action)
>    à FanControl.Domain.ComputerAccessLayer.Update()
>    à FanControl.Domain.ApplicationClock.DoActions()
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
>    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 

It would be nice for Fan Control to try reconnecting few times before cancelling all sensor pulls.

**Comment by Fr0stX76** [comment]
This has been fixed in recent builds of HWinfo, you will need to update.

See [here](https://www.hwinfo.com/forum/threads/feature-request-registry-lines-deleted-when-sensor-stop-reporting.9412/)

And for the record, FanControl HWinfo plugin will retry 10 times for 1seconds. So it means you sensor must be going offline for more than 10 seconds.

**Comment by TheRealBix** [comment]
Thanks for your answer, I indeed missed few HWinfo updates, I will try with everything up to date.
