### ISSUE TITLE
RTX 4080 Super FE Fans wont stop after default behavior is active.

### ISSUE THREAD

**Issue by angelt20003** [Rem0o/FanControl.Releases#2305]
FanControl cannot stop fans from the default behavior of the Nvidia RTX 4080 Super FE.

The fans can be manipulated from the 30% and above range but it won't go to 0% after the card default behavior is active. When the GPU default temperature threshold is reached, the fans will go to 30% speed. The GPU will not stop the fans until it is below the threshold and around 2:30 minutes have passed.

**Comment by Rem0o** [comment]
That's one known limitation/caveat.

See:
https://github.com/Rem0o/FanControl.Releases/wiki/Nvidia-30%25-and-0-RPM
