### ISSUE TITLE
Crashes after sleep

### ISSUE THREAD

**Issue by pelifix** [Rem0o/FanControl.Releases#231]
When PC is waking up after sleep, FanControl crashes with this error:
![image](https://user-images.githubusercontent.com/28622113/117552522-27670c80-b04c-11eb-93eb-c5cce6826ed5.png)

1) Please note I do not use "_Start with Windows_".

2) ~~`log.txt`  has this error, I don't know if it's related:~~
~~08.05.2021 17:12:43: Unhandled exception in FanControl v1.0.0.0
08.05.2021 17:12:43: System.ObjectDisposedException: Closed.
   at HidSharp.Platform.SysRefCountHelper.HandleAcquireIfOpenOrFail()
   at HidSharp.Platform.Windows.WinHidStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenX3.SoftwareControlValueChanged(Control control)
   at LibreHardwareMonitor.Hardware.Control.set_ControlMode(ControlMode value)
   at LibreHardwareMonitor.Hardware.Control.SetSoftware(Single value)
   at FanControl.ViewModels.ControlViewModel.PeriodicUpdate()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)~~

**Comment by cydRabbit** [comment]
have same issue

**Comment by pelifix** [comment]
Yes I have the NZXT Kraken X53. But I have never installed any software that came with it, feel they are to bloated. So no other software is running.

**Comment by cydRabbit** [comment]
I have NZXT Kraken X73. but I don't use NZXT CAM. never installed.
Other software that I am using RTSS and Afterburner only.

**Comment by pelifix** [comment]
Some updates:
* FanControl crashes consistently (on every) wake-up after computer has been sleeping.
* after wake-up, I see the process FanControl.exe using excessive CPU, at least one thread running on full (one cpu core on 100%)
* after wake-up, FanControl will run for 5sec to a minute, then crash with displaying the dialog box and error message (see top of this thread).
* the error, about `Nzxt.KrakenX3`, reported in `log.txt` does not show up in the log, so I think this is not related to the '_crashing after wake-up_'.

Is there anything I can do to turn on more detailed logging?

**Comment by pelifix** [comment]
Something wild is happening after PC wakes up, the FanControl.exe process is using an excessive amount of handles!
Over _**16 million**_ handles!
This is after wake-up, just before the process cashes:
![image](https://user-images.githubusercontent.com/28622113/119537679-95207180-bd8a-11eb-9bd2-9f9311ea4de9.png)


When I restart FanControl, and _before PC goes to sleep_, I see a more normal number:
![image](https://user-images.githubusercontent.com/28622113/119538072-06f8bb00-bd8b-11eb-926a-08685f8d19c0.png)

Let me know it there is anything I can do in helping logging/debugging this?

**Comment by daninko** [comment]
I am having a similar issue as pelifix with occasional crashes and excessive CPU usage after waking from sleep. I have the NZXT X53 cooler, but I have not had CAM running while I've been using the FanControl software.

**Comment by pelifix** [comment]
Yeah, FanControl still crashes on every single wake-up. I am now running version 86, no changes to behavior.

I just did a quick test, and used the "handle.exe" cli tool from SysInternals, and got this result:

```
D:\Christer\OneDrive\Tools>handle -p fancontrol -s

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

Handle type summary:
  ALPC Port       : 19
  Desktop         : 1
  Directory       : 3
  EtwRegistration : 203
  Event           : 10766716
  File            : 47
  IoCompletion    : 38
  IoCompletionReserve: 1
  IRTimer         : 8
  Key             : 83
  Mutant          : 22
  Section         : 38
  Semaphore       : 49
  Thread          : 56
  Timer           : 3
  Token           : 2
  TpWorkerFactory : 4
  WaitCompletionPacket: 49
  WindowStation   : 2
Total handles: 10767344

```

As you can see more than 10mil handles of type 'Event'. This is a few seconds before the process crashes.
Before going to sleep mode, I have around 432 Event Handles.

**Comment by pelifix** [comment]
Ok, just tested older releases, and found out:
* Version 74 - Works
* Version 76 - Fails after wakeup, leaks handles, crashes after 'using' 16millions handles.

@Rem0o , would you mind taking a look at what changed between release 74 and 76? Thanks!

**Comment by Rem0o** [comment]
What changed is now the driver is closed then reopened after a wake from sleep. 
I optimized that behavior in V86 so that it closes before going to sleep and reopens after resume from sleep.
So technically, it's just like you closed fan control before going to sleep and reopening it after it wakes up.

**Comment by pelifix** [comment]
I see, but are we sure the problem is in the driver?
I've tried to find a way to trigger the problem without going to sleep and I finally managed:

I can now reproduce the problem by doing this:
* Use version 86
* delete the CACHE file
* start FanControl
* Press "Load configuration..." and pick your settings file.
* or, just click "Refresh sensors detection"

I then instantly see the handle leak in Task Manager (or using handle.exe), crashes after 10-30 seconds.

No sleep - wake-up needed to trigger the problem.

**Comment by Rem0o** [comment]
@pelifix in that case, does it still log a problem with the NZXT handle ?

**Comment by pelifix** [comment]
No, nothing in the log file.

**Comment by Rem0o** [comment]
If you download the lastest LHM lib dll from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/964965830 (.NET Standard 2.0 ) and you swap that out into FanControl, same issue?

**Comment by pelifix** [comment]
I can't get this to work. I replace (overwrite) the files. Then FanControl will nor start. No error message, just won't start...

**Comment by Rem0o** [comment]
@pelifix  only the LibreHardwareMonitorLib.dll

**Comment by pelifix** [comment]
yes, same issue.

I replaced the dll, removed CACHE file, started FanControl, all is fine. Then I click "Refresh sensor detection..." and I see the handle leak and crash after 30 sec.

**Comment by cydRabbit** [comment]
> If you download the lastest LHM lib dll from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/964965830 ( Download the full 5mb artifact ) and you swap that out into FanControl, same issue?

It works for me. I was replaced LibreHardwareMonitorLib.dll and run FanControl successfully.
so I'll use it more times and leave result here.

**Comment by pelifix** [comment]
@cydRabbit , what is working for you? Did you even have the same problem as I am having?
Remember this is _not_ about the error in the log file.

**Comment by cydRabbit** [comment]
> > If you download the lastest LHM lib dll from https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/964965830 ( Download the full 5mb artifact ) and you swap that out into FanControl, same issue?
> 
> It works for me. I did replace LibreHardwareMonitorLib.dll and run FanControl successfully.
> so I'll use it more times and leave result here.

hmm.. still crashing after wakeup from sleep mode :(

**Comment by cydRabbit** [comment]
> @cydRabbit , what is working for you? Did you even have the same problem as I am having?
> Remember this is _not_ about the error in the log file.

yes, I have same problem like you.
FanControl.exe crash after wakeup with error alert window, right?

**Comment by Aphykit2006** [comment]
Hello
In my case, after sleep mode :  I have either an error message or a blank screen with the temperature at 0.
![after sleep](https://user-images.githubusercontent.com/78483005/125908760-19a43c4a-b01b-49c0-96cb-271111ac459c.jpg)

Log.txt
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6828682/log.txt)


Fan Control V87, Windows 10
regards

**Comment by jackoboy9** [comment]
Same issue here.

**Comment by kamolot2k** [comment]
Hi,

same here 
![fan](https://user-images.githubusercontent.com/87565644/126032739-9ed1e16e-678e-4907-ae5f-99f55ead22d1.JPG)

Test did nothing here - same result
v87, Win10 20H2

**Comment by Rem0o** [comment]
No error logs or anything?

**Comment by XanderTek** [comment]
Unfortunately V89 does not seem to have resolved this.  When it comes back from sleep, the "Handles" start increasing until it gets into the millions, then it crashes with an applications error, same as what Pelifix showed above.

Latest LHM lib.dll also doesn't seem to make a difference.

**Comment by Rem0o** [comment]
The only constant in all of this is the NZXT Kraken stuff. There is a leak in the implementation, most likely due to my Close() / Open() cycle. 

Not to sure the stream in there is handled correctly, especially with the thread and its while loop/try-catch messy looking code.
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Controller/Nzxt/KrakenX3.cs

**Comment by XanderTek** [comment]
I do have a Kraken X63.  But I've installed zero NZXT software.  I control it via https://github.com/liquidctl/liquidctl, which, if I understand correctly, doesn't leave anything running in the background.

Just tested, and LHM does the exact same thing after waking from sleep: the number of handles growing into the millions, then it crashes.  I'll see if there's an equivalent issue over there, and submit one if not.

**Comment by Rem0o** [comment]
> I do have a Kraken X63. But I've installed zero NZXT software. I control it via https://github.com/liquidctl/liquidctl, which, if I understand correctly, doesn't leave anything running in the background.
> 
> Just tested, and LHM does the exact same thing after waking from sleep: the number of handles growing into the millions, then it crashes. I'll see if there's an equivalent issue over there, and submit one if not.

That's great news you could reproduce it there, any chance you can debug C# with the source code there?

**Comment by cydRabbit** [comment]
This is my latest log file.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6959114/log.txt)

Updated latest version but still crashing after sleep.
I hope the log file to help to resolve this problem :)

**Comment by cydRabbit** [comment]
FanControl has no longer crash after sleep with V90 update.
I think this problem has resolved.

**Comment by Rem0o** [comment]
@cydRabbit  I did nothing about this problem for V90.  It probably has an external factor.

**Comment by pelifix** [comment]
**Great**! Version V90 seams to be working fine. I can cycle through sleep - wakeup without any issues. The handle count stays stable, typically just below 1000.

@Rem0o, does V90 contain an updated _LibreHardware_ component? Maybe they fixed something?

Anyway, I will monitor this for a couple of days and if everything is fine I'll close this issue.
Thanks everyone!

**Comment by pelifix** [comment]
Ok, I've been running on version V90 and V91 for a while. No problems, cycling through sleep -> wake-up working without issues.
Problem seams to be fixed in LHM.
I'm closing this issue now, thanks everyone!
