### ISSUE TITLE
Plug In for lian li galahad 2

### ISSUE THREAD

**Issue by KelCam** [Rem0o/FanControl.Releases#2314]
Please make a plugin for lian li galahad 2.
![lian li galahad 2 240](https://github.com/Rem0o/FanControl.Releases/assets/160187226/c5a1be76-56ba-44d9-983d-a3c732da7cd1)

Your program is awesome.
Will work better if it would work with my CPU cooler.
Thanks for your help.

KelCam

**Comment by Rem0o** [comment]
I can't make a plugin for this device out of thin air.  Probably can be communicated with HID, but the protocol it uses need to be sniffed with USBTrace, and for that someone with the device and some experience need to get at it.

**Comment by ClaudioVarandas** [comment]
Hi @Rem0o !

I have the device , here is the info from USBTrace as a contribution : Let me know what i can provide more and which format.


![Image](https://github.com/user-attachments/assets/61d22a75-6d59-4831-ad03-42f256a4d4ff)

![Image](https://github.com/user-attachments/assets/ed0be6df-add2-41f6-8a6f-e82eacbd5090)

![Image](https://github.com/user-attachments/assets/ddee9b34-a68d-46bd-b5ad-47e7aef3ae17)
