### ISSUE TITLE
Fans connected to controller not being detected

### ISSUE THREAD

**Issue by RenatoAAraujo** [Rem0o/FanControl.Releases#2317]
I'm trying to configure my setup and for some reason my Corsair controller is detected, but not the fans connected to it. So I can't configure my fans at all.
![image](https://github.com/Rem0o/FanControl.Releases/assets/42813455/b4346005-c5dd-40b5-affd-0470d04b4839)

Log:
[LibreHardwareMonitor.log](https://github.com/Rem0o/FanControl.Releases/files/14316235/LibreHardwareMonitor.log)

**Relevant hardware specs and setup**
Motherboard: GIGABYTE Z790 AORUS ELITE AX
CPU: i7 12700KF
GPU: NVIDIA ETX 3080 Ti
Water Cooler:  Corsair iCUE H115i ELITE CAPELLIX RGB - 280mm
Fan Controller: iCUE Commander CORE

**Comment by Rem0o** [comment]
I don't know where you see that your corsair controller is detected, because it for sure is not.  Fan #1 through 6 are empty channels on your motherboards. 

However, thanks to @EvanMulawski there is a [corsair plugin](https://github.com/EvanMulawski/FanControl.CorsairLink) available.

**Comment by RenatoAAraujo** [comment]
UPDATE

I disconnected the fans (not the RBG) from the Corsair Controller and tried to plug them directly into the motherboard, that seemed to sort everything out.
