### ISSUE TITLE
FanControl sensors and MSI Afterburner (question)

### ISSUE THREAD

**Issue by Ronin4862** [Rem0o/FanControl.Releases#2318]
Hi,

I've created a custom fan profile for the fans of a watercooled RTX 4090 GPU. The fans are connected to a motherboard fan header.

I'm very pleased with the flexibility of FanControl but I would like to know if there's a way to monitor the fans speed within MSI Afterburner.

FanControl reports that all the fans of my motherboard are controlled by the Nuvoton NCT6793D chip. I can see the fans speed within HWINFO 64 and I know I can import the monitoring data into MSI Afterburner but I don't want to run HWINFO at the same time too. 

Can I import the sensors from FanControl into MSI Afterburner?

Thanks

**Comment by Rem0o** [comment]
No, Afterburner isn't meant for that.

**Comment by SnowWolf247** [comment]
@Ronin4862 You can install this plugin https://github.com/ts-korhonen/LibreHardwareMonitorAfterburnerPlugin for msi afterburner to import sensors data from motherboard without HWINFO running. I used this plugin and set fancontrol to run my cpu fan at flat 60% and it read the %speed and rpm correctly.
![fan speed](https://github.com/Rem0o/FanControl.Releases/assets/79464143/81f1c119-0ca0-4928-b9ab-9e312d4a9422)

**Comment by Ronin4862** [comment]
> @Ronin4862 You can install this plugin https://github.com/ts-korhonen/LibreHardwareMonitorAfterburnerPlugin for msi afterburner to import sensors data from motherboard without HWINFO running. I used this plugin and set fancontrol to run my cpu fan at flat 60% and it read the %speed and rpm correctly. ![fan speed](https://private-user-images.githubusercontent.com/79464143/305815135-81f1c119-0ca0-4928-b9ab-9e312d4a9422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDY5NjYsIm5iZiI6MTcwODQwNjY2NiwicGF0aCI6Ii83OTQ2NDE0My8zMDU4MTUxMzUtODFmMWMxMTktMGNhMC00OTI4LWI5YWItOWUzMTJkNGE5NDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA1MjQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OWE4OTgwNDc5MWMyMjZiODQ0MzAwOWUwOWY2YjU1YTU2MThhMTUxZDUzNDg4MWY2ZTY1OTRkZWM1OTc4MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zFHRQddAN2ntItoS1PQhUZNwh6P2Z9fjkp7apPBli2o)

It works perfectly!
Thanks SnowWolf247!
