### ISSUE TITLE
FanControl recognizing only 2/3 mainboard headers

### ISSUE THREAD

**Issue by realsmoky** [Rem0o/FanControl.Releases#232]
Hello, everybody!

I am a huge _fan_ of this software (no pun intended). However, I am having a slight problem. 

Right now, your software is only displaying 2 out of 3 fan headers on my motherboard (not counting the CPU header).

In the software, I see a total of 4 fans I can control: the GPU fan, the CPU fan, and 2 motherboard fan headers, but the third one is missing. 

I have a Gigabyte GA-B150M-D3H motherboard. https://www.gigabyte.com/Motherboard/GA-B150M-D3H-rev-10#ov

In the bios, I can configure the third header, however, I am unable to find the third header with your software.

I will attach a screen shot of how it looks on my end. You will see that I am not using the GPU fan to cool the GPU, I am instead using a normal case fan strapped to it and plugged in into a motherboard header. 

Can you help me out with this?

Thanks in advance!

![Case Fan missing](https://user-images.githubusercontent.com/83909336/117572115-b833fb80-b0d1-11eb-80fd-2a58f97cc84f.jpg)

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/117674819-01d82100-b17a-11eb-94d7-65149a72670e.png)
