### ISSUE TITLE
Lian Li Fans not responding accordingly to FanControl

### ISSUE THREAD

**Issue by luhvi** [Rem0o/FanControl.Releases#2323]
Hi, so for some context my FanControl software has been working flawlessly for months, but after i did a fresh reinstall of windows a couple days ago i've been experiencing this bug where FanControl will show that the fan is at 0 % speed, but i will still be able to see it spinning in my case, and in the RPM section below, it also says the fan is still running at around 200-300RPM. It works flawlessly with the singular fan i have connected directly into my motherboard, and not into the Lian Li Hub.
(https://github.com/Rem0o/FanControl.Releases/assets/160776846/fba1e649-1878-4a44-b529-b8e3f86c0e0a)
(pay note to "360MM AIO Exaust" and "280MM Intake")*

ASUS B650E-F
Ryzen 7 7800X3D
RTX 4070 GAMING OC
DDR5 Corsair Vengeance 5600MHZ
Lian Li SL120 V2 - 3 Fans
Lian Li SL140 V2 - 2 Fans

I also use the 'Lian Li' plugin for FanControl, which enables me to control my Lian Li Fans, even though i use the hub.

**Comment by Rem0o** [comment]
0% != 0% speed.   It's a command, not an absolute order.

I would recommend you pair your speed sensors to your controls:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/82071dd8-a490-4f3e-bda6-f09f2e1062b7)

The plugin's control may work differently than those built-in into the software.

**Comment by luhvi** [comment]
Hi, thanks for the reply.
I tried doing as you said, but it didn't change anything, the same issue still accours, and it wasn't able to detect any sensors aside from the ones i previously states being my GPU fans, singular fan, and my 5 Lian Li Fans. And out those the only ones that don't work properly are the Lian Li ones.

**Comment by Rem0o** [comment]
Then most likely the issue is with the plugin. I would look into that repo for further bug hunting.
