### ISSUE TITLE
PC stuttering every second

### ISSUE THREAD

**Issue by joewearing** [Rem0o/FanControl.Releases#2325]
**Describe the bug**
- Every 1s, my PC stutters when FanControl is running, the mouse, audio and video freezes for around 30-80ms
- With some other apps open, FanControl is at the top of task manager as using the most CPU
- I've had FanControl for at least a year now, never had this problem
- I suspect the change was the latest Nvidia driver: v551.52, I've not had time to rollback yet, I will update this issue if I do

**Is there a log.txt file next to FanControl.exe with recent date entries?**
- No recent entries

**Relevant hardware specs and setup**
- Windows 11 Pro
- RTX 3080

**Comment by Rem0o** [comment]
What sensor sources are you using? 

Post a screenshot.  If you use the GPU section of LHM, you may want to swap to the NvAPIWrapper one.

**Comment by joewearing** [comment]
I already had NvApiWrapper enabled, disabling did not make a difference

After playing around with the LHM sensor settings, my problem is caused when "Motherboard" is checked
