### ISSUE TITLE
Sensor support missing

### ISSUE THREAD

**Issue by judgdredd** [Rem0o/FanControl.Releases#2328]
I noticed my Corsair H115i Platinum sensors aren't picked up, so i can't see the pump speed or the coolant temperature.

HWiNFO64 picks both these sensors up (please see attached pic).

Would it be possible to add these sensors as per HWiNFO64?

![2024-02-25](https://github.com/Rem0o/FanControl.Releases/assets/4535325/81b6f5a5-8ba8-4c04-a09e-434ef1fe89f5)

**Comment by Rem0o** [comment]
https://github.com/EvanMulawski/FanControl.CorsairLink
