### ISSUE TITLE
Only ITE IT8689E detected for fan control on Gigabyte Z690 Aorus Pro DDR4

### ISSUE THREAD

**Issue by MD11F** [Rem0o/FanControl.Releases#2335]
I'm currently using a Gigabyte Z690 Aorus Pro DDR4 motherboard. The board (according to HWINFO) got two ITE controllers. One controller is listed as ITE IT8689E, and another one listed as ITE IT87952E. Below are the list of fan header associated with each controller.

ITE IT8689E

1. CPU
2. SYSTEM 1
3. SYSTEM 2
4. SYSTEM 3
5. CPU_OPT

ITE IT87952E

1. SYSTEM 4
2. SYS_FAN_5_PUMP
3. SYS_FAN_6_PUMP

The software has no issue reading and controlling the first ITE controller (ITE IT8689E), but only able to read the RPM from the second controller (ITE IT87952E). can you clarify whether is this an issue regarding my motherboard or the second controller simply not supported yet?

Thank you for the great piece of software. If you need more information regarding my computer, feel free to let me know.

**Comment by Fr0stX76** [comment]
See [here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/251#issuecomment-1753939335) for some info on this issue. From what I can understand, until this is solved in LHM, it will not work on Intel based systems.
