### ISSUE TITLE
Windows 11 taskbar sensors' order changes on sensor refresh

### ISSUE THREAD

**Issue by Meh7991** [Rem0o/FanControl.Releases#2336]
Title says it all pretty much. 

I have two sensors created - one for my CPU package, and one for my GPU and have them shown all the time in my taskbar (in this order, next to the Ethernet/Volume icons) but when I manually refresh the sensors, the order of them reverses. 

It threw me off the other day whilst in a game, I checked the temps in my taskbar and was shocked when I saw, what I thought was, my CPU running at almost 70C! 

I have only noticed this since upgrading to Windows 11 from 10 earlier this week.

**Comment by Rem0o** [comment]
I don't have control over the icons order. Try and drag/n/drop them in place in the order you want. Order *should* stick in Windows.

**Comment by Meh7991** [comment]
Yeah, I thought so. 

I've tried dragging and dropping the icons to the order I want but whenever I refresh the sensors, the order of them changes. 

[Here is a video of it in action](https://youtu.be/rXgaou_cH6Q). 

I used to refresh the sensors back on Windows 10 but this never happened then, it has only happened to me since I upgraded to Windows 11 last week. 

Sometimes I need to refresh sensors due to my cooler glitching out, as per a fix mentioned in my [CorsairLink plugin issue](https://github.com/EvanMulawski/FanControl.CorsairLink/issues/144#issuecomment-1942238055).

**Comment by Rem0o** [comment]
Does the order in the Tray Icons section of FanControl match the order you
want? FanControl will add those in the tray in the order they are declared
in the Tray Icons list in the software.

**Comment by Meh7991** [comment]
Ah that makes sense - thanks! 

Weird how this only occurred on Windows 11 for me, maybe something corrupt during the upgrade.. Who knows!

**Comment by Meh7991** [comment]
Strange - manually exiting and re-opening FanControl keeps the icons in the order I set them to (**regardless** of the order in the Tray Icons list), but then when I refresh the sensors, the order of them changes (as mentioned previously). 

However, if I set the Tray Icons list order in the order where refreshing the sensors _does not_ mix up the order, then, every time FanControl opens on boot, the icons are in the wrong order again.

**Comment by ionGL** [comment]
> Strange - manually exiting and re-opening FanControl keeps the icons in the order I set them to (**regardless** of the order in the Tray Icons list), but then when I refresh the sensors, the order of them changes (as mentioned previously).
> 
> However, if I set the Tray Icons list order in the order where refreshing the sensors _does not_ mix up the order, then, every time FanControl opens on boot, the icons are in the wrong order again.

I can confirm the exact same behavior described.
I added 4 tray icons in the order i want them to be. All good. As soon as you close with ok or cancel the manual fan calibration card, or load another configuration, or refresh the sensors, all tray icons get refreshed and change order.

You can't even drag and drop them fully in the tray in the order you want. It's like they are in pairs, one can't be in certain spot.

You need to figure out how refreshing the icon mixes up the sensors, then add the tray icons in another order, by trial and error, to get them right after a refresh. So after fan control starts, a refresh is needed to get them right.

Launching the program.

![fantray1](https://github.com/Rem0o/FanControl.Releases/assets/80151979/a3f3eb67-7838-4645-92a8-fb84f2c4d704)


After opening the fan calibration card and closing it.

![fantray2](https://github.com/Rem0o/FanControl.Releases/assets/80151979/80fd8baf-84cd-4079-b72c-cf6c0a3aa879)

**Comment by Meh7991** [comment]
This seems to have been fixed as of V191.
