### ISSUE TITLE
Temps during monitor sleep

### ISSUE THREAD

**Issue by putorel** [Rem0o/FanControl.Releases#2337]
Hi, I have an OC'ed 3950x on a Dark Hero mobo. Win 11 is on high performance.  Monitors sleep after 5 min, system never. After I wake them up, I see the CPU temp at 60 C and then it drops to 35-40 pretty fast. Why doesn't it stay at idle temps even in monitor sleep mode ?  The monitored temp is of the Core (Tctl/Tdie) - i guess it's the one I should monitor for the CPU ....?  Thanks

**Comment by Rem0o** [comment]
Most likely you are seeing a CPU load spike after the monitor wake, where a lot of processes do a out of sleep routine, then once they finish it goes back down.   Nothing to worry about.

Closing as it is not a software issue.
