### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by LukePeltier** [Rem0o/FanControl.Releases#2338]
**Describe the bug**

Sometimes all sensors stop updating (RPM speeds, temp sensors, etc). If GPU or CPU heats up, fan control does not see the update, and fans do not increase speed. 

![image](https://github.com/Rem0o/FanControl.Releases/assets/18688112/5c452022-0137-49ab-8288-c60774fd13de)

Performing a sensor refresh results in the application being stuck like this indefinitely
![image](https://github.com/Rem0o/FanControl.Releases/assets/18688112/db224d18-4430-4ad4-bcda-0e478a8f119b)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Did a fresh restart, can see the issue but there are no logs after restart.

**Relevant hardware specs and setup**
[NZXT Kraken 360](https://nzxt.com/product/kraken-360)
[Nvidia 3080 MSI Ventus 3X 10G](https://us.msi.com/Graphics-Card/GeForce-RTX-3080-VENTUS-3X-10G-OC)
[ROG Maximus Z790 HERO](https://rog.asus.com/motherboards/rog-maximus/rog-maximus-z790-hero-model/)

**Comment by Rem0o** [comment]
What sensor sources do you got enabled?  Any plugin?

**Comment by LukePeltier** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/18688112/acd0c942-2da8-422d-ab8a-bdf3f06deac9)


No plugins, these are the sensors I have enabled.

**Comment by Rem0o** [comment]
I know you are using it, but does disabling controller fixes the issue?

**Comment by LukePeltier** [comment]
I will disable the controller and see if the issue reproduces

**Comment by LukePeltier** [comment]
After trying for a few hours, it seems disabling controller fixes the issue

**Comment by LukePeltier** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/18688112/45a5f468-dbaf-4bf5-92fc-2f1052246e38)
 Wondering if its related to this NZXT Kraken firmware version with LibreHardwareMonitor

**Comment by LukePeltier** [comment]
I can confirm i can actually reproduce this issue in LibreHardwareMonitor. I can create a bug ticket there if that's the better place for this.

**Comment by LukePeltier** [comment]
For anyone else seeing this, the [NZXT Kraken Plugin](https://github.com/brokenmass/Fancontrol.NzxtKraken) Resolved my issues while keeping the LibreHardwareMonitor Controller plugin disabled.

(Also here is the link to my LibreHardwareMonitor Issue) https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/1284
