### ISSUE TITLE
Gigabyte Gaming 4090 F11 BIOS upgrade issues

### ISSUE THREAD

**Issue by charles-001** [Rem0o/FanControl.Releases#2341]
Hello! I just upgraded the BIOS for my Gigabyte Gaming 4090 from F10 to F11 and Fan Control seems to not work properly with it now. I've tried playing around with my fan curve, but it seems the issues are random and don't make a whole lot of sense. Any idea what's going on here?

Great app btw!

**Comment by Rem0o** [comment]
Have you refreshed/restarted the app since?

**Comment by Rem0o** [comment]
Do you still get your sensors appearing in there or nothing at all?

**Comment by charles-001** [comment]
Yes, everything appears fine, it's just the controlling aspect. There's a question mark beside the percentage for `Controls` which means it's being controlled by an external source, but I don't have anything else controlling it. I tried to Force apply, but that didn't work.

**Comment by Rem0o** [comment]
Are you trying to run these fans below 30%?

**Comment by charles-001** [comment]
I am not. I have my curve set to 0%, but it's running @ 30%. Seems like the GPU is overriding it.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/wiki/Nvidia-30%25-and-0-RPM
