### ISSUE TITLE
MIX / Max Function

### ISSUE THREAD

**Issue by Bender2k** [Rem0o/FanControl.Releases#2342]
Hey,

i got a question if i expect the wrong thing from the Mix / Max Function.

Short Version:
I want start my Fans with a "load temp 1 OR load temp 2" function, but stop them with a "idle temp 1 AND idle temp 2" function.
Is this possible?

Long Version:
What i want to do is Turn the Case Fans On if the CPU **OR** the GPU hit their desired load temp.
**This is working with the Mix / Max function**

However the Case Fans should only turn Off if afterwards the CPU **AND** GPU are below their idle temp.
**This is not working.**

When the CPU load temp triggered the fans to turn on, the fans turn off already when the CPU temp is below the set idle.
Also if the GPU is still above the their set idle temp, even if the GPU was above their load temp while the Case Fans were already running but triggered by the CPU.

**Comment by Rem0o** [comment]
You got to use a mix fan curve, not a mix temp sensor.  Use the max function on it, and it will do exactly what you want.

**Comment by Bender2k** [comment]
Sorry, i was you using the Mix Fan, my test above refers to that.
However if you say it should work like that, i will use your screenshots and look if there's an error on my side.

If it does not work for some reason i will probably then use the mix sensor function, because my goal is to turn on the case fans only when gaming. Therefore a the mixed values of the GPU and CPU should also do something similar.

Thank you!
