### ISSUE TITLE
ASRock  970 Extreme3 r2.0 3Pin fan Port speed not readed

### ISSUE THREAD

**Issue by Liriel-666** [Rem0o/FanControl.Releases#2344]
i have a ASRock 970 Extreme3 r2.0 with a AMD-fx8320 (OC) which has a ATI Chipset.
Yeah i Know its old

It has 6 Fan Ports
CHA Fan 1 4pin
CHA Fan 2 3pin
CHA Fan 3 3pin
PWR Fan 1 3pin
CPU Fan 1 4pin
CPU Fan 2 3pin

On all 4 Pin Fan Port the Programm can Read the Spead.
On all 3 Pin Fan Port the Speed is unreadable and with 0 rpm blank.
I know that they can not control but the officialcontroll app can regulate the voltage of the 3pin.
The Plug pinout is the correct

Its seam that only this programm has a Problem because Aida64 or HWinfo64 show the Speed of the 3pin fans.
Please fix it

**Comment by Rem0o** [comment]
Hi,

See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
