### ISSUE TITLE
CPU Fan overridden by external source

### ISSUE THREAD

**Issue by Raf252** [Rem0o/FanControl.Releases#2347]
Hey,

Annoyingly my I cannot set my CPU fan curve as it stating that it is being overridden by an external source. I can’t for the life of me get to the bottom of the external source!!

It is set as PWM in MOBO. My case fans are working on FanControl as intended, just issues with the CPU cooler.

I have to to Force it but it is still not working, any help/advise would be great.

Mobo: ASUS ROG Strix B650E-F Gaming WiFi
CPU Cooler: Noctua NH-D15

Thank you

**Comment by Fr0stX76** [comment]
Armory crate installed or been installed?

If yes, [see here](https://www.reddit.com/r/ASUS/comments/o6a1ap/fan_speed_settings_messed_up_by_armoury_crate/?sort=new)

**Comment by Raf252** [comment]
> Armory crate installed or been installed?
> 
> If yes, [see here](https://www.reddit.com/r/ASUS/comments/o6a1ap/fan_speed_settings_messed_up_by_armoury_crate/?sort=new)

I did have Armoury Crate installed but I have now uninstalled it with the uninstaller. That thread mentions doing a Windows recovery, surely this is not the only workaround?

**Comment by Fr0stX76** [comment]
I would not go that far.

The thread mention asus fan service that stays installed even when AC is uninstalled.

[Here](https://www.reddit.com/r/ASUS/comments/o6a1ap/comment/h3ylmfr/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

> Sorry, I should have been more specific. I believe the service name is AsusFanControlService. I believe you can remove the service completely this command: SC delete "AsusFanControlService"

> Run the command from CMD.exe as Administrator.

**Comment by Fr0stX76** [comment]
One last thing, you need to disable AC in the Bios or the damn thing will silently sneak back in your system

**Comment by Raf252** [comment]
> One last thing, you need to disable AC in the Bios or the damn thing will silently sneak back in your system

Great, thank you, really appriciate you taking your time to come back to me. Il give this ago!
