### ISSUE TITLE
CPU idle power high with fancontrol

### ISSUE THREAD

**Issue by Logon0815** [Rem0o/FanControl.Releases#2349]
fancontrol is a real nice and flexible tool, it works even with intel scalable Xeon on Supermicro boards.

What I see else is one problem, that low power stages with desktop as well with server CPUs are not entered, when fancontrol is running.

Is there any solution for that?

I see for instance when CPU is on idle (approximately):

- Core i7-9700 power consumption 20 Watt instead of 10 Watt
- intel Xeon Gold 6326 95 Watt instead of 65 Watt

What can i do?
Logon0815

**Comment by Rem0o** [comment]
You could try and lower the process priority and deactivate all sensor sources that are not required to reduce CPU usage.
