### ISSUE TITLE
Can we have the option to use either the new or the old combo boxes for numerical input?

### ISSUE THREAD

**Issue by abqnm** [Rem0o/FanControl.Releases#235]
If this could be toggled by a setting, that would be so much better. The new numerical entry is counter to my workflow and adds about 20 minutes to fan RPM acoustic testing. Previously, I could just click in the box then roll my mouse wheel one step at a time to step the speed in 1% increments when testing the acoustic vs percentage performance of a new fan set to manual speed control. Now I have to literally type in a new value each time, adding about 20 minutes to a process that used to take about 3 minutes total.

So, _**please**_ can we get a setting to choose between the two input styles?  Thanks again for everything!

**Comment by Rem0o** [comment]
I plan to add up/down buttons with up/down arrow keyboard support.

**Comment by abqnm** [comment]
That would be perfect, thanks! Being able to step one at a time for acoustic testing when trying to find what RPMs correspond to what noise levels for new fans is really nice, so that would be a welcome addition. Cheers!

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/118566053-439c3500-b741-11eb-8fda-5f9fc26eb76c.png)

**Comment by abqnm** [comment]
Looks great! As long as they're included on the "flat" curve percentage selector as well, so I can step those one at a time, I'll be extremely happy!

**Comment by Rem0o** [comment]
They will be basically everywhere you have to choose a numeric value. Up/down arrow key support will also be there for every field.

**Comment by Rem0o** [comment]
By the way, you can also toggle manual mode and drag the cursor around if you quickly want to test 
![image](https://user-images.githubusercontent.com/14118956/118567079-28cac000-b743-11eb-84ae-2cdf0374b5a8.png)

**Comment by abqnm** [comment]
That all sounds great, thanks for taking the feedback and making changes so quickly. Cheers!

**Comment by Rem0o** [comment]
Np, it was already in the pipeline.
