### ISSUE TITLE
GPU Fan Speed gets locked to 30% sometimes

### ISSUE THREAD

**Issue by nefariouslegion** [Rem0o/FanControl.Releases#2350]
**Describe the bug**
I was playing Days Gone today and noticed my GPU was a lot hotter than normal. So first I looked at MSI Afterburner and noticed the fans were at 30%. Then I looked at FanControl and confirmed there was an issue. It seems the fans get locked at 30% for some reason. You can see the error message in my screenshot. This isn't the first time this has happened. This happened even with "Force apply(!)" enabled (as well as without it applied). I also have the "Nvidia 0% hardware curve override" enabled. 
![image](https://github.com/Rem0o/FanControl.Releases/assets/89366675/10df437b-634f-4599-b632-212369f72f62)
![image](https://github.com/Rem0o/FanControl.Releases/assets/89366675/106008cc-7f94-446a-b41f-a734b656cf2a)

Here's also a screenshot of my Afterburner setup:
![image](https://github.com/Rem0o/FanControl.Releases/assets/89366675/3122fc39-f3e5-4da5-9e99-2bfbe41c477f)
![image](https://github.com/Rem0o/FanControl.Releases/assets/89366675/fc299b9f-fc1d-409c-b074-9b28a5963438)

Also I've noticed with FanControl and Afterburner both running my GPU's fans also never go below 30% even though they're supposed to have a 0% mode.

I'm thinking it's some sort of compatibility issue with MSI Afterburner but I need that to be running to apply my GPU OC. And I use FanControl's mix curve to control both my case fans and GPU fans. So I really need this to be working again.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Here is the most recent log file.
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/14565158/log_1.txt)

**Relevant hardware specs and setup**
Custom built PC with the following specs:
-Motherboard: ASUS ROG Crosshair VIII Hero
-CPU: Ryzen 9 5900X
-GPU: Asus TUF RTX 4070 Ti
-RAM: 32GB Trident Z RAM at 3600MT/s

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/wiki/Nvidia-30%25-and-0-RPM

**Comment by nefariouslegion** [comment]
For Step 3 it says "Set your start AND stop% of your Nvidia controls to 30%." 
But where do I set that?

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/5fe4e610-1269-4ef9-99b5-0d6d9777033a)

**Comment by nefariouslegion** [comment]
Ok, i'm a bit confused as to what to put there now though. Reason being cause the steps say set it to 30% but then your screenshot shows 9% and 6%. Sorry for the dumb questions lol

**Comment by Rem0o** [comment]
do 30, just showed you where, values were not relevant to your specific case.

**Comment by nefariouslegion** [comment]
Ok I did that and it kind of fixed it? Like when I boot up a game the fans spin up accordingly. Then when I close the game the fans spin down, get locked at 30% (With the '?') for a few seconds, then go to zero. Not sure why it's getting locked for a couple seconds though. But at least things seem to be mostly working now.

Thanks for the help btw

**Comment by Rem0o** [comment]
> get locked at 30% (With the '?') for a few seconds, then go to zero. Not sure why 

As stated in the wiki, your GPU has its own logic to turn down its fans. It may have some kind of timer for the load/temperature to drop for X seconds, then go 0 RPM.
