### ISSUE TITLE
Front Case Fans stopped working after recent update

### ISSUE THREAD

**Issue by Amoeba00** [Rem0o/FanControl.Releases#2359]
I have a front case fan set of 3 fans all plugged into one expansion board that is then plugged into the motherboard.  Before this recent update it was working fine.  Now - they aren't spinning at all.  I can manually adjust the slider to confirm communication - but when that's done - they just stop.

I have it set to a flat curve where they spin at 55%.  In BIOS - it's set to DC mode.

What am I missing?
 Thanks!

**Comment by Amoeba00** [comment]
OK - So went back and removed/uninstalled FanControl (I was running the portable version).  Installed v181 and confirmed all was working fine with the configuration and fans.  Selected auto-update and the new one installed.  Front fans still spinning.  Then ran the auto-calibration utility - And that's when it "broke" and the fans stopped spinning. 

For that particular control - I selected the obsolete option for fan speed - and it reported being unable to detect anything - but at least the fans are still spinning.  I don't know how much control, if any, I have for this set though.

**Comment by LynnSnow13** [comment]
I restarted Fan Control and attempted the auto calibration again. This time the fans seemed to take a proper calibration. Problem solved for me, at least.

**Comment by Amoeba00** [comment]
> @Amoeba00 if you still have an issue, send a screenshot with your whole config visible, everything expanded, start% visible and so on.

Will do _  I'm out for a bit - but when I get back - I'll send you the config before and then the config after that keeps the fans going.

**Comment by Amoeba00** [comment]
OK went back and confirmed it again (even used the latest v186 version).

This config with v181 works - all fans work:
[V181_AllFansWork.json](https://github.com/Rem0o/FanControl.Releases/files/14858801/V181_AllFansWork.json)

This config is the same one after upgrading to v186 - pre-calibration - all fans work:
[v186-Precalibration_AllFansWorking.json](https://github.com/Rem0o/FanControl.Releases/files/14858805/v186-Precalibration_AllFansWorking.json)

Post calibration - here's the same config where that Front Case Fan stops working and even after manual calibration - the fans don't spin:
[v186_PostCalibration_FrontCaseStopped.json](https://github.com/Rem0o/FanControl.Releases/files/14858822/v186_PostCalibration_FrontCaseStopped.json)

So now, the only way to get the Front Case fans running is by selecting the Obsolete option to "Detect control % start automatically" - it does report that it was unable to detect the fan doing anything - even though the fan speeds did increase as the % increased:
[v186_Manual-Obsolete_AllFansWorking.json](https://github.com/Rem0o/FanControl.Releases/files/14858838/v186_Manual-Obsolete_AllFansWorking.json)

If I select the other Obsolete option for % stop - the fans don't spin.

Let me know if you want me to try anything else.  Thanks!

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/61951d31-58b7-46e5-bd28-03ac4f88f588)

These values make no sense.  Put back both start and stop% to 0 for your FrontCase fan.

**Comment by Amoeba00** [comment]
I agree they make no sense - but that's what the application put in there.  I do not manually edit these at all.

**Comment by Rem0o** [comment]
For now edit those manually back to 0 , you can do it from the UI in the control tile/card for your front fan.  I will investigate how it could have gone this way.

**Comment by Amoeba00** [comment]
OK - when I manually run the auto-calibration on just that fan - it repeatedly sets to 100 and 96 - but making the initial change to the stop from 96 to other values spins fans right up.

**Comment by Amoeba00** [comment]
Solution:  Turns out the [multi-fan adapter ](https://www.amazon.com/ThreeBulls-Cooling-Splitter-Adapter-Computer/dp/B07M5P7VHG)I was using needs to have a fan plugged into the first one.  Which is odd because it's labelled CPU and the ones I was using were labelled Case Fans.  If it was labelled FAN 1-5, then I would have plugged it into FAN 1 and this issue would have never happened.

**Comment by Amoeba00** [comment]
![FanControl_CaseFan](https://github.com/Rem0o/FanControl.Releases/assets/39176113/baf41c83-6c35-46c3-a3cb-7224de3347cd)
