### ISSUE TITLE
New version detected as Virus

### ISSUE THREAD

**Issue by Auribe18** [Rem0o/FanControl.Releases#2360]
Fan control prompted for an update, after the update the icon tray disappeared and the new folder created doesn't contain a executable program, just an updater, when running the updater I get the following message 

![image](https://github.com/Rem0o/FanControl.Releases/assets/33242724/5de47530-56f9-47c0-96cc-625951cd9548)

Tried downloading the new version from the website and it is also detected as a virus by chrome

![image](https://github.com/Rem0o/FanControl.Releases/assets/33242724/401ab0d1-67b6-478e-b017-8079730e2747)

I don't have any antivirus software other than Windows Defender

**Comment by Rem0o** [comment]
I tried on 2 different computers and none of the packages are flagged by Defender on W11. Maybe your definition is out of date? I will submit the packages to get white-listed.

**Comment by Auribe18** [comment]
I'll check my definitions.

In the meantime, this is what I found on windows defender's protection history, hope it helps
![image](https://github.com/Rem0o/FanControl.Releases/assets/33242724/ab939511-9e07-4c56-aaf8-b6163507f56b)

**Comment by bitbayio** [comment]
Same here, download blocked by chrome and Windows Defender detects Trojan:Win32:Wactac.B!ml.

Windows11Pro 23H2 build 22631.3296

**Comment by bitbayio** [comment]
seems like issue is resolved for me, maybe MS already whitelisted the newest version. I ran "Updater.exe" manually and now v183 starts fine.

**Comment by Auribe18** [comment]
Same here, I tried updating and I was able to upate to the newest version

**Comment by Rem0o** [comment]
Seems to be ok with defender. Closing.
