### ISSUE TITLE
Unable to delete installation foler

### ISSUE THREAD

**Issue by ECHOSUD** [Rem0o/FanControl.Releases#2363]
I am unable to delete the Fan Control folder. I have tried using windows explorer and cmd (as admin). 
Using cmd:
<code>cd C:\Program Files (x86)
rmdir "Fan Control" /s
Y</code>
I get the error <code>Fan Control\Fan Control.sys - Access is denied</code>
Using Windows Explorer, attempting to delete the file gives no error or prompts, it appears to just silently ignore the request.
I've tried: Recent reboot; Using File Locksmith from PowerToys, it dosn't detect what is causing the file to be denied from deletion; closing explorer.exe before using cmd.
Windows states the date created for the file is 12/03/2023 (DD/MM).

I'm using Windows 10. I was prompted to remove the Fan Control folder because v183 dosn't work for me so I was looking for a clean install of v181.

**Comment by Rem0o** [comment]
FanControl.sys is the driver used by the software.  Most likely the program was forced closed without proper exiting. Try and rename the file, reboot, then delete that renamed file.

**Comment by ECHOSUD** [comment]
I renamed the file to FanControlold.sys.old and after the reboot I still could not delete the Fan Control folder.
I then renamed the folder to Fan ControlOLD and found the task in task scheduler and disabled it. Either both or one of these steps then allowed me after a reboot to delete the Fan Control folder.

**Comment by ECHOSUD** [comment]
FYI, using the in application menu to exit and with no tasks in task scheduler, I am unable to delete the folder with a clean install of v183. v183 struggles to save or load configurations for me, often resulting in a blank interface with no sensors/fans.
