### ISSUE TITLE
Mix fan curve Averge function capped at 100 RPM

### ISSUE THREAD

**Issue by chli1** [Rem0o/FanControl.Releases#2365]
Using the new RPM feature the Mix fan curve seem to not work properly if using the average function.

For example: I'm having two input fan curves with 0 RPM and 869.3 RPM, so I'd expect an average of ~435 RPM, but instead the Mix fan curve returns 100 RPM.

![Bildschirmfoto vom 2024-03-15 09-13-26](https://github.com/Rem0o/FanControl.Releases/assets/2370018/8ef14a75-d995-4850-bf07-d68a74abeea5)

edit: sum and min functions seem to have the same problem: capped at 100RPM

**Comment by Rem0o** [comment]
Yup can confirm, forgot to change to max clamping values in RPM mode for those. Will fix next version.

**Comment by Rem0o** [comment]
V184
