### ISSUE TITLE
LianLi fans no more detected

### ISSUE THREAD

**Issue by GGisOnline** [Rem0o/FanControl.Releases#2366]
Since this new update, my lian li fans seems to not being detected anymore

**Comment by Rem0o** [comment]
Were you using a plugin to detect them? Did you change the installation location?

**Comment by WantStuff** [comment]
I have the same problem with the Lian Li fans and the AIO pump.
No Lian Li plugins installed. No changes to config before/after upgrade. 

After update, all Lian Li devices in the Controls section change to "Fan #1", "Fan #2", etc. They are "switched off" in the card, and do not have any Curves are associated.
I tried to reinstall 181 and revert back to V181_Sensors.json from the Backups folder, but they remained missing.
I also tried to use 181 with Windows Previous Versions to restore the folder, but they remained missing.
Eventually I had to restore the Fan Control folder from a backup.

**Comment by GGisOnline** [comment]
> Were you using a plugin to detect them? Did you change the installation location?

Yes, I was using this plugin : https://github.com/EightB1ts/FanControl.LianLi

Everything seemed fine. After I updated the app I was unable to edit the speed of my lian li fans, and after doing a new assisted setup (just in case I had to do that after the update), I totally lost my lian li fans on my panel.

Like WantStuff i decided to downgrade the version of the app and going back to the V181 one, but same issue... I don't know if the error was already there in the V181 one and that I haven't noticed it... Or if the new version just 'killed' everything related to lian li fans.

**Comment by GGisOnline** [comment]
Update : it seems that when I change the speed, my fans react to the change during 5 seconds, then go back to the minimal speed.. as if they lost the synchronization with the app

**Comment by GGisOnline** [comment]
Final update : my problem is resolved ahah, the calibration setings were making my fans at minimal speed even with 100% in manual control... Sorry for the inconvenience

**Comment by GGisOnline** [comment]
Final update : My problem is solved, L-Connect3 was still (i don't know how) installed in my computer so there was a conflict between Fan Control and L-Connect. Uninstalling L-Connect definitely solves the problem !
