### ISSUE TITLE
Crash on start after upgrading to .NET 8.0.3

### ISSUE THREAD

**Issue by tomasz1986** [Rem0o/FanControl.Releases#2367]
**Describe the bug**
This may be a problem in the new .NET 8.0.3 version itself, however just for information, Fan Control crashes on start after upgrading .NET from v8.0.2 to v8.0.3 (which was released 3 days ago). The same problem affects other .NET software (e.g. https://github.com/marticliment/WingetUI/issues/1952#issuecomment-1999455668).

**Is there a log.txt file next to FanControl.exe with recent date entries?**

```
Faulting application name: FanControl.exe, version: 183.0.0.0, time stamp: 0x65a80000
Faulting module name: coreclr.dll, version: 8.0.324.11423, time stamp: 0x65cd500d
Exception code: 0xc0000005
Fault offset: 0x000000000018c5e4
Faulting process id: 0x670
Faulting application start time: 0x01da76d782e0f159
Faulting application path: C:\Users\xxx\FanControl.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\coreclr.dll
Report Id: 190e19e7-dc47-490e-a9d5-9dcd98f39ff2
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: FanControl.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFF0188C5E4 (0x00007FFF01700000) with exit code 0x80131506.
```

**Relevant hardware specs and setup**
Not sure if Windows version is relevant, but this is happening under Windows 10 x64 here.

**Comment by Rem0o** [comment]
Seems to be a net 8.0.3 issue, try and downgrade to 8.0.2, seems to be the fix at the moment.

**Comment by tomasz1986** [comment]
Yeah, that's what I did, but the update is offered automatically by Windows Update, so I wouldn't be surprised when more people come with the same problem 😓.

**Comment by UweKeim** [comment]
Having the behavior in our own application (.NET WinForms Windows Desktop with WebView2 and DevExpress), too, downgrading the shipped application of ours to .NET 8.0.2 actually did _not_ solve it, unfortunately.
