### ISSUE TITLE
Loading a FanControl config changes my GPU fan speeds, even though control is disabled for those fans

### ISSUE THREAD

**Issue by DJN0** [Rem0o/FanControl.Releases#237]
I am experiencing an issue where loading a FanControl config changes my GPU's three fan speeds from 64-64-50 (the speeds I manually set in EVGA Precision X1) to 55-55-50. The GPU fan curves are toggled off in all of my FanControl configs, so FanControl should not be changing the GPU fan speeds. I have noticed this issue with two different GPU models - the EVGA 3090 I am using now, and the Asus 3080 I was using previously (although I don't remember the exact numbers for the 3080). I'm currently working around this issue by immediately reapplying my Precision X1 profile every time I change my FanControl config.

**Comment by Rem0o** [comment]
A similar issue was reported for AMD cards and was fixed, didn't think it would affect the Nvidia ones also.   Will fix.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V79
