### ISSUE TITLE
Pairing of CPU Fan not working

### ISSUE THREAD

**Issue by thegame4craft** [Rem0o/FanControl.Releases#2370]
**Describe the bug**
If i pair the CPU Fan manually (which is connected to FAN 2 on the mainboard), the popup lags for a second and closes. The Fan and the sensor isn't paired. During the popup the fan RPM gets moved to 50%. After the popup closes finally, the rpm gets resetted to where it was before, and nothing happend else. Even if i try to pair it manually, it wont pair them. Before the update they were paired. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
There is no log.txt file

**Relevant hardware specs and setup**
ASUS prime b450-plus
AMD Ryzen 5 3600
ASUS ROG STRIX Gaming RX 570 
16 gb ddr4 ram

**Comment by Rem0o** [comment]
At which point exactly does it not work in the workflow of the manual pairing? Can you highlight a speed sensor in the dialog correctly?

**Comment by thegame4craft** [comment]
Hi,
It doesn't work at the point where the sensor and the control are connected.
The workflow will be:
Open manual pairing modal for control (selected control will be set to 50%) > select sensor that matches the fan > press button (I don't know the button is named) > the app will hang for a second > the modal will close and at the control will the speed appear and disappear instantly). 

If you need any screenshots, please let me know that, I'm currently only on my mobile phone

**Comment by Rem0o** [comment]
Yes screenshot is a must.

**Comment by thegame4craft** [comment]
https://youtu.be/gVl9JEiG4uE

I've made a little video. I needed to upload it to youtube because the file was to large. I hope everthing is understandable

**Comment by Rem0o** [comment]
Thanks a lot for the video. 

Two things. Make sure you are on V184 (latest version), easier to debug for me.  
Also, mind sending me your userConfig.json file?

**Comment by Rem0o** [comment]
I'm a bit puzzled, because you are the only user as of now to have this issue, and I obviously can't get that bug on my test machines... Does it do the same for all fans? If you remove the paired fan sensor on an other control, do you get the same behavior?

**Comment by thegame4craft** [comment]
I'll update to v184 when im at home. I'll write again later

**Comment by thegame4craft** [comment]
With the newest v185 it seems to be fixed.

**Comment by thegame4craft** [comment]
And again in v194
