### ISSUE TITLE
Gigabyte Z790 AORUS ELITE AX ICE fans issue

### ISSUE THREAD

**Issue by Manee-1** [Rem0o/FanControl.Releases#2373]
hi,
i have issue with fans. 3 of my fans dont work as u can see in the pic. 4 thermalright fans work fine but the other 3 fans dont.
![3 Fan issue ](https://github.com/Rem0o/FanControl.Releases/assets/163699612/4e33ab0f-3abf-419f-962d-3ed3ea7bf1b2)

specs
Mb: Gigabyte Z790 AORUS ELITE AX ICE
windows 11 home
CPU: i7 14700k
Gpu: 4080s
Fans: 4x Thermalright TL-S12-W 120mm ARGB PWM = they work fine
other 3 fans: not working and dont know there name
case: Lian Li O11D Evo RGB White ATX Case

**Comment by Fr0stX76** [comment]
Fitst are they directly connected to the motherboard, not on any splitter/hub? If so, this could be the issue.

 Second, are they DC fans or PWM fans?

2 pins = DC, no rpm feedback. Very uncommun in 2024. If you have these, it will not work.
3 pins = DC
4 pins = PWM

Make sure your bios matches the type of fans you have and make sure they are configured in "manual" mode , suggested 50%

> Q: What settings should I set in my BIOS to play along nicely with FanControl?
A: You want to avoid any "smart" control from your BIOS. Setting a fixed default speed, like 50%, works great for most people. Also keep an eye if your BIOS has PWM or DC mode on. One could work better for you depending on your setup.

Beyond that, not sure what else to check

**Comment by Rem0o** [comment]
From the picture, we can see the 3 transparent controls have corresponding 0 RPM sensor, hence no fan plugged into them.  The cards aren't fans, they are fan headers on your motherboard.  Keep that in mind, look where you plugged your fans, and you should figure it out.

**Comment by Manee-1** [comment]
by cards u mean graphic cards. sorry i am didnt build this pc myself. what do i do now? i have zero knowledge of these things. i can see there is sticker on the fans and they are pwm fans.

**Comment by Rem0o** [comment]
By cards I meant the green squares in the user interfaces.

**Comment by Manee-1** [comment]
do i have to open pc case and check the wires. I hear about frying my pc components. what to do?

**Comment by Manee-1** [comment]
The fans rgb lights are on but just not spinning

**Comment by Manee-1** [comment]
sorry My bad, fans are spinning but in the "fan control" they are not sensed I guess not sure what's happening, I hop it makes sense 
FANS are : 7x Thermalright TL-S12-W 120mm ARGB PWM

**Comment by Manee-1** [comment]
Do I need to enable Gigabyte second chip option in the SETTINGS? what does the settings means

**Comment by Rem0o** [comment]
> Do I need to enable Gigabyte second chip option in the SETTINGS? what does the settings means

Some gigabyte boards require a special driver to enable the control of a secondary chip on the motherboard which controls half of the fan headers. However you should still get a RPM reading without it.

Now for your 3 missing fans, where are they physically plugged in, in your PC case.  My guess is not on motherboard headers, most likely directly to the PSU or through a small fan hub. The only way to get them to work through fan control is if they are plugged directly on a motherboard header.
