### ISSUE TITLE
Partial Calibration failed Update 184

### ISSUE THREAD

**Issue by Comprande** [Rem0o/FanControl.Releases#2374]
Updating from 183 to 184 via-software updater goes OK, but using fresh installer of either 4.8 or 8.0 and calibration on one of the fans on Strix 3090 fails. I see someone else reported the same.

Went back to installer 183 and all goes smoothly. 

Amazing software!! hopefully this gets sorted out and new update gets released.

Thank you 

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/14627739/log.txt)

**Comment by Comprande** [comment]
<img width="1441" alt="Untitled" src="https://github.com/Rem0o/FanControl.Releases/assets/163705740/8638ffd8-df8a-4a5f-bce8-651821c79d02">

**Comment by Comprande** [comment]
<img width="1441" alt="Untitled" src="https://github.com/Rem0o/FanControl.Releases/assets/163705740/bdc0154f-496d-410d-98f0-84409f4fcb6d">

**Comment by Rem0o** [comment]
You got no paired speed sensor, how could you do a calibration?

**Comment by Comprande** [comment]
Why wouldn't that bean  issue with 183 I didn't have to adjust anything. Any direction?
Thank you

**Comment by Comprande** [comment]
<img width="1501" alt="Untitled" src="https://github.com/Rem0o/FanControl.Releases/assets/163705740/79f04c3a-4765-452e-a796-fc026d49b428">

**Comment by Rem0o** [comment]
Did you try to re-run the assisted setup in V184?  
V184 now tries to see a stable max value out of your fan speed before starting to decrease slowly and calibrate.   If the value never stabilize, I don't think the software handles that scenario properly, hence your bug.  You can get to V184, just don't override your existing calibration and you'll be fine.   V184 fixes a few bugs you might want to get still.  I will fix the automatic-calibration procedure.

Side note:
Holy-sh** how many sensors do you got in tray 😅

**Comment by Comprande** [comment]
Thank you for your assistance I hear you. 
I might just stay on 183 and wait for update (whenever that might be :).
HWiNFO runs in the background, but most sensors are disabled except GPU core, hotspot and junction and 7950X's core and chipset temps.  I like to see the main temps as I do run some heavy programs that stress the heck both CPU and GPU.

As you can see there is also aquasuite icon which controls my aquaero 6XT and curves for case and CPU fans, but tbh. I am so impressed with your little fan utility that I'm considering removing aqaero and aquasuite as it takes some juice and adds overall extra latency and just use FanControl for all of my fans.
Thank you so much for the development and allowing for us to use for free.
Sometimes I will be sending donation your way. 
Thank you

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V185

**Comment by Comprande** [comment]
I am so excited to test this.
I have several systems in my office with very close configurations.
I'll take a  trip later tonight and I'll get back with results.🤞
Again, thank you so much for such a quick update.






Sent from my Galaxy



-------- Original message --------
From: Rem0o ***@***.***>
Date: 2024-03-22 3:59 p.m. (GMT-05:00)
To: "Rem0o/FanControl.Releases" ***@***.***>
Cc: Comprande ***@***.***>, Author ***@***.***>
Subject: Re: [Rem0o/FanControl.Releases] Partial Calibration failed Update 184 (Issue #2374)


https://github.com/Rem0o/FanControl.Releases/releases/tag/V185
