### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by IvanJuraj** [Rem0o/FanControl.Releases#2377]
When I am trying to update I get this message, anyone know where the problem might be and how to fix it?

(prompt from cmd)
Download failed:
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Download failed:
The remote certificate is invalid according to the validation procedure.
Restarting Fan Control...

RTX 2070 Super
i5-10400f
ASRock B460M pro 4
16GB RAM

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/14626720/log.txt)

**Comment by Rem0o** [comment]
Any VPN or fancy network software installed?  Seems like it can't trust the raw subdomain of Github.

**Comment by IvanJuraj** [comment]
Only Proton VPN but I wasn't using it. Otherwise nothing

**Comment by Rem0o** [comment]
That's a certificate issue on your machine.   Do you got a PiHole or something else like that? Otherwise I really can't tell, because that's an isolated issue on your end. It's a simple web request.

**Comment by IvanJuraj** [comment]
I've already figured out the issue, my ISP had some kind of online web
protection. I turned it off and everything works as expected.
Nevertheless, thanks for your help
