### ISSUE TITLE
[REQUEST] Adjustable x-axis for temperature graphs

### ISSUE THREAD

**Issue by akren2482** [Rem0o/FanControl.Releases#238]
Hello, sorry if this is the wrong place to post requests. I'm new to github, let me know. 

I'd like to be able to set fan curves up to ~110C, due to the high memory junction temperatures that are tolerated in the 3000 series gpus. For now my work-around is to make a custom mix sensor that averages the >100C signal with a 0C signal, effectively giving me double the range.

I also could see a use case for going sub 20C on the X-axis for sub-ambient setups that might want to control pump speeds or chillers with the PWM signal from the mobo.

**Comment by Rem0o** [comment]
I do have technically that option built-in, it is just not mapped to any way a user can change those values ( and saved in their config ).

Shouldn't be hard to do, will do if some more people manifest interest.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/160035525-7a9508ad-129b-4882-a1b2-ef4c4f930f90.png)
