### ISSUE TITLE
New Case, can't delete old fans?

### ISSUE THREAD

**Issue by joeSch75** [Rem0o/FanControl.Releases#2382]
Hey there, the app is working well as it has for a long time,  I love it but my confusion is after I got a new Fractal tower with a fan header inside (all under case fans) I am confused why my old fans are still there but obviously fan control cant communicate with them and I am just sick of seeing them in the app. However, my confusion is why can't I delete them? What am I missing?

Thanks!

![Screenshot 2024-03-18 105726](https://github.com/Rem0o/FanControl.Releases/assets/163886292/7be2bc84-8b1f-4144-9384-618d24cb8c1f)

**Comment by Rem0o** [comment]
Click the eye icon in the top right corner -> Uncheck Show hidden cards.

**Comment by joeSch75** [comment]
> Click the eye icon in the top right corner -> Uncheck Show hidden cards. Please close this issue if that does it.

Im sorry I did not explain myself well enough, I know how to hide them, but these fans do not exist anymore, I moved my parts into a new case and these are still there even though they do not exist, can I permanently delete them?

**Comment by Rem0o** [comment]
Those cards in the UI aren't "Fans", they are Fan headers, fan "channels" to be exact, which are still on your motherboard, just not plugged. No you can't "delete" them, as they are still there, just not in used.   Just leave them hidden.

**Comment by joeSch75** [comment]
> Those cards in the UI aren't "Fans", they are Fan headers, fan "channels" to be exact, which are still on your motherboard, just not plugged. No you can't "delete" them, as they are still there, just not in used. Just leave them hidden.

Thanks a ton, I appreciate the help, all good here
