### ISSUE TITLE
Sensor not found except CPU fans

### ISSUE THREAD

**Issue by Piggyman91011** [Rem0o/FanControl.Releases#2387]
![Screenshot 2024-03-19 180736](https://github.com/Rem0o/FanControl.Releases/assets/164110903/bed4e82e-6d05-4d56-b91f-e0ee790cf5a5)
![Screenshot 2024-03-19 180833](https://github.com/Rem0o/FanControl.Releases/assets/164110903/555676da-3cef-4326-bf85-219882008ac8)
I am having the issue of the software saying that I have no other fan sensors available other than the CPU fan(DeepCool). I looked up the issue on Reddit and all of the Bug report issue on Github and I found that it wasn't working with a certain AMD driver that is like 1-2 years old by now. I have the driver on 23.20.30. I have changed my fans in the BIOS to say that it was "PWM" and that didn't help. I also cleared my CMOS and that still didn't work.
These are the Fans I have:
3 GPU fans on a RX 7800x
Lian-Li L connect 3 software on the latest version at the time. Lian-L L connect 31.6.30 and SL V2 on version 2022/10/31\
I have 6 Lian Li SL 120 V2.
I saw this software on JayzTwoCents channel a while back and I tried to fix this before and didn't work.
Can you help me?

**Comment by Rem0o** [comment]
Where are your Lian-li fans connected? Are they on sys-headers on your motherboard?  if the answer is no, this is why the system fan headers don't respond, they have nothing plugged into them. 

Lucky for you, this plugin for L-Connect controller exists: https://github.com/EightB1ts/FanControl.LianLi
Read the README carefully in there, there are a few gotchas.

**Comment by Hyporeal** [comment]
I'm having a similar issue.  i've been using fan control for a few years now without issue. i'm trying to figure out what's going on

**Comment by Piggyman91011** [comment]
I have the Fan hub connected to my motherboard. Thanks for the info and the link.

**Comment by Piggyman91011** [comment]
What about the GPU fans not showing up on the software?

**Comment by Rem0o** [comment]
From FAQ:
Q: My new AMD card can't be controlled, why?
A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!

**Comment by Hyporeal** [comment]
> From FAQ: Q: My new AMD card can't be controlled, why? A: Newer AMD cards are not supported. If you can provide a working sample of code that works with these newer cards, please share!

Do you know if an RTX 4080 is supported? Did you recently add the warning when speed sensors are not detected? I'm still trying to diagnose my issues.

PS - Thanks Remi. You're the best!

**Comment by Piggyman91011** [comment]
RX 7800xt

**Comment by Piggyman91011** [comment]
The download didn’t work. What did I do wrong. Can you go step by step on how to install it?

**Comment by Rem0o** [comment]
@Piggyman91011 
https://github.com/EightB1ts/FanControl.LianLi#installation

There is an install section.  Keep in mind however that you may need to right click that dll, go into properties, and hit the "unblock/unlock" checkbox. Otherwise FanControl won't see it.

**Comment by Piggyman91011** [comment]
Alright. Is there any way for My 7800xt GPU fans to be picked up?

**Comment by Piggyman91011** [comment]
Do I need to download Net framework?

**Comment by Piggyman91011** [comment]
You said that my Graphics card isn’t supported. What can I give you to support my graphics card? If you want to.

**Comment by Hyporeal** [comment]
> You said that my Graphics card isn’t supported. What can I give you to support my graphics card? If you want to.

If you have programming skills or can collaborate with someone who does, you could use AMD's official GPU control APIs or reverse-engineering existing solutions that work with the RX 7800x.

In other words, nothing you can do right now.

**Comment by Piggyman91011** [comment]
Are you going to support more GPUs in the future?

**Comment by Rem0o** [comment]
I wish, but as @Hyporeal said, some work needs to be done to make the ADLX API work properly.  My best effort at it gave inconsistent results (https://github.com/Rem0o/FanControl.ADLX).

**Comment by Piggyman91011** [comment]
Thanks for the support. I really appreciate it. If I find anything I need you to help with, I’ll let you know. See Ya!
