### ISSUE TITLE
liquid temperature as sensor not working anymore

### ISSUE THREAD

**Issue by xxjoe2** [Rem0o/FanControl.Releases#2389]
hi

been using fancontrol and it's working perfectly, util recent update 184 (i skipped 183)

i have set up a "sensor" which bases on the AIO's liquid temperature to control the fans speed of the AIO. however, after updated to 184, it shows no sensor for my AIO fans but that "sensor" is still available at the bottom. and now those fans are out of control and making extra noise

i know i can use the cpu temp as the sensor for those fans but for some reasons i opted to link them to the temp of the AIO's liquid temp

is it intended or a bug?

thanks

**Comment by Rem0o** [comment]
Could you add screenshots to describe your situation?

> it shows no sensor for my AIO fans but that "sensor" is still available at the bottom.

That sentence makes no sense to me.

**Comment by xxjoe2** [comment]
> Could you add screenshots to describe your situation?
> 
> > it shows no sensor for my AIO fans but that "sensor" is still available at the bottom.
> 
> That sentence makes no sense to me.

yeah sure, maybe i didnt explain the problem very clearly

here is the screenshot

![Capture1](https://github.com/Rem0o/FanControl.Releases/assets/83495134/44f0bdc4-a221-430d-a18d-0829d6fc09c1)



thanks

**Comment by Rem0o** [comment]
What's the problem in the screenshot? You got a graph fan curve based on your H115i, and that graph is assigned to 3 controls of your H115i, so they are not missing?  What's "missing" ? Are you talking about this?:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/774ccaf4-73ab-40c6-a579-8797a7dcc3c2)

**Comment by xxjoe2** [comment]
> What's the problem in the screenshot? You got a graph fan curve based on your H115i, and that graph is assigned to 3 controls of your H115i, so they are not missing? What's "missing" ? Are you talking about this?: ![image](https://private-user-images.githubusercontent.com/14118956/315307138-774ccaf4-73ab-40c6-a579-8797a7dcc3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjgzNjYsIm5iZiI6MTcxMTAyODA2NiwicGF0aCI6Ii8xNDExODk1Ni8zMTUzMDcxMzgtNzc0Y2NhZjQtNzNhYi00MGM2LWE1NzktODc5N2E3ZGNjM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEzMzQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OTJmOTMzNGEyMzNlN2EwYzE1OTJiYWZjOWRmOWFlZjQxNDA4NDA4MjlkN2Y1YWE0ZDM0YmMxNjliZDljZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UngUC91nAMSsqVOFCv6Wc3O-jJ_VpnCmfgMtgk--mG8)

yes
when i clicked on that, it asks me to pair a speed sensor not that "liquid temperature" is not a real sensor and thus it is not in the list provided

![Capture2](https://github.com/Rem0o/FanControl.Releases/assets/83495134/6fdebf8b-f5bd-4e55-a6ea-71167ab718a4)

**Comment by Rem0o** [comment]
The list you see in the dialog is not meant to show you temperature sensors. It's meant to pair the RPM of the fan to the control card.  This has nothing to do with your fan curve, it's an entirely separate thing.

In this screenshot:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/db674234-baf5-45bf-acd4-a7a02e5437f8)

**Comment by ionGL** [comment]
How are you able to read that H150i RGB PRO XT liquid temp in Fan Control? 

I have an older h150i pro rgb that is not seen by LHM

**Comment by Rem0o** [comment]
@ionGL  https://github.com/EvanMulawski/FanControl.CorsairLink

**Comment by ionGL** [comment]
Damn, i was sleeping on that one. I've been using argus for the native h150i pro rgb support and fan control only for the gpu, as argus doesn't support multiple controllers for the gpu yet (its version of mix with max function).
Installed the plugin and it picked the fans, pump and liquid temp right away.
Bringing the curves and all from argus to Fan Control to test. I can see the ram usage going up! :D
