### ISSUE TITLE
FanControl Crashes, Rondom No RPM sensors detected, Inconsistent fans detection 

### ISSUE THREAD

**Issue by Comprande** [Rem0o/FanControl.Releases#2391]
So! As I mentioned previously, I fell in love with this small fan utility.  I knew at one point I would like to ditch aquauite by auacomputer and use only FanControl, but  didn't think I would do it so soon at least I have tried. 

Sadly, it didn't work as I expected and what I was facing was exactly the same as few people reported already.
I would still like to use only FanControl for all of my system fans, but till this is in someway resolved and more stable i will only use it for my Strix 3090 fans.

Currently and for the past 15 years since I was water-cooling I have been using Aquaero 6XT in combination with aquasuite. Its very powerful fan, pump and other aquacomputer devises controller, but my biggest gripe with it was that sometimes aquasuite service wouldn't start especially on system reboot and when user is not aware of that and in my case GPU and CPU custom curve wouldn't respond to temps changes and things would get really hot, that is why I have all necessary readouts icons in tray to keep eye on it.

For the past 2 days, pretty much since I discovered FanControl I have removed Aquaero and aquasuite from my system and because till now I was using aquasuite's voltage control and 3pin cables I replaced all cables to 4pin to make switch to PWM I meant to do that long time ago anyways. 

Anyhow. I was so exited and that should tell you how much i like the FanControl I got rid of my hardware controller and aquasuite that I have been renewing subscription every year, but things didn't work exactly as I thought.

Reason I writing this,  is hope that the reports of similar issues must be related to still buggy software and hopefully this can eventually be fixed so I can  try it again and have more successes, but till then I will keep on using what worked for me for the past years.

Now! the issues are...upon  launching FanControl and running assisted setup it would tell me "No RPM sensor detected" then would detect some fans but not other and when It did detect them, they would be grey out, and using manual control and moving slighter would not do anything with some. I reinstalled and re-did that several times and sometimes would detect my 2x front fans and bottom 2 fans then would not detect them at all so its inconsistent...

BTW. all fans are 120mm Noctua NF-A12x25 chromax. 

2 front intake
1 rear exhaust 
1 top exhaust
2x bottom intake
2x CPU

The only fans would run always correctly was CPU and GPU.

Also, randomly FanControl would crash after re-selecting  sensors to be included in assisted setup.

I hope this might help with further investigation and possibly fixes.

I apologize for this lengthy msg.

Thank you

**Comment by Rem0o** [comment]
How are your fans plugged in your system? Motherboard headers, still on Aquaero 6XT?  What motherboard do you got? What kind of config do you got in your motherboard bios on these fan headers? Also send a screenshot of the FanControl UI, what cards are showing and so on.

**Comment by Comprande** [comment]
Fans were connected directly to motherboards headers with Y splitters where needed  e.g. front intake, bottom intake and so on so forth. I have tried with aquaero,  regardless how I proceeded with configuration, nothing was detected other then CPU and GPU but, I wasn't expecting for that to work,  aquaero uses USB on motherboard to detect motherboards sensors so maybe that was conflicting I don't know, but I was going to totally remove aquaero, but that didn't work as planned :)

I have tried different settings in BIOS e.g. let motherboard detect connected fans but FanControl to control them, ignore, but then go from there, but nothing changed.
Motherboard is Strix x670E-E with ton of headers. I also tried moving fans to different headers, but that didn't make much difference.
I also tried with ALL and selective e.g. CPU, GPU and Motherboard sensors to be picked up my FanControl via assisted setup, no change, detected some, then after reboot running the same didn't detected the same.

Unfortunately all day yesterday I was moving all cabling, controller and aquasuite back so I cant make a screenshot.
I am disappointed, but not discourage. For now  I will wait and see maybe with others users reporting similar issues and you might find fixes I might try again in a while. 

For now I just don't want to take everything apart again till some movement in fixing of some of the bugs are made, but I will be patiently looking out for fixes and improvements of this absolutely amazing software. 

I hope sometimes I can move everything from aquaero and aquasuite to FanControl. I wouldn't mind setting annual donations to you rather then to keep on paying annual subscription to aquasuite. 

Thank you

**Comment by Comprande** [comment]
Atm. I'm running V183 to control fans on my GPU. 
FYI. 
While I was trying to have FanControl run all my fans (2x front Intake, 2x bottom intake, 1x rear exhaust, 1x top exhaust, GPU, CPU it did running flawlessly on GPU and CPU and  partly  pair of bottom fans while connected to M/B. 

I truly hope that FanControl can eventually run all of the fans as flawlessly  as it did with these I mentioned. I will be happy up to the moon.

Although, I mentioned that I put everything back together to original state and I really don't feel like taking all apart again, but make no mistake, if you think you found source(s) of the misbehaves I and others mentioned and have new release to test I will be more then happy and willing to take things apart again and try it, no doubt.  I don't even know why I'm so abscessed with this small app :):) small yet has some powerful features and most of all is so darn light on resources. 

Thanks again for continues development and I'm looking forward to see upcoming releases with hopefully fixes to address the reported misbehaves. 

Thank you again

**Comment by Comprande** [comment]
Hi Rem0o,

Just curios, can FanControl use 3pin cables in order to control the fans? Thus far I have been using 3 pin cables and controlling fans via aquasuite voltage rather then RPM. I'm about to order bunch or 4 pin custom length fan cables, rather then use my  own as they  all over as far is length and hopefully slowly switch to only FanControl, but before I do that I was wondering about alternative way of doing it with my current cables 3pin.
Any direction instructions would be great.
Thank you

________________________________

**Comment by Rem0o** [comment]
It can, as long as your motherboard allow DC control on its fan headers.

**Comment by Comprande** [comment]
That is a good start and for me to look into it.
If it does  and I thinkI so DC option in Bios and I know Im asking a lot questions do I need to change that in Bios of FanControl will use that and wi do that on its own.
Is there a different approach on  how I would start with FanControl opposed to with 4 pin, would FanControl still  do calibration.
I have tried to look for that info but no luck.
I'm thinking on trying to swich all today again  for the second  time that is why I'm asking to be prepare and what to look for.
Thank you




Sent from my Galaxy



-------- Original message --------
From: Rem0o ***@***.***>
Date: 2024-03-23 3:19 p.m. (GMT-05:00)
To: "Rem0o/FanControl.Releases" ***@***.***>
Cc: Comprande ***@***.***>, Author ***@***.***>
Subject: Re: [Rem0o/FanControl.Releases] FanControl Crashes, Rondom No RPM sensors detected, Inconsistent fans detection (Issue #2391)


It can, as long as your motherboard allow DC control on its fan headers.

**Comment by Comprande** [comment]
It does have DC mode.
You might be laughing, but I got obsessed with your FanControl software and although my aquaero with aquasuite  works good I still  would prefer to use only fancontrol.




Sent from my Galaxy



-------- Original message --------
From: Rem0o ***@***.***>
Date: 2024-03-23 3:19 p.m. (GMT-05:00)
To: "Rem0o/FanControl.Releases" ***@***.***>
Cc: Comprande ***@***.***>, Author ***@***.***>
Subject: Re: [Rem0o/FanControl.Releases] FanControl Crashes, Rondom No RPM sensors detected, Inconsistent fans detection (Issue #2391)


It can, as long as your motherboard allow DC control on its fan headers.

**Comment by Comprande** [comment]
Sorry, for flooding you with my questions. I just realize that my previous email wasn't clear, in fact some of it didn't make sense. Normally I whare glasses, but not only I don't have them on me, I'm also on the road so limitation in how I see what I'm typing and my big fingers hitting the wrong keys which that doesn't help.

I was wondering with 3 pin cables, what warning should I be looking for and what to expect in terms of initial run of FanControl opposed to having 4 pin cables.
Rason I'm asking because till I get my custom cables made I would keep my current 3 pin so I wouldn't have to take things apart, but how FanControl reacts to 3pin cables so I'm aware. Is the calibration based on rpm detection or generally voltage and then setting the % of start and stop.

Reason for all those question is because if I come across something obvious that is different between 3pin and 4 pin cables and FanControl initial setup run as it runs when connected to 4 pin cables I don't have to post  something as a "Bug" when in fact might not be.

I hope you can give me general idea and what I might expect from having 3 pin oppose to 4 pin.
Thank you
________________________________

**Comment by Comprande** [comment]
Hi there,
I was really hoping you would respond to my latest email... for reason, but that's OK.
Good day.
Thanks



Sent from my Galaxy



-------- Original message --------
From: Rem0o ***@***.***>
Date: 2024-03-23 3:19 p.m. (GMT-05:00)
To: "Rem0o/FanControl.Releases" ***@***.***>
Cc: Comprande ***@***.***>, Author ***@***.***>
Subject: Re: [Rem0o/FanControl.Releases] FanControl Crashes, Rondom No RPM sensors detected, Inconsistent fans detection (Issue #2391)


It can, as long as your motherboard allow DC control on its fan headers.

**Comment by Rem0o** [comment]
DC vs PWM control doesn't affect FanControl functionality.  The software will work the same, it's just your motherboard will output a varying voltage on the headers instead of a PWM signal.

**Comment by Comprande** [comment]
Thank you for your response  I really appreciate it.
I've decided I'm gonna wait for my custom 4 pin cables to arrive from ModDIY,  they have been my place of custom cables and other things for a long time.
Now! Here is what I'm debating on... As I have previously mentioned, there is something about FanControl that trully got my attention. The software is very intriguing and when it works the functionality  and option of configuration is awsom.
Please give me a little time to  figure out  If I want to donate you a chunk $ and do random donations or set a monthly donation.. I will figure that out,  but I definitely want to support this project.
I hope people that using FanControl and appreciate it will consider doing the same.
Thank you.




Sent from my Galaxy



-------- Original message --------
From: Rem0o ***@***.***>
Date: 2024-03-24 12:39 p.m. (GMT-05:00)
To: "Rem0o/FanControl.Releases" ***@***.***>
Cc: Comprande ***@***.***>, Author ***@***.***>
Subject: Re: [Rem0o/FanControl.Releases] FanControl Crashes, Rondom No RPM sensors detected, Inconsistent fans detection (Issue #2391)


DC vs PWM control doesn't affect FanControl functionality. The software will work the same, it's just your motherboard will output a varying voltage on the headers instead of a PWM signal.
