### ISSUE TITLE
V184 - 3070 Ti has 3 fans but 2 can be controlled

### ISSUE THREAD

**Issue by RealMenLoveZeus** [Rem0o/FanControl.Releases#2392]
I have read the FAQ but I still do not understand my issue.
When I select "pair speed sensor automatically" all 3 GPU fans spin but only "Fan 2 - NVIDIA..." can be paired to a control tile.

My issue is "Fan 1..." cannot be paired to the GPU.
If I try to manually pair the fan to another free fan spot nothing happens either.

![image](https://github.com/Rem0o/FanControl.Releases/assets/75200290/62f4309b-54ad-425c-bacc-da57d31f0c4e)

**Comment by Rem0o** [comment]
Go to the "eye" icon at the top right and show all tiles.  Now take the second Nvidia control tile, unhide it, then try to turn it on and put it in manual mode.  Does Fan1 respond to it?

**Comment by RealMenLoveZeus** [comment]
Thank you very much! That worked!
