### ISSUE TITLE
Unable to control all fans

### ISSUE THREAD

**Issue by ZephProjects** [Rem0o/FanControl.Releases#2394]
Hey everyone. Thanks for reading my post.

I've been using fan control for a while and I've had this issue for quite a long time but have never really been able to find a solution.

My PC contains 12 fans since I use the O-11 air and don't have enough headers, so I've utilized some splitters to help with that. I'm able to connect 3 fans into one splitter.

I'm unable to control all my fans (specifically my AIO mounted fans) and Its slightly annoying since they are noticeablly louder than the rest because they are running on a higher RPM.

In the BIOS, I've set all fan headers to run on PWM so I have full control over the RPMs, however, I'm still unable to control those 3 fans.

Any suggestions/solutions would be great.

Thanks.

**Comment by Rem0o** [comment]
Where exactly are these AIO fans plugged into? Also what mobo?

**Comment by ZephProjects** [comment]
Hi, 

My AIO is the Z53 and the fans are connected to a PWM fan hub that is connected directly to the motherboard. 

I don't connect them to the AIO itself as CAM isn't that great.

My motherboard is the Aorus X570S Pro AX

**Comment by Fr0stX76** [comment]
Gigabyte motherboards of this chipset have a controller issue with LHM. Have you tried enabling "InpOut" under settings as suggested here:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/251#issuecomment-1753939335

**Comment by ZephProjects** [comment]
Thanks for getting back again,

I have not done this yet. How can I do this?

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/51b01d36-ddfb-4986-976e-362b0f9e26a5)

**Comment by ZephProjects** [comment]
Just enabled that, running assisted setup again just for proper pairing.

will get back to you soon.

**Comment by ZephProjects** [comment]
Just finished running assisted setup,

still unable to control all the fans by the seems of it.

**Comment by ZephProjects** [comment]
Hey guys, just wanted to ask a question regarding my situation.

By any chance, could the fan header be the problem as to why I'm unable to control my fans? 

I switched over to a PWM fan hub from Arctic. I have 2 PWM hubs with majority of my fans connected to one hub and 3 of my fans connected to another. 

After switching, I can only control the 3 fans connected to the second hub. 

Would switching fan headers be a possible solution?

**Comment by ionGL** [comment]
It could be a motherboard header that can't be controlled.

Here is how you find out your problem. Disconnect all fans, nothing will burn for a few minutes of idle testing (just leave the pump running,  i think it takes power from a sata power connector). Then connect only one fan to each fan connector, open Fan Control and see if you are able to control it. If you do this, you will know what fan headers you can control for sure. Write them down in a .txt or on a paper to know in the future.

Then you take just one hub and connect it to a known working mobo fan header. If it's all good, you disconnect it and try the 2nd fan hub.

Come back with the results.

**Comment by Rem0o** [comment]
@ZephProjects  Update to V185 for the exception you showed. It shouldn't happen anymore.

**Comment by ZephProjects** [comment]
Hey guys, sorry for getting back to you a week late. I switched fan headers and it seems to work perfectly.

Really sorry for wasting your time with a simple fix.

Thanks again.
