### ISSUE TITLE
GPU Fan Function Broke

### ISSUE THREAD

**Issue by Comprande** [Rem0o/FanControl.Releases#2397]
Unfortunately this update v185 broke Strix 3090 fan curve proper functionality. Although, the V184 had other issues, but Strix 3090 operation worked flawlessly, after custom curve fans would stay at their min RPM (641 RPM-644 RPM)

After this update operation of fans became hit and miss, more miss. I have tried # of times, deleted custom curve, created new one, but still fans would spin to around 680rpm then would stop to 0 then ON and Off again.

Update:

I know this that the issue starts upon including "Motherboard" with or without "Embedded EC sensor"  in sensor detection. 

Hopefully this is in any of help 

Thank you 

<img width="1599" alt="Untitled" src="https://github.com/Rem0o/FanControl.Releases/assets/163705740/cf63e510-9780-4fb0-ac4b-4c0e3c86453c">
<img width="1822" alt="Untitled1" src="https://github.com/Rem0o/FanControl.Releases/assets/163705740/32e50973-084e-4053-a628-7a91b9605cdf">

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/3a5e4560-e98a-47b4-b88f-30e884648341)
Lookup the start and stop% of your GPU controls.

**Comment by Comprande** [comment]
Has this been changed from prior version because this worked perfectly without me even touching  in V183.
Thank you
