### ISSUE TITLE
Speed ​​indicator overlay

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [Rem0o/FanControl.Releases#2399]
The speed indicator is superimposed on the spoiler (^).
![изображение](https://github.com/Rem0o/FanControl.Releases/assets/38873082/ed753ffa-aaec-45c0-83b2-22613335df75)

Version: 185 (net 4.8)

**Comment by Rem0o** [comment]
Damn, didn't catch that one. Migrated to https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit 5.0 and taught I checked over everything, but I missed that one.
Thanks, will fix.

**Comment by Rem0o** [comment]
Fixed in V186
