### ISSUE TITLE
Compatibility issue with Arctic Mono Plus, Afterburner, and FC

### ISSUE THREAD

**Issue by realsmoky** [Rem0o/FanControl.Releases#240]
After installing an Arctic Mono Plus with a normal mini-4-pin to the GPU, I am having a slight issue where on startup, the fans go up to 100 percent and stay there. I THINK there is some compatibility issue between FC and Afterburner and maybe the card itself. I can work around the problem sometimes by manually setting the card to 100 percent in Afterburner and then FC seems to take control of it. Sometimes I can solve it in the same way by using nVidia Inspector. Somehow, setting the card to 100 percent manually makes it so that FC takes control of it afterward. Any ideas why this might be happening? 

Edit: further investigation has shown that this has something to do with the minimum fan speed of the Arctic cooler. If it drops to low, the card (?) panics and pushes it to 100 percent. It gets solved once I manually put the card to 100 percent via nVidia Inspector, then FC takes over on its own.

Also, it was shown that it only happens after I wake up my PC from sleep - on startup after a shutdown, it works fine and FC takes over right away, but after waking from sleep, the fan goes bananas until the workaround is applied.

Edit 2: Even further investigation has shown that my thought that it only happens on wakeups from sleep was wrong - it also does happen when the PC boots from a shut down.

**Comment by Rem0o** [comment]
AfterBurner fan control will interfere with FanControl. You got to deactivate 
![image](https://user-images.githubusercontent.com/14118956/119396629-1a305b80-bca3-11eb-8eab-f26b6c6cb696.png)

**Comment by realsmoky** [comment]
> AfterBurner fan control will interfere with FanControl. You got to deactivate
> ![image](https://user-images.githubusercontent.com/14118956/119396629-1a305b80-bca3-11eb-8eab-f26b6c6cb696.png)

Hi!

Thanks for the suggestion, but I think the issue remains. Even after disabling user defined software controls, the Arctic cooler goes crazy.

I think it is caused by the fact that all the fans turn off for a second or two when FC launches. During that time, it seems the card gets afraid because the fan is at 0 percent and pushes it to 100 percent. This remains until I use some software to "nudge" the card and tell it to go at 100 or at 80 percent, and when it notices that the fan actually works, it then lets FC choose the fan curve.

**Comment by realsmoky** [comment]
After further experimentation, I have found the workaround that works for me.

Disabling user defined software fan control in Afterburner is important, but at the same time, in Afterburner, the fan setting needs to be set at 100 percent and be applied automatically. Only that combination makes the card be controlled by FC again, at least in my case.

Thanks for the tip!
