### ISSUE TITLE
An exception occured during assisted setup

### ISSUE THREAD

**Issue by No-good-deed-goes-unpunished** [Rem0o/FanControl.Releases#2405]
**Describe the bug**
Upgraded from fan Control v173 to v185 with Corsairlink.dll v151
GUI shows "No calibration" and "No speed sensor" status for all controls.
Perform assissted setup
Some sensors not detected for various corsair devices (H115 Cooler, HX850i PSU)
One motherboard connected fan ranges from -32000 to +32000 RPM
Performs stop/start tests and shortly thereafter throws an exception

**Is there a log.txt file next to FanControl.exe with recent date entries?**
(https://pastebin.com/92x9Afqt)

**Relevant hardware specs and setup**
Desktop, Windows 10 21H2 19044-3570
Corsair HX850i PSU
Corsair H115PRORBG 280mm cooler
I9-10940X CPU on X299 XPower Gaming AC motherboard. Not overclocked.
RTX 2070S GPU
32GB DDR4-3600 16-16-16 RAM running at 3733.
Fan control is installed on Samsung 970 Evo Plus 2TB SSD

**Comment by Rem0o** [comment]
V186 should handle this better.
