### ISSUE TITLE
Linux version possible?

### ISSUE THREAD

**Issue by j4r3kb** [Rem0o/FanControl.Releases#241]
as in title.

**Comment by LiverBlow** [comment]
This would be awesome, please consider a linux version !

**Comment by Rem0o** [comment]
Most of the backend is https://github.com/LibreHardwareMonitor/LibreHardwareMonitor, which does not work in Linux.

**Comment by matthewstrasiotto** [comment]
> Most of the backend is https://github.com/LibreHardwareMonitor/LibreHardwareMonitor, which does not work in Linux.

I just had a look at the LibreHardwareMonitor issues, etc- It looks like linux is less supported, but still works
