### ISSUE TITLE
LibreHardwareMonitor could not initialize or has no sensors

### ISSUE THREAD

**Issue by CRAWLER-V** [Rem0o/FanControl.Releases#2417]
Hello, i've alreaty unpin all sensors, but continue to get this popup error every startup:
LibreHardwareMonitor could not initialize or has no sensors

![Immagine 2024-03-27 161709](https://github.com/Rem0o/FanControl.Releases/assets/62466956/16f0857d-c0ed-4a11-98b0-03ba33fa9f7a)
![Im
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/14775434/log_1.txt)
magine 2024-03-27 161731](https://github.com/Rem0o/FanControl.Releases/assets/62466956/1b823468-29be-4106-93dd-2da8bf4592c1)
![Immagine 2024-03-27 161742](https://github.com/Rem0o/FanControl.Releases/assets/62466956/091ff680-6807-40be-855f-677035955841)

[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/14775445/log_1.txt)

Hrdware:
I7 14700F
 Gigabyte b760m ds3h ax
Nvidia RTX 4080 super

**Comment by Rem0o** [comment]
Untick GPU?

**Comment by CRAWLER-V** [comment]
mm... unchecking GPU too, the error sems not coming up any more... but what mean this?
the gpu control work anyway in this mode?
good to know. But strange that happen that errro...

**Comment by Rem0o** [comment]
NvApiWrapper overrides the GPU section of LHM, leaving it empty but with the GPU section still "ticked".  It's a very narrow corner case.
