### ISSUE TITLE
Exit button not working (v79 - Windows)

### ISSUE THREAD

**Issue by FranzDeschler** [Rem0o/FanControl.Releases#242]
Sometimes, the exit button does not work in Windows so it´s not possible to close the window.
After pressing "save configuration" the button works and the window can be closed.
There is no error in the logs.

**Comment by Rem0o** [comment]
You gotta be a bit more specific, as a way to reproduce the issue.

**Comment by FranzDeschler** [comment]
Unfortunately I cannot really reproduce it. The behaviour occured right after the update.
If I can figure out how to reproduce it, I will write again.
