### ISSUE TITLE
Cant Control Lian Li Fan

### ISSUE THREAD

**Issue by marcmaster2009** [Rem0o/FanControl.Releases#2420]
One Channel from the Lian Li Controller cant be controlled by the Software. (Ch3)
It's changing from 900-1300 RPM with a 0 Percent setting
![Bild_2024-03-30_013103422](https://github.com/Rem0o/FanControl.Releases/assets/17489176/cee9841d-2836-49e6-a5de-32d65415d3c0)

**Comment by Rem0o** [comment]
That's from the plugin.  You should transfer your issue to the plugin's repo.

**Comment by Teku-Guy** [comment]
I also have this issues seems that the developer has abandon the repo. I notice this issue appeared with the new update sometimes it would work if I re calibrated. But now its stuck to a custom flat curve of 100% I have set. none of my other fan curves are working.

**Comment by marcmaster2009** [comment]
> One Channel from the Lian Li Controller cant be controlled by the Software. (Ch3)
> It's changing from 900-1300 RPM with a 0 Percent setting

Thanks for the help, found the Solution here: https://github.com/EightB1ts/FanControl.LianLi/issues/19
