### ISSUE TITLE
GPU fan starts at 100%.

### ISSUE THREAD

**Issue by Crowley007** [Rem0o/FanControl.Releases#2421]
**Describe the bug**

With the latest fan calibration feature, my GPU fan speeds shoot to 100% when starting up the GPU fan, and I can't find any way to control this. It worked fine before this calibration update. I have the fan set to start at 30% fan speed at 55c. Now when the fan should start at 30%, it shoots to 100% for a second and quickly ramps down to desired 30%. 

I have disabled the GPU fan control in "Fan Control" for now, and use MSI afterburner for GPU fans, no such problems with it.

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

Asus RTX 4080.

**Comment by ionGL** [comment]
Unfold the GPU fan control cards and look at the start %. It's probably too high. Set it to 30%.

**Comment by ionGL** [comment]
Just set it to 31% and see what happens.

**Comment by Rem0o** [comment]
Nvidia gpus have a built-in feature where if they were 0 rpm for a while, next time they start they will kick in max RPM to remove dust or something.   Mine does the same.   0 RPM operation is always finicky.

**Comment by Crowley007** [comment]
Mine has never done that and does not do that now. But when I set the start to 31% the problem seems to go away so thanks for that tip [ionGL].

It could be related to a minimum 30% rpm thing. When there is load on the GPU the fans start before a curve requests 30%. Fan Control shows this as an external control. Fan control only gains control after a curve requests over 30%. When the start is too low, the 100% thing happens when "Fan Control" gets control.

MSI Afterburner seems to have a feature to deal with this:

<img width="306" alt="afterburner" src="https://github.com/Rem0o/FanControl.Releases/assets/23026322/48b37b3e-e526-4a06-9975-0c664cdecd49">

Pethaps something to look into?

**Comment by ionGL** [comment]
1-29% is a "no go" zone for nvidia cards. Best case scenario the fan doesn't move, but sometimes you get this 100% jump for a few moments.

There is also this behaviour: Once the fan is spinning, let's say at 30%, if you hold the reporting RPM fans with your finger, it senses that it lost RPM and sets the pwm to 100%. When you release the fan, you will hear the it at 100% for a moment, and once it detects RPM, it instantly calms down to the % it was previously.

The "override zero fan speed with hardware curve" option exists in Fan Control. Open the sources card and it's there. Hold the mouse over its ? to get an explanation on what it does.

If you can set 0% at any temperature, you should keep that option **disabled** and avoid 1-29% points on the curve and have the start % at 30.


Here is how argus monitor deals with this. The continuous mode value will set a min %, anything lower that it, it's 0%. It's somewhat like the stop % in Fan control.
StartUp mode is more explicit. If the fan is stopped and a curve requests a non 0% value, the minimum control value will be applied for whatever seconds you select. 
This is our start % in Fan Control, without the "time to apply value" option.

![argusexample](https://github.com/Rem0o/FanControl.Releases/assets/80151979/5652e4f5-0489-4e65-bfb1-361cb267226c)

**Comment by Crowley007** [comment]
Yeah, it works ok now, no more ramp up to 100%. The 30% automatic load rpm is not a problem and fan control works as expected over 30%.

**Comment by Crowley007** [comment]
Rising the start rpm to 31% solves this.
