### ISSUE TITLE
Fan stop - GPU

### ISSUE THREAD

**Issue by BrunoZP** [Rem0o/FanControl.Releases#2426]
**Describe the bug**
Fan stop feature cannot enter in action due to the curve defined even if it's below the threashold.

**Relevant hardware specs and setup**
GPU: RTX 3090 Galax

On this specific card the minimu rpm of the fan is 1400rpm, so even if I set the fan curve to 25% it keeps at 1400 rpm, making it impossible to the fan stop featue of the manufacturer activate.
The solution is to have a minimum threashold or a minimum percentage set at the fan control card, to when it reaches that level tehe fan control application will stop to control the fans and let the card do it by itself.

So in my case for example, I set the curve to start acting at 40c with 30%, below that I set to 0% at the fan curve, when it's there (0% at the fan curve it should stop controlling and let the card do it's thing.)

Or it can be set by temperature also, if it's above the threashold it activate the fan control.

I tried setting everything and couldn't make that (fan stop) work automatically.

**Comment by ionGL** [comment]
Settings - Sensors - Edit sources - hold the mouse over the ? next to Nvidia 0% hardware curve override. 
Read that, enable the option and set a curve around your card's default zero rpm mode temp.

**Comment by BrunoZP** [comment]
Hi, Thanks.
Just tried that, it keeps on 30%, if I disable the control it goes to 0.
I set the fan curve to start at 40c and with 35% of the rpm, but it still locks to 30% is this the right setting?
![image](https://github.com/Rem0o/FanControl.Releases/assets/7763076/c5ed615b-49c7-43e1-99bc-99867c1a5b96)

**Comment by BrunoZP** [comment]
Got it working. For some reason the settings was not getting saved. I erased the .json file, restarted the aplication and set up all over again.
