### ISSUE TITLE
When resuming from Sleep (S4/S5) FanControl is not open anymore.

### ISSUE THREAD

**Issue by ovflowd** [Rem0o/FanControl.Releases#2429]
**Describe the bug**

When I resumed my computer from sleep, FanControl was simply not there (process closed, app not running). I need to open it again (manually). I don't see it crashing or closing; it's just not there. (I've checked Task Manager and such)

**Is there a log.txt file next to FanControl.exe with recent date entries?**

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/14851734/log.txt)

**Relevant hardware specs and setup**

Windows 11 Pro (22H2, 22621.3374) (OS)
Ryzen 7 7800x3D (CPU)
Radeon RX 7900XTX (GPU)
ASUS X670e Crosshair Hero (Motherboard)

**Comment by Rem0o** [comment]
ADLX plugin right? There has been a number of report where the latest version of adrenaline/ADLX causes crashes with the plugin.

**Comment by ovflowd** [comment]
> ADLX plugin right? There has been a number of report where the latest version of adrenaline/ADLX causes crashes with the plugin.

Hmm, should the crashes be included in the logs? Didn't notice any crash. Does Windows Event Viewer could have any information? And yes, using ADLX!

**Comment by bagusnl** [comment]
I can confirm the bug is happening on my system as well after an S3 sleep (S4/S5 sleep is not available for me).

System:
R7 5700x
Radeon RX 6600
Windows 11 23H2

Full dump file:
https://www.mediafire.com/file/rvti1rlo2w148g6/FanControl.exe_240423_012304.7z/file

**Comment by bagusnl** [comment]
Update: as of v 188 and ADLX v 0.2a with driver 24.4.1, crashing after S3 sleep not happening anymore

**Comment by ovflowd** [comment]
I can ack the issue is solved!
