### ISSUE TITLE
Custom Sensor - Temperature Offset

### ISSUE THREAD

**Issue by hpram99** [Rem0o/FanControl.Releases#243]
Devices have various temperature ranges based off their manufacturing limits.

The "Mix" Custom Sensor is very powerful, being able to offset by +/- Degrees or Percent would help tremendously for liquid cooling loops that combine CPU/GPU or fans that cool more than one devices.

e.g.
Sensor a: GPU Max 90C OFFSET-20
Sensor b: CPU Max 76C
Mix Sensor Max = 70C/76C respectively

**Comment by Rem0o** [comment]
Why don't you just average then?

**Comment by hpram99** [comment]
Averaging doesn't help the fan curve when there's a spread in design limits.  I will hit thermal throttling using the average function.

Some apps are GPU bound.
Some apps are CPU bound.
ASRock told me their X570 chipset supports 145C, yet my CPU supports 78C
Sometimes my NVMe drive is dumb and hotter than you can imagine, so I need more case airflow, but in liquid cooling Case fan = Radiator fan.

**Comment by Rem0o** [comment]
You could then make a curve for each GPU and CPU, then mix the two curves with a Max function. That's the way to achieve that effect right now.

**Comment by hpram99** [comment]
This is actually a better solution than I expected.
Thanks!
