### ISSUE TITLE
Bug - fan curves disconnect from speed settings

### ISSUE THREAD

**Issue by JMUDoc** [Rem0o/FanControl.Releases#2436]
When making adjustments to fan curves in rpm mode, the fan speed sometimes disconnect from the curve and default to 40% with a ?:

![Screenshot (182)](https://github.com/Rem0o/FanControl.Releases/assets/59938390/50416729-3a51-485a-a655-d49b598d7aca)

When the calibration link is clicked and OK'd out of, the fan speed is fixed.

**Comment by Oooch** [comment]
Seems every other update this breaks entirely and I have to set up all my fan curves again

**Comment by Rem0o** [comment]
You can check (!) Force apply. However this is a workaround, as "?" indicates indicates the current fan control value was not set by FanControl, and something else set that value.
