### ISSUE TITLE
Detecting only CPU Package temperature sensor, and not Cores Max

### ISSUE THREAD

**Issue by ficosime** [Rem0o/FanControl.Releases#2438]
Hello, just downloaded and started setting everything up.

However, I see YouTube videos I followed have a CPU "Core Max" sensor in the dropdown when creating a curve, but on my end (v186) I only see "Core" which is Package temperature, and CCD1. 

The sensor should be there because in HWMonitor I can see Cores Max temperature and temperature of each core. Now I can also go with setting up a curve with Package, but the package is inconsistent, sometimes +10° from the actual Core Max temperature, sometimes even 18° difference.
![image](https://github.com/Rem0o/FanControl.Releases/assets/166204905/ca73c67c-8dee-4fbc-980d-9b9a05431e8e)
![image](https://github.com/Rem0o/FanControl.Releases/assets/166204905/38920fca-52b9-4a78-8651-6f90d93af4f2)

PC Specs:
CPU: Ryzen 7 7800X3D (4.2-5.0 GHz)
CPU Cooler: Thermalright Frost Spirit 140
MBO: Asrock B650 PG Lighting, AM5
RAM: 2x Corsair Vengeance 16 GB (32GB) DDR5, 6000 MHz, CL30
GPU: RTX 4070 Ti Super ASUS TUF GAMING
CASE: Be Quite Shadow Base 800 FX, 4x140mm vent.
OS: Win 11 Pro

Thanks!

**Comment by Rem0o** [comment]
Closing, see : https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

General tip:
You can get good results with the Core (Tctl/tdie) .  It'll be different that the core temp, but there's no absolute here. Either/or can be a good reference for cooling. Core temp isn't inherently better, you just need to adjust your curve based on that temp probe's effective range.
