### ISSUE TITLE
PSU Corsair fan control

### ISSUE THREAD

**Issue by sqssman** [Rem0o/FanControl.Releases#244]
Hello.
Do you plan to support fan control for Corsair power supplies? 
As well as utilities corsair ICUE?

**Comment by Rem0o** [comment]
If you can hint me a way to do it, then I'll consider.

**Comment by Cubox** [comment]
This needs to be provided by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor at least to be implemented.
Can you access those controls using this software?

**Comment by Jonw82** [comment]
It would be great if you could do this.  I payed for other software, but would consider switching to yours.  This is the main thing holding me back.  The support for Corsair devices.

Either way, I commend you on your project.. looks great so far.

**Comment by Rem0o** [comment]
Just saying: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/458

👀
