### ISSUE TITLE
[Feature request] Fan Schedules

### ISSUE THREAD

**Issue by Awamori112** [Rem0o/FanControl.Releases#2441]
Option to have curves or triggers be set up as schedules 

Use case: 
I have a some fans that have pretty high RPMs, around the 2k RPM - 5k RPM range (dont really care about noise cause they're pretty quiet surprisingly). I leave my computer on at night to process pics and videos and sometimes like to have my fans at high blast but would like to set a schedule to ramp them down to a good speed where it's decently quiet and respectful to my family when they sleep.

Possible solutions: 
- hook into windows time to trigger
- hook into BIOS time to trigger
- something similar to temp triggers

**Comment by Rem0o** [comment]
Create 2 configurations. 1 silent, name it "silent", one normal, name it "normal" or whatever.

Create tasks in Task Scheduler in windows.

Put the right time you want.
Action:  FanControl.exe -c silent.json
Folder: [Point to the fan control folder]

Then create an other tasks to put it back to normal.
Action:  FanControl.exe -c normal.json
Folder: [Point to the fan control folder]
