### ISSUE TITLE
X670E Godlike Multiple Pumps Not Detected & Issues with HWInfo

### ISSUE THREAD

**Issue by MISTERSTEEZE** [Rem0o/FanControl.Releases#2442]
My motherboard (X670E Godlike) has 2x Fan Pump headers, and 6x fan headers, only one pump is detected in FanControl. All other fans are detected as long as HWInfo isn't open. If HWInfo is open, then none of the fans are detected. I have attempted to use the HWInfo plugin to import the sensor data. It does bring the sensor/speed data over, but won't allow me to control them as the software doesn't recognize them as controllable. Hoping to get this fixed, as the MSI Center fan control is absolutely terrible.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
