### ISSUE TITLE
storage sensor responds too slow(40s), and only this sensor has the issue.

### ISSUE THREAD

**Issue by jkwtbmyz** [Rem0o/FanControl.Releases#2447]
When I run diskmark to warm my m.2, m.2 temp sensors from Aida64 and HWinfo change immediately, while Fan control's m.2 sensor responds too slow for about 40s after temperature changes. 

Fan control's other sensors like CPU's and GPU's work fine.

![image](https://github.com/Rem0o/FanControl.Releases/assets/17421620/986f3b00-77b7-47d8-a1b2-82a42fc7ea1c)
![image](https://github.com/Rem0o/FanControl.Releases/assets/17421620/40c05158-96b2-49b7-81b7-a8d80557872b)

left is hwinfo, mid is fanctrl, right is aida64
![image](https://github.com/Rem0o/FanControl.Releases/assets/17421620/ff61b078-b2a9-42cc-ac43-e402aeab3a08)

My device:
![image](https://github.com/Rem0o/FanControl.Releases/assets/17421620/423b8293-b741-4b2a-93a8-ebf3060344fd)

BTW, even though I check the memory sensors in FanCtrl, they don't show up here. Aida64 can sense them so I figure it's not the memorie's problem.
![image](https://github.com/Rem0o/FanControl.Releases/assets/17421620/5b098f5c-1c4f-4f6a-8cc1-25ad22c871fa)

Thank you:)

**Comment by Rem0o** [comment]
That's odd, could be numerous things.  Running multiple programs at the same time fetching the same information might also cause some locking issues. 

You would have to look into https://github.com/LibreHardwareMonitor/LibreHardwareMonitor and see where it hangs.
