### ISSUE TITLE
Control Thermaltake fans that use a controller?

### ISSUE THREAD

**Issue by mhomorody** [Rem0o/FanControl.Releases#2452]
I have these fans https://www.thermaltake.com/pure-plus-12-rgb-radiator-fan-tt-premium-edition-3-fan-pack.html and I've previously used this TTController software since the official software is bad https://github.com/MoshiMoshi0/TTController but I've never really been happy with the setup. I found Fan Control so gave that a try, but it doesn't look like these TT fans with their own physical controller can be used? I see 3 system fans in the tool that it said it couldn't control. Is there anyway to get them to work?

**Comment by mhomorody** [comment]
Oops this was supposed to go in Discussions.

**Comment by Rem0o** [comment]
https://github.com/fu-raz/FanControlThermaltake

**Comment by mhomorody** [comment]
Yep thanks I found this after I accidentally made this issue.
