### ISSUE TITLE
Windows Defender blocks FanControl.sys

### ISSUE THREAD

**Issue by ShishirGupta** [Rem0o/FanControl.Releases#2458]
![image](https://github.com/Rem0o/FanControl.Releases/assets/7519542/2ccca1fe-409b-42af-ba6f-05dd77c1e20e)

Windows 11 PRO, connected to work account. This has been happening since few months. Had earlier escaped the folder through Defender but that is not allowed anymore by the work account settings. Why is this flagged?

This happens on both portable and installed service alike.

**Comment by Rem0o** [comment]
That's not a stock policy on windows, otherwise the app wouldn't work anywhere.  That's your work domain policies.   FanControl uses WinRing0 under the hood.  You can look it up, it's an old driver.

https://github.com/Rem0o/FanControl.Releases/issues/1521
