### ISSUE TITLE
Dumb question: does it need to run always

### ISSUE THREAD

**Issue by AtmanActive** [Rem0o/FanControl.Releases#246]
I'm sorry if I am asking dumb questions here.

Does FanControl need to run at all times to make it work as expected or is it enough to run it once and it will reprogram the motherboard's fan controller to work in a desired way?
In other words, is FanControl actively driving my fans or is motherboard's controller driving the fans?

Thanks.

**Comment by Rem0o** [comment]
It’s an active driver.
