### ISSUE TITLE
RPM Calibration Issue

### ISSUE THREAD

**Issue by solodolo-42** [Rem0o/FanControl.Releases#2460]
### [EVGA RTX 3080]
**Whenever I first boot up my desktop, percentage starts at zero and also rpm starts at zero in the control section of the software.**

<img src="https://live.staticflickr.com/65535/53656602806_0539d0bccc_w.jpg" width="400" height="368" alt="fan-control-9"/><br />

<img src="https://live.staticflickr.com/65535/53656908754_9310f64d72_b.jpg" width="640" height="228" alt="fan-control-1"/><br />

<img src="https://live.staticflickr.com/65535/53657020235_e672ee2f11_z.jpg" width="640" height="407" alt="fan-control-2"/><br />

<img src="https://live.staticflickr.com/65535/53657020230_e45aae127e_z.jpg" width="640" height="499" alt="fan-control-3"/><br />

<img src="https://live.staticflickr.com/65535/53656776343_07056ebaea_z.jpg" width="640" height="568" alt="fan-control-4"/><br />

<img src="https://live.staticflickr.com/65535/53656908749_a49d4f4318_z.jpg" width="640" height="433" alt="fan-control-5"/><br />

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------
### [EVGA RTX 3080]
**Then after about 10 min of the desktop running.**

<img src="https://live.staticflickr.com/65535/53655681627_0220e3de42_z.jpg" width="400" height="360" alt="fan-control-7"/><br/>

<img src="https://live.staticflickr.com/65535/53655730252_6a98f8d54a.jpg" width="640" height="409" alt="fan-control-8"/><br />

<img src="https://live.staticflickr.com/65535/53656776338_e95ddc2c88_z.jpg" width="640" height="409" alt="fan-control-6"/>

**Comment by Rem0o** [comment]
Remove both the start and stop % (set them to 0) in your control cards.

**Comment by solodolo-42** [comment]
Percentage and RPM don't match the calibration. Is the RPM just so post to be in range of the calibration set?

<img src="https://live.staticflickr.com/65535/53659233356_d668134a85.jpg" width="500" height="311" alt="Screenshot 2024-04-16 202214"/>

<img src="https://live.staticflickr.com/65535/53659233361_c3641a96fd.jpg" width="500" height="390" alt="Screenshot 2024-04-16 202250"/>

**Comment by Rem0o** [comment]
Yes it is, that's the whole point.

**Comment by solodolo-42** [comment]
Appreciate your help! Thanks
