### ISSUE TITLE
Controlfan cant load saved configuration when booting

### ISSUE THREAD

**Issue by hbugra** [Rem0o/FanControl.Releases#2461]
After the OS is started, the saved configuration of 'fancoltrol' is not loaded and the fans always have to be identified by me by clicking on the 'identify fans' button in the application. Is there a solution to this?

**Comment by Rem0o** [comment]
Uncheck and recheck start with windows. Also make sure to save your configuration with a proper name.

**Comment by hbugra** [comment]
unfortunatly, problem still persist ... I am sharing the screenshots with you, doing something wrong?

![Ekran görüntüsü 2024-04-17 020109](https://github.com/Rem0o/FanControl.Releases/assets/132520060/cc385d2d-60a5-40ac-a07f-3522fb07386f)
![Ekran görüntüsü 2024-04-17 020136](https://github.com/Rem0o/FanControl.Releases/assets/132520060/508fa1d7-7bb0-4505-949d-4b5efb7d0e2c)

**Comment by Rem0o** [comment]
Go into task scheduler, exit fan control, and run the fan control task manually.

**Comment by hbugra** [comment]
you mean task manager? (if not how can i exit fan control in scheduler?)

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/06250949-297a-4ff3-b1b7-8b98f28ab748)
