### ISSUE TITLE
Auto Fan Curve not working as intended

### ISSUE THREAD

**Issue by PhilippM7** [Rem0o/FanControl.Releases#2462]
![image](https://github.com/Rem0o/FanControl.Releases/assets/97338141/1e469302-4751-4dc0-ae22-5e5b3d01bd37)

In this Image can be seen, that the Auto fan curve is not working as intended. Restartet Fan Control already and then it works for some time until it does not. Also, changing the values makes it work for a short amount of time until it stops working.

**Comment by Rem0o** [comment]
How is it not working? Temp is under the load, fan speed is over minimum.

**Comment by PhilippM7** [comment]
Ok, i think i might not be getting what auto does but its fine. How can it be of use if it is just a trigger? It is bassically off until it is above temperature and 100%.

**Comment by Rem0o** [comment]
It's "off" until you get into a "load" scenario, so getting to load temp, then it will kick in.  In any case, if you start questioning it, you are not the target audience for it, and you should just use a graph.
