### ISSUE TITLE
AMD GPU not detecting fans when they are not spinning 

### ISSUE THREAD

**Issue by GoogleCheese** [Rem0o/FanControl.Releases#2463]
AMD GPU isnt detected with as having a speed sensor when the program started the auto calibration 
but somewhere during the calibration the GPU fans turned on and it started showing the fan speed, just not in the calibration.

The GPU i have is the AMD Radeon RX600XT

I think (but i have no real idea) this happens because the GPU fans dont turn on unless the GPU gets above a certain temperature 

![image](https://github.com/Rem0o/FanControl.Releases/assets/66805826/b21f7699-9fb0-4a9d-b403-525787b993a9)

**Comment by Rem0o** [comment]
That's because the GPU control up top had no influence on the RPM value of that sensor, hence the missed pairing. 

See FAQ: https://github.com/Rem0o/FanControl.Releases#faq
