### ISSUE TITLE
Can't detect any fans or Alienware M15 R3

### ISSUE THREAD

**Issue by lhg1992** [Rem0o/FanControl.Releases#2467]
Just as the title show.  The Fan Control software can't find the fans of the Alienware M15 R3 using windows 10. It can only detect the CPU temperature.
![image](https://github.com/Rem0o/FanControl.Releases/assets/29236300/99d4db29-4393-474a-8c65-176f7de214da)

The official alienware fan control (AWCC) works normally, but its advanced "smooth line" mode is so stupid. The stupid AWCC developers fixed two points at temperature 0 and 100° with a total number of 3 points available in the control, which means two points at the ends can only move vertically. Therefore, you can only build stupid control patterns as follows:
![Curve](https://github.com/Rem0o/FanControl.Releases/assets/29236300/266d4608-ccdb-4e1e-8e4c-ebb472da7df7)
![Curve2](https://github.com/Rem0o/FanControl.Releases/assets/29236300/0ecfc3b6-c510-4ff5-878b-034f17279aa2)

Based on the solution of fan control of alienware on Linux, it needs the "i8kutils" and "lm_sensors" packages to get the fan sensor data. Hope this can help you improve the Fan Control software and solve this issue.
https://gist.github.com/codexetreme/e2d0fa3049944d2c49381a7fd44b1cba/revisions

**Comment by Rem0o** [comment]
This is a hardware support request. 

See https://github.com/Rem0o/FanControl.Releases?tab=readme-ov-file#issues-and-hardware-compatibility

You may try this though: https://github.com/Rem0o/FanControl.DellPlugin
