### ISSUE TITLE
Auto stops working in certain games. 

### ISSUE THREAD

**Issue by charobi** [Rem0o/FanControl.Releases#2468]
My auto fan curve stops working in certain games such as R6 and The Finals. My temperature is being tracked but the fan speed keeps lowering until it reaches the min fan speed. It continues to stay there until I manually change the step which will cause the percentage to bump up again. However, the percentage goes back down once I tab back into the game.  This happens for my CPU auto curve in R6 and my GPU auto curve in The Finals. Anyone know what's causing this issue or is auto supposed to do that?

![image](https://github.com/Rem0o/FanControl.Releases/assets/156112758/eb257934-c492-49b0-97d9-ae06c255389a)

**Comment by Rem0o** [comment]
Auto is meant to give you the lowest possible fan speed while the temp stays under load.  In your case you set 80, so while the temp stays under 80, the fan curve will give you the lowest possible fan speed, here 20 because you are at 67, which is comfortably under 80.

**Comment by charobi** [comment]
> Auto is meant to give you the lowest possible fan speed while the temp stays under load. In your case you set 80, so while the temp stays under 80, the fan curve will give you the lowest possible fan speed, here 20 because you are at 67, which is comfortably under 80.

Wait so how come when I'm not in a game the fan percentage goes above 20% even when the temps are below 80? Does this only occur when you're in a game? Also is there some other setting that makes it so that the fan speed adjusts dynamically based on the max and min temps without being confined to the to the min temp when the temp is under the load temp? I know I could probably just make a graph but I'm just wondering if there's something like auto. Thank you for the help!
![image](https://github.com/Rem0o/FanControl.Releases/assets/156112758/ac17b1c2-a5a5-4b50-9fd6-2448afece107)

**Comment by charobi** [comment]
> Auto is meant to give you the lowest possible fan speed while the temp stays under load. In your case you set 80, so while the temp stays under 80, the fan curve will give you the lowest possible fan speed, here 20 because you are at 67, which is comfortably under 80.

I think I understand how it works now, thank you for the help!
