### ISSUE TITLE
Does not detect .sensor files in v79

### ISSUE THREAD

**Issue by johnwicksm** [Rem0o/FanControl.Releases#247]
Doesn't detect .sensor files placed in either the root directory or the "FileSensor" directory within program root. Clicking in the temperature sources dropdown doesn't list any of the .sensor files. Verified working as expected in v70.

**Comment by Rem0o** [comment]
You have to create a file sensor with the plus sign, and name the file properly.

**Comment by johnwicksm** [comment]
Brilliant! Works swimmingly. Thanks for such a prompt reply :)
