### ISSUE TITLE
FEATURE REQUEST - Is it possible to add detailed temperature detection of the GPU?

### ISSUE THREAD

**Issue by sunyink** [Rem0o/FanControl.Releases#2470]
I use NVDIA graphics card, FC helped me a lot, thank you. I discovered a new scenario and requested a feature enhancement.

I hope that the temperature detection of FC graphics cards can be detailed and divided into: core temperature, Memory Temperature, and Hot Spot, such as what gpuz implements.

I found that a new scenario caused me trouble: I changed the graphics card cooling DIY to use water cooling for the core, and air cooling for the video memory and others. This improves performance but introduces more nuanced issues.

At this time, the graphics card temperature "GPU Temperature" monitored by FC is actually the temperature of the GPU core. Due to different cooling systems, the core temperature value is decoupled from Memory and Hot. The gap between them is really big (a stress test chart is attached. The core is only 51 degrees Celsius, but the Memory temperature reaches 70 degrees Celsius). In fact, it is necessary to monitor the temperature of Memory and Hot. To control the fan speed on the GPU panel, in order to accurately achieve the balance between heat dissipation, energy absorption and noise.
![max01](https://github.com/Rem0o/FanControl.Releases/assets/37411580/667c9820-7443-4c51-ad00-b367b047218d)

**Comment by Rem0o** [comment]
Use the LHM GPU sensor source, untick NVAPIWrapper
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/a1efadce-d086-44ba-987b-42a15b1468d5)

**Comment by sunyink** [comment]
It worked, thank you. However, this combination cannot control the fan connected to the graphics card, which is a fly in the ointment.
