### ISSUE TITLE
Bug - fan calibrates correctly, but does not respond correctly outside of calibration screen

### ISSUE THREAD

**Issue by JMUDoc** [Rem0o/FanControl.Releases#2473]
Plugged a fan into a header on my motherboard and it showed up as "not calibrated" - expected, I have not used that header since the rpm calibration update.

Calibrated the fan at 10% increments and it responded perfectly but, once I closed the calibration window and tried manual control at the home screen, the speed was stuck at 0%.
![Screenshot (190)](https://github.com/Rem0o/FanControl.Releases/assets/59938390/fef7bbaf-cdb2-4291-9ca3-99c9086153c0)

**Comment by Rem0o** [comment]
What's the start and stop% set on that control?

**Comment by JMUDoc** [comment]
Interesting - I ran the (obsoleted) start/stop % detection, and the fan now seems to behave normally.

No idea why this would be...

**Comment by Rem0o** [comment]
As my question, you probably had non sense values set in your start stop fields in the expanded control tile.
