### ISSUE TITLE
Support decimal increments (0.1%+-) for Auto Min/Max Fan Speeds

### ISSUE THREAD

**Issue by raywdude** [Rem0o/FanControl.Releases#2474]
My specific use case: for <= Idle degrees, I want it to be as quiet as possible, and get the fan as slow as possible without turning off. In my case, it is 6.1%. Any lower than that, and it turns off. However, with "Auto" the lowest it can do is 7%.

Right now I'm (poorly) replicating the Auto behavior using "Graph" since it works with setting to 6.5%. Would be great if Auto worked out of the box.

**Comment by Rem0o** [comment]
Didn't notice it was still only integers value.  Will update them to decimal in the next version.

**Comment by Rem0o** [comment]
V188
