### ISSUE TITLE
Latest version of Fan Control freezing up on my PC. V187

### ISSUE THREAD

**Issue by Namtrooper** [Rem0o/FanControl.Releases#2475]
**After latest update patch V187 Fan control just freezing**
![image](https://github.com/Rem0o/FanControl.Releases/assets/21367736/870995fa-3e8e-4e14-8a53-f44e96dee06f)

Updates are rolling out so fast I was wondering how long it would be before an update breaks my Fan control. Seems V187 is the one.
I don't know if any of the following information is relevant. But I'm adding it with the hope something might help troubleshoot the issue.
Motherboard : Gigabyte B550 Aorus Elite V2
Cpu : 5800x3d
Memory : 16GB Corsair 3200Mhz memory (CMK16GX4M2B3200C16)
Front intake on case for cool air : ID-Cooling Frostflow 280 cooling my cpu, replaced original fans with Noctua 140mm's.
Top fan hot air outlet : Alphacool Eiswolf 2 360mm rad with their own fans. Cooling my 6800XT.

All fans plugged into Corsair commander pro. (I believe the problem lies here. I hade to add a plugin for the device in the past. But it seems at some point maybe the Fan control developers integrated the commander pro into fan control because the plugin is no longer available on github and it was working perfectly untill this last update)
I am looking at the dates on the Log.txt files and Log_1.txt files and they are very old.
Not sure if the info is relevant.
Log.txt dated 14 Dec 22
Log_1.txt dated 19 Jan 24
[log_1.txt](https://github.com/Rem0o/FanControl.Releases/files/15128282/log_1.txt)
Cannot upload log.txt because size limit is 25Mb and it's size is 27Mb

Not sure on relevancy. I have two OS's running from the main NVME ssd. Dual boot. Not VMs. 
One is standard W10 pro I run for work.
The second OS is Windows 10 lite for my gaming.
fan control freezing occurs on both OS's.
I have to kill the process in task manager to get it to stop.
Let me know if there is any other relevant information I can help with please.

Thank you.
Werner Lieske.

**Comment by Namtrooper** [comment]
Found this Log called "CommanderPRO.err.log" it has the date 29 March 24.
[CommanderPRO.err.log](https://github.com/Rem0o/FanControl.Releases/files/15128353/CommanderPRO.err.log)

**Comment by Namtrooper** [comment]
Another Update. I ended up completely deleting my Fan control folder. Downloaded the latest version, installed and started.
It at least launches now without freezing. Now I just have to setup everything again. At least it runs. 
Guess it was time for a fresh install.

**Comment by Namtrooper** [comment]
Should a clean install of fan control be able to detect and work with corsair commander pro or do I need to look for a plugin again or has support been completely dropped?
Apologies for a 100 questions.

**Comment by Rem0o** [comment]
I don't know what version of a plugin you got, but there is a well maintained one here: 
https://github.com/EvanMulawski/FanControl.CorsairLink

**Comment by Namtrooper** [comment]
Thank you very much Rem0o. I was about to state it seems the standard fan control installation doesn't seem to detect my commander pro. I appreciate it.

**Comment by Namtrooper** [comment]
I can honestly say. I was about to throw the commander pro in the trash because the Corsair Icue software was hot garbage and nothing worked properly. Your project Fan control is excellent and I don't regret my purchase of the commander pro anymore.
Thank you for taking the time to make this awesome piece of software. Also of course thank you EvanMulawski for the awesome plugin to make my commander pro usable in Fan control of course.
