### ISSUE TITLE
Set RPM instead of percentage

### ISSUE THREAD

**Issue by FireN1337** [Rem0o/FanControl.Releases#2476]
Hi,

at first, thank you for that wonderful software :)

I have the problem that the values in RPM change to the corresponding % each new start of the computer.
For example I´m setting my three different radiators to Rad1=45% Rad2=44% Rad3=46% which is close to 1000 RPM
Next start of the PC, the percentages are saved but the RPM are different for each radiator (one is over 1000RPM, one is almost close to 900RPM etc)

It would be a cool feature to implement an RPM setting (set 1000RPM) and that the software accounts for the changes in %

:)

Greetings

**Comment by Rem0o** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/d1cab408-1ad9-4a78-a71a-ed274a2ab2d3)

**Comment by FireN1337** [comment]
oopsie, I feel dumb now XD
thanks :)

**Comment by FireN1337** [comment]
oopsie, I feel dumb now XD
thanks :)
