### ISSUE TITLE
Fan Control not starting automatically

### ISSUE THREAD

**Issue by AnotherOddity** [Rem0o/FanControl.Releases#2477]
**Describe the bug**
Fan Control is set up to be one of the programs among startup apps, and **is** listed among them and enabled, however it does not appear to launch upon start up.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No.

**Relevant hardware specs and setup**
Windows 10 Pro
Ryzen 7 5800X
32GB DDR4 RAM
Gigabyte X570
Radeon RX580

**Comment by Rem0o** [comment]
> Fan Control is set up to be one of the programs among startup apps

You need to use the built-in method:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/6e6519e3-3837-4267-8b0e-34bb9410a46d)

**Comment by AnotherOddity** [comment]
> > Fan Control is set up to be one of the programs among startup apps
> 
> You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDI3NzMsIm5iZiI6MTcxNDM0MjQ3MywicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDIyMTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZDljMzk0MzVlMDNjYjZhNmNiMGNkYzI0MzlkMjhjN2Q2ZGMxZjA1Y2VmZWFkMDcwMjZjYjIxOGIxM2MzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.we_l-4mAnncAqmeceQABdWiiHw8qBu2G1GvqTTpK3B0)

It's turned on, has been the whole time, and still is. The delay is at 20 seconds, and has been the whole time.

For a fair while FanControl was starting up itself, at some point with one of the more recent updates it stopped doing that. I'm not sure exactly when, but when I noticed that's when I tried fiddling with Windows startup settings.

The in-software option has been turned on this whole time though.
![image](https://github.com/Rem0o/FanControl.Releases/assets/18012978/497cc22c-a078-4a27-be0b-2595421f7a14)

**Comment by Usulyre** [comment]
> > Fan Control is set up to be one of the programs among startup apps
> 
> You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)

Happening here too. Won't startup automatically have to manually turn it on. Using Windows 11 and 
FanControl_187_net_4_8_Installer.exe 

Was working on a previous release can't remember which one though.

**Comment by AnotherOddity** [comment]
> > > Fan Control is set up to be one of the programs among startup apps
> > 
> > 
> > You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)
> 
> Have that option on but won't startup automatically have to manually turn it on. Using Windows 11 and FanControl_187_net_4_8_Installer.exe
> 
> Was working on a previous release can't remember which one though.

What is the delay on your one?

Despite the delay having been 20s for me this whole time (which I think _was_ the default and having previously worked, decided to experiment and just bump it up to 30s. It launched this time. Gonna keep track and see if the issue reappears.

**Comment by Usulyre** [comment]
> > > > Fan Control is set up to be one of the programs among startup apps
> > > 
> > > 
> > > You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)
> > 
> > 
> > Have that option on but won't startup automatically have to manually turn it on. Using Windows 11 and FanControl_187_net_4_8_Installer.exe
> > Was working on a previous release can't remember which one though.
> 
> What is the delay on your one?
> 
> Despite the delay having been 20s for me this whole time (which I think _was_ the default and having previously worked, decided to experiment and just bump it up to 30s. It launched this time. Gonna keep track and see if the issue reappears.

Mine is 30 seconds. I will try to lower it to see if that makes a difference, also there is a newer Fan Control version to try today let's see if that helps at all.

**Comment by AnotherOddity** [comment]
> > > > > Fan Control is set up to be one of the programs among startup apps
> > > > 
> > > > 
> > > > You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)
> > > 
> > > 
> > > Have that option on but won't startup automatically have to manually turn it on. Using Windows 11 and FanControl_187_net_4_8_Installer.exe
> > > Was working on a previous release can't remember which one though.
> > 
> > 
> > What is the delay on your one?
> > Despite the delay having been 20s for me this whole time (which I think _was_ the default and having previously worked, decided to experiment and just bump it up to 30s. It launched this time. Gonna keep track and see if the issue reappears.
> 
> Mine is 30 seconds. I will try to lower it to see if that makes a difference, also there is a newer Fan Control version to try today let's see if that helps at all.

Yeah try lower it to 20s, and if that doesn't change anything, try raise it to 40s or 50s.

Mine was originally working on 20s. Then it broke (hence this issue). Raising it to 30s seems to have fixed it.

@Rem0o - just worth keeping an eye here in the event someone else has this issue, for the actual solution

**Comment by Usulyre** [comment]
> > > > > > Fan Control is set up to be one of the programs among startup apps
> > > > > 
> > > > > 
> > > > > You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)
> > > > 
> > > > 
> > > > Have that option on but won't startup automatically have to manually turn it on. Using Windows 11 and FanControl_187_net_4_8_Installer.exe
> > > > Was working on a previous release can't remember which one though.
> > > 
> > > 
> > > What is the delay on your one?
> > > Despite the delay having been 20s for me this whole time (which I think _was_ the default and having previously worked, decided to experiment and just bump it up to 30s. It launched this time. Gonna keep track and see if the issue reappears.
> > 
> > 
> > Mine is 30 seconds. I will try to lower it to see if that makes a difference, also there is a newer Fan Control version to try today let's see if that helps at all.
> 
> Yeah try lower it to 20s, and if that doesn't change anything, try raise it to 40s or 50s.
> 
> Mine was originally working on 20s. Then it broke (hence this issue). Raising it to 30s seems to have fixed it.
> 
> @Rem0o - just worth keeping an eye here in the event someone else has this issue, for the actual solution

I tried to actually lower it and saved it to my configuration but for some reason it keeps going back to 30s and it still won't start up after OS boot complete

**Comment by AnotherOddity** [comment]
> > > > > > > Fan Control is set up to be one of the programs among startup apps
> > > > > > 
> > > > > > 
> > > > > > You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)
> > > > > 
> > > > > 
> > > > > Have that option on but won't startup automatically have to manually turn it on. Using Windows 11 and FanControl_187_net_4_8_Installer.exe
> > > > > Was working on a previous release can't remember which one though.
> > > > 
> > > > 
> > > > What is the delay on your one?
> > > > Despite the delay having been 20s for me this whole time (which I think _was_ the default and having previously worked, decided to experiment and just bump it up to 30s. It launched this time. Gonna keep track and see if the issue reappears.
> > > 
> > > 
> > > Mine is 30 seconds. I will try to lower it to see if that makes a difference, also there is a newer Fan Control version to try today let's see if that helps at all.
> > 
> > 
> > Yeah try lower it to 20s, and if that doesn't change anything, try raise it to 40s or 50s.
> > Mine was originally working on 20s. Then it broke (hence this issue). Raising it to 30s seems to have fixed it.
> > @Rem0o - just worth keeping an eye here in the event someone else has this issue, for the actual solution
> 
> I tried to actually lower it and saved it to my configuration but for some reason it keeps going back to 30s and it still won't start up after OS boot complete

What about raising it to 40s delay? Does that save successfully and work?

**Comment by Usulyre** [comment]
> > > > > > > > Fan Control is set up to be one of the programs among startup apps
> > > > > > > 
> > > > > > > 
> > > > > > > You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)
> > > > > > 
> > > > > > 
> > > > > > Have that option on but won't startup automatically have to manually turn it on. Using Windows 11 and FanControl_187_net_4_8_Installer.exe
> > > > > > Was working on a previous release can't remember which one though.
> > > > > 
> > > > > 
> > > > > What is the delay on your one?
> > > > > Despite the delay having been 20s for me this whole time (which I think _was_ the default and having previously worked, decided to experiment and just bump it up to 30s. It launched this time. Gonna keep track and see if the issue reappears.
> > > > 
> > > > 
> > > > Mine is 30 seconds. I will try to lower it to see if that makes a difference, also there is a newer Fan Control version to try today let's see if that helps at all.
> > > 
> > > 
> > > Yeah try lower it to 20s, and if that doesn't change anything, try raise it to 40s or 50s.
> > > Mine was originally working on 20s. Then it broke (hence this issue). Raising it to 30s seems to have fixed it.
> > > @Rem0o - just worth keeping an eye here in the event someone else has this issue, for the actual solution
> > 
> > 
> > I tried to actually lower it and saved it to my configuration but for some reason it keeps going back to 30s and it still won't start up after OS boot complete
> 
> What about raising it to 40s delay? Does that save successfully and work?

Still stuck on 30s and still doesn't startup automatically.

**Comment by AnotherOddity** [comment]
> > > > > > > > > Fan Control is set up to be one of the programs among startup apps
> > > > > > > > 
> > > > > > > > 
> > > > > > > > You need to use the built-in method: ![image](https://private-user-images.githubusercontent.com/14118956/326265104-6e6519e3-3837-4267-8b0e-34bb9410a46d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjU1MDYsIm5iZiI6MTcxNDQyNTIwNiwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjUxMDQtNmU2NTE5ZTMtMzgzNy00MjY3LThiMGUtMzRiYjk0MTBhNDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDIxMTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjEzOThhYzI1MjBiZWJkNDZjZmYzZDkzYThlYmIwNjg4MGVjMTI2ZTJiZThmZTcxM2FmZGNjYzdjMWE3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bKu-xfOmeit0j09b9Vvid6G4dQFRSuAhtZp_zCCh58U)
> > > > > > > 
> > > > > > > 
> > > > > > > Have that option on but won't startup automatically have to manually turn it on. Using Windows 11 and FanControl_187_net_4_8_Installer.exe
> > > > > > > Was working on a previous release can't remember which one though.
> > > > > > 
> > > > > > 
> > > > > > What is the delay on your one?
> > > > > > Despite the delay having been 20s for me this whole time (which I think _was_ the default and having previously worked, decided to experiment and just bump it up to 30s. It launched this time. Gonna keep track and see if the issue reappears.
> > > > > 
> > > > > 
> > > > > Mine is 30 seconds. I will try to lower it to see if that makes a difference, also there is a newer Fan Control version to try today let's see if that helps at all.
> > > > 
> > > > 
> > > > Yeah try lower it to 20s, and if that doesn't change anything, try raise it to 40s or 50s.
> > > > Mine was originally working on 20s. Then it broke (hence this issue). Raising it to 30s seems to have fixed it.
> > > > @Rem0o - just worth keeping an eye here in the event someone else has this issue, for the actual solution
> > > 
> > > 
> > > I tried to actually lower it and saved it to my configuration but for some reason it keeps going back to 30s and it still won't start up after OS boot complete
> > 
> > 
> > What about raising it to 40s delay? Does that save successfully and work?
> 
> Still stuck on 30s and still doesn't startup automatically.

Was on holiday for a week, but it might be worth starting a new issue as it doesn't seem like @Rem0o has seen the subsequent messages on this one to know to reopen it?

**Comment by Rem0o** [comment]
In the end all FanControl does is set up this in the Task Scheduler:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/86c79dd3-c4dd-4433-a07a-f529741f2a9f)

You can try to untoggle and retoggle the start with user logon, this will delete and recreate the task.

**Comment by RandomCrashToDesktop** [comment]
It worked for me:

1. Press Win+R and type taskschd.msc

2. Go to “Task Scheduler library”

3. Find the item named “FanControl” automatically added by FanControl in the list, right-click on it and select 'Properties'

4. Go to the “Actions” tab and click ‘Edit’ on the only available task “Run program | FanControl.exe”

5. In “Settings” and the “Program/Script:” field, select the full path to the FanControl executable file, in my case it was D:\FanControl\FanControl.exe

6. Clear the “Start in (optional)” field

7. Voila! FanCotrol will start automatically after the next restart.
