### ISSUE TITLE
Mix Sensors always reported missing from other Mix Sensor after a while from fixing and re-saving.

### ISSUE THREAD

**Issue by LukeCall** [Rem0o/FanControl.Releases#2479]
**Describe the bug**
My bug is simple either that or it isn't a bug and I shouldn't be doing this. Can find no where else though of anyone either experiencing the issue or doing the same thing so have no reference but to report it and hope for an answer.

I'm using 3 mix custom temp sensors for SSD, MOBO and RAM temps respectively (seen in the image).
![image](https://github.com/Rem0o/FanControl.Releases/assets/11088217/b8c2ccd5-a179-45bb-8bac-6429eeb29c19)

Now the issue is, every now and then (usually after a few days from me manually fixing it and then re-saving) it'll just decide to report that all those mix sensors are missing from the main System mix sensor that is using the other 3 (seen in the image).
![image](https://github.com/Rem0o/FanControl.Releases/assets/11088217/47a89bd4-75ed-411b-8d6e-6a7062c8faa8)

When of course it should look like this (seen in the image) - which is after I manually have to keep fixing it after the issue happens eventually.
![image](https://github.com/Rem0o/FanControl.Releases/assets/11088217/d20c339a-dc22-42db-bb79-a385baab64ef)

**Comment by Rem0o** [comment]
You are using HWINfo to get those DIMM temps right? What is happening is that HWInfo will sometime not report DIMM temps, which will create an error for your RAM Temp mix sensor, which will create an error for your System mix sensor.

Do you use the latest HWInfo version beta? I believe that was fixed.

Now as for FanControl itself, I may have found a bug which correlates with your weird deserialization issue.  Will be in the next release.

**Comment by Rem0o** [comment]
See V188
