### ISSUE TITLE
Cannot add Fan Curve to Control with multiple fans

### ISSUE THREAD

**Issue by MrPieUK** [Rem0o/FanControl.Releases#248]
So i have 3 Noctua fans (pwm) hooked up to a splitter which then connects to the nexus+ hub on my fractal case. I've managed to find out which control card is linked with the noctua case fans however i can't seem to add a fan curve card onto it where as the cards for my graphics cards show me that option. Is there a reason for this?

![](https://puu.sh/HK7uO/bf91ba495a.png)

**Comment by Rem0o** [comment]
First you have to enable the card. Then make sure it's not in manual mode ( three dot menu, untick manual ). Then you should be able to select a fan curve.
