### ISSUE TITLE
UI: Loading config to reset changes of same config does nothing

### ISSUE THREAD

**Issue by typpos** [Rem0o/FanControl.Releases#2480]
FanControl v186
Win 11 Pro

Repro:
* Load a configuration
* Change a setting, for example, fan speed to manual control
* CTRL-L to load a configuration
* Select Discard
* Select the current configuration and click 'Load'

Expected:
* Configuration is loaded and changes are reset

Actual:
* Configuration does not load; changes are not reset

Workaround:
* Load a different configuration, then load the original configuration

**Comment by Rem0o** [comment]
Nice catch. I explicitly do not reload the config on "discard" when loading a new config to avoid reloading the current config, before loading the new config. However, if you select the same config and the dialog sees the same config, it won't reload, ending up with your bug. 

Will fix.

**Comment by Rem0o** [comment]
See V188
