### ISSUE TITLE
Round values on fan curves

### ISSUE THREAD

**Issue by Cubox** [Rem0o/FanControl.Releases#249]
Hi,

It seems fan curves are internally saved as floats.
``` "50,11.7227879050926",
              "60,19.9450101273148",
              "70,30.167232349537",
              "80,40.3894545717593",
              "88,50.6116767939815",
              "89,60.167232349537",
              "90,80.167232349537"
```
Could those values not be rounded automatically? Here, my 80 point should be 40% but is actually 40.3%
This would be fine, but I think this is the reason some of my controls are not at the same speed, while having points at the same position
![image](https://user-images.githubusercontent.com/479129/119927171-38cf7480-bf79-11eb-98ff-9c631703c448.png)

**Comment by Rem0o** [comment]
The controls are actually an 8 bit value, so 256 possible values that I round to a 100 possible values. Take note that each fan is unique and won't respond exactly the same to the same command.

**Comment by Cubox** [comment]
I did some more testing, the issue is not actually about the controls and the fact they are 8 bit. (Well, slightly)
It's that in the graph editor, you might have different actual values for a given percentage.

If I make a graph manually, then reproduce that graph (without copy/pasting the points), while I want the same points (60°C 20%, 70°C 30%, 80°C 40%), in practice, depending on how I dragged the point, the curves will (internally) be different.
This causes a problem, because I want to have the same curve at the start (up to 70°C) and then for one of them differ. But since I redid the curve manually, the lower values (50-60°C) might have different actual fan values. This causes the mismatch in actual fan duty requested by the software, and is what you see in my screenshot.

![image](https://user-images.githubusercontent.com/479129/120052610-61fa0e80-c026-11eb-8b60-23c4b39a41f1.png)
![image](https://user-images.githubusercontent.com/479129/120052612-66bec280-c026-11eb-8e41-864b72a175fd.png)
Those two graphs have the same points for 50-60-70°C. However, with the same temperature source, at those ranges, sometimes they produce a different percentage, being sent to the fans, due to the slight mismatch between the points.
It's not about the RPM, but the duty cycle being sent to the fans.

While it's a very very minor issue, I think the points on the graph editor should be made with values for each percent and each degree. Then the software can internally based on the values do the math and convert that into the actual 8 bit duty cycle for the fans. This would mean that a point on what looks like 50% will always be 50%, and not the current behaviour where it could be either 50.6116767939815 or (whatever value is just before that).

As always, your software is a life saver for me, so thanks for your work so far and for being open to suggestions.
I could always do "copy points" but if I change my curves I then need to remember the difference between each curve and then reproduce each after a switch, which is annoying.

**Comment by Rem0o** [comment]
@Cubox I get your point, but isn't that a bit of an OCD thing? Absolute worse case, eg. 244 is sent instead of 243 to the controller. And that's on a constantly moving target (temperature) on the curve.

**Comment by Rem0o** [comment]
Think what I'm gonna do is just show 1 decimal point on the % on the graph editor. Should solve your issue without changing anything.

**Comment by Cubox** [comment]
> @Cubox I get your point, but isn't that a bit of an OCD thing?
You are exactly right, in practice this is not an issue, it's more of an OCD type thing.

On my screenshot, the controls do not have the same fan curve "graph" item, but their "graph" curve has the same curve manually. But what I think happened is when manually reproducing the same points on the other curves, sometimes it's at like 19.9 and others 20.3 and you can't easily see it to make sure it's the same everywhere.

I also found that sometimes when selecting 100% you might get the one just below (253 instead of 254), and you can't really see it on the graph, unless you take the point and drag it to the top, seeing that indeed you were not straight on.

Showing 1 decimal point would absolutely fix this issue.

Thanks for spending the time on such a small issue. This software is the best of it's kind and I can't go back to not using it.

**Comment by sctanf** [comment]
@Cubox In the meantime, you can edit the configuration file and set the points manually, then reload the configuration.

**Comment by Rem0o** [comment]
Decimal point was added to graph editor.

**Comment by Cubox** [comment]
Thanks for your work on this
