### ISSUE TITLE
Toggling NvApiWrapper with pending changes doesn't work

### ISSUE THREAD

**Issue by Jademalo** [Rem0o/FanControl.Releases#2491]
**Describe the bug**
If you have pending changes and try to enable or disable NvApiWrapper, it will prompt you to save. If you click yes and save, then after the refresh NvApiWrapper will be in the previous state. 

The only way to successfully toggle the state is to not have any pending changes when changing the option.

**Comment by Rem0o** [comment]
Was able to repro.  Will fix.

**Comment by Rem0o** [comment]
V189
