### ISSUE TITLE
My GPU is not read correctly

### ISSUE THREAD

**Issue by Meteoblastdragon** [Rem0o/FanControl.Releases#2493]
**Describe the bug**
![image](https://github.com/Rem0o/FanControl.Releases/assets/118288901/2f51c81d-efb6-4219-813e-9caae4368409)
![image](https://github.com/Rem0o/FanControl.Releases/assets/118288901/1819f4ad-48a0-4013-a7ce-73aeea0d989d)

It seems there's an issue reading my GPU. It stays stuck at "25% - 33RPM" which is not right according to what I observed and what the AMD Adrenaline software tells me. The fan control does not control my GPU fans either. All other fans seem to work accordingly as far as I can tell. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No, the latest entry was 23/02/2024
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/15210490/log.txt)

**Relevant hardware specs and setup**
GPU: MSI MECH OC Radeon RX 5700 XT 8 GB 
CPU: AMD Ryzen 5 3600
Motherboard: MSI MPG x570 Gaming Plus

**Comment by Rem0o** [comment]
Install this:
https://github.com/Rem0o/FanControl.ADLX

Untick gpu in sensor settings, keep only ADLX.

**Comment by Meteoblastdragon** [comment]
So I already had ADLX installed, but didn't know about the unticking part. This is how it should look? 
![image](https://github.com/Rem0o/FanControl.Releases/assets/118288901/62f490ac-6feb-416f-8d8e-0cac79c90d42)

**Comment by Rem0o** [comment]
Yes, if you don't have an nvidia card, you can also untick NvApi.

**Comment by Meteoblastdragon** [comment]
So I think it's working, the RPM according to Fan Control now matches with AMD Adrenaline (it automatically created its own custom tuning settings). However, the GPU graph is different from the one I made in Fan Control. The graph in GPU control also doesn't seem to have a temperature source anymore. And there's something about the "match speed sensor". Am I supposed to do anything?
![image](https://github.com/Rem0o/FanControl.Releases/assets/118288901/e28c17cf-1cad-46dd-bcbd-9ecef8028c2c)
![image](https://github.com/Rem0o/FanControl.Releases/assets/118288901/3239549f-5905-4783-8f58-31734fc861c9)

**Comment by Rem0o** [comment]
You need to assign an ADLX sensor in the GPU graph, hotspot or gpu.  It is normal the fan control graph and adrenaline don't match. Don't worry about that.

**Comment by Meteoblastdragon** [comment]
Cool! Now I'm just hoping my temps are fine. I have run the software ever since Jay made the video on it and am not sure how long ago this issue started since I have it run minimised. I have no knowledge of temps and curves and what should be fine (especially since my CPU seems high but maybe it's normal). Though I should probably take this somewhere else. Thanks for the support though!

**Comment by Rem0o** [comment]
From what I can see in the screenshot you got the idea right with your setup. 

Cheers,
