### ISSUE TITLE
Extra word in error message

### ISSUE THREAD

**Issue by Noctis-** [Rem0o/FanControl.Releases#2495]
Got an error saying: `if this error occurs when upon startup, try increasing your startup delay.`

should probably just say `if this error occurs upon startup, try increasing your startup delay.`
version 188

![image](https://github.com/Rem0o/FanControl.Releases/assets/6160139/f7a82ca5-c63a-4ba4-a6e7-b2454e884e47)

**Comment by Rem0o** [comment]
Will fix.

**Comment by Rem0o** [comment]
V189
