### ISSUE TITLE
Errors with plugins installed

### ISSUE THREAD

**Issue by vfib** [Rem0o/FanControl.Releases#2497]
Hello together, I'm getting a lot of plugin related errors for some time now. The only plugins I installed are the HWiNFO and NvSensors plugins. Unfortunately, Im not able to locate the cause of the errors. log.txt is appended. Using FanControl 188 and HWiNFO 8.00.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/15221691/log.txt)

If you need further information, please ask.

Best regards

**Comment by Rem0o** [comment]
The errors are happening in the plugin's code. 
->  FanControl.NvThermalSensors.NvThermalSensor.Update()

This issue should be opened in that plugin's repo.

**Comment by vfib** [comment]
Hello, 
thanks for your quick answer. I will create an Issue there. Furthermore, thanks for your great work :)
