### ISSUE TITLE
winget Support

### ISSUE THREAD

**Issue by ackhack** [Rem0o/FanControl.Releases#250]
Will there be a winget package in the future? (FYI its the new [Windows 10 PackageManager)](https://github.com/microsoft/winget-cli)

**Comment by Rem0o** [comment]
The platform doesn't seem really mature, but I'll keep an eye on it.

**Comment by hazre** [comment]
Updates on this? V1.0 just released.

**Comment by Rem0o** [comment]
Well, I'd have to upload it to the Microsoft Store right?

**Comment by hazre** [comment]
No, its separate. https://docs.microsoft.com/en-us/windows/package-manager/package/

**Comment by BHoggs** [comment]
winget doesn't support portable apps yet (e.g. zipfile). Would need to either wait for that or package this app into an MSI.

Could do a chocolatey package though?
