### ISSUE TITLE
FanControl not working on latest update

### ISSUE THREAD

**Issue by Butter-On** [Rem0o/FanControl.Releases#2503]
**Describe the bug**
Fan control doesn't even start up - and if I somehow forced it to start it closed with only a popup on the screen that read something along the lines "Expected 34 sensors found 32" - Version 189 I think

**Is there a log.txt file next to FanControl.exe with recent date entries?**
https://pastebin.com/0vBSFVHw

**Relevant hardware specs and setup**
3 non PMW fans - 1 connected directly to Fan connector other 2 on Y splitter
A Arctic II 240 aio, everything on CPU_fan
a 6800XT Pulse

**Comment by dragondojo2** [comment]
Same error.

I think the AMD GPU drivers are buggy. Other programs I use are crashing too, and I'm getting some GPU driver errors in these programs.

**Comment by dragondojo2** [comment]
Steps to fix it (at least for me):

1) Remove all installed plugins.
2) Open FanControl and update it.
3) Download the [ADLX](https://github.com/Rem0o/FanControl.ADLX) plugin again.
4) Paste all DLL plugin files inside the plugin folder.

Now everything should work again!

**Comment by tarnith** [comment]
Also not reading GPU sensors at all with latest update (ASUS RX 480, running on latest official AMD pro driver)

**Comment by Rem0o** [comment]
Solved V191
