### ISSUE TITLE
FanControl icon is blending with Windows 11 Start Menu light theme background

### ISSUE THREAD

**Issue by soredake** [Rem0o/FanControl.Releases#2504]
**Describe the bug**
![image](https://github.com/Rem0o/FanControl.Releases/assets/5204968/b7c15826-a473-44a0-a4da-ec57dc4cfcea)

**Comment by Gittykittymitty** [comment]
This needs to be changed! It's also so easy, just add a black outline to the icon and it can clearly be seen even in light mode!

**Comment by Rem0o** [comment]
I agree a black outline would be appropriate.

Something like 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/60547117-90ee-49da-a434-c27947eb074d)

**Comment by Gittykittymitty** [comment]
Exactly how I pictured it!

**Comment by LRJuuu** [comment]
+1

**Comment by Gittykittymitty** [comment]
The newest version of fancontrol now fixes this issue! Thanks alot to the developer for actually listening! Really appreciate your work :)
