### ISSUE TITLE
Can't control fans on a fan hub

### ISSUE THREAD

**Issue by QAthulhu** [Rem0o/FanControl.Releases#2513]
**Describe the bug**
MB: Asrock B-560 Steel Legend
Case: Lancool II Mesh Performance

I have 3 case fans connected to a fan hub, and that fun hub connected to a fan header on the motherboard. I have the fan control switch on the case set to A, meaning it will use motherboard control.

Fan Control can detect the fan speed, but when I go to calibrate, setting it to zero or 100% does nothing, fans will not change speed. As such, I am unable to control my fan speed. CPU and GPU fans work fine

**Comment by Rem0o** [comment]
Is the PWM pin of the motherboard header actually connected to that hub? Sometime hubs only have the RPM sense wire connected, meaning the motherboard couldn't control that hub.

**Comment by QAthulhu** [comment]
I solved the issue. Motherboard settings have fan headers set to "AUTO" instead of "PWM". Updated them and Fan Control works now. Thanks!
