### ISSUE TITLE
Fan speed gets stuck at low value

### ISSUE THREAD

**Issue by orionduffy** [Rem0o/FanControl.Releases#2514]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]
Frequently, the fan speed will start decreasing all the way to the minimum while the temperature is still very high. Restarting the software will usually fix the bug, but only temporarily.
![Screenshot 2024-05-15 174242](https://github.com/Rem0o/FanControl.Releases/assets/45501204/c4724c34-adad-45d9-9235-4ed8ce1deddb)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/15327305/log.txt)

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]
ASUS ROG Strix Z790-E, Nvidia RTX 4090 Super, Intel i9-14900kf, Phanteks T30-120 fans set to 3000RPM max, the fans I'm trying to control are directly plugged into the mobo but I do also have fans in a corsair fan controller that are not controlled by the Fan Control software.

**Comment by orionduffy** [comment]
Changing the curve settings seems to somewhat fix it temporarily when it recalculates, but I'm pretty sure the speed % is still off and it starts going down again quickly.

**Comment by Rem0o** [comment]
That's the expected behavior of the auto curve. As long as it's under Load temp. (80 in your case) , it will go to the slowest possible value set. At 76 degree, you are under (80 - deadband).   If you want the temperature range from which it doesn't drop to be wider, increase the deadband.

**Comment by orionduffy** [comment]
Alright, sorry, upon further research, I realized I thought it worked like Linear. Thank you for the response.
