### ISSUE TITLE
Turning off NvApiWrapper results in permanent refreshing screen

### ISSUE THREAD

**Issue by Neocyte** [Rem0o/FanControl.Releases#2517]
### **Describe the bug**

When editing sources under Settings -> Sensors and turning off NvApiWrapper, the user is prompted to refresh the application. In my experience, clicking "Yes" results in a permanent refreshing screen even after 30 minutes of waiting.

The sensors Motherboard, CPU, and GPU are still ticked on as default. And I made sure to save the default configuration before editing any sensors.

### **Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/15358319/log.txt)

### **Relevant hardware specs and setup**
7800X3D
4090 FE
Asrock B650E PG-ITX

**Comment by Rem0o** [comment]
[FanControlLibWithExtraLog.zip](https://github.com/Rem0o/FanControl.Releases/files/15366077/FanControlLibWithExtraLog.zip)

Please swap this version I made with extra logs, and do the same thing, then post the new logs here.

**Comment by Neocyte** [comment]
https://github.com/Rem0o/FanControl.Releases/assets/37944166/a2c9291c-beea-4806-81f7-75c822ba5953

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/15366220/log.txt)

Here are the new logs with the swapped version. I also posted a video demonstrating the infinite refreshing after turning off NvApiWrapper.

**Comment by Rem0o** [comment]
The way you captured the video we can't see the dialog windows.

**Comment by Rem0o** [comment]
[FanControlLibrary.zip](https://github.com/Rem0o/FanControl.Releases/files/15366266/FanControlLibrary.zip)

Also here is yet another go at this.

**Comment by Neocyte** [comment]
https://github.com/Rem0o/FanControl.Releases/assets/37944166/91a10ca7-d0c6-4be8-9bfd-4cf9df07fe31

https://github.com/Rem0o/FanControl.Releases/assets/37944166/e10529e2-16e0-49f4-be39-77fdd0c8dc52

It seems that the newest .dll from FanControlLibrary.zip completely solved the infinite refresh issue. I have attached videos properly demonstrating the issue from before and after.

**Comment by Rem0o** [comment]
Fantastic thanks for the videos, makes it much easier to see what's going on. Glad it fixes the issue. Highlighted a flaw in the refresh process. The fix will be in the next release, in the meantime keep the Dll I gave you.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V192
