### ISSUE TITLE
Feature Request: Differential as control (PD-controller)

### ISSUE THREAD

**Issue by LDAP** [Rem0o/FanControl.Releases#252]
This would allow behaving differently for fast rising and falling temperatures. (Like a PD controller)

Ideally, this would be also available as a custom "Sensor" allowing for example feeding the real temperature and the differential into a "Target" controller.

**Comment by Rem0o** [comment]
I've been playing with the idea of a PID / PD / intelligent fan curve for a while. There is actually one in the software right now, just not activated. It's really hard to setup right now, as increasing fan speed doesn't usually change the temperature in a few seconds, it can take up to a minute to see a difference depending on the situation. That kind of reaction time between the controlled input (fan speed) and the output (temp) is tricky to deal with a controller.

**Comment by sctanf** [comment]
Would making the update rate higher help?

**Comment by LDAP** [comment]
> 
> 
> I've been playing with the idea of a PID / PD / intelligent fan curve for a while. There is actually one in the software right now, just not activated. It's really hard to setup right now, as increasing fan speed doesn't usually change the temperature in a few seconds, it can take up to a minute to see a difference depending on the situation. That kind of reaction time between the controlled input (fan speed) and the output (temp) is tricky to deal with a controller.

I would use it especially to trigger a "Target" fan curve, allowing to react to changing temperature faster.

**Comment by Rem0o** [comment]
> Would making the update rate higher help?

It ain't a clock problem, the physical phenomenon itself is slow to react.
