### ISSUE TITLE
Feature Request: Fan Speed "keep-out" zones/range avoidance.

### ISSUE THREAD

**Issue by Grey** [Rem0o/FanControl.Releases#2524]
Some of my fans make the most incredibly annoying noises at certain speed ranges; can we get an option that lets us create a normal curve; but define "keep-out" zones in those curves, (ie: `if x>=range-min: x=max(x,range-max)` )
 
[presuming I haven't missed the way to do this already of course]

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2108
