### ISSUE TITLE
[FEATURE REQUEST] Add option to ignore fan during calibration

### ISSUE THREAD

**Issue by spec-chum** [Rem0o/FanControl.Releases#2526]
I have a custom loop obviously with a pump - I really like auto calibration feature, but when I use it it drops my pump to 0, not for long, but I really don't want the pump speed to be touched.

Apologies if I've just missed it, but can you add an option to ignore a "fan" (pump in my case) when doing auto calibration?

I do want to monitor it's speed, so don't really want to unpair the speed sensor.

Just thought while typing this as well, is there a way to trigger an alarm or something if a speed sensor goes below a certain RPM?

**Comment by curious-city** [comment]
I don't use pumps in my system but you can choose the sensors you want to calibrate right in the beginning of the setup (see attachment).
If your pump is connected in a way that it is not listed separately (e.g. combined with the CPU header or something) I don't know how to solve that but that shouldn't be the case anyway. Hope that helps.

![FanControl_Sensors](https://github.com/Rem0o/FanControl.Releases/assets/170740006/9c61af83-b254-46ef-bdd2-a497d6633bb5)

**Comment by spec-chum** [comment]
> I don't use pumps in my system but you can choose the sensors you want to calibrate right in the beginning of the setup (see attachment). If your pump is connected in a way that it is not listed separately (e.g. combined with the CPU header or something) I don't know how to solve that but that shouldn't be the case anyway. Hope that helps.
> 
> ![FanControl_Sensors](https://private-user-images.githubusercontent.com/170740006/333805864-9c61af83-b254-46ef-bdd2-a497d6633bb5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NTA0ODAsIm5iZiI6MTcxNjY1MDE4MCwicGF0aCI6Ii8xNzA3NDAwMDYvMzMzODA1ODY0LTljNjFhZjgzLWIyNTQtNDZlZi1iZGQyLWE0OTdkNjYzM2JiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxNTE2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGM2MGE0YmQ4NDNjYjdjZjRjZWY4Mzk0ZTc1Mzc1MzY2YTRkZjU1OWNkOTE5NDYwYTAzODdjZTliYTYwNDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DWP4yyvHIfCuwz6gmx7ug9xeG65TRBU8GT2cu6jZD8s)

Thanks for that, most pump's RPM control is just connected to a normal 4 pin fan header, so it's just reported like any other fan, none of the settings you list on your screenshot will help, sadly.

**Comment by curious-city** [comment]
> Thanks for that, most pump's RPM control is just connected to a normal 4 pin fan header, so it's just reported like any other fan, none of the settings you list on your screenshot will help, sadly.
ah ok I see, so there is no distinction between a 'normal' fan header and the pump fan header, good to know.
I leave the issue to the dev then and show myself out - hope you find your answer/solution :)

**Comment by Rem0o** [comment]
You can do each control individually without using the assisted setup. However if you want to cheat it, unpair the rpm sensor on your pump, do the calibration from here:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/934c328b-811a-476f-885d-a6160496a50d)

Then pair the sensor back.  I know it might be a bit of a hassle, but that's the kind of thing you only need to do once then forget about it. 

As for the alarm feature, https://github.com/Rem0o/FanControl.Releases/issues/807.
