### ISSUE TITLE
Fan control does not allow to change Affinity

### ISSUE THREAD

**Issue by rolex20** [Rem0o/FanControl.Releases#2527]
I have a 12700K CPU with P-Cores and Efficient-cores.  When I change the affinity to FanControl to run only on efficient cores (My games are assigned the P-Cores only), taskmanager accepts but then FanControl returns to affinity to all cpu's.  Can you please allow changing the affinity?

**Comment by curious-city** [comment]
Is it imporant if FanControl runs on P- or E-Cores? The app barely uses any system ressources anyway, so it shouldn't be a concern.

**Comment by Rem0o** [comment]
FanControl doesn't mess with its process affinity or anything like that, so I don't know how I could "allow" changing affinity.

**Comment by rolex20** [comment]
This is about deciding which resources i want to give to fancontro.  As I said, task manager allows changing the affinity and it accepts.   Immediately I check again and the affinity is resetted to all cpu's.   This means that the program checks and reassigns it's own affinities.  I know some programs that don't allow this change so task manager fails when trying to change.   But in this case there is no error, just that when you check again ,the affinities are resseted to all cpu's.   If fancontrol itself does reset it's own affinities, how else could this happen?

**Comment by Rem0o** [comment]
Nevermind, found it: 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/e111fefe-8161-49ee-867e-3f785780af20)

It's in the Ring0 code from LHM:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/3959e8e3c04452fed566e88fb40d0847a64581d8/LibreHardwareMonitorLib/Hardware/Ring0.cs#L331

**Comment by rolex20** [comment]
thank you Rem0o!, any chance not executing that line with a configuration option or some other way?

**Comment by Rem0o** [comment]
Not really, as the thread affinity seems required to read each cores sensor.

**Comment by rolex20** [comment]
ok, I understand, but thanks for the reply
