### ISSUE TITLE
Only one AMD GPU Temp Sensor is shown in a Multi GPU Setup

### ISSUE THREAD

**Issue by NightHammer1000** [Rem0o/FanControl.Releases#253]
If you have a Multi GPU AMD Setup, FanControll only shows one Temp Sensor for Curves.

**Comment by NightHammer1000** [comment]
Latest Update does not see AMD GPUs at all it seems.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/commit/5be9e89635e1c0264b896fc94c8e140be1b0fc6c
