### ISSUE TITLE
Dell Fan Issue

### ISSUE THREAD

**Issue by Lotiara** [Rem0o/FanControl.Releases#2530]
Hi
I've set a Flat curve to test my fans
From 30% to 66% everything is working ok, lineal
0% is 0RPM
66% is 1988 RPM 
67% is 4183 RPM which is max speed
There is no way to have anything between 1988 to 4183, so, basically my regulation is ON/OFF instead of a smoth regulation
If i set fan control in manual I get the same behaviour.

Any idea ?

**Comment by Rem0o** [comment]
I guess you are using the dell plugin for your laptop? That's the way dell programs their fans, 3 speeds, nothing to do about it.

**Comment by Lotiara** [comment]
Yess Ia m using dell Plugin
Only 3 speeds ? pfffff
Thanks for the answer.
