### ISSUE TITLE
Feature request: add "graph" curve setting to latch fan speeds to only the nodes on the graph

### ISSUE THREAD

**Issue by ahydronous** [Rem0o/FanControl.Releases#2532]
**Describe the bug**
I use the fan curve for my CPU with very specific fan speeds per temperature because my fan has lots of horrible harmonic frequencies. I've hunted down which fan speeds do not cause this. It would be really nice to be able to tell FanControl to only use those specific speeds, and jump to the next node on the graph if temperature rises past the current temperature node in the graph.

**Comment by Rem0o** [comment]
You can already kind of do that, with a graph like so:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/218545e3-8874-4a9f-954f-b29d2cbd6e8c)

Otherwise, it's a duplicate of : https://github.com/Rem0o/FanControl.Releases/issues/2108

**Comment by ahydronous** [comment]
Ah, neat, thanks!

If you do ever consider it, I think most programs call it a stair curve.
