### ISSUE TITLE
Problem with sensors reading

### ISSUE THREAD

**Issue by mjova** [Rem0o/FanControl.Releases#2538]
There are errors in reading the CPU temperature on the Supermicro X12DPi-NT6 motherboard. Due to these errors, the fan operates uncontrollably. I have described the details here:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/1338

The problem is definitely in the LHM library, but maybe you can do something to resolve the issue...

**Comment by Rem0o** [comment]
Without the board on hand to test, I can't do anything more than any other person on this platform.

Sorry.
