### ISSUE TITLE
Not working in dell precision

### ISSUE THREAD

**Issue by wisamidris7** [Rem0o/FanControl.Releases#2547]
![image](https://github.com/Rem0o/FanControl.Releases/assets/104096256/1c7774df-76f8-476f-9360-2338d59b571b)

My computer is

Dell precision
Intel Xeon

Why this message appearing

**Comment by Rem0o** [comment]
Because you got the NvApi setting checked and no Nvidia GPU in your computer.

**Comment by wisamidris7** [comment]
I have nvidia gpu in my laptop
![image](https://github.com/user-attachments/assets/b4668cdc-9079-4610-a115-e4809cedb705)
