### ISSUE TITLE
Tray Icon 3 digit Problem

### ISSUE THREAD

**Issue by Ridianoid** [Rem0o/FanControl.Releases#2549]
**Describe the bug**
![2024-06-05 16_12_18-](https://github.com/Rem0o/FanControl.Releases/assets/20602186/efcc5eef-f187-449f-9394-0eb42ef898e0)

The 3 digit feature does not work as it should. I searched for an option for those who want to see at least 2 digits, but there was none or I couldn't find it. 

I was thinking that I could enlarge the values if I could, but it got even smaller :D 

W10 22H2 + Fan Control Net 8 Version

**Comment by Rem0o** [comment]
Ahhh problem here is the "," number separator I didn't account for. It should round the value.

**Comment by limetto** [comment]
My time avg temp sensor isn't showing at all now:
![grafik](https://github.com/Rem0o/FanControl.Releases/assets/17469894/86832b1e-5da9-4835-bf8d-f79b81731a4f)

**Comment by niklaskroe** [comment]
> My time avg temp sensor isn't showing at all now: ![grafik](https://private-user-images.githubusercontent.com/17469894/336867730-86832b1e-5da9-4835-bf8d-f79b81731a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTI3OTQsIm5iZiI6MTcxNzYxMjQ5NCwicGF0aCI6Ii8xNzQ2OTg5NC8zMzY4Njc3MzAtODY4MzJiMWUtNWRhOS00ODM1LWJmOGQtZjc5YjgxNzMxYTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE4MzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3N2M4MTZhMTRmMWM2OGQyYzRiMGZjOGM2OGY4OGU3MDVlYjRlZDIyNjY3YjgxOGFhNzQ3NGY3OTQyMzU5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Fq5pjvugInGGWw0L3iHf_scmogruH1g3uSutwzsKwY) Using , localisation as well.

yup, custom sensors dont show up at all

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V193
