### ISSUE TITLE
V192 - Tray Icon bug with a custom average sensor

### ISSUE THREAD

**Issue by FabFixxx** [Rem0o/FanControl.Releases#2550]
**Describe the bug**
Hi ! First thank you for your very good software !
I update on V192 and my temperature disapear in systray, if i add any sensor it's work but if i add my custom average one no temperature is showing, it's just the color of my task bar. See my example : there is "nothing" for the second tray icon.
![Capture d'écran 2024-06-05 170212](https://github.com/Rem0o/FanControl.Releases/assets/137110554/d9d7412c-ee0b-47d7-9d96-ff4a0b719944)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No

**Relevant hardware specs and setup**
Windows 11

Thank you !

**Comment by zme-ul** [comment]
can confirm this issue exists with V192 when displaying a MIX curve

example: the maximum between CPU temp and GPU temp

**Comment by SirStew** [comment]
I have the same issue, I have 4 AVG time sensors for Temps / Water Temps, all are blank not showing text or colour.
![3kUwqOV0x9](https://github.com/Rem0o/FanControl.Releases/assets/171836634/88b201e4-5695-4e5b-947e-88a5e431fc09)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V193

**Comment by zme-ul** [comment]
confirming issue is fixed with 193 build
