### ISSUE TITLE
V192 - Tray Icon cut off

### ISSUE THREAD

**Issue by tall1on** [Rem0o/FanControl.Releases#2551]
![nTOjkuaWe4](https://github.com/Rem0o/FanControl.Releases/assets/19853403/80e11a31-921b-4cb6-8637-b3d898b29896)
**Describe the bug**
As you can see on the screenshot, the tray icon has been cut off since the update. I think the reason for this is that it now shows decimal places. The tray icon also looks much worse than before.

**Relevant hardware specs and setup**
Windows 11
3840x2160
The temperature sensor is from a Ryzen 9 7950X

**Comment by Rem0o** [comment]
What scaling?

**Comment by c0dycode** [comment]
Same for me on 1920x1080 with 100% scaling.
Personally I don't care about showing decimals in the tray icon at all.

As that might be intended, I'd like to suggest an option to toggle rounding of the temp(s) in the tray icon(s). :)

**Comment by Rem0o** [comment]
The decimal was not intentional.  Will be fixed.

**Comment by Rem0o** [comment]
As for the flaky look, that's cleartype over white background, it just look bad indeed..... I'll try to find a good compromise for dark mode, light mode, high res screens, low res screens...

... (sigh)

We'll get there.   3 digits for the murica temperature units though :)

**Comment by tall1on** [comment]
> What scaling?

I am also on 100% scaling

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V193

**Comment by tall1on** [comment]
looks good, thank you
