### ISSUE TITLE
Laptop compatible?

### ISSUE THREAD

**Issue by Yexiaowei11** [Rem0o/FanControl.Releases#2552]
Why can't I adjust my laptop's cooling fan?
![屏幕截图 2024-06-06 011900](https://github.com/Rem0o/FanControl.Releases/assets/102587532/ff42e164-cdb8-490d-a509-54868c477925)
![屏幕截图 2024-06-06 011944](https://github.com/Rem0o/FanControl.Releases/assets/102587532/a2d387ed-c130-4bda-9383-021061d4fad9)
Will it be supported in subsequent versions?

**Comment by niklaskroe** [comment]
I doubt it, laptop manufacturers usually block overwriting their own fan curves due to warranty reasons.

**Comment by Rem0o** [comment]
FanControl is not compatible with laptops.
