### ISSUE TITLE
Since V192, custom sensors don't show anything on the system tray.

### ISSUE THREAD

**Issue by Cantejito** [Rem0o/FanControl.Releases#2553]
I tried changing between light and dark mode in FanControl and Windows 10 and nothing. Custom colors don't apply either.

If I add a curve it will show it, but it will be cut off from both sides as the decimals make it too wide.

[log.txt](https://github.com/user-attachments/files/15594818/log.txt)

![Screenshot_1](https://github.com/Rem0o/FanControl.Releases/assets/125479909/154be4e5-a5c8-453c-93db-88413e51fdbe)

**Comment by d-e-n-n-i-s-t** [comment]
Same for me. I already removed and re-added the sensor as the system tray icon, still doesn't work. Changing the color of the tray icon also didn't work.

**Comment by sh4rkman** [comment]
Same here :

![20240605_21h17m_iGCQkiQEzJX](https://github.com/Rem0o/FanControl.Releases/assets/9033912/5c1057de-2815-448e-9dea-32decfee30e8)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V193
