### ISSUE TITLE
Tray icon font loss its boldness now it looks ugly since v192

### ISSUE THREAD

**Issue by MrManinBlack1337** [Rem0o/FanControl.Releases#2555]
How do I make it look like previous versions?

![Screenshot 2024-06-06 101537](https://github.com/Rem0o/FanControl.Releases/assets/87234960/dcde1e70-98c4-406c-a2eb-c611c490dd24)

**Comment by Touhid0101** [comment]
![Screenshot 2024-06-06 105905](https://github.com/Rem0o/FanControl.Releases/assets/136336143/b702812b-f0c9-49d5-beb6-149f75c85379)

Hmm. I've also faced the same Issue. From version 192 it became like this and Couldn't find any solution

**Comment by FabFixxx** [comment]
Same problem here

**Comment by zeek-zag** [comment]
Would be nice if we were able to customize the font and size of the tray indicator.

**Comment by Satyrexx** [comment]
Agreed. Tray icon is no longer bold and extremely difficult to read.

My Corsair plugin also seems to be showing a decimal value now, as well.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/releases/tag/V193

**Comment by Thiago-Dantas** [comment]
> See https://github.com/Rem0o/FanControl.Releases/releases/tag/V193

hero

**Comment by MrManinBlack1337** [comment]
Thank you for the quick update!

**Comment by Touhid0101** [comment]
> See https://github.com/Rem0o/FanControl.Releases/releases/tag/V193

Thanks for the Update. It was quick 😊

**Comment by SetilaSilvios** [comment]
Still Ugly.

**Comment by SetilaSilvios** [comment]
Still Ugly.
Why did you stop using the same font as the program? Just as how it was before.

**Comment by Rem0o** [comment]
Because that font can't accommodate 3 digits in 16x16.

**Comment by SetilaSilvios** [comment]
> Because that font can't accommodate 3 digits in 16x16.

So sad...
Would it be too inefficient to use the previous font for 2 digits?
