### ISSUE TITLE
V81 breaks GPU detection

### ISSUE THREAD

**Issue by RaptDept** [Rem0o/FanControl.Releases#256]
GPU fan speed and GPU temp sensors aren't detected in V81 after updating from V80, which breaks my fan curves. I have an AMD 5700XT card.

I've downgraded to V80 since the issue doesn't occur there.

**Comment by marhensa** [comment]
yes, can confirm it breaks GPU temp sensors detection. mine is AMD RX 580.

**Comment by Fearmazter** [comment]
Replacing LibreHardwareMonitorLib DLL with an older one fixed the problem.

**Comment by Rem0o** [comment]
Will probably revert the DLL in the program, had no idea it broke AMD GPU.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/commit/5be9e89635e1c0264b896fc94c8e140be1b0fc6c

**Comment by PhyxionNL** [comment]
Can any of you try the LHM DLL from this build:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/921929234

Download the DLL from "LibreHardwareMonitor-net452" under Artifacts.

**Comment by Fearmazter** [comment]
> Can any of you try the LHM DLL from this build:
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/921929234
> 
> Download the DLL from "LibreHardwareMonitor-net452" under Artifacts.

No sensors

**Comment by PhyxionNL** [comment]
I suspect this one will work (still building, give it 2 minutes or so):
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/922034983

**Comment by Fearmazter** [comment]
Nothing, still

**Comment by PhyxionNL** [comment]
@Fearmazter can you open LibreHardwareMonitor.exe from the artifact and attach its report? It's in File > Save Report.

**Comment by Fearmazter** [comment]
[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6624861/LibreHardwareMonitor.Report.txt)

**Comment by PhyxionNL** [comment]
Hmm, is this version working? Just open LHM and check if it reports anything.
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/738139235

**Comment by Fearmazter** [comment]
It just reports the gpu power usage.
![5658451](https://user-images.githubusercontent.com/46049584/121383891-2ca2ca00-c91e-11eb-9c99-7c3b8e78c805.jpg)

**Comment by PhyxionNL** [comment]
Alright, another try then...
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/922349664
Still building (should be done in 2 mins)...

**Comment by Fearmazter** [comment]
![83264587](https://user-images.githubusercontent.com/46049584/121392150-80fd7800-c925-11eb-9c3f-b386d7882dec.png)

**Comment by PhyxionNL** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/922465090

Going by the pretty broken ADL documentation, this might work.

**Comment by Fearmazter** [comment]
Now is working fine! :grinning:

**Comment by PhyxionNL** [comment]
Can you try this build as well @Fearmazter:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/922576990

**Comment by Fearmazter** [comment]
Working fine too.
