### ISSUE TITLE
3 digits temp doesnt fit in the tray icon

### ISSUE THREAD

**Issue by M4RCK5** [Rem0o/FanControl.Releases#2561]
**Describe the bug**
![image](https://github.com/Rem0o/FanControl.Releases/assets/20927212/c220ae0e-290b-4937-a984-1f52d36a3ed1)

**Relevant hardware specs and setup**
Windows 11

**Comment by Rem0o** [comment]
What version? Should be fixed in V193

**Comment by M4RCK5** [comment]
> What version? Should be fixed in V193

My bad, im still at 192, thanks.
