### ISSUE TITLE
Kaspersky causing sensors / fan control to stop working.

### ISSUE THREAD

**Issue by SirStew** [Rem0o/FanControl.Releases#2563]
**Describe the bug**
Since updating to 193 my sensors arent detecting at all, they were fine for the first day but now it is showing the errors below, I never had this issue on v191 but trying to downgrade did not solve the issue, I am unsure what is causing this and I tried looking at past issues for a fix but could not find one. It also is saying how it cannot detect NVApi but never had this issue before either.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/user-attachments/files/15786165/log.txt)

**Relevant hardware specs and setup**
Intel 8086k
Intel Z390 Maximus Formula XI ASUS/ROG
![xONUmf1oLc](https://github.com/Rem0o/FanControl.Releases/assets/171836634/93197bd5-db23-4c17-8cdf-8140bd3c04e1)

Edit: I may have found the issue already: Windows updated last night KB5035942, going to try and uninstall this update and see if it fixes it. Not fixed from this, seems that is just a windows update that likes to show it has been installed on the day everyday.

Edit: It doesnt even detect the EC from Asus at all and I am very confused, as it literally worked last night, no updates or anything happened, just turned off and on is all.
![uk70KP92RD](https://github.com/Rem0o/FanControl.Releases/assets/171836634/3d6b8717-97ce-4fc2-8685-c848ec577864)

Edit 3: HWInfo is still picking up the NCT6798D from the mobo, just not Fancontrol - The only thing I have installed since it before it failed was Manor Lords, but I cannot see a game messing so badly with my EC that now Fancontrol cannot read it but HWinfo can.

**Comment by testzhima** [comment]
The problem lies in LibreHardwareMonitor.
I don't know why LibreHardwareMonitor suddenly couldn't detect CPU temperature and fan.

**Comment by kopalqude** [comment]
I may have had the same problem as you. LibreHardwareMonitor all of a sudden did not detect any motherboard sensors anymore although nothing was changed on my system, not hardware, not drivers or software or windows updates.

Specifically installing Windows update KB5039211 fixed this issue for me for whatever reason.

MSI MPG Z390 GAMING EDGE AC

**Comment by SirStew** [comment]
> I may have had the same problem as you. LibreHardwareMonitor all of a sudden did not detect any motherboard sensors anymore although nothing was changed on my system, not hardware, not drivers or software or windows updates.
> 
> Specifically installing Windows update KB5039211 fixed this issue for me for whatever reason.
> 
> Edit: Sorry, not fixed by the windows update. After system restart LHM shows motherboard sensors (but not CPU's own temperature data). Restarting LHM shortly after has the same problem as initially reported. Anyway, if at all, this is a LHM issue, not a Fan Control issue.
> 
> MSI MPG Z390 GAMING EDGE AC

Ah okay, shame it didn't work.. Thing is, nothing was updated or anything, just installed Manor Lords, played till midnight and suddenly next day it didn't work. I'm away at moment, I'll try the update too and see if anything changes, I'll also see if after leaving my pc completely off for 2 days if it works after. Shame you got the same issue, but glad I'm not the only one. 

> The problem lies in LibreHardwareMonitor. I don't know why LibreHardwareMonitor suddenly couldn't detect CPU temperature and fan.

Is LHM ever updated again? As the software to download doesn't seem updated at all. And it's odd it suddenly stopped working even though I didn't do anything at all. Same for the second reply guy too.. Its so strange.

**Comment by testzhima** [comment]
> > The problem lies in LibreHardwareMonitor. I don't know why LibreHardwareMonitor suddenly couldn't detect CPU temperature and fan.
> 
> Is LHM ever updated again? As the software to download doesn't seem updated at all. And it's odd it suddenly stopped working even though I didn't do anything at all. Same for the second reply guy too.. Its so strange.

It has never been updated, and two of my five computers have this issue. The driver and software have not been changed. Suddenly, the temperature and fan could not be detected. The motherboard is ROG STRIX Z790-A GAMING WIFI.

**Comment by TiiMe2tell** [comment]
Same here, updated Windows yesterday and now I noticed the only fans it detects are my GPU and the only sensors are GPU and HDDs. I changed nothing else, didn't update or download anything altho it could have already been since i updated FanControl to v193 2 days ago and i just didn't notice until now.
Also using a ROG STRIX Z590-A GAMING WIFI so it might be something specific to that series of motherboards, can't say without more data.

**Comment by leosrnh** [comment]
Same problem here. LibreHardwareMonitor doesn't detect CPU fans on Asus B550.
I tried the last Nightly build from LibreHardwareMonitor and doesn't work either.

**Comment by Rem0o** [comment]
Might it be some kind of AV which started blocking software? Anything in defender or any 3rd party AV?

**Comment by Willxfox** [comment]
Seeing the same issues after updating to latest Windows 11 (23H2) build. Missing speed sensors and control sensors for MSI board. LHM shows nothing attached to my MB.

**Comment by SirStew** [comment]
> Might it be some kind of AV which started blocking the software partially? Anything in defender or any 3rd party AV?

I use Kaspersky and of course windows defender, never had an issue before, Possibly but that would mean that everyones AV here updated the same stuff to block those things, mine never warned me it was stopping anything / blocking anything either.

**Comment by testzhima** [comment]
> Might it be some kind of AV which started blocking the software partially? Anything in defender or any 3rd party AV?

I uninstalled Kaspersky and it's currently working fine. But I still need more time for verification.

**Comment by Rem0o** [comment]
@SirStew hwinfo doesn't have an api the same way lhm does to tap into. Hwinfo is also required to run. Also hwinfo doesn't allow to set fan speeds, which is what fancontrol is all about.

**Comment by SirStew** [comment]
> @SirStew hwinfo doesn't have an api the same way lhm does to tap into. Hwinfo is also required to run. Also hwinfo doesn't allow to set fan speeds, which is what fancontrol is all about.

Ah okay, didnt know that. Shame really as it seems to work more consistently than LHM when looking at the issues on here. I will try without Kaspersky soon, but my partner who has Kaspersky with a MSI Tomahawk board is completely fine, so.. Not sure if that, plus both LHM and Fancontrol is in the trusted and allowed to pretty much do anything part from Kaspersky.

**Comment by Willxfox** [comment]
Uninstalling Kaspersky fixed my issues as well...what a bummer...

**Comment by SirStew** [comment]
Wow okay.. Kaspersky was blocking LHM.. I tried giving it exclusions, turning off Kaspersky, but nothing worked and now.. Uninstalling Kaspersky has given Fancontrol all of the sensors and such back.. That is really weird seeing as my partner has Kaspersky but no issues on an MSI board.

**Comment by testzhima** [comment]
> Wow okay.. Kaspersky was blocking LHM.. I tried giving it exclusions, turning off Kaspersky, but nothing worked and now.. Uninstalling Kaspersky has given Fancontrol all of the sensors and such back.. That is really weird seeing as my partner has Kaspersky but no issues on an MSI board.
> 
> Edit: I have messaged Kaspersky about this issue, but I doubt anything will happen. I will try to periodically install Kaspersky again, but for now will leave it uninstalled.. As I want my fans being controlled and I believe Windows Defender is good enough by itself as long as not downloading dodgy files.


@SirStew You can add the LibreHardwareMonitorLib.dll file from FanControl to the Kaspersky credit recognition list. And check these options.
My English is not good, I hope you can understand it.
![微信截图_20240615061749](https://github.com/Rem0o/FanControl.Releases/assets/172461142/4ce6ab98-1af4-4379-a671-be19abb324e8)

**Comment by SirStew** [comment]
> > Wow okay.. Kaspersky was blocking LHM.. I tried giving it exclusions, turning off Kaspersky, but nothing worked and now.. Uninstalling Kaspersky has given Fancontrol all of the sensors and such back.. That is really weird seeing as my partner has Kaspersky but no issues on an MSI board.
> > Edit: I have messaged Kaspersky about this issue, but I doubt anything will happen. I will try to periodically install Kaspersky again, but for now will leave it uninstalled.. As I want my fans being controlled and I believe Windows Defender is good enough by itself as long as not downloading dodgy files.
> 
> @SirStew You can add the LibreHardwareMonitorLib.dll file from FanControl to the Kaspersky credit recognition list. And check these options. My English is not good, I hope you can understand it. ![微信截图_20240615061749](https://private-user-images.githubusercontent.com/172461142/339915467-4ce6ab98-1af4-4379-a671-be19abb324e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MDY0MzEsIm5iZiI6MTcxODQwNjEzMSwicGF0aCI6Ii8xNzI0NjExNDIvMzM5OTE1NDY3LTRjZTZhYjk4LTFhZjQtNDM3OS1hNjcxLWJlMTlhYmIzMjRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQyMzAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDQxNDA1MjA5MTdjY2NjNmFlNWJjM2I4YzdlMGFjNmJiNTgxZTMyZWJiZWU1N2Y1NjlkM2QyZjhlYTIxZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9YMLo5nt_gKhdnYKpr6dN9cUP_mBuKkUcYVIVIW3cDI)

@testzhima Did this work for you? I will try it in a bit, will have to allow it for Steelseries folder one too

**Comment by testzhima** [comment]
> > > Wow okay.. Kaspersky was blocking LHM.. I tried giving it exclusions, turning off Kaspersky, but nothing worked and now.. Uninstalling Kaspersky has given Fancontrol all of the sensors and such back.. That is really weird seeing as my partner has Kaspersky but no issues on an MSI board.
> > > Edit: I have messaged Kaspersky about this issue, but I doubt anything will happen. I will try to periodically install Kaspersky again, but for now will leave it uninstalled.. As I want my fans being controlled and I believe Windows Defender is good enough by itself as long as not downloading dodgy files.
> > 
> > 
> > @SirStew You can add the LibreHardwareMonitorLib.dll file from FanControl to the Kaspersky credit recognition list. And check these options. My English is not good, I hope you can understand it. ![微信截图_20240615061749](https://private-user-images.githubusercontent.com/172461142/339915467-4ce6ab98-1af4-4379-a671-be19abb324e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MDY0MzEsIm5iZiI6MTcxODQwNjEzMSwicGF0aCI6Ii8xNzI0NjExNDIvMzM5OTE1NDY3LTRjZTZhYjk4LTFhZjQtNDM3OS1hNjcxLWJlMTlhYmIzMjRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQyMzAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDQxNDA1MjA5MTdjY2NjNmFlNWJjM2I4YzdlMGFjNmJiNTgxZTMyZWJiZWU1N2Y1NjlkM2QyZjhlYTIxZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9YMLo5nt_gKhdnYKpr6dN9cUP_mBuKkUcYVIVIW3cDI)
> 
> @testzhima Did this work for you? I will try it in a bit, will have to allow it for Steelseries folder one too

@SirStew After setting it up like this, FanControl works normally and I have been testing it for a day without any problems.

**Comment by SirStew** [comment]
![avpui_OD0ErDfCpv](https://github.com/Rem0o/FanControl.Releases/assets/171836634/488d6bbe-3e47-4b59-b5c3-f8e1346261e8)
@testzhima Just installed now and will try. I included the english version, you'll have to add the .dll as an exclusion, not just the whole folder of Fancontrol, if you use Steelseries keyboard that uses System Monitor too, you gotta do it for the .dll in that folder too. Will test and will get back about this, hopefully this is a fix and thank you Testzhima.

**Comment by testzhima** [comment]
> Edit: Sadly.. Didnt work for me at all, both on Fancontrol libre dll and where the steelseries keeps it dll for libre.. So no Kaspersky for me till they fix it / a workaround I guess.

@SirStew After setting up, the computer needs to be restarted.
If it still doesn't work, that's really strange. This setting is not a problem with me.
I hope Kaspersky can repair it in the future

**Comment by SirStew** [comment]
> > > > Wow okay.. Kaspersky was blocking LHM.. I tried giving it exclusions, turning off Kaspersky, but nothing worked and now.. Uninstalling Kaspersky has given Fancontrol all of the sensors and such back.. That is really weird seeing as my partner has Kaspersky but no issues on an MSI board.
> > > > Edit: I have messaged Kaspersky about this issue, but I doubt anything will happen. I will try to periodically install Kaspersky again, but for now will leave it uninstalled.. As I want my fans being controlled and I believe Windows Defender is good enough by itself as long as not downloading dodgy files.
> > > 
> > > 
> > > @SirStew You can add the LibreHardwareMonitorLib.dll file from FanControl to the Kaspersky credit recognition list. And check these options. My English is not good, I hope you can understand it. ![微信截图_20240615061749](https://private-user-images.githubusercontent.com/172461142/339915467-4ce6ab98-1af4-4379-a671-be19abb324e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MDY0MzEsIm5iZiI6MTcxODQwNjEzMSwicGF0aCI6Ii8xNzI0NjExNDIvMzM5OTE1NDY3LTRjZTZhYjk4LTFhZjQtNDM3OS1hNjcxLWJlMTlhYmIzMjRlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQyMzAyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDQxNDA1MjA5MTdjY2NjNmFlNWJjM2I4YzdlMGFjNmJiNTgxZTMyZWJiZWU1N2Y1NjlkM2QyZjhlYTIxZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9YMLo5nt_gKhdnYKpr6dN9cUP_mBuKkUcYVIVIW3cDI)
> > 
> > 
> > @testzhima Did this work for you? I will try it in a bit, will have to allow it for Steelseries folder one too
> 
> @SirStew After setting it up like this, FanControl works normally and I have been testing it for a day without any problems.

@testzhima I had restarted, I guess it is hit and miss? I am not sure, I will try again in the morning to make sure, but when I reinstalled this time it saved my exclusion from last time and didnt seem to work, but as I said, will try again and see when I wake up. Shame Kaspersky suddenly broke LHM

**Comment by pcooke9** [comment]
No problems with Kaspersky installed on my system-

[https://github.com/Rem0o/FanControl.Releases/issues/2571#issuecomment-2169073942](url)

**Comment by SirStew** [comment]
> No problems with Kaspersky installed on my system-
> 
> [#2571 (comment)](https://github.com/Rem0o/FanControl.Releases/issues/2571#issuecomment-2169073942)

Will try that too, but I use Kaspersky Premium, dont know if there is a difference or not

**Comment by pcooke9** [comment]
> > No problems with Kaspersky installed on my system-
> > [#2571 (comment)](https://github.com/Rem0o/FanControl.Releases/issues/2571#issuecomment-2169073942)
> 
> Will try that too, but I use Kaspersky Premium, dont know if there is a difference or not
> 
> Edit: Tried your exclusions and such, also tried adding the LHM.dll too, but nothing is working, still getting this- 

The only thing I can think of in Kaspersky Premium that would be any different from Kaspersky Standard would be the "Hard Drive Health Monitor". I think it monitors drive temps. If you have that enabled, try disabling it & reboot.  I doubt that's what's causing it, but it might be worth trying. Simultaneously running multiple apps that monitor or control hardware is generally a bad idea.

**Comment by dalgrim** [comment]
I have the exact same issue.
Windows 11, Kaspersky AV, I7-10700k, Nvidia 4090, MSI Z490Unify board.
Worked fine for years. I have multiple computers that use kaspersky and on Windows 11 that do not have this problem though.

**Comment by Leo-55ru** [comment]
With FanControl turned on and fully configured, when you open any monitoring program FanControl loses all fans and sensors completely.
Tested personally with Aida64, Gpu-z, Cpu-z, Rivatuner, HWiNFO64.
I repeat opening any monitoring program breaks FanControl.
Only a complete reboot of the PC helps.
Any ideas how to fix FanControl?
V193

The point is, it started just a couple days ago.
All of the above software has never conflicted with FanControl, even if you run them all at once.
I've never had this problem before.
I have never had such a conflict of applications.
I don't know what the cause of this behavior is.
Of the latest software updates was FanControl on V193 and the windows 10 update for June 2024.
Rolling back the latest windows 10 update does not solve the problem.
Rolling back the FanControl update to V192 does not solve the problem.
I don't know where to find the problem!

Pardon my English. I translated the text in DEEPL.
![2024-06-15 184455](https://github.com/Rem0o/FanControl.Releases/assets/172894201/c401e97d-bcf9-4fb9-8c8c-0b1b8bce4ae4)

**Comment by dalgrim** [comment]
I can now confirm it is 100% Kaspersky causing this issue. 
Two possible solutions:
1) uninstall Kaspersky and go YOLO on the MS Defender "Antivirus" (not recommended but an option)
OR
2) Follow the steps SirStew mentioned above with a couple of additions:
  a) Open Kaspersky and click Settings gear in bottom left
  b) click Threats and Exclusions
  c) Click "Specify trusted applications"
  d) add BOTH fancontrol.exe AND librehardwarelib.dll as trusted applications. (I don't understand why both are needed either...)
    d1) On the exclusions page be sure to click every box
(optional, was need in my case) Click "Manage Exclusions"
  e) add the FanControl folder and select Protection Components "All components"

After a reboot FanControl works correctly and detects all sensors.

**Comment by SirStew** [comment]
> I can now confirm it is 100% Kaspersky causing this issue. Two possible solutions:
> 
>     1. uninstall Kaspersky and go YOLO on the MS Defender "Antivirus" (not recommended but an option)
>        OR
> 
>     2. Follow the steps SirStew mentioned above with a couple of additions:
>        a) Open Kaspersky and click Settings gear in bottom left
>        b) click Threats and Exclusions
>        c) Click "Specify trusted applications"
>        d) add BOTH fancontrol.exe AND librehardwarelib.dll as trusted applications. (I don't understand why both are needed either...)
>        d1) On the exclusions page be sure to click every box
>        (optional, was need in my case) Click "Manage Exclusions"
>        e) add the FanControl folder and select Protection Components "All components"
> 
> 
> After a reboot FanControl works correctly and detects all sensors.

I have finally fixed it using this. But I have also double downed and added each .dll and folder too.. So far it works for my Steelseries keyboard and Fancontrol.
![avpui_cPlwe77ow8](https://github.com/Rem0o/FanCo
![avpui_6nEdfolXUP](https://github.com/Rem0o/FanControl.Releases/assets/171836634/9c236ca3-8f94-4226-a82d-372e0a201a9e)
ntrol.Releases/assets/171836634/4f78c087-86fb-4a6f-b929-55d8b84d8ab6)
![avpui_Mjm08wZJ2g](https://github.com/Rem0o/FanControl.Releases/assets/171836634/daa626f5-2467-46fe-b1e5-40827cae7568)
![avpui_FECM8JBQX4](https://github.com/Rem0o/FanControl.Releases/assets/171836634/12689c5b-bc4a-415a-a34c-4bac94640bc9)

So now this is working, but as I said I added pretty much the .dlls and fancontrol twice with the folders and the application to make sure it did work. But.. Hopefully this stays working and it works for others too!

**Comment by dalgrim** [comment]
> So now this is working, but as I said I added pretty much the .dlls and fancontrol twice with the folders and the application to make sure it did work. But.. Hopefully this stays working and it works for others too!

Seeing as this is a Kaspersky issue; you, and everyone else having this issue, should report it to Kaspersky. I think Vulnerability@kaspersky.com is their bug report e-mail.

**Comment by SirStew** [comment]
> > So now this is working, but as I said I added pretty much the .dlls and fancontrol twice with the folders and the application to make sure it did work. But.. Hopefully this stays working and it works for others too!
> 
> Seeing as this is a Kaspersky issue; you, and everyone else having this issue, should report it to Kaspersky. I think [Vulnerability@kaspersky.com](mailto:Vulnerability@kaspersky.com) is their bug report e-mail.

I have already emailed them, but will email that email too.

**Comment by Cina-1** [comment]
Adding all of the folders, dll's, and the exes like SirStew did has solved the issue for me. I had paid the $5 to use SignalRGB in case a fix took longer, but it's odd that Kaspersky had no issues with that program. Hopefully, a proper fix will come from Kaspersky soon, but I'm happy I can use Fan Control again.

**Comment by pcooke9** [comment]
I saw this over on the Kaspersky Forums. It seems Kaspersky did acknowledge and fix a problem. Strange that my system wasn't affected, but I do ALWAYS add everything hardware related to be FULLY excluded in any AV I use. I've had a lot of similar issues with other apps in the past, so now I just do it reflexively.

https://forum.kaspersky.com/topic/kaspersky-plus-sensor-reading-rgb-control-bug-48327/

**Comment by Leo-55ru** [comment]
Updated Kaspersky databases and rebooted the pc. Everything worked. There are no program conflicts and I don't think there were any. Kaspersky assholes.
I apologize for the emotion! But what the fuck was that! Kaspersky has once again fucked up its reputation.

**Comment by LinuxIsAlmostGood** [comment]
Tried to fiddle with Kaspersky's exclusions and trusted apps- nothing worked.. Then found out that they just dropped a patch a couple of hours ago, updated, restarted. Now Fan Control just works. Double checked by disabling FC's exclusions and trusted app in Kaspersky- still working. I guess it just was a bug they havent noticed in time.

Valuable system info
X570 Tomahawk Wi-Fi
Ryzen 9 5900X
Radeon 6950XT
32Gb Memory Micron Rev.B
A pair of NVMe SSDs

**Comment by SirStew** [comment]
I'll close this thread as it is fixed by Kaspersky officially now! Thank you all for trying to find solutions and finding some, and ofc now with a fix we don't gotta worry too much.

**Comment by dalgrim** [comment]
Well whatever Kaspersky pushed out re-broke mine. The exclusions no longer work and the /lpc/* sensors are controls no longer function.
