### ISSUE TITLE
Problems when only monitoring/controlling GPU fan - only GPU mode needed

### ISSUE THREAD

**Issue by d-e-n-n-i-s-t** [Rem0o/FanControl.Releases#2567]
I recently moved the controlling of my CPU and case fans to the BIOS. I still want to use FanControl for my GPU fan, but there are some bugs which I encountered.
When only choosing GPU like this on the setup:

![image](https://github.com/Rem0o/FanControl.Releases/assets/67392973/1e9a5895-c007-4d70-838d-1e566271ec79)

I get this warning:

![image](https://github.com/Rem0o/FanControl.Releases/assets/67392973/29e22ea8-4bc9-46c8-a334-3e1ede2ffa34)

After continuing, I get the following errors:

![image](https://github.com/Rem0o/FanControl.Releases/assets/67392973/e1d827e0-4af9-403b-8072-3f6875086848)

Understanding the message, I manually remove every case/CPU "Control" and "FanSensor" from my config via a text editor.
So far so good, I could life with this manual setup process. But now, on every start up, I get this warning:

![image](https://github.com/Rem0o/FanControl.Releases/assets/67392973/bfc2f993-7a66-4efb-86ce-fc3c1db85f46)

This warning also un-minimizes the application (so it pops up after every system reboot)

Is there a way to alter this behavior and properly introduce a GPU only behavior? Basically there's a need to modify the config file automatically when only selecting "GPU" on the setup (Sensor settings, first image) and the warning needs to be suppressed when having only GPU selected.

**Comment by ionGL** [comment]
Uncheck the GPU also. You will have the NvApiWrapper for the GPU.

**Comment by d-e-n-n-i-s-t** [comment]
> Uncheck the GPU also. You will have the NvApiWrapper for the GPU.

Is "GPU" only for AMD GPUs then? Seems counterintuitive to uncheck GPU when all I want to do is control my GPU fans

**Comment by ionGL** [comment]
Left part of the sensor settings window is for librehardwaremonitor sensors on/off. In your case, if you have an nvidia card and NvApiWrapper works, you can use only that instead of librehardwaremonitor.
I'm in the same situation, only using the program to control the gpu fans. Here is how i roll.
![1](https://github.com/Rem0o/FanControl.Releases/assets/80151979/2900eb05-7461-4888-9c08-446579ed7508)

![2](https://github.com/Rem0o/FanControl.Releases/assets/80151979/8d188e4f-beaf-4de9-a7f6-8ac8ce1d5d89)

**Comment by d-e-n-n-i-s-t** [comment]
> Left part of the sensor settings window is for librehardwaremonitor sensors on/off. In your case, if you have an nvidia card and NvApiWrapper works, you can use only that instead of librehardwaremonitor. I'm in the same situation, only using the program to control the gpu fans. Here is how i roll. ![1](https://private-user-images.githubusercontent.com/80151979/339094052-2900eb05-7461-4888-9c08-446579ed7508.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTg1NTgsIm5iZiI6MTcxODIxODI1OCwicGF0aCI6Ii84MDE1MTk3OS8zMzkwOTQwNTItMjkwMGViMDUtNzQ2MS00ODg4LTljMDgtNDQ2NTc5ZWQ3NTA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE4NTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5N2U0NTUwZjEwMjQ0ZGFiMmJkOTlkNzFjOTVkZmE4NWFlYTNhYzRlODRhN2YzNTEzOWE1MmUzMzUxMWE0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZUJpvEUMXkhQygJVe9tttdM0ympPnADqwM7aSyV3rs)
> 
> ![2](https://private-user-images.githubusercontent.com/80151979/339094062-8d188e4f-beaf-4de9-a7f6-8ac8ce1d5d89.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTg1NTgsIm5iZiI6MTcxODIxODI1OCwicGF0aCI6Ii84MDE1MTk3OS8zMzkwOTQwNjItOGQxODhlNGYtYmVhZi00ZGU5LWE3ZjYtOGFjOGNlMWQ1ZDg5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE4NTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2N2JiMTZmYTAyMDcyYjliMzM0Zjk3ZGQzMDg3YjJlYmY0YTBkNmI4M2UwMWFmNjdiZjBhNzg0MjIxYjczM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EErcW3azX1mMU2-EogmakIRjhPyoKUhg1OhLNIn6YBc)

Sweet! Thanks for the info :)
