### ISSUE TITLE
GPU hotspot temp not detected

### ISSUE THREAD

**Issue by Joeeeeb5** [Rem0o/FanControl.Releases#2569]
**Describe the bug**
GPU hotspot isnt being detected (everything is enabled in the settings) 
![image](https://github.com/Rem0o/FanControl.Releases/assets/125207782/de19024a-b66b-4c34-9e60-56de14940bbc)

**Relevant hardware specs and setup**
GPU: Gigabyte RTX 3060 vision oc rev2

**Comment by ionGL** [comment]
You need the [NvThermalSensors](https://github.com/TimSirmovics/FanControl.NvThermalSensors) plugin for that.

**Comment by Rem0o** [comment]
Or use the LHM "GPU" section by unchecking the NvAPIWrapper one.

**Comment by Joeeeeb5** [comment]
thanks, fixed
