### ISSUE TITLE
4080 Super Fans won't 0 RPM anymore

### ISSUE THREAD

**Issue by boat371** [Rem0o/FanControl.Releases#2570]
I'm not sure if it's since the latest update but my GPU Fans won't 0 RPM anymore, it was working until recently. Sometimes after I reload the software and close things and whatnot it'll work, but after the GPU Fans turn on they won't 0 RPM by themselves anymore.

![image](https://github.com/Rem0o/FanControl.Releases/assets/172622018/f718cea3-f07c-425b-b20e-a2b7521c2cb2)

**Comment by ionGL** [comment]
Try: Settings, edit sources, Nvidia 0% hardware curve override enabled/disabled.

**Comment by boat371** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/172622018/960a42f0-47cf-4419-b4ee-972d539fedc9)

its always been enabled

**Comment by ionGL** [comment]
Seems like some cards don't like when software messes with the fan controller and disables the 0 rpm feature.
You might need to give up on controlling the gpu fan and let the bios do its thing, or connect the gpu fans to a motherboard header and regain complete control.

**Comment by ionGL** [comment]
Seems like some cards don't like when software messes with the fan controller and disable the 0 rpm feature.
You might need to give up on controlling the gpu fan and let the bios do its thing, or connect the gpu fans to a motherboard header and regain complete control.

**Comment by Rem0o** [comment]
If you disable the control all together, does it go 0 RPM eventually by itself? Because that's what FanControl relies on, for it to go 0 RPM by itself.  It can't force it.

**Comment by boat371** [comment]
sorry, maybe this is a stupid question but how would i disable control, by just quitting the app?

**Comment by ionGL** [comment]
In the main window, on the gpu fans control cards, move the "lever" to the left.

**Comment by boat371** [comment]
no, it doesnt seem to 0 RPM by itself, I did realise I recently got a second monitor and I believe the issue started happening around the same time. is it possible that it has something to do with that?

**Comment by Rem0o** [comment]
Yes the second monitor increases the idle load of the gpu enough to keep it outside its 0 rpm operating range.
