### ISSUE TITLE
Can't control the fan speed of ASUS 7700XT DUAL

### ISSUE THREAD

**Issue by abcdehc** [Rem0o/FanControl.Releases#2572]
**Describe the bug**
FanControl V193  can not control the fan speed of ASUS 7700XT DUAL.
it can detect the speed of this GPU's fan,
but when it try to control the speed of this fan,
the fan speed will become 0,
even i tried set the "force apply".
the other softwares doesn't have this problem,
i tried ASUS GPU-Tweak-III V1.7.7.0 and AMD Software: Adrenalin Edition,
they can control the fan speed curves.
(by the way, for sure, only one software is used at a time）

**Relevant hardware specs and setup**
COLORFUL BATTLE-AX B650M-WHITE WIFI V14
DUAL-RX7700XT-O12G

**Comment by Rem0o** [comment]
This: https://github.com/Rem0o/FanControl.ADLX
