### ISSUE TITLE
No tray icons after changing to installer setup

### ISSUE THREAD

**Issue by sypher-66** [Rem0o/FanControl.Releases#2574]
Hi, i used the portable setup for a while and everthing was working as expected.  i decided to remove that and setup again using the installer but since then i can't get any tray icons to appear.  i've uninstalled and reinstalled and even tried the portable install again but nothing is working.  any suggestions to get this working again or how i can troubleshoot the issue.  I've tried running procmon when i add the tray icon in the application but nothing appears to be getting blocked or failing.

**Comment by Rem0o** [comment]
It might appear in this section:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/ab652651-eadb-4316-a6ea-87c919824e1a)

**Comment by sypher-66** [comment]
no sorry. its nothing so simple unfortunately
![image](https://github.com/Rem0o/FanControl.Releases/assets/172839068/51954443-821f-4573-ad35-2b1929ce7445)

**Comment by Rem0o** [comment]
Maybe take a look here:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/b917cb53-32fc-43a8-bed9-df24e0bebfc7)

**Comment by sypher-66** [comment]
yeah that was it thank you
