### ISSUE TITLE
why CPU_OPT can't be detected？

### ISSUE THREAD

**Issue by Jebynn** [Rem0o/FanControl.Releases#2578]
cpu_fan and aio_pump both detected correct
but cpu_opt is missing
how could this happen？
I'm confused.
![11](https://github.com/Rem0o/FanControl.Releases/assets/25218251/ad4a8f96-c549-4540-9441-7882fa3bdc42)

**Comment by Rem0o** [comment]
Motherboard support may not be 100% perfect for every model:
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.
