### ISSUE TITLE
Install issue Windows 11

### ISSUE THREAD

**Issue by MrTmint** [Rem0o/FanControl.Releases#2585]
Unable to run any install exe on Windows 11

I have updated .NET framework 8.0 I have tried both versions for 8 and 4.8 

PC is AMD 5600x running most recent Windows 11 update.

**Comment by Rem0o** [comment]
Could you describe what you mean by "unable" ?

Can't you run the portable version ? 
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/ecce1262-7f6b-4645-81ca-e518f57d4a59)

**Comment by MrTmint** [comment]
I have tried the Installer Versions and Portable Versions and I am unable to get the .exe to run or open for installation or running of the program which is rather odd and I have never come an issue like this.

**Comment by MrTmint** [comment]
> Could you describe what you mean by "unable" ?
> 
> Can't you run the portable version ? ![image](https://private-user-images.githubusercontent.com/14118956/342077613-ecce1262-7f6b-4645-81ca-e518f57d4a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTk1NjgsIm5iZiI6MTcxOTI1OTI2OCwicGF0aCI6Ii8xNDExODk1Ni8zNDIwNzc2MTMtZWNjZTEyNjItN2Y2Yi00NjQ1LTgxY2EtZTUxOGY1N2Q0YTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIwMDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMDNiODVkNTU0ZWIzNGY0NzQyNTRjMjAwMTZiYjNlYzBiODUyNzliOTk4NjIzNDljZjgyY2ZiMGQxZTM1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0MG4-LiMUf8Qu7bSyCaM76zt7qmwL3HBMQtY6FVo_bs)

It's ok apparently I am that out of touch Windows was blocking the software and I had to click a Check box my apologies.

**Comment by MrTmint** [comment]
It's ok apparently I am that out of touch Windows was blocking the software and I had to click a Check box my apologies.
