### ISSUE TITLE
Feature: Ability to configure different curves for Ramp Up and Ramp down

### ISSUE THREAD

**Issue by ct384** [Rem0o/FanControl.Releases#2587]
**Feature**
Not sure if it is already possible, but is it possible to have two separate curves for Temperature Increase to load and Temperature Decrease back to idle?
For example, I would like to have a GPU Curve set to 0% until 55C and then ramp up the fan percentage appropriately. But on the way back to idle temps, I would like the fan still run at some percentage until temps reach 40C, sort of like set-point for an enhanced cool down period.
**Curve to Load:**
![image](https://github.com/Rem0o/FanControl.Releases/assets/26100177/85ba2928-3c8c-4de2-a069-17ec36eb043c)

**Possible Curve to Idle**
![image](https://github.com/Rem0o/FanControl.Releases/assets/26100177/e7868c9e-2e43-44b9-8618-6ee73fdf0eb3)

**Comment by Rem0o** [comment]
Already possible, do it like this:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/c02a956b-7a41-4406-bf7a-50699f31d9bf)

**Comment by ct384** [comment]
Yup this was exactly what i was looking for! Thanks for the quick reply!
