### ISSUE TITLE
Nvidia GPU fans only applying curve above 50%

### ISSUE THREAD

**Issue by thewalkingfruit** [Rem0o/FanControl.Releases#2592]
**Describe the bug**
First of all, its worth mentioning that this only started after I launched MSI afterburner while fan controller was running and there was a conflict of control, I did turn them to auto mode, but this "issue" happens whether or not I have MSI afterburner on or not.

If the graph that my GPU fans are linked to is commanding it to be above 50% all 3 fans work fine, if its below, one of the controls (for 2 fans) shows conflict and stays at 0RPM, the other works sometimes, sometimes not.

 First picture showing me using a graph that starts at 50% to show what it looks like when its working (named Graph):
![image](https://github.com/Rem0o/FanControl.Releases/assets/104994445/9fddf781-aa4c-4b33-9fd9-93a833d0333f)

Second picture when using a graph that starts at 30% (named GPU Temperature):
![image](https://github.com/Rem0o/FanControl.Releases/assets/104994445/53ad7dd4-5169-4ab2-bc6b-da6e2f8cb1c6)
As you can see both fans now show a "?" and are stuck at 0RPM, i have managed to get one of them working but never both controls.

This worked perfectly before for many months, but today MSI afterburner seems to have broken it, I have tried multiple uninstalls, running the assisted setup, calibrating the fans, none of which worked.

Also worth showing what my sources look like:
![image](https://github.com/Rem0o/FanControl.Releases/assets/104994445/6f1296b0-613a-4835-878e-06f0b378b623)

**Relevant hardware specs and setup**
Gigabyte RTX 3060 Gaming OC

**Comment by Rem0o** [comment]
What's the start and stop % on both controls?

**Comment by thewalkingfruit** [comment]
> What's the start and stop % on both controls?

This is what it looks like, values left untouched from the assisted setup
![image](https://github.com/Rem0o/FanControl.Releases/assets/104994445/ad385202-1580-461b-ab90-9f7447478e6b)

**Comment by ionGL** [comment]
Set both start and stop % at 0 and then see how it behaves.

**Comment by ionGL** [comment]
You might remember wrong and 30% could be too little juice for the fans to be able to spin, if 51.4% represents ~1000 RPM.

Set them to 49%, wait, note the rpm. Go to 48, 47% and so on, until the rpm is no longer stable and you will see it tend to go to 0.

Do a video.

**Comment by thewalkingfruit** [comment]
> You might remember wrong and 30% could be too little juice for the fans to be able to spin, if 51.4% represents ~1000 RPM.
> 
> Set them to 49%, wait, note the rpm. Go to 48, 47% and so on, until the rpm is no longer stable and you will see it tend to go to 0.
> 
> Do a video.

You might be right, it's weird I never noticed that since I always had my GPU curve start at 30% and it was fine, but I forgot to mention I did switch GPU's 2 weeks ago so it might be that my new card cant go below 40% whereas my old one could go up to 30%, video here https://youtu.be/au_lCrQ6aW0?si=hW0mlHQxvV6BCKFm

**Comment by thewalkingfruit** [comment]
> There you go! Different gpu fans have different fan maps. Some spin at 30%, some need over 40%. Your map is better, as you can access very low RPMs with ~45-42%. Newer cards have 30% as the lowest possible %, and that 30% translates to 1000 RPM. Crazy.
> 
> If you care about rpm graphs, open the calibration for both fans (btw, confirm fan 1 behaves the same) and add desired points, 41, 42, 43, 45, 50, 55, .. 100. Even if you don't care, write all the values down in a .txt so you know what RPM corresponds to whatever fan %.
> 
> You can go the other way and find what % is needed to starts each fan. Set it to 0%, wait, then go to 41% and confirm they turn and stay on.
> 
> Do you want to use the 0 RPM feature in a graph? If you do, set start % to 50. This would set the fan % at 50% for a few seconds when starting from zero, to put in motion reliably. It would quickly return to 42% if that is your first graph point. As 40% is where it turns off, set stop % to 40.
> 
> If you don't use a graph where the fans turn off, work around what you found now. I would ignore the first few points over 40 and have 43 for as the lowest point and go up from there.

Thank you I really appreciate your help, I will tune it in the next few days to find what I think works best for me, thanks again!
