### ISSUE TITLE
Calibration and hidden card issue

### ISSUE THREAD

**Issue by vertigo220** [Rem0o/FanControl.Releases#2596]
I installed this and ran it without the initial setup, then ran it shortly after. Not sure if that has anything to do with it, but after running the setup, it only detected the CPU fan, but not the system fan. So I had to run the "Pair controls and speeds automatically" again in order for it to pick up the system fan, after which it was "hidden" (really subdued/faded), and it took me a minute to figure that out, as I thought it was actually disabled. So I'm not sure why it took two attempts to get it to see the system fan, or if there's any way to figure that out (I don't see any log options), but at the very least it seems it should either auto-show (unhide) or ask if the user wants to show a new fan that's hidden.

**Comment by Fr0stX76** [comment]
Seriously? Why not just create one thead for all your questions/issues? 

This is a bit much...

**Comment by Rem0o** [comment]
Hidding/unhidding only works from the full assisted setup, indeed not from the individual step.  Will make it work for both ways in the next release.

**Comment by Rem0o** [comment]
V195
