### ISSUE TITLE
FanControl doesn't work below 52%

### ISSUE THREAD

**Issue by tweety3d** [Rem0o/FanControl.Releases#2598]
**Describe the bug**
When I set anything below 52%, RPMs are just randomly jumping all around. I've tried with Nvidia 0% override and without.
I've tried with force and without.
I don't have Gigabyte Control Center installed.
I've tried calibrating, but it just doesn't make sense. For 51% should I put 0 RPM and for 52% around 900 RPM?
Video attached. 
[Video](https://github.com/Rem0o/FanControl.Releases/assets/1300764/49b38f0a-427e-4dca-a058-8d752d692edd)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Only thing log.txt says is "LibreHardwareMonitor could not initialize or has no sensors." for each app run.

**Relevant hardware specs and setup**
dxdiag attached. GPU is GIGABYTE GeForce RTX 4070Ti
Gaming OC 12GB (GV-N407TGAMING OC-12GD).
[DxDiag.txt](https://github.com/user-attachments/files/16044550/DxDiag.txt)

**Comment by ionGL** [comment]
Unfold the control cards and check start, stop, minimum %.

**Comment by tweety3d** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/1300764/6a50279e-0356-4d83-972d-b00d32f71b1a)

Below 52% fans are spinning on very low speed, occasionally speeding up for a second, but still on very low speed.
"Feels" like below 52% the card itself "takes control" and just spins the fans just to keep them alive.

**Comment by thewalkingfruit** [comment]
I believe our issues are related https://github.com/Rem0o/FanControl.Releases/issues/2592

**Comment by Rem0o** [comment]
This seems something out of FanControl's control's (no pun intended).  The % shown is a readback value from the card, so the control % value is applied.

One thing I'm curing about, in sensor settings, uncheck NvApiWrapper, and make sure "GPU" is checked on the left. Press "OK" but don't save anything, this will break your config.  Now with the new GPU control card, do the same procedure you did here. Same result?

**Comment by ionGL** [comment]
You need to find out this important detail: Are you able to set 0% and have the gpu fans stay at 0% no matter the temp? Disable the Nvidia 0% override thing and try that.
If you are able to have 0% at any temp, great.
Set start % at 52, stop % at 51 and build a graph around that. Manually calibrate the fans with 51% at 0 RPM, 52% at 978 RPM, 55% at whatever and so on in increments of 5%.

I'm guessing you want to have the fans off until a certain temp, then start spinning at the lowest rpm possible, 978 with 52% in your case and go up as needed. Something like this.
![gpugraphrpm](https://github.com/Rem0o/FanControl.Releases/assets/80151979/277f9014-88e8-44f1-9a92-dd614e30ea7c)

**Comment by tweety3d** [comment]
I've tested and I am able to keep 0 RPM (at 0%) no matter the temp (I mean, I've tested up to 65C).
I'm fine with the settings now, I can either set it to 53% for any temp below 50C (it's 900 RPM, basically silent), or to 0%, and then start at 53% from 50C and rise to 70% at 65C or something.
Anyhow, works for me :)
I actually wonder what does calibration do? Does it change anything?

**Comment by ionGL** [comment]
Calibration is needed to use curves in RPM mode. You are giving Fan Control information about each fan map. What RPM represents a %. This way, using an RPM curve, you would set points at 1000, 1200, 1400 RPM etc. The program would know what % to set for each RPM without you bothering. Just open the calibration window and do it manually. Select 52%, wait a bit for the fan speed to stabilize, hit add. Do the same for 53, 54, 55%, then go in steps of 5. See here: https://github.com/Rem0o/FanControl.Releases/discussions/2333

**Comment by Rem0o** [comment]
@tweety3d  [calibration](https://getfancontrol.com/docs/)
