### ISSUE TITLE
Pairing a Control with a sensor does nothing

### ISSUE THREAD

**Issue by thegame4craft** [Rem0o/FanControl.Releases#2600]
**Describe the bug**
Same thing as https://github.com/Rem0o/FanControl.Releases/issues/2370 in V194

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/user-attachments/files/16127026/log.txt)

**Relevant hardware specs and setup**
Same as in linked issue

**Comment by thegame4craft** [comment]
In the time between it worked, but now it wont work (again)

**Comment by Rem0o** [comment]
Same questions as the last issue you opened.  Does it do the same for all controls or only this specific one?

**Comment by thegame4craft** [comment]
Yes the error occours for all controls inside fancontrol. And yes this is the same, because the last issue were closed and i wrote on it but i got no response

**Comment by Rem0o** [comment]
Does automatic pairing works?

**Comment by thegame4craft** [comment]
No same like normal pairing. 

And i found another issue when Fancontrol is used together with HWMonitor, I get often the message 22 of 23 sensors found and then fancontrol just doesn't respond. Only solution is to kill fancontrol and try it again
![grafik](https://github.com/Rem0o/FanControl.Releases/assets/48205247/6094fc75-de54-4425-8446-f7b15a57fb4d)

**Comment by thegame4craft** [comment]
I now did this manually in the config file there it works. Calibration doesn't have an issue only pairing
