### ISSUE TITLE
Feature request: Sync Curve .1% precision

### ISSUE THREAD

**Issue by Marius8** [Rem0o/FanControl.Releases#2602]
I'd like to request the change of the Sync Curve to have a .1% precision.
meaning if the 'Control' Fan has the target speed of e.g. 54.3%, and the offset in the sync is +5%, the sync should have 59.3%.
currently the Sync Curve has a precision of 1%

**Comment by Rem0o** [comment]
The actual underlying value of the percent is a 8 bit value, there isn't "real" 0.1% precision, hence the small difference.
