### ISSUE TITLE
After updating to version 195, there is still a problem with the taskbar icon（I recorded a gif）

### ISSUE THREAD

**Issue by LRJuuu** [Rem0o/FanControl.Releases#2603]
**After updating to version 195, there is still a problem with the taskbar icon，the taskbar icon color setting is not automatically saved. When the system switches themes, you will be prompted to save the setting when you open fancontrol. If you do not choose to save (This setting is not saved by default after the computer is restarted or woken up from sleep mode.), the taskbar icon color will return to the original color. You can only open fancontrol again to turn on "sync theme with windows" or "sync icon color with windows" again.**

When turning on the Sync theme with Windows function，after a system theme switch, although fancontrol will synchronize the interface theme fancontrol interface is still out of sync after restarting the computer.
According to my observation, this problem actually occurs because when the system switches between dark and light modes, although fancontrol also synchronizes the interface theme at the same time, it does not save this setting. When you open fancontrol and close it, you will be prompted to save the settings.
So in my opinion, the setting for switching between dark and light interface colors can be separated into a configuration file and then enable automatic saving, which will solve the problem.
Maybe you have a better way to solve this bug. I hope it can be solved as soon as possible. Thank you.

(Sorry, I don’t speak English very well. This is through Google Translate. I hope you can understand what I expressed)
![PixPin_2024-07-11_06-30-07](https://github.com/Rem0o/FanControl.Releases/assets/46359246/38a3b328-b0cb-43e0-948b-e5eacddd45ee)
![PixPin_2024-07-11_06-44-10](https://github.com/Rem0o/FanControl.Releases/assets/46359246/9ae13c68-55c2-48f8-bb47-4eb96332229e)

**Comment by LRJuuu** [comment]
https://github.com/Rem0o/FanControl.Releases/issues/2562
There is a similar question here. I have replied to him before. It has been a month since this discussion.

**Comment by Rem0o** [comment]
The saved theme is not "dark" or "light" if sync is enabled. You got to save the sync checkbox once though.

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/8774b861-ec5a-4856-b2f2-5d265f80d32c)

**Comment by LRJuuu** [comment]
![PixPin_2024-07-11_06-30-07](https://github.com/Rem0o/FanControl.Releases/assets/46359246/18abbe47-6cb0-4e60-bbd6-ff587c78c09a)
I recorded a gif and you can check it out

**Comment by Rem0o** [comment]
Ahhh it's the tray icon color. Will fix.

**Comment by Rem0o** [comment]
V196

**Comment by LRJuuu** [comment]
> V196

Thanks, it's perfect now
