### ISSUE TITLE
V195 ADLX built it Wrong AMD GPU label

### ISSUE THREAD

**Issue by benshalev849** [Rem0o/FanControl.Releases#2606]
After updating to V195 with the built it ADLX AMD GPU support, label is wrong.

The 7900XTX is displayed as "AMD Radeon(TM) Graphics (1)"
![image](https://github.com/Rem0o/FanControl.Releases/assets/87974262/4de16316-1647-46ee-9639-2e1dda3384d6)

I can confirm it's indeed the XTX and not the CPU IGPU by seeing the hotspot on adrenalin (for the 7900xtx) match the hotspot displayed by fancontrol.
A seen here:
![image](https://github.com/Rem0o/FanControl.Releases/assets/87974262/68129e35-7b7a-4c6b-868d-c7409d6b4390)

NOTE: The GPU fans ARE being properly controlled by fancontrol (tested with 100% and 0% to see it works) but just not displayed.
No broken fan control, only label issue.

Steps to reproduce:
1) Have AMD IGPU+"external" GPU
2) Remove old ADLX plugin
3) Update to fancontrol version V195  
4) Enable ADLXWrapper in sources settings
5) Scan for sensors
6) Create a graph and choose "temperature source", there it will be wrong label.
7) Make sure with adrenalin that values are wrong.

Ty for this program, you are awesome <3

**Comment by rhomble** [comment]
I'm having the same issue.

**Comment by Rem0o** [comment]
Found the problem. Will fix.
