### ISSUE TITLE
Time Average sensor showing the wrong value on start

### ISSUE THREAD

**Issue by chjohans** [Rem0o/FanControl.Releases#2608]
There seems to be a bug with the time average custom sensors. I have a temp sensor that measures my intake air temp, and another that measures the ambient air temp in my chassis. I notice that when I start FanControl these both show very low values (initially zero or close to zero) that slowly increase until I reach the sensor's "Time value" after starting FanControl. It seems to me like it's trying to calculate an average for the "Time" period even if FC has not been running for a period equal to or greater than what "Time" for the sensor is set to, and it looks to me like it's using the value "0" for the period it doesn't have any data for (eg before FC was started). It should not try to average a longer period than the time FC has been running if that is shorter than the configured "Time" for the sensor. It looks to me like that's precisely what it's doing now.

I have reported a somewhat similar bug in the past where it would show "NaN" until "Time" was reached when FC was started, but that was fixed quite some time ago.

**Comment by Rem0o** [comment]
Might said sensor report 0 once on startup?

**Comment by chjohans** [comment]
I honestly don't know, they are temp sensors on a Corsair Commander Pro, and I'm using the excellent plugin by Evan Mulawski for Corsair stuff.

**Comment by Rem0o** [comment]
I suspect the initial state of the sensor is 0, hence why you get this effect.

**Comment by chjohans** [comment]
That might be, but if it only reports 0 degrees during the very first read cycle the average should ramp up fairly quickly. The "real" sensor was reading 25.9 degrees when I started FC just now. I have a custom average time sensor with that sensor as input, and it's set to average 120 seconds. It takes just about 120 seconds after start for it to reach roughly the same temp as the "real" sensor, and during those 120 seconds it just slowly increases by a few tenths of a degree every second. Not sure how you do the average here but if it had one 0 reading when FC starts, I would expect the average to be half way between 0 and the "real" sensor value already the next reading cycle, eg after a second or so. And then to ramp up slower and slower until it reaches 120 seconds. But I see a pretty linear increase in the average temperature until it reaches the "real" sensor value.

**Comment by Rem0o** [comment]
Took a deeper look. The first perceived value was spread over the entire buffer as if it lasted for "120 seconds". Thus why you got the described effect.   
I will change how it handles the first "N" seconds with the averaged value so that it averages out 1 value, 2 values, 3 values... until N.   It doesn't impact performance also.

**Comment by Rem0o** [comment]
V196

**Comment by chjohans** [comment]
Thanks, @Rem0o, that totally explains what I observed. Your dedication to improving FanControl is much appreciated!
