### ISSUE TITLE
Option to completly hide tray icon

### ISSUE THREAD

**Issue by kladnik** [Rem0o/FanControl.Releases#261]
Hello!

Right now there is no option to hide the stock tray icon as well.
It would be very useful to hide it.

Thanks!

**Comment by Rem0o** [comment]
Then how would you access the program when you close the window?

**Comment by kladnik** [comment]
Launch the program with the `.exe` or shortcut. Same as other programs.

**Comment by Rem0o** [comment]
The program still runs when the window is closed, it's a background application.

**Comment by kladnik** [comment]
I know. Would running the program again start a new instance instead of opening the current one?

**Comment by Rem0o** [comment]
Yes, but it is prevented with a mutex as 2 running instances would bug each other.

**Comment by kladnik** [comment]
Ah okay, then I guess there is no way of handling this currently. Will close the ticket then

**Comment by JKawmi** [comment]
I would also love an option to hide the tray icon!
Currently, I am running the program as a service to hide the icon but would love to have this option from within the app itself

**Comment by Spuner** [comment]
Yes, I would like to see such a feature in the profile settings - to have the icon hidden on one profile and not on the other.
