### ISSUE TITLE
Fan sensors don't work on special graphics cards

### ISSUE THREAD

**Issue by rhine14586** [Rem0o/FanControl.Releases#2611]
My graphics card is an old half-height graphics card with a mini 3-pin connector between the fan and the card, and the software can detect the real-time speed ratio of the graphics card fan, but not the fan speed (the software shows 0 rpm, which is of course true because there is only a 3-pin connector here).
I would like to ask if it is possible to control the fan speed according to the speed ratio without fan speed or if it is also possible to control the speed by the DC voltage adjustment.

**Comment by rhine14586** [comment]
![image](https://github.com/user-attachments/assets/514d6952-0452-4b34-95b0-24e0516a55dd)

**Comment by rhine14586** [comment]
I've heard that in some motherboard bios screen there will be a DC speed control method, but it's not in my motherboard bios, so I'm trying to find a solution in this software

**Comment by Rem0o** [comment]
3 pins should report RPM.  That's what the 3rd pin is for. If it doesn't report anything, sorry to say not much can be done.
