### ISSUE TITLE
Couldn't initialize ADLX on v196

### ISSUE THREAD

**Issue by rameel** [Rem0o/FanControl.Releases#2613]
After updating to version 196 from version 194, I got an error on startup. All my configuration files were deleted, and no sensors are being detected.
```
14.07.2024 6:13:39: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper..ctor()
   at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open()
14.07.2024 6:13:41: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper..ctor()
   at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open()
14.07.2024 6:13:41: ADLXWrapper could not initialize or has no sensors.
```

Ryzen 5900X
Motherboard: MSI MEG X570

**Comment by Rem0o** [comment]
FanControl doesn't delete configurations.   If it's been overwritten, lookup the "backup" folder inside the configuration folder.

As for ADLX, you are getting a ADLX_FAIL error code.   What's your GPU/driver situation.

**Comment by killia999** [comment]
having the same issue, just logged in from some days offline, accepted the 196 update, on reinitialization I get an error that says: "These errors occurred while restoring the configuration:

-Missing speed sensor: ADLX / ADLX / AMD Radeon(TM) Graphics/22784/fan - AMD Radeon(TM) Graphics
-Missing speed sensor: ADLX / ADLX / AMD Radeon RX 7900XTX/768/fan- AMD Radeon RX 7900XTX
-Missing control sensor: ADLX / ADLX / AMD Radeon RX 7900XTX/768/Control - AMD Radeon RX 7900XTX

If this error occurs at startup, try increasing your startup delay.

I am win10 pro AMD 7900XTX running driver 24.5.1 (24.6.1 is current but breaks some games I currently play)

**Comment by rameel** [comment]
Unfortunately, all the configuration files were deleted and no backup was made.

**Comment by Rem0o** [comment]
Are you using the installer version or portable?  Did you update through the built-in updater or you downloaded it seperatly?

**Comment by rameel** [comment]
I use the portable version and update it using the built-in updater.

**Comment by Rem0o** [comment]
What's your GPU? Is it an RDNA generation GPU?

**Comment by rameel** [comment]
AMD RX 6600

**Comment by Rem0o** [comment]
Driver version?

**Comment by dkdirekt** [comment]
Same here, driver version is Adrenalin v24.6.1

**Comment by agnulf** [comment]
I have the same problem.
FanControl v196 portable on Windows 11.
GPU: RTX 4070
Driver: 560.70

`2024-07-19 13:08:18: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper..ctor()
   at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open()
2024-07-19 13:08:20: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ADLXWrapper..ctor()
   at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open()
2024-07-19 13:08:20: ADLXWrapper could not initialize or has no sensors.`

**Comment by Fr0stX76** [comment]
> I have the same problem. FanControl v196 portable on Windows 11. GPU: RTX 4070 Driver: 560.70
> 
> `2024-07-19 13:08:18: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL Couldn't initialize ADLX at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message) at ADLXWrapper.ADLXWrapper..ctor() at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open() 2024-07-19 13:08:20: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL Couldn't initialize ADLX at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message) at ADLXWrapper.ADLXWrapper..ctor() at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open() 2024-07-19 13:08:20: ADLXWrapper could not initialize or has no sensors.`

Why would you have the ADLX plugin enabled on an NVidia GPU? Its for AMD cards

**Comment by kristofer-agnulf-lindex** [comment]
> > I have the same problem. FanControl v196 portable on Windows 11. GPU: RTX 4070 Driver: 560.70
> > `2024-07-19 13:08:18: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL Couldn't initialize ADLX at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message) at ADLXWrapper.ADLXWrapper..ctor() at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open() 2024-07-19 13:08:20: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL Couldn't initialize ADLX at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message) at ADLXWrapper.ADLXWrapper..ctor() at FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open() 2024-07-19 13:08:20: ADLXWrapper could not initialize or has no sensors.`
> 
> Why would you have the ADLX plugin enabled on an NVidia GPU? Its for AMD cards

I haven't enabled anything. I just downloaded the latest portable release and started it.
I guess I can ignore that error message then, but should it even appear in the first place if I have Nvidia?  
Makes the user think that there's something wrong if the user doesn't know that it's only for AMD.

**Comment by Fr0stX76** [comment]
Go in setting/sensors/edit sources and remove the check box under Adlx wrapper

**Comment by xyhbhtt** [comment]
> Why would you have the ADLX plugin enabled on an NVidia GPU? Its for AMD cards

I updated yesterday to V197 and got the ADLX error. I've only ever had an RTX2080 in my rig and I cannot remember eneabling the ADLXWrapper. Wierd.
Problem's solved after looking up this error.

**Comment by Auziuwu** [comment]
Hi, I updated my app to v197 and I'm getting this ADLX error? Never had any issues before and didn't touch any settings. 
I have an i9-13900kf and an rtx 4090 FE. 
Is this a bug?

**Comment by ToniMHeinonen** [comment]
I reinstalled Windows a week ago and I did not have this problem, but when I reinstalled my Windows again today (for stupid reasons) I started having this problem. The only thing I did differently was that I opened the FanControl software before installing Nvidia drivers, maybe it enabled the ADLX because of that?

**Comment by Rem0o** [comment]
Found the issue. Will be fixed in next release.

**Comment by 1Danothy** [comment]
> Found the issue. Will be fixed in next release.

Hi Remo,

This issue is still present in v197 as I am experiencing it.

Also, I personally am unable to untick ADLX Wrapper plugin box as FanControl just freezes...

v197 Portable - Windows 11

**Comment by deltapapa01** [comment]
Hi,
after update from v194 to 197, i got the ADLX Error:

26.07.2024 14:24:47: Open - ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   bei ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   bei ADLXWrapper.ADLXWrapper..ctor()
   bei FanControl.Domain.BackendProviders.ADLX.ADLXWrapperBackendProvider.Open()
26.07.2024 14:24:47: ADLXWrapper could not initialize or has no sensors.
I use Windows 11, Intel i7-13700k with build in GPU.
I roll back to v194 without error

**Comment by krismg** [comment]
Glad I found this thread. ADLX plugin getting enabled on its own after updating from 191 to 197.

**Comment by 1Danothy** [comment]
I just reverted back to v194, issue gone.

PLEASE fix on next update, v197 still broken

**Comment by Rem0o** [comment]
See V198

**Comment by deltapapa01** [comment]
Hi, i update to v198, and the ADLX Error gone! Thank you very much :-)

**Comment by XLDingleberry** [comment]
Hi, Im having an issue with fan control were it was working with the fans on my 7900XTX, now its not. Im getting the ADLXWrapper could not initialize error, and I even updated to V198 and its still just flat out not working. I was on V196 when the issue started. I did recently have to rollback to the Radeon driver 24.4.1 in order to play Pacific Drive. Pacific Drive will not run on the last two drivers for Radeon due to some bug. Am I missing something, or did I do something wrong? Ive even re-downloaded the software to start fresh and its not working either.

**Comment by XLDingleberry** [comment]
Well I found the issue, fan control wont work with radeon driver 24.4.1 for some reason. I re-updated to driver 24.7.1 and it fixed the issue with fan control. But still doesnt work with Pacific Drive, sent the bug report into AMD for that scenario.
