### ISSUE TITLE
Fancontrol chrashes with "Not Responding"

### ISSUE THREAD

**Issue by thegame4craft** [Rem0o/FanControl.Releases#2614]
**Describe the bug**
Changing A setting (for me ADLX enable) causes Fancontrol to Chrash. I'm also a .Net developer. I interpret from the log that you are throwing an exception when a sensor isn't found. I dont know how it was in the past, but about half a year ago, fancontrol didn't chrash everytime i open it after changing a setting. I think thats the reason why it chrashes

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/user-attachments/files/16284377/log.txt)

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
Built-in ADLX support is new.  It is meant for RDNA 3 GPUs.  Those throws should never happen in normal operation. There's a problem with the program in your system. 

What's the setup, parts, OS?

**Comment by Rem0o** [comment]
Polaris (RX 500) gpus are not supported by ADLX.  However you shouldn't get a "hard crash".   Anything in EventViewer?

**Comment by thegame4craft** [comment]
I don't know if there is anything in the event viewer. Im not at home for about two weeks. But what I noticed is that windows doesn't put "Not Responding" in the window title. The app just doesn't do anything
-------- Ursprüngliche Nachricht --------Von: Rem0o ***@***.***> Datum: 26.07.24  16:40  (GMT+01:00) An: "Rem0o/FanControl.Releases" ***@***.***> Cc: thegame4craft ***@***.***>, Author ***@***.***> Betreff: Re: [Rem0o/FanControl.Releases] Fancontrol chrashes with "Not Responding" (Issue #2614) 
Polaris (RX 500) gpus are not supported by ADLX.  However you shouldn't get a "hard crash".   Anything in EventViewer?
