### ISSUE TITLE
Fans spin very fast during shutdown

### ISSUE THREAD

**Issue by jadea630** [Rem0o/FanControl.Releases#2616]
**Describe the bug**
Sometimes not all the time, when I go to shutdown my PC, only during shutdown not during sleep or restart, all the case fans (not sure if GPU fans are impacted) will spin to 100% causing my PC to sound like a F15 ready for takeoff. It does this when there is an application waiting to be closed from what I've noticed, you know when you hit shutdown but it shows you the applications on the PC that are still running and waiting to be shutdown. 

No log file available since it doesn't appear as an error. 

**Relevant hardware specs and setup**
nvidia 2070s v560.7
intel i9-12900k
Mobo: ASUS TUF Gaming Z690-Plus Wifi D4
Windows 11 Home 64bit, version: 10.0.22631, Build: 22631
32 GB Ram

**Comment by Rem0o** [comment]
This is when FanControl gets closed.  When you close the program or disable it with Windows open, you should get the same result. FanControl reverts to whatever was set before it opened.  Take a look in your BIOS what kind of settings you got. I recommend you set a nice low fixed speed in there as a default before/after FanControl takes over.
