### ISSUE TITLE
Possible UI bug - Current temp indicator interferes with graph point editing

### ISSUE THREAD

**Issue by rufusw** [Rem0o/FanControl.Releases#2617]
**Describe the bug**
I believe I have found a UI bug. 
V192 introduced a current temp indicator while editing a graph. If the indicator circle is over a graph point, it appears to interfere with moving that graph point.
I can repeatably test this by dragging a point over the temp indicator and then trying to move it again. Instead of moving that point, a new point is created.

https://github.com/user-attachments/assets/95e61c0e-6696-48d9-bc5a-0590d98d800e

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Not relevant, no error generated

**Relevant hardware specs and setup**
Windows 10 22H2
FanControl V196

**Comment by Rem0o** [comment]
Nice catch. It's a 1 liner fix.  Will be fixed next release

**Comment by Rem0o** [comment]
V197
