### ISSUE TITLE
Compatibility with AMD Radeon HD 6700 ?

### ISSUE THREAD

**Issue by Endelos** [Rem0o/FanControl.Releases#262]
I have tried your soft, it looks great, but it does not detect the temperature of my AMD Radeon HD 6700 nor its fan.
I've tested with LibreHardwareMonitor's soft, it detects the graphic card correctly.

As SpeedFan works for me, I'll stay a bit more with it, but I wanted to let you know !

**Comment by marhensa** [comment]
v81 has that bug. mine Radeon RX 580. try update to v82.

**Comment by Rem0o** [comment]
Used a faulty version of LibreHardwareMonitor in V81. Update to V82, should be good.

**Comment by Endelos** [comment]
I've tried all versions from V80 to V83, my Radeon is still not
recognized...
