### ISSUE TITLE
ADLX Error

### ISSUE THREAD

**Issue by Meteoblastdragon** [Rem0o/FanControl.Releases#2621]
![image](https://github.com/user-attachments/assets/31e2c2fb-e714-40d3-8f69-8c5d8cddf0ac)

I noticed Fan Control didn't launch at start-up for a while now so I tried to open it manually didn't work. After some fiddling, I managed to (had to run the updater as admin). I was then greeted with the image above even though I have the plugin installed.

Also my GPU curve is now no longer working nor can I select my GPU from the temperature sources
![image](https://github.com/user-attachments/assets/f7577c49-b3dd-41da-86e8-9ed8b77019ca)

![image](https://github.com/user-attachments/assets/dcad76bb-f7df-4466-b947-9be8a25a2bf6)

What am I supposed to do?

**Comment by Rem0o** [comment]
Adrenaline driver version?
24.5.1 broke the ADLX plugin. Works on 24.6.1.

**Comment by Meteoblastdragon** [comment]
I'm on 24.6.1, though 24.7.1 exists now that I check, could try updating that to see if that makes a difference

**Comment by Meteoblastdragon** [comment]
So updating it to 24.7.1 didn't help me. Still the same error. Was also able to catch this message in case it's relevant: 
![image](https://github.com/user-attachments/assets/f195dfdb-1625-4214-8429-261da13548d5)

**Comment by Rem0o** [comment]
Any logs.txt?

**Comment by Rem0o** [comment]
There seem to have a mismatch with your plugin files.  As of you updated 1 dll in there but not all of them.  Take the latest release for the plugin, delete everything in the plugin folder and re copy the new release dlls in there.

**Comment by Meteoblastdragon** [comment]
Thank you! That seems to fix it!
