### ISSUE TITLE
PC periodic click sound with FC on.

### ISSUE THREAD

**Issue by Nem0404** [Rem0o/FanControl.Releases#2625]
The sound happens exactly every 1 minute, audio for reference: 

https://github.com/user-attachments/assets/d257aa22-e107-4f93-b7d7-eb4fc7933b0c

also my setting:
![123124](https://github.com/user-attachments/assets/00a50498-ca49-4276-b3dd-314872cebf0c)

though my HDD was dying or something (i checked health with softwares after,it was normal) , but turned out it was FC, if i turn if off then no more sound.

Win 10, 5800x, GTX1070.

**Comment by Rem0o** [comment]
Might it be the sound of your HDD being woken up? Uncheck the HDD detection in sensor source settings.

**Comment by Nem0404** [comment]
Unchecking fixed the problem, thanks.
