### ISSUE TITLE
FanControl won't Start

### ISSUE THREAD

**Issue by mikeg-de** [Rem0o/FanControl.Releases#2627]
**Describe the bug**
After the latest update, FanControl won't start anymore. I reinstalled but that didn't fixed it.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
26/07/2024 07:51:48: ADLXWrapper could not initialize or has no sensors.

**Relevant hardware specs and setup**
AMD Ryzen 9 7950X 16-Core Processor
Windows 11 Pro
MSSI Suprim X 3080 Ti

**Comment by anx10us** [comment]
Same issue here, NVidia GPU 4070 SUPER, crashes after latest update 

fancontrol.exe - 197.0.0.0

from log.txt
26/07/2024 10:58:08: ADLXWrapper could not initialize or has no sensors.

At a guess the new ADLX plugin is being automatically loaded without checking if a NVidia or AMD GPU is installed .. In my case it fails as I have a 4070 Super

**Comment by Fr0stX76** [comment]
Have you tried updating your .json fileÉ

From:
  "Sensors": {
    "AdlxWrapperSettings": {
      "Enabled": true

To:
  "Sensors": {
    "AdlxWrapperSettings": {
      "Enabled": false

**Comment by Fr0stX76** [comment]
As for the iGPU, it might be that even if it is disable in the bios, the driver could still be installed. Go in device manager/view section/enable hidden devices. Then expand graphic adapter section and see if the  AMD igpu is still there. Just uninstall and reboot. It should be gone for good

Or you can use driverstoreexplorer if you are comfortable using it.

**Comment by anx10us** [comment]
> Have you tried updating your .json config file?
> 
> From: "Sensors": { "AdlxWrapperSettings": { "Enabled": true
> 
> To: "Sensors": { "AdlxWrapperSettings": { "Enabled": false

That works as a temporary fix

> As for the iGPU, it might be that even if it is disable in the bios, the driver could still be installed. Go in device manager/view section/enable hidden devices. Then expand graphic adapter section and see if the AMD igpu is still there. Just uninstall and reboot. It should be gone for good
> 
> Or you can use driverstoreexplorer if you are comfortable using it.

This allows me to install the latest version without any issues, the .json now shows 'false' without the need for editing

`"Sensors": {
"AdlxWrapperSettings": {
"Enabled": false`

**Comment by mikeg-de** [comment]
Uninstalling the AMD driver, using [DDU](https://www.guru3d.com/download/display-driver-uninstaller-download/), made FanControl start again. However, the error is still present. I am trying the JSON setting to mitigate that.

**Comment by Fr0stX76** [comment]
@Rem0o seems like FanControl is detecting ghost devices and enabling the ADLX based on it. Any way you can prevent that? This will be an issue most 7000 serie Ryzen CPU if the user did not remove the device manually

**Comment by Rem0o** [comment]
@Fr0stX76  Yes I found out the issue. Will be fixed.

**Comment by giordiemk** [comment]
![Immagine 2024-08-13 233840](https://github.com/user-attachments/assets/001fc390-77b0-4412-9db5-1f3e657fe7a8)

I still had this issue in the last days, and I currently solved this using @Fr0stX76 fix ( "AdlxWrapperSettings": {
"Enabled": false ). FanControl didn't start at all, even manually. I've uploaded the error message screenshot in Windows Event log. Installing the last version available didn't solve anything either.

The fix made the app work, but I still had to reselect my GPU core as temp source.

I see that the last update was 3 weeks ago. Hasn't this been fixed yet?

**Comment by AsthmaQueen** [comment]
This just happened to me after installing latest windows update and downgrading from the AFMF2 preview driver for ryzen.
