### ISSUE TITLE
Feature request - fan curve profile with time

### ISSUE THREAD

**Issue by pillar11** [Rem0o/FanControl.Releases#263]
Hi, and thank you for this amazing soft ! i was wondering if its possible to add a feature where the fan will automatically switch to a profile according to the time of the day, for example, i want my fan to spin at a lower rpm at night when my pc is idle to reduce noise but when its day time i want the fan to automatically ramp up to a certain percentage even if im not using my pc, i have no experience with soft developing so idk if my idea is doable or even worth it.

**Comment by lordlightman** [comment]
Hello there. I would also like to see a feature like this implemented.

**Comment by s-geissler** [comment]
In the meantime, you can achieve something like that using two different profiles and the windows task scheduler. 
The most recent version supports the -c flag. So you can use the windows task scheduler to automatically kill the process and start a new one using the desired profile.
