### ISSUE TITLE
FanControl does not override the built-in AMD adrenaline control anymore

### ISSUE THREAD

**Issue by KemiYuki** [Rem0o/FanControl.Releases#2631]
**Describe the bug**
In simple words, from when the ADLX support was introduced officially, I can't control my gpu fans anymore, it's greyed out and unresponsive. In the past versions i used the FanControl.ADLX plugin, and it worked just fine, but now it does not work anymore.

Here is a screenshot of both fancontrol and amd adrenaline: https://imgur.com/a/H5dQqbi
As you can see, the gpu control is greyed out, automatic calibration does not change fan speed when initiated and manual control does nothing

Here is the log file: https://pastebin.com/6j5AaQ6N

**Relevant hardware specs and setup**
My GPU is an XFX SPEEDSTER 319 QICK 6750 XT
Intel Core i5-12600K
MSI MAG Z690 TOMAHAWK WIFI DDR4
32 GB of Corsair CMW32GX4MD3600C18

Windows 11 Home BUILD 22631.3880 (22H2)

**Comment by Fr0stX76** [comment]
Your log show v195. Are you on the latest?

> [V196](https://github.com/Rem0o/FanControl.Releases/releases/tag/V196)
Fix various ADLX bugs

> [V198](https://github.com/Rem0o/FanControl.Releases/releases/tag/V198)
Fix a bug where ADLX would get called when disabled

**Comment by KemiYuki** [comment]
Yeah I am on the latest version (just updated when I opened my computer)... strange. I double-checked and my logs do stop to 10/7/2024... maybe I'm stupid

**Comment by Rem0o** [comment]
Driver version for adrenaline?

**Comment by KemiYuki** [comment]
the driver version is the latest, the 24.7.1, but fancontrol didn't work with the older version also

**Comment by KemiYuki** [comment]
Nevermind, i actually solved it, for some weird reason it didn't even set the ADLX as the default option and i noticed just now
