### ISSUE TITLE
Using same graphs with same temperature source results into different RPM

### ISSUE THREAD

**Issue by Terepin** [Rem0o/FanControl.Releases#2632]
![image](https://github.com/user-attachments/assets/58cfaf99-9a4a-476e-9e62-191255f3b5a6)
This is a weird issue, because even though graphs are identical, and the fans themselves are also identical, the same temperature results into different percentage of speed. Any idea what might be causing this?

**Comment by Rem0o** [comment]
Hyteresis. The 2 temperatures don't fluctuate the same over time.

**Comment by Terepin** [comment]
That explains that, however I left a game run paused for 20 minutes so that temperatures would stabilize and despite both CPU and GPU were at 70 degrees, CPU fans were spinning at 100 RPM lower than case fans. Could be that I'm too stupid to understand how it works, but to me this doesn't make sense.

**Comment by Rem0o** [comment]
See hysteresis as a threshold box around a temperature point. When a temp jump from let say 45 to 55 in one cycle, the hysteresis box will reset around that new value. If the other temp jumped to 58, its hysteresis box will be centered around 58. Two different operating temperatures, but both temperatures can then cross without triggering their respective hysteresis threshold.

**Comment by ionGL** [comment]
Test with hysteresis 0 for both graphs and see if you get the same results.

**Comment by Terepin** [comment]
> Test with hysteresis 0 for both graphs and see if you get the same results.

This "fixed" it. Thanks!
