### ISSUE TITLE
V198 ADLX issue is back?

### ISSUE THREAD

**Issue by UbikNoir** [Rem0o/FanControl.Releases#2634]
**Describe the bug**
Similar issue to a previously reported one where Radeon GPU fans cannot be controlled and/or speed sensors be sensed for them...

Ryzen 9 5900X
Radeon RX 6950 XT

**Comment by Rem0o** [comment]
Driver version?

**Comment by Yusuf-Manjra** [comment]
im having this issue on 24.7.1 currently.
i'll try rolling back to see if that fixes it.

**Comment by Rem0o** [comment]
Try to install 24.7.1, but do a clean/full install when the checkbox presents itself.

**Comment by Yusuf-Manjra** [comment]
Figured it out. MSI afterburner was overwriting fan control despite me having it not controlling fan speeds...

**Comment by NathanMaia** [comment]
After updating amd drivers to 24.7.1, fancontrol is not detecting my gpu fans anymore. I sync case fans to my gpu fan speed.

The latest fancontrol version doesnt even initialize. I rolled back to older versions and it does open, but doesnt detect gpu fans.

Control through adrenaline working as expected.

GPU: AMD RX 6800xt
CPU: Ryzen R7 5700x
MOBO: Gigabyte b450 ds3h rev.1

All drivers updated. I'm using version V194 and flat fan speed for my case fan for now.
