### ISSUE TITLE
MSI B550 tomahawk 

### ISSUE THREAD

**Issue by beanie-439** [Rem0o/FanControl.Releases#2635]
Hey guys, so having an issue where the little question mark is constantly on CPU and fan header 1 and 2. Ive applied force apply does nothing also if I got into manual mode it’ll not let me control fan speeds 

I’ve tried setting fan in bios to DC or PWM. Also tried setting them all to manual 100%, 50% and 40% any lower it freaks out. I don’t have any other software for fan control on my pc. Don’t have MSI Centre 

I’ve even wiped and clean installed windows to see if there was any left over files from in the past still the same and have also tried reinstalling fan control 

Bios is up to date with the latest software 

PC specs 
MSI B550 tomahawk 
5800X3D 
32gb ram 
3060ti 
CPU cooler NH-D15 
Case fans AF12x25 x 6 
All using motherboard headers

**Comment by Rem0o** [comment]
Are you able to identify at what point the "?" symbol shows up?  It most likely only happen below a specific %.   This might be due to a soft limit on that header, like if its a CPU header, some of them have a soft minimum limit.  The "?" may not be a problem, more of an indication that at that point FanControl can't pull the fan speed as low as the fan curve ask, but as soon at said fan curve asks for say 100%, it will work as expected.

**Comment by beanie-439** [comment]
It's from around 40% upwards I can't control the fans with software but say I bench my pc and motherboard allows 100% then I can control fans from 1% to 100%. Noticed last night too that sometimes the fans will just got to 0% and stop working when they should be around 30%. Think I need to pay with bios a little more to see if that's taking over

**Comment by beanie-439** [comment]
![image](https://github.com/user-attachments/assets/5d6d0530-067d-40d3-8839-fdd311ffda25)
![image](https://github.com/user-attachments/assets/45e36543-39bf-46f9-b918-35d8563c78f9)
![image](https://github.com/user-attachments/assets/0b1b868c-b0ee-478f-b468-f4f762d80b66)
![image](https://github.com/user-attachments/assets/6740c009-795a-433b-8b8f-a79294ce1be2)

**Comment by Rem0o** [comment]
Your BIOS config looks fine.  I have 2 MSI boards at home and got the exact same BIOS setup and both work just fine. I can't tell why it doesn't work for you right now.

**Comment by beanie-439** [comment]
Well I've figured it out had to manually set a fan curve in smart fan then disable it which left the curve but took it off and set the control to auto instead of PWM or DC working fine now. I've never used the bios fan curve before always used MSI Centre previously
