### ISSUE TITLE
Detection issues in newer versions

### ISSUE THREAD

**Issue by averagebass** [Rem0o/FanControl.Releases#2636]
**Describe the bug**
Multiple fans no longer detected or no longer reliably detected after updating to 198 (and I think 197 as well, but 197 was only installed for half a day due to being away from home). System fan #1 through #3 stopped being detected, System fan #4, #5 and CPU fan are detected sometimes. Prior to these updates, all fans were detected all the time - though all of them constantly had question marks on them, but that should be a separate issue.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/user-attachments/files/16424006/log.txt)

**Relevant hardware specs and setup**
AMD Ryzen 5 5500 with an Arctic Freezer 33 eSports one
MSI MPG B550 Gaming Plus
INNO3D GeForce RTX 3060 12GB
Windows 11 Pro 23H2
Corsair 4000D with two stock fans and three beQuiet! Pure Wings 2 BL046
Corsair TX750M

**Comment by averagebass** [comment]
I went ahead and installed some older versions. Going back to V196 did not fix my issue, going back to V194 did however. Vacation's starting, but as soon as I get back I can try some other versions to narrow down what's happening, if that helps.

**Comment by Epicguru** [comment]
Bump, same issue. Certain system fans not detected, others work just fine.
AMD 7950x with an Aorus Master x670e.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
