### ISSUE TITLE
b82: no more fans or sensors detected except for GPU.

### ISSUE THREAD

**Issue by sofyanet** [Rem0o/FanControl.Releases#264]
Hi, just did the auto update not more than 2 mins ago and it completely broke my settings. On top of that, no other sensors or fan are recognized anymore except for my NV GPU fans.

I have the following error showing everytime the program starts:

![image](https://user-images.githubusercontent.com/65699547/122294498-65333c80-cef8-11eb-9f60-6fe3f5c6650e.png)

Just updated to build 82.

![image](https://user-images.githubusercontent.com/65699547/122294778-b5aa9a00-cef8-11eb-906d-436df10bf43b.png)

Let me know if you need any more info.

**Comment by seb9r** [comment]
Some Problem for me. After the first error (looks quite the same as the one from @sofyanet ) I get the prompt to refresh which does nothing except generating the error message again.

**Comment by sofyanet** [comment]
I also get the same refresh prompt box as @seb9r which infine does nothing unfortunately.

Also, the temperature selected to display in the taskbar has gone:

![image](https://user-images.githubusercontent.com/65699547/122388702-6c962c80-cf70-11eb-82ff-6ae35488dfe8.png)

Hope this helps.

**Comment by sinanmuslu** [comment]
For me it is the other way: sensors detected BUT no sensors for the GPU ... will there be an update soon? 
![Bildschirmfoto 2021-06-17 um 19 44 35-Fan Control V83 (alltagsprofil json)](https://user-images.githubusercontent.com/55310927/122447939-8b161b00-cfa4-11eb-8490-ac9438d34363.png)
![Bildschirmfoto 2021-06-17 um 19 44 47-](https://user-images.githubusercontent.com/55310927/122447941-8baeb180-cfa4-11eb-929f-27139359cc7e.png)

**Comment by DMAgit** [comment]
Identical issue persists on V83.

**Comment by Rem0o** [comment]
Any log.txt?

**Comment by PhyxionNL** [comment]
Hmm, driver bug? Everything seems to report as not supported. 

@DMAgit @sinanmuslu Can you run this build https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/948977915 and attach the log (File > Save Log)? I'm curious what it reports.

**Comment by sinanmuslu** [comment]
> Hmm, driver bug? Everything seems to report as not supported.
> 
> @DMAgit @sinanmuslu Can you run this build https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/948977915 and attach the log (File > Save Log)? I'm curious what it reports.

OK, I'll see if I can do this… I'm a little noob in these code-stuff 😬 
Will take time on weekend and looking forward to post the log!

**Comment by PhyxionNL** [comment]
Direct download link:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/suites/3027084156/artifacts/68634156
Run LibreHardwareMonitor.exe. Then File > Save Report and attach it here 🙂

**Comment by sofyanet** [comment]
[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6676896/LibreHardwareMonitor.Report.txt)

Hope this helps.

**Comment by sofyanet** [comment]
![image](https://user-images.githubusercontent.com/65699547/122558716-b1889480-d03e-11eb-9d46-12f7a0ea9477.png)

The problem persists on my side when trying b83. No log is generated though.

**Comment by PhyxionNL** [comment]
> 
> 
> [LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6676896/LibreHardwareMonitor.Report.txt)
> 
> Hope this helps.

You seem to have NVIDIA GPU instead of AMD 🙂 I'm more interested in that at the moment.

However, I went through NCT sensors as well and think @zeule mixed up two values. Can you try https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/949830093
I don't know if it solves your issue though, but please take a look. My own NCT sensor already worked correctly (and still does) so I can't verify this myself.

**Comment by sofyanet** [comment]
So I've try updating the "LibreHardwareMonitor" library using the .NET 5.0 version after updating my .NET version from 4.8 to 5.0.7.

build 83 will not launch at all.

**Comment by PhyxionNL** [comment]
@sofyanet please download this zip and run LibreHardwareMonitor.exe:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/suites/3029436357/artifacts/68707870
For FanControl you will need to use the DLL from this zip as well.

**Comment by sofyanet** [comment]
So LHM runs, but FanControl does not. However, the LHM tool does not pick up my CPU temps nor some RAM info. See below:

![image](https://user-images.githubusercontent.com/65699547/122590105-62a02680-d061-11eb-8220-bab51fd13fa7.png)

[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678214/LibreHardwareMonitor.Report.txt)

Let me know if you want me to try anything else.

**Comment by PhyxionNL** [comment]
Hmm, that's odd. Haswell CPUs should be supported. Do you run both LHM and FanControl? You should use only one program at a time. Otherwise you might want to try a system reboot.

**Comment by sofyanet** [comment]
I have rebooted my system already. And yes only one program at a time.

**Comment by PhyxionNL** [comment]
Do you get values with this one?
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/suites/2969241436/artifacts/66934330

**Comment by sofyanet** [comment]
![image](https://user-images.githubusercontent.com/65699547/122593673-4eaaf380-d066-11eb-9103-9a9e33dc17db.png)

[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678366/LibreHardwareMonitor.Report.txt)

This version seems to be working normally.

**Comment by PhyxionNL** [comment]
Alright, can you use the above zip again and replace LibreHardwareMonitor.exe and LibreHardwareMonitorLib.dll with the files in the following zip and try again? You do not have to reboot.
[net452.zip](https://github.com/Rem0o/FanControl.Releases/files/6678379/net452.zip)

**Comment by sofyanet** [comment]
![image](https://user-images.githubusercontent.com/65699547/122594647-94b48700-d067-11eb-950e-2d39e8128103.png)

[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678396/LibreHardwareMonitor.Report.txt)

Ok I've just tried and it seems to be running properly.

**Comment by sofyanet** [comment]
I can also confirm that b83 now works properly with this version of the library.

**Comment by sofyanet** [comment]
![image](https://user-images.githubusercontent.com/65699547/122594954-042a7680-d068-11eb-8069-81bb67fd4811.png)

**Comment by PhyxionNL** [comment]
Thank you, it seems the new WinRing0 driver added [here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/428) is not working properly for you. What antivirus are you using? I also have an Intel system here (Ivy) and that's working for me.

**Comment by DMAgit** [comment]
I ran [this](https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-864156279) LHM .zip with [this](https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-86416666) .exe and .dll 

[Here's the report.](https://github.com/Rem0o/FanControl.Releases/files/6678428/LibreHardwareMonitor.Report.txt)

**Comment by sinanmuslu** [comment]
hey there, here my logfile. 
I see that you uploaded the net452, should I just replace the LibreHardwareMonitorLib.dll in the FanControl folder?
[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678440/LibreHardwareMonitor.Report.txt)

**Comment by sofyanet** [comment]
> 
> 
> Thank you, it seems the new WinRing0 driver added [here](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/428) is not working properly for you. What antivirus are you using? I also have an Intel system here (Ivy) and that's working for me.

I do not run any antivirus and rely on a firewall. However, I have a group policy that prevents any windows auto update. I do run the last cumulative security patches when needed though.

**Comment by DMAgit** [comment]
I replaced the LibreHardwareMonitorLib.dll in the FanControl folder with the one from [here](https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-86416666). Everything is running as it should.

@sinanmuslu

**Comment by DMAgit** [comment]
As for firewalls, I only run MS Defender and MalwareBytes. I haven't got any alerts or anything from them though. 

I just checked and nothing is quarantined either.

**Comment by sofyanet** [comment]
As the problem is solved on my side and seems to be solved for the other contributors, should I close the issue ? @PhyxionNL @Rem0o

**Comment by PhyxionNL** [comment]
Thanks for the reports, it's really strange that it's not working on your systems. I only use Defender and didn't have any problems with that either (nor with my AMD and Intel systems). I'll see if I can revert the driver soon 👍

**Comment by sinanmuslu** [comment]
now the CPU temperatures are also gone...
here a new report
[LibreHardwareMonitor-2.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678516/LibreHardwareMonitor-2.Report.txt)

**Comment by sinanmuslu** [comment]
> I replaced the LibreHardwareMonitorLib.dll in the FanControl folder with the one from [here](https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-86416666). Everything is running as it should.
> 
> This is on the most recent release version right now (V83).
> 
> @sinanmuslu

which one exactly? the linked comment is no longer there? probably an edited one?

**Comment by PhyxionNL** [comment]
@sinanmuslu @sofyanet @DMAgit 
Can you try this zip?
[net452.zip](https://github.com/Rem0o/FanControl.Releases/files/6678619/net452.zip)
If it's not working, can you save the report in LHM? File > Save Report.

**Comment by sinanmuslu** [comment]
done. quit fancontrol, tell it to NOT start with windows, reboot, launched LHW from your linked zip file, and here is the report. 
[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678905/LibreHardwareMonitor.Report.txt)

thank you for your time :)

**Comment by PhyxionNL** [comment]
> 
> 
> done. quit fancontrol, tell it to NOT start with windows, reboot, launched LHW from your linked zip file, and here is the report.
> [LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678905/LibreHardwareMonitor.Report.txt)
> 
> thank you for your time :)

It seems to report everything now except for AMD? 
For AMD, can you try https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-863809076 and attach report as well?

I'm curious if https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-864194104 is working correctly for @sofyanet  and @DMAgit as well.

**Comment by sofyanet** [comment]
> 
> 
> > done. quit fancontrol, tell it to NOT start with windows, reboot, launched LHW from your linked zip file, and here is the report.
> > [LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6678905/LibreHardwareMonitor.Report.txt)
> > thank you for your time :)
> 
> It seems to report everything now except for AMD?
> For AMD, can you try [#264 (comment)](https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-863809076) and attach report as well?
> 
> I'm curious if [#264 (comment)](https://github.com/Rem0o/FanControl.Releases/issues/264#issuecomment-864194104) is working correctly for @sofyanet and @DMAgit as well.

![image](https://user-images.githubusercontent.com/65699547/122609991-32678080-d07f-11eb-8c4b-18bd72f22fdc.png)

Both LHM and FanControl are working properly on my side with this version of the library.

**Comment by sinanmuslu** [comment]
done... same procedure.  :/
I even tried the installatrion of a lower version, it does not run with all the sensors. i think a reall UNINSTALLATION is not neccessary to start from scratch?

[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6679148/LibreHardwareMonitor.Report.txt)
![Bildschirmfoto 2021-06-18 um 22 12 28-Libre Hardware Monitor](https://user-images.githubusercontent.com/55310927/122611837-4e205600-d082-11eb-901c-e154bc0fa14d.png)

**Comment by PhyxionNL** [comment]
@sinanmuslu If the latest normal release (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.8.7) isn't showing any sensors for your AMD GPU then I suspect it's a driver issue. I've checked your log file and everything returns error or unsupported status.

@sofyanet Are the sensors for your CPU now working as well?

**Comment by sofyanet** [comment]
![image](https://user-images.githubusercontent.com/65699547/122622541-56d05680-d099-11eb-92a0-caa9c5159432.png)

All CPU sensors seem to work properly yes.

**Comment by sinanmuslu** [comment]
> @sinanmuslu If the latest normal release (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.8.7) isn't showing any sensors for your AMD GPU then I suspect it's a driver issue. I've checked your log file and everything returns error or unsupported status.
> 
> @sofyanet Are the sensors for your CPU now working as well?

it all went 100% well until FanControl update to v83. The AMD driver is still the same. probably a complete delete / uninstall of FanControl / LHM would help? but.. it's not a installable exe so. damnit :/

**Comment by seb9r** [comment]
Just got the info about a critical error which has been saved in the log file. Maybe this helps :)

![2021-06-19 07_37_00-b82_ no more fans or sensors detected except for GPU](https://user-images.githubusercontent.com/86040707/122632166-4f2ca400-d0d1-11eb-8dfc-c59466df9dde.jpg)

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6680078/log.txt)

**Comment by PhyxionNL** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/65699547/122622541-56d05680-d099-11eb-92a0-caa9c5159432.png)
> 
> All CPU sensors seem to work properly yes.

@sofyanet Great, can you give this version a try as well and report if all sensors are shown in LHM (also @sinanmuslu and @DMAgit):
[net452.zip](https://github.com/Rem0o/FanControl.Releases/files/6680252/net452.zip)

@sinanmuslu Maybe Windows Update updated your driver? I don't know how to solve the AMD sensors otherwise, as everything reports error or unsupported.

@seb9r That's something @Rem0o must fix 👍

**Comment by sinanmuslu** [comment]
> @sinanmuslu Maybe Windows Update updated your driver? I don't know how to solve the AMD sensors otherwise, as everything reports error or unsupported.

Hm there was no update before / after upgrade to v83 of FanControl. When I delete the FanControl folder and reboot, will there still be some files to delete to start from scratch? 
or can I delete another file in the FanControl folder that has some infos in it that will be created new with a restart of the app after deleting it? 
sorry for my noobism concearning programming and deeper OS stuff.

**Comment by PhyxionNL** [comment]
I don't use FanControl so I can't tell, maybe @Rem0o can shed some light on it.

**Comment by sofyanet** [comment]
> > ![image](https://user-images.githubusercontent.com/65699547/122622541-56d05680-d099-11eb-92a0-caa9c5159432.png)
> > All CPU sensors seem to work properly yes.
> 
> @sofyanet Great, can you give this version a try as well and report if all sensors are shown in LHM (also @sinanmuslu and @DMAgit):
> [net452.zip](https://github.com/Rem0o/FanControl.Releases/files/6680252/net452.zip)
> 
> @sinanmuslu Maybe Windows Update updated your driver? I don't know how to solve the AMD sensors otherwise, as everything reports error or unsupported.
> 
> @seb9r That's something @Rem0o must fix 👍

I'll give it a try later today and keep you posted @PhyxionNL

**Comment by sofyanet** [comment]
This version isn't working properly on my side. CPU sensors are not detected @PhyxionNL 

![image](https://user-images.githubusercontent.com/65699547/122719629-bfbcf780-d26e-11eb-8322-5a7d9f33c829.png)

**Comment by PhyxionNL** [comment]
Can you attach the log @sofyanet?

**Comment by PhyxionNL** [comment]
@sofyanet 
**After creating said log**, can you give this version a try:
[net452.zip](https://github.com/Rem0o/FanControl.Releases/files/6685014/net452.zip)
If sensors do show now, please open Windows Task Manager and "End task" of LibreHardwareMonitor, then launch it again and see if it works.

**Comment by sofyanet** [comment]
@PhyxionNL as requested.  Both logs for the last two versions you wanted me to try. None of those two works on my system.

[LibreHardwareMonitor.Report #1.txt](https://github.com/Rem0o/FanControl.Releases/files/6685381/LibreHardwareMonitor.Report.1.txt)

[LibreHardwareMonitor.Report #2.txt](https://github.com/Rem0o/FanControl.Releases/files/6685366/LibreHardwareMonitor.Report.2.txt)

**Comment by PhyxionNL** [comment]
Thank you, both times the driver fails to start due to insufficient system resources (which is odd as there's plenty of RAM available). I will revert back to previous WinRing0 driver as that seems to work and include InpOut again for reading AMD's SMU.

**Comment by PhyxionNL** [comment]
@sofyanet Can you give this a try: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/957040240
This uses the old WinRing0 driver again.

**Comment by sofyanet** [comment]
As requested @PhyxionNL:

[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6688038/LibreHardwareMonitor.Report.txt)

![image](https://user-images.githubusercontent.com/65699547/122794221-4ea43100-d2bc-11eb-8c2c-0057af56a575.png)

**Comment by sofyanet** [comment]
As request @PhyxionNL:

[LibreHardwareMonitor.Report.txt](https://github.com/Rem0o/FanControl.Releases/files/6688053/LibreHardwareMonitor.Report.txt)

![image](https://user-images.githubusercontent.com/65699547/122794498-9aef7100-d2bc-11eb-90b6-b63512022fa8.png)

**Comment by PhyxionNL** [comment]
Thanks @sofyanet, glad to see the sensors back with the old WinRing0 build.

**Comment by sinanmuslu** [comment]
downgraded to 78 like sofyanet linked above. everything works again...

**Comment by PhyxionNL** [comment]
> 
> 
> downgraded to 78 like sofyanet linked above. everything works again...

The latest build (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/957777775) should work again.

**Comment by sinanmuslu** [comment]
> > downgraded to 78 like sofyanet linked above. everything works again...
> 
> The latest build (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/957777775) should work again.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/suites/3048040165/artifacts/69267743  this one?

**Comment by PhyxionNL** [comment]
Correct 😁

**Comment by sofyanet** [comment]
> 
> 
> Thanks @sofyanet, glad to see the sensors back with the old WinRing0 build.

You're welcome. Happy to have helped.

**Comment by seb9r** [comment]
Thanks for your support & help @PhyxionNL , works perfectly again. :)

**Comment by DMAgit** [comment]
@sofyanet Seems that you can close the issue. Thanks everyone for your help!

**Comment by Rem0o** [comment]
Will update the LHM dll with the latest, thanks @PhyxionNL.

Btw, why did you scrap all the built-in NVAPI implementation instead of updating it?

**Comment by PhyxionNL** [comment]
> Btw, why did you scrap all the built-in NVAPI implementation instead of updating it?

NvAPIWrapper has a lot more features and yes, it could all have been added to built-in one, but why reinvent the wheel.

**Comment by sofyanet** [comment]
@DMAgit @Rem0o @PhyxionNL thank you guys for your work on this.
