### ISSUE TITLE
Nzxt h1 v2 question 

### ISSUE THREAD

**Issue by Dotdk** [Rem0o/FanControl.Releases#2640]
I cant find somewhere else to ask so il ask u directly

I have nzxt h1 v2 will fan controle work with that have the nzxt controller so il probably need to move the pins to the motherboard right ?

Fan controller with no rpm sensors on my channel fans its working fine with my gfx card that good calibrated at first try have been in bios and set it to pwm mode Hope u can help me

**Comment by Dotdk** [comment]
![image](https://github.com/user-attachments/assets/dff28442-c403-40a1-9dc1-c34b0ee60f0f)
this is how it look when it run the control and speed pairing

![image](https://github.com/user-attachments/assets/fee85761-d0fa-40b4-b387-5f2ff0c4e6dc)
can be me there does somthing wrong

**Comment by Rem0o** [comment]
Fan #1 to #6 are your motherboard headers.  Your Controller isn't supported natively.

**Comment by Dotdk** [comment]
Allright so the only work around here is to take the headers and put them on the motherboard right ?

**Comment by Rem0o** [comment]
Thats one option.

**Comment by Dotdk** [comment]
Does u have another options ? Let me know
