### ISSUE TITLE
Fan Control crashing after Windows 11 Sleep Mode

### ISSUE THREAD

**Issue by manster-zz** [Rem0o/FanControl.Releases#2643]
**Describe the bug**
I am using Fan Control since more than 2 years on my custom built PC running Windows 11. Since a few days the program does not work after using the Windows Sleep mode. The fans spin faster which means that FanControl is not active, but I can see the icon in the taskbar for a split second, then it disappears. After starting the FanControl.exe manually it's working as usual.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No entries for this issue.

**Relevant hardware specs and setup**
CPU: 12th Gen Intel(R) Core(TM) i3-12100F   3.30 GHz
GPU: RX6600 (controlled through AMD software)
Windows 11 Pro 23H2

**Comment by Rem0o** [comment]
Anything in EventViewer? seems like a hard crash.

**Comment by manster-zz** [comment]
![Screenshot 2024-08-02 194538](https://github.com/user-attachments/assets/91390942-6261-458d-98ca-0932ad7d1027)

**Comment by manster-zz** [comment]
> Anything in EventViewer? seems like a hard crash.

![Screenshot 2024-08-02 194538](https://github.com/user-attachments/assets/165374e0-3335-440c-850c-731499b78158)

**Comment by Rem0o** [comment]
Tge atiadlx dll is amd driver. If you are not using it through fancontrol, disable adlx from sensor sources in the settings.

**Comment by manster-zz** [comment]
> The atiadlx dll is amd driver. If you are not using it through fancontrol, disable adlx from sensor sources in the settings.

Thanks! This fixed my problem.

**Comment by mdelag** [comment]
had same issue and disabling adlx from source fixed the issue. Been using Fan Control for 2 years and this is new, maybe something to do with AMD latest driver updates.
