### ISSUE TITLE
Every time I open the software, it displays' NaN RPM '

### ISSUE THREAD

**Issue by MaxBuer** [Rem0o/FanControl.Releases#2647]
Every time I completely close the software and then reopen it (including after booting), I need to manually turn off the "RPM Mode" in the tab and then turn it back on to read the GPU's fan speed. Because my GPU has an external button that can manually increase the fan speed, I want to use the manual button to control the speed of my chassis fan. However, as I mentioned earlier, I must manually turn on and off the "RPM Mode" to use it properly.
---Translated by translation software, there may be some unclear expressions ：）

↓↓↓↓My software records screens↓↓↓↓

https://github.com/user-attachments/assets/fc0ecd99-6121-4299-9a53-6004a21b1114

**Comment by MaxBuer** [comment]
Supplementary explanation
![20240804-015141](https://github.com/user-attachments/assets/2e6db8db-a1df-432c-b356-81698e132135)

**Comment by Rem0o** [comment]
This won't affect your problem, but you can uncheck "GPU" and "ADLX Enabled" in your sensor settings. 

I may have found the issue.  In the mean time, a workaround I found is to reorder the cards. Take your GPU control card and drag it all the way to the left.

**Comment by MaxBuer** [comment]
> This won't affect your problem, but you can uncheck "GPU" and "ADLX Enabled" in your sensor settings.
> 
> I may have found the issue. In the mean time, a workaround I found is to reorder the cards. Take your GPU control card and drag it all the way to the left.

really！
After I changed the GPU tab position, I can now recognize the fan speed normally!! Thank you:)

https://github.com/user-attachments/assets/25b76206-c4e6-4db6-ad73-175bd02cb515

**Comment by Rem0o** [comment]
Should be fixed as of V201.
