### ISSUE TITLE
Lian Li Hydroshift 360R AIO pump not detected.

### ISSUE THREAD

**Issue by Ryanizleee** [Rem0o/FanControl.Releases#2650]
As stated in the title, the AIO's pump is not detected in FC but it is detected and runs fine in Lian Li's L-Connect software.
Do note that the entire AIO is not connected to any Lian Li L-Connect hub at all, pump is connected directly to the mb's pump header.
I am not sure if this will be looked into, but I thought I'd try posting it here and see if anyone else that owns any of the 3 variants of this AIO that runs into the same issue as mine.

![Hydroshift 360R](https://github.com/user-attachments/assets/72a11ef5-3eaa-470b-9111-f0d48d54876d)

**Comment by Fr0stX76** [comment]
Pump MB header is sometime not controlled/100% by default. Have you tried another MB fan header? Also, make sure it`s in PWM mode in the BIOS.

**Comment by Ryanizleee** [comment]
> Pump MB header is sometime not controlled/100% by default. Have you tried another MB fan header? Also, make sure it`s in PWM mode in the BIOS.

I was using another AIO previously which was Deepcool's Mystique 360 and FC detects it just fine, in which the pump is plugged into the AIO_PUMP header on my MB.

Per your suggestions, I double checked in BIOS and it is indeed in PWM mode.
Tried other headers ie; CPU_FAN, CPU_OPT and they all yielded the same result, not detected in FC but detected in Lian Li's L-Connect software.

**Comment by Rem0o** [comment]
FanControl doesn't detect AIOs per say, it detects headers.  You won't "see" the name of your AIO appear, you should use the header control card/header you were using if it was plugged in the same header.

**Comment by Rem0o** [comment]
Is there also a USB header for it? It might not use the PWM signal at all, only the tach to report rpm.

**Comment by Ryanizleee** [comment]
Yes it does have a USB header.
Total of 3 cables : SATA, USB and PWM

**Comment by Rem0o** [comment]
Then the control aspect is most likely done through a USB driver, which FanControl won't support natively.

**Comment by bigfatggls** [comment]
Hi I have a similar problem but all my mobo slots are working when I tried a test fan. and it says on bios "CPU FAN ERROR" 
![20241108_214144](https://github.com/user-attachments/assets/90686d2d-79fd-48d7-a404-a4d773697e91)
