### ISSUE TITLE
Offset behaviour is incorrect

### ISSUE THREAD

**Issue by godzinilla** [Rem0o/FanControl.Releases#2655]
The offset option in my opinion behaves incorrectly.

Quick testing scenario:

Let's say we have a fan with following parameters: 0% - 0 RPM, 100% - 1000 RPM.
Configure the control with minimal speed set to 10% witch translates to 100 RPM.
Control is based on any curve in RPM mode. The minimal fan speed is set to 100 RPM.
Set the offset in control to e.g. 5% - the fan speed will not increase.
Set the offset in control to 12% - the fan speed will increase from 10% to 12%.
Set the offset in control to e.g. 5% and increase the minimal fan speed in curve to 20% (300 RPM) - the fan will increase to 25%.

So the offset value is not considered unless base fan speed reaches the minimal value set in control.

In my opinion it should work regardless the minimal option - then we can easily increase the speed of the specific/group fan/s for creating e.g. positive or negative pressure.

**Comment by Rem0o** [comment]
The formula for the final output in % for the control is the following:

( fan Curve Command + control offset ).Clamp( Minimum % , 100 );

> So the offset value is not considered unless base fan speed reaches the minimal value set in control.

That's not right.

![image](https://github.com/user-attachments/assets/c6a4bcc8-84c0-49dd-968b-352b95a59b5f)

In this example the input in 70.  Offset is 12.  Command is thus 82, which is above the minimum. 

The offset will always be applied to the input command, not the minimum.   Having the offset be applied to the minimum would be equivalent to just setting the minimum value to that offset.

**Comment by Rem0o** [comment]
What you might want to take a look at is the sync fan curve in RPM mode.   You can apply a proportional offset to it, and use that as a curve to the other fans in a group.
