### ISSUE TITLE
Fan control is sometimes reversed after waking up from hibernate.

### ISSUE THREAD

**Issue by pinapl** [Rem0o/FanControl.Releases#266]
Motherboard: Gigabyte B450 I Aorus Pro Wifi
Operating system: Windows 10 Home 20H2
Fans affected: CPU header + AMD Wraith Prism cooler (PWM); System fan header + Noctua FC1 PWM fan controller + Arctic P12 PWM fans
Fan Control version: currently V83, older versions are also affected.

Sometimes when waking up from hibernate, the fan controls will reverse. Instead of going from 0-100% load, it effectively goes from 100-0% load. so when I have a fan set to 25% load, it'll be spinning at 75% instead.

Recently it happened to my CPU fan header, but I've also seen it happen to the system fan header. Restarting the computer resolves the issue. The motherboard does have its own fan control in UEFI that "Fan Control" overrides, but no other fan control software is running.

It seems similar to [this issue](https://github.com/Rem0o/FanControl.Releases/issues/177), but the trigger in the linked issue appears time based while mine is based on power state.

**Comment by Rem0o** [comment]
Changed the wake/sleep routine for FanControl in V86, see if that helps.

**Comment by pinapl** [comment]
Thank you! I haven't noticed any issues since the update, so fingers crossed that the issue never shows again

**Comment by pinapl** [comment]
Popping in to say that I haven't had any reversed control issues since V86 was released. I don't have any reason to keep this open, so should I click that "close with comment" button?
