### ISSUE TITLE
Crashing when trying to refresh sensors.

### ISSUE THREAD

**Issue by Rporter996** [Rem0o/FanControl.Releases#2660]
Got a new GPU 4080 super and when I try to refresh my sensors it loads for a second then freezes and crashes. I've tried deleting all files and reinstalling multiple different versions it still crashes.

**Comment by Rem0o** [comment]
Any logs or EventViewer event?

**Comment by Rporter996** [comment]
Faulting application name: FanControl.exe, version: 198.0.0.0, time stamp: 0xbbb0526f
Faulting module name: atiadlxx.dll, version: 31.0.24028.3, time stamp: 0x65f0ebb1
Exception code: 0xc0000409
Fault offset: 0x0000000000162bf1
Faulting process id: 0x0x4688
Faulting application start time: 0x0x1DAECFBF0759E0C
Faulting application path: C:\Program Files (x86)\FanControl\FanControl.exe
Faulting module path: C:\Windows\SYSTEM32\atiadlxx.dll
Report Id: c8d23a57-5741-4499-ae3d-6e30acd8d81f
Faulting package full name:

**Comment by Fr0stX76** [comment]
DDU to the rescue

**Comment by Rporter996** [comment]
DDU worked thanks! Now I have to figure out why it's not controlling my
pump and fans,

**Comment by pikausp** [comment]
In case someone comes here because looking for `atiadlxx.dll`, my issue was that the app was detecting igpu, but I had it disabled in bios. Unticking the option fixed it.

**Comment by Rem0o** [comment]
> In case someone comes here because looking for atiadlxx.dll, my issue was that the app was detecting igpu, but I had it disabled in bios. Unticking the option fixed it. 

I fear most crashes with atiadlxx.dll are happening on Ryzen systems with igpu. Since they are not relevant for fancontrol, I think I will be filtering them out to avoid further issues.

**Comment by Rporter996** [comment]
> > In case someone comes here because looking for atiadlxx.dll, my issue was that the app was detecting igpu, but I had it disabled in bios. Unticking the option fixed it.
> 
> I fear most crashes with atiadlxx.dll are happening on Ryzen systems with igpu. Since they are not relevant for fancontrol, I think I will be filtering them out to avoid further issues.

That was exactly my issue! But using DDU seemed to fix it and its working flawlessly now! Thanks for the great app!!!
