### ISSUE TITLE
1 one of the Speed sensor just not working after the V199 Update!

### ISSUE THREAD

**Issue by Shanes26** [Rem0o/FanControl.Releases#2661]
As the title said, one of my speed sensor just not working after the update, it was fine before and been able to show all the RPM of my fans, but its just stopped working, although all the settings and curve that i set still working fine, im just kinda sad that one of my RPM sensor just stopped working, if u have the time, please take a look at it, it'll be much appreciated, and i love your work by the way :D

**Comment by Rem0o** [comment]
Which "one" ? Screenshot? What motherboard?

**Comment by IronMikeyB** [comment]
I'm seeing the same issue.  System1 fan drops to 0RPM on my MSI B460I Gaming Edge Wifi.

![Screenshot 2024-08-13 184417](https://github.com/user-attachments/assets/1c020f88-5abe-46cf-a391-aa6346fa8665)

**Comment by Rem0o** [comment]
How is that control configured? Screenshot the expanded control.

**Comment by IronMikeyB** [comment]
I played around with the configuration of that sensor.  I'd previously calibrated it on an older version of FanControl.  Recalibration seems to have sorted it out.

**Comment by Shanes26** [comment]
> Which "one" ? Screenshot? What motherboard?

thanks for the reply, after investigating the physical fan, i found that 1 of my fans rpm sensor just died (the fan still spinning tho), i also can smell the burn, and after i change the broken fan with the new one it was detected the rpm after i recalibrate the sensor automaticallu, sorry for the mess i made, your program is fine, its just my pc and me XP
