### ISSUE TITLE
FanControl >V193 missing 5/7 ASRock MB temp sensors

### ISSUE THREAD

**Issue by BlueTalon6** [Rem0o/FanControl.Releases#2662]
**Describe the bug**
V194 and later only show 2 of the 7 MB temp sensors, which are available in LHM (any version).
![image](https://github.com/user-attachments/assets/8b50a730-c8ac-46e6-a2b5-d38c337d6480)
![image](https://github.com/user-attachments/assets/7cadb284-6a29-434f-a393-a1c3a48a66f6)

<=V193 shows all 7.
![image](https://github.com/user-attachments/assets/7b46da99-be07-4d40-9117-ad68fe362a47)

I've read https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility, but v193+ all use LHM 0.9.3 (according to LibreHardwareMonitorLib.dll metadata)

The fact that >=V194 show an old nickname from LHM, for "Temperature # 2" ("Motherboard") makes me think the sensors might be cached somewhere, but same results with fresh copies of FanControl and LHM in new dirs. Refresh Sensors Detection doesn't rectify either.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No

**Relevant hardware specs and setup**
ASRock Z690 Steel Legend WiFi 6E

**Comment by Rem0o** [comment]
I compile LHH myself from the latest commit on master (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commits/master/),  The latest release from LHM dates like 8 months, so it is not up to date at all.

**Comment by BlueTalon6** [comment]
Thanks. They named known sensors only in https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1343
