### ISSUE TITLE
When Custom sensor is averaging over values and one of the values is NaN the whole value passed for curves is NaN

### ISSUE THREAD

**Issue by Otsomies** [Rem0o/FanControl.Releases#2665]
**Describe the bug**
I want to have a custom sensor and pass a value as an average from that custom sensor. 
If that custom sensor has sensor that gives NaN value the whole value passed onwards results in NaN value. 

Proposal for solution: Ignore NaN values when doing averages.
See the image attached:

![image](https://github.com/user-attachments/assets/697c18bb-f229-4b91-8f8c-31949ee641b8)

**Comment by Rem0o** [comment]
What is that NaN sensor? Is it from a plugin?

**Comment by Otsomies** [comment]
> What is that NaN sensor? Is it from a plugin?

Yep. For this case it's sensors coming from HWinfo64. 
Sometimes HWinfo64 is buggy, i have closed it, or i don't have it open when opening FanControl and then it's causing the following behavior.

**Comment by Rem0o** [comment]
You can get memory temperature if you use the "GPU" section of LHM and untick nvapiwrapper.
