### ISSUE TITLE
Auto curve randomly defaults to minimal fan speed

### ISSUE THREAD

**Issue by inobrevi** [Rem0o/FanControl.Releases#2667]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

On multiple occasions and randomly Auto Curve I set for CPU fan defaults to minimal fan speed until I change any value in configuration.

Expected behavior:
![2024-08-18 17_30_07-Fan Control V199 (userConfig json)](https://github.com/user-attachments/assets/e5977e7a-1c18-4e1d-bbdd-0104c7d64416)

Random default to min speed:
![2024-08-18 17_28_36-Fan Control V199 (userConfig json)](https://github.com/user-attachments/assets/66b97c05-a184-4a2f-87bf-af68d4594e30)

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No relevant information (last entry couple days ago, problem is occurring now)

**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]

**Comment by Rem0o** [comment]
It isn't random.  If your temperature is stable enough under the load temperature, the function will progressively slow down the fan as long as the temperature doesn't creep up towards the load temperature.  That's the whole point of the Auto fan curve.  If you want a classic linear progression, go with a graph or linear fan curve.

**Comment by inobrevi** [comment]
I see, 

Thank you for explaining, sorry for bothering you.

**Comment by Rem0o** [comment]
Not an issue glad to answer questions.
