### ISSUE TITLE
AMD GPU controls don't work as intended

### ISSUE THREAD

**Issue by kgorin8** [Rem0o/FanControl.Releases#2668]
**Describe the bug**
At some point AMD fan control was not working. Then after some Adrenaline update it suddenly started working according to Fan control curve actually.
After a recent Adrenaline update it started working poorly for me. The fans were going max speed when according to the curve they should be at 50%. So now I realized FC is applying custom preset which is
1) not accurate to the curve. if you try to manually control it it applied a flat line there. I don't think Adrenaline likes that kind of behavior with constantly changing settings
2) it applies this behavior every time even though I switched off control in FC.

The second one is a big deal as I have to go and manually reset Adrenalin settings when I start a game.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
RX 6750 XT
Adrenalin 24.7.1 (recent)
Fan Control 199
![image](https://github.com/user-attachments/assets/bc2a2e18-4a6e-4fca-9c42-8dd8c7213901)

**Comment by Rem0o** [comment]
1. Is normal. Thats the way fancontrol can apply a set % ignoring the built-in curve. 

2. Is a real problem that I will address in the next version. Actually realized that behaviour was a problem from an other user some days ago and a fix is in the works.

Some versions of the driver really did not play well with tuning from ADLX. So there may be some pinch of that in the mix in your case.

**Comment by kgorin8** [comment]
Adrenaline fan control got a lot better by default settings in a couple of recent months. Now I don't honestly think I want to use any curves for it. They even implemented some AI there that you can point to a mic to listen to noise. Probably a nice feature to have at some point in FC.

**Comment by Rem0o** [comment]
Hi,

With the AMD control disabled in FanControl, it shouldn't reset your settings in Adrenaline now as of V200+.

**Comment by kgorin8** [comment]
Does FC still interact with Adrenaline? After startup Adrenaline screen is always shown, while previously it started in tray.

**Comment by kgorin8** [comment]
The window pops after games are launched. Seems weird.
