### ISSUE TITLE
Fancontrol causes Windows to Reboot unexpectly (Event Viewer Code 1001/1002)

### ISSUE THREAD

**Issue by thegame4craft** [Rem0o/FanControl.Releases#2677]
**Describe the bug**
My PC crashed (or rebooted) in the recent few weeks sometimes. No BSOD, no "Rebooting...", just a black screen and the pc boots up again. I just thought it was a faulty power supply and searched for an alternative one to test it. Today the random reboot occurred again and i look into the windows event log. Just shortly before the time windows reboots, in the event log there are two (one of each) entries with eventid 1002 and 2 seconds later on with 1001. I have a .evtx (an export from the event log) on my desktop. Should i send it here? Maybe using E-Mail or other ways? 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
(No Logs, just from previous versions)

**Relevant hardware specs and setup**
Amd Ryzen 5 3600
Amd radeon Rx 570
Asus prime b450-plus
16gb ddr4 memory
FanControl V199

**Comment by Rem0o** [comment]
Send just the relevant entries.

**Comment by Rem0o** [comment]
The event viewer data shows no meaningful details or hint as to what's happening.  
The windows crash+reboot might be what causes the event viewer event for fan control, not the other way around.  Can't help you really at this point.

**Comment by richardm1** [comment]
What are the RX570 fans doing at the time of shutdown?  I've learned these cards will power-off your system if you're too aggressive about forcing the fans to a low RPM.  Even if the GPU sensor is reporting an acceptable 65-70C it seems other parts of the card (possibly the RAM) might be overheating.  I made these shutdowns go away by enforcing a minimum 1200rpm.
