### ISSUE TITLE
won't start on windows start up

### ISSUE THREAD

**Issue by PantheonOfSol** [Rem0o/FanControl.Releases#2679]
fan control won't open on start.

**Comment by d-e-n-n-i-s-t** [comment]
It does work for me

Do you have a FanControl entry in task scheduler?

**Comment by Rem0o** [comment]
![image](https://github.com/user-attachments/assets/f65969fd-eeb2-4595-876e-f108ffc4a4aa)

On some system, a delay is required to work on startup. Make sure you got something like 30 seconds.

**Comment by PantheonOfSol** [comment]
> ![image](https://private-user-images.githubusercontent.com/14118956/360724099-f65969fd-eeb2-4595-876e-f108ffc4a4aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzczNjYsIm5iZiI6MTcyNDM3NzA2NiwicGF0aCI6Ii8xNDExODk1Ni8zNjA3MjQwOTktZjY1OTY5ZmQtZWViMi00NTk1LTg3NmUtZjEwOGZmYzRhNGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAxMzc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZDJkNmJkMzlmYWQ4ODM3NTVlZDBhYzYxYzM1YmY5ZDRiNmY1ZDkwOTUyYmY0ZTA0NzZkNTUzYzlmZjkwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ypYB6gZL8If1rsv8qkErnJ9cU6ukgP6Xse7dulKP5GE)
> 
> On some system, a delay is required to work on startup. Make sure you got something like 30 seconds.

i think this worked
