### ISSUE TITLE
GPU Fan Control does not allow fan curve

### ISSUE THREAD

**Issue by Xuberone** [Rem0o/FanControl.Releases#2684]
![Screenshot 2024-08-25 090144](https://github.com/user-attachments/assets/da9de937-87f0-44ee-9e70-c9a747ea1d37)

Hi all, as you can see from the screenshot, fan control currently does not allow for fan curve for my gpu (4060ti). How do I rectify this issue?

**Comment by Fr0stX76** [comment]
You remove "manual control" by clicking on the 3 dots of the card

Then you hit the toggle of the card So it turns green like the 2 other cards on the SS)

**Comment by Xuberone** [comment]
that helped! thank you!

**Comment by Xuberone** [comment]
that helped! thank you!
