### ISSUE TITLE
Start with windows

### ISSUE THREAD

**Issue by skoer** [Rem0o/FanControl.Releases#269]
Hi there, I'm having problems getting the program to consistently start with windows.  I have "Start with windows" checked and it sometimes starts, but when it fails to start with windows, I manually start the program and the "Start with windows" is now unchecked. Appreciate any guidance on how to resolve.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/122772294-3a891100-d275-11eb-8355-28ea61e24c01.png)

The checkbox is basically the state of this task. If it gets unchecked, then somehow the task got deleted.

**Comment by skoer** [comment]
Still having recurring problems with this - I can see that the event task is being deleted but I have no idea what is doing that - examples below:

![image](https://user-images.githubusercontent.com/86178765/142400183-3733113d-7ced-4f12-8bda-acb5857ea2b6.png)

Any ideas on troubleshooting would be appreciated.

Thanks
