### ISSUE TITLE
UI Freeze when saving or loading a config

### ISSUE THREAD

**Issue by ProtekDev** [Rem0o/FanControl.Releases#2690]
I dont know why but since few updates this doesnt even work for me.
When i try to save or load a config it instantly crashes/freeze.

**Comment by yanislouis** [comment]
same for me

**Comment by Rem0o** [comment]
What CPU and GPU?

**Comment by Rem0o** [comment]
Do you have the controllers checkbox checked in sensor sources? If so try to untick.

**Comment by ProtekDev** [comment]
Okay i have to correct my initial problem.
It looks like it switches the profile, but this process is taking more than 1 minute.
And i have disabled the "Storage" Sensors also, but very long ago (this prevented my external harddrives from ejecting).
![1](https://github.com/user-attachments/assets/999dbe2a-5196-4ace-8927-ec81a2b69287)
![2](https://github.com/user-attachments/assets/d44978ce-e160-497e-a649-56885d9a2f89)

https://github.com/user-attachments/assets/59d6f5d6-47e2-4532-ae99-d272893ea5f1

**Comment by Rem0o** [comment]
It might be the liquid ctl plugin also. Basically it has to be one of these sources causing problem. Narrow it down.

**Comment by yanislouis** [comment]
> What CPU and GPU?
4090 + 7800x3d I set up my curves fan control makes my GPU fans works like I asked, but if I try to link the GPU fan to its rpm sensor it.crashes when I wanna save it

**Comment by ProtekDev** [comment]
> It might be the liquid ctl plugin also. Basically it has to be one of these sources causing problem. Narrow it down.

Yeah i had to disable this luqidctl for all my presets.
It works now as expected.

BUT: i am no longer able to control the speed of my AIO Pump.
I dont like it to run on 100%. 
Because its really annoying (high frequenzy).

And ive noticed that this liquidctl plugin is constantly restarting (when its enabled).
Maybe there is a different way to implement it ?

![liquidctl](https://github.com/user-attachments/assets/f541efef-0689-4c1e-a5e9-6f095ad31cc8)

**Comment by ProtekDev** [comment]
Update: i can control the speed of my AIO Pump when i re-enable the "controller (various third parties)".
Thanks for the support !

**Comment by SnowMN253** [comment]
I also have this issue since i updated version today, should i go without Liquid plugin for  now only, is there going to be a way to resolve this? or should i look for another way-soft to control pump from now on?

Thanks in advance

**Comment by dcog989** [comment]
https://github.com/Rem0o/FanControl.Releases/issues/2728
