### ISSUE TITLE
Lost all paired sensors and controls after reboot, cannot restore from config

### ISSUE THREAD

**Issue by chorong761** [Rem0o/FanControl.Releases#2691]
**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]

Yesterday I rebooted my PC, and today I noticed all my fan curve pairings are gone. I tried "import from configuration"  but it would only say "There is no fan curves or custom sensors to import". "Load Configuration" would just load nothing (just says it has loaded the config, but no settings restored).

My custom curves are still there, just lost the fan speed sensor pairings, calibration data, and curve paring. It has happened many times over the past few years (now it's bugging me enough to fill a bug report).

Running V199 now and here's what it looks like after rebooting.

![螢幕擷取畫面 2024-08-29 135729](https://github.com/user-attachments/assets/410546c4-4c4b-494f-8720-4889bf7f953b)

**Is there a log.txt file next to FanControl.exe with recent date entries?**

There are no logs close to the date when the issue occurred. Issue occurred on Aug 28, but latest logs dated back to Aug 22

**Comment by corndogslayer** [comment]
I have the same issue after reboot unable to pair any sensors or control fans in any way

**Comment by Rem0o** [comment]
Lookup the "Backup" folder in the configuration folder of the software.  If you got one for V198, try and copy it over to the config folder and load it.

**Comment by chorong761** [comment]
> Lookup the "Backup" folder in the configuration folder of the software. If you got one for V198, try and copy it over to the config folder and load it.

Thanks, that actually worked. I really had to copy the backup file into the config folder first.
