### ISSUE TITLE
Fan not detected

### ISSUE THREAD

**Issue by lou-sheng** [Rem0o/FanControl.Releases#2693]
What can I do if Fan Control fails to detect fans on cpu fan and cha fan? My motherboard model is ASUS B550M Plus.
![Snipaste_2024-08-31_02-49-38](https://github.com/user-attachments/assets/ae1d4b0e-a56b-41fe-a056-de2045058b68)

**Comment by Rem0o** [comment]
Make sure you got "motherboard" sensor source activated.

Otherwise: https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
