### ISSUE TITLE
GPU - only start controlling the curve if at certain temperature?

### ISSUE THREAD

**Issue by andre1808** [Rem0o/FanControl.Releases#2696]
**Describe the bug**
My GPU (Palit Geforce 4080) only allows custom fan speeds at 30% and above.
As soon as any tool (e.g. MSI Afterburner) starts trying to set custom fan speeds, the fan will just start spinning at 30%, even if it's set below that.
What's making this extremely annoying is, that my fans have some weird sound at 30-34% fan speed. It's so annoying, that I'd rather run them faster (and louder) than at 30-33%.

I've tried setting a graph with Fan Control, which only kicks in at 45°C. But as soon as I toggle that one on, the fans will ramp up to 30%, even if the gpu did not reach 45°C yet.

Is there any way to have it automatically toggle on at 45°C?
I've tried setting the graph to 0% until 45°C and at 45.1°C fan speed to 34%. But that doesn't work.
Also changing the min temp to 45°C doesn't help (that's my current setup).
![image](https://github.com/user-attachments/assets/d7421453-6004-4ccb-b6b7-a1529c0f8ebd)
![image](https://github.com/user-attachments/assets/c716c7a1-56e2-4847-9c1a-8493851d7547)
![image](https://github.com/user-attachments/assets/0345bd53-8ee0-428d-891a-c8d4735d8583)

Any help would be highly appreciated!
Thank you in advance!

**Comment by Rem0o** [comment]
Your graph needs to hit 0% below 45.  Do some kind of staircase like this, but at 45 
![image](https://github.com/user-attachments/assets/56f7afb5-1c03-4a40-88b0-06f5428955e6)

**Comment by andre1808** [comment]
Thank you for your reply.
That's actually what I've tried before and resulting in the issue I'm having with the fans just spinning up to 30% no matter how cold / warm the GPU is.

I have the feeling that the GPU will only stop fans if it's controlling them themself. But as soon as any task is trying to interfere it will ramp them to 30%.
![image](https://github.com/user-attachments/assets/cd9576c7-ef9d-42aa-ba01-7d7d328bc03e)
![image](https://github.com/user-attachments/assets/38530c71-69f0-4506-b3cb-fff7277e865e)

**Comment by Rem0o** [comment]
Go in sensor source in the settings. Make sure the nvidia override checkbox is on.

**Comment by andre1808** [comment]
This helped a bit :)
It doesn't ramp up the fans now when I toggle it on, but if I hit the temperature (e.g. 60%) so the fans start spinning, it won't stop them.
This is a screenshot after it hit the temp (and it's sitting like this for the past 3-5min)
![image](https://github.com/user-attachments/assets/890c4efe-eb57-463d-bf11-20f0a3764b41)

And this is when I've toggled the graph off and back on:
![image](https://github.com/user-attachments/assets/6da18dd7-4338-485e-af75-31d9898ec812)

**Comment by andre1808** [comment]
Do you have any further idea probably? :(
I guess there is no way to sort of automatically toggle the switch off and back on whenever the temp falls below the defined temperature? :)

I really love your tool - that's just the only issue I've got unfortunately.

**Comment by Rem0o** [comment]
> I guess there is no way to sort of automatically toggle the switch off and back on whenever the temp falls below the defined temperature?

The nvidia override checkbox does <i>exactly</i> that.  If a fan curve asks for 0%, the control is disabled.  The checkbox won't move, but under the hood, it's off.

**Comment by andre1808** [comment]
Hm that's strange. If I manually toggle, it's pretty much instantly dropping to 0%.
I've created a little video to demonstrate.

https://github.com/user-attachments/assets/c7d86c41-62f2-4bc0-bc68-ebb9d649af78

**Comment by Rem0o** [comment]
Disable force apply and set the start percentage to 30.

**Comment by andre1808** [comment]
Thank you so much! This works!
It's taking 20-30 seconds until they stop spinning, but they indeed do stop!
Love it!

Thank you for your brilliant support. I've sent you a little donation.
