### ISSUE TITLE
How do you uninstall FanControl?

### ISSUE THREAD

**Issue by backflip2** [Rem0o/FanControl.Releases#2698]
Today I tried Fan Control for the first time. And it did work as intended. I use W10.

For some test reasons I want to uninstall in order to remove any issue with ASUS Fan Xpert. I see no uninstall exe file. And in the Windows System Control Panel, I find no line in the list of programs with a name with reference to Fan Control. So how can I uninstall FanControl?

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#uninstall
