### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by W-Both** [Rem0o/FanControl.Releases#27]
the program used to work amazing but as of recent it wont open or rarely will but without my fan profile
Ive tried reinstalling the program many times and nothing has fixed it
i think the issues started after updating from v 45 to v 46

![image](https://user-images.githubusercontent.com/70458100/91649578-e11ede00-eab8-11ea-9aee-88215fddce94.png)

**Comment by Rem0o** [comment]
Are you running with full privilege? Have you tried moving it into an other folder?

**Comment by W-Both** [comment]
it kept giving me a windows do not run window so i opened my antivirus and
it allowed it to show the ask for permission window and now its working
again

**Comment by Rem0o** [comment]
Good, will close.
