### ISSUE TITLE
RTX 4080 Super not under 30% & Offset

### ISSUE THREAD

**Issue by riomio1** [Rem0o/FanControl.Releases#2701]
Hey there,

first of all i love this piece of software, such a great work thanks for that.

since a few days my RTX 4080 Super from Aero won't drop below 30% anymore. I know about the setting with the hardware override and its ticked on. I did some research aswell, as others have the same issue, but didn't find any solution for me. I'll attach my FanControl setup and the GPU fancurve.
![Screenshot 2024-09-03 160216](https://github.com/user-attachments/assets/6e45636b-12e1-48c9-b97a-35ee5ed39229)
![Screenshot 2024-09-03 160334](https://github.com/user-attachments/assets/eefa426a-4f90-46c2-80b6-14cc26c09ca7)

Furhtermore it seems i can't use the offset option for fanspeeds anymore, but only the minus one. When i want to offset a fan 5% up it works fine, but down it does nothing. Any suggestions?

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/user-attachments/files/16850009/log.txt)

Any help would be very much appreciated. Thanks.

**Comment by Rem0o** [comment]
Do you have multiple monitors plugged into your GPU? Saw some cases where GPU won't go 0 RPM if the load is above a threshold, which powering 2 monitors may cross. As for offset, well, I don't see how it doesn't work.  Off course if you try to offset below 30 for your GPU, that won't work.

**Comment by riomio1** [comment]
I have multiple monitors yes, but i've heard about that too and tried to unplug one to test if it was that, but it didn't change anything, unfortunately.
No the offset would be for the case fans as one is a bit higher in RPM, as u can see in the picture. But yea i don't know why its not working. It even shows at the percentage level in the fan control card 24% e.g. when i set -6% but the RPM won't change.

**Comment by Rem0o** [comment]
> It even shows at the percentage level in the fan control card 24% e.g. when i set -6% but the RPM won't change.

@riomio1   30 is a floor limit, you can't go lower. -6 from 30 is under 30, so of course that won't work.

**Comment by Turranius** [comment]
Same problem here when I attach a curve. Any curve at all and the fans on the GPU start spinning at 30%. 

If I disable the curve it goes down to 0% (0 RPM) as it should.

3080Ti. 

In other words, if I want to control the GPU fans with Fan Control, they will always be running at 30% minimum instead of 0% if I do not set a curve...

**Comment by Turranius** [comment]
![image](https://github.com/user-attachments/assets/bec677c4-8037-47ab-9d39-2d2e3c560704)
![image](https://github.com/user-attachments/assets/e68ccd00-5e67-423e-8d7a-6accea46e975)

**Comment by Rem0o** [comment]
See the nvidia section here https://getfancontrol.com/docs/

Also make sure you have the 0% override option on in sensor sources in the settings.

**Comment by Turranius** [comment]
That explains it. I checked the 0% override and now it stays at 0% until it gets any other command.. it then jumps to a minimum of 30%, which I understand is the minimum Nvidia cards can go to on command.

Thanks for a quick response!
