### ISSUE TITLE
Crashes after PC resumes from standby

### ISSUE THREAD

**Issue by Navi2016** [Rem0o/FanControl.Releases#2710]
**Describe the bug**
Running Windows 10 Pro 22H2, ever since i think v198, maybe even earlier, FanControl crashes after the PC resumes from standby. (regular standby, not hibernate)

Still happens on v199 and v200.

Did not happen before, been running FanControl for 1 year+

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No

**Relevant hardware specs and setup**
Asus ProArt X670E, AMD 7950X, RTX2080S

**Comment by Navi2016** [comment]
Found in Application log:
Faulting application name: FanControl.exe, version: 200.0.0.0, time stamp: 0xf4646609
Faulting module name: atiadlxx.dll, version: 31.0.24002.92, time stamp: 0x65a0256d
Exception code: 0xc0000409
Fault offset: 0x0000000000162b19
Faulting process id: 0x11c7c
Faulting application start time: 0x01daff8267cbd47a
Faulting application path: C:\DATA\apps\FanControl\FanControl.exe
Faulting module path: C:\WINDOWS\SYSTEM32\atiadlxx.dll
Report Id: 93314a5b-a294-4e6d-8ad5-03b2e75b8649
Faulting package full name: 
Faulting package-relative application ID: 


So maybe the same as #2669 and #2670 

Have disabled ADLXWrapper now and will update results soon..

**Comment by Navi2016** [comment]
Disabling ADLX seems to fix the issue.

Will try latest AMD drivers soon.

**Comment by arielmoraes** [comment]
+1 here.

**Comment by JN848433** [comment]
How do I disable ADLX? @Navi2016

**Comment by Navi2016** [comment]
In FanControl, go to Settings > Sensors > Edit sources and uncheck ADLXWrapper

**Comment by JN848433** [comment]
That worked! Thank you!

**Comment by Rem0o** [comment]
@JN848433  anything in your log.txt?

**Comment by Shaedwell** [comment]
I'm having the same problem with multiple versions of fancontrol and AMD Adrenalin.
A workaround I found somewhere on the web is adding the "On workstation unlock" trigger to the FanControl task in task scheduler.

**Comment by DarthZyll** [comment]
I too have this issue. I run with ADLXwrapper, and I am using an older AMD Adrenalin v24.1.1 because my game doesn't run as well with the latest version of Adrenalin. The workaround that @Shaedwell mentioned above worked for me, but obviously this is a bandaid because the service should not be crashing in the first place.

**Comment by Rem0o** [comment]
@DarthZyll  The crash happens inside the driver itself, which FanControl is hooked to. There was a few updates to Adrenaline which fixes a few bugs with the driver. Latest version from a clean install seems stable now.  There may be an integration problem from ADLXWrapper/FanControl, but a driver update fixing it for people points toward a driver problem.

**Comment by DarthZyll** [comment]
v202 today fixed the issue for me, i no longer need to do an "on workstation unlock" trigger to restart FanControl. Kudos!

**Comment by Shaedwell** [comment]
> v202 today fixed the issue for me, i no longer need to do an "on workstation unlock" trigger to restart FanControl. Kudos!

Same here. Everything working as it should. +1 Kudos!
