### ISSUE TITLE
V200 Some words/sentences changed to french? since v199

### ISSUE THREAD

**Issue by Impact123** [Rem0o/FanControl.Releases#2713]
**Describe the bug**
Some words/sentences have been replaced with french? ones in version v200.

## v199
![image](https://github.com/user-attachments/assets/86565d04-c63e-4e5f-89a5-12c8afc2a1a1)
![199_2](https://github.com/user-attachments/assets/659dd6b2-6f56-41b5-865c-106a6b640b80)

## V200
![image](https://github.com/user-attachments/assets/ea38bfb4-a4f0-40b9-879c-0a8ebce733af)
![v200_2](https://github.com/user-attachments/assets/7cb0ac30-8183-4dc2-8c5b-f6bba04d782e)
I assume it has something to do with this new option.
![v200_3](https://github.com/user-attachments/assets/54a4a717-124d-4588-853a-657e14408fd8)

**Comment by Rem0o** [comment]
I'm aware some translations slipped by.  Will be fixed next version.

**Comment by Impact123** [comment]
This is fixed in v201. Thanks.
