### ISSUE TITLE
Switching off ADLXWrapper crashes FanControl

### ISSUE THREAD

**Issue by JN848433** [Rem0o/FanControl.Releases#2717]
I thought I'd open a separate ticket for this as it is a separate bug. Not a big issue as restarting FanControl solves the issue.

Switching ADLXWrapper OFF in settings throws the following error when the refresh of the sensors is done afterwards in Windows Event log.

Anwendung: FanControl.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.AccessViolationException
bei ADLXWrapper.Bindings.ADLXPINVOKE.delete_ADLXHelper(System.Runtime.InteropServices.HandleRef)
bei ADLXWrapper.Bindings.ADLXHelper.Dispose(Boolean)
bei ADLXWrapper.Bindings.ADLXHelper.Finalize()

**Comment by Rem0o** [comment]
Update to V201 and see if this still happens?

**Comment by StainlessSteele** [comment]
I am on V201, and trying to edit my sources, and refresh crashes the app reliably. I tried uninstalling and reinstalling with the .net 8 version as well: crash report:
Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: FanControl.exe
P2: 201.0.0.0
P3: 66960000
P4: 0d63
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\Critical_FanControl.exe_70c9c0940d382ddadd8f4448c8f37dec7ac3e9_6b9e5809_f552fdf6-36d3-4692-87f6-0609c2c21994

Analysis symbol: 
Rechecking for solution: 0
Report Id: 17f3a2bb-8293-4c11-91e8-696ccc3a85a9
Report Status: 4
Hashed bucket: 
Cab Guid: 0

**Comment by Rem0o** [comment]
@StainlessSteele 
This doesn't look like an EventViewer crash report.

@JN848433 Did you update to V201?

**Comment by jilherme** [comment]
from event viewer:

Application: FanControl.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ADLXWrapper.Bindings.ADLXPINVOKE.delete_ADLXHelper(System.Runtime.InteropServices.HandleRef)
   at ADLXWrapper.Bindings.ADLXPINVOKE.delete_ADLXHelper(System.Runtime.InteropServices.HandleRef)
   at ADLXWrapper.Bindings.ADLXHelper.Dispose(Boolean)
   at ADLXWrapper.Bindings.ADLXHelper.Finalize()

![image](https://github.com/user-attachments/assets/861507cd-f596-4707-9751-52f9846701a9)

portable version just crashes, but the installed version (v202) gives me the error from the image

**Comment by Rem0o** [comment]
@jilherme  do you have an AMD GPU at all with Adrenaline installed?

**Comment by jilherme** [comment]
> @jilherme  do you have an AMD GPU at all with Adrenaline installed?

I have an AMD iGPU, with latest adrenalin drivers installed. ryzen 7 7700x.

**Comment by Rem0o** [comment]
Right, but from 202, do you get the hard crash still or just the popup error? If you only have an iGPU you can disable ADLX all together, it's meant for dedicated gpus.

**Comment by jilherme** [comment]
> Right, but from 202, do you get the hard crash still or just the popup error? If you only have an iGPU you can disable ADLX all together, it's meant for dedicated gpus.

I'm in bed right now, but I think I can't adjust any settings. If I remember correctly the app crashes after a couple of seconds

**Comment by TheSangral** [comment]
> Right, but from 202, do you get the hard crash still or just the popup error? If you only have an iGPU you can disable ADLX all together, it's meant for dedicated gpus.

I only got the popup in 201 and now in 202 I get hard crashes with this error of the app. I don't know what the heck happens here, I didn't change any settings, I don't have an AMD GPU at all, this just appeared after updating to 201 and I don't know where to disable this, I looked everywhere and I have zero plugins installed. It's driving me mad.

**Comment by Senaxx** [comment]
Same issue here. 

Clean windows install - AMD chipset drivers installed. I'm getting a crash on startup with ADLXWrapper message shown here. It's the same screen as @jilherme posted. 

Log just says: 
```
9/17/2024 1:34:50 AM: Initialization failed. Retry count (2) exceeded.
9/17/2024 1:35:09 AM: Initialization failed. Retry count (2) exceeded.
9/17/2024 1:36:10 AM: Initialization failed. Retry count (2) exceeded.
9/17/2024 1:36:56 AM: Initialization failed. Retry count (2) exceeded.
```

**Comment by DrBoiko** [comment]
Same issue, started to occur after I updated to 202 just now. Log just says:

9/17/2024 7:34:43 PM: Initialization failed. Retry count (2) exceeded.

**Comment by etherealremnant** [comment]
> Same issue here.
> 
> Clean windows install - AMD chipset drivers installed. I'm getting a crash on startup with ADLXWrapper message shown here. It's the same screen as @jilherme posted.
> 
> Log just says:
> 
> ```
> 9/17/2024 1:34:50 AM: Initialization failed. Retry count (2) exceeded.
> 9/17/2024 1:35:09 AM: Initialization failed. Retry count (2) exceeded.
> 9/17/2024 1:36:10 AM: Initialization failed. Retry count (2) exceeded.
> 9/17/2024 1:36:56 AM: Initialization failed. Retry count (2) exceeded.
> ```
> 
> Downgraded to v200 and it works.
> 
> AMD 7800x3d 4090

Thanks. V200 worked for me with my Ryzen 7 9700X that was crashing too.

**Comment by Rem0o** [comment]
See V203

**Comment by JN848433** [comment]
> V203

Yes and for me it all works on V203. Thank you for your dedication!

**Comment by JN848433** [comment]
Issue closed as error is fixed.
