### ISSUE TITLE
Fan Control Not Showing CPU Sensor

### ISSUE THREAD

**Issue by AmishMayhem** [Rem0o/FanControl.Releases#2719]
I just built a new desktop computer for someone else. When I went to set up the fan curves with fan control, I noticed that the CPU sensors weren't showing, and very few other sensors. Is the motherboard/cpu the culprit or is it the software? Is there something I'm missing?

Mobo - Asus Strix B650E-F
CPU - Ryzen 9 9900X
Cooler - Liquid Freezer iii 360mm

Thanks!
![IMG_8217](https://github.com/user-attachments/assets/7c90f0a4-cd91-4213-8bd5-c2ef050c77fb)

**Comment by Rem0o** [comment]
9000 series AMD are not supported yet.
