### ISSUE TITLE
Missing sensor (fixed by having Libre Hardware Monitor running)

### ISSUE THREAD

**Issue by R3lay0** [Rem0o/FanControl.Releases#272]
When I start the program normally all the sensors don't show up. If I have Libre Hardware Monitor running in the background before starting FanControl the sensors show up as expected. 

I'm running Windows 10 Pro 20H2 and I have the MSI B450 Tomahawk Max (I don't know if more information would be helpful)

**Comment by Rem0o** [comment]
Are you running as admin?

**Comment by R3lay0** [comment]
I am

**Comment by R3lay0** [comment]
Btw what version of Libre Hardware Monitor are you using? I can try using that version to see wheter it's just a problem with the LHM version.

**Comment by R3lay0** [comment]
Seems to be fixed in V84. Thank you for your work on this great project!
