### ISSUE TITLE
Crash during configuration change.

### ISSUE THREAD

**Issue by udioica** [Rem0o/FanControl.Releases#2729]
FanControl has been crashing whenever I try to change configuration. It does not matter if I change the configuration from the tray icon or from the GUI. It happens almost always (9 out of 10 times _I guess_). I have been facing this problem for a while now and over few updates. I have 3 configurations (Silent, Gaming and Full Blast) and I always update FanControl using the updater whenever I am notified on startup.

PC specs:

Mother Board: ASUS ProArt B650-Creator
Processor: AMD Ryzen 9 7900X
Graphics Card: EVGA 3080ti FTW ultra
RAM: Kingston Fury 32GB (2×16GB) DDR5 6000MT/s
Storage: Kingston KC3000 2TB PCIe 4.0 NVMe M.2
Case + Fans: Lian Li lancool II mesh c including 3 fans
CPU Cooler: Arctic Liquid Freezer II 280

Error log from FanContol log.txt:

14/09/2024 15:11:09: Initialization failed. Retry count (2) exceeded.

Error log from windows event viewer:

Log Name:      Application
Source:        Application Error
Date:          14/09/2024 15:10:51
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Description:
Faulting application name: FanControl.exe, version: 201.0.0.0, time stamp: 0x9a7bac66
Faulting module name: atiadlxx.dll, version: 31.0.24002.92, time stamp: 0x65a0256d
Exception code: 0xc0000409
Fault offset: 0x0000000000162b19
Faulting process id: 0x0x4FC8
Faulting application start time: 0x0x1DB069CC0755060
Faulting application path: C:\Program Files\FanControl\FanControl.exe
Faulting module path: C:\Windows\SYSTEM32\atiadlxx.dll
Report Id: 1c69dc7c-818b-4711-b2dd-5a2306672a2a
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-09-14T12:10:51.4583716Z" />
    <EventRecordID>53469</EventRecordID>
    <Correlation />
    <Execution ProcessID="5304" ThreadID="11808" />
    <Channel>Application</Channel>

  </System>
  <EventData>
    <Data Name="AppName">FanControl.exe</Data>
    <Data Name="AppVersion">201.0.0.0</Data>
    <Data Name="AppTimeStamp">9a7bac66</Data>
    <Data Name="ModuleName">atiadlxx.dll</Data>
    <Data Name="ModuleVersion">31.0.24002.92</Data>
    <Data Name="ModuleTimeStamp">65a0256d</Data>
    <Data Name="ExceptionCode">c0000409</Data>
    <Data Name="FaultingOffset">0000000000162b19</Data>
    <Data Name="ProcessId">0x4fc8</Data>
    <Data Name="ProcessCreationTime">0x1db069cc0755060</Data>
    <Data Name="AppPath">C:\Program Files\FanControl\FanControl.exe</Data>
    <Data Name="ModulePath">C:\Windows\SYSTEM32\atiadlxx.dll</Data>
    <Data Name="IntegratorReportId">1c69dc7c-818b-4711-b2dd-5a2306672a2a</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>
```

**Comment by Rem0o** [comment]
Seems like you got ADLX enabled but you don't have an AMD GPU?

**Comment by udioica** [comment]
Disabling ADLX solved the issue. Thanks.
Updated to v202 and tried to enable it. Still crashes on 202 if enabled.

**Comment by Rem0o** [comment]
> Still crashes on 202 if enabled.

Any log.txt?

**Comment by memlir** [comment]
Can confirm the same with a 7900XTX.

**Comment by udioica** [comment]
> > Still crashes on 202 if enabled.
> 
> Any log.txt? Hard crash or error popup?

Hard crash, and no I don't have AMD GPU.
To show you the logs, I turned ADLX on on all configurations and saved them. Now FanControl crashes before it launches and no new logs are recorded in log.txt 

Windows Event Logs:
1.
Log Name:      Application
Source:        .NET Runtime
Date:          16/09/2024 16:09:40
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Description:
Application: FanControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at ADLXWrapper.Bindings.ADLXPINVOKE.delete_ADLXHelper(System.Runtime.InteropServices.HandleRef)
   at ADLXWrapper.Bindings.ADLXHelper.Dispose(Boolean)
   at ADLXWrapper.Bindings.ADLXHelper.Finalize()

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-09-16T13:09:40.3779807Z" /> 
  <EventRecordID>53824</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="5144" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP[-](https://github.com/Rem0o/FanControl.Releases/issues/2729#)EKJEKFB</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: FanControl.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at ADLXWrapper.Bindings.ADLXPINVOKE.delete_ADLXHelper(System.Runtime.InteropServices.HandleRef) at ADLXWrapper.Bindings.ADLXHelper.Dispose(Boolean) at ADLXWrapper.Bindings.ADLXHelper.Finalize()</Data> 
  </EventData>
  </Event>
```

2.
Faulting application name: FanControl.exe, version: 202.0.0.0, time stamp: 0xf65f8f69
Faulting module name: amdadlx64.dll, version: 31.0.24002.92, time stamp: 0x65a026fd
Exception code: 0xc0000005
Fault offset: 0x000000000009726e
Faulting process id: 0x0x1418
Faulting application start time: 0x0x1DB0839AF073F4A
Faulting application path: C:\Program Files\FanControl\FanControl.exe
Faulting module path: C:\Windows\SYSTEM32\amdadlx64.dll
Report Id: d1a14f73-ba3c-4e8d-8a49-8238cf3eff0c
Faulting package full name: 
Faulting package-relative application ID: 

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-09-16T13:09:40.4369054Z" /> 
  <EventRecordID>53825</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="2192" ThreadID="19708" /> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-EKJEKFB</Computer> 
  <Security UserID="S[-](https://github.com/Rem0o/FanControl.Releases/issues/2729#)1-5-21-503725902-2920488094-1664404369-1001" /> 
  </System>
- <EventData>
  <Data Name="AppName">FanControl.exe</Data> 
  <Data Name="AppVersion">202.0.0.0</Data> 
  <Data Name="AppTimeStamp">f65f8f69</Data> 
  <Data Name="ModuleName">amdadlx64.dll</Data> 
  <Data Name="ModuleVersion">31.0.24002.92</Data> 
  <Data Name="ModuleTimeStamp">65a026fd</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">000000000009726e</Data> 
  <Data Name="ProcessId">0x1418</Data> 
  <Data Name="ProcessCreationTime">0x1db0839af073f4a</Data> 
  <Data Name="AppPath">C:\Program Files\FanControl\FanControl.exe</Data> 
  <Data Name="ModulePath">C:\Windows\SYSTEM32\amdadlx64.dll</Data> 
  <Data Name="IntegratorReportId">d1a14f73-ba3c-4e8d-8a49-8238cf3eff0c</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
```

**Comment by udioica** [comment]
I manually edited the json configuration files to disable ADLX. Now FanControl runs but it did not record anything new in log.txt

**Comment by renattou** [comment]
After upgrading from v201 to v202, FanControl also started crashing for me, but only after the first restart. Deleting userConfig,json and CACHE didn't help. But doing the same thing as @udioica (disabling ADLX manually in userConfig,json) fixed it. Thanks for the temporary fix!

**Comment by memlir** [comment]
crashing here as well. [Log](https://pastebin.com/NUyGS0ne)

initially it was the ADXL, which i found that we need to use the integrated one now.
but now any change results to the App just not reading the configuration file and going in the default state, crashing while at it.

Asus ProArt X670E / AMD 7800X3D / AMD 7900XTX

**Comment by Rem0o** [comment]
@memlir there seems to be still a plugin namely the gpu-z one in the mix from your log.

**Comment by memlir** [comment]
@Rem0o GPU-Z never caused any hiccups except a few occasions where its start is delayed. I just removed the whole app and the folder and have started from scratch. I am not sure what happened, but for me this is the summary of events:

1. v200 worked without any hassle
2. v201 started reporting missing sensors. My investigation was pointing to my ADXL plugin being deprecated, which is now part of the app itself. But it did not fix the issue, even after i disabled the former and enabled the latter.
3. v202 reported the same, and suddenly started loading with the default config. Once you opened the app, it froze, and at times it even froze my machine. Downgrades to v201 and v200 behaved the same.

Fresh install seems to work just fine now. I will try my other plugins later on, but i still am clueless at what corrupted my configuration.

**Comment by renattou** [comment]
v203 seems to have fixed the issue for me!

**Comment by udioica** [comment]
issues solved in v203.
