### ISSUE TITLE
Occasionally individual fans go to 0 and other times PCH sensor not found

### ISSUE THREAD

**Issue by dataslug1** [Rem0o/FanControl.Releases#273]
Hello,
I am running an MSI Z490 gaming plus motherboard and having two intermittent issues with Fancontrol.  I love the premise of this program and would gladly donate if these issues could be solved:

1) Individual fans sometimes go to zero upon launch, as per screenshot below (sysfan 2 and 5 here.  Ignore fan 3 as I have nothing connected).  It is fixable by toggling the green switch to off then back to on but a bit annoying to remember to check each time that all my fans are indeed running.

![Screenshot 2021-06-23 155410](https://user-images.githubusercontent.com/80533773/123333257-69370e00-d539-11eb-9121-b393b7474f32.png)

2) On startup quite often my fans and PCH temperature sensors are not detected as per screenshots below.  Sometimes this is fixed by pressing the refresh button, but other times not and often Fancontrol seems to completely crash as I am unable to close it and have to task kill it.  I think this is similar to this issue https://github.com/Rem0o/FanControl.Releases/issues/187 , although sometimes I don't have the warning and just have a NaN PCH sensor as per second screenshot:
![Screenshot 2021-06-21 091825](https://user-images.githubusercontent.com/80533773/123399920-17c06a80-d59d-11eb-9e92-189e7bdb1327.png)
![Screenshot 2021-06-21 091836](https://user-images.githubusercontent.com/80533773/123399925-18f19780-d59d-11eb-9a41-9f811f12f3af.png)

Thanks for any help that can be provided

**Comment by Rem0o** [comment]
Seems like a conflicting software issue.

**Comment by dataslug1** [comment]
Hmm its a pretty clean install, no other ICue or Hardware monitors or anything running

**Comment by dataslug1** [comment]
I was thinking,  would it be possible for you to set missing fans/sensors to 100% as a failsafe?  Better for them to be accidentally running at 100% rather than accidentally running at 0% !

**Comment by dataslug1** [comment]
I saw you added something like this on the last update, thank you.  However it seems that I still sometimes get a NaN sensor and missing fans, and some of the fans linked to the sensor are at zero (fan 5 in this case)

![image](https://user-images.githubusercontent.com/80533773/126674462-88688bca-7749-4494-a028-6710fb7b3c7e.png)
