### ISSUE TITLE
App Crash After Reviving from Sleep. 

### ISSUE THREAD

**Issue by DeckerCHAN** [Rem0o/FanControl.Releases#2732]
**If you are experiencing a crash**
Link the relevant/associated Windows EventViewer logs, and also FanControl's own log.txt.

```
11/09/2024 12:08:21 AM: Initialization failed. Retry count (2) exceeded.
11/09/2024 4:55:38 PM: Initialization failed. Retry count (6) exceeded.
12/09/2024 3:59:40 AM: Initialization failed. Retry count (2) exceeded.
12/09/2024 5:27:11 PM: Initialization failed. Retry count (2) exceeded.
12/09/2024 11:39:43 PM: Initialization failed. Retry count (6) exceeded.
13/09/2024 4:50:10 AM: Initialization failed. Retry count (2) exceeded.
13/09/2024 2:09:41 PM: Initialization failed. Retry count (6) exceeded.
14/09/2024 1:28:48 AM: Initialization failed. Retry count (2) exceeded.
15/09/2024 12:33:48 AM: Initialization failed. Retry count (6) exceeded.
15/09/2024 2:39:04 AM: Initialization failed. Retry count (2) exceeded.
15/09/2024 9:58:02 PM: Initialization failed. Retry count (2) exceeded.
16/09/2024 12:48:36 AM: Initialization failed. Retry count (2) exceeded.
```

**Describe the bug**

Since upgrading to V200+, I have started having this issue: The app vanishes from the taskbar after the desktop wakes up from sleep. 

I have the following error messages after reviving from sleep:
![image](https://github.com/user-attachments/assets/d3242ddd-ea31-4b64-b53d-05ba5c261f5b)
![image](https://github.com/user-attachments/assets/a4d006b5-80f5-4d7e-be8a-15d99cd2ebeb)

Then, the app vanished. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
![image](https://github.com/user-attachments/assets/53000767-21e0-43ba-a5f9-9a6ada462ee9)
![image](https://github.com/user-attachments/assets/789f5d5c-5ceb-4501-8aaa-cd26942c0ca9)
![image](https://github.com/user-attachments/assets/e98f2d9e-07c4-4472-bae5-68637fd51b06)

**Comment by Rem0o** [comment]
You do not have an AMD dedicated GPU. Disable ADLX.

**Comment by sam0thius** [comment]
Speed Fan crashing after resuming from sleep finally got fixed by the latest version 202 with my AMD (CPU/GPU) system. 👍

**Comment by DeckerCHAN** [comment]
Seems working now thx!
