### ISSUE TITLE
Fancontrol can't read cpu temperature RYZEN 9950X

### ISSUE THREAD

**Issue by wisepds** [Rem0o/FanControl.Releases#2733]
Going from the Ryzen 7950X to the 9950X I have found that FANCONTROL cannot know the CPU temperature so I cannot do CPU related profiling curves.

Will this be fixed soon? is there any way to get it to read the CPU temperature like HWINFO or HWMONITOR does?

Thanks for such an awesome software.

**Comment by wisepds** [comment]
Anybody? Really?

**Comment by Rem0o** [comment]
See 
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/1418 and 
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/1467

Nobody with a 9XXXX worked/dev on the issue yet.

**Comment by wisepds** [comment]
Hi, i’m not a programmer.. i don’t know about this.. sorry..

I guess we must wait 

☹

 

If you know any news please write me, please 😉

Best Regards

Manuel.

 

De: Rem0o ***@***.***> 
Enviado el: miércoles, 18 de septiembre de 2024 17:53
Para: Rem0o/FanControl.Releases ***@***.***>
CC: Wise ***@***.***>; Author ***@***.***>
Asunto: Re: [Rem0o/FanControl.Releases] Fancontrol can't read cpu temperature RYZEN 9950X (Issue #2733)

 

If you want to dig in yourself, start here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/3d02337487bea99b181c84c76adc7884e5e67b94/LibreHardwareMonitorLib/Hardware/Cpu/CpuGroup.cs#L38

Find the corresponding thread family by debugging for the processor and see if the existing Amd17Cpu implementation works or if its need updating.

**Comment by Rem0o** [comment]
Good news:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/23207acb098490523ca1b68488314a88489c4a58

**Comment by wisepds** [comment]
Great news!! So... when be ready on fancontrol? Thanks for share with me!

**Comment by twest820** [comment]
Can confirm v204's good with a 9900X.

**Comment by wisepds** [comment]
Yes!! Works fine!

Thank you very much!
Best regards

Manuel.

 

De: Todd West ***@***.***> 
Enviado el: martes, 24 de septiembre de 2024 21:17
Para: Rem0o/FanControl.Releases ***@***.***>
CC: Wise ***@***.***>; Author ***@***.***>
Asunto: Re: [Rem0o/FanControl.Releases] Fancontrol can't read cpu temperature RYZEN 9950X (Issue #2733)

 

Can confirm v204's good with a 9900X.
