### ISSUE TITLE
Asus PWM Headers dont shut off completely

### ISSUE THREAD

**Issue by TheEngineerGuy** [Rem0o/FanControl.Releases#274]
@Rem0o SpeedFan and Asus FanControl are able to shut the PWM headers off completely to bring the fans to a complete halt when not needed. But with FanControl I am unable to do so.

I am guessing it will be an easy fix for you to look into, so posting here to get your feedback.

**Comment by Rem0o** [comment]
Not really, as I don't your motherboard to test with.   
The backend is handled by : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by TheEngineerGuy** [comment]
@Rem0o this happens on every ASUS motherboard. Take your pick.

**Comment by Rem0o** [comment]
All of the actual driver portion is handled by LHM.  You can download the code yourself and test stuff with your board and open a PR. Any change made there will be merged onto FanControl eventually.
