### ISSUE TITLE
[Bug] Fancontrol not appearing in startup programs for non-primary user

### ISSUE THREAD

**Issue by SomeoneElse00** [Rem0o/FanControl.Releases#2748]
I have multiple non-administrator users on my PC that I would like for fancontrol to launch at startup on. I have the startup settings set to enabled, and enabled (30sec), but the application does not launch during startup for any user except for the primary administrator. After checking task manager, it does not appear in the startup tab for any except the primary admin.

**Comment by Rem0o** [comment]
> I have multiple non-administrator users on my PC that I would like for fancontrol to launch at startup on

That's not possible. An admin user must be running the program.

**Comment by SomeoneElse00** [comment]
Ok, but is it possible for an admin to temporarily run the program to get it to be added to the startup programs list?

**Comment by Rem0o** [comment]
You can setup a schedule task where the user is admin.   The program will run in the background without any ui available to the non admin user.

**Comment by SomeoneElse00** [comment]
Ok, that works. I also found the task that FanControl makes at installation. Shouldn't FanControl just do this for all users by default, or should there be a toggle for it within the settings menu (or during setup)?

> The program will run in the background without any ui available to the non admin user.

Could the default task be changed to do this as the default action for all users? Or a different settings option?

Just spitballing ideas, open to input.

**Comment by SomeoneElse00** [comment]
Regardless of the above, I don't think this will affect an average user. I believe that modifying the task scheduler has worked for my case, so closing as no change required.
