### ISSUE TITLE
Refuses to open

### ISSUE THREAD

**Issue by Andyholm** [Rem0o/FanControl.Releases#2750]
EventViewer log:
```
Faulting application name: FanControl.exe, version: 200.0.0.0, time stamp: 0x66960000
Faulting module name: atiadlxx.dll, version: 32.0.12011.1010, time stamp: 0x66d56383
Exception code: 0xc0000005
Fault offset: 0x0000000000062bd3
Faulting process id: 0x0x3140
Faulting application start time: 0x0x1DB0F33321493FB
Faulting application path: C:\Program Files (x86)\FanControl\FanControl.exe
Faulting module path: C:\WINDOWS\SYSTEM32\atiadlxx.dll
Report Id: 26f68d74-37f4-4c9c-816d-ac8021f48ff7
Faulting package full name: 
Faulting package-relative application ID: 
```

Description:
```
Updated to the latest AMD drivers then updated fancontrol.
Now fancontrol refuses to open. 
I have restarted several times, but still nothing.
Tried version 200 to see if the current fancontrol release was the issue, but that didn't change anything.
No log.txt is generated.
```

Specs:
```
RX 7900 XTX
Ryzen 5 7600X
Windows 11
Version: 23H2
OS build: 22631.4169
```

**Comment by Rem0o** [comment]
Update to the latest version (v204)

**Comment by Andyholm** [comment]
> Update to the latest version (v204)

I did, and it didn't work so I downgraded to see if it was an issue with the latest release. 
"Tried version 200 to see if the current fancontrol release was the issue"

**Comment by Valkyr2** [comment]
Had the exact same issue before, and it was caused by the AFMF preview driver. Both seems very uncompatible.

**Comment by Valkyr2** [comment]
Unfortunately, neither reinstalling Fancontrol, rolling back the GPU driver (to the not-preview one) or repairing windows could help. I had to use a restoration point of before installing the preview driver.

I also have a 7900XTX. Perhaps it only happens on these ones, or perhaps is it on all AMD GPU with AFMF 2 preview driver

**Comment by Andyholm** [comment]
Maybe. I'm not on a preview driver ATM and it worked fine when I was on the latest preview. For some reason updating to a non preview driver, then updating fancontrol seem to have broken it.
I'll see if rolling back my display driver or updating to a preview might fix it. I'll uninstall fancontrol first and check.
Will report back. :))

**Comment by Andyholm** [comment]
Fixed it!
Uninstalled fancontrol, updated from AMD's latest drivers to their latest preview drivers, restarted my pc, installed fancontrol.
Seems to be working now. :)
