### ISSUE TITLE
Problem with fan detection MOBO Aorus Master B650E 1.0

### ISSUE THREAD

**Issue by Nuctus** [Rem0o/FanControl.Releases#2753]
Hi Rem0o,

I am experiencing a fan detection problem in this MOBO.

As i can see, ControlFan only detects 6 Fan ports of 10 that MOBO have.

Attached log file. If you need anything else, please tell me.

Regards.

**Comment by Nuctus** [comment]
![Captura de pantalla 2024-09-27 132950](https://github.com/user-attachments/assets/95df019c-d6f0-4749-b4d2-cbdf09e7ebab)

**Comment by Nuctus** [comment]
I have connected two 4-pin fan. are detected but i cannot control them (via bios i am able to)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
