### ISSUE TITLE
Unexpected error v.205

### ISSUE THREAD

**Issue by gkarasik** [Rem0o/FanControl.Releases#2757]
WIn7/32bit/Enterprise:

Install v205 net 4.0: Trying to run causes error: "An unexpected error occurred. See log file for deatails."

Where's the log file?

**Comment by Rem0o** [comment]
Win 7 not supported. 10 and up.

**Comment by gkarasik** [comment]
Thanks. Is there an earlier version that runs under Win7?

**Comment by Rem0o** [comment]
Maybe V63 and under https://github.com/Rem0o/FanControl.Releases/releases?page=12

**Comment by gkarasik** [comment]
Thank you.
