### ISSUE TITLE
GPU sensors v84 undetected

### ISSUE THREAD

**Issue by mananong** [Rem0o/FanControl.Releases#276]
Hi there, I've been using fancontrol for couple of months, gone thru  different CPU and GPU upgrades, app update and mostly have been working great. Just today, it said it won't detect my GPU sensor. I've reseated GPU, reconnected cables, uninstalled, reinsatalled, rollbacked versions of the app and it just won't find my GPU anymore. Funny thing is i downloaded hardwarelibre and i have HWinfo they all see every single sensor.

specs:
Gigabyte b450i aorus
ryzen 3600
amd radeon 6700xt

**Comment by mananong** [comment]
btw now when i click on refresh sensors, app just crashes

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V85
