### ISSUE TITLE
Create new configuration exits the program

### ISSUE THREAD

**Issue by algotrash** [Rem0o/FanControl.Releases#2760]
**If you are experiencing a crash**
Link the relevant/associated Windows EventViewer logs, and also FanControl's own log.txt.
There is no new line in the log

**Describe the bug**
Create new configuration exits the program: As soon as I give my new config a name, the program exits with no warning

**Relevant hardware specs and setup**
Only thing uncommun is I have two GPU

**Comment by algotrash** [comment]
Update : When i right clic the tray icon, i can see the file is indeed created, but if i load it, the program crash with no warning.

**Comment by algotrash** [comment]
Created file contains this :

{
  "__VERSION__": {},
  "Main": {},
  "Sensors": {}
}

**Comment by Rem0o** [comment]
If the programs hard crash, there should be a Windows EventViewer log.

**Comment by algotrash** [comment]
Indeed! I get this

Application : FanControl.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.AccessViolationException
   à LibreHardwareMonitor.Hardware.InpOut.ReadMemory(IntPtr, UInt32)
   à LibreHardwareMonitor.Hardware.RyzenSMU.ReadDramToArray()
   à LibreHardwareMonitor.Hardware.RyzenSMU.GetPmTable()
   à LibreHardwareMonitor.Hardware.Cpu.Amd17Cpu+Processor.UpdateSensors()
   à LibreHardwareMonitor.Hardware.Cpu.Amd17Cpu.Update()
   à LibreHardwareMonitor.Hardware.Cpu.CpuGroup..ctor(LibreHardwareMonitor.Hardware.ISettings)
   à LibreHardwareMonitor.Hardware.Computer.AddGroups()
   à LibreHardwareMonitor.Hardware.Computer.Open()
   à FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()
   à FanControl.Domain.ComputerAccessLayer.Initialize()
   à FanControl.Domain.ComputerAccessLayer.Refresh()
   à FanControl.Bootstrap.<Startup>b__16_0(FanControl.Serializable.SerializableStartupSettings)
   à FanControl.Domain.ApplicationState+<>c__DisplayClass32_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SubscribeToCurrentConfig>g__subscription|0(System.Collections.Generic.Dictionary`2<System.String,System.Object>)
   à FanControl.Domain.ApplicationState.LoadAllApplicationState(System.Collections.Generic.Dictionary`2<System.String,System.Object>)
   à FanControl.Domain.ApplicationState.LoadApplicationState(System.String)
   à FanControl.Domain.ApplicationState.CreateNewConfig(System.String)
   à FanControl.ViewModels.Commands.CreateNewConfigCommand+<Execute>d__4.MoveNext()
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   à MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   à MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   à System.Windows.Application.RunDispatcher(System.Object)
   à System.Windows.Application.RunInternal(System.Windows.Window)
   à FanControl.App.Main()

**Comment by algotrash** [comment]
there is this one as well:


Nom de l’application défaillante FanControl.exe, version : 205.0.0.0, horodatage : 0xf011bd54
Nom du module défaillant : tmpD5C.dll_unloaded, version : 1.5.0.0, horodatage : 0x4d378abd
Code d’exception : 0xc0000005
Décalage d’erreur : 0x0000000000001aa0
ID du processus défaillant : 0x0x7250
Heure de début de l’application défaillante : 0x0x1DB13D29DEFC8E3
Chemin d’accès de l’application défaillante : C:\Program Files\fan-control-v137\FanControl.exe
Chemin d’accès du module défaillant: tmpD5C.dll
ID de rapport : 5906bfe4-6c24-4caf-bc67-342c9abe1309
Nom complet du package défaillant : 
ID de l’application relative au package défaillant :

**Comment by Rem0o** [comment]
In sensor source dialog in the settings, uncheck "InpOut" and save.

**Comment by algotrash** [comment]
It worked! Thank you very much for your quick answer, I can create my new config now.
Best regards, and have a pleasant day.
