### ISSUE TITLE
Allow a >100% proportional offset on a Sync curve 

### ISSUE THREAD

**Issue by ssomers** [Rem0o/FanControl.Releases#2761]
If you add a Sync curve, and enable Proportional Offset in its option, then (as far as I understand) you effectively multiply the source fan percentage with a factor of (1 + offset). The offset value is capped at ±100%, which makes sense for the default non-proportional case, so the factor ends up between 0 and 2. I would like a factor of around 3 (because the actual maximum speed of the source fan is merely 30% and the fan to steer needs more encouragement than 60%).

It's already possible to accomplish this by defining 2 Sync curves on the same source, both with factor 1.5, and combining them in a Mix curve with function Sum. Simpler would be to add the same Sync curve to a sum multiple times, but the software politely rejects that. But even simpler (for us) would be to allow the offset percentage to surpass 100 when it's proportional. I tried sneaking it in by editing userConfig.json but FanControl cannot be fooled that easily.

**Comment by Rem0o** [comment]
There is no good reason to limit it to 100% in proportional mode. Will increase to 1000% the limit.

**Comment by Rem0o** [comment]
V206
