### ISSUE TITLE
Fan Control failed to initialize.

### ISSUE THREAD

**Issue by avekifes** [Rem0o/FanControl.Releases#2764]
Just started getting this error after upgrading to V205:

> Fan Control failed to initialize. Retrying... Expected 23 sensors, found 21.
> 
> These errors occurred while restoring the configuration: • Missing control sensor: /lpc/it8665e/control/4 - Fan #5 • Missing speed sensor: /lpc/it8665e/fan/4 - Fan #5 if this error occurs upon startup, try increasing your startup delay.
> 
> Initialization retry failed.

Windows 10
5800X3D
RTX 4090
GeForce Game Ready 565.90 WHQL driver

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/2756#issuecomment-2389494690

**Comment by alansg90** [comment]
Here's a new explanation about the temporary solution.

https://www.reddit.com/r/FanControl/comments/1j93doq/why_does_defender_hate_fan_control_an_explanation/
