### ISSUE TITLE
Asus X870E Support?

### ISSUE THREAD

**Issue by roooots** [Rem0o/FanControl.Releases#2767]
Hi, 

first off - I absolutely love FanControl and have been using it with previous motherboards for years, so thanks for the great work!

Not unexpectedly though, it won't recognize the fans & sensors of my new Asus Rog Strix X870E-E motherboard. Is there any way I can aid and assist in getting support for this board? :-)

Cheers,
r.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
