### ISSUE TITLE
Arctic LF3 Pump not showing after v205 update, tried reinstalling no luck

### ISSUE THREAD

**Issue by anid786** [Rem0o/FanControl.Releases#2771]
After updating to the c205 update the LF3 AIO pump isn't showing anymore. Not sure how to get it back. I get the error mission control sensor for AIO pump and missing speed sensor for fan 6

**Comment by Rem0o** [comment]
Known bug, stick to v204. Will be fixed.

**Comment by Rem0o** [comment]
V206
