### ISSUE TITLE
AMD Fan Control Broke My Undervolt/Overclock

### ISSUE THREAD

**Issue by Ridianoid** [Rem0o/FanControl.Releases#2778]
![2024-10-11 15_02_27-Greenshot](https://github.com/user-attachments/assets/60f937a4-90bd-4f17-9c49-faf4298b0dbb)

I've attached the fan curve I used for the 6800 XT, where the overclock and undervolt switches turn off automatically when the percentage of fan operation changes. 

My settings; 
![2024-10-11 15_00_49-Greenshot](https://github.com/user-attachments/assets/de55fcd4-d14f-4955-911d-df58128d48e2)

Final settings after changing fan speed with Fancontrol;
![2024-10-11 15_00_39-Greenshot](https://github.com/user-attachments/assets/b206f48e-fe8b-4176-9303-db7c39a2e24c)

**Comment by Rem0o** [comment]
This is a known limitation.

Opened a ticket but no response:
https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/16
