### ISSUE TITLE
Sapphire Nitro+ RX 6700 XT 0% fan speed is broken

### ISSUE THREAD

**Issue by pc-v2** [Rem0o/FanControl.Releases#2779]
**If you are experiencing a crash**
Nah

**Describe the bug**
Fan is unable to set into 0 rpm with force apply, it stuck in ~599rpm (image 1)
or back to default advanced settings curve (image 3)
![image](https://github.com/user-attachments/assets/7a0aeb62-df39-4002-a5f9-afaa2a039582)
![image](https://github.com/user-attachments/assets/55a3d80f-e499-4e36-be6f-1ba840818e7d)
![image](https://github.com/user-attachments/assets/f08d92cd-1d2c-473b-8f4a-a6d08d340488)

**Is there a log.txt file next to FanControl.exe with recent date entries?**

 `12 Okt 2024 06.52.16: Open - System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 27
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
12 Okt 2024 06.53.07: Open - System.Exception: HWInfo is not running or reporting to gadget is not enabled.
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 27
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()`
(It have been fixed after I set what value I need in HWInfo Gadgets Settings)

**Relevant hardware specs and setup**
RX 6700 XT Sapphire Nitro+
B450 Steel Legend
Ryzen 5 5500
Driver 24.9.1
HWInfo Plugins

**Comment by Rem0o** [comment]
Your card restricts at what temperature it allows 0 RPM. Usually the threshold is arround 45 degree.

![image](https://github.com/user-attachments/assets/61f348b9-7bf3-473c-8713-85aafebacc41)

**Comment by pc-v2** [comment]
Yes p1 is on 45oC, so I have to modify the firmware if I want to force it, right?

**Comment by Rem0o** [comment]
If possible at all, but I dont believe it is.
