### ISSUE TITLE
Crash on start (HP Pavlion 15-dk1055ur)

### ISSUE THREAD

**Issue by Barmagler** [Rem0o/FanControl.Releases#278]
Hello!
Fancontrol crashing on start with unknown problem that I couldn't understand.
Can you tell me, what I can do?
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6728501/log.txt)

**Comment by Rem0o** [comment]
Well I don't expect a laptop to be supported in the first place, they don't use common chips like custom desktops do.

**Comment by Barmagler** [comment]
Okey, that was my last hope to get fun control on lava laptop :)
Will be waiting for news, may be one day I'll get update.

Anyway, I wish to say 'Thanks a lot', mate. You doing great work with FanControl, thanks!
