### ISSUE TITLE
Control everything except the GPU

### ISSUE THREAD

**Issue by apoklyps3** [Rem0o/FanControl.Releases#2782]
I can't seem to find an option for this program to leave the gpu control fans to the GPU software itself.
It messes with my 0 rpm mode and that's a no go.
read the guide, but can't find any info on how to exclude detected fans from fancontrol.
is there any way to achieve that or fancontrol removal is the way?

**Comment by Rem0o** [comment]
Yes.   You can uncheck the GPU source all together, otherwise just do not "toggle" the control card of the GPU.   It should leave it alone.
