### ISSUE TITLE
MSI MPG X870E CARBON WIFI fans not detected

### ISSUE THREAD

**Issue by Nuctus** [Rem0o/FanControl.Releases#2785]
Hello,

I am trying to detect all the fans in FanControl but i am not able to.

In LibreHardwareMonitor is working, i can see all the elements (nightly) version.

I do not know how to integrate nightly LibreHardwareMonitor to fan control.

So i am asking, is a FanControl "problem" or LibreHardwareMonitor problem?

Thanks in advance.

**Comment by Rem0o** [comment]
You can just use copy over the LibrehardwareMonitorLib.dll.

You also need to tick all the LHM sources you want:
![image](https://github.com/user-attachments/assets/998fd845-e627-4cb9-b85a-3a5b0e371113)

**Comment by Rem0o** [comment]
Maybe try a config from scratch:

CTRL + N   to create a new config.   You must have some stuff hidden in your current one:
![image](https://github.com/user-attachments/assets/0dd0bc61-609f-422c-88bf-ba22214ebaea)

**Comment by diesesQ** [comment]
Hi guys, i have the exact same problem. Seems to be related to the new X870 boards? I just finished my build with a ROG STRIX X870-F GAMING WIFI and installing and using FanControl like always.. no case fans detected. I can only control them via BIOS.

**Comment by Khromfire** [comment]
Hello, I bought a MSI X870e Carbon too, and only the CPU fan is detected, I can see i'm not alone, i checked all assets in librehardware monitor of course.

**Comment by Khromfire** [comment]
![Capture d’écran 2024-10-15 205149](https://github.com/user-attachments/assets/4b7367dd-1391-42ec-b5a9-73d65c0ce8b2)

**Comment by Nuctus** [comment]
@Khromfire you are lucky, at least you got cpu fan, in my case none of the sensors are detected

**Comment by Rem0o** [comment]
Closing, see https://github.com/Rem0o/FanControl.Releases?tab=readme-ov-file#issues-and-hardware-compatibility
