### ISSUE TITLE
So many patches and still can't uninstall correctly?

### ISSUE THREAD

**Issue by honey-sorry-i-ate-a-bus** [Rem0o/FanControl.Releases#2786]
Ran this thing because was curious if it can make my custom GPU fans fully stop and no, it can't. I ran some "calibration" during all this which affected all fans in my system. I configured them so they ain't completely unreasonable but didin't touch much.
After utter disappointment, I decided to delete this program. Closed it, ran uninstall.exe and found no trace of it being in startup, task manager, or services. 

BUT HERE THE FUN STARTS: it still has left some trace in some other place of Windows and fans completely ignore my BIOS settings and run at 100% speed all the time. This doesn't happen on my backup Windows build so it's definitely your software can't clean after itself. 

Big shame. Won't ever use it again. 

Software and hardware used:

Windows 10 Enterprise x64 22H2
Gigabyte B760M-DS3H, latest BIOS
i5-12400F
XFX RX 6700 XT SWFT309

**Comment by honey-sorry-i-ate-a-bus** [comment]
That's the neat part: I don't have literally any other software that can
affect fans behaviour in any way. Was easier to me to just reinstall
Windows so can't really investigate more but it's definitely not PEBCAK.

**Comment by Rem0o** [comment]
Without further investiguation on this specific case, closing.
