### ISSUE TITLE
FanControl disabling GPU Advanced Control in AMD Adrenalin app

### ISSUE THREAD

**Issue by dimitrovmaksim** [Rem0o/FanControl.Releases#2791]
**If you are experiencing a crash**
Link the relevant/associated Windows EventViewer logs, and also FanControl's own log.txt.

**Describe the bug**

It seems FanControl disables the Advanced Control for GPU Tuning in AMD Adrenalin. I happens every time when FanControl is launched or shut down. And if I enable it again while FanControl is running it will get disabled at some point again.

Dunno if the attached video is any helpful
https://github.com/user-attachments/assets/a0882cd7-a141-4829-bab7-485c42696dd9

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]

**Relevant hardware specs and setup**
GPU: Sapphite Nitro+ RX 7800 XT
AMD Driver version: 24.10.1
FanControl version: V206
Windows 11 Pro 23H2 (KB5044285)

**Comment by Rem0o** [comment]
That's a known limitation/bug: 
https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/16

Closing as duplicate.

**Comment by vaulton0592** [comment]
> That's a known limitation/bug: [GPUOpen-LibrariesAndSDKs/ADLX#16](https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/16)
> 
> Closing as duplicate.

Technically speaking, is it possible fix this limitation/bug? I would be willing to donate a generous amount of money for your time is it is possible. Thank you for your time, this is an amazing piece of software.

**Comment by Rem0o** [comment]
It's on AMD.

**Comment by vaulton0592** [comment]
Understood Remi, thank you for taking the time to respond. Again, much
respect to you for making this software, It is fantastic (pun intended).
