### ISSUE TITLE
FanControl causing strange GPU fan behaviors

### ISSUE THREAD

**Issue by JoeBeefus** [Rem0o/FanControl.Releases#2795]
After installing the latest FanControl my AMD GPU fans started acting weird. I do not use FanControl for my GPU, I was never able to get it working. I have always used Adrenaline. For some reason even when unchecking the AMD sensor and control options in FC it still shows up in the sensor and speed cards, and after a bit starts ramping up and down, oddly. Any help would be greatly appreciated.

**Comment by Rem0o** [comment]
Send the sensor options you got checked as a screenshot.

**Comment by Rem0o** [comment]
Stale.
