### ISSUE TITLE
Feature Request: Enable fan speeds above 0% if not spinning and use variables for trigger function

### ISSUE THREAD

**Issue by capitano799** [Rem0o/FanControl.Releases#2798]
Hello, 
I really like your program and it really helps to get my PC cool and silent.  
But I've noticed two limitations that would improve the program further:

First, as soon as you set the fan speed percentage below the minimal fan speed the percentage drops to zero. I run my CPU fan semi-passive on my mainboard header, and the fan starts at around ~30%. The jump from 0-30% takes around ~5 seconds on my mainboard, so the CPU temperature can really spike up during that period when applying a load. When controlling the fan manually and setting to ~25%, the fan almost immediatly starts spinning when increasing fan percentage over the 30% threshold. This is probably an upramp limitation of my mainboard fan header, because even with 50% ramp up speed per second in fan control the issue still persists. 
It would be good to have the option to keep the fan at a certain percentage, even when standing still, so the ramp up can happen more quickly. So for example the header always has a minimal PWM signal of ~25%, although the fan is not spinning.  

Also for semi passive cooling I use a fan curve combined with trigger function to use a wide hysteresis. With the CPU fan I also control certain chassis fans that have slightly different speeds, so there are multiple trigger functions. When adjusting the start and stop temperature you have to do this manually for every trigger. It would be good to just define a temperature variable somewhere in the program, like for example "fan enable temp" and apply this to all triggers. The advantage would be if you want to change the temperature you only change the variable and it applys to all triggers.

These two features would help to increase the usability and cooling optimization further with this program. 

Thanks in advance!

**Comment by Rem0o** [comment]
Letting a PWM or DC signal on your header where the fan doesn't spin potentially means that energy will be dissipated as heat in the motor. This is bad and want to avoid this at all cost. Now if your 0-30 is slow, why don't you increase your "configured" start% at let say 50?  This will increase the speed at which the fan starts spinning, and still allow it to go back down to 30.  Start% is really a "kickstart" value.

**Comment by capitano799** [comment]
I know that some fans try to spin at lower PWM values, but the fan I am talking about does stand still below a certain PWM value and you can spin it freely as if the PWM value was at 0.
Start% at 50 doesn't solve the problem, since the mainboard still limits the ramp speed to the same percentage per second. The fan does not turn on faster this way.

**Comment by Rem0o** [comment]
If you want to keep your fan at 25% which is below its minimal spinning speed, you can do it manually with a graph and remove the start and stop % value on the control you want to do this ( set 0 % ).   Again, this is a bad idea, but you do you.

**Comment by Rem0o** [comment]
For your second point, did you know you can control fans by rpm instead of % ? I don’t understand the many trigger curves because your fans have slightly different speeds.

**Comment by capitano799** [comment]
Thanks, the advice with reducing the start and stop percentage below the minimal percentage does exactly what I need.

I already control my fans with RPM. The different triggers are because of different RPMs, like for example my GPU turns on at 70°C hotspot and 650rpm (lowest possible speed), there are some semi passive case fans that also turn on but only at 500rpm. Would be nice if I could just sync the temperatures of the GPU trigger and case fan trigger.

**Comment by Rem0o** [comment]
I get the idea with the variables.   However, that's a level of complexity onto the software and UI I feel goes a bit over the edge.  Each "field" would have to support either a fixed or variable value.  As a programmer myself I like the concept and it fits the "building blocks" concept of the software, just not sure how neat I could make it so it doesn't overblow the ui.

**Comment by aynucalut** [comment]
I have been looking for such a program for a long time on my Asus tuf A15 Ryzen 6800h computer. I have been using the program for 2 days and I registered to the forum to thank you. I say thank you for your efforts. My request is, is there a possibility to provide Turkish language support? Because there will be many Turkish users who will need this program. Also, my most important expectation is to be able to lower the fan speed a little more in order to use it more comfortably in quiet environments such as libraries. It would be great.

**Comment by Rem0o** [comment]
@aynucalut  translations are open for contribution by the community: https://github.com/Rem0o/FanControl.i18n

If you want to provide a Turkish translation, go ahead.
