### ISSUE TITLE
Asus Sabertooth Z77 can't control fans

### ISSUE THREAD

**Issue by TimSirmovics** [Rem0o/FanControl.Releases#28]
I am able to see all of my fans in the app, but the RPM doesn't change when I apply a curve.
I downloaded Libre Hardware Monitor which seems to detect all of my fans - do I need to submit a report to them?
I also tried using Argus Monitor which was able to change the speed of each fan.

**Comment by Tom-Archer** [comment]
Which ITE chipset does Libre say the Z77 has? I've got a motherboard with the IT8628E and had a similar issue. I've raised a pull request on Libre Hardware Monitor to fix it.

![image](https://user-images.githubusercontent.com/18333795/91704161-20116a00-eb73-11ea-8334-bb32be92a95f.png)

**Comment by TimSirmovics** [comment]
Mine is the Nuvoton NCT6779D.
I'm currently poking around the Libre source to see if I can fix it.

**Comment by TimSirmovics** [comment]
Well after a very interesting few hours in the Libre source and the [NCT6779D Datasheet](https://datasheetspdf.com/pdf-file/788178/novoTon/NCT6779D/1), I realised that I could actually control the fans from the Libre UI.
So I think this is an issue with Fan Control and not the Libre library.

**Comment by TimSirmovics** [comment]
Looks like this was user error - fans weren't matched correctly.

**Comment by IIEleven11** [comment]
> 
> 
> Looks like this was user error - fans weren't matched correctly.

I have a nuvoton  board can you tell me what you did, I currently only have GPU control

**Comment by TimSirmovics** [comment]
I reset my profile and used the automatic fan matching
