### ISSUE TITLE
When selecting GPU temperature, there is only one default temperature.

### ISSUE THREAD

**Issue by laodaoxp** [Rem0o/FanControl.Releases#2800]
When selecting GPU temperature, there is only one default temperature.
There are three graphics card temperatures in GPU-Z.
GPU temperature
GPU Hot spot temperature
GPU memory temperature
Can FanControl add these three temperature options?

显卡 GPU 温度选择的时候只有一个默认温度。
GPU-Z 里面显卡温度有三个。
GPU temperature
GPU Hot spot temperature
GPU memory temperature
FanControl 可以增加这三个温度选择吗？

![微信截图_20241026154853](https://github.com/user-attachments/assets/25413a51-511b-4b3f-a916-1170d2c5c25f)
![微信截图_20241026154737](https://github.com/user-attachments/assets/f2eb9200-9364-4401-80fe-6f0abee40eb4)

IT OK

**Comment by Rem0o** [comment]
Uncheck NvAPIWrapper in sensor sources and check the GPU section of LHM. I believe that sources has at least hotspot.

**Comment by laodaoxp** [comment]
> 取消选中传感器源中的 NvAPIWrapper 并检查 LHM 的 GPU 部分。我相信来源至少有热点。

I searched very carefully and thoroughly, and it turns out that the GPU only has one temperature source
