### ISSUE TITLE
Window is outside screen or invisible

### ISSUE THREAD

**Issue by laxu** [Rem0o/FanControl.Releases#2801]
**If you are experiencing a crash**
Link the relevant/associated Windows EventViewer logs, and also FanControl's own log.txt.

**Describe the bug**
I had FanControl load with its window outside my screen, and the only way I could recover it was using DisplayFusion to create a profile that allowed me to type coordinates and size for the window. Win+arrows would not move it.

This might be because I had the FanControl window position moved on my 8Kx2K superultrawide, then used my 4K TV.

FanControl could use a "recover window" function where it would set its coordinates to 0,0, with some standard size on the current screen, or when launching the UI it should check if it's on screen (window coordinates/size vs current display resolution).

**Relevant hardware specs and setup**
Windows 11

**Comment by Rem0o** [comment]
Yeah the location of window is saved when the app is closed in the CACHE file.   If your screen setup changes, the coordinates might point to a "non-location".   Will have to take a look if I can reliably detect this.

**Comment by Rem0o** [comment]
V207
