### ISSUE TITLE
Asrock x870e Nova error

### ISSUE THREAD

**Issue by Schrotty74** [Rem0o/FanControl.Releases#2803]
I get the new Asrock x870e Nova and when start the latest FanControl i get a CPU Fan error.

![Screenshot 2024-10-30 055303](https://github.com/user-attachments/assets/09e9dede-932f-4eb1-b8cc-d00a540e965f)

**Comment by Rem0o** [comment]
Did you start from an existing configuration with an other board, or is this a fresh install?

**Comment by Rem0o** [comment]
Your (old) configuration will then be broken, that's normal, the sensors won't be the same.   You should create a new configuration, run the assisted setup on it, then use the "import from" option to import your old fan curves in the new configuration if that's what you want to do.

Regards,

Rémi
