### ISSUE TITLE
GPU Control (only) doesn't work at windows startup

### ISSUE THREAD

**Issue by dkdirekt** [Rem0o/FanControl.Releases#2804]
**Describe the bug**
Hi,

Every Windows startup and when FanControl starts, the GPU curve doesn't work. When I check in AMD Adrenalin, GPU Fan control is by default. If I switch from GPU curve GPU to CPU, the curve on AMD Adrenlin is now flat, and FanControl finally control the GPU Fan curve. As long as I haven't changed the curve at least once when starting Windows, Fancontrol doesn't control the GPU fan curve.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
No error.

**Relevant hardware specs and setup**
MB: MSI MPG B550 Gaming Plus
CPU: R7 5800X
GPU: RX 7600
RAM: 32Gb 3600Mhz
Adrenalin: 2.10.1 (24.20.19.01-241011a-408380c & 32.0.12019.1028)
Fancontrol V205 (NET 4.8 portable)

**Comment by Rem0o** [comment]
My guess is that on windows startup your GPU is at 0%/0 rpm? When in 0 RPM, the curve does switches in Adrenaline, that's normal and not a problem.   Do not try to make sense of what's happening in Adrenaline while using FanControl, because it won't.
