### ISSUE TITLE
Fan-Control for Gaming-PC

### ISSUE THREAD

**Issue by omexlu** [Rem0o/FanControl.Releases#2806]
Hello,

this is not a bug report but I am having problems.

The whole thing works fine, but as soon as you want to play with the PC, you notice how the fans keep turning up and down (depending on the load).

This can be extremely annoying if the fans are constantly adapting to the load.

How can you solve the problem for gaming?

Thanks in advance.

**Comment by Rem0o** [comment]
How did you setup your fan control configuration? Did you use any response time ? Hysteresis? The program ain't magic, you got to tell it what to do.  

Post a screenshot of what you got.

**Comment by omexlu** [comment]
Hi @Rem0o ,

I had Hysteresis 1° and response time 1 sec. Maybe I should do Hysteresis 2° and response time 5 sec to  prevent ramp ups and down?

Thanks in advance.

**Comment by omexlu** [comment]
@Rem0o Works fine now but something i have " ? " on top of my fans and says that the control cannot currently be made? What is the reason for this? Because for the most part it works, but only occasionally does it happen?

Thank you.

**Comment by Rem0o** [comment]
This may happen during the start and stop transitions or of the calibration is off. If it only flashes from time to time and doesn't persist you are ok. I will close this issue.
