### ISSUE TITLE
Can add support for SAMSUNG NP500 series laptops?

### ISSUE THREAD

**Issue by WiperElite** [Rem0o/FanControl.Releases#2808]
The program can´t control the SAMSUNG Laptop. I have read, laptop fan control is configured from the EC. But switching some values with RW-everithing.exe all values resets all the time.

The only program that can control the fans of the laptop is Samsung Settings 2.0.0.72, but only for donw the speed of the fans x_x

If i can add some atachments, just reply. I will be attentive
Waiting this support, very apreciated.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
