### ISSUE TITLE
3x Fans on Fan Hub, show up at 0RPM in FanControl

### ISSUE THREAD

**Issue by cantodorum** [Rem0o/FanControl.Releases#2811]
### Discussed in https://github.com/Rem0o/FanControl.Releases/discussions/2810

<div type='discussions-op-text'>

<sup>Originally posted by **cantodorum** November  1, 2024</sup>
I've got 3x the same NF-A14 plugged into a fan hub built-in to my case. It gets supplementary 12V power and I then connected the cable coming from the fan hub to my MB header "CHA_FAN2".
I got two of the fans linked via a Y-splitter from noctua, which then plugs into the hub, while the other fan is just on an extension cable going directly into the hub.
I tried plugging the pair into "CHA_FAN2" directly and the other one in "M.2_FAN", but then this one is running at max speed all the time.
![grafik](https://github.com/user-attachments/assets/2c61eeab-135a-415b-a1ad-4fd3d1f43315)
I got my fan profiles for all fan headers set to MANUAL in the BIOS and put in a curve thats just static 20%, so that FanControl can take all of the control.

I got an ASUS X570-E MB.
![2024 11 01_17-12-25_NVIDIA_Overlay](https://github.com/user-attachments/assets/ac836fc7-ecf8-41d7-b37e-9a418ef4a4be)
</div>

**Comment by Rem0o** [comment]
Hubs/splitters can mess up RPM reading.  There only 1 channel/wire for RPM reading in the end on your motherboard, so you can't read multiples fans at once on there.   Also, maybe the pairing you got on your control card is wrong?

**Comment by cantodorum** [comment]
> Hubs/splitters can mess up RPM reading.  There only 1 channel/wire for RPM reading in the end on your motherboard, so you can't read multiples fans at once on there.   Also, maybe the pairing you got on your control card is wrong?

How can I then control more fans than I have fan headers? I only got CHA_FAN2 and M2_FAN on the MB in the reach, the other could be CPU_OPT but that one is tied to CPU_FAN, which is occupied by my AiO. CHA_FAN1 is occupied by the single exhaust (which works perfectly although the RPM reports as static 540RPM, except when at 0%)

**Comment by Rem0o** [comment]
In your case I would do every "case" fans on the hub, then hub into CHA_FAN2.

**Comment by cantodorum** [comment]
> In your case I would do every "case" fans on the hub, then hub into CHA_FAN2.

That's... exactly how it is now and how I described it.

>  I've got 3x the same NF-A14 plugged into a fan hub built-in to my case. It gets supplementary 12V power and I then connected the cable coming from the fan hub to my MB header "CHA_FAN2".

**Comment by Rem0o** [comment]
> It reads 0 RPM and thus can't be calibrated, leaving me with the problem that I can't control them

Calibration is not required for controlling.  Put the control card in manual mode, crank it to 100%.  If you get faster fans, you're in business.

**Comment by cantodorum** [comment]
Okay, I now set the header to DC in BIOS, as PWM doesnt seem to be responding (either in BIOS or FanControl)
It seems to work now, even the RPM for whatever reason...
Thanks for your help! @Rem0o

**Comment by Rem0o** [comment]
Glad you got it worked out. Cheers.
