### ISSUE TITLE
v207 stuck in NVAPI_INVALID_HANDLE loop; rollback to 206 which fails to launch after install

### ISSUE THREAD

**Issue by TennesseePete** [Rem0o/FanControl.Releases#2812]
Updated to 207. Began receiving inescapable "NvAPI failed" and "NVAPI_INVALID_HANDLE" error loop.

Fully deleted FanControl, updated to latest .NET 8 version, clean installed latest Nvidia drivers, fresh install v206. After install, FanControl fails to launch.

Logs from 207 attached. No logs from 206 as it won't launch.
[207 errors.txt](https://github.com/user-attachments/files/17603278/207.errors.txt)

**Comment by Rem0o** [comment]
You probably updated your Nvidia drivers?  It usually fixes itself after a reboot.
