### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by nexusV2** [Rem0o/FanControl.Releases#2817]
220 mb memory usage controlling 3 fans with curves without any plugins.

![Screenshot 2024-11-06 130112](https://github.com/user-attachments/assets/e50967a9-a196-4d02-b845-65e1e264259a)

**Comment by Rem0o** [comment]
The UI takes most of the RAM.   Start the program minimized you will get much lower RAM usage.

**Comment by nexusV2** [comment]
Ok thank you. Starting minimized it takes 66,5 MB.
Appreciate your work, very advanced stuff!

**Comment by Rem0o** [comment]
If you leave it alone for a while it should go down even more.
