### ISSUE TITLE
Intel 285 and z890 Strix-E no Fans 

### ISSUE THREAD

**Issue by Benni231990** [Rem0o/FanControl.Releases#2818]
**Describe the bug**

I Use v207 and with my 12900k and z690 Strix-e no Problem i see all my Fan and CPU Temp but now i upgrade to 285k and Z890 Strix-e after the first Start I Have only Error Messages of Missing Fans i see Only my GPU in the Dashboard but no Fans from my z890 Strix-e 

Here i made a Screenshot: https://ibb.co/PYrN3qN

**Relevant hardware specs and setup**

Intel 285k
ASUS Z890 Strix-E

**Comment by Rem0o** [comment]
Most likely the z890 Strix-E uses a new superIO chip not yet supported by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.

**Comment by Benni231990** [comment]
ok so just need to wait? Or can you fix this?

**Comment by Fr0stX76** [comment]
Wait until it gets supported by LibreHardwareMonitor, which will make in work in Fan Control
