### ISSUE TITLE
Case fan cannot be controlled

### ISSUE THREAD

**Issue by MaitrePoul** [Rem0o/FanControl.Releases#282]
Hello,

Thanks for this excellent software.
However I have one issue I cannot manage to solve.

I have 4 case fans (all identical).
They are configured exactly the same (auto-mode) on my motherboard BIOS (Gigabyte Z390 AORUS PRO).
Each of them is connected to a different port of the motherboard : 
- Sys_Fan_2
- Sys_Fan_3
- Sys_Fan_4
- Sys_Fan_6_Pump

On FanControl, I see them all spinning but I can only control the ones on Sys_Fan_2 and Sys_Fan_3.
The two other cannot be controlled by the software. I had to match the fan controls with the fans manually, and then I see their RPM correctly but when I apply a 0% curve, they won't stop.

Any idea ?

Thanks.

**Comment by Rem0o** [comment]
Compatibility issue, see the README.
