### ISSUE TITLE
Not detecting case fans on CyberpowerPC

### ISSUE THREAD

**Issue by KrisLau** [Rem0o/FanControl.Releases#2821]
**Describe the bug**
It's weirdly detecting my the back fan (facing out) of my CoolerMaster AIO but not the front fan (facing the inside of the PC). There are also 2 more case fans on the side of the PC that doesn't seem to be detected at all and cannot be controlled.
![image](https://github.com/user-attachments/assets/9a39b1c7-9827-4b30-b820-4159a9ad9b08)
![image](https://github.com/user-attachments/assets/63fb3455-968a-49a8-921f-c3ee02b7086c)

However when I use the Nvidia Game Overlay those fans respond to the controls there and the speeds also _seem_ to be detected by the overlay

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Nope

**Relevant hardware specs and setup**
https://www.bhphotovideo.com/c/product/1639008-REG/cyberpowerpc_supreme_liquid_cool_slc10000cpgv7.html/specs

**Comment by Rem0o** [comment]
It all depends how these fans are plugged inside your computer.   For the fans to be controllable, they need to be plugged onto a motherboard header, not directly to the powersupply.

**Comment by KrisLau** [comment]
@Rem0o They are connected to my motherboard but I'm not exactly sure if it's the header (sorry not very knowledgeable on this) but I'll attach a photo:

**Comment by Rem0o** [comment]
That's a separate fan hub. If it's not plugged to a PWM header, FanControl can't do anything about these.

**Comment by KrisLau** [comment]
@Rem0o Ahh ok I see, thank you!
