### ISSUE TITLE
Stopped starting after mobo/ram change

### ISSUE THREAD

**Issue by sneakyjoeru** [Rem0o/FanControl.Releases#2822]
Doesn't start properly. It asks for admin permissions and then nothing. Tried running through command line, but no errors.
I did cycle through 2 motherboards in a week on the same install, and it used to work 2 days ago until I swapped ram to 2 sticks of 32gb instead of 4 sticks of 16. 
No log file is created. Tried removing configuration folder, tried clean install, .net 4 and 8 versions, different path. Nothing essentially works. How can I debug it without a debugging software on my end?

**Comment by Rem0o** [comment]
Any plugin? Any EventViewer event?

**Comment by sneakyjoeru** [comment]
No plugins.

Events:
![image](https://github.com/user-attachments/assets/042856ab-0c31-4936-8df3-62785558ce63)
![image](https://github.com/user-attachments/assets/194db893-4453-4570-ad2a-b5ec5acbb66e)

![image](https://github.com/user-attachments/assets/53e432cb-a0ff-4893-8927-dadf83acf0a5)
![image](https://github.com/user-attachments/assets/9ca92c3f-4a30-4ca6-8ccc-bfbad70f9448)

![image](https://github.com/user-attachments/assets/6b5cdf3c-bb8a-4d19-9feb-5bb5ff8f999c)
![image](https://github.com/user-attachments/assets/d0d845a8-0813-4f23-bd11-38b5b96fbe2d)

**Comment by LeoKeidran** [comment]
Also receiving the same issue. Recently had to downgrade my AMD Adrenaline version for comaptibility and FanControl no longer starts.
Like OP, I have attempted reinstalling with both the .NET 4.8 and 8.0 versions but no change.
Event viewer logs suggest same exception code/error.
![image](https://github.com/user-attachments/assets/5379bc3b-f005-436c-a8e3-2a8636528069)

![image](https://github.com/user-attachments/assets/fd8c3b16-e4bd-4c04-a8b3-8f6a5e10eced)

No plugins, restarting machine does not change behaviour.
Windows ver: Win10 22H2 (OS Build 19045.5011)

**Comment by LeoKeidran** [comment]
My issue was entirely related to the DLL mentioned in the error. Using DDL I was able to uninstall the driver, and reinstall the relevant version I needed. Not a FanControl issue though very hard to diagnose!
@sneakyjoeru  I'd suggest checking in Event Viewer for the Application error itself (not .NET) and see what module is failing. You might be able to see what DLL is failing, and with some searching online get some luck. My guess would be, given you've changed Mobo and RAM a few times, that there's some chipset drivers or something causing issues that FanControl uses (in the same way my GPU library caused issues).

**Comment by sneakyjoeru** [comment]
Removing AMD drivers for integrated GPU with DDU helped to get it working. I'll play with this DLL and with versions, thanks

**Comment by sneakyjoeru** [comment]
Removing amd drivers with ddu fixed it. Then updated with windows update, and downloaded 7800x3d drivers again. Works fine now, thanks @LeoKeidran
