### ISSUE TITLE
Fan Control Not saving config

### ISSUE THREAD

**Issue by shaby683** [Rem0o/FanControl.Releases#2823]
Recently when I save a config it hasn't actually been saving. So every time I start my pc or Fan Control I have to pair speed sensors and configure all desired settings again. I've tried reinstalling, running as admin but nothing seems to work.. 

Edit: I rolled back to V186 and it saves everything without issue. V207 is the one i have the save issue with.

Thank you.

**Comment by Rem0o** [comment]
FanControl saves to a json config file.  You can "Save as" with a specific name if you want to know what file it is. The file is visible in the title bar.  V207 saves just fine, so there must be something going on on your side.  Do you have multiple "installations" of the software?

**Comment by shaby683** [comment]
I done all the save as stuff. I even checked the json file to see if it saved the settings and names. It does save to the json file, V207 just doesn't load the settings for me unless they were saved on a previous version of FanControl (ie V186) no matter how many times I save or how many save as I do. I uninstalled a few times and nothing. I don't believe I have multiple installs either, I only install to the default on C drive and uninstalled via add remove programs in the control panel. The only thing that worked was installing an earlier version (V186 for me) and it works great. Thank you for taking the time to respond.

**Comment by Rem0o** [comment]
If you hit load im v207 ( ctrl + L ) and you select your saved json file nothings happen? No error nothing?

**Comment by shaby683** [comment]
The error I when loading a json file is missing control sensor /gpu-amd/5/control/0 - GPU Fan and Missing speed sensor: /gpu-amd/5/fan/0 -GPU Fan. That happens when I load the config from V186. When I hit save, the error goes away. Then any changes made and saved under V207 wont load upon next start up. 

As a test I just searched the json 'Test' file for 'Radiator' prior to saving the name in the program, it doesn't show up. I change the name of one of the fans to 'Radiator' hit save and 'Radiator' now shows up in the json file. But when I close out of fancontrol (whether its a pc restart or closing the program via the system tray or task manager) and load it back up, the json file still has 'Radiator' listed but the program doesn't seem to be loading names or settings unless they were made prior to updating to V207. I'm going to reinstall V186 until I can figure out whats going on as that version works flawless.

**Comment by shaby683** [comment]
I just done a full reinstall, deleted anything for Fancontrol in the program files 86 folder. Its saving most of the settings now but wont save the setting for the Lian Li SL fan controller plugin. I have to go to work and will try again when I get home. Thank you.

**Comment by shaby683** [comment]
I think I figured it out. It must have been an issue with the LianLi dll file. I replaced it in the plugins and it started saving again. I made a paypal donation for your troubles. Thank you.
