### ISSUE TITLE
FanControl hanging - NVAPI_GPU_NOT_POWERED error waking up from sleep

### ISSUE THREAD

**Issue by mattjones73** [Rem0o/FanControl.Releases#2824]
**Describe the bug**
Fan Control hanging, I have to kill it in Task Manager, happens randomly after the PC was sleeping. Looking at the logs I see an Nvidia error when my PC is waking up at 3am to back itself up. This started a few versions back, The only hardware change I made was removing an Lian-Li controller and it's plug in. All fans/aio pump run off the motherboard headers now. I have to kill the app in Task Manager and restart it and it's fine til the next hang. Currently on 207, this has been happening the last couple of updates.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[log.txt](https://github.com/user-attachments/files/17691984/log.txt)

**Relevant hardware specs and setup**
[hardware.txt](https://github.com/user-attachments/files/17691991/hardware.txt)

**Comment by Rem0o** [comment]
What sources do you have enabled in the settings.

**Comment by mattjones73** [comment]
These

https://i.gyazo.com/354bdc15400855b72914ddf2b74608e5.png

**Comment by Rem0o** [comment]
Don't think the Nvidia error causes the hang.  I would be tempted to test if disabling the EC stuff stops the hanging behavior.

**Comment by mattjones73** [comment]
I will disable it now and let it go a few days. It didn't hang overnight for me this time, it happens once or twice a week. Thanks for the response :)

**Comment by Rem0o** [comment]
Reopen if needed.
