### ISSUE TITLE
No Fans Detected on Gigabyte x870E

### ISSUE THREAD

**Issue by FrankFioretti** [Rem0o/FanControl.Releases#2826]
Using the latest version of fan control, on the latest chipset drivers, and the latest bios, no system fans are detected by FanControl on my Gigabyte Aorus x870e motherboard. I have uninstalled/reinstalled and no luck.

The gigabyte control center detects and allows me to control them, and HWInfo detects them. I have also tried uninstalling the Gigabyte control center but FC still doesn’t see any of the fans.

**Comment by Rem0o** [comment]
It's a new motherboard

See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

Closing.

**Comment by Slickrick17** [comment]
OP didn't specify which Gigabyte X870E motherboard they have. For the more common/popular ones, it's probably implemented in the latest versions of FanControl. On the off chance that OP has the Xtreme AI Top motherboard, I posted discussion #2977 for a temporary fix.
