### ISSUE TITLE
AMD PPC sdkusage.csv grows huge

### ISSUE THREAD

**Issue by Bnorus** [Rem0o/FanControl.Releases#2829]
I'm unsure if it is a bug, but I wanted to report this.

I have been running FanControl on Win11 for a few years. My ProgramData/AMD/PPC/sdkusage.csv file has grown to 37GB of FanControl usage records.

![image](https://github.com/user-attachments/assets/f72aa786-2ffb-4964-99fa-2cb83d4676cd)

**Relevant hardware specs and setup**
Gigabyte B450I AORUS PRO WIFI
AMD 5600X CPU
AMD RX6800 GPU

**Comment by Rem0o** [comment]
It's not fancontrol which logs this, it's the driver itself.  You got to opt out of the:
![image](https://github.com/user-attachments/assets/2f3f9a54-0076-4281-8c78-5bd269fbfd45)

**Comment by Bnorus** [comment]
Merci!
