### ISSUE TITLE
Pairing not completed / many of the fans don't have sensors

### ISSUE THREAD

**Issue by blkaleeb** [Rem0o/FanControl.Releases#2830]
Hi, i'm just download and trying your application, great app!
Although, i have some issue with starting with the application. currently i'm using the latest version v204.
So i let the apps to identified and calibrate the RPM, many attemps have a different result, like sometimes the SYS_FAN2 sometimes have sensor, sometime not. but i think i can pair it manually,

But my bottom fan, which was connected to SYS_FAN4 and SYS_FAN5
SYS_FAN4 working great, but the SYS_FAN5 is not identified, i want to pair it manually but the RPM also have 0 RPM
(Bottom right is SYS_FAN4)

![image](https://github.com/user-attachments/assets/b2cf633c-b41d-4ecf-84b6-ebc5cd65dc9c)

can i have your suggestion? thanks!

**Comment by Rem0o** [comment]
Latest version is V207 by the way.

Also read the nvidia section here: https://getfancontrol.com/docs/

**Comment by Rem0o** [comment]
If the SYS_FAN_5 speed sensor reports 0 RPM and your fan is physically spinning, then it's not plugged into SYS_FAN_5. It's hard to say without having the complete picture your where all your fans are plugged in and so on.   Basically you got to figure out which fan is which control/speed sensor in the software by deduction.

**Comment by blkaleeb** [comment]
I play around the percentage and it's working on SYS FAN, although the RPM isn't registered.
If i turn it to 0% the fan stop tho.

so i check the BIOS, and on the bios also the SYS FAN 5 RPM was not registered. Is this product faulty? hmm

thanks for replying tho!

**Comment by Rem0o** [comment]
RPM wire might be dead.
