### ISSUE TITLE
[feature request] Want curve control over pump fan

### ISSUE THREAD

**Issue by havedifficultyinfindingnames** [Rem0o/FanControl.Releases#2832]
I'm using air cooling, and I want separate control of two cpu fans, thus one of the fan is connected to pump fan connector. (Other reasons consist of easier assembling and disassembling and a distinct fan name.) The feature requested is that curve should be able to apply on pump fan control, while giving a warning or a suggestion.

**Comment by Rem0o** [comment]
It can already? Your pump header should be seen as a distinct control card in the software.

**Comment by havedifficultyinfindingnames** [comment]
> It can already? Your pump header should be seen as a distinct control card in the software.

Yes it's a distinct control, but it cannot be applied with a fan curve. It's been controlled directly by a slide, which is different from other fans. Do I got something wrong maybe?

**Comment by Rem0o** [comment]
![image](https://github.com/user-attachments/assets/a1534944-5c63-4ed3-a05c-3a31212b0377)

**Comment by havedifficultyinfindingnames** [comment]
I'm quite sorry about my own fault. May I ask one more question? When I switch from FanControl control to BIOS control, (which is turn off the switch button above the percentage number as shown on the picture), the fan will run at a constant speed 40%. And one more action of switch on and off will solve the problem. Is it intentional or something problematic?
