### ISSUE TITLE
Missing Controller on Gigabyte X870E motherboard

### ISSUE THREAD

**Issue by CourtJesterau** [Rem0o/FanControl.Releases#2833]
Have recently set up a new AM5 system with a Gigabyte X870E Pro Ice motherboard

FanControll is missing fans and temp sensors connected to one of the controllers on the board so I cant controll various fans or monitor temps

the Controller is : ITE IT89696E HW info has it in there fine but not in FanControl

<img width="410" alt="Missing1" src="https://github.com/user-attachments/assets/20c58352-39bb-4cea-b94c-b1b15520ca8d">
<img width="1115" alt="Missing2" src="https://github.com/user-attachments/assets/7921bb53-3a6a-41c9-b1f7-4ac2b09251a8">

It only detects sensors connected to the ITE IT87952E controller

<img width="457" alt="Missing3" src="https://github.com/user-attachments/assets/b0731205-21b8-4085-b850-1c44c145c7d9">

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

and https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1510
