### ISSUE TITLE
Auto Control settles at min speed despite high temperature

### ISSUE THREAD

**Issue by mermerico** [Rem0o/FanControl.Releases#2835]
After updating to v208, when using an auto control, if the temperature is below the load temperature then after a few seconds the commanded fan speed drops to the minimum and stays there. The graph control seems unaffected.

![image](https://github.com/user-attachments/assets/accfccfa-67ce-4166-8b89-0fe653c94c30)

**Comment by Rem0o** [comment]
That's how auto works and always worked.

**Comment by mermerico** [comment]
Ah, I see. Thanks! I guess I saw "Auto" with the "magic" icon and thought it meant the most common use case.
