### ISSUE TITLE
can not control gpu fans to lower 30%

### ISSUE THREAD

**Issue by mapengsen** [Rem0o/FanControl.Releases#2839]
![image](https://github.com/user-attachments/assets/064fdfc8-1c4a-4a43-85b9-800524f771c8)

When I set the fan speed, it always beats between 0% and 30%, what should I do

**Comment by Rem0o** [comment]
See nvidia section: https://getfancontrol.com/docs/

**Comment by mbonca** [comment]
Most of the fans cannot turn bellow 30% of their max speed.

**Comment by mbonca** [comment]
@mapengsen Most of the fans cannot turn bellow 30% of their max speed.
