### ISSUE TITLE
[Feature] Add ability to control Pumps

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [Rem0o/FanControl.Releases#284]
I have a newly installed water pump that sits on my mainboard, which has a speed that can be read out from HwInfo:
![image](https://user-images.githubusercontent.com/30594398/124399400-7a430480-dd1b-11eb-9a2b-801e45a40cb6.png)

The question here would be, if it's possible to control the pump? I'm not sure how much of an use case people would have, but as example, I would probably set it up in a way so that the pump ramps up to 100% before fans do so.

**Comment by Rem0o** [comment]
A water pump is connected the same way a fan is, so just plug it into a header FanControl can access.
