### ISSUE TITLE
Mix custom sensor max function shows 0 as maximum between two negative numbers

### ISSUE THREAD

**Issue by dave-mike** [Rem0o/FanControl.Releases#2841]
**Describe the bug**
Mix custom sensor max function shows 0 as maximum between two negative numbers

![image](https://github.com/user-attachments/assets/0e4cef0a-e70e-456a-a4b5-90b258760ddc)

Present in V208

**Comment by Rem0o** [comment]
Will fix.

**Comment by Rem0o** [comment]
V209
