### ISSUE TITLE
add control cards manually

### ISSUE THREAD

**Issue by light1490** [Rem0o/FanControl.Releases#2843]
Hello everyone. I would like to manually create control cards. The software does not create enough 3 plus 2 cards for the GPU

I connected fans to 5 PWM ports recognized in the speed cards but I do not have enough control cards to assign everything.

If you have a solution, thank you

**Comment by Rem0o** [comment]
You can't "add" control cards.   

For motherboard compatibility, see https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.

Closing.
