### ISSUE TITLE
Installer wont work, blocked by defender smart screen

### ISSUE THREAD

**Issue by MyZones** [Rem0o/FanControl.Releases#2845]
When I try to install this under win 11, I am prompted with a Microsoft Defender smart screen prevented an unrecognised app from running,
![Untitled](https://github.com/user-attachments/assets/75df193d-fbd2-428a-966d-3d2ae72c9909)

**Comment by Fr0stX76** [comment]
Microsoft...

See here: https://github.com/Rem0o/FanControl.Releases/issues/2322

**Comment by Rem0o** [comment]
Defender algorithm may decide to put this screen. I don't have any direct control over that. That's just the installer.  You may use the portable version if you want to see all the bundled files from the get go.
