### ISSUE TITLE
Fancontrol is not opening

### ISSUE THREAD

**Issue by SomeCrbn** [Rem0o/FanControl.Releases#285]
When unzipping the file then executing the .exe a few files get made but nothing opens. Is this some form of compatibility issue?

**Comment by Rem0o** [comment]
Probably, what's your OS? Any log.txt?

**Comment by SomeCrbn** [comment]
Windows 10
log.txt:
https://pastebin.com/N3YsXXth

**Comment by Rem0o** [comment]
What's your GPU?

**Comment by SomeCrbn** [comment]
I have an Nvidia 2080 Q-max

**Comment by Rem0o** [comment]
Oh you are on a laptop? Laptops are not supported.

**Comment by SomeCrbn** [comment]
Ah ok that's the issue then, thank you
