### ISSUE TITLE
Fan control not working/starting with older versions of Adrenaline 

### ISSUE THREAD

**Issue by ColdingNewb** [Rem0o/FanControl.Releases#2851]
**If you are experiencing a crash**
Link the relevant/associated Windows EventViewer logs, and also FanControl's own log.txt.

**Describe the bug**
[A clear and concise description of what the bug is.  Screenshots are worth a thousand words. Hardware support requests do NOT count as a bug. See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility.]
The bug I am seeing is that after downgrading from adrenaline version 24.10.1 -> 24.8.1 my fan control now no longer opens at all, and in the process of downgrading I was still able to have it opened in the background but unable to control my gpu fan curves, but after a system restart it cannot start at all anymore. The only fix I had been able to come up with is just to stick with the latest adrenaline verison but as a result (only fortnite) I cannot play because of driver related crashes, so hopefully anyone with a solution is able to let me know if there's a fix or solution for this. 
**Is there a log.txt file next to FanControl.exe with recent date entries?**
[Link it here]
11/25/2024 4:12:46 PM: Dispose - ADLXWrapper.ADLXEception: Result: ADLX_NOT_SUPPORTED 
SetZeroRPMState
   at ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   at ADLXWrapper.ManualFanTuning.SetZeroRPM(Boolean enabled)
   at ADLXWrapper.ManualFanTuning.Reset()
   at FanControl.Domain.BackendProviders.ADLX.ADLXControl.Reset()
   at FanControl.Domain.Control.Reset()
   at FanControl.Domain.Control.Dispose()
   at FanControl.ViewModels.ControlViewModel.Dispose()
   at FanControl.ViewModels.MainWindowViewModel.Dispose()
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at FanControl.Bootstrap.Dispose()
This is all I can find that's relevant to this
**Relevant hardware specs and setup**
[Laptops and most proprietary pre-built desktops are not supported.]
Main issue is with the 7900 GRE adrenaline drivers

It's my first ever post on github so I apologize if it's badly formatted

**Comment by Rem0o** [comment]
These old versions don't crash fortnite... but crash FanControl. It's a driver bug.  Pick your poison.

**Comment by ColdingNewb** [comment]
Yeah... that's what I'm saying too, I just decided fan control > Fortnite, especially since I barely play it. I hope there's some kind of solution to get best of both worlds

**Comment by Rem0o** [comment]
There is nothing we can do here. The solution is for AMD to get their **** together and deliver a driver that doesn't crash.

**Comment by ColdingNewb** [comment]
Yeah I appreciate you letting me know, that sucks that AMD still has issues with drivers, I should've listened to when people said AMD has driver issues :/ 
I appreciate your work though, I love fan control and it's great!
