### ISSUE TITLE
Fan control wont show motherboard sensors (AMD X870)

### ISSUE THREAD

**Issue by SLabayen** [Rem0o/FanControl.Releases#2856]
Hello, today i downloaded Fan control and i tried to configure it for my new PC. Upon opening up, i can only see two cards, that show information of my gpu, and Fan control can calibrate the gpu fans. 

But the motherboard fans never show up. I tried checking the "Controller (various third parties)" box, and unchecking it, i tried older versions up to V199, and i tried many .NET 4.8 and .NET 8 versions. All of them fail. 

After failing to detect the fans, a single card without any information appears.

This is how the program looks after failing to recognize the fans:
![fdsdd](https://github.com/user-attachments/assets/43cf5ec6-27ee-4e98-a6d4-2fb6cb3eab9a)

![fsfdsf](https://github.com/user-attachments/assets/42ab5373-f7bd-4959-9339-d086a220cf25)

Unfortunately, the "logs.txt" file only shows up if i paste the "FanControl.AsusWMI.dll" file into the plugins folder. I tried that dll, and the program says it only found two of 8 sensors, but none of them show. And this is the output:

"11/28/2024 4:35:43 PM: AsusWMIPlugin Initialization failed.
11/28/2024 4:35:44 PM: AsusWMIPlugin Initialization failed.
11/28/2024 4:35:49 PM: AsusWMIPlugin Initialization failed.
11/28/2024 4:35:55 PM: AsusWMIPlugin Initialization failed.
11/28/2024 4:36:00 PM: AsusWMIPlugin Initialization failed.
11/28/2024 4:36:05 PM: AsusWMIPlugin Initialization failed.
11/28/2024 4:36:11 PM: Try refresh failed. Retry count (6) exceeded.
Asus WMI could not initialize or has no sensors.
11/28/2024 4:37:12 PM: Sensor validation failed."

Without the dll, the logs.txt file doesn't show up.

PC specs:

CPU: Amd Ryzen 7 9800X3D.
Motherboard: ASUS X870E-E STRIX GAMING WIFI.
GPU: MSI RTX 3090.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

Closing.

**Comment by charley008** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/155
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1566
After I compiled the LibreHardwareMonitorLib.dll, FanControl was able to recognize the cpu fan

**Comment by aeevi** [comment]
FYI - [this ](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1566) is for the Asus ROG Strix X870-I only. The ITX board does some weird things, and not necessarily applicable to other X870 boards.
