### ISSUE TITLE
updater.exe enhancement / command line issues

### ISSUE THREAD

**Issue by truespirt14** [Rem0o/FanControl.Releases#2861]
1) Is there anyway to improve updater.exe to not update unless a new version is actually available?
2) Could we get the -m --minimized command line option on updater.exe so the program can be restarted in minimized mode?  I notice it reopens with a window, even if you have the option set fancontrol to always open minimized.
3) Using -e --exit command line in fancontrol.exe doesn't actually force fancontrol process to stop.  It restarts it for some reason, and not only that, it restarts it in a windows ignoring the option in settings to start minimized.  It also ignores -m --minimized.  Is this a bug?  Perhaps we need a -r --restart command line too?  and if so, hopefully have it respect the minimized settings / command line.

**Comment by Rem0o** [comment]
Hi,

* For 1 and 2, what's your use case exactly?  The updater is not meant to be used manually by the user. 
* For 3: indeed the exit option seems broken, will fix.  There is no need to make it work with -m, as it's meant to exit.

**Comment by truespirt14** [comment]
Use case for 1 and 2 is that instead of being annoyed by having to update fan control 2-3 times a month, I can just setup a scheduled task to do it once a week, or on startup perhaps.  I could simply have the task run updater.exe and it would automatically check for an update in the background and if one exists, update it for me.   No need to bother me with it.

**Comment by Rem0o** [comment]
So basically you want auto-update, or you want to turn off the update popup ?
You could just set the popup off, and leave FanControl alone until need be. You don't need to follow every update except if you got a specific reason to do update, like new hardware and so on.

**Comment by truespirt14** [comment]
Auto-update would be nice.  But with the suggestions I recommended, I could make my own auto-update that could run every so often.  That way if weeks go by and I had no reason to open Fan Control, the update could still be applied on its own.

**Comment by Rem0o** [comment]
V210 for --exit

As for auto-update I believe there is an issue already for this.
https://github.com/Rem0o/FanControl.Releases/issues/2067
