### ISSUE TITLE
Include support for Thinkbook 16p Gen 4

### ISSUE THREAD

**Issue by King-Chris111** [Rem0o/FanControl.Releases#2868]
Not fully clear until now, Read-Registers for the EC of a Thinkbook 16p Gen 4 are in position 6 for one fan and on position 254 for the other fan.
Can it be estimated where the fan control is located? It probably will be similar to a Legion Slim 7 Gen 8 which has the same base and most probably the same Embedded Controller.

![image](https://github.com/user-attachments/assets/f457ff90-86a8-4f5a-bb9a-758969a42977)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility

I don't do low-level research for specific laptops.   If you got it figured out enough to have it working in a program, a quick plugin could add support.
https://github.com/Rem0o/FanControl.Releases/wiki/Plugins
