### ISSUE TITLE
Feature request: Average of different temperature values

### ISSUE THREAD

**Issue by hruzgar** [Rem0o/FanControl.Releases#2869]
Before I start I really want to express my gratitude to the developers of this amazing application. It really helps me control my fans however I want which is amazing and no other software really does it the same way!

Sometimes I do heavy gpu work, but my cpu is not getting hot because I have an aio solution. 
Now my case fans are controlled by a curve which depends on the cpu temperature.
The problem is that the gpu is not getting enough fresh air because the case fans are dependant on the cpu.
I want the curve to depend on not only the temperature of the cpu, but also the gpu. This could be achieved if there was an option to take the average of some temperature values instead of depending on a single one.

**So would it be possible to make curves depend on the average of some temperature values instead of making it depend on a single one?**

**Comment by InHeritas** [comment]
You can create a single sensor that represents the average of multiple temperature readings using the custom sensor feature. Click the "+" icon in the bottom-right corner and select "mix." then, on the newly created card, choose "average" as the function and add the temperature sensors you wish to use.  Finally, on the curve card, set the temperature source to the custom sensor.
