### ISSUE TITLE
Won't even launch, log points to NVAPI_NOT_SUPPORTED

### ISSUE THREAD

**Issue by barc0de1989** [Rem0o/FanControl.Releases#287]
Log says this:

09.07.2021 11:01:39: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NOT_SUPPORTED
   bei NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   bei System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   bei System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei FanControl.Domain.ComputerAccessLayer.Initialize()
09.07.2021 11:01:39: Could not initialize.

(German operating system, hence the "bei")
This is happening on a 2020 Zephyrus G15 notebook with a GeForce RTX 1660 Ti Max Q. I have no idea why this is happening, it's working fine on my desktop PC

**Comment by Rem0o** [comment]
"notebook" is the key here, those are not supported.
