### ISSUE TITLE
Missing MIT license attribution

### ISSUE THREAD

**Issue by ghost** [Rem0o/FanControl.Releases#2874]
Your project is using libraries  licensed under the MIT License. The terms of this license require that the copyright notice and license text are included with all copies or substantial portions of the software. Currently, it seems this attribution is missing from your releases entirely. 

Compliance with the MIT License is important because failing to include the required attribution can mean the library is being used without proper permission. This **may also affect the legal standing of your project’s own license**, as it depends on properly licensed components. 

I encourage you to review the terms of the MIT License and consider adding the necessary attribution to your project to ensure compliance. This not only satisfies the legal requirements but also respects the contributions of the library’s developers.

I appreciate your work and hope you see this as valuable notice for your continuing effort. Not the opposite. Its not an accusation, but an "issue" up for your consideration. 

Thanks in advance :)

**Comment by Fr0stX76** [comment]
After the 1st one I was like...ok sure, why not.  But now, after opening a second similar issue, it feels more like someone who created a dummy account to troll using the small prints of the contract.

Am I the only one getting an "unhappy Linux open source fanboy vibe"?

**Comment by Rem0o** [comment]
Hi,

I linked all open-source libraries in the included EULA txt document directly, but I did not copy the text of each license itself. What in your opinion is missing exactly and would you remedy specifically ? I could rename it to EULA-Licenses.txt and present it as such.

This repo also has a license file already (https://github.com/Rem0o/FanControl.Releases?tab=License-1-ov-file#readme), should I add a "third-party" section at the bottom with a text copy of each license, stating like:

> __LibreHardwareMonitor__
FanControl uses LibreHardwareMonitorLib as is. This portion of the software is under the  following license:
[MPL-2.0-1 text here]

and so on?

**Comment by gh000000st** [comment]
Thank you for your detailed response and willingness to address the matter. 

I appreciate your proactive approach in already including references to open-source libraries in the EULA. However, the MIT License requires more than just linking to the libraries—it mandates that the license text and copyright notice be included with the software when it’s distributed. Here's what I’d suggest to ensure compliance:

1. **Rename the EULA file to include “Licenses”**: Renaming it to something like `EULA-Licenses.txt` (as you proposed) is a great idea, as it makes the purpose of the file clearer.

2. **Include full license texts and copyright notices**: For the libraries under the MIT License (and other licenses that require attribution), you should include the full license text and their copyright notices within the EULA-Licenses.txt file. Listing them in a "Third-Party Licenses" section, as you suggested, would work well.

3. **Update the repository’s `LICENSE` file (optional)**: Adding a section for third-party libraries at the bottom of the main `LICENSE` file is also a good practice. This section could summarize the libraries and their associated licenses and point to the EULA-Licenses.txt for the full texts.

Here’s an example structure for the "Third-Party Licenses" section in your repository’s LICENSE file:

* LibreHardwareMonitor: Licensed under MPL-2.0. See EULA-Licenses.txt for details.
* [Other Library Name]: Licensed under MIT. See EULA-Licenses.txt for details.

This ensures transparency while keeping the main LICENSE file concise.

By adopting these steps, you’ll not only fulfill the legal obligations of the MIT License but also demonstrate respect for the open-source contributors whose work supports your project. 

I hope you understand that my intention in raising these two issues is to support and protect your work, not to criticize it. If you disagree, feel free to close the issue. My sole aim is to encourage better compliance. Thank you :)

**Comment by Rem0o** [comment]
I will do 1) and 2) as suggested. Will be included in the next release. 

> I hope you understand that my intention in raising these two issues is to support and protect your work, not to criticize it. If you disagree, feel free to close the issue. My sole aim is to encourage better compliance. Thank you :)

I always assume good faith first, as I act in good faith myself. However, an anonymous "open-source police" post from a brand new account with no other history may seem suspect at first, but in the end this was a constructive conversation with what I think is a beneficial conclusion, so thank you!

Will close on the next release.

**Comment by Rem0o** [comment]
V210

**Comment by Fr0stX76** [comment]
So he basically created an account to raise this, then deleted it. Legit concern, not sure I get the approach.. The github licence shadow-ninja lol
