### ISSUE TITLE
Fan control only seeing GPU fans 

### ISSUE THREAD

**Issue by RC1991** [Rem0o/FanControl.Releases#2885]
Fan control only seeing GPU fans 

Device name	DESKTOP-NPECGAR
Processor	AMD Ryzen 7 9800X3D 8-Core Processor              4.70 GHz
Installed RAM	64.0 GB (61.6 GB usable)
Device ID	19864AFE-5A58-4366-8B07-B95BD6053E76
Product ID	00330-52852-68557-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is avai

<

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
