### ISSUE TITLE
v48 update wiped configuration.

### ISSUE THREAD

**Issue by SeekHplus** [Rem0o/FanControl.Releases#29]
First of all, thank you for this incredible tool! Gone are the days in which I had to wrestle with SpeedFan just to control some of my fans, now I can control everything with per-component mix curves like its the 21st century! Now, I just updated from v47 to v48, which seemingly reverted UserConfig to default, deleting al my curves and control card names, themes, etc. This is the first time this has happened in the 3-4 updates I have done already.

**Comment by Rem0o** [comment]
There seem to be an issue where the config file is getting "locked" and when the app starts back up, it can't read the file then overwrites it. Looking into it.

**Comment by Rem0o** [comment]
It's fixed. The update package had a default config built-in that would overwrite userConfig.json, my mistake.
