### ISSUE TITLE
Control Not Working

### ISSUE THREAD

**Issue by blackadar** [Rem0o/FanControl.Releases#290]
It seems that using FanControl to control fans sets them to 0% now on my system. Starting the match fan control process only seems to set my chipset fan to 60% and all other devices seem to stop, and the matching process doesn't seem to work well. It seems like FanControl can't actually change the speeds correctly.

Here's the log:

> Motherboard
> 
> SMBios Version: 3.3
> 
> BIOS Vendor: American Megatrends Inc.
> BIOS Version: 3405
> BIOS Date: 2/1/2021
> BIOS Size: 16 MB
> 
> System Manufacturer: System manufacturer
> System Name: System Product Name
> System Version: System Version
> System Wakeup: PowerSwitch
> 
> Motherboard Manufacturer: ASUSTeK COMPUTER INC.
> Motherboard Name: TUF GAMING X570-PLUS (WI-FI)
> Motherboard Version: Rev X.0x
> Motherboard Serial: 201076024500514
> 
> Chassis Type: Desktop
> Chassis Manufacturer: Default string
> Chassis Version: Default string
> Chassis Serial: Default string
> Chassis Asset Tag: Default string
> Chassis SKU: Default string
> Chassis Boot Up State: Safe
> Chassis Power Supply State: Safe
> Chassis Thermal State: Safe
> Chassis Power Cords: 1
> Chassis Lock Detected: No
> Chassis Security Status: None
> 
> Processor Manufacturer: Advanced Micro Devices, Inc.
> Processor Type: CentralProcessor
> Processor Version: AMD Ryzen 5 5600X 6-Core Processor
> Processor Serial: Unknown
> Processor Socket Destignation: AM4
> Processor Socket: AM4
> Processor Version: AMD Ryzen 5 5600X 6-Core Processor
> Processor Family: AmdZen
> Processor Core Count: 6
> Processor Core Enabled: 6
> Processor Thread Count: 12
> Processor External Clock: 100 Mhz
> Processor Max Speed: 4650 Mhz
> Processor Current Speed: 3700 Mhz
> 
> Cache [L1] Size: 384
> Cache [L1] Associativity: 8Way
> 
> Cache [L2] Size: 3072
> Cache [L2] Associativity: 8Way
> 
> Cache [L3] Size: 33280
> Cache [L3] Associativity: 16Way
> 
> Memory Device [0] Manufacturer: Unknown
> Memory Device [0] Part Number: Unknown
> Memory Device [0] Device Locator: DIMM_A1
> Memory Device [0] Bank Locator: BANK 0
> Memory Device [0] Speed: 0Memory Device [0] Size: 
> 0 MB
> 
> Memory Device [1] Manufacturer: G-Skill
> Memory Device [1] Part Number: F4-3600C16-16GTZRC
> Memory Device [1] Device Locator: DIMM_A2
> Memory Device [1] Bank Locator: BANK 1
> Memory Device [1] Speed: 3600Memory Device [1] Size: 
> 16384 MB
> 
> Memory Device [2] Manufacturer: Unknown
> Memory Device [2] Part Number: Unknown
> Memory Device [2] Device Locator: DIMM_B1
> Memory Device [2] Bank Locator: BANK 2
> Memory Device [2] Speed: 0Memory Device [2] Size: 
> 0 MB
> 
> Memory Device [3] Manufacturer: G-Skill
> Memory Device [3] Part Number: F4-3600C16-16GTZRC
> Memory Device [3] Device Locator: DIMM_B2
> Memory Device [3] Bank Locator: BANK 3
> Memory Device [3] Speed: 3600Memory Device [3] Size: 
> 16384 MB
> 
> SMBios Table
> 
>  AAMDAO8LAAAAGgAAAQIA8AP/gJyLPwEAAAADDQUR//8QAEFtZXJpY2FuIE1lZ2F0
>  cmVuZHMgSW5jLgAzNDA1ADAyLzAxLzIwMjEAAAEbAQABAgMEPIws3VWWd7hoDTx8
>  P/NkTAYFBlN5c3RlbSBtYW51ZmFjdHVyZXIAU3lzdGVtIFByb2R1Y3QgTmFtZQBT
>  eXN0ZW0gVmVyc2lvbgBTeXN0ZW0gU2VyaWFsIE51bWJlcgBTS1UAVG8gYmUgZmls
>  bGVkIGJ5IE8uRS5NLgAAAg8CAAECAwQFCQYDAAoAQVNVU1RlSyBDT01QVVRFUiBJ
>  TkMuAFRVRiBHQU1JTkcgWDU3MC1QTFVTIChXSS1GSSkAUmV2IFguMHgAMjAxMDc2
>  MDI0NTAwNTE0AERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAAADFgMAAQMC
>  AwQDAwMDAAAAAAABAAMFRGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcARGVm
>  YXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcAAAgJBAAB
>  AAIPDVBTLzIgS2V5Ym9hcmQvTW91c2UAUFMvMiBLZXlib2FyZC9Nb3VzZQAACAkF
>  AAEAAhIQVTMyRzFfNTYAVTMyRzFfNTYAAAgJBgABAAISEFUzMkcxXzM0AFUzMkcx
>  XzM0AAAICQcAAQACEhBVMzJHMl9DMwBVMzJHMl9DMwAACAkIAAEAAv8cRFAARFAg
>  cG9ydAAACAkJAAEAAv8cSERNSQBIRE1JIHBvcnQAAAgJCgABAAL//00uMihXSS1G
>  SSkATS4yKFdJLUZJKQAACAkLAAEAAhIQVTMyRzJfMTIAVTMyRzJfMTIAAAgJDAAB
>  AAILH0xBTgBMQU4AAAgJDQABAAL/HUFVRElPAEFVRElPAAAICQ4AASIAACBTQVRB
>  NkdfMQAACAkPAAEiAAAgU0FUQTZHXzIAAAgJEAABIgAAIFNBVEE2R18zAAAICREA
>  ASIAACBTQVRBNkdfNAAACAkSAAEiAAAgU0FUQTZHXzUAAAgJEwABIgAAIFNBVEE2
>  R182AAAICRQAASIAACBTQVRBNkdfNwAACAkVAAEiAAAgU0FUQTZHXzgAAAgJFgAB
>  IgAAIE0uMl8xKFNPQ0tFVDMpAAAICRcAASIAACBNLjJfMihTT0NLRVQzKQAACAkY
>  AAESAAAQVVNCNzgAAAgJGQABEgAAEFVTQjkxMAAACAkaAAESAAAQVTMyRzFfMTIA
>  AAgJGwAB/wAA/0NQVV9GQU4AAAgJHAAB/wAA/0NQVV9PUFQAAAgJHQAB/wAA/0NI
>  QV9GQU4xAAAICR4AAf8AAP9DSEFfRkFOMgAACAkfAAH/AAD/Q0hBX0ZBTjMAAAgJ
>  IAAB/wAA/0FJT19QVU1QAAAICSEAAf8AAP9QQ0hfRkFOAAAICSIAAQgAAAlDT00A
>  AAgJIwABHwAAHUFBRlAAAAgJJAAB/wAA/1BBTkVMAAAICSUAAf8AAP9TUElfVFBN
>  AAAICSYAAf8AAP9SR0JfSEVBREVSMQAACAknAAH/AAD/UkdCX0hFQURFUjIAAAgJ
>  KAAB/wAA/0FERF9HRU4gMgAACgYpAIMBICAgVG8gQmUgRmlsbGVkIEJ5IE8uRS5N
>  LgAACwUqAAhEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwBURVFVSUxBAERl
>  ZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1
>  bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAAAMBSsABERlZmF1bHQgc3RyaW5nAERl
>  ZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAAAgFCwA
>  AAAAAAAAAAAAAAAAAAAAAAAAIgstAAEBlQIAAANOQ1Q2Nzk4RC1SAAAoMi4ABQkp
>  AAEBAAAAAAkBAA8AHgAAAAk2AAECAAAAAAkBABoDAAAAAAkBABkEAwAAAFRvIEJl
>  IEZpbGxlZCBCeSBPLkUuTS4gMQBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uIDMAUFJP
>  RFVDVF9MSU5FAFBST0RVQ1RfU0tVAAApCy8AAYMBAAAAECBPbmJvYXJkIElHRAAA
>  LAkwAP//AQEAAAASFzEAAwICAAAAAAAAAIAAAACAAAAAgAAAEBcyAAMDAwAAAAgx
>  AAQAAAAAAAAAAAAAABMfMwAAAAAA//8zADIAAgAAAAAAAAAAAAAAAAAAAAAAABMf
>  NAAAAEAA//8LAjIAAgAAAAAAAAAAAAAAAAAAAAAAAAcbNQABgAGAAYABEAAQAAEG
>  BQeAAQAAgAEAAEwxIC0gQ2FjaGUAAAcbNgABgQEADAAMEAAQAAEGBQcADAAAAAwA
>  AEwyIC0gQ2FjaGUAAAcbNwABggEAggCCEAAQAAEGBQgAAgCAAAIAgEwzIC0gQ2Fj
>  aGUAAAQwOAABA2sCEA+iAP/7ixcDi2QAKhJ0DkExNQA2ADcABAUGBgYM/ABrAAYA
>  BgAMAEFNNABBZHZhbmNlZCBNaWNybyBEZXZpY2VzLCBJbmMuAEFNRCBSeXplbiA1
>  IDU2MDBYIDYtQ29yZSBQcm9jZXNzb3IgICAgICAgICAgICAgAFVua25vd24AVW5r
>  bm93bgBVbmtub3duAAASFzkAAwICAAAAAAAAAIAAAACAAAAAgAAAEVw6ADIAOQD/
>  ////AAACAAECAgQAAAADBAAFAAAAAAAAAAAAAAAAAAIEAAYAAAAAAAAAAAAAAAAA
>  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABESU1NX0ExAEJBTksg
>  MABVbmtub3duAFVua25vd24AVW5rbm93bgBVbmtub3duAAASFzsAAwICAAAAAAAA
>  AIAAAACAAAAAgAAAEVw8ADIAOwBAAEAAAEAJAAECGoBAEA4DBAAFAgAAAAAQDrAE
>  sASwBAMIAAYEzQAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA
>  AAAAAAAAAABESU1NX0EyAEJBTksgMQBHLVNraWxsADAwMDAwMDAwAEY0LTM2MDBD
>  MTYtMTZHVFpSQwBVbmtub3duAAAUIz0AAAAAAP///wE8ADQA////AAAAAAAAAAAA
>  AAAAAAAAAAAAEhc+AAMCAgAAAAAAAACAAAAAgAAAAIAAABFcPwAyAD4A/////wAA
>  AgABAgIEAAAAAwQABQAAAAAAAAAAAAAAAAACBAAGAAAAAAAAAAAAAAAAAAAAAAAA
>  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARElNTV9CMQBCQU5LIDIAVW5r
>  bm93bgBVbmtub3duAFVua25vd24AVW5rbm93bgAAEhdAAAMCAgAAAAAAAACAAAAA
>  gAAAAIAAABFcQQAyAEAAQABAAABACQABAhqAQBAOAwQABQIAAAAAEA6wBLAEsAQD
>  CAAGBM0AAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
>  AAAARElNTV9CMgBCQU5LIDMARy1Ta2lsbAAwMDAwMDAwMABGNC0zNjAwQzE2LTE2
>  R1RaUkMAVW5rbm93bgAAFCNCAAAAAAD///8BQQA0AP///wAAAAAAAAAAAAAAAAAA
>  AAAAAA0WQwAJAAAAAAAAAAAAAAAAAAAAAAFlbnxVU3xpc284ODU5LTEAZnJ8RlJ8
>  aXNvODg1OS0xAHpofFRXfHVuaWNvZGUAemh8Q058dW5pY29kZQBqYXxKUHx1bmlj
>  b2RlAGRlfERFfGlzbzg4NTktMQBlc3xFU3xpc284ODU5LTEAcnV8UlV8aXNvODg1
>  OS01AGtvfEtSfHVuaWNvZGUAAAkRRAABqg0EBAAABAEAAAAZUENJRVgxNl8xAAAJ
>  EUUAAagKAwQBAAQBAAAA/1BDSUVYMTZfMgAACRFGAAGmCAMDAgAEAQAAAP9QQ0lF
>  WDFfMQAACRFHAAGmCAMDAwAEAQAAAP9QQ0lFWDFfMgAAfwRIAAAA
> 
> 
> AMD CPU
> 
> Name: AMD Ryzen 5 5600X
> Number of Cores: 12
> Threads per Core: 1
> Timer Frequency: 14.31818 MHz
> Time Stamp Counter: None
> Estimated Time Stamp Counter Frequency: 3700.1 MHz
> Estimated Time Stamp Counter Frequency Error: 0.54785 Mhz
> Time Stamp Counter Frequency: 3700.1 MHz
> 
> MSR Core #1
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #2
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #3
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #4
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #5
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #6
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #7
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #8
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #9
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #10
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #11
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> MSR Core #12
> 
>  MSR       EDX       EAX
>  C0010000  00000000  00000000
>  C0010004  00000000  00000000
>  C0010015  00000001  89000111
>  C0010064  80000000  49520894
> 
> Ryzen SMU
> 
>  PM table version: 0x00380904
>  PM table supported: True
>  PM table layout defined: False
>  PM table size: 0x5A4
>  PM table start address: 0xCAA9A000
> 
>  PM table dump:
>   Idx    Offset   Value
>  ------------------------
>     0    0x000    0
> 
> 
> 
> LPC Nct677X
> 
> Chip Id: 0xD42B
> Chip Revision: 0x2B
> Base Address: 0x0290
> 
> Hardware Monitor Registers
> 
>         00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
> 
>  0000   03 AB 03 97 00 FF FF FF FF FF FF FF FF FF FF FF
>  0010   03 AB 03 AB 03 51 03 AB 40 FF FF FF FF FF FF FF
>  0020   FF FF FF FF FF FF FF 1E 03 FF FF DA 00 00 00 00
>  0030   00 00 00 00 00 00 00 00 00 50 4B FF FF FF FF FF
>  0040   03 0E 07 FF FF 00 3F FF 2D FF FF 10 08 55 00 A3
>  0050   15 FF FF FF FF FF FF FF C1 FF FF FF FF 01 00 01
>  0060   AA A5 FF FF FF 01 00 FF FF FF FF FF FF FF FF FF
>  0070   00 0A 00 2E 80 2E 80 2E 80 2E 80 3B 80 2E 80 FF
>  00F0   00 00 00 00 00 00 00 FF 1C 40 23 1B FF FF FF FF
>  0100   1C 00 40 00 00 01 01 3C 00 AB FF AB 00 FF FF FF
>  0110   FF 19 23 2D 37 FF FF 8C AA C8 E6 32 00 01 01 00
>  0120   FF 1E 4B 4B 4B FF FF 99 CC FF FF FF FF FF FF FF
>  0130   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
>  0140   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 01 FF
>  0150   25 00 00 4B 00 50 00 FF FF FF FF FF FF FF FF FF
>  0200   1C 32 40 00 00 01 01 3C 00 97 00 97 00 FF FF FF
>  0210   FF 14 4B 4B 4B FF FF 68 CC FF FF 14 82 02 02 00
>  0220   FF 00 00 00 00 FF FF 00 00 00 00 FF FF FF FF FF
>  0230   FF 00 FF FF 00 7D 01 FF 02 01 00 00 00 00 00 00
>  0240   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 02 FF
>  0250   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0260   FF FF FF FF FF FF 00 00 00 97 FF FF FF FF FF FF
>  0300   1C 00 40 00 00 01 01 3C 00 AB FF AB 00 FF FF FF
>  0320   FF 00 00 00 00 FF FF 00 00 00 00 FF FF FF FF FF
>  0330   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
>  0340   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 03 FF
>  0360   FF FF FF FF FF FF 00 00 00 AB FF FF FF FF FF FF
>  0400   00 00 00 00 00 00 00 00 00 39 60 3B A0 FF FF FF
>  0410   FF FF FF FF FF FF FF FF FF 00 00 FF FF FF FF FF
>  0420   FF FF FF 96 64 96 64 E1 96 00 FF FF FF FF FF FF
>  0440   FF 00 00 00 FF 00 FF FF FF FF 00 00 00 00 04 FF
>  0450   03 FB FF FF 00 00 00 FF FF 0E 13 33 09 00 FF FF
>  0460   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0480   9F 7C D4 D1 7F 74 7C D4 D1 71 21 44 81 7A 7F 74
>  0490   1E 25 1A 36 15 19 1E 2B 80 2E 2E 2E 2E 3B 5F 2E
>  04B0   FF 1F 1E 14 25 01 2D 0E 14 16 16 16 00 AB 00 00
>  04C0   00 00 05 61 04 73 03 A0 07 F7 07 43 FF 1F 00 00
>  04F0   39 80 3B 80 2E 3B F5 00 50 00 51 00 00 00 00 FF
>  0500   FF FF 00 FF FF FF 00 FF BA FF FF FF FF 00 00 FF
>  0550   D4 D1 80 FF 00 00 00 00 00 00 00 00 00 00 00 00
>  0560   00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF
>  0600   00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF
>  0610   00 00 00 00 00 00 00 FF 1F FF FF FF FF FF FF FF
>  0620   FF 01 02 00 00 FF FF FF FF FF FF FF FF FF 16 16
>  0630   FF 1F 1E 14 25 01 2D 0E 14 16 FF 1F FF 1F FF 1F
>  0640   FF 1F FF 1F 02 02 02 02 02 02 FF 1F FF 1F 06 02
>  0650   7F 7F 7F 7F 07 43 00 00 05 61 04 73 03 A0 07 F7
>  0660   00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0670   1A 80 36 80 15 00 19 00 1E 00 25 00 FF FF FF FF
>  0700   FF 85 02 10 00 00 00 00 00 00 00 00 00 00 00 00
>  0710   00 00 00 00 00 00 00 00 00 F8 80 F8 80 F8 80 0F
>  0720   00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
>  0730   00 00 00 00 00 00 00 00 00 00 00 0E 0A 00 00 00
>  0800   1C 00 40 00 00 01 01 3C 00 AB FF AB 00 FF FF FF
>  0820   FF 1E 4B 4B 4B FF FF 99 CC FF FF FF FF FF FF FF
>  0830   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
>  0840   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 08 FF
>  0900   09 00 40 00 00 01 01 3C 00 51 FF 51 00 FF FF FF
>  0920   FF 37 3C 5D 64 FF FF 00 66 FF FF FF FF FF FF FF
>  0930   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
>  0940   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 09 FF
>  0960   FF FF FF FF FF FF 00 00 00 51 FF FF FF FF FF FF
>  0A00   1C 00 40 00 00 01 01 3C 00 AB FF AB 00 FF FF FF
>  0A10   FF 19 23 2D 37 FF FF 8C AA C8 E6 3C 00 03 03 00
>  0A20   FF 1E 4B 4B 4B FF FF 99 CC FF FF FF FF FF FF FF
>  0A30   FF 00 FF FF 00 64 01 FF 02 FF FF FF FF FF FF 00
>  0A40   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 0A FF
>  0A50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0A60   FF FF FF FF FF FF 00 00 00 AB FF FF FF FF FF FF
>  0A70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0B00   03 00 00 0A 0A 01 01 3C 00 FF FF 00 00 FF FF FF
>  0B10   FF 19 23 2D 37 FF FF 8C AA C8 E6 3C 00 03 03 00
>  0B20   FF 19 23 2D 37 FF FF 8C AA C8 E6 FF FF FF FF FF
>  0B30   FF 00 FF FF 00 64 01 FF 00 FF FF FF FF FF FF 00
>  0B50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0B60   FF FF FF FF FF FF 11 00 00 FF FF FF FF FF FF FF
>  0B70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0C00   FF 00 00 00 3F 3F 3F 00 00 00 00 00 00 00 7F 7F
>  0C10   7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 50 50 50 50 50 50
>  0C20   4B 4B 4B 4B 4B 4B 03 04 05 06 07 02 00 00 00 00
>  0C30   00 00 00 00 00 00 00 00 00 00 00 00 00 00 0A 00
>  0C50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0C60   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0C70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0D00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0D10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0D20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0D30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0D50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0D60   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0E00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0E10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0E20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0E30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0F00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0F10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0F20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0F30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  8040   03 00 00 FF FF 00 3F FF 2D FF FF 10 08 55 80 5C
>  80F0   00 00 00 00 00 00 00 FF 1C 40 23 1B FF FF FF FF
> 
> 
> Storage
> 
> Drive Name: WDS100T3X0C-00SJG0
> Firmware Version: 111110WD
> 
> PCI Vendor ID: 0x15b7
> IEEE OUI Identifier: 0x001b44
> Total NVM Capacity: 1000204886016
> Unallocated NVM Capacity: 0
> Controller ID: 8215
> Number of Namespaces: 1
> Critical Warning: -
> Temperature: 46 Celsius
> Available Spare: 100%
> Available Spare Threshold: 10%
> Percentage Used: 1%
> Data Units Read: 20757909
> Data Units Written: 41339923
> Host Read Commands: 264157856
> Host Write Commands: 318405455
> Controller Busy Time: 610
> Power Cycles: 345
> Power On Hours: 3785
> Unsafe Shutdowns: 7
> Media Errors: 0
> Number of Error Information Log Entries: 1
> Warning Composite Temperature Time: 0
> Critical Composite Temperature Time: 0
> Logical Drive Name: C:\
> Format: NTFS
> Total Size: 999550160896
> Total Free Space: 588551913472

**Comment by Rem0o** [comment]
From your logs, I can't see any SuperIO chips, meaning the software doesn't support your motherboard properly.

See the README.

**Comment by blackadar** [comment]
It did work properly in previous updates!

**Comment by blackadar** [comment]
Also, the manual shows a Super IO chip on Page 1-2 https://dlcdnets.asus.com/pub/ASUS/mb/SocketAM4/TUF_GAMING_X570-PLUS_WI-FI/E15236_TUF_GAMING_X570-PLUS_WI-FI_UM_WEB_060319.pdf

Only pointing this out in case it's useful to know for compatibility. I can of course just use an old release :)
