### ISSUE TITLE
Feature Rquest - Ability to run FanControl without admin rights

### ISSUE THREAD

**Issue by le0mil** [Rem0o/FanControl.Releases#292]
Is there any solution, how to use FanControl with Windows standard user? FanControl probably needs admin level rights to pull the data, but it would useful if the standard user could run it even by not being able to make any configuration changes.

Thank you!

**Comment by orthoxerox** [comment]
#52 is one way to do it.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/52
