### ISSUE TITLE
Feature Request - Multiple Tray Icons

### ISSUE THREAD

**Issue by astra-io** [Rem0o/FanControl.Releases#293]
Would love the ability to select which temps to show in tray. I would love to show CPU and GPU. 
Colors would be nice too, orange for CPU and green for GPU. 

Thanks! Love the software.

**Comment by abqnm** [comment]
Was going to suggest adding colors to the tray icon that is tied to the profile (like the main app colors), which would allow setting different colors for different profiles and be able to identify with just a glance which profile is active without having to right click.

For extra icons, that seems like it's deviating beyond Fan Control and into stats reporting and might be better served by using HWiNFO and adding the relevant sensors to the tray. But the colors is a good idea and that's the only reason I'm commenting here and not starting a new issue, as it would functionally achieve the same thing I'm asking if colors were added to the tray icon.

**Comment by Rem0o** [comment]
Dup of https://github.com/Rem0o/FanControl.Releases/issues/38.

**Comment by florian51292** [comment]
its shown as completed? Is it implemented right now?
