### ISSUE TITLE
Fan curves temporarliy maxed when waking from sleep

### ISSUE THREAD

**Issue by sctanf** [Rem0o/FanControl.Releases#295]
When waking up from sleep, I can hear all fans ramping up (towards 100%, tested using 50% step size), then back down to normal. For now, I have set a smaller step size which makes the ramping less noticeable but doesn't stop it completely.

Took a look at v87 release notes, I think this may be related to v87 interpreting NaN as 100%?

**Comment by Rem0o** [comment]
Probably a transient state when the config is restored, will take a long.
