### ISSUE TITLE
Fan configuration error when resume from sleep

### ISSUE THREAD

**Issue by jackoboy9** [Rem0o/FanControl.Releases#296]
Get a load of fan configuration errors when resuming from sleep.
Using latest version (87).
See attached screenshot.
System specs:
AMD Ryzen 7 1700
Sapphire RX 580 Nitro+ 8GB
ASUS Crosshair VI Hero
<img width="316" alt="2021-07-18 09_28_20-" src="https://user-images.githubusercontent.com/20045623/126060954-77245f29-d68c-467e-9bef-7210569872b8.png">

**Comment by Rem0o** [comment]
Any error logs? (Log.txt)

**Comment by jackoboy9** [comment]
> Any error logs? (Log.txt)

Didn't realise there was one :)

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6836504/log.txt)

It probably contains multiple instances of the error.

**Comment by Rem0o** [comment]
Seems like upon wake from sleep, the driver can't get hold of your drives and times out.

![image](https://user-images.githubusercontent.com/14118956/126072996-5f353001-aba6-4f62-b9c5-1fc9006cb3ec.png)
 If you get that setting ticked, does it still happen?

**Comment by jackoboy9** [comment]
> Seems like upon wake from sleep, the driver can't get hold of your drives and times out.
> 
> ![image](https://user-images.githubusercontent.com/14118956/126072996-5f353001-aba6-4f62-b9c5-1fc9006cb3ec.png)
> If you get that setting ticked, does it still happen?

That did seem to work, but now the fan that is dependent on the HDD temperature just runs at a set 50% speed, since it can't find the sensor (as expected).
This only started happening after I upgraded to v87, btw. Was a change made to the timeout length? If so, is this value user-editable so the software waits a bit longer like in v86 and earlier?
Thanks.

**Comment by Rem0o** [comment]
Timeout is 10 seconds as it's always been.

**Comment by jackoboy9** [comment]
> Timeout is 10 seconds as it's always been.

How peculiar. I'll stick to v86 for now. Thanks!

**Comment by kamolot2k** [comment]
> 
> 
> Seems like upon wake from sleep, the driver can't get hold of your drives and times out.
> 
> ![image](https://user-images.githubusercontent.com/14118956/126072996-5f353001-aba6-4f62-b9c5-1fc9006cb3ec.png)
> If you get that setting ticked, does it still happen?

That solved it for me.

**Comment by Aphykit2006** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6838547/log.txt)
Hi
Here is mine.
Regards

**Comment by gordonthree** [comment]
Seeing same problem, mine is complaining about a linear curve I setup for the PCH ... running version 88

Here's the log 
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6888849/log.txt)

I have to go to task manager and end task, unable to close the program from the interface or tray icon. After restarting it works normally again.

**Comment by gordonthree** [comment]
No help from disabling storage sensors. Still get an huge error message when resuming from sleep. v89 asks if I want to refresh, I select yes (or no), it finds no fans, no sensors, and the program is generally unresponsive, can't exit have to end task. After restarting the program, it goes back to working normally.

**Comment by Mushin** [comment]
On v90, was also getting error messages that popped up every 30 seconds or so. Solved by disabling storage sensors. Log below:

`12/08/2021 13:45:30: Unhandled exception in FanControl v1.0.0.0
12/08/2021 13:45:30: System.IO.IOException: GetFeature failed. ---> System.ComponentModel.Win32Exception: The operation completed successfully
   --- End of inner exception stack trace ---
   at HidSharp.Platform.Windows.WinHidStream.GetFeature(Byte[] buffer, Int32 offset, Int32 count)
   at LibreHardwareMonitor.Hardware.Controller.AquaComputer.MPS.Update()
   at FanControl.Domain.UpdateVisitor.VisitHardware(IHardware hardware)
   at LibreHardwareMonitor.Hardware.Computer.Traverse(IVisitor visitor)
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
12/08/2021 13:45:30: System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully`

**Comment by mkossigit** [comment]
This issue just started for me a few days ago.

**Comment by Rem0o** [comment]
@Mushin 
Disable the controller section of the sensors from the settings.

**Comment by Rem0o** [comment]
Added a multi-retry mechanism since, until all sensors are back.
