### ISSUE TITLE
Nothing in log.txt

### ISSUE THREAD

**Issue by XanderTek** [Rem0o/FanControl.Releases#297]
My log.txt remains at 0 KB, even after a FanControl crash.  I've tried deleting it.  The file gets created again, but remains blank.  Also tried moving the location of the FanControl folder.  No change.

I think I'm experiencing issue #231 , but hard to be certain with no log.

**Comment by Rem0o** [comment]
EventViewer?

**Comment by XanderTek** [comment]
![Screenshot 2021-07-22 234926](https://user-images.githubusercontent.com/6239043/126735401-5fad6418-9896-4f76-805c-bdd3e5309765.png)
