### ISSUE TITLE
Request - PWMOUT Clock Frequency Setting

### ISSUE THREAD

**Issue by 1AGRESSOR** [Rem0o/FanControl.Releases#299]
I have seen this feature ONLY in "SpeedFan" no other software has it and it saved my ears and nerves
it eliminates whine from the fans i am now on "Nuvoton NCT6687D"

https://i.imgur.com/69OnaHv.png

I just tried your software and it is AWESOME simply the best ! however it is sad that is hard to find you should advertise it on more places like Twitter maybe, am there all the time.

Here i made a tweet about your software
https://twitter.com/1AGRESSOR/status/1417519636619345926

This person explains in more detail
https://silentpcreview.com/forums/viewtopic.php?t=59300

also here i think it's also called "PWM Duty Cycle"
https://www.allaboutcircuits.com/technical-articles/introduction-to-microcontroller-timers-pwm-timers/

Thank you

/Bane

**Comment by Rem0o** [comment]
The driver I'm using doesn't support such feature.
