### ISSUE TITLE
Feature Request - Show Temperatures

### ISSUE THREAD

**Issue by tedhong9** [Rem0o/FanControl.Releases#3]
Hi,
I think this a great project! Is there any way that I could show temperatures in card style as well? Thank you so much!

**Comment by Rem0o** [comment]
My goal for fan control is it to be a simple fan controlling software, not a monitoring software, even though it also has to show some monitoring stuff, like temperatures for curves or RPMs for fans. I fear it would bloat the UI, which is already pretty dense to my taste.

**Comment by tedhong9** [comment]
Ok, that's fine!

**Comment by Rem0o** [comment]
I will close this issue for now.
