### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by Zeliodas** [Rem0o/FanControl.Releases#300]
See attached log file below. Thanks!

[Log File.txt](https://github.com/Rem0o/FanControl.Releases/files/6859445/Log.File.txt)

**Comment by Rem0o** [comment]
What GPU?

**Comment by Zeliodas** [comment]
GTX 1650 Ti

**Comment by Zeliodas** [comment]
Was working last week. I have no idea what happened. Application just stopped running the other day on startup and when I tried manually opening the .exe, it does not start.

**Comment by Rem0o** [comment]
Logs tells me there is something wrong going with your GPU driver or something.

**Comment by Zeliodas** [comment]
Oh, just checked my Geforce Experience and it can't view the latest drivers. Will try reinstalling manually the updated GPU drivers and see if it fixes the issue in FanControl.
