### ISSUE TITLE
[Request] "Deadzone" fan curve - to avoid specific speeds

### ISSUE THREAD

**Issue by Aequita** [Rem0o/FanControl.Releases#303]
My old horse-drawn carriage is squeaking at some speeds like 68-72% case-fan-speed.
It would be awesome to have a curve-type similar to the "Mix" fan curve with multiple value-ranges to enter that are avoided.
A simple "Add dead range" for that curve would be sufficient.
If some other curve would set the specified fan at that range, the upper-%-speed is used instead.

In my case those ranges for case-fans would be
A) 40-45%
B) 68-72%
If any curve would set the case fans to e.g. 68% ---> 73% is used instead.

Awesome job - keep up the good work!

**Comment by rainmasak** [comment]
Why not doing something like this: 
![image](https://user-images.githubusercontent.com/22746015/127775441-f5ea272a-0e62-42b5-8af7-63b724f0ca3c.png)
1. area: go from 35% straight to 50% (skip 40-45% squeaky range)
2. area go from 65% straight to 75% (skip 68-72% squeaky range)

**Comment by Aequita** [comment]
That would work too I guess (haven't had time to set it up yet).
I currently have 3 linear curves for my case-fans, therefore my initial thought.
But changing them to graphs should work - thanks!
