### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by nonamed46** [Rem0o/FanControl.Releases#304]
Hi thanks for the amazing tool!
sadly the auto start (start with windows) keeps stopping to work and appears unchecked in the settings.
I manually turn it on and save the config and it works the next time i start my pc but then it stops again
-> looks like it turns off again after one successful auto start

PC:
Windows 10 Pro 64bit
CPU: Ryzen 9 5900x
RAM: 16gb Corsair Vengeance

**Comment by Rem0o** [comment]
Start with Windows is actually a wrapper around this: 
![image](https://user-images.githubusercontent.com/14118956/127406878-16ea72b9-4c45-47ef-ae76-56e50ced735a.png)

If the task is present, the checkbox is ticked. If somehow it gets deleted, the checkbox will untick by itself.
