### ISSUE TITLE
Not working Windows 7

### ISSUE THREAD

**Issue by ninja-gaijin** [Rem0o/FanControl.Releases#305]
Trying to install on Windows 7 Home Premium, but won't load.

Log file attached
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6909273/log.txt)

**Comment by Rem0o** [comment]
See FAQ:

Q: Does it run on my OS?
A: If your OS is Windows 10, yes.

**Comment by ninja-gaijin** [comment]
Would you recommend anything else for Windows 7?

**Comment by Rem0o** [comment]
SpeedFan, but it wasn't updated for over 5 years. My only suggestion would be to get off W7.

**Comment by ninja-gaijin** [comment]
> SpeedFan, but it wasn't updated for over 5 years. My only suggestion would be to get off W7.

Thank you, I figured this would be best, it was what I used to use before FanControl. I use a multiboot system and with Windows 7 I have <1GB ram usage with around 33 processes.. Windows 10, 130 processes, 3-4GB ram usage lol. So for my performance machine, Windows 7 still rules! Even over Windows 10 Ameliorated.

**Comment by Rem0o** [comment]
RAM usage on W10 can't be compared really since it will use unused RAM to cache a lot of stuff, but hey, to each their own.
