### ISSUE TITLE
graph edit mode - issues moving the default (0,0) point

### ISSUE THREAD

**Issue by pgarasz** [Rem0o/FanControl.Releases#306]
I've found that dragging the default first point (0,0) in graph editor mode is difficult. You have to move it very precisely after click and hold, otherwise it's very easy to loose it. It's like the area where you are able to click to activate that point is too small and a bit to the right. Other points don't exhibit this behaviour.

If you can't replicate it might be attributed to me having a custom DPI setting on my W10 (120dpi).

Thanks for the great app!

**Comment by rainmasak** [comment]
Can also confirm this. First point on the graph is very tricky to move (often does not move up or down with the cursor).

**Comment by Rem0o** [comment]
Currently looking to improve the graph editing, like being able to move points horizontally. Will look into this.

**Comment by Mushin** [comment]
I'm having an issue on v90, where I can't edit an existing graph by clicking on the 'edit' button. The button flashes as if pressed, but nothing happens. Not sure if related to the v90 update?

**Comment by Rem0o** [comment]
@Mushin  this has nothing to do with this issue.

**Comment by Mushin** [comment]
> @Mushin this has nothing to do with this issue.

Thanks - I did a clean install and it fixed the graph edit issue.

**Comment by pgarasz** [comment]
And I confirm that V90 fixed it. Case closed ;)
