### ISSUE TITLE
[BUG] AMD video card sensors showing up in librehardwaremonitor, not in Fan control

### ISSUE THREAD

**Issue by Klezkk** [Rem0o/FanControl.Releases#308]
As stated in the titled, every temp and fan sensor of my AMD 5700 video card disappeared. Everything's there when you use librehardwaremonitor 4.5.2. Outdated lib maybe?

**Comment by Artago** [comment]
My AMD 6700XT fans are also missing.

**Comment by Rem0o** [comment]
I'm using the latest build. 4.5.2 is way behind commit wise.

**Comment by Klezkk** [comment]
> I'm using the latest build. 4.5.2 is way behind commit wise.

I don't know, 4.5.2 is the latest available for download as standalone.

**Comment by Klezkk** [comment]
> I'm using the latest build. 4.5.2 is way behind commit wise.

I don't know, 4.5.2 is the latest available for download as standalone and the one I used to file the bug report

**Comment by Rem0o** [comment]
Do you mean this? https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.8.7

That's 0.8.7, 4.5.2 is the target .NET version.

It dates Feb 9, latest commit is like 10 days ago : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commits/master

Try the build from here, using the latest version available: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/1082498225

That's the same FanControl is using to detect everything.

**Comment by whoozy82** [comment]
I switched from a RX 480 to a RX 6600 XT. The sensors and fans did show up in FanSpeed with the old card, but not with the new one.

**Comment by Klezkk** [comment]
> 
> 
> Do you mean this? https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases/tag/v0.8.7
> 
> That's 0.8.7, 4.5.2 is the target .NET version.
> 
> It dates Feb 9, latest commit is like 10 days ago : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commits/master
> 
> Try the build from here, using the latest version available: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/1082498225
> 
> That's the same FanControl is using to detect everything. Pretty sure it will fail to detect your card the same way. Support was lost along the way and nobody attempted to fixed it yet.

Hey, here's the topic on librehardwaremonitor. It was a problem in their code. Don't know if its lib side or wrapper side.
LINK: [https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/516](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/516)

**Comment by Klezkk** [comment]
Oh, and by the way: thanks again for this awesome app! (donor here)

**Comment by Rem0o** [comment]
@Klezkk  no new commit yet, will wait for the repository to be updated.

**Comment by Klezkk** [comment]
> 
> 
> @Klezkk no new commit yet, will wait for the repository to be updated.

They just posted the commits!

**Comment by Rem0o** [comment]
Still a PR: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/518/commits

@Klezkk

**Comment by whoozy82** [comment]
Does CPUID HWMonitor use the same lib? The data is also missing there, but did work before with older card ...

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V91

**Comment by Klezkk** [comment]
Works perfectly!

**Comment by whoozy82** [comment]
Just updated to V91 and works like a charm. Thanks a lot!
