### ISSUE TITLE
Missing PWM Fan (MSI X570 Unify) V89

### ISSUE THREAD

**Issue by Bondarz** [Rem0o/FanControl.Releases#309]
Hello,

thanks for the tool! I use V89

I have a MSI X570 Unify, BIOS 7C35vAA, WIn 10, 6700 XT, Ryzen 5900X

2x FRONT fan, PWM, Noctua NF-A14
1x CPU cooler: NH-D15S with one fan, PWM
1x MSI chipset fan
1x TOP fan, DC, Fractal Dynamic X2
1x BACK fan, PWM, Noctua NF-F12
1x fan in Seasonic Focus power supply unit

Apparently FanControl does not recognise a  NF-A14 PWM fan
I connected the two Noctua NF-A14s in the front to two ports each. Both can be controlled via UEFI. One is missing in FanControl. When I look at HWMonitor, one of the fans is displayed under NUC126.

Also not adjustable: AMD GPU fan (Sapphire 6700 XT) and PSU fan of my Seasonic Focus.

Thanks

Log: https://hastebin.com/ofomufanaz.yam

![2021-08-03 18_42_02-Fan Control V89 (userConfig json)](https://user-images.githubusercontent.com/19914015/128079329-7939bcf6-b590-4e80-8d72-e25cc2d5446e.png)
![2021-08-03 19_02_33-Window](https://user-images.githubusercontent.com/19914015/128079300-eb24db88-9779-4eaf-b067-99e0f4936171.png)
![2021-08-03 22_15_34-E7C35v2 1 pdf](https://user-images.githubusercontent.com/19914015/128080153-9bc597b8-2f97-484e-95d1-581f8baccdaa.png)

**Comment by Rem0o** [comment]
NUC126 is a special MSI microcontroller, aka not standard and probably needs a special driver implementation to be able to read it, which I have no idea where/how to find.

Also, from the README.

_I am not the main developer for the driver portion of this software. Any issue regarding hardware compatibility should be submitted to LibreHardwareMonitor's repository._
