### ISSUE TITLE
Bitdefender flags as Malicius

### ISSUE THREAD

**Issue by wall03** [Rem0o/FanControl.Releases#31]
After installing, Bitdefender flagged this program and put the zip in quarentine.

![image](https://user-images.githubusercontent.com/65470133/92278614-9db2de00-eec3-11ea-82d9-872176ced6c2.png)

**Comment by Rem0o** [comment]
Just downloaded it, and it is not flagging it on my computer. Might be because it originates from it? 
![image](https://user-images.githubusercontent.com/14118956/92310831-f6e04780-ef7f-11ea-9f29-2fc121f5ec60.png)

**Comment by sdato001** [comment]
I am getting the same behavior with Bitdefender. For me the problem started after updating to FanControl version 48.
![FanControl_1](https://user-images.githubusercontent.com/5055975/92655923-61122880-f2af-11ea-8ef7-6f77bd9e181f.JPG)
![FanControl_2](https://user-images.githubusercontent.com/5055975/92655925-62435580-f2af-11ea-9424-546debfddeeb.JPG)

**Comment by Korkman** [comment]
"Gen" as in "generic" prefixed virus detection points to a heuristic treating anything uncommon with functions close to hardware as "suspicious". The solution is to promote FanControl. When it's popular enough, this should stop. For peace of mind, throw the release file into virustotal before installing to reassure it is not really infected in any way. V53 is undetected:
![image](https://user-images.githubusercontent.com/3186931/97113610-e6c92680-16eb-11eb-89a4-6894b30ba0f3.png)
