### ISSUE TITLE
FanControl past version 63 wont load on my PC with Windows 7

### ISSUE THREAD

**Issue by EmoTheKid** [Rem0o/FanControl.Releases#310]
Version 63 and older work on my PC with Windows 7 [Ultimate], 64 and onward show nothing though.
Newest version worked on Windows 10 on the same PC though.
Just wanted to let you know.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/6938646/log.txt)

**Comment by Rem0o** [comment]
From the README: 

Q: Does it run on my OS?
A: If your OS is Windows 10, yes.

Using Windows 10 API stuff for the UI.
