### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by BusyBusinessCat** [Rem0o/FanControl.Releases#311]
Hello, 

Using the last avaiable version, I get some rendering issue for some modal views, making it unusable so I have to shut down the program and launch it again (and be fast to edit a curse because the modal is corrupted a few moment after it shows up).

From my case, same issue can be observed in the drop down menu where you choose a temperature sensor (but it is not as annoying as the graph curve one because you can get out easily :) )

Here is an example with the graph curve editor.

![image](https://user-images.githubusercontent.com/3975610/128637716-2b56e8da-569d-4f81-943d-408e4b6e082f.png)

I haven't found any previous similar issue so I hope I'm not reopening something old.

Thanks for your work.

**Comment by Rem0o** [comment]
Windows version? Any custom theme or something similar?

**Comment by BusyBusinessCat** [comment]
New FanControl install (never user before on that computer).

Windows 10 20H2

**Comment by Rem0o** [comment]
What's your GPU situation? Driver up to date?

**Comment by BusyBusinessCat** [comment]
Yep.  ADM Driver 21.7.2 on an RX6800XT

**Comment by Rem0o** [comment]
Are you through any remote desktop software? Otherwise I have no clue.

**Comment by BusyBusinessCat** [comment]
Got an update of FanControl yesterday -> no more problem now (version 90).
