### ISSUE TITLE
Question about "Extreme Quiet mode" on ASUS Fan Expert

### ISSUE THREAD

**Issue by Oyami-Srk** [Rem0o/FanControl.Releases#312]
When I enabled "Extreme Quiet Mode" switch on my ASUS Fan Expert, It somehow magically gives my 1000rpm-3000rpm fans capability to be running under 1000rpm or stopped and VERY SILENT! 

But with that mode enabled, I cannot using FanControl to set my fans at 3000rpm, 100% only set to 1051rpm which is about 40% power of the fans. 

Everything is normal with that feature turning off and FanControl could set 1000rpm-3000rpm, but I really want to keep quiet by stop those powerful fans in low temp cond.

Is that ASUS feature magical or some "motherboard secret recipe"?

**Comment by Rem0o** [comment]
Seems to be a stupid Asus trick.  Fans are controlled with an 8 bit value, so 255 is max and 0 is well, 0.   This is what FanControl uses.  Asus probably has an other layer in between that value and the actual PWM/voltage output which changes the exposed range.

**Comment by Oyami-Srk** [comment]
> Seems to be a stupid Asus trick. Fans are controlled with an 8 bit value, so 255 is max and 0 is well, 0. This is what FanControl uses. Asus probably has an other layer in between that value and the actual PWM/voltage output which changes the exposed range.

Allllright, Thanks for the answer. Hope that one day all the hidden tricks will be documented and we can control everything by ourself... (haha, no possible)

**Comment by Xanardi** [comment]
I measured the voltage of the fan connected to the X570-F for ASUS Extreme Quiet.
In my case, it was measured as about 7.5V.

I think this is achieved by a hybrid of PWM control and voltage control.

Therefore, I think it is only when Extreme Quiet is enabled that the fan can be stopped from Fan Xpert.

I am not interested in too low RPM,
but I would like to have a function to stop the fan. :)
