### ISSUE TITLE
The app starts with Windows but has no effect on fans

### ISSUE THREAD

**Issue by Ahplla** [Rem0o/FanControl.Releases#313]
![image](https://user-images.githubusercontent.com/16189267/128717087-d6bcd379-1f9f-48af-829a-6ba609c9e73e.png)

The app starts with Windows but has no effect on fans.

It doesn't work unless I open the program and toggle the switch from on to off and on again.

**Comment by Rem0o** [comment]
That means something else probably overrides it after FanControl is loaded.

**Comment by Ahplla** [comment]
> That means something else probably overrides it after FanControl is loaded.

I set the delay from 30 seconds to 2 minutes it didn't work, I changed it to no delay it didn't work either. It only works by toggling the switch on/off/on or closing and reopening the app.

**Comment by Ahplla** [comment]
My old Gigabyte motherboard had the fans set to work at maximum. I left it default and that solved it, now Fancontrol can start controlling the fans automatically.

**Comment by Rem0o** [comment]
Every motherboard has its own quirk 😅
