### ISSUE TITLE
Errors after V90 Update

### ISSUE THREAD

**Issue by Maveric0623** [Rem0o/FanControl.Releases#314]
After updating to V90, I receive errors when launching FanControl:

![image](https://user-images.githubusercontent.com/72415238/128798172-86925d9b-cf3c-4e45-8eaf-fc6326dbdcbe.png)

Any suggestions to resolve these errors?

**Comment by Rem0o** [comment]
Motherboard?
Is it a one-time thing or all the time?
If you install an other copy on the side clean, is your stuff still detected?

**Comment by Maveric0623** [comment]
> Motherboard? ASUS ROG STRIX B550-I GAMING
> Is it a one-time thing or all the time? Everytime FanControl is launched (starts with Windows) and when it is refreshed when prompted.
> If you install an other copy on the side clean, is your stuff still detected? I don't quite understand the question clearly. Can you restate it? I have not tried to reinstall FanControl. Thanks.

**Comment by Rem0o** [comment]
"Install" the program over to an new folder, without all the json config files and the CACHE file.

**Comment by Maveric0623** [comment]
> "Install" the program over to an new folder, without all the json config files and the CACHE file.

I did this and it ran without errors with the "userConfig.json" file. I loaded my old config file and the errors returned. But after I closed the app and restarted, the old config file ran without errors. So far, so good. Thanks!
