### ISSUE TITLE
Bug: Self referencing loop detected while trying to actually target temperature

### ISSUE THREAD

**Issue by roman80k** [Rem0o/FanControl.Releases#319]
"Target" curve logic actually confused me: keep "Load" fan speed until "Idle" temperature reached, then keep "Idle" fan speed until "Load" temperature reached. This creates some sort of fan "roller-coasters", making them speed up and slow down in large magnitudes. Probably this scenario makes sense under certain conditions.

But I want my system to smoothly adjust fan speeds, so system temperature would not exceed some value. For example I want to keep system at 60 degrees no matter what resulting (in smooth transitions) fan speeds are.

I tried to make it this way: create "Sync" curve with corresponding attached control, then "Linear" curve which adds to current fan speed depending on current temperature, and then sum them both in "Mix" and point control to it. 

I can create this, and it works, but I can't save: log message says "Self referencing loop detected". Actually that is correct: in order to adjust current fan speed to target temperature you have to add or subtract something from current fan speed.

Question: how to fix this error? Or how can I reach my goal with your app in other ways?

**Comment by Rem0o** [comment]
Many, many ways to go about it:

First is to use a single target fan curve, no mixes, and lower the step up/step down values way down on your control ( like 2-3 % ). This will result in smoother transition instead of a fast ramp up/down. Also set something like a 3-5 seconds response time on the target fan curve to avoid changing fan speeds on small temp spikes.

Second and most obvious way, is to use a linear or graph fan curve and set a point at  (60 deg, 100% ). That way, the fan speed will adjust automatically based on temperature, and if 60 is hit, it will max out.

With a graph, you can also do something like this: 
![image](https://user-images.githubusercontent.com/14118956/130673016-1bde3ad4-b358-4178-a20c-42b8b25c23e5.png)

Which will spike to 100% if 60 is reached, otherwise will stay much lower.

**Comment by roman80k** [comment]
Thanks for fast reply, man.

I know all that... Probably I wasn't clear enough.

For example in winter 60 degrees for my system mean fans are at 35%. In summer at 60 degrees fans are already at something like 45%. In this scenario I have to adjust graph curve according to current conditions, which makes it inconvenient.

That is why in this scenario you have to add or subtract to/from current fan speed, not just to determine fan speed by system parts temperature with graph/linear curves.

You see my point? :)

**Comment by Rem0o** [comment]
`For example in winter 60 degrees for my system mean fans are at 35%. In summer at 60 degrees fans are already at something like 45%. In this scenario I have to adjust graph curve according to current conditions, which makes it inconvenient.`

That still doesn't make sense to me, a CPU doesn't care if its winter or summer, 60 deg is still 60 deg., It so happen that when the ambient temp is lower, it will be reached less often yes. But why is the fan speed different for the same temperature target in summer and winter? In Fan Control, temperature = % and that's it, you can then choose how fast a fan gets there but there is no more to it. A curve doesn't "add" to a fan's existing fan speed, it SETS its speed.

If you want to adjust your fan speeds based on ambient temp, try and use a sensor which values doesn't change much, like a spinning hard drive, and put it into a curve which does like 0 to 10% depending on the ambient temp, then use that as an offset to mix it with your regular linear curve.

Else, try and describe the exact inputs and outputs for different values of your desired behavior and how they interact. You may include time in your example.
like : 
Input 1 : X1, Input 2: Y1  => Output = Z1
Input 1 : X2, Input 2: Y2  => Output = Z2
( ... )

**Comment by roman80k** [comment]
`That still doesn't make sense to me, a CPU doesn't care if its winter or summer, 60 deg is still 60 deg.,`
Actually for this scenario I have GPU sitting on constant load 24h/day. And as I said I'd like it to auto adjust fan speed to keep at 60 degrees (in all indoor ambient temperatures).

`But why is the fan speed different for the same temperature target in summer and winter?`
Because circulating air temperature is different and therefore more/less air is needed to cool down to target temperature...

I'll try to play with another sensors like SSD or something like this as you suggested. But I suspect it will still be a not so precise approach. 

Would be nice for this scenario to either have a new type of curve, or have some sort of "pass-through" sensor which basically outputs current attached device fan speed, or for "Sync" curve to get out of self referencing loop...

Man, I don't see any other ways...

`Else, try and describe the exact inputs and outputs for different values`
Sorry, did not quite understand this.

**Comment by Rem0o** [comment]
@roman80k 
Explain exactly how your ideal fan curve would behave, what would be its inputs, and for said inputs, what would be the output (%).

If I understand correctly, you basically want a PID controller with 60 deg as the target.  Problems with PID is that they are super hard to configure properly and get them stable, especially with slow responding control systems, like PC cooling.

**Comment by sctanf** [comment]
I suggest using a temperature average sensor. It seems to be support sub degree values so it is much better for targeting a temperature with little variation. For example, using the average sensor with 10 seconds and setting your fan ramp as 30% at 58 deg to 100% at 62 deg.

**Comment by sctanf** [comment]
Proper PID control would be better, even if it had to be manually tuned.
Although if the sampling rate were faster, the oscillations could be reduced.
![Screenshot 2021-08-28 133724](https://user-images.githubusercontent.com/36978460/131227679-0aaf096c-97f5-47f1-b0a1-24787174a801.png)
