### ISSUE TITLE
Fan speeds visible but no controls

### ISSUE THREAD

**Issue by caddish** [Rem0o/FanControl.Releases#32]
Love this software but on one of my computer the fan speeds are visible but no controls.

The log refers two chip ITE IT8720F and LPC IT87XX which seems to be in LibreHardwareMonitor chip list .

Althouth for LPC IT87XX it says: IT87XX can enter only on port 0x2E
No idea what that means.

Any chance of making this work ?

**Comment by Rem0o** [comment]
Lookup the README. Any compatibility issue such as chip support is on LibreHardwareMonitor. I assume you got an Asus board? They love to use two chips, and support is hit and miss.

**Comment by caddish** [comment]
It's an older Gigabyte board H55N-USB3. I'll try to ask on LibreHardwareMonitor repo
