### ISSUE TITLE
Hotkeys for change profiles

### ISSUE THREAD

**Issue by Spuner** [Rem0o/FanControl.Releases#322]
Can you add the ability to assign profile changes to hotkeys?

**Comment by Spuner** [comment]
No plans to add this functionality?

**Comment by Rem0o** [comment]
Indirectly yes.

FanControl will accept a command line argument at runtime to change config. Any hotkey/binder will work then.

**Comment by Spuner** [comment]
To be honest, I do not quite understand what you mean? If not difficult, you can step by step - what should I do?

Thank you.

**Comment by Rem0o** [comment]
Was just an FYI to tell you the functionality will be possible via any keyboard software to swap profiles with a hotkey. 

Not ready for release yet, but will be coming soon in a future version.
Essentially, you'll be able to create shortcuts like this: 
![image](https://user-images.githubusercontent.com/14118956/199151532-8223bf53-4b8c-470f-934b-c23c1fa848d4.png)
which change the config.

Just use any keyboard software then to map these shortcuts to a key binding.

**Comment by Spuner** [comment]
`Not ready for release yet, but will be coming soon in a future version.`

Yes, I'd rather wait for the new version. Thanks.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/wiki/Hotkeys---Automate-config-changes-(V136-and-up)

**Comment by Spuner** [comment]
I do not want to open a new topic, so I will ask here: is it possible somehow to hide the icon on the system tray?

For example: if the first profile is applied - the icon is not shown in the system tray, and if the second profile is applied - the icon is shown.
