### ISSUE TITLE
AI Suite 3 Extreme Quiet Mode interference

### ISSUE THREAD

**Issue by Girofox** [Rem0o/FanControl.Releases#325]
Hello,

when I enable Fan Expert in AI Suite 3 with Extreme Quiet Mode the percentage range is off. Then a setting of 100 percent equals to 500 rpm and at around 50 percent CPU fan is spinning as low as 300 rpm.
Without Extreme Quiet Mode my CPU fan has a minimum of 500 rpm at around 28 percent but with Extreme Quiet Mode enabled 45 percent equals to a fan speed of under 300 rpm, with ability to even stop when going lower. It seems that AI Suite can reduce the fan voltage in PWM Mode to unlock the extra range from 200 to 500 rpm with ability to completely stop the fan.
![image](https://user-images.githubusercontent.com/43116061/132119162-d8b5a427-589a-4a23-a259-ac289da5214a.png)
![image](https://user-images.githubusercontent.com/43116061/132119217-bd217e6a-b79d-4bb8-b5d1-8da19c07959b.png)

**Comment by Rem0o** [comment]
FanControl isn't expected to play along other Fan Control software, especially ones from manufacturers like Asus, which clearly plays the the range available.
