### ISSUE TITLE
Split-second system freeze on start-up

### ISSUE THREAD

**Issue by mattrhcarlin** [Rem0o/FanControl.Releases#326]
When I start my PC with FanControl configured to auto-start, my system freezes for a split-second when the software initialises. This doesn't seem to cause additional problems while my PC is running from what I can tell, so I'm not sure if it's an expected/unavoidable phenomenon. There are no errors in Event Viewer indicting any problems either.

I'm using a Ryzen 5800X with Aorus Elite X570 motherboard.

I'm hesitant to mess with drivers and BIOS versions because the freeze is specifically caused by FanControl running. If it can't be fixed (or is expected behaviour), then I'm happy to accept that and ignore it.

Thanks.

**Comment by Rem0o** [comment]
Could be many things. In the background, the driver queries a bunch of stuff at startup which might block IO, like WMI, spinning hard drives and so on.

**Comment by Adiker** [comment]
Can confirm this, also Ryzen with B350 board. I'm on Win11 though
