### ISSUE TITLE
The following sensors are missing and could not be restored

### ISSUE THREAD

**Issue by neilangierof** [Rem0o/FanControl.Releases#33]
Every now and then, I realise that the fan speeds are not increasing or decreasing as per the curve I have configured. So I open up the program and get this error message. Pretty much every sensor comes up on the list. If it helps, I have a Gigabyte z370 Gaming 7. This only started happening after upgrading to v48. Reinstalling the previous versions does not seem to help.

**Comment by Rem0o** [comment]
That means for some reason the program could not read your sensors at all at startup. Do you have any other program that may interact with it? Rivatuner or something like that?

**Comment by neilangierof** [comment]
Yes I use Rivatuner Statistics Server. How can I prevent any more problems in future?

Sent from my iPhone

On 12 Sep 2020, at 11:06 PM, Rem0o <notifications@github.com> wrote:

﻿

That means for some reason the program could not read your sensors at all at startup. Do you have any other program that may interact with it? Rivatuner or something like that?

**Comment by Rem0o** [comment]
I've had a few people mention that Rivatuner prevents LibreHardwareMonitor to access the sensors and such. I'm affraid I don't have a fix for that.

**Comment by neilangierof** [comment]
That's ok. Your program is an amazing piece of work and I will continue to use it for as long as I can! I reinstalled it from scratch to see if the problems are fixed.
