### ISSUE TITLE
Controlling fan speed of navi gpus like 5700XT?

### ISSUE THREAD

**Issue by Piotrburz** [Rem0o/FanControl.Releases#333]
It seems that FanControl properly recognize the GPU fan controller and speed, but the GPU won't listen to the fancontrol custom graphs. Is it WAD? I understand there's fan control in adrenaline software, but it would be nice to also control it from your program.

**Comment by Rem0o** [comment]
Would be lovely, but unfortunately, there is no driver/api out there AFAIK that is publicly available to integrate into 3rd party programs like this one.

There is some AMD card support in here https://github.com/LibreHardwareMonitor/LibreHardwareMonitor, which is what I'm using. If it ever gets support for NAVI, FanControl will get it. Feel free to contribute.
