### ISSUE TITLE
The program cannot be opened after it is closed

### ISSUE THREAD

**Issue by 1073303** [Rem0o/FanControl.Releases#334]
If use upper right corner [X] of the browser to close the program, and it will enable to execute again.(even execute FanControl.exe is still the same) Only use the option Exit which in the menu can close the program browser normally and open it successfully in the next time.

**Comment by Rem0o** [comment]
It's a background app, look in the application tray.

**Comment by 1073303** [comment]
I know it still running in the background, but can't open the control browser if use [X] to close the browser.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/133460960-d0c83c87-b0e0-49eb-833b-dbf9d31e4835.png)
