### ISSUE TITLE
Set CPU Fan Curve not applying correctly.

### ISSUE THREAD

**Issue by Shadow091995** [Rem0o/FanControl.Releases#335]
Hello,

since the last update (at least I think it happened with it) the fan curve of my CPU is around 20-50% lower than it should be, still somewhat using the curve to scale up as soon as the temperatures rise. It also fails to hit the 100% mark on high temperatures and instead only goes up to 80%.

![Screenshot_6](https://user-images.githubusercontent.com/1573607/133346934-a8080a9b-214c-4ac4-9493-001ee5f0d29a.png)
(I know that the curve is not active at the moment, because I created a new one to prevent my CPU from getting too warm, but a totally new curve behaves the same way as seen on there)
The problem only exists for my CPU though. The other fans and GPU work perfectly fine.

(Ryzen 1800X on Asus Prime B350 Plus)

**Comment by Shadow091995** [comment]
The thing is, it worked perfectly fine until a few days ago and I haven't changed anything about the BIOS settings or anything other than updating FanControl. 
It's not just that it can't go to 0% it also can't hit 100% anymore. It basically always stays 20-30% under the set fan curve, but only for the CPU.

**Comment by Rem0o** [comment]
Well last update was only UI stuff (assisted setup), didn't change anything to do with the fan control mechanic itself.  Can you expend the control card of your CPU control and show a screenshot? Also a screenshot of the FanCurve you are using.

Also, if you put manual mode for your CPU (three dot menu => manual). Does the fan respond when you use the slider?

**Comment by Shadow091995** [comment]
If I control it manually or choose any value on a Flat curve it works just fine, but a Graph curve seems to not work correctly. 
CPU Control Card: 
![Screenshot_6](https://user-images.githubusercontent.com/1573607/133464563-723eddcc-bd05-4d27-8a69-eb6cd090fdc1.png) 
Fan Curve: 
![Screenshot_7](https://user-images.githubusercontent.com/1573607/133464651-f88c5bc0-c767-4ec1-b466-80a80edd4faa.png)

**Comment by Rem0o** [comment]
You'll have to be more precise on "acting out".  

Like, for a given situation, what's the temp, the fan curve target (% on the fan curve card), and the control %, ideally with a screenshot of the behavior with everything mentioned on screen.

**Comment by Shadow091995** [comment]
I hope this helps:
https://user-images.githubusercontent.com/1573607/133469030-f2f10814-6c93-4401-a932-31a87b647997.mp4

The thing is whenever there seems to be a steep incline it the control point doesn't stick to the specified curve anymore and thus it doesn't control the fan correctly anymore.

**Comment by Rem0o** [comment]
Thanks, was able to reproduce, will fix:
![image](https://user-images.githubusercontent.com/14118956/133476275-dfa2df92-0ce9-4c46-b96e-c5ea4ce1a6bb.png)

**Comment by Shadow091995** [comment]
That seems to do it for now. Thanks!

**Comment by Rem0o** [comment]
Good, the real issue will be fixed next release, closing.

**Comment by Rem0o** [comment]
Fixed in V93
