### ISSUE TITLE
Fans stopping and starting, not using correct speed

### ISSUE THREAD

**Issue by Schoof-T** [Rem0o/FanControl.Releases#336]
Hello

First all, thank you for this amazing application. It is seriously wonderful!

For the first couple of weeks the application was working correctly, but as of today I'm suddenly having the issue that my fans are not using the correct speeds. I also received an update notification today, which I installed, after which it asked me to match the fans and speed sensors automatically, which I did. But this seems to be unrelated because I removed the matching again, and manually redid them, causing the same issue.

This is the graph I'm using
![graph](https://user-images.githubusercontent.com/2319986/133429336-deb0fa0a-0697-47c4-ae24-6b7ea94377b4.png)

And this is the result I'm sometimes getting
![Screenshot 2021-09-15 105743](https://user-images.githubusercontent.com/2319986/133429350-27e65817-5e07-4abc-96d2-adc5117f0241.png)

As you can see, Front Middle, Front bottom and Back just completely stopped and Front Top is still spinning correctly. While they are all using the same Graph Curve.

After a couple of minutes the fans will suddenly start spinning again to the correct speed and then stop again after a couple of minutes.

Any idea what's going on here?

Thanks!

Schoof

**Comment by Schoof-T** [comment]
I reverted back to the previous version (V91) and I no longer seem to have the issue, could be something in the release?

**Comment by Rem0o** [comment]
What's the start % of your controls?

**Comment by Schoof-T** [comment]
It's at 6%
![image](https://user-images.githubusercontent.com/2319986/133487326-f80132e6-af0b-41fc-b3fd-97cc399c8cf0.png)

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/133488601-e5d5984a-3241-4bb5-add3-72badef7d339.png)

Let that run and report back the start %.

**Comment by Schoof-T** [comment]
It's very strange, every time to I run that it I get a different %. Once it was 0, then 27, then 50... It settles on this now:
![image](https://user-images.githubusercontent.com/2319986/133489863-ef2f932a-ebd1-4bca-af22-e72d78fcdbe9.png)

**Comment by Rem0o** [comment]
That's possible. Each fan is a bit different, also the tool is not perfect, it's an estimation.
