### ISSUE TITLE
Insufficient debug information

### ISSUE THREAD

**Issue by qreeves** [Rem0o/FanControl.Releases#337]
While trying to get Plugins going such as HWiNFO and GPU-Z, I have noticed a severe lack of debugging information provided in the log (Copy log to clipboard) when these plugins somehow fail. In the case of HWiNFO, I consistently got issues retrieving sensor information, and in the case of GPU-Z, it fails to load at all and I have no idea why. More information is needed from FanControl to help debug issues like these.

**Comment by Rem0o** [comment]
Well, "Copy log to clipboard" is basically the sensor detection report from LHM, so I guess the name of the button doesn't reflect properly what it does. 

However, any exception in the app, including any plugin should be cached inside log.txt.  Is it the case?

**Comment by qreeves** [comment]
Ah yes, I've just done a fresh install on a new computer and the file association icons all look the same so I didn't immediately notice the log file. Thanks. It does provide the plugin exception information, but even when everything is working there I still get "failed to find sensor" (even for builtin ones) followed by "do you want to refresh?" nine times out of ten when I start the program, and there's no debugging information for sensor enumeration failures.

**Comment by Rem0o** [comment]
That's with start with Windows enabled right?  That's a recurring issue. If started too soon after login, the driver sees nothing. Can't really raise an exception, as there is no "reason" to report, it just sees nothing, and I have not figured out what needs to be waited for.

**Comment by qreeves** [comment]
It happens even after the system has been up a while (I've spent all night trying to debug issues, so I've been constantly closing and re-opening the program). I haven't been able to figure out what's going on. Most of the time it resolves itself after a few attempts to click "OK" to both dialog boxes, but how long that takes seems almost random.

**Comment by Rem0o** [comment]
Make sure the app is ran as admin all these times. Also woken from sleep is equivalent to a fresh startup for the program, same problem might occur there.

**Comment by qreeves** [comment]
Yes, it always runs as administrator. I'll keep an eye out for further issues and try to get log output. Thanks for your help, and thanks for assisting the developer of the GPU-Z shared memory plugin.
