### ISSUE TITLE
Feature request - minimize to tray

### ISSUE THREAD

**Issue by PaFcio** [Rem0o/FanControl.Releases#338]
Hi,

I might be stupid but could not find this option anywhere and I assume it should exist since there is tray icon already.

So, can minimize to tray option be added? :D

Thanks,
Paul

**Comment by Rem0o** [comment]
Just press the "X", it doesn't exit the app, just shuts down the window.

**Comment by PaFcio** [comment]
> Just press the "X", it doesn't exit the app, just shuts down the window.

I was pretty sure that I have tried it and it was closing the app. Seems I'm stupid as predicted :D

Thanks! Closing the issue as it's not an issue :P
