### ISSUE TITLE
Feature Request Autosave Configuration every x seconds

### ISSUE THREAD

**Issue by pthoelken** [Rem0o/FanControl.Releases#340]
Is there a way to implement a option to setup auto save the configuration every x (to set by the user) seconds?

**Comment by Rem0o** [comment]
Why?

**Comment by pthoelken** [comment]
Because if you don't know that you have to save the configuration manually and close the app or restart the pc... I think it's not a bad idea and when the code is open source I will do a PR.

**Comment by Rem0o** [comment]
Won't do.
