### ISSUE TITLE
Feature Request Support Nvidia GPU in TCC mode

### ISSUE THREAD

**Issue by Ziffy2905** [Rem0o/FanControl.Releases#341]
Are you able to list Nvidia cards set to TCC mode so they can be used as a temperature source?
You should be able to use this NvAPIWrapper call GetTCCPhysicalGPUs() to get a list.

**Comment by Rem0o** [comment]
Didn't know about TCC, will take a look.

**Comment by Ziffy2905** [comment]
Thanks.  I'm happy to be a tester if you need someone.

**Comment by BacklitCat** [comment]
The same needs, I can also help test, looking forward to the update, thanks !!!

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/157706196-6881418e-4ac2-488f-925d-0165ceeebd64.png)

Already got the tcc in there.

**Comment by BacklitCat** [comment]
Thanks for your reply! But it doesn't work:

```
2022/3/11 9:28:35: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   在 NvAPIWrapper.Native.GPUApi.EnumPhysicalGPUs()
   在 NvAPIWrapper.GPU.PhysicalGPU.GetPhysicalGPUs()
   在 FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
2022/3/11 9:28:35: NVApi could not initialize.
2022/3/11 9:28:46: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   在 NvAPIWrapper.Native.GPUApi.EnumPhysicalGPUs()
   在 NvAPIWrapper.GPU.PhysicalGPU.GetPhysicalGPUs()
   在 FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
2022/3/11 9:28:46: NVApi could not initialize.
2022/3/11 9:28:46: Unhandled exception in FanControl v1.0.0.0
```

I write a python script to get the temperature and write it into a `.sensor` file, which works well.

![image](https://user-images.githubusercontent.com/34826904/157785555-37270568-85e6-403d-b15b-25843cac3b7c.png)

**Comment by Rem0o** [comment]
@BacklitCat from the look of it, it seems like if it can't find normal GPU (non tcc) it will throw and so it won't even try then to find the tcc gpus.

Will wrap both calls in a seperate try catch block and catch the NVAPI_NVIDIA_DEVICE_NOT_FOUND on both end.

**Comment by BacklitCat** [comment]
The version `106` works well, THANK YOU!!!
