### ISSUE TITLE
Fan still spinning at 0% speed

### ISSUE THREAD

**Issue by Mineplayerminer** [Rem0o/FanControl.Releases#342]
I want to report an issue with the PWM fans. I have set 0% on my PWM fans and the fans were still on 265RPM instead of 0RPM. Is there any way to completely turn off the fan?
![image](https://user-images.githubusercontent.com/82465758/134646562-699dc38d-a5f5-479b-9e39-13beea320969.png)
Also, the theme colors don't save after restarting the program.

**Comment by Rem0o** [comment]
For the 0%, your control reports 0%, that's a read value returned by your controller. So it reports 0, but actually spins the fan. Not much that I can do, since I'm sending the minimum command already.

As for colors, just tested, and it does save? Make sure to save your config after changing colors.

**Comment by sctanf** [comment]
Some fans will run with 0% pwm. 
Does your motherboard have a voltage mode?

**Comment by Mineplayerminer** [comment]
> Some fans will run with 0% pwm. Does your motherboard have a voltage mode?

Yes, but then my PWM fans cant be controlled precisely as they need constant 12V. The fans will turn of completely using the Stock fan control program as it cuts off the 12V supply when on 0% PWM. (Gigabyte SIV)

So basically the software needs to tell to the controller to turn off the fan header when 0% PWM duty cycle is reached to stop the fans spinning. Should be an easy fix.

**Comment by Rem0o** [comment]
Does that still happens with the latest release?

**Comment by Mineplayerminer** [comment]
Got it fixed eventually. Had to put my fans into the PWM mode. It also fixed my random freezes. Gigabyte can't make motherboards from now. Even puts the 12V fan header to LOW. (turns off)
