### ISSUE TITLE
cannot open the app

### ISSUE THREAD

**Issue by 1528riccardo** [Rem0o/FanControl.Releases#343]
hello, i m not able to open fan control , i only see the icon in the taskbar but if i click it nothing happens. My pc config is : msi z390gaming plus  i59600k  msi gtx1660 super ventus. Thank you

**Comment by Rem0o** [comment]
Try setting your display scaling to 100% and open the app, then revert back, some people reported weird issues with scaling.

**Comment by 1528riccardo** [comment]
Thanks for your help rem0o! Now it works 🙂
