### ISSUE TITLE
Feature request - sensor auto refresh

### ISSUE THREAD

**Issue by annqush** [Rem0o/FanControl.Releases#345]
If possible, add a sensor auto refresh when app is launching and loading config file.
Refresh few times with delays like 10 sec before spiting out that wall of missing sensors.

Btw. Great app.

**Comment by Rem0o** [comment]
it already does a delayed single auto refresh if it fails to detect anything.

**Comment by bgktmxg** [comment]
> 
> 
> it already does a delayed single auto refresh if it fails to detect anything.

Maybe me and @annqush are getting a different issue then?

Every time I start the app I get the wall of missing sensors. I have to refresh anywhere between 2-5 times before it loads properly.

Love the app btw, would really appreciate any feedback in getting this sorted.

Cheers

**Comment by bgktmxg** [comment]
> 
> 
> I'm planning to add granular control over which kind of sensor is detected. You could then exclude the corsair stuff.

Thanks! That sounds fantastic

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V96
