### ISSUE TITLE
Middle gpu fan won't start up

### ISSUE THREAD

**Issue by SassyBeard** [Rem0o/FanControl.Releases#346]
My middle gpu fan sits at 0% no matter what. I can only get it spinning again once I do the "detect fan start/stop%". The other two gpu fans work perfectly fine I'm not sure why Fan Control doesn't like the middle one.

**Comment by Rem0o** [comment]
set it to manual mode and slide it to 100%, won't start?

**Comment by SassyBeard** [comment]
Yeah that doesn't work either. The only thing I've found that makes it start is the "detect fan start/stop%". I've tried everything else, not sure why it's doing this.

**Comment by Rem0o** [comment]
Some guy had a similar issue -> #354
