### ISSUE TITLE
Loss of sensor recognition after driver update- ASUS X570

### ISSUE THREAD

**Issue by trekker6000** [Rem0o/FanControl.Releases#348]
I updated Asus HAL and Device SDK to 9/27/21 versions 1.1.36 and 1.00.39 respectively and FanControl no longer sees my case fan sensors.
![Screenshot 2021-10-04 093251](https://user-images.githubusercontent.com/91893509/135861458-8dd1c1d6-8d41-486f-8fd3-75e4d89e231f.jpg)
![Screenshot 2021-10-04 093740](https://user-images.githubusercontent.com/91893509/135861462-f62643af-6b7f-448d-997b-7d7c092576fa.jpg)

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/135883471-ce4ffc27-812f-48fa-8f84-087b37f56eb3.png)

**Comment by trekker6000** [comment]
My apologies for not including that on the initial post.  See pasted report below.



Motherboard

SMBios Version: 3.3

BIOS Vendor: American Megatrends Inc.
BIOS Version: 3405
BIOS Date: 02/01/2021
BIOS Size: 16 MB

System Manufacturer: System manufacturer
System Name: System Product Name
System Version: System Version
System Wakeup: PowerSwitch

Motherboard Manufacturer: ASUSTeK COMPUTER INC.
Motherboard Name: TUF GAMING X570-PLUS (WI-FI)
Motherboard Version: Rev X.0x
Motherboard Serial: 201278390702887

Chassis Type: Desktop
Chassis Manufacturer: Default string
Chassis Version: Default string
Chassis Serial: Default string
Chassis Asset Tag: Default string
Chassis SKU: Default string
Chassis Boot Up State: Safe
Chassis Power Supply State: Safe
Chassis Thermal State: Safe
Chassis Power Cords: 1
Chassis Lock Detected: No
Chassis Security Status: None

Processor Manufacturer: Advanced Micro Devices, Inc.
Processor Type: CentralProcessor
Processor Version: AMD Ryzen 7 3700X 8-Core Processor
Processor Serial: Unknown
Processor Socket Destignation: AM4
Processor Socket: AM4
Processor Version: AMD Ryzen 7 3700X 8-Core Processor
Processor Family: AmdZen
Processor Core Count: 8
Processor Core Enabled: 8
Processor Thread Count: 16
Processor External Clock: 100 Mhz
Processor Max Speed: 4400 Mhz
Processor Current Speed: 4050 Mhz

Cache [L1] Size: 512
Cache [L1] Associativity: 8Way

Cache [L2] Size: 4096
Cache [L2] Associativity: 8Way

Cache [L3] Size: 33280
Cache [L3] Associativity: 16Way

Memory Device [0] Manufacturer: Unknown
Memory Device [0] Part Number: Unknown
Memory Device [0] Device Locator: DIMM_A1
Memory Device [0] Bank Locator: BANK 0
Memory Device [0] Speed: 0Memory Device [0] Size: 
0 MB

Memory Device [1] Manufacturer: G-Skill
Memory Device [1] Part Number: F4-3200C16-16GVK
Memory Device [1] Device Locator: DIMM_A2
Memory Device [1] Bank Locator: BANK 1
Memory Device [1] Speed: 2666Memory Device [1] Size: 
16384 MB

Memory Device [2] Manufacturer: Unknown
Memory Device [2] Part Number: Unknown
Memory Device [2] Device Locator: DIMM_B1
Memory Device [2] Bank Locator: BANK 2
Memory Device [2] Speed: 0Memory Device [2] Size: 
0 MB

Memory Device [3] Manufacturer: G-Skill
Memory Device [3] Part Number: F4-3200C16-16GVK
Memory Device [3] Device Locator: DIMM_B2
Memory Device [3] Bank Locator: BANK 3
Memory Device [3] Speed: 2666Memory Device [3] Size: 
16384 MB

SMBios Table

 AAMDAOsLAAAAGgAAAQIA8AP/gJyLPwEAAAADDQUR//8QAEFtZXJpY2FuIE1lZ2F0
 cmVuZHMgSW5jLgAzNDA1ADAyLzAxLzIwMjEAAAEbAQABAgMECzPRAuPQ+80oFfAv
 dFEL9gYFBlN5c3RlbSBtYW51ZmFjdHVyZXIAU3lzdGVtIFByb2R1Y3QgTmFtZQBT
 eXN0ZW0gVmVyc2lvbgBTeXN0ZW0gU2VyaWFsIE51bWJlcgBTS1UAVG8gYmUgZmls
 bGVkIGJ5IE8uRS5NLgAAAg8CAAECAwQFCQYDAAoAQVNVU1RlSyBDT01QVVRFUiBJ
 TkMuAFRVRiBHQU1JTkcgWDU3MC1QTFVTIChXSS1GSSkAUmV2IFguMHgAMjAxMjc4
 MzkwNzAyODg3AERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAAADFgMAAQMC
 AwQDAwMDAAAAAAABAAMFRGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcARGVm
 YXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcAAAgJBAAB
 AAIPDVBTLzIgS2V5Ym9hcmQvTW91c2UAUFMvMiBLZXlib2FyZC9Nb3VzZQAACAkF
 AAEAAhIQVTMyRzFfNTYAVTMyRzFfNTYAAAgJBgABAAISEFUzMkcxXzM0AFUzMkcx
 XzM0AAAICQcAAQACEhBVMzJHMl9DMwBVMzJHMl9DMwAACAkIAAEAAv8cRFAARFAg
 cG9ydAAACAkJAAEAAv8cSERNSQBIRE1JIHBvcnQAAAgJCgABAAL//00uMihXSS1G
 SSkATS4yKFdJLUZJKQAACAkLAAEAAhIQVTMyRzJfMTIAVTMyRzJfMTIAAAgJDAAB
 AAILH0xBTgBMQU4AAAgJDQABAAL/HUFVRElPAEFVRElPAAAICQ4AASIAACBTQVRB
 NkdfMQAACAkPAAEiAAAgU0FUQTZHXzIAAAgJEAABIgAAIFNBVEE2R18zAAAICREA
 ASIAACBTQVRBNkdfNAAACAkSAAEiAAAgU0FUQTZHXzUAAAgJEwABIgAAIFNBVEE2
 R182AAAICRQAASIAACBTQVRBNkdfNwAACAkVAAEiAAAgU0FUQTZHXzgAAAgJFgAB
 IgAAIE0uMl8xKFNPQ0tFVDMpAAAICRcAASIAACBNLjJfMihTT0NLRVQzKQAACAkY
 AAESAAAQVVNCNzgAAAgJGQABEgAAEFVTQjkxMAAACAkaAAESAAAQVTMyRzFfMTIA
 AAgJGwAB/wAA/0NQVV9GQU4AAAgJHAAB/wAA/0NQVV9PUFQAAAgJHQAB/wAA/0NI
 QV9GQU4xAAAICR4AAf8AAP9DSEFfRkFOMgAACAkfAAH/AAD/Q0hBX0ZBTjMAAAgJ
 IAAB/wAA/0FJT19QVU1QAAAICSEAAf8AAP9QQ0hfRkFOAAAICSIAAQgAAAlDT00A
 AAgJIwABHwAAHUFBRlAAAAgJJAAB/wAA/1BBTkVMAAAICSUAAf8AAP9TUElfVFBN
 AAAICSYAAf8AAP9SR0JfSEVBREVSMQAACAknAAH/AAD/UkdCX0hFQURFUjIAAAgJ
 KAAB/wAA/0FERF9HRU4gMgAACgYpAIMBICAgVG8gQmUgRmlsbGVkIEJ5IE8uRS5N
 LgAACwUqAAhEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwBURVFVSUxBAERl
 ZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1
 bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAAAMBSsABERlZmF1bHQgc3RyaW5nAERl
 ZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAAAgFCwA
 AAAAAAAAAAAAAAAAAAAAAAAAIgstAAEBlQIAAANOQ1Q2Nzk4RC1SAAAoMi4ABQmh
 AAEBAAAAAAkRAA8AHgAAAAlyAAECAAAAAAkRABoDAAAAAAkRABkEAwAAAFRvIEJl
 IEZpbGxlZCBCeSBPLkUuTS4gMQBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uIDMAUFJP
 RFVDVF9MSU5FAFBST0RVQ1RfU0tVAAApCy8AAYMBAAAAECBPbmJvYXJkIElHRAAA
 LAkwAP//AQEAAAASFzEAAwICAAAAAAAAAIAAAACAAAAAgAAAEBcyAAMDAwAAAAgx
 AAQAAAAAAAAAAAAAABMfMwAAAAAA//8zADIAAgAAAAAAAAAAAAAAAAAAAAAAABMf
 NAAAAEAA//8LAjIAAgAAAAAAAAAAAAAAAAAAAAAAAAcbNQABgAEAAgACEAAQAAEG
 BQcAAgAAAAIAAEwxIC0gQ2FjaGUAAAcbNgABgQEAEAAQEAAQAAEGBQcAEAAAABAA
 AEwyIC0gQ2FjaGUAAAcbNwABggEAggCCEAAQAAEGBQgAAgCAAAIAgEwzIC0gQ2Fj
 aGUAAAQwOAABA2sCEA+HAP/7ixcDi2QAMBHSD0ExNQA2ADcABAUGCAgQ/ABrAAgA
 CAAQAEFNNABBZHZhbmNlZCBNaWNybyBEZXZpY2VzLCBJbmMuAEFNRCBSeXplbiA3
 IDM3MDBYIDgtQ29yZSBQcm9jZXNzb3IgICAgICAgICAgICAgAFVua25vd24AVW5r
 bm93bgBVbmtub3duAAASFzkAAwICAAAAAAAAAIAAAACAAAAAgAAAEVw6ADIAOQD/
 ////AAACAAECAgQAAAADBAAFAAAAAAAAAAAAAAAAAAIEAAYAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABESU1NX0ExAEJBTksg
 MABVbmtub3duAFVua25vd24AVW5rbm93bgBVbmtub3duAAASFzsAAwICAAAAAAAA
 AIAAAACAAAAAgAAAEVw8ADIAOwBAAEAAAEAJAAECGoBAagoDBAAFAQAAAABqCrAE
 sASwBAMIAAYEzQAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAABESU1NX0EyAEJBTksgMQBHLVNraWxsADAwMDAwMDAwAEY0LTMyMDBD
 MTYtMTZHVksAVW5rbm93bgAAFCM9AAAAAAD///8BPAA0AP///wAAAAAAAAAAAAAA
 AAAAAAAAABIXPgADAgIAAAAAAAAAgAAAAIAAAACAAAARXD8AMgA+AP////8AAAIA
 AQICBAAAAAMEAAUAAAAAAAAAAAAAAAAAAgQABgAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERJTU1fQjEAQkFOSyAyAFVua25v
 d24AVW5rbm93bgBVbmtub3duAFVua25vd24AABIXQAADAgIAAAAAAAAAgAAAAIAA
 AACAAAARXEEAMgBAAEAAQAAAQAkAAQIagEBqCgMEAAUBAAAAAGoKsASwBLAEAwgA
 BgTNAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AERJTU1fQjIAQkFOSyAzAEctU2tpbGwAMDAwMDAwMDAARjQtMzIwMEMxNi0xNkdW
 SwBVbmtub3duAAAUI0IAAAAAAP///wFBADQA////AAAAAAAAAAAAAAAAAAAAAAAA
 DRZDAAkAAAAAAAAAAAAAAAAAAAAAAWVufFVTfGlzbzg4NTktMQBmcnxGUnxpc284
 ODU5LTEAemh8VFd8dW5pY29kZQB6aHxDTnx1bmljb2RlAGphfEpQfHVuaWNvZGUA
 ZGV8REV8aXNvODg1OS0xAGVzfEVTfGlzbzg4NTktMQBydXxSVXxpc284ODU5LTUA
 a298S1J8dW5pY29kZQAACRFEAAGqDQQEAAAEAQAAABlQQ0lFWDE2XzEAAAkRRQAB
 qAoDBAEABAEAAAD/UENJRVgxNl8yAAAJEUYAAaYIAwMCAAQBAAAA/1BDSUVYMV8x
 AAAJEUcAAaYIAwMDAAQBAAAA/1BDSUVYMV8yAAB/BEgAAAA=


AMD CPU

Name: AMD Ryzen 7 3700X
Number of Cores: 16
Threads per Core: 1
Timer Frequency: 10 MHz
Time Stamp Counter: Invariant
Estimated Time Stamp Counter Frequency: 4050.02 MHz
Estimated Time Stamp Counter Frequency Error: 0.0486 Mhz
Time Stamp Counter Frequency: 4050 MHz

MSR Core #1

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFCDC486
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #2

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFE94839
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #3

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD00CD5
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #4

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD77B8C
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #5

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFFDF115
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #6

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD5D26E
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #7

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD23257
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #8

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD0580D
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #9

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFE20C03
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #10

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD0CC71
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #11

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD88DEA
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #12

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFDFC5C1
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #13

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFCD65E7
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #14

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFFAD15D
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #15

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFC5D562
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

MSR Core #16

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  0000FFFF  FFD12985
 C0010015  00000001  89000011
 C0010064  80000000  491208A2

Ryzen SMU

 PM table version: 0x00240903
 PM table supported: True
 PM table layout defined: True
 PM table size: 0x518
 PM table start address: 0xCA5E7000

 PM table dump:
  Idx    Offset   Value
 ------------------------
    0    0x000    0
    1    0x004    0
    2    0x008    0
    3    0x00C    0
    4    0x010    0
    5    0x014    0
    6    0x018    0
    7    0x01C    0
    8    0x020    0
    9    0x024    0
   10    0x028    0
   11    0x02C    0
   12    0x030    0
   13    0x034    0
   14    0x038    0
   15    0x03C    0
   16    0x040    0
   17    0x044    0
   18    0x048    0
   19    0x04C    0
   20    0x050    0
   21    0x054    0
   22    0x058    0
   23    0x05C    0
   24    0x060    0
   25    0x064    0
   26    0x068    0
   27    0x06C    0
   28    0x070    0
   29    0x074    0
   30    0x078    0
   31    0x07C    0
   32    0x080    0
   33    0x084    0
   34    0x088    0
   35    0x08C    0
   36    0x090    0
   37    0x094    0
   38    0x098    0
   39    0x09C    0
   40    0x0A0    0
   41    0x0A4    0
   42    0x0A8    0
   43    0x0AC    0
   44    0x0B0    0
   45    0x0B4    0
   46    0x0B8    0
   47    0x0BC    0
   48    0x0C0    0
   49    0x0C4    0
   50    0x0C8    0
   51    0x0CC    0
   52    0x0D0    0
   53    0x0D4    0
   54    0x0D8    0
   55    0x0DC    0
   56    0x0E0    0
   57    0x0E4    0
   58    0x0E8    0
   59    0x0EC    0
   60    0x0F0    0
   61    0x0F4    0
   62    0x0F8    0
   63    0x0FC    0
   64    0x100    0
   65    0x104    0
   66    0x108    0
   67    0x10C    0
   68    0x110    0
   69    0x114    0
   70    0x118    0
   71    0x11C    0
   72    0x120    0
   73    0x124    0
   74    0x128    0
   75    0x12C    0
   76    0x130    0
   77    0x134    0
   78    0x138    0
   79    0x13C    0
   80    0x140    0
   81    0x144    0
   82    0x148    0
   83    0x14C    0
   84    0x150    0
   85    0x154    0
   86    0x158    0
   87    0x15C    0
   88    0x160    0
   89    0x164    0
   90    0x168    0
   91    0x16C    0
   92    0x170    0
   93    0x174    0
   94    0x178    0
   95    0x17C    0
   96    0x180    0
   97    0x184    0
   98    0x188    0
   99    0x18C    0
  100    0x190    0
  101    0x194    0
  102    0x198    0
  103    0x19C    0
  104    0x1A0    0
  105    0x1A4    0
  106    0x1A8    0
  107    0x1AC    0
  108    0x1B0    0
  109    0x1B4    0
  110    0x1B8    0
  111    0x1BC    0
  112    0x1C0    0
  113    0x1C4    0
  114    0x1C8    0
  115    0x1CC    0
  116    0x1D0    0
  117    0x1D4    0
  118    0x1D8    0
  119    0x1DC    0
  120    0x1E0    0
  121    0x1E4    0
  122    0x1E8    0
  123    0x1EC    0
  124    0x1F0    0
  125    0x1F4    0
  126    0x1F8    0
  127    0x1FC    0
  128    0x200    0
  129    0x204    0
  130    0x208    0
  131    0x20C    0
  132    0x210    0
  133    0x214    0
  134    0x218    0
  135    0x21C    0
  136    0x220    0
  137    0x224    0
  138    0x228    0
  139    0x22C    0
  140    0x230    0
  141    0x234    0
  142    0x238    0
  143    0x23C    0
  144    0x240    0
  145    0x244    0
  146    0x248    0
  147    0x24C    0
  148    0x250    0
  149    0x254    0
  150    0x258    0
  151    0x25C    0
  152    0x260    0
  153    0x264    0
  154    0x268    0
  155    0x26C    0
  156    0x270    0
  157    0x274    0
  158    0x278    0
  159    0x27C    0
  160    0x280    0
  161    0x284    0
  162    0x288    0
  163    0x28C    0
  164    0x290    0
  165    0x294    0
  166    0x298    0
  167    0x29C    0
  168    0x2A0    0
  169    0x2A4    0
  170    0x2A8    0
  171    0x2AC    0
  172    0x2B0    0
  173    0x2B4    0
  174    0x2B8    0
  175    0x2BC    0
  176    0x2C0    0
  177    0x2C4    0
  178    0x2C8    0
  179    0x2CC    0
  180    0x2D0    0
  181    0x2D4    0
  182    0x2D8    0
  183    0x2DC    0
  184    0x2E0    0
  185    0x2E4    0
  186    0x2E8    0
  187    0x2EC    0
  188    0x2F0    0
  189    0x2F4    0
  190    0x2F8    0
  191    0x2FC    0
  192    0x300    0
  193    0x304    0
  194    0x308    0
  195    0x30C    0
  196    0x310    0
  197    0x314    0
  198    0x318    0
  199    0x31C    0
  200    0x320    0
  201    0x324    0
  202    0x328    0
  203    0x32C    0
  204    0x330    0
  205    0x334    0
  206    0x338    0
  207    0x33C    0
  208    0x340    0
  209    0x344    0
  210    0x348    0
  211    0x34C    0
  212    0x350    0
  213    0x354    0
  214    0x358    0
  215    0x35C    0
  216    0x360    0
  217    0x364    0
  218    0x368    0
  219    0x36C    0
  220    0x370    0
  221    0x374    0
  222    0x378    0
  223    0x37C    0
  224    0x380    0
  225    0x384    0
  226    0x388    0
  227    0x38C    0
  228    0x390    0
  229    0x394    0
  230    0x398    0
  231    0x39C    0
  232    0x3A0    0
  233    0x3A4    0
  234    0x3A8    0
  235    0x3AC    0
  236    0x3B0    0
  237    0x3B4    0
  238    0x3B8    0
  239    0x3BC    0
  240    0x3C0    0
  241    0x3C4    0
  242    0x3C8    0
  243    0x3CC    0
  244    0x3D0    0
  245    0x3D4    0
  246    0x3D8    0
  247    0x3DC    0
  248    0x3E0    0
  249    0x3E4    0
  250    0x3E8    0
  251    0x3EC    0
  252    0x3F0    0
  253    0x3F4    0
  254    0x3F8    0
  255    0x3FC    0
  256    0x400    0
  257    0x404    0
  258    0x408    0
  259    0x40C    0
  260    0x410    0
  261    0x414    0
  262    0x418    0
  263    0x41C    0
  264    0x420    0
  265    0x424    0
  266    0x428    0
  267    0x42C    0
  268    0x430    0
  269    0x434    0
  270    0x438    0
  271    0x43C    0
  272    0x440    0
  273    0x444    0
  274    0x448    0
  275    0x44C    0
  276    0x450    0
  277    0x454    0
  278    0x458    0
  279    0x45C    0
  280    0x460    0
  281    0x464    0
  282    0x468    0
  283    0x46C    0
  284    0x470    0
  285    0x474    0
  286    0x478    0
  287    0x47C    0
  288    0x480    0
  289    0x484    0
  290    0x488    0
  291    0x48C    0
  292    0x490    0
  293    0x494    0
  294    0x498    0
  295    0x49C    0
  296    0x4A0    0
  297    0x4A4    0
  298    0x4A8    0
  299    0x4AC    0
  300    0x4B0    0
  301    0x4B4    0
  302    0x4B8    0
  303    0x4BC    0
  304    0x4C0    0
  305    0x4C4    0
  306    0x4C8    0
  307    0x4CC    0
  308    0x4D0    0
  309    0x4D4    0
  310    0x4D8    0
  311    0x4DC    0
  312    0x4E0    0
  313    0x4E4    0
  314    0x4E8    0
  315    0x4EC    0
  316    0x4F0    0
  317    0x4F4    0
  318    0x4F8    0
  319    0x4FC    0
  320    0x500    0
  321    0x504    0
  322    0x508    0
  323    0x50C    0
  324    0x510    0
  325    0x514    0



LPC Nct677X

Chip Id: 0xD42B
Chip Revision: 0x2B
Base Address: 0x0290

Hardware Monitor Registers

        00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

 0000   03 9B 03 52 00 FF FF FF FF FF FF FF FF FF FF FF
 0010   03 9B 03 9B 03 3D 03 FF 40 FF FF FF FF FF FF FF
 0020   FF FF FF FF FF FF FF 1F 03 FF FF DA 00 00 00 00
 0030   00 00 00 00 00 00 00 00 00 50 4B FF FF FF FF FF
 0040   03 2E 07 FF FF 00 3F FF 2D FF FF 10 08 55 00 A3
 0050   15 FF FF FF FF FF FF FF C1 FF FF FF FF 01 00 01
 0060   0C 0C FF FF FF 01 00 FF FF FF FF FF FF FF FF FF
 0070   00 0A 00 1F 00 1F 00 1F 00 1F 00 3A 00 1F 00 FF
 00F0   00 00 00 00 00 00 00 FF 1C 40 21 1C 4F FF FF FF
 0100   1C 00 40 00 00 01 01 3C 00 9B FF 9B 00 FF FF FF
 0110   FF 19 23 2D 37 FF FF 8C AA C8 E6 32 00 01 01 00
 0120   FF 1E 4B 4B 69 FF FF 99 FF FF FF FF FF FF FF FF
 0130   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
 0140   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 01 FF
 0150   1F 80 00 4B 00 50 00 FF FF FF FF FF FF FF FF FF
 0200   1C 32 40 00 00 01 01 3C 00 52 00 52 00 FF FF FF
 0210   FF 28 32 3C 46 FF FF 8C AA C8 E6 3C 00 02 02 00
 0220   FF 14 41 46 64 FF FF 33 B2 FF FF FF FF FF FF FF
 0230   FF 00 FF FF 00 7D 01 FF 02 01 00 00 00 00 00 00
 0240   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 02 FF
 0250   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0260   FF FF FF FF FF FF 00 00 00 52 FF FF FF FF FF FF
 0300   1C 00 40 00 00 01 01 3C 00 9B FF 9B 00 FF FF FF
 0320   FF 1E 4B 4B 69 FF FF 99 FF FF FF FF FF FF FF FF
 0330   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
 0340   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 03 FF
 0360   FF FF FF FF FF FF 00 00 00 9B FF FF FF FF FF FF
 0400   00 00 00 00 00 00 00 00 00 28 80 3A 00 FF FF FF
 0410   FF FF FF FF FF FF FF FF FF 00 00 FF FF FF FF FF
 0420   FF FF FF 96 64 96 64 E1 96 00 FF FF FF FF FF FF
 0440   FF 20 00 00 FF 00 FF FF FF FF 00 00 00 00 04 FF
 0450   0B FB FF FF 00 00 00 FF FF 0E 13 33 09 01 FF FF
 0460   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0480   A6 7D D5 D1 7E 72 7D D4 CD 71 21 3F 81 7C 7F 72
 0490   1F 1F 1A 36 19 19 1F 29 00 1F 1F 1F 1F 3A 00 1F
 04B0   21 05 2C 18 2A 05 22 13 1B 11 FF 1F 00 FF 00 00
 04C0   04 F8 03 AE 03 E8 04 C3 05 FC 00 00 FF 1F 00 00
 04F0   28 40 3A 00 1F 3A F7 00 50 00 51 00 00 00 00 FF
 0500   FF FF 00 FF FF FF 00 FF FE FF FF FF FF 00 00 FF
 0550   D4 CD 80 FF 00 00 00 00 00 00 00 00 00 00 00 00
 0560   00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF
 0600   00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF
 0610   00 00 00 00 00 00 00 FF 1F FF FF FF FF FF FF FF
 0620   FF 01 02 00 00 FF FF FF FF FF FF FF FF FF FF 1F
 0630   21 05 2C 18 2A 05 22 13 1B 11 FF 1F FF 1F FF 1F
 0640   FF 1F FF 1F 02 02 02 02 02 02 FF 1F FF 1F 06 02
 0650   7F 7F 7F 7F 00 00 04 F8 03 AE 03 E8 04 C3 05 FC
 0660   00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0670   1A 00 36 80 19 80 19 80 1F 00 1F 80 FF FF FF FF
 0700   FF 85 02 10 00 00 00 00 00 00 00 00 00 00 00 00
 0710   00 00 00 00 00 00 00 00 00 F8 80 F8 80 F8 80 0F
 0720   00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
 0730   00 00 00 00 00 00 00 00 00 00 00 0E 0A 00 00 00
 0800   1C 00 40 00 00 01 01 3C 00 9B FF 9B 00 FF FF FF
 0820   FF 1E 4B 4B 69 FF FF 99 FF FF FF FF FF FF FF FF
 0830   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
 0840   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 08 FF
 0900   09 00 40 00 00 01 01 3C 00 3D FF 3D 00 FF FF FF
 0920   FF 37 3C 5D 64 FF FF 00 66 FF FF FF FF FF FF FF
 0930   FF 00 FF FF 00 7D 01 FF 02 FF FF FF FF FF FF 00
 0940   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 09 FF
 0960   FF FF FF FF FF FF 00 00 00 3D FF FF FF FF FF FF
 0A00   1C 00 40 00 00 01 01 3C 00 FF FF FF 00 FF FF FF
 0A10   FF 19 23 2D 37 FF FF 8C AA C8 E6 3C 00 03 03 00
 0A20   FF 00 64 64 64 FF FF FF FF FF FF FF FF FF FF FF
 0A30   FF 00 FF FF 00 64 01 FF 02 FF FF FF FF FF FF 00
 0A40   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 0A FF
 0A50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0A60   FF FF FF FF FF FF 00 00 00 FF FF FF FF FF FF FF
 0A70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B00   03 00 00 0A 0A 01 01 3C 00 FF FF 00 00 FF FF FF
 0B10   FF 19 23 2D 37 FF FF 8C AA C8 E6 3C 00 03 03 00
 0B20   FF 19 23 2D 37 FF FF 8C AA C8 E6 FF FF FF FF FF
 0B30   FF 00 FF FF 00 64 01 FF 00 FF FF FF FF FF FF 00
 0B50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B60   FF FF FF FF FF FF 11 00 00 FF FF FF FF FF FF FF
 0B70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C00   FF 00 00 00 3F 3F 3F 00 00 00 00 00 00 00 7F 7F
 0C10   7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 50 50 50 50 50 50
 0C20   4B 4B 4B 4B 4B 4B 03 04 05 06 07 02 00 00 00 28
 0C30   00 28 00 28 00 28 00 00 00 28 00 00 00 00 0A 00
 0C50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C60   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D60   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 8040   03 00 00 FF FF 00 3F FF 2D FF FF 10 08 55 80 5C
 80F0   00 00 00 00 00 00 00 FF 1C 40 21 1C 4F FF FF FF

**Comment by Rem0o** [comment]
And you got no cards at all? It still recognize your NCT6798D from the report.
