### ISSUE TITLE
FanControl window is flickering

### ISSUE THREAD

**Issue by HollyD9** [Rem0o/FanControl.Releases#352]
Hey

I've an issue with the fan controll window. if i start the program, the window of it is slightli flickering.
when i have more windows open, they are all flickering if im in "fan controll". if i leave the fc-window, then it's all good.

i've a 144hz monitor. is that the problem? gsync is enabled (but i testet it on and off) - nothing changed.

What can i do to stop this flickering?

Kind Regards, HollyD

**Comment by HollyD9** [comment]
Ooooh, thank you very much! 👯 :)
I didn't get the idea to look in the program settings in the nvidia panel.

It is working perfect 👯 :) Thank you again :)

**Comment by RSully** [comment]
Could we reopen this issue to see if it can be fixed by the app instead of using the workaround?

**Comment by thomaskunrath** [comment]
Can confirm, happening the same with a nvidia card.

**Comment by thomaskunrath** [comment]
@RSully do the steps Rem0o recommended, but instead of turning G-Sync off, just keep everything as it is, go to "Max frame rate" and set some value close to the refresh rate of the monitor. It worked here.

**Comment by RSully** [comment]
My point is I don't want to change any settings on my system to prevent this issue. No other apps seem to exhibit this, so it seems reasonable to reopen this issue and fix it in the app itself

**Comment by Rem0o** [comment]
That bug is embedded in the WPF framework, the one used to to build this app UI.  I can’t « fix » it from my end without changing framework. It’s one of those annoying thing, but for now you’ll have to use the workaround or just ignore it.

**Comment by RSully** [comment]
Got it. Is there an issue being tracked in the WPF framework we can follow?

**Comment by Rem0o** [comment]
https://github.com/dotnet/wpf/issues/2294

**Comment by polsrepo** [comment]
I fixed this using NVIDIA Control Panel:
Go to "Manage 3D settings" and then click on the "Program Settings" tab. There, in "1. Select a program to customiose:" click on "Add" and select your FanControl executable. Then, in "2. Specify the settings for this program:" set "Monitor Technology" to "Fixed Refresh". Restart FanControl and you shouldn't have the flickering issue any
<img width="554" alt="Screenshot 2023-09-03 163438" src="https://github.com/Rem0o/FanControl.Releases/assets/110729177/51e9ad48-9e4c-41ed-a0d2-c5c8ef443ce3">
more.
