### ISSUE TITLE
Tray Icon text cut off when sensor name is too long

### ISSUE THREAD

**Issue by pladux** [Rem0o/FanControl.Releases#359]
The tray icons text is cut off when the sensors name is too long. In my example the sensor is coming from hwinfo.

Actually I'm not interested in the sensors name at all, but in the current selected FanControl configuration.

![image](https://user-images.githubusercontent.com/19801768/137589613-c3e6f2c5-5c10-4368-8fb1-0fe7e35b87ab.png)

**Comment by Rem0o** [comment]
Text length is limited. I think I will refine it, haven't touched it since I originally made it. Putting the config first does make sense.
