### ISSUE TITLE
.exe shows in taskmanager, no gui

### ISSUE THREAD

**Issue by the-retag** [Rem0o/FanControl.Releases#360]
i've tried installing fancontrol (i think) according to instructions, but uppon starting fancontrol.exe no gui opens, but in taskmanager it can be seen running as a process (and not all the files it comes with can be deleted as windows tells me (with about half) that they are in use). i was hoping that someone can help or has the same issue, or tell me what additional info is needed. OS is 64 bit windows 7 on a GIGABYTE GA-880GM-UD2H with a phenom IIx4 965 cpu and gt 1030 , 8gig of ram and 100Gb+ of free ssd space. other programmes (although with installers) have worked propely, like kaspersky and malwarebytes (could they be the problem?). could be me being a bit of a noob btw, just as a warning
thanks

**Comment by Rem0o** [comment]
Windows 7 is not supported.
