### ISSUE TITLE
Missing sensors after wake from sleep

### ISSUE THREAD

**Issue by oraichu** [Rem0o/FanControl.Releases#365]
Hey. I recently started getting errors of all sensors missing after waking from sleep. Doesn't always happen, but most of the time.

Motherboard

SMBios Version: 3.1

BIOS Vendor: American Megatrends Inc.
BIOS Version: P4.40
BIOS Date: 26/11/2019
BIOS Size: 16 MB

System Manufacturer: To Be Filled By O.E.M.
System Name: To Be Filled By O.E.M.
System Version: To Be Filled By O.E.M.
System Wakeup: PciPme

Motherboard Manufacturer: ASRock
Motherboard Name: Z390 Phantom Gaming-ITX/ac
Motherboard Version: 
Motherboard Serial: M80-C5021600347

Chassis Type: Desktop
Chassis Manufacturer: To Be Filled By O.E.M.
Chassis Version: To Be Filled By O.E.M.
Chassis Serial: To Be Filled By O.E.M.
Chassis Asset Tag: To Be Filled By O.E.M.
Chassis SKU: To Be Filled By O.E.M.
Chassis Boot Up State: Safe
Chassis Power Supply State: Safe
Chassis Thermal State: Safe
Chassis Power Cords: 1
Chassis Lock Detected: No
Chassis Security Status: None

Processor Manufacturer: Intel(R) Corporation
Processor Type: CentralProcessor
Processor Version: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor Serial: To Be Filled By O.E.M.
Processor Socket Destignation: CPUSocket
Processor Socket: Lga1151
Processor Version: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor Family: IntelCoreI7
Processor Core Count: 8
Processor Core Enabled: 8
Processor Thread Count: 8
Processor External Clock: 100 Mhz
Processor Max Speed: 8300 Mhz
Processor Current Speed: 3600 Mhz

Cache [L1] Size: 512
Cache [L1] Associativity: 8Way

Cache [L2] Size: 2048
Cache [L2] Associativity: 4Way

Cache [L3] Size: 12288
Cache [L3] Associativity: 12Way

Memory Device [0] Manufacturer: Micron
Memory Device [0] Part Number: 18ADF2G72AZ-3G2E1
Memory Device [0] Device Locator: ChannelA-DIMM0
Memory Device [0] Bank Locator: BANK 0
Memory Device [0] Speed: 3200Memory Device [0] Size: 
16384 MB

Memory Device [1] Manufacturer: Micron
Memory Device [1] Part Number: 18ADF2G72AZ-3G2E1
Memory Device [1] Device Locator: ChannelB-DIMM0
Memory Device [1] Bank Locator: BANK 2
Memory Device [1] Speed: 3200Memory Device [1] Size: 
16384 MB

SMBios Table

 AAMBANkLAAAAGgAAAQIA8AP/gJiLPwEAAAADDQUN//8QAEFtZXJpY2FuIE1lZ2F0
 cmVuZHMgSW5jLgBQNC40MAAxMS8yNi8yMDE5AAABGwEAAQIDBHCFwtWPwgAAAAAA
 AAAAAAAHBQZUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBCeSBP
 LkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5F
 Lk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5N
 LgAAAg8CAAECAwQFCQYDAAoAQVNSb2NrAFozOTAgUGhhbnRvbSBHYW1pbmctSVRY
 L2FjACAgICAgICAgICAgICAgICAgICAgICAATTgwLUM1MDIxNjAwMzQ3ACAgICAg
 ICAgICAgICAgICAgICAgICAAICAgICAgICAgICAgICAgICAgICAgIAAAAxYDAAED
 AgMEAwMDAwAAAAAAAQADBVRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmls
 bGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAFRvIEJlIEZpbGxl
 ZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgAACREEAAGlDQQEEQAM
 AQAAAQBTbG90MQAACREFAAGlCgQDIQAMAQAAPABNMl8xAAAJEQYAAaUKBAMiAAwB
 AAACAE0yXzIAAAsFBwABVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgAAIBQIAAAAAAAA
 AAAAAAAAAAAAAAAAACgOCQABCaEAAQEAAAAATU9SRE9SAAAQFwoAAwMDAAAAAv7/
 AgAAAAAAAAAAAAAAESgLAAoA/v+AAEAAAEAJAAECGoAAgAwDBAUGAgAAAACADLAE
 sASwBENoYW5uZWxBLURJTU0wAEJBTksgMABNaWNyb24ANTcwMzAwMDAAOTg3NjU0
 MzIxMAAxOEFERjJHNzJBWi0zRzJFMSAgIAAAESgMAAoA/v+AAEAAAEAJAAECGoAA
 gAwDBAUGAgAAAACADLAEsASwBENoYW5uZWxCLURJTU0wAEJBTksgMgBNaWNyb24A
 NTYwMzAwMDAAOTg3NjU0MzIxMAAxOEFERjJHNzJBWi0zRzJFMSAgIAAAEx8NAAAA
 AAD///8BCgACAAAAAAAAAAAAAAAAAAAAAAAA3RoOAAMBAAcAQhAAAgAAAADKAAMA
 AQUAAABSZWZlcmVuY2UgQ29kZSAtIENQVQB1Q29kZSBWZXJzaW9uAFRYVCBBQ00g
 dmVyc2lvbgAA3RoPAAMBAAcAQhAAAgAMAAAKAAMEDAAIYwRSZWZlcmVuY2UgQ29k
 ZSAtIE1FAE1FQnggdmVyc2lvbgBNRSBGaXJtd2FyZSBWZXJzaW9uAENvbnN1bWVy
 IFNLVQAA3VkQAAwBAAcAQhAAAgP//////wQA////EAAFAP///xAABgD//////wcA
 AgAAAAAIAAkAAAAACQAKAAAAAAoAEwAAAAALAAcAAAAADAAGAAAAAA0ABwAAAABS
 ZWZlcmVuY2UgQ29kZSAtIENOTCBQQ0gAUENILUNSSUQgU3RhdHVzAERpc2FibGVk
 AFBDSC1DUklEIE9yaWdpbmFsIFZhbHVlAFBDSC1DUklEIE5ldyBWYWx1ZQBPUFJP
 TSAtIFJTVCAtIFJBSUQAQ05MIFBDSCBIIEEwIEhzaW8gVmVyc2lvbgBDTkwgUENI
 IEggQXggSHNpbyBWZXJzaW9uAENOTCBQQ0ggSCBCeCBIc2lvIFZlcnNpb24AQ05M
 IFBDSCBMUCBBeCBIc2lvIFZlcnNpb24AQ05MIFBDSCBMUCBCMCBIc2lvIFZlcnNp
 b24AQ05MIFBDSCBMUCBCeCBIc2lvIFZlcnNpb24AQ05MIFBDSCBMUCBEeCBIc2lv
 IFZlcnNpb24AAN02EQAHAQAHAEIQAAIAAAcBSAADAAcAQhAABAX//////wYAAAAA
 DQAHAAAAAA0ACAD//////1JlZmVyZW5jZSBDb2RlIC0gU0EgLSBTeXN0ZW0gQWdl
 bnQAUmVmZXJlbmNlIENvZGUgLSBNUkMAU0EgLSBQQ0llIFZlcnNpb24AU0EtQ1JJ
 RCBTdGF0dXMARGlzYWJsZWQAU0EtQ1JJRCBPcmlnaW5hbCBWYWx1ZQBTQS1DUklE
 IE5ldyBWYWx1ZQBPUFJPTSAtIFZCSU9TAADdDBIAAQEABAAAAABGU1AgQmluYXJ5
 IFZlcnNpb24AAAcTEwABgAEAAgACIAAgAAAEBQdMMSBDYWNoZQAABxMUAAGBAQAI
 AAggACAAAAUFBUwyIENhY2hlAAAHExUAAYIBADAAMCAAIAAABgUJTDMgQ2FjaGUA
 AAQwFgABA8YC7QYJAP/7678DiWQAbCAQDkEyEwAUABUABAUGCAgI7ADGAAgACAAI
 AENQVVNvY2tldABJbnRlbChSKSBDb3Jwb3JhdGlvbgBJbnRlbChSKSBDb3JlKFRN
 KSBpNy05NzAwSyBDUFUgQCAzLjYwR0h6AFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4A
 VG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAAAU
 IxcAAAAAAP///wALAA0AAQEBAAAAAAAAAAAAAAAAAAAAAAAAFCMYAAAAAAH///8B
 DAANAAECAQAAAAAAAAAAAAAAAAAAAAAAAIIUGQAkQU1UAAAAAAClrwLAAAAAAACD
 QBoANQAAAAwAAAAAAAoA+AAFowAAAAABAAAAAAAMAGMECAAAAAAA/gC8FQAAAAAA
 AAAAJgAAAHZQcm8AAAAAAAApCxsAAYEBAAAAAE9uYm9hcmQgLSBPdGhlcgAAKQsc
 AAGBAgAAAJBPbmJvYXJkIC0gT3RoZXIAACkLHQABgQMAAACgT25ib2FyZCAtIE90
 aGVyAAApCx4AAYEEAAAAok9uYm9hcmQgLSBPdGhlcgAAKQsfAAGFAQAAAKNPbmJv
 YXJkIC0gRXRoZXJuZXQAACkLIAABgQUAAACwT25ib2FyZCAtIE90aGVyAAApCyEA
 AYkBAAAAuE9uYm9hcmQgLSBTQVRBAAApCyIAAYEGAAAA+E9uYm9hcmQgLSBPdGhl
 cgAAKQsjAAGHAQAAAPtPbmJvYXJkIC0gU291bmQAACkLJAABgQcAAAD8T25ib2Fy
 ZCAtIE90aGVyAAApCyUAAYEIAAAA/U9uYm9hcmQgLSBPdGhlcgAAKQsmAAGFAgAA
 AP5PbmJvYXJkIC0gRXRoZXJuZXQAAN1ZJwAMAQAAAACmAAIA//////8DBP//////
 BQb//////wcI//////8JAAAAAAAACgD//////wsA//8AAAAMAP//////DQ4BBAMA
 AA8AAAcAAAAQAAACAA4ATGFuIFBoeSBWZXJzaW9uAFNlbnNvciBGaXJtd2FyZSBW
 ZXJzaW9uAERlYnVnIE1vZGUgU3RhdHVzAERpc2FibGVkAFBlcmZvcm1hbmNlIE1v
 ZGUgU3RhdHVzAERpc2FibGVkAERlYnVnIFVzZSBVU0IoRGlzYWJsZWQ6U2VyaWFs
 KQBEaXNhYmxlZABJQ0MgT3ZlcmNsb2NraW5nIFZlcnNpb24AVU5ESSBWZXJzaW9u
 AEVDIEZXIFZlcnNpb24AR09QIFZlcnNpb24AUm95YWwgUGFyayBWZXJzaW9uAEJQ
 MS40LjMuMF9SUDAxAFBsYXRmb3JtIFZlcnNpb24AQ2xpZW50IFNpbGljb24gVmVy
 c2lvbgAAiAYoAAAAAAAOCCkAAdsAACRNRUkAANtqKgABBAFFAgCQBgGFNiAAAAAE
 QAAAAAAAAAAAAEAC////////////////////////////////AwAAAIAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNRUkxAE1FSTIA
 TUVJMwBNRUk0AAB/BCsAAAA=

LPC Nct677X

Chip Id: 0xC803
Chip Revision: 0x3
Base Address: 0x0290

Hardware Monitor Registers

        00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

 0000   03 79 03 71 00 FF FF FF FF FF FF FF FF FF FF FF
 0010   03 88 03 4D 03 4D 03 4D 40 85 7E 97 A0 A1 85 00
 0020   48 D4 D8 D8 7E 85 85 2D FF FF FF DA 00 00 00 00
 0030   00 00 00 00 00 00 00 00 00 24 23 FF FF FF FF FF
 0040   03 3E 17 CF DF 00 3F FF 2D FF FF 10 08 55 00 A3
 0050   05 FF FF FF FF FF FF FF C1 FF FF FF FF 00 00 FF
 0060   30 AB FF FF FF 01 00 FF FF FF FF FF FF FF FF FF
 0070   00 0A 00 2D 00 3A 80 3A 80 16 80 16 80 FF FF FF
 00F0   00 00 00 00 00 00 00 00 00 00 00 0F DD FF FF FF
 0100   81 00 42 01 01 01 01 3C 00 79 FF 79 00 FF FF FF
 0110   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0120   FF 14 41 46 46 FF FF 33 B2 FF FF FF FF FF FF FF
 0130   FF 00 FF FF 00 64 00 CC 00 FF FF FF FF FF FF 00
 0140   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 01 FF
 0150   3A 80 00 23 00 24 00 FF FF FF FF FF FF FF FF FF
 0200   90 32 00 01 01 01 01 3C 00 71 00 6B 00 FF FF FF
 0210   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0220   FF 14 41 46 46 FF FF 33 B2 FF FF FF FF FF FF FF
 0230   FF 00 FF FF 00 64 00 CC 00 01 00 00 00 00 00 00
 0240   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 02 FF
 0250   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0260   FF FF FF FF FF FF 11 00 FF FF FF FF FF FF FF FF
 0300   90 00 00 01 01 01 01 3C 00 88 FF 71 00 FF FF FF
 0320   FF 14 41 46 46 FF FF 33 B2 FF FF FF FF FF FF FF
 0330   FF 00 FF FF 00 64 00 CC 00 FF FF FF FF FF FF 00
 0340   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 03 FF
 0360   FF FF FF FF FF FF 11 00 FF FF FF FF FF FF FF FF
 0400   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 0410   00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF FF
 0420   FF FF FF 96 64 96 64 E1 96 00 FF FF FF FF FF FF
 0440   FF FF 01 04 FF FF FF FF FF FF 00 00 00 00 04 FF
 0450   01 73 FF FF 00 00 00 FF FF 3E 13 31 09 00 FF FF
 0460   FF 01 00 00 00 00 00 00 FF FF FF FF FF FF FF FF
 0480   48 D4 D8 D8 7E 85 85 D9 00 85 7E 97 A0 A1 85 00
 0490   2D C1 16 19 0F 16 00 37 40 2D 3A 3A 16 16 1E 16
 04B0   FF 1F 2A 18 27 19 FF 1F FF 1F FF 1F 00 00 FF FF
 04C0   00 00 03 DA 04 24 00 00 00 00 00 00 FF FF FF FF
 04F0   3A 80 00 00 3A 00 00 00 00 00 00 00 00 00 00 FF
 0500   FF FF 00 00 00 06 00 FF 0F FF FF FF FF 00 00 FF
 0550   D9 00 00 FF 00 00 00 00 00 00 00 00 00 00 00 00
 0560   00 00 00 00 00 00 7F 3F 3F FF FF FF FF FF FF FF
 0600   00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF
 0610   00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF
 0620   FF 01 10 00 FF FF FF FF FF FF FF FF FF FF FF 1F
 0630   FF 1F 2A 18 27 19 FF 1F FF 1F FF 1F FF 1F FF 1F
 0640   FF 1F FF 1F 02 02 02 02 02 02 FF FF FF FF 06 FF
 0650   7F 7F 7F 7F 00 00 00 00 03 DA 04 24 00 00 00 00
 0660   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0670   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0700   FF 95 02 10 00 00 00 00 00 73 00 00 00 00 00 00
 0710   00 00 00 00 00 00 00 F1 E9 F8 80 F8 80 F8 80 01
 0720   3A 02 07 00 00 00 EF 27 00 EF 00 00 00 00 00 00
 0730   00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF
 0800   03 00 00 0A 0A 01 01 3C 00 4D FF 00 00 FF FF FF
 0820   FF 19 23 2D 37 FF FF 8C AA C8 E6 FF FF FF FF FF
 0830   FF 00 FF FF 00 3C 00 CC 00 FF FF FF FF FF FF 00
 0840   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 08 FF
 0900   03 00 00 0A 0A 01 01 3C 00 4D FF 00 00 FF FF FF
 0920   FF 19 23 2D 37 FF FF 8C AA C8 E6 FF FF FF FF FF
 0930   FF 00 FF FF 00 3C 00 CC 00 FF FF FF FF FF FF 00
 0940   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 09 FF
 0960   FF FF FF FF FF FF 00 00 FF FF FF FF FF FF FF FF
 0A00   03 00 00 0A 0A 01 01 3C 00 4D FF 00 00 FF FF FF
 0A10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0A20   FF 19 23 2D 37 FF FF 8C AA C8 E6 FF FF FF FF FF
 0A30   FF 00 FF FF 00 3C 00 CC 00 FF FF FF FF FF FF 00
 0A40   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 0A FF
 0A50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0A60   FF FF FF FF FF FF 00 00 FF FF FF FF FF FF FF FF
 0A70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B60   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0B70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C60   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0C70   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D50   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0D60   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0E30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 0F30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 8040   03 00 10 CF DF 00 3F FF 2D FF FF 10 08 55 80 5C
 80F0   00 00 00 00 00 00 00 00 00 00 00 0F DD FF FF FF

Intel CPU

Name: Intel Core i7-9700K
Number of Cores: 8
Threads per Core: 1
Timer Frequency: 10 MHz
Time Stamp Counter: None
Estimated Time Stamp Counter Frequency: 3600.04 MHz
Estimated Time Stamp Counter Frequency Error: 0.0576 Mhz
Time Stamp Counter Frequency: 3600.04 MHz

MSR Core #1

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  00002395  00002E00
 0000019C  00000000  883F0800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC081
 00000619  00000000  074754F6
 00000639  00000000  3E9ECEF5
 00000641  00000000  00000000

MSR Core #2

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  00002410  00002E00
 0000019C  00000000  88430800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC081
 00000619  00000000  074754F6
 00000639  00000000  3E9ECEF5
 00000641  00000000  00000000

MSR Core #3

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  0000231A  00002E00
 0000019C  00000000  88470800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC081
 00000619  00000000  074754F6
 00000639  00000000  3E9ECF58
 00000641  00000000  00000000

MSR Core #4

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  00002381  00002E00
 0000019C  00000000  88460800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC081
 00000619  00000000  074754F6
 00000639  00000000  3E9ECF58
 00000641  00000000  00000000

MSR Core #5

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  00002449  00002E00
 0000019C  00000000  88460800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC081
 00000619  00000000  074754F6
 00000639  00000000  3E9ECF96
 00000641  00000000  00000000

MSR Core #6

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  00002420  00002E00
 0000019C  00000000  88450800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC081
 00000619  00000000  074754F6
 00000639  00000000  3E9ECF96
 00000641  00000000  00000000

MSR Core #7

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  00002449  00002E00
 0000019C  00000000  88440800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC376
 00000619  00000000  074754F6
 00000639  00000000  3E9ECFF8
 00000641  00000000  00000000

MSR Core #8

 MSR       EDX       EAX
 000000CE  08080838  F1012400
 00000198  00002417  00002E00
 0000019C  00000000  88370800
 000001A2  00000000  00730E00
 000001B1  00000000  88370800
 00000606  00000000  000A0E03
 00000611  00000000  57EFC376
 00000619  00000000  0747551D
 00000639  00000000  3E9ECFF8
 00000641  00000000  00000000

MicroArchitecture: KabyLake
Time Stamp Counter Multiplier: 36

Storage

Drive Name: Sabrent Rocket Q
Firmware Version: RKT30Q.1

PCI Vendor ID: 0x1987
IEEE OUI Identifier: 0x6479a7
Total NVM Capacity: 2000398934016
Unallocated NVM Capacity: 0
Controller ID: 1
Number of Namespaces: 1
Critical Warning: -
Temperature: 32 Celsius
Available Spare: 100%
Available Spare Threshold: 5%
Percentage Used: 2%
Data Units Read: 32811798
Data Units Written: 29702583
Host Read Commands: 158282206
Host Write Commands: 66835758
Controller Busy Time: 817
Power Cycles: 1365
Power On Hours: 5974
Unsafe Shutdowns: 59
Media Errors: 0
Number of Error Information Log Entries: 363
Warning Composite Temperature Time: 0
Critical Composite Temperature Time: 0
Logical Drive Name: D:\
Format: NTFS
Total Size: 2000381014016
Total Free Space: 771971358720

Storage

Drive Name: Samsung SSD 870 EVO 4TB
Firmware Version: SVT01B6Q

 Id Description                        Raw Value    Worst Value ThresholdPhysical
 05 Reallocated Sectors Count          090000000000 99    99    10    -       
 09 Power-On Hours (POH)               930900000000 99    99    0     2451    
 0C Power Cycle Count                  E40100000000 99    99    0     484     
 B1 Wear Leveling Count                020000000000 99    99    0     2       
 B3 Used Reserved Block Count (Total)  090000000000 99    99    10    9       
 B5 Program Fail Count (Total)         000000000000 100   100   10    0       
 B6 Erase Fail Count (Total)           000000000000 100   100   10    0       
 B7 Runtime Bad Block Total            090000000000 99    99    10    9       
 BB Uncorrectable Error Count          000000000000 100   100   0     0       
 BE Temperature                        200000000000 43    68    0     32      
 C3 ECC Rate                           000000000000 200   200   0     -       
 C7 CRC Error Count                    000000000000 100   100   0     0       
 EB Power Recovery Count               0F0000000000 99    99    0     -       
 F1 Total LBAs Written                 7775D57F0200 99    99    0     5118.67 

Logical Drive Name: E:\
Format: NTFS
Total Size: 4000768323584
Total Free Space: 750855188480

Storage

Drive Name: Samsung SSD 870 QVO 8TB
Firmware Version: SVQ01B6Q

 Id Description                        Raw Value    Worst Value ThresholdPhysical
 05 Reallocated Sectors Count          000000000000 100   100   10    -       
 09 Power-On Hours (POH)               040500000000 99    99    0     1284    
 0C Power Cycle Count                  790000000000 99    99    0     121     
 B1 Wear Leveling Count                010000000000 99    99    0     1       
 B3 Used Reserved Block Count (Total)  000000000000 100   100   10    0       
 B5 Program Fail Count (Total)         000000000000 100   100   10    0       
 B6 Erase Fail Count (Total)           000000000000 100   100   10    0       
 B7 Runtime Bad Block Total            000000000000 100   100   10    0       
 BB Uncorrectable Error Count          000000000000 100   100   0     0       
 BE Temperature                        220000000000 40    66    0     34      
 C3 ECC Rate                           000000000000 200   200   0     -       
 C7 CRC Error Count                    000000000000 100   100   0     0       
 EB Power Recovery Count               040000000000 99    99    0     -       
 F1 Total LBAs Written                 328F58BB0200 99    99    0     5594.768

Logical Drive Name: F:\
Format: NTFS
Total Size: 8001545039872
Total Free Space: 3218315948032

Storage

Drive Name: Sabrent Rocket 4.0 Plus
Firmware Version: RKT4P1.2

PCI Vendor ID: 0x1987
IEEE OUI Identifier: 0x6479a7
Total NVM Capacity: 4000787030016
Unallocated NVM Capacity: 0
Controller ID: 1
Number of Namespaces: 1
Critical Warning: -
Temperature: 45 Celsius
Available Spare: 100%
Available Spare Threshold: 5%
Percentage Used: 1%
Data Units Read: 53430020
Data Units Written: 64941181
Host Read Commands: 333453078
Host Write Commands: 351764886
Controller Busy Time: 1060
Power Cycles: 471
Power On Hours: 2386
Unsafe Shutdowns: 23
Media Errors: 0
Number of Error Information Log Entries: 112
Warning Composite Temperature Time: 30
Critical Composite Temperature Time: 0
Logical Drive Name: C:\
Format: NTFS
Total Size: 3999992377344
Total Free Space: 1297630552064

**Comment by triton51** [comment]
Just adding to this, the issue is intermittent and most often occurs when waking the PC from SLEEP mode. The windows start delay setting doesn't seem to have any affect when waking from SLEEP.

**Comment by Rem0o** [comment]
@triton51  didn't think about adding the delay to wake from sleep, might be a good option for some folks.

**Comment by igi666** [comment]
+1 for that option! Came here because I usually also use hibernation and just started using FanControl and obviously came across that issue too.

btw; for me it's only my AMD GPU temp, CPU temp is working fine.

**Comment by begner** [comment]
+1 - same here... 

Currently trying with a Scheduled Task, which shit down FanControl, when going into Sleep or Hybernation...


Something like this:
(Can be added as Task into TaskScheduler)

`<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2022-01-26T16:55:26.9429186</Date>
    <URI>\FanControlStop</URI>
  </RegistrationInfo>
  <Triggers>
    <EventTrigger>
      <Enabled>true</Enabled>
      <Subscription>&lt;QueryList&gt;&lt;Query Id="0" Path="System"&gt;&lt;Select Path="System"&gt;*[System[Provider[@Name='User32'] and EventID=1074]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>
    </EventTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>taskkill</Command>
      <Arguments>/T /F /IM "FanControl.exe"</Arguments>
    </Exec>
  </Actions>
</Task>`

**Comment by hainfelder** [comment]
+1

**Comment by Rem0o** [comment]
Added a multi-retry mechanism since, until all sensors are back.

**Comment by mooseweener** [comment]
After sleep close FanControl, open HWMonitor and close, open FanControl and it will work.
