### ISSUE TITLE
Auto restart

### ISSUE THREAD

**Issue by r-or** [Rem0o/FanControl.Releases#369]
It would be nice to have an option to automatically restart when some sensors haven't been found.

**Comment by hainfelder** [comment]
+1 this would solve the problem with missings sensors / Sensors getting lost after hiberate / System Standby

**Comment by abien** [comment]
I experience this as well. After standby / hibernate the fan control is pretty much all over the place. 
This would likely fix #316 as well.

**Comment by JasonHorkles** [comment]
Almost every time I wake my computer from hibernate I get a massive list of sensors that couldn't be found, and refreshing doesn't help. I had to make a macro on my stream deck to restart FC so I can quickly restart it after hibernate each time since that's the only solution to making it work again

**Comment by Rem0o** [comment]
Added a multi-retry mechanism since, until all sensors are back.
