### ISSUE TITLE
Nvidia Hotspot / VRAM temps

### ISSUE THREAD

**Issue by TimSirmovics** [Rem0o/FanControl.Releases#371]
Libre now has support for VRAM / HotSpot temps for Nvidia graphics cards:

![image](https://user-images.githubusercontent.com/10243286/139235174-c8612930-b6dc-4db8-b8b1-13f7eca3a885.png)

I built the latest version of Libre and replaced LibreHardwareMonitorLib.dll in the FanControl folder, but I wasn't able to see these extra temperature sensors.

Is there something that needs to be done to make them available to FanControl?

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/140417876-c7b47d44-7d24-4251-9bdf-ca6b7a882bc2.png)

It is coming along.

**Comment by TimSirmovics** [comment]
Oh that's great.
I actually wrote my own plugin for the Nvidia Thermal Sensors which I have been testing for the past week.
I was going to release it today but this would make it redundant.

**Comment by Rem0o** [comment]
@TimSirmovics  in any case, I would be curious to see your work 👍

**Comment by TimSirmovics** [comment]
@Rem0o https://github.com/TimSirmovics/FanControl.NvThermalSensors

**Comment by SakuramuraYC** [comment]
![image](https://user-images.githubusercontent.com/26625383/140511402-c52bad9a-bc4d-4b58-b9b5-e5f53dadff16.png)

![image](https://user-images.githubusercontent.com/26625383/140511491-2863e612-a478-4e30-b5b1-4d35337a59ee.png)
Nothing seems to happen after installation

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/140520531-d8c58a4e-a14d-4fb3-a3f8-1d0253af892c.png)
 Nice

**Comment by SakuramuraYC** [comment]
> ![image](https://user-images.githubusercontent.com/14118956/140520531-d8c58a4e-a14d-4fb3-a3f8-1d0253af892c.png) Nice
Why is there no such thing after adding the dll to the plug-in folder?
Am I missing any action?

**Comment by Rem0o** [comment]
Unlock the dll by right click => property

**Comment by TimSirmovics** [comment]
@SakuramuraYC Did you restart FanControl after adding the plugin?
Also try right clicking and unblocking the file as @Rem0o said above.

Beyond that, if it's still not working, the plugin does not report any errors - it just does nothing if there are any issues.
I could supply a small test app with logging to see where the problem lies.
Although with @Rem0o changes above, you will soon be able to get these sensors from LibreHardwareMonitor itself.

**Comment by Rem0o** [comment]
See V96

**Comment by SirenBrink** [comment]
Disabling the NvAPIWrapper sensors worked for me. In other words, Nvidia's software couldn't see the hot spot temps but my motherboard sensors could.
