### ISSUE TITLE
Feature request: subtraction function in mix custom sensor

### ISSUE THREAD

**Issue by BashMellow** [Rem0o/FanControl.Releases#372]
Hi, could you please consider adding a subtraction function in the mix custom sensor? This may sound odd, but it's very useful for watercooling builds to create a delta sensor to set fan speeds based on the difference between water and ambient temperature. It can be done in HWInfo but in that case as the sensor is a software one its ID often changes after a pc restart and it needs to be reselected in Fan Control.

Thank you for your awesome work!

**Comment by Rem0o** [comment]
Will add.

**Comment by BashMellow** [comment]
Just a remark: fan curves starting from 0°C would also be needed to make it work properly, as water delta values are often <10°C (currently I multiply x10 the value in HWInfo).

Thanks again!

**Comment by Rem0o** [comment]
How can the water temp be lower than the ambient temp to get <0 values?

**Comment by Rem0o** [comment]
Linear fan curve supports 0 deg, should do the trick.

**Comment by BashMellow** [comment]
Oh I thought it was 20C like the graph curve, nice!

**Comment by Rem0o** [comment]
See V96

**Comment by BashMellow** [comment]
Works great! Thanks!
