### ISSUE TITLE
Bitdefender reporting infection (LibreHardwareMonitorLib.dll)

### ISSUE THREAD

**Issue by EvernoteD** [Rem0o/FanControl.Releases#373]
Hi all,

Bitdefender just reported that it found in infection in the dll files for this application.

'FanControl\LibreHardwareMonitorLib.dll is infected with Gen:Suspicious.Cloud.4.Om8@aqe0ECm and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.'

Regards,
Evernote

**Comment by djprmf** [comment]
I can report the same thing happening here.
Probably a false positive. Report it here: https://www.bitdefender.com/consumer/support/answer/40673/

**Comment by Rem0o** [comment]
that dll is open source, you can inspect it with ilspy, or see the source here: https://github.com/Rem0o/FanControl.Releases
