### ISSUE TITLE
Fan cuves based on flow rate

### ISSUE THREAD

**Issue by Schlurcher** [Rem0o/FanControl.Releases#376]
Would be cool if we could define fan curves based on flow rate.

I like to run my pump pretty slow, which currently is 55% at idle. But starting from cold it takes more like 70% to move the fluid fast enough for my high flow NEXT to detect any flow, probably because of higher coolant viscosity due to lower temperature. 
Once temperatures are settled I could reduce pump speed to around 40% without sacrificing temperatures, which would make the pump inaudible. 

I've tried Argus Monitor and Q-Fan Control but both won't allow me to use Flow Rate as a curve source.

**Comment by Rem0o** [comment]
What you are describing is a feedback loop, something like a PID controller, to increase the pump speed until a specific flow rate is achieved. FanControl is not tooled for that.  Also, I don't think it can detect any flow rate sensor.

**Comment by Schlurcher** [comment]
LibreHardwareMonitor detects the sensor, although the values are off by a factor of 100.
![image](https://user-images.githubusercontent.com/973681/140616159-a6d2521b-22fc-4d7f-85d5-59d8604c41cd.png)

To better illustrate my problem:
Pump needs to run at
- 70% at <25 degrees (very noticable in a silent room)
- 50% at 26 degrees (noticable)
- 45% at 26.5 degrees (unnoticable)
- 40% at 27 degrees (inaudible and at idle equilibrium)
to yield a flow rate of >20L/m. That's a huge difference in pump speed and noise levels.

If I could define a curve with a target flow rate of lets say 30 L/m and have the PWM signal adjusted to match that flow rate, wouldn't that be all I need? Then combine this coolant temperature curve, to increase pump speed if the coolant temperature increases and use the MAX value of both in a mixed curve and I would have a essentailly a minimum flow rate curve.

Thinking about it I could probably hack something together with an inversed fan curve based on coolant temperature, but that seems kinda hacky and not as reliable as directly adjusting pump speed based on flow rate.

**Comment by Moravuscz** [comment]
Could possibly be done as a sensor plugin.
Take the flow rate input, transform the value using a linear scaling function to a range of 0-100, and present it to FanControl as a temperature sensor. Then within FanControl you can use the sensor as input for whatever curve magic you need done.
A little convoluted, and not immediately obvious what the flow rate is from within FanControl though...

**Comment by rollsch** [comment]
Why can't we have a PID controller? 

If we can't have one, can we have a plugin or the source code so we can write one ourselves?

**Comment by Rem0o** [comment]
@rollsch  try the "Auto" fan curve.
