### ISSUE TITLE
Fans Ramp up to 100% & Screen turn black

### ISSUE THREAD

**Issue by metalgie** [Rem0o/FanControl.Releases#377]
I start getting this weird issue after updating windows 11 (KB5006674), my fans ramp up to 100% & screen turn black, i have to force shutdown windows, my Fan Control is updated to the latest. i attached the logs & sys info. I stopped using FanControl since this issue start happening and it never happened again.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/7495601/log.txt)
[Sys-Info.txt](https://github.com/Rem0o/FanControl.Releases/files/7495603/Sys-Info.txt)

**Comment by Rem0o** [comment]
From your logs, seems like the program tries to access NvAPI (graphic driver) but it is missing/bugged out.  What's your GPU/driver situation?

**Comment by metalgie** [comment]
I got Evga RTX 3080ti ftw 3 and the driver is updated (496.49)

**Comment by Rem0o** [comment]
Nevermind, those logs date back to mid october. Seems like your driver is crashing. Any logs from EventViewer?

**Comment by metalgie** [comment]
Here is the EventViewer logs when that happend

[Book1.xlsx](https://github.com/Rem0o/FanControl.Releases/files/7499370/Book1.xlsx)

**Comment by Rem0o** [comment]
There is nothing to do with that log you sent. Please do some work to filter out stuff and show details of what might be related to a GPU driver crash. Even if you narrow it down to FanControl crashing your driver but there is nothing specific as to why that might happen, there is nothing I can do really.

**Comment by metalgie** [comment]
I'm looking at windows logs > system, is there another place I should look at to see what is going? I would love to figure out what is the problem and start using FanControl

**Comment by SaschaStenger** [comment]
> I'm looking at windows logs > system, is there another place I should look at to see what is going? I would love to figure out what is the problem and start using FanControl

I have the same issue after updating to windows 11. 
Which los would be of help here?

**Comment by PeterPan669** [comment]
I'm also experiencing random crashes and lockups. Especially this 'black screen' issue is new to me and seem to be happening since I'm using Fan Control; My screen goes black, my computer still seems to get power on the mobo, but keyboard lights go off and everything is unresponsive. Even reset button won't work; I actually have to shut down the PSU, and restart it.
