### ISSUE TITLE
Unknown motherboard sensor display high temp.

### ISSUE THREAD

**Issue by suhdd** [Rem0o/FanControl.Releases#378]
![屏幕截图 2021-11-08 200559](https://user-images.githubusercontent.com/13049561/140740603-891dddb1-c7d7-423a-ac93-c97111c32aab.png)
a source called [AUX 2 C8DH] shows 120+ degree temp. but i can not find it in HWINFO. so how can i make sure what is it？

**Comment by Rem0o** [comment]
I wouldn't worry about it, especially if other softwares do not show such a sensor.   Motherboard support can be hit and miss. Just make sure the sensors you want to use are correct.
