### ISSUE TITLE
Suggestion: different font for status bar + additional tray monitor

### ISSUE THREAD

**Issue by coax** [Rem0o/FanControl.Releases#38]
Hello, thanks for the Fan Control, it really is helpful.

4K/5K UHD monitors are becoming a standard these days and one has to use scaling in Windows. This, however, reproduces blurred and upscaled icons/fonts in status bar. Have you considered using a different font which might be more clear?
![image](https://user-images.githubusercontent.com/189817/93664035-2c9b2b00-fa6c-11ea-897a-a62a1e1977d9.png)

Also, suggesting a feature to add another monitor into status bar (eg. one for CPU, another for GPU temperature).

**Comment by Rem0o** [comment]
Will look into it, I don't have a 4K monitor available though to test properly.

**Comment by Eldenroot** [comment]
Also can we change color if the temp is over? Or display more temps?

**Comment by Goldman1337** [comment]
another good idea might be an option to show the highest temp there, instead of a specific one

**Comment by svm420** [comment]
I would love at least 2 tray icons. One for CPU one for GPU

**Comment by 1ucay** [comment]
Hi, yes please, set Segoe UI for example, it will be better. Thanks

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/207975086-d64c1481-135a-45d5-8191-69cb5cc5412f.png)

This is coming.
