### ISSUE TITLE
[Feature request] Exponential back of at startup

### ISSUE THREAD

**Issue by piotrpo** [Rem0o/FanControl.Releases#381]
When the application starts it is dependent on the background driver initialization. It forces user to confirm the error, refresh sensors. 

To remediate this issue following changes are proposed:
 After start the application will not present first 20 errors to the user, while performing following algorithm in pseudo code:

```
attempt = 0
initialized = false
while(attempt < 20 && !initialized){
  initialized = initializeDriver()
  if(!initialized){
    wait(1second * 2^attempt
  }
}
```

**Comment by Rem0o** [comment]
Added a multi-retry mechanism since, until all sensors are back.
