### ISSUE TITLE
[Feature request] Configuration autosave

### ISSUE THREAD

**Issue by piotrpo** [Rem0o/FanControl.Releases#382]
When a change is made to configuration, the configuration file is saved without user prompt.

**Comment by Rem0o** [comment]
That's nice, until you made a change that you don't want to be saved.   I much prefer having a user from time to time forget to save than a ton of users emailing me that their config was saved without them knowing when they were experimenting with their setup.

**Comment by piotrpo** [comment]
Ok, what about having "auto-save" configuration parameter?

**Comment by kamenminkov** [comment]
Just started using FanControl and this is what came to mind immediately. I understand it might be too intrusive, but it would be nice to at least have it as an option, or only autosave things that the app itself does like detecting fan start/stop rates (unlike user changes like changing a curve or a fan mode).

**Comment by Rem0o** [comment]
FanControl now prevents shutdown/logout/restart if settings were changed and not saved, kinda like MSWord would do.
