### ISSUE TITLE
[Issue] after updating to v96, I no longer have a gpu control.

### ISSUE THREAD

**Issue by Not-AriStienfeld** [Rem0o/FanControl.Releases#384]
I have gpu sensors, such as gpu fan rpm and temp, but no control. It used to work, why doesn't it anymore? this was after I ran the auto setup.
![image](https://user-images.githubusercontent.com/56319363/141383676-f1ab2515-8a54-4d0a-aadd-efe8bb66144c.png)

**Comment by Rem0o** [comment]
The control was hidden because the assisted setup couldn't control it.  You can bring it back with the hamburger menu => Show hidden cards.
