### ISSUE TITLE
Really "sluggish" performance after update.

### ISSUE THREAD

**Issue by XXMarkicX** [Rem0o/FanControl.Releases#386]
Unsure how to actually describe issue, but after software got an update when I bring it up, it feels like its running on 5 fps and if I am in call with people on discord it just causes big lag spikes with voice... Took a look task manager, there is no noticeable spikes in performace.

**Comment by Rem0o** [comment]
Are you sure it's FanControl? Like its a 1:1 thing? If it is, you might want to try and remove sensor sources you don't need:
![image](https://user-images.githubusercontent.com/14118956/141654133-3dc31bf0-5944-4529-b174-e24e22b613e9.png)

**Comment by XXMarkicX** [comment]
I would like to believe its not, but I didnt do really anything in last few days software wise on whole PC, besides upgrading GPU driver. (it was already "sluggish" before I updated driver). Is it possible, that I roll-back to prev. version and report back to u?

**Comment by XXMarkicX** [comment]
Hey @Rem0o. 
I couldnt really experiment what was wrong, but latest update somehow fixed it, thank you for providing such a great software :D
