### ISSUE TITLE
Cycling case fan speed after updating to V96

### ISSUE THREAD

**Issue by Dope-johnny** [Rem0o/FanControl.Releases#388]
So after updating to V96 my case fan control doesn't work anymore. I now went back to V95 and it works fine again.

The issue:
The fan speed is that of the set curve for about 2 seconds and then 0% for the same time and looping over and over. For that short period the fan speed seems to be correct.

What I tried:
Refreshing sensors, set manual control, set flat curve (other card)

**Comment by Rem0o** [comment]
Try and set both the start and stop % to 0 for the fan in problem as a workaround, known issue.

**Comment by Dope-johnny** [comment]
Thanks, I just updated and wanted to try the work-around. Updated to V97 and the issue isn't there...
