### ISSUE TITLE
V96 keep prompting to save upon every start/send to tray

### ISSUE THREAD

**Issue by DfrostX** [Rem0o/FanControl.Releases#389]
Hi Remy, first thanks for this amazing piece of software. The new addition in V96 was long awaited by me as I only use hwinfo sensors so removing some from LHM which were interfering with hwinfo reading, like the corsair psu sensors is great.

Now im having a small issue (minor annoyance really) that seem to be related to the new function. 

Every time I start FanControl, open the gui, then close it without having changed anything, I get prompted to save. If I say yes, then it goes to tray and I can open and close without any saving prompt until I shutdown the app completely and start the above sequence again, at which point it will prompt again. If I say no, then it goes to tray anyway and I get prompted every open from tray until I say yes.

I did some compare of the .json file before and after saving (without changing anything...) and there seeem to be something weird going on with the 2 storage lines. 

There are two options in the file for storage sensor reading:

 "LibreHardwareMonitorSettings": {
      "Motherboard": true,
      "CPU": true,
      "Memory": true,
      "GPU": true,
      **_"Storage": false,_**
      "Controller": false,
      "PSU": false
    },
    "NvAPIWrapperSettings": {
      "Enabled": true
    },
    "DisabledPlugins": [],
    **_"DisableStorageSensors": false_**

I noticed that the option for storage in the GUI and for both line of the .json file keep changing status on their own upon every start, which might explain why it keep asking to save... Maybe this is related, maybe not, but I thought you would like to know.

Merci et bonne journée!

**Comment by Rem0o** [comment]
Good catch on DisableStorageSensors, it was defect. Fixed in V97.

**Comment by DfrostX** [comment]
Fixed! Thanks!
