### ISSUE TITLE
Missing 3 Fans in Controls, it879xe

### ISSUE THREAD

**Issue by DarkIrata** [Rem0o/FanControl.Releases#39]
Motherboard: Gigabyte Aorus x570 Master | Bios: F22
FanControl Version: V49

Missing Fan Controls: 
• System Fan 4 
• System Fan 5 - Pump  [Used as Fan] 
• System Fan 6 - Pump  [Unused] 

Speeds are shown correctly under speeds.
By the userconfig following identifiers where found:

• System Fan 4 => /lpc/**it879xe**/fan/2
• System Fan 5 - Pump => /lpc/**it879xe**/fan/0
• System Fan 6 - Pump => /lpc/**it879xe**/fan/1

for comparison, here is System Fan 2 
/lpc/**it8688e**/fan/2

Would be nice to see support for them too.

**Comment by Rem0o** [comment]
As far as I can see, the it879xe has no control mapped, only RPMs.  No idea if there is any control register available to be mapped.

**Comment by DarkIrata** [comment]
Checked the LibreHardwareMonitor repo. Also a known issue there. 
If i find the time i try to look into the openhardwaremonitor repo since there was an attempt to give fan controls for it879xe chips.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/283

**Comment by GittyBaer** [comment]
Just to inform you:
Linux Kernel has Support for the newer Gigabyte ITE Sensorchips now:
https://github.com/t-8ch/linux-gigabyte-wmi-driver
https://github.com/acidanthera/bugtracker/issues/1666

So it would be great if you can adapt it here?

(I will spread this on other cases about the same issue)

**Comment by ajhix36** [comment]
Any work on this? I have the same issue :(
