### ISSUE TITLE
FanControl claims "No plugins loaded", but for sure the HWiNFO plugin is loaded

### ISSUE THREAD

**Issue by chjohans** [Rem0o/FanControl.Releases#392]
See the screenshots, I have sensor values from HWiNFO and I use them, but FanControl claims no plugin is loaded

![snap002851](https://user-images.githubusercontent.com/24390228/141766051-d505eb15-161e-4c32-9bda-eb465f5e014e.png)
![snap002852](https://user-images.githubusercontent.com/24390228/141766056-419e988a-fc8f-4794-95d5-0d281d0893fd.png)

**Comment by Rem0o** [comment]
Log.txt?

**Comment by chjohans** [comment]
It didn't log anything, and when I checked now it had found the HWInfo plugin. I had restarted my PC and actually deleted log.txt to debug some other error, and not it doesn't even exists. But will look out for this happening again and update you with log.txt.

![snap002853](https://user-images.githubusercontent.com/24390228/141788817-da03e563-fba7-4437-a78c-b8407c02f424.png)

**Comment by TurboFiero** [comment]
Same issue here, disabling NvApiWrapper seems to resolve it

**Comment by whatisboom** [comment]
@Rem0o I'm experiencing a similar issue, however i am not seeing the HWinfo sensors like @chjohans attached my log, seems its having issues reading the HWinfo file?

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/7795505/log.txt)

**Comment by meldridge** [comment]
Same issue here, log.txt attached: [log.txt](https://github.com/Rem0o/FanControl.Releases/files/7967290/log.txt)

_System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information._

**Comment by meldridge** [comment]
Looks like it's just the Zone.Identifier flag on the plugin .dll. Checking this will fix the issue: 
![image](https://user-images.githubusercontent.com/8285554/151724495-87ec71b2-243a-45fc-bc5c-193e1703740a.png)
