### ISSUE TITLE
[Feature request] Multi line labels for controls, sensors, curves etc.

### ISSUE THREAD

**Issue by vaibhav2912** [Rem0o/FanControl.Releases#396]
Hi,

First of all thank you for a great piece of software for PC fan control.

Do you think you can allow multi line labels for the elements in the software? I have controls and curves that are a little descriptive (couple of lines). Most of the text doesn't show up on the label.

Thank you

**Comment by Rem0o** [comment]
Good point.
Will add multiline overflow.

**Comment by vaibhav2912** [comment]
Thanks!

**Comment by vaibhav2912** [comment]
Implemented in V99.
