### ISSUE TITLE
Problem with FanControl removal from task scheduler

### ISSUE THREAD

**Issue by skoer** [Rem0o/FanControl.Releases#397]
For some reason FanControl keeps being removed from the task scheduler and I have to manually run it - see example from log below:

![image](https://user-images.githubusercontent.com/86178765/142696454-b3183cab-a416-4f38-b1fe-20c08998337e.png)

I can't work out why this is happening - there's no obvious intervention from virus/malware software that I can see.

Any ideas would be much appreciated

**Comment by Rem0o** [comment]
FanControl overrides the task everytime the program is launched. These traces reflect these updates.

**Comment by skoer** [comment]
OK, but do you have any thoughts as to why FanControl isn't always executed at startup? 

I regularly have to run FanControl manually when it doesn't start, re-save the option to Start with Windows, and it works for a while again, before going through exactly the same issue again.  I can't see a pattern and I'[m not sure what could be going on here.
