### ISSUE TITLE
Controls missing, cannot find an add option.

### ISSUE THREAD

**Issue by cbigganz** [Rem0o/FanControl.Releases#4]
I am missing controls for 3 fan headers on my motherboard, but GPU appeared automatically. SpeedFan can control my fans, so they are not locked. 

Can an manually add control function be added?

Motherboard is a Alienware Aurora R4

![cbigganz fans](https://user-images.githubusercontent.com/67127938/85080320-b988cc80-b17d-11ea-8409-c1cc12270a4d.png)

**Comment by Rem0o** [comment]
The fan control detection is done by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor. You can't "add" a control from the UI. Either the driver portion for your specific board is implemented, or it is not. As of right now, it is not supported, so any compatibility issue should be redirected to the previously mentioned repo.
