### ISSUE TITLE
Fan Control doesn't (or partially) start.

### ISSUE THREAD

**Issue by KingTomaHawk** [Rem0o/FanControl.Releases#40]
Hello,

I have just found this software and wanted to test it, but when I start the .exe a symbol in the taskbar appears with no function.
It seems like NZXT is causing the problem, even when I don't have it running.

Here is the log:

22.09.2020 18:30:38: Unhandled exception in FanControl v1.0.0.0
22.09.2020 18:30:38: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenX3.Close()
   bei LibreHardwareMonitor.Hardware.Controller.Nzxt.NzxtGroup.Close()
   bei LibreHardwareMonitor.Hardware.Computer.Remove(IGroup group)
   bei LibreHardwareMonitor.Hardware.Computer.Close()
   bei FanControl.Domain.ComputerAccessLayer.Dispose()
   bei Autofac.Core.Disposer.Dispose(Boolean disposing)
   bei Autofac.Util.Disposable.Dispose()
   bei Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   bei Autofac.Util.Disposable.Dispose()
   bei Autofac.Core.Container.Dispose(Boolean disposing)
   bei Autofac.Util.Disposable.Dispose()
   bei FanControl.App.OnExit(ExitEventArgs e)
   bei System.Windows.Application.DoShutdown()
   bei System.Windows.Application.ShutdownImpl()
   bei System.Windows.Application.ShutdownCallback(Object arg)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
22.09.2020 18:32:25: Unhandled exception in FanControl v1.0.0.0
22.09.2020 18:32:25: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei LibreHardwareMonitor.Hardware.Controller.Nzxt.KrakenX3.Close()
   bei LibreHardwareMonitor.Hardware.Controller.Nzxt.NzxtGroup.Close()
   bei LibreHardwareMonitor.Hardware.Computer.Remove(IGroup group)
   bei LibreHardwareMonitor.Hardware.Computer.Close()
   bei FanControl.Domain.ComputerAccessLayer.Dispose()
   bei Autofac.Core.Disposer.Dispose(Boolean disposing)
   bei Autofac.Util.Disposable.Dispose()
   bei Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   bei Autofac.Util.Disposable.Dispose()
   bei Autofac.Core.Container.Dispose(Boolean disposing)
   bei Autofac.Util.Disposable.Dispose()
   bei FanControl.App.OnExit(ExitEventArgs e)
   bei System.Windows.Application.DoShutdown()
   bei System.Windows.Application.ShutdownImpl()
   bei System.Windows.Application.ShutdownCallback(Object arg)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Thanks

**Comment by crion66** [comment]
I see the fan symbol in the windows taskbar but when I click on it no window opens up. Also when rightclicking in the miniatured fan down on the right side of windows taskbar by the date/time section I can see Configuration/Open but when clicking on these nothing happens. I do not have NZXT running/installed knowingly atleast.

**Comment by KingTomaHawk** [comment]
I found the solution: 
The application was starting, I was just not able to maximize the window. I had to press Shift+Ctrl and then right-click its icon on the taskbar and select Restore or Maximize. 

I think this can be closed.
