### ISSUE TITLE
FanControl cannot remember the options for several versions.

### ISSUE THREAD

**Issue by MasterixCZ** [Rem0o/FanControl.Releases#406]
FanControl has been asking me over and over again since version 95 if I want to send money and detect fans. I always check the option that I don't want to be notified anymore, but it's always there. Same problem with the window size, it always gets smaller when I open it and I always have to make it bigger myself. I save the configuration, turn FanControl off and on but it doesn't help.

**Comment by Rem0o** [comment]
All those infos are handled by the CACHE file. Seems like your CACHE file isn't being saved/read? Do you launch FanControl from its own folder?

**Comment by MasterixCZ** [comment]
Yes.

**Comment by Rem0o** [comment]
Anything relevant in log.txt?

**Comment by MasterixCZ** [comment]
What should be there?

**Comment by Rem0o** [comment]
Send the file.

Also simple test. Open FanControl, move the top left corner tothe to the top left forner of your screen, then exit the app.

![image](https://user-images.githubusercontent.com/14118956/144080824-2c6e6797-bde9-4ecd-a501-7f948c882381.png)

The cache file should get updated with "top" and "left" near 0. When you open the app back, the window should be at that last location.

**Comment by MasterixCZ** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/7627558/log.txt)

**Comment by MasterixCZ** [comment]
It worked! Thank you.
