### ISSUE TITLE
[Feature Request] REST API Sensor Option

### ISSUE THREAD

**Issue by TheMasterofBlubb** [Rem0o/FanControl.Releases#409]
It would be nice to have an option of a REST API Sensor, where you can add a URL that gets pulled periodically (similar to the File Sensor).

Would allow for super simple custom sensors on Arduino/ESP32 basis

**Comment by Rem0o** [comment]
Seems like a great plugin idea.

See https://github.com/Rem0o/FanControl.Releases/wiki/Plugins.

**Comment by TheMasterofBlubb** [comment]
@Rem0o is there a way to have an Input field for Plugin Sensors? (Maybe adddition for the API)
Usecase would be having a Input-Field in the GUI to enter the URL, that is then forwarded to the plugin

**Comment by Rem0o** [comment]
There is no interface to interact with a plugin sensor, and I don't think you need it.

Possible solutions:
1) Create file sensors, update them externally ( write to these files ) with whatever code you want that fetches your API in a loop.
2) Create a plugin that reads a config file, let say (mypluginconfig.json), input the URL in there and read it from your plugin, then create all the temp sensors and inject them into FanControl like every other plugin.
