### ISSUE TITLE
Feature Request: Support for X570 chipset temperature

### ISSUE THREAD

**Issue by chjohans** [Rem0o/FanControl.Releases#410]
I would like to see support for the X570 chipset temperature sensor on X570 motherboards, a very common MB for AMD systems.

I have access to both the Fan and the Fan Control for the chipset fan, but I'm missing the chipset temperature.

I can get it through the HWiNFO plugin, but that plugin has too many issues to be usable.

**Comment by Rem0o** [comment]
See the README:

Feel free to contribute: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
