### ISSUE TITLE
Missing NZXT, nVidia sensors upon update to v98 from v95

### ISSUE THREAD

**Issue by daninko** [Rem0o/FanControl.Releases#411]
I recently updated from v95 to v98 and upon starting up FanControl, have received this error, and I can no longer control my radiator fans according to liquid temperatures as the NZXT liquid temperature sensor is no longer found. Restarting the app, reinstalling the app, and refreshing the sensors does not fix the problem. 

I loaded up CAM, and the sensors are still apparently accessible there, so I imagine that something happened in a recent update to LibreHardwareMonitor.

Upon trying older versions, it appears this issue started in v96. 

![bug](https://user-images.githubusercontent.com/5721292/144339259-f4c0a238-f10a-4ce3-b26e-9242c648aa0d.png)

**Comment by Rem0o** [comment]
Can you take a look at your sensor settings in the app?

**Comment by gmasil** [comment]
I have the same issue, I cannot find anything under _Controller_, in V95 everything shows up as expected.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/144467788-c34dcb69-823f-4e1f-bafc-e7aca55610b3.png)

Make sure the options you want are checked:
![image](https://user-images.githubusercontent.com/14118956/144467818-4a2e6354-f6bd-4fa3-aafa-91cd5161e9a2.png)

**Comment by daninko** [comment]
For me, Controller was unchecked by default after the update from v95. Upon checking off Controller and refreshing, the missing sensors are now available.

**Comment by gmasil** [comment]
Yes, that was the problem, I totally misunderstood you. Thank you both for pointing that out. Now knowing what to do it feels kinda obvious, but I was thinking in the wrong direction before.

**Comment by Rem0o** [comment]
For a lot of people, the controller section, depending on their setup, can cause some issues if said 3rd party are not configured properly from the outside. I prefer it to be an opt-in thing.
