### ISSUE TITLE
Occasionally incorrectly read values from HwInfo

### ISSUE THREAD

**Issue by pladux** [Rem0o/FanControl.Releases#414]
After some time FanControl starts reading wrong values for my Aquacomputer highflow NEXT.

(Water-) Temperature is either read as extremely high (> 150°C) or extremely low (< 3° C).

After restarting FanControl the sensor is read correctly.

Sensor data is read through HwInfo.
No error is shown in log file.

<img width="1111" alt="Screenshot 2021-12-03 101426" src="https://user-images.githubusercontent.com/19801768/144577758-c04dcf89-a057-46f6-a6af-06c83c1844c8.png">

**Comment by Rem0o** [comment]
Should this issue be in https://github.com/Rem0o/FanControl.HWInfo then?

**Comment by ichiban615** [comment]
I have same problem, Aquacomputer highflow NEXT in fancontrol 295c but HWinfo 27c, using the plugin, z690 mb

**Comment by DfrostX** [comment]
I know a plugin for Aquacomputer fixed this but if anyone is experiencing something similar with HWinfo plugin, see Note2 here https://github.com/Rem0o/FanControl.Releases/discussions/714

**Comment by Rem0o** [comment]
Use new HWInfo plugin version.
