### ISSUE TITLE
FanControl interferes with MSI Afterburner (nvapi?)

### ISSUE THREAD

**Issue by Simon566** [Rem0o/FanControl.Releases#415]
MSI afterburner and/or nvidia inspector reduce CPU speeds to minimum ( i think failsafe) when fancontrol is running. I have deactivated GPUA and nvapi access but this doesnt make a difference

**Comment by Moravuscz** [comment]
In MSIAB set fan control to Auto and disable user fan curve. That works for me, I have absolute control over my AORUS 3080 Ti's fans.
Setting Auto for fan in Inspector should work too, can't verify tho.

**Comment by Rem0o** [comment]
Both softwares will conflict with each other as they use the same methods to control the fans.  Activate only 1 or the other.
