### ISSUE TITLE
[Feature Request] T_Sensor temp?

### ISSUE THREAD

**Issue by axlgundam** [Rem0o/FanControl.Releases#416]
Hey so one of the issues I’m running into is that I can’t tell which temp gauge is the T_Sensor. I love to be able to base my fans on the temp of the water in my loop. However I can’t for the life me see which temp belongs to the T_Sensor. I know that AIDA 64 tell me the temp of the T_Sensor but it’s lower than any of them temps I can see on Fan Control. I run a Rog Strix B550 E-Gaming board.

**Comment by Rem0o** [comment]
I don't take hardware compatibility request here. See README.
