### ISSUE TITLE
Liquidctl Integration

### ISSUE THREAD

**Issue by RohitJones** [Rem0o/FanControl.Releases#42]
First off, Thank your amazing work on this tool. 

[Liquidctl ](https://github.com/jonasmalacofilho/liquidctl) an open source tool to manage AIO liquid coolers.
There had have been multiple attempts to make a gui for the tool, but all of them have stalled or never took off.

I believe that your existing GUI is perfect for this and that it should be possible to integrate Liquidctl into FanControl.

Obviously I don't expect you to just take a random person's feature request and implement it, so I want volunteer to help with the integration.

Thanks !

**Comment by C0NTi** [comment]
As far as I can tell Fan control is already controlling the pump speed of my Kraken x52.
The pump speed is not reported correctly always displays as 0% but it is actually sending the target percentage to the pump and using Liquidctl confirms the pump speed is at the target %age

![image](https://user-images.githubusercontent.com/29498865/94337425-19470d00-ffe2-11ea-8254-8666484b7bc7.png)


![image](https://user-images.githubusercontent.com/29498865/94337413-09c7c400-ffe2-11ea-82ec-5270c5210065.png)

**Comment by RohitJones** [comment]
One of the advantages of an integration with liquidctl is that you can also control the fans of AIO coolers which have an integrated fan controller (Corsair AIOs for example). I have a Corsair H80iv2 installed in my system but do not see pump showing up in FanControl, though that has already been identified as an issue #5  with LibreHardwareMonitor.

however with liquidctl integration, FanControl can be the one stop solution for all pc cooling control.

**Comment by Eldenroot** [comment]
+1

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/wiki/Plugins

**Comment by aeseok** [comment]
hey im a complete newbie to software plugins and things, but by linking fancontrol plugins are you trying to say that we can integrate liquidctl into fancontrol?

**Comment by Rem0o** [comment]
@aeseok yes you could.
