### ISSUE TITLE
[Feature Request]Hide tray icon

### ISSUE THREAD

**Issue by jwy090815** [Rem0o/FanControl.Releases#421]
隐藏后可以无感知地在后台运行，察觉不到它的存在，对于喜欢简洁的人来说十分有必要

**Comment by Rem0o** [comment]
Please make the effort to translate. I'm not a native English speaking person myself, but I comply to the most universal language on Github.

From Google translate:
`After being hidden, it can run in the background without perceptually, and it is imperceptible to its existence. It is very necessary for those who like simplicity.`

From what I understand, you want to hide the tray icon.

Answer: 
There needs to be a way to access the UI . If I removed the tray icon, you would have to force kill the process then rerun the program to get access to the UI. What you describe is more of a service behavior, which FanControl is not, and I see no real benefits of setting FanControl as a service.

Closing.

**Comment by jwy090815** [comment]
For example, Auto Dark Mode X, it can hide the tray icon, open ui with AutoDarkModeApp.exe, app can add end programs in ui,My English is not good

**Comment by jwy090815** [comment]
> Please make the effort to translate. I'm not a native English speaking person myself, but I comply to the most universal language on Github.
> 
> From Google translate: `After being hidden, it can run in the background without perceptually, and it is imperceptible to its existence. It is very necessary for those who like simplicity.`
> 
> From what I understand, you want to hide the tray icon.
> 
> Answer: There needs to be a way to access the UI . If I removed the tray icon, you would have to force kill the process then rerun the program to get access to the UI. What you describe is more of a service behavior, which FanControl is not, and I see no real benefits of setting FanControl as a service.
> 
> Closing.

例如Auto Dark Mode X，它可以隐藏托盘图标，用AutoDarkModeApp.exe打开ui，app可以在ui中添加结束程序，我的英文不好
