### ISSUE TITLE
PWM fans acting really weird

### ISSUE THREAD

**Issue by Mineplayerminer** [Rem0o/FanControl.Releases#422]
Hi! I found a really weird thing about my PWM fan control from the V98. After I set my fans on 100%, they just spin up to 300RPM and then zero out again. MB: GIGABYTE B450 Gaming X. This wasn't happening on the older versions.

**Comment by Rem0o** [comment]
Set your start% for that fan appropriately (higher), or set it to 0 to remove that functionality completly.

**Comment by Mineplayerminer** [comment]
Didn't help. I even killed the Gigabyte services running in the background, no difference.

**Comment by zzz0092** [comment]
Same issue here. All of my nine fans keep dropping their speed to around 40% then go back to full speed periodically, even though I set all of them manually to full speed. MB: MSI Z690 Pro A DDR4. CPU: 12700K

**Comment by Mineplayerminer** [comment]
> Same issue here. All of my nine PWM fans keep dropping their speed to around nothing then go back to full speed periodically, even though I set all of them manually to full speed. MB: MSI Z690 Pro A DDR4. CPU: 12700K

I fixed mine. I removed all the GIGABYTE junk from my PC and re-flashed the BIOS to the newest. The problem disappeared right away!
