### ISSUE TITLE
UI never pops up

### ISSUE THREAD

**Issue by JoshBatt1** [Rem0o/FanControl.Releases#423]
I used the Fan Control the first time great and it worked again as I had windows start-up enabled but after selecting minimize on start-up every time I run the program the UI doesn't show. Any ideas?

For some reason, my GPU's fans don't turn on until it is 60c as well and I have no idea why. I am positive I didn't set it at that speed.

**Comment by JoshBatt1** [comment]
13/12/2021 20:12:02: Unhandled exception in FanControl v1.0.0.0
13/12/2021 20:43:24: Unhandled exception in FanControl v1.0.0.0

There seems to be an unhandled exception, not sure how it is being caused.

**Comment by Rem0o** [comment]
No tray icon? 
![image](https://user-images.githubusercontent.com/14118956/145886785-9fafe7f3-1e96-4ea1-9984-e5372408c346.png)

**Comment by JoshBatt1** [comment]
Didn't even realize I could use that. Thank you.
