### ISSUE TITLE
Add temps to "control" cards

### ISSUE THREAD

**Issue by Goldman1337** [Rem0o/FanControl.Releases#43]
The cards in the control tab have fan speed and %, but not temps. It would be really helpful to add it on those cards, so you can check the whole status in a single place. 
Right now the only way to check temps in the app is to add a curve and check in the select from source.

**Comment by Rem0o** [comment]
But that's the whole point. The temps are only relevant to the fan curves. Could maybe edit the label of the fan curve to include the temperature if it has one, because some types of curve don't have any temps.

**Comment by Goldman1337** [comment]
Yeah, i understand, but at the same time there's no easy way to see temps, which are basically the most important data needed for everything.

**Comment by Rem0o** [comment]
What if your control uses a mix curves that feeds from multiple fan curves and temps?

**Comment by Goldman1337** [comment]
Good point, maybe showing it in the control isn't the best idea, as you say, but the problem that temps are not easily visible still stands. Maybe add them as different "Title"?(like controls, speeds and curves)
