### ISSUE TITLE
Can't close the graph edit window.

### ISSUE THREAD

**Issue by DreBoo** [Rem0o/FanControl.Releases#430]
<img width="656" alt="tttttttttttt" src="https://user-images.githubusercontent.com/47048826/146654844-1172a512-3d54-4b3a-99f4-0ca52065d3e1.PNG">

The ok button doesn't appear and as far as i know there's no other way to close the window without exiting fan control.

**Comment by Rem0o** [comment]
A part of the window is missing. You seam to have a kind of mod/skin on top of windows. That might interfere?

**Comment by DreBoo** [comment]
Im not using any skins just windows with high contrast. It seems to be something with how the editor window is being scaled. Resolution at 1080 scaling at 150% which is default

**Comment by Rem0o** [comment]
Ah, 150% is the culprit, the dialog window doesn't seem to handle the scaling properly.  Will take a look.

**Comment by Rem0o** [comment]
Tested at 150% in V120.
