### ISSUE TITLE
Time Average sensors result in NaN% speed on startup

### ISSUE THREAD

**Issue by sctanf** [Rem0o/FanControl.Releases#431]
I use Time Average sensors but they seem to output no temperature for a few seconds, causing the controller to set fan speed to 100% during that time. I can adjust the fan step to mitigate this but that is not a complete solution. This issue does not happen if I set the controller to the original CPU and GPU temperature sensors. Can you change the Time Average sensors to output the source temperature on startup?

![Screenshot 2021-12-18 225450](https://user-images.githubusercontent.com/36978460/146664375-b4aa481a-6aa4-4eb7-a9cf-6b72b0cceed2.png)

**Comment by Rem0o** [comment]
Was able to reproduce the issue.
Will fix.

**Comment by sctanf** [comment]
Fixed in v100, thank you!
