### ISSUE TITLE
App not controlling fans besides GPU fans

### ISSUE THREAD

**Issue by Maddeh66** [Rem0o/FanControl.Releases#432]
Hi there,

So I have had this problem recently in the past week where FanControl is unable to control fan speeds. My Case fans and CPU fans were all behaving on their own to what I can only assume to be the BIOS settings.  
I initially thought it may be due to the update to Version 99 so I rolled back to version 98 but was met with the same problem. I have been using a Fanhub to connect my fans but this configuration worked on previous versions, I also encountered the same problem for V97, 96. Which led me to believe it might be something else causing the issue. 
I haven't installed anything recently that could cause problems aside from updating graphics cards drivers. I did install MSI afterburner however tried uninstalling, and installing a fresh version of FanControl but again, same problem. I have also installed Winaero Tweaker and reset the tweaks but again no solution there. I haven't installed anything else recently that could cause problems aside from updating graphics cards drivers but I was sure this problem preceeded me updating the drivers. I also checked my processes and found an ASUS fan control so I deleted the process and folders attached to it but again this didn't resolve my issue. I checked the BIOS and fans are set to PWM with their manual curves, switching to auto/profiles and back again to manual didn't work either. 
I am kind of stumped now as this program worked so well before but for some reason last week it just stopped.
A copy of the report is pasted below;

Motherboard

SMBios Version: 3.1

BIOS Vendor: American Megatrends Inc.
BIOS Version: 2202
BIOS Date: 14/07/2020
BIOS Size: 16 MB

System Manufacturer: System manufacturer
System Name: System Product Name
System Version: System Version
System Wakeup: PowerSwitch

Motherboard Manufacturer: ASUSTeK COMPUTER INC.
Motherboard Name: PRIME B450-PLUS
Motherboard Version: Rev X.0x
Motherboard Serial: 191263404201512

Chassis Type: Desktop
Chassis Manufacturer: Default string
Chassis Version: Default string
Chassis Serial: Default string
Chassis Asset Tag: Default string
Chassis SKU: Default string
Chassis Boot Up State: Safe
Chassis Power Supply State: Safe
Chassis Thermal State: Safe
Chassis Power Cords: 1
Chassis Lock Detected: No
Chassis Security Status: None

Processor Manufacturer: Advanced Micro Devices, Inc.
Processor Type: CentralProcessor
Processor Version: AMD Ryzen 5 3600X 6-Core Processor
Processor Serial: Unknown
Processor Socket Destignation: AM4
Processor Socket: AM4
Processor Version: AMD Ryzen 5 3600X 6-Core Processor
Processor Family: AmdZen
Processor Core Count: 6
Processor Core Enabled: 6
Processor Thread Count: 12
Processor External Clock: 100 Mhz
Processor Max Speed: 4400 Mhz
Processor Current Speed: 4100 Mhz

Cache [L1] Size: 384
Cache [L1] Associativity: 8Way

Cache [L2] Size: 3072
Cache [L2] Associativity: 8Way

Cache [L3] Size: 33280
Cache [L3] Associativity: 16Way

Memory Device [0] Manufacturer: Unknown
Memory Device [0] Part Number: Unknown
Memory Device [0] Device Locator: DIMM_A1
Memory Device [0] Bank Locator: BANK 0
Memory Device [0] Speed: 0
Memory Device [0] Size: 0 MB

Memory Device [1] Manufacturer: Corsair
Memory Device [1] Part Number: CMW16GX4M2C3000C15
Memory Device [1] Device Locator: DIMM_A2
Memory Device [1] Bank Locator: BANK 1
Memory Device [1] Speed: 3000
Memory Device [1] Size: 8192 MB

Memory Device [2] Manufacturer: Unknown
Memory Device [2] Part Number: Unknown
Memory Device [2] Device Locator: DIMM_B1
Memory Device [2] Bank Locator: BANK 2
Memory Device [2] Speed: 0
Memory Device [2] Size: 0 MB

Memory Device [3] Manufacturer: Corsair
Memory Device [3] Part Number: CMW16GX4M2C3000C15
Memory Device [3] Device Locator: DIMM_B2
Memory Device [3] Bank Locator: BANK 3
Memory Device [3] Speed: 3000
Memory Device [3] Size: 8192 MB

SMBios Table

 AAMBAI8JAAAAGgAAAQIA8AP/gJyLPwEAAAADDQUN//8QAEFtZXJpY2FuIE1lZ2F0
 cmVuZHMgSW5jLgAyMjAyADA3LzE0LzIwMjAAAAEbAQABAgMEI3Ko6vgwswbqktRd
 ZDetkQYFBlN5c3RlbSBtYW51ZmFjdHVyZXIAU3lzdGVtIFByb2R1Y3QgTmFtZQBT
 eXN0ZW0gVmVyc2lvbgBTeXN0ZW0gU2VyaWFsIE51bWJlcgBTS1UAVG8gYmUgZmls
 bGVkIGJ5IE8uRS5NLgAAAg8CAAECAwQFCQYDAAoAQVNVU1RlSyBDT01QVVRFUiBJ
 TkMuAFBSSU1FIEI0NTAtUExVUwBSZXYgWC4weAAxOTEyNjM0MDQyMDE1MTIARGVm
 YXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcAAAMWAwABAwIDBAMDAwMAAAAAAAEA
 AwVEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwBE
 ZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwAACAkEAAEAAg8NUFMvMiBLZXli
 b2FyZC9Nb3VzZQBQUy8yIEtleWJvYXJkL01vdXNlAAAICQUAAQACEhBVU0IxMgBV
 U0IxMgAACAkGAAEAAv//RFZJAERWSSBwb3J0AAAICQcAAQAC//9IRE1JAEhETUkg
 cG9ydAAACAkIAAEAAhIQVTMxRzFfQzUAVTMxRzFfQzUAAAgJCQABAAISEFUzMUcy
 XzEyAFUzMUcyXzEyAAAICQoAAQACEhBVMzFHMV8zNABVMzFHMV8zNAAACAkLAAEA
 AgsfTEFOAExBTgAACAkMAAEAAv8dQVVESU8AQVVESU8AAAgJDQABIgAAIFNBVEE2
 R18xAAAICQ4AASIAACBTQVRBNkdfMgAACAkPAAEiAAAgU0FUQTZHXzMAAAgJEAAB
 IgAAIFNBVEE2R180AAAICREAASIAACBTQVRBNkdfNQAACAkSAAEiAAAgU0FUQTZH
 XzYAAAgJEwABIgAAIE0uMgAACAkUAAESAAAQVTMxRzFfMTIAAAgJFQABEgAAEFVT
 QjM0AAAICRYAARIAABBVU0I1NgAACAkXAAH/AAD/Q1BVX0ZBTgAACAkYAAH/AAD/
 Q0hBX0ZBTjEAAAgJGQAB/wAA/0NIQV9GQU4yAAAICRoAAf8AAP9DSEFfRkFOMwAA
 CAkbAAH/AAD/QUlPX1BVTVAAAAgJHAABCAAACUNPTQAACAkdAAEfAAAdQUFGUAAA
 CAkeAAH/AAD/UEFORUwAAAgJHwAB/wAA/1NQRElGX09VVAAACgYgAIMBICAgVG8g
 QmUgRmlsbGVkIEJ5IE8uRS5NLgAACwUhAAhEZWZhdWx0IHN0cmluZwBEZWZhdWx0
 IHN0cmluZwBEQVRFAERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1
 bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAAAMBSIABERl
 ZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1bHQgc3RyaW5nAERlZmF1
 bHQgc3RyaW5nAAAgFCMAAAAAAAAAAAAAAAAAAAAAAAAAIgskAAEBlQIAAANJVEUg
 SVQ4NjY1RQAAKQslAAGDAQAAABAgT25ib2FyZCBJR0QAABIXJgADAgIAAAAAAAAA
 gAAAAIAAAACAAAAQFycAAwMDAAAACCYABAAAAAAAAAAAAAAAEx8oAAAAAAD//zcA
 JwACAAAAAAAAAAAAAAAAAAAAAAAAEx8pAAAAQAD//wcBJwACAAAAAAAAAAAAAAAA
 AAAAAAAABxMqAAGAAYABgAEQABAAAQYFB0wxIC0gQ2FjaGUAAAcTKwABgQEADAAM
 EAAQAAEGBQdMMiAtIENhY2hlAAAHEywAAYIBAIIAghAAEAABBgUITDMgLSBDYWNo
 ZQAABDAtAAEDawIQD4cA//uLFwOLZAAwEQQQQTEqACsALAAEBQYGBgz8AGsABgAG
 AAwAQU00AEFkdmFuY2VkIE1pY3JvIERldmljZXMsIEluYy4AQU1EIFJ5emVuIDUg
 MzYwMFggNi1Db3JlIFByb2Nlc3NvciAgICAgICAgICAgICAAVW5rbm93bgBVbmtu
 b3duAFVua25vd24AABIXLgADAgIAAAAAAAAAgAAAAIAAAACAAAARKC8AJwAuAP//
 //8AAAIAAQICBAAAAAMEAAUAAAAAAAAAAAAAAAAARElNTV9BMQBCQU5LIDAAVW5r
 bm93bgBVbmtub3duAFVua25vd24AABIXMAADAgIAAAAAAAAAgAAAAIAAAACAAAAR
 KDEAJwAwAEAAQAAAIAkAAQIagEC4CwMEAAUBAAAAALgLsASwBLAERElNTV9BMgBC
 QU5LIDEAQ29yc2FpcgAwMDAwMDAwMABDTVcxNkdYNE0yQzMwMDBDMTUgIAAAFCMy
 AAAAAAD///8AMQApAP///wAAAAAAAAAAAAAAAAAAAAAAABIXMwADAgIAAAAAAAAA
 gAAAAIAAAACAAAARKDQAJwAzAP////8AAAIAAQICBAAAAAMEAAUAAAAAAAAAAAAA
 AAAARElNTV9CMQBCQU5LIDIAVW5rbm93bgBVbmtub3duAFVua25vd24AABIXNQAD
 AgIAAAAAAAAAgAAAAIAAAACAAAARKDYAJwA1AEAAQAAAIAkAAQIagEC4CwMEAAUB
 AAAAALgLsASwBLAERElNTV9CMgBCQU5LIDMAQ29yc2FpcgAwMDAwMDAwMABDTVcx
 NkdYNE0yQzMwMDBDMTUgIAAAFCM3AAAAAAD///8ANgApAP///wAAAAAAAAAAAAAA
 AAAAAAAAAA0WOAAJAAAAAAAAAAAAAAAAAAAAAAFlbnxVU3xpc284ODU5LTEAZnJ8
 RlJ8aXNvODg1OS0xAHpofFRXfHVuaWNvZGUAamF8SlB8dW5pY29kZQBkZXxERXxp
 c284ODU5LTEAZXN8RVN8aXNvODg1OS0xAHJ1fFJVfGlzbzg4NTktNQBrb3xLUnx1
 bmljb2RlAAAJETkAAaUNBAQAAAwBAAAAGVBDSUVYMTZfMQAACRE6AAGlCgMEAQAM
 AQAAAP9QQ0lFWDE2XzIAAAkROwABpQgDAwIADAEAAAD/UENJRVgxXzEAAAkRPAAB
 pQgDAwMADAEAAAD/UENJRVgxXzIAAAkRPQABpQgDAwQADAEAAAD/UENJRVgxXzMA
 AH8EPgAAAA==

LPC IT87XX

Chip ID: 0x8665
Chip Version: 0x6
Base Address: 0x0290
GPIO Address: 0x0300

Environment Controller Registers

      00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

 00   09 00 FF BF 00 00 40 00 00 C0 44 08 10 A6 FF 39
 10   32 90 00 07 7F 00 00 00 7F 00 00 00 7F 1A 00 00
 20   32 9B 00 00 7F 00 00 00 7F 00 00 00 7F FF C0 99
 30   32 95 00 00 7F 00 00 00 7F 00 00 00 7F 01 01 01
 40   32 97 00 00 7F 00 00 00 7F 00 00 00 7F 00 00 00
 50   7F 00 00 00 7F 00 00 00 7F 00 00 00 7F 3C 3C 3C
 60   32 94 00 5C 7F 00 00 00 7F 00 00 00 7F 3C 3C 3C
 70   08 1E 00 5C 4B 00 00 00 00 00 4B 00 11 00 0F 2A
 80   FF FF 00 00 00 00 00 00 00 00 00 00 00 E5 00 55
 90   00 00 80 FF FF 00 00 FF 40 00 00 00 00 8B 00 87
 A0   7F 7F 7F 00 00 00 0F 00 80 14 4B 33 14 00 0F 65

GPIO Registers

AMD CPU

Name: AMD Ryzen 5 3600X
Number of Cores: 12
Threads per Core: 1
Timer Frequency: 10 MHz
Time Stamp Counter: None
Estimated Time Stamp Counter Frequency: 4100.22 MHz
Estimated Time Stamp Counter Frequency Error: 0.36082 Mhz
Time Stamp Counter Frequency: 4100.22 MHz

MSR Core #1

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #2

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #3

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #4

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #5

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #6

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #7

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #8

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #9

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #10

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #11

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

MSR Core #12

 MSR       EDX       EAX
 C0010000  00000000  00000000
 C0010004  00000000  00000000
 C0010015  00000001  09000011
 C0010064  80000000  499208A4

Ryzen SMU

 PM table version: 0x00240903
 PM table supported: True
 PM table layout defined: True
 PM table size: 0x518
 PM table start address: 0xDA719000

 PM table dump:
  Idx    Offset   Value
 ------------------------
    0    0x000    0
    1    0x004    0
    2    0x008    0
    3    0x00C    0
    4    0x010    0
    5    0x014    0
    6    0x018    0
    7    0x01C    0
    8    0x020    0
    9    0x024    0
   10    0x028    0
   11    0x02C    0
   12    0x030    0
   13    0x034    0
   14    0x038    0
   15    0x03C    0
   16    0x040    0
   17    0x044    0
   18    0x048    0
   19    0x04C    0
   20    0x050    0
   21    0x054    0
   22    0x058    0
   23    0x05C    0
   24    0x060    0
   25    0x064    0
   26    0x068    0
   27    0x06C    0
   28    0x070    0
   29    0x074    0
   30    0x078    0
   31    0x07C    0
   32    0x080    0
   33    0x084    0
   34    0x088    0
   35    0x08C    0
   36    0x090    0
   37    0x094    0
   38    0x098    0
   39    0x09C    0
   40    0x0A0    0
   41    0x0A4    0
   42    0x0A8    0
   43    0x0AC    0
   44    0x0B0    0
   45    0x0B4    0
   46    0x0B8    0
   47    0x0BC    0
   48    0x0C0    0
   49    0x0C4    0
   50    0x0C8    0
   51    0x0CC    0
   52    0x0D0    0
   53    0x0D4    0
   54    0x0D8    0
   55    0x0DC    0
   56    0x0E0    0
   57    0x0E4    0
   58    0x0E8    0
   59    0x0EC    0
   60    0x0F0    0
   61    0x0F4    0
   62    0x0F8    0
   63    0x0FC    0
   64    0x100    0
   65    0x104    0
   66    0x108    0
   67    0x10C    0
   68    0x110    0
   69    0x114    0
   70    0x118    0
   71    0x11C    0
   72    0x120    0
   73    0x124    0
   74    0x128    0
   75    0x12C    0
   76    0x130    0
   77    0x134    0
   78    0x138    0
   79    0x13C    0
   80    0x140    0
   81    0x144    0
   82    0x148    0
   83    0x14C    0
   84    0x150    0
   85    0x154    0
   86    0x158    0
   87    0x15C    0
   88    0x160    0
   89    0x164    0
   90    0x168    0
   91    0x16C    0
   92    0x170    0
   93    0x174    0
   94    0x178    0
   95    0x17C    0
   96    0x180    0
   97    0x184    0
   98    0x188    0
   99    0x18C    0
  100    0x190    0
  101    0x194    0
  102    0x198    0
  103    0x19C    0
  104    0x1A0    0
  105    0x1A4    0
  106    0x1A8    0
  107    0x1AC    0
  108    0x1B0    0
  109    0x1B4    0
  110    0x1B8    0
  111    0x1BC    0
  112    0x1C0    0
  113    0x1C4    0
  114    0x1C8    0
  115    0x1CC    0
  116    0x1D0    0
  117    0x1D4    0
  118    0x1D8    0
  119    0x1DC    0
  120    0x1E0    0
  121    0x1E4    0
  122    0x1E8    0
  123    0x1EC    0
  124    0x1F0    0
  125    0x1F4    0
  126    0x1F8    0
  127    0x1FC    0
  128    0x200    0
  129    0x204    0
  130    0x208    0
  131    0x20C    0
  132    0x210    0
  133    0x214    0
  134    0x218    0
  135    0x21C    0
  136    0x220    0
  137    0x224    0
  138    0x228    0
  139    0x22C    0
  140    0x230    0
  141    0x234    0
  142    0x238    0
  143    0x23C    0
  144    0x240    0
  145    0x244    0
  146    0x248    0
  147    0x24C    0
  148    0x250    0
  149    0x254    0
  150    0x258    0
  151    0x25C    0
  152    0x260    0
  153    0x264    0
  154    0x268    0
  155    0x26C    0
  156    0x270    0
  157    0x274    0
  158    0x278    0
  159    0x27C    0
  160    0x280    0
  161    0x284    0
  162    0x288    0
  163    0x28C    0
  164    0x290    0
  165    0x294    0
  166    0x298    0
  167    0x29C    0
  168    0x2A0    0
  169    0x2A4    0
  170    0x2A8    0
  171    0x2AC    0
  172    0x2B0    0
  173    0x2B4    0
  174    0x2B8    0
  175    0x2BC    0
  176    0x2C0    0
  177    0x2C4    0
  178    0x2C8    0
  179    0x2CC    0
  180    0x2D0    0
  181    0x2D4    0
  182    0x2D8    0
  183    0x2DC    0
  184    0x2E0    0
  185    0x2E4    0
  186    0x2E8    0
  187    0x2EC    0
  188    0x2F0    0
  189    0x2F4    0
  190    0x2F8    0
  191    0x2FC    0
  192    0x300    0
  193    0x304    0
  194    0x308    0
  195    0x30C    0
  196    0x310    0
  197    0x314    0
  198    0x318    0
  199    0x31C    0
  200    0x320    0
  201    0x324    0
  202    0x328    0
  203    0x32C    0
  204    0x330    0
  205    0x334    0
  206    0x338    0
  207    0x33C    0
  208    0x340    0
  209    0x344    0
  210    0x348    0
  211    0x34C    0
  212    0x350    0
  213    0x354    0
  214    0x358    0
  215    0x35C    0
  216    0x360    0
  217    0x364    0
  218    0x368    0
  219    0x36C    0
  220    0x370    0
  221    0x374    0
  222    0x378    0
  223    0x37C    0
  224    0x380    0
  225    0x384    0
  226    0x388    0
  227    0x38C    0
  228    0x390    0
  229    0x394    0
  230    0x398    0
  231    0x39C    0
  232    0x3A0    0
  233    0x3A4    0
  234    0x3A8    0
  235    0x3AC    0
  236    0x3B0    0
  237    0x3B4    0
  238    0x3B8    0
  239    0x3BC    0
  240    0x3C0    0
  241    0x3C4    0
  242    0x3C8    0
  243    0x3CC    0
  244    0x3D0    0
  245    0x3D4    0
  246    0x3D8    0
  247    0x3DC    0
  248    0x3E0    0
  249    0x3E4    0
  250    0x3E8    0
  251    0x3EC    0
  252    0x3F0    0
  253    0x3F4    0
  254    0x3F8    0
  255    0x3FC    0
  256    0x400    0
  257    0x404    0
  258    0x408    0
  259    0x40C    0
  260    0x410    0
  261    0x414    0
  262    0x418    0
  263    0x41C    0
  264    0x420    0
  265    0x424    0
  266    0x428    0
  267    0x42C    0
  268    0x430    0
  269    0x434    0
  270    0x438    0
  271    0x43C    0
  272    0x440    0
  273    0x444    0
  274    0x448    0
  275    0x44C    0
  276    0x450    0
  277    0x454    0
  278    0x458    0
  279    0x45C    0
  280    0x460    0
  281    0x464    0
  282    0x468    0
  283    0x46C    0
  284    0x470    0
  285    0x474    0
  286    0x478    0
  287    0x47C    0
  288    0x480    0
  289    0x484    0
  290    0x488    0
  291    0x48C    0
  292    0x490    0
  293    0x494    0
  294    0x498    0
  295    0x49C    0
  296    0x4A0    0
  297    0x4A4    0
  298    0x4A8    0
  299    0x4AC    0
  300    0x4B0    0
  301    0x4B4    0
  302    0x4B8    0
  303    0x4BC    0
  304    0x4C0    0
  305    0x4C4    0
  306    0x4C8    0
  307    0x4CC    0
  308    0x4D0    0
  309    0x4D4    0
  310    0x4D8    0
  311    0x4DC    0
  312    0x4E0    0
  313    0x4E4    0
  314    0x4E8    0
  315    0x4EC    0
  316    0x4F0    0
  317    0x4F4    0
  318    0x4F8    0
  319    0x4FC    0
  320    0x500    0
  321    0x504    0
  322    0x508    0
  323    0x50C    0
  324    0x510    0
  325    0x514    0

Storage

Drive Name: Samsung SSD 970 EVO Plus 1TB
Firmware Version: 2B2QEXM7

PCI Vendor ID: 0x144d
IEEE OUI Identifier: 0x002538
Total NVM Capacity: 1000204886016
Unallocated NVM Capacity: 0
Controller ID: 4
Number of Namespaces: 0
Critical Warning: -
Temperature: 43 Celsius
Available Spare: 100%
Available Spare Threshold: 10%
Percentage Used: 1%
Data Units Read: 55232680
Data Units Written: 58859873
Host Read Commands: 553537681
Host Write Commands: 383939005
Controller Busy Time: 1512
Power Cycles: 1111
Power On Hours: 3940
Unsafe Shutdowns: 163
Media Errors: 0
Number of Error Information Log Entries: 4457
Warning Composite Temperature Time: 0
Critical Composite Temperature Time: 0
Temperature Sensor 1: 43 Celsius
Temperature Sensor 2: 51 Celsius
Logical Drive Name: C:\
Format: NTFS
Total Size: 999527804928
Total Free Space: 61465321472

Storage

Drive Name: WD Ext HDD 1021
Firmware Version: 2002

Logical Drive Name: G:\
Format: NTFS
Total Size: 1000200990720
Total Free Space: 122945511424

Storage

Drive Name: ST3000DM008-2DM166
Firmware Version: CC26

 Id Description                        Raw Value    Worst Value ThresholdPhysical
 01 Read Error Rate                    8816AD0A0000 99    118   6     -       
 03 Spin-Up Time                       000000000000 93    93    0     -       
 04 Start/Stop Count                   1F2600000000 91    91    20    9759    
 05 Reallocated Sectors Count          000000000000 100   100   10    -       
 07 Seek Error Rate                    0BB551000000 60    67    30    -       
 09 Power-On Hours (POH)               6D3500000000 85    85    0     13677   
 0A Spin Retry Count                   000000000000 100   100   97    -       
 0C Power Cycle Count                  380900000000 98    98    20    2360    
 B7 SATA Downshift Error Count         000000000000 100   100   0     0       
 B8 End-to-End error                   000000000000 100   100   99    -       
 BB Reported Uncorrectable Errors      000000000000 100   100   0     0       
 BC Command Timeout                    000000000000 100   100   0     0       
 BD High Fly Writes                    050000000000 95    95    0     -       
 BE Temperature Difference from 100    210013220000 47    67    45    33      
 BF G-sense Error Rate                 000000000000 100   100   0     -       
 C0 Emergency Retract Cycle Count      460000000000 100   100   0     -       
 C1 Load Cycle Count                   F24200000000 92    92    0     -       
 C2 Temperature                        210000000B00 53    33    0     33      
 C5 Current Pending Sector Count       000000000000 100   100   0     -       
 C6 Uncorrectable Sector Count         000000000000 100   100   0     -       
 C7 UltraDMA CRC Error Count           000000000000 200   200   0     -       
 F0 Head Flying Hours                  14260000DFC8 253   100   0     -       
 F1 Total LBAs Written                 4C141EFF0400 253   100   0     -       
 F2 Total LBAs Read                    A856628D0500 253   100   0     -       

Logical Drive Name: E:\
Format: NTFS
Total Size: 3000457228288
Total Free Space: 2197339594752

Storage

Drive Name: WDC WD30EFRX-68AX9N0
Firmware Version: 80.00A80

 Id Description                        Raw Value    Worst Value ThresholdPhysical
 01 Read Error Rate                    000000000000 200   200   51    -       
 03 Spin-Up Time                       591800000000 171   175   21    -       
 04 Start/Stop Count                   EB1800000000 94    94    0     6379    
 05 Reallocated Sectors Count          000000000000 200   200   140   -       
 07 Seek Error Rate                    000000000000 200   200   0     -       
 09 Power-On Hours (POH)               336600000000 65    65    0     26163   
 0A Spin Retry Count                   000000000000 100   100   0     -       
 0B Recalibration Retries              000000000000 100   100   0     -       
 0C Power Cycle Count                  F71000000000 96    96    0     4343    
 C0 Emergency Retract Cycle Count      E80000000000 200   200   0     -       
 C1 Load Cycle Count                   021800000000 198   198   0     -       
 C2 Temperature                        210000000000 96    117   0     33      
 C4 Reallocation Event Count           000000000000 200   200   0     -       
 C5 Current Pending Sector Count       000000000000 200   200   0     -       
 C6 Uncorrectable Sector Count         000000000000 253   100   0     -       
 C7 UltraDMA CRC Error Count           000000000000 200   200   0     -       
 C8 Write Error Rate                   000000000000 253   100   0     -       

Logical Drive Name: F:\
Format: NTFS
Total Size: 3000457228288
Total Free Space: 1116028915712

**Comment by Rem0o** [comment]
By your own you ruled out an update of the software being the issue, so there must be something on your end that changed. Be it a BIOS update, a setting, could be a lot of things. Can't really help you.

**Comment by Maddeh66** [comment]
Cheers for getting back ,was just not sure if there was any ideas of other apps that might have clashed with it. I'll check the event manager and see if there were any updates that may have conflicted with it. Thanks again.
