### ISSUE TITLE
Not detecting fans

### ISSUE THREAD

**Issue by kell90** [Rem0o/FanControl.Releases#433]
Hi! I've been using fan control for quite a while now, absolutely love it (and have donated). I just built a new PC and tried out the app, but for some reason, it's not detecting certain fans. 

I've attached a picture of my fan setup.
![pc fans](https://user-images.githubusercontent.com/44652363/146689819-acf648c5-e3cb-4928-b0bf-beeb5f1e5095.png)

**Not Detected:**
- 3 front fans that are daisy-chained and plugged into Sys Fan 2.
- Rear DC fan plugged into Sys Fan 1

I'm using a Gigabyte Z690 UD AX DDR4. 

I guess it looks like it just doesn't like Sys Fan headers (however my previous PC used all fan headers on the board and each one was detected)? Any ideas? 

EDIT: I forgot that I only daisy-chained two of the front fans. The third (bottom one) is solo, and plugged into Sys Fan 3. So I suppose that rules out daisy-chaining causing problems.

**Comment by Rem0o** [comment]
See README.
