### ISSUE TITLE
FanControl cannot remember the position and size of the window after PC shutdown.

### ISSUE THREAD

**Issue by MasterixCZ** [Rem0o/FanControl.Releases#436]
Hi, I've posted here once before, but the problem has reappeared. FanControl now doesn't remember the size of the window and its position. I know it worked in previous versions but not now. Also, when I check the option that I don't want to see the donate window anymore and don't even check the fans, I have to close it again and again after the next time I turn on the computer.

**Comment by Rem0o** [comment]
That means for some reason the program can't read the CACHE file in its folder.  That's where all theses infos are kept.

How are you starting up the application? Any log.txt?

**Comment by MasterixCZ** [comment]
I have it set to launch the app when I log in, I tried reinstalling the app a few times but it didn't help.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/7747794/log.txt)

**Comment by Rem0o** [comment]
If you launch the app by yourself, place the window somewhere, exit the app, then open it back up, does it remembers?
Can you post your CACHE file? Does it gets saved (look for the time and date of last modification).

**Comment by MasterixCZ** [comment]
Yeah it works like that, but when I turn off the PC and the app launches itself, it doesn't work. 
[CACHE.txt](https://github.com/Rem0o/FanControl.Releases/files/7756150/CACHE.txt)

**Comment by Rem0o** [comment]
Take a look at the task in task scheduler in windows. Did you edit it? In any case, try and untick then retick the start with windows checkbox.

**Comment by MasterixCZ** [comment]
![Snímek obrazovky 2021-12-21 174945](https://user-images.githubusercontent.com/84620639/146967966-bd8888c8-8542-4818-83d5-05143d231afc.png)
![Snímek obrazovky 2021-12-21 175032](https://user-images.githubusercontent.com/84620639/146967967-0922a5d7-e1cd-485d-8872-c00842d2ccee.png)

**Comment by MasterixCZ** [comment]
I didn't edit the task in any way.

**Comment by MasterixCZ** [comment]
![Snímek obrazovky 2021-12-21 175235](https://user-images.githubusercontent.com/84620639/146968231-b95a2098-2e2a-4f16-844a-3ed2883e543e.png)

**Comment by Rem0o** [comment]
if you run the task manually ( right click => run ), does it starts properly?

**Comment by MasterixCZ** [comment]
Yes, manually it starts fine.

**Comment by Rem0o** [comment]
Increase the delay?

**Comment by MasterixCZ** [comment]
Ok,  i'll try that.

**Comment by MasterixCZ** [comment]
No, it didn't help. I can't even extend the delay, even if I manually save the configuration.

**Comment by Mineplayerminer** [comment]
> No, it didn't help. I can't even extend the delay, even if I manually save the configuration.

Mám rovnaký problém. (I have the same problem)

**Comment by MasterixCZ** [comment]
Jsem rád, že v tom nejsem sám :D (I'm glad I'm not alone in this :D)

**Comment by MasterixCZ** [comment]
Version 100 still hasn't fixed this problem.
