### ISSUE TITLE
hard disk drive locked/read-only by fancontrol

### ISSUE THREAD

**Issue by dkdc** [Rem0o/FanControl.Releases#438]
For example VirtualBox with a physical hard disk won't start (with the same errors as in https://www.virtualbox.org/ticket/8760) when fancontrol is running in the background.

Workaround: stop fancontrol/start virtualbox/start fancontrol

**Comment by Rem0o** [comment]
I would remove hard drives from the sensor settings all together if you don't use them:
![image](https://user-images.githubusercontent.com/14118956/147170472-961864b1-501f-4753-bb10-f43c9c893363.png)

**Comment by dkdc** [comment]
Yes, this worked, so it can stay in autorun. Thanks!
