### ISSUE TITLE
Max temp source

### ISSUE THREAD

**Issue by Goldman1337** [Rem0o/FanControl.Releases#44]
It would be really useful to have a "Max temp" source to use for curves and the tray icon temp value. Specially for chassis fans.

**Comment by Rem0o** [comment]
What do you mean max temp? Like having multiple sensors and taking the max amongst them?

**Comment by Goldman1337** [comment]
Yup, exactly

**Comment by Korkman** [comment]
I would also love this feature. I have an array of SSDs and would like to control the chassis fans according to their max temperature reported (in addition to GFX and CPU temps). While this could be constructed with several "Mix" fan curves in cascade and a curve for every single SSD, it seems overly complicated. A virtual sensor for use as "Temperature source" combining max. or avg. of an arbitrary number of real sensors would be highly appreciated.

**Comment by artofsound** [comment]
Second that. It's just one fan curve having multiple temp sources.
At the moment you need to copy the same fan curve several times and mix them together to get the same behaviour. That's okay for two temps into one curve, but if you like 3+ it gets overly complicated.

**Comment by Rem0o** [comment]
It's coming along

![image](https://user-images.githubusercontent.com/14118956/105865755-3bb55b00-5fc1-11eb-8c14-7edf41f37b8a.png)

**Comment by Rem0o** [comment]
V65 now features custom sensors.
