### ISSUE TITLE
[critical bug] Fix the impact on hdd

### ISSUE THREAD

**Issue by shikulja** [Rem0o/FanControl.Releases#440]
- Prevents hdd spindown. (if the spindown time is above ~55sec - ~60sec)
This probably affects the system HDD drive as well

- Prevents disk unmounting
![image](https://user-images.githubusercontent.com/3386359/147344821-5bf04fee-7ea9-47ee-adcf-4702dcc0d8a0.png)

For verification, the following can be used:
smartctl -s standby,XX /dev/sda
smartctl -s standby,now /dev/sda
Zentimo xStorage Manager
hdparm

**Comment by Dark4Codrutz** [comment]
Are you monitoring the HDD temperature ?
That will call on SMART data and will keep your HDD spinned up

**Comment by shikulja** [comment]
@Dark4Codrutz 
No, no other applications had any effect on disk behavior. This is definitely a fancontrol

**Comment by Rem0o** [comment]
Simply untick storage in the sensor settings. The current implementation in librehardwaremonitor will keep the disks awake.

**Comment by shikulja** [comment]
@Rem0o
Thanks, it looks like it helped.
It would be better if it was disabled by default.
