### ISSUE TITLE
Fan curve (graph) gets NaN as value and fan speed goes to 100%

### ISSUE THREAD

**Issue by mambans** [Rem0o/FanControl.Releases#441]
From time to time the fan curve (graph) gets NaN as value and fan speed goes to 100%.
![image](https://user-images.githubusercontent.com/23280380/147492621-58632fca-5664-41c1-82c9-db65d940716d.png)

**Comment by Rem0o** [comment]
The only way to get NaN is for the temp to be sub-0 (invalid) or the temp. source to be empty.
```
if (_selectedTempSource == null || _selectedTempSource.Value <= 0)
{
    CurrentCommandTarget = float.NaN;
    return;
}
```

**Comment by mambans** [comment]
Hm.., just when I edit the curve the slightly the NaN value disappears briefly.
https://gyazo.com/9b0e7acd9d39ab75ea04bc80c908c57c

But I'll play around bit and see if there are any problems on my end.

**Comment by PeterPan669** [comment]
+1, having the exact same issue on e.g. Chipset values. Is it possible to make an exception for short-lived drops (2 seconds or so) to 0c or negative c?
