### ISSUE TITLE
If "sensor" / statement

### ISSUE THREAD

**Issue by jonalange** [Rem0o/FanControl.Releases#445]
I don't have a good title for this, but is it somehow possible to have a graph fan curve based on CPU temp for case and CPU fan, but if the GPU hits a specific temp, for example 90°C I want the case fans to go a little bit faster to help cool the GPU.

Is that possible? I couldn't get myself a good/ logic way of doing this.

Thanks!

**Comment by Rem0o** [comment]
Mix in Sum mode => Create a curve that adds like 10% when GPU hits 90 and add that to the mix.

**Comment by jonalange** [comment]
Thanks!
But how do I make the "when the GPU hits 90°" part?

**Comment by jonalange** [comment]
Omg, I'm stupid. I'm missing the forest through the trees. Got it now!

Thank you very much for your help and this awesome application!
