### ISSUE TITLE
Autostart not working

### ISSUE THREAD

**Issue by jonalange** [Rem0o/FanControl.Releases#446]
How is autostart supposed to work?
Should the temp icon be in the tray?

I enabled the "start with windows" option and also added a shortcut of the exe to windows auto start folder.
But I don't have the tray icon after startup and I can't find any process related to FanControl in taskmanager.

What is the process called?

**Comment by jonalange** [comment]
I found this issue https://github.com/Rem0o/FanControl.Releases/issues/304

But for me the checkbox is checked every time (it doesn't get unchecked automatically). The app is just not running

**Comment by Rem0o** [comment]
Take a look at the task in the Task Scheduler, and try to run it manually.

**Comment by jonalange** [comment]
It's not even in the list...

**Comment by jonalange** [comment]
Ok, I added the task myself. But now the app opens completely and not minimized. I set the checkbox in the settings, but it's not doing anything. Any suggestions?

**Comment by Rem0o** [comment]
Make sure the "start in" folder is set right in the task.

**Comment by jonalange** [comment]
I don't really know what you mean. 
Now every time the pc starts my saved config gets overridden by some default stuff...

Everything pretty strange and bugged

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/147892955-cce2242d-a309-440e-9514-8ae2eec2c144.png)

This must point to the same folder FanControl is in.

**Comment by uk02919** [comment]
I have the same issue too I think (v99). If I run manually it works fine - if I tick the box that says "Start with windows" (irrespective if I choose a delay or not) it can't load up the config correctly and loads what seems to be a default config. I've tried to run it through task manager but can't get that to work either :(

Smashing software, I really like the design and thinking behind it so hopefully we can track down the issue :)

**Comment by uk02919** [comment]
Just had a quick play - if I create a task with "Run with highest privileges" **unchecked** then it does run (although obviously it pops up the normal UAC prompt). If I run it with the option checked fancontrol.exe never starts.

On Windows 11 (latest consumer - not Insiders build)

**Comment by Rem0o** [comment]
Is the user running the task an admin?

**Comment by uk02919** [comment]
Yes, it has admin rights

**Comment by uk02919** [comment]
Yay! I have managed to get a bit of a hack working ok - basically using "start" rather than loading a new command shell and then getting task scheduler to call a bash file. Info below in case it helps.

fcstart.cmd:
start "" /d c:\utils\fancontrol /min /b c:\utils\fancontrol\fancontrol.exe

fcstart.xml (for task job):
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2022-01-05T08:14:08.0270221</Date>
    <Author>PC1\me</Author>
    <URI>\FCStart</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>PC1\me</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-302125468-2124314595-863171202-1001</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>C:\Utils\fcstart.cmd</Command>
    </Exec>
  </Actions>
</Task>

**Comment by OMGrant** [comment]
I was able to fix this by changing **Medium Mandatory Level** to **Administrators** under the "_When running the task, use the following user account:_" option. See link: https://appuals.com/task-scheduler-says-one-or-more-specified-arguments-not-valid/

**Comment by xhul-dev** [comment]
> I was able to fix this by changing **Medium Mandatory Level** to **Administrators** under the "_When running the task, use the following user account:_" option. See link: https://appuals.com/task-scheduler-says-one-or-more-specified-arguments-not-valid/

We currently suspect the bug affects admins that have identical account and computer names.
Is that your case?
Anyway, until it gets fixed, you can also use the tool i created, which automates everything: https://github.com/xhul-dev/FanControl-WinStart

**Comment by OMGrant** [comment]
> We currently suspect the bug affects admins that have identical account and computer names.
> Is that your case?

Negative. When I discovered _Startup with Windows_ wasn't working on my system, I investigated the Task Scheduler task. Just by opening the Task Properties and trying to save them again without any changes, I received this error message: _One or more specified arguments not valid_. Upon researching this error message I came upon the solution in the link above which fixed the issue for me.

**Comment by xhul-dev** [comment]
> > We currently suspect the bug affects admins that have identical account and computer names.
> > Is that your case?
> 
> Negative. When I discovered _Startup with Windows_ wasn't working on my system, I investigated the Task Scheduler task. Just by opening the Task Properties and trying to save them again without any changes, I received this error message: _One or more specified arguments not valid_. Upon researching this error message I came upon the solution in the link above which fixed the issue for me.

So, if you changed the user on the task scheduler, that means the task itself was successfully created by Fan Control, just wasn't working?
If yes, that means the issue you had was different than the one i was thinking about (where Fan Control fails to create the task).

**Comment by BrendanMan3** [comment]
I have a 30 second delay, set to start the app and minimize to system tray at startup yet it doesn't start when I boot my system.
