### ISSUE TITLE
Create Average Temperature over Time Temperature Source

### ISSUE THREAD

**Issue by Sparkerino1** [Rem0o/FanControl.Releases#45]
Could we potentially get a feature to create a custom temperature source to get an average over time? For example, the CPU tends to vary quite significantly in a short period of time sometimes with single cores randomly peaking 10-15 degrees above other cores at a time. For this, I think an ability to create a function that calculates an average value over an adjustable period of time would be ideal. The purpose of this would be similar to hysteresis and prevent fans from ramping up and down frequently. 

Another unrelated issue is that there is a typo where "Load Configuration" is spelled "Lond Configuration". Not sure if that's been brought up by anyone else yet.

**Comment by Rem0o** [comment]
Thanks for pointing out the typo.

As for your suggestion for an average source, how does the response time + hysteresis doesn't already cover your use case?

**Comment by Sparkerino1** [comment]
Maybe I don't properly understand how the hysteresis + response time function works? Assuming I get 10 values over 10 seconds, 55, 55, 55, 55, 65, 55, 55, 55, 55, 55 and a fan threshold to spin up past 60C. If I have hysteresis set to 8C, and a response time of 5 seconds, on that 5th second, won't it grab the 65 value and then spin up the fans until it checks in again at the 10 second part? On the other side, with an average value over 10 seconds, the value is 56 C and the fans won't spin up.  This is obviously an oversimplified scenario, but does this make sense?

**Comment by Rem0o** [comment]
Hysteresis 8 and response time 5 means your temperature needs to be changed 8 degree from the last point for 5 **consecutive** seconds. In your scenario, the 65 degree will get ignored because it would need to be ( 55 + 8 ) or above for 5 consecutive seconds for the fans to spin up.

**Comment by Sparkerino1** [comment]
Gotcha. That makes sense. I'll close this issue then.
