### ISSUE TITLE
Featurerequest: Custom Sensor - Mix should have <fixed value>

### ISSUE THREAD

**Issue by sheepchen** [Rem0o/FanControl.Releases#450]
"Mix" custom sensor has: Average, Max, Mix, Sum, Substract.

All of these use sensordata to do its operation. However it is not possible to work with fixed values.

Example: I want a sensor that returns 15°C below CPU(Tdie) for MAX it with my GPU to control the airflow as a whole.
(CPU 85°C and GPU 70°C should be the same for the MAX sensor)

Either "sustract" should take a fixed value or there should be the option "fixed value" as a mixed sensor so I it is possible to create a custom sensor "15°C" and then create a sensor Subtract(CPU,15°C)

**Comment by sctanf** [comment]
Try adding a custom sensor file with a fixed temperature

**Comment by Rem0o** [comment]
You can also mix curves, not just sensors. Create a curve per sensor you care about, then mix these curves. 
That's the "intended" way to handle a gpu + cpu scenario.
