### ISSUE TITLE
Featurerequest: Timegraphs

### ISSUE THREAD

**Issue by sheepchen** [Rem0o/FanControl.Releases#451]
It would be nice to have a new section with time/temperature-
graphs.
You create a graph of a chosen temperature-sensor that plots the last x minutes of this sensor.

Settings: Sensor, min, max, time
Sensor: the chosen sensor
min: the lowest temperature for the graph to render
max: the highest temperature for the graph to render
time: how long does the graph reach back in time

**Comment by Rem0o** [comment]
Got multiple similar request to this, and the answer is no. 
I don't intend for fan control to be a monitoring software, and so adding anything related to this kind of features would be bloat in that regards. There are already great monitoring softwares, and I don't intend to go in that direction for now.

**Comment by kamenminkov** [comment]
That's a valid point. My only concern would be two things running simultaneously interfering with each other. For example I've seen OpenHardwareMonitor cause problems for AISuite before.

**Comment by sheepchen** [comment]
> That's a valid point. My only concern would be two things running simultaneously interfering with each other. For example I've seen OpenHardwareMonitor cause problems for AISuite before.

There would be no conflict because the software allready has the data to show you. At the moment it just has the current value and doesn't store the old ones. Would be nice to see the last 5 or ten minutes to see how the system was a few minutes before. But this featurerequest is denied.

**Comment by kamenminkov** [comment]
> > That's a valid point. My only concern would be two things running simultaneously interfering with each other. For example I've seen OpenHardwareMonitor cause problems for AISuite before.
> 
> There would be no conflict because the software allready has the data to show you. At the moment it just has the current value and doesn't store the old ones. Would be nice to see the last 5 or ten minutes to see how the system was a few minutes before. But this featurerequest is denied.

It's theoretically a similar situation with AISuite & OHM and yet it has caused some issues (thankfully I have a beefy enough cooler to sustain some load even with the fan turned down).

As for stats, you can set up a time average custom sensor watching a temperature of your choosing over several minutes (and you don't need to hook it up to anything - it can be there just informatively) - it's not a graph, but it's still somewhat indicative.
