### ISSUE TITLE
GUI: there should be no <Edit> button in the Curves

### ISSUE THREAD

**Issue by sheepchen** [Rem0o/FanControl.Releases#452]
The <Edit> button on each curve should be a submenu of this curve options (3 dots).
This will free up some space. 

If you put the current temperature inside the right down corner of the graph then the Curve-tiles can be way shorter

**Comment by Rem0o** [comment]
I want the discoverability of the edit button to be as high as possible, since it is necessary to go through it to create a curve. Hiding it in a submenu would be terrible UX.
