### ISSUE TITLE
Unable to enter a negative sign in front of existing fan offset value

### ISSUE THREAD

**Issue by kccricket** [Rem0o/FanControl.Releases#459]
If a fan offset field contains a value greater than zero, the input field will not allow the user to place a negative sign (hyphen) in front of the existing value. The user can only enter a negative value if the field is empty or by using the increment/decrement controls.

Steps to reproduce:

1. Expand the advanced settings within a Fan Control card.
2. Enter "10" into the "Offset" input field.
3. Move the text input caret to the beginning of the field.
4. Press the hyphen key on your keyboard.

Actual Result: A hyphen/negative sign does not appear in the text field.

Expected Result: A hyphen/negative sign should appear in the text field.

**Comment by Rem0o** [comment]
Good catch, will fix.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V101
