### ISSUE TITLE
Temperature delta

### ISSUE THREAD

**Issue by geekyed** [Rem0o/FanControl.Releases#46]
I’m not sure if the software will detect sensors that plug in to a motherboard and can’t test as I don’t have one yet.  It if they did, would you consider adding a temperature source of the temperature delta between two sensors, for example an inline water temp vs room temperature. Thanks for all the hard work!

**Comment by Korkman** [comment]
This could be implemented together with #44. Have a virtual temperature sensor and instead of max. or avg., select subtract as the function.

**Comment by Rem0o** [comment]
Closing since it would be done in the same go as #44
