### ISSUE TITLE
v100, it pops up every time you close the window even though you haven't changed anything.

### ISSUE THREAD

**Issue by balganmeongge** [Rem0o/FanControl.Releases#462]
Thank you for making such a good program.

A problem that didn't exist in v99.
There's no problem with the default settings after initialization.
A problem only occurs in the json I was using.
Below is the content of my CUSTOM.json.

{
  "Main": {
    "Controls": [
      {
        "CancelMatchFanCommand": null,
        "Enable": true,
        "Identifier": "/gpu-amd/0/control/0",
        "IsHidden": false,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": {
          "Identifier": "/gpu-amd/0/fan/0",
          "IsHidden": true,
          "Name": "GPU Fan",
          "NickName": "GPU Fan"
        },
        "Name": "GPU Fan",
        "NickName": "GPU Fan",
        "SelectedCommandStepDown": 0.2,
        "SelectedCommandStepUp": 1.0,
        "SelectedFanCurve": {
          "Name": "GPU",
          "OneWayHysteresis": true,
          "Points": [
            "50,15",
            "80,70",
            "120,100"
          ],
          "SelectedHysteresis": 2,
          "SelectedIndex": 0,
          "SelectedIndexTemp": 50.0,
          "SelectedIndexValue": 15.0,
          "SelectedResponseTime": 2,
          "SelectedTempSource": {
            "Identifier": "/gpu-amd/0/temperature/0",
            "IsHidden": false,
            "Name": "GPU Core"
          }
        },
        "SelectedOffset": 0,
        "SelectedStart": 6,
        "SelectedStop": 0
      },
      {
        "CancelMatchFanCommand": null,
        "Enable": true,
        "Identifier": "/lpc/nct6798d/control/0",
        "IsHidden": false,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": {
          "Identifier": "/lpc/nct6798d/fan/0",
          "IsHidden": true,
          "Name": "Fan #1",
          "NickName": "Fan #1"
        },
        "Name": "Fan Control #1",
        "NickName": "BACK #1",
        "SelectedCommandStepDown": 0.5,
        "SelectedCommandStepUp": 1.0,
        "SelectedFanCurve": {
          "Name": "SYSFAN",
          "OneWayHysteresis": true,
          "Points": [
            "60,30",
            "70,100"
          ],
          "SelectedHysteresis": 2,
          "SelectedIndex": 0,
          "SelectedIndexTemp": 60.0,
          "SelectedIndexValue": 30.0,
          "SelectedResponseTime": 2,
          "SelectedTempSource": {
            "Identifier": "Mix/Mix",
            "Name": "Mix",
            "SelectedMixFunction": 1,
            "SelectedSensors": [
              {
                "Identifier": "/amdcpu/0/temperature/2",
                "IsHidden": false,
                "Name": "Core (Tctl/Tdie)"
              },
              {
                "Identifier": "/gpu-amd/0/temperature/0",
                "IsHidden": false,
                "Name": "GPU Core"
              }
            ]
          }
        },
        "SelectedOffset": 0,
        "SelectedStart": 0,
        "SelectedStop": 0
      },
      {
        "CancelMatchFanCommand": null,
        "Enable": true,
        "Identifier": "/lpc/nct6798d/control/1",
        "IsHidden": false,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": {
          "Identifier": "/lpc/nct6798d/fan/1",
          "IsHidden": true,
          "Name": "Fan #2",
          "NickName": "Fan #2"
        },
        "Name": "Fan Control #2",
        "NickName": "CPU #2",
        "SelectedCommandStepDown": 1.0,
        "SelectedCommandStepUp": 2.0,
        "SelectedFanCurve": {
          "Name": "CPU",
          "OneWayHysteresis": true,
          "Points": [
            "60,50",
            "70,100"
          ],
          "SelectedHysteresis": 2,
          "SelectedIndex": 0,
          "SelectedIndexTemp": 60.0,
          "SelectedIndexValue": 50.0,
          "SelectedResponseTime": 2,
          "SelectedTempSource": {
            "Identifier": "/amdcpu/0/temperature/2",
            "IsHidden": false,
            "Name": "Core (Tctl/Tdie)"
          }
        },
        "SelectedOffset": 0,
        "SelectedStart": 0,
        "SelectedStop": 0
      },
      {
        "CancelMatchFanCommand": null,
        "Enable": true,
        "Identifier": "/lpc/nct6798d/control/2",
        "IsHidden": false,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": {
          "Identifier": "/lpc/nct6798d/fan/2",
          "IsHidden": true,
          "Name": "Fan #3",
          "NickName": "Fan #3"
        },
        "Name": "Fan Control #3",
        "NickName": "FRONT #3",
        "SelectedCommandStepDown": 0.5,
        "SelectedCommandStepUp": 1.0,
        "SelectedFanCurve": {
          "Name": "SYSFAN",
          "OneWayHysteresis": true,
          "Points": [
            "60,30",
            "70,100"
          ],
          "SelectedHysteresis": 2,
          "SelectedIndex": 0,
          "SelectedIndexTemp": 60.0,
          "SelectedIndexValue": 30.0,
          "SelectedResponseTime": 2,
          "SelectedTempSource": {
            "Identifier": "Mix/Mix",
            "Name": "Mix",
            "SelectedMixFunction": 1,
            "SelectedSensors": [
              {
                "Identifier": "/amdcpu/0/temperature/2",
                "IsHidden": false,
                "Name": "Core (Tctl/Tdie)"
              },
              {
                "Identifier": "/gpu-amd/0/temperature/0",
                "IsHidden": false,
                "Name": "GPU Core"
              }
            ]
          }
        },
        "SelectedOffset": 10,
        "SelectedStart": 0,
        "SelectedStop": 0
      },
      {
        "CancelMatchFanCommand": null,
        "Enable": false,
        "Identifier": "/lpc/nct6798d/control/3",
        "IsHidden": false,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": {
          "Identifier": "/lpc/nct6798d/fan/3",
          "IsHidden": true,
          "Name": "Fan #4",
          "NickName": "Fan #4"
        },
        "Name": "Fan Control #4",
        "NickName": "SPOT #4",
        "SelectedCommandStepDown": 8.0,
        "SelectedCommandStepUp": 8.0,
        "SelectedFanCurve": null,
        "SelectedOffset": 0,
        "SelectedStart": 0,
        "SelectedStop": 0
      },
      {
        "CancelMatchFanCommand": null,
        "Enable": false,
        "Identifier": "/lpc/nct6798d/control/4",
        "IsHidden": true,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": null,
        "Name": "Fan Control #5",
        "NickName": "Fan Control #5",
        "SelectedCommandStepDown": 8.0,
        "SelectedCommandStepUp": 8.0,
        "SelectedFanCurve": null,
        "SelectedOffset": 0,
        "SelectedStart": 0,
        "SelectedStop": 0
      },
      {
        "CancelMatchFanCommand": null,
        "Enable": true,
        "Identifier": "/lpc/nct6798d/control/5",
        "IsHidden": false,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": {
          "Identifier": "/lpc/nct6798d/fan/5",
          "IsHidden": true,
          "Name": "Fan #6",
          "NickName": "Fan #6"
        },
        "Name": "Fan Control #6",
        "NickName": "PUMP #6",
        "SelectedCommandStepDown": 5.0,
        "SelectedCommandStepUp": 10.0,
        "SelectedFanCurve": {
          "Name": "CPU",
          "OneWayHysteresis": true,
          "Points": [
            "60,50",
            "70,100"
          ],
          "SelectedHysteresis": 2,
          "SelectedIndex": 0,
          "SelectedIndexTemp": 60.0,
          "SelectedIndexValue": 50.0,
          "SelectedResponseTime": 2,
          "SelectedTempSource": {
            "Identifier": "/amdcpu/0/temperature/2",
            "IsHidden": false,
            "Name": "Core (Tctl/Tdie)"
          }
        },
        "SelectedOffset": 20,
        "SelectedStart": 0,
        "SelectedStop": 0
      },
      {
        "CancelMatchFanCommand": null,
        "Enable": false,
        "Identifier": "/lpc/nct6798d/control/6",
        "IsHidden": true,
        "ManualControl": false,
        "ManualControlValue": 50,
        "MatchingFanSensor": null,
        "Name": "Fan Control #7",
        "NickName": "Fan Control #7",
        "SelectedCommandStepDown": 8.0,
        "SelectedCommandStepUp": 8.0,
        "SelectedFanCurve": null,
        "SelectedOffset": 0,
        "SelectedStart": 0,
        "SelectedStop": 0
      }
    ],
    "CustomSensors": [
      {
        "Identifier": "Mix/Mix",
        "Name": "Mix",
        "SelectedMixFunction": 1,
        "SelectedSensors": [
          {
            "Identifier": "/amdcpu/0/temperature/2",
            "IsHidden": false,
            "Name": "Core (Tctl/Tdie)"
          },
          {
            "Identifier": "/gpu-amd/0/temperature/0",
            "IsHidden": false,
            "Name": "GPU Core"
          }
        ]
      }
    ],
    "DisplayTrayIconTemperature": false,
    "FanCurves": [
      {
        "Name": "CPU",
        "OneWayHysteresis": true,
        "Points": [
          "60,50",
          "70,100"
        ],
        "SelectedHysteresis": 2,
        "SelectedIndex": 0,
        "SelectedIndexTemp": 60.0,
        "SelectedIndexValue": 50.0,
        "SelectedResponseTime": 2,
        "SelectedTempSource": {
          "Identifier": "/amdcpu/0/temperature/2",
          "IsHidden": false,
          "Name": "Core (Tctl/Tdie)"
        }
      },
      {
        "Name": "GPU",
        "OneWayHysteresis": true,
        "Points": [
          "50,15",
          "80,70",
          "120,100"
        ],
        "SelectedHysteresis": 2,
        "SelectedIndex": 0,
        "SelectedIndexTemp": 50.0,
        "SelectedIndexValue": 15.0,
        "SelectedResponseTime": 2,
        "SelectedTempSource": {
          "Identifier": "/gpu-amd/0/temperature/0",
          "IsHidden": false,
          "Name": "GPU Core"
        }
      },
      {
        "Name": "SYSFAN",
        "OneWayHysteresis": true,
        "Points": [
          "60,30",
          "70,100"
        ],
        "SelectedHysteresis": 2,
        "SelectedIndex": 0,
        "SelectedIndexTemp": 60.0,
        "SelectedIndexValue": 30.0,
        "SelectedResponseTime": 2,
        "SelectedTempSource": {
          "Identifier": "Mix/Mix",
          "Name": "Mix",
          "SelectedMixFunction": 1,
          "SelectedSensors": [
            {
              "Identifier": "/amdcpu/0/temperature/2",
              "IsHidden": false,
              "Name": "Core (Tctl/Tdie)"
            },
            {
              "Identifier": "/gpu-amd/0/temperature/0",
              "IsHidden": false,
              "Name": "GPU Core"
            }
          ]
        }
      }
    ],
    "FanSensors": [
      {
        "Identifier": "/gpu-amd/0/fan/0",
        "IsHidden": true,
        "Name": "GPU Fan",
        "NickName": "GPU Fan"
      },
      {
        "Identifier": "/lpc/nct6798d/fan/0",
        "IsHidden": true,
        "Name": "Fan #1",
        "NickName": "Fan #1"
      },
      {
        "Identifier": "/lpc/nct6798d/fan/1",
        "IsHidden": true,
        "Name": "Fan #2",
        "NickName": "Fan #2"
      },
      {
        "Identifier": "/lpc/nct6798d/fan/2",
        "IsHidden": true,
        "Name": "Fan #3",
        "NickName": "Fan #3"
      },
      {
        "Identifier": "/lpc/nct6798d/fan/3",
        "IsHidden": true,
        "Name": "Fan #4",
        "NickName": "Fan #4"
      },
      {
        "Identifier": "/lpc/nct6798d/fan/4",
        "IsHidden": false,
        "Name": "Fan #5",
        "NickName": "Fan #5"
      },
      {
        "Identifier": "/lpc/nct6798d/fan/5",
        "IsHidden": true,
        "Name": "Fan #6",
        "NickName": "Fan #6"
      },
      {
        "Identifier": "/lpc/nct6798d/fan/6",
        "IsHidden": false,
        "Name": "Fan #7",
        "NickName": "Fan #7"
      }
    ],
    "HideFanSpeedCards": true,
    "HorizontalUIOrientation": false,
    "PrimaryColor": "#FF607D8B",
    "SecondaryColor": "#FFAEEA00",
    "SelectedTheme": "",
    "SelectedTrayIconSensor": null,
    "ShowHiddenCards": false,
    "StartMinimized": true,
    "SyncThemeWithWindows": false
  },
  "Sensors": {
    "DisabledPlugins": [],
    "DisableStorageSensors": false,
    "LibreHardwareMonitorSettings": {
      "Controller": false,
      "CPU": true,
      "GPU": true,
      "Memory": true,
      "Motherboard": true,
      "PSU": false,
      "Storage": true
    },
    "NvAPIWrapperSettings": {
      "Enabled": true
    }
  }
}

**Comment by Rem0o** [comment]
Can you diff it with this https://text-compare.com/ and see what props the change?

**Comment by balganmeongge** [comment]
"your current configuration changed. do you want to save your current configuration?"  It keeps popping up even if I don't change it
![fancontrol](https://user-images.githubusercontent.com/97315780/148615457-777d40e7-ef45-4581-8d58-58a88ac042da.png)
.

**Comment by Rem0o** [comment]
I know, something is up. This is why I want you to diff the json before and after you save, so we can see which property triggers this popup.

**Comment by balganmeongge** [comment]
v101.. Still the same

https://user-images.githubusercontent.com/97315780/149427374-bf87d4fc-8cdb-46e9-a7e9-de9ecaa9b090.mp4

.

**Comment by Rem0o** [comment]
Can you send the json before and after a save?
