### ISSUE TITLE
FanControl installed but doesn't pop up

### ISSUE THREAD

**Issue by KotonoHanako** [Rem0o/FanControl.Releases#463]
Hello
I have FanControl installed and I extracted it to my downloads folder. I then opened the folder, click FanControl.exe, but nothing pops up. Opening task manager shows that it is up only as a background process. 
Am I doing something wrong?

**Comment by Rem0o** [comment]
Windows 10 or 11?

**Comment by KotonoHanako** [comment]
Windows 8.1

**Comment by KotonoHanako** [comment]
> Windows 10 or 11?

Sorry, windows 8,1

**Comment by Rem0o** [comment]
Not supported. Upgrade to 10 or 11
