### ISSUE TITLE
RPM readout update for zero RPM missing

### ISSUE THREAD

**Issue by Korkman** [Rem0o/FanControl.Releases#47]
Not sure if this is LibreHardwareMonitor or FanControl, but for my Asus X99-E Mainboard the RPM readout stops updating on the last non-zero readout when setting the fans to zero RPM. The effect being that those fans never get to display zero RPM.

Edit: Other software does display 0 RPM for them.

**Comment by Rem0o** [comment]
Pretty sure that's a Libre behavior. You can confirm using the stand-alone version.

**Comment by Korkman** [comment]
Didn't realize they have a build to download! Confirmed, it is a bug in LibreHardwareMonitor, opened a [new issue there](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/313), moving on
