### ISSUE TITLE
Can add gpu memory junction temp as temp source?

### ISSUE THREAD

**Issue by JayvnTJ** [Rem0o/FanControl.Releases#474]
Thanks a lot for creating such a useful app. It is really helpful in PC system cooling.  You know the RTX3090 has a high memory junction temp. So can u add this or hot spot temp as  temp source as well?  Expect your new update version including this function.  Your creation is the best fun control app that have ever met.  Thanks again.

**Comment by Rem0o** [comment]
First, see "Issues and hardware compatibility" in the README.

There is no official documentation from Nvidia on how to get that sensor's data. No idea how the other programs do it.

These are the libraries used to pull sensor data.

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
https://github.com/falahati/NvAPIWrapper

Closing.

**Comment by coworo** [comment]
@Rem0o Im not sure if something got updated between jan 17 and now but Libre Hardware Monitor v0.8.9 does pull memory junction temps. They are not accessible in FanControl unfortunately, would it be possible for you take a another look? It would be a pretty an excellent feature for owners of gpus with poor memory cooling (coughgigabytecoug)

**Comment by Rem0o** [comment]
Make sure you got NvApiWrapper disabled and "GPU" ticked under LHM in the sensor setting menu.

**Comment by coworo** [comment]
> Make sure you got NvApiWrapper disabled and "GPU" ticked under LHM in the sensor setting menu.

![image](https://user-images.githubusercontent.com/98850730/159950329-b8c5ca0f-925c-40e5-ae40-6bca429fda34.png)

Couldnt get it to read gpu like this. Found NvThermalSensors plugin in some other issue page and that works, but just native program doesnt for your information.

**Comment by coworo** [comment]
It seems to be fixed in v108. Thanks for the project.

**Comment by MonsieurKas** [comment]
> > Make sure you got NvApiWrapper disabled and "GPU" ticked under LHM in the sensor setting menu.
> 
> ![image](https://user-images.githubusercontent.com/98850730/159950329-b8c5ca0f-925c-40e5-ae40-6bca429fda34.png)
> 
> Couldnt get it to read gpu like this. Found NvThermalSensors plugin in some other issue page and that works, but just native program doesnt for your information.

this worked for me, now have core, mem junction and hotspot.
