### ISSUE TITLE
Artic ARGB 360

### ISSUE THREAD

**Issue by ironpink227** [Rem0o/FanControl.Releases#477]
hi, I have a problem with arctic argb 360.
Mmy AIO system (Artic ARGB 360) has only one PWM connector which I connect to the MB (PCU fan - not AIO fan) - https://support.arctic.de/lf2-360-argbr1
This AIO automatically manage the fans and pump. So when I try to setup the AIO in Fancontrol, my system (Asus TUF x570) only recognizes the pump fan and not the radiator fans (which it turns off).
it would be useful to fix the bug.
thanks raffaele

**Comment by Rem0o** [comment]
FanControl works with 1 header = 1 control. It's not a bug.

**Comment by ironpink227** [comment]
I can understand but my AIO doesn't think so. the pump works, the radiator fans do not.
also, when I align the sensor, the AIO tab turns gray and is unusable. I don't know if it's a bug but that's what it looks like.

finally is there a chance to set a curve based on chipset temp? if so, what I have to do?

tx
raffaele
