### ISSUE TITLE
v101 won't open

### ISSUE THREAD

**Issue by Gabeverd** [Rem0o/FanControl.Releases#484]
When I first downloaded fan control it worked perfectly (not sure which version it was), then at some point it just stopped opening. When I try to open the application it looks like it's booting, then it closes automatically. As far as I remember there was no update to the software or windows right before this issue, it just started. I've tried the most recent version of fan control as well as several older versions with no luck. Log file attached.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/7916502/log.txt)

**Comment by Rem0o** [comment]
Make sure you run it as an admin user?

**Comment by Gabeverd** [comment]
Just tried, no change

**Comment by Rem0o** [comment]
Windows version? 10 or 11?

**Comment by Gabeverd** [comment]
Windows 10.

**Comment by Rem0o** [comment]
Any anti-virus software that might block it?

**Comment by Gabeverd** [comment]
I have a free version of Norton Security that just scans for threats, it doesn't block anything.

**Comment by Rem0o** [comment]
Well it might still block it, AV softwares are always full of surprises. Try deactivating it.

 Otherwise anything in EventViewer? I need to kind of lead to help you out.

**Comment by Gabeverd** [comment]
Found the issue in event viewer, there was a conflict with riva statistics tuner. I uninstalled and restarted, appears to have fixed the issue.

Thanks for your help! Big fan of the software.
