### ISSUE TITLE
Getting BSoD right after booting the PC

### ISSUE THREAD

**Issue by Mineplayerminer** [Rem0o/FanControl.Releases#485]
I get a BSoD every time I boot my PC and start the FanControl. But, when I wait like 10 minutes and then start it, no crash occurs. I looked into the Even viewer and there is always a driver error.

**Comment by Rem0o** [comment]
Mind sharing said driver error?

**Comment by Mineplayerminer** [comment]
> Mind sharing said driver error?

I think I fixed it. Looks like starting the RGBFusion 2.0 and the Fan Control at the same time don't like the driver. I'll try uninstalling the SIV. I'm using the stock Gigabyte programs. I'm on Windows 10 2004 (can't get the 12-2021 security patch update to work)
![image](https://user-images.githubusercontent.com/82465758/151964481-0a203c2f-0be0-4185-8ea2-c19b9a3327bf.png)
