### ISSUE TITLE
Fan Control v101 was marked as unsafe by Malwarebytes

### ISSUE THREAD

**Issue by fuongbregas** [Rem0o/FanControl.Releases#486]
I think it was false alarm and added the folder to the Allow List, but I think it should be known

**Comment by slix** [comment]
Same issue. A scan tonight detected FanControl as malware.

**Comment by slix** [comment]
VirusTotal still marks Malwarebytes as "Undetected". Maybe this virus database update is so recent that VirusTotal isn't updated yet.

https://www.virustotal.com/gui/file/c4463085b4e95980d318ea172f4edf6b2c3a2136e2f28b0e3f78e747ae48fce2

**Comment by slix** [comment]
The identifier is `Malware.AI.1699155215` . Which links to https://blog.malwarebytes.com/detections/malware-ai/

**Comment by slix** [comment]
I don't think my version was v101, but I'm not sure. This may affect multiple versions of FanControl.

**Comment by SparkBoys** [comment]
v100 as well.

**Comment by zackoch** [comment]
I've decompiled and examined the executables - **I don't see anything to be concerned about.**

I suspect mb doesn't like the updater call to the bit.ly address. 

That being said - is there a reason why the source isn't made public? This isn't a shot at the maintainer, they've given no reason not to be trustworthy, I just am not a huge fan of github hosted 'precompiled' software repos. If there's no opposition I'd ask that the source be published along with the releases.

**Comment by Rem0o** [comment]
@zackoch if you are curious, I use the bitly link to track the update count and that’s it.

**Comment by zackoch** [comment]
> @zackoch if you are curious, I use the bitly link to track the update count and that’s it.

I figured that's what it was for, also saw the fallback.

Appreciate the software mate!

**Comment by Rem0o** [comment]
If anybody with malware byte wants to submit it for a false positive submission, feel free: https://support.malwarebytes.com/hc/en-us/articles/360038524154-Report-a-false-positive-to-Malwarebytes-Support.

**Comment by slix** [comment]
After an update to Malwarebytes, FanControl is no longer being stopped or put into quarantine. A scan on FanControl gives no warnings.
