### ISSUE TITLE
Feature request: additional parameter sources

### ISSUE THREAD

**Issue by rainmasak** [Rem0o/FanControl.Releases#487]
Just an idea, but I'll leave it here. 
Add an ability to monitor some other parameter too (in addition to temperature). Like load %, wattage?

Where it might come in handy? - I have a water loop that is currently only cooling my GPU. I would like to turn off the pump if GPU is in pretty much idle state. If I try to do that with temperatures, then while gaming the pump works in intervals, as it pushes water through GPU, the temps will almost instantly drop and therefore shut down the pump. I'm sure it could have some other usages too, like load % in conjunction with temperature or something like that.

**Comment by Rem0o** [comment]
Did you try the target fan curve? 
Set the load temp pretty high as a starting point for your pump to start, and an idle temp for your pump to shut off, it should be able to do what you want without oscillations between on and off all the time.

**Comment by rainmasak** [comment]
Target curve actually works perfectly. Thank you!
