### ISSUE TITLE
Feature request: Kickstart

### ISSUE THREAD

**Issue by Korkman** [Rem0o/FanControl.Releases#49]
Some (most?) fans need a certain voltage to start spinning. When coming from effective 0% (after "Activation threshold" is applied), any non-zero value should trigger a "Kickstart" by applying 100% for a second.

This way a silent system can start spinning fans slowly instead of heating up to a point when fans will kick in at 80% or so.

Edit: To be clear, I have a CPU fan that requires about 95% to start, but then only 40% to keep going, ranging from 700rpm to 240rpm. I have never been able to set a sane zero RPM curve for this. With a kickstart function, it would be possible.

**Comment by arjeousski** [comment]
I think kickstart % should also be configurable, for example my case fans require ~35% to start but are they able to run down to 20%.

**Comment by sunbeam60** [comment]
One comment on the above - the kickstart should observe 0 RPM, not 0%, surely?

**Comment by Rem0o** [comment]
Feels like the "Activation threshold" as implemented right now is actually the "kickstart %" you guys are asking for. However, you then want to be able to use the range % below it that keeps the fan spinning on its momentum. Is that correct?

**Comment by arjeousski** [comment]
You are right, "Activation threshold" does seem like "kickstart %". I guess what would be great is to define "Minimum %" for each fan such that fan would not be requested to spin below that %. 

So if fan is @ 0, and its requested to go to value above Minimum, it would first go to Activation threshold, and then go down to requested %.

**Comment by Korkman** [comment]
I don't see activation threshold related to kickstart except for the naming. Activation threshold prevents the fan from spinning at low speeds, while kickstart is required to start at low speeds. I agree setting a percentage for kickstart as well would be sweet.

**Comment by Rem0o** [comment]
@Korkman yes it is important to not mix the concepts. Activation Threshold is that case would be "Spin up %"

**Comment by Korkman** [comment]
A checkbox in the three-dot-menu could do the trick. "Use activation threshold to spin up for low speeds" <- just shorter.

**Comment by arjeousski** [comment]
Maybe it would makes sense to expand the card a bit? I could see few other useful options (unrelated to this ticket) which could be useful. ie "Max %" per fan could go on the same line as Spin down %.

**Comment by sunbeam60** [comment]
At the risk at adding complexity to a discussion that seems to have settled, the simplest case (which may not be the simplest the implement) surely is: “Clamp % to operating range” and then automatically detecting if a fan needs a kickstart?

If RPM is 0 and %>0, keep adding % until RPM increases (this sets the spin up %). Similarly as % goes down, detect when RPM starts dropping rapidly (this sets the spin down %)

**Comment by Korkman** [comment]
@sunbeam60 That would make RPM detection mandatory for it to work. Not sure if that is a good thing.

@Rem0o Or just make a dialog, like the edit button for the fan curves.

**Comment by sunbeam60** [comment]
Ah good point; not everyone is on 4-pin fans.

**Comment by Rem0o** [comment]
Testing some layouts 
![image](https://user-images.githubusercontent.com/14118956/96918821-e4ab6180-1478-11eb-9ef3-ad180801f7ea.png)

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V54
