### ISSUE TITLE
Some controls missing - MSI X570

### ISSUE THREAD

**Issue by SnowDrifterr** [Rem0o/FanControl.Releases#490]
I'm using an MSI X570 MEG Unify, fan header 5 control doesn't work in this software. [Bios](https://www.msi.com/Motherboard/MEG-X570-UNIFY/support#down-bios) revision 7C35vAA (latest non-beta at time of writing). Running Win11

Manual control nets no change, and attempting to pair either manually/automatically with a given set of fans nets no result.

Also noting that 2 out of 3 fans are controllable on the GPU (EVGA 3080ti XC3). #1 in software corresponds to GPU fan 1, #2 in software controls to GPU fans  2 and 3

![image](https://user-images.githubusercontent.com/57574629/151418816-375fadc6-1bba-4250-9d65-c8f426f2af95.png)

**Comment by seanharsh** [comment]
Can confirm on the MEG ACE model as well. Fan Header 5 shows no sensor nor fan control.

**Comment by Rem0o** [comment]
Since this is hardware support related, closing.
