### ISSUE TITLE
No CPU Data

### ISSUE THREAD

**Issue by juno-v** [Rem0o/FanControl.Releases#492]
![image](https://user-images.githubusercontent.com/45371495/151692465-ca53e4dc-0771-469e-90b4-4b83119421b0.png)
![image](https://user-images.githubusercontent.com/45371495/151692472-0e86fa27-d7c0-4ef5-9a5e-2cb9413f6f4e.png)
![image](https://user-images.githubusercontent.com/45371495/151692517-7213c5bb-0e76-492a-b33f-b6f737a9bbda.png)
![image](https://user-images.githubusercontent.com/45371495/151692532-02429ec6-f0e2-498f-9408-8747bc3b8491.png)

Isn't there supposed to be one for CPU temps as well? What am I missing?

**Comment by juno-v** [comment]
MOBO : ASUS TUF X570 PRO WIFI 
GPU: 1080 8GB 
CPU: Ryzen 7 5800x

**Comment by Rem0o** [comment]
You need to create a fan curve and assign a sensor from the combo-box. Then assign that curve to one of the controls on the left.

**Comment by juno-v** [comment]
![image](https://user-images.githubusercontent.com/45371495/151738219-b5cd6616-d372-427f-ac96-f77e3eab3706.png)

ahh gotcha, which one is the one to monitor? there's 2 source options for CPU

**Comment by Rem0o** [comment]
Core (Tctl/tdie)

**Comment by juno-v** [comment]
Is there a shortcut that is created out of this? Or do I always have to run the fancontrol.exe file that is in the unzipped downloads folder?
