### ISSUE TITLE
Lian Li fans are detected but no speed sensor

### ISSUE THREAD

**Issue by Pascal51882** [Rem0o/FanControl.Releases#493]
On the speed sensors I only get RPM values for my pump and GPU. For my Lian Li Uni Fan SL I only get 0 RPM under fan. The Lian Li software detects the RPM correctly. The fans are connected via the Lian Li controller and PWM is enabled and connected to my mainboard. The control in % works so far. 
Without speed sensor I cant use any curves.

Has anyone had any experience with this?

**Comment by Rem0o** [comment]
You don't actually need the RPM readings to control your fans.
If assigning a curve with whatever % does indeed change your fans speeds, you are good. 

It probably can't read the RPMs because the program expects a single fan per header and you got a controller in between.

**Comment by Pascal51882** [comment]
Thank you that makes sense. There are 120 and 140mm fans with different RPMs mixed. I now see that my mainboard does also not know the real RPM. In general it works but I dont see the RPM.
