### ISSUE TITLE
Which Temp Sensor is which? Asus Crosshair VIII Hero

### ISSUE THREAD

**Issue by WanaGo** [Rem0o/FanControl.Releases#494]
Just wondering if you can help me identify which each of the reported temps are for the Asus Crosshair VIII Hero (WiFi). The listings give no indication of address or anything, and none of them really match anything in HWiNFO64, so really struggling to know what they are trying to represent.

![image](https://user-images.githubusercontent.com/759846/152228578-0538fc00-50bc-44c5-8750-adbd2cd9c03c.png)

Thanks

**Comment by Rem0o** [comment]
I can't. But a PR to add your mobo is present here:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/647

**Comment by WanaGo** [comment]
This has been done :) Ready to pull in to your project when you are ready. Thanks

**Comment by Rem0o** [comment]
In the mean time, if you got the LibreHardware dll compiled and ready, you can just replace the one fan control uses by it, it should just work.

**Comment by WanaGo** [comment]
Yep its already working, thanks.
Nice piece of software, thanks very much. Ill make a donation.
