### ISSUE TITLE
AIO pump header not seen by fan control

### ISSUE THREAD

**Issue by drosado1** [Rem0o/FanControl.Releases#5]
Description: 
The fan I have connected to my AIO Pump Header isn't seen by the app. My BIOS can control the AIO pump header no problem. LibreHardware also doesn't see my AIO Header, see (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/275) Hoping that this functionality gets supported somewhere down the line. 

My Setup:
ASUS ROG Strix B450i

**Comment by Rem0o** [comment]
As you mentionned, if LibreHardwareMonitor doesn't see, FanControl can't see it. Libre is used as the backend "driver" library for fan detection, control and so on.  As you opened an issue on Libre, I will close this one.
