### ISSUE TITLE
Detect fans activation automatically doesn't work

### ISSUE THREAD

**Issue by DMAgit** [Rem0o/FanControl.Releases#50]
When I try to use the "Detect fans activation automatically" feature it turns all of my fans to 0%, I can see they are physically off in the case, but the program says none of them ever fully turned off. 

The RPM readings seem to get stuck at some point during the turning off, because when they start going back on again they change to a lower value than they were before. For example:

Fan 1 | 50% -> 1000RPM
Fan 1 | 0% -> 723RPM (but physically off in case)
Fan 1 | 10% -> 300RPM (during ramp-up back to normal)
(values are random but also not relevant)

**Comment by Korkman** [comment]
This is probably the [bug](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/313) in the LibreHardwareMonitor library I happen to have [fixed](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/314) just yesterday. They will take some time to accept the pull request and make it a release.

You can fetch the compiled LibreHardwareMonitorLib.dll from the [build](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/314/checks?check_run_id=1270934560) and replace the

**Comment by Unr3aL** [comment]
The link to the build artifact doesn't work. Could you please check it?
If you're about to push an update anyways don't worry about it...

**Comment by Korkman** [comment]
@Rem0o the fix was merged. I highly recommend publishing a new release with the updated library, as this affects a whole family of sensors

**Comment by Rem0o** [comment]
@Korkman I will, already tested it.

**Comment by Rem0o** [comment]
Fixed with https://github.com/Rem0o/FanControl.Releases/releases/tag/V53
