### ISSUE TITLE
FanControl is preventing some drives from being ejected?

### ISSUE THREAD

**Issue by Ozzuneoj** [Rem0o/FanControl.Releases#504]
I have an internal SATA drive dock (not USB, just removable SATA) and for some reason FanControl is preventing drives from being ejected as long as FanControl is set to monitor Storage sensors.

I got these errors in Event Viewer when I try to eject a drive:

(Sorry, GitHub is butchering the formatting of these... I'll keep trying to find something that doesn't look so bad.)
________
`Log Name:      System
Source:        Microsoft-Windows-Kernel-PnP
Date:          2/11/2022 2:07:58 PM
Event ID:      225
Task Category: (223)
Level:         Warning
Keywords:      
User:          SYSTEM
Computer:      DESKTOP-UMA5U94
Description:
The application System with process id 4 stopped the removal or ejection for the device SCSI\Disk&Ven_HGST&Prod_HMS5C4040BLE640\7&2e1550d9&0&010000.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-PnP" Guid="{9c205a39-1250-487d-abd7-e831c6290539}" />
    <EventID>225</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>223</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-02-11T19:07:58.0164854Z" />
    <EventRecordID>9372</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="4416" />
    <Channel>System</Channel>
    <Computer>DESKTOP-UMA5U94</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="ProcessId">4</Data>
    <Data Name="ProcessNameLength">6</Data>
    <Data Name="ProcessName">System</Data>
    <Data Name="DeviceInstanceLength">59</Data>
    <Data Name="DeviceInstance">SCSI\Disk&amp;Ven_HGST&amp;Prod_HMS5C4040BLE640\7&amp;2e1550d9&amp;0&amp;010000</Data>
  </EventData>
</Event>`
_________
`Log Name:      System
Source:        Microsoft-Windows-Kernel-PnP
Date:          2/11/2022 2:07:58 PM
Event ID:      225
Task Category: (223)
Level:         Warning
Keywords:      
User:          SYSTEM
Computer:      DESKTOP-UMA5U94
Description:
The application \Device\HarddiskVolume3\Program Files\FanControl\FanControl.exe with process id 10144 stopped the removal or ejection for the device SCSI\Disk&Ven_HGST&Prod_HMS5C4040BLE640\7&2e1550d9&0&010000.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-PnP" Guid="{9c205a39-1250-487d-abd7-e831c6290539}" />
    <EventID>225</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>223</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-02-11T19:07:58.0164871Z" />
    <EventRecordID>9373</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="4416" />
    <Channel>System</Channel>
    <Computer>DESKTOP-UMA5U94</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="ProcessId">10144</Data>
    <Data Name="ProcessNameLength">63</Data>
    <Data Name="ProcessName">\Device\HarddiskVolume3\Program Files\FanControl\FanControl.exe</Data>
    <Data Name="DeviceInstanceLength">59</Data>
    <Data Name="DeviceInstance">SCSI\Disk&amp;Ven_HGST&amp;Prod_HMS5C4040BLE640\7&amp;2e1550d9&amp;0&amp;010000</Data>
  </EventData>
</Event>`
______

This is on Windows 10 Pro 21H2 using a Gigabyte X570 Aorus Elite motherboard. The drive in question is a 4TB HGST. If it matters, the drive was connected at system startup and FanControl is set to launch with Windows. 

I have a feeling it is related to FanControl trying to monitor the hard disk temperature... but I have no curves set up to watch the temperatures of any of my drives anyway. When I disable Storage sensors entirely it seems to fix the problem, but I feel like there should be a more elegant solution because I'm sure there are plenty of people that want to monitor storage temps but also use external drives that have sensors.

**Comment by Rem0o** [comment]
```
I have a feeling it is related to FanControl trying to monitor the hard disk temperature
```

It is.  But all drives are under the same umbrella from:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Storage/StorageGroup.cs

I don't have the required API to only enable internal drives.

**Comment by Ozzuneoj** [comment]
Is there a way to have FanContrl only enable sensors that are being used in curves? That would eliminate the problem, as most people wouldn't be actively cooling removable drives, so those sensors would never be monitored.
