### ISSUE TITLE
Unable to view curves menu

### ISSUE THREAD

**Issue by parapixology** [Rem0o/FanControl.Releases#505]
Hello!

For some reason I'm unable to open the curve dropdown menu. I can only see a little bit of the menu but not enough to click on it. I'm guessing it's an UI graphics issue     
<img width="189" alt="Screenshot 2022-02-11 175617" src="https://user-images.githubusercontent.com/99514246/153681867-bc3c10c6-40a8-41eb-921a-8d3b56ae03ea.png">

I'd appreciate any help.
Thanks!

**Comment by Rem0o** [comment]
Try and set your scaling to 100% and see if that's the issue?

**Comment by parapixology** [comment]
> Try and set your scaling to 100% and see if that's the issue?

Hi @Rem0o ,
Thanks for the reply! I tried scaling my resolution to 100% restarted Fan Control but still have this issue. I actually have the same issue on both of my machines. both are running windows 10 pro and I have 4k screens. Could that be the problem?

**Comment by Rem0o** [comment]
Stupid question, but did you actually created any curve?

**Comment by parapixology** [comment]
Is that not where you create the curve in the first place? Sorry but I thought that to create a curve you need to click on curves I'm just not able to click on it. I might not understand how to create a curve. Please let me know if there is anything else I should do

Thanks for the help on this

**Comment by Rem0o** [comment]
Use the big + button at the bottom right corner?

**Comment by parapixology** [comment]
Ha! That worked.. not very straight forward but it does work.
Thanks for all your help! I really appreciate it
