### ISSUE TITLE
Consider using Scoop for distribution

### ISSUE THREAD

**Issue by kamenminkov** [Rem0o/FanControl.Releases#506]
I've been using Scoop for some time now and I find it super useful for both installing known to me software and searching for new software (akin to APT and other package managers on GNU/Linux). Having FanControl there might help with the discoverability of it and with updating it (even though it has its own update mechanism, updating many apps in bulk is sometimes more convenient).

If you decide to go forward with this, here's how you get started: https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md

**Comment by JustCryen** [comment]
I've never heard of ScoopInstaller but it sounds very similar to Chocolatey.
https://chocolatey.org/
