### ISSUE TITLE
points not on line

### ISSUE THREAD

**Issue by illusionmanager** [Rem0o/FanControl.Releases#508]
I was playing around, moving curves to different positions in the grid, renaming them, etc when suddenly the points in the curves were no longer on the line it should follow. They still moved, but not following the line
![Untitled-1](https://user-images.githubusercontent.com/79637793/154244482-06c30cf9-d1bc-4b0d-b491-0412a991f76b.jpg)
.

**Comment by Rem0o** [comment]
Can you send me that specific config (the json) ?

**Comment by illusionmanager** [comment]
One other issue I found, but harder to reproduce, is that I have a flat curve set to 100% (to make some fan spin to a full 100%). Sometimes, but not always, when I apply that curve, the displayed percentage ramps up, but stops at something like 96.4% or some other number close to 100.

**Comment by Rem0o** [comment]
The point not on line issue is fixed in V105.

**Comment by illusionmanager** [comment]
But is the not-updating-to-final-value also fixed, which I mentioned is the
same issue?

**Comment by Rem0o** [comment]
That's a different issue. Open a new ticket for it. From the look of it, seems like you got something else controlling that header. Is it specific to that header?
