### ISSUE TITLE
[FEATURE] Combining two or more curves into new curve

### ISSUE THREAD

**Issue by shtefko** [Rem0o/FanControl.Releases#509]
With a custom loop water cooling setups it is often the case that the same cooling components are used to cool both CPU and GPU in the same time. This presents a challenge to create meaningful fan control curve, since both CPU and GPU might require cooling independently from each other.
Using a Mix Sensor with MAX function only partially helps with this issue, since both CPU and GPU can have different thermal requirements, and only truly helps when they both fall into same thermal envelope.
The new Curve control cold be very similar to Mix Sensor design, where you chose number of curves, and a function which works with results (duty cycle) of each curve, finally the fan control would use function result as duty cycle to apply on the fan.
Hope you find this suggestion useful.

**Comment by Rem0o** [comment]
Not sure I understand what you mean... 
Can you give a specific example, with numbers?  How do you "combine" the curves?  

You can already "sum" the curves, if you want take account for the sum of the heat output of both your GPU and CPU in your watercooling loop.

**Comment by shtefko** [comment]
I have a Ryzen 3900x, which has idle temps ~60 degrees C, and to keep the system quiet I don't want to spin the fans much until CPU temps reach 75-80 degrees. On the other hand my RTX 2080 Ti runs around 35 degrees idle, and I would like fans to spin when it reaches 65-70 degrees.
Summing value of these two sensors would not help me much, since if the sum was for example a 120, it could be that both are running fine (60+60), or that CPU is overheating while GPU idles (35+85).

**Comment by Rem0o** [comment]
Ah, then you want to use the "mix fan curve", not mix sensor.

**Comment by shtefko** [comment]
Oh, right, not sure how I missed that. Thank you!
