### ISSUE TITLE
Feature Request: Graph Page

### ISSUE THREAD

**Issue by dramamoose** [Rem0o/FanControl.Releases#511]
Hello, I'm wondering if it would be possible to put together a page which would allow the user to manually select items to place into a time series chart. It would be fantastic if these could scale so that we could show two dissimilar items on the same timeline; for example, see GPU temperature vs Case Fan Speed vs CPU Curve %.

I'm currently trying to diagnose some thermal issues and being able to see what my system has been doing over the last 24 hours of gaming/idling would be helpful.

**Comment by kamenminkov** [comment]
I was thinking about suggesting the same. Since the app is already using the LibreHardwareMonitor backend, it should be fairly possible to do. Temperature graphs for example would be pretty useful when tuning fans.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/451

**Comment by dramamoose** [comment]
Unfortunate! I'm trying to minimize how much software I have running in the background so looks like I'm still on the look for a fan control app. Thank you so much for your response!

**Comment by Rem0o** [comment]
Well, such feature would have to be scoped to fit the FanControl general idea. I'm not 100% agains't it, just haven't had a specific idea on how to integrate it with the rest of the software without it feeling bloaty.

**Comment by Zyarra** [comment]
> Well, such feature would have to be scoped to fit the FanControl general idea. I'm not 100% agains't it, just haven't had a specific idea on how to integrate it with the rest of the software without it feeling bloaty.

Just make it a button which opens the monitoring just like in MSI afterburner.
And all it does is X: Time, Y: fan speed//temp(selectable for which ones, like RTSS in afterburner)

**Comment by Rem0o** [comment]
Monitoring is out of scope for FanControl.  Might make it to another project in the future. Closing.
