### ISSUE TITLE
custom sensors not shown

### ISSUE THREAD

**Issue by illusionmanager** [Rem0o/FanControl.Releases#512]
just updated to the latest version, but now the custom sensors cannot be selected as a source in the graphs. The menu just shows empty entries for each of the custom sensors
![Untitled-1](https://user-images.githubusercontent.com/79637793/155092384-0718e024-9cf6-4af8-9075-7bde7775d969.jpg)

**Comment by protycon** [comment]
I am having the same issue. Although the issues seems to be only visual. You are still able to select the empty entries and they seem to work fine for me.
Deleting and re-configuring the custom sensors, did not fix this issue.

Not sure, if this helps to pinpoint the issue, but i get the following message, when trying to save the configuration to a new file:
![image](https://user-images.githubusercontent.com/85905052/155107255-a086d801-946b-4bb8-a369-67c558061149.png)

My custom sensors, seem to be missing.

**Comment by s-geissler** [comment]
Can confirm. The same issue occurs on my system using the latest version.

**Comment by Rem0o** [comment]
Yeah catched it, was just a display error. Pushed a fix.
