### ISSUE TITLE
Feature Suggestion: autosave configurations

### ISSUE THREAD

**Issue by derei** [Rem0o/FanControl.Releases#513]
I had done some changes to the parameters and i forgot to explicitly save the new configuration. Computer went into sleep mode later on and when it resumed, the (unsaved) changes were gone.

I suggest that any alteration to a configuration to be saved in a "working" file, the moment it is being done. Then, the Save operation should overwrite the ACTUAL Profile.json.

A way to implement this would be instead of directly loading the Profile.json directly into the app, its contents to be dumped in a secondary file, let's call that one "work", and it could be of a different format (altered extension, so it is only being used internally by the software, rather than a formal profile) ... and any alteration that is being made to the current configuration to be also saved in the "work" file. When the user is doing a Save command, then the content of "work" would be saved into Profile.json.
Also, when the software starts, it would load the content of "work". And when the user is doing a "Load Configuration" command, then the content of Profile.jsoon would be dumped into "work" file, from where the program would load them, instead of loading them directly... 

What this would accomplish: user would not lose settings due to forgetting to save them, machine failure, sleep mode, etc. It would also protect the saved profile (named here as Profile.json), so not only the current modifications would be persistent, but also the saved profile wouldn't actually be changed, until the user decides to.

**Comment by graz68a** [comment]
+

**Comment by Revadike** [comment]
Jay agrees https://www.youtube.com/watch?v=uDPKVKBMQU8&t=793s

**Comment by Rem0o** [comment]
Auto-Save has goods and bads. Not to sure about it just yet.

The main problem I see is people shutting down their pc without ever leaving the window. If you do close the window, it looks for change and ask for save.  

I will take a look if I can "pause" the PC shutdown if the software is open to ask for save.

I feel like that would cover most cases already.

**Comment by derei** [comment]
@Rem0o what about situations where computer shuts down accidentally (BSOD, overheating, etc)? This is why I suggested an approach that would write all settings on the fly as they are being changed, but without altering the saved configuration (so, in case of a bad config, to not corrupt what works already).

**Comment by Rem0o** [comment]
@derei  I guess it could auto-save to a temp json file also, like "backup.json".  Every 30 sec or so when the UI is open, or something like that.   Tracking every field for a change to trigger a save would be a pain.

**Comment by Revadike** [comment]
> Tracking every field

That would be the proper way to do it. Perhaps there exist a function in material design to select all input field and an input listener to it, just like a CSS selectors and JavaScript can do:
```js
[...document.querySelector("input")].forEach(input => input.addEventListener("input", saveConfigFn))
```

**Comment by derei** [comment]
I agree that tracking every change instantly could be difficult. Perhaps even slowing down the program or freezing it. If done so, it should be implemented when the field loses focus (or else it could trigger for every key press and that may be undesirable). Also, it should validate the input (so it won't save some invalid data, which could potentially even cause a vector of vulnerability).

Periodic autosave in a temp.json could be a good alternative too.

**Comment by Rem0o** [comment]
> I agree that tracking every change instantly could be difficult. Perhaps even slowing down the program or freezing it. If done so, it should be implemented when the field loses focus (or else it could trigger for every key press and that may be undesirable). Also, it should validate the input (so it won't save some invalid data, which could potentially even cause a vector of vulnerability).
> 
> Periodic autosave in a temp.json could be a good alternative too.

I already validate every meaningful field ( or so I think ), so that's covered. Will try a few things for the auto-save idea, stay tuned.

**Comment by Revadike** [comment]
> Perhaps there exist a function in material design to select all input fields and add an input listener to it, just like a CSS selectors and JavaScript can do:

Rem0o: If only. Try that in WPF. Also I don't only serialize "fields". The order of cards and everything is also important. Right now to check for change, I call my serialize function, get the json structure, then diff it with the one in your json file.

**Comment by Rem0o** [comment]
FanControl will now prevent log out or shutdown kinda like any other kther software if something needs to be saved.
