### ISSUE TITLE
Cant control fan speed using Gigabyte B560m Aorus Pro AX 

### ISSUE THREAD

**Issue by Solrackko** [Rem0o/FanControl.Releases#515]
As title says. I think this is because of the ITE IT8689E which from my understanding is not supported on fancontrol.
Anyone here thinks it's possible to add it in an update or make it compatible? New to github and have little to no understanding of coding.
Thanks for your time.

⬇️⬇️⬇️

Motherboard

SMBios Version: 3.3

BIOS Vendor: American Megatrends International, LLC.
BIOS Version: F8
BIOS Date: 31/08/2021
BIOS Size: 32 MB

System Manufacturer: Gigabyte Technology Co., Ltd.
System Name: B560M AORUS PRO AX
System Version: -CF
System Wakeup: PowerSwitch

Motherboard Manufacturer: Gigabyte Technology Co., Ltd.
Motherboard Name: B560M AORUS PRO AX
Motherboard Version: x.x
Motherboard Serial: Default string

Chassis Type: Desktop
Chassis Manufacturer: Default string
Chassis Version: Default string
Chassis Serial: Default string
Chassis Asset Tag: Default string
Chassis SKU: Default string
Chassis Boot Up State: Safe
Chassis Power Supply State: Safe
Chassis Thermal State: Safe
Chassis Power Cords: 1
Chassis Lock Detected: No
Chassis Security Status: None

Processor Manufacturer: Intel(R) Corporation
Processor Type: CentralProcessor
Processor Version: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
Processor Serial: To Be Filled By O.E.M.
Processor Socket Destignation: U3E1
Processor Socket: Other
Processor Version: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
Processor Family: IntelCoreI5
Processor Core Count: 6
Processor Core Enabled: 6
Processor Thread Count: 12
Processor External Clock: 100 Mhz
Processor Max Speed: 4400 Mhz
Processor Current Speed: 2574 Mhz

Cache [L1] Size: 288
Cache [L1] Associativity: 12Way

Cache [L1] Size: 192
Cache [L1] Associativity: 8Way

Cache [L2] Size: 3072
Cache [L2] Associativity: 8Way

Cache [L3] Size: 12288
Cache [L3] Associativity: 16Way

Memory Device [0] Manufacturer: 
Memory Device [0] Part Number: 
Memory Device [0] Device Locator: Controller0-ChannelA-DIMM0
Memory Device [0] Bank Locator: BANK 0
Memory Device [0] Speed: 0
Memory Device [0] Size: 0 MB

Memory Device [1] Manufacturer: Corsair
Memory Device [1] Part Number: CMK16GX4M2A2666C16
Memory Device [1] Device Locator: Controller0-ChannelA-DIMM1
Memory Device [1] Bank Locator: BANK 0
Memory Device [1] Speed: 2666
Memory Device [1] Size: 8192 MB

Memory Device [2] Manufacturer: 
Memory Device [2] Part Number: 
Memory Device [2] Device Locator: Controller0-ChannelB-DIMM0
Memory Device [2] Bank Locator: BANK 1
Memory Device [2] Speed: 0
Memory Device [2] Size: 0 MB

Memory Device [3] Manufacturer: Corsair
Memory Device [3] Part Number: CMK16GX4M2A2666C16
Memory Device [3] Device Locator: Controller0-ChannelB-DIMM1
Memory Device [3] Bank Locator: BANK 1
Memory Device [3] Speed: 2666
Memory Device [3] Size: 8192 MB

SMBios Table

 AAMDAPEXAAAAGgAAAQIA8AP/gJj7dwEAAAACDQUT//8gAEFtZXJpY2FuIE1lZ2F0
 cmVuZHMgSW50ZXJuYXRpb25hbCwgTExDLgBGOAAwOC8zMS8yMDIxAAABGwEAAQID
 BBgCwANNBNoF1AZgBwAIAAkGBQZHaWdhYnl0ZSBUZWNobm9sb2d5IENvLiwgTHRk
 LgBCNTYwTSBBT1JVUyBQUk8gQVgALUNGAERlZmF1bHQgc3RyaW5nAERlZmF1bHQg
 c3RyaW5nAEI1NjAgTUIAAAIPAgABAgMEBQkGAwAKAEdpZ2FieXRlIFRlY2hub2xv
 Z3kgQ28uLCBMdGQuAEI1NjBNIEFPUlVTIFBSTyBBWAB4LngARGVmYXVsdCBzdHJp
 bmcARGVmYXVsdCBzdHJpbmcARGVmYXVsdCBzdHJpbmcAAAMWAwABAwIDBAMDAwMA
 AAAAAAEAAwVEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0
 cmluZwBEZWZhdWx0IHN0cmluZwBEZWZhdWx0IHN0cmluZwAACAkEAAEAAg8OSjFB
 MQBQUzJNb3VzZQAACAkFAAEAAg8NSjFBMQBLZXlib2FyZAAACAkGAAEAAh3/SjJB
 MQBUViBPdXQAAAgJBwABAAIICUoyQTJBAENPTSBBAAAICQgAAQACBxxKMkEyQgBW
 aWRlbwAACAkJAAEAAhIQSjNBMQBVU0IxAAAICQoAAQACEhBKM0ExAFVTQjIAAAgJ
 CwABAAISEEozQTEAVVNCMwAACAkMAAH/AAD/SjlBMSAtIFRQTSBIRFIAAAgJDQAB
 /wAA/0o5QzEgLSBQQ0lFIERPQ0tJTkcgQ09OTgAACAkOAAH/AAD/SjJCMyAtIENQ
 VSBGQU4AAAgJDwAB/wAA/0o2QzIgLSBFWFQgSERNSQAACAkQAAH/AAD/SjNDMSAt
 IEdNQ0ggRkFOAAAICREAAf8AAP9KMUQxIC0gSVRQAAAICRIAAf8AAP9KOUUyIC0g
 TURDIElOVFBTUgAACAkTAAH/AAD/SjlFNCAtIE1EQyBJTlRQU1IAAAgJFAAB/wAA
 /0o5RTMgLSBMUEMgSE9UIERPQ0tJTkcAAAgJFQAB/wAA/0o5RTEgLSBTQ0FOIE1B
 VFJJWAAACAkWAAH/AAD/SjlHMSAtIExQQyBTSURFIEJBTkQAAAgJFwAB/wAA/0o4
 RjEgLSBVTklGSUVEAAAICRgAAf8AAP9KNkYxIC0gTFZEUwAACAkZAAH/AAD/SjJG
 MSAtIExBSSBGQU4AAAgJGgAB/wAA/0oyRzEgLSBHRlggVklEAAAICRsAAf8AAP9K
 MUc2IC0gQUMgSkFDSwAACREcAAGlDQQEAAAMAQAAAAhKNkIyAAAJER0AAaUIBAMB
 AAwBAAAA40o2QjEAAAkRHgABpQgEAwIADAEAAADkSjZEMQAACREfAAGlCAQDAwAM
 AQAAAOVKN0IxAAAJESAAAaUIBAMEAAwBAAAA5ko4QjQAAAoGIQCDASAgIFRvIEJl
 IEZpbGxlZCBCeSBPLkUuTS4AAAsFIgABRGVmYXVsdCBzdHJpbmcAAAwFIwABRGVm
 YXVsdCBzdHJpbmcAACAUJAAAAAAAAAAAAAAAAAAAAAAAAAAiCyUAAQQAAAAAA0xN
 NzgtMQAAGhYmAAFnAIAAgACAAIAAgAAAAAAAgExNNzhBAAAkECcAAQACAAMABAAF
 AAYAAAAjCygAASUAJgAnAERlZmF1bHQgc3RyaW5nAAAcFikAAWcAgACAAIAAgACA
 AAAAAACATE03OEEAACQQKgABAAIAAwAEAAUABgAAACMLKwABJQApACoARGVmYXVs
 dCBzdHJpbmcAABsPLAApAGcBAAAAAACAAUNvb2xpbmcgRGV2IDEAACQQLQABAAIA
 AwAEAAUABgAAACMLLgABJQAsAC0ARGVmYXVsdCBzdHJpbmcAABsPLwApAGcBAAAA
 AACAAAAAJBAwAAEAAgADAAQABQAGAAAAIwsxAAElAC8AMABEZWZhdWx0IHN0cmlu
 ZwAAHRYyAAFnAIAAgACAAIAAgAAAAAAAgEFCQwAAJBAzAACAAIAAgACAAIAAgAAA
 Iws0AAElADIAMwBEZWZhdWx0IHN0cmluZwAAGhY1AAFqAIAAgACAAIAAgAAAAAAA
 gExNNzhBAAAcFjYAAWoAgACAAIAAgACAAAAAAACATE03OEEAABsPNwA2AGcBAAAA
 AACAAUNvb2xpbmcgRGV2IDEAAB0WOAABagCAAIAAgACAAIAAAAAAAIBBQkMAACcW
 OQABAQIDBAUGBwCAohE1ADcAOABUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAFRvIEJl
 IEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBUbyBCZSBG
 aWxsZWQgQnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmls
 bGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAAAsCToA//8BAQAA
 ACsfOwBJTlRDAgAHAFgCAAAAAAIQAAAAAAAAAAAAAABUUE0gMi4wAElOVEVMAAAQ
 FzwAAwMDAAAABP7/BAAAAAAAAAAAAAAAEx9BAAAAAAD///8APAACAAAAAAAAAAAA
 AAAAAAAAAAAAEVxCADwA/v8AAAAAAAACAAECAgAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAABDb250cm9sbGVyMC1DaGFubmVsQS1ESU1NMABCQU5LIDAAOTg3NjU0MzIx
 MAAAEVxDADwA/v9AAEAAACAJAAECGoAAagoDBAUGAgAAAABqCrAEsASwBAMIAAAC
 ngAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABD
 b250cm9sbGVyMC1DaGFubmVsQS1ESU1NMQBCQU5LIDAAQ29yc2FpcgAwMDAwMDAw
 MAA5ODc2NTQzMjEwAENNSzE2R1g0TTJBMjY2NkMxNiAgAAARXEQAPAD+/wAAAAAA
 AAIAAQICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAENvbnRyb2xsZXIwLUNoYW5u
 ZWxCLURJTU0wAEJBTksgMQA5ODc2NTQzMjEwAAARXEUAPAD+/0AAQAAAIAkAAQIa
 gABqCgMEBQYCAAAAAGoKsASwBLAEAwgAAAKeAAAAAAAAAAAAAAAAAAAAAAAAAgAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAENvbnRyb2xsZXIwLUNoYW5uZWxCLURJ
 TU0xAEJBTksgMQBDb3JzYWlyADAwMDAwMDAwADk4NzY1NDMyMTAAQ01LMTZHWDRN
 MkEyNjY2QzE2ICAAABQjRgAAAAAA//9/AEMAQQD/AQIAAAAAAAAAAAAAAAAAAAAA
 AAAUI0cAAACAAP///wBFAEEA/wICAAAAAAAAAAAAAAAAAAAAAAAA3RpIAAMBAAsB
 LSAAAgAAAABAAAMAAQ4QAABSZWZlcmVuY2UgQ29kZSAtIENQVQB1Q29kZSBWZXJz
 aW9uAFRYVCBBQ00gdmVyc2lvbgAA3RpJAAMBAAsBLSAAAgAPAAACAAMEDwAWVgZS
 ZWZlcmVuY2UgQ29kZSAtIE1FAE1FQnggdmVyc2lvbgBNRSBGaXJtd2FyZSBWZXJz
 aW9uAENvbnN1bWVyIFNLVQAA3S9KAAYBAAsBLSAAAgP//////wQA////EQAFAP//
 /xEABgD//////wcABAAAAABSZWZlcmVuY2UgQ29kZSAtIFBDSABQQ0gtQ1JJRCBT
 dGF0dXMARGlzYWJsZWQAUENILUNSSUQgT3JpZ2luYWwgVmFsdWUAUENILUNSSUQg
 TmV3IFZhbHVlAE9QUk9NIC0gUlNUIC0gUkFJRABQQ0ggSHNpbyBWZXJzaW9uAADd
 UksACwEACwEtIAACAAAEYWIAAwALAS0gAAQF//////8GAAAAAAEABwAAAAABAAgA
 //////8JAP//////CgD//////wsA//////8MAAEBAQAAUmVmZXJlbmNlIENvZGUg
 LSBTQSAtIFN5c3RlbSBBZ2VudABSZWZlcmVuY2UgQ29kZSAtIE1SQwBTQSAtIFBD
 SWUgVmVyc2lvbgBTQS1DUklEIFN0YXR1cwBEaXNhYmxlZABTQS1DUklEIE9yaWdp
 bmFsIFZhbHVlAFNBLUNSSUQgTmV3IFZhbHVlAE9QUk9NIC0gVkJJT1MASU8gTWFu
 YWdlYWJpbGl0eSBFbmdpbmUgRlcgVmVyc2lvbgBQSFkgQnVpbGQgVmVyc2lvbgBU
 aHVuZGVyYm9sdChUTSkgRlcgVmVyc2lvbgBTeXN0ZW0gQWdlbnQgTWFuYWdlYWJp
 bGl0eSBFbmdpbmUgRlcgVmVyc2lvbgAA3QxMAAEBAAQAAAAARlNQIEJpbmFyeSBW
 ZXJzaW9uAAAHG00AAYABIAEgASAAIAAABAQJIAEAACABAABMMSBDYWNoZQAABxtO
 AAGAAcAAwAAgACAAAAQDB8AAAADAAAAATDEgQ2FjaGUAAAcbTwABgQEADAAMIAAg
 AAAFBQcADAAAAAwAAEwyIENhY2hlAAAHG1AAAYIBADAAMCAAIAAABgUIADAAAAAw
 AABMMyBDYWNoZQAABDBRAAEDzQJxBgoA//vrvwOIZAAwEQ4KQQFOAE8AUAAEBQYG
 Bgz8AM0ABgAGAAwAVTNFMQBJbnRlbChSKSBDb3Jwb3JhdGlvbgAxMXRoIEdlbiBJ
 bnRlbChSKSBDb3JlKFRNKSBpNS0xMTQwMEYgQCAyLjYwR0h6AFRvIEJlIEZpbGxl
 ZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQg
 QnkgTy5FLk0uAACDQFIAMQAAAA8AAAAAAAIA+ACHQwAAAAABAAAAAAAPAFYGFgAA
 AAAA/gD//wAAAAAAAAAAIgAAAHZQcm8AAAAAAAApC1MAAYEBAAAAAE9uYm9hcmQg
 LSBPdGhlcgAAKQtUAAGBAgAAAKBPbmJvYXJkIC0gT3RoZXIAACkLVQABgQMAAACi
 T25ib2FyZCAtIE90aGVyAAApC1YAAYEEAAAAsE9uYm9hcmQgLSBPdGhlcgAAKQtX
 AAGJAQAAALhPbmJvYXJkIC0gU0FUQQAAKQtYAAGBBQAAAPhPbmJvYXJkIC0gT3Ro
 ZXIAACkLWQABhwEAAAD7T25ib2FyZCAtIFNvdW5kAAApC1oAAYEGAAAA/E9uYm9h
 cmQgLSBPdGhlcgAAKQtbAAGBBwAAAP1PbmJvYXJkIC0gT3RoZXIAAN1SXAALAQD/
 /////wIA//////8DBP//////BQb//////wcI//////8JAAAAAAAACgD//////wsA
 //8AAAAMAAAXAFUQDQD//////w4AAAcAAABMYW4gUGh5IFZlcnNpb24AU2Vuc29y
 IEZpcm13YXJlIFZlcnNpb24ARGVidWcgTW9kZSBTdGF0dXMARGlzYWJsZWQAUGVy
 Zm9ybWFuY2UgTW9kZSBTdGF0dXMARGlzYWJsZWQARGVidWcgVXNlIFVTQihEaXNh
 YmxlZDpTZXJpYWwpAERpc2FibGVkAElDQyBPdmVyY2xvY2tpbmcgVmVyc2lvbgBV
 TkRJIFZlcnNpb24ARUMgRlcgVmVyc2lvbgBHT1AgVmVyc2lvbgBSb3lhbCBQYXJr
 IFZlcnNpb24AUGxhdGZvcm0gVmVyc2lvbgAAIAtdAAAAAAAAAAAAAA0WXgAOAAAA
 AAAAAAAAAAAAAAAAAAFlbnxVU3xpc284ODU5LTEAemh8VFd8dW5pY29kZQB6aHxD
 Tnx1bmljb2RlAHJ1fFJVfGlzbzg4NTktNQBkZXxERXxpc284ODU5LTEAamF8SlB8
 dW5pY29kZQBrb3xLUnx1bmljb2RlAGVzfEVTfGlzbzg4NTktMQBmcnxGUnxpc284
 ODU5LTEAcHR8UFR8aXNvODg1OS0xAHZpfFZJfGlzbzg4NTktMQBpZHxJRHxpc284
 ODU5LTEAdHJ8VFJ8aXNvODg1OS0xAHBsfFBMfGlzbzg4NTktMQAACAlfAAEAAg8N
 Tm9uZQBLZXlib2FyZAAACAlgAAEAAg8OTm9uZQBNb3VzZQAACAlhAAH/AgAJTm9u
 ZQBDT00gMQAACAliAAH/AgccSjFBMkIAVmlkZW8AAAgJYwAB/wIAHEozQTIASERN
 SQAACAlkAAEAAhIQTm9uZQBVU0IxLjEgLSAxIwAACAllAAEAAhIQTm9uZQBVU0Ix
 LjEgLSAyIwAACAlmAAEAAhIQTm9uZQBVU0IxLjEgLSAzIwAACAlnAAEAAhIQTm9u
 ZQBVU0IxLjEgLSA0IwAACAloAAEAAhIQTm9uZQBVU0IxLjEgLSA1IwAACAlpAAEA
 AhIQTm9uZQBVU0IyLjAgLSAxIwAACAlqAAEAAhIQTm9uZQBVU0IyLjAgLSAyIwAA
 CAlrAAEAAgsfTm9uZQBFdGhlcm5ldAAACAlsAAEAAiIgSjhKMQBTQVRBIFBvcnQg
 MCBEaXJlY3QgQ29ubmVjdAAACAltAAEAAiIgSjdKMQBlU0FUQSBQb3J0IDQAAAgJ
 bgABAAIiIEo2SjEAZVNBVEEgUG9ydCAzAAAICW8AASICACBKN0cxIC0gU0FUQSBQ
 b3J0IDIATm9uZQAACAlwAAEiAgAgSjdHMiAtIFNBVEEgUG9ydCAxAE5vbmUAAAgJ
 cQABAAL//0oxRjIAQUMgSU4AAAgJcgAB/wIA/0o1QjEgLSBQQ0ggSlRBRwBOb25l
 AAAICXMAAf8CAP9KOUExIC0gVFBNL1BPUlQgODAATm9uZQAACAl0AAH/AgD/SjlF
 NCAtIEhEQSAyWDggSGVhZGVyAE5vbmUAAAgJdQAB/wIA/0o5RTcgLSBIREEgOFBp
 biBIZWFkZXIATm9uZQAACAl2AAH/AgD/SjhGMSAtIEhEQSBIRE1JAE5vbmUAAAgJ
 dwAB/wIA/0o5RTMgLSBTY2FuIE1hdHJpeCBLZXlib2FyZABOb25lAAAICXgAAf8C
 AP9KOEUxIC0gU1BJIFByb2dyYW0ATm9uZQAACAl5AAH/AgD/SjlFNSAtIExQQyBI
 b3QgRG9ja2luZwBOb25lAAAICXoAAf8CAP9KOUcyIC0gTFBDIFNJREUgQkFORABO
 b25lAAAICXsAAf8CAP9KOEYyIC0gTFBDIFNsb3QATm9uZQAACAl8AAH/AgD/SjhI
 MyAtIFBDSCBYRFAATm9uZQAACAl9AAH/AgD/SjZIMSAtIFNBVEEgUG93ZXIATm9u
 ZQAACAl+AAH/AgD/SjVKMSAtIEZQIEhlYWRlcgBOb25lAAAICX8AAf8CAP9KNEgx
 IC0gQVRYIFBvd2VyAE5vbmUAAAgJgAAB/wIA/0oxSjMgLSBBVk1DAE5vbmUAAAgJ
 gQAB/wIA/0oxSDEgLSBCQVRUIEIATm9uZQAACAmCAAH/AgD/SjFIMiAtIEJBVFQg
 QQBOb25lAAAICYMAAf8CAP9KMkcxIC0gQ1BVIEZhbgBOb25lAAAICYQAAf8CAP9K
 MUQzIC0gWERQAE5vbmUAAAgJhQAB/wIA/0o0VjEgLSBNZW1vcnkgU2xvdCAxAE5v
 bmUAAAgJhgAB/wIA/0o0VjIgLSBNZW1vcnkgU2xvdCAyAE5vbmUAAAgJhwAB/wIA
 /0o0QzEgLSBGQU4gUFdSAE5vbmUAAIgIiAAAAAAAAAAOCIkAAdsAACRNRUkAANtq
 igABBAFFAgCQBgGFOSAAAAAAQAAAAAAAAAAAAAAC////////////////////////
 ////////AwAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAABNRUkxAE1FSTIATUVJMwBNRUk0AACIBosAAAAAAA4XjAAB3UgA3UkA
 3UoA3UsA3UwA3VwARmlybXdhcmUgVmVyc2lvbiBJbmZvAAB/BI0AAAA=

LPC IT87XX

Chip ID: 0x8689
Chip Version: 0x1
Base Address: 0x0A40
GPIO Address: 0x0A00

Environment Controller Registers

      00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

 00   19 10 00 80 DF FF 00 20 FF 98 20 00 30 49 03 D2
 10   FF FF FF 77 C2 50 40 40 03 03 02 FF FF FF 19 19
 20   61 AA A7 AB 02 58 65 8E 85 22 26 26 24 2D 1F 80
 30   FF 00 FF 00 FF 00 FF 00 FF 00 FF 00 FF 00 FF 00
 40   7F 7F 7F 7F 7F 7F 5F 40 AD 6A D4 00 00 00 00 00
 50   FF 18 7F 7F 7F 40 00 00 90 64 16 FF 65 00 00 00
 60   00 1D 54 00 03 05 00 C0 00 14 3C 00 04 01 00 FF
 70   00 14 3C FF 04 01 00 2E 00 14 3C 3F 04 01 00 C0
 80   33 03 FF FF FF FF FF FF 02 30 01 02 01 34 E0 91
 90   00 00 00 00 FF 10 10 10 40 97 00 00 40 6E C1 00
 A0   00 14 41 7F 04 01 00 50 7F 7F 96 80 00 00 0F 98

GPIO Registers

Intel CPU

Name: 11th Gen Intel Core i5-11400F
Number of Cores: 6
Threads per Core: 2
Timer Frequency: 10 MHz
Time Stamp Counter: None
Estimated Time Stamp Counter Frequency: 2592.1 MHz
Estimated Time Stamp Counter Frequency Error: 0.16589 Mhz
Time Stamp Counter Frequency: 2592.1 MHz

MSR Core #1

 MSR       EDX       EAX
 000000CE  00080838  F1811A00
 00000198  0000290C  00002A00
 0000019C  00000000  883A0000
 000001A2  00000000  80640000
 000001B1  00000000  88360000
 00000606  00000000  000A0E03
 00000611  00000000  3C2C81F2
 00000619  00000000  00000000
 00000639  00000000  1C05A1E9
 00000641  00000000  00000000

MSR Core #2

 MSR       EDX       EAX
 000000CE  00080838  F1811A00
 00000198  000028EC  00002A00
 0000019C  00000000  883B0000
 000001A2  00000000  80640000
 000001B1  00000000  88360000
 00000606  00000000  000A0E03
 00000611  00000000  3C2C85A3
 00000619  00000000  00000000
 00000639  00000000  1C05A4B3
 00000641  00000000  00000000

MSR Core #3

 MSR       EDX       EAX
 000000CE  00080838  F1811A00
 00000198  00002967  00002B00
 0000019C  00000000  88360000
 000001A2  00000000  80640000
 000001B1  00000000  88360000
 00000606  00000000  000A0E03
 00000611  00000000  3C2C85A3
 00000619  00000000  00000000
 00000639  00000000  1C05A4B3
 00000641  00000000  00000000

MSR Core #4

 MSR       EDX       EAX
 000000CE  00080838  F1811A00
 00000198  00002967  00002B00
 0000019C  00000000  883C0000
 000001A2  00000000  80640000
 000001B1  00000000  88360000
 00000606  00000000  000A0E03
 00000611  00000000  3C2C85A3
 00000619  00000000  00000000
 00000639  00000000  1C05A4B3
 00000641  00000000  00000000

MSR Core #5

 MSR       EDX       EAX
 000000CE  00080838  F1811A00
 00000198  00002990  00002B00
 0000019C  00000000  883E0000
 000001A2  00000000  80640000
 000001B1  00000000  88360000
 00000606  00000000  000A0E03
 00000611  00000000  3C2C85A3
 00000619  00000000  00000000
 00000639  00000000  1C05A4B3
 00000641  00000000  00000000

MSR Core #6

 MSR       EDX       EAX
 000000CE  00080838  F1811A00
 00000198  000028EC  00002A00
 0000019C  00000000  88400000
 000001A2  00000000  80640000
 000001B1  00000000  88360000
 00000606  00000000  000A0E03
 00000611  00000000  3C2C85A3
 00000619  00000000  00000000
 00000639  00000000  1C05A4B3
 00000641  00000000  00000000

MicroArchitecture: RocketLake
Time Stamp Counter Multiplier: 26

Storage

Drive Name: Samsung SSD 980 1TB
Firmware Version: 1B4QFXO7

PCI Vendor ID: 0x144d
IEEE OUI Identifier: 0x002538
Total NVM Capacity: 1000204886016
Unallocated NVM Capacity: 0
Controller ID: 5
Number of Namespaces: 0
Critical Warning: -
Temperature: 39 Celsius
Available Spare: 100%
Available Spare Threshold: 0%
Percentage Used: 0%
Data Units Read: 0
Data Units Written: 0
Host Read Commands: 0
Host Write Commands: 0
Controller Busy Time: 0
Power Cycles: 0
Power On Hours: 0
Unsafe Shutdowns: 0
Media Errors: 0
Number of Error Information Log Entries: 0
Warning Composite Temperature Time: 0
Critical Composite Temperature Time: 0
Logical Drive Name: C:\
Format: NTFS
Total Size: 998913036288
Total Free Space: 493712494592

**Comment by Rem0o** [comment]
See the "Issues and hardware compatibility" section of the readme. Thank you.
