### ISSUE TITLE
Windows background service

### ISSUE THREAD

**Issue by sunbeam60** [Rem0o/FanControl.Releases#52]
At the minute Fan Control requires a user to be logged in, which leaves secondary users on the machine with default BIOS fan controls, often resulting in a loud, or overheated PC. It would be great if Fan Control could run as a background service instead.

**Comment by sunbeam60** [comment]
Further to this, if one user starts FanControl and another user logs in (while the first user remains logged in), Fan Control actually struggles with starting for the second user.

**Comment by Cubox** [comment]
Similar request #135

**Comment by Draydak** [comment]
I've noticed that when the PC is locked, the fans speed up I'm assuming this is related. Would be nice to have it working all the time.

**Comment by feeph** [comment]
Upvoting.

Maybe this program needs to be separated into a background service (monitoring logic) and a frontend (user making changes). I noticed the program does not auto-start if used by a non-privileged user. Making the monitoring logic a background service may address this as well.

**Comment by Rem0o** [comment]
Dupplicate of https://github.com/Rem0o/FanControl.Releases/issues/135

**Comment by sunbeam60** [comment]
Hi @Rem0o!

Great news that this is now possible!! Thank you!

What does one have to do to enable Fan Control as a service?

**Comment by Rem0o** [comment]
@sunbeam60  just cleaning up duplicate requests.

**Comment by sunbeam60** [comment]
Ah, my bad, I misread the Closed reason it seems.

**Comment by Ged-fi** [comment]
> @sunbeam60 just cleaning up duplicate requests.

So why do you close the oldest open bug on this - shouldn't you be closing the newer duplicates instead?

Also note that the various ways of running FanControl as a service via other methods will most likely result in security vulnerabilities on users' systems, as well as any attempts at running as privileged when the user is not admin.

The only architecturally correct way to implement this is actually a low-privileged Windows service.

**Comment by QUAKEULUS** [comment]
I could not figure out how to autorun fan control on a standard account at all. 
Nothing worked. Not Task Scheduler, not FanControl-WinStart.zip fix, not even putting a shortcut to fancontro.exe into:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\

What did work was making a batch file that launches the shortcut, and then putting that batch file into the startup folder. 
I don't know why. But this works, although I do have to enter the admin password after login for it to actually run, but at least it starts automatically.


C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\_Fancontrol start shortcut.bat_
`timeout /t 20 /nobreak
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\FanControl.lnk"
exit`
