### ISSUE TITLE
fans 2 and 3 respond only after starting fan 1 - manual

### ISSUE THREAD

**Issue by etss** [Rem0o/FanControl.Releases#521]
i have 3 mobo controlled fans and when i switch to manual(all of them) i cannot manual control fans 2 and 3 if i don't switch fan 1 on.
fan 1 is the back one, 2 is proc and 3 is front.

i don't know if this is normal.
i have win 10 and the mb is an older intel mobo.
ty.

**Comment by etss** [comment]
well,, i have added some graphs and now it works well on manual also.. idk.
i can switch manual to auto, stop and start any fan (manual, auto, all working fine).

anyway, it s the best fan controller ever.
great job.
ty.

**Comment by Dark4Codrutz** [comment]
is there still an issue open here ?
If not please close
