### ISSUE TITLE
FanControl cannot control the fan

### ISSUE THREAD

**Issue by ngoccuongyb92** [Rem0o/FanControl.Releases#522]
Currently I am using Aorus B660 pro, Fancontrol v105, window 10 home when in the application I can see the fan speed but cannot control it. I tried with smart fan 6 in bios everything works. Please help me!

**Comment by etss** [comment]
try assigning some graphs.

**Comment by ngoccuongyb92** [comment]
I tried with the graphs, it worked the first time when the computer started up but after about an hour I tried again it didn't work. When it's controlled, it seems that something is causing the fan to run unstable, sometimes fast, sometimes slow

**Comment by ngoccuongyb92** [comment]
Did you have a solution to this problem?

**Comment by ngoccuongyb92** [comment]
@Rem0o Can you help me with this problem?

**Comment by etss** [comment]
well, auto works fine for me and when i want to switch to manual i need to switch all of them to manual and on..

**Comment by ngoccuongyb92** [comment]
https://drive.google.com/file/d/1NNXULsFDNzR1hiBsv2UHfwyGFVqD69J4/view?usp=sharing

**Comment by Rem0o** [comment]
My guess is a conflicting setting in an other software or bios.

Could be pwm/dc setting. A bios fan curve. Smart fan conflicting etc…

**Comment by ngoccuongyb92** [comment]
@Rem0o My main is gigabyte B660 with smart fan 6, but I can't turn it off, so is there any way to fix this?

**Comment by Rem0o** [comment]
From my end there isn't anything I can do. Either it works, or it doesn't.
