### ISSUE TITLE
Complete freeze on computer

### ISSUE THREAD

**Issue by guidodobboletta** [Rem0o/FanControl.Releases#524]
I set up my fan curves and everything was working fine. I closed the program to have it go to the tray and after a minute my computer completely freezes. I can't turn it off even by holding the power down button, I need to unplug it and plug it back in.

Here's my log.txt: https://pastebin.com/ZE6ULYxK

My specs: https://i.imgur.com/r672iN7.png

**Comment by L47UK** [comment]
I have similar kind problems, V102 works fine but V103 and higher versions crashes the whole computer. I think the problem is Asus EC sensors what came with V103.
My motherboard is X570 Asus Crosshair VIII Hero

**Comment by Rem0o** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/b38699508a5a9b94a6bad48824dabb4748954eba

Seems like a mutex was badly used for EC controllers on Asus boards. Should be fixed.

**Comment by guidodobboletta** [comment]
Thanks for the update @Rem0o !
