### ISSUE TITLE
Custom Sensor not inheriting custom sensor name for field

### ISSUE THREAD

**Issue by khaosmaou** [Rem0o/FanControl.Releases#525]
If you rename a sensor and then that sensor shows up in a custom sensor, it still uses the original name instead of the custom one.

In this example, "Temperature 5" has been renamed to "VRM Mosfets", but the original name shows up at the bottom of the custom sensor.

![custom sensor](https://user-images.githubusercontent.com/87764090/156905691-4f97cb34-9af9-4e90-8456-5c84423aff54.jpg)
![sensor setting](https://user-images.githubusercontent.com/87764090/156905692-355e7cbb-e817-4229-8908-1b096e6599da.jpg)

**Comment by Rem0o** [comment]
Good catch, thanks, will fix.

**Comment by Rem0o** [comment]
See v106

**Comment by khaosmaou** [comment]
Confirmed fixed, and in very little time! Good work!
