### ISSUE TITLE
On computer resume, control doesn't consistently take effect

### ISSUE THREAD

**Issue by kitlaan** [Rem0o/FanControl.Releases#53]
When running v52 (or v51; haven't tried earlier versions), sometimes when Windows resumes from suspend it looks like FanControl isn't "taking control" of (motherboard) fans.  Toggling the control disabled and back to enabled causes it to drive the fans at the expected values again.

During this weird state, the fan percentage and RPM are not the expected setting (per the curve), and the fan itself seems to be moving at the rate as displayed.  (aka, curve says it should be 30%, but the reading and behavior is 50%.)

This also seems to happen (randomly) when the "turn off the display" power plan kicks in (and not just resuming from sleep).  I've seen my fans ramp up to what seems like the max BIOS-defined curve, but I can't seem to decipher any logic to it.

**Comment by Rem0o** [comment]
Does this still happens in V56?

**Comment by kitlaan** [comment]
The unexpected behavior looks unchanged with V56 (aka still happens).

**Comment by kitlaan** [comment]
FYI: still the same with V59.  If there's anything you can think of for data collection, I can try.

I wonder if a "hack/workaround" is to just "reapply any enabled controls" every once in a while.  (Like every 10 mins or something. Maybe as a hidden json setting?)  Hopefully that doesn't have any side-effects.

But what I've been doing is checking the UI sometime after I come back to the PC.  If the UI shows unstable/unexpected fan percentages, then toggling the control off-then-on.

**Comment by kitlaan** [comment]
With V63 (or the lastest Windows update, hard to say), things seem to be working properly now.

Both "resuming from suspend" and "turn off display" don't cause the fan control to be lost and need a manual toggle.
