### ISSUE TITLE
Decimal place Temperature sensor values

### ISSUE THREAD

**Issue by permissionBRICK** [Rem0o/FanControl.Releases#530]
Hi,

I was wondering if it would be possible / easy to enable processing of decimal values for temp sensors. 
The reason I am asking is I am trying to create a fan curve for my AIO cooler fans, to run the AIO fan speed based on the coolant input temperature. Since the whole operating temp range of the coolant is about 4-5 degrees C, a more gradual curve would be nice, hence, decimal places.
I am using the HWInfo Plugin, and HWInfo is delivering this value with one decimal place, so i guess it would only be a matter of converting the value to the right data type?

**Comment by Rem0o** [comment]
Are you specifically talking about the graph fan curve?

**Comment by permissionBRICK** [comment]
Yeah, I have a graph fan curve like this
![image](https://user-images.githubusercontent.com/40219477/158045717-920bb42d-fd5d-47ba-9b88-1356f36a05ab.png)
and the temp indicator does not show decimal places, and it looks like the graph calculation is not using them either since the speed seems to be jumping between several values, always at exact whole numbers of temperature

**Comment by permissionBRICK** [comment]
Or is it using floating numbers and just not displaying them, and the jumps are for a different reason?

**Comment by Rem0o** [comment]
Decimal places should be now supported in the graph.
