### ISSUE TITLE
since 106 release i have a lot of latency issues while running Fan Control.

### ISSUE THREAD

**Issue by pcfrc** [Rem0o/FanControl.Releases#532]
Windows 11 Pro, MSI Z390 MPG Gaming Pro Carbon + 9900K.

**Comment by Rem0o** [comment]
What do you mean latency?

**Comment by pcfrc** [comment]
still happening with version 110 :/

on older versions (currently using 71) works perfect.

**Comment by Rem0o** [comment]
Try and remove sensor sources one at a time.

**Comment by Rem0o** [comment]
In this window 

![image](https://user-images.githubusercontent.com/14118956/180330504-a486c42b-011d-4050-95d8-a03fec487a40.png)
