### ISSUE TITLE
[BUG] - Closing the app causes saving popup to appear when not making any changes

### ISSUE THREAD

**Issue by BigFlubba** [Rem0o/FanControl.Releases#533]
When you close the app it causes the save popup to appear even when you haven't made any changes.
![image](https://user-images.githubusercontent.com/69104450/158088250-66b9164b-5cb7-42e7-b5fa-98fe7c2c0d1c.png)

**Comment by Rem0o** [comment]
When it prompts, can you save and diff the json file?

**Comment by BigFlubba** [comment]
wdym

**Comment by Rem0o** [comment]
V108 should fix it.
