### ISSUE TITLE
Linear Curve calculation wrong

### ISSUE THREAD

**Issue by larixk** [Rem0o/FanControl.Releases#538]
Maybe I misinterpret the behavior of Linear Curves, but getting a result of over 162% while having the Max. Speed set to 80% would seem incorrect to me. See values in screenshot.

This is happening after updating to version 107.

![image](https://user-images.githubusercontent.com/38729/158459829-f34e6050-cdf5-4eda-8944-3d1374d3627f.png)

**Comment by d-allin** [comment]
Similar issue here. I'm afraid no log is being generated - please let me know if I can provide anything to help troubleshoot.
![image](https://user-images.githubusercontent.com/21145526/158465061-be2b8aee-e5bc-4d30-b108-57b0d2eb5700.png)

**Comment by mrvicyu** [comment]
Similar. Once updated to 107, linear fan curve has been acting up for my GPU.
![image](https://user-images.githubusercontent.com/78929900/158476096-e947dc4c-777d-43df-bdba-0b564c39d75c.png)

**Comment by Rem0o** [comment]
Sorry about this, 107 introduced a really stupid bug.   Pushed an update already.

**Comment by larixk** [comment]
Awesome seems fixed! Thank you so much.
