### ISSUE TITLE
Can't see the window

### ISSUE THREAD

**Issue by JkAcktuator** [Rem0o/FanControl.Releases#539]
I opened the FanControl but can't see any window displayed on screen. However I can see the icon in the task bar, It's like the window is invisible. 
And it's the latest version.

**Comment by Rem0o** [comment]
Windows 10 or 11 ?

**Comment by JkAcktuator** [comment]
Windows 10

Rem0o ***@***.***>于2022年3月16日 周三下午1:05写道：

**Comment by Rem0o** [comment]
log.txt?

**Comment by Rem0o** [comment]
Next to FanControl.exe, is there a log.txt file, if yes, post it.

**Comment by Tiernomrg** [comment]
i have the same issue the software cant detect my fans. i am using win10 on Hp

**Comment by Bardan666** [comment]
Hi,
just installed the software, did all the checks for the fans and then the GUI window doesn't appears.
I still get the try icon and the task icon but no GUI window.
I'm on Windows 11, and same as the other guy, there's not log.txt in the folder

**Comment by xhul-dev** [comment]
Hello there.
1) Right-click the Fan Control systray icon.
2) Left-click on "Open".
3) Press [Windows key] + [Up arrow].
Let us know how that went.

**Comment by Bardan666** [comment]
> Hello there.
> 
> 1. Right-click on the Fan Control systray icon.
> 2. Left-click on "Open".
> 3. Press [Windows key] + [Up arrow].
> 
> Let us know how that went.

Hello again,

already done that but I tried again anyway but nothing happens.

Even the other arrow keys doesn't change nothing.

It's as if the window exists, but stays hidden near the systray icon.

However, if has choose to close all the windows of FanControl, a notification appears to prompt if I want to save my config before exiting.

**Comment by Bardan666** [comment]
![nowindow](https://user-images.githubusercontent.com/23550097/164966602-0b4b0792-9413-417c-a617-014e536bdebf.png)
This is an example of what happens when the software is launched.

**Comment by xhul-dev** [comment]
> > Hello there.
> > 
> > 1. Right-click on the Fan Control systray icon.
> > 2. Left-click on "Open".
> > 3. Press [Windows key] + [Up arrow].
> > 
> > Let us know how that went.
> 
> Hello again,
> 
> already done that but I tried again anyway but nothing happens.
> 
> Even the other arrow keys doesn't change nothing.
> 
> It's as if the window exists, but stays hidden near the systray icon.
> 
> However, if has choose to close all the windows of FanControl, a notification appears to prompt if I want to save my config before exiting.

You can also try right-clicking the mini-window, and select "maximize".
Another user solved it that way.
By the way, what is your desktop resolution?

**Comment by Bardan666** [comment]
> licking the mi

FFS you're a genius!
The right-click and Maximize did the trick!

And I'm in 3480x2160 ;)

Thanks again!

**Comment by drayquan** [comment]
> > > Hello there.
> > > 
> > > 1. Right-click on the Fan Control systray icon.
> > > 2. Left-click on "Open".
> > > 3. Press [Windows key] + [Up arrow].
> > > 
> > > Let us know how that went.
> > 
> > 
> > Hello again,
> > already done that but I tried again anyway but nothing happens.
> > Even the other arrow keys doesn't change nothing.
> > It's as if the window exists, but stays hidden near the systray icon.
> > However, if has choose to close all the windows of FanControl, a notification appears to prompt if I want to save my config before exiting.
> 
> You can also try right-clicking the mini-window, and select "maximize" (if "maximize" is greyed out, that means you need to click FC in the taskbar once first, to make it the active window). Another user solved it that way. By the way, what is your desktop resolution?

Had same problem, this fixed it for me, thanks :D
