### ISSUE TITLE
Fan revving up to max speed since V53

### ISSUE THREAD

**Issue by Alresh** [Rem0o/FanControl.Releases#54]
Whenever I re-enable my custom setup or when it gets enabled when I boot up my pc (have it on start with windows) part of my fans get set to max speed. Immediately after they slowly go down to the speed they're supposed to be at, connected to a graph of highest temp of cpu/gpu. This didn't happen before V53 and also doesn't affect all my fans.

If more information is needed / can be helpful let me know!

**Comment by CZonin** [comment]
I've been having a lot of issues since updating to 53, and ended up having to roll back to 52. I would have sensors fail to load very often, and the pump on my AIO would randomly go to 100%. Worst thing was that it stopped reading my 3090s temps and never started spinning the fans. I ended up finding out it was at over 90C.

**Comment by Rem0o** [comment]
Can you send me the application log from the top right menu? Seems like it only affects people with a specific type of SuperIO chip.

**Comment by neilangierof** [comment]
I haven't experienced any sensors crashing prior to 53. Since then, my GPU fans have not been spinning up as well, also resulting in 90C temps.

**Comment by CZonin** [comment]
> Can you send me the application log from the top right menu? Seems like it only affects people with a specific type of SuperIO chip.

Do I need to wait until an issue occurs or can I just install 54 and grab the log quick? Kind of nervous about having it running to too long.

**Comment by nutsforalmonds** [comment]
I've been having the same issue with a NCT6678D. Specifically, my water pump is using a flat curve set to 15%, but the actual signal will at random change to another value. Values it sets itself to seem to be either 0, 40, or 100. I also have a graph curve that will at random output whatever the maximum value of the curve is regardless of the input value.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5496135/log.txt)

**Comment by Rem0o** [comment]
Made a change in V55 regarding resume from sleep. I "underflowed" the value from 0 so it looped back to 255, so max speed. Fixed it. Could you tell me if it still happens?

**Comment by nutsforalmonds** [comment]
I've been on V55 since yesterday morning and my subjective experience is that the phenomena are happening with increased frequency compared to V54, if anything.

**Comment by Rem0o** [comment]
@nutsforalmonds is it specifically when it wakes up from sleep? If not, it is a different issue not related to this one.

**Comment by nutsforalmonds** [comment]
Oh, I'll make a new issue then.

**Comment by Rem0o** [comment]
Fixed in V59.
