### ISSUE TITLE
Feature suggestion: Display of CPU/GPU utilization in GUI 

### ISSUE THREAD

**Issue by mouchesvolantes** [Rem0o/FanControl.Releases#544]

**Comment by Dark4Codrutz** [comment]
I think this is beyond the scope of the software.
I wouldn't want an all-in solution like this.

**Comment by graz68a** [comment]
I would have it too

**Comment by Rem0o** [comment]
More and more, I'm thinking of having some kind of optional plugin/ui to have monitoring capabilities.  By default you only get the lightweight fancontrol, but the backend engine has all the data for monitoring, I'm just not showing it. You could optionally install an extension or something.

**Comment by mouchesvolantes** [comment]
I don't know how complicated it would be to integrate this functionality but CPU/GPU utilization and temperatures have a direct relationship. I was using CPUID HWMonitor to check my temperature, fan speed and utilization parameters before, but this program displays temperatures and fan speeds much more clearly. The only reason I still have CPUID HWMonitor is to check the utilization values (and FPS sometimes).
