### ISSUE TITLE
Error after editing graph fan curve

### ISSUE THREAD

**Issue by StoopidSam** [Rem0o/FanControl.Releases#546]
After I create a graph fan curve, and edit it, I receive this message:
![image](https://user-images.githubusercontent.com/66969418/159111858-04e083fb-a8f4-4aad-9853-3d56290701ca.png)

In case it helps, this is my fan curve:

![image](https://user-images.githubusercontent.com/66969418/159112114-ee623988-197a-493e-89fb-510f9fdae28a.png)

After clicking on the OK button, I am unable to click the edit button on any of my graph fan curves, and clicking the question mark button on any section does not do anything.

I tried to exit the program through the system tray. I right clicked on the fan control icon, and I was unable to select any of the options. This menu stayed up no matter what I did, and I was forced to end the process through the task manager. Note that this only happens 4/5 times.

Here is my [log.txt](https://github.com/Rem0o/FanControl.Releases/files/8308783/log.txt) file.

I am on Windows 10 Pro 21H2, OS build 19044.1586.

After I manage to exit the program and re-open it, everything works fine.

**Comment by Kurandx** [comment]
Yes, I have the same problem. After an error occurs, any dialogs stop opening until the program is completely restarted.
P.S. Windows 10 Pro 21H1, OS build 19043.928

**Comment by Rem0o** [comment]
I think it occurs when you are moving a point (holding) then right click to delete it. The state of the graph edit under the hood then gets messed up. I was able to get a similar result this way.

**Comment by Rem0o** [comment]
I'm actually working on the graph window, fixed the previously mentioned issue, plus rearranged it a bit and added a new feature to set the range of temperature of the graph.

![image](https://user-images.githubusercontent.com/14118956/160037198-ad46c6d0-056f-40f3-a90b-58ca924c47b1.png)
