### ISSUE TITLE
Target CPU Mode : Takes a "long" time to slow down

### ISSUE THREAD

**Issue by Naokor** [Rem0o/FanControl.Releases#549]
Hello, 

In the 108 version of the soft, the "Target" mode is really effective in ramping up the fans. It takes several minutes for them to spin down, while the sensor temperature is compatible with the lowest speed of this target mode. On the attached picture, temp is 46C so fans should be around 30% (ish) according to my settings. If I change a speed value by 1% in the "Target" UI, fans immediately goes down to the correct value. They seem to be "stuck" at the highest RPM setting. 

If this is a normal behaviour designed to prevent a speed back and forth, fine. If not, I hope this will help making a fantastic software. Thank you! 

![image](https://user-images.githubusercontent.com/26311252/159153808-632c9235-2418-4254-af27-bf01ca964aba.png)

**Comment by Rem0o** [comment]
There is a description of how this function works if you click on its icon ( the target ).   The behaviour you describe is the linear fan curve.

**Comment by Naokor** [comment]
Hi,

It is definitely not a bug so. Understood perfectely! Thanks man!
