### ISSUE TITLE
Feature: Force fan set

### ISSUE THREAD

**Issue by Dreaming-Codes** [Rem0o/FanControl.Releases#55]
Is it possible to add an option that forces the fans to run at a certain speed every second?
Because after a few minutes my fans stop following the schedule, it is probably the fault of some leftover AiSuite (asus) but I don't want to reset and a feature like that would solve my problems.

**Comment by Rem0o** [comment]
That would take unnecessary resources in most cases. I suggest you take a look in your BIOS and try to fix your issue there in the first place instead.
