### ISSUE TITLE
RPM would not be changed when fan speed percentage changes

### ISSUE THREAD

**Issue by chorong761** [Rem0o/FanControl.Releases#550]
v108, WIndows 11

Starting today, my fan controls suddenly got cleared (curves are still there). Didn't reboot system or do any updates.

After my controls got cleared, I noticed that the rpm of my fans would not change when I change the percentage (fans does actually change speeds, but doesn't get reflected). The fan rpm would still be fluctuating, but would not be based on the percentage set. 

More info could be provided (I'm not too sure what to include)

**Comment by Rem0o** [comment]
What do you mean "cleared" ?   Seems like something else took over.

**Comment by chorong761** [comment]
> What do you mean "cleared" ? Seems like something else took over.

"Cleared" as in all the fans are gone under the "Controls" section

**Comment by Rem0o** [comment]
Seems like your sensor pairing is off. Remove all pairing.
