### ISSUE TITLE
FanControl triggers AntiCheat Software

### ISSUE THREAD

**Issue by spaceXrace** [Rem0o/FanControl.Releases#554]
I just wanted to let you know that the WinRing0.sys driver that appears to be loaded by FanControl triggers Badlion Anticheat (https://store.badlion.net/category/bac) 

While there is nothing wrong with FanControl, it may be helpful if it's mentioned somewhere for the few users that will encounter the same problem.

Thanks for making this software!

**Comment by Sacred-Shadow** [comment]
It would be better if you just inform the manufacturer that they have a false positive here.
