### ISSUE TITLE
start with windows not working

### ISSUE THREAD

**Issue by xhul-dev** [Rem0o/FanControl.Releases#559]
Hello there.
Thanks a lot for your work on this software, loving it so far.

Basically, the option does absolutely nothing, and the box is always unchecked when reloading configuration.
Nothing gets registered in task scheduler at all.
No log.txt is generated whatsoever.
I have admin rights, so i highly doubt it's related.

On my machine, only versions **100 to 109** are concerned.

As far as version **99** goes, it behaves a bit strangely :
The option in itself works correctly (task registered and working).
However, if the option is active when a configuration is loaded, a "Could not load the configuration." error occurs (again, that error doesn't keep the option from doing its job).
Here is the associated log.txt data :
31/03/2022 18:35:56: System.ArgumentException: (19,8):UserId:
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   at FanControl.Domain.WindowsSettings.SetRegisterInStartup(Boolean register, TimeSpan delay)
   at FanControl.MVVM.ViewModel.SetPropertyAndDo[T](T& property, T value, Action action, String memberName)
   at FanControl.ViewModels.WindowSettingsViewModel.set_StartupWindows(Boolean value)
   at FanControl.ViewModels.WindowSettingsViewModel.Restore(SerializableMainWindow state)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state, IFanCurveProvider`1 fanCurveProvider, ICustomSensorProvider`1 customSensorProvider)
   at FanControl.ViewModels.MainWindowViewModel.RestoreApplicationState(SerializableMainWindow state)

Regarding versions **46 to 98**, the option seems to work perfectly fine.

Hope it'll help, thanks in advance for your time =]

**Comment by Rem0o** [comment]
I won't focus on older version. 

![image](https://user-images.githubusercontent.com/14118956/161121362-7ae82ec4-ba2a-4275-93c2-0c5fa4946f9d.png)

Do you get that message at all? Basically I set the task, then I fetch it back to make sure the task was created in the task scheduler.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/161121970-d3c9da8b-f1b8-4121-8e9c-12d9ffa8c3f2.png)

**Comment by xhul-dev** [comment]
Thanks for the replies =]

> I won't focus on older versions.
> 
> ![image](https://user-images.githubusercontent.com/14118956/161121362-7ae82ec4-ba2a-4275-93c2-0c5fa4946f9d.png)
> 
> Do you get that message at all? Basically I set the task, then I fetch it back to make sure the task was created in the task scheduler.
Nope, that message never occurs.

> ![image](https://user-images.githubusercontent.com/14118956/161121970-d3c9da8b-f1b8-4121-8e9c-12d9ffa8c3f2.png)
> 
> Maybe you got an AV or something that's deleting the task?
No AV at all whatsoever on my machine (not even win defender).
I suspect the task isn't deleted by anything, something just prevents it from being created.

In the mean time, i found a roundabout, which is to create the task using version 98, and then use version 109 afterwards, it works just fine (i guess i just have to keep the option box checked after that).
If i have time, i'll take a look at the code from version 100, to see what makes the task creation being handled differently.

**Comment by xhul-dev** [comment]
I did a bit of research, and it appears the problem comes from the task scheduler itself, which seems to not digest some admin accounts properly, under (yet) unknown circumstances.
In the mean time, i created a tool that bypasses the problem: https://github.com/xhul-dev/FanControl-WinStart

**Comment by gumnutTHFC** [comment]
> I did a bit of research, and it appears the problem comes from the task scheduler itself, which seems to not digest some admin accounts properly, under (yet) unknown circumstances. In the mean time, i created a tool that bypasses the issue: https://github.com/xhul-dev/FanControl-WinStart

This works perfectly - thank you! This has been bugging me for a while.
