### ISSUE TITLE
FanControl.exe - being auto deleted (Win 10)

### ISSUE THREAD

**Issue by Ragmon88** [Rem0o/FanControl.Releases#561]
Hi.
Love Fancontrol, helps out a lot.

Its working as intended when it is open/on. After a while the task closes, usually after a restart, and the "FanControl.exe" disappears. This never ever happened to any other software I used before (been using PCs/Windows for 20 years now). Other then an Antivirus software detecting something and moving it to quarantine. 

I'm using Windows 10 64-bit.
It's not in the recycling bin. 
I'm using Avast, but its not showing up in its log/history. Also I set it as an exception.

Let me know what information I need to provide to help you out with identifying this issue.

**Comment by Rem0o** [comment]
Windows security/ defender maybe? That's actually the first time I've heard something like this.

**Comment by xhul-dev** [comment]
> After a while the task closes, usually **after a restart**, and the "FanControl.exe" disappears.

Is the "Start with Windows" option properly checked?

**Comment by Ragmon88** [comment]
> Is the "Start with Windows" option properly checked?

Yes the check box is checked. Can't see it in the Task Manager > Startup tab tho.
And I'm excluding it in Windows Firewall and Avast (working instead of Win Protection).

**Comment by xhul-dev** [comment]
> > Is the "Start with Windows" option properly checked?
> 
> Yes the check box is checked. Can't see it in the Task Manager > Startup tab tho. And I'm excluding it in Windows Firewall and Avast (working instead of Win Protection).

It's not supposed to be listed in the startup apps, that's expected.
Do you have any log.txt file in the FanControl folder?
Other than that, it could be worth checking windows application logs, to see if the system logs something when FanControl unloads itself (open "event viewer" app, expand "Windows Logs" on the left, select "Application", and check recent "Error" and "Warning" level entries, to see if one is related to FanControl).

**Comment by Ragmon88** [comment]
> It's not supposed to be listed in the startup apps, that's expected. Do you have any log.txt file in the FanControl folder? Other than that, it could be worth checking windows application logs, to see if the system logs something when FanControl unloads itself (open "event viewer" app, expand "Windows Logs" on the left, select "Application", and check recent "Error" and "Warning" level entries, to see if one is related to FanControl).

I checked every Warning, Error and similar tags in the past 30 days. I found nothing related. No I don't have a "log.txt" in the Fancontrol folder.

**Comment by xhul-dev** [comment]
Then you'll have to investigate by yourself, if you're not out of time, of course.
Personally, i would bet on a conflict with another code.
To identify if a resident program interferes, just let a fresh windows session run by itself for long enough.
If FanControl survives, that means an app that you run manually is more likely involved.
To catch it, just remember to pay extra attention to the presence of the FanControl tray icon each time you open and close an app, amongst the ones that you commonly use.
At least that's where i would start.

**Comment by Ragmon88** [comment]
> Then you'll have to investigate by yourself, if you're not out of time, of course. .... At least that's where i would start.

Yea, I'm kind of doing that. Thought I would ask around, someone might know something.

Well thanks for the help. See ya.
