### ISSUE TITLE
Fan control can't detect fans after windows update

### ISSUE THREAD

**Issue by owenliu66** [Rem0o/FanControl.Releases#564]
I began to use this at V104 and everything worked perfectly. Now, after a windows update, FanControl is unable to detect the fans. I'm using windows 10 professional 20H2. The motherboard is MSI Z390M Mortar.

**Comment by xhul-dev** [comment]
Nasty windows updates.
It might be a configuration issue, due to the system changes.
Redownload the latest version of FanControl, open it, and see if your fans are still missing.

**Comment by owenliu66** [comment]
> Nasty windows updates. It might be a configuration issue, due to the system changes. Redownload the latest version of FanControl, open it and see if your fans are still missing.

Thanks for the reply! I reinstalled the latest version, but it still can't find the fans. The only fan I can see is the GPU fan. The case fans are missing.

**Comment by xhul-dev** [comment]
It could be that the win update you performed included a faulty driver that causes the OS to not recognise the fan controller anymore.
Let us know if your device manager displays something unusual.

**Comment by MrBroccoliJP** [comment]
I have the same problem, Asrock B450M Steel legend, After latest windows update all motherboard fans disappeared, only showing the gpu fan.

**Comment by ShadyHarbinger** [comment]
Same issue with X670E and the latest Windows 10 version.

**Comment by trezum** [comment]
Same issue with 
ASUS TUF GAMING X670E-PLUS WIFI 
Bios patched to latest version
Windows 11 Updated
Fan Control V136
