### ISSUE TITLE
Plugin Request - MSI Center (AIO Pump Control) 

### ISSUE THREAD

**Issue by MaceAus** [Rem0o/FanControl.Releases#565]
Hi, I am hoping someone can help me to develop a plugin similar to: https://github.com/medevil84/FanControl.AquacomputerHighFlowNext for MSI AIO's (in my case CORELIQUID 240K). It can hopefully access the required data in a similar way. 

My programming knowledge doesn't go far beyond Matlab, I am very lost on how I would do this.

The default program (MSI Center) is awful, and doesn't allow me to set temperature sensor, and is basically bloatware. 

Apologies if I have posted this to the wrong section, please delete/move if so.

Thanks.

**Comment by Rem0o** [comment]
You would need official documentation for the HID protocol, or most likely reverse engineer it, like by intercepting the data stream from the device while it interact with an official software, like the MSI one, and figure out what is what depending on what is happening in the software. You would also need to figure out the memory structure of the data being sent/received to the device.

**Comment by MaceAus** [comment]
Hi Remi,

Thank you for the information.
Do you have a recommended tool/software for intercepting the data stream?

MSI states that the 240K uses an Asetek gen7 pump, perhaps that is similar architecture to gen6 (asetek_pro.py in the link you provided)?

The pump head also has a fan built into it which is the main thing I want to control, it's small and very loud at default speed.
