### ISSUE TITLE
Fans without RPM sensor never running above the set "Start %"

### ISSUE THREAD

**Issue by ELowry** [Rem0o/FanControl.Releases#566]
Hi there,

### The Situation

Here is what I'm working with:
![image](https://user-images.githubusercontent.com/7792033/155717193-57225d5e-6d07-44de-9683-27854028bb4f.png)

The `Front Top`, `Front Bottom` and `Chongus` fans are the white LED fans that came with my Carbide 500R case; they were initially driven by the case directly and ran at 3 speeds (probably something like 60%, 80% and 100% I'd say).

I have now plugged them into my motherboard's system fan headers (MSI B550 Gaming Plus); and they work great (except for the LEDs not lighting up all the way, which from what I can tell is just that it doesn't deliver as much power as the case did; but that's fine with me).

Those fans do not appear to have an RPM sensor, and do not report anything to the software as a result.

### The issue
Even when the load reaches a point where my "General" curve should trigger them to increase past their base 30/52%, they seem to just stay at that value and never increase.

In the screenshot for example, the fans "should" be running at roughly **33/55**%, but they don't.

And yes, even if I force the curve much higher, the values don't change.

Am I missing something here?

&nbsp;

***PS:** The two "Front" fans are 120mm and "Chongus" is a 200mm fan.*

**Comment by xhul-dev** [comment]
How many pins do the cables for those fans have?

**Comment by xhul-dev** [comment]
So, they never go past 0 RPM at all when using a curve? even when they are sent a very high % value?

**Comment by ELowry** [comment]
Unfortunately that didn't do the trick.
Here's an example where I tried to artificially force the curve to its maximum, and you can clearly see the problematic fans are running at their exact `Start%` value:
![image](https://user-images.githubusercontent.com/7792033/161578963-7b752ab5-423c-430d-a840-bfdbef3e493d.png)

**Comment by ELowry** [comment]
Edit: after some further testing (I had run my initial tests quite a while back), even when using Manual Control, the fans never go beyond their `Start%` value; but if I boost both the manual value and the `Start%` to 100%, the fan does properly run at its max speed.

**Comment by Rem0o** [comment]
You say your Front Top, Front Bottom and Chongus fans don't have a RPM sensor. Yet, on your control cards, I can see a RPM sensor matched. Hover your mouse over the RPM, what is it?

**Comment by ELowry** [comment]
OK, that did the trick!
During the initial setup process, it had paired them to the corresponding sensor (4th pin on the motherboard I imagine?); I somehow thought this was required regardless of the fan only using 3 pins and not having a built-in sensor.

I'll mark this as resolved; though I imagine it could be nice to have some sort of warning if the RPM sensor remains at 0 even after prolonged times at the Start% value? Or something along those lines.

**Comment by Rem0o** [comment]
If the software paired them with those RPM sensors, it means those RPM sensors worked at that time.

Try and remove all the rpm sensors from your controls, then redo the pairing process.

![image](https://user-images.githubusercontent.com/14118956/161582808-a0e9d9c6-ae44-4063-9d7c-dc098507fdec.png)

![image](https://user-images.githubusercontent.com/14118956/161582918-c2120037-9487-445c-9fb0-6d350b255c7c.png)

**Comment by ELowry** [comment]
The automatic pairing didn't find a sensor; so my best guess is that I did it manually and just forgot about it (I did a significant bit of playing around initially before understanding how things worked).

Either way, it's working like a charm now, which is amazing!!
