### ISSUE TITLE
Virustotal: 3 security vendors mark FanControl.Releases-110.zip as malicious

### ISSUE THREAD

**Issue by deliciousbob** [Rem0o/FanControl.Releases#568]
Hi, thank you for sharing such a tool, I want to give it a try, 
but as I always check downloads on Virustotal i uploaded your package to them:
- They found 3 suspicious files. Can you explain why that is happening?- https://www.virustotal.com/gui/file/27e9af1c92b88c60b85245513ddd3f587f0ac41e55910e6df46c8957291ff9ec?nocache=1
![image](https://user-images.githubusercontent.com/13135271/161715743-e63fb1d8-e726-40c3-9f0c-8b369bb631d4.png)
Thank you for clarification, best regards

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/161798220-60b8dbc7-3a81-4a17-b3fe-3b0f5b2f7f84.png)

Well the 3 dlls are open-source, and FanControl.exe of course use those. 
Nothing is signed (security vendors), so I guess that's what is triggering it.

**Comment by Sacred-Shadow** [comment]
FalsePositiv from NoName Vendors.

**Comment by aemondis** [comment]
@Rem0o any chance of sharing the source? It's much easier to trust the app when the source is seen, and is ultimately the goal of Open Source. This would help with AV vendors being able to validate such apps too, and potentially trust the app.

**Comment by Rem0o** [comment]
False positive.
