### ISSUE TITLE
Adding decimal to hysteresis of graph cause saving prompt when closing

### ISSUE THREAD

**Issue by DfrostX** [Rem0o/FanControl.Releases#569]
Hi Rémi,

Thanks for adding decimals to the hysteresis of graphs! It work perfectly. But it has created a minor issue (very minor actually). When adding a decimal to the hysteresis field of a graph, it works as intended, but every time I open Fan Control, then close it without having changed anything, I get the saving/ discard prompt. 

Note that I did a compare of the .Json file before and after saving and I did not see anything different. Also, note that saving or discarding the change (or rather "non-change") does not break the hysteresis functionnality or anything.

As soon as I remove the decimal to integer values, the saving prompt goes away.

No big deal, but I'm reporting it anyway.

Thanks!

**Comment by Rem0o** [comment]
Just tested. Went from "1", to 1.5.  Prompted, saved.

Closed FanControl, opened it back. Values are there. Close window, no prompt.

**Comment by DfrostX** [comment]
Thats odd, I'm not getting the same result.

One thing I just tried is changing the regional settings of Windows for decimals from comma to dot (I use FR-CA localization and comma is the default). But no luck. It kinda fixed an annoyance (my OCD really) since Fan Control has now switched to using a dot for decimals in the graph windows but it was already a dot in the json file so it does not change much as far as functionnality (which was fine anyway).

Next step will be to redo my whole setup profile since I've been porting it since version 50ish, it might be off or something.

Ill update later if that helped or not

Thanks!

**Comment by DfrostX** [comment]
I found the cause of the prompt. Setting the hysteresis value to anything outside a multiple of 0.5 will cause the prompt to save to happen. I was setting it to 0.2C which is why I was having it. That also explains why 1.5C worked for you.

**Comment by Rem0o** [comment]
Found the culprit:

https://github.com/JamesNK/Newtonsoft.Json/blob/f7e7bd05d9280f17993500085202ff4ea150564a/Src/Newtonsoft.Json/Linq/JValue.cs#L398

Nasty bug. 

Basically, the float originating from the software ( local state ) converted to a double will have a very very small error, like 0.00000001, where the file state won't. The method above will thus return false, and trigger a prompt.

**Comment by Rem0o** [comment]
Now uses double precision everywhere, closing.
