### ISSUE TITLE
Feature: Visual indicator that something need to be saved

### ISSUE THREAD

**Issue by sarbian** [Rem0o/FanControl.Releases#57]
I lost a curve config twice because I forgot to save before turning off the computer. 

Some kind of visual indicator that something changed and a save is need might be nice. I suggest changing the background color of the top header.

**Comment by Rem0o** [comment]
Hum, that would mean doing the "something change check" every time you change any value, which would be quite resource intensive. I do agree though that if you close your computer with a FanControl window open, it won't save, which can be an issue. Will have to think about it.

**Comment by luxferro** [comment]
You could always do a save on minimize for a quick and easy bandaid.

**Comment by Rem0o** [comment]
@luxferro the software does it already when you close the window down to the tray icon.
