### ISSUE TITLE
Fan RPM

### ISSUE THREAD

**Issue by Tomizz55x** [Rem0o/FanControl.Releases#570]
Is this normal?
![image](https://user-images.githubusercontent.com/103187311/162185832-440613c8-2067-4260-a269-b46898313d7e.png)

**Comment by Rem0o** [comment]
If its always like that, no.

**Comment by Rem0o** [comment]
under that range, does it stops? Seems like it's stuck at a starting threshold.

**Comment by Tomizz55x** [comment]
no it shows a little over 8000rpm at 28% but it works just fine when its a little over 60%.
and its my cpu fan thats doing this (120mm)

**Comment by Rem0o** [comment]
What's the RPM range of that fan?

Like at 60%, what's the RPM?

**Comment by Tomizz55x** [comment]
200-1800rpm
at 60% its at about 1255rpm but if i go little lower than that it starts to freak out
its set to pwm

**Comment by Rem0o** [comment]
See README.
