### ISSUE TITLE
Feature suggestion: Process or time-of-day based configuration

### ISSUE THREAD

**Issue by mouchesvolantes** [Rem0o/FanControl.Releases#573]
The time-of-day functionality is self-explanatory, so I'll skip it. For program-related configuration: When a certain process is running (e.g. games, simulation programs, someprogram.exe), a certain user configuration can be activated. When I play games, I have my headphones on, so loud fans are not a problem lol.

**Comment by Rem0o** [comment]
Dup of https://github.com/Rem0o/FanControl.Releases/issues/97
