### ISSUE TITLE
Saved configurations are not found

### ISSUE THREAD

**Issue by mouchesvolantes** [Rem0o/FanControl.Releases#574]
I have two user configurations in the program folder, but they are not displayed when I click Menu -> Load Configuration.

But they are visible when I click on the icon in the notification area and select Configurations. After I change my configuration via the notification area they are displayed in Menu -> Load Configuration.

![SavedConfigurations](https://user-images.githubusercontent.com/94894376/162627627-fc46f62a-073a-4cc7-bb87-12088ae8ea42.png)
![LoadConfigurationDialog](https://user-images.githubusercontent.com/94894376/162627630-36ea69dd-bdf8-45cc-b235-fb15caf15f13.png)
![SystemTray](https://user-images.githubusercontent.com/94894376/162627764-9cdba082-b135-45c5-bc6b-1e6bd3b0b339.png)

**Comment by Rem0o** [comment]
Seems like you run FanControl.exe from an other folder. You need to have your local folder "context" to be the same folder as the exe.
