### ISSUE TITLE
Noctua-a12 not changing RPM

### ISSUE THREAD

**Issue by M1katchu** [Rem0o/FanControl.Releases#575]
Hi guys,
so my cpu fan is just not changing rpm or listening to the software.
I changed the fan from the cpu header to another fan header and its still not working.
Back fan works fine.
help pls :(
![image](https://user-images.githubusercontent.com/103436318/162758960-409b59bc-b15b-4781-9f54-b8b83c253224.png)

**Comment by M1katchu** [comment]
The curve doesn't actually do anything. Curve-manual-off, all the same.

**Comment by M1katchu** [comment]
Found the issue, apparently i need to find the right control aswell.

**Comment by Rem0o** [comment]
Control and RPM sensors need to be matched yes.
