### ISSUE TITLE
0℃（"subtract" ） made the fan 100%

### ISSUE THREAD

**Issue by MiyukiLoveu** [Rem0o/FanControl.Releases#576]
Hello, the fan control is awesome.
I really love the custom sensor function，it's really so good.
However if the subtrahend to 0℃ , fans would be out of control.
All fans came to 100%,and show me NaN%.
Please help me fix this issue,thank you very much.

**Comment by Rem0o** [comment]
Right now, anything below 0 is considered "unexpected behavior" and thus the fans will go 100% as a fail-safe.

**Comment by MiyukiLoveu** [comment]
Could you to make this an option that can be turned off manually？
Thank you！

**Comment by MiyukiLoveu** [comment]
> Right now, anything below 0 is considered "unexpected behavior" and thus the fans will go 100% as a fail-safe.

Could you to make this an option that can be turned off manually？
Thank you！

**Comment by Rem0o** [comment]
Planed.

**Comment by Rem0o** [comment]
0C is now supported.
