### ISSUE TITLE
[Improvement] Smaller font for card titles

### ISSUE THREAD

**Issue by ddenev** [Rem0o/FanControl.Releases#58]
Would it be possible to make the card title font smaller?

Currently the title font is a little bit big so more than ~15 characters become truncated.

I believe that the title bar could be optimized - the main icon and the "More" icon could be made smaller, currently they take around 50% of the width of the title altogether.

Thank you for the wonderful piece of software!

**Comment by Rem0o** [comment]
I will definitely add a tooltip when you mouse hover to see the full text, but I will also try and tweak the padding and margins to see a bit more of the text in the first place.
