### ISSUE TITLE
How do i delete the "FanControl.sys"

### ISSUE THREAD

**Issue by Himsonor** [Rem0o/FanControl.Releases#582]
How do i delete the "FanControl.sys" cuz it says some apps are using this, so it cannot be deleted, so any ways to solve this problem?

**Comment by Himsonor** [comment]
![image](https://user-images.githubusercontent.com/104180963/164585911-f2a9e12b-4222-489c-b063-44a8fc5e64f3.png)

**Comment by xhul-dev** [comment]
Hello there.
FanControl.sys should only exist when Fan Control is currently running, it's a temporary file.
When exiting Fan Control completely (right click on system tray icon, then select "Exit"), it should vanish automatically.
Cheers.

**Comment by Himsonor** [comment]
> Hello there. FanControl.sys should only exist when Fan Control is currently running, it's a temporary file. When exiting Fan Control completely (right click on the Fan Control system tray icon, then select "Exit"), it should vanish automatically. Cheers.

thankyou for u reply. but I have forgotten to close the fan control app and delete all of the documents, it still shows " some apps are using this file ", how can I solve this problem? thanks and sorry for my poor English grammar , thanks for ur help

**Comment by xhul-dev** [comment]
Type "taskschd" in Windows Search, then press enter.
When the task scheduler is open, select "Task Scheduler Library".
On the list that appears in the middle, check if you see one called "FanControl".
If yes, delete it (confirm deletion when asked).
Then, restart Windows, and you should be able to delete FanControl.sys manually.
Let us know how it went.

**Comment by Himsonor** [comment]
ok thanks !!!! it can be deleted ,thankyou for ur help

**Comment by Gussy70** [comment]
I tried all of the above; full shut down restarts a few times and I still cannot delete the file. What gives?

**Comment by TheNotoriousKld** [comment]
> ok thanks !!!! it can be deleted ,thankyou for ur help

how did you do it I can't and it's very bothering

**Comment by AndrianoTurner** [comment]
It creates a service named R0FanControl, stop it then delete it, and then you'll be able to delete the .sys file.

**Comment by 9xbt** [comment]
dude what in the actual fuck. there is no service for me named R0FanControl and i have to restart my whole computer just to delete this bullshit?? this app is bloated as fuck, fuck yall but im never using this shit again
