### ISSUE TITLE
are the curves applied when the app is closed as well?

### ISSUE THREAD

**Issue by EmekC** [Rem0o/FanControl.Releases#583]
Is it saved throught the computer or do I have to run as windows start in order to use it?

**Comment by xhul-dev** [comment]
Hello there.
When exiting Fan Control entirely, only the BIOS sends data to the fans.
So yeah, having the app in your system tray is required for the curves to do their job.
The built-in "Start with Windows" option is there for that purpose.
That option is known to mysteriously not work on some systems, let us know if that's the case.
Cheers.
