### ISSUE TITLE
You might want to see this :)

### ISSUE THREAD

**Issue by DoogeJ** [Rem0o/FanControl.Releases#587]
Hi @Rem0o !

Your project has been featured in JayzTwoCents's latest video:
https://www.youtube.com/watch?v=uDPKVKBMQU8

Not really an issue, feel free to close - but if you get an influx of new users/issues/etc; this is probably the reason.

**Comment by jassmith** [comment]
Congratulations :)

**Comment by mharris1984** [comment]
Jay just sent me here for it.  Downloading and donating!   This little utility is worth more then its weight in GOLD.

**Comment by IntelGamer2021** [comment]
Me too

**Comment by fguille94** [comment]
![image](https://user-images.githubusercontent.com/12054064/164815144-33968d81-86c0-4ffd-865f-9c94f043230d.png)

well I think this is actually an issue that needs fixing, I'm here because of Jayz and unable to donate

**Comment by MoridinTX** [comment]
Just downloaded this and donated as well, thanks to Jay.

**Comment by spacepill0w** [comment]
Hehe, I've been a FanControl user for 6 months or so. Very glad it's finally getting some well-deserved attention

**Comment by Rem0o** [comment]
My inbox absolutely exploded, so yes, I noticed :)

Also, got Jay's donation a while ago, figured out a video or something was coming. 

Thanks a lot everyone!

**Comment by Simpy** [comment]
Me here too to get the program and drop you a donation, wish it could have been more...

**Comment by ozdeadmeat** [comment]
$5 USD donated. Hope everyone pitches in. Great app Reme. Keep up the awesome work.

**Comment by EvoPulseGaming** [comment]
Showing my support. Congrats on being featured!

**Comment by Moravuscz** [comment]
I recommended this to Jay (though someone else might have as well and it may not have been my comment specifically that got Jay's attention) so feel free to fault me xD

Been using this for almost a year now and it's been just great!
I've donated last year already, but I just dropped some more because I really appreciate the work you do.
Thank you, and keep up the good work.
