### ISSUE TITLE
GUI appears in nowhere land

### ISSUE THREAD

**Issue by MikeJakubik** [Rem0o/FanControl.Releases#588]
Hi,

The UI of this software looks like it's about to maximize from the bottom right but ends up going to nowhere land. If I hit alt-space to try to move the window it does the same thing.

Windows 11 21H2 build 22000.613

Thanks.

**Comment by bassposaune** [comment]
Yeah same issue with me too

**Comment by xhul-dev** [comment]
Hello there.
Do you use multiple displays|monitors on  your system?

**Comment by bassposaune** [comment]
> Hello there. Do you use multiple displays|monitors on your system?

No

**Comment by xhul-dev** [comment]
> > Hello there. Do you use multiple displays|monitors on your system?
> 
> No

Thanks.
What about softwares that mess with window positions (nview or similar)?

**Comment by bassposaune** [comment]
> > > Hello there. Do you use multiple displays|monitors on your system?
> > 
> > 
> > No
> 
> Thanks. What about softwares that auto align window positions (nview or similar)?

no nothing unusual.  I have a very straight forward PC setup.

**Comment by xhul-dev** [comment]
After you right-clicked the tray icon, and selected "Open", are you able to see the app in the taskbar? (where all currently active windows go)

**Comment by Rem0o** [comment]
4K 200% scaling by any chance? I've seen some weird behavior with some users with scaling and multi-monitor setup.

**Comment by bassposaune** [comment]
I don't have the right click move option
![image](https://user-images.githubusercontent.com/104238503/164873085-7376b7cc-87b3-42fc-af33-8af332dfa6a1.png)

Yes, I do have 4k 250% scaling but I don't want to scale down bc everything is way to small for my eyes

**Comment by xhul-dev** [comment]
[Rem0o](https://github.com/Rem0o)'s lead about the 4K resolution makes sense.

About the "Move" trick, i just realised it seems to have been abandoned in win10.

I digged a bit, and something worth trying would be [Windows key] + [left arrow] or [windows key] + [right arrow].
If it's a window coordinates issue like i suspect, it may solve the problem.

**Comment by bassposaune** [comment]
The windows key left or right doesn't do anything that i can tell.  But, I figured it out.  The move function is on the windows preview thumbnail.  Right click on that preview pop up and then do move and was able to get the UI window to show by moving it.  Thanks guys for the prompt help.

![image](https://user-images.githubusercontent.com/104238503/164874179-7893ae72-da0f-45a8-a564-3dbeac3272d9.png)

**Comment by xhul-dev** [comment]
Glad it worked, and very nice to know where the "Move" option can be accessed.
So it was a coordinates issue after all.

< solved >

**Comment by MikeJakubik** [comment]
Hello,

After messing around with the move window feature I finally got it to display correctly, but there is definitely something wrong with the way it initially launches. I also do not have multi monitors.

Thanks.
