### ISSUE TITLE
Button to "clear heat"

### ISSUE THREAD

**Issue by Maingron** [Rem0o/FanControl.Releases#589]
Maybe you could add some kind of buttons which allow various actions, like Setting all Fans to a defined max value for a specific time, like 1 minute or until restart.

This could help me in the summer to improve my thermal buffer in my room. Also useful if you just want to get rid of the heat for some reason.

**Comment by Rem0o** [comment]
You can create a profile that maxes everything out? Just activate it when needed and switch back when you are done.

Call it "MAX" or something and activate it from the tray icon.

**Comment by Maingron** [comment]
Yes, I think there are multiple workarounds for this specific case. Thank you.
Actually what I wanted to suggest, are "actions", maybe a bit like Samsung's Bixby Routines. Agreeably, I went too much into this very example here.
Anyway, here a list of possible parts:

### Triggers:
- Button
  - Within the program
  - On desktop (shortcut)
  - Via Command line
- Program run
- Temperature hit
- User logged off / in
- CPU / GPU usage between, above, below
- Specific time
- User is in a meeting

### Actions:
Well, run a defined "profile" or "collection", which contains selected Fans and fan speed

Additionally, there's a timer component, of which I'm not sure where to put it. 
This timer component could say "run for a minute after `trigger`.

### Examples
- If button pressed, run profile/collection 1, which sets fan 1,2,3 to 90%
- If game is opened, run profile 2, which sets fans 1,3,5 to 90%; Stop 5 Minutes after game is closed
- If PC hits a critical temperature, run profile 3, which sets all fans to 100%; Stop once everything cooled down again

**Comment by Maingron** [comment]
Please apologize if I'm completely off topic or doubling on features here.

**Comment by Rem0o** [comment]
Well, what you call for is basically automation. However, that goes kinda against the idea of the software, which is a set and forget. Why do you need such specificity? Either your components are hot, or they are not.
What you want to do is cool off temperatures, and a good curve logic already handle that case.

**Comment by Maingron** [comment]
Well, it's just a feature suggestion.
Thought it might be handy for people to get the last few megahertz out of their graphics card when they're gaming or have a silent PC when they're in a meeting.
Or maybe they're running a home server and would like to have silent fans at night but it doesn't matter during the day. Or maybe someone is benchmarking and just wants to push out the heat between runs faster.

**Comment by Rem0o** [comment]
@Maingron  in those very specific scenario, just change configuration with right-click on tray icon => select a dedicated profile.

A big asset of this software is it's relatively "focused" and "light-weight" nature. Doing a lot of different things with a small amount of features that can be combined to do all sorts of stuff.
