### ISSUE TITLE
No RPM or Temps for Radeon RX 5700xt

### ISSUE THREAD

**Issue by LtLasagna** [Rem0o/FanControl.Releases#590]

**Comment by spacepill0w** [comment]
you may want to provide your specific mobo and GPU :)

**Comment by LtLasagna** [comment]
Powercolor Radeon RX 5700XT
Gigabyte X570 UD

**Comment by DfrostX** [comment]
From the readme:

Issues and hardware compatibility
I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
https://github.com/falahati/NvAPIWrapper
Please only open issues for the software itself, UI, feature request and so on.

If you do have a hardware compatibility request and you can provide a working sample of code that can be used in .NET, like with a [Plugin](https://github.com/Rem0o/FanControl.Releases/wiki/Plugins), then feel free to submit that.

**Comment by Rem0o** [comment]
^

 If LHM has updates which adds better support for AMD card, FanControl will get it.

**Comment by mrsikboy** [comment]
thats still where i dont understand. my card is detected ok in LHM
![2](https://user-images.githubusercontent.com/18359769/164872960-15af7d63-c534-40f4-a246-cb53e9b85587.jpg)

**Comment by Rem0o** [comment]
Weird...  If you drop the dll (LibreHardwareMonitorLib.dll) from LHM into FanControl, different result?
Any log.txt?

Also, untick NVApiWrapper from the sensor settings, just in case.

**Comment by mrsikboy** [comment]
let me try

**Comment by mrsikboy** [comment]
the file is already in their

**Comment by Rem0o** [comment]
I meant, replace it with the one you got from LHM. Might be a different version.

**Comment by mrsikboy** [comment]
ok

**Comment by mrsikboy** [comment]
same error i get all the time
![Screenshot 2022-04-23 133549](https://user-images.githubusercontent.com/18359769/164873714-2d23c363-5cf0-442f-aab3-e2be9f526aa2.jpg)

**Comment by mrsikboy** [comment]
then after it finishes, i try to pair and and choose the fan under speeds section, but still unable to control the gpu

**Comment by mrsikboy** [comment]
i just tried something.....i have installed argus monitor and msi afterburner. none of those allow me to adjust the speed of the fans anymore also for the gpu.

there must be an issue somewhere with drivers or windows 11

**Comment by ccaballero646** [comment]
Same issue
Mobo: Gigabyte X570 Aorus ELITE
GPU: Gigabyte Radeeon RX 5700XT Gaming OC 8Gb

**Comment by Rem0o** [comment]
5000 and 6000 radeon GPUs should have their temp reported, but actual fan control on these cards right now doesn't work AFAIK (Ain't got one of those).

Support is provided by
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

**Comment by spacepill0w** [comment]
> 5000 and 6000 radeon GPUs should have their temp reported, but actual fan control on these cards right now doesn't work AFAIK (Ain't got one of those).
> 
> Support is provided by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor

RX 6600 user, can confirm this. Fan curves can be set via AMD software but not through fan control.

**Comment by mrsikboy** [comment]
cheers

**Comment by Michael82548** [comment]
> From the readme:
> 
> Issues and hardware compatibility I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on:
> 
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor https://github.com/falahati/NvAPIWrapper Please only open issues for the software itself, UI, feature request and so on.
> 
> If you do have a hardware compatibility request and you can provide a working sample of code that can be used in .NET, like with a [Plugin](https://github.com/Rem0o/FanControl.Releases/wiki/Plugins), then feel free to submit that.

You can add this information in a new filed called "ISSUE_TEMPLATE.md" that you can place in your .github folder iirc. This should autofill text when you create a new issue

**Comment by Michael82548** [comment]
@

> From the readme:
> 
> Issues and hardware compatibility I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on:
> 
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor https://github.com/falahati/NvAPIWrapper Please only open issues for the software itself, UI, feature request and so on.
> 
> If you do have a hardware compatibility request and you can provide a working sample of code that can be used in .NET, like with a [Plugin](https://github.com/Rem0o/FanControl.Releases/wiki/Plugins), then feel free to submit that.

@Rem0o should add this information in a new filed called "ISSUE_TEMPLATE.md" that you can place in your .github folder iirc. This should autofill text when you create a new issue

More info here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by Rem0o** [comment]
Please, please read the "Issues and hardware compatibility" section of the README.
