### ISSUE TITLE
Not working with Asus Prime B450M

### ISSUE THREAD

**Issue by Ethan17155** [Rem0o/FanControl.Releases#593]
The only control I have is with my GPU. But the program is not doing anything with the case or CPU fans. On top of that, it's only detecting two case fans out of the three headers(All are in use btw). I'm not quite sure what to do because Asus' program for the fans is ACTUALLY cancer and nothing else has worked.

**Comment by DfrostX** [comment]
From the readme:

Issues and hardware compatibility
I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
https://github.com/falahati/NvAPIWrapper
Please only open issues for the software itself, UI, feature request and so on.

If you do have a hardware compatibility request and you can provide a working sample of code that can be used in .NET, like with a [Plugin](https://github.com/Rem0o/FanControl.Releases/wiki/Plugins), then feel free to submit that.

**Comment by DHager** [comment]
This might be "the blind leading the blind", but just today I submitted [a patch to support a missing header for my own motherboard](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/704), if you feel up to trying to fix it yourself.

**Comment by Ethan17155** [comment]
> This might be "the blind leading the blind", but just today I submitted [a patch to support a missing header for my own motherboard](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/704), if you feel up to trying to fix it yourself.

I have done very little Coding in my life. A little Python and Java. I wouldn't even know how to get started with doing that.

> From the readme:
> 
> Issues and hardware compatibility I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on:
> 
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor https://github.com/falahati/NvAPIWrapper Please only open issues for the software itself, UI, feature request and so on.
> 
> If you do have a hardware compatibility request and you can provide a working sample of code that can be used in .NET, like with a [Plugin](https://github.com/Rem0o/FanControl.Releases/wiki/Plugins), then feel free to submit that.

The issue isn't that the program isn't detecting them. I can see them. The issue I'm having is controlling them. I've tried multiple softwares and none actually let me change the fan speed. There seems to be some block on my mother board that only lets its BIOS or the company's awful software control it. Nothing else works.

**Comment by KonouChan** [comment]
I also seem to be having the same problem with Asus B450-F. It detects gpu fan, but only Fan control #4 out of 5 fans (cant control the rest for some reason)

**Comment by TaoRS** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/614

**Comment by Ethan17155** [comment]
> [LibreHardwareMonitor/LibreHardwareMonitor#614](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/614)

This fixed my issue!



> I also seem to be having the same problem with Asus B450-F. It detects gpu fan, but only Fan control #4 out of 5 fans (cant control the rest for some reason). Must be wrong address for the fan? Idk. Mine currently uses IT8665E if you want to look into that.

Here's how I fixed my problem. I downloaded and installed CPUID's HWMonitor and ran it every time before opening Fan control. A lot of people were complaining about this solution. But what I did is add the hardware monitor to Startup by pasting a shortcut in the startup folder. (Press **Window's Key+R** and type **"shell:startup**) I then went into fan control and set it to a 30 second startup delay. When I turn on my computer, HWMonitor starts up and initializes everything, then all I have to do is close it.
