### ISSUE TITLE
Missing temp sensor and Pump RPM for ASUS Maximus VIII Gene

### ISSUE THREAD

**Issue by ryan-mccullough** [Rem0o/FanControl.Releases#598]
Love the app. Unfortunately I can't use it as it can't detect the "T_Sensor" headers on the ASUS Maximus VIII Gene. Also missing the rump RPM but that's not too big of a deal to me. Here's what HWiNFO  sees.

![image](https://user-images.githubusercontent.com/5368131/164861927-52d34f73-75e7-40a3-8d29-b38e025ac190.png)

**Comment by xhul-dev** [comment]
Hello there.

Some sensors aren't supported yet, or they can be by using the hwinfo plugin (which is sadly time-limited if hwinfo wasn't purchased).

As for the pump RPM, it could be that it wasn't paired correctly.
Did you run the automatic fan detection|configuration thing?

**Comment by ryan-mccullough** [comment]
I did let the auto config happen the first time the app started.

How do I tell if the HWiNFO pluggin is working? I copied the 4 files into the plugin folder and restarted Fan Control and HWiNFO but I don't see any additional sensors.

**Comment by DfrostX** [comment]
enable the hwinfo plugin from the sensor settings (top right menu, the 3 dots)

**Comment by Rem0o** [comment]
Make sure it's unlocked also:
![image](https://user-images.githubusercontent.com/14118956/164870799-789056c2-e3ec-4991-a4f5-4f5cbbe079d4.png)

**Comment by ryan-mccullough** [comment]
Hmm. It doesn't appear in sensor settings.
![image](https://user-images.githubusercontent.com/5368131/164872578-ffe8e35c-e50f-4cf6-ae8a-fe3f1ab30bf1.png)

**Comment by Rem0o** [comment]
Any log.txt next to FanControl.exe ?

**Comment by ryan-mccullough** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8546042/log.txt)

**Comment by ryan-mccullough** [comment]
Got it! Had to refresh sensor settings. Maybe add that to the HWiNFO wiki page?

**Comment by Rem0o** [comment]
Ah!   That's actually a current bug where the plugin names aren't displayed properly. It's fixed already, will be in the next release.

Cheers.
