### ISSUE TITLE
Support for Linux? 

### ISSUE THREAD

**Issue by ziogref** [Rem0o/FanControl.Releases#599]
Unsure on how much of a task this would be, but would it possible to build this to work on Linux (more specifically Debian/Ubuntu based OS).

I would LOVE some software to control the fans in my system as with my water cooled loop is cooling the CPU and GPU and I am reliant on my gpu heating up the loop, heating up the CPU before the fans can do their thing. (and gigabytes software is hot trash fire)

Would be happy to test on my system if you looked into developing it.

I have been looking for something on Linux and haven't found anything.

**Comment by DfrostX** [comment]
Answered here: https://github.com/Rem0o/FanControl.Releases/issues/535
