### ISSUE TITLE
Suggestion: Update Notification while minimized

### ISSUE THREAD

**Issue by drosado1** [Rem0o/FanControl.Releases#6]
First off, I love the functionality built into this thing already! Thanks so much for your hard work on this. 

My suggestion is just more of a pet peeve than anything: I don't see update notifications when the fan control starts minimized. I'd love for the app to either drop a notification while still minimized or pop itself open when an update is available so I don't miss it! 

Thanks for for consideration :)

**Comment by Rem0o** [comment]
It's in the pipeline already, I will look into it pretty soon!

**Comment by AdrenalinaGit** [comment]
If this feature is implemented, I would like for there to be an associated checkbox so it would be optional.

**Comment by Eldenroot** [comment]
+1 👍

**Comment by Rem0o** [comment]
Included in next version.
