### ISSUE TITLE
Feature request: Ability to set multiplicative offsets

### ISSUE THREAD

**Issue by DHager** [Rem0o/FanControl.Releases#603]
**Current behavior:** The Sync Curve allows a linear offset, like taking input 60% and modifying by -20% to get 40%. 

**Additional behavior:** The ability to use a multiplicative-offset option, such as  taking 60% and modifying by 0.75x to get 45%.

**Why:** This would be useful for balancing incoming and outgoing airflow between different fans or fan-sets. 

For example, I might have 3 front-intake fans, and I want to roughly balance the work they do across 3 top-exhaust and 1 back-exhaust fan:

|3 intake|3 exhaust|1 exhaust|
|---:|---:|---:|
|100.00%|75.00%|25.00%|
|90.00%|67.50%|22.50%|
|80.00%|60.00%|20.00%|
|70.00%|52.50%|17.50%|
|60.00%|45.00%|15.00%|
|50.00%|37.50%|12.50%|
|40.00%|30.00%|10.00%|
|30.00%|22.50%|7.50%|
|20.00%|15.00%|5.00%|
|10.00%|7.50%|2.50%|
|0.00%|0.00%|0.00%|

With linear offset this can't be done, the other fans will bottom-out too quickly.

**P.S.:** Another way to solve this would be a "Sync Sensor" that takes the output of a graph and makes it available to a Graph curve that can do the conversion that way, however this opens up the potential for loops.

**Comment by Rem0o** [comment]
Sync now has a "proportional" offset.
