### ISSUE TITLE
MSI MAG CORELIQUID P360

### ISSUE THREAD

**Issue by SaintBroseph84** [Rem0o/FanControl.Releases#605]
Will not pick up my MSI MAG CORELIQUID P360 water pump. I have tried several headers and I'm wondering if this isnt because its a 3 pin power and not PMW.

**Comment by Rem0o** [comment]
Make sure to set whatever header to DC mode in your BIOS and not PWM.

**Comment by SaintBroseph84** [comment]
Question. if i use non pmw fans, will this wtill work properly through all of my fans?

Shayne LewisPh# ***@***.*** 

    On Saturday, April 23, 2022, 07:24:08 PM CDT, Rem0o ***@***.***> wrote:  
 
 


Make sure to set whatever header to DC mode in your BIOS and not PWM.
