### ISSUE TITLE
[BUG] Starting Fan Control spins up HDDs although them being in power save mode

### ISSUE THREAD

**Issue by Eiion** [Rem0o/FanControl.Releases#61]
The only noise complaint I have about my PC are two WD40EFRX HDDs. So I'm playing around with power plan settings to finally getting my PC actually completely quiet.

The issue is: Whenever I start up Fan Control to then see how far down I can adjust the rpm of my system fans both my HDDs spin up again.
Using the "Disable Storage Sensors" feature makes no difference - both drives spin up as soon as Fan Control is started (from one of the SSDs).

So I can only assume that either the feature is broken or there has to be something else Fan Control is checking that causes the HDDs to spin up.

**Comment by Rem0o** [comment]
Should be fixed with https://github.com/Rem0o/FanControl.Releases/releases/tag/V57

The setting is now read before the initialization, which should skip activating the HDDs.
