### ISSUE TITLE
No RPM detected for GPU

### ISSUE THREAD

**Issue by Sage009** [Rem0o/FanControl.Releases#610]
I have a Powercolor Red Devil Radeon 6700XT and the startup test doesn't detect an RPM signal from my GPU, even though Adrenaline shows RPM in the performance tab.

**Comment by Samm223** [comment]
make sure all 3rd party software is closed. had the same issue with my 3090 but after closing Icue and MSI and rescanning for sensors it picked up both GPU fans

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/618
