### ISSUE TITLE
Gigabyte Aero 15-YA (Laptop)

### ISSUE THREAD

**Issue by Dracwula** [Rem0o/FanControl.Releases#611]
Can not detect any fans?

**Comment by Rem0o** [comment]
Sadly, most laptops are not supported, since they use proprietary stuff.

**Comment by timber-schroeder** [comment]
For anyone else stumbling across this trying to use FanControl for Gigabyte laptops, there is a very good piece of software called [aeroctl](https://gitlab.com/wtwrp/aeroctl) that includes some basic fan control funcationality. Its no replacement for FanControl, but its a lot better than the godawful Gigabyte Control Center.

**Comment by Rem0o** [comment]
@timber-schroeder  Took a quick look, since it's .NET, I think wrapping that code in a plugin could have good potential 🚀
