### ISSUE TITLE
Asus Rog G14

### ISSUE THREAD

**Issue by Sesam17** [Rem0o/FanControl.Releases#612]
Dear remoo thanks for this marvelous software 

currently i can see my cpu temp and sensor but no controls is shown in the ui for the fans i have an Asus Rog g14 2020 laptop would you be able to implement its controls

**Comment by JTJ8** [comment]
Thanks in advance for the effort. 

Similar request... I have a G14 2022 (Ryzen 6900H + RX 6800S)

I would be happy to test, or help with anything else I'm able to do.

**Comment by SavageAUS** [comment]
Metabox laptop here (Clevo)
Temp sensors are detected but no fans as well.

**Comment by DfrostX** [comment]
See README.

Sadly, laptops use proprietary stuff which isn't standard.
