### ISSUE TITLE
SAMSUNG 980 PRO SSD 1TB showing 0 degrees

### ISSUE THREAD

**Issue by multigraph123** [Rem0o/FanControl.Releases#617]
SAMSUNG 980 PRO SSD 1TB showing 0 degrees
![2022-04-23_10-31-05](https://user-images.githubusercontent.com/7667024/164884998-37f0d734-6ea3-4028-bbe0-287ffffaf474.jpg)

**Comment by multigraph123** [comment]
Downloaded LibreHardwareMonitor and there teperature showed up correctly

**Comment by Rem0o** [comment]
Did you upgrade to V111?

I made sure it uses the exact latest dll from LHM.

**Comment by feeph** [comment]
I can confirm this issue still persists in v111.

FYI: In addition to the Samsung 980 Pro 1TB I have a Firecuda 530 and a Western Digital HDD in the same motherboard. Both are showing up fine.

**Comment by multigraph123** [comment]
Yes I did upgrade and still same issue

![2022-04-24_09-38-40](https://user-images.githubusercontent.com/7667024/164960244-b808dd80-f8bc-4fba-8f43-8bfc45fa5fc0.jpg)

**Comment by fulm44** [comment]
My 980 Pro shows up correctly for me, but it's the 2TB version.

![image](https://user-images.githubusercontent.com/84825929/164977095-938d0036-f8e1-47b4-adaa-5729f958286e.png)

**Comment by multigraph123** [comment]
updated NVMe firmware and now temp shows as should :)
