### ISSUE TITLE
Unexpected curve outputs, seemingly changing at random

### ISSUE THREAD

**Issue by nutsforalmonds** [Rem0o/FanControl.Releases#62]
I've been having this issue with an NCT6678D (which I realize was only recently supported by LibreHardwareMonitor). 

Specifically, my water pump is using a flat curve set to 15%, but the signal actually being sent will at random change to another value. Values it sets itself to seem to be either 0, 40, or 100. Changing the fan curve selected for the water pump away from the flat curve and back will momentarily result in the correct value being used.

I also have a graph curve that will at random output whatever the maximum value of the curve is regardless of the input value. Changing the input source for the curve has no effect. Editing the curve in any way will result in expected operation for a variable amount of time before it pegs itself to the maximum value again.

![image](https://user-images.githubusercontent.com/5829782/98280938-f7319a80-1f50-11eb-9ed9-6a86d82e6c50.png)

Both issues happen independently of one another and can remain in this state for seconds to 10s of minutes (and anecdotally seems to be happening more often and for longer recently).

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5496198/log.txt)

**Comment by Rem0o** [comment]
Can you show me the Edit window of that specific curve?

**Comment by nutsforalmonds** [comment]
![image](https://user-images.githubusercontent.com/5829782/98451848-aeb7df80-20fe-11eb-94db-29c929d6a7ce.png)

Additional things I've noticed: only one of several graph curves ever results in the behavior described, but every control that uses a flat curve is affected.

**Comment by nutsforalmonds** [comment]
This issue seems to be fixed in V59. I've been at my macine for 9 hours and haven't had a single anomaly since updating.
