### ISSUE TITLE
Clevo laptop compatibility 

### ISSUE THREAD

**Issue by j3tstream** [Rem0o/FanControl.Releases#620]
Hi there, I have tried this software on my clevo p170em, and like most softwares it doesnt recognize the laptop fans on clevo.
There is this piece of software https://github.com/zuyan9/RLECViewer that has been used as a workaround for many years, I wonder if you could integrate this somehow or use it as reference for the fan drivers and sensors. 

Thank you for your work. Very appreciated :)

**Comment by Rem0o** [comment]
See readme about hardware compatibility.
