### ISSUE TITLE
Only detects 2 of the fans on a rtx 3070 EVGA Ftw3 Ultra

### ISSUE THREAD

**Issue by Methodicle** [Rem0o/FanControl.Releases#621]
![image](https://user-images.githubusercontent.com/48024196/164892476-fb8b4d3c-1843-4b4c-bffc-3db5675317b1.png)

**Comment by ashleybeshir** [comment]
it had same issue but turns out control 2 is right 2 fans and control 1 is left  single fan.

**Comment by Methodicle** [comment]
> it had same issue but turns out control 2 is right 2 fans and control 1 is left single fan.

Ah thanks a bunch, that makes things easier!
