### ISSUE TITLE
FANS WON"T STOP SPINNING AT MAX EVEN WHEN I DELETE PROGRAM

### ISSUE THREAD

**Issue by Freebandstv** [Rem0o/FanControl.Releases#622]
I didn't like the fan curves being set in this program so I deleted it. They were all very noisy. After deleting even when I reset the curve in bios it does not work fans stuck at 100% please help. How do I reset the program?

**Comment by DfrostX** [comment]
This is weird. Closing the program should bring back bios curve as this overide the bios only while running.

But anyway... Close the program, delete its folder in windows, reboot...

**Comment by Rem0o** [comment]
Going to sleep/reboot/shutdown will revert back to whatever the bios normally does.

**Comment by SILENCEuk** [comment]
similar issue curves remain even after deletion and reboot

**Comment by Rem0o** [comment]
Well at that point the software has no influence what so ever anymore. You got to set your stuff in your bios.

**Comment by ShadowRep** [comment]
Maybe your BIOS fancontrol is set to "Auto" instead of "pwm" or "voltage"?

This is the case with my x570 Gigabyte Aorus Master.
When set to "Auto" the fans are set to 100% because the mainboard fails to detect that it should use pwm to control the fans. When set to "pwm" it works as it should.

**Comment by Freebandstv** [comment]
> Maybe your BIOS fancontrol is set to "Auto" instead of "pwm" or "voltage"?
> 
> This is the case with my x570 Gigabyte Aorus Master. When set to "Auto" the fans are set to 100% because the mainboard fails to detect that it should use pwm to control the fans. When set to "pwm" it works as it should.

This is the one the worked I'm running the x570s Aorus Master and for some reason even though I deleted the program it set all my fans to 100% and resetting fan control in bios wasn't working.

Thanks for the help.

**Comment by ShadowRep** [comment]
I'm glad I was able to help.
