### ISSUE TITLE
Installed while watching a youtube video now broke vido streaming seemingly

### ISSUE THREAD

**Issue by SmurfNturf** [Rem0o/FanControl.Releases#625]
Was refered to your software from a jays2 cents video. downloaded and installed while watching and when it got to scanning fan controllers it took the video to about 1 frame every 5 seconds and no audio, it now does it perpetually across all browsers even after deleting and reinstalling, have restarted closed tasks and the program. cant seem to fix it.

**Comment by Rem0o** [comment]
Seems like something is hanging up. Go the sensor settings, and try disabling stuff until you don't get that behavior. Notice that you will get missing sensors errors, as you are removing them.
