### ISSUE TITLE
unable to cleanly remove?

### ISSUE THREAD

**Issue by SILENCEuk** [Rem0o/FanControl.Releases#626]
having issues so would like to remove all settings.

even after deleting all files and resetting fans in other controllers the setings from this remain. any ideas?

**Comment by Rem0o** [comment]
Put your computer to sleep and wake it back up, should reset everything back to BIOS.

**Comment by SILENCEuk** [comment]
tried this multiple times. my l connect group 1 fan still spins up at random (the issue i had with this script) even after doing this cycle multiple times

**Comment by Rem0o** [comment]
In any case, it's impossible for FanControl to do anything if it was removed.  Whatever behavior you got right now is not on the software, it's most likely your BIOS config which acts weird.

**Comment by saynotocode** [comment]
try a complete power down then boot up. I've found that fancontrol can cause issues with my bios (gigabyte z590) that persist over restarts, but go away after a complete shutdown.

**Comment by WarpRules** [comment]
If powering completely down doesn't work, maybe also try turning the PSU completely off (using its power button) after having shut down the system. (Even with a shut down system the BIOS is still running at some level if it has power. After a full power cycle it will start fresh.) If that fails too, as a last resort try clearing the CMOS (this will restore all BIOS settings to factory defaults). Your motherboard documentation will have instructions on how to do that.
