### ISSUE TITLE
support winget 

### ISSUE THREAD

**Issue by cjwijtmans** [Rem0o/FanControl.Releases#628]
https://github.com/microsoft/winget-pkgs

**Comment by mekwall** [comment]
[Anyone can add packages to winget](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest) but the package must have an installer/uninstaller specified in the manifest that winget can use. So this issue is blocked until an installer is added. Do you have any plans on doing that @Rem0o?

**Comment by Rem0o** [comment]
Well, FanControl doesn't have any installer, since it's a portable exe.

**Comment by Rem0o** [comment]
You could just curl the zip (https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip?raw=true) and that would work from the command line.

**Comment by Rem0o** [comment]
@mekwall  not on the roadmap, since its a portable app, I don't see the benefits of adding additional bulk for a single exe with dlls, plus it has auto-update already.  I prefer keeping it as simple as possible.

**Comment by cjwijtmans** [comment]
> @mekwall not on the roadmap, since its a portable app, I don't see the benefits of adding additional bulk for a single exe with dlls, plus it has auto-update already. I prefer keeping it as simple as possible.

A bit of a weird reply. Packages exist for a reason. So much so that microsoft created the MSIX packages. They allow tracking of files and (registry) settings. Packages could even run in a container or a sandbox for security and whatnot. 

https://docs.microsoft.com/en-us/windows/msix/packaging-tool/generate-template-file

**Comment by dschoerk** [comment]
i would love to see support for package managers like winget and chocolatey. it allows to quickly install the tool on a new pc. reducing the need to implement and maintain the update routine could even simplify the codebase.

**Comment by mekwall** [comment]
[winget zip installs](https://github.com/microsoft/winget-cli/pull/2500) are in preview so anyone can create a manifest in the [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo to install FanControl.

**Comment by Rem0o** [comment]
Feel free to package whatever version in there.

**Comment by xIUPITERx** [comment]
> [winget zip installs](https://github.com/microsoft/winget-cli/pull/2500) are in preview so anyone can create a PR with a manifest in the [winget-pkgs](https://github.com/microsoft/winget-pkgs) repo to make it possible to install FanControl with winget.

I tried it with Komac, but unfortunately I couldn't do it. But if you have a bit of technical know-how, you should be able to do it very quickly.

**Comment by xIUPITERx** [comment]
If you would then add a switch to disable the in-app updater, part of #1629 would also be solved.
Winget takes care of entering the version number, etc.
The winget download link should then always lead to the GitHub repo to keep the update process safe.

**Comment by xIUPITERx** [comment]
and maybe a non-portable installer version is not that far away
