### ISSUE TITLE
Temperature sensor issue on Ryzen 5000

### ISSUE THREAD

**Issue by Mettkrieger** [Rem0o/FanControl.Releases#63]
There seems to be an issue with Ryzen 5000 CPUs and their temperature. None of the sensors I can choose match the temperature according to ryzen master / CPUID HWMonitor. Like: [https://i.imgur.com/S21EkqW.png](url) compared to: [https://i.imgur.com/jYLachM.png](url) CPU from HWInfo matches the reported temperature from ryzen master

**Comment by Rem0o** [comment]
These CPUs just came out,  support should come soon.

**Comment by Mettkrieger** [comment]
I guess [https://github.com/LibreHardwareMonitor/LibreHardwareMonitor](url) has to be updated for that?

**Comment by Rem0o** [comment]
Exactly.

**Comment by abqnm** [comment]
> Exactly. Seems like an issue has already been opened [LibreHardwareMonitor/LibreHardwareMonitor#310](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/310)

Looks like Zen3 support has now been added to LibreHardwareMonitor, as the above issue was closed and merged with https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/328.

**Comment by Rem0o** [comment]
@abqnm will update soon.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V57

**Comment by Rem0o** [comment]
Can't test, close if it works.

**Comment by Mettkrieger** [comment]
seems to work https://i.imgur.com/k1HtCoi.png
