### ISSUE TITLE
Does not detect DIMM temp on Asrock Taichi X570

### ISSUE THREAD

**Issue by Kendeue** [Rem0o/FanControl.Releases#633]
Detecting dimm temp has always worked fine in hwinfo but fancontrol does not seem to be able to do so. Anything I can provide to troubleshoot this?

**Comment by DfrostX** [comment]
This program is based on LibreHardwareMonitor, not Hwinfo. Most likely its not supported by LHM.

2 suggestions: 

1. You can try to download the latest LHM .dll from their repo
2. If 1. does not fix this, ask for support on LHM 
3. You can try to use the HWinfo plugin, see instructions here https://github.com/Rem0o/FanControl.Releases/discussions/631 but note that it will require the paid version of HWinfo (not affiliated with FanControl dev) to get full support to the feature that will make it work without any nag
