### ISSUE TITLE
Adding an option to completely hide the tray icon

### ISSUE THREAD

**Issue by RinMinase** [Rem0o/FanControl.Releases#635]
Similar to both: #261 and #421

Thank you for finally combining all concurrently running fan control applications into one location. 😁

The application is extremely great, but it still has a tray icon which for me seems a bit unnecessary. Since the only time to open the application again is only when you want to reconfigure your setup, or to check the status of each fan. Running it as a service-like application would reduce another clutter found on your tray icon which you only open at extremely rare times (after configuring your fan setup)

A suggestion to the additions would be:
- A toggle switch in the menu to hide the tray icon (defaults to unchecked / tray icon shown)

  _(if the toggle stated above is checked)_
- Closing the application does not minimize it to tray. This makes it a "full" background application without anything to show to the user
- Exiting the application can be done using the menu **once you open the application**
- Opening the application can be done using either the (windows) shortcut or the executable file to reopen the existing application
    - Either that or opening the application would close the existing application then run a new instance of the application

**Comment by Rem0o** [comment]
What you describe is fancontrol to run as a service and the UI to be a client to that service.
Dupplicate of https://github.com/Rem0o/FanControl.Releases/issues/52 and https://github.com/Rem0o/FanControl.Releases/issues/135.
