### ISSUE TITLE
Cant uninstall

### ISSUE THREAD

**Issue by Roby2336** [Rem0o/FanControl.Releases#637]
cant uninstall the program
![dwsg](https://user-images.githubusercontent.com/57678985/164943699-46b10612-a77e-4d4f-8e94-1a0d290276db.PNG)
![erg](https://user-images.githubusercontent.com/57678985/164943700-3ccc48a8-d1e7-4c13-b48e-cdda998aa311.PNG)

**Comment by xhul-dev** [comment]
Hello there.
1) Open the task scheduler (type "taskschd" in Windows search).
2) In the Task Scheduler Library, delete the task called "FanControl" if there is one.
3) Restart system.
You're welcome.
