### ISSUE TITLE
BitDefender blocking download

### ISSUE THREAD

**Issue by pocketdrummer** [Rem0o/FanControl.Releases#64]
Received warning from BitDefender when attempting to download this app. See Below:

![image](https://user-images.githubusercontent.com/43502851/98432168-74076600-2070-11eb-9cbb-a1455a89fb8a.png)

**Comment by Rem0o** [comment]
Well what can I do?

**Comment by jimmydorry** [comment]
It's getting picked up via malwarebytes too.

----

It's getting picked up via malwarebytes too.

----

Malwarebytes
www.malwarebytes.com

-Log Details-
Scan Date: 11/16/20
Scan Time: 9:30 AM
Log File: 7a9a79f4-279a-11eb-b2c8-001b21bf605c.json

-Software Information-
Version: 4.2.0.82
Components Version: 1.0.1025
Update Package Version: 1.0.32946
License: Premium

-System Information-
OS: Windows 10 (Build 19041.508)
CPU: x64
File System: NTFS
User: System

-Scan Summary-
Scan Type: Threat Scan
Scan Initiated By: Scheduler
Result: Completed
Objects Scanned: 361692
Threats Detected: 7
Threats Quarantined: 0
Time Elapsed: 3 min, 40 sec

-Scan Options-
Memory: Enabled
Startup: Enabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Detect
PUM: Detect

-Scan Details-
Process: 1
RiskWare.Suspicious.TaskExecution, C:\USERS\USERNAME\DOWNLOADS\FANCONTROL.RELEASES-47\FANCONTROL.EXE, No Action By User, 10249, 857638, , , , , 3DDCAC094850A9D14332D97B7281DAF4, 607DEEE4DEDFFD90CC89BB6AD37732D9006020530954D6611B22CA649A462B10

Module: 1
RiskWare.Suspicious.TaskExecution, C:\USERS\USERNAME\DOWNLOADS\FANCONTROL.RELEASES-47\FANCONTROL.EXE, No Action By User, 10249, 857638, , , , , 3DDCAC094850A9D14332D97B7281DAF4, 607DEEE4DEDFFD90CC89BB6AD37732D9006020530954D6611B22CA649A462B10

Registry Key: 3
RiskWare.Suspicious.TaskExecution, HKLM\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION\SCHEDULE\TASKCACHE\TREE\FanControl, No Action By User, 10249, 857638, , , , , , 
RiskWare.Suspicious.TaskExecution, HKLM\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION\SCHEDULE\TASKCACHE\TASKS\{738858FB-1A92-47AA-83D1-38C16492191D}, No Action By User, 10249, 857638, , , , , , 
RiskWare.Suspicious.TaskExecution, HKLM\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION\SCHEDULE\TASKCACHE\LOGON\{738858FB-1A92-47AA-83D1-38C16492191D}, No Action By User, 10249, 857638, , , , , , 

Registry Value: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)

Data Stream: 0
(No malicious items detected)

Folder: 0
(No malicious items detected)

File: 2
RiskWare.Suspicious.TaskExecution, C:\WINDOWS\SYSTEM32\TASKS\FanControl, No Action By User, 10249, 857638, , , , , DA06B741849D8DB6E2FE84E461814373, 0067230909361321080366DCBD01F282AEDB895A737FBEEE954CE461492F1C8B
RiskWare.Suspicious.TaskExecution, C:\USERS\USERNAME\DOWNLOADS\FANCONTROL.RELEASES-47\FANCONTROL.EXE, No Action By User, 10249, 857638, 1.0.32946, , ame, , 3DDCAC094850A9D14332D97B7281DAF4, 607DEEE4DEDFFD90CC89BB6AD37732D9006020530954D6611B22CA649A462B10

Physical Sector: 0
(No malicious items detected)

WMI: 0
(No malicious items detected)


(end)

**Comment by Cubox** [comment]
From the Malwarebytes output, it looks like it's considering the addition to task scheduler suspicious.
Nothing the author can do, it's just anti PUA protection that flags unknown binaries.
