### ISSUE TITLE
Minus Decrement is Near impossible to see

### ISSUE THREAD

**Issue by kaseyawolf2** [Rem0o/FanControl.Releases#644]
While Editing Graph Curves the Minus Decrement if impossible to see when the using the light theme

visible in Dark Mode
![image](https://user-images.githubusercontent.com/11696792/164950041-84705971-717b-4956-ac43-349ec14bbfb7.png)
Invisible in Light mode
![image](https://user-images.githubusercontent.com/11696792/164950051-a97c0504-d462-4d96-b4af-2bc1c885c02a.png)

Possible way to fix
turn it red
![image](https://user-images.githubusercontent.com/11696792/164950104-f0cb26c2-03f4-4974-8b35-9dda76c4abf8.png)
![image](https://user-images.githubusercontent.com/11696792/164950117-1fc3d55e-c92e-4d0f-be0c-113cc8ca67d6.png)

**Comment by feeph** [comment]
Upvoting.

Using light theme as well and was wondering why there's a `+` but no `-` button. This Github issue made me realise there actually is a `-` and it's just not noticeable in light theme.

**Comment by Rem0o** [comment]
Wil be fixed in the next version!

![image](https://user-images.githubusercontent.com/14118956/164984217-f540849c-96a5-4de2-81c2-071c4f24ea22.png)
![image](https://user-images.githubusercontent.com/14118956/164984227-479acf41-22f9-4a7d-9772-b365d7e19353.png)

**Comment by Rem0o** [comment]
See V112
