### ISSUE TITLE
System.ArgumentOutOfRangeException: Index must be within the bounds of the List.

### ISSUE THREAD

**Issue by emreaktrk** [Rem0o/FanControl.Releases#649]
Reproduce Steps:
- Show hidden cards unchecked in hamburger menu
- Move first any (controls, speeds, curves) material card to last one

I attached [log.txt](https://github.com/Rem0o/FanControl.Releases/files/8549076/log.txt)

Thank you for this masterpiece software.
Cheers

**Comment by Rem0o** [comment]
Yup, can reproduce.
Dumb index logic from the collection because the "move" action actually copies, then remove the original location, which messes up the indexes.

**Comment by Rem0o** [comment]
Fixed in 112.
