### ISSUE TITLE
Add AMD graphic card support for fan rpm readings

### ISSUE THREAD

**Issue by Eldenroot** [Rem0o/FanControl.Releases#65]
Would be nice to get info from fans - amd - msi 5700 graphic card. in Argus monitor it is displayed correctly and even in hardwaremonitor... not here :(

**Comment by Rem0o** [comment]
I don't have a working AMD driver for the newer cards. LibreHardwareMonitorLib GPU support is not up to date. 
If you could make it work there, I would port it here. 
As a workaround I'm using NvApiWrapper for Nvidia GPUs, but I don't have any alternatives for AMD.
