### ISSUE TITLE
Wrong Fan RPM Speed up until I start HWMonitor or HWInfo.

### ISSUE THREAD

**Issue by VatorArt** [Rem0o/FanControl.Releases#652]
Edit: The issue isn't related to actual Fan Control software, it's the LibreHardwareMonitor

Hi, I don't want to pile on with issue reporting, and if this is not related to Fan Control software, I apologies. 

When I start up the computer, and open Fan Control, the RPM Speeds on my fans are wrong and show values that these fans can't even reach. (Due to this, fans spin at higher rate than they should, thankfully not actually trying to reach 3900rpm)

While this is going on, if I open HWMonitor or HWInfo as a separate program, the RPM Speeds go back to normal values.
Turning HWMonitor or HWInfo off after the RPM Speeds have been fixed, doesn't impact the RPMs and they stay normal until next reboot.

I don't mind solving this issue on daily basis, or just making HWMonitor and Fan Control start up on boot automatically, but figured it's maybe something worth looking into.

Specs:
AMD R5 1600X
ASUS B350 Prime Plus (BIOS ver. 5606)
Kingston 32GB 3000MHz
AMD Sapphire Nitro+ RX480 4GB 

Fans (from left to right on the image): 
1x Fans from GPU ("GPU Fan")
1x 120mm Cooler Master PWM (Fan Control # 1  [CPU Cooler Tower] )
1x 120mm Thermaltake 3pin (Fan Control # 2 [Case Exhaust] )
3x 120mm Arctic PWM (Fan Control # 3 [Case Intakes Daisy-Chained] )

RPM Speeds right after a clean boot up
![ImageGlass_6XX3WFHylv](https://user-images.githubusercontent.com/78219944/164972012-8290338c-08a3-4582-bf03-d0d8df278966.png)

RPM Speeds right after I manually start HWMonitor or HWInfo
![ImageGlass_DFBpsmPutb](https://user-images.githubusercontent.com/78219944/164972036-90146e81-9707-4731-9a34-270a9d81373b.png)

**Comment by VatorArt** [comment]
Welp, I should've done this before posting. 
I installed LibreHardwareMonitor, rebooted the computer, and started the LibreHardwareMonitor on it's own, and it's showing those same bad RPM values. After opening HWMonitor alongside it, LibreHardwareMonitor starts showing correct values.

The issue is indeed not with Fan Control, but rather the LibreHardwareMonitor.
My bad.
![image](https://user-images.githubusercontent.com/78219944/164972612-1135ac5d-518b-4770-b53d-b2e52213ebe3.png)

**Comment by tranviethaidn** [comment]
how to fix
