### ISSUE TITLE
Add a "unit" inside the IPluginSensor interface

### ISSUE THREAD

**Issue by medevil84** [Rem0o/FanControl.Releases#653]
Hello, would it be possible to add a property of type string named "unit" inside the IPluginSensor interface? Currently the [FanControl.AquacomputerHighFlowNext](https://github.com/medevil84/FanControl.AquacomputerHighFlowNext/issues/2) plugin reports the water quality and water conductivity but are shown in the interface as "RPM". It would be nice to report it as percent and uS/cm.

**Comment by Rem0o** [comment]
But what for? How would those be of used by the software?

**Comment by medevil84** [comment]
Correct, it's just a "cosmetic" fix.

**Comment by Rem0o** [comment]
Couldn't you simply not add those sensors to the container in your plugin?

**Comment by medevil84** [comment]
I would, but then I'll need to install additional software to watch those value... if this isn't possible it's ok, I understand.

**Comment by Rem0o** [comment]
Not possible with the current plugin system. Will close.
