### ISSUE TITLE
Feature not working "Hysteresis only applies on the way down " check box.

### ISSUE THREAD

**Issue by IronBeardKnight** [Rem0o/FanControl.Releases#654]
When this is checked it will still apply the settings to temp increase and fan increase.

When checking this box it is supposed to only hold rpm / after the temp has dropped not on temp rise.

**Comment by Rem0o** [comment]
You are right, somehow the logic going up was still from the response time and hysteresis value.

Will fix.

**Comment by Rem0o** [comment]
See V112
