### ISSUE TITLE
Missing fan on GPU

### ISSUE THREAD

**Issue by Miloye11** [Rem0o/FanControl.Releases#658]
Hi, I have 3 fan RTX 3050 GPU (https://www.gigabyte.com/Graphics-Card/GV-N3050GAMING-OC-8GD#kf) but it detects only 2 fans. Great work btw

**Comment by Rem0o** [comment]
The cards only have 2 channels. 2 fans are hooked to the same 1. Jay was wrong saying there would be 3 cards in the software for 3 fans.
