### ISSUE TITLE
Hidden window or something

### ISSUE THREAD

**Issue by asheenlevrai** [Rem0o/FanControl.Releases#659]
Hi Remy :)

I just DLed your app (v111) and installed it on my machine.
I went through the guided setup wizard and everything went smoothly. I saved my config at the end.

Now I have a tray icon corresponding to the app but I cannot make any change or display the app UI. It seems like the window is hidden or something.

If I alt-tab, I can see the preview of the window corresponding to the app (it's all black btw) but switching to it doesn't display anything...

I tried rebooting the rig but that didn't help...

Probably I missed something?

Can you help me troubleshoot that?

Side questions:
 - Does the app support automatic launch at startup or do I need to set that up manually?
 - Does the app support automatic update or do I need to monitor your github account regularly?

Thank you very much in advance for your help and congratulations on the amazing work.

Best,
-a-

**Comment by Simpy** [comment]
I not had it hide on me, but If you right click the icon in the tray does it show "open" and can you click it? - and yes I have found it supports auto startup, menu on left, tick the boxes, and same for updates, right menu and click check for updates.

**Comment by Simpy** [comment]
> Can you help me troubleshoot that?

supports auto startup, menu on left, tick the boxes, and same for updates, right menu and click check for updates.

**Comment by xhul-dev** [comment]
To get the window back, first right-click on the Fan Control tray icon, and select "Open".
Then, press [Windows key] + [Up arrow] (if that doesn't do anything, left-click on Fan Control in the taskbar once, and press again).

**Comment by asheenlevrai** [comment]
> > Can you help me troubleshoot that?
> 
> can you right click the tray icon and then choose "open" does that do anything?, it does supports auto startup, menu on left, tick the boxes, and same for updates, right menu and click check for updates.

It does "nothing". Display a "transparent" window I guess...

**Comment by asheenlevrai** [comment]
> To get the window back, you first need to have Fan Control open in the taskbar (if not already the case, either execute it, or if it's already visible in the systray, right-click on it and select "Open"). Then, you need to make sure it's the active window (if not already the case, select it using [Alt] + [Tab]). Finally, press [Windows key] + [Up].

Did all that (as mentioned). No effect...

**Comment by Rem0o** [comment]
in your CACHE file, if you open it with a text editor, what are the window coordinate ?

**Comment by xhul-dev** [comment]
> in your CACHE file, if you open it with a text editor, what are the window coordinate ?

This.

> Did all that (as mentioned). No effect...

Despite it does the exact same thing, people have been more successful with the second method, which consists in right-clicking on the mini-window that appears when you hover on FC when it's in the taskbar, then select "Maximize".
Likewise, it can only work if Fan Control is the active window beforehand, don't hesitate to use [Alt]+[Tab] to be sure.

**Comment by asheenlevrai** [comment]
> in your CACHE file, if you open it with a text editor, what are the window coordinate ?

Here is the content of my CACHE file:
"{
  "CurrentConfigFileName": "userConfig.json",
  "Main": {
    "DisableDonationPopup": true,
    "FirstLaunch": false,
    "Height": 500,
    "Left": 1570,
    "PopupShownDateTime": "2022-04-24T22:53:15.1523035+02:00",
    "Top": 830,
    "Width": 700
  }
}"

However, it wasn't updated since yesterday.
When I launched FC just now, the file FileControl.sys was modified (opening it with Notepad results in a bunch of gibberish to me).

**Comment by asheenlevrai** [comment]
> > Did all that (as mentioned). No effect...
> 
> Despite it does the exact same thing, people have been more successful with the second method, which consists in right-clicking on the mini-window that appears when you hover on FC when it's in the taskbar, then select "Maximize". Likewise, it can only work if Fan Control is the active window beforehand, don't hesitate to use [Alt]+[Tab] to be sure.


This worked!!!!  :-D
Thank you so much.

It was still behaving the same (hidden) after closing and restarting, though.
I was able to "solve" the issue by draging the FC window so it was no longer fullscreen and then the app would behave normally after closing and restarting (window is no longer hidden).

I guess FC doesn't like to be displayed fullscreen in my setup, for some reason.

Thanks a lot to all of you.
Best,
-a-

**Comment by asheenlevrai** [comment]
Let me know if you want me to run any further tests or something.

**Comment by danko12321** [comment]
The right click taskbar mini window and "Maximise" worked for me! Windows + Arrow keys did not. Display is 3840x2160.

**Comment by asheenlevrai** [comment]
> The right click taskbar mini window and "Maximise" worked for me! Windows + Arrow keys did not. Display is 3840x2160. Edit: I do have to do this everytime I want to access the gui which is unfortunate. Love the software though apart from that! Edit: As with above commenter this is fixed if I manually resize the window to not fullscreen then close and re-open, stops working if you maximize it close and reopen

Yup. 100% the same here.

**Comment by Rem0o** [comment]
When you open and get a hidden window, post the CACHE file content here. That file tracks where the window spawns.

**Comment by asheenlevrai** [comment]
> Here is the content of my CACHE file: 
> { 
> "CurrentConfigFileName": "userConfig.json", 
> "Main": { 
> "DisableDonationPopup": true, 
> "FirstLaunch": false, 
> "Height": 500, 
> "Left": 1570, 
> "PopupShownDateTime": "2022-04-24T22:53:15.1523035+02:00", 
< "Top": 830, 
> "Width": 700 
> } 
> }
> 

What part of this is useful? And How can I use it to solve the problem.
NOTE: I don't need to solve anything now since the right click taskbar mini window and "Maximise" works for me too. But I'm curious.

**Comment by Rem0o** [comment]
Left, Top is the (X,Y) position. If that number is negative or some huge value, might give us a hint.

**Comment by asheenlevrai** [comment]
OK. So in my case the values were reasonable (4K display) but still the windows was actually fullscreen (or minimized?) and transparent.

**Comment by danko12321** [comment]
Yeah mine didn't seem obscure but mine was also 4k, something about that it doesn't like.

**Comment by Rem0o** [comment]
Are you guys on multi-display setups with different resolutions on each display?

**Comment by asheenlevrai** [comment]
single monitor here too

**Comment by danko12321** [comment]
I reinstalled windows (for unrelated reasons) and after installing the latest version of fan control (112) I did not get the same issue. Not sure if you made a change for this issue but if you did it worked for me :)

**Comment by Rem0o** [comment]
I did in V112.
