### ISSUE TITLE
Version 55 doesn't recognize any of my fans (only my graphics card) after reboot

### ISSUE THREAD

**Issue by tuschla** [Rem0o/FanControl.Releases#66]
Working flawlessly in the setup process with every fan fully controllable. After reboot it stops recognizing any of my fans and returns an error. Only my graphics card is still recognized. If I setup the program again everything is recognized again.
Didn't have this issue with earlier versions. 
Specs: Gigabyte X570 Pro I WIFI

**Comment by Rem0o** [comment]
What error? Do you have a log file in the app folder?

**Comment by tuschla** [comment]
Here is an image of the error. It always happens after a reboot. 
![image](https://user-images.githubusercontent.com/53692914/98470133-09773700-21e4-11eb-845d-1a5624c01826.png)
Is this the log file you were asking for?
[FanControl_log.txt.txt](https://github.com/Rem0o/FanControl.Releases/files/5506653/FanControl_log.txt.txt)

**Comment by tuschla** [comment]
Now it gives me the same error with every version. Might have something to do with my different GPU? It's the only thing that is still detected after a reboot.

**Comment by Rem0o** [comment]
@tuschla  for the log I was looking for, look for a log.txt file in your fancontrol folder.

**Comment by tuschla** [comment]
Here it is. It has only been generated two minutes ago. That's why I couldn't find it.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5506793/log.txt)

**Comment by Rem0o** [comment]
Updater.exe simply redownload the same exe you got in your folder, it shouldn't change anything. Might be closing/reopening that fixes the issue.   If you use "refresh sensor detection" in the top right menu, does it restores your sensors?

**Comment by tuschla** [comment]
Unfortunately "refresh sensor detection" doesn't change anything.

**Comment by tuschla** [comment]
So I did a stupid workaround where the updater is executed at startup. I will however report here if the problem is somehow fixed in the future

**Comment by Rem0o** [comment]
> So I did a stupid workaround where the updater is executed at startup. I will however report here if the problem is somehow fixed in the future

What does that achieves?
