### ISSUE TITLE
Corsair iCUE

### ISSUE THREAD

**Issue by woomdawg** [Rem0o/FanControl.Releases#661]
Will not work with Corsair iCUE commander.

**Comment by DfrostX** [comment]
No it wont

Corsair commanders are not supported by LHM. A plugin is in devellopement but it is still in beta. see here https://github.com/Rem0o/FanControl.Releases/discussions/602

**Comment by mermelmadness** [comment]
Corsair Commander Pro plugin works well.

Could support be added for Corsair AIOs?  I have an H150i Pro XT that has a 3-to-1 PWM cable.

![image](https://user-images.githubusercontent.com/38080873/165184553-d9d2afb2-8951-4f10-9a48-1eb5cf5dc3b1.png)

**Comment by woomdawg** [comment]
The plugin kinda worked for me but it did not report RPM correctly.

**Comment by mermelmadness** [comment]
That's not the plugin, that's the Corsair hardware.  I get the same results in iCue, which would constantly misreport the RPM and even drop two fans from view sporadically.  Been that way since I updated the firmware last year.

**Comment by woomdawg** [comment]
It does it in the fan control app. iCUE has always worked flawlessly for me.

**Comment by mermelmadness** [comment]
I understand it does in the fan control app.  I'm saying that I get the same erratic RPM readouts in iCue, so I don't think it's a problem with the program.

**Comment by woomdawg** [comment]
I do not get those erratic readouts in iCue.

**Comment by Rem0o** [comment]
Do you run ICUE and FanControl side by side? They will conflict.

**Comment by woomdawg** [comment]
Yes. I need iCUE to run my RGB

**Comment by mermelmadness** [comment]
Only for a direct comparison.  I typically don't have iCue running at all.  I use OpenRGB to run my RGB.

**Comment by woomdawg** [comment]
I also need it for all KB macro's.  I ordered two fan splitters to run my fans on my mobo headers. I absolutely love the Fan Control software.

**Comment by DfrostX** [comment]
You cannot run both. Its that simple. Corsair iCue does not play well with anythig accessing its hardware simultaneously.

**Comment by Rem0o** [comment]
If you have further issues/discussions, please move this conversation to the plugin's repo. Thank you.
