### ISSUE TITLE
Bug Found when removing point and changing the graph min at the same time.

### ISSUE THREAD

**Issue by Wolphin5** [Rem0o/FanControl.Releases#662]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8550675/log.txt)

Editing the Fan curve, with a point on the minimum point.  Removing the minimum point and then adjusting the minimum of the graph before clicking OK, where the point removed was below the new minimum.  Causes the caught bug, but then the software goes really weird and had to end it using task manager (after it not exiting correctly).

Removing the point, clicking OK, then going back in and then setting the minimum and clicking OK doesn't have an issue.  I am thinking the order that it was trying to save the changes is at fault, as it may have been trying to change the graph before removing the point.

**Comment by Rem0o** [comment]
Trying to reproduce the issue... Your log tells me the bug was happening while you were moving a point, which you didn't really mention.

Can you try and give me a clear step by step ?

**Comment by Wolphin5** [comment]
I had a point on the minimum that I had moved by removing the point, so that I could increase the minimum.  Doing both at the same time caused it.  Tried to reproduce the issue, and it didn't have an issue on a new graph, and did both at the same time, so not too sure.

**Comment by Wolphin5** [comment]
Haven't been able to reproduce this issue after submitting it, so either was a glitch at that time, or another fix has already resolved it.
