### ISSUE TITLE
macOS Support planed? 

### ISSUE THREAD

**Issue by anonym323** [Rem0o/FanControl.Releases#664]
No issues here… would love to see this application under macOS. Anything in this direction planed ?

**Comment by asheenlevrai** [comment]
+1 (watched topic)

**Comment by Rem0o** [comment]
I got no MacOS experience.  Are there libraries available with proper fan control support?

**Comment by gvasco** [comment]
There's already a fairly similar app: macs fan control, maybe not as robust in terms of configurability but still quite robust, which is available for both MacOS and Windows bootcamp.

**Comment by asheenlevrai** [comment]
> There's already a fairly similar app: macs fan control, maybe not as robust in terms of configurability but still quite robust, which is available for both MacOS and Windows bootcamp.

I'm using it on a daily basis. It's a good app indeed.

**Comment by Rem0o** [comment]
Unless incredible demand, won't do.

**Comment by XVII** [comment]
Linux implementation (if it's of any use): https://github.com/linux-on-mac/mbpfan/tree/master/src

Macs Fan Control uses a custom driver `applesmc.sys`

**Comment by Rem0o** [comment]
@XVII see https://github.com/linux-on-mac/mbpfan/wiki/Tested-Mac-Models
Only works on intel era macs.

**Comment by XVII** [comment]
> @XVII see https://github.com/linux-on-mac/mbpfan/wiki/Tested-Mac-Models
> Only works on intel era macs.

@Rem0o , yeah bootcamp for Windows no longer works with Apple silicone so it's just the intel ones that can do this.
