### ISSUE TITLE
L-Connect 3 and new Controller Firmware is not recognized

### ISSUE THREAD

**Issue by Pascal51882** [Rem0o/FanControl.Releases#669]
After Upgrading to L-Connect 3 and the new Firmware the Controller is no longer recognized.
Can I provide any information to support it in future releases?

**Comment by Rem0o** [comment]
the Controller... what controller? Lian-Li controller stuff was never supported in the first place?

**Comment by Pascal51882** [comment]
The Controller/Hub of the Lian Li UNI FAN SL Fans. It worked great with the L-Connect 2 Software and the older Firmware on the Controller.

**Comment by Pascal51882** [comment]
Yes it was picked up without any problems. I hope I can downgrade its firmware somehow.

**Comment by EightB1ts** [comment]
Hi @Pascal51882 !

I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi
Looking for beta testers. If you have time, please let me know if it works for you!

**Comment by Pascal51882** [comment]
Hi @EightB1ts I tried it but I get an init error at the start up of fan control.
![2023-06-24 12_28_57-](https://github.com/Rem0o/FanControl.Releases/assets/41856419/e6f631cd-42c9-482a-b046-ea6be6e70a8e)
![2023-06-24 12_28_16-](https://github.com/Rem0o/FanControl.Releases/assets/41856419/a0b97855-000b-4e49-a03d-16d9eeda6e9b)

**Comment by EightB1ts** [comment]
Hi, please share a copy of the log file (located in the same folder as the FanControl) in a new issue on the LianLi plug-in repo so it can be tracked. Thanks!
