### ISSUE TITLE
Feature Request: Stair Step Curve

### ISSUE THREAD

**Issue by Nyanino** [Rem0o/FanControl.Releases#67]
Just downloaded this software and have been using it tonight, so please let me know if this is already a feature (I looked through the previous threads and didn't find what I was looking for).

Is it possible to use stairstep curves in the graph? Currently, the closest way to do it is to increase by one degree and then have a large slope to the next point.

Something like this
![image](https://user-images.githubusercontent.com/44222566/98501795-76eb8d80-220d-11eb-826b-2adf59f1bcc9.png)

Instead of what I've got here
![2020-11-08 21_56_03-](https://user-images.githubusercontent.com/44222566/98501780-6fc47f80-220d-11eb-9016-629371357488.png)

Additionally, I was wondering about instead of having a flat speed for the target curve, you could control the idle and load curves individually, or have the fan speed find the minimal value to operate at the desired temperature. Not sure how feasible this is, but just a thought!

Thank you for this great software!

**Comment by Korkman** [comment]
I wondered about this, too, but come to think of it, having two points for one temperature value is technically kind of weird. Stair steps look nice, but they don't add any value and complicate code and GUI?

**Comment by Rem0o** [comment]
@Korkman kind of my thought also, a step discrete function is not actually a valid "function", as you have to pick either if the value for a given step transition is floored or ceiled. In order to do the same "effect", 

@Nyanino 
I would do a linear function (straight line) with two-way hysteresis half the plateau size you want. For a 10 deg plateau, do 5 deg hysteresis.

**Comment by Korkman** [comment]
@Nyanino As for keeping a desired temperature, here's a fun hack using the "Target" curve: Say you'd like to keep CPU package at about 47°C, and keep a minimum fan speed of 40% even when idle:
![grafik](https://user-images.githubusercontent.com/3186931/98731655-543cae80-239e-11eb-8f4d-1452d397377e.png)
![grafik](https://user-images.githubusercontent.com/3186931/98731695-6585bb00-239e-11eb-947f-afd4902ed6c0.png)

The curve will bounce between 40% and 100%, but the low Step % / Sec will roughly average out on the fan speed required to keep the temperature.
