### ISSUE TITLE
SUGGESTION re: "Mix" curves

### ISSUE THREAD

**Issue by REALabPC** [Rem0o/FanControl.Releases#673]
As it stands, the options for curve mixtures are nearly comprehensive; there is, however, one option I feel could be added.
Currently, the "Max" option allows a "Mix" curve to take on the setting for whichever temperature is the highest within the selected curves. It would be _great_, however, to also have the option of outputting the highest _percentage_ within the given curves.

e.g.: Say the CPU curve is set to go to 70% at 60° and the GPU curve is set to go to 75% at 55°...
When "Max" is selected for a "Mix" curve, the affected fan(s) will go to 70% if the CPU hits 60° and the GPU is 55°. Under a (proposed) "Max Pct", the affected fan(s) would go 75% once the GPU hits 55° _even when the CPU temp is higher_.

**Comment by REALabPC** [comment]
Yeah, I just realized I said it backwards. It currently puts out whichever percentage is highest. It'd be great to put out the percentage corresponding to whichever _temp_ is highest as well.  8-)

**Comment by REALabPC** [comment]
P.S.: I'm closing this is as it isn't truly an "issue" (just a suggestion) and doesn't require immediate resolution.

**Comment by Rem0o** [comment]
But that wouldn't make sense. A 60 deg CPU is chill, but a 50 deg HDD or SSD is toasty AF.   
Simply adjust your curves until it makes sense for your components.
