### ISSUE TITLE
"Control "Fan Control #" pairs with"none"" - Control Hub

### ISSUE THREAD

**Issue by stoopkid93** [Rem0o/FanControl.Releases#678]
I get this indicated for all 5 of my case fans.
![Annotation 2022-04-25 200801](https://user-images.githubusercontent.com/47932366/165193974-318546e5-e8a7-4bd7-b8bb-e55c6544a393.png)
Detects my CPU fan and one of the 2 fans on my GPU (1070ti).
My case fans are tied into a Corsair Commander Pro controller hub - that's probably where I'm going wrong? I installed iCue and they are all reporting fine through that so I know they are reporting RPM fine.
Is there a workaround or known bug for controller hubs?

**Comment by Rem0o** [comment]
No built-in support for Commander pro.

see https://github.com/iJacks1980/FanControl.CommanderPRO
