### ISSUE TITLE
Using Application WITHOUT Admin rights

### ISSUE THREAD

**Issue by Attitum** [Rem0o/FanControl.Releases#68]
Im unable to use FanControl without Admin rights even with the trick below.

A trick to use apps without admin rights is as follows
Example : 
change Shortcut to this "C:\Windows\System32\runas.exe" /profile /user:Administrator /savecred "C:\Program Files (x86)\Battle.net\Battle.net Launcher.exe"

**Comment by Rem0o** [comment]
Well, admin right IS required,
