### ISSUE TITLE
Closing & fan curve editing issue

### ISSUE THREAD

**Issue by Mr-Blvck** [Rem0o/FanControl.Releases#685]
Ran the program and set it up with no issues however after the fact I've ran into 3 issues:
1. After opening the program, if I close it and try to open it again I get nothing - program window won't open.
2. I initially set up some custom fan curves and now when I go back to try and edit them the edit window doesn't open.
3. Can't control GPU fans, set curves, etc. (6600XT)

Thanks in advance for any help.

**Comment by xhul-dev** [comment]
Hello there.
You say the curve edit window doesn't open, so we can assume that you have access to the interface.
Maybe it's just me, but how can you have access to the interface if the program window doesn't open?
It's hard to understand how you can have both issues at the same time.
Could you please clarify?

**Comment by xhul-dev** [comment]
Thanks.
Let's try to solve the whole program not opening first.
It has to start with an important question, when you say "when i try to reopen the program", is it by running the executable again, or by using the system tray icon?

**Comment by xhul-dev** [comment]
Thanks, so that's what i suspected.
Basically, trying to run the executable again doesn't work because it's already open in the background, which is the normal behaviour.
After you closed the app window, if you want to open it again, you have to use the system tray icon instead, which should be located on the right side of your taskbar.
The icon is a white fan, simply double-click on it to open the interface again.
Let us know if that worked.

**Comment by Mr-Blvck** [comment]
Ok so opening it from the system tray icon worked!

I still can't edit any fan curves.

Also I don't know if this has been brought up before but my GPU fan was/is
not detected by the program either.

**Comment by xhul-dev** [comment]
About the GPU fan(s) detection:
If not already the case, i would recommend using the most recent GPU drivers.
Maybe an update of LibreHardwareMonitor can be done aswell, somebody else please confirm (and let us know the easiest way to do it).
Then, in "Sensor settings", try both options separately: "LibreHardwareMonitor" - "GPU", and then "NvApiWrapper" - "Enabled".

**Comment by Mr-Blvck** [comment]
I did you ask and the GPU fans still didn't show up. Tried running a game
and I had to manually go into the GPU software to manually kick the fan
curve on (all drivers are up to date).

The fan control program if anything has gotten more buggy. I keep getting
error log messages and now settings, fan curves, etc. aren't saving and I'm
back to a default GUI with no fan names, fan curves, etc.

Is there a way to uninstall the program and try to do a fresh install? I
feel like I'm going backwards lol

**Comment by xhul-dev** [comment]
> Is there a way to uninstall the program and try to do a fresh install? I feel like I'm going backwards lol

Fan control requires no installation, it's standalone.
Close Fan Control (right-click the tray icon, then select "Exit"), delete the whole FanControl folder (you'll lose all configuration), and simply re-download the current version.

**Comment by Mr-Blvck** [comment]
sounds good. I'll do that and hopefully that resets everything.

Thanks for being so responsive and helpful!

**Comment by Mr-Blvck** [comment]
I’m at work right now so I won’t be able to test till tomorrow morning but
I’ll email you asap.
