### ISSUE TITLE
Some issues after restarting Windows

### ISSUE THREAD

**Issue by Tminus89** [Rem0o/FanControl.Releases#689]
Hi there. I just booted up my pc for the first time today. All sliders (on the left of the selected curve) for my available fans were turned to the left. Had to switch them on manually, after which everything started behaving as it should again. Also I had my case fans (connected through a Corsair Commander Pro) lose connection once yesterday, I thought I had to check this out today but all fans have re appeared. For now It seems I just have to check everything once after booting my system. So it seems solved, but I wanted to report this anyway, if someone doesn't pay attention when booting and starts working/gaming :) Keep up the great work!
If there isn't a clear answer for this, please close the issue after reading. If I needed to report this another way please tell me because I just joined Github and am a complete Noob, just want to do what I can to get you guys further. And if I encounter this again, I will come back to you with logs and a screenshot.

Quick guestion, in my overview I have all my unused fan headers greyed out. Maybe someone has asked this elsewhere, but would it be possible to put an option in the main menu where you can choose to hide those flagged as hidden completely from view for a less cluttered interface?

p.s. I thought maybe I had to put the software outside of my C drive, I have it in Program Files now. But since everything works again, it doesn't seem that W10 is screwing with permissions or access to files. So I will leave it there.

**Comment by xhul-dev** [comment]
> Quick guestion, in my overview I have all my unused fan headers greyed out. Maybe someone has asked this elsewhere, but would it be possible to put an option in the main menu where you can choose to hide those flagged as hidden completely from view for a less cluttered interface?

Absolutely.
Uncheck "Show hidden cards" in the options.

**Comment by Tminus89** [comment]
Oops it's early, better get the coffee machine going. Sorry for that. FYI I just rebooted, the app started normally and functioned correctly right away. As I said, if it acts up again I will come back to you. Thanks for now, wasn't expecting a reaction that quickly!

**Comment by xhul-dev** [comment]
> Oops it's early, better get the coffee machine going. Sorry for that. FYI I just rebooted, the app started normally and functioned correctly right away. As I said, if it acts up again I will come back to you. Thanks for now, wasn't expecting a reaction that quickly!

Pleasure.
I suspect the configuration wasn't saved correctly the first time, which would explain why it's working now.
Don't forget to use the "Save configuration" thing each time you make significant changes (which includes toggling curves on & off).

**Comment by Tminus89** [comment]
Yes I could have forgotten somewhere along the lines. Will keep paying attention to this should I want to change something like the speed of ramping down later on
