### ISSUE TITLE
GIGABYTE Z390 AORUS ULTRA

### ISSUE THREAD

**Issue by CloudPuncher123** [Rem0o/FanControl.Releases#69]
Hello, thank you for this amazing software!

My issue is that while I can read the RPM of all fans in my system, it is unable to control them from half of the headers in my MOBO. I can use CPU and CPU OPT, as well as SYS FAN 1-3, but SYS FAN 4, SYS FAN 5 PUMP, and SYS FAN 6 PUMP dont have control. 

When I set the "Flat" fan curve to either 100% or 0% and physically check the fans, there is no result for these headers. Selecting "Automatically Match Fans" sets the control cards to all control my AIO tachometer (H115i RBG Platinum, tach plugged into CPUFAN header). You will see in the attached image that 4 of the cards have no titles, and those are all the ones that have been matched up to the AIO tachometer. When I have the Top 140mm plugged into SYSFAN3, no issue, but any of the above mentioned ones dont allow control.

Any help would be greatly appreciated!

![Capture](https://user-images.githubusercontent.com/74412752/99075637-320a8280-2590-11eb-94d6-3f77bb0d0a7b.PNG)

**Comment by Rem0o** [comment]
Any conflicting software that might run? Any BIOS config to control those fans?

**Comment by R1fast** [comment]
@Rem0o Exact same motherboard here (Z390 Aorus Master) and exact same symptoms.  

I can use CPU and CPU OPT, as well as SYS FAN 1-3, but SYS FAN 4, SYS FAN 5 (PUMP), and SYS FAN 6 (AIO PUMP) have no control.

Guessing these are using a different IC that may not be supported (?).  

Note that the software does match SYS FAN 4 but doesn't control.  Both pump headers are not detected even though these work like normal fan headers (e.g. can control a PWM fan via either PUMP header).

**Comment by NickNerd** [comment]
I am having the same issue on my Gigabyte B550 Aorus Pro.

**Comment by virusmoere** [comment]
The second control chip (IT8792E) is currently not fully supported by LibreHardwareMonitor --> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/251

**Comment by Shasoosh** [comment]
@Rem0o Is there any info we can give you in order to debug this?

**Comment by Rem0o** [comment]
ITE8792E driver implementation documentation is needed, which isn't public.

**Comment by Shasoosh** [comment]
Thanks @Rem0o 
Can you elaborate a bit about what info in the implementation is needed?
Will the ITE Register map suffice? 

Found a pdf here: https://github.com/richard378/it87-eol

**Comment by Rem0o** [comment]
@Shasoosh  ITE8792E isn't in there.

**Comment by Shasoosh** [comment]
Why are you referring to it as ITE8792E?
I believe it should be **ITE IT8792E** which is in the PDF in the link above.

**Comment by Rem0o** [comment]
Good find. 
From that, you could try and debug that class https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/IT87XX.cs to make sure the registers are proper. Add the ITE8792E in the chip enum and start from there. In the different switch cases, make sure it is configured to match the specs in the PDF ( if they are any good ).

It seems like some of these need to be maked has _hasExtReg, which then sets an other memory address, probably to set the FAN_CTL outp mod or FAN_CTL ON/OFF, from your PDF. The ITE IT8792E seems to behave this way.

**Comment by Shasoosh** [comment]
Thanks for the info. 

I've also found this commit which indicates that there is some kind of problem leaving the configuration mode of the chip. Not sure how much it's relevant but I'll add it here for future reference. 

https://github.com/richard378/it87-eol/commit/485178c1ecc1835066178eeda681a4d0a9cdd0ef

**Comment by MilRefDev** [comment]
@Rem0o Was this issue fixed? I have a Gigabyte Z690 Gaming X board and am unable to control the sys pump header.

**Comment by Shasoosh** [comment]
Hey @Rem0o , Is this issue supposed to be fixed? 
None of the linked issues indicate this and the latest Fan Control \ LibreHardwareMonitor still have the same issue.

**Comment by Rem0o** [comment]
@Shasoosh  AFAIK its not, but from this repo I can't do anything, so this issue is blank.

**Comment by Shasoosh** [comment]
I see. Thanks.
