### ISSUE TITLE
Thermaltake Riing controllers not detected/X570 Aorus Issue

### ISSUE THREAD

**Issue by bonkas** [Rem0o/FanControl.Releases#690]
Thermaltake Riing controllers not detected - Are there plans to support these in the future?

Only the chipset/mosfet fan is detected on my Gigabyte X570 Aorus Mainboard, no pumps or directly connected fans are detected.

**Comment by Gucioo** [comment]
Same issue for Gigabyte X570 Aorus Master. Seems to be missing Controls for second controller:
ITE IT8792E. 

If you need more data, ids or logs I can provide them.
![GigabyteX570aorusMaster](https://user-images.githubusercontent.com/7483436/166084982-c50eb9d6-a319-47e0-83c4-de4d2ac42527.jpg)

**Comment by Gucioo** [comment]
I have gone thru FanControl readme and this is a hardware support request.
I raised issue on the LibreHardwareMonitor project to get controls supported for IT8792E.
[https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/731](url)

**Comment by Rem0o** [comment]
Thanks, will close this.
