### ISSUE TITLE
Fan control not always working on Nvidia GTX 1660 super

### ISSUE THREAD

**Issue by Tminus89** [Rem0o/FanControl.Releases#694]
Just did a test with a game. Everything ramps up just fine, but when I go back to the menu it often ramps down to quickly. After shutting the game down, I saw the card was 60 degrees Celsius, but the gpu fans were already turning at a slow speed. Since the temp sensor does keep working, the other fans did follow my mix curve and were still at a higher speed. Also before starting I could not manually control the gpu fans in the software, so I was prepared to shut the game down right away. To my surprise it did react accordingly at that moment

**Comment by Rem0o** [comment]
Your issue is really not clear. How did you configure your GPU card? Show a screenshot of everything.

**Comment by Tminus89** [comment]
Excuse me but of course. Will come back with you when I'm back home

**Comment by Tminus89** [comment]
<img width="1357" alt="Overview" src="https://user-images.githubusercontent.com/104441269/165542341-8a41ccdd-45b9-481b-8b9d-aae32c64b442.png">
<img width="517" alt="GPU curve" src="https://user-images.githubusercontent.com/104441269/165542343-bc390f94-6cd0-4006-91f4-78668db5364c.png">

It's set to ramp up fast, but ramp down slowly and after 10 seconds. The RPM readouts are inaccurate. After just booting my system, I am able to manually control the GPU fan speed. Earlier today I could at first, but later on (after some browsing, no settings changed) I couldn't anymore. Hope that makes things more clear

**Comment by DfrostX** [comment]
Do you use MSI afterburner? If so, you might want to turn off the Fan control (in afterburner). Or else it might conflict.

You can still use afterburner, just not to control fans

**Comment by Tminus89** [comment]
Ok so I already had the user defined fan curve option off. So if there are no other options for me to toggle off Afterburner can't be the issue.

**Comment by Tminus89** [comment]
The only reason I run MSI Afterburner is for a small OC. I tried searching whether there is an option for automatic control in Afterburner, but from what I can find it runs the GPU factory settings on auto whenever it is running. So are you really sure there is no way Afterburner could interfere when I have the user defined curve off? If there is a possibility I would be willing to uninstall Afterburner to test this, but only if it makes any sense to do so. Otherwise I would have to run the auto OC again afterwards.

**Comment by Tminus89** [comment]
Everything works straight away when booting. I didn't have to pair again, could take manual control straight away. Ran the update afterwards so that had nothing to do with it. Doesn't matter, it works now. Will close this issue
