### ISSUE TITLE
Same Fans, Same Curve, Different Speeds

### ISSUE THREAD

**Issue by ERLoft** [Rem0o/FanControl.Releases#697]
3 of the 8 cooling devices in my system are identical.  Light Wings 120mm high pressure variants.  Purchased in a 3 pack.  These are the pull fans for my radiator.  Each connected to a different mobo header.  Left fan is connected to System 5, center fan is connected to System 2, right fan is connected to System 6.

The center fan is in sync with my CPU/GPU mix curve - whatever % is showing there, the center fan runs at.  The left and right fans, however, run at different speeds - as I'm typing this now, center is 29%, left is 40% and right is 42%.  

I've tried detect fan speed stop and start on all, but the out of sync issue persists.  I know I could solve this by running all three to a hub and connecting that to a single MOBO header, but is there another solution to the issue?

As well, the exhaust fan (Light Wings 120mm high flow variant) runs at a much higher % as well - currently 60% despite using the same curve.  It's connected to the System 4 header.

If it's relevant, only a couple of my fans auto detected and mated speed to control by themselves.  The rest were manually set up.

Fan Control Report:

[LibreReport.txt](https://github.com/Rem0o/FanControl.Releases/files/8578659/LibreReport.txt)

**Comment by xhul-dev** [comment]
Hello there.
Are you sure the control (left-right toggle) is correctly enabled on the fans that don't follow their curve?
If yes, are you sure that those aren't set to manual control (check box)?
If yes, do you use another software that controls those fans?
If no, is it something permanent, or do they sometimes follow their curve correctly?

**Comment by ERLoft** [comment]
Hello!

Fans are curve enabled, no manual control.  Other software was removed.
These fans never follow the set curve.
![Screenshot 2022-04-27 212659](https://user-images.githubusercontent.com/104538587/165676664-06bf4437-3ffa-44c0-a00e-59934c176458.png)

See attached for setup.

**Comment by xhul-dev** [comment]
Thanks for the screenshot, might help to investigate.
Another thing worth checking, is if the concerned fans have an "Offset" setting different than 0%.

**Comment by Rem0o** [comment]
My guess is you have a fan curve set somewhere else, like in your BIOS, or other 3rd party, which takes over.

**Comment by ERLoft** [comment]
At work now, so checking BIOS will have to wait until I get home, but I uninstalled the other fan control utilities - I had been using SIV (Gigabyte App) and just prior to learning of Fan Curve had downloaded / installed Argus Monitor, but hadn't set it up.  The only other vaguely similar software is AIDA64 Extreme, but that's just monitoring, not control, so I don't think that's it.  

It's possible that something is persisting in BIOS - I'll check tonight.

I didn't set up any offsets, but I'll look into that as well.

**Comment by quangkieu** [comment]
I would try to set all those to manual and try to run at same low speed and a high speed like 40% and 90% to see if there is other stuff try to override FanControl as that program might behave differently in high, low fan speeds. Then I would also check the start, stop speed per fan as they might be different

**Comment by ERLoft** [comment]
After a lot of trial and error, it looks like this Aorus Ultra Z390 just won't release certain connections for manual control.  Despite everything being set to manual control in bios (Can't turn off Smart Fan 5 completely, bleh), Sys4, Sys5 and Sys6 headers wouldn't respond to manual control at all.  Just kept doing their thing.  CPU, CPU OPT, Sys2, and Sys3 all work fine with Fan Control.  Didn't test Sys1, as the header is in a bad spot for cable routing, but was able to get all fans and the pump working with their intended curves via the use of 2 PWM hubs.  Not 100% ideal, but way better than the stock setup or anything I was able to get set up using the Gigabyte Smart Fan app.  

Thanks much for the help and follow up!
