### ISSUE TITLE
Secure !safe! mode

### ISSUE THREAD

**Issue by Eldenroot** [Rem0o/FanControl.Releases#7]
Is possible to add a new feature where you can set the max temperature when all settings (speeds, hysterezis etc.) will be skipped and the fans will run at full speed to get back to the normal temperature?

**Comment by AdrenalinaGit** [comment]
Why don't the existing features suffice?  If you set each fan's associated curve so the speed will be 100% at the temperature(s) when you want 100%, how does FanControl's behavior differ from what you want?

**Comment by Rem0o** [comment]
As @AdrenalinaGit said, simply set your fan curves so that at the critical temperature it jumps to the desired fan speed.
