### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Qfrijters** [Rem0o/FanControl.Releases#701]
I have the same issue with the latest version (v111) as in issue #302. The GUI suddenly goes really slow, takes a considerately long time to handle the mouseclick (when I click any button). Instead of instantly, it takes about 3-5 seconds. 
The screen goes entirely black, like a graphics driver crash, which actually seems to happen, as that's what even viewer says.

"Display driver nvlddmkm stopped responding and has recovered."
Systemspecs:
CPU: AMD Ryzen 9 5900X
Mobo: Gigabyte X570 Aorus Pro (non wifi)
RAM: G.Skill Trident Z Neo F4-3600C16D-32GTZNC (2x16GB)
GPU: MSI Geforce GTX 1650 D6 VENTUS XS OC  (saving for an AMD 6000 series or Nvidia 3000 series)
OS: Win10 Pro
(was not sure if I should have included systemspecs, some dev's like it, some don't)

Log file didn't have anything of today.

**Comment by Qfrijters** [comment]
Ok so, apparantly I did not have the latest GPU driver. So I've installed that (clean install). The program is back responsive and I did not have any black screens so far (let's hope it stays like that.)

**Comment by Rem0o** [comment]
Closing.
