### ISSUE TITLE
Cooler Master MasterFan MF120 Halo Do Not Stop

### ISSUE THREAD

**Issue by Y4m4k** [Rem0o/FanControl.Releases#704]
Hi - I am unable to stop my Cooler Master MasterFan in Fan Control. When I was using AI Suite3, I could stop them. Any idea what I need to do so that they are able to stop? I tried doing a detect stop automatically, but it says fan never stopped. Rad Fans/Back Exhaust (both are Cooler Master MasterFan, back exhaust is a MF140) have the same issue. I am able to stop my front fans (they are Noctua NF-A14 iPPC-2000 IP67 PWM).

I appreciate any guidance!

![image](https://user-images.githubusercontent.com/86619370/165786765-e949dbba-ffb9-4277-8594-de34d2f64596.png)

**Comment by Y4m4k** [comment]
@Rem0o any ideas?

**Comment by Rem0o** [comment]
Some headers are tricky and won't allow to be stopped like all other headers. Such trickery is probably board specific and handled in Asus software, can't do much.

**Comment by Y4m4k** [comment]
Okay, thanks for the input.

**Comment by quangkieu** [comment]
@Rem0o So I got this problem too but I do not think there is a way to fix it. So this is problem with PWM fan (4 pin) and Asus board. In bios you could choose DC or PWM mode (default PWM if it see 4 pin). In this mode, it cap the lowest fan speed to keep it running so around 500-600 depending on fan. Only if you change to DC mode in bios to have full control stop the fan. Even Asus software have silent mode/auto off feature, my guess is that it switch the fan over to DC mode to turn off.

**Comment by Y4m4k** [comment]
@Rem0o I had to figure out what was the issue :-D... turns out that for the Asus Crosshair VIII Dark Hero, you have to go into the QControl fan setup in BIOS (not in advance mode) and change the fans to DC mode and enable fan stop. Now they are stopping :-)

Hopefully it will help someone in the future.

![image](https://user-images.githubusercontent.com/86619370/166324892-f29534eb-de5b-4b0d-b2d2-ff515a7f94cd.png)
