### ISSUE TITLE
NVidia GPU Fans don't start until 43% on curve

### ISSUE THREAD

**Issue by JimmyJFly** [Rem0o/FanControl.Releases#706]
Noticing that the fans on my 3080Ti will stay at 0% until the fan curve hits 43%.  Anything lower on any type of fan curve and the fans go directly to 0%.  Is there a setting somewhere that I need to change?  Or is this the expected result?  Thank you

![image](https://user-images.githubusercontent.com/104599572/165854779-ffeae6f6-6b7a-4eaa-88d7-4fbee39c324e.png)

![image](https://user-images.githubusercontent.com/104599572/165854947-0266aeb8-724d-4bef-8e6b-40cd5b0264fa.png)

**Comment by Rem0o** [comment]
expand your control cards, your Start % must be 43.

**Comment by JimmyJFly** [comment]
Thank you.  If I want to use a graph curve that the curve has a full range of 0% to 100%, what should the start and stop % be when I expand the control cards?

**Comment by JimmyJFly** [comment]
I guess I don't understand, based on this screenshot, shouldn't the GPU fans be running at 39.9%?

![image](https://user-images.githubusercontent.com/104599572/165858916-898280f4-d339-45eb-863f-d5ea71ce784d.png)

**Comment by JimmyJFly** [comment]
Not sure if this helps but the app crashed and generated a log file
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8587160/log.txt)
.

**Comment by Rem0o** [comment]
Do you have a custom curve in MSI afterburner or "auto" mode enabled in there?

**Comment by JimmyJFly** [comment]
Don't have Afterburner installed.  After more testing I don't think it's an issue with your software, I think it's a fan limitation. What I think is going on is that the fans on this Strix 3080Ti have a minimum RPM that they can run at.  When I run the "Detect fan start% auto...", that even comes back at a min start % of 44% which for these fans is only like 500 RPM.  Based on that, anytime the curve was going lower then about 40% (even with the start% set to like 30%) the fans wouldn't run and wouldn't come back on again until the curve hit 40-45%.  Let me know if I'm off base with this.  This software is really amazing, thank you for putting it together.  I dropped you a dono as well :)

**Comment by JimmyJFly** [comment]
One thing I just noticed as well is that the speed % doesn't seem to be relative for these GPU fans either.  44% says 500 RPM while 100% is 3000 RPM.   Based on that, 500 RPM is more like 16%.  If the % showed correctly, the Mix curves might work better.    Is there something I can do in the settings to have the speed% be more accurate?  Thank you

![image](https://user-images.githubusercontent.com/104599572/165872293-896edec0-8d14-44b1-922d-2804b9b29075.png)
![image](https://user-images.githubusercontent.com/104599572/165872330-020bafb1-3cb1-44d3-a8f4-885149bcf7c7.png)

**Comment by xhul-dev** [comment]
Hello there.

About the minimum value of 43%, that's expected, all fans have a minimum % to trigger the rotation, that value is just usually higher for GPU fans.
Though i don't know how Fan Control actually uses those values, you should put 43 in "Start %", and 42 in "Stop %", as [Rem0o](https://github.com/Rem0o) suggested.

About the 44%>500RPM & 100%>3000RPM thing, that's surprising indeed, though i'm not sure if the %>RPM function is actually linear on any fan, and i wouldn't be surprised if the linearity decreases with high RPM fans such as on GPUs.

**Comment by TheWolfie96** [comment]
Based on my own observations, the start and stop % should be left for the program to determine, with any customization of actual fan behaviour being done in fan curves etc, **not** those percentages as hey are static hard-set values for each fan. I think that could be clarified a little better as I was messing around with those initially myself :P

As for the weird fan rpm behaviour, it's because the % shown is simply referencing your fan curve %, not your true fan rpm %. The actual rpm range of your fan will be the minimum fan curve % it starts at, all the way up to 100. So the rpm will in fact scale linearly, just from whatever the minimum is (so ~72% fan curve for you should be 50% rpm). Having a true 0-100 fan rpm percentage would be nice tbh.

**Comment by JimmyJFly** [comment]
Ahh OK, that makes sense.  Thank you for that info!

**Comment by Rem0o** [comment]
% is, let say for a DC fan, percentage of power applied, so % of 5 V.

Fan might only start at 2.5V, so 50%, and will increase in RPM until 100%, 5V.
