### ISSUE TITLE
Trojan.Malware.300983.susgen?

### ISSUE THREAD

**Issue by You4eea** [Rem0o/FanControl.Releases#707]
When I drop the fancontrol.exe file into pestudio 8.32.. 

Please advise.. is this malware or a false positive?

![FanControl-Question-v1](https://user-images.githubusercontent.com/12564224/165857220-bdf466ca-c872-42b2-b503-3fdd1194685a.png)

**Comment by DreiPixel** [comment]
1/67... yes its a false positive.

**Comment by Firecul** [comment]
> 1/67... yes its a false positive.

I've got to agree. It's unlikely with only 1 vendor getting a match that there is anything malicious. Not impossible, but very unlikely.
