### ISSUE TITLE
Cannot view GUI - Windows 10

### ISSUE THREAD

**Issue by R1fast** [Rem0o/FanControl.Releases#71]
**RESOLVED**:  See post 8 for workaround if you are on Windows 10 and experiencing this issue.

1. Downloaded latest release and unpacked 
2. Moved folder first to Program files, then tried Program Files (x86) then tried another drive entirely
3. Launching fancontrol.exe starts program, showing a fan icon in taskbar and notification area but cannot open the GUI
4. Right clicking the notification area icon shows the menu with Open, Configuration, Exit.  Open and Configuration do nothing.  Exit works.
5. Hovering over the taskbar icon pops up the mini window dialog "Fan Control v56 (userconfig.json" but its blank
6. Cannot find any way to get this program to work!

![fanctrl](https://user-images.githubusercontent.com/28174023/99156055-be8d7180-2672-11eb-851d-213104927de0.png)
![fanctrl2](https://user-images.githubusercontent.com/28174023/99156098-3f4c6d80-2673-11eb-86d7-57775d1b1b59.png)

**Comment by Rem0o** [comment]
Do you havbe .NEt Framework 4.8 installed? Do you launch as admin?

**Comment by R1fast** [comment]
Hi Rem0o. Yes - running .Net runtime 4.8.07352 I did try both as admin and non.

**Comment by Rem0o** [comment]
Do you have a log.txt file in your app folder? If so, post it here.

**Comment by R1fast** [comment]
Unfortunately no, I don't see a log file in the app folder.

![appfolder](https://user-images.githubusercontent.com/28174023/99156411-76238300-2675-11eb-896f-7b135261e842.PNG)

**Comment by R1fast** [comment]
FWIW - I did try the current ver of LibreHWM and it does work

![LHW2](https://user-images.githubusercontent.com/28174023/99156645-61e08580-2677-11eb-8cf4-a625f5a1509f.png)

**Comment by Rem0o** [comment]
The UI for Libre is not using the same framework, so that doesn't help much.

**Comment by R1fast** [comment]
@Rem0o - I found a solution for this which seems to be related to display scaling in Windows 10.  Note I'm on a 4k native monitor at 300% scaling, this may have something to do with the issue though I was able to repro still at 100, 150, 200% scaling as well.  

The fix:  

1- Right click on fancontrol.exe in your install directory and select Properties
2- Select the Compatibility tab and check the box below 'Program DPI'
3- Also check the box below 'High DPI Scaling Override' and choose System Enhanced.
4- Click ok and start the program... it should now work.  If not - you can also check the 'Run as Administrator' and 'Disable Fullscreen Optimizations' boxes (though may not be needed).

![image](https://user-images.githubusercontent.com/28174023/99753332-e6c60780-2a9a-11eb-9cf8-a990c3501068.png)
