### ISSUE TITLE
Cannot exit program

### ISSUE THREAD

**Issue by martinlanza** [Rem0o/FanControl.Releases#713]
"Exit" from task tray brings the app to the forground - exit from main window does nothing

**Comment by Y4m4k** [comment]
Maybe end task from task manager?

**Comment by martinlanza** [comment]
1) Should not have to
2) Does not show up in task manager

**Comment by Y4m4k** [comment]
Odd, mine does. Both in the Processes tab and Users tab.

![image](https://user-images.githubusercontent.com/86619370/166086877-a85566ec-ae4e-4cd9-98f8-d6c5718428f4.png)

**Comment by martinlanza** [comment]
It may have been minimized when I was looking in task manager

Never the less, when a user clicks the "Exit" nmenu option the expected action is for the program to exit - not much to expect

**Comment by Y4m4k** [comment]
Agreed 100%, just thought if it was still running and you wanted to exit it, you could end task it as a temporary alternative.

**Comment by Rem0o** [comment]
The exit from tray will check if part of your config changed and if you forgot the save it, if the window pops up, it should show this:
![image](https://user-images.githubusercontent.com/14118956/167179251-984325e2-e0c0-4710-b8ca-5d39d93cc642.png)

Otherwise, it will exit.

**Comment by Rem0o** [comment]
if you still have issues with closing the app in V115, please open a new issue.
