### ISSUE TITLE
Settings RESET after updating to Fan Control V112?

### ISSUE THREAD

**Issue by Rechain** [Rem0o/FanControl.Releases#715]
I updated Fan Control yesterday, but today all my settings was gone. It started over with the welcome, have to go through it all again? Version 112 at the moment. What happened??

**Comment by Rem0o** [comment]
Make sure it launches from the same folder? The setting are in a json file.

**Comment by Rechain** [comment]
Since it starts with windows, I have not done anything than updating via the program updater yesteday. When I logged into Windows today, it just started over.

**Comment by kladnik** [comment]
Same thing happened to me. 
It didn't reset instantly though, but after next restart

**Comment by Rechain** [comment]
It was the same for me, updated one day and the day after (after a shut down) it was reset when opening with Windows. The json configuration file save was back to start. Had to redo my settings. Now using custom ones too, as backups. Just in case.

**Comment by Rem0o** [comment]
Do a search for userconfig.json on your drive. Is there more than 1 result?

**Comment by kladnik** [comment]
Just did a complete search. The only file I found was the one in the same folder

**Comment by Rem0o** [comment]
@Rechain 

If it started over with a welcome, it means the "context folder" the program runs on changed. It couldn't find its CACHE file. I don't know where you put the program, or how you start it, but if you put it on your C:\ drive and start it using the scheduled task or by manually opening it, you shouldn't have any issue going forwards.

**Comment by Rechain** [comment]
It's on my C drive (Windows drive) and I choosed Start with Windows and minimized in the program after setting everything up. Then updating to 112 via the auto updater when it said it was ready 2 days ago, worked fine. But next day settings was reset when I turned on the PC and Windows started. Have not moved where the program is installed, it's in the same spot.

**Comment by Rem0o** [comment]
Any more update? Hard to get anything out if this.

**Comment by Rechain** [comment]
There isn't more to it than that. Have not experienced issues other than the update to 112 did what I mentioned 🤔
