### ISSUE TITLE
Error when trying to use the built in updater

### ISSUE THREAD

**Issue by nefariouslegion** [Rem0o/FanControl.Releases#717]
Hello,
I opened FanControl today and asked me if I wanted to update it.  I clicked on "Update" and then FanControl closed and this window popped up with what appears to be an access denied error. It won't update due to this error. How can I fix it? I am on an Admin account and FanControl is set to run as administrator. FYI I'm on Windows 11.
![image](https://user-images.githubusercontent.com/89366675/166112879-84447e09-534a-486d-9367-3f2efa6a788a.png)

**Comment by vaibhav2912** [comment]
I had the same issue. I manually ran the updater.exe and that worked.

**Comment by nefariouslegion** [comment]
> 

Ah yep that works. Thank you.

**Comment by Rem0o** [comment]
Access denied means it wasn't running as admin somehow.

**Comment by nefariouslegion** [comment]
> Access denied means it wasn't running as admin somehow.

FanControl does run as admin though. Everytime I manually launch it it pops up with the UAC prompt

**Comment by Rem0o** [comment]
Have you tried manually executing the updater.exe ?

**Comment by nefariouslegion** [comment]
Yeah I did as per @vaibhav2912 suggestion earlier in these replies and that worked. Idk why the in-app updater didn't work though lol

**Comment by Rem0o** [comment]
@nefariouslegion 
That's odd, the "built-in" one is actually just FanControl calling updater.exe.  It's like your FanControl instance didn't have the right user privileges to run it or something.

**Comment by nefariouslegion** [comment]
@Rem0o Yeah idk why though. I use an admin account lol

**Comment by Rem0o** [comment]
Maybe take a look at the scheduled task that starts FanControl, and see if something is wrong as far as user/admin etc..

**Comment by nefariouslegion** [comment]
Here's what task scheduler shows. I'm not exactly sure which setting I should be focused on. But it does say it's set to execute with highest priveledges 
![image](https://user-images.githubusercontent.com/89366675/167190919-43dd78cd-dda7-44cd-a8b4-698c8a4994df.png)
![image](https://user-images.githubusercontent.com/89366675/167190960-88030522-631e-4eb9-b35f-c5f698c6a52f.png)
![image](https://user-images.githubusercontent.com/89366675/167191002-c33d939a-4b42-4cbe-b598-13438cd766f6.png)
![image](https://user-images.githubusercontent.com/89366675/167191039-ab10af8f-9a38-44ab-9b99-f74ef0fd7625.png)
![image](https://user-images.githubusercontent.com/89366675/167191097-81304a08-9667-4ebe-9c29-b7d903469e03.png)

**Comment by Rem0o** [comment]
I assume the "andre" account is admin, I don't know really what would be missing, as this setup works for 99% of users.

**Comment by nefariouslegion** [comment]
Yeah that's my account. For some reason using a microsoft accounts causes Windows to shorten Andrew to andre lol. Idk either honestly. Maybe it'll fix itself when it tries to update next time lol

**Comment by nefariouslegion** [comment]
Still getting this issue trying to update from 112 to 114. I had to close FanControl and manually re-open it as admin in order for it to install the update. But idk why since you can see in those previous screenshots that it's set to run with the highest priveledges.
