### ISSUE TITLE
Disable GPU Control

### ISSUE THREAD

**Issue by Gweg83** [Rem0o/FanControl.Releases#72]
Hello
Sorry for my bad english
I manage gpu fan curve with msi afterburner
I manage all case fan with FanControl

FanControl take the top of afterburner at windows startup
If i manually open curve editor of aftreburner, afterburner take the top
I would like to deactivate the gpu part of FanControl
Possible ???

Thank you

**Comment by Gweg83** [comment]
I delayed start of afterburner for temporary solve the problem

**Comment by Rem0o** [comment]
If the toggle for the GPU card is not enabled in FanControl, it shouldn't take over.

**Comment by Gweg83** [comment]
It shouldn't take over, but the bios curve in graphic card take the top, and not the afterburner curve.
I have disabled fan curve in afterburner and activate fan curve in FanContol.

Its good

Thank you for this very good soft
