### ISSUE TITLE
how to reinstal or downgrade?

### ISSUE THREAD

**Issue by loemoembo** [Rem0o/FanControl.Releases#722]
So the noob question of the day. 
sins the last 3 version i have 1 fan spinning at max speed without any way to control it. Another just says 0 rpm. I would like to deinstal/reinstal or downgrade to an older version to try and fix it. Bit i dont find how i can do this. 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/104710371/166135132-199af120-cfe4-4eb8-b0aa-63218870dfbf.png">

Thanks for the help.

**Comment by xhul-dev** [comment]
Hello there.

At first sight, it sounds like an incorrect fan pairing in the software
Did you try the "Pair controls and speeds automatically..." thing?

If you want to downgrade, it's quite simple, since Fan Control doesn't require any installation.
Simply delete the folder where it's located.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases

**Comment by loemoembo** [comment]
thanks for the help. wanst sure if just deleting the folder would be doing the trick or not.
i have a aio cooler installed on te gpu. so the fans are "normal" fan on a mobo 4 pin connector.
