### ISSUE TITLE
Plugin would not load

### ISSUE THREAD

**Issue by jcnwholland** [Rem0o/FanControl.Releases#724]
Hi, i'm trying to run the hwinfo plugin, followed the instructions, but its remains on no plugins?

Furthermore, why on earth do you zip the build on github? This is a but suspicious..

**Comment by DfrostX** [comment]
Did you do this: unblock the dll (see [here](https://2.bp.blogspot.com/-PZjsMvjdLf8/VzpHwD95KAI/AAAAAAAABwA/XZ3v-bbCc7or7I2ObLiRVK2kyyFZFJkKQCLcB/s640/security.png)

**Comment by Rem0o** [comment]
^  what he says 

Why did I zip the build on github? Because it's simple and it works.

**Comment by jcnwholland** [comment]
ok, but you cannot view the content in the zip on github right? and its the oldest trick in the book to mask certain types of code. Just saying..
