### ISSUE TITLE
Missing sensors error, fancontrol finds no fans

### ISSUE THREAD

**Issue by broconut123** [Rem0o/FanControl.Releases#725]
In he last few days I've gotten missing sensors errors. I've been using the program for a few months now. Fan control does not seem to be able to discover any fans connected to the 4pins on the motherboard. I've tried completely reinstalling, but it still wont work. Anyone knows any fix?

**Comment by Rem0o** [comment]
Try and earlier build: https://github.com/Rem0o/FanControl.Releases/releases
