### ISSUE TITLE
If i enable a curve the corresponding fan stop working

### ISSUE THREAD

**Issue by MrLokiku** [Rem0o/FanControl.Releases#726]
CPU and Chassis3 doesn't work, if i enable some curve the cpu or chassis3 fans stop to work and go to zero, i'm using fan control for cpu and chassis3 from some months and it worked until some days ago. Chassis2 still working correctly.

**Comment by Rem0o** [comment]
Screenshot of the problem?

**Comment by MrLokiku** [comment]
![Fanbefore](https://user-images.githubusercontent.com/104724487/166152587-28baf2b1-dcd4-4adc-aeaa-854a5f11ee92.jpg)
![Fanafter](https://user-images.githubusercontent.com/104724487/166152589-99280761-b58a-41f8-9aa6-6c93a4620862.jpg)

**Comment by Nightinggale** [comment]
I noticed precisely the same problem in issue #720. Regardless of what I do, if I set fan 2 to anything, the fan will stop.

Interestingly I use an ASUS motherboard too, which makes me wonder if ASUS updated something, though strictly speaking there might be a Microsoft update too for all I know. Mine is a prime X570-PRO. While FanControl updated from v111 to v112 it doesn't mean that ASUS didn't silently update something at the same time. This would explain why downgrading FanControl won't fix the problem. It's also worth repeating that my GPU seems unaffected and the issue only affects fans controlled by my motherboard.

**Comment by Rem0o** [comment]
Some users reported that updating their stuff via armory crate fixed the issue, @MrLokiku .

**Comment by chrisjudk** [comment]
Just wanted to add this in case anyone else runs into this issue. I was able to get it working via an update in armory crate as @Rem0o mentioned above. Specifically, I found the issue continued to persist until I updated AI Suite to the latest version.
