### ISSUE TITLE
Curve i set sets fan to instant 100%, ignores curve

### ISSUE THREAD

**Issue by DuckersMcQuack** [Rem0o/FanControl.Releases#728]
I set curve to 80%, yet fans spins at 100%, i change curve to 40%, still 100. 

![FanControl_Esh4DYZdV4](https://user-images.githubusercontent.com/9039370/166245990-9a82497d-665b-4d2f-8637-f21150c46181.png)

**Comment by Rem0o** [comment]
Your curve is not set to anything in your screenshot.

Otherwise, check your bios fans config.

**Comment by DfrostX** [comment]
Exactly, you need to associate the fan curve with a sensor in the "temperature source" drop down menu
![Sans titre](https://user-images.githubusercontent.com/70845235/166316734-5ee6a4f8-4684-412a-83e3-fd724bd379b0.png)

**Comment by Rem0o** [comment]
No answer, assuming @DuckersMcQuack figured it out. Closing.
