### ISSUE TITLE
the AIO pump header is missing 

### ISSUE THREAD

**Issue by REACHER217** [Rem0o/FanControl.Releases#729]
the AIO pump header is missing from the program . it dont show the rpm of the pump nor it can control it 
the motherboard is the strix b450-f gaming

**Comment by Rem0o** [comment]
See Readme please.

**Comment by REACHER217** [comment]
> See Readme please.

i did , cant find how thats supposed to help

**Comment by DfrostX** [comment]
That part:

> Issues and hardware compatibility
> I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on:
> 
> https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
> https://github.com/falahati/NvAPIWrapper
> Please only open issues for the software itself, UI, feature request and so on.
