### ISSUE TITLE
Add temperature delta curve option.

### ISSUE THREAD

**Issue by dutenhnj** [Rem0o/FanControl.Releases#73]
A unique and useful feature for some people would be a fan curve that adjusts the speeds based off of the difference between two temperature sources.  For instance in my system I have an ambient air temperature sensor and a coolant temperature sensor in my water loop.  If I could control my fan speeds so only when the coolant temperature is 10C higher than the ambient temperature do the fans start ramping up it would be very nice.  Currently I have to base everything off the coolant temperature alone which is often too aggressive to ramp up in higher ambient temperatures during summer but works perfectly in winter.

**Comment by Rem0o** [comment]
Already mentionned in #44
