### ISSUE TITLE
Nvidia 1660: a paired RPM sensor is required

### ISSUE THREAD

**Issue by tormento** [Rem0o/FanControl.Releases#731]
Whenever I start "detect fan start" or "detect fan stop", I get the error:

![image](https://user-images.githubusercontent.com/2351785/166503175-342a9cd8-c066-42d2-8f75-a4dc652b22f3.png)

Anyway the RPM are there:

![image](https://user-images.githubusercontent.com/2351785/166503228-4ba465b8-284d-4a9d-82d8-2e838952bf6d.png)

What is the meaning of that message? Is that intended or an issue?

My card is a EVGA GeForce GTX 1660 Super SC Ultra.

**Comment by Rem0o** [comment]
It means the program couldn’t pair the control with the speed sensor since rpm are not changing when trying to change the control %. Most likely you have an other fan control software which plays with the hpu.

**Comment by tormento** [comment]
@Rem0o thanks for you answer.

I have no other software but FanControl to set the fan speed. I don't even use Afterburner or other branded overclocking programs.

The thing that I have noticed is that manually changing the % of fan speed, functions only on limited span of values, i.e.:

%	RPM
100	2130
90	2130
80	2130
70	2130
60	2100
55	1925
50	1750
45	1575
40	1400
35	1225
30	1050
25	875
21	700
19	640
0	640

**Comment by Rem0o** [comment]
There you got your answer, its range is limited. You can still set curves at or above 19 then.

manually pair the rpm sensor to its control and you are all set.

**Comment by tormento** [comment]
@Rem0o what about to automatize the process I did manually?

Finding the correct range took me about half an hour. 

You could add "detect fan range" beside "start" and "stop" process and show the limits in the fan curve editor.

Another idea I had that you could implement was to scan every fan to find the rpm for every %, as some are not completely linear, and show it as a graph too.

**Comment by Rem0o** [comment]
> You could add "detect fan range" beside "start" and "stop" process and show the limits in the fan curve editor.

Thought about a similar idea, but the UX of it is still not set in stone.

**Comment by tormento** [comment]
And what about the RPM scan?

**Comment by Rem0o** [comment]
> And what about the RPM scan? It could be nice to select wanted RPM instead of % of fan speed, as usually % is based on duty cicle but RPM is much more realistic.

It would introduce a lot of complexity in the software, for a minimum gain really, as figuring out %/rpm is pretty straightforward if you really want to, but really, you shouldn't target a "RPM" value itself, as it is pretty meaningless. It does not tell you how silent it is, or how much it cools your component. 1000 rpm for a 92 mm fan isn't the same cooling capacity as 1000 rpm for a 140mm fan and so on.  It would restrict a specific curve to a specific fan, which kinda goes agains't the main idea behind the software.
