### ISSUE TITLE
Question: Should I disable fan control in BIOS when using this software?

### ISSUE THREAD

**Issue by freddiehaddad** [Rem0o/FanControl.Releases#732]
I'm not sure if the BIOS fan control settings conflict with this software or does the software override the BIOS fan control settings?  Prior to finding out about this tool, I manually configured the fan temp/speed thresholds in the BIOS.

I have an MSI Z-690 Carbon WiFi

**Comment by Rem0o** [comment]
There is no overriding the BIOS. Both use the same "levers" to try and control the fans and WILL conflict.

**Comment by freddiehaddad** [comment]
Thanks for the quick response and awesome program.  FYI, JayzTwoCents on YT (https://www.youtube.com/c/Jayztwocents) gave you the shoutout.  Incoming $$$ support!

**Comment by crawfishie** [comment]
> There is no overriding the BIOS. Both use the same "levers" to try and control the fans and WILL conflict. Disable any smart control from the BIOS, set a nice default manual speed in there, like 50%, as a fallback just in case.

My Asus B550 BIOS offers "Full speed", some multi-point presets, and then a multi-point manual mode. The only one that would seem to have a chance of eliminating conflicts is Full Speed, and I clearly don't want that. The good news is, I've never observed a conflict, neither with your software nor Asus's Fan Xpert, which I used for 10 years prior. It sure acts like it's "overriding" the BIOS, but if it doesn't, how does the software always win?

**Comment by Simpy** [comment]
Same here, your program seems to be overriding my Asus x570-f bios cause soon as I got things setup using your program the fans just obeyed your program without me editing anything in the bios.

**Comment by xhul-dev** [comment]
There might be some differences from one fan controller to another.
In my case, there doesn't seem to be any conflict, but interestingly enough, if i disable the control of my fans in FC, they are always given a fixed 40% activity value, which doesn't follow my BIOS curves at all.
That would imply that in some cases, once FC gets control over a fan, the BIOS curve code gets somehow "lost", and only a machine restart can get it running again.

**Comment by crawfishie** [comment]
I guess it is YMMV. I just tried exiting FC, and my Asus B550 BIOS curves came back into force. After restarting FC, it resumed control. I can tell by the lower baseline speeds and the slower ramp down I've configured in FC.

**Comment by Rem0o** [comment]
Closing.
