### ISSUE TITLE
AMD 5600XT Fan unable to pair/control

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [Rem0o/FanControl.Releases#735]
GPU sensor detected and reports correct temp, unable to control the fan speed.
![image](https://user-images.githubusercontent.com/22002023/166665971-4fe20928-f01d-4553-b22c-dc07407a4d1f.png)

**Comment by DfrostX** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/618

**Comment by Misunderstood-Wookiee** [comment]
I see.
So I updated rhe backend from gitrepo, no luck, I'm going to have pester
them or fork it and figure this out myself.

**Comment by Rem0o** [comment]
Can't do anything from FanControl itself, closing.
