### ISSUE TITLE
Fans are not detected

### ISSUE THREAD

**Issue by garethsnaim** [Rem0o/FanControl.Releases#738]
Hi. I set this all up it takes a while as it goes through fan detection etc and it was working.

A restart later and I get an error and all the fans were there are listed as missing. I am going through the set up again, but is there something I am not doing right?

Also I have only one RTX 3080 but it is detailed twice as control 1 and control 2

My motherboard is not asus.

**Comment by Dracaerys2a** [comment]
Same for me. I was using your software on my Aorus B450 elite, everything was perfect, but after upgrading only my motherboard to a asus rog strix gaming f, everytime I restart the computer, fan names are missing. Maybe it has to do with some settings in the BIOS ?

**Comment by garethsnaim** [comment]
To be clear my motherboard is MSI. I only mention this because there was another thread talking about it relating to asus. My graphics card is asus, nothing else.

**Comment by Rem0o** [comment]
If you get errors after restart, try increasing the startup delay as mentioned in the popup.

**Comment by garethsnaim** [comment]
Hi I dont have it to start on start up so it had plenty of time. I would like to start again is it just a case of deleting the folder the App is in and redownloadiung?

**Comment by Dracaerys2a** [comment]
I found a fix for me, I tried increasing the startup delay but it was not the problem. I had to disable q fan in my asus rog strix motherboard BIOS. works perfectly fine now

**Comment by xhul-dev** [comment]
> Hi I dont have it to start on start up so it had plenty of time. I would like to start again is it just a case of deleting the folder the App is in and redownloadiung?

Yes.
