### ISSUE TITLE
Challenges getting set up > Fan match to sensor issues

### ISSUE THREAD

**Issue by quadcom** [Rem0o/FanControl.Releases#744]
Great piece of kit!

Thanks to Reddit and Jays2cents for telling us all about it!!!!

But I'm having some issues getting set up. Lot's of missing sensor to fan match problems.

I have a Corsair Commander on an Asus WSx570-ACE board with an Asus RTX2080.

![image](https://user-images.githubusercontent.com/7085931/167219257-5d7006fe-c245-4eb3-94ea-ba00d94fdd07.png)

I have some fans with splitters from Noctua. Most fans are Noctua aside from CPU and built in GPU fans.

![image](https://user-images.githubusercontent.com/7085931/167219331-5fcf3771-1778-472f-b058-fb7beba38b53.png)

**Comment by quadcom** [comment]
Nevermind!

Super old BIOS, updated to the latest official release.

Corsair Commander plugin working too after unblocking DLL.

**Comment by jpierce22** [comment]
im new could you help me ublock the dll?

**Comment by quadcom** [comment]
right click the dll and look at properties

You will see the unblock checkbox.

**Comment by jpierce22** [comment]
ive looked and in my general tab in properties doesnt have that check box. im on windows 10 home

**Comment by quadcom** [comment]
So you don't have this?

Are you an admin on the computer?

![image](https://user-images.githubusercontent.com/7085931/167227541-3132b7d6-1b20-46e8-87ce-5c9cc6255a5c.png)

**Comment by jpierce22** [comment]
no dont and yes im admin. eveywhere i look says i should have the option but i dont and even dont on the zip file

**Comment by quadcom** [comment]
I came across this PowerShell approach

https://support.hawkridgesys.com/hc/en-us/articles/360037654392-Unblock-Single-File-Zipped-Folder-Missing-Unblock-Option

**Comment by jpierce22** [comment]
thanks ill give it a shot

**Comment by Rem0o** [comment]
@quadcom  Since you got all your RPM sensors matched, 
![image](https://user-images.githubusercontent.com/14118956/167264300-734d30ee-067b-4795-97b4-b3a3cc970f85.png)

**Comment by quadcom** [comment]
> @quadcom Since you got all your RPM sensors matched, ![image](https://user-images.githubusercontent.com/14118956/167264300-734d30ee-067b-4795-97b4-b3a3cc970f85.png)

Yeah, I saw that after the fact.

Running into some other quirks. I posted another thread.
