### ISSUE TITLE
Tray Icon Light Theme - Windows 11

### ISSUE THREAD

**Issue by Cyrris** [Rem0o/FanControl.Releases#745]
Minor. While I think this was sorted on Windows 10 in Issue #127, this is still a problem in Windows 11 (or there is a regression, but I'm afraid I no longer have a Windows 10 box to check that). 

Windows 11 dark/light theme comparison below.

![image](https://user-images.githubusercontent.com/71960891/167232267-da3c8f26-0e3b-4b85-839e-abb246a85ea0.png)

![image](https://user-images.githubusercontent.com/71960891/167232163-b50dc67f-4dfd-42af-8801-dbd3802a9f1a.png)

The FanControl UI theme itself obeys the Windows theme just fine, it just seems to be the system tray icon itself. No combination of System or App theme selections makes a difference to this.

**Comment by Rem0o** [comment]
The icon won't change color dynamically with the windows theme, but it should sync when the app starts.

I will add dynamic synching in the next release.

**Comment by medevil84** [comment]
Unfortunately, with the latest review I have black text on a black taskbar... 
![Capture](https://user-images.githubusercontent.com/20990558/167519507-b6d3f192-d2db-4029-8794-9f9d72f4b7c6.PNG)
Probably, an option to override the color manually would be the optimum!

**Comment by Rem0o** [comment]
@medevil84  
![image](https://user-images.githubusercontent.com/14118956/167519665-6e0aa8ab-62dc-4c93-bf32-87316b98d659.png)

**Comment by medevil84** [comment]
> @medevil84 ![image](https://user-images.githubusercontent.com/14118956/167519665-6e0aa8ab-62dc-4c93-bf32-87316b98d659.png) Come to the dark side.

I will, but I need to upgrade to windows 11 first. On windows 10, dark mode is a punch in the eyes on some apps...

**Comment by CodeExplode** [comment]
Hey guys I'm also having this problem on windows 10.

![Temperature](https://user-images.githubusercontent.com/79982924/167541829-e1fb6b44-c704-438b-ac0b-f645f765a63f.png)

Default and on mouse over.

It might have something to do with that I've customized the taskbar a bit beyond just the default windows colour options using some registry settings for colours, to ty to get things generally dark, but all app titles / clock digits / etc are readable as white text and it's just this one temp sensor text which is unreadable on the taskbar.

**Comment by outgriber** [comment]
I'm having the same issue - the black digits on the black tray background. Win 11.

**Comment by Cyrris** [comment]
Win11 light/dark theme now works well for me (sorry to all above). Temp text is now dark-on-light and light-on-dark as appropriate.

Stock standard, no customisations on my PC - just using [AutoDarkMode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) to switch between the default light and dark themes.

**Comment by jpsjpsjps** [comment]
> Minor. While I think this was sorted on Windows 10 in Issue #127, this is still a problem in Windows 11 (or there is a regression, but I'm afraid I no longer have a Windows 10 box to check that).
> 
> Windows 11 dark/light theme comparison below.
> 

> 
> The FanControl UI theme itself obeys the Windows theme just fine, it just seems to be the system tray icon itself. No combination of System or App theme selections makes a difference to this.

This is a regression bug, it's broken in Windows 10 too this morning.

![Screenshot 2022-05-10 084905](https://user-images.githubusercontent.com/105273621/167576881-2b417bfa-13f1-4a89-b94a-9501da26a10c.png)

**Comment by Rem0o** [comment]
See V115.
