### ISSUE TITLE
Special EUFI motherboard Fan config?

### ISSUE THREAD

**Issue by quadcom** [Rem0o/FanControl.Releases#746]
I'm curious about if I am seeing a fan control war going on. The fan speeds being reported seem to jump all over th place for different fan headers. Including those on a Corsair Commander.

I also see a fan, driven by a curve, at 0% yet physically still spinning.

Is there a fan config in the UEFI Bios that we should set so that everything plays nicely?

If there are log files or any special steps I can do to help diagnose let me know.

**Comment by Rem0o** [comment]
Ideally you want to set a manual speed in your BIOS, like 50% as a default, before FanControl takes over.  For the corsair commander, if you got ICUE running, well, you can't. Both softwares will try to take the steering wheel.

**Comment by quadcom** [comment]
Yeah, I figured icue wouldn't play nice so that's disabled.

But, the motherboard does have its own fan curve control. I'll clear that out and see how things behave.

Perhaps a note in the install instructions to disable MB fan curves?

again, this is awesome work!

**Comment by Rem0o** [comment]
@quadcom  will add that in the Q/A of the readme. Might be improving the assisted setup also, tons of room for improvement in there.
