### ISSUE TITLE
All possible fan sensors are already matched

### ISSUE THREAD

**Issue by garethsnaim** [Rem0o/FanControl.Releases#748]
I am really struggling with this software. I deleted it and started again.

Its an MSI z590 wifi motherboard.

I have two fans connected at front 1 at rear a fan pump for a water cooler AIO and and a 3080.

After it runs all the setup only the 3080 is matched to 'speeds' The rest of 'controls' are shown but hidden. I can adjust fans speeds etc from control, however they cannot be matched to a sensor because 'all possible sensors are already matched'

Its probably me not understanding something fundamental here, isn't each fan supposed to have its own 'speeds' section?

**Comment by Rem0o** [comment]
A screenshot would do wonders.

**Comment by garethsnaim** [comment]
I quit the app then loaded again then it said this, (As it has done since I have tried these past few days)

![Screenshot 2022-05-07 201712](https://user-images.githubusercontent.com/64017211/167268757-c3f68be2-f254-414b-ace5-ad129e61cb3c.jpg)

Then when I click refresh all the fans show speeds as well. Which is great but I know if I restart the PC I will egt that screen again and they wont show :(

**Comment by quadcom** [comment]
increase the delay setting in the menu on the left side of the UI.

**Comment by Rem0o** [comment]
No news. Closing.
