### ISSUE TITLE
UI will not display

### ISSUE THREAD

**Issue by MacMcGarrigle2** [Rem0o/FanControl.Releases#750]
Hi,
First I love this software and will contribute later.  However, it does not show the UI when selecting the icon.  It does not show up in the list of programs so I can not reinstall or modify it.  I think it is running in the background but worried it is not working.  I want to modify if to fix a high temperature but can't get to it without the UI being there.  This is the first time I installed it.
Thanks for your help in advance.
Cheers,
Mac
mac.mcgarrigle@gmail.com

**Comment by Rem0o** [comment]
The app should be in the bottom right tray, in your taskbar.

**Comment by quadcom** [comment]
Open the folder you extracted all the files to. Right click on the EXE files and choose PIN TO START. That will create a shortcut on your start menu.

In your systray (where the clock is showing the date/time) you will find a small picture of a fan. Double click that and the application will open for you to make your config changes.

Make sure you save any changes you make.

**Comment by MacMcGarrigle2** [comment]
Thanks for the quick reply.  I tried that and it did not work.  How can I
uninstall it and reinstall it?  I really like it….

**Comment by xhul-dev** [comment]
Is the Fan Control icon still present in the system tray?

**Comment by MacMcGarrigle2** [comment]
Yes.  It appears in the system tray and I have it pinned to the start and the task bar.  It is running as a service as well.  It is not displaying the UI if I click on any of these.  It also not in my list of programs.
I have an i7 12700X, and a ASUS TUF 3080 TI GPU running Windows 10 if that helps any. 
Any help would be appreciated.

**Comment by quadcom** [comment]
You have to double click the fan in the systray

**Comment by MacMcGarrigle2** [comment]
Hi Guys,
I deleted everything, rebooted and reinstalled.  Works fine now.  Thanks for the help.
Cheers,
Mac

**Comment by MacMcGarrigle2** [comment]
Thanks, well done…
