### ISSUE TITLE
Tray Icon not readable

### ISSUE THREAD

**Issue by bobdig** [Rem0o/FanControl.Releases#756]
I updated to version 113 this morning and later I noticed, I couldn't read the tray icon anymore. Even rebooted the machine and it didn't helped. So I guess it is from this new version. 

![Clipboard01](https://user-images.githubusercontent.com/46788742/167629431-449bec9f-becd-47c2-81c2-637457467f5c.png)

**Comment by Rem0o** [comment]
Went to mess again with detecting darkmode/lightmode => it's a total nightmare.

On W11 they cleaned it up, but on W10 there are like 3 different places someone can set a "dark" theme. 

I think I will provide an override in the theme section of the software.

**Comment by bobdig** [comment]
@Rem0o Mine is set like this but will switch on apps to dark too at night times.
![Capture2](https://user-images.githubusercontent.com/46788742/167634528-75fc9d04-c621-4f53-81a3-f1a96b179cb6.PNG)

**Comment by bobdig** [comment]
Now with Apps also being dark it is looking like it should and always was for me.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/167960535-c92acccb-4429-4778-abb6-1631d1d05ea7.png)

incoming.

**Comment by bobdig** [comment]
I don't know if you are aware that, this is the important part, I guess:

![bbb](https://user-images.githubusercontent.com/46788742/168008210-feb4f528-7aaf-41bd-8c11-fd8e3ba8e6d1.PNG)

With all the bad news regarding future Windows11 (online account is a must even for pro), it would be nice to have a solid Windos10 support with your nice tool.

**Comment by renesdk** [comment]
I have this exact issue under Windows 11 after updating from V112 to V114.

Looking forward to an override to this in the settings of Fan Control.

**Comment by bobdig** [comment]
@Rem0o Thanks for the fix with V115!

**Comment by renesdk** [comment]
Yes, thank you for the fix. Worked perfectly
