### ISSUE TITLE
hwinfo plugin problem

### ISSUE THREAD

**Issue by hryarih32** [Rem0o/FanControl.Releases#758]
Hi.
After updating to v113, the app doesn't recognize hwinfo plugin 1.0.31.
also, the hwinfo plugin 1.0.32 doesn't recognize hwinfo below v7 which you can't use shared memory before the paywall.
so what should I do?

**Comment by ChaplainTIG** [comment]
following

**Comment by Rem0o** [comment]
I updated the plugin to use the gadget system instead of the shared memory, since it has a time limit.

Download the new version of the plugin.

However, the old one should still work too, that's a bug/regression.

**Comment by hryarih32** [comment]
thank you.

> I updated the plugin to use the gadget system instead of the shared memory, since it has a time limit.
> 
> Download the new version of the plugin. Use the latest of HWInfo also.
> 
> However, the old one should still work too, that's a bug/regression.

**Comment by bootyburglar** [comment]
Ah, just found this thread. I opened another issue here: https://github.com/Rem0o/FanControl.Releases/issues/760, let me know if you recommend just using the latest HWInfo and there will be backward support for HWInfo below v7.

**Comment by Rem0o** [comment]
Well for V7 and below, use the old plugin/shared memory.
