### ISSUE TITLE
Does not effect AIO

### ISSUE THREAD

**Issue by garethsnaim** [Rem0o/FanControl.Releases#759]
Hi there.

I have a NZXT Kraken AIO. Nothing I do changes the pump speed which is a constant 2020rpm even though the cpu is like 35 degrees.

I have tried on both the pump and cpu header

**Comment by KALRONG** [comment]
Hi @garethsnaim,

Maybe a stupid suggestion but I had a similar issue and found out that the problem is that after a BIOS reset my pump was set to PWM instead of DC so while the RPMs where propertly reported I couldn't control it for obvious reasons.

Hope it helps, if not, I will recommed providing the exact model of the kraken io and your motherboard.

Best regards!

**Comment by garethsnaim** [comment]
I think I am going to leave this software for now, I love the idea of it, but between it and my system something is not happy, yet again all the sensor are missing even though PC has been on 10 mins.

I'll visit back in a few months.

**Comment by MartinTophill** [comment]
I had the exact same problem in the beginning.

Disable your NZXT CAM auto-start-up at windows boot and make sure you have ''Controller (various third party)'' selected in sensor settings.
It's probably your CAM software messing things up and/or overriding something.  After I stopped using CAM, fan-control works just fine.

**Comment by garethsnaim** [comment]
Hi thanks for this. No dice here though, I tried running the setup again just looking at third party controllers and it only sees the RTX. I read the cam software is poor so have not installed it. 

I see real potential in this app, but its a mile away for me right now. I will try and set things through bios and revisit this app in the future.
![Screenshot 2022-05-17 074327](https://user-images.githubusercontent.com/64017211/168746127-1e023585-af32-4042-9899-ae8e8440bbb9.jpg)
