### ISSUE TITLE
Provide graph for all curves

### ISSUE THREAD

**Issue by cowwoc** [Rem0o/FanControl.Releases#76]
Please provide a graph of temperature vs fan speed for all curves, including "mix" and "target" which currently do not have this.

**Comment by Rem0o** [comment]
You mean as documentation in this repo or in the software itself? 
Some curves like "Target" and "Mix" don't really make sense in a graph form.

**Comment by cowwoc** [comment]
I meant in the software itself. Why doesn't "Mix" make sense in a graph form?

**Comment by Rem0o** [comment]
Because you can not only mix graphs, but also other types, like an other mix, a target fan curve or others. Covering all possibilities for it to make sense to the user would be tedious.

**Comment by cowwoc** [comment]
@Rem0o Can you implement this only for the easy types? For example, if the types being mixed are a linear graph, flat graph and so on.

**Comment by Rem0o** [comment]
Could be, but this ain't at the top of my list right now. Right now I working on adding a "help" section for each fan curve type to explain the features of each, their use cases and so on.

**Comment by weebsnore** [comment]
Similar request - hopefully this is an OK place for it?

What do you think about providing some preset curves, like you get in GPU tweak software or the BIOS?

Standard, quiet, turbo, and so on.

Keep up the great work!

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V60
