### ISSUE TITLE
v114 no longer loads sensor values from HWINFO64

### ISSUE THREAD

**Issue by bootyburglar** [Rem0o/FanControl.Releases#760]
**Update**
https://github.com/Rem0o/FanControl.Releases/issues/758
It's recommended to use the latest HWInfo because the plugin no longer relies on shared memory in HWInfo v7 or above, which has a time limit and a paywall

**Context**
HWInfo64 version `6.42-4360`. 
I have done the following steps:
- Download the latest binary for the HWINFO plugin
- Extract in the plugins folder and unblock the `FanControl.HWInfo.dll` and `FanControl.Plugins.dll` in the `Plugins` folder
- Enable reporting and report value in gadget

see the attached screenshot below
<img width="842" alt="image" src="https://user-images.githubusercontent.com/67488743/167725328-b6d6cbbd-06fa-42ed-a3bc-0ff0bb3f2b4b.png">
The error logs didn't show any loading errors but just can't see the enabled sensor value in hwinfo.

**Comment by Rem0o** [comment]
Requires HWInfo V7+ I believe. They changed how they write to the registry.  Try the latest version. Else stick with the old plugin.

**Comment by Rem0o** [comment]
Also, that's an issue for the HWInfo repo, not the main FanControl one.

**Comment by bootyburglar** [comment]
all right, thank you!
