### ISSUE TITLE
Can't control case and cpu fans

### ISSUE THREAD

**Issue by paolov55** [Rem0o/FanControl.Releases#761]
Hello, guys. So, I've installed FanControl, run through the assisted setup but it seems I'm running into a problem where the program can't control the case and cpu fans. As you can see in the image below, all 3 sensors say "a paired RPM sensor is required", while the GPUs are normally tested.

![image](https://user-images.githubusercontent.com/105325499/167739782-31fee126-00cf-4a3a-863b-4baf2c8b4cf5.png)

My mobo is a B350-prime plus from ASUS, which has 2 CHA_FAN headers and 1 CPU_FAN header, it has q-fan control enabled in the bios (tried to disable it and nothing changes). I'm running 5 fans (3 front ones connected through a splitter to one header, a back one connected directly to the mobo and the CPU fan, also connected to the mobo).

Also, as you can see, it seems like the readings from the RPM aren't fine either (except for the GPU), since it says one of them is running at 20 RPM and the other two would be above max speed.

![image](https://user-images.githubusercontent.com/105325499/167740189-31d494c7-e3c0-445b-871c-5ee4c0b628a1.png)

Sorry if I wasn't clear enough, but I'm not really an expert, but you can ask me if anything. Hope you can find a way to get me through this.

**Comment by ronjr2** [comment]
same here   i got 6 case fans with same problem

**Comment by MartinTophill** [comment]
Stupid question but, are you sure you have PWM fans and not DC fans? 
Or maybe different size / brand / types of fans?
And remember, splitters only read PRM from one of the fans connected to it.

You could also try setting your fans to ''manual control'' in ASUS's BIOS

**Comment by Rem0o** [comment]
See Readme.
