### ISSUE TITLE
Not Working after Windows11 Update/Patchday on 10.05.2022

### ISSUE THREAD

**Issue by 9716cwr** [Rem0o/FanControl.Releases#763]
Before reboot after the newest Updates works normal, after that no chance to start even when start in admin mode.
Status update, 
after deinstall the latest Win11 updates and reboot, everything works fine again (Keepass also didnt work), MS sucks!

**Comment by KALRONG** [comment]
Same issue here after reboot, but after closing and reopening the app the sensors are back while in autostart it coulnd't find them.

**Comment by crawfishie** [comment]
No KeePass or Fan Control problems here after the latest Windows 11 update.

**Comment by 9716cwr** [comment]
It seems to be an .NET Framework 3.5 issue, as described on the following site:
https://docs.microsoft.com/en-us/windows/release-health/status-windows-11-21H2 
After running the command " dism /online /enable-feature /featurename:netfx3 /all " in elevated Command Prompt and reboot everything seems to work normal, at least for me :- )
