### ISSUE TITLE
Nicehash Quickminer Crashes Fancontrol

### ISSUE THREAD

**Issue by moveit124** [Rem0o/FanControl.Releases#767]
Whenever Nicehash Quickminer opens up Fancontrol instantly crashes and refuses to run.  I think this has to do with the OCTune on Nicehash Quickminer???  Just a guess

But it would be nice if Fancontrol would just go on Standby or something along these lines whenever something else forces control of fans.  Or if it released control of the GPU fans/sensors.

**Comment by Rem0o** [comment]
FanControl can't really detect if an other process is messing with the superio chip at the same time. It's kind of unexpected behavior when 2 programs try and read/set memory registers at the same time.  Can't do much.
