### ISSUE TITLE
Fan grouping question

### ISSUE THREAD

**Issue by dfgdgdgfd** [Rem0o/FanControl.Releases#768]
Ok, not an issue as such, but the last time I tried to do this, I wrecked my config.
I want my case fans (All installed to motherboard headers so all able to manually control etc) to spin up from 50% (Manually set atm) to 100% once the cpu fan either reaches a certain speed, or temperature.  I had a bit of a play around with curves but didn't really know what I was doing and wrecked my config + my cpu fan curve that's managed by msi center.  I'm really hoping I wouldn't have to get rid of that to do this, my system gets really weird if the cpu fan is controlled by bios settings or anything other than msi center.  If I'm only telling other fans to do something, it should be fairly easy, right?

**Comment by xhul-dev** [comment]
Hello there.
If the CPU temp is the only temp you care about, you should already be able to do that using the BIOS alone.
The only reason to use Fan Control that i see would be to have curves with more than 4 points, which is usually what you get in MSI BIOS.
But yeah, such setup would be easy to do in Fan Control, assuming everything is detected properly.
And yeah, you can turn off the control of the CPU fan specifically, if you want MSI center to handle it.
