### ISSUE TITLE
After editing curve Ive got crash

### ISSUE THREAD

**Issue by Majber** [Rem0o/FanControl.Releases#769]
After editing curve Ive got crash and must restart program to edit again. (for another crash/bug after edit)

Here is my log:
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8679629/log.txt)
Here is my report from "copy report to clipboard, i dont know if its helpfull:
[report.txt](https://github.com/Rem0o/FanControl.Releases/files/8679638/report.txt)

**Comment by Rem0o** [comment]
Figured out the bug ( I think ), will fix.

happens when you put 2 points to the far left of a graph.

**Comment by Rem0o** [comment]
See V118
