### ISSUE TITLE
Please let us disable the constant popup

### ISSUE THREAD

**Issue by Znunu** [Rem0o/FanControl.Releases#77]
As much as I like fan control, the popup to support the development is so annoying. Surely there's a better way to do this? If someone donates will that actually make it stop?

**Comment by Rem0o** [comment]
Clicking the "Donate" button, even if you don't actually donate, will pause the popup for a while ( months ).  Right now it will popup weekly if you have at least 1 fan curve active.  

So free to use with weekly popup is the actual model. 
I'm open to suggestions. 

One thing though, ideally, I don't want to track ANYTHING on your computer, be it donation, software key and so on.

**Comment by Znunu** [comment]
hmmm... guess I should start clicking the other button. I'll try and see if that's better for me
> One thing though, ideally, I don't want to track ANYTHING on your computer, be it donation, software key and so on.

Why not?

**Comment by Rem0o** [comment]
Mainly because it is tedious to do it right, and is simply not fun, and I want this to stay a fun project to work on.

**Comment by Znunu** [comment]
I see. Well, I guess you could maybe have a premium version?

**Comment by Rem0o** [comment]
> I see. Well, I guess you could maybe have a premium version?

Yeah, thought about it, but again, that would involve software keys, licenses and so on, and I'm not sure I want to get involved in that realm right now.

**Comment by Znunu** [comment]
That's... fair, just don't think it goes well with the popup
