### ISSUE TITLE
As a user, I'd like to import and export profiles

### ISSUE THREAD

**Issue by Heinzen** [Rem0o/FanControl.Releases#774]
I tried the software before having to reformat my PC and having to reconfigure everything else is sort of a pain. As a user, I would like to be able to export my profile to a generic format and be able to import the settings afterwards

**Comment by bgktmxg** [comment]
Fairly certain the JSON file in the FanControl program directory contains all the user settings. Just copy it out and drop it back in after formatting

**Comment by Rem0o** [comment]
This ^ . Closing
