### ISSUE TITLE
grosse latence du prog.

### ISSUE THREAD

**Issue by PurPPle77** [Rem0o/FanControl.Releases#778]
Bonjour,
J'ai vu que le dev. est francais du coup c’est plus simple pour moi en v.o...dsl
Le programme est très lent quand on l'utilise, par exemple en mettant un ventilo en manuel, il ne réagit pas de suite.
Et aussi même avec 30sec de délais au démarrage il ne veux pas reconnaitre les détecteurs.
J'utilise Win 10 pro et j'ai une Asus X470pro avec le Q-fan désactivé dans le bios.
Cordialement.

**Comment by xhul-dev** [comment]
Ca sent le souci de compatibilité entre carte mère et LibreHardwareMonitor.
Peut-être que Rem0o pourra confirmer.

**Comment by PurPPle77** [comment]
ok.
En tout cas l'app est super (marche pas tip top), mais quand même, merci.

**Comment by Rem0o** [comment]
Essaye de désactiver les sources de capteurs que tu n'utilise pas, pour n'avoir que le stricte minimum. Certaines sources (comme les disques) peuvent être à l'origine de la latence que tu observes.

![image](https://user-images.githubusercontent.com/14118956/168872777-5808be96-bba3-4f7f-a113-e91306d5bf2b.png)

**Comment by PurPPle77** [comment]
Bonjour,
D'accord merci. Ça à l'air de mieux répondre en effet, mais en manuel, ça met toujours un peu de temps a réagir quand même. J'ajoute aussi qu'avec l'assisted setup la 1ere fois que j'ai intall l'app et que j'avais pas désactivé q-fan (et je crois que c’était en DC dans le bios) il m'avait reconnu et assigné tout les fans et sensors. Un peu après j'avais fait un reinstall propre avec q-fan désactivé et là le prog. ne voulait plus assigner et détecter certains case fan, c'est en faisant "paired sensor auto." sur quelque controls qu'il avait pu les assigner. Si ça peut aider. (j'ai testé toutes les combi dans le bios :  avec/sans q-fan, DC, PWM )
Merci encore pour cet app "gratos" !
