### ISSUE TITLE
Chained PWM fans don't seem to spin as fast as they should

### ISSUE THREAD

**Issue by ALexus1907** [Rem0o/FanControl.Releases#78]
With multiple fans connected to a single PWM fan header the fans seem to be spinning slower than they should according to the set curve. Almost as if they were getting the power required for a single fan instead of multiple fans connected together. (when controlled through the motherboard bios settings this issue doesn't occure)
not sure if it's an issue specific to my hardware but I'm using an aorus b450 elite motherboard.

P.S. - You're doing God's work man, I've been looking for something like this for ages since speedfan doesn't seem to be updated anymore and doesn't work with my mobo (and frankly even if it did work your UI is miles ahead of it lol). Thanks for taking time to make this amazing piece of software.

**Comment by Znunu** [comment]
Same. A lot of pages recommended speedfan so I tried it. Something wasn't working so when I went to research it, I also realized the developer abandoned it years ago.

**Comment by Znunu** [comment]
Just realized that my setup is similar. asrock b450 pro4 with 3 chained arctic P12 fans. I don't have this issue. UEFI and FanControl 100% both result in the same fan speed, the rated max for the p12.

**Comment by trankillity** [comment]
This explains why my fans are quieter using this than with stock BIOS settings. Haven't done a linear test between them yet, but will edit this response when I get a chance to.

**Comment by fredskis** [comment]
Do the fans report different RPM when set to the same %? Or is it just noise & perceived volume that is showing the different speeds? 

I'm just wondering if I could check out my setup and see if I can reproduce. I have an ASUS ROG Strix Z490-I and splitting two NF-A14 PWM in my NCASE M1 for GPU exhaust. I didn't notice any perceived difference but I didn't really look that hard either. 

When set at 50% they report ~820 RPM which is in line with their max 1500 RPM spec. The mobo settings in BIOS resulted in the same reported RPM and from memory, similar noise. 

Setting to 100% pumps the reported RPM to 1400ish and about as loud as when I set it to 100% in BIOS.
