### ISSUE TITLE
Application doesn't start

### ISSUE THREAD

**Issue by Kor1134** [Rem0o/FanControl.Releases#780]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8693543/log.txt)
Get several errors in log, including "System.PlatformNotSupportedException: Operation is not supported on this platform."
I could not find any minimum system requirements so I can only assume Windows 7 is supported, since Windows 10 is an ugly mess that breaks with every update.

**Comment by xhul-dev** [comment]
Nope, win7 not supported on the current release.
You might wanna try version 63 though, just be aware that a lot of bug fixes were performed since.

**Comment by Kor1134** [comment]
I appreciate the quick response.  Thank you.
