### ISSUE TITLE
sensor detection fails on startup

### ISSUE THREAD

**Issue by Migamix** [Rem0o/FanControl.Releases#783]
MSI Pro Z690a-DDR4 every fan slot in use. 
7 times out of 10 fan control will startup but not detect fan sensors. it takes me a couple of presses of the refresh sensors in menu and it works perfectly. it doesnt matter what delay settings i have (from 15 all the way to 120sec) it still happens. 
my request is to **add an option to have the scan sensors run a few of times with maybe a delay before it tosses up the error window to give it the chance to take control. doable in settings i would think** i really dont want to use the MSI fan control as it lacks....everything. 
blame jay for all of us showing up. 
 this is the only issue i have run across everything else works nicely
thanks for the hard work

logs are after fans are working, logs before showed less info. so i assume you want working logs too. 
[fanControl20220515.log](https://github.com/Rem0o/FanControl.Releases/files/8695571/fanControl20220515.log)

log since first run on new system
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8695578/log.txt)
.

**Comment by turbobitterbal** [comment]
Hey, im having exactly the same problem and I also have the MSI PRO Z690-A DDR4 you can also have my logs I you want, let me now.

**Comment by chorong761** [comment]
Same issue here. I've delayed the startup to 2 minutes and added a kill task before it so it kills the program before it starting it again. Even with that, the sensor detect error still shows after relaunching the program. I think there should be a launch command that could refresh the sensors, so it could be added to a launch .bat file.

**Comment by javierportillo** [comment]
Same issue on MSI B550-A PRO.

**Comment by bretleasure** [comment]
I have the same issue with MSI MEG x570s Ace Max. Also experiencing it with another similar fan control software. Definitely seems to be an issue with MSI boards. I didn't have the issue with an Asus motherboard.

**Comment by Migamix** [comment]
> I have the same issue with MSI MEG x570s Ace Max. Also experiencing it with another similar fan control software. Seems to be an issue with MSI boards. I didn't have the issue with an Asus motherboard.

thats what i was afraid of, its why i suggested that maybe the programme bumps the sensors a few times to to the board, hey, gimmi control before it tosses up the error.
im going to look over the forums on msi and see if there has been a workaround for the boards wanting exclusive control, seem to have the same type of issue with aRGB headers.

**Comment by Rem0o** [comment]
Added a multi-retry mechanism since, until all sensors are back.
