### ISSUE TITLE
Feature Request: Fan speed minimum

### ISSUE THREAD

**Issue by Wolphin5** [Rem0o/FanControl.Releases#785]
With What I have set up is a Fan header is controlled by a Mix Curve, which is controlled by the Max of 3 different Temperature Graph curves (CPU, GPU, and MB) and a flat curve.

What I would like to do is set the fan to have a minimum set, so the fans don't spin below this, even if the curves have it doing so.  In this case, would want to set 25%.  I would also like to do so for my AIO pump (40-50% in that case).

I can set an offset, but I would prefer to have it follow the curve when it is above the minimum.
I can set the curve to have a minimum of it, but the curves are shared with other fans, which I do want to turn off.  
I have additional Flat Curves used in the Mix to set the minimum, but this makes it so I have to have multiple mixes, where the only differences is fan minimums, which could be simplified.

What I would like to request, is beside the Offset in the Fan Control, being able to set a Minimum Speed, where the fan will never try to go below.  If the controls tell it to go below it, it will just sit at this programmed minimum.

**Comment by Rem0o** [comment]
See V138
