### ISSUE TITLE
Problem with reading NZXT Pump speed %

### ISSUE THREAD

**Issue by Mettkrieger** [Rem0o/FanControl.Releases#79]
The % at which the pump is running is sometimes not updated.
I think it's the case when you have a startup for liquidctl to control your pump where you set pump speeds and then turn on FanControl.
https://i.imgur.com/E2iZwcY.png
The control itself seems to work just fine 👍

**Comment by C0NTi** [comment]
I have the same behaviour.
RPM is correct, and control is fine.
However, I think its more a problem with librehardwaremonitor rather than with fan control

![image](https://user-images.githubusercontent.com/29498865/113472257-e599e380-9459-11eb-8e26-e69d8e5b70f1.png)

**Comment by Rem0o** [comment]
Has nothing to do with FanControl itself, closing.
