### ISSUE TITLE
Feature Request: Support for Lian Li Controller

### ISSUE THREAD

**Issue by immortal-cabbage** [Rem0o/FanControl.Releases#796]
I don't know if this can be done, but would it be possible to get support for the Lian Li fan controller? I have Lian Li Uni fans and whatever I do, I can't seem to get Fan Control to sense the fans. If it can't be done, or if I missed a plugin somewhere, I may just switch fans and use the mobo. I like this software too much to be without it.

**Comment by jmarucha** [comment]
If you fire up LibreHardwareMonitor, does the controller show up?

**Comment by immortal-cabbage** [comment]
Under the "Controls" section I have CPU, Pump, and 6 system fans. (I do* have 8 fans) But it is showing them all @60% which is not correct. Under the "Fans" section there is nothing listed. So I would go ahead and say they are not being recognized? At least not properly.

**Comment by immortal-cabbage** [comment]
Alright well then I'm ditching the controller because your program is better. I was just wondering if there was a way. But thanks for the reply!

**Comment by BatteryAcid** [comment]
@Rem0o 
> It won't pick up your external controller.

Is that due to a lack of ability to get data from an external controller, or just a choice to not support that functionality?

Thanks!

**Comment by Rem0o** [comment]
If the controller has an API through an HID interface, support may be added in. 

Can be done through https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
or a stand-alone plugin: https://github.com/Rem0o/FanControl.Releases/wiki/Plugins

**Comment by josephJaoNasser** [comment]
## I found a workaround!!!

Hello, I have discovered a workaround for this. Your results may vary, but this solution worked for me.

### Step 1: Plug in the Lian Li hub PWM connector
- I plugged in the PWM header from my L-Connect fan hub to my motherboard. 
- This PWM connector should've come inside the box along with the controller, it's the one bundled up with the ARGB header (you don't need to plug in the ARGB header). 
- I plugged it into one of the CPU headers, but you can try to plug it into case fan headers although I haven't tried it myself.
But to save you the hassle of unplugging it in case it doesn't work, just plug it into one of the the CPU headers (although in theory it should work with any of the fan headers)

<img src="https://user-images.githubusercontent.com/57519561/199957953-ac15b7ba-4b4c-4b8a-847d-0dbbd1744b87.jpg" height="600"/>

### Step 2: MB RPM sync in L-connect software
- Get the L-Connect software, I used L-connect 3.
- On the sidebar, go to **Fan/Pump Profile**
- At the top you should see **MB RPM Sync** and turn it on

![image](https://user-images.githubusercontent.com/57519561/199959143-83836d5f-9a33-449c-99d3-399686c24514.png)

### Step 3: Find the corresponding controller in the Fan Control app
This step is pretty much self explanatory. Inside Fan Control app, set all your fans to manual. One-by-one set the controllers to 100%. Which ever one makes your fans ramp up is the one that controls the Lian Li fan hub

![image](https://user-images.githubusercontent.com/57519561/199960138-d444567c-7469-419b-955a-29f0940c1c7d.png)

Once you found which one controls the Lian Li fans, rename it, and then test it with your curves.

![image](https://user-images.githubusercontent.com/57519561/199960519-a35fcbb6-35ae-421a-b88a-547ee21c6b90.png)

And voila! You can use the Lian Li fan hub with Fan Control!

**Comment by robinslate** [comment]
> @Rem0o @immortal-cabbage @BatteryAcid @jmarucha 
> 
> # I found a workaround!!!
> 
> 
> 
> Hello, I have discovered a workaround for this. Your results may vary, but this solution worked for me. 
> 
> 
> 
> **Note:** This only works if you want to control ALL the fans connected to the hub. You can't really control each single fan/fan group. For my use case, I just want to control all the fans, and if there are any other fans that I want to control individually, I just plug them into a separate PWM header on the M/B
> 
> 
> 
> ## Step 1: Plug in the Lian Li hub PWM connector
> 
> - I plugged in the PWM header from my L-Connect fan hub to my motherboard. 
> 
> - This PWM connector should've come inside the box along with the controller, it's the one bundled up with the ARGB header (you don't need to plug in the ARGB header). 
> 
> - I plugged it into one of the CPU headers, but you can try to plug it into case fan headers although I haven't tried it myself.
> 
> 
> 
> <img src="https://user-images.githubusercontent.com/57519561/199957953-ac15b7ba-4b4c-4b8a-847d-0dbbd1744b87.jpg" height="600"/>
> 
> 
> 
> ## Step 2: MB RPM sync in L-connect software
> 
> - Get the L-Connect software, I used L-connect 3.
> 
> - On the sidebar, go to **Fan/Pump Profile**
> 
> - At the top you should see **MB RPM Sync** and turn it on
> 
> - If you're using an earlier version of L-connect, I'm not sure if there's something similar but hopefully there is
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/57519561/199959143-83836d5f-9a33-449c-99d3-399686c24514.png)
> 
> 
> 
> ## Step 3: Find the corresponding controller in the Fan Control app
> 
> This step is pretty much self explanatory. 
> 
> - Inside Fan Control app, set all your fan controls to manual.
> 
> - One-by-one set the controllers to 100% and find which controller ramps up your fans. 
> 
> - If you have L-connect installed try checking "Force Apply", or if you haven't done step 2, go do it
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/57519561/199960138-d444567c-7469-419b-955a-29f0940c1c7d.png)
> 
> 
> 
> Once you found which one controls the Lian Li fans, rename it, and then test it with your curves.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/57519561/199960519-a35fcbb6-35ae-421a-b88a-547ee21c6b90.png)
> 
> 
> 
> And voila! You can use the Lian Li fan hub with Fan Control!
> 
> 

Amazing! It works! Thank you so much for figuring this out and posting. Much appreciated.

**Comment by EightB1ts** [comment]
For those not interested in connecting to the PWM header...

I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi
Looking for beta testers. If you have time, please let me know if it works for you!

**Comment by ItsGonnabeSoCoolDude** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/56778781/17c770b2-9e4a-4e0f-8d7f-8ffb286622bf)

> Looking for beta testers. If you have time, please let me know if it works for you!

@EightB1ts It sees the fans, and -- sort of -- controlled port 3 of the Lian Li controller. Once. it's not repeatable. Manual control and force apply doesn't do anything for any of them now though, and ports 2 and 4 were never responsive. I do not have anything in port 1

**Comment by EightB1ts** [comment]
@ItsGonnabeSoCoolDude Hi, please make sure L-Connect isn't running in the background and that RPM sync is disabled. If it's still being problematic, could you create an issue in the repo so it can be tracked? Please include the PID of the controller, info on where to find this is located in the readme. Thanks!

**Comment by ItsGonnabeSoCoolDude** [comment]
> @ItsGonnabeSoCoolDude Hi, please make sure L-Connect isn't running in the background and that RPM sync is disabled. If it's still being problematic, could you create an issue in the repo so it can be tracked? Please include the PID of the controller, info on where to find this is located in the readme. Thanks!

It works!

**Comment by Bastis95** [comment]
> For those not interested in connecting to the PWM header...
> 
> I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi Looking for beta testers. If you have time, please let me know if it works for you!

Just tried your Plugin and it works really well. I am able to control each channel of the Lian Li control hub.

Do you have any plans to add the ability to control individual Lian Li Fans on each channel? or is this not feasible?

I ask because I am currently running the following setup:
3 x 120mm front fans
2x 140mm top fans
1 x 120mm back fan 
all Lian Li Uni AL v2s

I would like to set the first top fan at a slower rpm to stop it from venting still-cool air from the front fans before the air has had a chance to soak up heat.

**Comment by EightB1ts** [comment]
This is not possible, limitation with the hardware.

**Comment by Bastis95** [comment]
Thanks for the update.

**Comment by Michipulatos** [comment]
> * ****
> * At the top you should see **MB RPM Sync** and turn it on
> * If you're using an earlier version of L-connect, I'm not sure if there's something similar but hopefully there is
> 
> ![image](https://user-images.githubusercontent.com/57519561/199959143-83836d5f-9a33-449c-99d3-399686c24514.png)

Amazing! Thank you so much for spending the time to make this. I can no finally remove l-connect from my life once and for all.

**Comment by Michipulatos** [comment]
> For those not interested in connecting to the PWM header...
> 
> I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi Looking for beta testers. If you have time, please let me know if it works for you!

Amazing! I have been waiting years for this. Thank you so much for spending the time to develop this. I can now finally remove l-connect from my system once and for all.

**Comment by Bastis95** [comment]
Thanks for the update I will give it a try.

**Comment by d1way** [comment]
> For those not interested in connecting to the PWM header...
> 
> I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi Looking for beta testers. If you have time, please let me know if it works for you!

I cant find the plugin folder. can you help me? this is my first time installing this software

**Comment by d1way** [comment]
![image](https://github.com/Rem0o/FanControl.Releases/assets/155358710/ed5f942d-bf46-429e-b766-3fa48d4383e8)

It detects the unifans but why it doesnt detect the rpm? and i also cant control it. The controller is connected to cpu_header

**Comment by lowrey2142** [comment]
> For those not interested in connecting to the PWM header...
> 
> I've written a plugin that added support for LianLi controllers: https://github.com/EightB1ts/FanControl.LianLi Looking for beta testers. If you have time, please let me know if it works for you!

This worked great for me, thanks!
