### ISSUE TITLE
Feature Request: Add the ability to toggle BIOS control

### ISSUE THREAD

**Issue by nootey** [Rem0o/FanControl.Releases#798]
Hey, 
so this is very specific for my setup, but would be appreciated. I have an aio pump port on my motherboard which sometimes acts up when restarting my pc and I need to toggle the fan control for that specific port to "BIOS controlled" and then back to fan control to start it up (I don't know why it does this and I gave up trying to fix it permanently). 

Argus monitor has this functionality, where you can change fan control to manual, fan control or BIOS control.
 Thanks!

**Comment by Rem0o** [comment]
"Disabled" on the control card is "BIOS-controlled".

**Comment by nootey** [comment]
Alright, had a hunch it was that. Would you know why it doesn't toggle correctly? I had to boot up Argus monitor back up twice now cause it wouldn't toggle to BIOS control and re-enable the header.

**Comment by nootey** [comment]
Sorry for the poor wording, what I meant is that when i disable the control card, it should switch to BIOS control and in turn "re-enable" control for the aio pump header, but it doesn't. It seems to be stuck on "fan control" mode. Again, this is very specific to my setup and I don't expect anything, just wanted to point out that disabling the control card (switching to BIOS control) may not work correctly. Anyway, thanks for your time, great app!

**Comment by Rem0o** [comment]
Well, that's compatibility issue I guess. See the README for that, not much that I can do.

closing.
