### ISSUE TITLE
FanControl crashes upon reloading sensors. 

### ISSUE THREAD

**Issue by lbibass** [Rem0o/FanControl.Releases#80]
If I try to refresh sensors detection, it crashes, with this error. 

`System.DllNotFoundException: Unable to load DLL 'nvapi64': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

I am using an AMD gpu, so missing the nvapi64 should be expected. The crashing is not.

**Comment by Rem0o** [comment]
Could you provide the complete log? I think I found the issue, but just to be sure.

**Comment by Rem0o** [comment]
Will be fixed in the next version.

**Comment by Rem0o** [comment]
Fixed in V58.
