### ISSUE TITLE
V115 update, now all fans stuck on 43.5%

### ISSUE THREAD

**Issue by WanaGo** [Rem0o/FanControl.Releases#800]
Hi,

Have been using this a number of months now, and I love it.
Updated to V115 today, and noticed now that all of my fans are running at 43.5%... which doesn't seem right.
I even played with the idle and load temps on the "T Sensor Temp" block, which controls my Radiator fans from a sensor in my water loop, and it made no difference, the fans just stay on 43.5%...

Any ideas?

![image](https://user-images.githubusercontent.com/759846/168965649-67fdd156-bc5d-4a22-86b0-75ac4ae484c1.png)

**Comment by WanaGo** [comment]
I've checked BIOS, Tried Q-Fan, PWM, DC and Disabled, and it seems to make no difference other than if I toggle off the control in Fan Control, and then it defaults to the Bios. When Bios is on Disabled, if the Fan Controls is turned off in this software then the fans go to 100%, as you would expect. But otherwise I can only get them running at 43.5%.

I don't get what changed

I haven't done a Bios update recently.
Asus Crosshair VIII Hero WiFi motherboard.

**Comment by jmarucha** [comment]
So you are in Asus territory. I had exactly the same thing with my update yesterday. I don't know what changed, maybe @Rem0o  can say if there is a significant difference in LibreHardwareMonitor.

But I found how to get rid of the issue, at least for me

Please check if there is "AsusFanControl" service running (last tab of task manager). If it is running stop it, restart FanControl and take a look if it now works.

For me that was that.

Now get rid of this nasty piece forever. Click "Open Services", find this AsusFanControl thingy, go to properties, set Startup Type to Disabled.

Let me know if it works.

**Comment by WanaGo** [comment]
The weird thing is Argus Monitor controls it totally fine, but FanControl no longer does. 
No - I am not running both at the same time.
FanControl is just stuck at 43.5%, while Argus is happily doing the full range, based on the same sensor input.

@jmarucha I will check the AsusFanControl service, but its totally weird for this to only become an issue now, drivers etc have been installed since mid last year and have not changed, it only seems to have changed with this update - unless it changed the update before, and I didn't notice..... @Rem0o

**Comment by WanaGo** [comment]
> Please check if there is "AsusFanControl" service running (last tab of task manager). If it is running stop it, restart FanControl and take a look if it now works.

@jmarucha No AsusFanControl service running on my system.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V113 updated the backend library.

But looking at your curves, you use a weirdly configured auto fan curve setup.
All your curve are outputting 43.5, which is what your fans are at.  From what I can see on the screenshot, it works as expected. Maybe the "auto" fan curve is not what you should be using?

**Comment by WanaGo** [comment]
Weird as the Beta Auto curves is what I have always used, and seemed to work great... hmm.

I have changed them to Linear for now, and they certainly are different now.

So what is the Beta Auto actually doing, and why would it always be on 43.5 with that, no matter what the other settings are - as I am sure that never use to be the case...

![image](https://user-images.githubusercontent.com/759846/169172988-371c2417-b9b1-4d6d-ad30-dffa562f1652.png)

**Comment by Rem0o** [comment]
that 43 % was 25% the range up from minimum speed because you were still above idle temperature. It will only go to minimum if at or below idle temp from a load situation. Make sure the idle temp is reachable.

**Comment by cjwijtmans** [comment]
sometimes some of my fans are stuck on 0 even though all my fans are on mix curve and one fan is working fine. All of them are above start %.
