### ISSUE TITLE
Donation from Singapore is not supported 

### ISSUE THREAD

**Issue by vincentzz** [Rem0o/FanControl.Releases#802]
Trying to buy the author a cup of coffee but failed on payment via Paypal. I don't know if it's a bug or not?
Is there any plan to support donation from Singapore in the furture?

![image](https://user-images.githubusercontent.com/6860913/169202681-dfbc2efb-9ea0-432e-a3bd-14bc72861c45.png)

**Comment by Rem0o** [comment]
You can use my github sponsor page. Look for 
![image](https://user-images.githubusercontent.com/14118956/169382583-d14647fe-dbb8-44a0-b646-ae3de92cc197.png)

You can go through the official github sponsor stuff, which has 1 time donation and supports more payment system I believe.

**Comment by vincentzz** [comment]
Enjoy your coffee ;)
