### ISSUE TITLE
Program fails after hibernate / sleep.

### ISSUE THREAD

**Issue by diebobo** [Rem0o/FanControl.Releases#805]
Hi,

After my system wake's up again about 50% of the time FanControl does not work anymore. The picto is showing in the Icon tray, bu when clicked the program just vanishes and its gone. Also there is no fan control anymore ( temps rise and rise ). Not sure since what version i have this but at least some versions, hoped it worked better with the current release. That didn't happen that's why i am posting now..

When it does work it is briliant, so thumbs up for that :-)

**Comment by Rem0o** [comment]
There is a built-in delay when waking from sleep before your system is redetected. That's intended.  It should restore your config after a few seconds.

Does it crash? Any log.txt?

**Comment by diebobo** [comment]
The program does not crash, as in big error warning. The fan icon is showing but when i hoover my mouse on top is just disappears and that's it.. Its not right after wake up the computer when it happens.. Sometimes hours later when i found out when i play a game and my GFX are hot, i check for FanControl and then the icon is there but when pointing the mouse on it just disappears..

For now i changed the properties of the program to run as admin, see if that makes any change.

There is no log.txt created and i don't have any plugins installed / using..  Windows 10 up 2 date...
