### ISSUE TITLE
Weird issue with rpm display for cooler master 120mm sickleflow pwm in an msi z97 gaming 3 board

### ISSUE THREAD

**Issue by moezlam** [Rem0o/FanControl.Releases#809]
- so i have an issue regarding the display of rpm speed for 3 pwm fans i have
- the fans are cooler master sickleflow 120mm
- msi z97 gaming 3 motherboard the fans are working the pwm fan headers too 
- in FanControl it display zero rpm untill it reach 50+%
- in HWmonitor same issue it doesnt even show there's any fan at all untill they are around 1080rp
![1](https://user-images.githubusercontent.com/105930345/169555869-d555ef6c-cc36-434b-909d-3cafd791ad8e.jpg)
![2](https://user-images.githubusercontent.com/105930345/169555895-684cd1d8-4ffe-4c62-84f7-91165570dbea.jpg)
![3](https://user-images.githubusercontent.com/105930345/169555915-b2fb8539-dc5c-4b33-a425-08c9346d5e40.jpg)
![4](https://user-images.githubusercontent.com/105930345/169555940-30ba38cb-ec0a-4425-9c81-1c35cd51cadf.jpg)
![5](https://user-images.githubusercontent.com/105930345/169555960-cc149e71-8a42-450f-bdda-9ab7be9696d2.jpg)
 thanks for any and every answer and interaction about this weird issue i just want to understand what's going on is it specific to this fans model or is it normal

**Comment by Rem0o** [comment]
Expand your control card with the little arrow. What start% is set?

**Comment by moezlam** [comment]
> Expand your control card with the little arrow. What start and stop % is set?

all my fans are set to 0% but if you meant what's the threashold on when the fans start and stop i remember it was something around 52% im assuming it's voltage thing

**Comment by Rem0o** [comment]
Soooooo there isn't any problem then? If your fans need 52% power to start up, it's normal you get 0 rpm until you get there?

**Comment by moezlam** [comment]
> Soooooo there isn't any problem then? If your fans need 52% power to start up, it's normal you get 0 rpm until you get there?

- the fans works starting at 25% but the rpm display 0%
- the rpm start showing actual speed when it reaches 52%=1080rpm
- same problem in HWmonitor that's why i wanted to check if it's maybe an issue with this particular model of fans i have

**Comment by Rem0o** [comment]
If you get the same behavior in HWMonitor, I guess it's not a specific implementation problem of the software, more of a weird edge case associated with your specific setup.

**Comment by moezlam** [comment]
> If you get the same behavior in HWMonitor, I guess it's not a specific implementation problem of the software, more of a weird edge case associated with your specific setup.

that's exactly what i assumed after trying to figure out what's wrong with the rpm speed display maybe you should set a pull for the same issue and let guys put the brand and model of their fans doing the same stuff and later when you get enough data run a comparison and try to understand what's the common denominator with it maybe it's a voltage thing or maybe it's something related to cooler master specifically of who know anyway thanx for your work bro have a great day

**Comment by moezlam** [comment]
> If you get the same behavior in HWMonitor, I guess it's not a specific implementation problem of the software, more of a weird edge case associated with your specific setup.

i found a solution somehow to display rpm lower then 52% but only using the cpu fan2 header with a splitter so i just plugged my two intake fans on it and im somehow relieved lol
![1](https://user-images.githubusercontent.com/105930345/169700846-873c7546-e2c9-4dc8-9a50-dd9495eea193.jpg)
![2](https://user-images.githubusercontent.com/105930345/169700851-e051844c-54d5-41d4-ac6a-eb29b53b7ef7.jpg)

**Comment by Rem0o** [comment]
Good, will close.
