### ISSUE TITLE
HDD noise when running the app

### ISSUE THREAD

**Issue by andriuspetrauskis** [Rem0o/FanControl.Releases#812]
I have a Toshiba MG08ACA16TE and it works fine. Just when starting the fan control app, the HDD starts to make this noise every 5~6 seconds and it continues all the time when the app is running. The HDD makes that sound on its own when starting the PC and it is detecting devices but then noise stops and is never heard.

Maybe app sends some sort of signal to the hdd every 5~6 seconds or something? 

You can listen to the sound here: https://soundcloud.com/user-897646141/hdd-sound

**Comment by Rem0o** [comment]
Untick the HDD detection in sensor settings.

**Comment by andriuspetrauskis** [comment]
Tried it. That didn't helped. After it I tried to remove other sensors as well. Once I removed all of the sensors and restarted it stopped! Then I started to add all of the sensors one by one. So all of the sensors were enabled and there were no sound. Great! Of course, disabling sensors removed all of my fan controls. Then I started to re-setup fan controls and as soon as I enabled the GPU control, HDD sound started appearing again... 

Can this be related to the fact that HDD is attached to a specific SATA controller that is attached to PCI?

**Comment by Rem0o** [comment]
> Then I started to re-setup fan controls and as soon as I enabled the GPU control, HDD sound started appearing again...

> Can this be related to the fact that HDD is attached to a specific SATA controller that is attached to PCI?

That's... odd to say the least. Never seen something like this before.

**Comment by andriuspetrauskis** [comment]
I'll try next day to reconnect that HDD to onboard SATA port and see if the problem still remains.
