### ISSUE TITLE
Feature Request: Ability to click on plot points without moving it

### ISSUE THREAD

**Issue by chorong761** [Rem0o/FanControl.Releases#814]
Currently when you click on the plot points on the fan graphs, it would move it. It would be nice if it could be clicked and not move, so the plot could be edited manually by inputting manual percentages without it moving around changing the percentage/temps.

**Comment by xhul-dev** [comment]
Hello there.
You can already edit the points without altering them.
You just need to hover on them with the mouse, without clicking.
Not sure if it's ideal, but at least it can be done.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/169854284-a1a025ac-3b79-426f-8b93-2664fc2fc230.png)

**Comment by chorong761** [comment]
Oh I didn't notice that, Thanks
