### ISSUE TITLE
AIO fans not detected

### ISSUE THREAD

**Issue by wistfulglen** [Rem0o/FanControl.Releases#819]
My two AIO fans don't get detected at all, despite me being able to control them from Corsair iCUE. Any idea as to why?

The AIO pump gets detected, but it seems like it isn't connected properly between the speeds tab and controls tab, seeing as the controls tab won't display percentage or RPM, but the speeds tab does display RPM.

**Comment by Rem0o** [comment]
What are they connected to?

**Comment by wistfulglen** [comment]
> What are they connected to? If it's to the pump unit, then that's normal, FanControl doesn't interface Corsair AIOs.

Yeah, they're connected to a fan connector that comes off of the pump head. The pump head is then connected to the CPU_FAN slot.

Is there a way for me to have FanControl interface them? Could I connect the AIO fans to a fan hub or another fan/pump header on the motherboard? I'm new to PC building still, so fans and fan control is something I still have to figure out fully.

**Comment by Rem0o** [comment]
Sure, you could connect the fans to a motherboard header, which FanControl should pickup
