### ISSUE TITLE
FanControl set all fans to 0% when loading a configuration

### ISSUE THREAD

**Issue by drauh** [Rem0o/FanControl.Releases#82]
Hello,

Great tool ! However, every time it load a configuration (thus also when starting), it set all fans to 0 (instantly, which is not good for them). There is no error loggged.

Thanks for your help,

**Comment by Rem0o** [comment]
To 0 or 100? Your title and text conflict each other.

**Comment by drauh** [comment]
To 0 percent, i'm sorry for the typo, i fixed the title.

**Comment by drauh** [comment]
I can provide any information you need, screenshots, configuration etc... (It's doing that for any configuration i make, even with everything deactivated)

**Comment by Rem0o** [comment]
I think I can see how that would happen, will patch.

**Comment by drauh** [comment]
Great, glad to hear it, I'm ready to do some testing if you need it,

Thanks you for your work,

**Comment by Rem0o** [comment]
Fixed in https://github.com/Rem0o/FanControl.Releases/releases/tag/V59

**Comment by drauh** [comment]
I can confirm this. Thanks a lot, perfect piece of software for my use now !
