### ISSUE TITLE
Feature Request: Hysteresis on all Curves

### ISSUE THREAD

**Issue by Wolphin5** [Rem0o/FanControl.Releases#820]
I like to delay turning down the fans after the system starts to cool down, and can turn them on the Graph and Linear Curves, but doesn't exist on the Mix, Target, Sync, or Auto (Nor Flat, but that one doesn't change).

**Comment by Rem0o** [comment]
Doesn't make sense on the mix, it has no temperature. Same for sync. Auto has deadband.
