### ISSUE TITLE
RX 6750 XT

### ISSUE THREAD

**Issue by oXyiGYJ** [Rem0o/FanControl.Releases#821]
I know this is probably in the works, but on 115 if I try and change the fan speed in any way on my RX 6750 XT, it does not change the fan speed on the card (and reflect so in the percentage and RPM).

If this is a known issue, I apologize. Tried searching for the 6750 XT and did not get any results.

**Comment by Rem0o** [comment]
As of right now, newer AMD gpu's fan control isn't working. Known issue, but no fix yet.

**Comment by SAJewers** [comment]
Yeah, looks like an issue with the latest AMD 22.5.2 drivers
https://www.reddit.com/r/Amd/comments/uw9hai/comment/i9qp45f/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by Fishman2294** [comment]
has anyone tried to downgrade off 22.5.2

**Comment by Aklugua** [comment]
Same issue with RX 5700 XT under AMD 22.5.1 driver, haven't tried with downgrade yet. Awesome work by Rem0o though 💯

**Comment by MeeniMc** [comment]
Same issue with AMD 22.5.1 (rx580), I had to rollback to 22.4.2 (and use the AMD cleanup utility, wouldn't work with simple restart).

**Comment by Fishman2294** [comment]
> 

Can you show me how you did all of it

**Comment by SAJewers** [comment]
AMD 22.6.1 drivers just dropped, and it seems to have fixed this.

**Comment by oXyiGYJ** [comment]
I can confirm I can do this with Adrenaline, but it still does not respond to Fan Control. Running V119.

**Comment by fartwhif** [comment]
GPU control wasn't working with my RX 6950 XT

https://github.com/Rem0o/FanControl.Releases/issues/1647#issue-1638138925

in there someone mentions the fancontrol plugin https://github.com/Rem0o/FanControl.ADLX

sensor layout: motherboard, CPU, ADLX, ran assisted setup, and now it works.

**Comment by MeeniMc** [comment]
That issue has been resolved for years now it works as intended with no special plugins.

**Comment by fartwhif** [comment]
> That issue has been resolved for years now it works as intended with no special plugins.

seems it's unresolved again.

**Comment by tmdarlan** [comment]
> That issue has been resolved for years now it works as intended with no special plugins.

is there something we have to do to make this work. mine has never worked.
