### ISSUE TITLE
Fan Control not Working After Pc Sleep Mode

### ISSUE THREAD

**Issue by Audipower** [Rem0o/FanControl.Releases#823]
Hello 
First i will say Fan Control is Great Software Thanks for That

But i Have 1 Problem afer the Pc goes to Sleep the Controls of the Onboard Fans Stop Working
CPU Fan and Fan 2 for the Case fans. Fan 2 ist Extended to a  Fan Hub ( Aero Cool P7 - S1 ). This Device Use the PWM Signal from Fan 2 
( Asus Prime B350 - Plus ) and distribute the PWM Signal to the 5 Fans in the Case. All This Works Fine after a Pc restart.
Only after Sleep the Control does Nothing restart the Software dosent Help only Pc Restart 

I Have no Errors in the Log and i use Win 10 Pro 
Thanks for your Help and Great Work from Germany

**Comment by Rem0o** [comment]
What kind of sleep? S0? S1? S2?

**Comment by NatasKrad** [comment]
Similar issue here after sleep. (S4)
I get the attached LibreHardwareMonitor error after coming out of sleep.
Thanks

![Fan Control Error](https://user-images.githubusercontent.com/106728282/171568704-f0304ea4-6e0a-400e-9c88-937b3e46764c.jpg)

**Comment by Rem0o** [comment]
@NatasKrad  In your case, it failed once, retried, and succeeded, since the control cards are there. The popup is the first time it failed.

**Comment by Audipower** [comment]
Its S4 
As i Said i have no Error or Something 
it Looks like Fan Control works Fine but it Makes no Changes and the Control from the Mainbord  is Working. 
I can see it on the data from the CPU Fan Mainbord minimum is 600~ RPM when Fan Control Works it gets down to 320~ RPM

**Comment by NatasKrad** [comment]
@Rem0o Thanks for the reply.
So is it safe to ignore?

**Comment by Rem0o** [comment]
Added a multi-retry mechanism since, until all sensors are back.

**Comment by otDan** [comment]
it seems that this is still an issue with the latest version, it fails, loads in the cards for the fans but the sensors are not updating and the fans aren't controlled by fan control anymore.
trying to refresh the sensors just makes it refresh indefinitely, restarting the app doesn't work either even if I close the process and start up a new one, to make it work again I have to reboot

**Comment by FireDragon761138** [comment]
I have the same problem.  Fan Control fails to control the fans after waking from sleep.

**Comment by RevGemmy** [comment]
Same issue still. I'm hoping to find a fix since restarting my computer to get fancontrol working is annoying

**Comment by Seppideluxe** [comment]
Same issue still.

**Comment by Drbob21** [comment]
Same issue here. Sleeping for a long period of time causes the sensors to be missing when waking.

**Comment by MonkeysForSimon** [comment]
Yes, same issue still.

**Comment by Charlye71** [comment]
Same issue here. I receive the errors in the screenshot after exiting sleeping mode.
![fancontrol](https://github.com/user-attachments/assets/323f5491-ed5c-4399-bfcf-1b50e834703f)
Increasing startup delay doesn't help.
