### ISSUE TITLE
Asus Motherboard Fans wont stop to 0 RPM

### ISSUE THREAD

**Issue by networkneil** [Rem0o/FanControl.Releases#825]
Hello, 

Is there any way or a plugin that we can use to make the PWM fans go all the way to 0 RPM. 

Thanks in advance. :)

**Comment by Rem0o** [comment]
Nop. Some motherboard in PWM mode just don't want to go 0 rpm.

**Comment by Wolphin5** [comment]
PWM fans have a constant 12V to them.  They take the digital Pulse-Width Modulated signal and using circuitry on the fan turn it into the control of the fan speed.  If you look at the specs of the fan, the minimum is likely not 0, which means the fans will never actually stop, as long as there is 12V power provided to them.  (My Lian Li AL120s are like that...)

**Comment by networkneil** [comment]
Understood. But I’m curious because the Asus AI Suite software (really bad software btw) was able to turn all fans down to 0 rpm. 

May be we don’t have something Asus has to control the fans down to 0.

**Comment by Wolphin5** [comment]
I expect that it turns off the 12V when it does 0.  But it's the manufacture's software, so is likely doing something strange.

**Comment by everdrone** [comment]
I'm having the same issue
Also the fan sensors always show 0 rpm no matter what

<img width="551" alt="image" src="https://user-images.githubusercontent.com/22671061/212450730-efb27ae6-07d8-4dee-9b1a-46d56b531c70.png">

Motherboard: ASUS ROG Crosshair X670E Hero
