### ISSUE TITLE
Can't edit "graph" fan curves

### ISSUE THREAD

**Issue by Merve147** [Rem0o/FanControl.Releases#826]
When clicking the edit button on "graph" fan curves the popup does not show up. Clicking the tray icon in the tab and clicking "exit" did not close the app. After manually exiting through Task Manager and starting up the app again, the same issue occurred.

**Comment by xhul-dev** [comment]
Hello there.
I don't have any solution to suggest.
However, for the record, that guy had a similar issue: https://github.com/Rem0o/FanControl.Releases/issues/685

**Comment by Rem0o** [comment]
any log.txt?

**Comment by Merve147** [comment]
I looked through issue 685 and tried some fixes but it didn't work. I have now included the log
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8782345/log.txt)

**Comment by Rem0o** [comment]
Seems like the program got stuck in some weird state with the graph dialog. Have you tried to restart the app?

**Comment by Merve147** [comment]
I have restarted the app multiple times and even rebooted but nothing changes. i updated from 115 to 116 and still have the same issue.

**Comment by Rem0o** [comment]
Other theory: Somehow, you got a graph saved with an invalid state in your json file.

**Comment by xhul-dev** [comment]
You could start Windows in safe mode and try on a brand new copy of fan control there.
That would allow to know if something in memory interferes with those functionalities.

**Comment by Merve147** [comment]
Somehow it fixed itself. I did close razer synapse in the system tray and then restarted though so that might have been the culprit. Anyway, i thank you guys for your help!
