### ISSUE TITLE
WinRing0x64.sys driver installation issue

### ISSUE THREAD

**Issue by ciukacz** [Rem0o/FanControl.Releases#828]
Hello,

First of all thank you for this software, I love it! I can now get rid of AI Suite :)
One issue I've noticed is that FanControl installs a renamed WinRing0x64.sys driver as FanControl.sys.
When other software (like OpenRGB) wants to install a "shared" WinRing0x64 driver in c:\Windows\System32\drivers\ it fails because that exact same driver (but just renamed) is already registered as FanControl.sys.
Then any attempt to start WinRing0x64 service return WIN32 API error 0xB7 (Cannot create a file when that file already exists).
Can you make use of a "shared" driver in c:\Windows\System32\drivers\ (with the original name) so that it won't clash?

Regards

**Comment by Rem0o** [comment]
Yes that's one thing I noticed that might conflict at some point. Would require a change here though: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.  If you can submit a PR there, would help a lot.

**Comment by ciukacz** [comment]
Yup, excerpts from their code:

Ring0.cs:
_driver = new KernelDriver(GetServiceName(), "WinRing0_1_2_0");

        private static string GetServiceName()
        {
                ProcessModule processModule = Process.GetCurrentProcess().MainModule;
                name = Path.GetFileNameWithoutExtension(processModule.FileName);

            static string GetName(string name)
            {
                return $"R0{name}".Replace(" ", string.Empty).Replace(".", "_");
            }
        }

Will try asking there

**Comment by Rem0o** [comment]
Maybe they want to keep it "portable" to be able to kill it once the process die.

**Comment by ciukacz** [comment]
They do exactly that, but the thing is they are using a "shared" name for a device driver id with a changed service name.
Maaaaybe they could be convinced to try to detect a "shared" WinRing0 kernel drive already installed (identified for example by code signing certificate thumbprint?) and use that as a special case instead of loading their own dynamically.
