### ISSUE TITLE
Autorunning FanControl

### ISSUE THREAD

**Issue by mcharsley2** [Rem0o/FanControl.Releases#830]
I typically run Windows as a limited user. I can happily run FanControl manually, with no problems. However, I'd like it to start automatically with Windows, or at least when I log on. I've so far tried
 - ticking the Start with WIndows control within FanControl
 - adding FanControl to the list of Startup Apps in Windows Settings

Neither has worked. My guess is that it's due to some combination of
 - running as a Limited User
 - having to confirm that I want to let an app from an untrusted publisher make changes to my device (when I run it manually)
 - it presumably needing to run with admin privileges

Any advice?

thanks

**Comment by Audipower** [comment]
Have you Tried Windows Task Scheduler ? 
https://www.howtogeek.com/123393/how-to-automatically-run-programs-and-set-reminders-with-the-windows-task-scheduler/

with this Windows Tool you can Start Every program on Login with Admin Rights and more. You can find Plenty of How to with Google 

Sorry English is not my Main Language

**Comment by xhul-dev** [comment]
Hello there.
Try that: https://github.com/xhul-dev/FanControl-WinStart

**Comment by mcharsley2** [comment]
https://github.com/xhul-dev/FanControl-WinStart (which is a simple wrapper around task scheduler) almost did the trick. Need the "run whether user is logged in or not" option enabled for the task to work.

thanks all

**Comment by mareking** [comment]
> Hello there. Try that: https://github.com/xhul-dev/FanControl-WinStart

Hi xhul-dev,
your repo is gone! Can you upload it again?
Thank you :)
