### ISSUE TITLE
Controls: CPU FAN Speed

### ISSUE THREAD

**Issue by Spuner** [Rem0o/FanControl.Releases#831]
I do not know why, but it does not show the speed of the CPU fans. As you can see in the screenshot, the video card is fine. Is there any way to fix this?

Fan Control V116. (previous versions did not show fans speed either.)

![2](https://user-images.githubusercontent.com/30773815/170828854-bd957bec-37fb-435b-a711-ad8812f09de2.png)

**Comment by Audipower** [comment]
Have you Pair  Controls / Processor  with Speeds / Processor ?

Click on Controls/ Processor and then (Pair Speed Sensor ) then Click on Speeds/Processor (The Fan Icon ) and then it should work

**Comment by Spuner** [comment]
> Have you Pair Controls / Processor with Speeds / Processor ?
> 
> Click on Controls/ Processor and then (Pair Speed Sensor ) then Click on Speeds/Processor (The Fan Icon ) and then it should work

Everything is working. Thank you very much.

**Comment by Spuner** [comment]
> Have you Pair Controls / Processor with Speeds / Processor ?
> 
> Click on Controls/ Processor and then (Pair Speed Sensor ) then Click on Speeds/Processor (The Fan Icon ) and then it should work

Everything is working. Thank you very much.
