### ISSUE TITLE
Fan Control keep showing pop-up for donation and assisted setup

### ISSUE THREAD

**Issue by Optimus-Bull** [Rem0o/FanControl.Releases#834]
I don't know if this issue has been reported, but I thought I should lay it out here just in case.

I keep getting the pop-up about considering giving a donation even after checking "don't show this pop-up in the future"

And it keep giving me a pop-up prompting me to do the assisted setup even after I have done the whole setup and configured everything to how I want it to be.

This happens when rebooting the PC and when you shut it down for the night and boot it back up the next day.

**Comment by kogosa** [comment]
I face the exact same issue with latest v116. This was not happening with older versions.

**Comment by DuMichAuch72** [comment]
Same here...

**Comment by Audipower** [comment]
Now i have the Same bug i change Nothing but now after restart every Time Donation POp up and then the Setup Windows but everything is set and work

**Comment by kogosa** [comment]
It's just a bug on latest v116 i guess, cause i reverted back to v115 and it doesn't happen.

**Comment by Rem0o** [comment]
Yup, should be fixed for everybody on 117.
