### ISSUE TITLE
Fan control keeps breaking

### ISSUE THREAD

**Issue by DuckersMcQuack** [Rem0o/FanControl.Releases#835]
It especially breaks when i try to control the south bridge fan on my x570 taichi, and broke now when i tried to adjust cpu fans from fractal R6 fan controller connected to cpu fan header.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8794167/log.txt)

**Comment by Rem0o** [comment]
You are somehow doing something specific with the graph editor that breaks it.  Exiting the app and reopening it should work. If you could provide some steps to reproduce the glitch, would help a lot.
