### ISSUE TITLE
Fan speed goes below minimum speed

### ISSUE THREAD

**Issue by LeadFreeCandy** [Rem0o/FanControl.Releases#84]
![image](https://user-images.githubusercontent.com/39067807/100911361-f888b100-3483-11eb-9fef-c34a52ff658b.png)
Fan speed should be zero, but it is going below what it should be.

**Comment by LeadFreeCandy** [comment]
The fix is to set the start % back to 0%, then back to whatever it was before. Force quitting and restarting does not fix.

**Comment by Rem0o** [comment]
Where you actively changing your start % for this exact state to happen in the screenshot.

**Comment by LeadFreeCandy** [comment]
No, I always leave it at 30% and it seems to bug maybe on startup?

**Comment by Rem0o** [comment]
Probably an initial state problem at startup yes, will investiguate.

**Comment by LeadFreeCandy** [comment]
It fluctuates +-5% around 25%, which is strange because it's not even following the curves that it was given. You can see that I am taking the max of those two curves, and yet it is doing 25% when it should be doing 29%, that is if I didn't have the minimum speed set.

**Comment by LeadFreeCandy** [comment]
It's not doing it atm, but I can try to give you more info when it happens again. Thanks for taking a look

**Comment by Rem0o** [comment]
I believe this is the exact same thing as https://github.com/Rem0o/FanControl.Releases/issues/85, which will be fixed.

**Comment by Rem0o** [comment]
Fixed in https://github.com/Rem0o/FanControl.Releases/releases/tag/V59
