### ISSUE TITLE
Trojan detected in latest update

### ISSUE THREAD

**Issue by bearlygeek** [Rem0o/FanControl.Releases#840]
Well, currently doing a full system scan after the latest pushed update seems to have had something else with it - "Trojan:Win32/Wacatac.B!ml" - windows defender stopped the install before and nuked it. Have since removed all traces of the program.

**Comment by trankillity** [comment]
Also saw this, unsure if false positive or if @Rem0o has been infected and has distributed it.

**Comment by Rem0o** [comment]
Same stuff pops up every few weeks/months.

See https://github.com/Rem0o/FanControl.Releases/issues/719

**Comment by bearlygeek** [comment]
> Also saw this, unsure if false positive or if @Rem0o has been infected and has distributed it.

I didn't want to take any chances, and thought I should bring it up.

**Comment by bearlygeek** [comment]
> Same stuff pops up every few weeks/months.
> 
> It's a false positive, as usual.
> 
> See #719

Ok thank you :)
