### ISSUE TITLE
Fan Control Initialization Failed

### ISSUE THREAD

**Issue by mooreman234** [Rem0o/FanControl.Releases#844]
The Fan Control has worked fine for the past 8 weeks. I sent you a payment of $20.00 after the last update fixed an issue of the 2 case fans being uncontrolable. After waking Win10 up I have to manually launch the fan program, not a big deal. On May 30 it would not initialize per the Windows error screen. I deleted the program files, downloaded the latest version, unzipped into an empty folder and it won't open in Win10 Pro 64-bit. BTW my Win10 is stuck at 21H1 and crashes every time it tries to update past that. Renders my PC unbootable after each attempt. Since a major update last July the CPU fan only runs at idle speed. This causes my CPU to overheat. Prior to that update it was stuck at full speed and sounded like a hair dryer running. Windows 10 I believe is not virtualizing my older BIOS properly, at least the fan control part. Your program was a good band aid fix to force speed-up of the CPU fan and two case fans to prevent overheating. I am retired and can't afford a newer system. I built this one in 2015.

System Info:
Processor	 AMD FX-8350  
Installed RAM	16.0 GB
Item type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Pro
Version	21H1
Installed on	‎2/‎12/‎2022 (Updated manually).
OS build	19043.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

Motherboard:
Manufacturer	Gigabyte Technology Co. Ltd.
Model	990FXA-UD3
Version	x.x
Chipset Vendor	AMD
Chipset Model	RD9x0
Chipset Revision	02
Southbridge Vendor	AMD
Southbridge Model	SB910/950
Southbridge Revision	40
System Temperature	88 °F
	BIOS
		Brand	American Megatrends Inc.
		Version	F3 (No updates available from Gigabyte).
		Date	5/28/2015
Cores	8
Threads	8
Name	AMD FX-8350
Code Name	Vishera
Package	Socket AM3+ (942)
Technology	32nm
Specification	AMD FX-8350 Eight-Core Processor
Family	F
Extended Family	15
Model	2
Extended Model	2
Stepping	0
Revision	OR-C0
Instructions	MMX (+), SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, SSE4A, AMD 64, NX, VMX, AES, AVX, FMA3, FMA4
Virtualization	Supported, Disabled
Hyperthreading	Not supported
CPU  Fan Speed	2556 RPM
Rated Bus Speed	2611.5 MHz
Stock Core Speed	4000 MHz
Stock Bus Speed	200 MHz
Average Temperature	66 °F (Not accurate) My room temp is around 72°F. so not possible.

Here is the log.txt file.
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8812149/log.txt)

**Comment by Rem0o** [comment]
FanControl is stuck at initializing your hard drive detection. You should remove the storage detection:
![image](https://user-images.githubusercontent.com/14118956/171408247-5adbe1fc-a67f-4221-9710-ffc87a1f8e5c.png)

**Comment by lwk123qq** [comment]
> FanControl is stuck at initializing your hard drive detection. You should remove the storage detection: ![image](https://user-images.githubusercontent.com/14118956/171408247-5adbe1fc-a67f-4221-9710-ffc87a1f8e5c.png)

Ver118 , win 11
find a problem almost like that,
run exe,alert no tip,when I change guide mode(nsconfig),enter the safeMode ，
I get a alertView about 
“exception processing Message 0xc0000005 - Unexpected parameters”,

btw,能 中文交流吗。。。 好累
