### ISSUE TITLE
Curves randomly disappearing after some time

### ISSUE THREAD

**Issue by Mineplayerminer** [Rem0o/FanControl.Releases#845]
I noticed that my set curves for my GPU and chassis fans went missing. (That's why I was getting 90°C on my GPU while in the game)
![image](https://user-images.githubusercontent.com/82465758/171670923-1f5a0209-477b-48ab-98b1-6c3f34e4a354.png)
I had to set them back manually. It didn't set back from the config after restarting the Fan Control.
When the Curves were set to None, they were controlled by the default BIOS set fan curves. The GPU fans are connected to the motherboard instead of the GPU's fan connector. (There was no PWM control on the GPU's fan header)

It happened again while I was writing this.

I noticed this issue since V111 was released. I had no problems with the V109.

**Comment by Rem0o** [comment]
Can you try and elaborate steps to reproduce this?

**Comment by Mineplayerminer** [comment]
> Can you try and elaborate steps to reproduce this?

I start the Fan Control as normal every time my PC boots. It automatically loads the configs. Everything works as usual. After "9 hours" of PC being idle or downloading some stuff, I noticed the curves I've set in the Controls were set to _None_ for some reason.

My solution: assign the curves back or load the config again.

It's been the 3rd time I noticed that the Curves were gone.
I can put here my configs if needed. This started happening since the update. I don't think it's because I've set my fans as PWM in the BIOS settings. (As Gigabyte has a weird glitch that the system freezes for a second every few minutes, I think the cause is that it checks the fan control type whether it's a DC or a PWM speed control)
[Quiet.json.txt](https://github.com/Rem0o/FanControl.Releases/files/8835357/Quiet.json.txt)

The "Back" and "Front" didn't have any Curve assigned. Same for the "GPU", it happened only one time, when my card almost melted along with its Low Profile heatsink. Poor GTX 1650 😭.
![image](https://user-images.githubusercontent.com/82465758/171941291-26be614c-2850-4f7e-b678-f2072a5efadd.png)

**Comment by Rem0o** [comment]
> After "9 hours" of PC being idle or downloading some stuff, I noticed the curves I've set in the Controls were set to None for some reason.

That's not really what I meant for "steps to reproduce" 😅.  I meant steps I can do myself and try to get the same issue locally. There is nothing wrong or weird about your config. By the way, the curves gets cleared off WHILE fancontrol is running in the backgroup? No sleep?

Do you have a log.txt file?

**Comment by Mineplayerminer** [comment]
> > After "9 hours" of PC being idle or downloading some stuff, I noticed the curves I've set in the Controls were set to None for some reason.
> 
> That's not really what I meant for "steps to reproduce" 😅. I meant steps I can do myself and try to get the same issue locally. There is nothing wrong or weird about your config. By the way, the curves gets cleared off WHILE fancontrol is running in the backgroup? No sleep?
> 
> Do you have a log.txt file?

I have the Fan Control in the Program Files, but the Read/Write works as normal. Here is the image after running my PC for 10 hours today. I just noticed the Curves have disappeared.
![image](https://user-images.githubusercontent.com/82465758/172203605-8750c169-f42a-404a-81ad-46f7603b3d84.png)

**Comment by Rem0o** [comment]
I know the effect.   What I want is stuff to help me diagnose the cause of the problem. Same 2 questions:

1) Do you have a log.txt file in your fan control directory that you can share here.
2) During that 9h/10h, does your computer goes to sleep/wake?

**Comment by Mineplayerminer** [comment]
> I know the effect. What I want is stuff to help me diagnose the cause of the problem. Same 2 questions:
> 
> 1. Do you have a log.txt file in your fan control directory that you can share here.
> 2. During that 9h/10h, does your computer goes to sleep/wake?
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8846246/log.txt)

1. the log file
2. No, my motherboard doesn't even support the sleep function. It's just idle at a locked screen (Win + L)

**Comment by Mineplayerminer** [comment]
![image](https://user-images.githubusercontent.com/82465758/176681426-f3e544e3-804d-4763-b7c6-c0142d29fce6.png)
After updating to the V119, it started happening again.

**Comment by Mineplayerminer** [comment]
Update: It's still happening even after putting the Fan Control folder somewhere else like on a desktop. Version 120.
![image](https://user-images.githubusercontent.com/82465758/181209062-8e6d518d-6352-4355-aa7f-047d00771dfe.png)

**Comment by Rem0o** [comment]
My guess is that it's the same issue as which has been fixed.

https://github.com/Rem0o/FanControl.Releases/issues/1008

**Comment by Mineplayerminer** [comment]
I hope so.

**Comment by d0verenny** [comment]
It was never fixed! It happens to me all the time!
