### ISSUE TITLE
GPU Fan speed sensor not recognized

### ISSUE THREAD

**Issue by NathanD38** [Rem0o/FanControl.Releases#846]
@Rem0o 

Thank you for creating and sharing an invaluable piece of software.
I've discovered your software through [JayzTwoCents](https://m.youtube.com/user/Jayztwocents),
and attempted to replicate his configuration setup for my poor man's PC.

I've donated to your project and I hope I'll be able to donate more in the future.

My computer has only one case fan, one cpu fan and a dual-fan gpu.
The specs are as follows:

Motherboard: MSI B450M PRO-VDH (Bios vM.G7 - 25/05/2022)
CPU: AMD Ryzen 5 2600 + stock cooler (running all cores at 3.6GHz)
PSU: Corsair VS 450W
RAM: G.SKILL Trident Z Neo (AMD Ryzen Compatible) 2 x 16GB DDR4 3200
GPU: Sapphire Radeon RX580 8GB GDDR5 PCI Express 3.0 x 16 1366MHz (Drivers: AMD Adrenalin Edition 22.5.2) 
Case: Thermaltake Versa H17 (1x120mm rear exhaust fan)
Boot Drive: Samsung 970 Evo Plus 1TB NVMe PCIe Gen 3.0x4 + some internal and external drives

I attach my current config file (changed to txt to enable upload) which includes some hidden fans 
that are recognized twice or incorrectly recognized.

The GPU Fan RPM did work before, but at some point when the computer restarted, the gpu fan speed stopped working.
I assume there was an error due to the default 30s delay. Now it's set to 120s, but it did not solve the problem.

The funny thing is that the GPU Curve I've set does follow the RPM percentage, but without showing the speed.
The GPU RPM is recognized in AMD software and in HWiNFO64:

![image](https://user-images.githubusercontent.com/84139569/171724013-ea0b9146-dbac-4749-8ee8-44519edb5b53.png)
![image](https://user-images.githubusercontent.com/84139569/171724228-aeb6bdfa-2dd6-472c-babe-c5d0bdb1e705.png)

I've tried to reset the software, but the fans are not recognized properly anymore, so I have to revert to the attached 
config file, at the cost of not having an rpm sensor for my GPU.

I'd love to know how to correct the issue.

Regards,
Nathan.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/8827225/log.txt)

[config.txt](https://github.com/Rem0o/FanControl.Releases/files/8827277/config.txt)

![image](https://user-images.githubusercontent.com/84139569/171719751-c7d50d6d-c977-4bd0-95c1-f83dcc97834a.png)

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/821

I think a driver is causing issue.

**Comment by NathanD38** [comment]
@Rem0o 
Thank you! 
That did the trick! 👍
