### ISSUE TITLE
Fan control sensors go missing after sleep

### ISSUE THREAD

**Issue by bfrancom22** [Rem0o/FanControl.Releases#847]
Hi @Rem0o, my whole pump not turning on issue has turned out to be fine, but now sometimes after the PC sleeps for a good few hours, fan control does not work. I open it, and it says every single speed sensor is missing. Then, I have to restart the whole PC.

**Comment by bfrancom22** [comment]
I did search and tried disabling my storage sensor. Let's see if that fixes it

**Comment by bluespresso** [comment]
There seems to be a general issue with sleep. The problem only occurs when my pc sleeps for a longer time, at least 30 minutes or so. Then on wakeup FanControl does not display any fans or curves. It is not responding and I cannot forcefully shut the application it down. During this hanging state the fans do spin (most likely the rpm before sleep) but rpm does not increase with load. So it is possible to overheat CPU or GPU. A restart is required to fix the hanging.

**Comment by bluespresso** [comment]
In the hanging state if I try to load up my config I get the attached error message.
![Fan_Control_Error_After_Sleep](https://user-images.githubusercontent.com/58310550/172544613-cf0a1f5d-b3fe-491a-b9a7-3be2d4988659.jpg)

In the mean time I found a workaround for me:
As I put my desktop PC into standby mode via a programmable button I am able to terminate FanControl using a small batch script (run as admin) first:
  taskkill /F /T /IM "FanControl.exe"
  powercfg -hibernate off
  rundll32.exe powrprof.dll,SetSuspendState 0,1,0

Startup FanControl via taskscheduler on return from sleep. The custom trigger for this is: Information, System, Power-Troubleshooter, ID: 1
The only downside is that the FanControl tray icon of the terminated instance does not disappear automatically as I have to terminate FanControl.exe forcefully. The takkill does not work without /F.

**Comment by bfrancom22** [comment]
@Rem0o I am continuing to have sensors go missing randomly about 1/10 times from sleep. I have a Z690 Carbon WiFi MSI board. Does this latest update potentially address these issues?

**Comment by bluespresso** [comment]
I had this issue 100% of the time if sleep duration was morge than 30 minutes. Now it seems to work.

**Comment by JasonHorkles** [comment]
I also have this problem after using hibernate. Perhaps something like #369 could fix the issue

**Comment by bluespresso** [comment]
are you already on version 118? Update 117 to 118 fixed this for me.

**Comment by apszika** [comment]
At simple start Windows I have this problem. Unfortunately no solution yet.

**Comment by Rem0o** [comment]
Made some major changes in the latest releases. Still an issue?
