### ISSUE TITLE
FanControl not working for case fans

### ISSUE THREAD

**Issue by ljsguitar33** [Rem0o/FanControl.Releases#848]
I was trying to use FanControl to control my case fans based on the temperature of my GPU while gaming. I am using an MSI MAG Tomahawk X570S mobo, Nvidia 3080 FE. When I downloaded FanControl and tried to set up my fans, it would tell me that an RPM sensors were not detected for my case fans, and it only detected my GPU fans.

My 4 case fans are connected to a splitter that is plugged into my SYS_FAN1 header on my mobo. So not sure why there are not being detected and can't change the speed.

One thing to note is that during the testing process, my case fans do turn off and then back on to their default speed but the software still says they were not detected. Any way to resolve this so I can control my case fans?

**Comment by Audipower** [comment]
Can you Control this Fans with the Mobo Settings in Bios ? Some Case fans are 1 Speed Only. Ans what Connection do ther Use 3 Pin DC Control or 4 Pin Pwm Control. And is the Mobo Controller set to the Right DC or PWM Control on SYS_Fan 1 corresponding to your Fans

**Comment by Rem0o** [comment]
@ljsguitar33  That's because since you got multiple fans on the same channel, the RPM detection is bust, so it can't rely on it. But it's not mandatory. If you can see your fans changing speed, then you're all good.

**Comment by ljsguitar33** [comment]
I can control the fans in bios. They use a 4 pin connection and they are set to PWM.

Sent from my iPhone

On Jun 3, 2022, at 7:13 AM, Audipower ***@***.***> wrote:

﻿

Can you Control this Fans with the Mobo Settings in Bios ? Some Case fans are 1 Speed Only. Ans what Connection do ther Use 3 Pin DC Control or 4 Pin Pwm Control. And is the Mobo Controller set to the Right DC or PWM Control on SYS_Fan 1 corresponding to your Fans

**Comment by ljsguitar33** [comment]
But I can’t control the fans in the software when the attempted connection is done.

Sent from my iPhone

On Jun 3, 2022, at 7:20 AM, Rem0o ***@***.***> wrote:

﻿

@ljsguitar33<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fljsguitar33&data=05%7C01%7C%7C6dfe42079cac49c300d808da455b6f71%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637898556253002803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iTBPB5myRpBdBS5DDmIXr0qo5EeBfJfO2jNFgelcNOs%3D&reserved=0> That's because since you got multiple fans on the same channel, the RPM detection is bust, so it can't rely on it. But it's not mandatory. If you can see your fans changing speed, then you're all good.

**Comment by ljsguitar33** [comment]
But how do I know which fan to assign the curve to? And is there any way to test which fan cars controls the case fans?

Sent from my iPhone

On Jun 3, 2022, at 12:41 PM, Rem0o ***@***.***> wrote:

﻿

But you mentioned the fans stopped during detection right? Don't bother with the speed cards with RPM, or any of the "detected" stuff from the assisted setup. Just assign a curve to the appropriate control, it should work.

**Comment by ljsguitar33** [comment]
So click on identify fans?

Sent from my iPhone

On Jun 3, 2022, at 3:36 PM, Rem0o ***@***.***> wrote:

﻿

Made a utility for that:
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F14118956%2F171948421-6a1feeac-f08e-4983-908b-790207d1f24e.png&data=05%7C01%7C%7C7b2cbf6288a8409ae90808da45a0ab4b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637898853621821651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G%2FWXS7T%2Fho8KaGxLGGDZYKIep6mH3SZeXc77ui1RPb0%3D&reserved=0>

Then watch your fans IRL as you slide each to figure out which is which.

**Comment by ljsguitar33** [comment]
I actually was able to get it to work and it works great except for one more issue. I put a custom fan curve for my GPU fans to go to 0% when below 37 C. But as you can see in the picture, the fans are running at 30% at 1000 RPMs when they should be off. Any fix for this?
![khjg](https://user-images.githubusercontent.com/106785030/172036779-454ddbc5-177b-477c-8468-c80025bc2463.jpg)

**Comment by ljsguitar33** [comment]
Are you there?

**Comment by Audipower** [comment]
No their is no fix some Mainbords don't let you set fans under a Minimum RPM and some fans do the Same. Some Fans set 100 % Speed when you turn off the RPM Signal off for Safty. And Other Fans can't Start when the  RPM is under 20 % - 30 %. Zero RPM works most for GPU and some Price Fans like Noctua. FanControl test the minimum RPM at the First Start.

And in ( Controls FanControl #4 )  their is no Speed Sensor Connected. Click on the 3 Dots and select Pair Speed Sensor then on the Fan Symbol from the Sensor that you will pair.

**Comment by ljsguitar33** [comment]
So you're saying that even though the GPU fans stopped running at a certain point before I ever used FanControl, now that I'm using FanControl they can't be turned off?

**Comment by ljsguitar33** [comment]
Are you still there?

**Comment by ljsguitar33** [comment]
Can someone please still answer my question?

**Comment by Rem0o** [comment]
@ljsguitar33  don't spam a thread for an answer.

FanControl is limited with specific GPUs in its control. Some Nvidia cards limit to 30% as a floor value.  You can still go below 30% with other softwares like afterburner.

**Comment by ljsguitar33** [comment]
So I can use Afterburner and FanControl in tandem at the same time? And well I didn't mean to spam but I was waiting for nearly 2 weeks for a follow up.

**Comment by Rem0o** [comment]
Yes you can.

**Comment by Rem0o** [comment]
There is a now an option in sensor settings for the 30%/0% override.
