### ISSUE TITLE
Dramatic drop of GPU clock and GPU memory clock frequency.

### ISSUE THREAD

**Issue by tiancaipipi110** [Rem0o/FanControl.Releases#849]
Hi, thanks for your repo. I just tried setting a flat curve for the GPU fans and it works great. However I noticed a dramatic drop of GPU clock and GPU memory clock. Uncheck the GPU fans' manual control can't seem to bring clock frequency back up. Is there a way to manage this more precisely or am I doing something wrong? 
![before](https://user-images.githubusercontent.com/35275506/171919925-4c8cd46e-8f7c-4424-a604-47cd0e06abfa.PNG)
![after](https://user-images.githubusercontent.com/35275506/171919942-a4ea4c74-d57d-4b40-a1a2-735cf8a04ef7.PNG)

**Comment by Rem0o** [comment]
I got no hands on any of that clock stuff. I suspect some cards have tight integration between clocks and fans, and if something else takes over, it default to lower clocks.
