### ISSUE TITLE
Cant Close or edit Fan Curves

### ISSUE THREAD

**Issue by Erik85** [Rem0o/FanControl.Releases#851]
After the first curve setup i cant close the software or edit the fan curves even after closing it via task manger and starting it again.

**Comment by xhul-dev** [comment]
Hello there.
There was a similar report recently, and we found the culprit.
I'm not saying you're concerned, but it was mouse-related, more specifically an incompatibility between Fan Control and a specific process.
The user closed a Ryzer mouse utility in the system tray, and the bug went away.
Until a fix is found somehow, you can't have both at the same time.

**Comment by Erik85** [comment]
Ok thx i dont use Razer but i do use Logitech But after Deleting FanControl and did the setup again it works most of the times now 70% no problem but the main thing is the fans spinning and working and i dont need to change the curves any more,
