### ISSUE TITLE
Is Fan Control using PWM or DC to control fan speeds?

### ISSUE THREAD

**Issue by Firefly518** [Rem0o/FanControl.Releases#855]
The app doesn't appear to mention either word anywhere. Is PWM limited to BIOS?

**Comment by Rem0o** [comment]
Fan Control has no hook for that setting. It’s whatever is set by default or in bios.

**Comment by Firefly518** [comment]
> Fan Control has no hook for that setting. It’s whatever is set by default or in bios.

So if I go to BIOS and set all fans to be controlled through PWM, DC options will not be available to Fan Control at all?

Does this mean that Fan Control builds on top of the BIOS to some extent instead of fully overriding it?

Background: Not a developer. Created git account only to ask questions about FC.

Btw Rem0o pleasure to meet you love the software will donate one day when I have money.

**Comment by Rem0o** [comment]
The SuperIO chip has different settings, BIOS by default pushes all of its settings, including DC/PWM.   FanControl then pushes some of its own specific settings, like manual control and the %, which doesn't override all of the previously set settings by the BIOS, like PWM/DC.

**Comment by Firefly518** [comment]
> 

Thanks a ton man!
