### ISSUE TITLE
EVGA CLC AIO issues

### ISSUE THREAD

**Issue by Sainthavoc** [Rem0o/FanControl.Releases#857]
When fan control is active my EVGA CLC AIO is detected then undetected over and over in a never ending loop. Along with sound of being detected and undetected. When its not detected the lights and fan stops and when detected lights and fan starts.

**Comment by Rem0o** [comment]
What are you sensor settings? I would remove the "controller" checkbox.

**Comment by Sainthavoc** [comment]
Its set to average cpu, but does it with any cpu sensor. as long as i dont use the sensor for cpu's it doesnt disconnect and reconnect.
