### ISSUE TITLE
GPU fan control does not activate

### ISSUE THREAD

**Issue by sengtsan** [Rem0o/FanControl.Releases#86]
I have set up a profile which includes control of the GPU fan - sometimes the profile doesn't activate for the GPU fan on occasion. To be clear, it happens only some of the time. 

The profile created controls the case and CPU fans too, and these work fine. It's only the GPU part that doesn't work at times. Unfortunately, since the GPU fans do not start at all when this happens, the GPU overheats and crashes my PC.

**Comment by Rem0o** [comment]
RTX 30XX series I suppose?

**Comment by sengtsan** [comment]
I wish!

Just a regular Sapphire rx580 pulse, 4gb.

**Comment by Rem0o** [comment]
When you say "doesn't activate" do you mean the "switch" on the card is off or that the software doesn't take over the fan ?  Do you have any MSI AfterBurner or similar software running ? If so, make sure to disable all of their fan control.

**Comment by sengtsan** [comment]
I mean The Fan Control software doesn't take over the fan. When Fan control is loaded, the GPU fans do not work at all, so it looks like Fan Control interferes with the default Fan behaviour.     

In terms of other software active: the Radeon software is running the background. The fan controls are disabled, however a custom profile that undervolts the GPU is active. I can try disabling that and see if that helps.

Another aspect I have noticed. The problem doesn't arise when I load Fan Control manually, however when I have Fan Control to run at boot, that's when things become unpredictable.

**Comment by Rem0o** [comment]
Maybe it's a software firing order thing. Like if the Radeon software launches first or vice-versa.

**Comment by sengtsan** [comment]
That sounds like a good theory. I will see if running manually rather than at boot sorts this issue. 

So far I think Fan Control very promising software. Much more intuitive than speedfan. If it will run reliably on my PC Fan Control might be the replacement. The videos on Youtube were very helpful too.

**Comment by tuschla** [comment]
> 
> 
> RTX 30XX series I suppose?

RTX 3080 works perfectly fine over here 👍🏻

**Comment by lhimo** [comment]
I have a similar issue with a 1650 super, but in my case the GPU fan won't start at all, causing throttling in gaming. I'm trying to go back to version 58, which was working fine, and see if the problem is solved or not.

**Comment by lhimo** [comment]
Note that my GPU custom profile was deactivated since I configured it but in the end I switched it off and I'm using only case fan control.

**Comment by lhimo** [comment]
It seems not to be related to Fan Control.. When I turn on the pc if I launch a game the fan won't start. The only way to make it start is to launch Fan Control and toggle GPU fan on and off.

Any idea why this could happen? The only fan controlling software is the mobo one (gigabyte app center).

**Comment by Rem0o** [comment]
@lhimo Toggling on then off sets it from "user defined" to "default". If FanControl isn't the one putting it in "user defined", here 0%, then something else is, and I can't help you on that front.

**Comment by lhimo** [comment]
You're right, I've no idea what's going on 😄 restoring windows did the trick

**Comment by mhartvig** [comment]
I'm seeing somewhat of the same thing with a 3090, the curve say the fans should be spining at some % but they never starts spining. If I remove the fan curve, the fans starts spining, I've uninstalled all other software that should be control the fans.

**Comment by lhimo** [comment]
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5683080/log.txt)
Here's a log if it can be useful

**Comment by Richie78321** [comment]
> > RTX 30XX series I suppose?
> 
> RTX 3080 works perfectly fine over here 👍🏻

Same here

**Comment by jptissot** [comment]
The fans on my 3080 spin up but they don't go back down to 0 once the gpu cools off. They stay at 30%. I have to toggle the fan curve for the fans to stop completely.

**Comment by Richie78321** [comment]
> The fans on my 3080 spin up but they don't go back down to 0 once the gpu cools off. They stay at 30%. I have to toggle the fan curve for the fans to stop completely.

Hmm without much investigation I’d say that you’re encountering the minimum fan speed for your particular GPU. My gigabyte card has a minimum of 45%

**Comment by jptissot** [comment]
> > The fans on my 3080 spin up but they don't go back down to 0 once the gpu cools off. They stay at 30%. I have to toggle the fan curve for the fans to stop completely.
> 
> Hmm without further investigation I’d say that you’re encountering the minimum fan speed for your particular GPU. My gigabyte card has a minimum of 45%

I think you are right. The same issue happens with msi afterburner.

**Comment by Rem0o** [comment]
Old issue, no real insight or meaningful conclusion, closing.
