### ISSUE TITLE
Software will not control Asrock GPU 

### ISSUE THREAD

**Issue by Timmybread22** [Rem0o/FanControl.Releases#860]
I have an AMD Radeon RX 6900 XT Phantom Gaming D 16G OC
I can control my gpu fan speed through ASRock Tweak, and while Fan Control V117 can detect my fan and rpm, it does not move when I change the slider

![GPU 0 percent](https://user-images.githubusercontent.com/105469828/172338163-fb9eb01f-c10f-4bde-85ea-61f37590e971.png)
![GPU 100 percent](https://user-images.githubusercontent.com/105469828/172338175-98ede09f-743d-4471-8086-05f34cdbf824.png)
![Changed GPU fan speed on Asrock Tweak](https://user-images.githubusercontent.com/105469828/172338197-c34d9382-1790-49c1-a431-d778b7286f70.png)

**Comment by Sainthavoc** [comment]
Have you tried running it without ASrock tweak running?

**Comment by Timmybread22** [comment]
Thank you for the help!
I tried it, but it still doesn't work.

**Comment by Rem0o** [comment]
Newer ish AMD cards are not supported for control, only read temp.
