### ISSUE TITLE
No Edits

### ISSUE THREAD

**Issue by Lauzl** [Rem0o/FanControl.Releases#865]
I cant Edit any curve. no Ui opens

**Comment by xhul-dev** [comment]
Hello there.
Some mouse-related softwares are known to interfer.
By any chance, do you happen to have a mouse utility present in the system tray? (it could be anything that changes the way your mouse operates).
If yes, and for testing purpose, could you please close it, and try interacting with the curve edit button afterwards?
If closing it fixes the problem, that would allow us to identify which software is concerned.
Thanks in advance =]

**Comment by Lauzl** [comment]
The error came right after the update. I uninstalled and reloaded it. -> and it worked again. but now my 3 fans (CPU) stuck at 20.5rpms :(. According to AIDA64 I have a higher speed, which I can hear.
I also deleted the .json file and created a new profile, but it doesn't work either.
Before the update everything works.
PWM Controller: EZDIY-FAB Moonlight RGB PWM Hub

**Comment by Gurrrra** [comment]
Nothing happens for me either when pressing Edit. Worked last night and today I put another CPU in my system, don't know if it's related but still.
