### ISSUE TITLE
Button to add new control covers existing controls

### ISSUE THREAD

**Issue by ntoff** [Rem0o/FanControl.Releases#869]
The big green + button to add a new control type covers existing controls, making it impossible to interact with part of an existing control.

![image](https://user-images.githubusercontent.com/9030085/173319446-1af46cd3-e9e7-4056-8978-ed49de0579bc.png)

The button to add new curves should either be moved, or a margin added to the right hand side to prevent it from covering existing controls. This only seems to be an issue in maximized mode at a resolution of 1920x1080 (haven't tested other resolutions).

**Comment by Rem0o** [comment]
Well, that's part of the design of a floating button. It just to happen that this exact disposition you are showing makes the button overlap a card.  Could add a right margin, but that would take away a lot of space for 95% of scenarios where the button doesn't hides anything.
