### ISSUE TITLE
Reboot windows if CPU temperature gets too high

### ISSUE THREAD

**Issue by cowwoc** [Rem0o/FanControl.Releases#872]
I just experienced a very odd issue in Windows 10. All fans spun up to 100% and CPU temperature went from 60C to 100C. Task Manager showed CPU usage at under 5% and I couldn't find the source of the high CPU usage. Rebooting Windows fixed the problem.

I'm afraid of this event repeating in the middle of the night, when I am not around to shut down the computer. Can you add a feature that allows us to trigger Windows shutdown or reboot if CPU usage rises above a configurable threshold?

**Comment by Jackaed** [comment]
This is a feature that should be configurable in your motherboard. Most CPUs have hard thermal limits that will shut the computer down if exceeded.

**Comment by cowwoc** [comment]
@Jackaed To my understanding, there are two separate components at play.

1. The motherboard sends a `PROCHOT` signal.
2. A windows application intercepts the `PROCHOT` and does something with it.

If the applications don't handle the event properly and the temperature keeps on rising then the power will get cut.

I want to ensure that Windows shuts down gracefully, and returns after a reboot. I don't believe this functionality exists anywhere.

**Comment by Rem0o** [comment]
See https://github.com/Rem0o/FanControl.Releases/issues/807

**Comment by cowwoc** [comment]
Great. I'll close this issue and move my comments there.
