### ISSUE TITLE
(Feature request) Option in main (left sandwich) menu to display fan RPM in fan control cards when hiding fan speed cards

### ISSUE THREAD

**Issue by 0x6A7232** [Rem0o/FanControl.Releases#873]
What it says on the tin. Expanding the fan control card for a small RPM readout seems preferable to either having a second set of cards to rename and watch, or loosing RPM readout. Great program BTW! Saw you mentioned on JayzTwoCents.
PS if you wanted to make it fancy you could include options for displaying as a meter instead of numbers for RPM. Or even a color shading of the card. But that's just a random idea I had when typing this up.

**Comment by Rem0o** [comment]
You can do that already?

![image](https://user-images.githubusercontent.com/14118956/173582785-707d6473-e063-467f-930d-c3df589ddbf5.png)

I can't escape the second set of cards initially. RPM sensors are separate, and I can't 100% guarantee match it with a control card from the get go for all possible setups.
