### ISSUE TITLE
Cant Detect All Of My Fans

### ISSUE THREAD

**Issue by UltimateBoi** [Rem0o/FanControl.Releases#875]
So, I have 5 fans in my case (including psu, gpu and cpu fan) but it is only showing 3?

Any help?

![image](https://user-images.githubusercontent.com/63293118/173638342-d9d57a44-47c5-47c7-b7d9-4c00959f29be.png)

**Comment by broconut123** [comment]
I think the last version that worked good for me was v110. .
I have a 120s delay and it usually does not find my sensors unless i refresh it many times, sometimes that don't even work at all.
Auto pair does not work, but I can manually pair my sensors, but after shutdown and reboot it's usually the same missing sensors error.

**Comment by apszika** [comment]
Hi! 
Same problem here. Sometimes when start Windows work properly, and sometimes this problem me too, and I can't figure why. I click refresh sensors and start working properly.

**Comment by Rem0o** [comment]
See Readme.
