### ISSUE TITLE
CPU Fans uncontrollable

### ISSUE THREAD

**Issue by Mertymen2010** [Rem0o/FanControl.Releases#877]
I have an AIO Corsair CPU cooler but the radiator fans appear to be uncontrollable. All case fans and GPU fans are fully controllable with all curves, etc via application.
The fans for the AIO are plugged into CPU and CPU_OPT on the mobo. When putting the CPU fans on the manual control or any sort of curve, they just come to a stop. If put back to  default with no curve or manual control, they seem to work as expected via mobo but this gives no control with the application.

Other than this issue, this software is works amazingly!

Any help would be appreciated.

Kind regards, 
Martin

**Comment by Rem0o** [comment]
Most of the times, these issues are BIOS config related, either PWM/DC setting or similar.

**Comment by 8BitShadow** [comment]
Same issue, looks like PWM fans (maybe when plugged into non-PWM pins?) and CPU AIO water coolers function incorrectly.
Not a BIOS config issue, other fan controller software handle this fine - guessing just an oversight, it happens.

**Comment by FynnApp** [comment]
> Edit: or are PWM fans just not currently supported outright ATM?

Has this question been answered elsewhere?

**Comment by TychoNova** [comment]
> Most of the times, these issues are BIOS config related, either PWM/DC setting or similar.

This isn't BIOS related. v119 fixed the issue.

**Comment by Rem0o** [comment]
@TychoNova  might have been something with LHM, updated the library.

**Comment by TychoNova** [comment]
Not exactly sure which version brought this bug back, but it definitely returned in v129 and it's still here having just updated to v130
