### ISSUE TITLE
Not showing CPU or Chassis fans

### ISSUE THREAD

**Issue by russdyer** [Rem0o/FanControl.Releases#88]
FanControl is only showing GPU fans, not showing CPU or Chassis fans.  I have an ASRock Z270M Pro4 board, RTX 2070 Super, CPU fan is plugged into CPU Fan #1, fan hub that powers 4 fans plugged into Chassic Fan #1 and 2 fans on a splitter plugged into Chassic Fan #2.
![fancontrol](https://user-images.githubusercontent.com/5117285/101568767-3bc1b300-39a1-11eb-8dea-ff4fd185a271.PNG)

**Comment by Rem0o** [comment]
As written in the Readme, motherboard compatibility is all coming from LibreHardwareMonitorLib. If nothings comes up, then you can work to add support to your board in that repo and any improvement will be reflected here.
