### ISSUE TITLE
Missing GPU fan/Control

### ISSUE THREAD

**Issue by SomeRandomDude870** [Rem0o/FanControl.Releases#881]
HI,
until 117 I had the problem that the CPU was not shown.
Well, now at 118 I have the problem that the GPU is not shown anymore, but the CPU is...

Gigabyte B560m Aorus pro 
RX590

Would be good to be able to control it again.

**Comment by Rem0o** [comment]
See README please.

**Comment by Rem0o** [comment]
One of the latest Windows update (KB5014697) messed with a lot of stuff. Make sure your GPU driver is up to date.

**Comment by Kanmuu** [comment]
I have the same problem, gpu fan control has disappeared since last amd update (RX480 here)
Someone posted the problem on librehardware too

**Comment by SomeRandomDude870** [comment]
Okay,
On which Version of LibreHardwareMonitor is FanControl atm?

**Comment by xCuri0** [comment]
Same problem RX 580 22.5.2

**Comment by Ghastleigh** [comment]
Me too, also RX 580 on 22.5.2
I can see the sensor through "Mixed Sensor" option, but can't use it anywhere else.

**Comment by toufuboi** [comment]
I am having the same issues and after I installed 22.6.1 AMD drivers the issue persists. I have tried download v 119 (what I think to be the last working version) and the graphics temps do not pop up

**Comment by Ghastleigh** [comment]
> I am having the same issues and after I installed 22.6.1 AMD drivers the issue persists. I have tried download v 119 (what I think to be the last working version) and the graphics temps do not pop up

update to v120, it started working for me after the update. I'm now on 22.6.1 as well.

**Comment by antt0n** [comment]
Same issue with Sapphire RX 5500 XT. Win 11 22H2 / AMD V22.7.1.
FanControl 130.
Speed detected, but can't control it (force apply didnt change anything).
![image](https://user-images.githubusercontent.com/20756073/193377537-ca16aeb5-772b-49fc-8acf-45b994b96884.png)

**Comment by Rem0o** [comment]
@antt0n  XT cards are not supported for control. Known issue. Sadly there has not been any progress on that front.

**Comment by antt0n** [comment]
> @antt0n  XT cards are not supported for control. Known issue. Sadly there has not been any progress on that front.

Oh, I see.
But theoretically, it's not impossible?
If it's just that no one has looked into it, I can try to see what I can do, doing some development.

**Comment by Rem0o** [comment]
@antt0n  yeah I've played a bit with it in that branch, but couldn't really move forward. Documentation isn't great.

**Comment by antt0n** [comment]
> @antt0n  yeah I've played a bit with it in that branch, but couldn't really move forward. Documentation isn't great.

The ADL documentation is clearly hell. But it seems that using Overdrive N is the most suitable for the new AMD graphics cards.
Although, I have a big doubt whether Overdrine N or 8 is the most suitable.
It would be necessary to make tests.
Nevertheless, Overdrive 8 and N offer functions to control the fans, so the solution must be there.

**Comment by xhemp** [comment]
Posted something on https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/833 which (I hope) might shed a light.

**Comment by Rem0o** [comment]
@antt0n 
@Kanmuu 

See https://github.com/Rem0o/ADLX/tree/main/Samples/csharp

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX
