### ISSUE TITLE
Instant-crash from clicking open in system tray

### ISSUE THREAD

**Issue by Konraddo** [Rem0o/FanControl.Releases#882]
Using v118 version. The crash doesn't update log.txt
This happens immediately after restart from KB5014697 Windows update.

(It works in the background but the GUI doesn't open)

**Comment by Rem0o** [comment]
I'll do the update and report back.

**Comment by Rem0o** [comment]
Confirmed that KB5014697 breaks a lot of stuff.
Will investigate.

**Comment by Rem0o** [comment]
In my case, I had to update my Nvidia GPU driver. Now everything works as before.

**Comment by Konraddo** [comment]
Had to restore Windows back to pre-update. But yes, the update breaks a lot of stuff. Certain games can't launch and other random applications crash at startup too. Will try updating nVidia driver.
