### ISSUE TITLE
Pairing Detection

### ISSUE THREAD

**Issue by ChumBombarda** [Rem0o/FanControl.Releases#890]
the Front top and middle fan are not atutomatic pairing. i check with the gigabyte SIV software and during calibration all fans turn off, but on Fan Control when i try to manual speed control, the 2 fans dont responde, they keep the bio default profile.

all the other fans  i have control even the front bottom fan. The top and middle fan i cant control on Fan Control. But on gigabyte software i tried do it manually and woeked.  saying this i think maybe is just some lil bug that can be fix.

the rpm reading is working.
Rpm was checked by turnning off manually on gigabyte soft, doing that the rpm reading on Fan Control was going to 0%.
Thats why i manually pair the front  top and middle
Front Top and middle fan are the issue
![Capturar](https://user-images.githubusercontent.com/108042141/175222096-e3c27e92-ec34-4fff-9dca-a58297eb4efe.PNG)
More recent pic with curve turn off.
![Capturar2](https://user-images.githubusercontent.com/108042141/175223544-d96f55ac-4b05-4325-a926-a6c8091dc93a.PNG)

Bottom fan working with Fan control

![IMG_20220623_073302](https://user-images.githubusercontent.com/108042141/175231999-adfc9a69-8fc7-44b2-915a-a1bf29a128dd.jpg)
![IMG_20220623_073318](https://user-images.githubusercontent.com/108042141/175232012-879dc78c-ae46-4dac-b566-4db8813b7486.jpg)

i already uninstall Gigabyte fan software(SIV). but still the same

Motherboard
Gigabyte Z590 Aorus pro ax
BIOS version: F9a

**Comment by Rem0o** [comment]
Are these 2 fans setup differently in the bios from the others?

**Comment by ChumBombarda** [comment]
Wasnt me that build the pc, was mounted ina stopre, so i dont know. But i can sent pic from bios if need.
the only thing i tested is if all fans was working manually in the gigabyte SIV software.

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: 23 de junho de 2022 14:24
Para: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Assunto: Re: [Rem0o/FanControl.Releases] Pairing Detection (Issue #890)


Are these 2 fans setup differently in the bios from the others?

**Comment by ChumBombarda** [comment]
Wasnt me that build the pc, was mounted ina stopre, so i dont know. But i can sent pic from bios if need.
the only thing i tested is if all fans was working manually in the gigabyte SIV software.
![IMG_20220623_191319](https://user-images.githubusercontent.com/108042141/175448343-2903325d-fcdb-41e8-ad12-9574b3bd37f4.jpg)

**Comment by ChumBombarda** [comment]
got another pic while using the calibration of gygabyte SIV software to try figure out if was any problem with my software but they all fans was working in sync.
![IMG_20220624_024851](https://user-images.githubusercontent.com/108042141/175448475-30a3c2fe-72a7-42ab-8f55-491f0fbdd4f7.jpg)
![IMG_20220624_024811](https://user-images.githubusercontent.com/108042141/175448483-7d6e0aa7-c73a-495e-8f94-76386efde565.jpg)

**Comment by ChumBombarda** [comment]
well anyway if you any more info just say.
keep the ggod work and gratz for the creation of this awsome interface. very user friendly.
wish you all good and cheers from portugal.
