### ISSUE TITLE
Target Fan curve glitch

### ISSUE THREAD

**Issue by Bianks84** [Rem0o/FanControl.Releases#892]
Just a minor glitch I'm having with some target fan curves.

Happens usually on startup.
Fan speed will jump to load % when temps aren't at load.
Changing any of the values (idle/load temps or fan %) resolves the issue.

**Comment by macadamiacreme** [comment]
I have exactly the same problem. It usually occurs after the computer wakes up from hibernation or power saving mode. It only affects the target curves.

**Comment by Rem0o** [comment]
Fixed.
