### ISSUE TITLE
Feature request/possible bug?

### ISSUE THREAD

**Issue by Praelia7or** [Rem0o/FanControl.Releases#895]
I picked up an aquacomputer octo after checking that it would work with the fan control software, shows stats in HWInfo and there is a HWInfo plugin, great!

However it seems I have either made an error or run into an issue, as it will pull sensors from HWInfo but not give me any control over the fans.

It looks like my options would be to either use the powered fan hub with my case and put everything on a single curve or use multiple motherboard headers with messy wiring.

Supporting the aquacomputer octo would be a great feature for those with fan heavy water cooled builds, probably the main audience for fan control software!

Otherwise awesome project, really looking forward to using the custom fan curves.

**Comment by Rem0o** [comment]
HWInfo doesn't provide any control sensors, it's read-only. That's expected.   FanControl won't give more features from the sensors pulled by HWInfo.   Third party controllers like the octo aren't all supported. 

Hardware compat. is provided by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.
Some people develop plugins also like this one https://github.com/medevil84/FanControl.AquacomputerHighFlowNext.

If the API/doc is available for third party integration for the octo, it could be integrated.

**Comment by Praelia7or** [comment]
Unfortunately I've not found anything which has opened up the control side, just access to the sensors as you've mentioned. Hopefully someone will pick it up as it would be great to use it with your software!

**Comment by Rem0o** [comment]
Some guy added Octo support : https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/b0de6e3ad762c18083b9198bd1982537e7c0f16c

Will be pulled in the next version.

**Comment by Praelia7or** [comment]
Awesome news, looking forward to switching over!

**Comment by dreckbaer** [comment]
> Some guy added Octo support : [LibreHardwareMonitor/LibreHardwareMonitor@b0de6e3](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/b0de6e3ad762c18083b9198bd1982537e7c0f16c)
> 
> Will be pulled in the next version.

Is the Aquacomputer Octo supported by now? Cos if it is, I cant seem to get the data from it.
