### ISSUE TITLE
Need to refresh multiple times to get all sensors detected on every boot

### ISSUE THREAD

**Issue by hapklaar** [Rem0o/FanControl.Releases#899]
Most of the time, after resuming from sleep and/or fresh start, Fan Control complains it can't find all sensors/fans. I need to click the refresh button up to 5 times to get everything detected properly. This also happens many minutes after the system is up, so everything should be initialized.

Are there any logs or config files I should include in this issue report?

**Comment by ArtursGailis1995** [comment]
I have same issue for months now. Cant use the program at all, as it loses sensors and updating sensors takes lots of clicks. It loses all the sensors, even Nvidia. Would be great if this program had some way to tell what is wrong with it.

Every shutdown (Hybrid sleep off), longer idle or PC Sleep mode it fails to detect any sensors at all. Havent figured out what software or hardware is causing those issues. 

Even when its running well, changing things around too fast will fail and fans will get stuck in some random mode, either full blats, totally off or somewhere random %. 

First click (after fresh PC startup/wake or manual program start - I know about startup delay, doesnt fix issue):
<img width="1455" alt="Screenshot 2022-06-27 112856" src="https://user-images.githubusercontent.com/18446644/175936482-c1a2e195-3bb9-434c-9f05-f9db9202cad4.png">

Second click (things in background disapeared): 
<img width="1467" alt="Screenshot 2022-06-27 112914" src="https://user-images.githubusercontent.com/18446644/175936566-2f7ca6d7-15bc-4bdd-a9ee-2a19d1718fcb.png">

Its as if something is interfering with the software.

**Comment by Rem0o** [comment]
@ArtursGailis1995 multiple things can interfere with the software.  For eg. some guy reported that the Asus Fan service was causing similar issues, and had to be running before fan control was started, otherwise his controls were all messed up.

**Comment by hapklaar** [comment]
@Rem0o would it be possible to add some more logging to be able to determine the cause? It's just weird that hitting refresh 4 or 5 times fixes it. This doesn't seem to fit the picture of it being caused by other software.

**Comment by Rem0o** [comment]
@hapklaar  Yes and no.

From what I've seen, when "that" happens, the "Detect() " method here https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/54a407dc50149e255209e4642f7bbcd828fc36fa/LibreHardwareMonitorLib/Hardware/Motherboard/Lpc/LpcIO.cs#L15 doesn't detect anything.  Refreshing will basically call this over and over until some LPC port returns the super io identifier. Now why does the LPC port doesn't return the ID for a while after boot/sleep, that, I have no idea.

**Comment by stalsma** [comment]
I'm seeing the same thing on my MSI B550 (NUVOTON NCT6687-R Controller Chip).  Works great on boot, but hit-and-miss (mostly miss) coming out of hibernate/sleep.

There are several references to Chip.NCT6687D in the LibreHardwareMonitor code.  Not sure if the "D" refers to all hardware revisions for that chip or not.

**Comment by Krmloo** [comment]
Same problem, MSI Z690 EDGE
A solution that comes to mind is calling mentioned Detect() a bunch of times with a delay before showing the error.

**Comment by ArtursGailis1995** [comment]
The thing I discovered is that when this happens, LHM doesnt show my motherboard AT ALL in its interface. As it doesnt exist. Happens rarely on cold boot but always when coming out of sleep,

**Comment by Rem0o** [comment]
Curious to see if my changes made in V121 help in any way.

**Comment by ArtursGailis1995** [comment]
@Rem0o Checked it with latest version. As soon as I turn on any fan control, it instantly is overridden by an external source. I don't have any external source installed and bios crap is disabled too. Even the GPU gets overridden every few seconds and then goes back to normal. :D

**Comment by hapklaar** [comment]
> Curious to see if my changes made in V121 help in any way.

Installed, put my PC through a sleep/wake cycle a couple of times, so far so good.

**Comment by Krmloo** [comment]
Still the same problem for me, but now it sometimes shows that the fans are controlled by an external source.

**Comment by Rem0o** [comment]
@hapklaar  From cold boot it's an other issue that I will tackle separately. My V121 changes only applied to wake from sleep.

**Comment by hapklaar** [comment]
@Rem0o It's looking good. As long as I use a +-30 sec delay, no more issues for me.

**Comment by Krmloo** [comment]
Seems to be more stable now, but sometimes still fails to find the sensors with 120s delay.

**Comment by hapklaar** [comment]
@Rem0o the issue seems to be back, at least since v133 but also in v134. Has anything changed that could cause this?

**Comment by Rem0o** [comment]
@hapklaar  you are right.  There was a regression. Will get to it asap and push a fix.

**Comment by hapklaar** [comment]
@Rem0o Is it possible there has been a regression again? Most of the time when resuming from sleep, I need to refresh 5-10 times before all sensors are detected again. This has been so for at least a couple of weeks, maybe more. Not sure when it started again. Tested up until v176.

**Comment by Rem0o** [comment]
@hapklaar   I can't see any change recently on that front that would affect resume from sleep.

**Comment by hapklaar** [comment]
@Rem0o Hmm curious... any debugging or log checking I can do to try and determine the cause? I don't see anything relevant (or recent) in the error log.

**Comment by stalsma** [comment]
I'm seeing the same thing.  Every time I come out of sleep (but only sleep--not after a reboot), I have to refresh ~3x before everything loads.  Running v175.

**Comment by hapklaar** [comment]
@Rem0o still having this issue when resuming from sleep. It has totally regressed to the status before v121 for me where the sensors are never detected after resuming from sleep and I need to refresh 5 or 6 times to get them back again.

Please let me know if you need any extra debugging from me?
