### ISSUE TITLE
Noisy drive of mine will not sleep when Fan Control is running.

### ISSUE THREAD

**Issue by beezley** [Rem0o/FanControl.Releases#9]
First off thanks for a great piece of software 👍

I am guessing it is to do with LibreHardwareMonitor monitoring the drives.

Is it possible to add an option to stop monitoring drives please or you may know of another possible workaround?

I would love to be able to use Fan Control but my noisy storage drive is louder than my fans lol :-)

thanks once again for your great work,

all the best,

Mark

**Comment by Rem0o** [comment]
I guess polling the drive from LibreHardwareMonitor does indeed prevent sleep. I will investigate.

**Comment by AdrenalinaGit** [comment]
This thread appears very relevant:
"Enhancement: Switch from hdparm to smartctl for some hdd queries"
https://github.com/desbma/hddfancontrol/issues/21

**Comment by beezley** [comment]
> 
> 
> I guess polling the drive from LibreHardwareMonitor does indeed prevent sleep. I will investigate.

Hi Rem0o thanks for looking into that, I downloaded the standalone version of LibreHardwareMonitor and in the hardware tab in settings you can uncheck drives which does prevent polling of the drives.

I can imagine it is feasibly possible to implement into your software, but I have no idea how easy or hard that would be. I have no programming experience apart from being a script kiddy that plays around with batch files and autoit now and again.

Thanks again for looking into it though buddy.

kind regards Mark.

**Comment by Rem0o** [comment]
@beezley in my current dev build I've added the option to disable the storage update. The hard drives will still be detected at boot, but the sensors won't get updated if the option is checked.

**Comment by AdrenalinaGit** [comment]
@Rem0o: Do you mean you added one checkbox per drive, or one "global" checkbox that disables reading temperatures of all drives?  Beezley gave the impression that he has only one drive in his system, but some users of FanControl have more than one drive and might want FanControl to read temperatures of a subset of the drives.

**Comment by beezley** [comment]
> 
> 
> @beezley in my current dev build I've added the option to disable the storage update. The hard drives will still be detected at boot, but the sensors won't get updated if the option is checked.

@Rem0o that's great I will look forward to testing in out, thanks again!

**Comment by Rem0o** [comment]
Was fixed in V36 with the disable storage option.
