### ISSUE TITLE
Fan ignoring set speed and runing at 34%

### ISSUE THREAD

**Issue by Tondascz** [Rem0o/FanControl.Releases#902]
I have two fans setuped identically but one of them just ignors the speed it should be runing at. When i change the offset from 5% to 4% it goes to the speed it should be runing but after like 3 minutes it's back to 34%
![Snímek obrazovky (48)](https://user-images.githubusercontent.com/85064072/175993952-f5c725ac-fcf4-4ab3-8b84-5660e42ed6a1.png)

**Comment by Rem0o** [comment]
Something "else" is taking control over. Look over your other softwares, and BIOS config for your fans.
