### ISSUE TITLE
Lowest Max temp for a graph is 80 degrees

### ISSUE THREAD

**Issue by andreaenis** [Rem0o/FanControl.Releases#903]
In watercooling context i have created a mix sensor by doing.
air temperature - coolant temperature, this would bring me temperatures in a range from 0 to 11 celsius however the app does not allow me to create a curve that has a max value set at 11 celsius making deltaT cooling not an option for me.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/176008238-edd31d21-5fe2-4b6d-963c-c43965e0fa38.png)

You can. Make sure you got no points outside the desired range when changing the max/min values.

**Comment by andreaenis** [comment]
Thank you i just worked around it editing the Json profile!
