### ISSUE TITLE
Question: Is this software will work with water cooling (for controlling the pump?)

### ISSUE THREAD

**Issue by meilleur102** [Rem0o/FanControl.Releases#904]
Title say everything. Thanks.

**Comment by Jk-Hamly** [comment]
@Rem0o is it possible to integrate something like liquidctl into fancontrol to control fan speed, pump speed, and monitor liquid temps?

**Comment by Rem0o** [comment]
@Jk-Hamly 

Some guy did https://github.com/jmarucha/FanControl.Liquidctl

**Comment by ycodryn** [comment]
@meilleur102 Yes you can, I`m doing this with my alphacool pump connected to water+ header from asus mb.

**Comment by Cole931** [comment]
Rem0o how does the install of that Liquidctl plugin work? I've unzipped it into the plugins folder but I'm coding illiterate and attempting to understand the process to get it to recognize it as a plugin.
