### ISSUE TITLE
Starting the app twice generates two instances in V119

### ISSUE THREAD

**Issue by Alreiber** [Rem0o/FanControl.Releases#908]
Just installed V119 which in theory solves this issue, but still getting two different instances of FanControl running simultaneously.

**Comment by Rem0o** [comment]
If you got 2 different .exe and start from both places, it won't work, that's expected.

**Comment by Alreiber** [comment]
I’ve got a single .exe, set to start with Windows. Sometimes I don’t see the app because the tray icon is white and I have the light Windows theme so I run the .exe again, or simply press win key + fan… to pull it up easily, and in both cases I end up with two instances of FanControl. Is this the desired behaviour?

**Comment by Rem0o** [comment]
Two instance of FC shouldn't happen anymore. IPC was implemented.
