### ISSUE TITLE
Sensor not react.

### ISSUE THREAD

**Issue by ChumBombarda** [Rem0o/FanControl.Releases#909]
hi. afther update i wanted to see if the previous issue was solved. but wasnt. 
i know my hardware is fine because i check with gigabyte SIV software and all fans can be manually controled.
so i just want leave this info maybe you can have some ideia of the issue.
[report afther trying automatic pairing on front middle fan.txt](https://github.com/Rem0o/FanControl.Releases/files/9015011/report.afther.trying.automatic.pairing.on.front.middle.fan.txt)

![m b](https://user-images.githubusercontent.com/108042141/176559565-d17d3d73-d140-4433-aafa-0b19408db61d.jpg)
![sensor](https://user-images.githubusercontent.com/108042141/176559573-eae93d09-c720-4440-9e54-d94f6cbf838c.PNG)
![fan cfg](https://user-images.githubusercontent.com/108042141/176559576-568c2481-6041-4ce3-94d5-e7cbd5b7a286.PNG)

**Comment by Rem0o** [comment]
See the README please, especially the hardware compatibility part.

**Comment by ChumBombarda** [comment]
ohh ok ty for info. stay well
