### ISSUE TITLE
PWM vs. Voltage

### ISSUE THREAD

**Issue by leones00** [Rem0o/FanControl.Releases#91]
Hi, thanks for this great software.

After waking-up from the sleep mode, my PC's CPU fan speeds up higher than usual rpm, despite the same speed (%) shown on cards in the Fan Control v59.

![Screenshot 2020-12-14 220225](https://user-images.githubusercontent.com/37134260/102084559-ae76d680-3e58-11eb-9bb9-02fa8db9e1c6.png)
Before sleep.
![Screenshot 2020-12-14 215836](https://user-images.githubusercontent.com/37134260/102084571-b3d42100-3e58-11eb-8b7e-87eba835c468.png)
Woke-up from sleep.

This problem does not allow setting CPU fan speed exactly. (The difference of ~690 rpm is not small.) I don't know if it's the actual reason, but I think it's the matter of PWM vs. voltage, because I see very similar behavior on the fan control mode in BIOS (UEFI) setting. (low rpm for voltage vs high rpm for PWM  at the same % fan speed.) By the way, I have set it voltage mode, not auto or pwm mode.

Please consider this issue or tell me some workarounds.

Windows 10 Pro 20H2, Gigabyte A320m-sh2, Ryzen 2200g stock cooler.

**Comment by Rem0o** [comment]
When that does happen, does disabling/enabling the control resets to the expected behavior?

**Comment by leones00** [comment]
![Screenshot 2020-12-15 031242](https://user-images.githubusercontent.com/37134260/102118823-8f416e80-3e83-11eb-808c-ac77c74371a4.png)
![Screenshot 2020-12-15 031256](https://user-images.githubusercontent.com/37134260/102118827-90729b80-3e83-11eb-847b-5d5593201b0b.png)
No, disabling/enabling does not reset to fan speed to initial rpm.
~1300 rpm is minimum speed for PWM mode (24%).

**Comment by Rem0o** [comment]
But is it FanControl that somehow changes this behavior? The software doesn't do anything behind the scenes differently after waking up from sleep. However, when waking up from sleep, your BIOS can reset some stuff, like your BIOS fan config and so on. Do you have a gigabyte service / app running also that can control those kinds of things?

**Comment by leones00** [comment]
> The software doesn't do anything behind the scenes differently after waking up from sleep.

That's what I wondered, if there is some option to change speed mode in FanControl, either automatically or manually.
I will test if there's same issue in SIV after waking-up from sleep.

> Do you have a gigabyte service / app running also that can control those kinds of things?

No, I am not using SIV for fan speed control. I just installed it to test RPM range. (By the way, in SIV I can lower fan speed to 10%, 400 rpm in voltage mode, 1200 rpm in PWM mode, but in FanControl I can't lower speed below 24%. In voltage mode 0-24% 0 rpm, in PWM mode 0-23 1310 rpm.)

**Comment by leones00** [comment]
> I will test if there's same issue in SIV after waking-up from sleep.

I found same issue in SIV, so the problem might be my motherboard or OS.
Thanks for your kind reply.
