### ISSUE TITLE
FanControl keeps totally breaking - multiple issues

### ISSUE THREAD

**Issue by nefariouslegion** [Rem0o/FanControl.Releases#910]
Ever since v115 my FanControl has completely broken. The following issues all occur:
-GPU loses it's set fan curve and the manual toggle for it turns off 
-The GPU fan curve always loses it's temperature source
-The UI totally breaks. i.e. Can't close the GUI (X button does nothing), can't edit curves because the "Edit" button does nothing, can't save or load configs because those buttons all do nothing.
      -Basically any button that should open an overlay/another window on top of the main UI do nothing at all.
-Many missing sensor errors. Most of which are GPU things
-It doesn't notify me of new versions anymore. I didn't realize until I manually checked for an update that the current version was v119 hence why I was still on v115. 
-v119 also still has all the above issues

I don't have a clue as to what has caused it to break so badly. Chipset, BIOS and drivers are all up to date. 

EDIT: So I decided to re-setup my configuration from scratch to see if it would fix anything. I didn't think that it would since I don't see how a config could break it. But it seems (for now anyways) that doing so has fixed the issues. I've attached a copy of my config that seemingly breaks FanControl if you'd like to take a look at it and see if you can figure out what causes the problems. 
[backup of userConfig.zip](https://github.com/Rem0o/FanControl.Releases/files/9016399/backup.of.userConfig.zip)

**Comment by Rem0o** [comment]
Any log.txt to share?
