### ISSUE TITLE
Fan Profile not working when an update is available

### ISSUE THREAD

**Issue by jonahdami** [Rem0o/FanControl.Releases#915]
Unfortunately, when there is an update available the fans are not being controlled.
Had multiple occasions where my CPU got to 90 something degrees due to my fans not spinning.

Just had this happen again with the 119 Update

**Comment by Rem0o** [comment]
Not working, you mean not loaded?  Any log.txt?

**Comment by jonahdami** [comment]
> Not working, you mean not loaded? Any log.txt?

I could send supply the log.txt but the last entry is from the 25th.

Yes, I would guess that when there is an update available there is no profile loaded as. To "solve" it I press update, wait a bit and then the profile reapplies.
