### ISSUE TITLE
Fan control V119 UI Menu driven  pop up dialogs fail to show and app refuses to exit

### ISSUE THREAD

**Issue by antojk** [Rem0o/FanControl.Releases#916]
The software fails to respond to UI inputs both on almost all the menu items. It refuses to "exit" or show any of the pop up dialogs. It  sometimes holds up windows from shutting down!
Here is my log:
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9032380/log.txt)

**Comment by Rem0o** [comment]
Seems like you got a corsair plugin that crashes the app.
