### ISSUE TITLE
FanControl only works before/after opening CPU-Z / HWMonitor

### ISSUE THREAD

**Issue by xtasix** [Rem0o/FanControl.Releases#918]
I tried FanControl long time ago but it wouldn't work controlling fan speeds or showing the correct RPMs. Now I decided to try it again after some updates but I got the same problem as before and just testing things found that FanControl would work and show correct RPMs after opening CPU-Z / HWMonitor at least once (Idk why that works so if you could explain to me, it would be good)

*Note: GPU speed control and RPMs is always good.

### Fan Control after a fresh Windows Start without opening CPU-Z/HWMonitor (Controlling speed doesn't work and RPMs are not correct)
![1](https://user-images.githubusercontent.com/11654815/177087146-cf9a5545-5623-4a34-9af7-af37f15793cc.PNG)

### Fan Control when CPU-Z/HWMonitor was initialized at least once (Controlling speed works and shows correct RPMs)
![2](https://user-images.githubusercontent.com/11654815/177087197-c803c686-4ba2-40e0-a4eb-7b176bbe9ef0.PNG)

Any idea why is that and how can it be fixed so I don't have to keep opening CPU-Z/HWMonitor after every Windows startup to get working controls and updated speed Info.

**Comment by jaivu** [comment]
I also had the same experience with my mobo Asus TUF B450M-PRO S. Tried many solutions and combos, and it seems this is the only workaround for Asus boards.

**Comment by Rem0o** [comment]
Yup Asus boards have something going on that needs to be set somehow before being able to read sensors properly. Seems like CPU-Z / HWInfo got that right, but LHM doesn't, hence FanControl.

**Comment by sduford** [comment]
> Yup Asus boards have something going on that needs to be set somehow before being able to read sensors properly. Seems like CPU-Z / HWInfo got that right, but LHM doesn't, hence FanControl.

But the funny thing is you only need to run CPU-Z once and then you can shut it down. HWInfo did not have the same effect.

**Comment by xtasix** [comment]
Yup, HWInfo and CPU-Z does the work I had to create scheduled tasks for that when login and unlocking the PC.

I hope LHM could find a fix for this in the future.
