### ISSUE TITLE
Controls stop applying curves

### ISSUE THREAD

**Issue by JordanMunroe** [Rem0o/FanControl.Releases#92]
I'm currently unable to use this software due to controls randomly locking up, they (seemingly at random) stop applying curves and just stick to whatever the current value was until I toggle them on and off. They don't only freeze at 0% as seen in the screenshot below, they'll just freeze at whatever value they were at when they do.

### Here's a screenshot of my exhaust/intake fan curves not applying, though it also happens to my GPU and CPU controls(I had to disable them after they froze the first time and overheated the CPU)
![image](https://user-images.githubusercontent.com/3692535/102126314-86638500-3e10-11eb-822c-41d0ac0fe089.png)

### And here's a screenshot of my whole configuration
![image](https://user-images.githubusercontent.com/3692535/102126594-e3f7d180-3e10-11eb-9311-968f6de47372.png)

**Logs**
> Motherboard
> 
> SMBios Version: 2.7
> 
> BIOS Vendor: American Megatrends Inc.
> BIOS Version: 1015
> BIOS Date: 5/2/2012
> BIOS Size: 8 MB
> 
> System Manufacturer: System manufacturer
> System Name: System Product Name
> System Version: System Version
> System Wakeup: PowerSwitch
> 
> Motherboard Manufacturer: ASUSTeK COMPUTER INC.
> Motherboard Name: SABERTOOTH Z77
> Motherboard Version: Rev 1.xx
> Motherboard Serial: MT7025K12302128
> 
> Chassis Type: Desktop
> Chassis Manufacturer: Chassis Manufacture
> Chassis Version: Chassis Version
> Chassis Serial: Chassis Serial Number
> Chassis Asset Tag: Asset-1234567890
> Chassis SKU: To be filled by O.E.M.
> Chassis Boot Up State: Safe
> Chassis Power Supply State: Safe
> Chassis Thermal State: Safe
> Chassis Power Cords: 1
> Chassis Lock Detected: No
> Chassis Security Status: None
> 
> Processor Manufacturer: Intel
> Processor Type: CentralProcessor
> Processor Version: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
> Processor Serial: To Be Filled By O.E.M.
> Processor Socket Destignation: LGA1155
> Processor Socket: Other
> Processor Version: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
> Processor Family: IntelCore2Duo
> Processor Core Count: 4
> Processor Core Enabled: 1
> Processor Thread Count: 2
> Processor External Clock: 105 Mhz
> Processor Max Speed: 3800 Mhz
> Processor Current Speed: 3584 Mhz
> 
> Cache [L1] Size: 32
> Cache [L1] Associativity: 16Way
> 
> Cache [L2] Size: 256
> Cache [L2] Associativity: 16Way
> 
> Cache [L3] Size: 8192
> Cache [L3] Associativity: 12Way
> 
> Memory Device [0] Manufacturer: 029E
> Memory Device [0] Part Number: CMY16GX3M2A2400C11
> Memory Device [0] Device Locator: ChannelA-DIMM0
> Memory Device [0] Bank Locator: BANK 0
> Memory Device [0] Speed: 2000 MHz
> 
> Memory Device [1] Manufacturer: [Empty]
> Memory Device [1] Part Number: [Empty]
> Memory Device [1] Device Locator: ChannelA-DIMM1
> Memory Device [1] Bank Locator: BANK 1
> Memory Device [1] Speed: 0 MHz
> 
> Memory Device [2] Manufacturer: 029E
> Memory Device [2] Part Number: CMY16GX3M2A2400C11
> Memory Device [2] Device Locator: ChannelB-DIMM0
> Memory Device [2] Bank Locator: BANK 2
> Memory Device [2] Speed: 2000 MHz
> 
> Memory Device [3] Manufacturer: [Empty]
> Memory Device [3] Part Number: [Empty]
> Memory Device [3] Device Locator: ChannelB-DIMM1
> Memory Device [3] Bank Locator: BANK 3
> Memory Device [3] Speed: 0 MHz
> 
> SMBios Table
> 
>  ABgAAAECAPADf4CYiz8BAAAAAw0EBv//QW1lcmljYW4gTWVnYXRyZW5kcyBJbmMu
>  ADEwMTUAMDUvMDIvMjAxMgAAARsBAAECAwRgOYen2tfdEYOPyGAAzCX3BgUGU3lz
>  dGVtIG1hbnVmYWN0dXJlcgBTeXN0ZW0gUHJvZHVjdCBOYW1lAFN5c3RlbSBWZXJz
>  aW9uAHN5c3RlbQBTS1UAVG8gYmUgZmlsbGVkIGJ5IE8uRS5NLgAAAg8CAAECAwQF
>  CQYDAAoAQVNVU1RlSyBDT01QVVRFUiBJTkMuAFNBQkVSVE9PVEggWjc3AFJldiAx
>  Lnh4AE1UNzAyNUsxMjMwMjEyOABUbyBiZSBmaWxsZWQgYnkgTy5FLk0uAFRvIGJl
>  IGZpbGxlZCBieSBPLkUuTS4AAAMWAwABAwIDBAMDAwMAAAAAAAEAAAVDaGFzc2lz
>  IE1hbnVmYWN0dXJlAENoYXNzaXMgVmVyc2lvbgBDaGFzc2lzIFNlcmlhbCBOdW1i
>  ZXIAQXNzZXQtMTIzNDU2Nzg5MABUbyBiZSBmaWxsZWQgYnkgTy5FLk0uAAAEKgQA
>  AQO/AqkGAwD/++u/A4ppANgOAA5BAQUABgAHAAQFBgQBAgQAvwBMR0ExMTU1AElu
>  dGVsAEludGVsKFIpIENvcmUoVE0pIGk3LTM3NzAgQ1BVIEAgMy40MEdIegBUbyBC
>  ZSBGaWxsZWQgQnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUg
>  RmlsbGVkIEJ5IE8uRS5NLgAABxMFAAGAASAAIAABAAEAAAMFB0wxLUNhY2hlAAAH
>  EwYAAYECAAEAAQEAAQAAAwUHTDItQ2FjaGUAAAcTBwABAgMAIAAgAQABAAADBQhM
>  My1DYWNoZQAACAkIAAEAAhIQVVNCOV8xMABVU0I5XzEwAAAICQkAAQACCx9HYkUg
>  TEFOAEdiRSBMQU4AAAgJCgABAAL/HUFVRElPAEFVRElPAAAICQsAASIAACBTQVRB
>  MQAACAkMAAEiAAAgU0FUQTIAAAgJDQABIgAAIFNBVEEzAAAICQ4AASIAACBTQVRB
>  NAAACAkPAAEiAAAgU0FUQTUAAAgJEAABIgAAIFNBVEE2AAAICREAARIAABBVU0Ix
>  XzIAAAgJEgABEgAAEFVTQjNfNAAACAkTAAESAAAQVVNCNV82AAAICRQAARIAABBV
>  U0I3XzgAAAgJFQABHwAAHUFBRlAAAAgJFgAB/wAA/0NQVV9GQU4AAAgJFwAB/wAA
>  /0NQVV9PUFRfRkFOAAAICRgAAf8AAP9DSEFfRkFOMQAACAkZAAH/AAD/Q0hBX0ZB
>  TjIAAAgJGgAB/wAA/0NIQV9GQU4zAAAICRsAAf8AAP9DSEFfRkFONAAACAkcAAH/
>  AAD/QVNTVF9GQU4xAAAICR0AAf8AAP9BU1NUX0ZBTjIAAAkRHgABpQUDAwEADAEA
>  AP8IUENJRVgxXzEAAAkRHwABpQUEAwIADAEAAAHjUENJRVgxNl8xAAAJESAAAaUF
>  AwMDAAwBAAD/5FBDSUVYMV8yAAAJESEAAaUFAwMEAAwBAAD/5lBDSUUxNl8yAAAJ
>  ESIAAaUFAwMFAAwBAAD/CVBDSUVYMV8zAAAJESMAAaUFAwMGAAwBAAACCFBDSUVY
>  MTZfMwAACgYkAIUBT25ib2FyZCBFdGhlcm5ldAAACwUlAARUbyBCZSBGaWxsZWQg
>  QnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5
>  IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAAAMBSYAAVRvIEJlIEZpbGxl
>  ZCBCeSBPLkUuTS4AACAUJwAAAAAAAAAAAAAAAAAAAAAAAAAiCygAAQQAAAAAA0xN
>  NzgtMQAAGhYpAAEAAIAAgACAAIAAgAAAAAAAgExNNzhBAAAkECoAAQACAAMABAAF
>  AAYAAAAjCysAASgAKAApAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AABwWLAABAACA
>  AIAAgACAAIAAAAAAAIBMTTc4QQAAJBAtAAEAAgADAAQABQAGAAAAIwsuAAEoACsA
>  LABUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAAAbDy8ALAASAQAAAAAAgAFDb29saW5n
>  IERldiAxAAAkEDAAAQACAAMABAAFAAYAAAAjCzEAASgALgAvAFRvIEJlIEZpbGxl
>  ZCBCeSBPLkUuTS4AABsPMgAsABIBAAAAAACAAAAAJBAzAAEAAgADAAQABQAGAAAA
>  Iws0AAEoADEAMgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAAAdFjUAAQAAgACAAIAA
>  gACAAAAAAACAQUJDAAAkEDYAAIAAgACAAIAAgACAAAAjCzcAASgANAAyAFRvIEJl
>  IEZpbGxlZCBCeSBPLkUuTS4AACIQOAABBAAAAAADTE03OC0yAAAaFjkAAQAAgACA
>  AIAAgACAAAAAAACATE03OEIAACQQOgAHAAgACAAKAAsADAAAACMLOwABOAA4ADkA
>  VG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgAAGhY8AAEAAIAAgACAAIAAgAAAAAAAgExN
>  NzhCAAAkED0ADQAOAA8AEAARABIAAAAjCz4AATgAOwA8AFRvIEJlIEZpbGxlZCBC
>  eSBPLkUuTS4AABwWPwABAACAAIAAgACAAIAAAAAAAIBMTTc4QgAAJBBAAAEAAgAD
>  AAQABQAGAAAAIwtBAAE4AD4APwBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAAAbD0IA
>  PwASAQAAAAAAgAFDb29saW5nIERldiAyAAAkEEMAAQACAAMABAAFAAYAAAAjC0QA
>  ATgAQQBCAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AABwWRQABAACAAIAAgACAAIAA
>  AAAAAIBMTTc4QgAAJBBGAAEAAgADAAQABQAGAAAAIwtHAAE4AEQARQBUbyBCZSBG
>  aWxsZWQgQnkgTy5FLk0uAAAbD0gARQASAQAAAAAAgAFDb29saW5nIERldiAyAAAk
>  EEkAAQACAAMABAAFAAYAAAAjC0oAATgARwBIAFRvIEJlIEZpbGxlZCBCeSBPLkUu
>  TS4AAB0WSwABAACAAIAAgACAAIAAAAAAAIBERUYAACQQTAAAgACAAIAAgACAAIAA
>  ACMLTQABOABKAEgAVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgAAHRZOAAEAAIAAgACA
>  AIAAgAAAAAAAgEdISQAAJBBPAACAAIAAgACAAIAAgAAAIwtQAAE4AE0ASABUbyBC
>  ZSBGaWxsZWQgQnkgTy5FLk0uAAAaFlEAAWoAgACAAIAAgACAAAAAAACATE03OEEA
>  ABwWUgABagCAAIAAgACAAIAAAAAAAIBMTTc4QQAAGw9TAFIAZwEAAAAAAIABQ29v
>  bGluZyBEZXYgMQAAHRZUAAFqAIAAgACAAIAAgAAAAAAAgEFCQwAAJxZVAAEBAgME
>  BQYHAICiEVEAUwBUAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AVG8gQmUgRmlsbGVk
>  IEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkgTy5FLk0uAFRvIEJlIEZpbGxlZCBC
>  eSBPLkUuTS4AVG8gQmUgRmlsbGVkIEJ5IE8uRS5NLgBUbyBCZSBGaWxsZWQgQnkg
>  Ty5FLk0uAFRvIEJlIEZpbGxlZCBCeSBPLkUuTS4AACkLVgABgwEAAAAQIE9uYm9h
>  cmQgSUdEAAApC1cAAYUBAAAAyCBPbmJvYXJkIExBTgAAKQtYAAGBAQAAA+IgT25i
>  b2FyZCAxMzk0AACLXlkA/ty6mHZUMhAEBDJV+ACiAqEAQGNDEP6BA99AgAAgAHM8
>  EAgAYA8GERUEIAA8EAAAAAAAAAAAAAAAAAAAAAAAAGkAAP//BhEABAAAIzMAAAAA
>  AAAAAAAAAAABVjEzOTRHVUlEAAARIloAWwBfAEAAQAAAIAkAAQIYgADQBwMEBQYC
>  AAAAANAHQ2hhbm5lbEEtRElNTTAAQkFOSyAwADAyOUUAMDAwMDAwMDAAOTg3NjU0
>  MzIxMABDTVkxNkdYM00yQTI0MDBDMTEAABAXWwADAwMAAAACXAAEAAAAAAAAAAAA
>  AAASF1wAAwICAAAAAAAAAIAAAACAAAAAgAAAFCNdAAAAAAD//38AWgBlAP8BAgAA
>  AAAAAAAAAAAAAAAAAAAAABEiXgBbAP//AAAAAAAACQABAgIAAAAAAwQFBgAAAAAA
>  AABDaGFubmVsQS1ESU1NMQBCQU5LIDEAW0VtcHR5XQBbRW1wdHldADk4NzY1NDMy
>  MTAAW0VtcHR5XQAAEhdfAAMCAgAAAAAAAACAAAAAgAAAAIAAABEiYABbAGEAQABA
>  AAAgCQABAhiAANAHAwQFBgIAAAAA0AdDaGFubmVsQi1ESU1NMABCQU5LIDIAMDI5
>  RQAwMDAwMDAwMAA5ODc2NTQzMjEwAENNWTE2R1gzTTJBMjQwMEMxMQAAEhdhAAMC
>  AgAAAAAAAACAAAAAgAAAAIAAABQjYgAAAIAA////AGAAZQD/AgIAAIAAAAAAAAAA
>  AAAAAAAAAAARImMAWwD//wAAAAAAAAkAAQICAAAAAAMEBQYAAAAAAAAAQ2hhbm5l
>  bEItRElNTTEAQkFOSyAzAFtFbXB0eV0AW0VtcHR5XQA5ODc2NTQzMjEwAFtFbXB0
>  eV0AABIXZAADAgIAAAAAAAAAgAAAAIAAAACAAAATH2UAAAAAAP///wBbAAQAAAAA
>  AAAAAAAAAAAAAAAAAAB/BGgAAAA=
> 
> 
> Intel CPU
> 
> Name: Intel Core i7-3770
> Number of Cores: 4
> Threads per Core: 2
> Timer Frequency: 10 MHz
> Time Stamp Counter: Invariant
> Estimated Time Stamp Counter Frequency: 3569.86 MHz
> Estimated Time Stamp Counter Frequency Error: 0.27131 Mhz
> Time Stamp Counter Frequency: 3569.67 MHz
> 
> MSR Core #1
> 
>  MSR       EDX       EAX
>  000000CE  00081010  F0012200
>  00000198  000024AB  00002900
>  0000019C  00000000  882F0000
>  000001A2  00000000  00691400
>  000001B1  00000000  88290000
>  00000606  00000000  000A1003
>  00000611  00000000  A08266A1
>  00000639  00000000  B9D1A81B
>  00000641  00000000  00000000
> 
> MSR Core #2
> 
>  MSR       EDX       EAX
>  000000CE  00081010  F0012200
>  00000198  0000254F  00002900
>  0000019C  00000000  882E0000
>  000001A2  00000000  00691400
>  000001B1  00000000  88290000
>  00000606  00000000  000A1003
>  00000611  00000000  A08266A1
>  00000639  00000000  B9D1A81B
>  00000641  00000000  00000000
> 
> MSR Core #3
> 
>  MSR       EDX       EAX
>  000000CE  00081010  F0012200
>  00000198  000024AB  00002900
>  0000019C  00000000  882E0000
>  000001A2  00000000  00691400
>  000001B1  00000000  88290000
>  00000606  00000000  000A1003
>  00000611  00000000  A08266A1
>  00000639  00000000  B9D1A81B
>  00000641  00000000  00000000
> 
> MSR Core #4
> 
>  MSR       EDX       EAX
>  000000CE  00081010  F0012200
>  00000198  0000254F  00002900
>  0000019C  00000000  88290000
>  000001A2  00000000  00691400
>  000001B1  00000000  88290000
>  00000606  00000000  000A1003
>  00000611  00000000  A08266A1
>  00000639  00000000  B9D1A81B
>  00000641  00000000  00000000
> 
> MicroArchitecture: IvyBridge
> Time Stamp Counter Multiplier: 34
> 
> 
> Nvidia GPU
> 
> Name: NVIDIA GeForce GTX 1080
> Index: 0
> Driver Version: 460.79
> Driver Branch: r460_74-5
> 
> DeviceID: 0x1B8010DE
> SubSystemID: 0x119E10DE
> RevisionID: 0xA1
> ExtDeviceID: 0x1B80
> 
> Thermal Settings
> 
>  Sensor[0].Controller: GPU_INTERNAL
>  Sensor[0].DefaultMinTemp: 0
>  Sensor[0].DefaultMaxTemp: 127
>  Sensor[0].CurrentTemp: 69
>  Sensor[0].Target: GPU
> 
> Clocks
> 
>  Clock[8]: 5602500
>  Clock[9]: 11
>  Clock[10]: 571428
>  Clock[11]: 1
>  Clock[12]: 1325000
>  Clock[13]: 17
>  Clock[16]: 543500
>  Clock[17]: 1
>  Clock[18]: 27000
>  Clock[19]: 1
>  Clock[30]: 4176000
>  Clock[31]: 17
>  Clock[32]: 4050000
>  Clock[33]: 25
>  Clock[34]: 3746000
>  Clock[35]: 25
>  Clock[36]: 1296000
>  Clock[37]: 25
>  Clock[40]: 540000
>  Clock[41]: 1
>  Clock[44]: 108000
>  Clock[45]: 1
>  Clock[62]: 3
>  Clock[63]: 9
>  Clock[92]: 5602500
>  Clock[93]: 32
>  Clock[99]: 571428
>  Clock[100]: 32
>  Clock[106]: 1325000
>  Clock[107]: 32
>  Clock[120]: 543500
>  Clock[121]: 32
>  Clock[127]: 27000
>  Clock[128]: 32
>  Clock[169]: 4153816
>  Clock[170]: 32
>  Clock[176]: 4047204
>  Clock[177]: 15
>  Clock[183]: 3745338
>  Clock[184]: 15
>  Clock[190]: 1296000
>  Clock[191]: 6
>  Clock[204]: 540000
>  Clock[205]: 32
>  Clock[218]: 108000
>  Clock[219]: 32
>  Clock[281]: 3
>  Clock[282]: 32
> 
> Tachometer
> 
>  Value: 1827
> 
> P-States
> 
>  Percentage[0]: 14
>  Percentage[1]: 7
>  Percentage[2]: 0
>  Percentage[3]: 0
> 
> Usages
> 
>  Usage[1]: 1
>  Usage[2]: 14
>  Usage[3]: 40
>  Usage[4]: 30
>  Usage[5]: 1
>  Usage[6]: 7
>  Usage[7]: 58
>  Usage[8]: 50
>  Usage[9]: 1
>  Usage[11]: 40
>  Usage[12]: 35
>  Usage[13]: 1
>  Usage[15]: 100
>  Usage[16]: 100
> 
> Cooler Settings
> 
>  Cooler[0].Type: 1
>  Cooler[0].Controller: 1
>  Cooler[0].DefaultMin: 27
>  Cooler[0].DefaultMax: 100
>  Cooler[0].CurrentMin: 27
>  Cooler[0].CurrentMax: 100
>  Cooler[0].CurrentLevel: 46
>  Cooler[0].DefaultPolicy: 16
>  Cooler[0].CurrentPolicy: 16
>  Cooler[0].Target: 7
>  Cooler[0].ControlType: 2
>  Cooler[0].Active: 0
> 
> Fan Coolers Status
> 
>  Status: NOT_SUPPORTED
> 
> Memory Info
> 
>  Value[0]: 8388608
>  Value[1]: 8272896
>  Value[2]: 0
>  Value[3]: 8364536
>  Value[4]: 2697144
> 
> 
> 
> LPC Nct677X
> 
> Chip Id: 0xC560
> Chip Revision: 0x62
> Base Address: 0x0290
> 
> Hardware Monitor Registers
> 
>         00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
> 
>  0000   04 00 04 75 00 FF FF FF FF FF FF FF FF FF FF FF
>  0010   04 C1 04 C1 04 00 FF FF 40 86 BA BA 1F 17 BA 00
>  0020   93 7E CF CE 80 FF BA 20 FF FF FF DA 00 00 00 00
>  0030   00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF FF
>  0040   03 3E 07 FF DF 00 1F FF 2D FF FF 10 00 55 00 A3
>  0050   01 FF FF FF FF FF FF FF C1 FF FF FF FF 01 00 FF
>  0060   A0 FF FF FF FF 01 00 FF FF FF FF FF FF FF FF FF
>  0070   00 0A 00 2E 00 2E 00 2E 00 2E 00 2E 00 FF FF FF
>  00F0   00 00 00 00 00 00 00 00 00 00 00 00 33 FF FF FF
>  0100   10 00 00 01 01 01 01 3C 00 00 00 A8 00 FF FF FF
>  0110   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0120   00 1E 46 46 46 FF FF 99 FF FF FF FF FF FF FF FF
>  0130   FF 00 FF FF 00 4B 00 CC 02 01 00 00 00 00 00 00
>  0140   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 01 FF
>  0150   00 80 00 4B 00 50 00 FF FF FF FF FF FF FF FF FF
>  0200   10 32 40 01 01 01 01 3C 00 75 00 75 00 FF FF FF
>  0210   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0220   00 14 46 4B 4B FF FF 33 B2 FF FF FF FF FF FF FF
>  0230   FF 00 FF FF 00 4B 00 CC 02 01 00 00 00 00 00 00
>  0240   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 02 FF
>  0250   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0260   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0300   10 00 40 01 01 01 01 3C 00 C1 00 C1 00 FF FF FF
>  0320   00 1E 46 46 46 FF FF 99 FF FF FF FF FF FF FF FF
>  0330   FF 00 FF FF 00 4B 00 CC 02 01 00 00 00 00 00 00
>  0340   FF FF FF FF FF 00 00 FF FF FF FF FF FF FF 03 FF
>  0360   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0400   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>  0410   00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF FF
>  0420   FF FF FF 90 6A 90 6A ED AF 06 FF FF FF FF FF FF
>  0440   FF FF 00 00 FF FF FF FF FF FF 00 00 00 00 04 FF
>  0450   03 73 FF FF 00 00 00 FF FF 1E 13 33 09 FF FF FF
>  0460   FF 01 00 00 00 00 00 00 FF FF FF FF FF FF FF FF
>  0480   93 7E CF CE 80 FF BA D4 D2 86 BA BA 1F 17 BA 00
>  0490   20 00 00 00 00 00 00 33 80 2E 2E 2E 2E 2E 00 FF
>  04B0   FF 1F FF 1F 22 00 1A 03 FF 1F FF FF FF FF FF FF
>  04C0   00 00 00 00 04 D8 06 50 00 00 FF FF FF FF FF FF
>  04F0   2E 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF
>  0500   FF FF 00 00 00 06 00 FF 0F FF FF FF FF 00 00 FF
>  0550   D4 D2 00 FF 00 00 00 00 00 00 00 00 00 00 00 00
>  0560   00 00 00 00 00 00 7F 3F 3F FF FF FF FF FF FF FF
>  0600   00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF
>  0610   FF 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF
>  0620   FF 01 02 FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0630   FF 1F FF 1F 22 00 1A 03 FF 1F FF 1F FF 1F FF 1F
>  0640   FF 1F FF 1F 02 02 02 02 02 FF FF FF FF FF 06 FF
>  0650   7F 7F 7F 7F FF FF 00 00 00 00 04 D8 06 50 00 00
>  0660   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0670   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0700   FF 95 02 10 00 00 00 00 00 59 00 00 00 00 00 00
>  0710   00 00 00 00 00 00 00 F5 4E F8 80 F8 80 F8 80 01
>  0720   2E 00 06 00 00 00 EF 48 00 EF 00 00 00 00 00 00
>  0730   00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0800   10 00 40 01 01 01 01 3C 00 C1 00 C1 00 FF FF FF
>  0820   00 1E 46 46 46 FF FF 99 FF FF FF FF FF FF FF FF
>  0830   FF 00 FF FF 00 4B 00 CC 02 01 00 00 00 00 00 00
>  0840   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 08 FF
>  0900   10 00 00 01 01 01 01 3C 00 00 00 AD 00 FF FF FF
>  0920   00 1E 46 46 46 FF FF 99 FF FF FF FF FF FF FF FF
>  0930   FF 00 FF FF 00 4B 00 CC 02 01 00 00 00 00 00 00
>  0940   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 09 FF
>  0960   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0A00   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0A10   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0A20   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0A30   FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
>  0A40   FF FF FF FF FF FF FF FF FF FF FF FF FF FF 0A 0A
>  0A50   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0A60   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0A70   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0B00   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0B10   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0B20   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0B30   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0B50   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0B60   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0B70   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0C00   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0C10   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0C20   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0C30   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0C50   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0C60   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0C70   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0D00   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0D10   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0D20   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0D30   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0D50   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0D60   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0E00   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0E10   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0E20   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0E30   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0F00   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0F10   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0F20   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  0F30   0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A 0A
>  8040   03 00 00 FF DF 00 1F FF 2D FF FF 10 00 55 80 5C
>  80F0   00 00 00 00 00 00 00 00 00 00 00 00 33 FF FF FF

**Comment by Rem0o** [comment]
Any log.txt file in your app folder?

**Comment by JordanMunroe** [comment]
Sure is! With a stack trace and everything. I was wondering why the "logs" that got copied to clipboard were devoid of any useful information.

[log.txt](https://github.com/Rem0o/FanControl.Releases/files/5697646/log.txt)

**Comment by Rem0o** [comment]
Could you expand your controls cards?

**Comment by Rem0o** [comment]
Try removing the matched RPMs on your control cards.
