### ISSUE TITLE
Fan Detection Issue? Fan RPM flashing/toggling 850 then1450

### ISSUE THREAD

**Issue by FynnApp** [Rem0o/FanControl.Releases#920]
### Discussed in https://github.com/Rem0o/FanControl.Releases/discussions/919

<div type='discussions-op-text'>

<sup>Originally posted by **FynnApp** July  4, 2022</sup>
First post, new user, planning donate for sure if this works on my system. The concept seems great but I am new to this and not sure if I am able to make it run properly.

Question: My CPU fan (top front radiator) is 3pin standard 120mm fan that came with system. I created cpu and gpu curves as well as a "mix" curve set to max detection. Seems to be working fine with logical fan speeds on the fans but...

CPU fan (mentioned above) is set to mix curve but speed flashes (toggles) between 850rpm to 1450rpm. Fan is set to DC in BIOS and Smart Fan box is not ticked. This is the only fan (Apevia standard 120 3 pin) that does this particular behavior.

Also, the bottom radiator fan, 3pin 120mm standard, shows 1700-1800rpm but curve is at 53%, visual inspection indicates fan is turning slower than that for sure., when set to 100% manual only reaches 1600rpm (?) </div>

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
