### ISSUE TITLE
FC won't start with windows when login into a standard (non-admin) account

### ISSUE THREAD

**Issue by asheenlevrai** [Rem0o/FanControl.Releases#921]
Hey :)

I recently installed Fan Control and it seems to work alright except for the following:

Even though I specified in the settings that FC should start (minimized) with windows, it only does so when login into an admin account. FC doesn't start automatically when login into a standard user account. From there, I can start FC manually, though (UAC prompt). So I could just setup a shortcut to start FC manually but it would be more convenient (and coherent) if the setting actually allowed FC to start with windows, regardless of the type of user account, right?

Thank you very much in advance for your help and congratulation on the app and success you got among youtubers ;)

Best,
-a-

**Comment by Rem0o** [comment]
You should be able to configured the scheduled task named "FanControl" to use the user you want with the right privilege.

**Comment by asheenlevrai** [comment]
Thanks,
I'll look it up.
However, if you can teach me or point to a tutorial, I'd appreciate it ;)

Best,
-a-

**Comment by asheenlevrai** [comment]
OK @Rem0o here is what I did:
 - went into Windows Task Scheduler
 -  FanControl->Properties->General
 - switched to "Run Whether user is logged in or not"
 - clicked OK and input the admin password.

Now what happens is that FanControl starts with windows alright. However, the tray temperature indicator is no longer displayed. If I re-launch FanControl (I'm not sure if this creates a 2nd instance or if it just displayed the one that was already running), UAC pops up and the tray icon displays temperature (after I input the password in UAC).

Anyway I could "fix" this?

Thanks a lot for your help.

Best,
-a-

**Comment by Rem0o** [comment]
You can't have a tray icon for a single instance across multiple users/sessions. The way you have it set up, it runs "headless", meaning there is no UI available since a UI needs a specific user.

"Relaunching" it, I would check in the "Details" section of task manager if there is only one instance.

**Comment by asheenlevrai** [comment]
Thanks :)

**Comment by ThisIsStupidGitHub** [comment]
Is there a way to set it up to not run 'headless'? When i launch it again, it does still run only one instance, but it switches the user running it (i know this because i setup Task Schedule to run under System).
