### ISSUE TITLE
CPU Package not appearing for CPU Temp

### ISSUE THREAD

**Issue by brunoafonsos** [Rem0o/FanControl.Releases#927]
Hey guys, been loving the program but something is bugging me since I started using (couple of weeks ago)

The CPU Package is not showing in the list of thermal indicators to use. I have a B550i Asus ROG motherboard. The main problem with this is that the CPU indicator from the motherboard is very different in temps than the actual Core from my Rynze 5 5600x.

![image](https://user-images.githubusercontent.com/108899299/177860802-234eca2d-6a2e-47d1-9118-48763ed4ec71.png)

Is there any way of solving this issue?

Just to point out, within HWInfo it shows the CPU Package. Is there any bad configuration that I did? Thanks for creating an amazing program!

**Comment by Rem0o** [comment]
See README for hardware compatibility.  Will close.
Feel free to contribute if you got the resources necessary to add such implementation of a CPU package sensor for your board.
