### ISSUE TITLE
Graph showing NaN% instead of 0

### ISSUE THREAD

**Issue by Wolphin5** [Rem0o/FanControl.Releases#928]
Configuration Details:
I have a Custom Sensor which takes the Water Temp Out (Pass through on the exit of the block before the rad), and subtracts Water Temp In (Sensor is on my water Pump), to get the delta-T (change in temp) for the loop.
![image](https://user-images.githubusercontent.com/44385601/178089692-ebaeede8-f753-4409-beb1-5ab969690b51.png)

This Custom Sensor is then used in a graph to control the temp for the pump.
 ![image](https://user-images.githubusercontent.com/44385601/178089686-4caac8c4-e463-435e-a1e1-833995596abb.png)

Often, if I have the pump running 75% or higher, the water is flowing fast enough that there is no detectable difference (it takes only 2-3s by my calculation to have the whole loop's volume cycle the loop).  

Not sure if this is expected, as in this case 0C is actually an expected value (I could even see -1 if I had a sudden decrease in use), not an error.

**Comment by Rem0o** [comment]
Right now 0 and below are unexpected values, hence the NaN. I plan to change that soon to make your kind of scenario work.

**Comment by Rem0o** [comment]
See V125.
