### ISSUE TITLE
Curve does not work

### ISSUE THREAD

**Issue by griffin-warrior** [Rem0o/FanControl.Releases#929]
Curve does not work for ASUS ATS GeForce RTX3050-O8G-GAMING. Fans stop working and never spin if they are linked to any curves I created. 
![Snipaste_2022-07-09_14-23-15](https://user-images.githubusercontent.com/29499271/178094379-43fad161-a91b-4fb5-9f84-9e7457d92fea.png)

**Comment by Rem0o** [comment]
Expand those NVIDIA control cards so we can see the settings?

**Comment by griffin-warrior** [comment]
> Expand those NVIDIA control cards so we can see the settings? Does manual mode work?

Yes, manual mode do work. I don't know what the problem is. 
But after I tried to disable `NvApiWrapper` in Sensor Settings, save and then enable it again, another two new control cards appeared, which were automatically linked to the two fans on my video card.
Now these two new control cards are working fine with any curves.
