### ISSUE TITLE
ITE IT8686e sensor 

### ISSUE THREAD

**Issue by neilangierof** [Rem0o/FanControl.Releases#93]
While playing Cyberpunk 2077, the CPU tends to get quite warm and I noticed this causes the sensors on my mobo (Gigabyte z370 Gaming 7) to crash and disappear! Is there any way to map control to the other sensor (ITE IT8792E) instead?

Edit: I'm just trying to link PWM fan speeds to GPU temps.

**Comment by Rem0o** [comment]
ITE IT8792E is not supported.
