### ISSUE TITLE
Can't turn of fans with Asus motherboard 

### ISSUE THREAD

**Issue by beyondthemind91an** [Rem0o/FanControl.Releases#930]
Hi Rem0o,

I have a Asus Prime B560 plus. In the Ai Suite (fan xpert) I'm able to turn every fan completely off except for the CPU header, as it usually is. However, not in the FanControl software. That is, if I set a fan to 0% it still runs. I am however able to turn a fan completely off in FanControl if I first in Ai Suite turn off all the fans, close Ai Suite and then open FanControl. However, now I can't ramp the fans up above the lowest rpm that Ai Suite detected they can run. The program, FanControl, says it is sending a 100% speed signal, but the fans doesn't exceed around 500rpm. It is like I have to choose between:
500 to 2000rpm
Off/500rpm

It is like it can't trigger either one of the desired funktions. Do you have any idea why this is happening?

**Comment by beyondthemind91an** [comment]
@Rem0o 
After looking into the data files of Asus Ai Suite (Fan Xpert) i noticed something. It seems that Fan Xpert changes turns of the fan by changing the header into rpm-mode and then dropping the voltage down to nothing. That also explains why i cant crank the fans above 500rpm when I first in Ai Suite turn off the fans and then tries to fire them upp in Fan Control. And also explains the other way around, that when I have the fans on in Ai Suite and then tries to turn them oss in Fan Controll, they wont because it doesent turn the voltage to the fans off.

Here is the code of the file I found:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root>
<fan key="0">
<name>CPU Fan</name>
<rpmtable>
<rpm_0>500</rpm_0>
<rpm_1>506</rpm_1>
<rpm_2>549</rpm_2>
<rpm_3>700</rpm_3>
<rpm_4>862</rpm_4>
<rpm_5>1107</rpm_5>
<rpm_6>1336</rpm_6>
<rpm_7>1553</rpm_7>
<rpm_8>1776</rpm_8>
<rpm_9>1864</rpm_9>
<rpm_10>1864</rpm_10>
</rpmtable>
<pwmrpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>0</rpm_3>
<rpm_4>0</rpm_4>
<rpm_5>0</rpm_5>
<rpm_6>0</rpm_6>
<rpm_7>0</rpm_7>
<rpm_8>0</rpm_8>
<rpm_9>0</rpm_9>
<rpm_10>0</rpm_10>
</pwmrpmtable>
<dcrpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>0</rpm_3>
<rpm_4>0</rpm_4>
<rpm_5>0</rpm_5>
<rpm_6>0</rpm_6>
<rpm_7>0</rpm_7>
<rpm_8>0</rpm_8>
<rpm_9>0</rpm_9>
<rpm_10>0</rpm_10>
</dcrpmtable>
<maxdutytokeepstill>22</maxdutytokeepstill>
<mindutytokeepruning>0</mindutytokeepruning>
<rpmofmaxdutytokeepstill>522</rpmofmaxdutytokeepstill>
<rpmofmindutytokeepruning>0</rpmofmindutytokeepruning>
<rpmlimitation>0</rpmlimitation>
<effectiveduty>0</effectiveduty>
<stddeviationofmaxrpm>4</stddeviationofmaxrpm>
<issupporteddualmode>0</issupporteddualmode>
<durationofmaxspeed>0</durationofmaxspeed>
<haspwm>1</haspwm>
<dualmodeenable>0</dualmodeenable>
<newcriticaltempenable>0</newcriticaltempenable>
</fan>
<fan key="1">
<name/>
<rpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>582</rpm_3>
<rpm_4>777</rpm_4>
<rpm_5>971</rpm_5>
<rpm_6>1165</rpm_6>
<rpm_7>1360</rpm_7>
<rpm_8>1554</rpm_8>
<rpm_9>1748</rpm_9>
<rpm_10>1943</rpm_10>
</rpmtable>
<pwmrpmtable>
<rpm_0>526</rpm_0>
<rpm_1>526</rpm_1>
<rpm_2>526</rpm_2>
<rpm_3>700</rpm_3>
<rpm_4>872</rpm_4>
<rpm_5>1095</rpm_5>
<rpm_6>1331</rpm_6>
<rpm_7>1542</rpm_7>
<rpm_8>1785</rpm_8>
<rpm_9>1904</rpm_9>
<rpm_10>1943</rpm_10>
</pwmrpmtable>
<dcrpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>366</rpm_3>
<rpm_4>399</rpm_4>
<rpm_5>422</rpm_5>
<rpm_6>447</rpm_6>
<rpm_7>454</rpm_7>
<rpm_8>466</rpm_8>
<rpm_9>475</rpm_9>
<rpm_10>526</rpm_10>
</dcrpmtable>
<maxdutytokeepstill>29</maxdutytokeepstill>
<mindutytokeepruning>25</mindutytokeepruning>
<rpmofmaxdutytokeepstill>563</rpmofmaxdutytokeepstill>
<rpmofmindutytokeepruning>481</rpmofmindutytokeepruning>
<rpmlimitation>526</rpmlimitation>
<effectiveduty>22</effectiveduty>
<stddeviationofmaxrpm>0</stddeviationofmaxrpm>
<issupporteddualmode>1</issupporteddualmode>
<durationofmaxspeed>0</durationofmaxspeed>
<haspwm>1</haspwm>
<dualmodeenable>1</dualmodeenable>
<newcriticaltempenable>1</newcriticaltempenable>
</fan>
<fan key="2">
<name/>
<rpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>431</rpm_3>
<rpm_4>574</rpm_4>
<rpm_5>718</rpm_5>
<rpm_6>862</rpm_6>
<rpm_7>1005</rpm_7>
<rpm_8>1149</rpm_8>
<rpm_9>1293</rpm_9>
<rpm_10>1436</rpm_10>
</rpmtable>
<pwmrpmtable>
<rpm_0>440</rpm_0>
<rpm_1>440</rpm_1>
<rpm_2>440</rpm_2>
<rpm_3>538</rpm_3>
<rpm_4>673</rpm_4>
<rpm_5>828</rpm_5>
<rpm_6>981</rpm_6>
<rpm_7>1125</rpm_7>
<rpm_8>1262</rpm_8>
<rpm_9>1371</rpm_9>
<rpm_10>1437</rpm_10>
</pwmrpmtable>
<dcrpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>0</rpm_3>
<rpm_4>0</rpm_4>
<rpm_5>0</rpm_5>
<rpm_6>209</rpm_6>
<rpm_7>267</rpm_7>
<rpm_8>321</rpm_8>
<rpm_9>378</rpm_9>
<rpm_10>440</rpm_10>
</dcrpmtable>
<maxdutytokeepstill>24</maxdutytokeepstill>
<mindutytokeepruning>20</mindutytokeepruning>
<rpmofmaxdutytokeepstill>344</rpmofmaxdutytokeepstill>
<rpmofmindutytokeepruning>284</rpmofmindutytokeepruning>
<rpmlimitation>440</rpmlimitation>
<effectiveduty>25</effectiveduty>
<stddeviationofmaxrpm>0</stddeviationofmaxrpm>
<issupporteddualmode>1</issupporteddualmode>
<durationofmaxspeed>0</durationofmaxspeed>
<haspwm>1</haspwm>
<dualmodeenable>1</dualmodeenable>
<newcriticaltempenable>1</newcriticaltempenable>
</fan>
<fan key="3">
<name>Chassis Fan 3</name>
<rpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>921</rpm_2>
<rpm_3>1195</rpm_3>
<rpm_4>1468</rpm_4>
<rpm_5>1730</rpm_5>
<rpm_6>1936</rpm_6>
<rpm_7>2070</rpm_7>
<rpm_8>2272</rpm_8>
<rpm_9>2445</rpm_9>
<rpm_10>2571</rpm_10>
</rpmtable>
<pwmrpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>0</rpm_3>
<rpm_4>0</rpm_4>
<rpm_5>0</rpm_5>
<rpm_6>0</rpm_6>
<rpm_7>0</rpm_7>
<rpm_8>0</rpm_8>
<rpm_9>0</rpm_9>
<rpm_10>0</rpm_10>
</pwmrpmtable>
<dcrpmtable>
<rpm_0>0</rpm_0>
<rpm_1>0</rpm_1>
<rpm_2>0</rpm_2>
<rpm_3>0</rpm_3>
<rpm_4>0</rpm_4>
<rpm_5>0</rpm_5>
<rpm_6>0</rpm_6>
<rpm_7>0</rpm_7>
<rpm_8>0</rpm_8>
<rpm_9>0</rpm_9>
<rpm_10>0</rpm_10>
</dcrpmtable>
<maxdutytokeepstill>15</maxdutytokeepstill>
<mindutytokeepruning>0</mindutytokeepruning>
<rpmofmaxdutytokeepstill>460</rpmofmaxdutytokeepstill>
<rpmofmindutytokeepruning>0</rpmofmindutytokeepruning>
<rpmlimitation>0</rpmlimitation>
<effectiveduty>0</effectiveduty>
<stddeviationofmaxrpm>7</stddeviationofmaxrpm>
<issupporteddualmode>0</issupporteddualmode>
<durationofmaxspeed>0</durationofmaxspeed>
<haspwm>0</haspwm>
<dualmodeenable>0</dualmodeenable>
<newcriticaltempenable>0</newcriticaltempenable>
</fan>
<hastune>1</hastune>
<haschangefan>0</haschangefan>
<fan_pos key="2">
<position>1</position>
</fan_pos>
<fan_pos key="1">
<position>2</position>
</fan_pos>
</root>

**Comment by wcoleman320** [comment]
This is very interesting, I am also interested. There is a bios level lock at a minimum PWM%, but a fan expert (not the bios) can send a message to lower the PWM range. It would be very nice to be able to implement that with fan control. However, this might be an issue for Libre Hardware Monitor.

**Comment by Rem0o** [comment]
As @wcoleman320 suggests, it's a backend level implementation detail that seems to be specific to Asus boards which changes the range available with the control chip.  This notion is not available in LHM, and would hardly make sense being implemented in there with the current common interfaces across different boards.

**Comment by jaivu** [comment]
Try running CPU-Z at least once, then Fan Control works for me.

**Comment by beyondthemind91an** [comment]
Well this is interesting. I just changed some fans, for example i connected the graphics card fan to header 3 on the motherboard. I'm still using it in PWM mode, but now I'm able to turn it of completely. Not header 1 though.
