### ISSUE TITLE
FanControl Closes immediately

### ISSUE THREAD

**Issue by IcebearForPresident** [Rem0o/FanControl.Releases#931]
FanControl just closes immediately if i try to open it.

I deleted the folder and downloaded the newest version and the same thing happened again. 

When I try to install it it open a blank window, you can see in the upper left corner FanControl V119 (userConfig.json) and then after a second it closes immediately.

Any Idea how to fix this?

**Comment by Rem0o** [comment]
Windows version? Mobo?

**Comment by IcebearForPresident** [comment]
I'm using windows 11 and I have a ROG Strix B550-F. A few Day ago it worked, but suddenly Fan Control had stoped working for me.

**Comment by Rem0o** [comment]
Any eventviewer event? A log.txt next tot he exe?

**Comment by IcebearForPresident** [comment]
This is the log from right now:
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9079489/log.txt)

**Comment by Rem0o** [comment]
From the look of it, something is wrong with your config. 

Try and move the CACHE file and any .json config file out of your folder, and see if it launches.

**Comment by IcebearForPresident** [comment]
If I remove the .json file it does the same thing as before but without creating a log file.

What is the cache file?

**Comment by Rem0o** [comment]
> What is the cache file?

There is a file simply called "CACHE" that gets created which hold some basic information that is used globally by the software.

**Comment by rollingmoai** [comment]
> > What is the cache file?
> 
> There is a file simply called "CACHE" that gets created which hold some basic information that is used globally by the software.

This seems to be poorly named. A "cache" is usually referred to data that is temporarily stored. Maybe rename it to something like `settings.json`?

**Comment by efesa1** [comment]
Hi I am having the exact same issue. It was working fine a few days ago. I am getting the following message in the log file:

7/17/2022 5:44:46 PM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR
   at FanControl.Models.NVApiControlSensor.HandleException(NVIDIAApiException exception)
   at FanControl.Models.NVApiControlSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Update()
   at FanControl.Domain.ApplicationClock.DoActions()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by efesa1** [comment]
Hi, any thoughts on this issue?
