### ISSUE TITLE
119 update causes my EVGA AIO to disconnect and reconnect randomly

### ISSUE THREAD

**Issue by haoohao** [Rem0o/FanControl.Releases#936]
The new update seems to cause my AIO to disconnect and reconnect randomly. It stopped after I stopped using the fan software. 
I'm not sure if anyone else having this issue.

**Comment by Rem0o** [comment]
Go into sensor settings, and maybe remove the "controller" section checkbox, see if that helps.  You should only keep in their what you are using, nothing else.

**Comment by haoohao** [comment]
> Go into sensor settings, and maybe remove the "controller" section checkbox, see if that helps. You should only keep in their what you are using, nothing else.

Hi, I checked and the sensor for the controller is unchecked and I believe it has been unchecked since I started using Fancontrol months ago.
