### ISSUE TITLE
FanControl shut down PC

### ISSUE THREAD

**Issue by MatejVanObi** [Rem0o/FanControl.Releases#937]
Hi, im new one and try that program, but i have issue to install or run it. When i first start it and try to configurate all program just shut down my PC. What can be wrong? Should i need to uninstall any program related to fan controling?

 Below is link to my video of problem.

https://we.tl/t-W4xpwe1GaQ

Tnx for help.

Best regards, Matej

**Comment by Rem0o** [comment]
There has to be one of the sensor source that is badly implemented with something you got in your rig. If I were you, I would untick every sensor source until I find the culprit. Else, I would not use the software.

**Comment by mtbossa** [comment]
> There has to be one of the sensor source that is badly implemented with something you got in your rig. If I were you, I would untick every sensor source until I find the culprit. Else, I would not use the software.

What do you mean by "sensor source". It's something in the software?

**Comment by mtbossa** [comment]
> ![image](https://user-images.githubusercontent.com/14118956/180326387-458789de-34fa-4300-9c11-a172dad08cc0.png)

Even if I uncheck all of them, my computer restarts. I have a Fan #4, which is a 3-pin fan connected to my SYS_FAN3 header. The fan itself is spinning, however, Fan #4 control is showing 0 RPM. I've notice that every time I try to manual control this fan (Control #4), when I tick the "Manual Control", my computer restarts. I'm also getting some errors sometimes: 

> https://gist.github.com/mtbossa/8450e8eaebf6ea976e0dce406753defc
