### ISSUE TITLE
Not properly controlling fan speeds

### ISSUE THREAD

**Issue by sduford** [Rem0o/FanControl.Releases#942]
### Discussed in https://github.com/Rem0o/FanControl.Releases/discussions/941

<div type='discussions-op-text'>

<sup>Originally posted by **sduford** July 15, 2022</sup>
When using a curve based on CPU temperature, whether it is a custom curve, an auto curve, a sync curve or a linear curve, my Noctua CPU cooler fans stay at zero RPM and my Scythe Kaze Flex case fans stay between about 200 RPM (60% PWM) and up to a max of 360 RPM (100% PWM). (their max RPM is 1800. )

I tried switching to manual control to see if the curve was the problem, the CPU cooler fans (Noctua PWM) remain at zero RPM, no matter what. The Scythe case fans follow the same pattern as with a curve, 60% = 200 RPM and 100% = 350 RPM. 

I have an ASUS X-570 Tuf Gaming Plus motherboard and no external fan controller. The motherboard has no issues controlling the fans and before installing Fan Control, I was using ASUS' AI Suite 3/Fan Expert, and it had no issues controlling them either...

Any advice on how to resolve this issue?</div>

**Comment by Rem0o** [comment]
Asus boards have a weird mechanism that limits the available RPM range, either by dropping the 12V line then using PWM on top, or I don't know exactly. See https://github.com/Rem0o/FanControl.Releases/issues/930.

Asus proprietary software uses this functionality, but it messes up third party control.

**Comment by sduford** [comment]
OK thanks, I guess its back to Fan Xpert then.

**Comment by jaivu** [comment]
> OK thanks, I guess its back to Fan Xpert then.

My only solutions as of this moment is you run CPU-Z at startup, then Fan Control. Mobo is Asus TUF B450 .

**Comment by sduford** [comment]
> 

Wow, that actually works! 

Thanks a lot
