### ISSUE TITLE
Cannot find program in startup menu

### ISSUE THREAD

**Issue by Suhycide** [Rem0o/FanControl.Releases#943]
I'm trying to remove Fan Control from my startup menu and i had unchecked it from "start with windows" but it always starts with windows still with the 4 windows opening up automatically, help please lol

**Comment by Rem0o** [comment]
The program uses the Task Scheduler to start with Windows. Make sure no hanging tasks lies in there.

**Comment by Suhycide** [comment]
I'm not exactly sure what im looking for but i dont see anything that says "fancontrol" at all ot anything that looks to me like it would be related (i dont know much software stuff i just came here because of Jay's video, i love the way this program regulates my temps) but it still starts with windows opening those 3 windows on startup and restart of the system

**Comment by Impact123** [comment]
[Autoruns](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns) may be helpful to you.
