### ISSUE TITLE
Auto Curve bugs

### ISSUE THREAD

**Issue by MichaelDavidGK** [Rem0o/FanControl.Releases#944]
Bugs found in both V119 and V120

- response time is not working normally, fan speed goes up/down instantly (works only when hitting load temp. or deadband? unsure about that [deadband seems to be broken] = waits set time till instantly going down);
- since response time is not working step is not working either, but I have a feeling it isn't even working since it changes fan speed instantly by 30% or more and not doing any steps;
- Deadband not working properly? I am definitely not in the range at that moment, or am I misunderstanding smth? (When lowering deadband by just 2-5 the fan speed went to the same value as on the left)
![image](https://user-images.githubusercontent.com/39009683/179329733-6c760453-ce71-4674-b485-a4507deacfc0.png) 
- very rarely this can happen = 2 issues there:
exact same settings, but different fan speed, sometimes the difference is much bigger 
temp is quite high but fan speed extremely low (this was like 30 seconds on stress test)
I cannot really replicate this, happens randomly
![image](https://user-images.githubusercontent.com/39009683/179332850-6c711538-62ac-48f7-bf13-f76b23fc95f8.png)

**Comment by Rem0o** [comment]
The auto fan curve has a really "knows what's best" behavior. Some of the parameters only affect load scenarios ( close to load temp ), and will be ignored at idle. Also, the fan curve has built-in state/memory, which means two auto fan curves that were created one after the other might not have the same output.  I should probably document it better.

Since you seem to be very specific about your needs/ wanted behaviors, I would not use this specific fan curve, and would instead rely on "pure" fan curve type, basically any other type.

**Comment by MichaelDavidGK** [comment]
I'm fine with using multiple targets and mixing them and using it like
this.
It suits my needs better when my PC gets too hot and it runs fans on high
rotation till it's back to normal idle temps (for example 50°C = 50% fans,
60°C = 70% , 75°C =100% with long response time for cooling down and mix
set to highest value so it will cool down my PC no matter what temp it had
and will stay on idle temps afterwards).
I made it even more complicated by now, but it would take ages to explain
and I'm abroad right now so can't really show my configuration.

However I still think Auto should have some kind of stepping and not adjust
instantly (or step percentage to work whole the time not only around load
temp/deadband, but with high default value or even 2 step settings, 1 for
going up and 1 for going down).

You could also change names of response time to something like slow down
delay, for better understanding, since it works like this on auto.

As you also seen my deadband was on 18°C but it was triggered when it was
on 22°C range. I might have tried to explain it in my own complicated way
of thinking, but this is what I meant.

**Comment by MichaelDavidGK** [comment]
@Rem0o 
![image](https://user-images.githubusercontent.com/39009683/182971445-bba3c061-2f04-4ae0-92c3-1fd75e84ca00.png)
Found another bug, when changing configs GPU goes instantly to 0 even tho step down is set to 1%/s unlike everything else honoring the setting

**Comment by Rem0o** [comment]
Changing config is basically a hard reset and the software "restarts" internally, it doesn't have any control over the transition.
