### ISSUE TITLE
Not detecting controls nor speed of water pump

### ISSUE THREAD

**Issue by Mourdraug** [Rem0o/FanControl.Releases#945]
I have the water pump connected to W_PUMP+ header on Asus Crosshair Hero VII I can see the pump speed in hw info but Fan Control doesn't show it, it also doesn't detect this header at all. I guess I could simply connect pump to the fan header since it's powered directly from psu, but is there a way to directly control the W_PUMP+ header?
EDIT: I also noticed that it does not detect all the temperatures from mobo, it seems to detect WATER_IN just fine, but not WATER_OUT, mobo is Asus Crosshair Hero VII it uses IT8665E chip afaik

**Comment by Mourdraug** [comment]
My bad did not rea thoroughly enough, I managed to work around it by creating a plugin to read required temps (https://github.com/Mourdraug/FanControl.AsusWMI if someone needs it) and connecting pump to CPU fan header which can be controlled from fancontrol.

**Comment by NolonQ** [comment]
> My bad did not rea thoroughly enough, I managed to work around it by creating a plugin to read required temps (https://github.com/Mourdraug/FanControl.AsusWMI if someone needs it) and connecting pump to CPU fan header which can be controlled from fancontrol.

Can't get this working, opened a sperata issue here https://github.com/Rem0o/FanControl.Releases/issues/2241

And the code you shared doesn't work for me.

PS C:\Windows\system32> $asushw = Get-CimInstance -Namespace root/wmi -ClassName ASUSHW
PS C:\Windows\system32> Invoke-CimMethod $asushw -MethodName sensor_get_version
Invoke-CimMethod : Method "sensor_get_version" not found
At line:1 char:1

    Invoke-CimMethod $asushw -MethodName sensor_get_version

      + CategoryInfo          : ObjectNotFound: (ASUSHW (Instanc...C14\ASUSWMI_0"):CimInstance) [Invoke-CimMethod], CimE
     xception
      + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand
