### ISSUE TITLE
Fans on GPU will not turn on after upgrading

### ISSUE THREAD

**Issue by powpow-git** [Rem0o/FanControl.Releases#946]
I had a fan control setup with my previous gtx1660 Super GPU and upgraded to a rtx 3060 today. I was running a Unigine Valley benchmark on the card to test it and was shocked to see my temps go up over 90 degrees c and the card had to downclock itself and then I noticed the fan speed at 0%. At first I thought my card had defective fans, but then I remembered I was using your software and when I closed it and ran benchmark again the fans started working. I did a startup configuration in FanControl and works as it should now, so maybe implement a auto detect of changed hardware feature so you are prompted to reconfigure settings to detect new hardware properly.

**Comment by Rem0o** [comment]
Technically, the id of the new hardware would be different, and FanControl wouldn't be enabled for your new GPU fans, since you never configured them. Or did you? Without seeing the state of your settings when that event occured, hard to say exactly what was going on.

**Comment by powpow-git** [comment]
Right it was still configured for the 1660 Super, but maybe implement an update to the program that detects hardware changes and prompts for a sensor rescan or something. As the fans started working after I did the startup sensor scan.
