### ISSUE TITLE
Allow response time in the target curve

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [Rem0o/FanControl.Releases#95]
I am currently using the target fan curve to manage my fans during mostly non-intensive workloads, such as internet browsing. My curve looks like this

![image](https://user-images.githubusercontent.com/51249734/102665400-e6737600-41d8-11eb-8395-bf0fd9704f20.png)

![image](https://user-images.githubusercontent.com/51249734/102665336-d360a600-41d8-11eb-8875-225a18a58bed.png)

I have my idle fan speed at the absolute maximum speed that will not annoy me i.e. going 1% higher will annoy me, which is also why lowering the step % won't help, and my load fan speed at 100% because I want the CPU to be cooled as effectively and fast as possible if the system is under prolonged load. The problem with this is that if my temperature spikes briefly, e.g. 1-3 seconds, my fans will go to 100% and annoy me. The solution to this would be the response time. It should behave as such, assuming a 3 second response time: 

1. load temperature is reached  (current count = 0 sec)
2. wait 1 second 
3. check if current temperature is at or above load temperature (current count = 1 sec)
- if so, continue to step 4
- if not, stop checking and restart count
4. wait 1 second
5. check if current temperature is at or above load temperature (current count = 2 sec)
- if so, continue to step 6
- if not, stop checking and restart count
6. wait 1 second
7. check if current temperature is at or above load temperature (current count = 3 sec)
- if so, set fans to load speed/state
- if not, stop checking and restart count

**Comment by Rem0o** [comment]
I already have this behavior in other types of fan curves, could merge it to the Target without any issue.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V60

**Comment by asdsadsaasd12312132** [comment]
> https://github.com/Rem0o/FanControl.Releases/releases/tag/V60

Will setting the response time to 1 sec have the same behaviour from V59 i.e. instant changes because I still want that while gaming? I just use a response time while I am idling.

**Comment by Rem0o** [comment]
Yes, 1 sec is like the previous behavior.
