### ISSUE TITLE
Proms after every update keep showing

### ISSUE THREAD

**Issue by melcarthus** [Rem0o/FanControl.Releases#950]
I can't exactly remember if it always had these issues, or if it was only in the last couple of updates. But everytime when I start windows I get the donation pop-up and the 'scan pop-up' although I have checked the boxes to not show this again each time.

I seems it only does this when I've restarten or booted up the system. If afterwards i close fan controle and open it again i'm not getting the donation pop-up nor the scan pop-up.

Here is my report if it helps.
https://pastebin.com/1PXcRZ9h

**Comment by Rem0o** [comment]
Look at the task in the task scheduler, make sure the "start in" folder is correct.
