### ISSUE TITLE
GPU sensor lost after driver update

### ISSUE THREAD

**Issue by WaynGames** [Rem0o/FanControl.Releases#954]
Hello,
I have a 3080 Ti from MSI and after updating the driver using gforce experience I now have this erroir message in the Fan Control logs : 

18/07/2022 21:17:35: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_ERROR
   à NvAPIWrapper.Native.GPUApi.GetClientFanCoolersStatus(PhysicalGPUHandle gpuHandle)
   à NvAPIWrapper.GPU.GPUCoolerInformation.<get_Coolers>d__2.MoveNext()
   à System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   à System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Open()
18/07/2022 21:17:35: NVApi could not initialize or has no sensors. See the error log for more details.

And I lost the GPU sensor and fan control...
Any idea how to fix it ?

**Comment by WAYN-Games** [comment]
NVM, will post in NvAPI github issue.
