### ISSUE TITLE
Feature request read lines of a file

### ISSUE THREAD

**Issue by IFD3** [Rem0o/FanControl.Releases#956]
I have some programs like t-balancer which writes values in files for programs like Samurize.
Is it possible to read lines from a File like this too?

One file for example looks like this:

> Innenluft
> 33,5
> MOSFET
> 50,0
> Sensor D2
> 0,0
> Sensor D3
> 0,0
> Sensor D4
> 0,0
> Sensor D5
> 0,0
> Sensor D6
> 0,0
> Sensor D7
> 0,0

It's all new lines and with a comma for decimals

**Comment by Rem0o** [comment]
Yes, either through a file sensor, but you have to format the file to only have 1 value, or use/create a plugin.
