### ISSUE TITLE
Odd Fan Issue on EVGA FTW 3090 Ti 

### ISSUE THREAD

**Issue by SpaceballsTheGithubName** [Rem0o/FanControl.Releases#957]
FanControl correctly finds two fan sensors on the GPU, one controls the fan in the back near the I/O, the other controls the middle and front fans.  I have the fans set to a curve so that they are always spinning at least 45% (640~ RPM) regardless of GPU temperature.  Whats odd is that the front fan (and only the front fan), even though it is on the same header as the middle one, constantly ramps and slows down every second upon initial boot of my Windows 11 system, restart or shutdown. If I ramp the front and middle fans manually above 1000 RPM, and then bring them back down to 640, the ramp/slow stops completely and operates like normal. I dont see anything wrong with my GPU, the temps are fine and it functions perfectly. Could this be a zero RPM mode overwriting my FanControl profile?

**Comment by Rem0o** [comment]
Set a start% so that it spins to 1000 rpm before going back down.
