### ISSUE TITLE
Any chance of DIMM temperatures as temperature source?

### ISSUE THREAD

**Issue by johnneren** [Rem0o/FanControl.Releases#96]
I would love to be able to PWM control my RAM cooling fans so they ramp up automatically during test.
At idle my RAM temps are 28-30 degrees but when you stess them they can reach 55 degrees. (HWiNFO64)

If that is not possible / within the scope of FanControl feel free to close this issue :)

Thanks!

**Comment by Rem0o** [comment]
My temp source (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) doesn't have any RAM support.

**Comment by Cubox** [comment]
Hi @Rem0o, there is a pull request for LHM to enable DIMM temperature support (see https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/395 and https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/399)

However, I have replaced LHM's DLL in FanControl directory and the DIMMs are not showing, contrary to what you were saying in https://github.com/Rem0o/FanControl.Releases/issues/89#issuecomment-777726717 point 4.

Is there something on FanControl's side that need to be changed so those DIMMs show up?

**Comment by Rem0o** [comment]
@Cubox  yes, I need to activate "memory" on the backend.

**Comment by Cubox** [comment]
> 
> 
> @Cubox yes, I need to activate "memory" on the backend.

Alright, I'm up for getting a beta build to test it out and confirm if this works. Or next release if you go directly that way

**Comment by Rem0o** [comment]
> > @Cubox yes, I need to activate "memory" on the backend.
> 
> Alright, I'm up for getting a beta build to test it out and confirm if this works. Or next release if you go directly that way

Well I will wait for the PR to be merged into master before making any change.

**Comment by Rem0o** [comment]
@Cubox V72 has memory enabled

**Comment by Cubox** [comment]
> @Cubox V72 has memory enabled

Thanks! I will let you know if it works with the modified DLL

**Comment by Cubox** [comment]
This works great!
![image](https://user-images.githubusercontent.com/479129/112227776-78ec4100-8c30-11eb-9aa2-f90d893ab339.png)

As you can see, I made a max using all the DIMMs and am using this to control my DIMM fan.

Thanks for your work

**Comment by Lokh33d** [comment]
I am having the same issue.  While it shows the ability to select Dimms from the temp sources when loading FanControl, it doesn’t actually display the Ram temps in any of the drop-down menus for the fan curves.

**Comment by rzhlm** [comment]
> I am having the same issue. While it shows the ability to select Dimms from the temp sources when loading FanControl, it doesn’t actually display the Ram temps in any of the drop-down menus for the fan curves.

I have the same problem. It seems to be an issue in the upstream package LibreHardwareMonitor. E.g., see:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/941
or https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/993

**Comment by Jadatmag1** [comment]
Same problem as [Lokh33d](https://github.com/Lokh33d) and [rzhlm](https://github.com/rzhlm)

**Comment by PINPAL** [comment]
Any updates on this? Would love to have RAM temperatures.
