### ISSUE TITLE
No longer detecting GPU temperatures to make curves.

### ISSUE THREAD

**Issue by erob456** [Rem0o/FanControl.Releases#960]
I had to downgrade my AMD graphics drivers but now it won't detect the GPU temps or even show the sensors.  Updated to 120, tried refreshing everything, running setup again, etc, but nothing fixed it. I see other sensor temps (CPU, Mobo, storage) only GPU doesn't show. Any help would be great. 

AMD RX 5700 xt, Ryzen 7 3700x system

**Comment by toufuboi** [comment]
I am also having the same problems recently after downloading FanControl version 120

**Comment by KeatsPeeks** [comment]
Same here. 

V120 does not work.

V119 works. You can revert to it by downloading the zip file manually.

**Comment by Andrew-McCauley** [comment]
Same problem upon updating to 120.

**Comment by toufuboi** [comment]
I redownloaded version 119 and the GPU temps are still not appearing. I have a rx 6900xt so it may be an AMD problem?

**Comment by toufuboi** [comment]
I have a different PC with an nvidia GPU, and its on version 110 and it is working. With this in mind I tried to download 110 on my main PC and it does not work still, so either it is a AMD GPU problem, or a windows 11 problem, at least for me/

**Comment by erob456** [comment]
Ok, so I figured a fix out. Now that AMD is doing their "lightning" drivers that don't do a full install, just change the files they need to, I think that messes with things. So I downgraded to 22.4.1 and did a Factory Reset install and now my temp sensors are back. So if you have an AMD card, try that.

**Comment by goathens** [comment]
> Ok, so I figured a fix out. Now that AMD is doing their "lightning" drivers that don't do a full install, just change the files they need to, I think that messes with things. This was also messing with other apps like Davinci Resolve. So I downgraded to 22.4.1 and did a Factory Reset install and now my temp sensors are back. So if you have an AMD card, try that.

"factory reset" install fixed this for me, thanks from another 5700xt owner.  I upgraded to 22.7.1 only to discover it broke steam's overlays for me, so I reverted to 22.6.1.  I was considering trying DDU, which is probably similar to AMD's factory reset.

**Comment by Timothy21** [comment]
> > Ok, so I figured a fix out. Now that AMD is doing their "lightning" drivers that don't do a full install, just change the files they need to, I think that messes with things. This was also messing with other apps like Davinci Resolve. So I downgraded to 22.4.1 and did a Factory Reset install and now my temp sensors are back. So if you have an AMD card, try that.
> 
> "factory reset" install fixed this for me, thanks from another 5700xt owner. I upgraded to 22.7.1 only to discover it broke steam's overlays for me, so I reverted to 22.6.1. I was considering trying DDU, which is probably similar to AMD's factory reset.

For my case(6800XT), I used DDU to fully clean my old driver and update driver, but still cannot see GPU temp in FanControl. What does this Factory Reset actually mean?

**Comment by heheda2033** [comment]
> 我不得不降级我的 AMD 图形驱动程序，但现在它不会检测 GPU 温度，甚至不会显示传感器。更新到 120，尝试刷新所有内容，再次运行安装程序等，但没有任何修复。我看到其他传感器温度（CPU、主板、存储）只有 GPU 没有显示。任何帮助都会很棒。
> 
> AMD RX 5700 xt、Ryzen 7 3700x 系统



> I had to downgrade my AMD graphics drivers but now it won't detect the GPU temps or even show the sensors. Updated to 120, tried refreshing everything, running setup again, etc, but nothing fixed it. I see other sensor temps (CPU, Mobo, storage) only GPU doesn't show. Any help would be great.
> 
> AMD RX 5700 xt, Ryzen 7 3700x system

Please tell me，How to use Fancontrol control 5700XT GPU fan,I useing 5500XT ,Fancontrol unable to control GPU fan, GPU driver version 22.9.2.Any help would be great.

**Comment by heheda2033** [comment]
> I had to downgrade my AMD graphics drivers but now it won't detect the GPU temps or even show the sensors. Updated to 120, tried refreshing everything, running setup again, etc, but nothing fixed it. I see other sensor temps (CPU, Mobo, storage) only GPU doesn't show. Any help would be great.
> 
> AMD RX 5700 xt, Ryzen 7 3700x system

Any help would be great.

**Comment by heheda2033** [comment]
> I had to downgrade my AMD graphics drivers but now it won't detect the GPU temps or even show the sensors. Updated to 120, tried refreshing everything, running setup again, etc, but nothing fixed it. I see other sensor temps (CPU, Mobo, storage) only GPU doesn't show. Any help would be great.
> 
> AMD RX 5700 xt, Ryzen 7 3700x system

Please tell me , How to use Fancontrol control 5700XT GPU fan. I'm useing 5500XT ,but Fancontrol unable to control my GPU fan.my GPU driver version 22.9.2.Any help would be great.
