### ISSUE TITLE
Fan ramp to 100% on shutdown and start

### ISSUE THREAD

**Issue by SteelSkeleton** [Rem0o/FanControl.Releases#961]
Hi prior to the last two updates had no issues. Now when I restart, my fans ramp to 100% on shutdown and startup. In My bios I have a fan curve, which runs about 50%. When I move the bios curve, the fans ramp down and then seem to ramp right back up to 100%. Once FanControl loads, everything runs fine. 

Temps look fine in BIOS 30-40 area, if I launch HWINFO very early after windows when fans are running 100% I see temps into the high 70s and as fans slow, temps settles in the 30s.

Any ideas? 

Thank you!

**Comment by FynnApp** [comment]
Mine does the same. I set my start up delay so FC will take control of fans more quickly after startup. If fans don't have a setting in FC, or at start before FC has initated, they run at 100% by default since they are no longer controlled by bios curves. This is my experience so far.
