### ISSUE TITLE
Feature request: Show curve's current target point in curve's edit window

### ISSUE THREAD

**Issue by Impact123** [Rem0o/FanControl.Releases#964]
The curves in the main UI show a green bullet to indicate what the current target point is.
![image](https://user-images.githubusercontent.com/899193/180367632-25b7cba6-d40d-45b1-93b7-6dd44aa2af16.png)
Unfortunately it's not shown in the edit window.
![image](https://user-images.githubusercontent.com/899193/180368246-00570a72-bae9-4bc7-a77c-7b3186621197.png)

Here's an example from ASUS' Fan Xpert.
![image](https://user-images.githubusercontent.com/899193/180368508-8c663348-93dd-4692-8704-627796cbb71d.png)

Is there any chance to have this added to the edit graph too?

**Comment by fti7** [comment]
+1. Would be very handy when editing the curves

**Comment by Rem0o** [comment]
Will do a dashed dot to avoid confusion with the points of the graph itself:
![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/460f250a-62cd-4649-95a6-24c521cc3f5a)

**Comment by Impact123** [comment]
That's great to hear but it's kind of hard to see in your screenshot.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V192
