### ISSUE TITLE
Couple of questions before I download this

### ISSUE THREAD

**Issue by Maple38** [Rem0o/FanControl.Releases#966]
Hey there, hope you're having a good day, this program seems really cool but I have two questions.

1. Does it work with AIOs?
2. Is there like, a list of compatible hardware? I have fairly common hardware so it should probably be compatible, but like is there a list I can check? I checked the related section on the main page but it may just be because I'm tired but I didn't see a list.

**Comment by Rem0o** [comment]
1: Yes
2: Hardware compatibility is a moving target. Just try it out and see if your stuff is detected.
