### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by RMneanCA** [Rem0o/FanControl.Releases#969]
Both in ZIP and out of it, when I go and run the FanControl.exe the both give me the "Do you want to run this ..unknown publisher..."
I click "yes"  and nothing happens, ever time.  

Down loaded it again, I have attempted to run it at lease 15 times, nothing.

Any suggestions?

I just DL the software today 2022-07-23.  so it should be v120

**Comment by Rem0o** [comment]
OS? Specs?

**Comment by RMneanCA** [comment]
OS:
Win10

PC:
I7-8700k
Asus Prime z370-P
32G RAM  Trident
1070 ti

**Comment by RMneanCA** [comment]
1.21 still will not install

**Comment by Rem0o** [comment]
Any log.txt file created next to the exe?

**Comment by RMneanCA** [comment]
I have tried to installed v120 many times
and I have just tried v121 5-6 times

Both cases I tried DL the zip from different location here on your profile and from both within the ZIP and and with the .exe extracted from the zip
