### ISSUE TITLE
App profiles

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [Rem0o/FanControl.Releases#97]
App profiles would allow Fan Control to be set up such that a certain configuration is used when a certain program is running. This would be useful for automating the switching between gaming and non-gaming profiles (or anything really). Someone would just add all their games to their gaming profile and when the game runs, Fan Control automatically swaps to the gaming configuration. When the game closes, Fan Control automatically swaps back to another configuration of choice.

**Comment by Wolphin5** [comment]
There appears to be profiles which can be used to switch, just no automation of the switching (the automation takes much, much more resources, as it needs to monitor the programs which are running).

**Comment by asdsadsaasd12312132** [comment]
> There appears to be profiles which can be used to switch, just no automation of the switching (the automation takes much, much more resources, as it needs to monitor the programs which are running).

To avoid unnecessary resource usage, they can just make it only monitor programs when app profiles are enabled.

**Comment by Rem0o** [comment]
Loading config through a command-line argument/shortcut at runtime is coming. Possibility of automation/3rd party app loading a profile.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/wiki/Hotkeys---Automate-config-changes-(V136-and-up)

**Comment by jacobcxdev** [comment]
I would still love this feature! I already use iCue's auto-switching for all of my Corsair fans, but the remainder in FanControl don't currently have a built-in way to auto-switch.
