### ISSUE TITLE
Feature request: Multiple Tray Icon temperatures

### ISSUE THREAD

**Issue by aFanControlFan** [Rem0o/FanControl.Releases#974]
First of all, HUGE fan of your program! I made this account just to tell you this.
While I'm here though, can you make possible to have more than one temperature tray icon?
Maybe similar to how HWinfo does it?[
![אובסס2](https://user-images.githubusercontent.com/109928021/180671375-09e54a09-1e6f-4bd6-907a-e77db9209e4f.png)
](url)

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.Releases/issues/38

**Comment by aFanControlFan** [comment]
Whoops, sorry!
