### ISSUE TITLE
Tray icon stuck in dark mode (white icon)

### ISSUE THREAD

**Issue by deancommasteven** [Rem0o/FanControl.Releases#976]
I saw that there are several closed issues where this looks like this was solved, so I apologize that I seem to have found it again. 

I use light mode in Windows 11. I've set the tray icon to light, dark, and "Sync theme with Windows", but it stays white no matter what. I've quit the app, restarted the computer, and even deleted and reinstalled the app.

Please let me know if there's any more info you need.

![Screenshot 2022-07-25 153415](https://user-images.githubusercontent.com/25689810/180860237-29e8d18d-d3dd-4328-a7a4-ad5a55e832ab.png)

**Comment by Rem0o** [comment]
Set a temperature for the tray icon, then dark.

**Comment by deancommasteven** [comment]
Oh I see. Displaying temperature does indeed respect the dark/light setting. Is there no black standard toolbar icon for the app? I don't want to show the temperature in my toolbar.

**Comment by Rem0o** [comment]
There is now a black fan logo.
