### ISSUE TITLE
Fan Control does not find all fans.

### ISSUE THREAD

**Issue by fat-delinquent** [Rem0o/FanControl.Releases#977]
To start off : I'm an absolute beginner when it comes to this kind of software so if you have answers please keep it as simple as possible , thank you =) 

System : 
Mainboard - Gigabyte X470 Aorus Ultra Gaming
CPU - Ryzen 7 2700x
GPU - Gigabyte RTX 2060 OC 6gb
Case - Phanteks Enthoo Luxe
OS - Windows 10

Had to replace all my case fans and ghetto rig 2 120mm fans to my GPU. Found this software by watching jayztwocents and followed his video because this seems exactly what I need now that my GPU fans are controlled by the motherboard.
Fan Control sadly only finds two fans in my case. The CPU Cooler Fan and the rear exhaust case fan. The two GPU fans , top exhaust and the two front intake fans are "found" but not controlable. (Icons grayed out but showing rpm. Maybe I can add a screenshot?!)
![Unbenannt](https://user-images.githubusercontent.com/109990444/180868045-f0586073-e557-4c6e-9b1f-841fd965b0e1.jpg)
![Unbenannt1](https://user-images.githubusercontent.com/109990444/180868049-1f01f294-5814-416d-8f7d-d172bcf0293e.jpg)

At first I connected all the fans to the fan controller/hub build into the case. When I encountered my issue I hooked every fan up to an sys-fan slot on the Mainboard. That changed nothing sadly. Just in case this might be of importance : the two intake fans are connected to one sys-fan slot with an Y-cable/splitter/junction (don't know what it's called) and so are the two GPU fans so I can control them as one unit.
I can control every fan with the bios but that isn't really what I want since it's all dependant on the CPU temp.

I really need this to work...so thank you very much for taking your time to read this.

edit : I just got CPUID HWMonitor and it only shows two fans aswell...wtf is going on :(

**Comment by Dark360** [comment]
> To start off : I'm an absolute beginner when it comes to this kind of software so if you have answers please keep it as simple as possible , thank you =)
> 
> System : Mainboard - Gigabyte X470 Aorus Ultra Gaming CPU - Ryzen 7 2700x GPU - Gigabyte RTX 2060 OC 6gb Case - Phanteks Enthoo Luxe OS - Windows 10
> 
> Had to replace all my case fans and ghetto rig 2 120mm fans to my GPU. Found this software by watching jayztwocents and followed his video because this seems exactly what I need now that my GPU fans are controlled by the motherboard. Fan Control sadly only finds two fans in my case. The CPU Cooler Fan and the rear exhaust case fan. The two GPU fans , top exhaust and the two front intake fans are "found" but not controlable. (Icons grayed out but showing rpm. Maybe I can add a screenshot?!) ![Unbenannt](https://user-images.githubusercontent.com/109990444/180868045-f0586073-e557-4c6e-9b1f-841fd965b0e1.jpg) ![Unbenannt1](https://user-images.githubusercontent.com/109990444/180868049-1f01f294-5814-416d-8f7d-d172bcf0293e.jpg)
> 
> At first I connected all the fans to the fan controller/hub build into the case. When I encountered my issue I hooked every fan up to an sys-fan slot on the Mainboard. That changed nothing sadly. Just in case this might be of importance : the two intake fans are connected to one sys-fan slot with an Y-cable/splitter/junction (don't know what it's called) and so are the two GPU fans so I can control them as one unit. I can control every fan with the bios but that isn't really what I want since it's all dependant on the CPU temp.
> 
> I really need this to work...so thank you very much for taking your time to read this.
> 
> edit : I just got CPUID HWMonitor and it only shows two fans aswell...wtf is going on :(

I beleived that two fans connected to a PWM Splitter (Y-cable/splitter/junction) will only be detected as one fan as the Y Splitter only has one pin for detected RPM from one of the two fans connected.

[https://m.media-amazon.com/images/I/51iePheHJQL._AC_SL1000_.jpg](url)

**Comment by fat-delinquent** [comment]
Thank you for your contribution. That however I did know =)  Keeping that in mind the system should find 5 fans. 

I believe the problem is maybe hardware related ?! I changed the fans arround on the sys_fan slots and now I can atleast control the GPU fans still not finding all fans however ^^ 

Problem still remains - Bios finds all fans and control all of them , software does not.

**Comment by Rem0o** [comment]
Keep in mind any software will NOT recognize a "fan" per say that is connected, it recognizes fan headers. A motherboard doesn't "know" what a fan is. It just feeds power to its header and reads a "RPM" signal.

A control card in FanControl represent a header, not a specific fan. If you got 3 fans connected to a single header, you will still only have 1 control card for these 3. Also, having splitters onto a header will mess with RPM readings, and fan control won't be able to auto-detect your fans. They should still be controllable though, you just won't get any relevant RPM reading.

**Comment by triplese** [comment]
Gigabyte B550 aorus pro. 5 fans connected to MB - 3 is 3 pin and 2 is pwm 4 pin. Only 3 (3 pin) controllable from fan control (SYS_FAN1-3 on MB) but 2 (pwm) is being overriden by external control (SYS_FAN4 and SYS_FAN5 on MB), but RPM read correctly. In bios I can control all of them, but dont have temp sensor (nvidia memory). Tried set pwm fans to voltage control in bios, no luck. Any advices?

**Comment by Knutowskie** [comment]
I am using the gigabyte x470 board too. fancontrol can't find the fans connected to a onboard controller IT87...something. Fancontrol is using librehardwaremonitor stuff and they dont support it.

So my guess is: i am fucked. using a watercooler on GPU that is not controlled by GPU Temperatur. Gigabyte software only knows CPU Temp. Shit.
