### ISSUE TITLE
FanControl prevents non-primary hard drives from sleeping.

### ISSUE THREAD

**Issue by batthing** [Rem0o/FanControl.Releases#98]
As title really - if the software is running it prevents my secondary and tertiary mechanical hard drives from sleeping, even when they're not in use. If I don't use the PC then the whole PC will still sleep after 30 minutes, as expected, but the drives won't spin down independently. If I close the app then they will spin down after 20 minutes without use, as expected. I work mostly RDCed into another PC and so the non-primary drives almost never get accessed, so this is quite noticeable. If I force the drives to Idle, using a 3rd party program, then they spin up again after a few minutes. It seems FanControl is pinging the drives every few minutes for some reason.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/102903020-c395cb80-443d-11eb-8bf5-2c41b89bae92.png)
Do you have this option checked?

**Comment by batthing** [comment]
lol, i did not! thanks!
