### ISSUE TITLE
Uninstalled but still trying to start on start up of PC

### ISSUE THREAD

**Issue by EricJi150** [Rem0o/FanControl.Releases#982]
I installed new fans and a new cpu cooler so don't need fancontrol anymore as my temps are now under control. I deleted all the files, but for some reason now everytime I start my pc I get an error message saying fancontrol.exe doesn't exist and it opens up CMD. Does anyone know where I can remove it from still trying to start fancontrol? I search task manager and shell:startup.

**Comment by Rem0o** [comment]
Look for the Task Scheduler, task named "FanControl".
