### ISSUE TITLE
Old GPU still listed in the UI after upgrading to a new GPU

### ISSUE THREAD

**Issue by MasterZoen** [Rem0o/FanControl.Releases#983]
I upgraded my GPU, but the old GPU "Controls" and "Speeds" are still in the list after refreshing the sensors.

**Comment by Rem0o** [comment]
That's because the GPU falls under the same index driver side.  Just rename the cards if appropriate. They should control your new GPU.

**Comment by MasterZoen** [comment]
You misunderstand, it's listing controls and sensors for both GPUs, even though one of them is no longer physically present.

**Comment by Rem0o** [comment]
RTX 3080 will have 2 fan control cards.  The old name of the single 2080 card just carried over. Rename it and control both. Any hardware change is unexpected behavior and should require a reinstall / reconfig.

**Comment by MasterZoen** [comment]
Yes, the RTX 3080 does have 2 fan control cards, however, the one controlling a single fan is not being detected. Using MSI Afterburner to set all fans to 100% speed, the card for the RTX 2080 does not change from "0%" speed and simply shows "0 RPM".
