### ISSUE TITLE
error on pc startup

### ISSUE THREAD

**Issue by siampulse** [Rem0o/FanControl.Releases#984]
![unknown](https://user-images.githubusercontent.com/110235149/181750273-505fa893-7842-428d-96ca-23fb391130bf.png)

ever since i installed fan control this error comes up every time i load into my windows on my pc. i have tried to fix it by making fan control open on startup but it hasn't changed anything.

**Comment by Rem0o** [comment]
Look for the Task "FanControl" in Task scheduler.  Delete it.
