### ISSUE TITLE
Fancontrol uses a custom sensor under windows11, which will cause the speed problem that cannot reach the curves configuration

### ISSUE THREAD

**Issue by theside9** [Rem0o/FanControl.Releases#985]
I use gpu-z to output the GPU memory temperature to a file. After being processed by my own Python script, it is stored in F In the sensor file, then let fancontrol carry out temperature control. Every time I just turn on the control, it can work normally, but after a period of time, it will be in a low-speed state, as shown in the figure below. It should be at 100% speed, but it is now at 37.6%. It can be restored to normal only after closing and re enabling this control
![image](https://user-images.githubusercontent.com/33222224/181793654-32f7e4bc-177c-4153-9be6-319a81e560a8.png)

**Comment by Rem0o** [comment]
That's because something else outside of FanControl did set that fan at 37.6.

**Comment by theside9** [comment]
Thank you. Because I didn't install any temperature control software, I went into the BIOS and found that q-fan was turned on. It seemed that there was no problem after turning it off. Incidentally, I would like to make a little suggestion. Can we add GPU memory temperature monitoring to fancontrol? As far as I know, gpu-z can recognize the GPU memory temperature at present.

**Comment by Rem0o** [comment]
> Can we add GPU memory temperature monitoring to fancontrol? 

See README and https://github.com/LibreHardwareMonitor/LibreHardwareMonitor or https://github.com/falahati/NvAPIWrapper
