### ISSUE TITLE
The software ignores the minimum and maximum values for fan controls

### ISSUE THREAD

**Issue by snake-4** [Rem0o/FanControl.Releases#986]
My GPU reports the range of the fan controls as [30, 100] as in
ISensor.Control.MinSoftwareValue is 30 and ISensor.Control.MaxSoftwareValue is 100.
The FanControl program should rescale the values in this case but unfortunately it seems to have a hardcoded range of [0, 100].
What could be done instead is something like this
```
UIToHW = (UIValue / 100) * (HWMax - HWMin) + HWMin
HWToUI = (HWValue - HWMin) / (HWMax - HWMin) * 100
```

**Comment by Rem0o** [comment]
I'm not sure to understand the benefit here. Your fan (here an Nvidia card I believe) being limited to 30% means it can't be manually be set to below 30%, but it's full technical range is still 0-100, it's just software/driver limited. 
I don't think hiding that state detail/state benefits the user in any way.

**Comment by SnakePin** [comment]
I've a Zotac RTX3070. It should make sense as the user seeing that the fans are not spinning even though it's set to %30 is not an expected behavior. Besides, it's not exactly limited at %30, the range really does appear to be [30,100] as the fans don't spin at %30 and they spin at about 200RPM at %34. The driver could've also reported a range that has a maximum value above 100 so assuming the range for the control is not a future-proof approach.

**Comment by Rem0o** [comment]
Ah! What you describe then is the start %. It is already being handled with the start% field in the control card.  The % shown is the roughly percentage of power ( here 12V with PWM) being applied to the fan. RPM/Power is NOT a linear relation, that's expected. Your fan needs 30% to cross the physical threshold required to start spinning.  Set a value a bit above that, like the 34 you described in that field.   The effect is that any fan curve % below that threshold will "snap" to 0 for that control, so you don't feed power to the fan without them spinning, which will cause heat and can damage the fan long term.

**Comment by SnakePin** [comment]
![image](https://user-images.githubusercontent.com/18491360/182005175-3325cdba-9b7d-4661-b724-c65002cb2091.png)
I hope this clears the confusion.
The GPUs range really is [30, 100]. The duty cycle at 30 is the same as every level below 30.
Leftmost graph is the control level reported by the NVIDIA driver and the X axis on all graphs is the level that the software sets the fans to.

**Comment by SnakePin** [comment]
@Rem0o Can you review this?
If you implement this change, the users wouldn't have to set the "Minimum" and "Offset" fields themselves.
The range of the control would be proportionally scaled to range reported by driver ([30, 100] in this case).
You could then change the Hardware Curve override setting to disable software control at %0 in the new range.
