### ISSUE TITLE
FanControl v120 Missing Speed Sensor

### ISSUE THREAD

**Issue by Blackwolf2022** [Rem0o/FanControl.Releases#987]
I have an MSI Z490-A PRO motherboard and I have never had problems with previous versions of FanControl, today I turned off the computer and when I turned it on, it tells me "MISSING SPEED SENSOR" I had about 5 seconds boot time, so I downloaded again fancontrol and I didn't do the pairing sensor, I increased the boot time to 10 seconds (I have an m2 ssd and I think that's enough time) and for now it doesn't tell me error, hopefully well, I just wanted to share my experience.
<img width="374" alt="Missing Speed sensor" src="https://user-images.githubusercontent.com/105545576/181937372-a79b5d43-4019-48a5-8a7d-f88ba30c78aa.png">

**Comment by n-r-w** [comment]
Same issue after last windows 11 update (21H2 build 22000.795). I don't know if this is related to the windows update or fancontrol

**Comment by n-r-w** [comment]
After another reboot, the sensors appeared, but all their settings were reset. After the reconfiguration, everything works, but the reason for the failure is not clear. The error log is empty.

**Comment by Blackwolf2022** [comment]
> After another reboot, the sensors appeared, but all their settings were reset. After the reconfiguration, everything works, but the reason for the failure is not clear. The error log is empty.

My windows 11 version is 22000.832 and even I don't understand why, however I did as I already wrote, I downloaded again fancontrol v120 (121 aspect) without running the paired speed sensor and for now the problem is not there, so you just have to wait and see.

**Comment by Octaviorios** [comment]
Same thing happening to me, and it doesnt matter how much delay i set in it.
