### ISSUE TITLE
1.21 ver. ? 

### ISSUE THREAD

**Issue by EvilRunner** [Rem0o/FanControl.Releases#989]
The app told me new version 1.21 avaible, but clicking update close app e nothing more happens. In repo I can find 1.20 is the last..so i'm a bit confused.
Thanks

**Comment by Impact123** [comment]
![image](https://user-images.githubusercontent.com/899193/182047987-790a7c81-ebe1-41ab-8b5f-b8a4b67b3ef1.png)
I presume the github release was forgotten but [the binary's available here](https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip).

**Comment by EvilRunner** [comment]
thnks !
