### ISSUE TITLE
Fan controls do not work with any Curves

### ISSUE THREAD

**Issue by Scaryterry1** [Rem0o/FanControl.Releases#990]
Hi there,

For some reason my Fan controls just stopped working when connected with any curves i've created. 

Both Chassis 3 and H_AMP fans just do not work until i turn the curve slider off and its stuck at 60%.

Only the W_PUMP works with the curves and manual control.

![image](https://user-images.githubusercontent.com/110368185/182069807-2169a80e-32e4-44b9-b2b7-b8dad1e75b2f.png)

**Comment by Scaryterry1** [comment]
Found the issue - seems to be caused by ASUS armory crate. Fiddled with the fan settings and now FanControl works as per normal.

**Comment by Wheels35** [comment]
> Found the issue - seems to be caused by ASUS armory crate. Fiddled with the fan settings and now FanControl works as per normal.

Do you have any reference to what you 'fiddled with' my armoury crate had an update and broke my previously working FanControl and I'd love to go back to using FanControl

**Comment by Scaryterry1** [comment]
Under Dashboard in Armoury Crate -> Fan Speed. i just toggled between full speed/turbo/standard/silent profiles, load your configuration within FanControl and it just worked again.
