### ISSUE TITLE
Detects fans but they don't show up in "Controls" selection

### ISSUE THREAD

**Issue by Tofally** [Rem0o/FanControl.Releases#992]
I can control my fans perfectly fine with SpeedFan, but I would like to move to Fan Control. I can control my GPU fans but not case fans. 
I know that I can control these fans bc software called SpeedFan works. with this. 
The software detects my fans (in the "Speeds" tab), but I cannot control those.
Can sb help?
![Screenshot_295](https://user-images.githubusercontent.com/110530660/182571260-d856f3d7-7813-4ca5-9d39-810f4055dadb.png)

**Comment by Rem0o** [comment]
Your board support is limited, that's it. See README.

**Comment by Tofally** [comment]
> Your board support is limited, that's it. See README.

What section of README? Can you reference at the specific part?

**Comment by Tofally** [comment]
I have fans set to 50% from MB bios.

**Comment by Rem0o** [comment]
@Tofally https://github.com/Rem0o/FanControl.Releases#issues-and-hardware-compatibility
