### ISSUE TITLE
Doesn't start when switching windows account

### ISSUE THREAD

**Issue by wziel** [Rem0o/FanControl.Releases#993]
I created a secondary windows account on my PC, when Windows starts I log into the first account, FanControl starts, when I switch to the second account FanControl doesn't start. I open it manually on second account, save the config, restart the PC, it starts on the second account and not on the first one. It looks like it remembers the account it was last opened on and only starts on that account. One more thing, when I open it manually on the account it didn't start on startup, it gives me the tutorial every time, which suggests that it somehow resets every time it is opened on a different account.

**Comment by Rem0o** [comment]
FanControl right now is user-based. See https://github.com/Rem0o/FanControl.Releases/issues/135.
