### ISSUE TITLE
need help with fully uninstalling Fan Control

### ISSUE THREAD

**Issue by RapidJamer** [Rem0o/FanControl.Releases#995]
I need help being able to delete fan control but i cant do it because the supposed name thats supposed to pop in task scheduler isnt showing
![Screenshot 2022-08-03 204147](https://user-images.githubusercontent.com/110575892/182738878-e7ed6fe5-cce0-42aa-9a03-999d3267bfc2.png)

**Comment by Rem0o** [comment]
If you never activated Start With Windows, there won't be any task.
