### ISSUE TITLE
GPU has 3 fans and two controllers, 2 fans are controlled by 1 fan controller, 1 fan is controlled by the other; Fan Control is only detecting and controlling the two fans

### ISSUE THREAD

**Issue by MasterZoen** [Rem0o/FanControl.Releases#997]
MSI Afterburner is detecting two fan tachometers for the ZOTAC GAMING GeForce RTX 3080 Trinity OC LHR ZT-A30800J-10PLHR video card. The first fan tachometer registers a single fan that is farthest from the monitor connection ports. Fan tachometer 2 is registering the other two fans that are closest to the monitor connection ports. Fan Control is only detecting and controlling the 2 fans that are close to the monitor connection ports.

**Comment by SpaceballsTheGithubName** [comment]
i have a similar issue. I have an EVGA 3090 Ti, two of the fans are on one fan header so one fan header controls two fans. Are you sure thats not the issue?

**Comment by Rem0o** [comment]
The 2 control channels detected by FanControl should be a 2+1.   Use manual mode and confirm which channel controls which fans. 1 of the channel should control fans.

**Comment by MasterZoen** [comment]
The single fan was being detected as the old GPU. You can close this.
