### ISSUE TITLE
All fans don't respond to their curves anymore

### ISSUE THREAD

**Issue by Bluefluffy** [Rem0o/FanControl.Releases#999]
the software worked fine and has been untouched after my initial setup, however just today all of the fans are at 0% as I suddenly saw my CPU was at 90 degrees. I checked the software, they were all supposed to be at max but all of them stated 0rpm either way and all fans were physically not spinning.

**Comment by Bluefluffy** [comment]
% shows as for example fan being at 70% but the rpm states 0, shutting down fan control makes my fans works again because of the bios settings (which also have never been touched)

**Comment by T0bl** [comment]
i have the same problem, i noticed this behavior after an asus software update (Armoury Crate)

**Comment by Bluefluffy** [comment]
> i have the same problem, i noticed this behavior after an asus software update (Armoury Crate) Windows 10 Pro 21H2 Fan Control v121

It fixed by going in armoury crate, and using the fan speed options there, i noticed any setting was different from the default with fan control not running. When i turned fan control back on it seemed to take control again

**Comment by T0bl** [comment]
I fixed it for myself yesterday in the same way :D
